### ISSUE TITLE
Question - Service Fabric Reverse Proxy Health

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1000]
Team,

In SF Explorer, which system service is healthy means reverse proxy is healthy ?
i dont see Reverse Proxy as System Service.

is there way to see number of request received by RP and resolved it and how much time it took to resolve ?

fabric:/System/ClusterManagerService
fabric:/System/FailoverManagerService
fabric:/System/FaultAnalysisService
fabric:/System/ImageStoreService
fabric:/System/NamingService
fabric:/System/UpgradeOrchestrationService

Thanks,
naresh Khatri

**Comment by kavyako** [comment]
Reverse proxy does not show up under the system services in SFX. It runs as process FabricApplicationGateway.exe on the nodes.

Have you looked at [reverse proxy diagnostics](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics)?  You can configure events from these channels to be uploaded to storage and query the events there.

For success case, there should be one event per request processed at the reverse proxy, of type ReverseProxy.RequestReceived. 
This is usually of the form:
0a1fbfa6-40dd-4ddc-b66b-61671947125a Request url = http://10.0.10.10:19081/AppName/ServiceName/pathsegments, verb = GET, remote (client) address = 10.0.10.10, resolved service url = http://10.0.10.20:8874/pathsegments, request processing start time = 2018-4-2 16:19:05.867

For failure cases, you will see more events with the same activity ID (The GUID at the beginning of the above sample event). 

Kavya

**Comment by nareshkhatri81** [comment]
Does reverse proxy errors gets logged in eventviewer ?

**Comment by kavyako** [comment]
yes, they should show up in the Admin channel under Microsoft-Service Fabric, usually next to the Operational channel. Task Category = ReverseProxy.

**Comment by kavyako** [comment]
By default only "Data and Messaging Channel - Base:" events would go there => failure logs from the reverse proxy will show up in the event viewer. 
@dkkapur How can one configure "Data & Messaging Channel - Detailed" logs to show up in the eventviewer, for standalone clusters? This channel will include a log entry for every request processed by the reverse proxy, however we recommend you enable this only for troubleshooting purposes, it is very verbose.

**Comment by nareshkhatri81** [comment]
i am looking for failure log of Service fabric in Event Viewer.

**Comment by kavyako** [comment]
ah so looks like they do not show up in Event Viewer. 

You could configure event flow to output the Data & Messaging events using the ETW provider & keyword values listed [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad#log-collection-configurations) to any of the preferred outputs.
