### ISSUE TITLE
Service Fabric application not working in a 5 node cluster

### ISSUE THREAD

**Issue by paulsaxton** [Azure/service-fabric-issues#1001]
Hello

I have a service fabic application with 5 nodes (VMS)

I am getting the error shown below 

Unhealthy event: SourceId='RunAsync', Property='RunAsyncUnhandledException', HealthState='Warning', ConsiderWarningAsError=false.
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {CE92C3B9-9A93-40E1-85AB-6A49170AEF7F} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

The application uses a dll which I have registered in all of the VMs.  

This dll accessing an api to obtain market data.  There can only be 1 instance of this running logged in at any one time

When I run my application in a single node it all works fine

The application works completely when in a single node, but I don’t even get my log files created in the 5 node cluster

Any ideas what could be causing this?

The important aspect here is that everything works fine when in a single node cluster

Paul

**Comment by xunlu** [comment]
Is the DLL part of your application package?

**Comment by masnider** [comment]
@paulsaxton Hi Paul. We haven't heard back from you on this and without more information we're not going to be able to provide much more help. Making sure the dll is present and registered seems like the next right step. For now I'm going to close down this issue. If you're still having this problem and need help, just reopen it and let us know where you are. If you have other questions or issues, please feel free to open another issue. Thanks!
