### ISSUE TITLE
Service Fabric App not working

### ISSUE THREAD

**Issue by cpatte7372** [Azure/service-fabric-issues#1002]
Hello community,

I have created a service fabric app following the guide here:
https://github.com/jjcollinge/traefik-on-service-fabric/blob/master/Docs/Deployments/VisualStudio.MD

The service fabric app continually fails with the error:

Partition is below target replica or instance count.
<img width="904" alt="traefik3" src="https://user-images.githubusercontent.com/24607961/39127017-b989c67e-46fb-11e8-94c2-a053351f786e.png">

I think is a problem that a number of people have identified, but I have no idea how to fix it.

Any help will be greatly appreciated

Thanks

Carlton

**Comment by cpatte7372** [comment]
Hi Community,

Just saw you know I'm running Windows 10 64bit

**Comment by justinSelf** [comment]
Does the details of the partition node provide anymore context (the node just under the highlighted node in the screen shot)?

**Comment by negberts** [comment]
Did you upgrade nuget packages to version 6.2 and are you deploying to Azure? 6.2 is not available on Azure yet....

**Comment by cpatte7372** [comment]
Hi Justin,

Thanks for getting in touch. I have rebuilt the Service Fabric Cluster again, just to make sure, and I'm getting the same error see image

![traefik4](https://user-images.githubusercontent.com/24607961/39153489-30c6ee3c-4743-11e8-9fc4-e79f15770847.png)

**Comment by cpatte7372** [comment]
@negberts thanks to you too for getting in touch. I'm deploying to my Local Cluster, not Azure

**Comment by justinSelf** [comment]
What about the individual replicas? What's the messaging for those? Also, check out the event viewer. You'll see a folder called SF or Service Fabric or something like that. You may find errors/warnings in there that help point to the problem.

**Comment by cpatte7372** [comment]
@justinSelf thanks for getting in touch. I will check out the replicas and the event viewer.

Cheers

**Comment by lawrencegripper** [comment]
@cpatte7372 Are you running with a 5 node local cluster? If so this might explain the issue, traefik runs as a guest exe and tried to listen on ports `80` and `8080`by default. In a local cluster all nodes are actually running on the same machine so traefik is unable to bind to the ports. 

If you are running on a local cluster either set the instance count to `1` fro `-1`

**Comment by cpatte7372** [comment]
@lawrencegripper thanks for reaching out. I am running on Local Cluster.

I get the same problem when running on 5 node cluster or 1 node cluster.
Can you let me know what you mean by:

> If you are running on a local cluster either set the instance count to 1 fro -1

**Comment by cpatte7372** [comment]
@lawrencegripper the toml config is as follows:

```
################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
debug = true

# Traefik logs file
# If not defined, logs to stdout
#
# Optional
#
# traefikLogsFile = "log/traefik.log"

# Log level
#
# Optional
# Default: "ERROR"

logLevel = "INFO"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.traefik]
address = ":8080"

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API definition
################################################################

[api]
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard = true

  # Enable debug mode.
  # This will install HTTP handlers to expose Go expvars under /debug/vars and
  # pprof profiling data under /debug/pprof.
  # Additionally, the log level will be set to DEBUG.
  #
  # Optional
  # Default: false
  #
  debug = true

################################################################
# Service Fabric provider
################################################################

# Enable Service Fabric configuration backend
[servicefabric]

# Service Fabric Management Endpoint
clustermanagementurl = "http://localhost:19080"
# Note: use "https://localhost:19080" if you're using a secure cluster

# Service Fabric Management Endpoint API Version
apiversion = "3.0"

# Enable TLS connection.
#
# Optional
#
#[serviceFabric.tls]
#  cert = "certs/servicefabric.crt"
#  key = "certs/servicefabric.key"
#  insecureskipverify = true

```

**Comment by cpatte7372** [comment]
Hi guys,

The following is the error on single instance

<img width="745" alt="traefik4" src="https://user-images.githubusercontent.com/24607961/39306505-462e07f8-4958-11e8-942b-5eec882ca748.png">

**Comment by lawrencegripper** [comment]
So can you update the instance count to 1 [here from -1]( https://github.com/jjcollinge/traefik-on-service-fabric/blob/master/Traefik/ApplicationPackageRoot/ApplicationManifest.xml#L4)

If that doesn't work the next step is to run Traefik outside the cluster and review the logs. To do this you need to run the `traefik.exe` with the `toml` config file. For example `cd` into the `code` directory of the solution [here](https://github.com/jjcollinge/traefik-on-service-fabric/tree/master/Traefik/ApplicationPackageRoot/TraefikPkg/Code) then run `traefik.exe --configfile=./traefik.toml` and review the output.

I would *guess* what you may see is a warning about port 80 already being in use. If that's the case then Traeifk is failing as it can't bind to port 80 as it's likely used already by something else like IIS. 

Update your toml to a different port here:
```toml
[entryPoints.http]
address = ":80"
```

**Comment by lawrencegripper** [comment]
Can you follow the suggestions in my last comment and share the output? I'd still suspect port issue. Do you have something listening on port 80 already?

**Comment by cpatte7372** [comment]
@lawrencegripper .. Its all good. I reset the SF and pushed Traefik back up to the cluster and all is looking good. Thanks
![traefik7](https://user-images.githubusercontent.com/24607961/39371928-f87fa2e4-4a3a-11e8-9b61-1f3ab8082600.png)
![traefik6](https://user-images.githubusercontent.com/24607961/39371929-f899d664-4a3a-11e8-8e3d-2c8bed42abb3.png)

**Comment by masnider** [comment]
Great! @cpatte7372 glad you're up and running and thanks a ton @lawrencegripper for the help!
