### ISSUE TITLE
FabricTransportServiceRemotingClientFactory TraceId — how to access it on the service side?

### ISSUE THREAD

**Issue by sathiathirumal** [Azure/service-fabric-issues#1006]
I have a service fabric project - there is an APIGateway (Facade) that hosts the public webapi layer. It talks to a few different microservices (not exposed publicly) via Fabric Remoting v2.

Now, I want to pass a TraceId (basically HttpContext.TraceIdentifier) from the APIGateway service to the Microservice(s) for tracing/logging purposes. I see that the FabricTransportServiceRemotingClientFactory object (which is the client side svc proxy) takes a TraceId, which is great. However, how do I access this traceId on the listener side so that the logger can emit that traceid so I can eventually search for all logs across multiple services for that same Http request using the same traceId?

public MyController()
    {
        // explicitly create V2 remoting client (as listener is V2)
        var proxyFactory = new ServiceProxyFactory((c) =>
        {
            return new FabricTransportServiceRemotingClientFactory(
                traceId: traceIdentifier // <--- from HttpContext, for logging
                );
        });
      _svcProxy = proxyFactory.CreateServiceProxy<IMyService>(
            ServiceUri, 
            listenerName: MyMicroservice.Models.Constants.ListenerName);
    }

Question is how to retrieve the traceId on the Microservice side (listener side) so I can use it there?

**Comment by Expecho** [comment]
The `ServiceContext` has a property `TraceId`  you can use. See [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.servicecontext.traceid?view=azure-dotnet)

Example:

    public sealed class Stateless1 : StatelessService, IStateless1
    {
        public Stateless1(StatelessServiceContext context)
            : base(context)
        { }

        public string SayHello()
        {
            return $"Hello World (traceid: {Context.TraceId}";
        }

        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new[]
            {
                new ServiceInstanceListener((c) => new FabricTransportServiceRemotingListener(c, this))
            };
        }
    }

**Comment by sathiathirumal** [comment]
I added a comment to my SO thread as well. Unfortunately, this is not what I want - or there is a bug in SF. The behavior I am seeing with ServiceContext.TraceId is that it holds a "static" value that was seeded in its constructor at the time of service instantiation (something like "{83bfe8c8-5869-4155-8e5a-d12fc451fcbe}:131690554413858492"). This value never changes for the lifetime of that process, and does not hold the value I set on the client side via the FabricTransportServiceRemotingClientFactory(traceid: traceIdentifier) call.

**Comment by suchiagicha** [comment]
@sathiathirumal 

If you are using app insights, they have a package doing the same for you for SF services.
https://github.com/Microsoft/ApplicationInsights-ServiceFabric

If not, then you need to add traceId in header on client side  and need to retrieve the traceId From header on service side.Here is a sample : 
https://github.com/amanbha/servicefabric/tree/master/samples/ServiceCustomMessageHandler

@amanbha  is the owner for the sample. 

TraceId on client factory is not getting passed to service. Its used only for local tracing

**Comment by sathiathirumal** [comment]
perfect, thanks @suchiagicha - will take a look. (no, not using app insights)

**Comment by suchiagicha** [comment]
Closing this issue.  If you have further question , you can reopen it.
