### ISSUE TITLE
Installing on Win10 Linux Docker (Ubuntu) or Win10 Bash error - "Failed to connect to bus: No such file or directory"

### ISSUE THREAD

**Issue by MarkoKacprzak** [Azure/service-fabric-issues#101]
Setting environment for FabricDeployer to run
Deleting all old content in FabricDataRoot
Running FabricDeployer on /opt/microsoft/sdk/servicefabric/common/clustersetup/nonsecure/servicefabric-scalemin.xml
sh: 1: iptables: not found
Setting sfuser as owner for FabricDataRoot
Setting sfuser as owner of FabricBinRoot
Enable service fabric service
Created symlink /etc/systemd/system/multi-user.target.wants/servicefabric.service, pointing to /etc/systemd/system/servicefabric.service.
Starting service
Failed to connect to bus: No such file or directory
Error: Starting service failed. Check output for details

**Comment by GetchaDEAGLE** [comment]
@MarkoKacprzak, I believe this has to do with **systemd** and its relation with Docker as it pertains to being used inside containers ([this describes the issue more](http://stackoverflow.com/questions/28495341/start-a-service-in-docker-container-failed-with-error-failed-to-get-d-bus-conne)). I suggest taking a look at [this](https://github.com/solita/docker-systemd) Docker image (based on Ubuntu 16.04) as a starting point as it supports systemd and should allow you to get everything working. Just be mindful of the caveats listed in the documentation.

**Comment by mani-ramaswamy** [comment]
You cannot run the SF Linux runtime inside Windows 10 Bash. You need an Ubuntu VM - does that work?

**Comment by mani-ramaswamy** [comment]
I am closing the issue since the cluster isn't supported in Windows 10 bash and we've not heard back from you. Please re-open the issue as appropriate.
