### ISSUE TITLE
NuGet 'ref' folder overriding framwork resolution for Remoting assembly

### ISSUE THREAD

**Issue by keithbo** [Azure/service-fabric-issues#1010]
As best as I have been able to find (I have been digging on this for days on and off) since Service Fabric added Net Standard 2.0 support there has been no real way to build against any types in the V1 remoting stack.

There was an explicit decision to remove the V1 assemblies from Net Standard 2.0, which is fine and I have no issue with, and with that came multi-targeted assemblies against netstandard2.0 and net45.

When the assemblies build, ie don't reference any remoting stack, then the different frameworks output the correct version of assembly and net45 does in fact contain the V1 namespaces still. However it appears that a 'ref' folder has been built in to the nuget package that *only* contains the netstandard2.0 assembly.

Now, this wouldn't be an issue for my project if #590 was fixed, but it is not so our project cannot move to remoting V2. And we have allot of test code around actors which requires mocking of the V1 remoting interfaces.

This has been raised multiple times #815 #930 but never really addresses the fact that it would be a non-issue if 'ref' was not used to explicitly override which assembly msbuild uses, see link:
https://developercommunity.visualstudio.com/content/problem/231208/wap-project-references-wrong-nuget-package-dlls-re.html

**Comment by ashishnegi** [comment]
@keithbo Are you targeting specific framework like net46 from net core project ? 
We are aware of the problem. We have the fix ready. Apologies for not able to ship it till now.

As a mitigation, can you build using .Net Framework for *now* ? If your code is already .net standard compliant, you should not have any problem with moving to net core after you move to sdk which has the fix.

**Comment by keithbo** [comment]
@ashishnegi Our codebase is still building with net461. We haven't moved on from 2.8.219 yet because of this. And we probably won't move to netstandard2.0 until the interface surrogate issue in #590 is resolved.

**Comment by ashishnegi** [comment]
we are tracking this via #930 . Closing this as duplicate.
