### ISSUE TITLE
Stand-alone cluster installation

### ISSUE THREAD

**Issue by JunRamoneda** [Azure/service-fabric-issues#1015]
I am having issues trying to create a stand-alone cluster with Service Fabric 6.2.262.9494: Here is the error log:

4/26/2018 11:32:17 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-5GP0PU0 - Error - Config for Hosting.FirewallPolicyEnabled changed but this entry can not be dynamically updated
4/26/2018 11:32:17 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-5GP0PU0 - Error - Configuration can not be updated dynamically for Hosting/FirewallPolicyEnabled
4/26/2018 11:32:17 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-5GP0PU0 - Error - Exiting the process as configuration can not be updated dynamically.
4/26/2018 11:32:17 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:42 AM - EC2AMAZ-5GP0PU0 - Error - Failed to get the Certificate's private key. Thumbprint:AzureServiceFabric-AnonymousClient. Error: FABRIC_E_CERTIFICATE_NOT_FOUND
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:28:05 AM - EC2AMAZ-5GP0PU0 - Error - Exception occured while creating an object of type FabricDCA.FileShareEtwCsvUploader (assembly FileShareUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer FileShareWinFabEtw. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Unable to create destination directory \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabriclogs-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm2. ---> System.IO.FileNotFoundException: The network path was not found. (Exception from HRESULT: 0x80070035)
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.NativeCommon.FabricDirectoryCreate(IntPtr path)
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Common.FabricDirectory.CreateHelper(String path)
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
4/26/2018 11:32:18 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.RunInMTA(Action action)
4/26/2018 11:32:19 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Common.FabricDirectory.CreateDirectory(String path)
4/26/2018 11:32:19 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader.<>c.<.ctor>b__6_2(Object ctx)
4/26/2018 11:32:19 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader.PerformDestinationOperation(DestinationOperation operation, Object context)
4/26/2018 11:32:19 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
4/26/2018 11:32:19 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Dca.Utility.PerformIOWithRetries(Action worker)
4/26/2018 11:32:20 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader..ctor(ExtensionsEvents traceSource, String logSourceId, Boolean runningOnBehalfOfApplication, String folderName, String destinationPath, AccessInformation accessInfo, String workFolder, TimeSpan uploadInterval, TimeSpan fileSyncInterval, TimeSpan fileDeletionAge, Boolean destinationIsLocalAppFolder, String fabricNodeId)
4/26/2018 11:32:20 AM - EC2AMAZ-MFFNCSB - Error -    --- End of inner exception stack trace ---
4/26/2018 11:32:20 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader..ctor(ExtensionsEvents traceSource, String logSourceId, Boolean runningOnBehalfOfApplication, String folderName, String destinationPath, AccessInformation accessInfo, String workFolder, TimeSpan uploadInterval, TimeSpan fileSyncInterval, TimeSpan fileDeletionAge, Boolean destinationIsLocalAppFolder, String fabricNodeId)
4/26/2018 11:32:20 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters param, ExtensionsEvents traceSource)
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareEtwCsvUploader..ctor(ConsumerInitializationParameters initParam)
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    --- End of inner exception stack trace ---
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
4/26/2018 11:32:21 AM - EC2AMAZ-MFFNCSB - Error -    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
4/26/2018 11:32:22 AM - EC2AMAZ-MFFNCSB - Error -    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
4/26/2018 11:32:22 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.ConsumerFactory.CreateConsumer(String consumerInstance, ConsumerInitializationParameters initParam, String moduleName, String typeName).
4/26/2018 11:32:22 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:29:21 AM - EC2AMAZ-5GP0PU0 - Error - Failed to configure upload to file share.  Destination: \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabricdumps-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm2, Local folder path: C:\SF\Log\CrashDumps.
4/26/2018 11:32:22 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:30:36 AM - EC2AMAZ-5GP0PU0 - Error - Failed to configure upload to file share.  Destination: \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabricperf-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm2, Local folder path: C:\SF\Log\PerformanceCounters_WinFabPerfCtrFolder.
4/26/2018 11:32:24 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-Q1D24U1 - Error - Config for Hosting.FirewallPolicyEnabled changed but this entry can not be dynamically updated
4/26/2018 11:32:24 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-Q1D24U1 - Error - Configuration can not be updated dynamically for Hosting/FirewallPolicyEnabled
4/26/2018 11:32:25 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:28 AM - EC2AMAZ-Q1D24U1 - Error - Exiting the process as configuration can not be updated dynamically.
4/26/2018 11:32:26 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:26:44 AM - EC2AMAZ-Q1D24U1 - Error - Failed to get the Certificate's private key. Thumbprint:AzureServiceFabric-AnonymousClient. Error: FABRIC_E_CERTIFICATE_NOT_FOUND
4/26/2018 11:32:26 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:28:06 AM - EC2AMAZ-Q1D24U1 - Error - Exception occured while creating an object of type FabricDCA.FileShareEtwCsvUploader (assembly FileShareUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer FileShareWinFabEtw. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Unable to create destination directory \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabriclogs-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm1. ---> System.IO.FileNotFoundException: The network path was not found. (Exception from HRESULT: 0x80070035)
4/26/2018 11:32:27 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.NativeCommon.FabricDirectoryCreate(IntPtr path)
4/26/2018 11:32:28 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Common.FabricDirectory.CreateHelper(String path)
4/26/2018 11:32:29 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
4/26/2018 11:32:29 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
4/26/2018 11:32:30 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Interop.Utility.RunInMTA(Action action)
4/26/2018 11:32:30 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Common.FabricDirectory.CreateDirectory(String path)
4/26/2018 11:32:31 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader.<>c.<.ctor>b__6_2(Object ctx)
4/26/2018 11:32:31 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader.PerformDestinationOperation(DestinationOperation operation, Object context)
4/26/2018 11:32:31 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
4/26/2018 11:32:32 AM - EC2AMAZ-MFFNCSB - Error -    at System.Fabric.Dca.Utility.PerformIOWithRetries(Action worker)
4/26/2018 11:32:32 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader..ctor(ExtensionsEvents traceSource, String logSourceId, Boolean runningOnBehalfOfApplication, String folderName, String destinationPath, AccessInformation accessInfo, String workFolder, TimeSpan uploadInterval, TimeSpan fileSyncInterval, TimeSpan fileDeletionAge, Boolean destinationIsLocalAppFolder, String fabricNodeId)
4/26/2018 11:32:33 AM - EC2AMAZ-MFFNCSB - Error -    --- End of inner exception stack trace ---
4/26/2018 11:32:33 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareUploader..ctor(ExtensionsEvents traceSource, String logSourceId, Boolean runningOnBehalfOfApplication, String folderName, String destinationPath, AccessInformation accessInfo, String workFolder, TimeSpan uploadInterval, TimeSpan fileSyncInterval, TimeSpan fileDeletionAge, Boolean destinationIsLocalAppFolder, String fabricNodeId)
4/26/2018 11:32:35 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters param, ExtensionsEvents traceSource)
4/26/2018 11:32:35 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.FileShareEtwCsvUploader..ctor(ConsumerInitializationParameters initParam)
4/26/2018 11:32:35 AM - EC2AMAZ-MFFNCSB - Error -    --- End of inner exception stack trace ---
4/26/2018 11:32:35 AM - EC2AMAZ-MFFNCSB - Error -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error -    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error -    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error -    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error -    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error -    at FabricDCA.ConsumerFactory.CreateConsumer(String consumerInstance, ConsumerInitializationParameters initParam, String moduleName, String typeName).
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:29:23 AM - EC2AMAZ-Q1D24U1 - Error - Failed to configure upload to file share.  Destination: \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabricdumps-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm1, Local folder path: C:\SF\Log\CrashDumps.
4/26/2018 11:32:36 AM - EC2AMAZ-MFFNCSB - Error - 4/26/2018 11:30:38 AM - EC2AMAZ-Q1D24U1 - Error - Failed to configure upload to file share.  Destination: \\ec2amaz-mffncsb\SF\DiagnosticsStore\fabricperf-600783b0-f7fd-4fba-9836-60a34cd6b4e6\vm1, Local folder path: C:\SF\Log\PerformanceCounters_WinFabPerfCtrFolder.
4/26/2018 11:53:59 AM - EC2AMAZ-MFFNCSB - Error - Config for Hosting.FirewallPolicyEnabled changed but this entry can not be dynamically updated
4/26/2018 11:53:59 AM - EC2AMAZ-MFFNCSB - Error - Configuration can not be updated dynamically for Hosting/FirewallPolicyEnabled
4/26/2018 11:53:59 AM - EC2AMAZ-MFFNCSB - Error - Exiting the process as configuration can not be updated dynamically.
4/26/2018 11:55:23 AM - EC2AMAZ-MFFNCSB - Error - Timed out waiting for Installer Service to complete for machine 172.31.29.110. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
4/26/2018 11:55:24 AM - EC2AMAZ-MFFNCSB - Error - CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine 172.31.29.110. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(MachineHealthContainer machineHealthContainer, FabricPackageType fabricPackageType, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine 172.31.29.110. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by ashishnegi** [comment]
@JunRamoneda Is this windows or Linux cluster ?
@deepakjangid-MSFT for DCA errors. This looks like a Linux cluster.

**Comment by deepakjangid-MSFT** [comment]
@ashishnegi  This is not a Linux cluster.

@JunRamoneda Can you make sure the network path you have in cluster manifest is present and accessible to Service Fabric Services?

System.IO.FileNotFoundException: The network path was not found. (Exception from HRESULT: 0x80070035)

**Comment by JunRamoneda** [comment]
@ashishnegi I am trying to build a cluster on 3 Windows servers

**Comment by deepakjangid-MSFT** [comment]
@JunRamoneda any update on this?

Can you make sure the network path you have in cluster manifest is present and accessible to Service Fabric Services?
System.IO.FileNotFoundException: The network path was not found. (Exception from HRESULT: 0x80070035)

**Comment by deepakjangid-MSFT** [comment]
Any update @JunRamoneda?

**Comment by JunRamoneda** [comment]
@deepakjangid-MSFT Sorry for not replying sooner. I decided to roll back to 6.1.480.9494 instead. Thanks for all the help

**Comment by deepakjangid-MSFT** [comment]
Ok. I am closing this issue for now. Please let us know in case you update to 6.2 some other time and face any issues.
