### ISSUE TITLE
msbuild sfproj package command copy wrong files to Pkg Code folder

### ISSUE THREAD

**Issue by AWaterColorPen** [Azure/service-fabric-issues#1016]
when I upgrade Microsoft.VisualStudio.Azure.Fabric.MSBuild.**1.6.0** to **1.6.5** or **1.6.6**, I find the sfproj package issue.

The build command ( from VSTS service fabric build task - "Build solution \*\*\\\*.sfproj" ) :  
```
msbuild.exe *.sfproj /t:Package /p:PackageLocation=D:\applicationpackage /p:platform="x64" /p:configuration="Release"
```

Example: here is my project with ServiceA and ServiceB :
```
src\ServiceA\ServiceA.csproj
src\ServiceB\ServiceB.csproj
src\Fabric\Fabric.sfproj 
```
After build command:
```
D:\applicationpackage
   - \ServiceAPkg
       - \Code        // It is right. All the files are equal with ServiceA\bin\x64\Release\
       - \Config      // It is right 
   - \ServiceBPkg
       - \Code        // It is wrong. All the files come Fabric\   what happened?
           - \ApplicationPackageRoot
           - \ApplicationParameters 
           - \bin
           - \obj
           - \PublishProfiles
           - \Scripts
           - app.config
           - packages.config
           - Fabric.sfproj
           - Fabric.sfproj.user
       - \Config      // It is right Settings.xml file from ServiceB.
```
what is the issue? how can I fix it?
Anyone can help?

**Comment by ashishnegi** [comment]
cc @ravipal @dbreshears

**Comment by BinWuMSFT** [comment]
@AWaterColorPen How do you upgrade Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0?

**Comment by BinWuMSFT** [comment]
@AWaterColorPen I can not repo this issue. Do you see this issue even if you create a new project? Could you share a reproducible project to us so that we can investigate?

**Comment by AWaterColorPen** [comment]
@dbreshears @BinWuMSFT 
There is my project structure: 
![image](https://user-images.githubusercontent.com/1636892/39466544-21d44734-4d5c-11e8-9fd3-36b719b9b3e7.png)
![image](https://user-images.githubusercontent.com/1636892/39466577-454fad20-4d5c-11e8-8d76-62290c661cbd.png)
After build with the command:
![image](https://user-images.githubusercontent.com/1636892/39467009-64605032-4d5e-11e8-86ba-1ad7f2f2869b.png)
I find **MiyoKonsouru** service with some package issue.

**Comment by AWaterColorPen** [comment]
@dbreshears @BinWuMSFT 
After cleaning up the projects
```
  <DefaultServices>
    <Service Name="MiyoKonsouru">
      <StatefulService ServiceTypeName="MiyoKonsouruType" TargetReplicaSetSize="[MiyoKonsouru_TargetReplicaSetSize]" MinReplicaSetSize="[MiyoKonsouru_MinReplicaSetSize]">
        <UniformInt64Partition PartitionCount="[MiyoKonsouru_PartitionCount]" LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>
  </DefaultServices>
```
![image](https://user-images.githubusercontent.com/1636892/39468671-e08724ee-4d66-11e8-99ec-6e2adda0033b.png)

There is the my project with the issue
[test.zip](https://github.com/Azure/service-fabric-issues/files/1963452/test.zip)

**Comment by BinWuMSFT** [comment]
@AWaterColorPen What is the VS version you are using?

**Comment by BinWuMSFT** [comment]
@AWaterColorPen I reproduced the issue on the test project. However, when I create a new project, I did not see this issue. Does this issue happen for any project you create?

**Comment by AWaterColorPen** [comment]
@BinWuMSFT The issue is only happened at this project. I want to know how to fix the issue on this project.

**Comment by ravipal** [comment]
@AWaterColorPen, Your service project defines the platform as AnyCPU. 
    \<Platform Condition=" '$(Platform)' == '' ">AnyCPU\</Platform>

The Package task from MSBuild didn't pass the input platform value to all the service projects so it uses the default value defined in the service project which is AnyCPU. AnyCPU is not supported platform for service fabric services.

Please use one of the following workarounds
1. Use Visual Studio to package the application. This package will use the build configuration.
2. Update the service project to use the x64 as default value.
    \<Platform Condition=" '$(Platform)' == '' ">x64\</Platform>
