### ISSUE TITLE
Backup restore example for on-premise fileshare

### ISSUE THREAD

**Issue by Sweiii** [Azure/service-fabric-issues#1017]
Hi, 

i have looked at the Periodic backup and restore in Azure Service Fabric (Preview) post and see that its possible with an on-premise file share. I cant find an example for the on-premise stuff for the $StorageInfo. So can you help me with an configuration example for the StorageInfo

`$StorageInfo = @{
    ConnectionString = 'UNC PATH?'
    ContainerName = 'FolderName?'
    StorageKind = 'FileShare?'
}`

or is there anything completely different?

Best regards,
Andreas Andersson

**Comment by raunakpandya** [comment]
Hey, Have you checked this - https://docs.microsoft.com/en-in/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-standalonecluster

This documentation is specific to standalone scenatio.

**Comment by raunakpandya** [comment]
You can additionally pass username and password as well if the share is secured with a specific credentials and not authorized for access by cluster nodes. 
Check API documentation here, which has REST example as well - https://docs.microsoft.com/en-in/rest/api/servicefabric/sfclient-api-createbackuppolicy

**Comment by Sweiii** [comment]
Ah thanks, i missed that completly

**Comment by raunakpandya** [comment]
Cool. I will close this issue. Let us know how it goes and if you have any feedback.
