### ISSUE TITLE
When will Azure Service Fabric version 6.2.262.9494 be available

### ISSUE THREAD

**Issue by ThiemeNL** [Azure/service-fabric-issues#1018]
Hi,

I have a cluster running in west Europe and cannot upgrade to 6.2.262.9494, because it is not available.

New applications are unhealthy once I deploy it to this cluster, because of the lower version than om my dev box. When will the 6.2.262.9494 be available in Azure?

See related issue:
https://github.com/Azure/service-fabric-issues/issues/997

Thieme

**Comment by raunakpandya** [comment]
Please see - https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/26/second-update-on-the-service-fabric-6-2-release/
We are working to get this out soon :) 
Till then, can you downgrade the SDK back to v6.1/v3.0 and build apps using that? They should work on your v6.1 cluster.

**Comment by ThiemeNL** [comment]
Our sprint is ending the 3th May, before that when need to push the release live. Do you think that the SF team have a fix before that date?

**Comment by salariamanisha** [comment]
We are getting the same issue ? When this upgrade option be available on azure. Also its scary to know that azure and SDK release cycles are out of sync ?

**Comment by JeffMushmo** [comment]
When will there be a fix? This is TERRIBLE!

**Comment by JeffMushmo** [comment]
Every link I find to install the SDK & tools gives me the latest version. Where can we download the 6.1 version from?

On the Service Fabric documentation page, it states that 6.2 IS supported.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

Might be a good idea to get your story straight before sending entire development teams down the wrong path.

**Comment by vikramdadwal** [comment]
Do we have a concrete timelines on when the fix would be coming ? This will really help us settings our sprint goals. Thanks.

**Comment by DHoefakker** [comment]
@JeffMushmo Yeah thanks that was it. Manual start WebPlatform Installer, go to Applications, search "Service Fabric" and install SDK 3.0.480.

**Comment by salariamanisha** [comment]
I see the latest version on Azure as 6.2.274.9494 now. But still nuget is pointing to 6.2.262. Should we assume this is fixed now ?
--

**Comment by ThiemeNL** [comment]
Hi found found this article: https://blogs.msdn.microsoft.com/azureservicefabric/2018/05/14/6-2-release-update/
So it should be fixed now, therefor I will close the ticket. 

I expected that somebody in the SF team would notified use. I'm really disappointed in the communication. Hope it will improve soon.
