### ISSUE TITLE
Service Fabric Specific Standalone Cluster Runtime Version

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#1023]
Hi,
I have a stable Azure Production Cluster that has a version **6.1.467.9494**
And I have a Standalone Staging Cluster that I deployed using this [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server)

The problem is when I run the CreateCluster powershell on my Staging Cluster it updates runtime to latest version 6.1.480.9494. I would like to keep Staging and Prod on same version.

How can I downgrade my Staging Cluster?

**Comment by rishirsinha** [comment]
You can download the correct cab file and use it to create the standalone cluster by passing the cab file to the create cluster command.

**Comment by masnider** [comment]
Closing this issue out as it has been some time and we have not heard back. If you are still having problems with this process, feel free to reopen this issue. If you have other questions, go ahead and open a separate issue and we can help out. Thanks!
