### ISSUE TITLE
Making VS2017 experience nice for creating a dotnet core service package targeting both linux and windows.

### ISSUE THREAD

**Issue by pksorensen** [Azure/service-fabric-issues#1025]
# In visual studio

1. Create Service Fabric Application
2. Select dotnet core stateless service
3. Empty Web template

What are the needed steps to make this project packable for both Unix and Windows clusters?

I know that i found some quickstart repository with an example. But hey, that was a bunch of sh, cmd files and what not. Its not the experience I am looking for. I dont want to develop on linux.

I just want a nice visual studio experience where I can press F5 to test on my windows dev box and when done commit the code and have VSTS build both a linux and windows package.

# Here is what I tried.

Updating web1.csproj to use two RuntimeIdentifiers for Unix and windows. This broke the visual studio build/f5 experience.

I could get vsts to build this semi buy adding msbuild arguments to select the right runtime. 

I am up for trying more things, but would be super cool to have some advices on best path/most promishing path that will lead to success.

# repository
https://github.com/pksorensen/fs-target-unix-windows

[  ] update web1.csproj
[  ] update entrypoint to something that works on both unix/windows

sofar i only been self contained applications. Would a better option be to launch by dotnet web1.dll and have the runtimes installed on the cluster?

**Comment by MikkelHegn** [comment]
Thanks for this Poul - yes we need it.

Framework dependent binaries is definitely the way to go, however it requires .net core installed in the cluster, which we do in Linux at this point. We are working on enabling it in Windows as well. #500.

This is just an initial response, will get back once we find more time to look at this.

**Comment by pksorensen** [comment]
Self contained application is also okay. We just need something that can pick the right ServiceManifest.xml at build time.

I am perfectly happy with any solution that can be done by right clicking in visual studio and altering .sfproj or .csproj.

Maybe it already exists. But if i can define property groups in .sfproj conditional on which runtimeidentifier that is being used such it pick ServiceManifest-runtimeidentifier.xml - that would solve it I think.

**Comment by MikkelHegn** [comment]
@bigmorty

**Comment by anantshankar17** [comment]
This is fixed in the latest 6.5 release.
