### ISSUE TITLE
Mounting a host folder inside a container?

### ISSUE THREAD

**Issue by petertiedemann** [Azure/service-fabric-issues#1027]
I am trying to run RavenDb 4.x in a Service Fabric (Linux) cluster. I was hoping to mount a folder from the local VM SSD into the container. RavenDb has its own clustering mechanism that replicates data between nodes (and does backup etc), so it is ok to lose the data if the node goes down. 

However, I have not been able to discover how to do this with Service Fabric. Is it possible?

**Comment by raunakpandya** [comment]
you can map local volume to container by specifying something like below under containerhostpolicies tag in applicationmanifest..

        <Volume Source="/mnt/myvol/folder1/" Destination="/var/folder1" IsReadOnly="false" />

**Comment by petertiedemann** [comment]
@raunakpandya Like below? I dont see anything?

**Comment by raunakpandya** [comment]
" <Volume Source="/mnt/hostfolder/" Destination="/var/containerfolder" IsReadOnly="false" />  "

**Comment by raunakpandya** [comment]
Arghh.. The xml statement got removed. Had to format it correctly.. 

```xml
<Volume Source="/mnt/hostfolder/" Destination="/var/containerfolder/" IsReadOnly="false" /> 
```
Check here for eg. https://github.com/suhuruli/jenkins-container-application/blob/master/JenkinsSF/ApplicationManifest.xml

BTW, very soon we are coming up with a Service Fabric volume driver which would keep the container state locally within the cluster replicated using service fabric replication stack.

**Comment by petertiedemann** [comment]
@raunakpandya That sounds like exactly what I need. I will close this issue now, as I think you answered it.
