### ISSUE TITLE
ClaimsIdentity not serialized/deserialized correctly on remoting between .net 4.6.2 and dotnetcore 2.0

### ISSUE THREAD

**Issue by angrymrt** [Azure/service-fabric-issues#1028]
When using remoting (V2) between services that target different versions of the .net we have noticed that object aren't being serialized / deserialized correctly. For example, the ClaimsIdentity object is correctly serialized and deserialized when passing between services that both target .net 4.6.2, but when passing between .net 4.6.2 and dotnetcore 2.0, the Claims property on the ClaimsIdentity is empty after deserializing on the dotnetcore 2.0 project, when in fact it wasn't empty on the .net 4.6.2 project.

**Comment by angrymrt** [comment]
@hrushib 2.0.6

**Comment by hrushib** [comment]
ClaimsIdentity isn't marked Serializable in dotnet so can't be serialized by default serializer used by remoting (v2). You can see the difference in [ClaimsIdentity code from dotnet repo](https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/ClaimsIdentity.cs) and [ClaimsIdentity code from .net 4.6.2 reference source](https://github.com/Microsoft/referencesource/blob/1acafe20a789a55daa17aac6bb47d1b0ec04519f/mscorlib/system/security/claims/ClaimsIdentity.cs).

You may use [custom serialization with V2 remoting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2) to make serialization/ deserialization to work correctly.

For out-of-box serialization / deserialization support, open issue in [dotnet/corefx](https://github.com/dotnet/corefx) repo.

Marking this issue closed as this behavior is expected.
