### ISSUE TITLE
Refresh Application and 1 Node Cluster causes Visual Studio to hang

### ISSUE THREAD

**Issue by ddignam** [Azure/service-fabric-issues#1031]
I've been trying to get the 1 node cluster and refresh application to work for the last couple of days, and it consistently hangs visual studio. Unfortunately I can't get anything form the output window, but it doesn't reveal much, it builds the final project before the service fabric project, and then hangs. Using procmon the last sign of activity from devenv is to read 'HKLM\SOFTWARE\Microsoft\Service Fabric SDK' which has the value 1.

I'm using 

`Microsoft` Visual Studio Enterprise 2017 
Version 15.6.7
VisualStudio.15.Release/15.6.7+27428.2043
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio
`

The application is F# and Owin based, and has 3 stateless and 1 stateful service. It deploys fine to a local 5 node cluster, and to a cluster on Azure. Really need the refresh applciaiton scenario to work, deploying takes an age to the 5 node cluster.

**Comment by ddignam** [comment]
Another observation, a colleague  tried and got a message about having to set protections of the folder, which set some protections up for servicefabricAllowedUsers. I don't think I've seen this dialog, and setting it by hand doesn't see to help.

**Comment by dbreshears** [comment]
@ddignam,   do you happen to have a small repro project that we can clone for investigation?  If so, we will take a look, however I will mention that F# is completely untested on our end and thus we have never intended support for it in the VS tooling.    Hopefully it is something easy we can address, but if not I can't guarantee we can resolve this.

**Comment by ddignam** [comment]
@dbreshears 

The F# aspect is probably a red herring, the same repository does work for another developer so it's something environmental. I've tried with the voting application sample (https://github.com/Azure-Samples/service-fabric-dotnet-quickstart) and I get the dialog asking to grant permissions, and the debug session works correctly. 

It appears to hang at the deploy stage, but that line never appears in the build output window

I've tried removing the Service Fabric tools from the VS install, and re installing them and that doesn't fix it, and I've also cloned the repro from scratch.


Is there any debuggin I can enable ?

**Comment by dbreshears** [comment]
@ddignam , So just issuing a Rebuild doesn't cause VS to hang,  only an F5  and only when using Refresh mode and 1 node cluster?    Can you try updating to 15.7 now that it is out?

Can you change MSBuild project build output verbosity to "Detailed" in Tools->Options->Projects and Solution->Build and Run. Do you get anything in the output panes for Build or  Service Fabric Tools when you F5 and if so can you share that?

**Comment by ddignam** [comment]
@dbreshears thanks for the interest. This is quite a killer for us, it takes several minutes to deploy in the 5 node cluster.

I moved to 15.7 earlier in the week, and the hang is still there. The hang happens on build/rebuild, so not run/debug. It only happens in the 1 Node Cluster with Refresh Mode.

I've turned detailed on, but nothing unexpected appears in the output window, I think it hangs as it's about to display stuff (the scroll bar slider moves up, but the output never appears). I can't copy the output as VisualStudio is hung, and I can't find a way to direct the build output to a file.

The last thing that appears to happen in ProcMon is a query of the LocalClusterNodeCount value in the registry.

Packing the  project from the command line using msbuild works, as does building the solution using msbuild.

**Comment by ddignam** [comment]
@dbreshears  Thx, here's the dump file (without heap, with heap came in at 1.2Gb ...)

[devenv.zip](https://github.com/Azure/service-fabric-issues/files/1996634/devenv.zip)

**Comment by ddignam** [comment]
@dbreshears I managed to cut things down to a simple application, with 1 FShapre project. It builds under 5 nodes, but hangs under 1 node

[Application1.zip](https://github.com/Azure/service-fabric-issues/files/1997872/Application1.zip)

Extract the zip, and cd to the solution folder, then run 

.\.paket\paket.exe restore

and build the solution in Visual Studio.

**Comment by dbreshears** [comment]
@ddignam , thanks I will take a look

**Comment by dbreshears** [comment]
@ddignam, I believe I have found a fix for the build deadlock issue in the tooling with Fsharp services.  I will see about getting this integrated into the next 15.8 preview release.

**Comment by ddignam** [comment]
@dbreshears That's great news, thanks for the update.

**Comment by dbreshears** [comment]
Closing as this should be resolved
