### ISSUE TITLE
Is it possible to run fabric in a docker container?

### ISSUE THREAD

**Issue by alexgman** [Azure/service-fabric-issues#1032]
Is it possible to run fabric in a docker container?

**Comment by masnider** [comment]
Yes though today only as a part of your development/build experience. https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux

**Comment by mani-ramaswamy** [comment]
You can also run reliable services in containers (preview) as described in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-services-inside-containers
