### ISSUE TITLE
SF Authentication 

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1036]
Hi Team,

we were able to co-relate below error #6038 in event viewer with Service Fabric user P_FSSUserffffffff using the security event log.

is there way to make this communication more secure using Kerberos/Extended Protection?

Microsoft Windows Server has detected that NTLM authentication is presently being used between clients and this server. This event occurs once per boot of the server on the first time a client uses NTLM with this server.
 
NTLM is a weaker authentication mechanism. Please check:
 
      Which applications are using NTLM authentication?
      Are there configuration issues preventing the use of stronger authentication such as Kerberos authentication?
      If NTLM must be supported, is Extended Protection configured?
 
Details on how to complete these checks can be found at http://go.microsoft.com/fwlink/?LinkId=225699.

Thanks,
Naresh

**Comment by oanapl** [comment]
@nareshkhatri81 , the user is used by fabric:/System/ImageStoreService to authenticate SMB copy between nodes. There is no way at the moment to remove NTLM usage. We are working on removing SMB usage for image store, but that will take some time (probably in a few service fabric releases).
