### ISSUE TITLE
Run a script after F5 in visual studio

### ISSUE THREAD

**Issue by pdylanross** [Azure/service-fabric-issues#1038]
We have recently taken on our first client live and have production resources now, and as we were warned default services have began to bite us. I'm currently in the middle of investigating how we want to approach removal of default services with regards to local development and I'm having a tricky time getting something clean working. 

The approach I first took was to write some psh that reads a file with a straightforward definition of which services need to be spun up on local, taking a hint from the default services section in the app manifest. My initial thought was to just run that script from the end of `Deploy-FabricApplication.ps1`, however once I had my initial ps1 done and I looked at that I realized that that script only publishes the package when used with F5 in VS, and the VS tooling later actually creates the fabric app after the debugger is attached. I had also done the experiment of running my local default service deployment once the VS debugger had attached and found that everything worked as expected - breakpoints hit, and so on. 

Is there any existing tooling for me to hook into VS to run a script once the F5 deployment has finished? If not are there any suggestions for how to approach a local development workflow without default services?

**Comment by masnider** [comment]
VS has tooling for this. You place a service called Start-Service.ps1 within the scripts directory of the application, and that gets called after the application is provisioned. Inside that script is where you can create your services. I've got an example one stashed [here](https://gist.github.com/masnider/b1dd1551c24626dbf744a7bc819d62be).

**Comment by pdylanross** [comment]
Awesome! This is exactly what I needed.
