### ISSUE TITLE
ApplicationParamter in Deploy-FabricApplication.ps1 do not get set

### ISSUE THREAD

**Issue by dannythunder** [Azure/service-fabric-issues#1041]
I've modified my `Deploy-FabricApplication.ps1` to add some custom applicationparameters depending on username to override default-parameters (in the long run I will get all my settings from Azure Key Vault as applicationparameters).

I see my settings with a simple Write-Host just before the Publish-NewServiceFabricApplication script is being triggered:

`Write-Host "User custom parameters:"
	$PublishParameters.ApplicationParameter.Keys | % { "key = $_ , value = " + $PublishParameters.ApplicationParameter.Item($_) }
    Publish-NewServiceFabricApplication @PublishParameters`

Giving me the output:

`key = AzureServiceBusConnectionString value = "******"`

My custom parameters is set and added as in-parameters to `Publish-NewServiceFabricApplication.ps1`.  I've modified `Publish-NewServiceFabricApplication.ps1` and added debug-ouput seeing my custom parameters. At first, everything looks fine:

The same output, as I expect: `key = AzureServiceBusConnectionString value = "******"`.

But then it seems like Publish-NewServiceFabricApplication.ps1 is excecuted once more. This time my debug output looks like this:

`key = _WFDebugParams_ , value = [{"CodePackageName":"Code","CodePackageLinkFolder":null,"ConfigPackageName":null,"ConfigPackageLinkFolder":nu
`...

And the only settings getting set is from `$ApplicationParameterFilePath` (looking at details via _localhost:19080/Explorer/index.html#/apptype/MyApplicationType/app/MyApplication/tab/details_)

**Steps for repro:**

Modify  `Deploy-FabricApplication.ps1` by adding a parameter to `$ApplicationParameter` (that exists in your application, and in yout `Local.1Node.xml` (or whatever you are running).

See if your parameter is overridden.

**System**
Windows 10 Enterprise
Visual Studio 2017: 15.5.7
Microsoft Azure Service Fabric: 6.1.467.9494
Microsoft Azure Service Fabric SDK: 3.0.467.9494

**Comment by NCarlsonMSFT** [comment]
The Deploy-FabricApplication.ps1 is only used for publishing, not local debugging.

Asking around the team the only solution we could dream up to solve your problem for the local debugging case is to modify the Publish-NewServiceFabricApplication.ps1 installed by the SDK, which I can't really recommend as it will affect all deployments form the machine and is not easy for sharing on a team.

**Comment by dannythunder** [comment]
@NCarlsonMSFT maby I was a bit unclear what we want to accomplish


We modify our `Deploy-FabricApplication.ps1` to do stuff if run on a dev-machine, user specific stuff.
For now, the script writes to the` Local.1Node.xml` inApplicationParameters. 

But we dont want this solution as it is a risk of checking in secret keys to git. Thats why we want to load them into `$ApplicationParameters` in the `Deploy-FabricApplication.ps1` script.

---

Whats is triggering `Publish-NewServiceFabricApplication.ps1` the second time with `WFDebugParams_ , value = [{"CodePackageName":"Code","CodePackageLinkFolder":null,"ConfigPackageName":null,"ConfigPackageLinkFolder":nu` as `$ApplicationParameter`?

I've already modified `Publish-NewServiceFabricApplication.ps1` on my local machine to `Write-Host` the content of `$ApplicationParameters`.

The problem is `Publish-NewServiceFabricApplication.ps1` gets called twice. The first run looks OK, the parameters are what I expect . The second run is with `WFDebugParams_ `-crap, and not getting deployd with my parameters (all parameter names are the same as in Local.1Node.xml and Manifest).

**Comment by NCarlsonMSFT** [comment]
I believe what you are seeing are the separate calls to register the type and start the application. You should see the parameter "-Action Create" in the second call indicating that it is starting an instance of the type.

**Comment by dannythunder** [comment]
@NCarlsonMSFT Then how do I set the `$ApplicationParameters` so they get passed to the application?

**Comment by dannythunder** [comment]
So there is no way of doing it from the calling script (`Deploy-FabricApplication.ps1`)? Sorry for late reply.

**Comment by NCarlsonMSFT** [comment]
Sorry perhaps I was unclear, Deploy-FabricApplication.ps1 is never called as part of debugging. So changing that file will not impact debugging. Publish-NewServiceFabricApplication.ps1 is called directly so changing that would be your only opportunity to alter the deployment.

**Comment by NCarlsonMSFT** [comment]
I'm assuming one of my proposals worked for you and closing the issue as inactive. Please let us know if you are still having an issue.
