### ISSUE TITLE
Can't run a specific Docker container on Windows Service Fabric

### ISSUE THREAD

**Issue by louiswrwright** [Azure/service-fabric-issues#1042]
I've been trying to run [browserless/chrome](https://hub.docker.com/r/browserless/chrome/~/dockerfile/) inside of service fabric.

I've run the instance locally through Docker fine.

When running through Service Fabric, the following error is created

```
Creating Container from Image=browserless/chrome failed for ContainerName=sf-0-0b830cf2-7746-41a5-9520-98507610d8f7_c9e5fe2f-be7f-4ba7-9257-04754818e25f, ApplicationId=Document.PDFGeneration.ServiceType_App0, ApplicationName=fabric:/Document.PDFGeneration.Service. DockerRequest returned StatusCode=InternalServerError with ResponseBody=Mount denied:
The source path "C:/SfDevCluster/Data/_App/_Node_0/Document.PDFGeneration.ServiceType_App0:C"
doesn't exist and is not known to Docker
```

At a guess it does not like that ":C" at the end of the path, but I'm not sure where it's getting that from.

Also I have this working fine when using Service Fabric on Linux.

**Comment by RajeetN** [comment]
@louiswrwright, Linux Containers On Windows (LCOW) is not supported on Service fabric in the current release.

**Comment by heavenwing** [comment]
@RajeetN Any plan to support it ?

**Comment by RajeetN** [comment]
Yes its in the plans but we don't have a timeline to share as yet.
