### ISSUE TITLE
Error on service fabric local cluster setup - Unable to find an entry point named 'FabricGetCodePath' in DLL 'FabricCommon.dll

### ISSUE THREAD

**Issue by ramnath-jayaraj** [Azure/service-fabric-issues#1043]
I am getting below error while setting up local service fabric cluster. Any help please?

Followed the steup given in for windows
 https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started

PS C:\WINDOWS\system32> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser
PS C:\WINDOWS\system32> & "$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1"

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

WARNING: The cluster data root (C:\SfDevCluster\Data) is not empty. All files and subfolders under it will be deleted.
Do you want to continue [Y/N]?: Y
The generated json path is C:\Users\<<profile>>\AppData\Local\Temp\tmpE3F7.tmp.json
Processing and validating cluster config.
Unable to find an entry point named 'FabricGetCodePath' in DLL 'FabricCommon.dll'.
C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1 : Exception calling "GetClusterManifest
FromJsonConfig" with "3" argument(s): "Unable to find an entry point named 'FabricGetCodePath' in DLL 'FabricCommon.dll
'."
At line:1 char:1
+ & "$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevCl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [DevClusterSetup.ps1], MethodInvocationException
    + FullyQualifiedErrorId : EntryPointNotFoundException,DevClusterSetup.ps1

**Comment by rishirsinha** [comment]
Please try restarting the OS. It looks like the path variable has not been properly updated.
