### ISSUE TITLE
Subsequent builds with .net framework fail when using Refresh Application.

### ISSUE THREAD

**Issue by bgiftge** [Azure/service-fabric-issues#1050]
Error MSB3027: Could not copy "obj\x64\Debug\MyApp.exe" to "bin\x64\Debug\MyApp.exe". Exceeded retry count of 10. Failed. The file is locked by: "MyApp.exe (16128)" (1, 1)
    Error MSB3021: Unable to copy file "obj\x64\Debug\MyApp.exe" to "bin\x64\Debug\MyApp.exe". The process cannot access the file 'bin\x64\Debug\MyApp.exe' because it is being used by another process. (1, 1)

using VS 2017 and latest service fabric (version ending with 269)

It works fine with .net core projects, just not with .net framework.

**Comment by stofte** [comment]
I'm seeing the same error but with a shared lib reference between two services. Shared.dll prevents the Second.exe from starting up because the file is locked by First.exe.

**Comment by ravipal** [comment]
@bgiftge, Do you hit this problem all the time? Can you please share a repro project?

**Comment by bgiftge** [comment]
I just noticed that after using the debugger the same issue starts happening under .net core.

**Comment by stofte** [comment]
I have the exact opposite problem. I have a years old (eg crufty) SF solution based on .netfull. I added a single .netfull aspnetcore based service and this singular service cannot be redeployed. I assume it relates to the new "refresh" setting that SF/VS mentioned at some point. We have another brand-new SF solution which is fully .netcore based. That solution also has classic ".netcore/netfull" integration issues, such as file locking consistently.

**Comment by ravipal** [comment]
@bgiftge & @stofte, We need to collect the diagnostics level logging to narrow down this issue. Please enable the diagnostics level log, by setting the environment variable "MS_VS_SF_TOOLS_LOGGING_ENABLED=true" and relaunch the VS. This flag will produce the diagnostics log at %temp%\Microsoft.VisualStudio.Azure.Fabric\. Once you hit the issue, please share the log with me at ravipal@microsoft.com.

**Comment by ravipal** [comment]
If this is still an issue, please share the traces.

**Comment by MikeJohnsonDev** [comment]
After updating to Windows 10 version 2004, I now experience this issue. @ravipal, I have emailed you my traces. Hopefully, these are helpful.
