### ISSUE TITLE
Environmental Variable set by Service Fabric inside containers are not available inside w3wp

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1051]
Team,

i see bunch of environmental variables inside docker containers which are set by Service fabric when i do docker exec -it containerid cmd.

Fabric_NodeIPOrFQDN=######
Fabric_NodeName=######
 
But those environmental variables are not passed to application(asp.net) running under iis.

i written simple api inside containers to get those but no luck.

  [SwaggerIgnore]
        [HttpGet, Route("api/GetEnvironmentVariable")]
        public String GetEnvironmentVariable()
        {
            string FabricCodePathEnvironmentVariableName = "Fabric_NodeIPOrFQDN";
            string SFCodePath = Environment.GetEnvironmentVariable(FabricCodePathEnvironmentVariableName, EnvironmentVariableTarget.User);
            if (string.IsNullOrEmpty(SFCodePath))
            {
                SFCodePath = Environment.GetEnvironmentVariable(FabricCodePathEnvironmentVariableName, EnvironmentVariableTarget.Process);
                SFCodePath += "Found in Process";
            }
            if (string.IsNullOrEmpty(SFCodePath))
            {
                SFCodePath = Environment.GetEnvironmentVariable(FabricCodePathEnvironmentVariableName, EnvironmentVariableTarget.Machine);
                SFCodePath += "Found in Machine";
            }
            if (string.IsNullOrEmpty(SFCodePath))
            {
                SFCodePath = Environment.GetEnvironmentVariable(FabricCodePathEnvironmentVariableName);
            }

            return "Environmental Variable" + SFCodePath + " " + "GetInternalGatewayAddress" + "" + this.GetInternalGatewayAddress();
        }

SF -> Docker -> Service Monitor -> IIS -> w3wp().

do we need to do something to pass(promote) environmental variable to w3wp ?

**Comment by harahma** [comment]
This sounds like a docker bug. If you start the container directly with docker run command line and pass some env, do you see it available?

**Comment by nareshkhatri81** [comment]
How does SF set docker env variables ?
I can see env variables inside containers.
Docker passes those env variables to app default pool as per them.

**Comment by harahma** [comment]
SF uses this api passing the environment in Env field of request body: https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate

**Comment by nareshkhatri81** [comment]
We got it fixed by promoting env variables via boostrap script from process to machine level.
Iis supports machine level env variables.

**Comment by UkooLabs** [comment]
@nareshkhatri81 how did you promote the variables facing same issue?

**Comment by nareshkhatri81** [comment]
@UkooLabs - we wrote powershell script to copy env variables from process to machine.
