### ISSUE TITLE
Add-AzureRmServiceFabricClusterCertificate: Throws AggregateException

### ISSUE THREAD

**Issue by smflorentino** [Azure/service-fabric-issues#1054]
Passing something wrong to `Add-AzureRmServiceFabricClusterCertificate` throws a very unhelpful `AggregateException`
```
$rgName = "myGroup"
$cluster = "myCluster"
$secret = "https://<vault name>.vault.azure.net/certificates/ServiceFabricServer/<ID>"
Add-AzureRmServiceFabricClusterCertificate -ResourceGroupName $rgName -Name $cluster -SecretIdentifier $secret
```
throws:
```
Add-AzureRmServiceFabricClusterCertificate : One or more errors occurred.
At C:\Users\scflor\Desktop\repro.ps1:6 char:5
+     Add-AzureRmServiceFabricClusterCertificate -ResourceGroupName $rg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmServ...sterCertificate], AggregateException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricClusterCertificate
```

Can you tell what the error was at first glance?

It took me a few minutes of figuring out how to unpack exceptions in PowerShell, but eventually I found this:
```
PS C:\Users\scflor> $error[0].Exception.InnerExceptions
Invalid ObjectIdentifier: https://myvault.vault.azure.net/certificates/ServiceFabricServer/<ID>. segment [1] should be 
'secrets/', found 'certificates/'
```

It would be nice if the real exception is thrown, not `AggregateException`

**Comment by juhacket** [comment]
@smflorentino Can you tell me what version of AzureRM you are using?

**Comment by smflorentino** [comment]
@juhacket 5.7

**Comment by juhacket** [comment]
We will investigate why the error is not being flattened and traced to the user.

**Comment by GrootMona** [comment]
@juhacket & @smflorentino : any news on this topic?

we are also receiving this error while updating the certificate by using powershell

Add-AzureRmServiceFabricClusterCertificate : One or more errors occurred.
At line:1 char:1
+ Add-AzureRmServiceFabricClusterCertificate -ResourceGroupName 'xxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmServ...sterCertificate], AggregateException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricClusterCertificat
   e

**Comment by killerjoe1990** [comment]
`Write-Host` $Error[0].Exception`

gives you the error output

**Comment by smflorentino** [comment]
Can the cmdlet just be fixed to not throw an AggregateException in the first place?

The above is obvious after a bit of digging but not to folks new to PowerShell.

**Comment by gpraveenonline** [comment]
Is there any fix available? as we are facing issue to move forward

**Comment by rfcdejong** [comment]
Easy when you know to use '$error[0].Exception.InnerExceptions' command. But most people simply do not know, at least make it visible in the error in the first place "One or more errors occurrred. Use $error[0].Exception.InnerExceptions for more details"

**Comment by a-santamaria** [comment]
This is fixed starting in AzureRM.ServiceFabric  0.3.13 ([Azure PowerShell 6.12.0](https://github.com/Azure/azure-powershell/releases/tag/v6.12.0-November2018)) https://github.com/Azure/azure-powershell/pull/7597
