### ISSUE TITLE
Question regarding memory usage of Stateful Services with ReliableConcurrentQueue

### ISSUE THREAD

**Issue by cedheim** [Azure/service-fabric-issues#1057]
Hello
In our application I have noticed that our Stateful Service hosts seem to allocate a lot more memory than other parts of the application (i.e. actors). Basically we use a pattern of Stateful Services with queues to dispatch messages to external sources and I am curious if we are using this correctly and if the memory allocation is working as intended.

When dumping the memory of a service host I noticed that there are 4 million "domain objects" allocated in memory. These are objects that I assume should have passed through the queue at one time or another. Our application is not under heavy load and the queue itself should basically never be backed up too far.
I feel like something is holding a reference to our domain objects, possibly too long?

Below is the memory dump of one of our hosts, domain objects blanked out.
![memory_usage_of_stateful_services](https://user-images.githubusercontent.com/12694400/40048040-808dac86-5831-11e8-8610-556d44adae32.PNG)

The structure of the class which we base our "writers" on below.

    public abstract class WriteDocumentServiceBase<T> : StatefulService where T : IDomainState
    {
        private const string QueueName = "QueueName";

        protected WriteDocumentServiceBase(
            StatefulServiceContext context,
            IReliableStateManagerReplica2 stateManager) : base(context, stateManager)
        {
        }

        protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            var queue = await StateManager.GetOrAddAsync<IReliableConcurrentQueue<T>>(QueueName);

            while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    bool managedToDequeue;

                    using (var transaction = StateManager.CreateTransaction())
                    {
                        var conditionalValue = await queue.TryDequeueAsync(transaction, cancellationToken);
                        managedToDequeue = conditionalValue.HasValue;

                        if (conditionalValue.HasValue)
                        {
                            // ... WRITE TO EXTERNAL SOURCE
                        }

                        await transaction.CommitAsync();
                    }

                    if (!managedToDequeue)
                        await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
                }
                // ... EXCEPTION HANDLING
            }
        }

        protected async Task AddToQueue(T objectToStore)
        {
            var queue = await this.StateManager.GetOrAddAsync<IReliableConcurrentQueue<T>>(QueueName);

            while (true)
            {
                try
                {
                    using (var transaction = this.StateManager.CreateTransaction())
                    {
                        await queue.EnqueueAsync(transaction, objectToStore);
                        await transaction.CommitAsync();
                    }

                    break;
                }
                catch (TimeoutException)
                {
                    await Task.Delay(100, CancellationToken.None);
                }
            }
        }
    }

_Edit: We are currently using SF SDK 6.1.480_

**Comment by sachevl** [comment]
Are you sure someone is holding references to those objects?

They might go to GEN1 easily since they are taking part in writing into external sources and GEN1 will be collected only when memory coming to the end or when GEN1 will exceed a capacity threshold.

A couple of highlights on your code:

1. No need to initialize `IReliableConcurrentQueue` each and everytime to ensure queue is there. Initialize it just once when service is booting up. E.g. as the first step in RunAsync method.
2. Making a call to external sources will hold state manager transaction for longer than needed.

Both of those will have bad impact when increasing load on the service.

**Comment by cedheim** [comment]
@sachevl Thank you for your comment.
1. Regarding initializing of `IReliableConcurrentQueue`, I think we only initialize the queue at the top of RunAsync or am I missunderstanding you? We do get a reference to it every time we "add to the queue" though.
2. We went for not committing the transaction until the data has been sent to have some sort of guarantee. This combined with that ReliableConcurrentQueue should have independent Enqueue / Dequeue operations with the note that it does not provide strict FIFO. Which seemed to match what we wanted, we want to be sure that all messages are sent but order doesn't matter that much.

Also attached is an image of the reference tree for the domain objects.
![memory_usage_of_stateful_services_2](https://user-images.githubusercontent.com/12694400/40053979-85865ed8-5843-11e8-8857-4b5479d33167.PNG)

**Comment by cedheim** [comment]
Also a note, I'm not implying that this is a memory leak per-say. The allocated amount of memory doesn't grow beyond a certain point. I'm guessing it might be some kind of buffer in the replicator? It's just that it seems fairly big and currently it's causing us to use vms with more memory than I think our application actually needs.

**Comment by sachevl** [comment]
I meant you are calling `var queue = await this.StateManager.GetOrAddAsync<IReliableConcurrentQueue<T>>(QueueName);` before each and every enqueue which is relatively heavy operation.

Could you use the same reliable queue object in `AddToQueue` which you've created in `RunAsync`?

I have a suspicion that you are creating multiple reliable queues objects and each of them is caching 1 queue item...

**Comment by ashishnegi** [comment]
@cedheim Try adding `System.GC.Collect()` after you have removed X items from queue. 
If it does not help, look at the memory dump to see which objects are being held ?

May be the code you are showing is simple representation of actual code. If not, what happens if `WRITE TO EXTERNAL SOURCE` succeeds but `await transaction.CommitAsync();` throws ? In that case, your `WRITE TO EXTERNAL SOURCE` needs to be idempotent. If it's idempotent, why not push messages directly to external store ?

**Comment by cedheim** [comment]
Thank you for your feedback.
@sachevl I will test a single instance of the reliable queue.

@ashishnegi The main reason for this solution is that the receiver might not be reliable or performant. We do not want external communication from our actors to block calls to that actor for an extended period of time.

**Comment by masnider** [comment]
@cedheim Given that we haven't heard back from you in a while, I'm going to close down this issue. If you are still seeing this issue and have a live repro on recent SF bits, feel free to reopen and provide that info and we can take a look. If you have other questions or issues, do feel free to open a new issue as well.
