### ISSUE TITLE
Encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present

### ISSUE THREAD

**Issue by mvperez** [Azure/service-fabric-issues#1063]
Hi,
Copying the issue I posted here. 
[Encountered an error during CreateContainer: failure in a Windows system call: No hypervisor is present](https://github.com/Microsoft/service-fabric/issues/131)

**Comment by chunliu** [comment]
What is the sku and os version of your cluster? hyperv isolation is only available on Dv3 and Ev3. And hyper-v was not turned on on RS1 by default, while it is on RS3.

**Comment by marvinvperez** [comment]
I see. My cluster is 6.2.
SKU: 2016-Datacenter-with-Containers
Size: Standard_D2_V2

That means I need to upgrade first to use hyperv. Thanks

**Comment by chunliu** [comment]
@marvinvperez you will want to get a new cluster on D2_v3 and Datacenter-Core-1709-with-Containers.

**Comment by marvinvperez** [comment]
Now I can deploy to azure sf cluster removing isolation="hyperv", it is successful.
However, deploying locally still not. But gives different error message. "Error event: SourceId='System.Hosting', Property='Download:1.0:1.0:64a58831-920e-4c74-adeb-699fb06bba2d'.
There was an error during download.Container deployment is not supported on the node. "

I also mentioned this in my original post. What do you think the cause why I couldn't deploy to my local cluster? The version is also 6.2.  I can download the image manually, and run a container.

**Comment by masnider** [comment]
What's your local OS?

**Comment by marvinvperez** [comment]
Windows 10 Pro

**Comment by marvinvperez** [comment]
I will try again on this and will get back with my feedback.

**Comment by masnider** [comment]
Closing as we haven't heard back. If you are still experiencing this issue on a recent release and setup of SF, please let us know.
