### ISSUE TITLE
Remoting V1 method call times out after 5 min without reaching target service

### ISSUE THREAD

**Issue by rasmus-s** [Azure/service-fabric-issues#1066]
After we upgrade the SF nuget packages to version: 3.1.274 from a old 2.6. We start see issues with remoting v1 communication to/from our service.

We get this exception after 5 min timeout in method call to target service: 
 ```
System.TimeoutException: 
This can happen if message is dropped when service is busy or its long running operation and taking more time than configured Operation Timeout.
at async Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.InvokeWithRetryAsync[](?)
 at async Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.InvokeAsync(?)
 at async Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.InvokeAsync(?)
 at async Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.ContinueWithResult[](?)
 at async BC.WebServer.Controllers.Web.ManageController.Index(?)
 at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync(?)
 at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync(?)
....
```

From the Microsoft-ServiceFabric ETW, we see many warnings and errors (each is repeated many times):
```
Error While Receiving Reply Message : FABRIC_E_ENDPOINT_NOT_FOUND 
Service not Found for this Actor : 6b836dd3-26d9-4610-a156-5f40a75a4e76-131664586727418102-42978541-7167-423f-a093-a9791f0aa85c
Transition: Target=Closed, Before:Aborted, After=Aborted, AfterRefCount=0, Error=FABRIC_E_INVALID_OPERATION, CallAbort=false. 
```

**Our setup:**
Website application that call our Account application that we see the issue with. The Account application contains 3 actor types, 14 stateful/stateless services - Not all the actor/services is getting the timeouts when call them with remoting v1. 

During and short after we update the Account application everything is working fine. But then we starts getting the SF ETW messages above and some of the service (maybe only partitions) is stop working. If we deploy the same package/code again with a new version we are able to get responses from all services/actors, during the update, but again 2-3 min after update is finished we start getting timeouts again.

All services and partitions in Service Fabric Explorer is green.

When i lookup the message ids (_Service not Found for this Actor : 6b836dd3-26d9-4610-a156-5f40a75a4e76-131664586727418102-42978541-7167-423f-a093-a9791f0aa85c_) its pointing to a ActiveSecondary actor on node_0 same node that ETW messages is received on.

From my point of view its seems like the FabricTransportListener look at the ActiveSecondary and not the Primary replica, and that way by mistake detect the service is not found. Because its exist in SF Explorer, and its only the nuget package that its changed.

How can we debug whats going on here?  

-----
I ref, this #692 where there never came a solution for the remoting V1. And due the remoting V2, is still have issues like #590. We want to get remoting V1 to work with the latest nuget packages, and then upgrade to remoting V2 later.

**Comment by rasmus-s** [comment]
We did have tried with remoting V2 on that cluster for months ago. But rolled all services/applications back to SF nuget 2.6 where only V1 exist - and the cluster had worked fine. So, if you not set some persisted flag that this cluster at some point has been using V2, then we can exclude the first issue.
We are not using compactmode attributes. Has just double checked we only using `Microsoft.ServiceFabric.Services.Remoting.V1`.

We had always created our own ReplicaListeners like this, to get some context back and forth the services (like callId, traceId etc). `ExtendedServiceRemotingDispatcher` just read the headers and set CallContext.
```
protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
{
    yield return new ServiceReplicaListener(context => new FabricTransportServiceRemotingListener(context, new ExtendedServiceRemotingDispatcher(context, this)));
}
```

Yes, we also upgrade our web project to asp.net core 2.0 because after the SF nuget upgrade the web project could not deploy/build - on Stackoverflow I did find that the solution was to upgrade to asp.net core 2.0. From my side it's not the web application there is the problem, but one or more account services.
When I deploy the Web application first (latest nuget) and keep the Account running with old nuget (sw), I dont seen any issues. But when I upgrade the Account application I start getting timeouts. I also get timeouts when I keep the Web application running old nuget (sw) and upgrade only the Account application.

On my local dev env (same SDK/Runtime as our Dev cluster) I can deploy new or upgrade the old applications without issues. Its only happen when I do it on our Azure Dev env. Maybe due more nodes?

Are there a way to check if the complaint based resolution is work as it should? 

Have attached our ServiceManifest for Account application.

[ServiceManifest.xml.txt](https://github.com/Azure/service-fabric-issues/files/2015946/ServiceManifest.xml.txt)

**Comment by suchiagicha** [comment]
Why are you using Port 0  for this endpoint.? 

 **<Endpoint Name="AccountActorServiceEndpoint" Port="0">**

Could you remove the port . It should be like this . Try this change and see if this works for you.
<Endpoint Name="AccountActorServiceEndpoint" />
<Endpoint Name="UserActorServiceEndpoint"  />
 <Endpoint Name="DeviceActorServiceEndpoint"  />

**Comment by suchiagicha** [comment]
@rasmus-s 
Also Account Service is an Actor Service or just a statefulservice?
If its an Actor , you should be using FabricTransportActorRemotingListener instead of FabricTransportServiceRemotingListener.

**Comment by rasmus-s** [comment]
Its was due a bug back in 2016 SF runtime 5.4, where the ports get reused and that gave issues, by settings the port to 0 it will use the dynamic port range from the OS (high port number 56xxx) instead of the 20000-30000 port range. 

I tried to remove the port="0" as you describe but, now it look like its all call to account services actors its timeouts.

**Comment by rasmus-s** [comment]
Our Account application have multiple service insite. All stateless/statefull services use FabricTransportServiceRemotingListener and all 3 actors use FabricTransportActorRemotingListener.

**Comment by suchiagicha** [comment]
Please share the SF traces with us to further investigate. 
Also which node your client was on when you saw the timeout and the timestamp.

If Azure cluster, then you can tell me the resource Id and region.

If onprem, give the traces table storage details.

PS : To investigate the issues, could you please open a support ticket from Azure portal, which will enable us to give you a faster resolution and complete postmortum on this issue. Please open a ticket using https://portal.azure.com/?#blade/Microsoft_Azure_Support/HelpAndSupportBlade  
Please refer https://azure.microsoft.com/en-us/support/options/ for details on support options

**Comment by rasmus-s** [comment]
@suchiagicha I dont know if you have seen it but the support ticket created and have Id: [REG:118052218231248]

**Comment by suchiagicha** [comment]
@rasmus-s 
Yes . Look at the traces. Something looks wrong with the way service resolution is working for you .Could you provide me the code-snippet pf how  are you creating proxy for  service fabric:/BC.Account/UserActorService ?
Are you using your own implementation of ClientFactory?

**Comment by suchiagicha** [comment]
@rasmus-s 
Is this the same code for the proxy for service **UserActorService**?
I am seeing the resolve issue for UserActorService?

Looks like Your AccountActorService calls UserActorService . UserActorService is stuck in resolution path.
Above code snippet is for service **AccountActorService**

**Comment by rasmus-s** [comment]
@suchiagicha I fix the fist line in the snippet it should be the ApplicationName not a service uri, was a copy mistake when i try to slim it for github.
The method `ResolveUserActor(Guid userId)` is the method that create a proxy for our `UserActorService` (a actor).
`AccountActorService` is another actor and that actor never call or resolve/create a proxy for the `UserActorService` (actor).

Maybe I misunderstand you?

**Comment by suchiagicha** [comment]
@rasmus-s 
I found one issue in your code. You don't set RSP in your remoting client implementation. We use that information to re-resolve.
I am not sure how it was working before.
Please follow this sample on how to inject custom headers.
https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/tree/classic/Services/ServiceRemotingCustomHeaders

https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/blob/3a0d018d08bb1be6034c6a1eddadcabac8c512ac/Services/ServiceRemotingCustomHeaders/Common/MyServiceRemotingClient.cs#L42

**Comment by rasmus-s** [comment]
Hi @suchiagicha 
It have now run on our developer cluster for 1 day without any issues. The solution was as you mention the ResolvedServicePartition not use the innerClient.ResolvedServicePartition. 
Its very strange that it has worked in the past, but that code had not been touched for years...
Again thanks for the solution, you can close this and the support ticket.
