### ISSUE TITLE
ExtractInstallerService failed to extract C:\Users\****\AppData\Local\Temp\ayznbit1.sei\FabricInstallerService.Code\FabricClient.dll.

### ISSUE THREAD

**Issue by rspandi1985** [Azure/service-fabric-issues#1068]
I am installing service fabric cluster and getting following error.

ExtractInstallerService failed to extract C:\Users\***\AppData\Local\Temp\ayznbit1.sei\FabricInstallerService.Code\F
abricClient.dll.
CreateCluster Error: System.IO.FileNotFoundException: ExtractInstallerService failed to extract C:\Users\***\AppData
\Local\Temp\ayznbit1.sei\FabricInstallerService.Code\FabricClient.dll.
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.ExtractInstallerService(String cabPath, String
 pathToExtract)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass14_0.<ConfigureNodesAsync>b__
0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
Trace folder already exists. Traces will be written to existing trace folder: F:\Microsoft.Azure.ServiceFabric.WindowsSe
rver.6.1.467.9494\DeploymentTraces
Cleaning up faulted installation.
Collecting event logs failed due to error System.IO.FileNotFoundException: Could not find file '\\**.***.**.34\C$\Window
s\temp\ServiceFabricEventLog.txt'.
File name: '\\**.***.**.34\C$\Windows\temp\ServiceFabricEventLog.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName) on machine **.***.**.34. Please go to each node to view event logs.
Collecting event logs failed due to error System.IO.FileNotFoundException: Could not find file '\\**.***.**.35\C$\Window
s\temp\ServiceFabricEventLog.txt'.
File name: '\\**.***.**.35\C$\Windows\temp\ServiceFabricEventLog.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName) on machine **.***.**.35. Please go to each node to view event logs.
Collecting event logs failed due to error System.IO.FileNotFoundException: Could not find file '\\**.***.**.15\C$\Window
s\temp\ServiceFabricEventLog.txt'.
File name: '\\**.***.**.15\C$\Windows\temp\ServiceFabricEventLog.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName) on machine **.***.**.15. Please go to each node to view event logs.
Create Cluster failed. For more information please look at traces in FabricLogRoot.

**Comment by pocki** [comment]
I had the same issue.
My Workaround: Delete the folders DeploymentComponents, DeploymentRuntimePackages and DeploymentTraces before running CreateServiceFabricCluster.ps1

**Comment by AndreasHassing** [comment]
I ran into this issue and solved it by fetching the latest version of the SF standalone setup scripts.

**Comment by rspandi1985** [comment]
I had to install new version of SF which fixed this issue.

**Comment by gore01** [comment]
I have the same issue with the last package
MicrosoftAzureServiceFabric.6.3.187.9494.cab

There is no FabricClient.dll and creating cluster failed with the error
`
ExtractInstallerService failed to extract C:\Users\user\AppData\Local\Temp\e3n22vqk.phh\FabricInstallerService.Code\FabricClient.dll.
CreateCluster Error: System.IO.FileNotFoundException: ExtractInstallerService failed to extract C:\Users\user\AppData\Local\Temp\e3n22vqk.phh\FabricInstallerService.Code\FabricClient.dll.
   in Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.ExtractInstallerService(String cabPath, String
pathToExtract)
   в Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass14_0.<ConfigureNodesAsync>b__0
()
   в System.Threading.Tasks.Task.Execute()

Is it possible that there something wrong with the package?

**Comment by gore01** [comment]
I was able to install the only 6.2.262.9494 version. I've found it in my dev cluster setup under SF working folder.
