### ISSUE TITLE
Auto creation of Service without DefaultServices on developer machines

### ISSUE THREAD

**Issue by knowhoper** [Azure/service-fabric-issues#1069]
At the recent Service Fabric Community Q&A 24th Edition there was a lot of discussion around using the DefaultService construct in the ```ApplicationManifest.xml``` and it's drawbacks. Microsoft suggested omitting this from an ApplicationManifest entirely and instead modifying the ```Deploy-FabricApplication.ps1``` to construct a default implementation of an application so developers still have a decent F5 experience. 

So I have modified the ```Deploy-FabricApplication.ps1``` to the following (this excerpt is the bottom of the script):

       if ($IsUpgrade)
    {
        $Action = "RegisterAndUpgrade"
        if ($DeployOnly)
        {
            $Action = "Register"
        }
        
        $UpgradeParameters = $publishProfile.UpgradeDeployment.Parameters
    
        if ($OverrideUpgradeBehavior -eq 'ForceUpgrade')
        {
            # Warning: Do not alter these upgrade parameters. It will create an inconsistency with Visual Studio's behavior.
            $UpgradeParameters = @{ UnmonitoredAuto = $true; Force = $true }
        }
    
        $PublishParameters['Action'] = $Action
        $PublishParameters['UpgradeParameters'] = $UpgradeParameters
        $PublishParameters['UnregisterUnusedVersions'] = $UnregisterUnusedApplicationVersionsAfterUpgrade
    
        Publish-UpgradedServiceFabricApplication @PublishParameters
    }
    else
    {
        $Action = "RegisterAndCreate"
        if ($DeployOnly)
        {
            $Action = "Register"
        }
    
        $PublishParameters['Action'] = $Action
        $PublishParameters['OverwriteBehavior'] = $OverwriteBehavior
        $PublishParameters['SkipPackageValidation'] = $SkipPackageValidation
        
        Publish-NewServiceFabricApplication @PublishParameters
        #Get-ServiceFabricApplication
      
       New-ServiceFabricService -Stateless -ApplicationName "fabric:/Acme.Hierarchy" -ServiceTypeName "Acme.Hierarchy.HierarchyServiceType" -ServiceName "fabric:/Acme.Hierarchy/Acme.Hierarchy.HierarchyService"-InstanceCount 1 -PartitionSchemeSingleton
    }

 
The above fails with the error 

> FabricElementNotFoundException

However, if you uncomment the line  ``` #Get-ServiceFabricApplication``` you will see that it does in fact return an application of 

    ApplicationName        : fabric:/Acme.Hierarchy
    ApplicationTypeName    : Acme.HierarchyType
    ApplicationTypeVersion : 1.0.0
    ApplicationParameters  : { "_WFDebugParams_" = "[{"CodePackageName":"Code","Cod
                             ePackageLinkFolder":null,"ConfigPackageName":null,"Con
                             figPackageLinkFolder":null,"DataPackageName":null,"Dat
                             aPackageLinkFolder":null,"LockFile":null,"WorkingFolde
                             r":null,"ServiceManifestName":"Quantium.RetailToolkit.
                             Fabric.Hierarchy.HierarchyServicePkg","EntryPointType"
                             :"Main","DebugExePath":"C:\\Program Files 
                             (x86)\\Microsoft Visual Studio\\2017\\Professional\\Co
                             mmon7\\Packages\\Debugger\\VsDebugLaunchNotify.exe","D
                             ebugArguments":" 
                             {6286e1ef-907b-4371-961c-d833ab9509dd} -p [ProcessId] 
                             -tid [ThreadId]","DebugParametersFile":null}]";
                             "Acme.Hierarchy.HierarchyServ
                             ice_InstanceCount" = "1" }
    
    Create application succeeded.

and running the command that fails after the publish script has finished works perfectly.

Does anyone have a solution as to how I can get a good developer experience by not using DefaultServices and instead using Powershell scripts?

**Comment by masnider** [comment]
As we talked about in the call, there's also Start-Service.ps1, which you can add to the /Scripts folder within the application project. This will get called after the application gets created.

![image](https://user-images.githubusercontent.com/10968331/40323425-2e14300c-5cea-11e8-9d59-aa04751d4a03.png)

Here's the content of one that I have that I use for local development. This will be in the next update (major rewrite) of the data aggregation [sample](https://azure.microsoft.com/en-us/resources/samples/service-fabric-dotnet-data-aggregation/), so it doesn't quite line up today but it should give you the idea. Note that we're also talking with the tooling team to see what other information could be presented to Start-Service.ps1 so that you don't have to keep these parameters present, know what environment you're targeting etc, but it works great for my dev box. 

```
$cloud = $false
$singleNode = $true
$constrainedNodeTypes = $false

$lowkey = "-9223372036854775808"
$highkey = "9223372036854775807" 

$countyLowKey = 0
$countyHighKey = 57000

$appName = "fabric:/DataAggregation"
$appType = "DataAggregationType"
$appInitialVersion = "1.0.0"

if($singleNode)
{
    $webServiceInstanceCount = -1
    $deviceCreationInstanceCount = -1
    $countyServicePartitionCount = 1
    $deviceActorServicePartitionCount = 1
    $doctorServicePartitionCount = 1
}
else
{
    $webServiceInstanceCount = @{$true=-1;$false=1}[$cloud -eq $true] 
    $deviceCreationInstanceCount = @{$true=-1;$false=1}[$cloud -eq $true] 
    $countyServicePartitionCount = @{$true=10;$false=5}[$cloud -eq $true]  
    $deviceActorServicePartitionCount = @{$true=15;$false=5}[$cloud -eq $true]  
    $doctorServicePartitionCount = @{$true=100;$false=5}[$cloud -eq $true]  

    if($constrainedNodeTypes)
    {
        $webServiceConstraint = "NodeType == "
        $countyServiceConstraint = "NodeType == "
        $nationalServiceConstraint = "NodeType == "
        $deviceServiceConstraint = "NodeType == "
        $doctorServiceConstraint = "NodeType == "   
        $deviceCreationServiceConstraint = "NodeType == "        
    }
    else
    {
        $webServiceConstraint = ""
        $countyServiceConstraint = ""
        $nationalServiceConstraint = ""
        $deviceServiceConstraint = ""
        $doctorServiceConstraint = ""
        $deviceCreationServiceConstraint = ""   
    }
}

$webServiceType = "DataAggregation.WebServiceType"
$webServiceName = "DataAggregation.WebService"

$nationalServiceType = "DataAggregation.NationalServiceType"
$nationalServiceName = "DataAggregation.NationalService"
$nationalServiceReplicaCount = @{$true=1;$false=3}[$singleNode -eq $true]  

$countyServiceType = "DataAggregation.CountyServiceType"
$countyServiceName = "DataAggregation.CountyService"
$countyServiceReplicaCount = @{$true=1;$false=3}[$singleNode -eq $true]  

$deviceCreationServiceType = "DataAggregation.DeviceCreationServiceType"
$deviceCreationServiceName = "DataAggregation.DeviceCreationService"

$doctorServiceType = "DataAggregation.DoctorServiceType"
$doctorServiceName = "DataAggregation.DoctorService"
$doctorServiceReplicaCount = @{$true=1;$false=3}[$singleNode -eq $true]

$deviceActorServiceType = "DeviceActorServiceType"
$deviceActorServiceName= "DataAggregation.DeviceActorService"
$deviceActorReplicaCount = @{$true=1;$false=3}[$singleNode -eq $true]

New-ServiceFabricService -ServiceTypeName $webServiceType -Stateless -ApplicationName $appName -ServiceName "$appName/$webServiceName" -PartitionSchemeSingleton -InstanceCount $webServiceInstanceCount -PlacementConstraint $webServiceConstraint -ServicePackageActivationMode ExclusiveProcess

#create national
New-ServiceFabricService -ServiceTypeName $nationalServiceType -Stateful -HasPersistedState -ApplicationName $appName -ServiceName "$appName/$nationalServiceName" -PartitionSchemeSingleton -MinReplicaSetSize $nationalServiceReplicaCount -TargetReplicaSetSize $nationalServiceReplicaCount -PlacementConstraint $nationalServiceConstraint -ServicePackageActivationMode ExclusiveProcess

#create county
New-ServiceFabricService -ServiceTypeName $countyServiceType -Stateful -HasPersistedState -ApplicationName $appName -ServiceName "$appName/$countyServiceName" -PartitionSchemeUniformInt64 -LowKey $countyLowKey -HighKey $countyHighKey -PartitionCount $countyServicePartitionCount -MinReplicaSetSize $countyServiceReplicaCount -TargetReplicaSetSize $countyServiceReplicaCount -PlacementConstraint $countyServiceConstraint -ServicePackageActivationMode ExclusiveProcess

#create doctor
New-ServiceFabricService -ServiceTypeName $doctorServiceType -Stateful -HasPersistedState -ApplicationName $appName -ServiceName "$appName/$doctorServiceName" -PartitionSchemeUniformInt64 -LowKey $lowkey -HighKey $highkey -PartitionCount $doctorServicePartitionCount -MinReplicaSetSize $doctorServiceReplicaCount -TargetReplicaSetSize $doctorServiceReplicaCount -PlacementConstraint $doctorServiceConstraint -ServicePackageActivationMode ExclusiveProcess

#create device
New-ServiceFabricService -ServiceTypeName $deviceActorServiceType -Stateful -HasPersistedState -ApplicationName $appName -ServiceName "$appName/$deviceActorServiceName" -PartitionSchemeUniformInt64 -LowKey $lowkey -HighKey $highkey -PartitionCount $deviceActorServicePartitionCount -MinReplicaSetSize $deviceActorReplicaCount -TargetReplicaSetSize $deviceActorReplicaCount -PlacementConstraint $deviceServiceConstraint -ServicePackageActivationMode ExclusiveProcess -Verbose

#create device creation
New-ServiceFabricService -ServiceTypeName $deviceCreationServiceType -Stateless -ApplicationName $appName -ServiceName "$appName/$deviceCreationServiceName" -PartitionSchemeSingleton -InstanceCount $deviceCreationInstanceCount -PlacementConstraint $deviceCreationServiceConstraint -ServicePackageActivationMode ExclusiveProcess
```

**Comment by knowhoper** [comment]
I missed the script name in the call. Are the calls recorded - there is a lot of useful info in them that's easy to miss?

Regardless, the above is super useful. Thank you!

**Comment by olitomlinson** [comment]
@knowhoper 

https://www.youtube.com/channel/UC0nFiDDfBO8yhmGV0kgPiNw

**Comment by knowhoper** [comment]
@olitomlinson  thank you!
