### ISSUE TITLE
Windows Container support on Win10 local dev cluster

### ISSUE THREAD

**Issue by mikanyg** [Azure/service-fabric-issues#107]
Have just kicked the tires at the latest 5.4 release which include preview of windows container support. Was very disappointed when I found out that only Win Server 2016 is supported. 

Visual Studio templates explicitly states that my local cluster on Win10 anniversay edition is not supported, how come?

I have enabled Windows container support and played around with using docker for windows, so I see no reason why SF SDK would not support Win10 local clusters.

Any workarounds or plans to add Win10 support?

**Comment by MikkelHegn** [comment]
Hi Mikael,

Service Fabric only support Windows Server Containers at this time: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-overview#service-fabric-support-for-containers

Windows 10 only supports Hyper-V containers: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10

**Comment by mikanyg** [comment]
Thx, makes sense, got confused since Docker for windows just calls it "Swith to Windows Containers", so I actually thought it was to other way round, that hyper-v containers where only available on Server2016
