### ISSUE TITLE
Service fabric package stuck in error during code package activation

### ISSUE THREAD

**Issue by fridastenebo** [Azure/service-fabric-issues#1070]
I have a ServiceFabric Application running on 5 nodes. I was in the process of restarting the nodes one by one to get rid of a known Memory Leakage problem. Restarting node 1 went fine.

Ran into problems when restarting node 2. On node 2 there is a Stateful Service with 1 (large) partition that ended up in Quarum Loss.

> Unhealthy deployed service package: ApplicationName='fabric:/MyApplication', 
> ServiceManifestName='ServicePkg',ServicePackageActivationId='', NodeName='node02', AggregatedHealthState='Error'.

Deleted the Service from the node(Via Manage Local Cluster), which was fine but ServicePkg is still lingering on that node, trying to activate the package with the following Error

> Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'. There was an error during CodePackage activation.The service host terminated with exit code:2148734499

For now I managed to get the service started on other nodes as long as I allowed for more Replicas, but as long as the error on Node 2 exists, upgrades will fail because the Application is in a Failed state.

**Can this be fixed without a complete purge on Node 2?**

Thanks!

**Comment by harahma** [comment]
@fridastenebo Is it a local dev cluster as you mentioned "Via Manage Local Cluster"? When you say 1 large partition, do you mean the state stored in that partition is large?

When you issue delete for a stateful service, the local state associated with replicas of service also needs to be deleted so it may take some minutes to get it complete deleted. The service process will also go away in few minutes.
