### ISSUE TITLE
Problems attaching Visual Studio Debugger to Remote Service Fabric Cluster with Network Security Group

### ISSUE THREAD

**Issue by assadf** [Azure/service-fabric-issues#1076]
Hi all,

I'm trying to attach my Visual Studio debugger to a remote Service Fabric cluster to try and debug a failing service which isn't starting up (no useful info in the Explorer nor Application Insights which has been configured as well).  When I try to enable debugging in Visual Studio cloud explorer I get the following error:

Configuring network security group 'MySecurityGroup' used by cluster 'MyCluster' - The remote server returned an error: (400) Bad Request. 

My Network Security Group has port restrictions and I suspect this is why I'm getting this error.  If I'm right, what port number do I need to open in order for me to be able to debug remotely, or am I barking up the wrong tree here?

Thanks,
Assad

**Comment by ashishnegi** [comment]
Can you try `4020` and other ports as given in https://msdn.microsoft.com/en-us/library/mt592019.aspx ?

**Comment by ashishnegi** [comment]
You can also `remote desktop` RDP to the machine and try running your service executable from command prompt. You will see actual error then.

**Comment by ashishnegi** [comment]
@ravipal Can you help @assadfaizi setup remote debugger in VS when network security group is configured ?

**Comment by ashishnegi** [comment]
@assadfaizi We have open sourced most of our code. The trace/debug viewer code open sourcing is also in progress. I don't have a date yet. But with that, it will be much easier for you to find these errors without RDP.

**Comment by mack0196** [comment]
For standalone clusters, could I attach to service fabric services on server-nodes if the debug service msvsmon.exe was running?

**Comment by ravipal** [comment]
Yes that would be similar to any other remote debugging. In that case, you need to know a specific node where the primary replica is running. Also the ports needs to be opened up if it is behind a load balancer.

**Comment by ravipal** [comment]
Enable debugging should open the required port in the load balancer and it should also configure the NSG to allow those ports. If there are some NSG rules added after the configuration, it might fail. Please check the load balancer's inbount NAT pool rule and corresponding ports are not restricted in NSG. Please reopen this issue, if enable (configuration) is not opening up the port.
