### ISSUE TITLE
Azure API's for Vertical Scaling

### ISSUE THREAD

**Issue by NISHANTH2066** [Azure/service-fabric-issues#1077]
Actually can we vertically scale things using some API's?

The Fluent Azure Management Libraries for .NET docs are not available. 

And whenever I do Horizontal scaling using this

StatelessServiceUpdateDescription updateDescription = new StatelessServiceUpdateDescription(); 
updateDescription.InstanceCount = 50;
await fabricClient.ServiceManager.UpdateServiceAsync(new Uri("fabric:/app/service"), updateDescription); 

I get Health warning in SDK standalone clusters? Like this Failed to bind to address http://[::]:8080: address already in use.

I wanted to be proactive instead of being reactive. 

So writing rules for using autoscaling present in Azure is not the solution.

Thanks.

So can you help me out with Vertical Scaling API's and the docs.

I want to do things programmatically.

**Comment by NISHANTH2066** [comment]
Hello @ashishnegi, Can you please help me in finding the number of Instances a service is running given that service Uri.
If I want to scale out, the update Description method updates given the number of instances.
But it will be great if we could get the number of instances it is running currently and then do that.

**Comment by ashishnegi** [comment]
@NISHANTH2066 Can you try [GetServiceDescriptionAsync](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.servicemanagementclient.getservicedescriptionasync?view=azure-dotnet#System_Fabric_FabricClient_ServiceManagementClient_GetServiceDescriptionAsync_System_Uri_) ? and then use `instance of` for `StatelessServiceDescription` and look for [InstanceCount](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.statelessservicedescription.instancecount?view=azure-dotnet#System_Fabric_Description_StatelessServiceDescription_InstanceCount) .

**Comment by NISHANTH2066** [comment]
Thank you @ashishnegi. Thanks a lot

**Comment by NISHANTH2066** [comment]
If I add some "ScalingPolicies" to a service say based on "servicefabric:/_CpuCores".

And at later point in time, if I want to update its desciption. What is the better way of doing this. As ScalingPolicies is a list, I have to iterate to all of them, find which refers to "servicefabric:/_CpuCores" delete it and then add the new policy.

Is there any better way.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-autoscaling

I am referring to the above link.

**Comment by ashishnegi** [comment]
@radicmilos Can you suggest better way to dynamically change scaling policies as asked on [question](https://github.com/Azure/service-fabric-issues/issues/1077#issuecomment-395311617) ?

**Comment by ivan12346** [comment]
You should just update service with new scaling policy. It should override (update) old policy.
ScalingPolicies is a list but currently is supported only one scaling policy per service. This way, update service with new policy will always delete old and set new scaling policy.

**Comment by aljo-microsoft** [comment]
@NISHANTH2066 

If you have any future issues, please open a support case, and file any documentation issues against any document that isn't helping your achieve success.
