### ISSUE TITLE
Dynamic partition scaling in an on premise cluster - docs incorrect?

### ISSUE THREAD

**Issue by knowhoper** [Azure/service-fabric-issues#1079]
Hi,

I am looking at creating an application that stores blobs across an on prem cluster. As well as being useful this would provide a good reference implementation for us to explore dynamic partition scaling in ASF via load metrics -MemoryMB.

The following script I copied from [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-autoscaling) doesn't work though.

```
$mechanism = New-Object -TypeName System.Fabric.Description.AddRemoveIncrementalNamedParitionScalingMechanism
$mechanism.MinPartitionCount = 1
$mechanism.MaxPartitionCount = 3
$mechanism.ScaleIncrement = 2
$trigger = New-Object -TypeName System.Fabric.Description.AverageServiceLoadScalingTrigger
$trigger.MetricName = "servicefabric:/_MemoryInMB"
$trigger.LowerLoadThreshold = 5
$trigger.UpperLoadThreshold = 10
$trigger.ScaleInterval = New-TimeSpan -Minutes 25
$scalingpolicy = New-Object -TypeName System.Fabric.Description.ScalingPolicyDescription
$scalingpolicy.ScalingMechanism = $mechanism
$scalingpolicy.ScalingTrigger = $trigger
$scalingpolicies = New-Object 'System.Collections.Generic.List[System.Fabric.Description.ScalingPolicyDescription]'
$scalingpolicies.Add($scalingpolicy)
#as we are using scaling on a resource this must be exclusive service
#also resource monitor service needs to be enabled
New-ServiceFabricService -ApplicationName  fabric:/Acme.Fabric.System -ServiceName fabric:/Acme.Fabric.System/Acme.Fabric.System.BlobStore -ServiceTypeName Acme.Fabric.System.BlobStoreType –Stateful -TargetReplicaSetSize 3 -MinReplicaSetSize 2 -HasPersistedState true -PartitionNames @("0","1") -ServicePackageActivationMode ExclusiveProcessScalingPolicies -ScalingPolicies $scalingpolicies

```

Seems like the ```New-ServiceFabricService``` no longer accepts a ScalingPolicies argument? We'd like to achieve this via Powershell if possible as we are steering away from DefaultServices.

Any help would be appreciated.

Thanks

**Comment by puzovicnikola** [comment]
Hi @knowhoper ,

Auto scaling requires runtime version 6.2 or higher, and SDK version 3.1 or higher. If you don't have those, then you can't use Powershell or C# to specify auto scaling policies. If you have correct versions, give me the exact error that you get in Powershell and I will take a look.

In C#, the error states that "Scaling the number of partitions is only supported with average service load." You will need to change the code like this:

```
var fabricClient = new FabricClient();
           var serviceUpdate = new StatefulServiceUpdateDescription();
           var trigger = new AverageServiceLoadScalingTrigger();
           var mechanism = new AddRemoveIncrementalNamedPartitionScalingMechanism();
           mechanism.MaxPartitionCount = 4;
           mechanism.MinPartitionCount = 1;
           mechanism.ScaleIncrement = 1;
           //expecting that the service already has metric NumberOfConnections
           trigger.MetricName = "NumberOfConnections";
           trigger.ScaleInterval = TimeSpan.FromMinutes(15);
           trigger.LowerLoadThreshold = 10000;
           trigger.UpperLoadThreshold = 20000;
           ScalingPolicyDescription policy = new ScalingPolicyDescription(mechanism, trigger);
           serviceUpdate.ScalingPolicies = new List<ScalingPolicyDescription>();
           serviceUpdate.ScalingPolicies.Add(policy);
           await fabricClient.ServiceManager.UpdateServiceAsync(new Uri("fabric:/acme/blobstore"), serviceUpdate);
```

I changed the trigger is changed from AveragePartitionLoadScalingTrigger to AverageServiceLoadScalingTrigger. This difference is that the first trigger that you originally used looks at load of all instances of a single partition and can be used to scale by adding/removing instances. AverageServiceLoadScalingTrigger on the other hand looks at the load of all partitions of the service and can be used to scale by adding/removing named partitions. These are the only supported combinations of trigger and mechanism now. If this does not work, please reply with the error.

Cheers,
Nikola

**Comment by knowhoper** [comment]
@puzovicnikola  thank you for this. It works - or doesn't error. However, I am struggling to scale the service. 

I use a Metric of BytesUsed in the above code snippet, as follows:


```
           var fabricClient = new FabricClient();
            var serviceUpdate = new StatefulServiceUpdateDescription();
            var trigger = new AverageServiceLoadScalingTrigger();

            var mechanism = new AddRemoveIncrementalNamedPartitionScalingMechanism
            {
                MaxPartitionCount = 4,
                MinPartitionCount = 1,
                ScaleIncrement = 1
            };

            trigger.MetricName = "BytesUsed";
            trigger.ScaleInterval = TimeSpan.FromMinutes(15);
            trigger.LowerLoadThreshold = 0;
            trigger.UpperLoadThreshold = 15000;
            var policy = new ScalingPolicyDescription(mechanism, trigger);
            serviceUpdate.ScalingPolicies = new List<ScalingPolicyDescription> { policy };
            await fabricClient.ServiceManager.UpdateServiceAsync(new Uri("fabric:/Acme/Acme.BlobStore"), serviceUpdate);
```

With a service manifest file of

```
     <StatefulServiceType ServiceTypeName="Acme.BlobStoreType" HasPersistedState="true">
          <LoadMetrics>
              <LoadMetric Name="BytesUsed" Weight="High" DefaultLoad="0"/>
          </LoadMetrics>
      </StatefulServiceType>
```
Then, I have implemented a method to simulate the load - to try to stimulate scaling

```
 public Task Load()
        {
            Partition.ReportLoad(new[] { new LoadMetric("BytesUsed", 21000) });

            return Task.CompletedTask;
        }
```
I run the following PowerShell to create the services after deployment.

```
New-ServiceFabricService -ApplicationName fabric:/Acme -ServiceName fabric:/Acme/Acme.BlobStore.API  -ServiceType Acme.BlobStore.APIType   -Stateless -PartitionSchemeSingleton -InstanceCount 1

New-ServiceFabricService -ApplicationName fabric:/Acme -ServiceName fabric:/Acme/AcmeBlobStore -ServiceType Quantium.Fabric.System.BlobStoreType -Stateful -PartitionSchemeNamed -PartitionNames @("0") -MinReplicaSetSize 2 -TargetReplicaSetSize 3 -HasPersistedState
```
The service does not scale its partitions as I would hope it would.  Can you help? - this feature would be really useful for us.

Many thanks in advance.

**Comment by puzovicnikola** [comment]
Hi,

From the code snippets, it looks like you are creating service with name fabric:/Acme/AcmeBlobStore and updating service with name fabric:/Acme/Acme.BlobStore (difference is one dot in the name).

To make sure that everything is setup correctly for auto scaling, can you please run these two commands (please use correct service name):
1) Check if service description has ScalingPolicies field set properly:
`Get-ServiceFabricServiceDescription - ServiceName fabric:/Acme/AcmeBlobStore`
2) Check if load is reported correctly for the partitions of this service:
```
Get-ServiceFabricService -ServiceName fabric:/Demo/DemoService -ApplicationName fabric:/Demo | Get
-ServiceFabricPartition | Get-ServiceFabricPartitionLoadInformation
```

Please post the output here.

Cheers,
Nikola

**Comment by knowhoper** [comment]
Hi @puzovicnikola,

Thanks for your help with this. The typo was my mistake -  it doesn't exist in the prod code, i changed the company name.

The scaling actually works perfectly, I changed the scale interval to 1 minute and saw scaling very quickly. Awesome feature.

Thanks for your help, much appreciated.
