### ISSUE TITLE
Service Fabric Core Project Creation Fails

### ISSUE THREAD

**Issue by SmegheadSev** [Azure/service-fabric-issues#1082]
I'm trying to create a new Service Fabric Service within an existing solution and anytime I try creating a Core project Visual Studio hangs and I have to restart VS. When relaunched the project was created but without any of the NuGet packages. If I add them by hand it seems to work but this is a bit of a hassle. Until recently this issue didn't happen so I'm guessing it has something to do with the new Service Fabric SDK that was released earlier this month.

**Comment by baltie** [comment]
This happens with me as well. I can create a new .NET Core stateless service without problems, but not a new .NET Core stateful service, experiencing the same. This is my environment:
VS 15.7.3 with Azure Service Fabric Tools 2.1
Azure Service Fabric SDK 3.1.283
Runtime 6.2.283

**Comment by danijel-peric** [comment]
Same issue, latest vs 2017, adding new core service to existing service project blocks the vs, i had this for last few versions of vs and fabric sdk, anyone can repeat this problem, its not machine or os version related

**Comment by H286424** [comment]
try to debug the code remotely at least using the below Azure SF cluster.
For your ref: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#debug-a-remote-service-fabric-application

**Comment by dbreshears** [comment]
@danijel-peric .  Can you confirm you are on 15.7.4.  We did address a timing issue with underlying project system and nuget restore causing a deadlock that could be relatd.  
If you still reproduce with this build of the VS 2017 then we need to further investigate.

Can you upload a Dump file.   Attach another instance of VS 2017 (devenv.exe) via Debug -> Attach to Process... and then choose Debug -> Break All and Debug -> Save Dump As...

**Comment by dbreshears** [comment]
@danijel-peric, @baltie, @SmegheadSev  .  Do any of you happen to have Resharper installed?   There is also an issue we recently discovered where adding an SF Service can hang when Resharper is installed and loaded.  There is a fix for that issue currently in 15.8 Preview 4.  Would be interested to see if this is what you are running into.

**Comment by danijel-peric** [comment]
I have resharper installed, will try to disable it and check

**Comment by danijel-peric** [comment]
disabling resharper fixes the issue, so it looks like we will need to wait for 15.8 version, i have 15.7.4 installed
