### ISSUE TITLE
Rollback of Manual Application Upgrade gets stuck in RollbackInProgress

### ISSUE THREAD

**Issue by AaronRM** [Azure/service-fabric-issues#1084]
### Environment
This issue is present on SF 6.2.274.9494 running either locally or Azure. Attempted with both 5-Node and 7-Node clusters.

### Repro Steps
1. Create a new Service Fabric Application (e.g. a new SF app with a single Stateless Service)
2. Build both 1.0.0 and 2.0.0 versions of the app (via Edit Manifest Versions)
3. Copy and register both versions of the application to a 5-node cluster (via the `Copy-ServiceFabricApplicationPackage` and `Register-ServiceFabricApplicationType` Powershell cmdlets)
4. Create an instance of the 1.0.0 app type and wait for it to deploy successfully.
5. From Powershell, initiate [a manual application upgrade](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#manual-upgrade-mode) via the following command: `Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/MyApp -ApplicationTypeVersion 2.0.0 -UnmonitoredManual`
6. Manually upgrade an additional 1-2 upgrade domains via `Resume-ServiceFabricApplicationUpgrade -ApplicationName fabric:/MyApp -UpgradeDomainName <n>`
7. After 2-3 upgrade domains have deployed successfully, initiate [a rollback of the application upgrade](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#rolling-back-application-upgrades) via `Start-ServiceFabricApplicationRollback -ApplicationName fabric:/MyApp`

### Issue
Eventually the application upgrade rollback will get 'stuck' with the Upgrade State set to RollingBackInProgress. Some of the upgrade domains will be marked with Complete and one with be InProgress. As far as I know, the only way out of this state is deleting the Application instance from the cluster.

**Comment by masnider** [comment]
What is it waiting for?

https://blogs.msdn.microsoft.com/huizhu/2018/05/04/troubleshoot-service-fabric-cluster-upgrade-issues/

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-troubleshooting

**Comment by alexwun** [comment]
Does the issue still repro on version 6.2.279 or later? There was a bug where unmonitored manual rollbacks could get stuck that was fixed starting in that version.

**Comment by AaronRM** [comment]
@masnider I'm not sure what it's waiting for exactly. The output from `Get-ServiceFabricApplicationUpgrade` doesn't show anything useful other than the UpgradeState is 'RollingBackInProgress'.

@alexwun Thanks! I upgraded my local SF cluster to the latest version (6.2.283.9494), and I'm still seeing similar behavior (although the rollback operation gets farther this time...all the upgrade domains that were 'Completed' on the initial application upgrade are getting rolled back, but the remaining ones [which the rollback should have nothing to do for] continue to be marked as Pending).

For example, I was trying out upgrading this example app from version 1.0.1 => 2.0.0 with UnmonitoredManual mode. I allowed the upgrade to complete for upgrade domains 0-2 and then issued `Start-ServiceFabricApplicationRollback`. I then see SF starting the rollback by deploying version 1.0.1 to domains 0, then 1, then 2. At that point, it gets "stuck" in Upgrade state RollingBackInProgress with domains 0-2 marked "complete" and 3-4 marked as "Pending". The rollback should be a no-op for domains 3-4 since the upgrade was never done for those upgrade domains:

![image](https://user-images.githubusercontent.com/437496/40933383-2c4a0164-67e6-11e8-8322-47a5469b0011.png)

![image](https://user-images.githubusercontent.com/437496/40933428-474d9aa2-67e6-11e8-9bd8-b2bf25bb3068.png)

In the screenshots above, I notice that the 'Current Upgrade Domain Progress' (3) is marked as Failure Reason = 'Interrupted'. Maybe the rollback logic is getting confused on Upgrade domain 3 as being in some sort of error state because the upgrade was interrupted?

**Comment by alexwun** [comment]
Interrupted just means that the upgrade was interrupted with an explicit rollback request (as opposed to rolling back automatically due to health policy). Do either Resume-ServiceFabricApplicationUpgrade or Update-ServiceFabricApplicationUpgrade -UpgradeMode UnmonitoredAuto unblock the rollback?

https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-failurereason

https://docs.microsoft.com/en-us/powershell/module/servicefabric/resume-servicefabricapplicationupgrade?view=azureservicefabricps

https://docs.microsoft.com/en-us/powershell/module/servicefabric/update-servicefabricapplicationupgrade?view=azureservicefabricps

**Comment by alexwun** [comment]
Do you still have the cluster around? With the cluster resource ID (not the cluster ID) and region (both accessible in the properties of the Service Fabric cluster resource), we can take a look at the logs and see what happened here.

**Comment by AaronRM** [comment]
**Cluster Resource ID**: /subscriptions/b5582b30-cbe9-44dc-9949-a071ed89ecbd/resourcegroups/prs-dev2/providers/Microsoft.ServiceFabric/clusters/prs-dev2
**Region**: West US 2

Thanks!

**Comment by masnider** [comment]
Hi! This was fixed and was rolled out as a part of our 6.2 release, so should be everywhere by now. I'm going to close down this issue. If you see it again after getting the cluster up to 6.2 or greater, please reopen and we can see what's up. If you have any other problems or questions, please feel free to create more issues. Thanks for reporting!
