### ISSUE TITLE
Application services not starting - KeyNotFoundException (AspNetCore 1.1)

### ISSUE THREAD

**Issue by mattfrear** [Azure/service-fabric-issues#1086]
A number of application services in our Service Fabric cluster have started failing since yesterday. They crash when starting up.

On one service I had upgraded its .sfproj files to 2.1 (from 1.6), by following the prompts in Visual Studio (15.7.1) when opening the solution. After the upgrade the below exception starts occurring. Undoing the commit, i.e. rolling back the .sfproj ProjectVersion to 1.6 and (Microsoft.VisualStudio.Azure.Fabric.MSBuild 1.6.0) and the issue goes away.

Another service had its .sfproj updated to 2.0 about a month ago, was running fine, and now no longer starts up after being deployed yesterday.

The Azure SF cluster runtime version is set to automatically upgrade, and is currently on `6.2.274.9494`.

```
System.Collections.Generic.KeyNotFoundException (-2146232969)
The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.d__4.MoveNext()
   at System.Linq.Enumerable.d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Nhh.Core.Web.TestableWebStartupBase.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()
```

**Comment by mattfrear** [comment]
I haven't yet figured out the root cause but I have figured out a workaround.
Our services that work fine use
- .sfproj ProjectVersion 1.6
- .NET Framework 4.6
- ASP.NET Core 1.1.1

or 
- .sfproj ProjectVersion 2.0 or 2.1
- .NET Framework 4.6.2
- ASP.NET Core 2.0.0

Our services that fail to start are using 
- .sfproj ProjectVersion 2.0 or 2.1
- .NET Framework 4.6
- ASP.NET Core 1.1.1

The workaround then is to upgrade all services to .NET Framework to 4.6.2 and ASP.NET Core 2.0.0.

N.B. It might well be the case that the upgrade to ASP.NET Core 2.0.0 is all that's needed (i.e. no need to target .NET Framework 4.6.2), but due to the way our internal NuGet packages work it is easier for me to upgrade both at once.

This however is still an issue as it is time consuming to have to upgrade all of our services, and we went from a working system to a broken one, without changing anything on our end.

**Comment by samiam236** [comment]
@mattfrear have you found a root cause for this yet? We are experiencing this as well. Our failing service is also on ASP.NET Core 1.1. I'm working on an upgrade, but it'd be nice to know if there was a quicker short-term fix to get our releases working again.

**Comment by mattfrear** [comment]
Nope, I haven't figured out the root cause yet. It feels like someone in Microsoft either upgraded something in Azure Service Fabric, or maybe they upgraded something in the VSTS build process, and that has broken it. I've had to upgrade 4 of our services to .NET Core 2.0 to get them to work.

**Comment by samiam236** [comment]
Good point. I hadn't thought about a VSTS change being a possible culprit.

**Comment by cdowneyM3** [comment]
I'm seeing similar issues on my Azure website, my stack trace looks the same once you start at "at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()" and go up.

I'm convinced this is a VSTS issue - of some sort.  I created new build from an old known good commit and published that build.  My azure website didn't start up on the new build.  I have an old build from the same commit that I can publish and the site works fine.

I'm going to be testing a few things and I'll update if i find a fix.

**Comment by mattfrear** [comment]
Yep, I noticed the same thing earlier too. Created a new build from an old commit that works, and it fails. But the old build from the same commit works.

**Comment by cdowneyM3** [comment]
Some things I tried 

- I tried updating my donet publish step in my VSTS build from 1.* to 2.* and that didn't fix the issue.
- I deployed manually from Visual studio (I had relearn out to do that, because we are using slots and that changes the process from what I'm used to).  **And that gave me a working site**.  I had to update my app settings manually, because our CI pipeline normally does that for us.

Another team member was in the middle of updating to a newer version of .net, so we will go through that process and see if we can get the deployment working again.

**Comment by alemag1986** [comment]
Hey guys, same thing here! We are having the same issue since last Monday. All builds and releases previous May 26th work fine but not after that date; actually every built after the that fails on production, throwing an exception on Startup method: 

```
KeyNotFoundException: The given key was not present in the dictionary.
System.ThrowHelper.ThrowKeyNotFoundException()
System.Collections.Generic.Dictionary.get_Item(TKey key)
Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider+CandidateResolver.ComputeClassification(string dependency)
Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider+CandidateResolver.ComputeClassification(string dependency)
Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider+CandidateResolver.ComputeClassification(string dependency)
Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider+CandidateResolver+<GetCandidates>d__4.MoveNext()
System.Linq.Enumerable+<SelectManyIterator>d__17.MoveNext()
System.Linq.Enumerable+WhereSelectEnumerableIterator.MoveNext()
Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action<MvcOptions> setupAction)
MVC.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

And this is from the log stream:

```
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModule</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://FRCoreNemesisAS:80/</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
```
We are doing direct builds from Visual Studio, that's so far the only remedy.
Tried: 
- changing build arguments: different VS versions, 
- creating build and release definition
- updating nuget libraries to newest version when possible
- about to create a new WebApp to see if the issue is related

**Comment by dvanherten** [comment]
Having the same issue, but locally. Had a working 1.1 project early last week.

Trying now with no changes, it doesn't run anymore. Only substantial thing I did that I can think was install the Core 2.1 SDK and upgrade VS to latest on Friday for a different project.

**Comment by dvanherten** [comment]
@cdowneyM3 @alemag1986 

Have you installed .Net Core 2.1 on your local machines? Did the build agents you use have it? Just wondering if that's the difference. 

Not related to Service Fabric for me, but I'm having the exact same problem on my local and that install is the only significant change I've made recently that I can think of.

**Comment by alemag1986** [comment]
Yeah, we are not using Fabric at all. We don't have .net core 2.1 installed locally, sorry just me (the preview version for a while now), and not in the build agents. 
We are using 4.6.2  and ASP.NET Core 1.1.x

**Comment by samiam236** [comment]
Not really new info at this point, but upgrading our ASP.NET Core 1.1 project to 2.0 fixed the problem for us, as it has for everyone above.

**Comment by masnider** [comment]
Looks like this is (or at least related to) https://github.com/aspnet/Home/issues/3132 ?

**Comment by sagoo33** [comment]
We have the same issue,  a .net core 1.1 full framework, stopped working around 26th may, works fine when deployed direct from vs2017. I've found that when downloading the artifact from vsts and replacing the .deps.json file with the locally built file, the site will run. I think something has changed on vsts.

**Comment by cdowneyM3** [comment]
So we ended up moving to AspNetCore 2.1 and that fixed our issue.

**Comment by alemag1986** [comment]
So,
this 3 lines in the startup solved the issue:
```
var manager = new ApplicationPartManager();
manager.ApplicationParts.Add(new AssemblyPart(typeof(Startup).Assembly));
services.AddSingleton(manager);

services.AddMvc( options => .......
```

More info here: 
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.1

**Comment by mattfrear** [comment]
Thanks @alemag1986 and @masnider for the links.

It seems that the comment here https://github.com/aspnet/Home/issues/3132#issuecomment-388082725 by @pranavkm has 3 possible fixes, one of which is upgrading to ASP.NET Core 2.0 which is what I found to work. His `global.json` fix is probably the simplest option.

Will close this issue since it's not related to Service Fabric.

**Comment by CANUSA** [comment]
So upgrading to 2.0 is not currently an option for us. This seems like a pretty huge breaking change. I just spent an entire night and morning wondering why my deployments were failing. We may have multiple projects that fail VSTS builds now, need to check...

**Comment by mattfrear** [comment]
@CANUSA Yeah so if you read my last message there are 3 possible workarounds, so you probably won't need to upgrade to 2.0.

**Comment by CANUSA** [comment]
Yep, I implemented a workaround, thanks for that! A workaround in my mind is not a fix however. The underlying problem needs to be addressed.

**Comment by mattfrear** [comment]
> A workaround in my mind is not a fix however. The underlying problem needs to be addressed.

I totally agree.

**Comment by ericbrunner** [comment]
@CANUSA Try publish form VS2017 v15.7.3 . It worked for my as a temporary workaround. I filed a report in VSTS forum: [KeyNotFoundException](https://developercommunity.visualstudio.com/content/problem/274416/keynotfoundexception.html?childToView=274417#comment-274417)

**Comment by RobertoPrevato** [comment]
The exact same problem is affecting Azure Web App Service. Recently I tried to redeploy the DEV environment of an application I didn't touch in months, and I was getting the same error at startup. I updated the application to ASP.NET Core 2.x and it now works, I need to deploy an hotfix to PROD.

It's the second time that one of my deployment jobs stop working due to updates in Microsoft infrastructure.

Lesson learnt:
* I need VSTS scheduled job that tries to redeploy DEV environment every week or every day, even if I am not working on a given application for months, because I am busy working on other projects

**Comment by ericbrunner** [comment]
@RobertoPrevato Try .NET Core Tool installer task before building your app in VSTS for put a global.json file in your sln/project dir with the .NET Core SDK you are targeting. I took the .NET Core Tool task in my VSTS build config as first task and worked again.

**Comment by RobertoPrevato** [comment]
Thanks, Eric! I am actually using 4.61 Framework with ASP.NET Core web framework for this application, I am not sure if NET Core SDK would help in my case. But I already updated to ASP.NET Core 2.x framework (still targeting net461) and it works, like @mattfrear said.

**Comment by ericbrunner** [comment]
@RobertoPrevato I use the TargetFramework net461 , too. But the project is a netcore 1.0.4 sdk project.
The net461 is only the runtime. The second is the .Net Core SDK with which it is built. The issue on VSTS currently is that they build all .Net Core Apps with the latest stable .Net Core 2.1 SDK which causes that issue. Specifying that .Net Core 1.0.4 SDK explicitely in global.json or with the VSTS task .Net Core Tool you are on the bright side of life;-)

**Comment by RobertoPrevato** [comment]
Thanks again, @ericbrunner, now everything's clear!
