### ISSUE TITLE
Improve The Error Message for: The Settings section with name 'Blah' in ConfigOverride 'Config' is invalid. Cannot find a section with the same name.

### ISSUE THREAD

**Issue by spottedmahn** [Azure/service-fabric-issues#1091]
I'm trying to add a new config section to our app configuration and it is failing:

>Register-ServiceFabricApplicationType : The Settings section with name 'Blah' in ConfigOverride 
>'Config' is invalid. Cannot find a section with the same name.

Nothing fancy, done this many times before but I'm doing something wrong I don't see.

```xml
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="eBenefits.OrganizationDomainType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
	<Parameters>
		<Parameter Name="Parameter1" DefaultValue="" />
		<Parameter Name="Parameter2" DefaultValue="" />
		<Parameter Name="Parameter3" DefaultValue="" />
	</Parameters>
	<ConfigOverrides>
		<ConfigOverride Name="Config">
			<Settings>
	                         ...
				<Section Name="Blah">
					<Parameter Name="Parameter1" Value="[Parameter1]" />
					<Parameter Name="Parameter2" Value="[Parameter1]" />
					<Parameter Name="Parameter3" Value="[Parameter1]" />
				</Section>
			</Settings>
		</ConfigOverride>
	</ConfigOverrides>
        ...
</ApplicationManifest>
```

>Copying application to image store...
>Upload to Image Store succeeded
>Registering application type...
>Register-ServiceFabricApplicationType : The Settings section with name 'RegistrationEmailOptions' in ConfigOverride 
>'Config' is invalid. Cannot find a section with the same name.
>FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\a2b68765-272d-4477-aad2-f3d4818365c7\ApplicationManifest.xml
>At C:\Program Files\Microsoft SDKs\Service 
>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:251 char:9
>+         Register-ServiceFabricApplicationType -ApplicationPathInImage ...
>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic 
>   eFabricApplicationType], FabricException
>    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp 
>   e
> 
>Finished executing script 'Deploy-FabricApplication.ps1'.
>Time elapsed: 00:00:39.7598137
>The PowerShell script failed to execute.

**Comment by spottedmahn** [comment]
⭐ Turns out I forgot to define it in `My-Service\PackageRoot\Config\Settings.xml`

---

Can we improve the error message here?  Something more self-documenting?  Something that directs you to where the problem could?

Maybe:

> The Settings section with name 'Blah' in ConfigOverride 'Config' is invalid. Cannot find a section with the same name.  Please check your `PackageRoot\Config\Settings.xml` and ensure you have defined it there.

I'm not fan of the following b/c **to me**, it says there is something wrong with it.  But there isn't.  The problem is in another file.
>The Settings section with name 'Blah' in ConfigOverride 'Config' is invalid.

**Comment by spottedmahn** [comment]
Thoughts? 💭

**Comment by masnider** [comment]
Seems reasonable that this could be improved. We're creating a tracking issue for this. We've already got similar improvements in the pipeline for Test-ServiceFabricApplication, so this shouldn't be too hard to add.

**Comment by oanapl** [comment]
We have made many error message improvements, including this scenario. The messages should now include more details. Here are some examples:

```csharp
The Settings section with name '{0}' in ConfigOverride '{1}' for service manifest '{2}' is invalid. Cannot find a section with the same name. Check that it is defined in your Settings.xml file.

The override parameter with name '{0}' in section '{1}' for service manifest '{2}' is invalid. Cannot find parameter with the same name to override. Check that it is defined in your Settings.xml file.
```

**Comment by spottedmahn** [comment]
awesome, thanks! 👏👏
