### ISSUE TITLE
Incorrect value of X509StoreName removes attribute after deployment

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#1092]
After deploying using VS 2017 the whole attribute is removed from the element in application manifest if its value can't be parsed, including this:

    <EndpointCertificate X509StoreName="My"

and only this is persisted:

    <EndpointCertificate X509StoreName="MY"

**Comment by dbreshears** [comment]
@abatishchev,    Can you try the following as see if it works around the issue 

Unload and edit the .sfproj and add this property to the Globals property group.  Save, close and reload the solution.

`<UpdateServiceFabricApplicationManifestEnabled>false</UpdateServiceFabricApplicationManifestEnabled`

**Comment by abatishchev** [comment]
Yes, this is a nice workaround, thanks. What I'd like to have in long-run: Allow My as valid value. And do not remove attributes with invalid values. Fail the build instead.

**Comment by dbreshears** [comment]
Can you clarify what was being removed, both strings above are identical.    If we can get a repro from it I can log a bug here for investigation.   It is probably failing to deserialize from the XML for some reason.

**Comment by abatishchev** [comment]
If I have this:

    <EndpointCertificate X509StoreName="My" X509FindValue="[WebApiService_EndpointThumbprint]" Name="WebApiServiceEndpointCert" />

Then it'll become this:

    <EndpointCertificate X509FindValue="[WebApiService_EndpointThumbprint]" Name="WebApiServiceEndpointCert" />

In other words, the whole attribute ` X509StoreName="My"` is getting removed.

**Comment by amanbha** [comment]
@abatishchev "My" is default value for "X509StoreName" attribute in the schema, we use xml deserialization and serialization to update the manifests during the build. Schema is available [here](https://github.com/Microsoft/service-fabric/blob/master/src/prod/src/ServiceModel/xsd/ServiceFabricServiceModel.xsd#L268) This default value is not written during serialization, I understand that value is not kept here, but there is no correctness issue.

**Comment by abatishchev** [comment]
The schema says "My" but "My" will be removed. Why? And only "MY" will stay. Again why?

**Comment by amanbha** [comment]
As I mentioned in the previous respinse, default values are removed and "My" is default value.

**Comment by abatishchev** [comment]
So you're saying that MY stays because it's not a default value? Can everything stay, like it does in all other parts of application/service manifest, any other SF settings, or anywhere else in .NET or XML world? What's the reason behind it's removal? Even it's default I'd expect it to stay.

**Comment by amanbha** [comment]
Tooling modifies the application  manifest to ensure that only required service manifets are kept, it uses xml serialization/deserialization for this. I understand the confusion  it causes but there is no correctness issue, there is a work item to track this, but this is low priority as compared to other work items for the tram.

**Comment by abatishchev** [comment]
I see, fair enough. Closing this then.
Meanwhile can you please send me a link to the work item to alexbat@microsoft.com? Thanks!

**Comment by amanbha** [comment]
Sure thing!
