### ISSUE TITLE
Container is constantly recreated

### ISSUE THREAD

**Issue by lkts** [Azure/service-fabric-issues#1093]
I am running Windows container based on nanoserver on Service Fabric.

I am constantly seeing error `There was an error during CodePackage activation.The service host terminated with exit code:7148` on different nodes.

Event logs contain the following warnings:
`OnAbort called for HostId=a767a7b7-b127-4e43-ac1d-9cac93f0af40, ServicePackageInstanceId=MyApp_App130:apiPkg@bb40f8f8-5562-405b-bf6c-7942e89ff12f@f9ece59f-5248-40b7-a267-63b6c9a6284e.`

`MainEntryPoint:EntryPointDescription { EntryPointType = ExeExecutable = ExeEntryPointDescription { Program = , Arguments =  -type:fabricType, WorkingFolder = Work, PeriodicIntervalInSeconds = 0 ConsoleRedirectionEnabled = false ConsoleRedirectionFileRetentionCount = 2 ConsoleRedirectionFileMaxSizeInKb = 20480 }} terminated with exitcode 7148. CodePackageInstanceIdentifier { ServicePackageInstanceId = MyApp_App130:apiPkg@bb40f8f8-5562-405b-bf6c-7942e89ff12f@f9ece59f-5248-40b7-a267-63b6c9a6284e, CodePackageName = FabricTypeHost-DF95B56E-29EE-4418-B124-061740D7282C }:131723235024529890`

`CodePackage cannot transition to Setup_Initializing state. ErrorCode=FABRIC_E_INVALID_OPERATION. Current State=Deactivating. CodePackageInstanceIdentifier { ServicePackageInstanceId = MyApp_App130:apiPkg@bb40f8f8-5562-405b-bf6c-7942e89ff12f@f9ece59f-5248-40b7-a267-63b6c9a6284e, CodePackageName = Code }:131723235024529889`

`Could not restart termininated entry point because of error FABRIC_E_INVALID_OPERATION, retry scheduled after  10.000 `

and some `UnregisterFabricRuntime: ErrorCode=FABRIC_E_OBJECT_CLOSED`

**Comment by cod7alex** [comment]
@masnider yes, i am sure it was due to healthcheck

**Comment by masnider** [comment]
@cod7alex can you try something to confirm what's going on here? Get it into this state where things are failing but you're not seeing any more information. Then expand the Nodes, and drill down into a node you know is having problems. There's a suspicion that this is a health check that's getting reported at a "Code Package" level, which then isn't easily viewable at the service level.

**Comment by cod7alex** [comment]
I see the same message on Node level 
> There was an error during CodePackage activation.The service host terminated with exit code:7148

**Comment by masnider** [comment]
Further down, there should be an individual report at the code package level (within the node).
@harahma, @mani-ramaswamy, @RajeetN any ideas in the meantime for how to get more info?

**Comment by cod7alex** [comment]
@harahma isn't my first post sufficient ?

**Comment by masnider** [comment]
We've improved both docker health check integration as well as general health errors and information available within SF when these types of errors happen. Closing this for now. Please reopen if there are other errors or if the information you see on a more recent release still isn't helpful and we can continue to improve.
