### ISSUE TITLE
Is resetting Administrator password on service node compliant with PCI? 

### ISSUE THREAD

**Issue by mkarlsson** [Azure/service-fabric-issues#1094]
Can Azure subscription owners reset Admin password for Service Fabric clusters? Thinking this would override PCI compliance which are generally set by Group policy objects?  I.e. Group policy no longer important if you can override it from Azure owner/contributor?

**Comment by masnider** [comment]
Hi @mkarlsson 

There's no such thing as an admin password for SF clusters. You're probably thinking about the password you have to set on the VMs for the VM Scale Set. SF doesn't control this and has no restrictions or requirements on it, so I don't know how to answer your question, unfortunately.  I would move your question over to https://github.com/Azure/vm-scale-sets/issues Once you have, can you close this one, please?

Thanks and sorry we're unable to help here.

**Comment by mkarlsson** [comment]
Hi @masnider ,
Thanks for your reply. Seems I was misinformed about the SF admin account. I will close the issue. 
Regards
Magnus
