### ISSUE TITLE
Error (0x80071D0A) trying to run Chaos sample on local cluster.

### ISSUE THREAD

**Issue by Scythen** [Azure/service-fabric-issues#1096]
Hello,

I am trying to use the Service Fabric TestManager to simulate issues on my local cluster. I have copied the sample code from here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-controlled-chaos and attempted to execute it against my local cluster. This results in the error: 
COMException: Exception from HRESULT: 0x80071D0A

I am developing in Visual Studio 2017 Preview running as administrator and have Service Fabric SDK 3.1.283 installed.

I am unable to find any information on the error code.

Regards,
Eli

**Comment by Alexandr63** [comment]
Possibly it help to you
https://stackoverflow.com/questions/42269032/startpartitiondatalossasync-throws-fabricexception

**Comment by likevi-MSFT** [comment]
@MZDN Which version of Service fabric do you have installed? Is Fault Analysis Service running in the cluster?

**Comment by MZDN** [comment]
![sfcluster-version](https://user-images.githubusercontent.com/16664882/56195102-8fe18c00-6034-11e9-8dc2-07a4f13e3d7d.png)

**Comment by likevi-MSFT** [comment]
@MZDN  do you see a FabricFAS.exe running?

**Comment by MZDN** [comment]
@likevi-MSFT no, unfortunately. I hope this is the right location:
`C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code`

**Comment by likevi-MSFT** [comment]
@MZDN Is your local cluster a one node cluster? If so, FAS will not be running and Chaos won't work. Switch to a 3 or 5 node cluster.
