### ISSUE TITLE
Static singleton in Service Fabric stateful/stateless service

### ISSUE THREAD

**Issue by UnProgrammatore** [Azure/service-fabric-issues#1098]
We are developing an application using service fabric.
We need to use a third parties SDK which offers a static singleton instance of the object it uses for basically everything. Since the SDK is not developed by us, we cannot change this, and not using this SDK is out of the question.
We are aware that, by default, service fabric can use the same executable to build different instances of a service, and we are also aware that this behavior can be altered through configuration. That said, we have no way (short of manually restarting the executable on the host machine) to actually get the instance to be recreated (because the powershell commands to restart instances and partitions don't actually restart the executable, they just restart the service class). So, should the third party ask us to restart our executable to fix an hypothetical issue in production, we would have no way to safely do that.
Is there a suggested solution to this?

Thank you in advance.

**Comment by masnider** [comment]
Restart-ServiceFabricDeployedCodePackage should be what you're looking for? Or what does it not accomplish today that you're trying to do or avoid?

**Comment by UnProgrammatore** [comment]
Does the "Restart-ServiceFabricDeployedCodePackage" command abruptly stop the executable or does it cancel the cancellation token of the RunAsync method the same way Start-ServiceFabricPartitionRestart does?

**Comment by masnider** [comment]
Well, you need to restart the process, and that's the command that does it :) That one would close the process (Ctrl+C) so if you have a handler for that (which usually is a good idea) then you can drain out any work before allowing it to exit. If you're checking health before you do this, then you should be fine. 

If you really need to march the services through their full shutdown sequence, you can combine could combine Restart-ServiceFabricDeployedCodePackage with Disable-ServiceFabricNode -Intent Restart. Disabling the node will shut things down/move things elsewhere if necessary, at which point you can just bounce the process in question and then Enable-ServiceFabricNode.

**Comment by UnProgrammatore** [comment]
Very well, this seems like a good solution. Not very elegant, but it will do in case of emergency. Thank you very much.
