### ISSUE TITLE
What does the "Restart" option do on nodes?

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#110]
What does the "Restart" option on the node do? I ran it on a test cluster and it appears to spike the CPU on all services for a short time, and then nothing else happens:

![image](https://cloud.githubusercontent.com/assets/309938/21407042/fa3772be-c7ce-11e6-807d-13c7fb7c872e.png)

**Comment by aarondandy** [comment]
Also note that the docs don't mention this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-visualizing-your-cluster

**Comment by masnider** [comment]
https://docs.microsoft.com/en-us/powershell/servicefabric/vlatest/Restart-ServiceFabricNode

**Comment by csu-msft** [comment]
Closing this issue as [the docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-visualizing-your-cluster) now describe this option and the table formatting has been fixed.
