### ISSUE TITLE
Copy-ServiceFabricApplicationPackage hangs our times out. Local Cluster Version 6.2.274.9494

### ISSUE THREAD

**Issue by groogiam** [Azure/service-fabric-issues#1100]
The Copy-ServiceFabricApplicationPackage takes appears to not be working correctly in 6.2.274.9494. I am trying to upload a 190 MB package which is taking at least 30 minutes when it does not time out.

Using -showProgress seems to show long delays between content being uploaded.

**Comment by leikong** [comment]
@Oana Platon<mailto:Oana.Platon@microsoft.com>
I can help the customer get rid of the warning, but I don’t believe such warning will not cause hanging.

**Comment by oanapl** [comment]
One thing to check for slow copy is that [the cluster and the client machine have exclusions for antivirus set](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#environment-setup). We have seen very large copy times when that is not properly set. 
Another thing to check is the health of the fabric:/System/ImageStoreService and the other system services in SFX. Is everything green?

**Comment by groogiam** [comment]
It appears something was not right with one of the machine in the cluster. The machine completely crashed when we attempted to update Windows. However it is still worrisome that a malfunctioning machine can prevent code from being deployed to the cluster.
