### ISSUE TITLE
Azure Timer functions + Azure service fabric

### ISSUE THREAD

**Issue by NISHANTH2066** [Azure/service-fabric-issues#1101]
Is there any way to call some service fabric function when the timer is triggered in Azure Timer functions.

Something like service remoting?

**Comment by NISHANTH2066** [comment]
It seems that I have to write some listeners, Actually, I want something like Azure Timer function in Azure service fabric, I want to do some stuff say every ten minutes, Azure timer function allows me to do that effectively instead of busy waiting, Is there something of that kind in Azure Service fabric too?

Creating a listener is as good as doing that and sleep for rest of the time.

**Comment by ashishnegi** [comment]
@NISHANTH2066 see, if service fabric actors [reminders/timers](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-timers-reminders) help you.

**Comment by raunakpandya** [comment]
Closing the issue. You can open it again if you still have related question.
