### ISSUE TITLE
Cannot Remove Failed Node on Local Cluster

### ISSUE THREAD

**Issue by groogiam** [Azure/service-fabric-issues#1107]
I am attempting to remove a node on standalone cluster based on your documentation.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes

The node in question has failed and is no longer on the network. When running the cluster config upgrade to remove a failed node, the upgrade hangs due to the health checks.  I attempted to disable the health checks with
`Update-ServiceFabricClusterUpgrade -EnableDeltaHealthEvaluation $False -MaxPercentUnhealthyNodes 50 -MaxPercentDeltaUnhealthyNodes 50`

 and the upgrade completes for all upgrade domains at this point but then just hangs in RollingForwardCompleted status.

Is there some other documentation on deleting a failed node? It seems that this use case is not well supported which is surprising as this can be a relatively common occurrence with larger clusters.

**Comment by jkochhar** [comment]
When you say it hangs at RollingforwardCompleted.. is that what you see in SFX? Are you able to share logs from the cluster?

**Comment by groogiam** [comment]
It looks like the operation completed but the node still showed in the explorer. The remove node functionality did not appear to work if the node was completely offline. In the end I was forced to delete and recreate the whole cluster so I'm not sure I have the logs. Where would these logs be located so I can check if I still have them?

**Comment by jkochhar** [comment]
In your json config you usually set your log root (eg. C:\programdata\sf\) like below. Its a bunch of .etl files. If you see it again, feel free to share the logs and I can take a look. 

"fabricSettings": [
        {
          "name": "Setup",
          "parameters": [
            {
                "name": "FabricDataRoot",
                "value": "C:\\ProgramData\\SF"
            },
            {
                "name": "FabricLogRoot",
                "value": "C:\\ProgramData\\SF\\Log"
            }
          ]
        }
      ]

**Comment by groogiam** [comment]
OK, just to clarify. The procedure referenced in my original post should work to remove a node  that is completely off the network? I just want to make sure I was following the correct procedure.

**Comment by jkochhar** [comment]
Yes the link is correct. However the link mentions using Start-ServiceFabricClusterConfigurationUpgrade after updating the config to remove node while you have mentioned Update-ServiceFabricClusterUpgrade in your comment. Did you use the Start-ServiceFabricClusterConfigurationUpgrade?

**Comment by groogiam** [comment]
Hmm... Its hard to say at this point. I would have probably copied the command from the linked page when attempting, but I can't say for sure. If I used the wrong command that would explain why it did not work. I'm gonna close the issue for now. Next time a node fails I'll give it another shot and if I still can't get it to work using the correct command, I'll reopen the issue. Thanks for your help.
