### ISSUE TITLE
Getting Publish-UpgradedServiceFabricApplication : Upgrade was Rolled back error when adding resource governance configuration in applicationmanifest.xml file

### ISSUE THREAD

**Issue by Rakesh201180** [Azure/service-fabric-issues#1109]
We are deploying our application to azure service fabric cluster using VSTS and Octopus build
After adding resource governance parameters. 

```
<Policies>
      <ContainerHostPolicies CodePackageRef="Code" Isolation="default">
        <RepositoryCredentials AccountName="#{ContainerRegistry_AccountName}" Password="#{ContainerRegistry_Password}" PasswordEncrypted="false"/>
        <NetworkConfig NetworkType="Open"/>
      </ContainerHostPolicies>
      <ServicePackageResourceGovernancePolicy CpuCores="1"/>
      <ResourceGovernancePolicy CodePackageRef="Code" CpuShares="1024" MemoryReservationInMB="1024" />
    </Policies>
```
We are getting below error during build.

**Publish-UpgradedServiceFabricApplication : Upgrade was Rolled back.**

Please let us know if any issue is there related to configuration.

we are following below link for configuration

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-resource-governance

Thanks
Rakesh

**Comment by Rakesh201180** [comment]
Any update

**Comment by masnider** [comment]
During the upgrade if it's rolling back there should be health errors somewhere that provide more information. Can you kick off the upgrade and then watch for those health errors?

**Comment by masnider** [comment]
@Rakesh201180 any chance you can provide more information?

**Comment by Rakesh201180** [comment]
I am able rectify error ,We have only One code package in our application so we are using 

`<ServicePackageResourceGovernancePolicy CpuCores="1"/> ` only

as per our requirement we no need to use <ResourceGovernancePolicy> because it will work better when we have more then one code package to divide CPUshare.

Thanks
Rakesh
