### ISSUE TITLE
How Service Fabric supposed to coexist with docker service?

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#1112]
Hello,

I can see that Service Fabric runtime launching `dockerd.exe` while there is also a service called `DockerD` installed by default when you install `docker` package from `DockerMsftProvider` by default. So OS have 2 incompatible services trying to launch the same executable. What is guidance to avoid this situation?

**Comment by harahma** [comment]
When SF comes up on a node, it first stops DockerD running as a service and then starts it as a child process of SF and then monitors it. If DockerD goes down for any reason, SF will again start it. This is done to ensure that internal state of SF about containers running on node remains synchronized with actual container running on the machine.

For debugging scenarios (not recommended in production) there is a configuration which can be enabled such that SF will skip trying to manage DockerD on the machine and simply assume that it is up and running.

To enable debugging scenario you should set 'SkipDockerProcessManagement' to 'true' in 'Hosting' section under fabricsettings in the ARM template as show [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings#customize-cluster-settings-using-resource-manager-templates). Following is json snippet:
 {
   "fabricSettings":[
      {
         "name":"Hosting",
         "parameters":[
            {
               "name":"SkipDockerProcessManagement",
               "value":"true"
            }
         ]
      }
   ]
}

**Comment by artisticcheese** [comment]
Is it possible it it's interfering with docker config under programdata? Seeing SF doing some strange things with docker images outside of what is specified to be a `data-root`. 
See https://github.com/Azure/service-fabric-issues/issues/1122

**Comment by harahma** [comment]
SF does not touch daemon.json but it does set DOCKER_TMPDIR environment variable. This is done to avoid piling up partially downloaded container image file for cases of interrupted downloads. Since windows container images are large in size and the default C: drive on provisioned VMs are small, in rare cases DOCKER_TMPDIR may eat up the significant disk size causing other side effects.
