### ISSUE TITLE
Unable to install an on premise cluster because of file share requirement

### ISSUE THREAD

**Issue by RandyWilkinson** [Azure/service-fabric-issues#1114]
I have a simple one node on premise cluster that will not startup cleanly. I continue to get ImageStoreService errors as follows:

![image](https://user-images.githubusercontent.com/15603092/41486293-ccc5fdae-7098-11e8-8981-754c1f2b2073.png)

After many days of investigation and experimentation I discovered the following event log entry:
```
ProcessActivationManager
SetupShare: Failed to create share. LocalFullPath:C:\ProgramData\SF\vm0\Fabric\work\Applications\__FabricSystem_App4294967295\work\Store, ShareName:StoreShare_vm0, AccessMask:2684354560, Error:E_ACCESSDENIED

```
Trying to share this folder directly revealed that we have a corporate level group policy in place that prevents the creation of file shares for security reasons. I believe this is the reason I can't get the service fabric cluster to start. 

Has anyone encountered this before and am I on the right track? Is there a way to configure this service to not use an SMB file share?

I also realized that that "Have file sharing (SMB) enabled" is on the checklist for setting up the environment, and technically the feature is enabled. But I am wondering if anyone else has had to try and install SF in such a restrictive environment?

**Comment by oanapl** [comment]
Is this cluster used for local development only? If that's the case, can you use file store based image store instead of the native image store? This is actually the default when creating local cluster, native image store is enabled when you create cluster with UseMachineName parameter.

**Comment by RandyWilkinson** [comment]
Thank you for responding so quickly, I have found a workaround for this group policy in the cluster VMs. But I think that the option of being able to use a file store without the SMB share is great, so this is only for a local cluster? This is a cluster I am setting up to use for testing in a more production like environment as I will be running some performance tests.

Just to be clear, can I use the file store based image store in a 3 node cluster for performance testing? This is ultimately what I am trying to do.

**Comment by oanapl** [comment]
No, we only recommend file store based image store for single machine (even if the cluster is multi-node, it must be on a single machine). 
FYI, we are working on removing SMB dependency for native image store, but it will take some time (a few releases).

**Comment by oanapl** [comment]
@RandyWilkinson , since you are unblocked I will close the issue. Let me know if you hit other issues / have more questions.

**Comment by RandyWilkinson** [comment]
Is there any progress on removing the SMB dependency?

**Comment by oanapl** [comment]
We are actively working on it at this point. It is not in 6.4. We will add release notes when it will be available.

**Comment by RandyWilkinson** [comment]
Great, thanks. 
It would seem that disabling SMB is becoming a popular security measure among the servers I deal with. I look forward to this feature.

**Comment by sastarkey** [comment]
Release notes from version 7.1 says the SMB dependency has been removed:
https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-1-release/ba-p/1311373

Image Store improvements

Service Fabric 7.1 uses custom transport to secure file transfer between nodes by default. The dependency on SMB file share is removed from the version 7.1. The secured SMB file shares are still existing on nodes that contains Image Store Service replica for customer's choice to opt out from default and for upgrade and downgrade to old version.
