### ISSUE TITLE
Transaction 131735920369201969 was internally aborted by the replicator as it was active for too long and blocked a checkpoint 

### ISSUE THREAD

**Issue by somesh84** [Azure/service-fabric-issues#1116]
AddUpdateOrRemovePrefix failed with exception System.Fabric.TransactionFaultedException: Transaction 131735920369201969 was internally aborted by the replicator as it was active for too long and blocked a checkpoint     at System.Fabric.Store.TStore`5.<AddOrUpdateAsync>d__223.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.ServiceFabric.Data.Collections.DistributedDictionary`2.<AddOrUpdateAsync>d__98.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Microsoft.Windows.Azure.WANDP.RouteCollectorBaseService.RouteCollectorBaseService.<AddUpdateOrRemovePrefix>d__31.MoveNext() in E:\bt\937679\repo\src\Services\RouteCollectorBaseService\RouteCollectorBaseService.cs:line 388 return error

**Comment by somesh84** [comment]
This turned out to be issue in code where object was getting modified during SetAsync. thanks

**Comment by PTC-JoshuaMatthews** [comment]
@somesh84  can you elaborate on what the issue was? I am having the same issue... looping through a collection of 100k items trying to add them to my reliable dictionary.  I don't think anything is being modified as I am simply adding item and it fails before it gets to the commit.
