### ISSUE TITLE
Start-ServiceFabricClusterConfigurationUpgrade does not work with UpgradeTimeoutSec param

### ISSUE THREAD

**Issue by qmarc** [Azure/service-fabric-issues#1119]
The first thing I will say as a gotcha is that the Start-ServiceFabricClusterConfigurationUpgrade only works if you run it from a session (RDC) in a cluster Node directly, remotely running the command does not work.

Secondly, if you provide the UpgradeTimeoutSec parameter like this:

`Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\cluster-certificate-config-v1.1.2.json' -UpgradeTimeoutSec 600`

You will find that the upgrade status does not change, and that is because nothing is performed, no information logged in the Event log etc. to suggest what might have happened. Remove the UpgradeTimeoutSec parameter and the upgrade is performed.

My cluster is version 6.2.274.9494, one version behind the latest.

**Comment by aljo-microsoft** [comment]
@qmarc 

We appreciate your feedback on the usability of our client module. If you have any issues or concerns please don't hesitate to use support or file github issues.
