### ISSUE TITLE
GetPartitionDataLossProgressAsync shows completed but it should be in progress

### ISSUE THREAD

**Issue by mflod** [Azure/service-fabric-issues#1120]
I use this code to invoke the OnDataLossAsync on a service:

```
await client.TestManager.StartPartitionDataLossAsync(
    progressId,
    PartitionSelector.PartitionIdOf(statefulService.ServiceName, servicePartition.PartitionInformation.Id),
    DataLossMode.FullDataLoss);
```

To check the progress I use following:

```
PartitionDataLossProgress progress = await client.TestManager.GetPartitionDataLossProgressAsync(progressId);

while (progress.State != TestCommandProgressState.Completed)
```

I set a breakpoint in the OnDataLossAsync and hold the process to simulate long running operations like downloading big amount of data. The problem is, that the progress state becomes completed even though the Method OnDataLossAsync is still running.

I would like to repair each partition one by one. I don't want so spam the whole server with OnDataLoss.

Is this a bug of GetParitionDataLossProgressAsync? Is there any workaround?

**Comment by raunakpandya** [comment]
Actually the state returned by GetPartitionDataLoassProgressAsync is just to indicate whether dataloss has been invoked or not. It really doesn't wait for it to get completed actually. 

The new [Backup Restore service](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster), would help you achieve this. You can trigger [restore ](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-restorepartition)of a partition one by one and monitor its [progress](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getpartitionrestoreprogress). Once restore is completed, if you would like to do any custom operation (apart from restore), you can use the callback, [OnRestoreCompletedAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.istateproviderreplica2.onrestorecompletedasync?view=azure-dotnet#Microsoft_ServiceFabric_Data_IStateProviderReplica2_OnRestoreCompletedAsync).

**Comment by mflod** [comment]
Thank you for your fast response! Maybe the documentation gave me a bit too much room for misinterpretation:

> Completed - The operation has completed successfully and is no longer running.

https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-partitiondatalossprogress

I know about the new Backup Restore Service, but its currently in the preview and I need restore functionality asp.

**Comment by raunakpandya** [comment]
Thanks. Let us know if you have any more question here.
