### ISSUE TITLE
_sf_docker_temp folder keeps growing untill all disk space is taken

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#1122]
Folder is in excess of 70GB now where SF is supposed to host single image worth about 10 GB.

![image](https://user-images.githubusercontent.com/13176884/41695417-9416aa40-74d4-11e8-8c64-b683fa084270.png)
![image](https://user-images.githubusercontent.com/13176884/41696010-75d8e82e-74d7-11e8-908a-dfbcaa779319.png)

**Comment by harahma** [comment]
@artisticcheese You should enable pruning of container images in your cluster. See [Configure the runtime to remove unused container images](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-the-runtime-to-remove-unused-container-images).

**Comment by harahma** [comment]
@artisticcheese Can you share details to access SF logs? You can email me details at harahma[at]microsoft[dot]com

**Comment by artisticcheese** [comment]
Sent via email. SF fills drive E and shuts down even though I even deactivated node form cluster manager.

**Comment by harahma** [comment]
@artisticcheese This is actually a DockerD issue where it not cleaning up its temp files. You should post a bug on their GitHub project.

To mitigate you can restart your node and SF will cleanup this folder before starting the DockerD again,
