### ISSUE TITLE
Upgrading to SF cluster of 5 nodes taking too long especially for the 5th Node

### ISSUE THREAD

**Issue by jagany** [Azure/service-fabric-issues#1123]
Hi team,
We are trying to upgrade our SF service package to SF cluster which has 5 nodes, first 4 nodes it takes around 6 to 7 mins to upgrade but for the 5th node its taking too much time some time takes more than 2hrs and sometimes even longer. May I know what could be the issue? Is that something related to a cluster or node itself? We tried to deactivate & deregister 5th node but not solved. Any pointer or know issue to know?
Thanks

**Comment by masnider** [comment]
You'll need to look at the actual upgrade status to determine what it is stuck/waiting for. Also sharing the parameters you used when starting the upgrade would help. 

You can follow the guide [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-troubleshooting).

[This guide](https://blogs.msdn.microsoft.com/huizhu/2018/05/04/troubleshoot-service-fabric-cluster-upgrade-issues/) is more about cluster upgrades, but the same patterns are useful for troubleshooting app upgrades too. 

[This page](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade) should give you a good starting point for figuring out what's up with your application, and [this page](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-parameters) will help you figure out what parameters you should set when you start an upgrade.
