### ISSUE TITLE
ImageStoreService Warning

### ISSUE THREAD

**Issue by letrungkien211** [Azure/service-fabric-issues#1131]
![image](https://user-images.githubusercontent.com/2506734/41768053-306f8cb4-7646-11e8-93f3-5e28c31e0ff9.png)

Hi, one of my deployment stuck at FrontEnd_0 node, so I restarted the node. But then, ImageStoreService has warning sign, which I don't know how to resolve. 
Could some one help me on this?

**Comment by masnider** [comment]
0x8007000e | -2147024882 | E_OUTOFMEMORY | Ran out of memory 

So looks like the machine is under memory pressure? Can you check the machine utilization? What size VMs are these?

**Comment by letrungkien211** [comment]
Hi, thanks for responding. 
Machine type was d4s_v3. Cluster of 5 nodes. Memory wasn’t that high. The issue was still there after I restarted the VM. 
At the end, I reimaged the machine and it is resolved now. Probably there is better and less forceful method.
