### ISSUE TITLE
Is reverse proxy for containers supported (similar to docker routing mesh)

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#1134]
Hello,

Docker routing mesh is available on windows since 1709 release which allows to have services deployed to only some hosts while have port listening on all nodes. (https://blogs.technet.microsoft.com/virtualization/2017/09/26/dockers-ingress-routing-mesh-available-with-windows-server-version-1709/)
Is something similar is available/supported in Service Fabric or what is alternative on Service Fabric other then deploying service on every single node.

**Comment by masnider** [comment]
Most commonly today we see people deploy some reverse proxy like [Traefik](https://docs.traefik.io/v1.7/configuration/backends/servicefabric/), or use some other L7 API manager like [Azure API Management](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-deploy-api-management)
