### ISSUE TITLE
How do you do container upgrades with no downtime

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#1135]
Docker swarm features overlapping upgrade of tasks (`order` attribute of `update_config`), that is new container is prepped while old one is still running and then swapped once HEALTHCHECK etc passed. This allows seemless upgrade with no downtime.
You can see details here (https://docs.docker.com/compose/compose-file/#update_config).
In addition to that since docker swarm has a routing mesh feature you can do upgrades with no downtime even without using `order` attribute since swarm is aware which node members hosting a service.
What are the options for similar requirements in Service Fabric?

**Comment by masnider** [comment]
Fundamentally this isn't different for containers vs. noncontainerized workloads in SF. Most commonly a "no downtime" upgrade has two pieces:

1. The actual rolling upgrade. In SF this is a normal [application upgrade](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade), which is going to watch for [healthchecks](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers-linux#configure-docker-healthcheck) which get converted into errors. Errors pause SF upgrades until they stabilize and can cause rollbacks. 

2. While doing the upgrade, you need something to take care of the traffic coming into the containers and ensuring that they drain. The most common solutions for that were referenced in your other question: https://github.com/Azure/service-fabric-issues/issues/1134 Note that some of these have better support for health probes which can help ensure that the container has stopped accepting new calls before it is shut down. 

The second part really depends on your traffic pattern for the container, however. If for example the container is just a long running competing consumer off of some queue, then step 2 generally isn't necessary, the container just needs to stop pulling new workloads and complete the ones it has in flight before shutting down.
