### ISSUE TITLE
Update of service fabric SDK results in FaultAnalysisService failure by startup of cluster

### ISSUE THREAD

**Issue by vmarsen** [Azure/service-fabric-issues#1136]
Hello,

We have been updating Service Fabric SDK to: 
 - Microsoft Azure Service Fabric SDK version 3.1.283.9494
 - Microsoft Azure Service Fabric 6.2.283.9494

But we noticed that the 'fabric:/System/FaultAnalysisService' was failing by startup of the cluster with the following error:
Unhealthy event: SourceId='System.RAP', Property='IStatefulServiceReplica.OpenDuration', HealthState='Warning', ConsiderWarningAsError=false.
The api IStatefulServiceReplica.Open on node _Node_3 is stuck. Start Time (UTC): 2018-06-25 12:42:37.576.

We already did a reset of the cluster, an update of the SDK, a restart of the system, ....

Is this a know bug? What can we do about it?

**Comment by likevi-MSFT** [comment]
Hi @vmarsen, 
A few questions:
1. Is this a cluster running on your local dev machine? 
2. Which version of SDK and runtime did you have previously?
3. Are you running out of disk space on the machine hosting node 3?

**Comment by vmarsen** [comment]
Hi,

Is this a cluster running on your local dev machine?
 => Yes, indeed, (and my machine is running in the local Belgium time zone).

Which version of SDK and runtime did you have previously?
=> Before, I had: 
- Microsoft Azure Service Fabric SDK version 2.8.232.9494
- Microsoft Azure Service Fabric 6.0.232.9494

Are you running out of disk space on the machine hosting node 3?
=> No, I'm not running out of disk space.

**Comment by santo2** [comment]
same issue when starting up my cluster locally

**Comment by likevi-MSFT** [comment]
Are either of you seeing FAS repeatedly crash and restart?

**Comment by likevi-MSFT** [comment]
@santo2, @vmarsen If the disk is within 8G of being full then that could cause disk issue. FAS requires 8G of disk space.

**Comment by likevi-MSFT** [comment]
I installed the product (same version as OP), and have not been able to repro the behavior. I have tried setting my date time formats to Belgium local time format and other non US time formats as well. 


In addition to the questions in my previous post could you also answer the following:
3. Did you uninstall the previous runtime and SDK before installing the new runtime and SDK?
4. Were you using Chaos features previous to updating the SDK and runtime?
6. Are the clusters you are trying to start completely new or are they being upgraded from a previous cluster?

**Comment by vmarsen** [comment]
3. Did you uninstall the previous runtime and SDK before installing the new runtime and SDK?
=> No, I didn't
4. Were you using Chaos features previous to updating the SDK and runtime?
=> No
6. Are the clusters you are trying to start completely new or are they being upgraded from a previous cluster?
=> the local cluster is completely new every time we start it. We also did a reset or reinstallation of the cluster.

**Comment by vmarsen** [comment]
1. Are either of you seeing FAS repeatedly crash and restart? If so, do you have crash dumps?
=> There are no crash dump files in CrashDumps folder

2. Could you also share the traces which will be under "FabricLogRoot" in the output of this command?
[Traces_Issue1136.zip](https://github.com/Azure/service-fabric-issues/files/2145453/Traces_Issue1136.zip)

**Comment by AlanWarwick** [comment]
I have looked at the traces and have a few questions.  What I am seeing is that a log file is being created but the call to create the log file never returns back to the FAS application. The file in question is typically a sparse file with a size of 256GB and from the traces it looks as if it is configured not to be a sparse file but instead a fixed allocation file. This would mean that the code would need to initialize the entire 256GB before returning - I suspect this is what happens. 

* Does the FAS eventually start successfully or does the FAS stay in this state forever ?

* Have you changed any of the TransactionReplicatorSettings that might be in the cluster manifest or your application's settings.xml ?

* Do you see a file named C:\SfDevCluster\Data\_App\_Node_3\__FabricSystem_App4294967295\work\6c5ec9de-b464-4ad2-809a-f6ad7873536d.SFlog ? If so can you please send me the size of the file and the output of the following command:  fsutil file queryallocranges offset=0 length=<length of file> C:\SfDevCluster\Data\_App\_Node_3\__FabricSystem_App4294967295\work\6c5ec9de-b464-4ad2-809a-f6ad7873536d.SFlog.   For example:   fsutil file queryallocranges offset=0 length=268435464192 C:\SfDevCluster\Data\_App\_Node_3\__FabricSystem_App4294967295\work\6c5ec9de-b464-4ad2-809a-f6ad7873536d.SFlog

* Do you have any antivirus or other storage filters or other kind of non standard storage drivers installed ? 

* What version of windows are you running ? 

* You mentioned that the CPU goes to 100%. Can you determine which process it is that is using all of that CPU ? TaskManager or Perfmon may be helpful. 


Thank you

**Comment by vmarsen** [comment]
Thanks for the feedback already. Here is an answer to your questions:

**Does the FAS eventually start successfully or does the FAS stay in this state forever ?**
=> No, it stays in the this state forever.

**Have you changed any of the TransactionReplicatorSettings that might be in the cluster manifest or your application's settings.xml ?**
=> No

**Do you see a file named 6c5ec9de-b464-4ad2-809a-f6ad7873536d.SFlog?** 
=> Yes, I can find the file named 6c5ec9de-b464-4ad2-809a-f6ad7873536d.SFlog, but I found it on another location (C:\SfDevCluster\Data\_App\_Node_3\__FabricSystem_App4294967295\work)
=> File size: 250 GB (268 435 464 192 bytes)
=> output of command:
Allocated range[0]: Offset: 0x0         Length: 0x10000
Allocated range[1]: Offset: 0x3e80000000  Length: 0x2000

**Do you have any antivirus or other storage filters or other kind of non standard storage drivers installed ?**
=> Yes, we have Symantec Endpoint Protection, but we have already tried to ignore the C:\SfDevCluster folder.

**What version of windows are you running ?**
=> Microsoft Windows 10 Enterprise, Version 10.0.16299 Build 16299

**Can you determine which process it is that is using all of that CPU ?** 
=> Mainly the System process (and my colleague mentioned also the Fabric process)

**Comment by vmarsen** [comment]
It seems that after waiting a long time, that the FaultAnalysisService can be started with no errors. It has indeed something to do with the fixed allocation file of  256 GB. Then it takes too long to initiate. 
We also noticed that there was a lot of I/O traffic during the FaultAnalysisService startup. 

Probably, issue #1139 is the same problem.

**Comment by vmarsen** [comment]
Is there already a fix for this issue?

**Comment by RubenVantilt** [comment]
When will a fix be available? I'm having the same issue

**Comment by AlanWarwick** [comment]
Can you please try to remove (not just disable) the Symantec Endpoint Protection and try this again. I want to be sure it is not interfering.

**Comment by vmarsen** [comment]
Hi AlanWarwick,
We have removed the Symantec Endpoint Protection and the problem is still there. My colleague received a new laptop and did a clean installation and also he has the same problem.
We notice that there a lot of read operations to the sflog file you mentioned. This is the reason why everything is slow or not working.

**Comment by vmarsen** [comment]
Below, you can find some extra information about the read operations:
![screenshot reads](https://user-images.githubusercontent.com/602036/42329778-ce121754-8071-11e8-84b7-ced97173f102.png)
![stacktraceofonereadline](https://user-images.githubusercontent.com/602036/42329779-ce2fa8fa-8071-11e8-91db-3244ec439032.jpg)

**Comment by AlanWarwick** [comment]
I would like to try to repro this on my own machines although I suspect that it won't happen.  Are you willing to try to replace one of the SF drivers with a diagnostic driver that will have more tracing information ? That will not fix the issue but will help me pinpoint what is going on. Another possibility would be if you are willing to send me a live kernel crash dump while the reading is taking place. 
It is hard to tell from your stack dump above what is doing the reading. It is possible that the SF log recovery code is confused if the file is sparse or not - it is also possible that there is some other storage component interfering. 

I am also checking to see if there is any settings that can be change for FAS to work around this issue.

**Comment by AlanWarwick** [comment]
@VMarsen - how did you create the cluster ? Did you use the tool that is part of the toolbar tray ?

**Comment by likevi-MSFT** [comment]
@vmarsen We haven't heard from you in a while. I will be closing this issue. If the problem is still occurring please re-open and we will take a look.

**Comment by PTCruiserGT** [comment]
In vmarsen's last post in this thread, you can see that the Microsoft sysmon filter driver (sysmondrv.sys) is running.  There is another thread here where Microsoft's Sysmon was identified as the culprit for a similar issue.  See https://github.com/Azure/service-fabric-issues/issues/1139.
