### ISSUE TITLE
Service Fabric PowerShell cmdlets are incompatible with PowerShell Core so with .NET Core apps

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#1138]
We're getting this error:

>Could not load file or assembly System.Diagnostics.Eventing.EventProvider

When try to call any cmdlet from the ServiceFabric.psd1 module from a .NET Core 2.1 app using [System.Management.Automation](https://powershell.myget.org/feed/powershell-core/package/nuget/System.Management.Automation) nuget (the only official package for PowerShell/Core)

**Comment by masnider** [comment]
@abatishchev were you able to try the new library I pointed you to? Adding some other folks to take a look and see if this is a known issue.

**Comment by MikkelHegn** [comment]
The PowerShell modules on the Service Fabric SDK depends on .NET Framework. I would assume that is why you are seeing this error.

We do have a new client library based on HTTP, which could be the foundation for PowerShell modules without that dependency, however I don't have a specific timeline for us to deliver this.

**Comment by abatishchev** [comment]
@masnider, The new client sounds very promising but we've designed our application is to delegate the heavy-lifting to SF PS. So unfortunately doesn't unblock us.

@MikkelHegn looking forward for the revamped SF PS then.

Meanwhile, if we'd like to continue using PowerShell and would like to give the new HTTP-based client a try, we would need to call one from another ourselves, correct?

**Comment by raunakpandya** [comment]
Not sure if I got your question here.. You cannot continue using powershell from a .NET Core app though..

**Comment by abatishchev** [comment]
>You cannot continue using powershell from a .NET Core app though..

That's not want I meant. We'll continue uisng .NET Framework and PoweShell.

But if we want to try using .NET Core, PoweShell Core, and the new SF client on Core then we'll have to wire up everything ourselves, that it, call the new client from PS/C#.

**Comment by raunakpandya** [comment]
Yes.. And just to be clear, by wiring up you really mean you will have to come up with SF cmdlets youself which internally use the new SF client. As Mikkel mentioned, we do plan to release the revamped SF PS on top of new client in future.

**Comment by amanbha** [comment]
@abatishchev  We will be a releasing a new Powershell module for pwoershell core whcih works over SF REST apis and doesnt need runtime to be installed. ETA 2-3 weeks

**Comment by abatishchev** [comment]
Awesome news! We can dogfood this if you need some additional testing. Is there a preview package to try today?

**Comment by abatishchev** [comment]
[New REST-based PowerShell modules](https://blogs.msdn.microsoft.com/azureservicefabric/2018/12/11/announcing-new-rest-based-service-fabric-powershell-module/) supposedly address this issue.
