### ISSUE TITLE
Node gets stuck when running Stateful service

### ISSUE THREAD

**Issue by TomSmets86** [Azure/service-fabric-issues#1139]
Hello,

When running any Stateful service project the node gets in a stuck state:

Unhealthy event: SourceId='System.RAP', Property='IStatefulServiceReplica.OpenDuration', HealthState='Warning', ConsiderWarningAsError=false. The api IStatefulServiceReplica.Open on node _Node_0 is stuck. Start Time (UTC): 2018-06-26 11:25:40.358.

This also occurs with a default / blank stateful service project.

I tried upgrading my Service Fabric SDK from 3.1.274.9494 to 3.1.283.9494 but the issue happens on both versions.

Is anyone experiencing the same issues?

Adding the code  new ArgumentException();  to the main() did not resolve anything either.
Thank you for the feedback!

**Comment by raunakpandya** [comment]
1. Is this a .NET Core app or a full .NET app?
2. Windows/ Linux?
3. Location of cluster? Devbox?
4. Runtime version?

**Comment by masnider** [comment]
Yeah the version of the cluster and the environment would be useful here.

**Comment by TomSmets86** [comment]
Hi,

The cluster is running on my local machine (Windows 10)

The problem occurs with both Core and full .NET.

Runtime version is 6.2.283.9494

Thanks in advance!

**Comment by motanv** [comment]
Hello @TomSmets86,
I could not repro on a clean Azure VM (Windows 10 Pro, SF Runtime 6.2.283 and SF SDK 3.1.283). It could be some environment issue specific to your machine. Could you please share the SF logs, they usually lives in C:\SfDevCluster\Log\Traces and have names like fabric_traces_6.2.283.9494_131838307785070975_0.etl

Also, what do you mean by "I tried upgrading my Service Fabric SDK from 3.1.274.9494 to 3.1.283.9494 but the issue happens on both versions."

How many nodes are in your cluster?

Thanks,
Tanvir

**Comment by Krishna-teja** [comment]
@motanv I am also having this same exact issue whenever I am using 5 node cluster. Here are the trace logs - 
[Traces.zip](https://github.com/Azure/service-fabric-issues/files/2480173/Traces.zip)

**Comment by Krishna-teja** [comment]
@motanv The problem occurs with both Core and full .NET for all stateful services. It happens with both 1Node cluster and 5Node cluster. Its affecting all the devs here. Could you please look into this issue?

**Comment by Krishna-teja** [comment]
One other strange behavior is that when this issue happens - The system process spikes up quite huge on CPU and Disk and over time it gradually keeps growing.
![image](https://user-images.githubusercontent.com/6452602/46974407-88432980-d089-11e8-8c08-bc68e73d2b51.png)

**Comment by motanv** [comment]
@Krishna-teja, it appears that you are on Service Fabric runtime 6.3.176, which SDK version are you using?

**Comment by motanv** [comment]
@Krishna-teja, also could you please make sure if the logs you have shared correspond to the SFX screen snapshot ? (The reason I am asking is, I cannot find the partition ids or apps in the trace). Please stop the local cluster, remove the contents of C:\SfDevCluster\Log\Traces and then start the cluster and deploy the app, let it run (stuck on _Node_0) for a while and then please share the contents in C:\SfDevCluster\Log\Traces.

**Comment by Krishna-teja** [comment]
Yes, I was on SF Runtime 6.3.176, Now I tried uninstalling and reinstalling the new SDK and runtime - 6.3.187. Its still the same issue. Here are the traces that you requested and the snapshot of my cluster.
traces
[Traces.zip](https://github.com/Azure/service-fabric-issues/files/2497546/Traces.zip)

  ![image](https://user-images.githubusercontent.com/6452602/47246744-3bcb5700-d3c5-11e8-922a-be639c2d37c4.png)

So we tried in few other local dev machines and basically, the trigger point was when we switched to 5 node cluster this issue starts happening. Also this error goes away after waiting for about an hour.

**Comment by AlanWarwick** [comment]
@Krishna-teja,   Reliable collections uses a log to store data and for the log it needs to create a set of files. From the traces it looks as if the creation of the log file dedicated to this specific replica is taking a long time to create - from your description, about an hour.  By default this log is a sparse file, that is, a file with a nominally large size but whose disk allocations are allocated on as needed. My guess is that somehow the file may not be being created as sparse and so the whole file (256GB) would need to be initialized and thus take an hour. 

Would you be willing to check a few things to help me understand if this is actually the case:

* Can you confirm that it always works on the one node cluster but never works on the 5 node cluster ? That is once it fails on the 5 node cluster that you can switch back to the one node cluster and it works ? Or once it starts failing that it continues to fail ? 

* Is there some sort of file system filter driver or antivirus driver or something might intercept file system requests ? Perhaps it might want to scan the whole 256GB log file ?  If so is it possible to configure it to ignore the \SfDevCluster directory and/or ignore .SFlog files ? 

* In the case above the dedicated log file created is named \SfDevCluster\Data\_App\_Node_0\Identity4AppType_App0\work\bc532316-6106-4b5d-b5dc-f3fe1e1a149f.SFlog. If you redeploy the app then the file path will be similar and the file be of type .SFlog but the name will be a different guid name. Would you be able to run these commands on that file (replace the filename as appropriate):  

"fsutil sparse queryflag SfDevCluster\Data\_App\_Node_0\Identity4AppType_App0\work\bc532316-6106-4b5d-b5dc-f3fe1e1a149f.SFlog"

"fsutil sparse queryrange SfDevCluster\Data\_App\_Node_0\Identity4AppType_App0\work\bc532316-6106-4b5d-b5dc-f3fe1e1a149f.SFlog"

Thank you,
Alan

**Comment by Krishna-teja** [comment]
@AlanWarwick @motanv Thanks, Alan for your response. Sorry for the late response. 

1. It does not work in either 1 node or 5 node cluster. Once it starts failing it continues to fail.

2. We have tried uninstalling entire sophos antivirus to check and see if thats not related to it.

3. ![microsoftteams-image](https://user-images.githubusercontent.com/6452602/47877390-c3fc2400-dde9-11e8-8d85-4744ea88ebcf.png)

I have tried all approaches but it still doesnt fix the issue. Is there any way one of you could get on a Hangout to analyze and see what exactly is happening on our machines?

Thanks,
Krishna

**Comment by AlanWarwick** [comment]
@Krishna-teja - would you be willing try to try a special ktlllogger.sys driver with extra instrumentation that would help me to diagnose this issue ? All you need to do is to replace the file, restart the driver, redo the scenario and then send me the traces as you did before.

Also would you mind sending me the output of the "fltmc"  and "fltmc instances" commands, please. This will show any fs minifilters installed.

Thank you for your help,   Alan

**Comment by AlanWarwick** [comment]
@Krishna-teja, If you run the fltmc and fltmc instances command and see any additional minifilters installed, specifically SysmonDrv (from the sysmon tool) then please uninstall and try to deploy the cluster again. I had heard that SysmonDrv may get in the way of the sparse file log creation.

**Comment by Krishna-teja** [comment]
@AlanWarwick Oh cool. Thanks, that worked. Do you know why SysmonDrv is causing this issue?

**Comment by AlanWarwick** [comment]
@Krishna-teja, thank you for trying this out.

The delay is happening within the NtCreateFile() api call. I don't have access to the SysMonDrv source code and so am not sure what it is doing to cause the delay.

**Comment by PTC-JoshuaMatthews** [comment]
I am seeing the same error, but in my case it works fine on both local 1 node and local 5 node cluster, but has this error on my Azure generated 5 node cluster.
