### ISSUE TITLE
Add ability to specify the shutdown timeout for a container

### ISSUE THREAD

**Issue by dagirard** [Azure/service-fabric-issues#1140]
Windows Server Core added the ability for applications to receive a shutdown event, enabling to have a graceful shutdown of the container:
[https://github.com/moby/moby/issues/25982]

By default, docker stop has a timeout of 5s, which is too short for us (stateful server application). But, this can be controlled as it is a parameter of "docker stop" command.
docker stop -t <time to let the container shutdown in seconds>

Can this be added in the ApplicationManifest/SF?

Acceptance criteria:
1. Service Fabric call docker stop with the timeout specified in the application manifest
2. Application running inside the container receives CTRL_SHUTDOWN_EVENT, and terminate gracefully
3. Docker stop the container after the given timeout

Thanks

**Comment by artisticcheese** [comment]
This seems to be already supported https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-time-interval-before-container-is-force-terminated

**Comment by raunakpandya** [comment]
Hopefully that addresses your question. Closing the issue.
