### ISSUE TITLE
DNS Service using hostname instead of localhost

### ISSUE THREAD

**Issue by felipecruz91** [Azure/service-fabric-issues#1144]
**Environment information**
OS: Windows 10 Pro
Version: 10.0.16299 Build 16299
Microsoft Azure Service Fabric: 6.2.301.9494
Microsoft Azure Service Fabric SDK: 3.1.301.9494
SF Cluster mode: 1 Node

Why is my hostname showing up instead of localhost?

I cannot get any HTTP requests hitting the WebAPI service with that URL:

![image](https://user-images.githubusercontent.com/15997951/41979373-3e8adfe2-7a24-11e8-8061-5ff0f8ce6441.png)

**Comment by MikkelHegn** [comment]
It's because that is what was specified in the cluster manifest for the IPAddressOrFQDN. If it's a local onebox (dev clusters) and you used the -UseMachineName parameter to setup the cluster, the script will make this configuration.

**Comment by felipecruz91** [comment]
@MikkelHegn I have changed in the `C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\Secure\OneNode\ClusterManifestTemplate.json` file from:

![image](https://user-images.githubusercontent.com/15997951/41994103-b21dbe74-7a4d-11e8-822d-ddc0a0170352.png)

to:

![image](https://user-images.githubusercontent.com/15997951/41994095-aac0d9ae-7a4d-11e8-8fef-47271d41c268.png)

And now the Web API address shows **localhost** instead of the fully qualified domain name:

![image](https://user-images.githubusercontent.com/15997951/41994122-cd57462e-7a4d-11e8-83aa-0d4e2b04dd0a.png)

Thank you.

**Comment by MikkelHegn** [comment]
@felipecruz91 Be aware this will be overwritten when updating the SDK.

**Comment by felipecruz91** [comment]
@MikkelHegn Oh right, thanks for the note - is there any way to make localhost to show up as default, instead of the full qualified domain name?

**Comment by WillTartak** [comment]
Thank you for posting this. For it to work for me I had to reset the local cluster after modifying the ClusterManifestTemplate.json file(s).
