### ISSUE TITLE
Unable to publish my code using Microsoft Azure ServiceFabric SDK-3.1.274 & runtime -6.2.274

### ISSUE THREAD

**Issue by H286424** [Azure/service-fabric-issues#1150]
unable to publish my code using Microsoft Azure ServiceFabric SDK-3.1.274 & runtime -6.2.274 on Local Cluster. Can someone suggest the required changes.

**Comment by masnider** [comment]
Please provide more information. What's failing? What errors are you getting? etc.

**Comment by MikkelHegn** [comment]
Closing due to no response
