### ISSUE TITLE
Service Fabric Remoting usage

### ISSUE THREAD

**Issue by danijel-peric** [Azure/service-fabric-issues#1151]
Hi,

Is it true that if i don't set listener name on remoting service, and use that listener name for ServiceProxy, communication will not work

example this work

StatefulService
```
  protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
        {
            //add the pubsub listener
            yield return new ServiceReplicaListener(context => new FabricTransportServiceRemotingListener(context, this), "GatewayServiceListener");
        }
```
on StatelessService

```
 var service = ServiceProxy.Create<IGatewayService>(new Uri("fabric:/TestApp/GatewayService"), new ServicePartitionKey(0), TargetReplicaSelector.Default, "GatewayServiceListener");
 var message = await service.GetMessage();
```

if i don't specify listener name on any side, communication will not work

above works without defining ServiceEndpointV2 or [assembly: FabricTransportServiceRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]

GatewayService

```
  <Endpoints>
      <Endpoint Name="ServiceEndpoint" />
      <Endpoint Name="ReplicatorEndpoint" />
    </Endpoints>
```

maybe i'm missing something, but i know that on some version i didn't need to define listener name if service is using only one

services are in net core, version of sf is 6.2.283

**Comment by suchiagicha** [comment]
@danijel-peric 

if you specify listenerName on the service , you have to specify on client side. ListenerName act as a identifier for listener. If you use Providerattribuite for listener , we by default assign listenerName to it.
Reason for this is we now support Compact version which requires multiple listeners hence we needed unique name for them.

**Comment by danijel-peric** [comment]
if i don't specify listener name on service and on client side, it should work? and if i don't use providerattribute

can you check this test repo and let me know why communication is not working

https://github.com/danijel-peric/service-fabric-playground/tree/master/CommunicationTest

**Comment by suchiagicha** [comment]
@danijel-peric 
You are using explicit classes at Listener side to use V2 remoting and on client side you are using default attribute. That is not correct.

There are 2 ways to configure remoting : 1) is explicitly creating Listener and Client Factory (Here is how to : https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#using-explicit-v2-classes-to-use-the-v2-stack) and 
Another way is using provider attribute (Here is how to : https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-the-remoting-v2-stack)

You are using mix of both. You should use either of them if you don't want to provide listenerName.

**Comment by danijel-peric** [comment]
thanks, works now, it was more straight forward when we did have only one remoting implementation, now with v2 it can be confusing
