### ISSUE TITLE
Question-Service fabric cluster monitoring solution for on-premises,poll data from OMS agent

### ISSUE THREAD

**Issue by dineshkotwani** [Azure/service-fabric-issues#1154]
Hi,
Currently we have setup a standalone cluster running service fabric v6.2 on nodes running windows server 2016 datacenter and we are currently creating a web UI /dashboard to view historical/trend health / metrics for each node inside cluster .
We have explored installing OMS agent and setting up workspace in Azure , but we don't really want to push metrics data to public cloud like Azure via OMS agent .
Do we have any option to configure the sink of OMS agent from Azure OMS workspace to custom on-premise DB/KV store .
If not , what options will you suggest to some customer if customer doesn't want to push any metric data/logs to Azure/public cloud .

**Comment by dkkapur** [comment]
I'd recommend looking into setting up the ELK stack locally (Elasticsearch + Logstash + Kibana) or considering a premium monitoring solution like Dynatrace. ELK would be the cheaper option but would require a little more set up complexity.
