### ISSUE TITLE
Cannot publish or connect to secured SF cluster from VS

### ISSUE THREAD

**Issue by piffarettig** [Azure/service-fabric-issues#1155]
I've created a secured SF cluster from the portal, but I can't connect to the explorer from the browser or deploy my app from VS. I have the cluster certificate (the one it makes you create on a Key Vault when you first deploy the cluster) installed on my machine. I got the .pfx file from the Key Vault and installed it on my Windows machine both with double click/wizard and with Powershell Import-PfxCertificate cmdlet. 

Still after that, VS says **_Failed to contact the server. Please try again later or get help from "How to configure secure connections"_**

I tried added an client "admin" certificate, but it only asks me for the Thumbprint or the subject name, where I put the ones from the previously created cluster certificate. I don't really know if I need to buy a client certificate to make it work, or where do I get it?

And as I said, I can't access to the explorer using the browser either. Any ideas?

Here some screenshots:

<img width="563" alt="screen shot 2018-07-02 at 11 15 24 pm" src="https://user-images.githubusercontent.com/16963208/42195251-522424e0-7e4e-11e8-94c5-eb6a4686a9b9.png">
<img width="874" alt="screen shot 2018-07-02 at 11 17 12 pm" src="https://user-images.githubusercontent.com/16963208/42195252-524882ae-7e4e-11e8-9603-1e8f5d15b4c0.png">

**Comment by NCarlsonMSFT** [comment]
The first screen shot is indicative of a cert that is not trusted. I'm assuming your cluster certificate is self signed? If so you can add it to your trusted root certificate authorities to avoid the dialog:
![image](https://user-images.githubusercontent.com/14239288/42525002-f755dcf0-8426-11e8-8aff-7204871e1426.png)

You can also click the proceed button on the bottom. Provided you verify the thumbprint of the certificate is yours you will be securly connected to your cluster.

For the connection issues in VS. Make sure you have configured the certifcate in your publish profile (expland the advanced section or open the XML file).

In the xml file there should be an example in the comments:
<ClusterConnectionParameters ConnectionEndpoint="mycluster.westus.cloudapp.azure.com:19000"
                                    X509Credential="true"
                                    ServerCertThumbprint="0123456789012345678901234567890123456789"
                                    FindType="FindByThumbprint"
                                    FindValue="9876543210987654321098765432109876543210"
                                    StoreLocation="CurrentUser"
                                    StoreName="My" />

You need to tell VS which cert to use (In this example it is indicated by thumprint) and which certificate 
store it is in (In this example the User Certificates, My <In the cert manger UI it is called personal>)

**Comment by NCarlsonMSFT** [comment]
I'm assuming this worked for you and closing the issue as inactive. Please let us know if you are still having an issue.
