### ISSUE TITLE
Question - Service Fabric readiness checklist

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1156]
i was looking into below links for service fabric prod checklist.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-production-readiness-checklist

first item in checklist is 

(1) For clusters with more than 20 cores or 10 nodes, create a dedicated primary node type for system services. Add placement constraints to reserve the primary node type for system services

how can i deploy system services on primary node type only ?

Consider i have two nodes type one for SystemService and other for WorkerNodes.
do i need to remove all ports for System Services from workerNode ? and SystemServices will not being having any application ports ?

"nodeTypes": [
            {
                "name": "SystemService",
                "clientConnectionEndpointPort": "19000",
                "clusterConnectionEndpointPort": "19001",
                "leaseDriverEndpointPort": "19002",
                "serviceConnectionEndpointPort": "19003",
                "httpGatewayEndpointPort": "19080",
                "reverseProxyEndpointPort": "19081",
                "isPrimary": true
            },
            {
                "name": "WorkerNodes",
                "applicationPorts": {
                    "startPort": "20288",
                    "endPort": "20318"
                },
                "isPrimary": false
            },

For 5 nodes cluster, 2 nodes for system services and 3 nodes for Application services is good design ?

Thanks,
Naresh Khatri

**Comment by guibirow** [comment]
When you set the NodeType as Primary, you are already telling service fabric that the system services should be placed there.

This [docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity) describe it in more details

To limit your services of running on these nodes, you should use [placement contraints](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#node-properties-and-placement-constraints)

For the size of the cluster, the first link I provided also mention about the sizes

**Comment by guibirow** [comment]
Fabric.exe you mean?

**Comment by guibirow** [comment]
Can you send a print?

**Comment by masnider** [comment]
Since the base case is that there's only a single node type, once you have more than one node type you need to explicitly tell SF where to run services. 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#node-properties-and-placement-constraints

**Comment by masnider** [comment]
@nareshkhatri81 - were you able to resolve the problem here?

**Comment by aljo-microsoft** [comment]
Being multiple months without response that the user resolved their issue. #close
