### ISSUE TITLE
Service Fabric Application Wide Environment Variables

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#1157]
Can I have service fabric services sharing environment variables? I.e if one of the stateless service sets an environment variable can I have a way to access that value in other services? 
I have tried running both the services under same user but that did not work.

Adding some more info, Iam creating an azure file share resource on the fly in a stateless service startup code, and want to access that file share in another service using environment var

**Comment by guibirow** [comment]
Environment Variables are set per process, if you want to share them, you should set a machine environment variable.

These links should provide some help:

https://stackoverflow.com/questions/19705401/how-to-set-system-environment-variable-in-c
https://stackoverflow.com/questions/3803581/setting-a-system-environment-variable-from-a-windows-batch-file

I don't think service fabric has any secret sharing feature, you could build your own service that expose these configuration to other services or using existing configuration service/secret management tool like Azure Keyvault with a single account shared among your application service, I think this will be more flexible.

**Comment by masnider** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-how-to-specify-environment-variables

**Comment by usamaazhar** [comment]
The machine environment variable did the trick here, I had to run the service as an admin though to set the machine env var.  In the ServicemanifestImport section of the service I had
```
<Policies>
      <RunAsPolicy CodePackageRef="Code" UserRef="SetupAdmin" EntryPointType="All" />
    </Policies>
```
and I created this user as: 
```
  <Principals>
    <Users>
      <User Name="SetupAdmin">
        <MemberOf>
          <SystemGroup Name="Administrators" />
        </MemberOf>
      </User>
    </Users>
  </Principals>
```
