### ISSUE TITLE
Actor Runtime - direct access without using sf remoting

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#116]
Is it possible to access Actor Runtime directly from the ActorService (avoiding data serialization and retry logic applied by the ActorProxy)? I would like to expose an HTTP endpoint to perform operations on actors using Actor Runtime

**Comment by VipulM-MSFT** [comment]
We are working on improvement to allow this.

**Comment by mkosieradzki** [comment]
@masnider Can we reopen this one, please? I asked this question during Q&A and the response was there are no plans.

**Comment by mkosieradzki** [comment]
If necessary I can describe a scenario which really justifies this feature.

**Comment by pisees** [comment]
Hi, was this feature enabled?
