### ISSUE TITLE
No Issues Being Shown

### ISSUE THREAD

**Issue by haseeb-ahmed-tkxel** [Azure/service-fabric-issues#1165]
Hi Guys,
I'm having this issue where my stateless services are not showing any error but are not running either. The best that I have been able to get from OMS on a deployed dev cluster was that there was some problem initializing the service.

Please find below what my SF Cluster Explorer looks like on a local 1 Node cluster.
![image](https://user-images.githubusercontent.com/21213521/42448883-2d221586-8398-11e8-9637-362c84c22ea3.png)

Previously, if I have had issues, I have seen a warning sign next to the node and in the node's details is some sort of error but this time, there is nothing. Nothing at all.

**Comment by masnider** [comment]
For these errors, you can usually see them if you continue expanding, looking in the service's details pane, or drilling down under the actual Node (via the Node root, not the service/app root). Can you show that portion of SFX as well? You can also try get-servicefabric*health commands at different levels to see if you can find the actual error info.

**Comment by haseeb-ahmed-tkxel** [comment]
@masnider Yeah, I know. But as you can see, it apparently doesn't have any Node under three of them.

**Comment by srrengar** [comment]
Hey @haseeb-ahmed-tkxel can you share the full output of the OMS event you mentioned and also any error information in the Service Fabric Explorer? Do you have default services enabled in your manifest as well?

**Comment by srrengar** [comment]
@haseeb-ahmed-tkxel could you share the error information?

**Comment by masnider** [comment]
Hi @haseeb-ahmed-tkxel , we're going to close down this issue since we haven't heard back from you. If you are still having this problem, please feel free to reopen this issue or create a new one. Thanks!
