### ISSUE TITLE
Add-AzureRmServiceFabricClusterCertificate: KeyVaultAndVMInDifferentRegions

### ISSUE THREAD

**Issue by alexwilsh** [Azure/service-fabric-issues#1166]
Trying to add a secondary certificate to an existing cluster using this Add-AzureRmServiceFabricClusterCertificate:

` Add-AzureRmServiceFabricClusterCertificate -ResourceGroupName '..' -Name '..' -SecretIdentifier '..'`

And the following error is returned:

"... Code: KeyVaultAndVMInDifferentRegions, Message: The Key Vault ... is located in location
eastus, which is different from the location of the VM, westeurope ..."

Key Vault, SF cluster and VM scale set are in East US:
![image](https://user-images.githubusercontent.com/22404115/42476367-b9be33fa-839b-11e8-9821-669fc15f0e18.png)

I actually have other clusters and VM sets in the same resource group which are located in West Europe, but I'm trying to apply a certificate to a cluster in the same region as my Key Vault.

PowerShell AzureRm version: 5.7.0

Any suggestions on what can be wrong?

**Comment by alexwilsh** [comment]
Small update on this issue. 
I decided to move resources from other regions to other resource groups just to try one more time with cluster certificate update.
Unfortunately, I couldn't move VM scale set created for a SF cluster by default since it uses managed disks. Eventually, I moved everything except this VM scale set.

After this when I ran the command mentioned above one more time, it returned the following exception:
`Add-AzureRmServiceFabricClusterCertificate : Code: InvalidResourceReference, Message: Resource
/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/..-VNET referenced by resource
/subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/virtualMachineScaleSets/..vmqa was not found. Please make sure that the referenced resource exists, and that both
resources are in the same region.`

Yes, as I said I moved VNET to another resource group, but my command was addressed to completely different SF cluster. It looks like the PowerShell command tries to access other resources within resource group as well even thought I didn't tell it to do that.

I'm not sure how to resolve this puzzle so far. And this really scares me since the only way I see right now is to recreate the whole cluster and redeploy everything from the scratch. This is not a production scenario at all :(

**Comment by alexwilsh** [comment]
Ok.. now it became more clear what is going on :)

As I wrote I moved my resources to specific resource group and only VM scale set is left in old group.
Now, when I run the Add-AzureRmServiceFabricClusterCertificate command, I'm getting this error:

`Add-AzureRmServiceFabricClusterCertificate : Did not find any node type in resource group WCG-IRB-DEV`

Which means I was right. The command is looking for all VMs inside resource group instead of looking into VM scale set specified for SF cluster mentioned in the command itself.
That is why it doesn't work if you have more than one VM within one resource group. And now it does't work if VM scale set is in another resource group.

Something is definitely wrong with this PS command :)

**Comment by juhacket** [comment]
VMSS and KeyVault must be in the same resource group. This is a requirement for all compute resources.

**Comment by alexwilsh** [comment]
You're right..
But there is another case when you have more than one VMSS in one resource group - in this case the command doesn't work as well even if you specify correct SF cluster. So, it doesn't check VMSS for a cluster.. - it just ignores this.
