### ISSUE TITLE
issue while publishing a container application into the Azure Service fabrics from Visual studio

### ISSUE THREAD

**Issue by fazilmajeed** [Azure/service-fabric-issues#1168]
Hai ,

I have a issue while publishing my service fabrics container application into Azure Service fabrics from Visual Studio.I Installed the certificate into my local machine.  My connection to the cluster is validate and succeded. 

![capture](https://user-images.githubusercontent.com/14705805/42572423-20a1cad6-8537-11e8-9b60-b63071146e6a.PNG)

But when I publish it I got a error 

![capture1](https://user-images.githubusercontent.com/14705805/42572740-c1ddc8dc-8537-11e8-825e-2d2509044cf7.PNG)

Can some one figure out this?

With Thanks and Regards,
Fasil V A

**Comment by fazilmajeed** [comment]
Hi, It happends every time through Visual studio, let me try it from powershell

**Comment by fazilmajeed** [comment]
Hi,
I had tryed to connect from powershell. there I could able to connect to the cluster. But not able to publish.

![capture2](https://user-images.githubusercontent.com/14705805/42624945-370d6aac-85e4-11e8-8832-8ad9d3f48774.PNG)

**Comment by dbreshears** [comment]
Closing older issue.  Looks to have been an issue with the cluster or network issue since Copy-ServiceFabricApplicationPackage was failing.  Please re-activate if you hit this again
