### ISSUE TITLE
ServiceProxy.Create - Improved documentation and guidelines for use

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#117]
I wish there was some better documentation for the ServiceProxy.Create, like is it OK to reuse after exception? Can it live for the entirety of the lifetime of the service? Is it thread-safe? Does it handle transitions of primary partitions across nodes?

These are the docs that perhaps could be improved:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.client.serviceproxy

https://github.com/Microsoft/azure-docs/blob/master/articles/service-fabric/service-fabric-reliable-services-communication-remoting.md

**Comment by BharatNarasimman** [comment]
Thanks for the feedback. We will improve these docs.

**Comment by BharatNarasimman** [comment]
We have added more details to  https://github.com/Microsoft/azure-docs/blob/master/articles/service-fabric/service-fabric-reliable-services-communication-remoting.md

**Comment by masnider** [comment]
Great! Thanks @BharatNarasimman . 

@sondreb I'll close this for now, but please let us know if you have any further questions. Thanks again for reporting this.
