### ISSUE TITLE
Unable to start docker containers with Open networking on a Ubuntu cluster

### ISSUE THREAD

**Issue by likewarster** [Azure/service-fabric-issues#1171]
I have created a Ubuntu service fabric cluster on Azure with Open networking as described in: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-networking-modes

When I attempt to deploy a docker container with `<NetworkConfig NetworkType="Open"/>` defined in the ApplicationManifest.xml the container fails to start with the error:

`Failed to start Container. ContainerName=sf-7-dcb8744f-2981-0b41-8d5a-84cce36359ed, ApplicationId=test-appType_App7, ApplicationName=fabric:/test-app. DockerRequest returned StatusCode=InternalServerError with ResponseBody={"message":"failed to create endpoint sf-7-dcb8744f-2981-0b41-8d5a-84cce36359ed on network servicefabric_network: remote: Network not found`

If I remove `<NetworkConfig NetworkType="Open"/>` The container will start, but its endpoints do not seem to be reachable, regardless of whether or not a portBinding is specified

**Comment by sdkadam2017** [comment]
Does the cluster manifest have these settings?
<Section Name="Setup">
   <Parameter Name="ContainerNetworkSetup" Value="true"/>
  </Section>
 <Section Name="Hosting">
   <Parameter Name="IPProviderEnabled" Value="true"/>
  </Section>

**Comment by sdkadam2017** [comment]
There was another issue with open network which is fixed in 6.4 (related to servicefabric_network not found). But to ensure you are not running into the same issue can you please forward the deployer logs?

**Comment by masnider** [comment]
There were a couple issues around open networking in prior releases. Since we haven't heard back from you, closing this issue for now. If you are continuing to experience this issue on a recent release of SF, please reopen the issue and provide the SF cluster, docker, and windows version and logs. Thanks.
