### ISSUE TITLE
[error]Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Lemraj** [Azure/service-fabric-issues#1173]
Hello,

Since a couple of days we are experiencing deploy problems in a specific environment (ACC) with our service fabric application. This application is not changed and we just tried te deploy it again.
When starting the deployment, it get stuck with the next error: "**[error]Exception has been thrown by the target of an invocation.**" This error appears after the action "**Copying application to image store...**"
![image](https://user-images.githubusercontent.com/10677560/42685367-14df18d6-8693-11e8-8e38-6775e0c85c0f.png)

Our service fabric cluster is running the latest version (**6.2.301.9494**).
We have multiple environments (DEV/ACC/PROD) and we are now having trouble only in ACC.

I tried all the scenarios I could think of, but without success.

I think that the problem is related to the latest release of service fabric runtime/sdk, but I am not sure, because it works fine in other environments with the same version.

I also tried to deploy an older version again which was successfully deployed, but we get the same error.

I tried also to deploy another application and it this gets stuck in the "**Registering application type...**" step:

![image](https://user-images.githubusercontent.com/10677560/42688456-93f1ff72-869c-11e8-9d74-8480bf3678ca.png)

Almost 26 minutes busy with this last step, and then it timed out

Any help? thank you.

**Comment by rfcdejong** [comment]
Do you have the PatchOrchestration service? Try removing it.

**Comment by Lemraj** [comment]
Thank you guys for the suggestions. We finally contacted Microsoft for support.

This is the answer we have got (including a patch script)

-----------------------------------

A recent regression in tcp code during July’s windows update may cause http.sys based Listener(s) hung. In this scenario, our Service Fabric customers will notice below mentioned symptom(s) :

Symptom : 

1.	During the time of issue ‘netsh http show servicestate’ cmd should hang
2.	Http listener calls will be hung, in general there should be a warning in RAP like Service Open failed
3.	Process using http can’t be killed
4.	http endpoint fails 
5.	Cluster/Application Upgrade fails  or timeout

List of technologies built on top of Http.sys Kernel listener, which may be impacted on this TCP regression.

OwinListener, https://msdn.microsoft.com/en-us/library/microsoft.owin.host.httplistener.owinhttplistener(v=vs.113).aspx 

HttpListener, https://msdn.microsoft.com/en-us/library/system.net.httplistener(v=vs.110).aspx 

WebListener, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener 

WCF Listener with basicHttpBinding, https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/basichttpbinding 

Mitigation :

1.	You may consider to use SF POA to patch your cluster, More info https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application 
2.	For immediate detection and mitigation. Please use the attached script to identify if your environment is impacted on this issue. 
a.	Save the attached .txt script file as patchcheck.ps1
b.	Run the patchcheck.ps1 script from PowerShell
c.	If you want to do an installation for the patch, please manually install it though Upgrade Domain one by one. Or you can use the attached Installing-Patch.txt script which you can save as Installing-Patch.ps1 which automatically install the appropriate patch.
3.	Restart the effected VM from VMSS Portal blade through UD(upgrade domain) walk as needed.

Note: Please run those scripts at one node(VM) at a time and move on to the next once it is completed in the current node.

Thanks.

**Comment by oanapl** [comment]
Thank you for the update, @Lemraj . I will close the issue based on the above. Please reopen or open a new one if you are still having issues.
