### ISSUE TITLE
Can Owin service and other services be hosted in one project?

### ISSUE THREAD

**Issue by zhenm** [Azure/service-fabric-issues#1176]
I have 2 type of services, one is called OwinSerivce that will be used as listener to process external request; the other one is called for example InternalProcessService, and I want to expose this internal service interface for others to use directly(using internal ur; fabric:/application/InternalProcess) as they are in the same cluster. So I just want to know whether I can put there 2 services in one project(define them in the same ServiceManifest.xml)? Like below:
<ServiceTypes>
    
    <StatelessServiceType ServiceTypeName="OwinServiceType" />
    <StatelessServiceType ServiceTypeName="InternalProcessServiceType" />
  </ServiceTypes>

OwinService: impl like:
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new[]
            {
                new ServiceInstanceListener(initParams => new OwinCommunicationListener(String.Empty, new Startup(), initParams))
            };
        }

InternalProcessService: impl:
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new[]
            {
                new ServiceInstanceListener(this.CreateServiceRemotingListener)
            };
        }

From my test, the internalprocess service can not be started correctly. So I want to know am I wrong or which step I am wrong? Or whether we can do like this way?
I know that the 2 service can be split into 2 different projects, but for some reason, I want to put them into one project.
Thanks.

**Comment by ashishnegi** [comment]
You can register multiple services in `Program.cs`.
and add in your `ServiceManifest.xml` :

```xml
<ServiceTypes>
    <StatelessServiceType ServiceTypeName="Service1Type" >
    </StatelessServiceType>

    <StatelessServiceType ServiceTypeName="Service2Type" >
    </StatelessServiceType>
  </ServiceTypes>
</ServiceTypes>
```
See [SO : service-fabric-are-multiple-service-types-allowed-in-servicemanifest-xml](https://stackoverflow.com/questions/38687657/service-fabric-are-multiple-service-types-allowed-in-servicemanifest-xml)

**Comment by zhenm** [comment]
Hi Ashish, 
What I want to confirm is that whether the 2 services can be listened by different type: one is owin, and the other one is just listen internal request. You can go through my question again. Thanks.

**Comment by ashishnegi** [comment]
>From my test, the internalprocess service can not be started correctly

What is failing for you ? Can you tell us what have you tried ?

**Comment by suchiagicha** [comment]
@zhenm 

Makes sure you are using different ServiceEndpoint for both. Below error is for the same (AddressAlreadyInUse).
For Remoting , default it looks for "ServiceEndpoint". 
For Owin Add new endpoint in manifest and use the same for it.
Follow below doc for adding endpoint.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources

**Comment by zhenm** [comment]
Hi Suchiagicha,

Thanks very much. This is the root cause as in my Owin service, I got the endpoint info from 'ServiceEndpoint' too. 
Thanks again,
Zhen
