### ISSUE TITLE
There was an error during download. Property=Download:1.0:1.2

### ISSUE THREAD

**Issue by w-star** [Azure/service-fabric-issues#1181]
We're sometimes seeing the following errors when deploying new versions of services

![image](https://user-images.githubusercontent.com/25615005/42844746-d834c22e-8a0b-11e8-83d7-a08ceeac8787.png)

Is there a way we can find out what exactly is causing those errors? At the moment the only solution seem to be working is deleting the application and deploying again. 

Standalone cluster (6.2.283)

**Comment by iyyappam** [comment]
We need traces to investigate this issue. Could you send us the traces along with the timestamp of this issue. Also can you check if the missing file is present in image store using "Get-ServiceFabricImageStoreContent -RemoteRelativePath <storeRelativePath>".

**Comment by w-star** [comment]
can you clarify what traces you require and where to find them? Thanks

**Comment by oanapl** [comment]
@w-star, the Service Fabric cluster emits traces [as explained here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server). You can use [StandaloneLogCollector.exe](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-package-contents) to collect traces on standalone clusters.

**Comment by oanapl** [comment]
@w-star , we haven't heard back from you in a while. I will close this issue. If you have another repro with traces, please re-open and we will take a look.
