### ISSUE TITLE
Remote socket closed while receiving connection preamble data from endpoint "168.63.129.16:62273"

### ISSUE THREAD

**Issue by ifle** [Azure/service-fabric-issues#1182]
Hi,

I try to run application as docker container and inside the container have a lot of warnings like
`Remote socket closed while receiving connection preamble data from endpoint "168.63.129.16:62273"`
I know that the related to Load Balancer probe, but what is missing, what I need to define inside container? 
 My application use to Microsoft Orleans framework that use sockets.

**Comment by davebown** [comment]
I'm having this exact problem too on a kubernetes cluster with orleans 2.0. Anybody got any advice?

**Comment by broersa** [comment]
anyone?

**Comment by MikkelHegn** [comment]
@ReubenBond - any ideas?

**Comment by Roman-Blinkov** [comment]
Same problem, 
Tried Orleans 2.0, 2.1 and 2.2-beta in kubernetes (I am using https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes )
Silo: 
warn: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101307]
      Remote socket closed while receiving connection preamble data from endpoint 10.42.0.71:44221.
Client: Exception while attempting to connect to Orleans cluster: Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request *cli/b8b763ba@d7d79fbc->S10.42.0.72:20025:278019671*stg/17/00000011@S00000011 #222: . Target History is: <S10.42.0.72:20025:278019671:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at Orleans.OutsideRuntimeClient.<>c__DisplayClass56_0.<<StartInternal>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries|56_3(Func`1 task, Func`2 shouldRetry)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
