### ISSUE TITLE
Question - Service Fabric Security Auditing

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1183]
Team,

With client certificate based security, is it possible to know from logs which actions were performed by which client certificate thumbprint ?

we are planning to use certificate based authentication. 

Consider scenarios where client with admin certificate from Sfx performs scaling up/scaling down.
Does Service fabrics logs which clients cert thumbprint has performed that action in logs ?

Thanks,
Naresh Khatri

**Comment by srrengar** [comment]
@DulebT do you know if this is tracked in events, I believe not?

**Comment by srrengar** [comment]
@aljo-microsoft do you know where this is tracked?

**Comment by aljo-microsoft** [comment]
@nareshkhatri81 

User's can not perform any actions against management endpoint other than read; so explicitly only your admin can cause this. Further as a best practice you should not be using certificates for client identity; use Azure Active Directory. This will give you auditing, and eliminate certificates that need to be managed.
