### ISSUE TITLE
Running a Mesh (Resource Model) application locally fails - vanilla implementation

### ISSUE THREAD

**Issue by knowhoper** [Azure/service-fabric-issues#1184]
Running a Mesh project in the local cluster gives the following error:

> An error occurred running C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Mesh\Scripts\Deploy-ServiceFabricApplicationResource.ps1.
> Exit Code: 1
> Connect-SFCluster : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, 
> PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
> At line:1 char:123
> + ... odule.dll'; Connect-SFCluster -Endpoint http://localhost:19080; .'C:\ ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (:) [Connect-SFCluster], FileNotFoundException
>    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.ServiceFabric.Powershell.ConnectClusterCmdlet
> 
> Unable to Verify connection to Service Fabric cluster. Connect to cluster before invoking the script using the 
> Connect-SFCluster cmdlet.
> At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Mesh\Scripts\ModuleUtilities.psm1:28 char:9
> +         throw($errMsg)
> +         ~~~~~~~~~~~~~~
>    + CategoryInfo          : OperationStopped: (Unable to Verif...Cluster cmdlet.:String) [], RuntimeException
>    + FullyQualifiedErrorId : Unable to Verify connection to Service Fabric cluster. Connect to cluster before invokin
>   g the script using the Connect-SFCluster cmdlet.
> 
>     TestConsoleApp    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.SFApp.Sdk\build\Microsoft.VisualStudio.Azure.SFApp.Targets.targets    225

Is it possible to run code via the new resource model locally?

**Comment by anantshankar17** [comment]
Hi,
Mesh applications can both be deployed locally as well as published to the cloud. Can you please check if the local dev setup is completed following this guide: https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-setup-developer-environment-sdk.

Also can you validate if no traces of the previous runtime/sdk are left behind and the cluster is indeed running locally ?

**Comment by amanbha** [comment]
@knowhoper Could you share the .net framework installed on the machine.

**Comment by amanbha** [comment]
@knowhoper I am closing this because of lack of response, please feel free to reopen if the issue still persists or you need any help.
