### ISSUE TITLE
Cluster capacity limitation

### ISSUE THREAD

**Issue by nineralpha** [Azure/service-fabric-issues#1185]
Hi
we have a six node azure cluster (Standard_A6 machines). we are trying to find the capacity of cluster.Initially we tested with our nodejs guest executable service and we were only able to host approx 100 services/node (620 services in cluster), after that number the services starts shifting continuously with error **

> There was an error during CodePackage activation.The service host terminated with exit code:3221225794

** and CPU goes from 10% to 100% for each node and cluster goes in error state although 17 GBs of memory is free on each node,same was the case with single node cluster i.e. it was able to host 100 services.
Later on we tested with dummy stateless service and result was the same except cpu remains at 10-20%.
Console redirection does not log any error.
Both guest and stateless services used for testing were idle, doing nothing.
Does anyone has any idea why this is happening?

**Comment by ashishnegi** [comment]
Your node.js app package is exiting with code : 3221225794
which means failed to find some dll. Since this is guest executable, none of SF dlls are required. So, looks like a non SF issue.

I found this node.js issue with same exit code : https://github.com/nodejs/node/issues/7064
See, if it helps.

You can also try starting 100 instances of node.js app on same node with a script.

There is good guidelines on cluster planning here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity

**Comment by nineralpha** [comment]
@ashishnegi thanks for your kind time, as i mentioned we also tested with a stateless service just containing the auto-created Visual Studio template code
protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            long iterations = 0;
            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();
                ServiceEventSource.Current.ServiceMessage(this.Context, "Working-{0}", ++iterations);
                await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
            }
        }
 and we were able to host exact same number i.e. 100 services (Singleton partition with  instance Count =1) on  single node cluster(Standard_A6 Machine).
After that number services start failing with exact same message same code (exit code:3221225794).
A lot of RAM is free (around 20GBs) CPU is at 10%.
that implies that issue is not Node.js related. Something else is going on in there.

**Comment by ashishnegi** [comment]
@nineralpha You can open an ICM for further investigation. We need to look at logs to see what is happening. 
Otherwise, for single-node-cluster and stateless app, if possible, share the logs using public endpoint or at asnegi[at]Microsoft.com. Logs will be at `Installation Directory`:`SFDevCluster\Log`

**Comment by nineralpha** [comment]
I shared the link of logs. 
further testing elaborated that when we use ServicePackageActivationMode.ExclusiveProcess we encounter the limitation but if we change it to ServicePackageActivationMode.SharedProcess we are fine to create 200+ services and even more.
but that will be not helpful in our secase as se need to keep the services exclusive.

**Comment by ashishnegi** [comment]
@nineralpha  I am looking at logs. 
To get you unblocked, can you tell, what kind of workload are you running that will require 100s of exclusive processes on a node ? How many processes in one node will serve your purpose/workload ?

Are you not hitting memory or network or disk resources limit before this problem hits you in real world ?

**Comment by ashishnegi** [comment]
@nineralpha I see that error code : `3221225794` also mean : 

```
 ERROR_DEVICE_NO_RESOURCES | The target device has insufficient resources to complete the operation. | winerror.h
```
I looked at performance counters during that time, and IO has spiked.
Remember that you are running SF's system service also on the same node, which are staterful. 

To really test it, create a 5+N node cluster, where reserve 5 nodes for SF System Services by Placement constraints. Then deploy your apps on remaining N nodes. That will give you actual picture.

**Comment by ashishnegi** [comment]
We have got similar issues before, where OS limits are rot cause. See if this [comment](https://github.com/Azure/service-fabric-issues/issues/915#issuecomment-374705113) helps you.

**Comment by masnider** [comment]
3221225794 is 0xc0000142. You're out of memory in some form. Please see here and the related issue. 

https://github.com/Azure/service-fabric-issues/issues/915#issuecomment-374705113

**Comment by ashishnegi** [comment]
@nineralpha Seems like you found the actual issue. Can we close this ?

**Comment by nineralpha** [comment]
Yeah Sure.
________________________________
