### ISSUE TITLE
6.2.301.9494 ServiceFabricNodeBootstrapAgent Response: null

### ISSUE THREAD

**Issue by rfcdejong** [Azure/service-fabric-issues#1186]
As of today all applications in our cluster became unresponsive and even the Explorer was not available. Rebooting the entire scale set didn't help, looking with RDP on the servers shows no errors and nothing really strange except in the Windows Logs under Application some Information level messages from the ServiceFabricNodeBootstrapAgent.

Every 2 minutes: Response: null

The only way the cluster was fixed was by setting the update to manual and back to an older version
6.2.274.9494 works fine

BootstrapAgent said: 
- Operation: Upgrade started
- Upgrade Agent operation: UAStartedPrepareNextState

and no more Response: null messages

**Comment by rfcdejong** [comment]
Seems it might be related to PatchOrchestrationApplication

Rolling back to an older version also results into warnings like:


Event | Warning | Unhealthy event: SourceId='System.RA', Property='Reconfiguration', HealthState='Warning', ConsiderWarningAsError=false. Reconfiguration is stuck. Waiting for response from the local replica  Reconfiguration start time: 2018-07-18 10:34:40.821. Reconfiguration phase start time: 2018-07-18 10:34:41.023.  For more information see: http://aka.ms/sfhealth
-- | -- | --

**Comment by slipvayne** [comment]
I don't know if it's related or not, but it started a few days ago... Our web apps inside fabric sometimes became stuck after a new deploy or a scale up/down.

And i suspect that it can be related with this windows update:
https://support.microsoft.com/pt-pt/help/4338815/windows-81-update-kb4338815
I have removed KB4338815 and it seems more stable now...

**Comment by masnider** [comment]
@slipvayne yeah this looks the same. I would try the updated KB or remove it to validate and let us know if that doesn't fix it.

**Comment by HakanL** [comment]
We experienced this as well. opened a ticket with Microsoft to resolve it. It was determined that the root cause was KB4338815, fixed with KB4338831. We just manually installed KB4338831 on our VMs and all our problems with the cluster went away. It was determined to be an issue with locks in http.sys introduced on July 10 via Windows Update.

**Comment by rfcdejong** [comment]
It seems the new preview patch fixed our cluster as well, and other products having a service fabric cluster within our company are also applying the patch. Seems several teams have this issue. The windows division guys did fix it quickly but they should test their patches in more environments before releasing it for the whole world. And also better communication, the Microsoft support employee's couldn't fix it and weren't even aware of this.

Closing my issue cause it was related to the patch.. not sure if Response: null is anything, but will just ignore ;)
