### ISSUE TITLE
IStatelessServiceInstance.Close wont close

### ISSUE THREAD

**Issue by mflod** [Azure/service-fabric-issues#1189]
Hi all,

The latest release of our application with Service Fabric was like a rollercoaster trip. During the upgrade, Service Fabric tried to shut down the old Gateway Service (Stateless Service), but it got stuck:

`Unhealthy event: SourceId='System.RAP', Property='IStatelessServiceInstance.CloseDuration', HealthState='Warning', ConsiderWarningAsError=false. The API IStatelessServiceInstance.Close on node _stag_2 is stuck.`

As the Warning pops up, the whole Cluster started to get Errors and Warnings and became unavailable (Also per Service Fabric Explorer). I had the luck to connect per Powershell and execute a Rollback of the current upgrade. Afterward, I had to restart the VMs which couldn't shut down the Gateway.exe.

As we managed to reproduce this issue on our test cluster (We haven't be able to reproduce this locally), we dumped the Gateway and checked the call stack:

![stuck](https://user-images.githubusercontent.com/14921031/42941298-9d1bea76-8b5c-11e8-8bad-31000a6db05b.png)

What do you think is causing the Gateway to get stuck? This issue has come sort of overnight, without changing something on the gateway.

Remarks:
- When we connect to the VM and try to kill the process directly, we get _access denied_
- We could reproduce this issue without an upgrade, just delete the service in SFE
- We are having a hard time to reproduce this issue. It doesn't have to happen on the same VM
- Mostly the Service Fabric Explorer is not able to connect to the cluster when the error happens
- We are using Service Fabric Version 6.2.301.9494 on the cluster

**Comment by pedrosaraiva** [comment]
The problem seems to be related with a windows update(kb4338815) we removed it and everything is working fine.

**Comment by masnider** [comment]
Yes that KB has caused issues with http.sys, which is impacting multiple workloads. As far as I know the Windows/TCP folks have already released a new update that addresses the issue. 

https://support.microsoft.com/en-us/help/4345424/improvements-and-fixes-windows-8-1-and-server-2012-r2

**Comment by slipvayne** [comment]
Yes. Probably related issue:
https://github.com/Azure/service-fabric-issues/issues/1186

**Comment by MedAnd** [comment]
Hi @masnider, apart from internal SF customers at MS, think we were one of the first customers to hit this issue on Saturday... working with Azure Support can confirm KB4338815 fixes the issue... root cause being in TCP/IP stack (we use kestrel which I believe does not use http.sys) but we were affected nonetheless.

**Comment by mflod** [comment]
A very big thanks! We can also affirmative that the new KB resolves the issue.
