### ISSUE TITLE
"Enable Streaming Traces" and other actions not available in VS 2017 RC2 Cloud Explorer

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#119]
VS 2015:
![image](https://cloud.githubusercontent.com/assets/496737/21679410/99e0c4cc-d34c-11e6-8725-08e958756319.png)

VS 2017 RC2:
![image](https://cloud.githubusercontent.com/assets/496737/21679454/dc4eaeaa-d34c-11e6-9303-cd1bda994b32.png)

PS - it would be nice if you enable this feature for any VM/VMSS, not just SF.

**Comment by MikkelHegn** [comment]
Closing as this just got too old. I'm pretty sure this got fixed back in the days...
