### ISSUE TITLE
Service Fabric AD Authentication Issue

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1193]
Team,

We are trying to protect SF Cluster with AD groups. Users who will be part of AD groups will be able to access Sfx.

currently we are seeing in our dev environment that SF is not able to do lookup of groups which are outside of current domain where SF runtime is deployed.

is it possible for SF to provide some option by which we can provide where to do lookup in AD like which domain ?

Thanks,
Naresh Khatri

**Comment by dragav** [comment]
The security settings are declarative - the SF runtime doesn't test/check whether the accounts or groups you specify exist, or whether there exists trust between domains. That means you could lock yourself out of the cluster fairly easily.
I don't think we're inclined to invest much more in Kerberos-based authentication; we have plenty of options with X509- and AAD- (OAuth2) based authentication.
