### ISSUE TITLE
Periodic Alerts happening with Service Fabric Clusters

### ISSUE THREAD

**Issue by michaelseto** [Azure/service-fabric-issues#1194]
In the last few hours I have started to receive numerous alerts (from Zabbix) over my SF cluster nodes -

- Service Fabric HTTP Gateway, api, explorer port (19080) not in LISTEN state
- Service Fabric Client Connection port (19000) not in LISTEN state
- Service fabric FileStoreService.exe process is not running
- Service Fabric US process (FabricUS.exe) is not running
- Service Fabric FabricFAS.exe process is not running

This is happening across random nodes in 2 different SF clusters. I have RDP'd into these nodes and investigated the Event Viewer to no avail.

Can someone please help me with some direction as to what could possibly be happening? Other things to look at? SF is kind of a black box to me.

Thank you!

**Comment by masnider** [comment]
Are the machines just getting restarted due to maintenance? What's SFX list as the node uptimes?

**Comment by michaelseto** [comment]
This is a frequent occurrence, how do I know if it’s being caused by maintenance? I will pull the uptimes.

**Comment by michaelseto** [comment]
node1 - 24.05:24:34.0
node2 - 2.01:26:28.0
node3 - 1.18:13:18.0
node4 - 22.19:45:27.0
node5 - 0.21:23:27.0

**Comment by aljo-microsoft** [comment]
@michaelseto 

My understanding is you don't actually have LiveSite issue with a SF application?

If you have a LiveSite issue, please leverage a support option to resolve your issue:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

Properly configuring rules for an unsupported 3rd party monitoring solution (https://www.zabbix.com/), to know what common behavior distributed system orchestrators perform that it should ignore, is something your vendor would need to support (its their configurations for their systems rules); in Azure Application Insights is a recommended monitoring solution, but plenty of 3rd party solutions can deliver value from their implemented Azure support (Dynatrace being one whom has a VMSS extension for native Azure Compute deployment/configuration of their agents).

If you have any issue being successful with our documentation, please open an issue against the correct documentation you followed that isn't helping you be successful; so I can take ownership of that issue, and deliver content to help all users.

If you desire additional Service Fabric supportability content in addition to our 1000+ pages of documentation, please check out Azure's channel for Service Fabric videos:

https://www.youtube.com/user/windowsazure/search?query=service+fabric

Or any of the other videos published, like the I gave on best practices: 
https://www.youtube.com/watch?v=uVJx_WJ3xbY&t=14s
