### ISSUE TITLE
[Question] Multi region cluster or DNS failover

### ISSUE THREAD

**Issue by Franklin89** [Azure/service-fabric-issues#1198]
Hi

What is the best practice to implement multi regional clusters? Would it make more sense to create 1 cluster per datacenter and incase one service is not available route to the second datacenter through DNS / Loadbalancing or create 1 cluster with hosts from both datacenters?

Thanks for the support

**Comment by suhuruli** [comment]
In Azure, using one cluster per region is the recommended approach.

**Comment by Franklin89** [comment]
okay thank you
