### ISSUE TITLE
Visual Studio Update 15.7.4 and Service Fabric MSBuild 1.6.6

### ISSUE THREAD

**Issue by johanstenberg92** [Azure/service-fabric-issues#1199]
Hi,

After updating to VS 15.7.4, I get this prompt when I open my project:

![image](https://user-images.githubusercontent.com/1280550/43247773-034866cc-90b6-11e8-95b2-ee565ba5eefc.png)

If I press "Yes" in the prompt, a bunch of modifications happens to my SFPROJ and a new packages.config file including a single  reference to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.6`  was added. We use some central props and targets files so I removed these changes but kept the seemingly important one:

`<SupportedMSBuildNuGetPackageVersion>1.6.6</SupportedMSBuildNuGetPackageVersion>`

We also have a central packages solution so I deleted the generated packages.config, the SFPROJ reference to the packages.config and updated our central packages solution with the new version. However, when re-starting VS the prompt still came up - that the application has an incompatible nuget version installed.

I found out that if I re-add the packages.config file, without even referencing it, it started working!

It seems like VS is looking for a packages.config file, even if it is not explicitly referenced in SFPROJ and only then allowing the project to load?

**Comment by ravipal** [comment]
@johanstenberg92 we use an Nuget API from IVsPackageInstallerServices which gets the installed nuget version. If packages.config is missing, then this API returns null and we treat it as the nuget package is not installed as a result we prompt to install the nuget package. This is a recent change to automatically update *sfproj file, if the latest nuget package is installed. But this breaks the scenario if the nuget package is managed externally. Looks like you already found the workaround of adding the packages.config file. We also added a MS build property "DoNotUpdateNuGetImport" to disable such automatic update in VS 15.8.
