### ISSUE TITLE
Upload and Register packages missing from REST Api documentation

### ISSUE THREAD

**Issue by andersosthus** [Azure/service-fabric-issues#120]
Hi,

Looking over the REST API documentation (https://docs.microsoft.com/en-us/rest/api/servicefabric/) I am unable to find any information about how to implement uploading and registering application packages through the REST API.

**Comment by oanapl** [comment]
We don't have a REST equivalent for copy application package command, but you can use [Upload a file to image store](https://docs.microsoft.com/rest/api/servicefabric/upload-a-file-to-image-store) to upload files from your package one by one.
To provision, you can use [Provision application](https://docs.microsoft.com/rest/api/servicefabric/provision-an-application).
