### ISSUE TITLE
Service Fabric local cluster corrupt and wont start

### ISSUE THREAD

**Issue by paulsaxton** [Azure/service-fabric-issues#1205]
I have installed Service Fabric and although the cluster explorer has installed I have noticed that the standard SFDevCluster folder has not been created

The error message in the local cluster manager is useless - error occurred resetting cluster

I then delved into the powershell side and got the message below

I am out of ideas and getting pretty frustrated! This has installed loads of other times on other machines without any issues at all

I have uninstalled and reinstalled multiple times

I have added Service Fabric to Visual Studio

    PS C:\program files\microsoft sdks\service fabric\clustersetup> .\DevClusterSetup.ps1
A parameter cannot be found that matches parameter name 'Refresh'.
Get-Module : A parameter cannot be found that matches parameter name 'Refresh'.
At C:\program files\microsoft sdks\service fabric\clustersetup\DevClusterSetup.ps1:54 char:35
+ Get-Module -ListAvailable -Refresh <<<<  --quiet *>$null
    + CategoryInfo          : InvalidArgument: (:) [Get-Module], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetModuleCommand

PS C:\program files\microsoft sdks\service fabric\clustersetup>
I have even tried to copy my service fabric files over to the machine and that doesnt work either

Has anyone ever had anything like this? Please note that these issues are occurring outside of Visual Studio (2017)

Paul

**Comment by oanapl** [comment]
Did you try to update Windows Powershell on the box? Try to download [PowerShell 5.0](https://www.microsoft.com/en-us/download/details.aspx?id=50395) from the Microsoft Download Center.

**Comment by paulsaxton** [comment]
What do I do then? The cluster manager is useless it just says error resetting cluster and error starting cluster

I was guessing going into the power shell folder I don’t even know if I am supposed to pass any parameters

This is a really frustrating no uninstalls or reinstalls make any difference

Do update and try the local cluster again?

Paul

Sent from my iPhone



[cid:image0a681e.PNG@c490b611.41a3c26f]<http://>
Paul Saxton  Systems Architect
Inspired Energy PLC
29 Progress Business Park, Orders Lane, Kirkham, Preston, Lancashire, PR4 2TZ
Tel: +44 (0) 1772 689 250  Fax:  +44 (0) 1772 689 251
DD: 02084662907<tel:02084662907>  Mob: 07967964125<tel:07967964125>
Email: Paul.Saxton@inspiredenergy.co.uk<mailto:Paul.Saxton@inspiredenergy.co.uk>

Email<mailto:hello@inspiredenergy.co.uk> | Website<http://inspiredenergy.co.uk> | Twitter<https://twitter.com/InspiredEnergy> | LinkedIn<http://www.linkedin.com/company/inspired-energy-solutions>
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you have received this email in error please notify the sender. Please note that views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. The recipient should check this email and any (all) attachments for the presence of viruses. Inspired Energy PLC accepts no liability for any damage caused by viruses transmitted by this email.
[Footer]<http://>


On 30 Jul 2018, at 21:57, Oana Platon <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try to update Windows Powershell on the box? Try to download PowerShell 5.0<https://www.microsoft.com/en-us/download/details.aspx?id=50395> from the Microsoft Download Center.

**Comment by oanapl** [comment]
@paulsaxton , see [instructions for setting up the cluster](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started), especially Powershell specific ones. My suggestion is to check what powershell you have on the box (outside and unrelated to Service Fabric), and update it if needed. Then follow the instructions in that article.

The error you showed above is not coming directly from Service Fabric. Try running this from a Powershell window and get it to work:
```powershell
Get-Module -ListAvailable -Refresh
```

**Comment by oanapl** [comment]
@paulsaxton , any update? Are you still experiencing this issue?

**Comment by oanapl** [comment]
@paulsaxton , sorry to hear that this is not resolved. I will close this issue, please re-open if you are still blocked.
