### ISSUE TITLE
Endpoint with multiple WCF ServiceInstanceListeners not accessible through service fabric reverse proxy

### ISSUE THREAD

**Issue by tomheijmans** [Azure/service-fabric-issues#1206]
I got an issue creating multiple ServiceInstanceListeners for WCF inside a service fabric application. I've created a simple demo application here: https://github.com/tomheijmans/WcfListenersDemo. 

My stateless1 service contains two WCF services (service1, service2). They are registered in the Stateless1 service (https://github.com/tomheijmans/WcfListenersDemo/blob/master/Stateless1/Stateless1.cs). As you can see the ServiceEndpointListeners are registered using the urls of the same endpoint but they got a different path suffix.  

When I run the project it got two endpoints; http://localhost:30043/service1, http://localhost:30043/service2. I can visit the mex endpoint for both of them ; http://localhost:30043/service1/mex, http://localhost:30043/service2/mex. How can I visit them through the SF reverse proxy? It looks like the suffix in the URL is ignored when accessing it through the reverse proxy. I would expect the mex endpoint can be found at http://localhost:19081/WcfListenersDemo/Stateless1/service1/mex and http://localhost:19081/WcfListenersDemo/Stateless1/service2/mex but that doesn't work. See also the reverse proxy log for this request. It is always resolving an URL for service1:

`{
  "Timestamp": "2018-07-30T19:31:32.570834+02:00",
  "ProviderName": "Microsoft-ServiceFabric",
  "Id": 51477,
  "Message": "a7fce2dc-3f44-43fd-a743-7ebc42ece843 Request url = http://localhost:19081/WcfListenersDemo/Stateless1/service2/mex, verb = GET, remote (client) address = ::1, resolved service url = http://[machine name]:30043/service1/service2/mex, request processing start time = 07/30/2018 19:31:32 ",
  "ProcessId": 12956,
  "Level": "Informational",
  "Keywords": "0x1000000000000021",
  "EventName": "ReverseProxy",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "traceId": "a7fce2dc-3f44-43fd-a743-7ebc42ece843",
    "requestUrl": "http://localhost:19081/WcfListenersDemo/Stateless1/service2/mex",
    "verb": "GET",
    "remoteAddress": "::1",
    "resolvedServiceUrl": "http://[machine name]:30043/service1/service2/mex",
    "requestStartTime": "\"\/Date(1532971892562)\/\""
  }
}`

When I go to http://localhost:19081/WcfListenersDemo/Stateless1/mex it will resolve the mex endpoint of service1 as you can see in the logging:

`{
  "Timestamp": "2018-07-30T19:23:32.1817367+02:00",
  "ProviderName": "Microsoft-ServiceFabric",
  "Id": 51477,
  "Message": "81b9f0c1-dff8-47c9-9ade-acedeeaada1f Request url = http://localhost:19081/WcfListenersDemo/Stateless1/mex?listenerName=service1, verb = GET, remote (client) address = ::1, resolved service url = http://[machine name]:30043/service1/mex?listenerName=service1, request processing start time = 07/30/2018 19:23:32 ",
  "ProcessId": 12956,
  "Level": "Informational",
  "Keywords": "0x1000000000000021",
  "EventName": "ReverseProxy",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "traceId": "81b9f0c1-dff8-47c9-9ade-acedeeaada1f",
    "requestUrl": "http://localhost:19081/WcfListenersDemo/Stateless1/mex?listenerName=service1",
    "verb": "GET",
    "remoteAddress": "::1",
    "resolvedServiceUrl": "http://[machine name]:30043/service1/mex?listenerName=service1",
    "requestStartTime": "\"\/Date(1532971412179)\/\""
  }
}`

It always resolves an URL based on the first listener (in alphabetical order) for what I have seen after some test cases. Should the reverse proxy ignore the path suffix or am I doing something wrong? 

Service Fabric SDK version 3.2.162

**Comment by tomheijmans** [comment]
We've found the solution for our problem. A colleague pointed me to the documentation of the reverseproxy where https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#uri-format-for-addressing-services-by-using-the-reverse-proxy. It says you can access the listener by adding the ListenerName=<listenerName> query parameter. 
> http(s)://<Cluster FQDN | internal IP>:Port/<ServiceInstanceName>/<Suffix path>?PartitionKey=<key>&PartitionKind=<partitionkind>&ListenerName=<listenerName>&TargetReplicaSelector=<targetReplicaSelector>&Timeout=<timeout_in_seconds>

Notice the the query string parameter is casesensitive. That got me stuck for a while.

**Comment by kavyako** [comment]
Closing based on above comment.

**Comment by julioas09** [comment]
I am in a very similar situation, but that solution is not working. I am working on a 5 node on-prem Windows Cluster. I have a service with 5 endpoints (5 WCF listeners). 
![ss](https://user-images.githubusercontent.com/3543529/52965179-81645480-33a4-11e9-81e1-f013d8aa96a7.jpg)

I I navigate to those url (ex: http://ibsfabfe01pru:20597/CheckElegibility) it does work. However, when trying to access through Reverse Proxy I get a 400 ERROR. Here's the URL I'm trying for this case:

http://ibsfabfe01pru:19081/AppName/ServiceName?ListenerName=CheckElegibility

Any ideas why can this be happening?
