### ISSUE TITLE
Question - Service Fabric Containers monitoring with Dynatrace

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1207]
Team,

we saw couple of articles related to dynatrace integration with service fabric.

https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/26/monitoring-service-fabric-clusters-with-dynatrace/

We have setup dyntrace agents on nodes in onprem - cluster.
We are able to see containers running in cluster getting displayed in dynatrace.
we have couple of questions.

(1) how does monitoring of service fabric works ?  Dynatrace agent automatically looks into ETW events of service fabric and send those to Dynatrace server.
where can i see those diagnostic information in Dynatrace.

(2) how can i see platform errors happening in service fabric in dynatrace ?

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
Hi Patrick
I would like to know more about event flow plugin. If I can test with dynatrace, it would be nice.

Thanks
Naresh

**Comment by nareshkhatri81** [comment]
@dtPaTh 
You said above something is coming up with dynatrace agent 149 with containers.
what are different features are going to be added ?
is there somewhere roadmap published where we can see list of features coming up with windows containers/service fabric ?

We are seeing few issues with windows containers like
(1) IIS logs of windows containers are not discovered by dynatrace.
(2) Docker deamons logs are not getting displayed in Log viewer.
(3) Perf counters of windows containers were getting displayed initially but it stopped displayed.

What is best way to reach out to dynatrace team for issues ?

Currently i am running trail version.

Thanks,
naresh khatri

**Comment by dtPaTh** [comment]
Hi naresh, 
looks like you already catched an early adopter ring with your trial account as you have the windows container injection available. 

I suggest to catch up with our in-product chat team to get you onboarded in dynatrace. I'll also send over an email so we can have a deeper conversation about roadmap and the event-flow plugin.

Best
Patrick

**Comment by nareshkhatri81** [comment]
Hi Patrick,

could you provide access to preview event flow plugin for Service fabric ETW logs ?

Thanks,
naresh
