### ISSUE TITLE
'The "DeployableServiceProjectReferences" parameter is not supported by the "GetServiceProjectReferences" task' exception

### ISSUE THREAD

**Issue by Indreshbn** [Azure/service-fabric-issues#121]
We are getting 'The "DeployableServiceProjectReferences" parameter is not supported by the "GetServiceProjectReferences"' error when we upgraded to Service Fabric runtime 5.4.145. We verified "Microsoft.VisualStudio.Azure.Fabric.Application.targets" file and it contains "DeployableServiceProjectReferences" parameter. 

Below is the command that we are executing for which build is failing.

started package_service_fabric_app "Honeywell.Usp.Tenant" "E:\builds\"

Command Name: msbuild

Arguments: "E:\builds\src\ServiceFabricPrj.sfproj" /t:package /p:PackageLocation=E:\builds\packages\ /p:Configuration=debug /p:VisualStudioVersion=14.0 /m

Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started .

1>Project "E:\builds\src\ServiceFabricPrj.sfproj" on node 1 (package target(s)).

1>E:\builds\src\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets(87,7): error MSB4131: The "DeployableServiceProjectReferences" parameter is not supported by the "GetServiceProjectReferences" task. Verify the parameter exists on the task, and it is a gettable public instance property. [E:\builds\src\ServiceFabricPrj.sfproj]

1>Done Building Project "E:\builds\src\ServiceFabricPrj.sfproj" (package target(s)) -- FAILED.

**Comment by MikkelHegn** [comment]
Thanks for reporting this. We will investigate and report back here.

**Comment by dbreshears** [comment]
@Indreshbn ,   Are you able to right click on the Service Fabric Project in the Visual Studio Solution and select "Package" and does that also fail?    Does this occur for all new projects or just the existing project/solution?     Can you turn up the verbosity with MSBuild and upload the log.   Use "/verbosity:d" on command line.

**Comment by MikkelHegn** [comment]
Closing
