### ISSUE TITLE
Should report Failure/Rollback instead of Succeeded after app upgrade rollbacked

### ISSUE THREAD

**Issue by juniwang** [Azure/service-fabric-issues#1214]
We are using [resource management template](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-fabric/service-fabric-application-arm-resource.md#add-a-new-application-to-your-resource-manager-template) to upgrade our Service Fabric applications. The application will either be upgraded or rollbacked automatically. What troubles us in the upgading is that we still get a `Succeeded` Azure deployment even when it's rollbacked actually.  We are expecting a state like Failed or Rollbacked so that we know something wrong happened.  Please kindly sugget if I miss anything.

**Comment by juniwang** [comment]
any feedback?

**Comment by vaishnavk** [comment]
@juniwang : This might be a bug. We will look into it. 

Do you have a specific instance where this happened? The following details will be helpful.

Region Name
Timestamp
Application ResourceId
Correlation Id

**Comment by juniwang** [comment]
I'm sorry that tje problematic SF was already removed.  I wish I could help but I can only find these in emails:

Region : West US
Resource group: sfsignalrprodwestus
Reource Id: /subscriptions/752c04e5-92cd-4483-ad8f-e1417ba935b0/resourcegroups/sfsignalrprodwestus/providers/Microsoft.ServiceFabric/clusters/signalrprod
time of the upgrade: 07/19/2018 01:32:00 UTC - 07/19/2018 01:57:48 UTC

We were upgrading our application from `1.0.544.1` to `1.0.554.1`. We received a email from EV2 indicating it's successfull. We can also find on Activity logs the deployment was successful. However, telling from SF explorer, the app version was still `1.0.544.1`. We also tried to search the SF logs in the `sflogsXXX` storage account, and we found clear evidence it was rollbacked.


Resource Group | Region | Service Resource | Action | Resource Operation | Status | Start Time | End Time | Duration
-- | -- | -- | -- | -- | -- | -- | -- | --
sfsignalrprodwestus | westus | RP-WestUS | Deploy | Name: signalrprod/AzSignalR.RP   Type: Microsoft.ServiceFabric/clusters/applications | Succeeded | 07/19/2018 01:32:00 UTC | 07/19/2018 01:57:48 UTC | 0 hr 25 min 47 sec
sfsignalrprodwestus | westus|RP-WestUS | Deploy | Name:   signalrprod/AzSignalR.ServiceFabricType/1.0.554.1   Type: Microsoft.ServiceFabric/clusters/applicationTypes/versions | Succeeded | 07/19/2018 01:32:00 UTC | 07/19/2018 01:57:48 UTC | 0 hr 25 min 47 sec
sfsignalrprodwestus| westus |RP-WestUS | Deploy | Name:   signalrprod/AzSignalR.ServiceFabricType   Type: Microsoft.ServiceFabric/clusters/applicationTypes | Succeeded | 07/19/2018 01:32:00 UTC | 07/19/2018 01:57:48 UTC | 0 hr 25 min 47 sec

**Comment by vaishnavk** [comment]
I don't think logs will be available for that time range now. Please re-open if see this issue again.
