### ISSUE TITLE
FABRIC_E_DNS_SERVICE_NOT_FOUND

### ISSUE THREAD

**Issue by thuru** [Azure/service-fabric-issues#1216]
Do we need DNS service running in order to deploy an application. 
In a cluster in Azure, I have uploaded the package to image store and registered the application type. But when I try to create an app instance from Powershell I get the following error.

Upload to Image Store succeeded
Register application type succeeded
New-ServiceFabricApplication : Application type and version not found
At line:11 char:1
+ New-ServiceFabricApplication -ApplicationName fabric:/MyApplication - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [New-ServiceFabricApplication], FabricElementNotFoundExc 
   eption
    + FullyQualifiedErrorId : CreateApplicationInstanceErrorId,Microsoft.ServiceFabric.Powershell.NewApplication

When I try to create the instance from the SF Explorer it shows below 

![image](https://user-images.githubusercontent.com/10653957/43731316-b9967e8c-99cb-11e8-8eb9-6b2629b080d4.png)

I disabled the DNS Service when setting this cluster in Azure. But is it mandatory to have DNS service in order to create application instances ? Is there any documentation on this ?

The same application is deployed successfully in another cluster where DNS service is running.

**Comment by masnider** [comment]
DNS is not required. Can you share the rest of the create New app command as well as the app manifest?

**Comment by masnider** [comment]
Hi @thuru were you able to get past this? 

We haven't heard back from you for a bit, so I'm going to close this down for now. If you are still having problems and can provide the information I asked for above, that would be great. If you're still having problems or having other issues, please reopen here or file a new incident and we can help out.
