### ISSUE TITLE
Question: Does the Actor Model disable USING statements disposal?

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#1217]
When implementing service fabric actors, does the SDK somewhere disable the GC from collecting `using `statement variables? specifically EF contexts/connections? should i have known this from the start?

**Comment by ashishnegi** [comment]
@ConX-Ryan What kind of errors are you seeing that lead to your question ? 
Can you show some sample code where you are seeing these errors ?

**Comment by ConX-Ryan** [comment]
pre 6.2 i was using(var db = new dbcontext()) inside the actors this now causes a connection leak it seems the using dispose is ignored

**Comment by amanbha** [comment]
@ConX-Ryan Could you point to some code sample? In which Actor method you see this happening (eg. OnActivate, OnDeactivate or your Actor methods). SDK doesn't changes the GC behavior.

**Comment by ConX-Ryan** [comment]
my actor spins up and subscribes to a service bus topic, during the OnMessage event i make a db connection in a using statement to an azure sql instance. this connection is never cleaned up

**Comment by amanbha** [comment]
@ConX-Ryan Actors runtime don't modify this behavior, Is the Dispose method of your dbcontext disposing correctly?

**Comment by ConX-Ryan** [comment]
same use in other services is working fine

**Comment by ConX-Ryan** [comment]
Hmmm good point about the turn based concurrency, I didn't think much of that thought it was similar to the Reminder or Timer events so didn't see a problem.
