### ISSUE TITLE
Service Fabric New-AzureRmServiceFabricCluster generates a new certificate even when user passes -CertificateFile

### ISSUE THREAD

**Issue by uditjh** [Azure/service-fabric-issues#1218]
@juhacket @ChackDan  @vaishnavk  @masnider  
Opening this as a new issue related to issue 1022 which was closed earlier.
[1022](https://github.com/Azure/service-fabric-issues/issues/1022)

I upgraded to AzureRM 6.6 and still cant follow the documentation listed [here](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/new-azurermservicefabriccluster?view=azurermps-5.7.0#examples) Example 2 to resolve my issue of being able to use my own certificate when I standup service fabric cluster for client to node security.
(Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'AzureRM' }) ` | Select Version, Name, Author, PowerShellVersion | Format-List;

Version : 6.6.0
Name : AzureRM
Author : Microsoft Corporation
PowerShellVersion : 5.0
New-AzureRmServiceFabricCluster -ResourceGroupName $rgName -TemplateFile $templatePath -ParameterFile $parametersPath -SecretIdentifier $secretId
New-AzureRmServiceFabricCluster : Please specify the -certificateSubjectName
At line:1 char:1

New-AzureRmServiceFabricCluster -ResourceGroupName $rgName -TemplateF ...
  + CategoryInfo          : CloseError: (:) [New-AzureRmServiceFabricCluster], PSInvalidOperationException
  + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster

New-AzureRmServiceFabricCluster -ResourceGroupName $rgName -TemplateFile $templatePath -ParameterFile $parametersPath -SecretIdentifier $secretId -CertificateSubjectName $certSubject
New-AzureRmServiceFabricCluster : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1

New-AzureRmServiceFabricCluster -ResourceGroupName $rgName -TemplateF ...
  + CategoryInfo          : InvalidArgument: (:) [New-AzureRmServiceFabricCluster], ParameterBindingException
  + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster

**Comment by juhacket** [comment]
Can you send me your template file? It seems there is a missing value that is triggering this error.

"apiVersion": "[variables('publicIPApiVersion')]",
      "type": "Microsoft.Network/publicIPAddresses",
      "name": "[concat(variables('lbIPName'),'-',variables('vmNodeType0Name'))]",
      "location": "[variables('computeLocation')]",
      "properties": {
        "dnsSettings": {
          **"domainNameLabel": "[variables('dnsName')]"**

**Comment by uditjh** [comment]
@juhacket  whats your email address?

**Comment by juhacket** [comment]
Can you just paste a snippet of your template here? Specifically, the “Microsoft.Network/publicIPAddresses” resource.

**Comment by uditjh** [comment]
I dont see this resource in my template. I'm copying the ServiceFabric resource but let me know if you need anything else.
        {
            "apiVersion": "2018-02-01",
            "type": "Microsoft.ServiceFabric/clusters",
            "name": "[parameters('SF-ClusterName')]",
            "location": "[parameters('SF-ClusterLocation')]",
            "dependsOn": [
                "[concat('Microsoft.Storage/storageAccounts/', parameters('SupportLog-AccountName'))]"
            ],
            "properties": {
                "addonFeatures": [
                    "DnsService",
                    "ResourceMonitorService"
                ],
                "certificate": {
                    "thumbprint": "[parameters('certificateThumbprint')]",
                    "thumbprintSecondary": "[parameters('secCertificateThumbprint')]",
                    "x509StoreName": "[parameters('SF-ClusterCertificateStore')]"
                },
                "clientCertificateCommonNames": [],
                "clientCertificateThumbprints": [],
                "azureActiveDirectory": {
                    "tenantId": "[parameters('aadTenantId')]",
                    "clusterApplication": "[parameters('aadClusterApplicationId')]",
                    "clientApplication": "[parameters('aadClientApplicationId')]"
                },
                "clusterState": "Default",
                "diagnosticsStorageAccountConfig": {
                    "blobEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', parameters('SupportLog-AccountName')), variables('storageApiVersion')).primaryEndpoints.blob]",
                    "protectedAccountKeyName": "StorageAccountKey1",
                    "queueEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', parameters('SupportLog-AccountName')), variables('storageApiVersion')).primaryEndpoints.queue]",
                    "storageAccountName": "[parameters('SupportLog-AccountName')]",
                    "tableEndpoint": "[reference(concat('Microsoft.Storage/storageAccounts/', parameters('SupportLog-AccountName')), variables('storageApiVersion')).primaryEndpoints.table]"
                },
                "fabricSettings": [
                    {
                        "name": "Security",
                        "parameters": [
                            {
                                "name": "ClusterProtectionLevel",
                                "value": "[parameters('SF-ClusterProtectionLevel')]"
                            }
                        ]
                    },
                    {
                        "name": "DnsService",
                        "parameters": [
                            {
                                "name": "IsEnabled",
                                "value": "true"
                            }
                        ]
                    },
                    {
                        "name": "ResourceMonitorService",
                        "parameters": [
                            {
                                "name": "IsEnabled",
                                "value": "true"
                            }
                        ]
                    },
                    {
                        "name": "Hosting",
                        "parameters": [
                            {
                                "name": "IPProviderEnabled",
                                "value": "true"
                            },
                            {
                                "name": "PruneContainerImages",
                                "value": "True"
                            },
                            {
                                "name": "ContainerServiceArguments",
                                "value": " "
                            }
                        ]
                    },
                    {
                        "name": "Trace/Etw",
                        "parameters": [
                            {
                                "name": "Level",
                                "value": "5"
                            }
                        ]
                    },
                    {
                        "name": "Setup",
                        "parameters": [
                            {
                                "name": "ContainerNetworkSetup",
                                "value": "true"
                            }
                        ]
                    }
                ],
                "managementEndpoint": "[variables('SF-ManagementEndpoint')]",
                "nodeTypes": [
                    {
                        "name": "[parameters('PrimaryNT-TypeName')]",
                        "applicationPorts": {
                            "endPort": "[parameters('SF-ApplicationEndPort')]",
                            "startPort": "[parameters('SF-ApplicationStartPort')]"
                        },
                        "clientConnectionEndpointPort": "[parameters('SF-TcpGatewayPort')]",
                        "durabilityLevel": "[parameters('SF-DurabilityLevel')]",
                        "ephemeralPorts": {
                            "endPort": "[parameters('SF-EphemeralEndPort')]",
                            "startPort": "[parameters('SF-EphemeralStartPort')]"
                        },
                        "httpGatewayEndpointPort": "[parameters('SF-HttpGatewayPort')]",
                        "isPrimary": true,
                        "vmInstanceCount": "[parameters('PrimaryNT-Count')]"
                    },
                    {
                        "name": "[parameters('WebNT-TypeName')]",
                        "applicationPorts": {
                            "endPort": "[parameters('SF-ApplicationEndPort')]",
                            "startPort": "[parameters('SF-ApplicationStartPort')]"
                        },
                        "clientConnectionEndpointPort": "[parameters('SF-TcpGatewayPort')]",
                        "durabilityLevel": "[parameters('SF-DurabilityLevel')]",
                        "ephemeralPorts": {
                            "endPort": "[parameters('SF-EphemeralEndPort')]",
                            "startPort": "[parameters('SF-EphemeralStartPort')]"
                        },
                        "httpGatewayEndpointPort": "[parameters('SF-HttpGatewayPort')]",
                        "isPrimary": false,
                        "vmInstanceCount": "[parameters('WebNT-Count')]"
                    }
                ],
                "provisioningState": "Default",
                "reliabilityLevel": "[parameters('SF-ReliabilityLevel')]",
                "upgradeMode": "Manual",
                "vmImage": "Windows"
            },
            "tags": "[variables('Tags')]"
        }

**Comment by juhacket** [comment]
To create a cluster your template must include all required resources (network, storage, etc.). Please see this sample: https://github.com/Azure/azure-quickstart-templates/tree/master/service-fabric-secure-cluster-5-node-1-nodetype.

**Comment by uditjh** [comment]
Hello Justin,
Sorry for late reply but I do have everything in the template and it works fine except for the part where I have to use a custom existing certificate. I only pasted the Service Fabric resource as I thought there is something missing in it.

**Comment by uditjh** [comment]
@juhacket Do you want me to share the entire json file? its works fine and we have been using it to spin up multiple clusters along with other azure resources.

**Comment by ChackDan** [comment]
Alex and Justin can help with that.

**Comment by aljo-microsoft** [comment]
@uditjh 

Use a group deployment like:

az group deployment create -g <YOUR RG> --name <YOUR DEPLOYMENT NAME> --template-file <AzureDeploy.json> --parameters @AzureDeploy.Parameters.json

I demonstrate this in my daily build script (actively being developed but using a precreated certificate works) that can be found here:

https://github.com/aljo-microsoft/demo/blob/master/ServiceFabricBestPractices.py

**Comment by aljo-microsoft** [comment]
@uditjh Although I closed this, please reach out to me if this process is still confusing?
