### ISSUE TITLE
RegisterServiceNotificationFilterAsync for 'root name' fails.

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#122]
Registering for notifications for 'root name' fails, with a FabricException:

> Invalid name URI.

According to the [docs ](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.servicenotificationfilterdescription) it should work.

> Name 
> Gets the name for which service notifications should be delivered. The name must be in the fabric:/ scheme. The root name (fabric:/) is allowed.

Sample code to reproduce:

``` 
var filterDescription = new ServiceNotificationFilterDescription
{
	Name = new Uri("fabric:/"),
	MatchNamePrefix = true,
	MatchPrimaryChangeOnly = true
};
long id = await _fabricClient.ServiceManager.RegisterServiceNotificationFilterAsync(filterDescription);

```

**Comment by alexwun** [comment]
Use "fabric:" rather than "fabric:/" for the root URI (remove the trailing slash). We'll update the docs - thanks!

**Comment by oanapl** [comment]
This has been fixed. See [ServiceNotificationFilterDescription.Name](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.servicenotificationfilterdescription.name?view=azure-dotnet)

**Comment by nineralpha** [comment]
for me when one instance is reset sometime event is raised once while sometimes it is raised twice??
logging looks like this

Change Occured1/15/2018 6:49:05 PM

Change Occured1/15/2018 6:50:05 PM

Change Occured1/15/2018 6:50:50 PM
Change Occured1/15/2018 6:50:55 PM

Change Occured1/15/2018 6:51:45 PM

Change Occured1/15/2018 6:52:05 PM
Change Occured1/15/2018 6:52:10 PM

Change Occured1/15/2018 6:52:40 PM

Change Occured1/15/2018 6:53:00 PM
Change Occured1/15/2018 6:53:05 PM

**Comment by oanapl** [comment]
@nineralpha , this is a new issue, I recommend starting another thread.
Are the changes raised the same? Or is the first change for the previous instance closing and the second for the new instance started? Or for stateful services, first notice is for one replica going down and the second for new replica being added?

**Comment by nineralpha** [comment]
@oanapl Already did that. 
https://github.com/Azure/service-fabric-issues/issues/760
