### ISSUE TITLE
Publish SF app from VS2017 to unsecured cluster 

### ISSUE THREAD

**Issue by krvladislav** [Azure/service-fabric-issues#1223]
I try to make an Service Fabric app publication from Visual Studio and get Publish button disabled with a warning "The selected cluster must have a server certificate which must be installed on this machine to publish a container application"

![untitled](https://user-images.githubusercontent.com/886098/43937483-1d5640d8-9c88-11e8-9766-9de19262255d.png)

Meanwhile deployment via TFS job or Deploy-FabricApplication.ps1 works excellent.

I didn't find any mention in the docs about this restriction. Do I need some tuning to make it work?

**Comment by MikkelHegn** [comment]
Hi @krvladislav , the title of this issue implies that the cluster management endpoints run unsecured, but it looks like VS detects that it's secured. Can you please validate if the management endpoint has been secured in the cluster?

**Comment by krvladislav** [comment]
Hi @MikkelHegn !

I use standard ClusterConfig.Unsecure.MultiMachine.json with "addOnFeatures": [ "DnsService" ]. 
[ClusterConfig.json](https://github.com/Azure/service-fabric-issues/files/2290074/ClusterConfig.json.txt)
There is no "security" properties.

Also manifest shows to me:

     <Section Name="Security">
      <Parameter Name="ClientRoleEnabled" Value="false" />
      <Parameter Name="ClusterCredentialType" Value="None" />
      <Parameter Name="DisableFirewallRuleForDomainProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPrivateProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPublicProfile" Value="false" />
      <Parameter Name="ServerAuthCredentialType" Value="None" />
    </Section>

Is it enough info? How to validate endpoint is secured?

**Comment by MikkelHegn** [comment]
Is this a Windows standalone cluster deployed outside of Azure? If so, it might be Windows authentication to the cluster. @dbreshears: can you remember the parameter to do Windows authentication in VS publish? I don't find it here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-visualstudio-configure-secure-connections

**Comment by krvladislav** [comment]
Yes, it is Windows standalone cluster. 

I can Connect-ServiceFabricCluster via powershell without any additional auth parameters like WindowsCredential

**Comment by krvladislav** [comment]
Now it is unable to connect:

![screenshot_4](https://user-images.githubusercontent.com/886098/44206409-da4bf980-a183-11e8-8f4a-17c4f698511a.png)

And there is no success via shell:

```

PS > Connect-ServiceFabricCluster  -ConnectionEndpoint xxx:19000 -WindowsCredential:$true

WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM...
False
Connect-ServiceFabricCluster : Could not ping any of the provided Service Fabric gateway endpoints.

```

Some additonal info:

Cluster SF Version is Microsoft.Azure.ServiceFabric.WindowsServer.6.3.162.9494
Cluster OS Windows Server 2016 Version 1607 (OS Build 14393.2273)

VS2017 Version Release/15.7.5+27703.2042
Azure App Service Tools v3.0.0 - 15.0.40608.0
Microsoft Azure Service Fabric Tools for Visual Studio - 2.2.
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

**Comment by ravipal** [comment]
In order to publish a container application, the target cluster must be a secure cluster. Because we need a cert to encrypt the ACR credential. That is why the publish dialog shows the message "The selected cluster must have a server certificate which must be installed on this machine to publish a **container application**". Publish operation doesn't support unsecure cluster for container application.

Later on since "WindowsCredential=true" is added manually for non-secure cluster, you are getting the connection failure.

**Comment by krvladislav** [comment]
Hi @ravipal,
 
1. Why a publish operation of the same container application works ok via TFS job and Deploy-FabricApplication.ps1 script to remote unsecure cluster? 

2. Why does it work via VS2017 to local unsecure cluster?

![screenshot_5](https://user-images.githubusercontent.com/886098/44247828-53ddf900-a211-11e8-8908-b05bcdd92b64.png)

Local cluster manifest contains:
   ```
 <Section Name="Security">
      <Parameter Name="ClusterCredentialType" Value="None" />
      <Parameter Name="ServerAuthCredentialType" Value="None" />
    </Section>

```

3. How does ACR coresspond to _standalone_ cluster?

**Comment by ravipal** [comment]
1. VSTS release job will support both secure and unsecure cluster and when unsecure cluster is used, the credential will not be encrypted and it shows this detail in the information icon.
2. For local cluster deployment, the image will be picked up from local machine, so no remote container registry is involved.

**Comment by krvladislav** [comment]
Thanks for answers.

So VSTS supports unsecure publish. 
Are there any plans for unsecure publish from VS2017 as well? I think it will be relevant for a fast start with standalone Service Fabric cluster without time-spending security configuration.

**Comment by MikkelHegn** [comment]
Reopening as I think we haven't fully figured out the ask.

@krvladislav: If you create a container image on your dev box, it needs a container registry to be published to, before any cluster can download the container image.

As opposed to Service Fabric applications (Reliable Services or guest executeables), the container is not uploaded to the clusters imagestore. It is uploaded to a container registry and then pulled by the individual cluster nodes on application deployment, using the Docker daemon installed on the nodes.

The missing support here is for public container registries, like Docker Hub. What is supported is Azure Container Registries, which are private container registries. This has nothing to do with the cluster security configuration.

**Comment by krvladislav** [comment]
@MikkelHegn 
Is there any way to use on-premise container registry like ImageStore?

**Comment by MikkelHegn** [comment]
@krvladislav - Visual Studio is trying to help you with the steps of building your container image an uploading it to a registry, then finally updating the application manifest file with the credentials to that registry. All of this can be done via PowerShell.

ImageStore is not a container registry, it's an equivalent store for application types in a service fabric cluster, but does not support Docker container registries. You'll need one of these https://docs.docker.com/registry/ to upload your containers to.

**Comment by ravipal** [comment]
Please reopen this bug if you need more information than what @MikkelHegn  shared. Closing for now
