### ISSUE TITLE
Missing "EnableDefaultServicesUpgrade" Fabric settings for "ClusterManager" section in Azure Portal

### ISSUE THREAD

**Issue by cdtlaurence** [Azure/service-fabric-issues#1224]
I was trying to allow default service upgrades through Azure Portal. I can see ClusterManager in the Fabric Settings section but I don't see the "EnableDefaultServicesUpgrade" property in the dropdown as shown in screenshot below. 

This should be here as per this page: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings

![image](https://user-images.githubusercontent.com/13982922/43952300-6edba790-9c8d-11e8-9879-2424a25f43c6.png)

**Comment by MikkelHegn** [comment]
I don't think all the settings are exposed through the portalUI @aljo-microsoft to confirm. You need to configure this via an ARM deployment.

**Comment by Pothulapati** [comment]
I think, the portal dosen't actually support configuring many settings (as of now I guess). As @MikkelHegn here suggested, We can configure most of the settings by using the Azure Resource Manager. 

[Here](https://blogs.msdn.microsoft.com/maheshk/2017/05/24/azure-service-fabric-error-to-allow-it-set-enabledefaultservicesupgrade-to-true/) is blog post on changing the ```EnableDefaultServicesUpgrade``` setting using resouces.azure.com(https://resources.azure.com)


The Azure doc that you have mentioned, also has enough information on changing other settings.

Hope this helps. :smile:

**Comment by aljo-microsoft** [comment]
That is correct. Portal is a great UI for common happy path Dev\Test provisioning, and providing UI for resource management. However, all settings for any azure resource, will not have all configurations available to you; forcing you to leverage appropriate ARM Rest API's to configure resources for production solutions.
