### ISSUE TITLE
Cannot access service fabric app from browser

### ISSUE THREAD

**Issue by stembhekar** [Azure/service-fabric-issues#1227]
I have deployed a service fabric app on azure. This app works fine on localhost however I cannot access the one deployed on azure from a browser. Chrome returns ERR_CONNECTION_TIMED_OUT, Edge returns INET_E_RESOURCE_NOT_FOUND. There are no errors in Service Fabric Explorer.

**Comment by MikkelHegn** [comment]
Hi @stembhekar - have you checked if the endpoint is exposed via the Azure Load Balancer and probes are configured correctly? https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services#connections-from-external-clients

**Comment by stembhekar** [comment]
Thanks. That did the trick.
