### ISSUE TITLE
Unable to debug service fabric app in VS 15.8

### ISSUE THREAD

**Issue by mjsabin01** [Azure/service-fabric-issues#1228]
I just updated to VS 15.8 and no I am unable to debug my Service Fabric App.  I am able to build fine and i see the debugger start and see the dialog showing Discovering ETW sources.  However, it immediately stops and I see the following output in debugger window:

C:\Code\xxx\xxx\pkg\Debug is not found.
At C:\Program Files\Microsoft SDKs\Service 
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:120 char:9
+         throw $errMsg
+         ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\Code\xxx...g is not found.:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\Code\CatalogService\XACatalogService\pkg\Debug is not found.
 
Finished executing script 'Publish-NewServiceFabricApplication'.
Time elapsed: 00:00:02.1121204

**Comment by berndku** [comment]
+1

**Comment by mjsabin01** [comment]
I re-installed VS 2018 and my Service Fabric install on my dev machine.  When I try to start debugging, i just get error:

6>------ Deploy started: Project: XXX, Configuration: Debug x64 ------
6>Object reference not set to an instance of an object.
========== Build: 5 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by hamjo** [comment]
I also encountered this error. Changing "MSBuild project build output verbosity" to "Diagnostic" doesn't display any other information.

**Comment by hamjo** [comment]
I was able to get it to deploy using HTTP protocol for my only endpoint instead of HTTPS.

**Comment by dbreshears** [comment]
Apologize for this, same as #1236.  it is due to a regression from the https support that went in 15.8 for ASP.NET core 2.1.     We have a fix queued and hopefully will release on Monday 8/27, right now would need to switch the endpoint to http for debugging and then publish with https from command line

**Comment by dbreshears** [comment]
@mjsabin01,  15.8.2 update is released now

**Comment by mjsabin01** [comment]
Thanks.  Just downloaded and it is working now

**Comment by rchzh** [comment]
Have same issue but with VS 2017 version 15.9.6.
I cannot start or debug my service fabric project using VS.

**Comment by dbreshears** [comment]
@rchzh, can you open a new issue for this as this has been closed for several months and believe this particular issue is sitll fixed.   Please provide as much detail as possible for your environment and any errors or logs you have.
