### ISSUE TITLE
Multi availability zone cluster scaling issues

### ISSUE THREAD

**Issue by skwasiborski** [Azure/service-fabric-issues#1229]
I am experimenting with increasing reliability of an SF cluster by deploying the nodes to multiple availability zones. I would like the seed nodes to be spread among 3 availability zones. Since SF does not support using large VMSS (i.e. singlePlacementGroup=False) and single non large VMSS cannot be deployed to multiple AZ, I am using three VMSS deployed to different AZs all assigned to same primary node type.

### My Setup
SF cluster build on 3 VMSS. Every scale set contains 3 VMs and is deployed to different AZ in the same region. All VMSS are put in a single vnet. There is single LoadBalancer in front of all VMSS. Durability is set to Silver, reliability level is set to Platinum.

I know that this is not totally inline with the recommendations i.e. it does not follow recommendations from [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity#operational-recommendations-for-the-node-type-that-you-have-set-to-silver-or-gold-durability-level).

#### When scaling out VMSS (increasing number of VMs)
Only one VMSS scaled successfully, other two were stuck in updating state for a long time and finally failed with internal error i.e.:
``` json
{
    "resourceType": "Microsoft.Azure.ResourceProvider.CoreFramework.Strings, ResourceProvider.CoreFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
    "ResourceCode": "InternalExecutionError",
    "ResourceParameters": []
}
```  
It seems that the VMSS that scaled successfully is the one that hosts primary replica of ClusterManagerService.

Only way I found to fix the situation was to deallocate the VMSS and restart it. This fixed the issue and all new nodes were registered in SF cluster.
#### When scaling in VMSS (decresing number of VMs)
Two VMSS that failed earlier scaled down successfully but the corresponding nodes were not removed from SF cluster i.e. they were listed as down in SF explorer. The system behaved like in Bronze durability tier. I assume this also has to do with ClusterManagerService and recommendation to map every VMSS to different node type.

One VMSS that originally scaled successfully got stuck when scaling down i.e. the VMs were not removed and continued to run. All VMs from this VMSS were listed as healthy in SF (even the ones in deleting state in VMSS).

Is there any recommendation for making such or similar setup running smoothly?

**Comment by ashishnegi** [comment]
@alexwun For ClusterManagerService related query.

**Comment by skwasiborski** [comment]
Interesting thing is that changing SKU (size) on all VMSS though not supported as such went without any problems. VMs where taken offline and updated one by one and afterwords rejoined the cluster without issues.

**Comment by masnider** [comment]
@TassaduqBasu fyi

**Comment by aljo-microsoft** [comment]
@skwasiborski 

Cross AZ with Silver durability support isn't implemented yet, and is something we are working on.

Until its supported you'd need to reduce durability to Bronze for SF Clusters.

If you have any other questions, please don't hesitate to reach out.
