### ISSUE TITLE
Configure Application Gateway with public facing load Balancer and Service Fabric

### ISSUE THREAD

**Issue by AkshayBhalerao333** [Azure/service-fabric-issues#1233]
Hi Team, I am configuring the Service fabric. its working fine stand alone with public facing loadbalancer, you i am not able to configure the Application gateway+public facing loadbalancer+ Service fabric. can you please provide me some guide how to configure this.

**Comment by AkshayBhalerao333** [comment]
When I am configuring the application gateway i am missing some configuration details. i have setup the backend pool as a load balancer's public facing IP.

**Comment by nareshkhatri81** [comment]
How you are exposing service fabric to public LB?
Are you using reverse proxy of service fabric ?
What configuration error you are getting ?

**Comment by AkshayBhalerao333** [comment]
Yes using by default LB which is public facing and also using the reverse proxy for SF.
I am getting the 502 error when I am trying to access the application container.
How can we configure the Path-Base rule in Application gateway for Public LB. I wanted to allow traffic only from 80 port. 
Eg. http://gatewayIP:80/client1 divert this traffic to container port 20000
      http://gatewayIP:80/client2 divert this traffic to container port 20001

**Comment by AkshayBhalerao333** [comment]
yes i am able to test the container with service fabric and LB. but not able to test it with the App gateway.

**Comment by masnider** [comment]
So as it is set up now, you can hit the network load balancer directly, and things work, but not when you go through AppGW? So the configuration issue must be somewhere between AppGW and the LB. What's different between how you are hitting the LB and how AppGW is doing it?

**Comment by masnider** [comment]
Some basic/similar patterns are documented here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patterns-networking

**Comment by aljo-microsoft** [comment]
@AkshayBhalerao333 
It appears to the referenced documentation resolved your issue. Please reopen if you have any other questions.
