### ISSUE TITLE
JsonSerializationException in SF extension

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#1235]
When deploying a SF cluster on Azure, not all of the ARM schema is validated. If there are errors in the template, it can cause the deployment to get stuck for a long time. The internal extension logs are the only way to figure out what happened.

Also, I think a serialization exception is always non-transient in this case, so retries might be redundant.

For example (log from a VM):

```
Error: InstallService failed, retries remaining = 39: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "foo.westus.cloudapp.azure.com" to type 'System.String[]'. Path 'runtimeSettings[0].handlerSettings.publicSettings.certificate.commonNames', line 7, position 354. ---> System.ArgumentException: Could not cast or convert from System.String to System.String[].
    at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
    at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
    <truncated stack>
    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at Microsoft.Azure.ServiceFabric.Extension.Core.JsonHelper.ReadFromJsonStream[T](Stream stream)
    at Microsoft.Azure.ServiceFabric.Extension.Core.Models.HandlerConfig.LoadFrom(String filePath)
    at Microsoft.Azure.ServiceFabric.Extension.Core.VMExtensionHandler.InstallService()
    at Microsoft.Azure.ServiceFabric.Extension.Core.VMExtensionHandler.InstallServiceWithRetry()
```

**Comment by vaishnavk** [comment]
@mhatreabhay : Can you take a look?

**Comment by mhatreabhay** [comment]
Thanks for reporting. I will add validation to fail deployment in case of serialization failure.

**Comment by 4c74356b41** [comment]
@mhatreabhay ok what does this error mean? why would it try to convert common name to array? how to work around this? i'm doing exactly what is stated in the documentation

**Comment by mhatreabhay** [comment]
Common name should be an array under service fabric vm extension. 

"commonNames": [
"<<coomon name>>"
]

**Comment by 4c74356b41** [comment]
yeah, i've already found out that a person who created docs owes me 2 days of my life due to his extreme formatting skills. i've also submitted a PR to amend that.

**Comment by 4c74356b41** [comment]
is there a way to stop failing upgrade or do i have to wait 2-4 hours between attempts? @mhatreabhay

**Comment by 4c74356b41** [comment]
also, is it expected that none of the properties seem to be changed when i run the template? they just stay as they were before the deployment @mhatreabhay

**Comment by mhatreabhay** [comment]
If you are not modifying anything in resource it will be no op. If you have updated any resource (arm json) it will patch and it should update resource properties accordingly. 

are you sure, upgrade went through? 

you can check your arm template  deployment status through Portal.azure.com 's activity tab. It should be listed under your resource group. It will tell you exactly how long upgrade took, and which succeeded/failed with error message. 

Its always better to have health check wait duration and health check stable duration on higher side, It makes upgrade safer, so in case upgrade is causing any issue that will be detected and rollback.
However this also makes upgrade slower. Say e.g. Health Check Wait duration = 5 min and Health check stable duration 5 min. and you have 5 UDs  then it will take 50+t min to complete upgrade, where t is upgrade duration. On each UD it will spend 5 min for Health check + 5 min to verify upgrade stability. Then if both passed it will move to next UD. You can lower these values to expediate your upgrade time. however be very cautious.  

if your upgrades are taking 4 hrs. please file a ticket with CSS / share your resource ID. 
@vaishnavk @mostafaez

**Comment by mhatreabhay** [comment]
@mchiriac-msft

**Comment by 4c74356b41** [comment]
hey, no it didnt went throught, but it failed on the very first UD, but it takes about 2-3 hours for the cluster to fail upgrade (using default upgrade settings). @mhatreabhay

**Comment by mhatreabhay** [comment]
I believe it kept retrying. 
If you can capture correlation id from portal.azure.com for that operation and share with @vaishnavk /@mostafaez / @mchiriac-msft
they can check why upgrade failed and why it took 2-4 hrs.

**Comment by 4c74356b41** [comment]
yeah, i believe so as well. how to make it not retry, just rollback on the first error? @mhatreabhay

**Comment by mhatreabhay** [comment]
That is not in your control. SFRP orchestrate that. Please share your cluster resource id and correlation Id with folks I mentioned above. they will able to look up what's going on will guide your further.
