### ISSUE TITLE
Service Fabric StatefulService CPU usage keeps growing

### ISSUE THREAD

**Issue by cosie90** [Azure/service-fabric-issues#1239]
We have a Service Fabric `StatefulService` that is running away nicely. It consumes messages, processes them and has two `IReliableState`s for storing away some data from each message. It will process about 500 messages per minute per replica.

The `MessageProcessor` will take all pending messages that we create a new `ITransaction` using `IReliableStateManager` that is wrapped in a `using` block and pass that transaction to the `OuterMessageHandler`. After message has been processed we do a `ITransaction.CommitAsync` or `ITransaction.Abort` if something has failed. 

`OuterMessageHandler` looks like this - 
```
        public async Task Handle(ITransaction tx, params Envelope[] messages)
        {
            foreach (var msg in messages)
            {
                using (var scope = _scope.BeginLifetimeScope())
                {
                    var contextProvider = scope.Resolve<MessageContextProvider>();

                    contextProvider.Set(tx);

                    await innerHandler.Handle(msg);
                }
            }
        }
```
`MessageContextProvider` is simply the below - 
```
internal class MessageContextProvider
    {
        private ITransaction _tx;

        public void Set(ITransaction tx)
        {
            _tx = tx;
        }

        public ITransaction GetTransaction()
        {
            if (_tx == null)
                throw new Exception("ITransaction has not been set");

            return _tx;
        }
    }
```
This is registered with Autofac -
```
             builder
                .Register(c =>
                {
                    var context = c.Resolve<MessageContextProvider>();

                    return context.GetTransaction();
                })
                .As<ITransaction>()
                .ExternallyOwned();

            builder
                .RegisterType<MessageContextProvider>()
                .AsSelf()
                .InstancePerLifetimeScope();
```
`MessageContextProvider` exists simply to allow us to use `ITransaction` in all of the `InnerMessageHandler` as if its just a normal dependency, while still just using the same transaction in each message.
`ITransaction` is marked as `ExternallyOwned` so that the `OuterMessageHandler` does not dispose of it before we do a commit within `MessageProcessor`.

`InnerMessageHandler`s are just handlers to execute our business logic. 

`IReliableState` has 2 methods `SomeType Find(long id)` and `Update(long id, SomeType someType)`. 

Find method looks like the below - 
```
           var snapshotHandler = await _stateManager.GetOrAddAsync<IReliableDictionary<long, SomeType>>(SomeTypeKey);

            var snapshot = await snapshotHandler.GetOrAddAsync(
                _transaction,
                Id,
                new SomeType());

            return snapshot;
```
Update looks like this - 
```
var snapshotHandler = await _stateManager.GetOrAddAsync<IReliableDictionary<long, SomeType>>(SomeTypeKey);

            await snapshotHandler.SetAsync(_transaction, Id, snapshot);
```

When we throw a lot of requests at the service, all replicas stay well below 1% CPU usage. After about an hour one of the replicas gets to around 30%-35%. When we stop the tests from hitting the service (ie: service is now sitting idle) CPU usage still stays between 30-35%. It would be fine if we had spikes and went back down but it staying with high CPU usage is the problem. 

From our investigation we have replaced the 2 `IReliableState`'s with just 2 in memory `ConcurrentDictionary`'s. This solved the issue. We could run it for hours and nothing will rise above 2% CPU usage. This is obviously not a solution as we need the internal state persisted for resilient reasons.

We have used PerfView and dotTrace to see what is happening and not much of any valid information has been coming up.

At this point I believe it is something to do with how we use either `IReliableDictionary` or `ITransaction`. Anyone having similar issues? Could anyone shed some light on what we could possibly be doing wrong? 

**Edit**
One of the `ReliableState` repositories (lets call it `state2`) had the Find method slightly differently. It looked like the below - 
```
           var snapshotHandler = await _stateManager.GetOrAddAsync<IReliableDictionary<long, SomeType2>>(SomeTypeKey2);

            var snapshot = await snapshotHandler.TryGetValueAsync(
                _transaction,
                Id);
           
            if(snapshot.HasValue)
                 return snapshot.Value.Clone(); // Clone is a deep copy 

           var stateFromSomeApi = await someApi.GetStartState(id);

           await snapshotHandler.SetValue(_transaction, Id, stateFromSomeApi);

            return stateFromSomeApi ;
```

Now we changed it to do the following - 

```
        public async Task<SomeType2> Find(long id)
        {
            var snapshotHandler = await _stateManager.GetOrAddAsync<IReliableDictionary<long, SomeType2>>(
                SomeTypeKey2);

            var snapshot = await snapshotHandler.GetOrAddAsync(
                _transaction,
                id,
                await GetStartState(id));

           return snapshot.Clone();
        }

        private async Task<SomeType2> GetStartState(long id)
        {
            return await _someApi.GetStartState(id);
        }
```

We changed `state2` to do a `GetOrAddAsync` and it is working perfectly fine. Why would doing `TryGetValueAsync` and `SetValue` instead of `GetOrAddAsync` have threads hang around so much? We have tested it with nearly double the production load and CPU stays well below 5% on each primary replica.

**Comment by olitomlinson** [comment]
I’m no specialist but I have a few thoughts

> rom our investigation we have replaced the 2 IReliableState's with just 2 in memory ConcurrentDictionary's. This solved the issue. We could run it for hours and nothing will rise above 2% CPU usage. This is obviously not a solution as we need the internal state persisted for resilient reasons.

When using ReliableState have you noticed any correlatble differences in High disk IO, high memory utilisation in disk or Ram, versus when you just use concurrentDictionary? In service fabric explorer, drill into your replicas, can you spot the sequence numbers never catching up/stabilising in the primary and secondaries, could it be the underlying state stack doing a lot of work like replication/checkpointing and taking a hell of a long time to complete for some reason. (Like dead locking?)

> After about an hour one of the replicas gets to around 30%-35%. When we stop the tests from hitting the service (ie: service is now sitting idle) CPU usage still stays between 30-35%

How long have you observed the high CPU after stopping the tests? Did it drop naturally after X minutes/hours or did it continue seemingly forever until you forceably killed your service?

Just had another thought, could this be dead locking in the state manager? Are you using update locks where appropriate? 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-reliable-collections-guidelines

How many partitions are concurrently doing work? if you are using shared process hosting of your service could they all be sharing the same underlying statemanager and concurrent transactions is causing dead locks? I’m assuming you are running on local cluster? Have you tried a real cluster to see if you get the same results?

I’m out of suggestions other than can you remove your layers of indirection and DI to simplify the code and remove uncertainty around what’s actually happening?

**Comment by ashishnegi** [comment]
Are you using one Transaction per message or one Transaction per multiple messages ? 

Below comment implies you are creating one per transaction:
>For each message that comes into the MessageProcessor, we create a new ITransaction using IReliableStateManager

Below comment implies you are sharing transaction across messages:
>allow us to use ITransaction in all of the InnerMessageHandler as if its just a normal dependency, while still just using the same transaction in each message.

**Comment by cosie90** [comment]
Hi @olitomlinson, 
>When using ReliableState have you noticed any correlatble differences in High disk IO, high memory utilisation in disk or Ram, versus when you just use concurrentDictionary?

Yes so disk usage did increase as well, we didn't think anything of it because it was expected with using ReliableState really. 

>In service fabric explorer, drill into your replicas, can you spot the sequence numbers never catching up/stabilising in the primary and secondaries, could it be the underlying state stack doing a lot of work like replication/checkpointing and taking a hell of a long time to complete for some reason. (Like dead locking?)

No I did not drill into the replicas. That is actually a very valid point. I will rerun the test during the week to check these out actually. 

>How long have you observed the high CPU after stopping the tests? Did it drop naturally after X minutes/hours or did it continue seemingly forever until you forceably killed your service?

I left the service idle overnight and it still stayed hovering around 30-35% CPU.  

>Just had another thought, could this be dead locking in the state manager? Are you using update locks where appropriate?

This was my initial though as well actually. We just use the default locks per operation and did not tweak things. I was about to get into this before I saw that the GetOrAdd operation does not do the same thing.

>How many partitions are concurrently doing work?

3 Partitions. On Production we have 10  and it was showing the same issues. 

> If you are using shared process hosting of your service could they all be sharing the same underlying statemanager and concurrent transactions is causing dead locks? I’m assuming you are running on local cluster? Have you tried a real cluster to see if you get the same results?

This is a possibility actually. The test to reproduce it was all local and we have the application running on three different clusters (test, pre live and live) and all showed the same issues. Now they are all on shared infrastructure.

**Comment by cosie90** [comment]
Hi @ashishnegi ,

Thanks very much for your comment and apologies for the really late response.

>Are you using one Transaction per message or one Transaction per multiple messages ?

So we are creating a Transaction per multiple messages (depending how many are currently due to be processed). Apologies for the ambiguity here, I will tidy up the post to make this clear.

**Comment by zuhairp** [comment]
@cosie90, a few questions:

* What version of Service Fabric are you using?
* How much contention are you expecting? Are many transactions changing a few keys?
* If you use an update lock for the TryGetValue in the original code, does the issue still repro? You can set the lock mode with [this API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.collections.ireliabledictionary-2.trygetvalueasync?view=azure-dotnet#Microsoft_ServiceFabric_Data_Collections_IReliableDictionary_2_TryGetValueAsync_Microsoft_ServiceFabric_Data_ITransaction__0_Microsoft_ServiceFabric_Data_Collections_LockMode_)

**Comment by zuhairp** [comment]
Closing issue since there has not been any activity
