### ISSUE TITLE
Does Azure virtual machine scale set automatic OS upgrades supersede POA?

### ISSUE THREAD

**Issue by skwasiborski** [Azure/service-fabric-issues#1240]
I am wondering if the new ability to automatically patch VMSS with OS upgrades is a replacement for patch orchestration application?

The documentation [here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade) mentions Service Fabric in few places but it is not clear how the patching would work and how will it interact with SF. As far as I understand both solutions work differently POA patches existing OS "in" the VM and automatic OS upgrades just swaps system disk. 

Which approach would be the recommended solution?

**Comment by masnider** [comment]
and @TassaduqBasu fyi

**Comment by aljo-microsoft** [comment]
@skwasiborski 

I've created this PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/54747

To add the following statement:

[Azure virtual machine scale set automatic OS image upgrades](https://docs.microsoft.com/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade) is the best practice for keeping your Operating Systems patched in Azure, and the patch orchestration application is a wrapper around Service Fabrics RepairManager Systems service that enables configuration based OS patch scheduling for non-Azure hosted clusters. POA is not required for non-Azure hosted clusters, but scheduling patch installation by Upgrade Domains, is required to patch Service Fabric clusters hosts without downtime.

To the beginning of this document: 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application

**Comment by aljo-microsoft** [comment]
@skwasiborski 

So being clear VMSS AutoOSUpgrade is an reimaging process, and is the recommendation.

If you have any other questions, please don't hesitate to reach out. Thanks
