### ISSUE TITLE
OnPremise cluster restarting nodes

### ISSUE THREAD

**Issue by TomaszSynak** [Azure/service-fabric-issues#1241]
We've got OnPremise cluster v  6.2.301.9494 with 10 nodes running. We've noticed that cluster is restarting its nodes one by one each week around same time (Friday 10:00 a.m.). I'm trying to find anything relevant either in documentation or in cluster's manifest, but without success. What can be responsible for such consequent restarts ? Is it rebalancing or patching we don't know about as pointed [here](https://github.com/Azure/service-fabric-issues/issues/1222)? 

> However, any move of a replica would give you a fresh start. Moves could happen if nodes need restarting (after patching or similar), or through re-balancing based on capacity or placement constraints updates.

**Comment by VipulM-MSFT** [comment]
Is the node restarting or your service processes? If it is nodes, check to see if you have POA or Chaos app installed and enabled.

**Comment by TomaszSynak** [comment]
Thx @VipulM-MSFT for reply. These are nodes restarting, one by one. Can't think of any Chaos being set up, but will double check that along with POA settings and will get back to you soon.

**Comment by VipulM-MSFT** [comment]
@TomaszSynak - let us know if you have update for this issue. If this is resolved, please feel free to close the issue.

**Comment by TomaszSynak** [comment]
Thanks @VipulM-MSFT - closing the issue as it's no longer a problem.
