### ISSUE TITLE
FabricTransportRemotingConnectionHandler.Finalize() throws NullReferenceException

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/service-fabric-issues#1244]
Good day,

I have noticed that in very quick scenarios (in my case it is rapidly failed unit-tests) the `FabricTransportRemotingConnectionHandler.Finalize()` throws `NullReferenceException`.

I have inspected the code and found that by some reason implementation of `FabricTransportRemotingConnectionHandler.Finalize()` method tries to access managed object.

``` csharp
internal class FabricTransportRemotingConnectionHandler : IFabricTransportConnectionHandler
  {
    private ConcurrentDictionary<string, FabricTransportCallbackClient> clientCallbackConnection;

    public FabricTransportRemotingConnectionHandler()
    {
      this.clientCallbackConnection = new ConcurrentDictionary<string, FabricTransportCallbackClient>();
    }

    ~FabricTransportRemotingConnectionHandler()
    {
      this.clientCallbackConnection.Clear();
    }

    // The rest is omitted
}
```

Based on [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.object.finalize?view=netframework-4.7.2):

> An object's Finalize method shouldn't call a method on any objects other than that of its base class. This is because the other objects being called could be collected at the same time as the calling object, such as in the case of a common language runtime shutdown.

The finalize method shouldn't access any managed objects, so this looks like a bug.

**Comment by VipulM-MSFT** [comment]
@suchiagicha - is there a way to get this fix in the repo now and include in the CU release?

**Comment by OlegKarasik** [comment]
Hi @amanbha, @masnider,

Is it fixed? I see a merge but the issue is still opened :)

**Comment by amanbha** [comment]
@OlegKarasik Thansk for pointing it out, I am closing it now.
