### ISSUE TITLE
PropertyManager.NameExists incorrectly returns true when service is not running

### ISSUE THREAD

**Issue by mtucker2112** [Azure/service-fabric-issues#1245]
Since upgrading to 6.3.162 we have noticed an issue where fabricClient.PropertyManager.NameExistsAsync(serviceUri) will return true when the service is not actually running.  We know the service doesn't actually exist by checking SF explorer or with a PS query. This code is run by another SF service in the same cluster.  Nothing seems to clear this issue except removing all app types, apps and services from the cluster, restarting the scale set and redeploying everything.

Is this a known issue?  Is there some other troubleshooting we can do?  Our code relies on NameExists quite heavily and currently cannot rely on this to tell if a service is actually already running.

Thanks in advance for your help!!

**Comment by oanapl** [comment]
@mtucker2112 , there have been no changes in Naming in 6.3, so I don't know of anything that would explain this behavior.

Internally, when the service is created, the name for that service is created in Naming; when the service is deleted, that name is deleted as well. I assume you are talking about the actual service URI, and not another name that you are creating? Could you elaborate on the sequence of events - service was created, deleted and then name exists returns true forever? Is the service with the same name re-created at any point?

Is it possible that your code writes a property under that name and doesn't delete it? If a name is not empty, deletion would fall. Though you would probably see the service deletion fail in that case. Similarly, is it possible that your code writes the name itself?

**Comment by mtucker2112** [comment]
Yes the serviceUri is a URL to the service, not another name.  Our design is such that we have a manager service that starts worker services when needed.  The manager starts a worker (in ExclusiveProcess mode) with the following:

```
var service = new StatelessServiceDescription()
{
    ApplicationName = appUri,
    ServiceName = serviceUri,
    ServiceTypeName = $"{workerName}Type",
    DefaultMoveCost = MoveCost.High,
    PartitionSchemeDescription = new SingletonPartitionSchemeDescription(),
    InstanceCount = 1,
    ServicePackageActivationMode = ServicePackageActivationMode.ExclusiveProcess
};

using (var client = new FabricClient())
{
    var svcExists = await client.PropertyManager.NameExistsAsync(serviceUri);
    if (!svcExists)
        await client.ServiceManager.CreateServiceAsync(service);
}

```
When the worker is done, it shuts down with:

```
using (var client = new FabricClient())
{
    var service = new DeleteServiceDescription(context.ServiceName);
    service.ForceDelete = false;
    try
    {
        client.ApplicationManager.DeleteApplicationAsync(deleteApplicationDescription, TimeSpan.FromSeconds(120), CancellationToken.None).Wait(token);
    }
    catch (OperationCanceledException)
    {
        //some logging
    }
    catch (Exception ex)
    {
        deleteApplicationDescription.ForceDelete = true;
        client.ApplicationManager.DeleteApplicationAsync(deleteApplicationDescription);
    }
}

```

This worker may (and often is) restarted numerous times an hour with the exact same name (URI).  This logic has worked perfectly now for a long time (over a year) and we only started to have this issue after upgrading to 6.3.162.  Although I am I'm somewhat suspicious of the catch (OperationCanceledException) above - could that interfere with a clean shutdown?  

We don't see any errors when shutting down a worker that later cannot be started due to this issue.  I'm not sure what you mean by "is it possible that your code writes the name itself" - this is the only way we start\stop services.

Thanks!

**Comment by oanapl** [comment]
Thank you for the details.
- In the code you pasted, you create a service. But the cleanup code deletes the application with DeleteApplicationAsync(deleteApplicationDescription). Why do you delete the application instead of the service? Also, in catch, you delete application with the service description?
- The code above has logging when it encounters exceptions - have you checked your logging to see what exceptions are caught? 
- Why do you treat OperationCanceledException differently?
- You should cache the FabricClient rather than re-creating it for each command.
- Is it possible that multiple threads can execute code in parallel in this manager? Eg. one thread calls NameExists and the service exists, so doesn't create; another thread deletes the service. 
In general, since the 2 calls (NameExists and CreateService) are not put into a transaction, races can happen between them. This may be OK based on your scenario, but if it's not, you need additional logic to protect against it.

While NameExists works because of the internals of the system, another way you can check whether the service exists is using [GetServicePagedList with your service name](https://docs.microsoft.com/dotnet/api/system.fabric.fabricclient.queryclient.getservicepagedlistasync?view=azure-dotnet). This returns the service if it exists or nothing otherwise. If the service exists, you can check [Status](https://docs.microsoft.com/dotnet/api/system.fabric.query.servicestatus?view=azure-dotnet) to see if the service is Creating, Deleting etc.

**Comment by mtucker2112** [comment]
- In the code you pasted, you create a service. But the cleanup code deletes the application with DeleteApplicationAsync(deleteApplicationDescription). Why do you delete the application instead of the service? Also, in catch, you delete application with the service description?
[mtucker2112] Sorry I originally pasted the wrong code, post updated.  We are deleting the service not the application.

- The code above has logging when it encounters exceptions - have you checked your logging to see what exceptions are caught?
[mtucker2112] Yes, we don't see any exceptions logged.  Unfortunately the OperationCanceledException currently only logs in debug mode so we don't have any logs for those exceptions.

- Why do you treat OperationCanceledException differently?
[mtucker2112] Good question, I'm not sure why this is done; it does seem suspicious.  But again this code worked before upgrading to 6.3.162.

- You should cache the FabricClient rather than re-creating it for each command.
[mtucker2112] Why is that?  Is there a performance gain?

- Is it possible that multiple threads can execute code in parallel in this manager? Eg. one thread calls NameExists and the service exists, so doesn't create; another thread deletes the service.
[mtucker2112] No there is only one manager service that starts the worker services, running from a single thread.

- In general, since the 2 calls (NameExists and CreateService) are not put into a transaction, races can happen between them. This may be OK based on your scenario, but if it's not, you need additional logic to protect against it.
[mtucker2112] I don't know what you mean by a transaction, can you elaborate?

Good to know about GetServicePagesList, thanks.  Is it preferable \ more reliable than NameExists in our scenario then?

**Comment by mtucker2112** [comment]
Great information thanks - we'll work on applying it.  

Yes our mix of await\wait()\noawait is odd :)
Yes once NameExists _incorrectly_ returns true for a worker service, it continues to do so forever. 
These services are running in an Azure cluster.  Where are the cluster traces found?

**Comment by oanapl** [comment]
You can [open a support ticket](https://ms.portal.azure.com/microsoft.onmicrosoft.com#blade/Microsoft_Azure_Support/HelpAndSupportBlade) and provide the following info:
- the cluster resource id
- the region where the cluster is 
- the time (UTC) at which a repro happened (the service didn't exist, but NameExists returned true)
- the name of the service

Or, if you prefer, you can send me the info at oanapl at microsoft.com.

**Comment by mtucker2112** [comment]
Thank you!  I sent you an email with details as I couldn't open a support ticket with that link for some reason.

**Comment by oanapl** [comment]
@mtucker2112 , I haven't heard back from you for a while. Is this still an issue?

**Comment by oanapl** [comment]
Talked offline with @mtucker2112 , he can't repro the issue anymore. He made a change in how they shutdown services (basically caught an unhandled exception) and that seems to have eliminated the problem.
