### ISSUE TITLE
Using the SFCTL command to publish code to a Linux environment has exceptions

### ISSUE THREAD

**Issue by anlem12** [Azure/service-fabric-issues#1247]
Using the SFCTL command to publish code to a Linux environment has exceptions？

1、sfctl cluster select --endpoint http://192.168.229.130:19080

2、./install.sh

`Command arguments: ['application', 'create', '--app-name', 'fabric:/CounterServiceApplication', '--app-type', 'CounterServiceApplicationType', '--app-version', '1.0.0', '--debug', '--verbose', '--parameters', '{"CounterServiceWebService_InstanceCount":"1"}']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f85186dfb70>, <function OutputProducer.on_global_arguments at 0x7f851a95f840>, <function CLIQuery.on_global_arguments at 0x7f85185c0400>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7f85186dfbf8>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f851a95f8c8>, <function CLIQuery.handle_query_parameter at 0x7f85185c0488>]
msrest.service_client : Accept header absent and forced to application/json
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTP connection (1): 192.168.229.130:19080
urllib3.connectionpool : http://192.168.229.130:19080 "POST /Applications/$/Create?api-version=6.0&timeout=60 HTTP/1.1" 404 107
msrest.exceptions : (FABRIC_E_APPLICATION_TYPE_NOT_FOUND) Application type and version not found`

**Comment by rapatchi** [comment]
@anlem12  It seems that your application seems have got provisioned but failed while during creation. Could you take a look in Service Fabric Explorer and identify what is the application type and version mentioned ?

If I am not wrong are you deploying https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started/tree/master/Services/CounterService application ?

**Comment by anlem12** [comment]
thanks，  @rapatchi  Yes, I am deployed is https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started/tree/master/Services/CounterService, in the service fabric explorer what also have no, is a new environment

**Comment by rapatchi** [comment]
@anlem12 ,

Please perform the following and report back on which step it is failing. As I am not able to repro the issue which you are mentioning above:
1. clean and make sure your repo is on par with master branch
2. Rename  ServiceManifest-Linux.xml to  ServiceManifest.xml in CounterServicePkg and  
CounterServiceWebServicePkg 
3. run ./build.sh
4. Upload:
    sfctl application upload --path CounterServiceApplication --show-progress
5. Provision: 
   sfctl application provision --application-type-build-path CounterServiceApplication
6. Create:
   sfctl application create --app-name fabric:/CounterServiceApplication --app-type CounterServiceApplicationType --app-version 1.0.0 --parameters {\"CounterServiceWebService_InstanceCount\":\"1\"}

**Comment by anlem12** [comment]
thanks,It's ready to work
