### ISSUE TITLE
[Feature request] Reverse Proxy - allow choosing between primary and secondary replicas

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#125]
First of all, please allow Reverse Proxy to connect to the secondary replicas.
Also it would be great if one could specify using another query parameter whether they want primary or secondary replica.

For example one could use secondaries for reads and primaries for writes.

**Comment by BharatNarasimman** [comment]
The default picks the primary replica. For picking the secondary, add the query param - TargetReplicaSelector=RandomSecondaryReplica.
I will update the documentation.

**Comment by mkosieradzki** [comment]
Thanks!

**Comment by VipulM-MSFT** [comment]
I am closing this issue. We will close the issue 126 when the documentation is updated.
