### ISSUE TITLE
ServiceFabric and Docker with Linux Container has issue publishing Container Service

### ISSUE THREAD

**Issue by subas4u** [Azure/service-fabric-issues#1256]
I have added a ServiceFabric service with Container application, and my docker is set to Linux Container, and after publishing service fabric, I see the error " ... DockerRequest returned StatusCode=InternalServerError with ResponseBody=Mount denied: The source path ...".

**Environment**: Windows 10 Pro
**Docker Image**: registry.hub.docker.com/sheyenrath/wiremock.net:1.0.4.5
**Docker for Windows (Community Edition) Version**: 18.06.1-ce-win73 (19507)

**Complete Error:**
Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'. There was an error during CodePackage activation.System.Fabric.FabricException (-2147017731) Creating Container from Image=registry.hub.docker.com/sheyenrath/wiremock.net:1.0.4.5 failed for ContainerName=sf-2-5577fa18-0edb-4d76-a6e2-714a5b581568_6f33e8d4-e24e-4771-9e92-655621d70756, ApplicationId=Intelex.Alliance.ContentRepoType_App2, ApplicationName=fabric:/Intelex.Alliance.ContentRepo. **DockerRequest returned StatusCode=InternalServerError with ResponseBody=Mount denied: The source path "C:/SfDevCluster/Data/_App/_Node_0/Intelex.Alliance.ContentRepoType**

**Comment by MikkelHegn** [comment]
@subas4u - It look slike you are using Docker for Windows in Linux mode. This is not supported with Service Fabric on Windows 10.

**Comment by subas4u** [comment]
Hi @MikkelHegn, thank you for your response. Does the following documentation not applicable for Windows 10?

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers-linux

**Comment by MikkelHegn** [comment]
@subas4u No sorry, it doesn't. You need the SF cluster runtime and docker runtime to use the same OS. I'll raise an issue to get this clarified in the docs.

**Comment by subas4u** [comment]
Ok. Thank you.

**Comment by rwike77** [comment]
@subas4u @MikkelHegn  I'm updating the documentation.
