### ISSUE TITLE
[Documentation] Reverse Proxy - please disclose all undocumented query parameters, headers and so on

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#126]
It is crucial to disclose all undocumented query parameters, headers and so on that have influence on the Reverse Proxy so developer can strip such parameters and headers before passing request from the Internet Facing Proxy to Reverse Proxy!

Otherwise we are facing potential security issues!

For example, in #125 user aware of TargetReplicaSelector query parameter could force underlying proxies to route requests to secondary replicas.

**Comment by mkosieradzki** [comment]
Thank you so much for adding documentation for the ListenerName parameter! It's very useful!

**Comment by kavyako** [comment]
The document has been updated. Closing the issue.
