### ISSUE TITLE
Managed Service Identity(MSI) is not working on Service Fabric runtime version 6.3.176.9494 

### ISSUE THREAD

**Issue by pavanpadavala** [Azure/service-fabric-issues#1269]
We have .net core 2 APIs that were using Managed Service Identity(MSI). 
We enabled MSI on VM scale sets and added them to our keyvault access policies.
This is working fine in other environments with lower runtime version (<= 6.3.162.9494) but not in this 6.3.176.9494 
We're getting below error which is generated while accessing keyvault

```
Error = Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException (-2146233088)
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-8
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClient.d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.d__11.MoveNext()
For more information see: http://aka.ms/sfhealth
```

**Comment by masnider** [comment]
Hi @pavanpadavala 

Some follow up questions:

- Can you share how you're making that call to KV (what API)? 
- Also do you still have examples of environments where this is currently working and also not working? 
- Was this environment that is not working an upgrade from a working environment, or is it a separate cluster that's only run this version?

**Comment by dragav** [comment]
You seem to have an issue with the MSI endpoint on the VMSS. If you have access to one of the nodes, please run the following from a PowerShell prompt:

$response = Invoke-WebRequest -Uri 'http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fvault.azure.net' -Method GET -Headers @{Metadata="true"}
$response

$response = Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -Method GET -Headers @{Metadata="true"}
$response

(Your localhost MSI port may vary).
If that works, next step is to engage VS; if not, this is an issue for Compute. In either case, this is not related to the SF runtime.

**Comment by pavanpadavala** [comment]
Thanks for your replies @masnider and @dragav 
We identified the issue in the ARM resources and/or portal.
When we enabled the MSI extension on the VM Scaleset in the portal, it was not adding the below extension to the resource. We edited and manually added that in the resource and it started working.

`          {
            "properties": {
              "autoUpgradeMinorVersion": true,
              "settings": {
                "port": 50342
              },
              "publisher": "Microsoft.ManagedIdentity",
              "type": "ManagedIdentityExtensionForWindows",
              "typeHandlerVersion": "1.0"
            },
            "name": "ManagedIdentityExtensionForWindows"
          }`

**Comment by dragav** [comment]
Thanks for the update, will consider this resolved.

**Comment by Mortana89** [comment]
Hi @pavanpadavala, where exactly did you specify this extra configuration?
I've extracted the automation script from the azure portal, to see if I can find the same section, but am unable to find anything saying 'ManagedIdentity' in the ARM template generated. 
Even though I've enabled MSI on the VMSS

**Comment by dragav** [comment]
The configuration mentioned above corresponds to the MSI VM extension, which is now deprecated. You no longer need to specify this extension to have access to the VMSS's identity; simply enabling it suffices. 
Access tokens can be obtained from the IMDS endpoint (e.g.: $response = Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -Method GET -Headers @{Metadata="true"})

**Comment by vikasparihar** [comment]
I am still facing a similar issue and i have enabled UserAssigned identity on SF cluster. I am able to access token using IMDS endpoint when i login to a node in the SF cluster but from my code i am not able to get token. Same code works on my local SF cluster with my identity

            var azureServiceTokenProvider = new AzureServiceTokenProvider();  //defined in Microsoft.Azure.Services.AppAuthentication, Version=1.0.1.0
            string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync(resource);
            return accessToken;

Below is the error i see 
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException (-2146233088) Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked. Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the M at

**Comment by pavanpadavala** [comment]
@vikasparihar  Did you add your UserAssigned app to the keyvault access policies and clicked save? 
In local it may be using your identity to connect to keyvault. You can see this in azureServiceTokenProvider.PrincipalUsed property

**Comment by vikasparihar** [comment]
@pavanpadavala  yes i have given access to MSI on my keyvault using Policies. I am not sure which endpoint code is hitting in SF cluster. Is it IMDS endpoint or localhost one. When i login to cluster VM and execute Invoke WebRequest for IMDS it works but when i try using localhost it doesn't . Is there a need to define a environment variable AzureServicesAuthConnectionString as this doesn't exist on my cluster VM

**Comment by dragav** [comment]
The exception points to an MSI configuration issue - that is, an access token cannot be obtained. @vikasparihar The code you referenced above refers to [https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication](service-to-service auth), and is not related to SF. I suspect you may have multiple identities assigned to the VMSS, and so a 'default' identity cannot be resolved by the token request call.

**Comment by mikeruhl** [comment]
@dragav do you mind explaining that a little more?  I am having the same issue as @vikasparihar and not too sure where to go from here.  I have 1 managed identity in each VMSS (system-assigned).  I have added them to KeyVault access policies with appropriate permissions.  I can get the secret via `$response = Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -Method GET -Headers @{Metadata="true"}` directly on the node but via code does not work.  

I'm not using the same sample code though, I grabbed mine from [https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/key-vault-configuration/sample](here).

**Comment by mikeruhl** [comment]
So, just to put a button on this and hopefully it helps @vikasparihar , I found [https://luisfsgoncalves.wordpress.com/2018/09/06/asp-net-core-on-azure-service-fabric-accessing-key-vault-with-managed-identities-and-the-errors-on-the-token-endpoint/](this blog post) and once I added the "Lesson #1" of using `RunAs=App;`, it worked.  

From the blog. in case it's ever removed:
> Lesson #1: pass “RunAs=App;” in the connectionString parameter  of AzureServiceTokenProvider. This way it will not try different modes to obtain a token, and the exception is a bit better.
