### ISSUE TITLE
Not possible to set sfproj package location

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#127]
Neither `/p:PackageFileName` nor  `/p:DesktopBuildPackageLocation` work when packaging sfproj files, It's been working ok for web sites and what not. Known issue? Any workarounds?

**Comment by MikkelHegn** [comment]
You can use /p:PackageLocation to control where the directory that is you app package, will be placed. That directory is your package, so that would also be the package name.

**Comment by TarasRoshko** [comment]
That works, thanks! I'd be nice If docs mentioned this somewhere as it's sort of confusing there are at least 3 ways to set this and they don't consistently work for all projects
