### ISSUE TITLE
Error : activation.NotEnoughCPUForServicePackage  Service fabric deployment

### ISSUE THREAD

**Issue by Rakesh201180** [Azure/service-fabric-issues#1277]
We are getting activation.NotEnoughCPUForServicePackage error during application deployment.
We are setting MaxInstanceCount =1 and MinInstanceCount =1 in application manifest

Can anybody update more on this

Thanks

**Comment by MikkelHegn** [comment]
Do you have any ResourceGovernancePolicies set on the service and/or code packages? This is probably because the capacity is used on the nodes available.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-resource-governance#specify-resource-governance

**Comment by Rakesh201180** [comment]
Yes Mikkel We are having ResourceGovernancePolicies like below
<ServicePackageResourceGovernancePolicy CpuCores="0.8" MemoryInMB="1024" />

one question if we increase instance count  to 2,Is this get resolved ?

**Comment by MikkelHegn** [comment]
I suspect you don't have the capacity for the extra instance to be placed. Do you have other services running also with resource governance? As a default the cluster has 20% resources reserved for the system.
> To leave buffer space for the operating system, and for other processes might be running on the node, Service Fabric uses only 80% of the available resources on the node. This percentage is configurable, and can be changed in the cluster manifest.
From the above article.

Which means in your case 6.4 CPU cores and 25.6 GB of memory are available for the services.

**Comment by masnider** [comment]
@Rakesh201180 if you can provide more information about what other workloads you're running and the output of Get-ServiceFabricClusterLoadInformation and Get-ServiceFabricNodeLoadInformation for a node where you'd expect the service to be getting placed, then we can take a look. Also can you share the whole policies section for the application/service that you're trying to create?

**Comment by Rakesh201180** [comment]
Output for Get-ServiceFabricNodeLoadInformation

LastBalancingStartTimeUtc : 9/18/2018 3:28:39 AM
LastBalancingEndTimeUtc   : 9/18/2018 3:28:40 AM
LoadMetricInformation     : 
                            LoadMetricName        : Count
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0.00731707317073175
                            DeviationAfter        : 0.00731707317073175
                            BalancingThreshold    : 1
                            Action                : NewReplicaPlacementWithMove
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 41
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 4
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 5
                            MaxNodeLoadNodeId     : 806c9b3880b6eeda4cd82c40ef72ac3f
                            
                            LoadMetricName        : PrimaryCount
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NewReplicaPlacementWithMove
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 2
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : a7024d207c082809b932cf2be4f0f19b
                            
                            LoadMetricName        : ReplicaCount
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0.15
                            DeviationAfter        : 0.15
                            BalancingThreshold    : 1
                            Action                : NewReplicaPlacementWithMove
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 8
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                            LoadMetricName        : __ClusterManagerServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 1
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : a7024d207c082809b932cf2be4f0f19b
                            
                            LoadMetricName        : __ClusterManagerServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0
                            DeviationAfter        : 0
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 5
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                            LoadMetricName        : __FaultAnalysisServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 1
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : df1e5b5c1dd8e9f0a091fd43e7098b79
                            
                            LoadMetricName        : __FaultAnalysisServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0
                            DeviationAfter        : 0
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 5
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                            LoadMetricName        : __FileStoreServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 1
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : a7024d207c082809b932cf2be4f0f19b
                            
                            LoadMetricName        : __FileStoreServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0
                            DeviationAfter        : 0
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 5
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                            LoadMetricName        : __InfrastructureServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 2
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            
                            LoadMetricName        : __InfrastructureServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0.244948974278318
                            DeviationAfter        : 0.244948974278318
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 6
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            
                            LoadMetricName        : __NamingServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0.816496580927726
                            DeviationAfter        : 0.816496580927726
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 3
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : a7024d207c082809b932cf2be4f0f19b
                            
                            LoadMetricName        : __NamingServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0
                            DeviationAfter        : 0
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 15
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 3
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                            LoadMetricName        : __RepairManagerServicePrimaryCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 2
                            DeviationAfter        : 2
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 1
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : c310542333ba35d75b0cf29452e5d3e1
                            
                            LoadMetricName        : __RepairManagerServiceReplicaCount__
                            IsBalancedBefore      : True
                            IsBalancedAfter       : True
                            DeviationBefore       : 0
                            DeviationAfter        : 0
                            BalancingThreshold    : 1
                            Action                : NoActionNeeded
                            ActivityThreshold     : 0
                            ClusterCapacity       : 0
                            ClusterLoad           : 5
                            ClusterRemainingCapacity : 0
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 0
                            ClusterRemainingBufferedCapacity : 0
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            MaxNodeLoadValue      : 1
                            MaxNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            
                         ```
   LoadMetricName        : servicefabric:/_CpuCores
                            IsBalancedBefore      : False
                            IsBalancedAfter       : False
                            DeviationBefore       : 0.0874817765279709
                            DeviationAfter        : 0.0874817765279709
                            BalancingThreshold    : 1
                            Action                : NewReplicaPlacementWithMove
                            ActivityThreshold     : 0
                            ClusterCapacity       : 35
                            ClusterLoad           : 22.4
                            ClusterRemainingCapacity : 12.6
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 35
                            ClusterRemainingBufferedCapacity : 12.6
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 4.8
                            MaxNodeLoadNodeId     : 645e94150e8dcb37e6d571c75924cd74
                            
```
                            LoadMetricName        : servicefabric:/_MemoryInMB
                            IsBalancedBefore      : False
                            IsBalancedAfter       : False
                            DeviationBefore       : 0.0340206908719891
                            DeviationAfter        : 0.0340206908719891
                            BalancingThreshold    : 1
                            Action                : NewReplicaPlacementWithMove
                            ActivityThreshold     : 0
                            ClusterCapacity       : 163825
                            ClusterLoad           : 73728
                            ClusterRemainingCapacity : 90097
                            NodeBufferPercentage  : 0
                            ClusterBufferedCapacity : 163825
                            ClusterRemainingBufferedCapacity : 90097
                            ClusterCapacityViolation : False
                            MinNodeLoadValue      : 0
                            MinNodeLoadNodeId     : 173a69138303545817d3079f466a0cd9
                            MaxNodeLoadValue      : 15360
                            MaxNodeLoadNodeId     : 806c9b3880b6eeda4cd82c40ef72ac3f

**Comment by Rakesh201180** [comment]
Node _0
--
MetricName :   servicefabric:/_CpuCores
NodeCapacity :   6
NodeLoad : 4.8
NodeRemainingCapacity   : 1.2
NodeBufferedCapacity   : 6
NodeRemainingBufferedCapacity   : 1.2
IsCapacityViolation   : False
 
Node _1
MetricName :   servicefabric:/_CpuCores
NodeCapacity :   6
NodeLoad : 4
NodeRemainingCapacity   : 2
NodeBufferedCapacity   : 6
NodeRemainingBufferedCapacity   : 2
IsCapacityViolation   : False
 
Node _2
MetricName :   servicefabric:/_CpuCores
NodeCapacity :   6
NodeLoad : 4.8
NodeRemainingCapacity   : 1.2
NodeBufferedCapacity   : 6
NodeRemainingBufferedCapacity   : 1.2
IsCapacityViolation   : False
 
Node _3
MetricName :   servicefabric:/_CpuCores
NodeCapacity :   6
NodeLoad : 4.8
NodeRemainingCapacity   : 1.2
NodeBufferedCapacity   : 6
NodeRemainingBufferedCapacity   : 1.2
IsCapacityViolation   : False
 
Node _4
MetricName :   servicefabric:/_CpuCores
NodeCapacity :   6
NodeLoad : 4
NodeRemainingCapacity   : 2
NodeBufferedCapacity   : 6
NodeRemainingBufferedCapacity   : 2
IsCapacityViolation   : False

**Comment by puzovicnikola** [comment]
Hi @Rakesh201180 

Can you please open a support ticket for this problem?
This is required for us to take a look at logs from your cluster.

Just by looking at node loads that you provided it is not possible to determine what is going on.

Thanks.

**Comment by puzovicnikola** [comment]
Hi @Rakesh201180,

We haven't heard from you, so we're going to close this issue.
If you're still having this problem, please reopen and let us know what you are seeing.

Thanks.
