### ISSUE TITLE
Which version of remoting should I use for future proof

### ISSUE THREAD

**Issue by IvanAlekseev** [Azure/service-fabric-issues#1280]
Hi,

I am a bit confused with remoting versions described in [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting).

Which version of remoting v2 or v2_1 should I use going forward?
Also it is not clear to me what do you mean by interface compatible stack.

It will be nice to have a bit more info about that in documentation.

**Comment by IvanAlekseev** [comment]
Hello, any chance to have an answer here?

**Comment by VipulM-MSFT** [comment]
Use V2_1. 

Here is the bit of history:

The V2 remoting stack provided support for custom serialization and transport for remoting messaging. However in addition to the changes in the wire protocol, there were some changes in the way serialization types for method parameters were generated. This prevented some interfaces to be not functional over V2 remoting protocol. If your service was using such interface it could not upgrade from V1 to V2 implementation of remoting without taking the downtime. The V2_1 with the interface compatibility flag fix this issue.
