### ISSUE TITLE
Exception thrown during async task execution System.Runtime.InteropServices.COMException 

### ISSUE THREAD

**Issue by denisprsa** [Azure/service-fabric-issues#1284]
We have nodejs guest executable services, and one of our services was crashing due to unable to connect to another service. 

First few times when service crashed, it restarted successfully, but then after few restarts process just hanged unactive.

We tried to restart Code Package via fabric explorer but was nonresponsive.  In fabric traces we found following warnings:

1.) 
```
System.Runtime.InteropServices.COMException (0x80071BC7): Chaos has not been started; please call StartChaos with appropriate parameters.
```

2.) 
```
4016dbb7-e8e9-484b-a800-0af14d258291 - System.Runtime.InteropServices.COMException (0x80071BC7): Chaos has not been started; please call StartChaos with appropriate parameters.
   at System.Fabric.FaultAnalysis.Service.Chaos.ChaosUtil.ThrowNotReady(String message)
   at System.Fabric.FaultAnalysis.Service.Chaos.ChaosMessageProcessor.<ProcessGetChaosReportAsyncPrivate>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.FaultAnalysis.Service.Common.FaultAnalysisServiceUtility.<RunAndReportFaultOnRepeatedFailure>d__5`1.MoveNext()
```

3.)
```
4016dbb7-e8e9-484b-a800-0af14d258291:GetChaosReportAsync - Exception occurred: Chaos has not been started; please call StartChaos with appropriate parameters.
```

4.)
```
Exception thrown during async task execution
System.Runtime.InteropServices.COMException (0x80071BC7): Chaos has not been started; please call StartChaos with appropriate parameters.
   at System.Fabric.FaultAnalysis.Service.Chaos.ChaosUtil.ThrowNotReady(String message)
   at System.Fabric.FaultAnalysis.Service.Chaos.ChaosMessageProcessor.<ProcessGetChaosReportAsyncPrivate>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.FaultAnalysis.Service.Common.FaultAnalysisServiceUtility.<RunAndReportFaultOnRepeatedFailure>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.FaultAnalysis.Service.Chaos.ChaosMessageProcessor.<ProcessGetChaosReportAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.FaultAnalysis.Service.FaultAnalysisServiceImpl.<GetChaosReportAsync>d__25.MoveNext()
```

5.)
```
AsyncCalloutAdapter-18350765: end delegate threw an exception
System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017785)
Chaos has not been started; please call StartChaos with appropriate parameters. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BC7
   at System.Fabric.Interop.NativeClient.IFabricTestManagementClient4.EndGetChaosReport(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.TestManagementClient.GetChaosReportAsyncEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
```

Here are logs in this time frame, error occured on 5:48:19:
[fabric-bug-05-48-19-Caos.evtx.zip](https://github.com/Azure/service-fabric-issues/files/2401126/fabric-bug-05-48-19-Caos.evtx.zip)

**Comment by VipulM-MSFT** [comment]
@likevi-MSFT, @motanv  - can you follow up?

**Comment by likevi-MSFT** [comment]
Looking into the issue right now.

**Comment by likevi-MSFT** [comment]
I don't think the Restart CodePackage API would cause the Chaos related exceptions. I'm assuming you are calling Restart on your application and not FaultAnalysisService which is the service that runs Chaos.

**Comment by motanv** [comment]
For telemetry GetChaosReport is called once an hour, if Chaos has never been enabled in the cluster, those benign exceptions will occur. @denisprsa it seems that the issue is gone after you have fixed the bug in your sevice, is that correct?

**Comment by denisprsa** [comment]
I was testing on fabric what happens if service is crashing after the start. I wrote a simple stateless http nodejs app, which crashed on purpose after 30 seconds. 

After the first crash, there was a warning on explorer. At the second crash, an error appeared and after the fifth crash, error on explorer disappeared and service was no longer able to restart. Health state on explorer went to OK. 

You cannot know from fabric APIs that service is no longer running since health state is OK. 
Our service registry which is collecting health from services does report that service is no longer running. But is unable to do anything since restart is not working.

Is this expected?

Application Manifest:

```xml 
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="app-testing-crash" ApplicationTypeVersion="0.0.4" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="testing-crash" ServiceManifestVersion="0.0.4" />
  </ServiceManifestImport>
  <DefaultServices>
    <Service Name="app-testing-crashService">
      <StatelessService ServiceTypeName="testing-crash" InstanceCount="-1">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>
```

Service Manifest:

```xml
<ServiceManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="testing-crash" Version="0.0.4" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="testing-crash" UseImplicitHost="true" />
  </ServiceTypes>
  <CodePackage Name="Code" Version="0.0.4">
    <EntryPoint>
      <ExeHost>
        <Program>node.exe</Program>
        <Arguments>app.js</Arguments>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="NODE_ENV" Value="production" />
      <EnvironmentVariable Name="SERVICE_REGISTRY_PORT" Value="3501" />
    </EnvironmentVariables>
  </CodePackage>
</ServiceManifest>
```

**Comment by motanv** [comment]
@denisprsa, were you able to collect the SF logs this time, now that you can repro it at will? If the cluster in on your Windows machine you may find them following the value of registry key FabricLogRoot like C:\SfDevCluster\Log\Trace and they look like “fabric_traces_6.3.187.9494_131848675483647056_0.etl” 

C:\Users\motanv>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric
    FabricRoot    REG_EXPAND_SZ    C:\Program Files\Microsoft Service Fabric
    FabricBinRoot    REG_EXPAND_SZ    C:\Program Files\Microsoft Service Fabric\bin
    FabricCodePath    REG_EXPAND_SZ    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code
    FabricDataRoot    REG_EXPAND_SZ    C:\SfDevCluster\Data
    FabricLogRoot    REG_EXPAND_SZ    C:\SfDevCluster\Log
    FabricVersion    REG_EXPAND_SZ    6.3.187.9494
    CompatibilityJsonPath    REG_EXPAND_SZ    C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\SdKRuntimeCompatibility.json
    UseFabricInstallerSvc    REG_DWORD    0x1
    EnableCircularTraceSession    REG_DWORD    0x1
    NodeLastBootUpTime    REG_SZ    10/19/2018 5:27:54 PM
    FabricDnsServerIPAddress    REG_SZ    10.31.60.134

Also, is it at all possible to share the sample application package that you wrote to repro with us, so that we could take a deeper look? Also, is this a cluster on your dev box? Is it a Windows or Linux cluster? What is the version of ServiceFabric runtime and ServiceFabric sdk that you are using?

**Comment by denisprsa** [comment]
@motanv here are the traces. Unfortunately, I cannot share code that is causing this. Simple hello world app was restarting for infinite time. SF is running on Windows and on Azure.

However, I was able to find another log. When service stop responding this appeared in Deployed Service Package details. I cannot find anything that would explain what went wrong.

```The CodePackage was activated successfully.The service host terminated with exit code:7147```

In logs this is EventID: 23042 at 11/5/2018 11:50:04 AM

[fabric_traces_6.3.187.9494_131836167162373812_765.zip](https://github.com/Azure/service-fabric-issues/files/2548410/fabric_traces_6.3.187.9494_131836167162373812_765.zip)

**Comment by motanv** [comment]
Sorry, just to clarify, the issues with you service are gone, right? 
You are saying that the following appears to indicate the there is a bug in ServiceFabric, right?

"After the first crash, there was a warning on explorer. At the second crash, an error appeared and after the fifth crash, error on explorer disappeared and service was no longer able to restart. Health state on explorer went to OK.

You cannot know from fabric APIs that service is no longer running since health state is OK.
Our service registry which is collecting health from services does report that service is no longer running. But is unable to do anything since restart is not working."

The situation sounds like blocklisting:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-management-integration#blocklisting-nodes

**Comment by denisprsa** [comment]
It does behave like it's described in the docs.

Sorry for bothering you, but I couldn't find it in the docs why this was happening.

Thanks.

**Comment by denisprsa** [comment]
@motanv I have one more question. As I was trying some stuff, I came across some weird behavior.

If service is crashing (more than 3 times in row) and then calling ``` /Nodes/_produ_0/$/GetApplications/service-fabric-testing/$/GetCodePackages/$/Restart?api-version=3.0&_cacheToken=1541667026012 ``` API,  service will go to health state OK, and you will get this message:  ``` The CodePackage was activated successfully.The service host terminated with exit code:7147 ```. 

It seems that service never restarts again.

Is this expected?
