### ISSUE TITLE
Register-ServiceFabricClusterpackage fails with file not found

### ISSUE THREAD

**Issue by JanMcke** [Azure/service-fabric-issues#1286]
I ran into a problem where I can't upgrade a cluster configuration.
The problem seems to be identical to
https://github.com/Azure/service-fabric-issues/issues/988

However, when I follow the steps to repair the issue, the command Register-ServiceFabricClusterpackage, no matter what I provide returns a 'File not found' error.

![image](https://user-images.githubusercontent.com/43542279/45955323-df685800-c00f-11e8-86b7-51a524c05801.png)

Any idea on how to proceed?

**Comment by oanapl** [comment]
I see you copied the ClusterManifest.xml to the cluster, but you didn't copy the cab file. You need to copy that too and then specify CodePackagePath as the path from image store.

(Unrelated) 6.1 is out of support, consider a [newer Service Fabric version](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-versions).

**Comment by JanMcke** [comment]
Thanks!
That did the trick
