### ISSUE TITLE
Service Fabric + Key Vault ARM Template

### ISSUE THREAD

**Issue by jonmill** [Azure/service-fabric-issues#1287]
I'm trying to create an ARM template in an Azure Managed Application that will create a secured Service Fabric Cluster and Key Vault (among other resources), but this doesn't seem to be supported from the documentation I could find (most require a Key Vault already be created and already have a certificate stored). Is there a way to create a secured Service Fabric cluster and corresponding Key Vault using ARM templates without any previous resources already created?

**Comment by dragav** [comment]
@jonmill would you be open and available for a quick call next week with folks from ARM and SF? If so, please reply to dragosav at Microsoft dot com. Thanks!

**Comment by aljo-microsoft** [comment]
@jonmill 
Please reach out to me at aljo@microsoft.com if you'd like to collaboratively design a solution.

If the question is simply "Can you provision Certificate, which is NOT an Azure Resource, in Keyvault through ARM"

The answer is not today.

Certificates are NOT azure resources, and Keyvault certificate policies can NOT be defined in an ARM template; you must use Rest API (I.E. az cli, portal, et) to create a certificate policy for your keyvault.
