### ISSUE TITLE
Service Fabric backup restore service - upload fails

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#1288]
I’ve configured the Service Fabric backup and restore service to create periodic backups.
Followed [this ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster )guideline.

My target service displays an error message:
“Failed to take periodic backup for this partition with error:\nSystem.Fabric.FabricException: An error occurred during this operation.  Please check the trace logs for more details. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C7D
   at System.Fabric.BackupRestore.Interop.NativeBackupRestoreRuntime.IFabricBackupRestoreAgent.EndUploadBackup(IFabricAsyncOperationContext context)”

The backup container in the storage account is created, but no backups are in it. 

Storage account:
-	General purpose **v2**
-	Premium tier
-	Secure access required

Please note that when I use a standard **V1** storage account it works properly.

**Comment by hrushib** [comment]
@loekd, Service Fabric backup restore service requires storage to support Block blobs which are not supported by Premium tier Storage account. If you use Standard V2 storage account this should work as expected.
Is there any reason to use Premium tier Storage account for backup storage?

**Comment by hrushib** [comment]
@loekd, closing this issue as Premium tier Storage account is not supported. Please file another issue in case Premium tier Storage account is must for backup storage for your scenario and we will treat that as feature request and prioritize appropriately.

**Comment by loekd** [comment]
@hrushib Thanks for the update. 
Could you mention this in the documentation, so people don't need to find out here why their backup doesn't work?
