### ISSUE TITLE
If my service fabric project contains 5 services which are already deployed to production, can i deploy only 2 services next time which are changed or I have to deploy all 5 again?

### ISSUE THREAD

**Issue by rspandi1985** [Azure/service-fabric-issues#1290]

**Comment by guibirow** [comment]
You can do a differential packaging to deploy only the changed services.

Take a look on the following links:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#upgrade-with-a-diff-package

https://stackoverflow.com/questions/34873891/differential-packaging

**Comment by oanapl** [comment]
@rspandi1985 , as @guibirow replied, diff packaging will help you achieve this. I will close the issue, if you have other questions feel free to re-open this one or open new one.
