### ISSUE TITLE
Upgrading broken ServiceFabric application

### ISSUE THREAD

**Issue by arunas-z** [Azure/service-fabric-issues#1292]
Recently Azure has experienced outage due to storms, which caused our application to stuck into crash-restart loop.

The failing dependency was Azure Log Analytics which was not critical, so we have made an update where we just disabled it temporarily.

Unfortunately in situation like this the upgrade deployment process does not work smoothly. 
100% of applications and their replicas are in error health state, so upgrade with default parameters fails because of health validation. Setting MaxPercentUnhealthyXYZ to 100% for upgrade seems wrong, but is is this what needs to be done in this case?

Another issue is that Service Fabric sends events to service processes and waits for the response before proceeding. If the process is misbehaving or hanging it results timeouts. Since our app was down anyway I tried to remove it with -ForceRemove and recreating it from newly deployed type but I recall I had to remote to the nodes and kill the processes manually for this to finally succeed - it was taking too long.

So my question is, what parameters etc. needs to be set for Start-ServiceFabricApplicationUpgrade to upgrade in this level of brokenness? Or something else needs to be done to roll forward in such scenario?

**Comment by oanapl** [comment]
If the application is in really bad state and it's not functioning anyway, one option is to set the upgrade to Unmonitored Auto or Unmonitored Manual, which does no health checks. Another thing that may be needed is to reduce [UpgradeReplicaSetCheckTimeout](https://docs.microsoft.com/azure/service-fabric/service-fabric-application-upgrade-parameters) to not wait for safety checks like partition quorum.

**Comment by oanapl** [comment]
@arunas-z , we haven't heard back from you. I will close this issue. If you still have questions or need more information, feel free to re-open.
