### ISSUE TITLE
Internal only service over http

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#1295]
Hi we have an asp.net core (stateful) service running on http exposing couple of endpoints.
While we have marked the endpoint as internal explicitly even than when using the reverse proxy we are able to access the service endpoints (Conceptually I thought internal services should not be accessible from outside) 
example endpoint we are accessing is :[https://*.com/{applicationname}/RegistryService/api/Registry/test?PartitionKey=0&PartitionKind=Int64Range]()
The services endpoint is defined as : 
` <Endpoint Name="RegistryEndpoint" Type="Internal" Protocol="http"  />`

Note due to this these endpoints showup in the swagger documentation aswell, eventhough the swagger is configured in another service on the same cluster.
Is there some specific setting to set a service as internal only ?

**Comment by usamaazhar** [comment]
Looks like no one wants to reply :)

**Comment by vturecek** [comment]
The "Type" attribute in the Endpoint element doesn't do anything. You have to make the reverse proxy port inaccessible outside your cluster by closing the port on your load balancer.

**Comment by usamaazhar** [comment]
The thing is we are using reverse proxy for other services we want to expose, cant we have some services as internal ?  If this is not possible whats the whole point of having the internal stateful services ?

**Comment by masnider** [comment]
This is not possible today with the built-in reverse proxy on Windows. If the reverse proxy is exposed outside the cluster, then all services are exposed externally. If it is used within the cluster only, then all services are exposed, but only internally. We are working on addressing this shortcoming of the reverse proxy in upcoming releases.

**Comment by usamaazhar** [comment]
Thanks for the update :)

**Comment by usamaazhar** [comment]
Will be interested in knowing when this would get released?

**Comment by masnider** [comment]
This is currently not planned and we do not have a timeframe for doing so. For the most part, we've seen people being with other networking layers on top of or in place of the existing reverse proxy as a means of exposing some services and not others. The integration available via [Traefik ](https://docs.traefik.io/v1.7/configuration/backends/servicefabric/)is one option, as is [APIM ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-overview) within Azure.
