### ISSUE TITLE
SDK 3.2.176 installation broken

### ISSUE THREAD

**Issue by michael-damatov** [Azure/service-fabric-issues#1296]
The installer tries to download "MicrosoftServiceFabric.6.3.176.9494.exe" with invalid signature.

More details here: https://github.com/MicrosoftDocs/azure-docs/issues/15897

Log file: https://github.com/MicrosoftDocs/azure-docs/files/2433570/webpi11.txt

**Comment by MikkelHegn** [comment]
@maburlik

**Comment by MikkelHegn** [comment]
From log file:

DownloadManager Error: 0 : Signature verification failed on downloaded file. URL: https://download.microsoft.com/download/1/A/A/1AA062F9-0E1D-40E9-BD4F-6F12ABB71083/MicrosoftServiceFabric.6.3.176.9494.exe. File location: C:\Users\damatov\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_3_CU1\4899616B52FD9EB3F6EAB9F595BBC44D1081A5E4\MicrosoftServiceFabric.6.3.176.9494.exe. File size: 94460 kb

**Comment by maburlik** [comment]
Based on this https://forums.iis.net/t/1195572.aspx
it seems this can happen if a firewall filters downloaded files. Can you check if this is applicable, and if so add an exception for downloaded files from: https://download.microsoft.com

In addition, delete the cached installer directory here to force a re-download of the file:
C:\Users\damatov\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_3_CU1\

Let us know if still hit issues after this.
