### ISSUE TITLE
Azure Blob Storage is not working inside Service Fabric

### ISSUE THREAD

**Issue by nikubesliu** [Azure/service-fabric-issues#1297]
We have a stateless AspNet.Core service running in Service Fabric local cluster. When we are trying to upload an image to Azure Blob Storage we receive a request timeout. The same code is working ok outside service fabric. We are behind a corporate proxy. Can we somehow solve this problem ?

**Comment by masnider** [comment]
When you say outside service fabric, you mean on the same node you can launch the same process and that can connect?

Usually this is some permissions or connectivity issue on the cluster machines.

**Comment by dkkapur** [comment]
Closing this due since it's been a while. Happy to reopen and address if still relevant. Thanks!
