### ISSUE TITLE
VS2015 Upgrade publishing to cloud fails when version # is same as local

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/service-fabric-issues#13]
I get the following error message during publishing:

> An attempt was made to upgrade the application but the application's version has not been changed.  Be sure to update the version in the application manifest prior to upgrading.

Steps to reproduce:
- Deploy SF app upgrade to local cluster at version X (prior version is X-n) [this succeeds]
- Deploy SF app upgrade to cloud cluster at version X (prior version is X-m) [this fails]

Workaround:
- Increment the version to X+1 before deploying to cloud cluster

**Comment by seanmck** [comment]
Thanks for reporting this, Lars. We will have a fix out in the 1.2 release of the VS tools, which should be available in early August.

**Comment by LarsKemmann** [comment]
Good to hear, thank you!

Sent from my phone



On Fri, Jul 15, 2016 at 2:26 PM -0400, "Sean McKenna" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting this, Lars. We will have a fix out in the 1.2 release of the VS tools, which should be available in early August.

-

**Comment by yustun** [comment]
Hi, 
I am getting the same error. is this really fixed?

**Comment by PetriOosthuizen** [comment]
Update publishing profiles Upgrade deployment mode:
`<UpgradeDeployment Mode="Monitored" Enabled="false">`
