### ISSUE TITLE
How to control Build Configuration in PublishProfile when publishing from VS

### ISSUE THREAD

**Issue by marclallen** [Azure/service-fabric-issues#1308]
When I was deploying my solution as a Cloud Service, the publish profile included a build configuration.  So, no matter what the solution build configuration was set to, when I published to environment X, I always built and used the correct configuration.

That appears to be different for Service Fabric, and, frankly, it's causing grief.  I can't tell you the number of times I have accidentally deployed the wrong build to a given cluster because I neglected to properly set the solution build configuration.

Any suggestions?  I'd like, as an improvement, that a build configuration be included in the publish profile and that it be used as the build that occurs before the publish.

**Comment by dbreshears** [comment]
Seems like a reasonable request.   Will look into adding this to our Publish dialog in a future release.

**Comment by dbreshears** [comment]
Closing as BuildConfiguration support was added to the PublishProfile awhile back
