### ISSUE TITLE
UpgradeService.Primary SFRPStreamChannel fails intermittently

### ISSUE THREAD

**Issue by enemaerke** [Azure/service-fabric-issues#1315]
Hi all

We are seeing some intermittent errors from the UpgradeService on our cluster, where an error with TTL of 10 minutes is raised. It seems like once we get the error (through our alerting system) and we go to inspect the cluster through  ServiceExplorer there are no other indications ofther than the TTl 10 minute error and the rest of the service reports OK. The following  stacktrace is shown in the ServiceExplorer:

Error event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel'.
Exception encountered: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamReader.d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamReader.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Fabric.UpgradeService.WrpStreamChannel.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Fabric.UpgradeService.WrpStreamChannel.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Fabric.UpgradeService.ClusterCoordinator.d__16.MoveNext()

Is this a known error and how can we avoid it. It triggers our alerting setup and we'd like to understand why this is happening in an (seemingly) otherwise healthy system.

**Comment by enemaerke** [comment]
Any progress on this? Have you identified a root cause?

**Comment by enemaerke** [comment]
...and I'll ping this once more.

Can I get an indication of someone actually working on or looking into this issue? Our monitoring systems kicks off on this exception and it is becoming less fun to get automated txt messages in the middle of the night.

**Comment by vaishnavk** [comment]
@TassaduqBasu: Can we take a look at this? Maybe the health reporting from FabricUS is still too aggressive.

**Comment by TassaduqBasu** [comment]
@jkochhar, Can you please follow-up on this. Please include Marius as needed.

**Comment by jkochhar** [comment]
@enemaerke What's the version of your SF cluster? Please ping me @jkochhar AT microsoft DOT com and we can follow up there.

**Comment by aljo-microsoft** [comment]
Thank you for filing a Service Fabric Issue for UpgradeService.

There are several reasons why your clusters UpgradeService could go into an error state, and yes you need to be concerned and respond to the incident in alignment with you management process and SLA’s.

An example is a user deploys a NSG rule that blocks communication between your cluster and Azure Service Fabric Resource Provider; please adopt [Service Fabric Networking best practices](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-networking#cluster-networking) to mitigate preventable issues. 

Another example is a user forgets to apply an [Access Control List (ACL) to your certificate for your Service Fabric Cluster](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#apply-an-access-control-list-acl-to-your-certificate-for-your-service-fabric-cluster), when deploying a new certificate thumbprint, resulting in their cluster being unable to access the certificate installed on their machines; please adopt [Azure Service Fabric Security Best Practices of secure a cluster by certificate common name](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#secure-a-service-fabric-cluster-certificate-by-common-name) to mitigate preventable issues.

Please ensure all reliable environment comply with [Azure Service Fabric Production readiness checklist](https://docs.microsoft.com/azure/service-fabric/service-fabric-production-readiness-checklist), leverage the appropriate [support options](https://docs.microsoft.com/azure/service-fabric/service-fabric-support), and self service discovering if your issue symptoms indicate it could be mitigated using an available [Troublehshooting guides](https://github.com/Azure/Service-Fabric-Troubleshooting-Guides).

Although I'm closing this, feel free to reopen if you need additional clarity on how to mitigate preventable issues.
