### ISSUE TITLE
ApplicationGateway.exe stopped running on a few nodes in cluster

### ISSUE THREAD

**Issue by hkuizenga** [Azure/service-fabric-issues#1318]
Hi folks,

We have an existing cluster which abruptly started showing a handful of nodes as down in the cluster.  Upon investigating, we discovered that ApplicationGateway.exe is not running on those nodes (and that it is running on nodes still showing as up).  We have not made any configuration changes in our cluster, so I'm trying to figure out how to figure out why this is not running.  Are there certain things to look for in the event log?  Other logging files? etc.  

I need to figure out why these nodes are down and get them up and running.  Any help would be appreciated.

Thanks,
Howard

**Comment by hkuizenga** [comment]
I found the following in my fabric_traces files around the time that the issue began.  I do not see any errors before these.  

![image](https://user-images.githubusercontent.com/36278411/47135737-ba61b080-d26e-11e8-844a-d3725817dd50.png)

![image](https://user-images.githubusercontent.com/36278411/47135754-c51c4580-d26e-11e8-9140-99faad18d155.png)

![image](https://user-images.githubusercontent.com/36278411/47135779-d6655200-d26e-11e8-842f-4a286f933ac7.png)

Any help would be appreciated.

Thanks,
Howard

**Comment by VipulM-MSFT** [comment]
Lease failures typically indicate network partition among the nodes of the cluster.
