### ISSUE TITLE
Reserved Instance for existing Service Fabric cluster

### ISSUE THREAD

**Issue by gicat** [Azure/service-fabric-issues#1319]
Is it possible to apply reserved instance to an existing Service Fabric cluster?
Otherwise, how to modify an existing Service Fabric template to apply reserved instance during creation?
Thanks.

**Comment by gicat** [comment]
Where can I find more documentation on this argument? Thanks.

**Comment by gicat** [comment]
Thanks. After buying, for example, 5 instances for 3 years, I should be able to assign the reserved instances to existing SF's VMSS?

**Comment by masnider** [comment]
As far as the service fabric team knows yes, but this might be a good question for general azure support. There's nothing special about the VM's themselves, so SF doesn't care.

**Comment by aljo-microsoft** [comment]
@gicat 

This is at the subscription billing level and should work:
https://docs.microsoft.com/en-us/azure/billing/billing-save-compute-costs-reservations
