### ISSUE TITLE
Can't add additional Client Certificate with PowerShell

### ISSUE THREAD

**Issue by bigglesuk69** [Azure/service-fabric-issues#1321]
I've been trying to add a second client certificate to a test Service Fabric cluster in Azure using the following command: -

_Add-AzureRmServiceFabricClientCertificate -ResourceGroupName $serviceFabricInstanceRG -Name $serviceFabricInstanceName -Thumbprint $clientThumbprint_

Every time it errors, but when trying through the portal it works without issues.

> Add-AzureRmServiceFabricClientCertificate : Code: AuthenticationTypeCannotBeChangedByRemovingCertificate, Message: The certificate cannot be removed since the authentication type of the cluster cannot be modified.

Any ideas why this isn't working? It seems to be version 0.3.12 of the AzureRM.ServiceFabric module that I'm running.

**Comment by aljo-microsoft** [comment]
@bigglesuk69 
Please use ARM to achieve this:
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-model-clusterproperties#clientcertificatethumbprints

That command-let: https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/add-azurermservicefabricclientcertificate?view=azurermps-6.11.0

Error is telling you it cannot perform the simultaneous action of removing old cert, and deploying new one at the same time. Using arm properties I referenced, will allow you to declare the second certificate while leaving the first one in place. At the end of that deployment, you can do a second deployment to remove the certificate, if that is what you want to do.
