### ISSUE TITLE
Poor deployment experience with ARM templates

### ISSUE THREAD

**Issue by xenalite** [Azure/service-fabric-issues#1327]
I deployed a dev cluster from the Marketplace template. It creates a massive, single template to deploy everything.
I now have to "productionize" the deployment using some ARM templates with our corporate standards applied. For instance, they can create a generic VMSS - without OS profile certificates or extensions, and return a JSON object, which I can then consume in my "update" templates to add product-specific enhancements.

This mode of deployment is totally out the window with Service Fabric templating. I don't want to output a single giant template that will do everything. I want to componentize my deployments into smaller chunks, onto which I can layer more and more changes.

To add a SF node extension to a VMSS, I can only apply it at VMSS creation time, and not to an existing VMSS. Why is that? I configured the extension as such and got the error below:
```
"serviceFabricNodeExtension": {
      "name": "[concat(variables('vmScaleSetName'), '_ServiceFabricNode')]",
      "properties": {
        "publisher": "Microsoft.Azure.ServiceFabric",
        "type": "ServiceFabricNode",
        "typeHandlerVersion": "1.0",
        "autoUpgradeMinorVersion": true,
        "settings": {
          "clusterEndpoint": "[parameters('serviceFabricConfig').clusterEndpoint]",
          "nodeTypeRef": "[parameters('serviceFabricConfig').nodeType]",
          "dataPath": "[parameters('serviceFabricConfig').dataPath]",
          "durabilityLevel": "[parameters('serviceFabricConfig').durabilityLevel]",
          "enableParallelJobs": true,
          "nicPrefixOverride": "[parameters('serviceFabricConfig').subnetAddressSpace]",
          "certificate": {
            "thumbprint": "[parameters('serviceFabricConfig').certificateThumbprint]",
            "x509StoreName": "My"
          }
        },
        "protectedSettings": {
          "StorageAccountKey1": "[parameters('serviceFabricConfig').logStorageAccountKey1]",
          "StorageAccountKey2": "[parameters('serviceFabricConfig').logStorageAccountKey2]"
        }
      }
    },
```

```
"error": {
    "code": "OperationNotAllowed",
    "message": "VM Scale Set extensions of handler 'Microsoft.Azure.ServiceFabric.ServiceFabricNode' can be added only at the time of VM Scale Set creation."
  }
```

Also, to apply this extension, I need to know details about the SF cluster resource, like the cluster endpoint (e.g. https://westeurope.servicefabric.azure.com/runtime/clusters/<guid>).
`"clusterEndpoint": "[parameters('serviceFabricConfig').clusterEndpoint]",`

But to deploy a SF cluster resource - I need to know about VMSS details to populate node types. This is a chicken and egg problem - what do I deploy first? The SF cluster or scale sets? 
And how do I apply a SF node extension to an existing scale set?

**Comment by aljo-microsoft** [comment]
@xenalite 
As the error stated, extensions are creation time provisioning operations. 

You can use linked templates to achieve your layering, or resource declaration file seperation:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-linked-templates

But you must include the extension at provisioning time.

**Comment by johncrim** [comment]
I ran into the same issue. It turns out that the `Microsoft.ServiceFabric/clusters` resource needs to be created before the VM ScaleSet + extensions. So if structuring your ARM templates to separate/modularize your resources, keep that in mind. You can use a reference or a link to the created `Microsoft.ServiceFabric/clusters` to resolve the endpoint.

I had to figure this out, didn't see it in the docs anywhere.
