### ISSUE TITLE
Service Fabric FabricRuntime.dll not found if JRE higher on %PATH%

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#133]
If JRE is installed before SF SDK, SF tries to load `zip.dll` from JRE installation. The mitigation is to move SF SDK all the way up on system %PATH%

Originally found on [stackoverflow](http://stackoverflow.com/questions/33826002/service-fabric-fabricruntime-dll-not-found)

**Comment by masnider** [comment]
Hi @TarasRoshko What version of the SDK and runtime are you using? We had this bug but it was resolved a long time ago (pre-GA, I believe, ~start **2016**) Can you check can check bin/Fabric/Fabric.Code in the node's working directory to see if it has a dll named FabricZip.dll or Zip.dll ?

**Comment by TarasRoshko** [comment]
```
λ get-module -Name "ServiceFabric"

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.1.0.0    ServiceFabric                       {Add-ServiceFabricNode, Approve-ServiceFabricRepairTask, Complete-ServiceFabricRepairTask, Connect-ServiceFabricCluster...}
```

Downloaded latest SDK from Azure like days ago, will check the node directory once get something deployed and reply here

**Comment by TarasRoshko** [comment]
`C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricZip.dll`
`zip.dll` not present anywhere on the box (scanned all drives)

**Comment by masnider** [comment]
Ok, and are you actually still seeing the issue or are you just echoing what folks reported on SO back in the day?

**Comment by TarasRoshko** [comment]
Why would I echo a bug which has been fixed? :) I installed the SDK some days ago using
`https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started`
`Install the Microsoft Azure Service Fabric SDK` link

File `MicrosoftAzure-ServiceFabric-VS2015.exe` version `7.1.50430.0`

**Comment by masnider** [comment]
Who knows - but with the latest you shouldn't be seeing zip.dll as the culprit. That dependency was moved to FabricZip.dll as you can see. So I wonder if it isn't some other resource (or how are you determining that it is zip.dll?. Is that the error you are actually receiving? Can you share the actual stack trace/exception? Last I knew it just said FabricRuntime.dll couldn't be loaded but not the underlying resource.

Also that version you give is just the version of the WebPI launcher. As you have in other threads it would be good if you showed the SDK and runtime version as listed in programs. If you need help finding it let me know. Also if you can share the version and type of java SDK/Runtime that you have we can try to repro the issue.  

Adding some folks to help take a look

**Comment by TarasRoshko** [comment]
Sorry for the delay, I'll try to repro on a clean VM this week and let you know the result, meanwhile:

`java -XshowSettings:properties -version`

```
...
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_111-b14
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_111
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.111-b14
    line.separator = \r \n
    os.arch = amd64
    os.name = Windows 10
    os.version = 10.0
...
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
...
```

SF SDK downloaded from [official downloads here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started) some two weeks ago

```
2.4.145
5.4.145
```

I never installed any previous versions

**Comment by VipulM-MSFT** [comment]
@TarasRoshko - I am closing this issue as we have not seen this in our testing with the latest SDK and runtime. If you do happen to get a repro, please provide the information and feel free to reopen the issue.

**Comment by Jose-CF** [comment]
Hello...
I am experiencing this issue with latest SDK and ServiceFabric packages.
