### ISSUE TITLE
Failed to login to hyperv container

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/service-fabric-issues#1330]
Service Fabric version: 6.3.187.9494
Node image: 2016-Datacenter-with-Containers

Windows Server 1607 hosting microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 with isolation=hyperv fails to run docker exec -it <container_id> cmd with error: 

container <container_id> encountered an error during CreateProcess: failure in a Windows system call: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (0x274c)

**Comment by gkhanna79** [comment]
@gustavo-armenta Can you confirm that the container is running when you are attempting to connect to it via _docker exec_? Additionally, can you please provide the following data?

- Are you running as admin when attempting to _exec_? 
- If you run the container outside SF, are you able to exec into it?

**Comment by masnider** [comment]
Closing this issue as we haven't heard back. If you are still experiencing this issue, please reopen and provide the steps to repro, or open a new issue with the additional information that @gkhanna79 mentioned. Thanks!
