### ISSUE TITLE
New-AzureRmServiceFabricCluster fails with "At least 5 vm instances required for Silver reliability level"

### ISSUE THREAD

**Issue by joudot** [Azure/service-fabric-issues#1332]
When running New-AzureRmServiceFabricCluster with 3 as a cluster size, the following error is returned:

> Primary NodeType 'nt1vm' has only 3 vm instances. At least 5 vm instances required for Silver reliability level.

The cmdlet should allow to override the reliability tier or it should be deduced from the cluster size.

**Comment by ChackDan** [comment]
Thankyou for the feedback. the suggestion for improvement has been added to the backlog. The error message is clear enough on the next steps, but can do with the improvement you mention.

**Comment by MichelZ** [comment]
Any updates?

**Comment by ChackDan** [comment]
@MichelZ - This improvement is a part of our backlog and we will work on it as time permits. In the meanwhile You can make changes to your ARM template to add more nodes to the primary node type first, before changing the reliability. You can use AzureRmResourceGroupDeployment powershell provided by the ARM team for this.

**Comment by joudot** [comment]
@MichelZ: a good option for me is to use
`az sf cluster create --resource-group "SF-cluster-rg" --location "eastus"  --certificate-output-folder ".\" --vault-name "SF-cluster-kv" --vault-resource-group "SF-cluster-rg" --cluster-size 3 --vm-os "WindowsServer2016DatacenterWithContainers"  --vm-password "<MY_PASSWORD>" --vm-user-name "myadmin" --certificate-subject-name "SF-cluster-rg"`

**Comment by peterpogorski** [comment]
@joudot In order to declare the durability level using the New-AzureRmServiceFabricCluster cmdlet you must use the -TemplateFile parameter and set the durability level within the template.  You can set the durability level in the SF extension section for a Virtual Machine Scale Set resource. 

@MicahMcKittrick-MSFT
Please close this
