### ISSUE TITLE
[Question] Why KestrelCommunicationListener doesn't call IWebHost.StopAsync?

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/service-fabric-issues#1333]
Based on the documentation of `IWebHost.StopAsync` method it should be used to gracefully stop the host.

Recently I have noticed that when using `KestrelCommunicationListener` the `StopAsync` method is never called even when the listener is gracefully shutdown using `KestrelCommunicationListener.CloseAsync`.

I've checked the `CloseAsync` method implementation and noticed that it doesn't call `StopAsync` method but instead it calls the `Dispose` method. 

I understand why `KestrelCommunicationListener.Abort` implementation does this but can you explain why the `StopAsync` step is ignored in `CloseAsync` method?

**Comment by amanbha** [comment]
The communication listener can be used for aspnetcore 1.0.* which didn't have the CloseAsync. CloseAsync was added in later versions of aspnetcore.
