### ISSUE TITLE
Unable to upgrade VMSS Service Fabric Extension Version

### ISSUE THREAD

**Issue by rabsie** [Azure/service-fabric-issues#1335]
Hello,

I am currently trying to upgrade my Virtual Machine Scale Set Service Fabric Extension using the az cli. 

```
az vmss extension set --vmss-name svns-sfn --resource-group svns-ServiceFabric --name ServiceFabricNodeVmExt_vmNodeType0Name --publisher Microsoft.Azure.ServiceFabric --version 1.1 --force-update
On resource 'svns-sfn', extension name 'ServiceFabricNodeVmExt_vmNodeType0Name' cannot be used for more than one extension.
```
Getting the extension yields:
```
az vmss extension show --vmss-name svns-sfn --resource-group svns-ServiceFabric --name ServiceFabricNodeVmExt_vmNodeType0Name
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": null,
  "name": "ServiceFabricNodeVmExt_vmNodeType0Name",
  "protectedSettings": null,
  "provisioningState": null,
  "publisher": "Microsoft.Azure.ServiceFabric",
  "settings": {
    "certificate": {
      "thumbprint": "<redacted>",
      "x509StoreName": "My"
    },
    "clusterEndpoint": "<redacted>",

    "dataPath": "C:\\\\SvcFab",
    "durabilityLevel": "Silver",
    "enableParallelJobs": true,
    "nicPrefixOverride": "<redacted>",
    "nodeTypeRef": "svns-sfn"
  },
  "type": "ServiceFabricNode",
  "typeHandlerVersion": "1.0"
}
```
Is there a supported way to update the version of the Service Fabric extension? The only guidance I can find around updating extension versions is to uninstall and re-install. The [azure cli docs](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#az-vmss-extension-set) seem to imply the force-update parameter should update the extension even without configuration changes.

**Comment by aljo-microsoft** [comment]
@rabsie 
You should always use an ARM template to make a change to your Azure resources:

Specifically typeHandlerVersion SF extension property value should be change in this case.

Please reopen if you are having issues.

**Comment by DOliana** [comment]
@aljo-microsoft how should the ARM template look if the latest stable version of the extension is to be used? Removing the typeHandlerVersion is not the solution (at least not for an existing cluster).
Also is there a place where the parameters for the extension are documented?

**Comment by palenshus** [comment]
I reached out to Azure support and was directed to change the setting through the Azure Resource Explorer, which worked for me! Hope this helps others.

Navigate to:
https://resources.azure.com/subscriptions/[subscriptionId]/resourceGroups/[resource group]/providers/Microsoft.Compute/virtualMachineScaleSets/[vmss]/extensions/[vmss]_ServiceFabricNode

(or you can just go to https://resources.azure.com and navigate to your VMSS via the UI)

Click Edit, change the typeHandlerVersion to 1.1, then PUT
