### ISSUE TITLE
Azure Service Fabric deployment issue

### ISSUE THREAD

**Issue by dirkslab** [Azure/service-fabric-issues#1337]
We have the following environments sbx, dev, tst, stg and prd. All Azure ARM resources gets deployed using VSTS CI/CD pipeline. I regularly deploy (running for almost a year).
Today Azure Service Fabric Cluster deployment Step started failing. There has been no changes to the SFC ARM template and the last round of deployments in Sept 2018 were all successful. If I redeploy the last successful deployment, I still get this new error. Please see error below from VSTS failed Release.

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
Details:
BadRequest: {
  "error": {
    "code": "BadRequest",
    "message": "On resource 'sfctstpri', extension name 'VMDiagnosticsVmExt_vmNT1Name' cannot be used for more than one extension."
  }
} undefined
Task failed while creating or updating the template deployment.

**Comment by VipulM-MSFT** [comment]
@ChackDan @vaishnavk - can you comment?

**Comment by srrengar** [comment]
Can you check how many VMSS extensions in your template have the name "VMDiagnosticsVmExt_vmNT1Name" it appears each must have a unique name

**Comment by dirkslab** [comment]
> Can you check how many VMSS extensions in your template have the name "VMDiagnosticsVmExt_vmNT1Name" it appears each must have a unique name

Thanks @vaishnavk. I have checked and it appears only once in the Template. We have been deploying without an issue for almost a year. I can send you the template if required.

**Comment by aljo-microsoft** [comment]
@dirkslab 

hello,
please reach out to me at aljo@microsoft.com if you are still having this issue.

**Comment by dirkslab** [comment]
> @dirkslab
> 
> hello,
> please reach out to me at [aljo@microsoft.com](mailto:aljo@microsoft.com) if you are still having this issue.

Thanks @aljo-microsoft, I will do a deploy this morning to confirm issue is still there and then reach out to you with feedback.

**Comment by dirkslab** [comment]
just an fyi update. I wanted to start updating my sf clusters to use managed identity. 
So could not keep this issue on the backlog anymore.
All deployments ran fine, without above mentioned issues. 
I presume update to sf, windows update or fixed backend issue must have been resolved by Azure. Thanks.

**Comment by ChackDan** [comment]
Thankyou Dirk.
