### ISSUE TITLE
ProjectReference to non-service-fabric projects fail

### ISSUE THREAD

**Issue by aybassiouny** [Azure/service-fabric-issues#1338]
When using the MSBuild tag `ProjectReference` in my `.sfproj`, Service Fabric MSBuild props assumes it's for another service fabric project, and I get the error:  

`Microsoft.VisualStudio.Azure.Fabric.Application.targets(94,5): error : The required file '<path_to_referenced_project>\PackageRoot\ServiceManifest.xml' does not exist.` 

Looking into source, seems that the target file does indeed force such requirement: 
```
<Target Name="GetServiceProjectReferences"
          DependsOnTargets="ResolveProjectReferences"
          BeforeTargets="Build"
          Condition=" '@(ProjectReference)' != '' ">

    <GetServiceProjectReferences ProjectReferences="@(ProjectReference)"
                                 ProjectReferencesWithConfiguration="@(ProjectReferenceWithConfiguration)"
                                 ServicePackageRootFolder="$(ServicePackageRootFolder)"
                                 ApplicationManifestPath="$(ApplicationManifestFilePath)"
                                 IncludeInPackagePaths="@(IncludeInPackagePaths)"
                                 PackageBehavior="$(PackageBehavior)"
                                 Configuration="$(Configuration)">
```

Why does service fabric prohibit non-ServiceFabric project references? I am assuming my use case if pretty common, namely that I would like to first build my native project, then use the binaries in Service Fabric.

**Comment by ravipal** [comment]
.sfproj is just a container project that holds reference to other service projects and it doesn't have any business logic. The library project should be consumed by one or more service projects. Please update the service project to consume the library project and the build will take care of the dependency and build with right order.

**Comment by dbreshears** [comment]
Closing stale issue. If this is still an issue after reading the comments from @ravipal , please let us know.
