### ISSUE TITLE
What is the correct way to run multiple microservices on one port

### ISSUE THREAD

**Issue by MikeChristensen** [Azure/service-fabric-issues#1339]
We’d like to run multiple microservices in a single Service Fabric cluster.  We don’t want to have a separate port (or IP address) for each microservice, so we’re looking for a way to have Service Fabric route the caller to the correct service based on the URL.  For example:

https://mydomain.com/api/ ---> Routes to an “api” service running in some Docker container
https://mydomain.com/service-information/ ---> Routes to a “service-information” service running in some other Docker container

All of these endpoints would listen on port 80, but the URL would figure out the correct service within the application to handle the call.  Seems fairly straight forward.

My first attempt was to use the “PathSuffix” attribute on the Resources/Endpoints/Endpoint node in the ServiceManifest.xml file.  I was under the impression that the service fabric load balancer or proxy would use this path to route my request.  However, after playing around with it quite a bit, the setting seems to make no difference.  Whatever service is listening on port 80 will answer the request, and if I had two services running on port 80 (even with different PathSuffixes), I’d sometimes get deployments errors if they both got put on the same node (only one thing can bind to port 80).

Then, digging into this even more, I discovered a feature called “reverse proxy” which seems to do what I want.  Almost.  Once enabled (and exposed by the firewall), I can reference http://mydomain.com:19081/MyWebsite/Information, which will route to an app called MyWebsite and a Service called Information.  This is apparently the preferred method for locating a service within a cluster without exposing all the various ports your services might be using.  In other words, the Information service might be listening on port 85 but the reverse proxy will proxy that call over.  With this setup, as far as I can tell, the PathSuffix attribute is completely ignored.

So, I have a few questions:

1) What’s the actual purpose of PathSuffix and in what case would I use it?  Does it actually have anything to do with the reverse proxy?
2) Is there a better way to do what I’m trying to do?  I believe if we wanted to use the reverse proxy, we’d have to have one public IP address listening on port 80 that NATs to the reverse proxy port which handles all the various microservices, and another public IP listening on port 80 that goes right to the website.
3) Ideally, I want URLs to work the way described up above.  I don’t want to fully qualify the app name, and I want to control exactly what services are exposed and what their path suffix is.  Is there a way to do this?

Thanks!!

**Comment by VipulM-MSFT** [comment]
The PathSuffix and the protocol information in the endpoint is used for the URL ACLing on the Windows platform. Today, reverse proxy does not have whitelisting mechanism, this means that all of the micro-services would be exposed on the internet if the reverse proxy port is exposed on the LB.  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy 

You can have an ingress service and then forward to reverse proxy port that is not exposed or if your internal services are hardened you can change the reverse proxy port to be 80 as well. 

We are also working on integrating Envoy based reserve proxy. https://github.com/Microsoft/service-fabric-reverse-proxy @sridmad

**Comment by MikeChristensen** [comment]
Thanks @VipulM-MSFT for the info.  Can you provide me an example of when the PathSuffix would be used?  Would it only be used if you had two of the same service types and wanted to disambiguate which one to call?  If you're talking to the reverse proxy, you use a format such as localhost:19081/MyAppName/MyServiceName - with the PathSuffix go on the end of there?

**Comment by guibirow** [comment]
@MikeChristensen this issue might give you some idea:
https://github.com/Microsoft/service-fabric-aspnetcore/issues/3

I am not aware if any changes has happened since then, but previously, multiple services could share a single port in a node.

So for example, multiple APIs listening on port :80 would be mapped each to a suffix:
http://127.0.0.1:80/customers -> redirects to the service Customer
http://127.0.0.1:80/employees -> redirects to the service Employee

So a request to these URLs would go to a different services

**Comment by masnider** [comment]
Sharing ports also requires that the underlying transport can share ports. Different http transport providers do/don't so you'd have to look into each in order to determine what works. Other than that the guidance above is correct. 

Given that we haven't heard further discussion here in some time, I'm closing down this issue. If you are still having this problem feel free to reopen, and if you have other questions or issues please open a new issue. Thanks!

**Comment by MikeChristensen** [comment]
@masnider Thanks for the comments!  We ended up using Traefik, and then routing based on the URL from there.  Works fine!  It doesn't appear SF has anything built in that does this.
