### ISSUE TITLE
Connect-ServiceFabricCluster should use Azure Auth Context if present

### ISSUE THREAD

**Issue by troshko111** [Azure/service-fabric-issues#134]
Enhancement request:

If cmdlet user is already authenticated using `Add-AzureRmAccount` (so `Get-AzureRmContext` would return a valid context), SF API should not request additional authentication to connect to a cluster

**Comment by ChackDan** [comment]
@TarasRoshko  - thankyou for the suggestion.  Today the SF PS module that needs a connect-service fabricCluster is not a part of the Azure PS nor does it understand the use of JWT token that  Add-AzureRmAccount  returns. when we enable app and service level operations as a part of the SFRM PS module, it will make use of the  Get-AzureRmContext .

**Comment by TarasRoshko** [comment]
@ChackDan thanks for the heads up, that's great to know. I'd keep this opened until the changes make it to a release (otherwise people may open a similar issue)

**Comment by ChackDan** [comment]
ACK. the new SF RM PS module that will contain this is planned for Q3CY2017.

**Comment by mkosieradzki** [comment]
Any news on this one? This is such an awesome idea.

**Comment by masnider** [comment]
This is how the Azure SF powershell commands work. It will not be ported to the "basic" SF powershell commands as those have to work outside of an Azure environment.
