### ISSUE TITLE
ServiceFabricNodeBootstrapAgent crashing with System.Management.ManagementException

### ISSUE THREAD

**Issue by demyanenko** [Azure/service-fabric-issues#1340]
Our SF app is running on a 15-node cluster in Azure. During rolling app upgrade, ServiceFabricNodeBootstrapAgent started crashing on one of the nodes about once a minute. Restarting the node resolved the issue, but manual intervention was still required.

Here's a stack trace from application events:
```
Error:System.Management.ManagementException: Invalid class 
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunAsync>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceFabric.Extension.Service.Service.<ThreadProc>d__7.MoveNext() in X:\bt\937555\repo\src\ServiceExe\Service.cs:line 78
```

Please let me know if any other info is required.

**Comment by aljo-microsoft** [comment]
@demyanenko 
If you need support for your Azure solution please review support options:
https://docs.microsoft.com/azure/service-fabric/service-fabric-support

What compute custom extensions are you running?

**Comment by mhatreabhay** [comment]
To mitigate, please restart Winmgmt service on that node. 
Issue is with Windows management service, wmi objects return out of memory while trying to read wmi object state.

**Comment by vinniep79** [comment]
Are we expected to manually intervene every time this happens, or is there another workstream being pursued to prevent or automatically resolve this issue?

**Comment by awcab** [comment]
I just ran into this issue as well.  It would be great to get some more information about how to prevent this from happening.

**Comment by aljo-microsoft** [comment]
@vinniep79 and @awcab and @demyanenko 

RS1 didn't have this issue and RS4 had a fix merged; so only RS2 and RS3 should have this issue.

Can you confirm you've upgraded your OS to the latest version and are still experiencing this issue?

**Comment by awcab** [comment]
Hi @aljo-microsoft I'm running 2016 Datacenter Core R3.  Is it possible to upgrade the OS or do I have to create a new cluster to get the patch?

**Comment by vinniep79** [comment]
@aljo-microsoft We are not currently running into this issue.  I just wanted to clarify that a fix was being pursued since this thread made it look like the "fix" was manually restarting the Winmgmt service.
