### ISSUE TITLE
Question: F# Support

### ISSUE THREAD

**Issue by knowhoper** [Azure/service-fabric-issues#1342]
Hi,

My company would like to pursue Reliable Services via F# from some heavily algorithmic services. Is there any reason this may not be possible - given its .net it should work in theory right? 

There is a documentation scaffold for it in the MSDocs which is empty

https://github.com/dotnet/docs/blob/master/docs/fsharp/using-fsharp-on-azure/using-fsharp-on-azure-service-fabric.md

Is this empty for a reason? 

Any advice would be much appreciated.

**Comment by masnider** [comment]
Should work since it's just another .NET language, but I do not think we have any dedicated examples or testing. Use at your own risk :) @raja-krishnan FYI in case he has any particular comments.
