### ISSUE TITLE
Copy-ServiceFabricApplicationPackage : Could not load type 'System.Fabric.Management.ImageStore.ImageStoreUtility' from assembly 'System.Fabric.Management'

### ISSUE THREAD

**Issue by eeropenttinen** [Azure/service-fabric-issues#1343]
When trying to deploy an application to Service Fabric Cluster running in Azure from a PowerShell script, I get following error:
**Copy-ServiceFabricApplicationPackage : Could not load type 'System.Fabric.Management.ImageStore.ImageStoreUtility'
from assembly 'System.Fabric.Management, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.**

I have Microsoft Azure Service Fabric SDK 3.2.187.9494 installed.

I tried to execute the script from PowerShell ISE as well, same result.

The script manages to communicate with the cluster, all other steps are working fine except application copying.

Kind of strange since this script worked out of the box during summer and no changes have been done to the script.

**Comment by oanapl** [comment]
This usually happens when there is some old binary in the GAC. Can you run gacutil and check?
```cmd
gacutil /l | findstr System.Fabric
```

**Comment by eeropenttinen** [comment]
Gacutil provides following information: System.Fabric, Version=6.0.0.0

**Comment by lumiao** [comment]
So the assembly version of System.Fabric is 6.0.0.0; could you please check the file version of that DLL in the GAC location? The file version should be same as the SF runtime version, which is 6.3.xx.xx.

**Comment by eeropenttinen** [comment]
In folder C:\Windows\Microsoft.NET\assembly\GAC_64, I found the System.Fabric folder. I has one folder named:
**v4.0_6.0.0.0__31bf3856ad364e35**
In that folder, there is a file, **System.Fabric.dll**, which properties indicated that the file version is 6.3.187.9494 (the product version is the same).

**Comment by eeropenttinen** [comment]
Update: I managed this to get working by:
- Uninstalling the Service Fabric SDK
- Uninstalling Azure Development tools in VS 2017
and installing those again.
