### ISSUE TITLE
Question: Can I call .NET service from Java client with Remoting

### ISSUE THREAD

**Issue by heavenwing** [Azure/service-fabric-issues#1346]
I have no idea that how to share remoting interface for proxy?

**Comment by vturecek** [comment]
No, there's no cross-language support. gRPC is a better fit for polyglot services, but note that it does not provide stateful service resolution on its own.

**Comment by masnider** [comment]
Hi @heavenwing I'm going to close down this question. If Vas's answer isn't clear or you have any other questions please let us know or open up another issue.
