### ISSUE TITLE
Service fabric crashes on any upgrade that happens

### ISSUE THREAD

**Issue by pixelicous** [Azure/service-fabric-issues#1347]
Well i couldn't find much data on this issue online.
Anytime we get an upgrade to our cluster it fails with this error message, it just goes by itself after a few days in which the cluster acts chaoticly
There is absolutely zero knowledge online for service fabric issues and the errors and exception dont help much

I see many many issues with cluster upgrades on any version, why cant it work smoothly??

Get-ServiceFabricUpgradeOrchestrationServiceState doesn't output any messages- 
Get-ServiceFabricUpgradeOrchestrationServiceState : Operation timed out.
At line:1 char:1
+ Get-ServiceFabricUpgradeOrchestrationServiceState
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabr 
   ...ionServiceState], TimeoutException
    + FullyQualifiedErrorId : GetUpgradeOrchestrationServiceStateErrorId,Microsoft.ServiceFabric.Powershell.GetUpgrade 
   OrchestrationServiceState

However i am connected to the cluster.. 
The upgrade service gets the following message:

Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'. Exception encountered: System.IO.FileNotFoundException: The file 'WindowsFabricStore\ClusterManifest.3.xml' was not found in the Image Store ---> System.Runtime.InteropServices.COMException (0x80071C00): Exception from HRESULT: 0x80071C00    at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeFabric(IFabricAsyncOperationContext context)    at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.b__0(IFabricAsyncOperationContext context)    at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.Common.FabricClientRetryHelper.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.FabricClientWrapper.d__24.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.FabricClientWrapper.d__22.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__17.MoveNext()
--

**Comment by mchiriac-msft** [comment]
Based on the error event the cluster is an ARM managed one.
For the clusters that you are seeing these problems can you provide?
- ARM resource ID
- ARM correlation ID for the deployment
- Region 
- Time period when the issue manifested

**Comment by pixelicous** [comment]
@mchiriac-msft We are managing it using ARM template, is there any other way? there is terraform but according to hashicorp you cannot update SF through API so it's not good for production use, we can only update using ARM, although we never managed to do any successful update, changing relability, durability or just adding a scale set always fails!

Regarding the data above, i wont have specific time & date i believe.. also i am not sure where to get that ARM correlation ID

**Comment by aljo-microsoft** [comment]
@pixelicous 

The following is my understanding of the problem:

You have an Azure Service Fabric Cluster with a Terraform control plane, and are unable to successfully use Terraform to change your clusters configurations; specifically you appear to be leveraging Terraform to not only provision a cluster using an ARM template, but invoke Service Fabric's PowerShell Module function: get-servicefabricupgradeorchestrationservicestate.

Ref:
https://docs.microsoft.com/powershell/module/servicefabric/get-servicefabricupgradeorchestrationservicestate?view=azureservicefabricps

My recommendation would be to use your authored Azure Resource Manager Template to provision one of your lower QA/Test environments, and validate your changes before promoting to production; which will allow you to isolate issues more efficiently. 

E.G. You should use you ARM template to provision a Test cluster using the commands within https://shell.azure.com/:

# Set the Subscription owners for the cluster
az account set --subscription "YOUR SUBSCRIPTION"

# Create a Resource Group
az group create --location westus --name "YOUR RESOURCE GROUP NAME"

# Provision Resource's
az group deployment create -g "YOUR RESOURCE GROUP NAME" --name "YOUR DEPLOYMENT NAME" --template-file AzureDeploy.json --parameters AzureDeploy.parameters.json

Subsequent resource changes should leverage the last command above (az group deployment ...), when you are testing your changes, and enable you to isolate which API is causing your issue: 

For SF ARM API (Azure Hosted Provider that proxy's operations to Azure hosted SF cluster endpoints):
https://docs.microsoft.com/rest/api/servicefabric/sfrp-index

If you invoke any commands against cluster directly, like get-servicefabricupgradeorchestrationservicestate (Every Commandlet that doesn't say 'AzureRm' in the name), then reference the SF Client API (your cluster's endpoint):
https://docs.microsoft.com/rest/api/servicefabric/sfclient-index

Although I'm closing this, if you have a ARM template that you used to provision your cluster, and the command you invoked that caused your issue please reopen; as I should be able to use your template to repro (Provision resources in an identical state), and provide appropriate API documentation references where necessary.
