### ISSUE TITLE
Publish-NewServiceFabricApplication or equivalent should be part of the SDK

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#135]
VS generated `Scripts\Deploy-FabricApplication.ps1` uses `Publish-NewServiceFabricApplication` which is dynamically imported as:

```
$RegKey = "HKLM:\SOFTWARE\Microsoft\Service Fabric SDK"
$ModuleFolderPath = (Get-ItemProperty -Path $RegKey -Name FabricSDKPSModulePath).FabricSDKPSModulePath
Import-Module "$ModuleFolderPath\ServiceFabricSDK.psm1"
```

Such API should really be part of the SDK (`ServiceFabric` PowerShell module), right now to automate application deployment using PowerShell we have to manually import said function from said location.

**Comment by MikkelHegn** [comment]
The Scripts\Deploy-FabricApplication.ps1 is tied to you SF Application project in VS and part of the tooling, not the SDK/API. You could go ahead and change it to your applications need. It is also being used by VS to deploy locally.

For any automation scenarios, I would recommend not relying on this script, but rather use the SDK provided functions or the CMDlets / APIs in the runtime.

We don't consider the SDK provided functions to be APIs.

**Comment by TarasRoshko** [comment]
`Publish-NewServiceFabricApplication` is much much nicer, you connect to the cluster, run this cmdlet giving it a path and settings - and you're done. This is what PS experience also looks like for deploying websites and other things. Just one cmdlet. With SDK, you need

```
Copy-ServiceFabricApplicationPackage
Register-ServiceFabricApplicationType
New-ServiceFabricApplication
```

which require quite some arguments getting which is many lines of boilerplate.

I'd say providing analog to `Publish-NewServiceFabricApplication` in the SDK would be really nice

your call anyway, but SDK does not seem very friendly when it comes to publishing, imo the amount of boilerplate could be less

**Comment by gperrego** [comment]
I agree that it is clean using Publish-NewServiceFabricApplicaiton.  We are having issues identifying how to pass a publish profile via the API?  I'm not seeing any other powershell that allows you to pass the publish profile, just the Hashtable to override the values?

https://docs.microsoft.com/en-us/powershell/servicefabric/vlatest/new-servicefabricapplication

 [-ApplicationParameter <Hashtable>]

Am I missing something?

**Comment by MikkelHegn** [comment]
@gperrego The API does not support Publish Profiles, but the scripts and functions you've discovered in the SDK does. You can use these scripts to see how it can be done.

**Comment by alltej** [comment]
@MikkelHegn do you use the SDK cmdlets (Copy-*, Register-*,New-*) for upgrading existing SF apps?

**Comment by MikkelHegn** [comment]
@alltej 2 of 3 :-)
1. Copy- (puts the app package in to the image store in the cluster)
2. Register- (Registers the package in the cluster) Application Packages are Types (combination of Type and Version). Once they are registered they are available to be instantiated.

Now it's either New- or Start-ServiceFabricApplicationUpgrade

New- (Creates a new Application Instance of the specified type+version. Becomes a unique app instance in the cluster with the uri fabric:/MyAppInstance).
Start-ServiceFabricApplicationUpgrade- (Upgrades an application instance to the specified type+version). If you have multiple instances of the same application type in the cluster, you upgrade them individually.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-tutorial-powershell

**Comment by artisticcheese** [comment]
Do any of you guys have a good walkthrough of automation of deployment of application outside of Visual Studio for windows containers. Since container applications do not contain any code and only configuration files.
