### ISSUE TITLE
VMDiagnosticsVmExt timeouts when running Add-AzureRmServiceFabricClusterCertificate

### ISSUE THREAD

**Issue by danrozenberg** [Azure/service-fabric-issues#1351]
I ran the ``Add-AzureRmServiceFabricClusterCertificate`` command, using -SecretIdentifier parameter pointing to a certificate in an Azure Key Vault.

After more than an hour, I received this output in PowerShell:

```
Add-AzureRmServiceFabricClusterCertificate : Code: VMExtensionProvisioningTimeout, Message: Provisioning of VM extension 'VMDiagnosticsVmExt_vmNodeType2Name' has timed out. 
Extension installation may be taking too long, or extension status could not be obtained.
```
Looking at the cluster ARM template, it seems like a pretty standard diagnostic tool of the ``IaaSDiagnostics`` type and ``Microsoft.Azure.Diagnostics`` provider. 

I am a bit unsure on how to proceed, or what my best option would be, at this point...

**Comment by aljo-microsoft** [comment]
@danrozenberg  and @nkorai 

Use ARM template properties to configure Azure resources.

E.G. Use https://docs.microsoft.com/en-us/rest/api/servicefabric/sfrp-model-servercertificatecommonnames.

Similar issue with additional context: https://github.com/MicrosoftDocs/azure-docs/issues/14348

If you have any further questions, please reopen.
