### ISSUE TITLE
VS 2017 - Publish not copying Package completely, Config and other folder missing out on VM

### ISSUE THREAD

**Issue by manums** [Azure/service-fabric-issues#1354]
This looks very strange. I could deploy our service fabric app from VS2017 to our cluster earlier. I made only few changes in Config folder like adding new certs etc. I see that packages is built without any issues and it contains Config folder and new certs as expected. Problem is when it is published to cluster, deployment runs into errors for certificate which was part of config folder. In the local folder where package was built I can see Config folder with all necessary certificates.

Error from VM after deployment -

> Failed to get private key file. x509FindValue: <<>>, x509StoreName: My, findType: FindByThumbprint, Error FABRIC_E_CERTIFICATE_NOT_FOUND

![image](https://user-images.githubusercontent.com/3592179/48459981-6b317180-e781-11e8-8232-879558765425.png)

I even ran : `Test-ServiceFabricApplicationPackage -ApplicationPackagePath .\Release\`
It outputted true - True

When I logged into VM and check D:\svcfab I see weird issue only for this package. I do not see Pkg.Config.Version and Pkg.Code.Version folders.

![image](https://user-images.githubusercontent.com/3592179/48459809-ada67e80-e780-11e8-832e-ffdca6865b73.png)

I tried cleaning all folders, rebuilding and trying to deploy. VS output folder does not show any errors and folder from which it is picking up package also has Config folder with certificates. I'm puzzled why are these not getting copied to VM.

I can share VS output while publishing but that does not have any errors. I'm blocked with this issue, all I did was adding new certificates and referring to them in ApplicationParameters file for new environments.

We use docker containers and Application Manifest is updated with correct image to be deployed.

Kindly help me here!

**Comment by iyyappam** [comment]
Can you check if your certificate is uploaded to correct location in the image store. You can use "Get-ServiceFabricImageStoreContent -RemoteRelativePath <PathInImageStore>. If it is present in the image store, send us your serviceManifest.xml along with folder structure. @tugup , could you also provide the location of the downloaded files by hositng on the node to check if the certificate is present there?

**Comment by iyyappam** [comment]
Can you also check if the package you built locally has the certificate? There should be a "pkg" folder under your solution where the local package will be created. Ex: If your solution root is App1, then your pkg folder would be under %SOLUTIONROOT\%App1\Pkg. 

If it is present locally, then we can check if the file is in image store using the cmdlet above.
If it is in image store, then we can check if it downloaded to the nodes correctly.

**Comment by manums** [comment]
It looks like our AppManifest was incorrectly configured with both Certificates section to look for a secrets certificates and ServiceManifestImport with CertificateRef to look in Config packages for certificate. First one was failing because our certificate was part of config package. 

Since both of them had same certificate thumbprint, it became confusing.

You can close this issue as not an issue.

**Comment by iyyappam** [comment]
Sounds good. I'll close the issue.
