### ISSUE TITLE
Image Store keeping (very) old versions, becomes a space problem

### ISSUE THREAD

**Issue by julioas09** [Azure/service-fabric-issues#1358]
Hi, I have a Service Fabric standalone (5 nodes) cluster, and lately I've had to deal with space problems on the nodes. While investigating the source of such large storage being used, I saw that the ImageStore is keeping packages of very old versions.
If I navigate on one of the nodes to the ImageStore directory, I see the SF upgrade packages and application packages, and also a "Store" folder which occupies the most space:

![er](https://user-images.githubusercontent.com/3543529/48550939-55809100-e8d4-11e8-8369-6eaf45832e32.PNG)

If I go into this folder, I find again a list of folders of the applications, and inside of each there is a list of compressed packages, of versions that have been deployed. In some cases, there are packages dating back to the first deployments to the cluster. For example:

![er2](https://user-images.githubusercontent.com/3543529/48551028-94aee200-e8d4-11e8-90eb-b756b6736c48.PNG)

Shouldn't SF keep only the last packages in the ImageStore? Why could this be happening? And mos importantly, how cloud I avoid this? It is becoming a big space problem.

Thank you!

**Comment by oanapl** [comment]
Service Fabric doesn't automatically unregister the previous version. [You need to unregister](https://docs.microsoft.com/azure/service-fabric/service-fabric-deploy-remove-applications#unregister-an-application-type) when you decide you don't need them anymore. CI/CD tools like VSTS auto unregister the previous version when an app is upgraded. What method do you use for deployments?

As an aside, we are working on a feature that will auto-unregister old provisioned app packages, leaving only a configured number of versions. The feature will most probably come in our 6.5.x.x release.

**Comment by julioas09** [comment]
We use VSTS indeed, however we used a custom powershell script instead of the VSTS Service Fabric Deployment template until recently. 
However, I found out the following option:

https://docs.microsoft.com/en-us/powershell/module/servicefabric/register-servicefabricapplicationtype?view=azureservicefabricps
 

> ApplicationPackageCleanupPolicy:
> Determines the cleanup policy of the application package used for registering the application type. If not cleaned up, the application packages consume disk space and can lead to failures. This parameter specifies how to manage the application package after successfully registering the application type (successful provision).
>  
> When set to `Automatic`, Service Fabric runtime determines when to perform application package cleanup. Current runtime implementation deletes the application package after successfully registering the application type. If registration fails, then the application package is not deleted from the image store.
>  
> When set to `Manual`, the application package is not deleted from the image store and the users have to explicitly call “Remove-ServiceFabricApplicationPackage” cmdlet to remove it from the image store.

I'll go ahead and set that, and also manually (unregister-ServiceFabricApplicationType ) unregister the existing old packages.

**Comment by oanapl** [comment]
@julioas09 , thank you for the details.
ApplicationPackageCleanupPolicy removes the temporary package (used to provision). VSTS scripts always remove the temporary package, so this may not help (though it definitely can't hurt).

You still have to manually cleanup the packages accumulated so far in the cluster, since there is no mechanism to auto-cleanup after the fact. 
- for each provisioned app type that is not in use, call unprovision
- For temporary package, [list the image store content](https://docs.microsoft.com/powershell/module/servicefabric/get-servicefabricimagestorecontent?view=azureservicefabricps) and [delete the temporary packages](https://docs.microsoft.com/powershell/module/servicefabric/remove-servicefabricapplicationpackage?view=azureservicefabricps). Make sure to not delete anything that is in use (nothing under Store folder).

**Comment by abatishchev** [comment]
Any plans to implement retention policy for provisioned types? It's very needed.

**Comment by oanapl** [comment]
We are implementing the feature and will come in 6.5 (the next release after the current rolling one, 6.4)

**Comment by johnib** [comment]
> We are implementing the feature and will come in 6.5 (the next release after the current rolling one, 6.4)

What is the ETA for that ?

**Comment by Sarthaktrivedi** [comment]
Hello
We have solution available to resolve this issue ?

**Comment by johnib** [comment]
Yes, I can confirm I’ve been consuming this feature for the part few months and there was automatic retention keeping the last N versions of each app type. 

N is configurable and defaults to 3.

You need your cluster to be v7 at least.

**Comment by Sarthaktrivedi** [comment]
Can you please share ref, 
I preferred to add/update SF cluster ARM template ?
