### ISSUE TITLE
ErrorAction preference (SilentlyContinue) does not working for Get-ServiceFabricService

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#136]
**Cmdlet(s)**

Get-ServiceFabricService

**PowerShell Version**

4.0

**Module Version**

**OS Version**

6.3.9600.17400

**Description**

ErrorAction preference of -SilentlyContune does not work for command Get-ServiceFabricService on failure cases.

Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue

**Debug Output**

Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden/Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue -debug
VERBOSE: System.Fabric.FabricElementNotFoundException: Application not found ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BDD
VERBOSE: at System.Fabric.Interop.NativeClient.IFabricQueryClient7.EndGetServiceList2(IFabricAsyncOperationContext context)
VERBOSE: at System.Fabric.FabricClient.QueryClient.GetServiceListAsyncEndWrapper(IFabricAsyncOperationContext context)
VERBOSE: at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
VERBOSE: --- End of inner exception stack trace ---
Get-ServiceFabricService : Application not found
At line:1 char:1
Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fa ...
  + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabricService], FabricElementNotFoundException
  + FullyQualifiedErrorId : GetServiceErrorId,Microsoft.ServiceFabric.Powershell.GetService

**Script/Steps for Reproduction**

Connect to Service Fabric Cluster
Run the below command when Application is not deployed yet.
Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue
Thanks,
Pradebban Raja

**Comment by TarasRoshko** [comment]
In my experience, It does not work on many cmdlets, we should consolidate all of them into single issue so it's fixed for good

**Comment by rajaprad** [comment]
Is there an update on this ?

**Comment by heeldin** [comment]
This issue is expected since –ErrorAction SilentlyContinue doesnot work on terminating errors and we are throwing terminating errors in all of our powershell commands.
A workaround: 
use a try catch or change the ErrorActionPreference to silentlycontinue which is a global change.

**Comment by rajaprad** [comment]
@heeldin - I think supporting error action preferences is a basic need and closing the issue without having this in a back log/milestone of some kind does not help. Issues are added to make way for new enhancement and customer needs and scenarios. I would reopen this with a new bug if not reopened in this same instance. Thanks!
@ChackDan - Please asses and do the needful

**Comment by ChackDan** [comment]
Adding a defect to add this issue to the backlog

**Comment by ChackDan** [comment]
Bug 10490354<http://vstfrd:8080/Azure/RD/_workitems#_a=edit&id=10490354> created to track this issue.

Further messages on the original thread will be added to the bug description as long as the Mail2Bug alias (sfm2b) is kept in the recipients list.
Note: Bugs are created with default area and iteration paths. You can update the bug with the different area and iteration.

________________________________
From: Chacko Daniel
Sent: Friday, October 13, 2017 6:06:12 AM
To: Azure/service-fabric-issues; Azure/service-fabric-issues
Cc: Mention; SF Mail2Bug
Subject: RE: [Azure/service-fabric-issues] ErrorAction preference (SilentlyContinue) does not working for Get-ServiceFabricService (#136)

Adding a defect to add this issue to the backlog

**Comment by ChackDan** [comment]
Internal use only - workitems id=8915692

**Comment by Christina-Kang** [comment]
Silently continue is meant to catch non terminating errors and we return these errors as terminating ones. My recommendation is to use a try catch block to allow the API to continue.

**Comment by masnider** [comment]
Thanks @Christina-Kang. also @amanbha can we confirm this works correctly with the http based PS module? If so then we should be good going forward as well.
