### ISSUE TITLE
Define User + User secrets is not working without certificate configuration part

### ISSUE THREAD

**Issue by klettier** [Azure/service-fabric-issues#1362]
Hello,

I have followed instructions [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management) to manage secrets in my application (1) an all is working fine.

Example of configuration

```xml
<ConfigOverrides>
  <ConfigOverride Name="Config">
	<Settings>
	  <Section Name="MySettings">
		<Parameter Name="MySecret" Value="MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggFRMIIBTQIBADA1MCExHzAdBgNVBAMMFm15ZGF0YWVuY2lwaGVybWVudGNlcnQCEGIfp1W6LmeCSzlMT7tZWpcwDQYJKoZIhvcNAQEHMAAEggEAWnbHkiA/QJ4esE/KEc/wTWVJmCQ/FkDyNbSPkpdv+Evac8vm05mHpzPsgnsgI1fBqYdX0S1YT4R0vV2L5as19uIBCNoRGrd8mDzLZ5p4uu3lnI3cIGz1LXSbDvq9MylltvC3y4IG1w4XHgSAUWwB1z0yS3W65mt5kjmBxwxiMw80FTguCa9FTmbqW/VMJFg18k5r+RwBpo0v5fE3Dx7ffPaZIcGmodCbaiHZLvzR8qFWgsV2np7GH5628VIwgRabGOQcHmsKkiOzoJ+WskQ1oqTVSwzE4qCYz9q+Fd6/xfWX4BZlyv2ypwxN5D8nmH2vZgBDg9cXgcVlXx85MJU8QDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDzg6AnPPjvHLx9RK4wmRXrgCCyRMYMIqmtSqQbVmMS6wzCLitCda3JP92qIMMCjhb2PA==" IsEncrypted="true" />
	  </Section>
	</Settings>
  </ConfigOverride>
</ConfigOverrides>
```

I setuped a user as described [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security) in another application (2) and everything working fine.

Example of configuration

```xml
<Principals>
<Users>
  <User Name="Service1" AccountType="DomainUser" AccountName="foo\bar" Password="MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggFRMIIBTQIBADA1MCExHzAdBgNVBAMMFm15ZGF0YWVuY2lwaGVybWVudGNlcnQCEGIfp1W6LmeCSzlMT7tZWpcwDQYJKoZIhvcNAQEHMAAEggEAWnbHkiA/QJ4esE/KEc/wTWVJmCQ/FkDyNbSPkpdv+Evac8vm05mHpzPsgnsgI1fBqYdX0S1YT4R0vV2L5as19uIBCNoRGrd8mDzLZ5p4uu3lnI3cIGz1LXSbDvq9MylltvC3y4IG1w4XHgSAUWwB1z0yS3W65mt5kjmBxwxiMw80FTguCa9FTmbqW/VMJFg18k5r+RwBpo0v5fE3Dx7ffPaZIcGmodCbaiHZLvzR8qFWgsV2np7GH5628VIwgRabGOQcHmsKkiOzoJ+WskQ1oqTVSwzE4qCYz9q+Fd6/xfWX4BZlyv2ypwxN5D8nmH2vZgBDg9cXgcVlXx85MJU8QDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDzg6AnPPjvHLx9RK4wmRXrgCCyRMYMIqmtSqQbVmMS6wzCLitCda3JP92qIMMCjhb2PA==" PasswordEncrypted="true" />
</Users>
</Principals>
```

I tried to setup a user like above in my application 1 with encrypted passwords and got the error below

```
FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR: The IsEncrypted value of the override parameter with name 'MySecret' in section 'MySettings' for service manifest 'Stateless1Pkg' does not match the IsEncrypted value of the corresponding parameter.
```

To resolve my issue I added the configuration below 

```xml
<Policies>
<SecurityAccessPolicies>
  <SecurityAccessPolicy GrantRights=”Read” PrincipalRef="Service1" ResourceRef="MyCert" ResourceType="Certificate"/>
</SecurityAccessPolicies>
</Policies>
<Certificates>
<SecretsCertificate Name="MyCert" X509FindType="FindByThumbprint" X509FindValue="[YourCertThumbrint]"/>
</Certificates>
```

I find really strange to have to add that part of configuration only when you activate both **User** and **Secrets** but not when they are activated separately ?

**Comment by masnider** [comment]
The additional portion I believe acls the cert in the store specifically to this service so that it can automatically decrypt the encrypted value. But I'm not quite sure if we need to improve the error message.

**Comment by klettier** [comment]
hi @masnider

Thank you for your reply, my point is more on the utility of the configuration portion added than on the misleading error message. 
I think there is a check issue on the deployment because for me I shouldn't provide that portion at all, if not how does it manage the case when I specify only the user or the encrypted passwords without the certificate portion and things are working?
