### ISSUE TITLE
Failed deployment in refresh application mode results in inconsistent local cluster state

### ISSUE THREAD

**Issue by skwasiborski** [Azure/service-fabric-issues#1365]
Setup:
Set Application Debug Mode to Refresh Application.
Start debugging the application in local dev cluster from VisualStudio (via F5).
Stop debugging.
Start debugging the application again but in a way that results in deployment error (a way to do that described later).

Result:
No application instance is created (which is expected since the deployment failed) 
Some of the code packages are actually run. In SFExplorer no application instance is listed but when inspecting node one can see deployed packages. When inspecting Task Manager one can also confirm that the packages are running (screen shot attached). When the executable is killed from Task Manager it is restarted by SF runtime.
It is not possible to build the application again nor deploy it, unless the cluster is stopped or reset.

Simple way to reproduce failed deployment is to define stateful service with UniformInt64Partition with LowKey=0 and HighKey=1 and then try to deploy the service with partitions count equal to 10. I also experienced the error in case of other random deployment errors.

![image](https://user-images.githubusercontent.com/1712802/48779411-da561b00-ecd7-11e8-8338-88e6c398c6b2.png)

**Comment by MikkelHegn** [comment]
@dbreshears for Visual Studio to investigate further.

Thanks for the report, as part of Refresh Mode, Visual Studio does not remove the application as part of stopping the debugger. However, any change to the application which requires a redeployment would trigger the removal and redeployment of the application.

One thing to try is to use the "Clean solution" from Visual Studio. This would remove the application in Service Fabric.

**Comment by skwasiborski** [comment]
@MikkelHegn using the "Clean solution" or removing the application manually solves the issue (but also partially defeats the porpoise to use refresh application).

I confirmed that the orphaned code package deployment is the one from first deployment (the one that succeeds) rather than the second one (the failed one).

In general the issue is not very problematic since it is only present when the deployment fails late (in my case it fails when creating the new application). If the deployment fails early e.g. due to error in manifest, then the old application is not deleted and the problem cannot be observed.

**Comment by ravipal** [comment]
@skwasiborski, I tried to reproduce the issue following your example but I am not able to reproduce. In refresh mode, if we detect any change in applicationmanifest.xml, then we will try to redeploy the application using the PS script "Publish-NewServiceFabricApplication", which will first remove the application if present.

VS output
![image](https://user-images.githubusercontent.com/1775825/51716400-7ad6fd00-1ff1-11e9-93b0-f7ee92db044c.png)

Service Fabric Explorer
![image](https://user-images.githubusercontent.com/1775825/51716433-96da9e80-1ff1-11e9-8f3c-9d54f614bbaa.png)

If you can reproduce the issue, please share the VS output window. May be there is a problem uninstalling the application, in which case this is not related to debugging.

**Comment by ravipal** [comment]
@skwasiborski please reopen this issue with the output window log, if you can still reproduce this issue.
