### ISSUE TITLE
Scaling Policies are not used

### ISSUE THREAD

**Issue by primez** [Azure/service-fabric-issues#1366]
Hello. Thank you in advance for help.
There is an issue with scaling policies applied to services hosted on Azure Service Fabric cluster.
I've tried to set them through `ApplicationManifest.xml` and through Powershell. I can see them  in Service Fabric Explorer and ResourceMonitorService is enabled on the cluster.

Basically on a 3-node cluster I should have 2 instances of a service according to the policy, but it seems that it is not triggered when ResourceMonitorService reports the data.

I've tried the same policies on another cluster and it works.
The only thing I can blame is the fact I've changed the size of VMs of the underlying VMSS today and after that added scaling policies.

Here are the screenshots with my settings.
![service fabric explorer - google chrome 2018-11-21 21 14 31](https://user-images.githubusercontent.com/6368162/48866038-15407780-edda-11e8-9c2d-70cb3c02f10e.png)
![service fabric explorer - google chrome 2018-11-21 21 18 06](https://user-images.githubusercontent.com/6368162/48866043-196c9500-edda-11e8-9e1c-f65a2a778009.png)

**Comment by masnider** [comment]
Hm. Not sure. As an experiment, what happens if on the polic you defined a max of 3 instead of -1?

**Comment by primez** [comment]
Just tried to set max instances to 3. No changes. I've also tried to set `servicefabric:/_CpuCores` with ridiculously high value like 400 for `Lower Load Threshold` to ensure that current load is less than the threshold, but nothing changes.

**Comment by puzovicnikola** [comment]
Hi @primez 

Looks like you are using -1 as Instance Count for you service. Due to this, your service will be placed on every node in the cluster and auto scaling will not work.

Can you change instance count to 3. When you do this, auto scaling will kick in and Service Fabric will manage instance count for this partition.

--
Nikola

**Comment by primez** [comment]
Now it works. Thank you @puzovicnikola. But it rises another question - how should autoscaling work in case more nodes are added to the cluster if the max count is hard coded now.

**Comment by puzovicnikola** [comment]
You can leave "Max Instance Count" set to -1 in the scaling policy description, and auto scaling will work. It is important that you do not set "Instance Count" in service description to -1 so that application can scale. Please mind that these two are two different fields.

**Comment by primez** [comment]
Ok. Now it is totally clear. Thank you so much for such quick and informative response. Problem solved!

**Comment by puzovicnikola** [comment]
Glad that we were able to help. I'm going to close the issue now.
