### ISSUE TITLE
Can we setup open networking for containers with an on-prem standalone cluster?

### ISSUE THREAD

**Issue by marcjonesuk** [Azure/service-fabric-issues#1368]
Hi - we are trying to configure open networking for our standalone cluster, version 6.3.187.9494

I am following the instructions here (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-networking-modes) but I have no idea where the networkprofile or variables configuration should go in the cluster configuration?

**Comment by marcjonesuk** [comment]
Hi - we are trying to configure open networking for our standalone cluster, version 6.3.187.9494

I am following the instructions here (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-networking-modes) but I have no idea where the networkprofile or variables configuration should go in the cluster configuration?

**Comment by mkosieradzki** [comment]
I am afraid it currently works only in Azure (see: https://github.com/Microsoft/service-fabric/blob/c326b801c6c709f36684700edfe7bb88ceec9d7f/src/prod/src/managed/Api/src/System/Fabric/Management/fabricdeployer/FlatNetwork/ContainerNetworkSetupOperation.cs) the code checks for Azure and depends on azure cni - there are tons of Azure-specific code in this area today.

**Comment by dkkapur** [comment]
This is currently not supported, and @mkosieradzki nice catch!

@marcjonesuk you could theoretically try to replicate the stuff we do in azure manually and have it run on-prem. This will include allocating secondary IPs for nodes and setting up a metadata server, etc. If this is something you'd like to do, let me know and we can get you in touch with some folks here (including @dario-ms) that will be able to help. To be clear though, we aren't testing this actively and we don't currently have plans to support this as part of the Standalone offering. 

(Closing this issue for now, but if you'd like to reopen it for any reason or do decide to pursue it manually, let me know and we can follow up accordingly).
