### ISSUE TITLE
Can I change Service Name ?

### ISSUE THREAD

**Issue by maxcli** [Azure/service-fabric-issues#1371]
hello,
I am adding HTTS endpoint to Service Fabric API using this wiki: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.

The ApplicationManifest.xml was:
<Service Name="MYAPP.Web.API"

I changed it to :
<Service Name="MYAPPWebAPI

  so that i could add a class called MYAPPWebAPI so that I could override the  CreateServiceInstanceListeners()   (C# class name cannot contain Periods)

But now when I deploy locally, i see this error 
FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR: he BuildLayout of the application in C:\SfDevCluster\Data\ImageBuilderProxy\AppType\xxxx is invalid. Code is missing for service MYAPP.Web.APIPkg.

Should I start all over with a new service name ? Or can i change a config file  ?

Thanks alot, Peter

**Comment by masnider** [comment]
Service names cannot be changed/upgraded for services that already exist. But the error you are getting there is about the structure of the application package, not related to the name of the service. If you can provide more info from the manifests (the service package imports into the application manifest and then the default service section) and what you changed, then we might be able to provide more information. As it is it looks like you changed the name of the service package import in the application manifest but not the corresponding reference in the actual service package.

**Comment by masnider** [comment]
We have a bug to improve this error output in the future which would help here (so making sure that's linked here), but if you can answer my questions above we can figure out what is wrong in this case.

**Comment by oanapl** [comment]
We have improved many error messages in the app package validation path.
