### ISSUE TITLE
FabricApplicationGateway crashes during security scan

### ISSUE THREAD

**Issue by Markvdbe** [Azure/service-fabric-issues#1373]
We are running a small Service Fabric cluster on premise for testing purposes and have noticed that FabricApplicationGateway.exe crashes a few times a day. These crashes are centered around the time an internal Nessus scan runs.

**Dump Summary**
------------
Dump File:	FabricApplicationGateway.exe.8032.dmp : C:\Temp\FabricApplicationGateway.exe.8032.dmp
Last Write Time:	29-11-2018 23:44:31
Process Name:	FabricApplicationGateway.exe : C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Present

System Information
------------------
OS Version:	10.0.14393
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
FabricApplicationGateway.exe	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricApplicationGateway.exe	6.3.162.9494
ntdll.dll	C:\Windows\System32\ntdll.dll	10.0.14393.1715
kernel32.dll	C:\Windows\System32\kernel32.dll	10.0.14393.2155
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	10.0.14393.2155
advapi32.dll	C:\Windows\System32\advapi32.dll	10.0.14393.2007
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.14393.0
sechost.dll	C:\Windows\System32\sechost.dll	10.0.14393.1613
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	10.0.14393.2155
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.14393.2097
msvcp140.dll	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcp140.dll	14.12.25810.0
ws2_32.dll	C:\Windows\System32\ws2_32.dll	10.0.14393.206
VCRUNTIME140.dll	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\VCRUNTIME140.dll	14.12.25810.0
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	10.0.14393.953
httpapi.dll	C:\Windows\System32\httpapi.dll	10.0.14393.1532
user32.dll	C:\Windows\System32\user32.dll	10.0.14393.1770
win32u.dll	C:\Windows\System32\win32u.dll	10.0.14393.51
gdi32.dll	C:\Windows\System32\gdi32.dll	10.0.14393.206
gdi32full.dll	C:\Windows\System32\gdi32full.dll	10.0.14393.1770
websocket.dll	C:\Windows\System32\websocket.dll	10.0.14393.0
shlwapi.dll	C:\Windows\System32\shlwapi.dll	10.0.14393.0
userenv.dll	C:\Windows\System32\userenv.dll	10.0.14393.0
combase.dll	C:\Windows\System32\combase.dll	10.0.14393.2155
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	10.0.14393.2155
netapi32.dll	C:\Windows\System32\netapi32.dll	10.0.14393.0
dbghelp.dll	C:\Windows\System32\dbghelp.dll	10.0.14321.1024
secur32.dll	C:\Windows\System32\secur32.dll	10.0.14393.0
profapi.dll	C:\Windows\System32\profapi.dll	10.0.14393.0
crypt32.dll	C:\Windows\System32\crypt32.dll	10.0.14393.1198
winhttp.dll	C:\Windows\System32\winhttp.dll	10.0.14393.2155
FabricResources.dll	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricResources.dll	6.3.162.9494
FabricCommon.dll	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricCommon.dll	6.3.162.9494
FabricAad.Client.dll	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricAad.Client.dll	6.3.162.9494
bcrypt.dll	C:\Windows\System32\bcrypt.dll	10.0.14393.576
msasn1.dll	C:\Windows\System32\msasn1.dll	10.0.14393.0
mscoree.dll	C:\Windows\System32\mscoree.dll	10.0.14393.0
cabinet.dll	C:\Windows\System32\cabinet.dll	5.0.1.1
xmllite.dll	C:\Windows\System32\xmllite.dll	10.0.14393.0
version.dll	C:\Windows\System32\version.dll	10.0.14393.0
wintrust.dll	C:\Windows\System32\wintrust.dll	10.0.14393.2125
dsrole.dll	C:\Windows\System32\dsrole.dll	10.0.14393.0
sspicli.dll	C:\Windows\System32\sspicli.dll	10.0.14393.1770
mscoreei.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll	4.7.2623.0
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	10.0.14393.0
mswsock.dll	C:\Windows\System32\mswsock.dll	10.0.14393.0
nsi.dll	C:\Windows\System32\nsi.dll	10.0.14393.0
kerberos.dll	C:\Windows\System32\kerberos.dll	10.0.14393.2097
cryptdll.dll	C:\Windows\System32\cryptdll.dll	10.0.14393.0

**Stack trace**
Following the advice from https://github.com/Azure/service-fabric-issues/issues/634 I've produced the following stacktrace. Hopefully that helps.

FabricApplicationGateway.exe!HttpApplicationGateway::ParsedGatewayUri::TryGetServiceName(class Common::NamingUri &)
FabricApplicationGateway.exe!HttpApplicationGateway::ServiceResolverImpl::PrefixResolveAsyncOperation::OnStart(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AsyncOperation::Start(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AllocableAsyncOperation::CreateAndStart<class HttpApplicationGateway::ServiceResolverImpl::PrefixResolveAsyncOperation,class HttpApplicationGateway::ServiceResolverImpl &,class std::shared_ptr<class HttpApplicationGateway::ParsedGatewayUri> const &,class Common::RootedObjectPointer<class Api::IResolvedServicePartitionResult> &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class Common::TimeSpan &,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &>(class KAllocator &,class HttpApplicationGateway::ServiceResolverImpl &,class std::shared_ptr<class HttpApplicationGateway::ParsedGatewayUri> const &,class Common::RootedObjectPointer<class Api::IResolvedServicePartitionResult> &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class Common::TimeSpan &,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::ServiceResolverImpl::BeginPrefixResolveServicePartition(class std::shared_ptr<class HttpApplicationGateway::ParsedGatewayUri> const &,class Common::RootedObjectPointer<class Api::IResolvedServicePartitionResult> &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class KAllocator &,class Common::TimeSpan &,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::ProcessRequestAsyncOperation::DoResolve(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::ProcessRequestAsyncOperation::OnStart(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AsyncOperation::Start(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AllocableAsyncOperation::CreateAndStart<class HttpApplicationGateway::GatewayRequestHandler::ProcessRequestAsyncOperation,class HttpApplicationGateway::GatewayRequestHandler &,class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> > &,class std::unique_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> >,struct std::default_delete<class std::vector<unsigned char,class std::allocator<unsigned char> > > >,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &>(class KAllocator &,class HttpApplicationGateway::GatewayRequestHandler &,class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext>
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::BeginProcessReverseProxyRequest(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> > &,class std::unique_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> >,struct std::default_delete<class std::vector<unsigned char,class std::allocator<unsigned char> > > > &&,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::HandlerAsyncOperation::InvokeHandler(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::HandlerAsyncOperation::OnStart(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AsyncOperation::Start(class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!Common::AllocableAsyncOperation::CreateAndStart<class HttpApplicationGateway::GatewayRequestHandler::HandlerAsyncOperation,class HttpApplicationGateway::GatewayRequestHandler &,class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> >,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &>(class KAllocator &,class HttpApplicationGateway::GatewayRequestHandler &,class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> > &&,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpApplicationGateway::GatewayRequestHandler::BeginProcessRequest(class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> >,class std::function<void > const &,class std::shared_ptr<class Common::AsyncOperation> const &)
FabricApplicationGateway.exe!HttpServer::HttpServerImpl::DispatchRequest(class std::unique_ptr<class HttpServer::IRequestMessageContext,struct std::default_delete<class HttpServer::IRequestMessageContext> >)
FabricApplicationGateway.exe!HttpServer::HttpServerImpl::OnRequestReceived(class KSharedPtr<class KHttpServerRequest>)
FabricApplicationGateway.exe!HttpServer::HttpServerImpl::OnHeaderReadComplete(class KSharedPtr<class KHttpServerRequest>,enum KHttpServer::HeaderHandlerAction &)
FabricApplicationGateway.exe!KDelegate<void >::operator()(class KSharedPtr<class KHttpServerRequest>,enum KHttpServer::HeaderHandlerAction &)
FabricApplicationGateway.exe!KHttpServer::InvokeHeaderHandler(class KSharedPtr<class KHttpServerRequest>,enum KHttpServer::HeaderHandlerAction &)
FabricApplicationGateway.exe!KHttpServerRequest::IOCP_Completion_Impl(unsigned long,unsigned long)
FabricApplicationGateway.exe!KHttp_IOCP_Handler::_Raw_IOCP_Completion(void *,struct _OVERLAPPED *,unsigned long,unsigned long)
FabricApplicationGateway.exe!KThreadPoolStandard::Worker(void *)
FabricApplicationGateway.exe!KThread::HostStartRoutine(void *)
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()

**Comment by masnider** [comment]
Thanks for the report. Do you happen to know what particular scan or test Nessus was running at the time, or can you narrow it down to a certain type of scan?

**Comment by masnider** [comment]
@Markvdbe given that we have not heard back from you I'm going to close this issue down. Thanks for reporting! If you're still seeing this or anything similar feel free to either reopen this issue or create another one.
