### ISSUE TITLE
Unable to run simple client actor - getting COMException from HRESULT 0x80071BFD

### ISSUE THREAD

**Issue by schwartzma1** [Azure/service-fabric-issues#1374]
I am running a local Service Fabric Cluster version 6.3.187.9494 and running through the examples at:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-get-started

Getting exception:

◢ | $exception | {"Exception from HRESULT: 0x80071BFD"} | System.Runtime.InteropServices.COMException
   at System.Fabric.Interop.NativeRuntime.FabricGetActivationContext(Guid& riid)
   at System.Fabric.FabricRuntime.NativeFabricRuntimeFactory.GetCodePackageActivationContextHelper()
  | HResult | -2147017731 | int

The line where this happens is:
          IActor1 actor = ActorProxy.Create<IActor1>(new ActorId(threadToActor[Thread.CurrentThread.Name]), new Uri("fabric:/ActorHelloWorld/Actor1ActorService"));
                
Sometimes I was able to get a simple Console Application working - but this was not consistent.  However I tried to also create a WPF client and tried changing the <TargetFramework> in all of my .csproj files from <TargetFramework>netcoreapp2.1<</TargetFramework> to     <TargetFramework>net461</TargetFramework>

I have not been able to get this working from a WPF client or the Console application since.

The service fabric application has a status of OK on 1 node or multiple nodes when I view it in the local cluster manager.

Also sometimes I am getting InvalidOperationException at the same spot.

InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricSecretStoreClient'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{38C4C723-3815-49D8-BDF2-68BFB536B8C9}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

Stack trace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ActorClient.Program.TestMethod() in C:\Users\mschwartz\source\repos\ActorHelloWorld\ActorClient\Program.cs:line 58
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

This is where I am trying to print:
 Task<string> retval = actor.GetHelloWorldAsync();
   Console.WriteLine(System.Threading.Thread.CurrentThread.Name + " " + retval.Result);

**Comment by derailan** [comment]
I'm getting the same exception. 

During execution of ```new FabricClient() ```

```
            using (var client = new FabricClient())
            {
                      ....
            }
```
Issue does not occur with version 3.2.187 of Microsoft.ServiceFabric.AspNetCore.Kestrel, but occurs with 3.3.617

**Comment by guibirow** [comment]
What version are the libraries you are using? and the SDK?

It is probably that you are using the libraries versions 6.4.617 and 3.3.617 on top of an older SDK(3.2).

If you are using the old SDK(3.2 or less) you might have to downgrade the libraries, Or upgrade the SDK to 3.3 and cluster 6.4.

I assume it is related to the same issue from here: https://github.com/Microsoft/service-fabric/issues/262

**Comment by schwartzma1** [comment]
I am using Service Fabric SDK 6.3.187 and I have Microsoft.ServiceFabrice.Actors.3.2.187 and other 3.2.187 sdk libraries it looks like.

In my Visual Studio application I am using version 3.3.617 of the nuget packages.

So far I have tried downgrading all of my Visual Studio projects to use v 3.2.187 of Microsoft.ServiceFabric.Actors nuget package.  That seems to generally resolve the issue.... thanks!

**Comment by guibirow** [comment]
Cool, the trick here is to always use the package version targeting the same runtime version of your cluster.

Older packages also works on new runtime version, but new packages does not run on old runtime.

**Comment by masnider** [comment]
Yeah the E_NOINTERFACE is an especially strong indicator that your service is bound to an SDK version > than what the cluster currrently supports.

**Comment by masnider** [comment]
As we haven't heard back from you, I'll consider this issue resolved. If you have any other problems, please let us know by opening a new issue. If this issue is still live for you, feel free to comment and reopen or create a new issue.
