### ISSUE TITLE
Connect to service fabric from Azure Automation (Runbook)

### ISSUE THREAD

**Issue by ojasp** [Azure/service-fabric-issues#1377]
I am trying to connect to the service fabric cluster using the Connect-ServiceFabricCluster commandlet from runbook but cannot figure out how to use the certificate that is in automation assets to authenticate. The _FindType_ and _Findvalue_ parameters need a Certificate store to look in, and I can't find any documentation for what should be selected as stores in the case of runbooks.

**Comment by masnider** [comment]
Not sure since this isn't really a SF question, but I looked and found this: https://docs.microsoft.com/en-us/azure/automation/automation-certificates. You might have better look checking with Azure Automation to see if they have a recommendation or example of how to use the above.

**Comment by dennyx** [comment]
@ojasp 
Do you find solutions to help on this scenario? I'm facing this issue too.
Appreciate if any kindly suggestions, thanks

**Comment by ojasp** [comment]
> @ojasp
> Do you find solutions to help on this scenario? I'm facing this issue too.
> Appreciate if any kindly suggestions, thanks

No, I didn't find a way to do it. I instead ended up installing the authentication certificate on one of the windows machines & have a powershell job authenticating using this certificate.

**Comment by dennyx** [comment]
Tthanks for the kindly suggestion

**Comment by athinanthny** [comment]
#reassign @sridmad

**Comment by peterpogorski** [comment]
#please-close

**Comment by athinanthny** [comment]
#please-close
