### ISSUE TITLE
Error message trying to enable EventStoreService

### ISSUE THREAD

**Issue by israellot** [Azure/service-fabric-issues#1378]
`        "message": "Error converting value \"EventStoreService\" to type 'System.Fabric.Wrp.BackendService.Model.Public.AddOnFeatureFebruary2018'. Path 'properties.addonFeatures[1]', line 115, position 25."`

Trying to enable EventStoreService according to 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-eventstore

**Comment by raunakpandya** [comment]
As the doc mentions for Azure cluster you shouldn’t use addOnFeature but modify the fabricSettings to enable the event store service. That should unblock you.

**Comment by israellot** [comment]
That indeed unblocked the process. Thank you.
