### ISSUE TITLE
ServiceFabricVolumeDisk on private cluster

### ISSUE THREAD

**Issue by israellot** [Azure/service-fabric-issues#1380]
Can the new ServiceFabricVolumeDisk be deployed on a normal SF cluster besides Mesh?

**Comment by raunakpandya** [comment]
@israellot - Ideally it can be and we do plan to support it soon. However there are number of manual steps involved at the moment and the experience isn't optimized. If you really wanna try them, we can share the steps.

**Comment by deepakjangid-MSFT** [comment]
@israellot can you please reach out to me at deepakj at Microsoft dot com. We can work together to get you the setup needed.

**Comment by mevora-msft** [comment]
@israellot Do you want to try out this on Windows or Linux cluster?

**Comment by israellot** [comment]
Thanks @raunakpandya for your prompt response, and @deepakjangid-MSFT and @mevora-msft for the follow up. 
I would like to try it on a Windows cluster. I currently have a requirement for a feature that involves replicating files  and I ended up building a service backed by reliable dictionaries to replicate files that involves paging files to dictionaries and keeping a directory. ServiceFabricVolumeDisk would superseed this solution and simplify workflows requiring reliable disk access without the need to using external storage solutions like Azure Blob.

**Comment by deepakjangid-MSFT** [comment]
1. From portal follow all the steps to create a cluster(Datacenter-with-Containers image and nodes with nested virtualization support). At the end instead of creating, download the ARM template.
Note: Cluster upgrade won't work. You need to create a new cluster.
2. Update the ARM template with following settings in Microsoft.ServiceFabric/clusters resource:-
	a. In fabricSettings add below configs
	                {
                        "name":  "Common",
                        "parameters":  [
                            {
                                "value":  "true",
                                "name":  "EnableUnsupportedPreviewFeatures"
                            }
                        ]
                    },
                    {
                        "name":  "Hosting",
                        "parameters":  [
                            {
                                "value":  "true",
                                "name":  "IsSFVolumeDiskServiceEnabled"
                            }
                        ]
                    }
	b. In "properties" section, change the "upgradeMode" to "Manual"
3. Deploy the arm template using New-AzureRmResourceGroupDeployment.
4. After successful deployment, deploy SFVolumeDisk VolumeDriver Application on cluster (/opt/microsoft/servicefabric/bin/AddonServices/ServiceFabricVolumeDriver)
	a. The port VolumeDriver listens on is provided in ApplicationManifest. Update it to any desired value, avoiding any port clashes. This service runs with -1 instance i.e. on all the nodes. For 1-box run it with 1 instance.
5. Application Deployment
		a. REST API : In application json add below in "codePackages"
		(supported sizeDisk: Small(32G), Medium(64G), Large(128G))
		(destinationPath can be updated as per requirements)
		        "volumes": [
				    {
				        "name": "myvol",
		                "creationParameters": {
		                "kind": "ServiceFabricVolumeDisk",
		                "sizeDisk": "Medium"
		                },
		                "destinationPath": "C:\data\db"
		            }
		        ]

**Comment by MedAnd** [comment]
Hi @raunakpandya / @deepakjangid-MSFT, any progress on the ServiceFabric.VolumeDriver? I'm interested to configure and deploy on a local 1 or 5 node Windows development cluster? Thx.

**Comment by anantshankar17** [comment]
@MedAnd This is already enabled on the mesh dev cluster by default. You can use the mesh cluster for deployment of the native apps aswell.

**Comment by MedAnd** [comment]
I would like to enable on a local Windows 1 or 5 node development cluster and assume this is possible as Mesh runs on the same SF runtime?

**Comment by anantshankar17** [comment]
As described earlier by @deepakjangid-MSFT , there are a few manual steps to enable this in a cluster. The Mesh Local Windows dev cluster already has those taken care of. The local Windows Mesh dev cluster also has the option for 1 or 5 nodes, and can be used for deploying native apps. Right now this is not enabled on the non mesh cluster by default.

**Comment by MedAnd** [comment]
I would like to enable for a **non Mesh cluster**... in other words I would like to enable for a local Windows 1 or 5 node Service Fabric development cluster but cannot find the documentation & hence this request. 

To also further clarify, I would like to use the ServiceFabricVolumeDisk with processes, not containers. Please let me know if that makes sense?

**Comment by raunakpandya** [comment]
Technically it would work on non mesh local dev cluster as well and is really not tied with containers and would work with processes as well. I have tagged this as an enhancement for now.

**Comment by MedAnd** [comment]
Hi @raunakpandya / @masnider - any update on above? Thanks.

**Comment by deepakjangid-MSFT** [comment]
I am closing this issue right now as ServcieFabricVolumeDisk support for services is not being worked on currently. The use cases are currently only focused on containers.

**Comment by MedAnd** [comment]
@deepakjangid - why can’t this be labelled as an enhancement / feature request vs closed?
