### ISSUE TITLE
Wrong documentation related to connecting to secured cluster with certificates

### ISSUE THREAD

**Issue by sistoimenov** [Azure/service-fabric-issues#1386]
Hello,

In this documentation article:

[](https://docs.microsoft.com/en-us/powershell/module/servicefabric/connect-servicefabriccluster?view=azureservicefabricps#examples)

Under: **Example 2: Connect to a cluster using an X.509 certificate**

The example didn't work for me. I managed to get it working by providing the -ServerCertThumbprint property which is missing from the example. I lost like an hour to fix this and connect to the cluster... Please fix the example.

**Comment by TylerMSFT** [comment]
#please-close
