### ISSUE TITLE
SF program data eats lots of space (Service Bus 1.1 on prem version)

### ISSUE THREAD

**Issue by himanshuladola** [Azure/service-fabric-issues#1387]
I was trouble-shooting issue of disk space and found that SF (Service fabric) log files contains lots of ETL files. I am not sure is it safe to delete those and why it's dumping/eating these much of space. Attached win-dir snapshot for better understanding. 

I have installed on-prem instance of service bus azure (Service bus 1.1)

![image](https://user-images.githubusercontent.com/24384240/49868504-a764fa00-fe33-11e8-88df-41b8864dd4a1.png)

_Originally posted by @himanshuladola in https://github.com/Azure/service-fabric-issues/issue_comments#issuecomment-446565037_

**Comment by masnider** [comment]
We expect the Service Bus product to handle cleanup of the underlying SF environment in that case. Have you followed up there?

**Comment by himanshuladola** [comment]
Do we mean raising ticket against Microsoft service bus?

I do see clean-up is not done properly and this is development environment, minimal usage of SB.

Regards,
Himanshu

**Comment by masnider** [comment]
Yes this needs to be handled via a support ticket with Microsoft for the Service Bus on prem product. Please follow up there if you haven't already.
