### ISSUE TITLE
Visual Studio unloads SFPROJ if Microsoft.VisualStudio.Azure.Fabric.MSBuild was added from unorthodox path

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#1388]
If SFPROJ imports Microsoft.VisualStudio.Azure.Fabric.MSBuild like this:

```xml
<Import Project="$(PkgMicrosoft_VisualStudio_Azure_Fabric_MSBuild)\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" />
```

Then when I open solution, I'm getting this dialog popped-up:

> Your Fabric Application project 'D:\Projects\MyProject\src\Applications\MyProject\Application\MyProjectsfproj' must be upgraded in order to be loaded. Would you like to do that? Yes, No.

If I answer Yes then it removes all customizations and imports everything from "orthodox" (aka default VS template) path:

```xml
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets=";ValidateMSBuildFiles">
  <Import Project="..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />

  <Import Project="..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />
  <Target Name="ValidateMSBuildFiles">
    <Error Condition="!Exists('..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" Text="Unable to find the '..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
    <Error Condition="!Exists('..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" Text="Unable to find the '..\..\..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
  </Target>
</Project>
```

If I answer No then VS unloads the project forever.

This is a regression (aka new behavior) of VS 2017 after an update in the middle of this year.

You're using CoreXT as well so likely facing the same issue.

**Comment by abatishchev** [comment]
Ping.

**Comment by dbreshears** [comment]
We added the ability to bypass this behavior to help with CoreXT users.   Can you try adding this to the .sfproj file as a property

<DoNotUpdateNuGetImport>true</DoNotUpdateNuGetImport>

**Comment by abatishchev** [comment]
@dbreshears hi, unfortunately this didn't work for us. Having this

```
Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.0319
```

and this

```
<package id="Microsoft.VisualStudio.Azure.Fabric.MSBuild" version="1.6.7" />
```

It still behaves the old way. Is there a package or something we should update/upgrade?

**Comment by ravipal** [comment]
Project upgrade installs the latest MSBuild nuget package supported by the tooling and updates the project with the paths to the imported nuget package. No flag to disable this update.
@abatishchev Hope this answers your question. Please reopen if you need more information.

**Comment by abatishchev** [comment]
The problem is that the latest MSBuild nuget package is already installed but in CoreXT form. VS prompts to update anyway, changes paths to retail form and fails to open the project afterwards regardless.

Please reopen. But some reason I cannot.

**Comment by ravipal** [comment]
The project upgrade is controlled by the ProjectVersion specified in the *sfproj. If your project has the non supported project version, then we prompt to upgrade the project. And as part of project upgrade, we upgrade the nuget pakage as well. This upgrade is not related to current MSBuild nuget package version.
