### ISSUE TITLE
Error message when trying to enable reverse proxy

### ISSUE THREAD

**Issue by JefSchraag** [Azure/service-fabric-issues#1389]
Hi,

To enable the reverse proxy service in our standalone cluster, I followed the guides [Enable reverse proxy on standalone clusters](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-setup#enable-reverse-proxy-on-standalone-clusters) and [Upgrade the configuration of a standalone cluster](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-config-upgrade-windows-server).

I added the `"reverseProxyEndpointPort": "19081",` line to the configuration file and issued this command:

```powershell
Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath  d:\updatedconfig.json
```

The output is:

```powershell
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: The update of 'HttpApplicationGatewayEndpoint' is not allowed.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath  D: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade

```

What can I do enable it?

_Side note:_

The reverse proxy worked before but it disappeared with the last configuration I executed. I suspect that it was enabled a long time ago via `Start-ServiceFabricClusterUpgrade` with a modified manifest XML file. It looks like the configuration JSON that I updated was not in sync with the manifest.

Thanks,

Jef

**Comment by JefSchraag** [comment]
This [config-and-manifest-old-and-new.zip](https://github.com/Azure/service-fabric-issues/files/2675041/config-and-manifest-old-and-new.zip) contains the old and new config.json and manifest.xml files.

**Comment by masnider** [comment]
I believe there is a known issue where the reverse proxy can't be enabled in a standalone cluster if the cluster was initially created without it enabled. We are aware of this issue and are going to be releasing an update to SF that makes it possible to enable the reverse proxy. @kavyako can provide more information and confirm if I'm correct.

**Comment by JefSchraag** [comment]
The root cause turned out to be that our manifest XML and configuration JSON were out of sync.
