### ISSUE TITLE
Can't start the service fabric dev cluster after upgrade

### ISSUE THREAD

**Issue by jstawski** [Azure/service-fabric-issues#1391]
I had a previous version of the SDK and Runtime running on my local development environment (i'm not sure which one). After upgrading the nuget packages I was running into a COM error of some sort, which after reading online was mentioning that there was a mismatch between the packages and the SDK. At least that is what I understood. So I used Web Platform installer to install the latest SDK 3.3.617.9590 and the Runtime 6.4.617.9590. After that I couldn't deploy my services locally with VS 2017. After lots of troubleshooting steps I realized there is a probklem with the local cluster. I tried reinstalling many times, including the VS Tools.

Attached is the installation log as well as the event logs. Please help, i've been dealing with this issue for 2 days!

I'm running Windows 10 with the latest updates on a Virtual Machine using VMWare Fusion with a Mac Host. This was not an issue before the upgrade.

[ServiceFabriLogs.zip](https://github.com/Azure/service-fabric-issues/files/2677675/ServiceFabriLogs.zip)

[MicrosoftServiceFabricSDK.3.3.617.zip](https://github.com/Azure/service-fabric-issues/files/2677660/MicrosoftServiceFabricSDK.3.3.617.zip)

**EDIT**
Reading the event logs, it seemed like a restart was pending, so here are the logs again after the restart

[ServiceFabriLogsAfterRestart.zip](https://github.com/Azure/service-fabric-issues/files/2678042/ServiceFabriLogsAfterRestart.zip)

**Comment by anantshankar17** [comment]
Are you setting up the cluster using the LocalClusterManager or & "C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1" -Auto  ?
Can you redeploy cluster using the DevClusterSetup script and share the output ? Also can you share traces on failure from: C:\SfDevCluster\Log\Traces ?

**Comment by jstawski** [comment]
I was actually setting it up through the UI of Local Cluster Manager. Trying the PowerShell above without -Auto yields: 

> PS C:\WINDOWS\system32>  cd "$env:ProgramW6432\Microsoft SDKs\Service Fabric\ClusterSetup"
> PS C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup>  .\DevClusterSetup.ps1
> WARNING: A local Service Fabric Cluster already exists on this machine and will be removed.
> Do you want to continue [Y/N]?: Y
> Removing cluster configuration...
> Cleaning existing certificates...
> Certificates removed.
> Stopping all logman sessions...
> Cleaning log and data folder...
> 
> Using Cluster Data Root: C:\SfDevCluster\Data
> Using Cluster Log Root: C:\SfDevCluster\Log
> 
> The generated json path is C:\Users\jstaw\AppData\Local\Temp\tmpAC49.tmp.json
> Processing and validating cluster config.
> Check if machine 'ComputerFullName' is IOT Core: False. Could not open registry key.
> Performing Stop-Service on service: FabricHostSvc . This may take a few minutes...
> Create node configuration succeeded
> Performing Start-Service on service: FabricHostSvc . This may take a few minutes...
> 
> Waiting for Service Fabric Cluster to be ready. This may take a few minutes...
> Local Cluster ready status: 4% completed.
> Local Cluster ready status: 8% completed.
> Local Cluster ready status: 12% completed.
> Local Cluster ready status: 17% completed.
> Local Cluster ready status: 21% completed.
> Local Cluster ready status: 25% completed.
> Local Cluster ready status: 29% completed.
> Local Cluster ready status: 33% completed.
> Local Cluster ready status: 38% completed.
> Local Cluster ready status: 42% completed.
> Local Cluster ready status: 46% completed.
> Local Cluster ready status: 50% completed.
> Local Cluster ready status: 54% completed.
> Local Cluster ready status: 58% completed.
> Local Cluster ready status: 62% completed.
> Local Cluster ready status: 67% completed.
> Local Cluster ready status: 71% completed.
> Local Cluster ready status: 75% completed.
> Local Cluster ready status: 79% completed.
> Local Cluster ready status: 83% completed.
> Local Cluster ready status: 88% completed.
> Local Cluster ready status: 92% completed.
> Local Cluster ready status: 96% completed.
> Local Cluster ready status: 100% completed.
> WARNING: Service Fabric Cluster is taking longer than expected to connect.
> 
> Waiting for fabric:/System/NamingService to be ready. This may take a few minutes...
> No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.
> Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS
> issue.
> At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:979 char:12
> +     [void](Connect-ServiceFabricCluster @connParams)
> +            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException
>     + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster
> 

I'm trying with the Auto flag now, I will add the traces once that is finished

**Comment by jstawski** [comment]
Same result with the -Auto flag. Here are the traces:
[Traces.zip](https://github.com/Azure/service-fabric-issues/files/2681914/Traces.zip)

**Comment by anantshankar17** [comment]
Thanks @jstawski for sharing the traces.
It seems the fabric.exe is getting terminated with the error code indicating some dll not found. It might occur due to a missing/corrupt vcredist instance. To mitigate this, I would suggest you to uninstall both the vcredist and the SF runtime/sdks, and re-install everything again through webPI. Can you try that and let us know ? Thanks!

**Comment by jstawski** [comment]
Which redistributable should I uninstall?

![image](https://user-images.githubusercontent.com/873800/50098466-fb802d80-01e9-11e9-9985-bb12f764825c.png)

**Comment by jstawski** [comment]
Ok, I uninstalled all three 2012 C++ Redistributables, Service Fabric Runtime and SDK followed by a an installation of Service Fabric SDK through Web Platform Installer. When finished, I restarted just in case and started the Installation of the Cluster through PowerShell: `.\DevClusterSetup.sp1 -Auto`.

I have the same output as above and attached are my new traces
[Traces.zip](https://github.com/Azure/service-fabric-issues/files/2686966/Traces.zip)

**Comment by anantshankar17** [comment]
These are the vc redists that come for the 6.4 runtime, can you repair these:
![image](https://user-images.githubusercontent.com/39825466/50102950-7e39d480-024c-11e9-85ba-5339f57866ec.png)
Also, I see the same error in the traces, all fabric.exe are terminating with the same error: 
HostedServiceInstance:HostedService/_Node_1_Fabric terminated with exitcode 3221225781
@harahma can you also take a look ?

**Comment by jstawski** [comment]
I will also uninstall the 2017 Redistributable and try again

**Comment by jstawski** [comment]
Uninstalling the 2017 Redistributables was the key. I'm back in business

**Comment by anantshankar17** [comment]
Good to know!
