### ISSUE TITLE
How can I reactive a actor when it excute OnDeactiveAsync method.

### ISSUE THREAD

**Issue by Damon227** [Azure/service-fabric-issues#1392]
I create a actor and it has q queue, so I want to keep actor in active state when the queue is not empty.
Is there any method to do it?

**Comment by guibirow** [comment]
You try using [Actor Reminders](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-lifecycle), every time a reminder is activated it will extend the life of the active actor.

So, whenever you put items in the queue, you register a reminder, when the queue gets empty you remove the reminder.

**Comment by Damon227** [comment]
@guibirow Thank you, It's helped to me by using Actor Reminder, but is there other way to fix it?

**Comment by guibirow** [comment]
What you mean with "fix it"?

It is the default behaviour, not a bug.

If you want to change the configuration to increase the lifetime, you can set the Idle timeout for garbage collection, then the actor will stay longer in memory.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-lifecycle
