### ISSUE TITLE
Manifest validations appears to require XML tags in some specific order

### ISSUE THREAD

**Issue by IanMercer** [Azure/service-fabric-issues#1394]
I'm getting the completely unhelpful error message "Exception while parsing XML file" on our ApplicationManifest.xml file. The XML file is a perfectly valid, well-formed XML file.

Running `Test-ServiceFabricApplicationPackage -ApplicationPackagePath .` whilst trying every possible permutation of the ApplicationManifest,xml file has helped me figure out why it's objecting.

It appears that the order of the `ConfigOverrides` element and the `EnvironmentOverrides` elements within the `ServiceManifestImport` tag have to be in that specific order. If I switch them the Test command fails.

Why would you insist on these elements being in some specific order?

Suggest that the Test script should not enforce some un-knowable order on the elements but allow any valid XML with the appropriate elements to be used.

**Comment by oanapl** [comment]
@IanMercer , thank you for your feedback,
Test-ServiceFabricApplicationPackage checks whether the given manifest respects the [service model XML schema](https://docs.microsoft.com/azure/service-fabric/service-fabric-service-model-schema). The reason for the check is to ensure the Service Fabric can read and parse the manifest. If it doesn't respect the schema, the package can't be provisioned and then instantiated to create applications.

Therefore, to ignore the order of elements, we would need to update the schema, and not the validation logic. Please check https://github.com/Azure/service-fabric-issues/issues/65 for a similar issue. Changes to schema would require significant work on our side to ensure compatibility and correct validation. I understand your frustration. As the mentioned issue describes, you can open our xsd at "C:\Program Files\Microsoft SDKs\Service Fabric\schemas\ServiceFabricServiceModel.xsd" in Visual Studio to get better intellisense for manifest issues.

**Comment by IanMercer** [comment]
I have suggested an update to the docs but maybe you should also consider splitting the various XML validation errors into distinct cases, e.g. malformed XML vs XSD validation failed so you can make the error message more specific, like, perhaps "Failed XSD validation, check element names and ordering" and thus help lead people to the realization that the only thing wrong with their XML is some hidden ordering constraint in the XSD.

**Comment by oanapl** [comment]
I have opened a tracking issue on our side to look into improving the error message to show more specific failure info. Thank you for your feedback!

**Comment by iyyappam** [comment]
This is fixed in v6.5 RTO.
