### ISSUE TITLE
Error upgrading the SF cluster to latest version (manual & automatic)

### ISSUE THREAD

**Issue by Lemraj** [Azure/service-fabric-issues#1395]
Hi,

I have a question about upgrading the SF clusters. We have 3 SF clusters (Dev\QA\PRD), all set to automatic upgrade mode. The Dev cluster is upgraded to the latest version (**6.4.617.9590**) , the other clusters still have the version (**6.3.187.9494**). I discovered this after deploying an application (updated with the laterst SF packages) to the QA cluster. The new application was succefully deployed, but we got runtime errors.

I tried to manually to upgrade the cluster to the latest version using the portal & ARM template, but I get now this error:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "ClusterUpgradeFailed", "message": "Cluster upgrade failed. Reason Code: 'HealthCheck', Upgrade Progress: '{"upgradeDescription":{"targetCodeVersion":"6.3.187.9494","targetConfigVersion":"55","upgradePolicyDescription":{"upgradeMode":"UnmonitoredAuto","forceRestart":false,"upgradeReplicaSetCheckTimeout":"00:20:00","kind":"Rolling"}},"targetCodeVersion":"6.3.187.9494","targetConfigVersion":"55","upgradeState":"RollingBackCompleted","upgradeDomains":[{"name":"0","state":"Completed"},{"name":"1","state":"Completed"},{"name":"2","state":"Completed"},{"name":"3","state":"Completed"},{"name":"4","state":"Completed"}],"rollingUpgradeMode":"UnmonitoredAuto","upgradeDuration":"00:49:03","currentUpgradeDomainDuration":"00:00:00","unhealthyEvaluations":[{"baselineErrorCount":0,"baselineTotalCount":7,"totalCount":7,"maxPercentDeltaUnhealthyNodes":0,"unhealthyEvaluations":[{"nodeName":"_Frontend_0","unhealthyEvaluations":[{"unhealthyEvent":{"sourceUtcTimestamp":"2018-12-18T22:01:20.0181726Z","lastModifiedUtcTimestamp":"2018-12-18T22:01:29.541081Z","isExpired":false,"lastOkTransitionAt":"0001-01-01T00:00:00","lastWarningTransitionAt":"0001-01-01T00:00:00","lastErrorTransitionAt":"2018-12-18T22:01:29.541081Z","healthInformation":{"sourceId":"System.FM","property":"State","healthState":"Error","description":"Fabric node is down.","timeToLive":"10675199.02:48:05.4775807","removeWhenExpired":false,"sequenceNumber":908}},"considerWarningAsError":false,"kind":"Event","description":"Error event: SourceId='System.FM', Property='State'.","aggregatedHealthState":"Error"}],"kind":"Node","description":"Unhealthy node: NodeName='_Frontend_0', AggregatedHealthState='Error'.","aggregatedHealthState":"Error"}],"kind":"DeltaNodesCheck","description":"Delta nodes health check failed. Baseline and current status: 0% (0/7) - 14% (1/7), MaxPercentDeltaUnhealthyNodes=0%.","aggregatedHealthState":"Error"}],"currentUpgradeDomainProgress":{"upgradeDomainName":"","nodeProgressList":[]},"startTimestampUtc":"2018-12-18T21:14:53.489004Z","failureTimestampUtc":"2018-12-18T22:01:56.879326Z","failureReason":"HealthCheck","upgradeDomainProgressAtFailure":{"upgradeDomainName":"","nodeProgressList":[]}}'.", "details": [] } ] }}"}]}`

---------
**Errors in Event Viewer in VM node:**
Faulting application name: Fabric.exe, version: 6.4.617.9590, time stamp: 0x5bf55547
Faulting module name: CONCRT140.dll, version: 6.3.9600.19153, time stamp: 0x5b93ffa7
Exception code: 0xc0000135
Fault offset: 0x00000000000ecf30
Faulting process id: 0x878
Faulting application start time: 0x01d496e8c6256620
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Fabric.exe
Faulting module path: CONCRT140.dll
Report Id: 03d6b6cc-02dc-11e9-810f-000d3a27a9af
Faulting package full name: 
Faulting package-relative application ID: 
----------

Any idea why this is happening?

Thanks.

**Comment by masnider** [comment]
Looks like another instance of https://github.com/Azure/service-fabric-issues/issues/1382. Can you confirm? If so we can take the discussion over there.

**Comment by Lemraj** [comment]
@masnider Thank you for your comment! It looks the same. In the mean time I have also created a support ticket and send them some log & dump/crash files for investigation. We have 3 clusters and only 1 was successfully upgraded (automatic). Today I tried twice after rebooting the node was causing the issue (on advice of support), but still the same problem.

**Comment by Lemraj** [comment]
Upgrading to the new version 6.4.622.9590 solved my problem I think. One more thing is that status of the cluster now set to **Failed**. Anyone knows why?
