### ISSUE TITLE
Service crash during upgrade with less reliable dictionary

### ISSUE THREAD

**Issue by losha228** [Azure/service-fabric-issues#1396]
SF version :  6.4.617.9590

I deployed a new version of application, and  the new version of my stateful service added a new reliable dictionary ,  it works fine. Then I upgrade the application by old version of application.  The upgrade was failed, the error said the host was crash.  So when upgrade with more reliable dictionary works, but  upgrade with less reliable dictionary fails.    

The error was : 

`There was an error during CodePackage activation.The service host terminated with exit code:2148734499`
--

**Comment by masnider** [comment]
That's just a failfast. If you look in the service's logs or event viewer on the machine you'll usually find a more detailed description of the failure.  

Sounds like you're running into https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-data-serialization

**Comment by zuhairp** [comment]
Closing since there hasn't been any recent activity
