### ISSUE TITLE
Guest exe deployment - stuck on upgrade

### ISSUE THREAD

**Issue by asosMikeGore** [Azure/service-fabric-issues#1398]
I am running an upgrade of a guest exe in unmonitored auto mode in test environments to speed up my CI/CD pipeline.  However, I have noticed that during the upgrade process that the process gets hung per upgrade domain with the following event:

Unhealthy event: SourceId='System.RAP', Property='IStatelessServiceInstance.CloseDuration', HealthState='Warning', ConsiderWarningAsError=false.
The api IStatelessServiceInstance.Close on node _FrontEnd_1 is stuck.

The guest exe is an ASP.NET Core 2.2 application, and my understanding is that I shouldn't need to write any code to handle CTRL+C commands which if not responded to would cause this I believe.  Is there any guidance on how to get rid of these warnings?

Originally the guest exe entry point was a .bat file so I could set ASP.NET Core hosting environment variables, which I was concerned was blocking CTRL+C termination (due to Terminate Batch Job (Y/N) message with the Windows cmd shell).

This is running Service Fabric 6.4.622.9590.  Do you have any guidance as to how we could optimise this?  Releases are currently taking 20 mins for a 5 node cluster, and I was expecting it to take 5 minutes with default deployment settings.

**Comment by suhuruli** [comment]
@tugup @harahma can you help investigate this?

**Comment by suhuruli** [comment]
@asosMikeGore, to clarify, what is the guest exe entry point now? If it is still the .bat file?

**Comment by asosMikeGore** [comment]
The entry point is the ASP.NET Core 2.2 app at the moment.  Once I understand what's going on with that though I would like to see if I can get the .bat file approach working as it removes platform coupling in the service.

All the guest exe is doing right now is binding to the port Service Fabric supplies via the "Fabric_Endpoint_<SERVICENAME>TypeEndpoint" environment variable.

**Comment by suhuruli** [comment]
That's interesting. With a .bat file, there is a known issue that you mentioned above with Windows just holding the shutdown hook. With a regular .NET Core app this should not be happening unless your app is specifically holding a Ctrl+C. @harahma, can you please help?

**Comment by MonDeveloper** [comment]
I think it's due to the command interpreter, probably it's not a SF issue.
I noticed SF decides to run the commands this way: 
```
cmd /c "<your command here>"
``` 
and when I try to replicate the behaviour sending manually a CTRL-C I receive the "Terminate Batch Job (Y/N)" message so, probably, this is the reason why SF waits so long before deciding to kill the process (I guess)

I'm using guest service to run a standard 
```
java.exe -jar x.y.z.jar
```
