### ISSUE TITLE
Error when passing existing certificate to New-AzureRmServiceFabricCluster

### ISSUE THREAD

**Issue by markti** [Azure/service-fabric-issues#1402]
I am trying to automate the deployment of a secure service fabric cluster using a Wildcard SSL Certificate (*.mydomain.com) that I purchased from a public Certificate authority. 

I am using the 5-VM-Windows-1-NodeTypes-Secure-NSG template from the samples provided. In my template, I specified the following parameters:

- certificateStoreValue
- certificateThumbprint
- sourceVaultValue
- certificateUrlValue

When I execute the following Powershell, it ignores the values I pass in for certificate thumbprint / sourceVaultValue / certificateUrlValue and dynamically generates a KeyVault and a new certificate and uses that certificates thumbprint in my SF cluster.

```
New-AzureRmServiceFabricCluster  `
    -ResourceGroupName $resourceGroupName  `
    -TemplateFile $templateFilePath  `
    -ParameterFile $parameterFilePath  `
```

In reading some of the documentation on the "New-AzureRmServiceFabricCluster" command, I found that there are some additional parameters that drive behavior that I may need to use even if I am supplying those in the ARM Template. I was expecting that supplying these directives through parameters to the ARM template would be enough but given the behavior described above this is clearly not the case.

The "New-AzureRmServiceFabricCluster" has the following parameters of interest:

- SecretIdentifier
- KeyVaultName 
- KeyVaultResouceGroupName 

Example 2 from the [Powershell examples](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/new-azurermservicefabriccluster?view=azurermps-6.13.0) shows that you should be able to use SecretIdentifier alone. However, when I execute the example as such:

```
New-AzureRmServiceFabricCluster  `
    -ResourceGroupName $resourceGroupName  `
    -TemplateFile $templateFilePath  `
    -ParameterFile $parameterFilePath  `
    -SecretIdentifier $secretId
```

I get the following error:

> New-AzureRmServiceFabricCluster : One or more errors occurred.
> At C:\src\ClusterTemplate\Deploy-Cluster.ps1:9 char:1
> + New-AzureRmServiceFabricCluster  `
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [New-AzureRmServiceFabricCluster], AggregateException
>     + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster

It doesn't make sense to me. After trying different combinations of the fore-mentioned parameters I found that passing in the existing KeyVaultName and KeyVaultResourceGroupName does indeed utilize that KeyVault but only to store an newly inserted self-signed certificate. Which is not my intention. My intention is to use an existing certificate in an existing KeyVault.

**Comment by masnider** [comment]
Hi @markti , since we haven't heard back from you, closing down this issue. If you are still having problems please let us know either by reopening this issue or creating another. Thanks!
