### ISSUE TITLE
Automatic Backup and Restore service for Service Fabric

### ISSUE THREAD

**Issue by balukantu** [Azure/service-fabric-issues#1404]
Hi Team,

We are eager to work on Automatic Backup and Restore service for Service Fabric. 

We have created a .Net Core Service Fabric solution with Reliable services which include the following capabilities:
	1. Stateful Service ( To store data)
	2. Stateless Service ( gateway)
	3. Backup And Restore ( We have implemented custom logic to take backup and restore it)	

All these components are implemented using.Net Core So can you please provide me with a mechanism to automate backup and restore.
It would be grateful if you provide any sample application.

Thanks 
Balu

**Comment by raunakpandya** [comment]
Have you looked at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster 
With this you don't need to write any custom logic to automate backup restore. The article covers in details the steps to enable and configure the service. Let us know if you face any trouble or have questions.

**Comment by hrushib** [comment]
Marking this as closed as the original question for this issue is already addressed.
