### ISSUE TITLE
Enabling backup and restore service

### ISSUE THREAD

**Issue by balukantu** [Azure/service-fabric-issues#1405]
Hi Team,

I am working on [Automatic Backup and Restore service for Service Fabric.](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster) As part of this, I have updated DevCluster.Config to enable backup and restore service.

Now I am trying to upgrade my local cluster with below endpoint and facing error.

**Cluster command to upgrade**
_Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath  "ClusterMani
festTemplate.json"_

**Error message**
Start-ServiceFabricClusterConfigurationUpgrade : Operation timed out.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath  "C ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gurationUpgrade], TimeoutException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade

Can someone help me how to upgrade my local cluster to enable backup and restore service?

**Comment by raunakpandya** [comment]
We would need to look at the logs to understand the failure. However, just to workaround, since its a dev cluster, why are you trying to upgrade? Do you see issues if bringing up the cluster with the service on in json still causes issue for you?

**Comment by raunakpandya** [comment]
@balukantu - Did you try out?

**Comment by raunakpandya** [comment]
Closing this as we havent heard back here. Please reactivate if you are still facing issue or want further follow up.
