### ISSUE TITLE
Dev Cluster is not starting if the computer name contains dash

### ISSUE THREAD

**Issue by alexisconia** [Azure/service-fabric-issues#1406]
I was trying to deploy an app on a dev cluster (Azure Service Fabric SDK 3.3.622) and i always got "Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.". The service was started but i could not connect to the explorer. I also got event in Event viewer "client-SURFACEBOOK-ALE:19000 : connect failed, having tried all addresses"
I discovered that the problem came from my computer name. There was a dash. After removing it, everything is ok.

**Comment by anantshankar17** [comment]
@alexisconia your issue could be related to https://github.com/Azure/service-fabric-issues/issues/1060#issuecomment-425033033 aswell, where a cluster can't be created if the machine name is longer than 15 characters, as cluster creation normally works even if the machine name contains a "-"

**Comment by alexisconia** [comment]
Thanks for the reply @anantshankar17
