### ISSUE TITLE
Synchronization issue in azure service fabric application upgrade

### ISSUE THREAD

**Issue by muradkhateeb78** [Azure/service-fabric-issues#1412]
Hi,

I have a service fabric application that has a single guest executable type in it. I have created 150 services inside that application. Each of these services does the following in **SetupEntryPoint**.
![syn_app_upgrade](https://user-images.githubusercontent.com/24789672/51037437-0a33e780-15d2-11e9-81d5-41540ede17d8.PNG)
Now initially the services gets created in a sequential order and only the first service will extract **tests.zip** and all the remaining services will be using the already extracted package. So far so good.

In case of **application upgrade** , the service fabric tries to restart all the services in parallel and runs into a synchronization issue on only a subsets of nodes (usually one). This results in service not getting initialized properly. So some of those 150 services which were responsive before the upgrade are now unresponsive, even though the upgrade has completed successfully. 
We want to have your feedback on this.

Thanks!

**Comment by muradkhateeb78** [comment]
@oanapl any comments?

**Comment by oanapl** [comment]
@raunakpandya is right, the upgrade itself doesn't synchronize anything. The app itself must take care of any specific requirements. You will probably hit similar issues (at lower scale) if nodes go down unexpectedly, so it's not upgrade specific issue (though obviously that's where you will see it most). 
You need a way to ensure extracting/cleaning is done in a safe manner. I don't have enough info about your requirements (are the zips different, do all replicas need to setup this way or one can do it and the rest await for it to be done etc), but you should look at these and set something at app level.
