### ISSUE TITLE
Patch Orchestration Application v1.3.0 does not work on Windows Server 2012 

### ISSUE THREAD

**Issue by raunakpandya** [Azure/service-fabric-issues#1417]
POA v1.3.0 has a regression where it doesnt work on WIndows Server 2012 OS. It runs healthy but doesnt patch the system. Till a fix is released, please fall back to using v1.2.2 using the link http://download.microsoft.com/download/C/9/1/C91780A5-F4B8-46AE-ADD9-E76B9B0104F6/PatchOrchestrationApplication_v1.2.2.zip

**Comment by rapatchi** [comment]
This issue has been fixed and released in 1.3.1 . 

The release is available [here](https://go.microsoft.com/fwlink/?linkid=869566) and can also downloaded form the documentation page.
