### ISSUE TITLE
Service Fabric local cluster setup failing with error 32

### ISSUE THREAD

**Issue by RamjotSingh** [Azure/service-fabric-issues#1442]
I am trying to setup Service Fabric local cluster on my machine and it is failing. I have tried using the powershell and the local cluster manager.

Attaching the Event Viewer logs
[SFLocalClusterSetupFailure.txt](https://github.com/Azure/service-fabric-issues/files/2849419/SFLocalClusterSetupFailure.txt)

The first error I could see is
CreateFileW failed: file=\\?\C:\SfDevCluster\Data\FabricHostSettings.xml error=32
However the file actually does exist.

**Comment by anantshankar17** [comment]
Hello @RamjotSingh, can you please share traces from here: C:\SFDevCluster\Log\Traces ? 
Since there is an error "Hosting Failed to load vmcompute.dll. Error:126", do you have the FabricContainerAppsEnabled enabled ? Also just a sanity check, do you have containers enabled in windows ? Do you have docker for windows installed ? Is it configured for Windows Containers ?

**Comment by RamjotSingh** [comment]
I think I figured this one out not sure if this was indeed the issue. Apparently if your machine name is beyong NetBIOS limits (15 chars) it fails. Sadly I have lost repro since I cleared all directories. But should be easy enough to repro on your side I guess?

**Comment by anantshankar17** [comment]
It would really help if you can repro and then share the traces for this issue. I wanted to nail down why does the cluster setup fails when there is a mismatch in the hostname and the NetBIOS name. Sadly, I tried reproing it but it works for me.

**Comment by RamjotSingh** [comment]
No I had to rename my machine to get it working. Without renaming it was not working. I will try to see if I can get it break again in a Virtual machine on Azure.

**Comment by anantshankar17** [comment]
Thanks, I got the repro now.

**Comment by anantshankar17** [comment]
This has been fixed in the latest released runtime version 6.4.642. Please let us know if it works for you now.
