### ISSUE TITLE
The package stays uncompressed when publishing from Visual Studio

### ISSUE THREAD

**Issue by lilraft** [Azure/service-fabric-issues#1449]
When publishing the application to the SF cluster from Visual Studio with 
`<CopyPackageParameters CompressPackage="true"/>`
 in publish profile the package stays uncompressed. It also takes a long time to publish same as when CompressPackage is off. But when I force compress the package using SDK Copy-ServiceFabricApplicationPackage with SkipCopy flag on before publishing I can see that the subfolders are zipped and the package size is almost 3 times less than the original size. It takes just several minutes to publish and register while Visual Studio publishes much longer and even causes default timeouts

**Comment by dbreshears** [comment]
@lilraft .  Sorry for the delay on this.  I believe we had an issue and was fixed in later versions of the tooling.  When I examine the pkg output folder I notice a code.zip and config.zip file now.  Let  us know if you are not seeing this.
