### ISSUE TITLE
VMSS over-provisioning should not be allowed

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/service-fabric-issues#145]
It is now possible to set
```
"overprovision": true
```
on VMSS resource when provisioning SF cluster which leads to complete disaster (random nodes down potentially in same fault / upgrade domains etc)

It would be nice if template was rejected if VMSS is configured with over-provisioning as this does not seem to work well (in cases I tried - at all) with SF.

In one of the test deployments with over-provisioning, VMSS provisioned 7 nodes and took some down resulting in absolutely broken SF cluster:

![failed](https://cloud.githubusercontent.com/assets/931973/22233308/4e9ee302-e1a4-11e6-9b5a-a36187752c36.png)

**Comment by ChackDan** [comment]
I had explained the reason for this issue at http://stackoverflow.com/questions/36447326/overprovision-a-clusters-scale-set . 
however it does make sense that VMSS prevents this from happening when SF extension is deployed to it. I have filled a defect item on the VMSS team.

**Comment by TarasRoshko** [comment]
Can you please reference the VMSS issue you opened here? Otherwise it'd be hard to track if/when VMSS guys fix it

**Comment by ChackDan** [comment]
The internal TFS work item # is 8328086

**Comment by Mortana89** [comment]
Due to this it doesn't seem to be possible anymore to change admin passwords of a VMSS;
Overprovisioning not allowed on Virtual Machine Scale Sets with Service Fabric extension.

**Comment by ChackDan** [comment]
Please open a CSS ticket on VMSS for that.

**Comment by ChackDan** [comment]
I spoke the the VMSS engineers on this and they do not think the admin password issue you are hitting is related. If you still have that issue, please open a CSS ticket so that they can get to the bottom of the issue you are seeing.
