### ISSUE TITLE
Is there any benefit to using multiple sfproj files?

### ISSUE THREAD

**Issue by delradie** [Azure/service-fabric-issues#1452]
Hi All

I'm after a little guidance. We are expanding the number of services we are deploying to our fabric in Azure. Given all our services will be deployed together in the same devops release pipeline, is there any benefit to using separae sfproj files? 

It makes sense to me to keep the one referencing the different code projects, but wanted to check

Thanks in advance

**Comment by MattHartz** [comment]
I am not an expert, but where i've landed on this is any consolidated application (still can be many microservices) I would recommend 1 sfproj. If you're entire architecture is many applications, then you can break it out into more sfprojs.

Hope that helps! :)

**Comment by MikkelHegn** [comment]
In general all services referenced by an sfproj file will always deploy together, looking from a CI/CD perspective. That is how the tooling around VS and Azure DevOps is built. The fact that SF only upgrades services (code packages and config) which actually changed is a different story). As long as you are good with that, there is no benefit of using multiple sfproj files.

There are options to break this out in other workflows, but I would recommend only to go there if the above mentioned model does not work for you.

**Comment by delradie** [comment]
Thanks for the feedback guys, and sorry for not responding sooner. We've gone the route of the single file. Our pipelines are quite convoluted enough thank you very much :)

The only counter-argument we came up with when brainstorming internally was that when debugging you've got the load on the dev PC of all referenced services starting up, which we felt was nowhere near a good enough reason to cause more complexity in production.

Thanks again

Mark
