### ISSUE TITLE
fabric:/System/UpgradeService - Errors / improve stability of this service

### ISSUE THREAD

**Issue by rasmus-s** [Azure/service-fabric-issues#1455]
We getting some errors from the UpgradeService on our clusters. It seems like once we get the error (through our alerting system when the Cluster get into error mode) and we go to inspect the cluster through ServiceExplorer there are no other indications ofther than service fabric:/System/UpgradeService reports ERROR. The following stacktrace is shown in the ServiceExplorer:

`Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'.
AggregateException encountered:
InnerException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext()`

In the Events view we can see its happen a lot.
![image](https://user-images.githubusercontent.com/8188529/52998086-a26b8a80-3422-11e9-89f9-cf5adf66af5a.png)

Its all started 02/18/2019 08:42:40 PM on all our different environments, we have not upgraded the cluster recently.
We running SF version 6.4.617.9590 and 6.4.637.9590 on our clusters.

This is not first time the UpgradeService seems not handle the internal errors very well. (as ref see issue #1315)

**Comment by pksorensen** [comment]
i am seeing semilar

```
'UpgradeService.Primary' reported Warning for property 'SFRPPoll'.
AggregateException encountered:
InnerException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext() 
```

**Comment by pksorensen** [comment]
```
UpgradeService.Primary' reported Error for property 'SFRPPoll'.
AggregateException encountered:
InnerException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.174.163.204:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext() 
```

**Comment by pksorensen** [comment]
@rasmus-s - was this also resolved on your cluster now?

**Comment by rasmus-s** [comment]
@pksorensen Yes its return as healthy "11:24:39 AM (+0100)".

Service fabric team please improve the service reliability / stability - so when the service cannot communicate with external resources not make the whole cluster in Error mode.

**Comment by MikkelHegn** [comment]
@aljo-microsoft might be able to comment on this.

**Comment by mohannad-abwah** [comment]
Seems like the issue has come back in EUS. It's marking our entire cluster unhealthy and firing high severity alerts & phone calls to our live site engineer.

@aljo-microsoft: Is this actually a really bad problem that we need to be concerned about? What do we need to do?

**Comment by aljo-microsoft** [comment]
Thank you for filing a Service Fabric Issue for UpgradeService.

There are several reasons why your clusters UpgradeService could go into an error state, and yes you need to be concerned and respond to the incident in alignment with you management process and SLA’s.

An example is a user deploys a NSG rule that blocks communication between your cluster and Azure Service Fabric Resource Provider; please adopt [Service Fabric Networking best practices](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-networking#cluster-networking) to mitigate preventable issues. 

Another example is a user forgets to apply an [Access Control List (ACL) to your certificate for your Service Fabric Cluster](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#apply-an-access-control-list-acl-to-your-certificate-for-your-service-fabric-cluster), when deploying a new certificate thumbprint, resulting in their cluster being unable to access the certificate installed on their machines; please adopt [Azure Service Fabric Security Best Practices of secure a cluster by certificate common name](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#secure-a-service-fabric-cluster-certificate-by-common-name) to mitigate preventable issues.

Please ensure all reliable environment comply with [Azure Service Fabric Production readiness checklist](https://docs.microsoft.com/azure/service-fabric/service-fabric-production-readiness-checklist), leverage the appropriate [support options](https://docs.microsoft.com/azure/service-fabric/service-fabric-support), and self service discovering if your issue symptoms indicate it could be mitigated using an available [Troublehshooting guides](https://github.com/Azure/Service-Fabric-Troubleshooting-Guides).

Thank you for filing a Service Fabric Issue for UpgradeService.

There are several reasons why your clusters UpgradeService could go into an error state, and yes you need to be concerned and respond to the incident in alignment with you management process and SLA’s.

An example is a user deploys a NSG rule that blocks communication between your cluster and Azure Service Fabric Resource Provider; please adopt [Service Fabric Networking best practices](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-networking#cluster-networking) to mitigate preventable issues. 

Another example is a user forgets to apply an [Access Control List (ACL) to your certificate for your Service Fabric Cluster](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#apply-an-access-control-list-acl-to-your-certificate-for-your-service-fabric-cluster), when deploying a new certificate thumbprint, resulting in their cluster being unable to access the certificate installed on their machines; please adopt [Azure Service Fabric Security Best Practices of secure a cluster by certificate common name](https://docs.microsoft.com/azure/service-fabric/service-fabric-best-practices-security#secure-a-service-fabric-cluster-certificate-by-common-name) to mitigate preventable issues.

Please ensure all reliable environment comply with [Azure Service Fabric Production readiness checklist](https://docs.microsoft.com/azure/service-fabric/service-fabric-production-readiness-checklist), leverage the appropriate [support options](https://docs.microsoft.com/azure/service-fabric/service-fabric-support), and self service discovering if your issue symptoms indicate it could be mitigated using an available [Troublehshooting guides](https://github.com/Azure/Service-Fabric-Troubleshooting-Guides).

@mohannad-abwah 
Although I'm closing this, please feel free to reopen this issue, if you feel the only question asked wasn't answered completely.
