### ISSUE TITLE
 'System.ReplicatedStore' reported Warning for property 'CommitPerformance' -Service Fabric Actors

### ISSUE THREAD

**Issue by sfsjoshi** [Azure/service-fabric-issues#1456]
Environment Details -
1.  5 instances of Stateless Service - Reads byte[] message from Azure Event Hub (Ingress hub) and Creates Actor. Leverages Event Processor Host
2.  40 Partitions Stateful Relaiable Actors - Persistent actors - Saves the passed byte[] to actor state. Pushes the same byte[] to another Azure Event hub.
3. 5 Instance of Stateless Service - Load generator - pushes continuous event to ingress event hub to be read by Service defined in point 1 above.

After continuous run for 5 minutes. Pushing 15000 message (size byte[](300 bytes) every 30 seconds - all actor partitions go into warning state with below warning. and after 2 minutes Primary replica of actor starts going down for most of partitions.
Could you advise what might be causing this slow commit error? Please let me know if you have any questions. Thanks. 
'System.ReplicatedStore' reported Warning for property 'CommitPerformance'.
Slow commits detected: count=60 time=[2019-02-21 06:11:28.941, 2019-02-21 06:12:27.649]

**Comment by ashishnegi** [comment]
@sfsjoshi Can you share your Reliable Actor transaction code ?
Are you making IO network calls in your transaction ?

**Comment by sfsjoshi** [comment]
Thanks Ashish for your response. 




using System;
using System.Threading.Tasks;
using Microsoft.ServiceFabric.Actors;
using Microsoft.ServiceFabric.Actors.Runtime;
using Microsoft.Azure.EventHubs;
using Innovapost.EventManager.Interfaces.Internal;
using System.Diagnostics;

namespace Innovapost.EventManager.Services.Processor
{

    [StatePersistence(StatePersistence.Persisted)]
    internal class Processor2 : Actor, IEventProcessorActor
    {


        /// <summary>
        /// Initializes a new instance of EventProcessorActor
        /// </summary>
        /// <param name="actorService">The Microsoft.ServiceFabric.Actors.Runtime.ActorService that will host this actor instance.</param>
        /// <param name="actorId">The Microsoft.ServiceFabric.Actors.ActorId for this actor instance.</param>
        public Processor2(EventProcessorActorService actorService, ActorId actorId)
            : base(actorService, actorId)
        {
        }

        /// <summary>
        /// Actor Processing logic + Persisting events in Database
        /// </summary>
        /// <param name="payload"></param>
        /// <returns></returns>
        public async Task ProcessEventAsync(byte[] payload)
        {
            try
            {
                ActorEventSource.Current.Message($"Actor Processing: {this.Id} processing started.");

                Stopwatch stpWatch = new Stopwatch();
                stpWatch.Start();
                // Validate payload
                if (payload == null)
                {
                    return;
                }

                //store actor state 
                var statePersisted = AddEventAsync(payload);

                
                stpWatch.Stop();

                //Push event to event Hub
                PersistEvent(payload);

            }
            catch (Exception ex)
            {
                // Trace exception as ETW event
                ActorEventSource.Current.Message($"{ex.Message} :: {ex.StackTrace}");
            }
        }

        /// <summary>
        /// This method is called whenever an actor is activated.
        /// An actor is activated the first time any of its methods are invoked.
        /// </summary>
        protected override async Task OnActivateAsync()
        {
            try
            {
               await base.OnActivateAsync();
            }
            catch (AggregateException aggregateEx)
            {
                // Trace Exception
                foreach (var exception in aggregateEx.InnerExceptions)
                {
                    ActorEventSource.Current.Message($"Exception:{exception.Message}");
                }
            }
            catch (Exception ex)
            {

                ActorEventSource.Current.Message($"Exception Message {ex.Message} : stack {ex.StackTrace}");
            }
        }

        protected override Task OnDeactivateAsync()
        {
            base.OnDeactivateAsync();
            //TODO:Cleaning and hydrating state to DB
            return Task.FromResult(true);
        }

        private void PersistEvent(byte[] eventData)
        {
            try
            {
                Stopwatch stpWatch = new Stopwatch();
                stpWatch.Start();

                var eventProcessorActor = ActorService as EventProcessorActorService;
                EventHubClient egressEventhub = null;

                if ((egressEventhub = eventProcessorActor?.EgressEventhubClient) == null)
                {
                    return;
                }

                var byteEvent = eventData;

                using (var eventhubData = new Microsoft.Azure.EventHubs.EventData(byteEvent))
                {
                    // Create custom properties
                    eventhubData.Properties.Add("Timestamp", DateTime.UtcNow);

                    egressEventhub.SendAsync(eventhubData);
                }
                stpWatch.Stop();
                ActorEventSource.Current.Message($"Actor Processing - Send to Egress EH Over AMQP:{stpWatch.Elapsed}, TrackingId{this.Id}");

            }
            catch (AggregateException aggregateEx)
            {
                /*
                 * To Do
                 * 1. Retry policies with Polly
                 * 2. Explore Redis cache usage for replaying message
                */
                // Trace Exception
                foreach (var exception in aggregateEx.InnerExceptions)
                {
                    ActorEventSource.Current.Message($"Exception:{exception.Message}");
                }
            }
            catch (Exception ex)
            {
                /*
                * To Do
                * 1. Retry policies with Polly
                * 2. Explore Redis cache usage for replaying message
               */
                // Trace Exception
                ActorEventSource.Current.Message($"Exception Message {ex.Message} : stack {ex.StackTrace}");
            }
        }


        public Task AddEventAsync(byte[] payload)
        {
            return StateManager.AddOrUpdateStateAsync(DateTime.UtcNow.Ticks.ToString(), payload, null);
        }

       

    }
}

Are you making IO network calls in your transaction ?
Yes transaction involves IO , as I mentioned in step 2 above - One is storing event/message data in Actor State and sendasync call on event hub client.

**Comment by ashishnegi** [comment]
You are not awaiting on the `AddEventAsync` returned `Task` at :
```
            //store actor state 
            var statePersisted = AddEventAsync(payload);
```

Also, not at :
```
      egressEventhub.SendAsync(eventhubData);
```

You should await on them, IMHO.
If you want to do both parallelly, you can use `Task.WaitAll(new Task[] { statePersistedTask, eventHubTask });`

+ @amanbha for Actor issues.

**Comment by sfsjoshi** [comment]
Thanks @amanbha , @ashishnegi .  
We are working on event streaming application and throughput being main concern.
We observed improved throughput with fire and forget.  Await was slowing the application throughput. Fire and forget handling happens on the thread as below. Please advise on your recommendations. Thanks.

ASYNCTask.ContinueWith
                        ((t) =>
                            {
                                if (!t.IsCompletedSuccessfully)
                                {
//Log failure
//Push event data into Re-try Event hub
                                    ServiceEventSource.Current.Message($"Exception processing actor:{t.Exception.Message}{t.Exception.InnerException}{t.Exception.StackTrace}");

                                }
                            
                            }
                        )
                        ;
Machine Type - DS3_V2 (4 VCPUs, 14 GB RAM) with Premium SSDs.

**Comment by amanbha** [comment]
Could you open a support ticket with Microsoft for this, please see: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

**Comment by amanbha** [comment]
Closing this issue, please open a support ticket with Microsoft for this, please see: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
