### ISSUE TITLE
Refresh Application works occasionally

### ISSUE THREAD

**Issue by JeffMushmo** [Azure/service-fabric-issues#1459]
Very consistently refresh application works the first time when debugging. The second time, it will completely reinstall my application. Sometimes it locks up the dlls and I have to stop and start the local cluster.

**Comment by ravipal** [comment]
Redeploy application: Refresh mode will redeploy the application, if it detemines that the application metadata has changed like application manifest or any of the service manifest. When you observed the application redeploy, were there any changes to application or service manifest?

dll lock up: Can you please share the output log or a sample repro application?

**Comment by JeffMushmo** [comment]
It seems that the refresh only works the first time. I'm not modifying anything that would change the app/service manifests. In fact, I can reproduce the issue by not modifying any code, and just pressing Run from within Visual Studio.

I've been able to reproduce this issue in every service fabric application we build.

Here's the consistent behavior I've seen:

- Run SF app from VS -> First install of SF app
- Test Web API call -> Hits breakpoint successfully
- Continue executing
- Stop executing SF app from VS
- Run SF app from VS -> Refresh of SF app successfully
- Test Web API call -> Hits breakpoint successfully
- Continue executing
- Stop executing SF app from VS
- Run SF app from VS -> SF app is completely uninstalled and reinstalled, no refresh appears to occur
![postuninstallreinstall](https://user-images.githubusercontent.com/37258233/53658247-1836d980-3c0d-11e9-8da5-564512fb28ef.png)
- Test Web API call -> Hits breakpoint successfully
- Continue executing
- Stop executing SF app from VS
- Run SF app from VS -> Refresh appears to have happened, but didn't see an indicator of this within SF explorer
- Test Web API call -> Doesn't hit breakpoint, but API call succeeds
- Stop executing SF app from VS
- Run SF app from VS -> cannot copy DLLs issue shows up and I have to stop and start SF cluster to recover
[CannotCopyLog.txt](https://github.com/Azure/service-fabric-issues/files/2920623/CannotCopyLog.txt)

**Comment by ravipal** [comment]
From the above steps it seems like first F5 succeeded with application deployment. Then second F5 succeeded and used the refresh mode properly(5th bullet point in your steps). The third F5 (9th bullet point) uninstalled and reinstalled the application. 

Lets first focus on why application gets redeployed and that could be the cause for dll lock issue. Please share the following
1. Clean the application from VS. This will uninstall the application from SF cluster. Also clear the "Service Fabric Tools" output window. So we can start the investigation from clean state.
2. Continue your usual steps (F5, stop, F5, stop, etc.) and collect the build output window. Please note that the build output will be truncated before each build. So please save the out put at the end of each F5, until you see an F5 is redeploying the application.
3. Collect the "Service Fabric Tools" output window, this should have the logging from all F5s.

**Comment by JeffMushmo** [comment]
Step 1 - Initial install & run
[01 - BuildOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920773/01.-.BuildOutput.txt)
[01 - ServiceFabricToolsOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920774/01.-.ServiceFabricToolsOutput.txt)

Step 2 - Refresh application
[02 - BuildOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920776/02.-.BuildOutput.txt)
[02 - ServiceFabricToolsOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920777/02.-.ServiceFabricToolsOutput.txt)

Step 3 - Failed refresh application, full reinstall
[03 - BuildOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920780/03.-.BuildOutput.txt)
[03 - ServiceFabricToolsOutput.txt](https://github.com/Azure/service-fabric-issues/files/2920781/03.-.ServiceFabricToolsOutput.txt)

**Comment by ravipal** [comment]
Output logs didn't show any issues, but somehow the refresh mode got reset. By any chance the service manifest or application manifests or dockerfiles if any gets updated between the first F5 and 3rd F5? To confirm, after First F5, rename the folder pkg at C:\MarqMetrix\Cloud\MAIN\Source\ServiceFabric.InstrumentAwarenessServices\InstrumentAwarenessServices\ to pkg1. Then once you hit the refresh issue (3rd F5), compare this pkg1 and pkg and see if there is any difference in application manifest and service manifest files.
If you don't have confidential information in your project, please share the project or similar repro project to ravipal@microsoft.com, so it is easier to debug.

**Comment by JeffMushmo** [comment]
You were right. The ApplicationManifest.xml file was being updated.

The commented out lines are the cause of this:
```xml
    <Service Name="InstrumentAwarenessWorkerServices" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="InstrumentAwarenessWorkerServicesType" InstanceCount="[InstrumentAwarenessWorkerServices_InstanceCount]">
        <SingletonPartition />
        <PlacementConstraints>[InstrumentAwarenessWorkerServices_PlacementConstraints]</PlacementConstraints>
      </StatelessService>
    </Service>
    <!--<Service Name="InstrumentRequestProcessor" ServicePackageActivationMode="ExclusiveProcess">
      <StatefulService ServiceTypeName="InstrumentRequestProcessorType" TargetReplicaSetSize="[InstrumentRequestProcessor_TargetReplicaSetSize]" MinReplicaSetSize="[InstrumentRequestProcessor_MinReplicaSetSize]">
        <UniformInt64Partition PartitionCount="[InstrumentRequestProcessor_PartitionCount]" LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>-->
    <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
```

In this order, everything works fine (the build/run process is changing the file to this, causing the difference):
```xml
    <Service Name="InstrumentAwarenessWorkerServices" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="InstrumentAwarenessWorkerServicesType" InstanceCount="[InstrumentAwarenessWorkerServices_InstanceCount]">
        <SingletonPartition />
        <PlacementConstraints>[InstrumentAwarenessWorkerServices_PlacementConstraints]</PlacementConstraints>
      </StatelessService>
    </Service>
    <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
    <!--<Service Name="InstrumentRequestProcessor" ServicePackageActivationMode="ExclusiveProcess">
      <StatefulService ServiceTypeName="InstrumentRequestProcessorType" TargetReplicaSetSize="[InstrumentRequestProcessor_TargetReplicaSetSize]" MinReplicaSetSize="[InstrumentRequestProcessor_MinReplicaSetSize]">
        <UniformInt64Partition PartitionCount="[InstrumentRequestProcessor_PartitionCount]" LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>-->
```

But I've changed things back to a more appropriate order (now the file is not being modified during build/run):
```xml
    <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
    <Service Name="InstrumentAwarenessWorkerServices" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="InstrumentAwarenessWorkerServicesType" InstanceCount="[InstrumentAwarenessWorkerServices_InstanceCount]">
        <SingletonPartition />
        <PlacementConstraints>[InstrumentAwarenessWorkerServices_PlacementConstraints]</PlacementConstraints>
      </StatelessService>
    </Service>
```

The issue was something is actually reversing the order of these two comments when they were in the improper order after every build/run.

An artifact of having things setup improperly, is after every build/run, if ApplicationManifest.xml is left open, Visual Studio mentions the ApplicationManifest.xml has been modified and offers to reload the file.

The issue observed in other solutions must be a similar fix.

Thank you.

**Comment by ravipal** [comment]
Glad you were able to identify the issue. During build AppManifestCleanupUtil.exe from Service Fabric SDK to clean up the ApplicationManifest.xml to remove any stale service definition or parameters definition. Unfortunately sometimes this tool will update the file, even when it is not really needed and caused this issue.
