### ISSUE TITLE
Service Fabric Cluster | Issues with Installing an Chained Certificate 

### ISSUE THREAD

**Issue by niragvt** [Azure/service-fabric-issues#1461]
Background 
•	We need to install a certificate chain (install a .pfx which installs certificates to trusted root & Intermediate certificate store) on our ASF cluster nodes so the services can call an external API
•	we uploaded the certificate to Key vault and installed it to VM Scale set using ARM template 
•	Certificate got uploaded to cert store of all nodes but the chain is not created & external API calls are failing from cluster 
•	When doing this on my local development machine, the chaining is correctly created & API call works (See below screenshots)

Queries 
•	Has anyone faced similar issue & resolved it for ASF cluster 
•	Is there any other way to install these certs? we also have .cer files which we can directly install to respective stores but currently not able to do it as KV supports on pfx

**Comment by dragav** [comment]
I believe we solved this over email (internally), please let me know if that is not the case.

In a nutshell, for this particular case:
- the pfx represents the full chain of a server cert and is therefore not a secret; as such, it should not be stored in KV
- the chain can be installed in the 'Trusted People' store
- for trusting the chain, the options are [Custom Script extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows), or something like SF's SetupEntryPoint of the application which would authenticate the remote party. I'm not aware of good cleanup options.
