### ISSUE TITLE
Generate alerts for service fabric buggy service

### ISSUE THREAD

**Issue by TehseenNawaz** [Azure/service-fabric-issues#1463]
Hi ,
Using the bellow approach we can Register the notification of cluster. 
![code](https://user-images.githubusercontent.com/41328964/53632801-a3c56000-3c37-11e9-9533-146237726c48.PNG)

So service Fabric will ping when any change will occur e.g when a new service will be created or deleted from cluster. But it will not notify if a service goes into **error or warning state**.

So is there is any way i can register the notification related to health monitoring of an application. If a service goes into warning or in error state, so service fabric will explicitly ping me about that.

Thanks

**Comment by oanapl** [comment]
No, we don't provide notifications out of the box for health issues. Take a look at our documentation for [monitoring overview](https://docs.microsoft.com/azure/service-fabric/service-fabric-diagnostics-overview) and look around at our monitoring options.
