### ISSUE TITLE
Running Guest Exe's from within Native SF instance

### ISSUE THREAD

**Issue by skirby1996** [Azure/service-fabric-issues#1465]
Hello, we have a node script we wanted to run as a guest executable in our cluster, whose behavior would be to perform some work, then delete itself when it has completed. However, we found that Service Fabric will automatically restart an executable if it terminates or crashes, which is not a behavior we wanted. Our workaround for this is to create a Native SF stateless service to contain the node process, and run it using the System.Diagnostics.Process library, before letting the service delete itself once it detects that the node process has finished. So far this approach fits our desired workflow, but I wanted to ask if there are any issues or concerns with using this approach (i.e. performance) that we may run into.

**Comment by ashishnegi** [comment]
Once work has finished, node process app can delete itself from service fabric using REST apis : [delete application](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deleteapplication) or [delete service](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deleteservice).

**Comment by ashishnegi** [comment]
@skirby1996 Hope this helped you. I will close the issue now.
