### ISSUE TITLE
Cannot publish to Azure Service Fabric Cluster

### ISSUE THREAD

**Issue by andyb70** [Azure/service-fabric-issues#1467]
Just trying to evaluate MS Service Fabric and we simply cannot deploy to our Azure remote cluster, I have read issues regarding what seems like the same problem but it appears the issue with MaxMessageSize was resolved sometime ago so shouldn't be impacting us.

The version we are running is 6.4.637.9590 this was taken from Control Panel -> Programs and Features

I'm getting a lot messages in with windows event viewer the same as this: -

client-XXXXXXX.northeurope.cloudapp.azure.com:19000: dropping message {6745d607-9abd-444f-bf2f-648c4983a5fa}:1023, Actor = FileReceiver, Action = 'FileUploadCommit'

and VS is just stuck at "Copying application to image store..." and simply sits there for hours!

I have removed my local cluster and retried but I get the same outcome.

**Comment by ashishnegi** [comment]
@andyb70 Is this a Linux cluster ?

**Comment by andyb70** [comment]
I retried this after a couple of days and everything was working again!
