### ISSUE TITLE
Do not set up dns service on local dev clusters if been disabled in the past

### ISSUE THREAD

**Issue by pksorensen** [Azure/service-fabric-issues#1478]
https://twitter.com/pksorensen/status/1109347078680072193

Every time I update SF SDKs the config files are rewritten and every time it causes me pain at some point because the DNS service updates my network settings to use the local DNS. I don't want that as it caused me more pain than gain. I keep disabling it on my local machine.

It would be nice if the installer/updates could respect this decision.

**Comment by anantshankar17** [comment]
@pksorensen thanks for the feedback. We will consider this. Also, we have recently root caused why the DNS service was screwing up the local DNS resolutions and working to fix that.

**Comment by masnider** [comment]
Thanks @anantshankar17 is there a corresponding public issue for the DNS problems that we can reference? If not let's consider making one for our own tracking.

**Comment by anantshankar17** [comment]
@masnider there isn't one yet. Will create and share that here.

**Comment by anantshankar17** [comment]
duplicate #https://github.com/Azure/service-fabric-issues/issues/1480
