### ISSUE TITLE
Cannot Add a Node (Running on Remote Host) to a Cluster

### ISSUE THREAD

**Issue by sg1970** [Azure/service-fabric-issues#148]
Hello,

**Scenario**: 
I need to add a remote Node (Running on a Separate PC say PC2 ) to a 5 node Cluster (C1) Running on say PC1. Both PC1 and PC2 can be running Win-10/7 or Windows Server 2016 but need clear clarifications on which Env is supported and which is not. Also Iam not sure if this scenario is supported.

(tl/dr scroll down to the Error I get section )

**What I have tried:**

Iam trying to add a Node which is running on a remote host to a 5 node cluster that I created using steps described in this link using Web Platform Installer --> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started

While the cluster (C1) was working and allowing me deploy applications , it was not allowing me to connect from remote node on PC2 when I ran this PS Command from PC2: **Connect--ServiceFabricCluster -ConnectionEndpoint "PC1:19000"** 

The Error I got was: "Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue".

I got past that error by cleaning the cluster (C1) and re-creating it by running these 2 commands on PC1:

`

    1. PS C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\> .\CleanCluster.ps1 

    2. PS C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup> .\DevClusterSetup.ps1 -PathToClusterDataRoot "C:\SFDevCluster\Data" -PathToClusterLogRoot "C:\SFDevCluster\Log" –UseMachineName 

`

So now to the main issue... to add the 6th node from PC2 (tried on Win10/Server 2016)  using steps described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes

PS Command I run to add Node (also tried various UD + FD combo's and on different Wkstn + Servers):
`
PS C:\Users\sg1970\Downloads\Microsoft.Azure.ServiceFabric.WindowsServer.5.4.145.9494> .\AddNode.ps1 -NodeName SG_5 -NodeType NodeType5 -NodeIPAddressorFQDN PC2 -ExistingClientConnectionEndpoint PC1:19000 -UpgradeDomain 5 -FaultDomain fd:/5 –AcceptEULA
`

**Error I get:**

Trace folder doesn't exist. Creating trace folder: C:\Users\sg1970\Downloads\Microsoft.Azure.ServiceFabric.WindowsServer.5.4.145.9494\DeploymentTraces
Add node to existing cluster failed with exception: System.InvalidOperationException: Cluster manifest did not have a Setup section.
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.GetFabricDataRootFromClusterManifest(ClusterManifestType clusterManifest)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<AddNodeAsyncInternal>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<AddNodeAsync>d__6.MoveNext()
VERBOSE: System.InvalidOperationException: Cluster manifest did not have a Setup section.
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.GetFabricDataRootFromClusterManifest(ClusterManifestType clusterManifest)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<AddNodeAsyncInternal>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<AddNodeAsync>d__6.MoveNext()
Add node to existing cluster failed with exception: System.InvalidOperationException: Cluster manifest did not have a Setup section.
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.GetFabricDataRootFromClusterManifest(ClusterManifestType clusterManifest)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<AddNodeAsyncInternal>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<AddNodeAsync>d__6.MoveNext()

Any help to get past this error and setting up a remote node will be greatly appreciated !

Thanks
SG

**Comment by mkosieradzki** [comment]
If I understand correctly you are trying to add node using Service Fabric Standalone installation tools to a Development Cluster. I believe it's totally not supported. Development Cluster is intended for development and testing only on a single machine.

If you want to create a multi machine Service Fabric cluster you should use Service Fabric Standalone installation and create a cluster using the Service Fabric Standalone package you have downloaded.

**Comment by sg1970** [comment]
@mkosieradzki 

Thanks,  If that is indeed the case the Link for https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes should add some extra clarification to that effect (that you cannot add remote nodes to a Dev Cluster)

**Comment by ChackDan** [comment]
Thankyou. This is a good suggestion. we will add the clarification to the document.

**Comment by sg1970** [comment]
@ChackDan 
Thanks, Any chance of allowing Dev Clusters to span across  at-least a limited no.of remote nodes in the future ?

**Comment by ChackDan** [comment]
I understand that enabling this feature will allow for simulating scale-out scenarios like say setting up 50 node cluster with just 5 machines..We have talked about this feature before, but it has always landed as low priority, since if you have three physical machines, you can always set up a non-scale min/dev cluster on them.  or use smaller VMs on the physical machines to achieve the scale out. I have created a new feature request and added it to our backlog.  However, I doubt it will get staffed any time soon.

**Comment by sg1970** [comment]
@ChackDan 

Thanks for the quick response !!

When you say:

> or use smaller VMs on the physical machines to achieve the scale out

Are you referring to this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server 

Is it possible to use that package on Win 7/10 workstations or Iam limited to running that on WIN Servers only ? 

Thanks
-SG

**Comment by ChackDan** [comment]
Refer to https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/create-virtual-machine to set up your VMs. It has nothing to do with service fabric.

**Comment by sg1970** [comment]
@ChackDan 

Running Server VMs is not an option for me due to restrictions ... However I can have a few physical Win 7/10 Workstations to play with .. so I just wanted to clarify if the multi-machine cluster configuration supports Win7/10 or is it strictly limited to Win Servers. ( The document  implies Server here --> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server)

Thanks
-SG

**Comment by masnider** [comment]
@sg1970 for production workloads we only support Windows Server today. Physical or Virtual doesn't matter. If it's just for development clusters/playing around/learning, then I think win10 workstation should be fine, but Chacko can confirm if there's anything known to be broken.

**Comment by ChackDan** [comment]
+1 to what Matt says. we do not support running production workloads on client OS. I am not aware of anything broken when using win10 to set up clusters, however those clusters should be used for dev/learn/play purposes only. Let us know if you find any issues.

**Comment by sg1970** [comment]
@masnider 

Right now for evaluation/experimental purposes ... but surely needs to support Win Workstations also (Atleast Win 10 Anniversary) in order for my org to be able to use it for prod workloads.

**Comment by ChackDan** [comment]
I apologize, but there is no current plans to add support for client OS for production use.
