### ISSUE TITLE
Service fabric does not honor CPUShares for Windows Containers

### ISSUE THREAD

**Issue by artisticcheese** [Azure/service-fabric-issues#149]
Putting CPUshares attribute in "ResourceGovernancePolicy" does not work for Windows Containers along with memory limits. Documented at <http://stackoverflow.com/questions/41665401/how-do-cpushares-in-resourcegovernancepolicy-works>

**Comment by mani-ramaswamy** [comment]
This is now fixed with the latest release @ https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/23/release-of-sdk-2-5-216-and-runtime-5-5-216-for-windows/.
