### ISSUE TITLE
Using Azure key vault as secret store for service fabric

### ISSUE THREAD

**Issue by Ahmad-Magdy** [Azure/service-fabric-issues#1490]
Hi 
I was wondering if there is a way to use Azure Key Vault as a secret store instead of using the encrypted XML files.
I searched in the docs and i didn't find any helpful information about doing that and if it possible or not.
Thanks.

**Comment by dragav** [comment]
@stevshan 

We are currently working on supporting application secrets declared as KeyVault references. In the meantime, you could use one of these options:

- if you own the VMSS and fully trust all the code running on it, then you can use its managed identity to access the vault (and obtain access tokens from your SF application). Here is an [intro to Managed Identities](https://azure.microsoft.com/en-us/blog/keep-credentials-out-of-code-introducing-azure-ad-managed-service-identity/). There is also a VM(SS) extension that can retrieve certificates from a vault for you: [KeyVault VM extension](https://devblogs.microsoft.com/aspnet/announcing-an-easier-way-to-use-latest-certificates-from-key-vault/)

- set up your own "managed identity": manually create an AAD app, generate credentials for it, provision its credentials onto the VMSS at deployment time (as a VMSS secret), and then use those credentials to obtain an auth token for the vault. Probably not worth the hassle, listing it here for completeness.

**Comment by Ahmad-Magdy** [comment]
@dragav Thanks Dragos.

**Comment by lgoncalv** [comment]
Hi @dragav , is there an issue number I can follow to track this feature?

Thanks

**Comment by dragav** [comment]
@tijoytom 

@lgoncalv No, this tracked internally. However, it is scheduled to be released with the upcoming SF 7.0 release. SF also supports [managed identities for SF apps](https://docs.microsoft.com/en-us/azure/service-fabric/concepts-managed-identity) now.
