### ISSUE TITLE
Lift&Shift WebApi app in VS2017 through Container Orchestrator Support  Publish does not work On Prem

### ISSUE THREAD

**Issue by undecided2013** [Azure/service-fabric-issues#1496]
Trying to add Service Fabric support to existing WebApi application to deploy to on-prem Service Fabric orchestrator. The resulting SF Project has a tie-in to Azure registry. 
It is showing an empty Azure Container Registry ComboBox and the Publish button is disabled.

This behavior is different than the dialog that is presented if we manually create a Service Fabric Application with Containers. When the project is created manually, the container image is retrieved and constructed on the Service Fabric nodes. The Publish dialog then does not have an Azure registry combo box.

When using the 'Add'->'Container Orchestrator Support' option on the webapi application, the resulting Service Fabric Container Application attempts to retrieve and assemble the container inside VS2017. I suggest that the two mechanisms need to converge by making the behavior controllable by the user/programmer.

I scoured all the .sln, .csproj  and .xml files to see how to resolve this but it seems hardcoded.

**Comment by BigMorty** [comment]
The Service Fabric publish dialog in Visual Studio currently only works with Azure Container Registry (ACR), there are currently no plans to update this to work with on-prem registries. You will need to either use ACR to push your images to if you want to use the publish dialog. Other options would be command line tools or use a CI/CD pipeline to build and push your images, and then deploy the app to Service Fabric.
