### ISSUE TITLE
Stateful Service Replication Falling Behind

### ISSUE THREAD

**Issue by MattDarg** [Azure/service-fabric-issues#1510]
Hi,

We are using an on-premise cluster with a stateful service and Reliable dictionary that we're using as a simple distributed cache.  The cluster is spread geographically, with 2 in the same region, and then 1 remote (transatlantic).  

I've increased the MaxReplicationMessageSize int the ReplicatorConfig for the svc to 1342177280 and we're writing about 10 values of about 25 MB in to the primary at once (separate transactions), plus some associated metadata.  There's also some smaller updates that go on.

We're not doing these updates at a high rate (say 1 set of these 10 every 5 minutes), but if we do a few of these then the replication to the "remote" node falls behind, and eventually we see the replication queue fill up and start getting time outs (which I've also increased):

System.TimeoutException: Timed out waiting for replication; [...], timeout=120000ms, txn=132016955233804028
   at System.Fabric.Store.TStore`5.<AddOrUpdateAsync>d__227.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.Collections.DistributedDictionary`2.<AddOrUpdateAsync>d__98.MoveNext()

The replication queue is full and in the event log I can see:

EventName: StatefulReplicaNewHealthReport Category: Health Partition={8fe0f872-989e-4e69-b21a-35a8cdb62073} StatefulReplica=132011688830051098 InstanceId=132011688830051103 SourceId=System.Replicator Property=PrimaryReplicationQueueStatus HealthState=Warning TTL=922337203685477ms SequenceNumber=132016949467654179 Description='Primary Replication Queue Usage of 85% has reached/exceeded the threshold 80%. First Replication Operation = 451262, Last Replication Operation = 458288
Detailed Progress Information:

Active Configuration Replicas: (
8fe0f872-989e-4e69-b21a-35a8cdb62073-132011688830051098;1dffb569-01f1-4e53-8fa8-e0d7ff011da0->XXREMOTEXX:20004/8fe0f872-989e-4e69-b21a-35a8cdb62073-132011688830051097;9516d838-97a4-44e9-9767-12460cfe74e1:ef279979888d0bf4a2fb0e575b70a30: REPL:	NotReceivedCount=7026	ReceivedAndNotAppliedCount=0	Receive.ACK=451261(Avg 383693ms)	Apply.ACK=451261(Avg 383693ms)	SWS=2048	CompletedLSN=451261	 acksSkipped=0 IsIdleFaultedDueToSlowProgress=false IsActiveFaultedDueToSlowProgress=false
 
8fe0f872-989e-4e69-b21a-35a8cdb62073-132011688830051098;1dffb569-01f1-4e53-8fa8-e0d7ff011da0->XXNEARXX:20001/8fe0f872-989e-4e69-b21a-35a8cdb62073-132011688621474515;780f03cc-ffae-4e30-82c4-cfe7adda2e1a:4785a37cef372cdbf53e9d1bb66b84e7: REPL:	NotReceivedCount=0	ReceivedAndNotAppliedCount=0	Receive.ACK=458287(Avg 236ms)	Apply.ACK=458287(Avg 1026ms)	SWS=8192	CompletedLSN=451261	 acksSkipped=0 IsIdleFaultedDueToSlowProgress=false IsActiveFaultedDueToSlowProgress=false
)
Idle Replicas: ()
Previous Configuration Replicas: ()' RemoveWhenExpired=false SourceUTCTimestamp=‎2019‎-‎05‎-‎07T09:29:06.765417900Z

On the primary node there are alot of these errors (practically continuous):

XXNEARXX:20084-XXREMOTEXX:20068/09c063a4-8d2c-43d2-a8f5-f80dc56a1eec-132016958196709381;b746c3ae-44f5-43bc-b7a5-628d00165cc9: dropping message {9299c299-0f92-4c79-ae89-54d75f553e3b}:134632, Actor = Empty, Action = 'ReplicationOperation'

Is there a required link latency we need to ensure messages aren't being dropped and retried alot? Is there something we can check to see where the bottle neck is?  The infrastructure team believe that the transatlantic link has plenty of capacity.

Kind Regards,

Matthew

**Comment by tyms** [comment]
Hi Matthew,

You're likely running into a known issue in versions prior to 6.5. Once you start getting message expiration and retries, the retries can outcompete legitimate traffic due to the way the send windows are calculated. 6.5 should hopefully be releasing soon, so you can upgrade and pick up the improvements then.

In the meantime, you may be able to tweak your replicator settings a bit to somewhat alleviate this. The replicator RetryInterval is by default 5 seconds, which might not be enough for a transatlantic round-trip of all the data you queue up at once. You can do some simple testing on your end to see what you can expect for the round-trip (e.g. measure transferring a ~25MB file between the machines one way, and a few KB back) and add a healthy margin on top. Or you can simply test out a few higher values for the retry interval (say, 10 seconds) and see if it improves things. This shouldn't really have a downside unless the network connections between these nodes are prone to being reset/broken (the valid case where retries are needed). 

-Tyler

**Comment by MattDarg** [comment]
Thanks Tyler, that's very useful.  We'll give the workaround you suggest a try.

**Comment by TheAzureGuy** [comment]
@tyms please can you clarify whether you were rereferring to SF cluster version or SF SDK version when pointing out the possible bug in 6.5? What is this version number for?

**Comment by tyms** [comment]
@TheAzureGuy yes, I was referring to the SF cluster version, apologies for not making that explicit.

@MattDarg have you had another occurrence of this since the 6.5 rollout (which began mid-June)?

**Comment by tyms** [comment]
Closing this one as we haven't heard back - please reopen or create a new issue if this reoccurs.

**Comment by MattDarg** [comment]
@tyms Hi Tyler, the company I was working with mitigated the issue a different way in the end.  Good to know that the issue has been resolved in 6.5 though, thanks.

**Comment by PTC-JoshuaMatthews** [comment]
@MattDarg  can you share how you increased the replication timeout? Not seeing any way to do that in the replicator config settings.
