### ISSUE TITLE
Prevent services from occupying same host

### ISSUE THREAD

**Issue by marcjonesuk** [Azure/service-fabric-issues#1511]
Hi - I have a stateless service that is scaled out to 2 instances. Service Fabric prevents these instances for running on a single host at the moment. I'd like to supply different config (environment variables) to each instance so I am considering splitting it into 2 individual services to support this. When I do this, the 2 instances gain the ability to run on a single host, which is undesired. 

Is there any way to achieve what I want? i.e. different configuration but maintain the distribution across hosts/UDs.

**Comment by aljo-microsoft** [comment]
https://docs.microsoft.com/azure/service-fabric/service-fabric-cluster-resource-manager-configure-services#placement-constraints

Please reopen if question is not answered.
