### ISSUE TITLE
Unable to Upgrade Cluster Configuration at All: Start-ServiceFabricClusterConfigurationUpgrade incorrectly identifies an incompatible authentication type change

### ISSUE THREAD

**Issue by JustinKaffenberger** [Azure/service-fabric-issues#1512]
I wasn't sure where to post this issue, so here it is:

I've been learning how to stand up a cluster with X509 authentication, and encountered an issue with the `Start-ServiceFabricClusterConfigurationUpgrade` incorrectly identifying an incompatible authentication type change. The reality is, I am not changing the authentication type, but merely trying to update the `ApplicationPorts.PortRange`. I will go over my reproduction steps here:

1. Create a valid cluster following the template `.\Microsoft.Azure.ServiceFabric.WindowsServer.6.4.654.9590\ClusterConfig.X509.MultiMachine.json` that is provided with the on-premise install package.
2. Deploy a small Service Fabric application to validate that the install is stable and correct. In my case I am able to use a client certificate to access my remote cluster and deploy my application. The application successfully deploys.
3. I created a Powershell script to automate the process of pulling down the existing configuration, modifying the ports and the version, and then invoking the  `Start-ServiceFabricClusterConfigurationUpgrade` cmdlet.

```
# This code assumes we are executing out of the
# Microsoft.Azure.ServiceFabric.WindowsServer.6.4.654.9590 
# installation package folder

# Load the previous configuration from the cluster into an in-memory JSON object
# that we can modify.
$previousConfig = (Join-Path $env:TEMP ([string][System.Guid]::NewGuid() + ".json"))
Get-ServiceFabricClusterConfiguration | Out-File $previousConfig
$scratchJson = Get-Content $previousConfig | ConvertFrom-Json

# Modify the JSON as needed. In this case I am just modifying the end port.
$scratchJson.Properties.NodeTypes[0].ApplicationPorts.EndPort = 22048 # This is the end port I wanted to use
$scratchJson.ClusterConfigurationVersion = "1.0.1"

# Export the modified in-memory JSON object to a file
$newConfig = (Join-Path $env:TEMP ([string][System.Guid]::NewGuid() + ".json"))
$scratchJson | ConvertTo-Json -Depth 32 | Out-File $newConfig 

# Run the TestConfiguration cmdlet in the installer folder. I am seeing the following:
#
# Trace folder already exists. Traces will be written to existing trace folder: C:\Users\Administrator\Downloads\Microsoft.Azure.ServiceFabric.WindowsServer.6.4.654.9590\DeploymentTraces
# Running Best Practices Analyzer...
# Running Best Practices Upgrade Analyzer. Please make sure you are validating against the current cluster json config in your cluster. Cluster configuration in the system may change after you add or remove node which means the original cluster json config can't represent the cluster state anymore. You can get the latest configuration by Get-ServiceFabricClusterConfiguration in Powershell.
# Best Practices Analyzer completed successfully.
# LocalAdminPrivilege        : True
# IsJsonValid                : True
# IsCabValid                 :
# RequiredPortsOpen          : True
# RemoteRegistryAvailable    : True
# FirewallAvailable          : True
# RpcCheckPassed             : True
# NoDomainController         : True
# NoConflictingInstallations : True
# FabricInstallable          :
# DataDrivesAvailable        : True
# DrivesEnoughAvailableSpace : True
# IsAllOrNoneIOTDevice       : True
# DotNetExeInPath            : True
# Passed                     : True
#
.\TestConfiguration.ps1 -ClusterConfigFilePath $newConfig -OldClusterConfigFilePath $previousConfig -Verbose

Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath $newConfig
```

The result of this script is the following exception:

```
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: Authentication type cannot be changed from unsecured to Windows.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath $ne ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa
   ...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterC
   onfigurationUpgrade
```

At no point is my cluster unsecured, and the new config is not set to use Windows authentication, so I'm assuming this is a bug. Any help would be appreciated.

**Comment by JustinKaffenberger** [comment]
Updated the title to reflect the severity of the issue.

**Comment by JustinKaffenberger** [comment]
Nobody from Microsoft has any comments on this? I can't upgrade the configuration of an on-premise cluster that is using X509 authentication. Period. How am I supposed to use Service Fabric in production if huge issues like this are not even acknowledged?

**Comment by jkochhar** [comment]
You should do a diff between the original json and the one you are getting back via your script (via Get-ServiceFabricClusterConfiguration) and see if there are additional changes. The auto generated json may have added some WindowsIdentities fields which you may have to remove to update the config.

**Comment by JustinKaffenberger** [comment]
Thanks for the insight @jkochhar. Oddly enough, right before you responded, out of frustration I've been digging into the JSON returned from the `Get-ServiceFabricClusterConfiguration`, and I noticed the empty `WindowsIdentities` element. When I delete this element, I no longer get the exception that I originally referenced. However, now when I run `Start-ServiceFabricClusterConfigurationUpgrade`, even though no errors are thrown, subsequent calls to `Get-ServiceFabricClusterConfigurationUpgradeStatus` do not indicate that any attempt to perform the upgrade was performed, and the configuration version on my cluster remains as:

```
UpgradeState ProgressStatus ConfigVersion Details                                                                                                                                                                                                                                                                                                                          ------------ -------------- ------------- -------                                                                                                                                                                                                                                                                                                               RollingForwardCompleted              0 1.0.0                
```

**Comment by jkochhar** [comment]
Are you changing the version number of the json config? I think there were some checks if nothing changes it just no-ops so you may want to tweak some setting and see if that makes it trigger. If not, feel free to ping me and I can take a look at the logs.

**Comment by JustinKaffenberger** [comment]
@jkochhar, I've tried updating `ApplicationPorts` for an existing `NodeType`, as well as adding a new `NodeType` altogether. Both have the same result, no errors, but no evidence of a configuration change ever starting on the cluster.

**Comment by jkochhar** [comment]
Hmm may be something is failing silently. Are you able to open a support case so I can look at the logs.
Am assuming you tried the Test-ServiceFabricConfiguration and that didn’t tell anything.

**Comment by JustinKaffenberger** [comment]
I just created the support request and linked this issue. As for `Test-ServiceFabricConfiguration`, as long as I remove all reference to the `WindowsIdentities` element in the configurations being tested, the cmdlet succeeds with no issue.

**Comment by JustinKaffenberger** [comment]
Although I'm no longer getting the exception, the upgrade is a no-op, with no informative output as to what could be happening. I created [this issue](https://github.com/Azure/service-fabric-issues/issues/1572) that describes the no-op that is occurring after removing the `WindowsIdentities` element.

**Comment by jkochhar** [comment]
@ejccomptech Are you able to collect the cluster logs and share? 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server#get-support-for-the-service-fabric-for-windows-server-package

**Comment by ejccomptech** [comment]
> @ejccomptech Are you able to collect the cluster logs and share?
> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server#get-support-for-the-service-fabric-for-windows-server-package

I was able to resolve mine by adding the old certificates which I had removed. Thank you.

**Comment by JustinKaffenberger** [comment]
After a bunch of time fiddling with different configurations, I've found the root cause of the problem to be the existence of duplicate thumbprints in the `Thumbprint` and `ThumbprintSecondary` JSON fields. In my naivety I assumed that was a valid configuration, at least until I needed to do a certificate rollover. 

By re-creating the cluster with only `Thumprint` populated I was able to once again upgrade the cluster configuration.

**Comment by davebally** [comment]
FWIW we've had this issue on an unsecured dev cluster.  The security attribute had some rouge entries of "CertificateInformation" and "WindowsIndentities" .  We removed the entire security attribute and then we could update fine.  Additionally, It seems that the latest SF update "7.0.457.9590" correctly outputs the JSON so they don't need to be removed.

**Comment by jkochhar** [comment]
@davebally Thanks for confirming the 7.0 is working better. @maburlik made the change for it.
