### ISSUE TITLE
Using MSBuild to package Service Fabric app including .NET Core projects fails

### ISSUE THREAD

**Issue by htuomola** [Azure/service-fabric-issues#152]
As a background, I'm trying to setup continuous deployment for a Service Fabric application as explained in [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-set-up-continuous-integration), using VSTS Service Fabric Application build template. This issue is not limited to VSTS though, as the operation also fails on my dev machine.

I have a solution which contains the following projects:
- HealthMonitor.Services: SF application project
- HealthMonitor.Web: ASP.NET core web application, running on full .NET
- HealthMonitor.Core: .NET core class library
- HealthMonitor.Agent.FabricHost: .NET core stateless service, running on full .NET

The solution works fine on Visual Studio and publishing it to local & Azure-hosted cluster works without problems. I tried building it in VSTS but it fails in the "Build solution **\*.sfproj" step, with error:
```
"C:\code\HealthMonitor\src\HealthMonitor.Services\HealthMonitor.Services.sfproj" (Package target) (1) ->
"C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\HealthMonitor.Agent.FabricHost.xproj" (default target) (2:4) ->
"C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (default target) (3:7) ->
"C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (CIPublish target) (3:8) ->
(GatherAllFilesToPublish target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): 
	error : **Can not find runtime target for framework '.NETStandard,Version=v1.2' compatible with one of the target runtimes: 'win10-x64, w in81-x64, win8-x64, win7-x64'. Possible causes:** [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): 
	error : 1. The project has not been restored or restore failed - run `dotnet restore` [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): 
	error : 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): 
	error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
```

Looking at the output, the last command which it's running & which fails is:
*C:\Program Files\dotnet\dotnet.exe publish "C:\code\HealthMonitor\src\HealthMonitor.Core" --output "C:\Users\HenriTuomola\AppData\Local\Temp\PublishTemp\HealthMonitor.Core69" --configuration Release --no-build*

If I run that command independently it fails with same error. Actually I think the error is valid, I don't see a reason why it's trying to publish the *class library* project. I'm not sure if it's the same thing but running Package of the Service Fabric project in VS 2015 succeeds also and from the logs I can see that it doesn't try to publish the .NET core class library project.

I'm not quite sure if it's more of a .NET core issue but the overall scenario fails, nevertheless.

**Comment by MikkelHegn** [comment]
Hi @htuomola Dotnet Publish means creating an output of the class library and all of it's dependencies "Packs the application and all of its dependencies into a folder getting it ready for publishing" - https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish - not publish to Service Fabric. 

Take a look at this SO: http://stackoverflow.com/questions/37590604/can-not-find-runtime-target-for-framework-netcoreapp-v1-compatible-with-one-of - Do you have a runtime specified in the .xproj files for the Class Library?

**Comment by MikkelHegn** [comment]
Sorry - didn't mean to close - just hit the wrong button :-)

**Comment by htuomola** [comment]
Yes I understood that, maybe I didn't describe the problem well enough. 
I'm just trying to package the Service Fabric application for deployment and the MSBuild *Package* target (which I apparently should be using) fails. I'm not calling "dotnet publish" but MSBuild seems to call it. As I said, publishing the same project from Visual Studio works so there seems to be (yet again) a difference in MsBuild and VS behavior.

Here's the MSBuild command and the end of the output, in case it helps.
```
> msbuild.exe "src\HealthMonitor.Services\HealthMonitor.Services.sfproj" /nologo /nr:false  /t:Package /p:PackageLocation=c:\temp\sfbuildout /p:platform="x64" /p:configuration="Release" /p:VisualStudioVersion="14.0"
[.....]
FixUpServiceFabricApplicationManifest:
  "C:\Program Files\Microsoft SDKs\Service Fabric\\Tools\AppManifestCleanupUtil\AppManifestCleanupUtil.exe" /amp:"C:\code\HealthMonitor\src\HealthMonitor.Services\ApplicationPackageRoot\ApplicationManifest.xml" /smpl:"C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\PackageRoot\ServiceManifest.xml;C:\code\HealthMonitor\src\HealthMoni
  tor.Web\PackageRoot\ServiceManifest.xml" /appparamfiles:"C:\code\HealthMonitor\src\HealthMonitor.Services\ApplicationParameters\Cloud.xml;C:\code\HealthMonitor\src\HealthMonitor.Services\ApplicationParameters\Local.1Node.xml;C:\code\HealthMonitor\src\HealthMonitor.Services\ApplicationParameters\Local.5Node.xml"
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,71)" does not exist in the project, and will be ignored.
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,71)" does not exist in the project, and will be ignored.
Project "C:\code\HealthMonitor\src\HealthMonitor.Services\HealthMonitor.Services.sfproj" (1) is building "C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\HealthMonitor.Agent.FabricHost.xproj" (2:4) on node 1 (default targets).
Project "C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\HealthMonitor.Agent.FabricHost.xproj" (2:4) is building "C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (3:7) on node 1 (default targets).
CoreCompile:
  C:\Program Files\dotnet\dotnet.exe build "C:\code\HealthMonitor\src\HealthMonitor.Core" --configuration Release --no-dependencies
  Project HealthMonitor.Core (.NETStandard,Version=v1.2) was previously compiled. Skipping compilation.
Project "C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (3:7) is building "C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (3:8) on node 1 (CIPublish target(s)).
GatherAllFilesToPublish:
  Environment variables:
  Path=[.....]
  C:\Program Files\dotnet\dotnet.exe publish "C:\code\HealthMonitor\src\HealthMonitor.Core" --output "C:\Users\HenriTuomola\AppData\Local\Temp\PublishTemp\HealthMonitor.Core69" --configuration Release --no-build
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : Can not find runtime target for framework '.NETStandard,Version=v1.2' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes: [C:\code\H ealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 1. The project has not been resto red or restore failed - run `dotnet restore` [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 2. The project does not list oneof 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
Done Building Project "C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (CIPublish target(s)) -- FAILED.

Done Building Project "C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (default targets) -- FAILED.

Done Building Project "C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\HealthMonitor.Agent.FabricHost.xproj" (default targets) -- FAILED.

Done Building Project "C:\code\HealthMonitor\src\HealthMonitor.Services\HealthMonitor.Services.sfproj" (Package target(s)) -- FAILED.

Build FAILED.

"C:\code\HealthMonitor\src\HealthMonitor.Services\HealthMonitor.Services.sfproj" (Package target) (1) ->
"C:\code\HealthMonitor\src\HealthMonitor.Agent.FabricHost\HealthMonitor.Agent.FabricHost.xproj" (default target) (2:4) ->
"C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (default target) (3:7) ->
"C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj" (CIPublish target) (3:8) ->
(GatherAllFilesToPublish target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : Can not find runtime target for framework '.NETStandard,Version=v1.2' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes: [C:\code \HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 1. The project has not been restored or restore failed - run `dotnet restore` [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]

    0 Warning(s)
    4 Error(s)
```

**Comment by MikkelHegn** [comment]
Are you looking for help to resolve this - or asking a specific question? I'm trying to understand as well :-)

The /t:Package target includes building the project, which causes publishing dotnet core apps (running dotnet publish - I know the terminology kind of collapses here), but please bear over with us.

There is no obvious reason why the behavior should be any different.

Are you runnig both commands on the same machine? Can you please check the .NET Core tooling version?

According to this error:
> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 2. The project does not list oneof 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section. [C:\code\HealthMonitor\src\HealthMonitor.Core\HealthMonitor.Core.xproj]

Is this part in you xproj file? Will it work if you add this to the xproj file?

**Comment by htuomola** [comment]
Yes I'm trying to resolve this :). Or rather, I'm trying to setup a continuous delivery setup of a Service Fabric application like [instructed here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-set-up-continuous-integration). I haven't modified the Build template except for adding "dotnet restore". Furthermore, I'm able to deploy the app from VS to local & Azure cluster just fine so I assumed that the solution itself is correct and this is some tooling issue.

If I add for example this to project.json of HealthMonitor.Core (which is a class library):
```
"runtimes": {
    "win7-x64":  {} 
  }
```
`dotnet restore` fails with bunch of errors of kind:
    System.Linq 4.1.0 provides a compile-time reference assembly for System.Linq on .NETStandard,Version=v1.2, but there is no run-time assembly compatible with win7-x64.
Error is similar for example with win*10*-x64

I have .NET Core version ".NET Core 1.0.1 - SDK Preview 2-003131."

Is the MsBuild Package target supposed to be same functionality as Visual Studio "Package" context menu action of the Service Fabric project? 
The latter one works fine and from the output I can see that it's only running `dotnet publish` for HealthMonitor.Agent.FabricHost and HealthMonitor.Web - not on HealthMonitor.Core as MsBuild is doing.

**Comment by MikkelHegn** [comment]
Adding @ravipal 
I just tried a repo and do see the same difference you identified (that dotnet publish is being run on the class library when using msbuild, but not when packaging in VS).

However, my project doesn't fail, so I guess we have two things to consider:

1. Why is there a difference in executing packaing through VS and MSBuild.exe
>@ravipal to look in to this.
2. Why is your dotnet publish failing in your CI?
> Can you share your project.json file?

**Comment by htuomola** [comment]
Hi, sorry for the delay - I already wrote a reply a few days ago but apparently failed to post it eventually. Anyway, [here](https://1drv.ms/u/s!AqIZOh4P3_LPm6Z7t8geV8pFCLaQPA)'s a full, minimal repro of the issue.

Did your setup include a ASP.NET Core (full .NET) application project *and* a .NET Core class library referenced by it? You can find the project.json files from the attachment. I have done very minimal modifications to those so they are very close to "File -> New Project" scenario.

Using the same command as VSTS Task is using (apart from msbuild logger configs etc.): `msbuild.exe "SfMsBuildRepro.Fabric\SfMsbuildRepro.Fabric.sfproj" /nologo /nr:false  /t:Package /p:PackageLocation=c:\temp\sfbuildout /p:platform="x64" /p:configuration="Release" /p:VisualStudioVersion="14.0"` it fails with the same errors.
Running VS `Package` command for the application works fine.

**Comment by dbreshears** [comment]
Closing as appears this issue has been fixed as I no longer repro when packaging .sfproj via command line with a .NETStandard Library reference from the ASP.NET core service project.
