### ISSUE TITLE
Current Upgrade State: RollingForwardInProgress

### ISSUE THREAD

**Issue by jrmcdona** [Azure/service-fabric-issues#1521]
Our SF cluster hosted in Azure has been stuck for sometime for a few hours.

Here is  pic from SF explorer.  Should I just kill the deployment and restart?

![image](https://user-images.githubusercontent.com/4327773/58287509-cc608000-7d76-11e9-94b9-a1b3f3c9f3d9.png)

**Comment by jrmcdona** [comment]
More info:

'System.FM' reported Warning for property 'State'.
Partition reconfiguration is taking longer than expected.
fabric:/Microsoft.AmbassadorsPlatform/UserActorService 3 3 a8e079ea-aaac-44f7-8614-2ae1fb29223d
  P/S Ready _amb_2 132029831095931815
  S/P Ready _amb_0 132031093858439969
  S/S Ready _amb_3 132029854880446618

For more information see: https://aka.ms/sfhealth

**Comment by masnider** [comment]
Try following the guide here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-troubleshooting.

That error you pasted usually means that the service is not responding to the lifecycle APIs that SF is trying to call on it. At a lower level or from your own application level logs you should be able to see other errors or warnings indicating what API call specifically is stuck or not behaving correctly. 

The most common cause is that a service is not respecting the cancellation token passed into RunAsync.
