### ISSUE TITLE
Unable to update Cert - FABRIC_E_INVALID_X509_THUMBPRINT

### ISSUE THREAD

**Issue by gperrego** [Azure/service-fabric-issues#1529]
1. We had a public cert expire on Saturday, 
2. Friday we installed the new cert on the server.
3. Granted access to network service via powershell.  
4. Redeployed our Gateway application with the updated thumbprint.
     The gateway shows the updated thumbprint in on the details tab in SFX
6. Deployment fails with FABRIC_E_INVALID_X509_THUMBPRINT.  

When looking at the permissions via mmc/certificates console I see Network Service has full access to the cert.

When using netsh http show sslcert I do not see that the cert if bound to any port.  I'm assuming this is because the app just isn't getting there yet. (my other environment for this cluster shows the certs are bound, this one does not)

I've tried removing the spaces from the cert, that doesn't work.  

Here is the powershell i'm using to set the perms:
```

$serviceAccount = "NETWORK SERVICE"

$cert = Get-ChildItem -Path cert:\LocalMachine\My | Where-Object -FilterScript { $PSItem.ThumbPrint -eq $pfxThumbPrint; }

# Specify the user, the permissions and the permission type
$permission = "$($serviceAccount)","FullControl","Allow"
$accessRule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule -ArgumentList $permission

# Location of the machine related keys
$keyPath = Join-Path -Path $env:ProgramData -ChildPath "\Microsoft\Crypto\RSA\MachineKeys"
$keyName = $cert.PrivateKey.CspKeyContainerInfo.UniqueKeyContainerName
$keyFullPath = Join-Path -Path $keyPath -ChildPath $keyName

# Get the current acl of the private key
$acl = (Get-Item $keyFullPath).GetAccessControl('Access')

# Add the new ace to the acl of the private key
$acl.SetAccessRule($accessRule)

# Write back the new acl
Set-Acl -Path $keyFullPath -AclObject $acl -ErrorAction Stop

# Observe the access rights currently assigned to this certificate.
get-acl $keyFullPath| fl

```
This is affecting my vendor testing.... argh.

**Comment by gperrego** [comment]
I've tried removing and adding back in the spaces in the thumbprint to see if there were some special characters copied from the MMC GUI... to no avail.  

Now I've tried to re deploy my old pipeline with the expired cert.  This was last deployed 2 months ago.  This also fails.  This has me thinking it is not something related to the thumbprint.  It seems like SF is having an issue with changing the cert.  I'm tempted to try to bind the cert to the static port manually using netsh, just to see if it works.

**Comment by gperrego** [comment]
ok, getting a bit closer.  In the event viewer i see "Thumbprint::Initialize: Failed to parse ‎7b b1 fa 94 a4 9b 78 d6 59 bb eb 38 39 05 ba 8b 48 b7 bf a8 as certificate thumbprint, the format should be '2855e9bbedc65d3dc82c7335d1ec074586b09006' or '28 55 e9 bb ed c6 5d 3d c8 2c 73 35 d1 ec 07 45 86 b0 90 06'"

The thing is my format matches the required format.  Unless there is a need for the single quotes?   I can try removing the spaces yet again but... is this possibly a known issue?  My cluster is version 6.4.637.9590

**Comment by gperrego** [comment]
removed the spaces, redeployed... same thing:
Thumbprint::Initialize: Failed to parse ‎7bb1fa94a49b78d659bbeb383905ba8b48b7bfa8 as certificate thumbprint, the format should be '2855e9bbedc65d3dc82c7335d1ec074586b09006' or '28 55 e9 bb ed c6 5d 3d c8 2c 73 35 d1 ec 07 45 86 b0 90 06'

**Comment by gperrego** [comment]
for giggles i added single quotes to the parameter file:  Thumbprint::Initialize: Failed to parse ‎'7b b1 fa 94 a4 9b 78 d6 59 bb eb 38 39 05 ba 8b 48 b7 bf a8' as certificate thumbprint, the format should be '2855e9bbedc65d3dc82c7335d1ec074586b09006' or '28 55 e9 bb ed c6 5d 3d c8 2c 73 35 d1 ec 07 45 86 b0 90 06'  still no dice.  

FYI i have hand typed in this value based on https://social.msdn.microsoft.com/Forums/en-US/33728367-8759-46b1-b9ac-a1280157ec7b/problem-with-https-endpoint-thumbprintinitialize-failed-to-parse

**Comment by gperrego** [comment]
Looks like it doesn't like the refresh, ConfigurePortCertificate: httpsPort=41200, certStoreName MY, certfindvalue '7bb1fa94a49b78d659bbeb383905ba8b48b7bfa8', error AlreadyExists

**Comment by gperrego** [comment]
So I've fixed it but... it may be a bug.  When we deploy an application with a new ssl cert it should delete the existing HTTP binding so it can rebind.  It seems like one of the previous deployments had bound the cert but it wasn't working.  So first I unprovisioned my previous types to clean things up.  Then I executed the netsh commands below to delete the http port binding and then I redeployed. 

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>netsh http show sslcert ipport=0.0.0.0:41200

SSL Certificate bindings:
-------------------------

    IP:port                      : 0.0.0.0:41200
    Certificate Hash             : 7bb1fa94a49b78d659bbeb383905ba8b48b7bfa8
    Application ID               : {e6e4fd62-36d6-4ac1-828e-a3cb243f98ad}
    Certificate Store Name       : MY
    Verify Client Certificate Revocation : Disabled
    Verify Revocation Using Cached Client Certificate Only : Disabled
    Usage Check                  : Enabled
    Revocation Freshness Time    : 0
    URL Retrieval Timeout        : 0
    Ctl Identifier               : (null)
    Ctl Store Name               : (null)
    DS Mapper Usage              : Disabled
    Negotiate Client Certificate : Disabled
    Reject Connections           : Disabled
    Disable HTTP2                : Not Set



C:\Windows\system32>netsh http delete sslcert ipport=0.0.0.0:41200

SSL Certificate successfully deleted
```

**Comment by masnider** [comment]
@dragav / @hans-olav can one of you take a look here and see if something might be wrong?

**Comment by dragav** [comment]
SF will clear the binding on a failed app activation, or on deactivation. An app upgrade would trigger a deactivation, and so the ssl binding is cleared first. Please see below examples of traces confirming clearing.

In your case, it seems that the TP string contained invalid characters; if you have an older Windows version and you copied the TP from the certmgmt.msc console, there is an invisible leading character - i'd suggest copying the TP from the second character on, and typing in the first character manually.


2020-2-6 18:00:05.803 | Hosting.ProcessActivationManager | 3740 | 6604 | Processing configure request for port certificate for port: 8564, certificatefindvalue F13........468F cleanup true
-- | -- | -- | -- | --

2020-2-6 18:00:05.803 | Hosting.HttpEndpointSecurityProvider | 3740 | 6604 | CleanupPortCertificate: httpsPort=8564, certStoreName MY, thumbprint F13.......468F
