### ISSUE TITLE
S_FSSUserffffffff and P_FSSUserffffffff

### ISSUE THREAD

**Issue by tully32** [Azure/service-fabric-issues#153]
There's 0 documentation on either user. Why am I seeing security audit errors for these users?

An account failed to log on.

Subject:
	Security ID:		NETWORK SERVICE
	Account Name:		redacted
	Account Domain:		redacted
	Logon ID:		0x3E4

Logon Type:			8

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		S_FSSUserffffffff
	Account Domain:		redacted

Failure Information:
	Failure Reason:		The user has not been granted the requested logon type at this machine.
	Status:			0xC000015B
	Sub Status:		0x0

Process Information:
	Caller Process ID:	0x1d08
	Caller Process Name:	C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricGateway.exe

Network Information:
	Workstation Name:	redacted
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	Negotiate
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

**Comment by oanapl** [comment]
We are creating those users based on the configuration you have for ImageStore for NTLM authentication. They are used to ACL shares used by ImageStore to copy files securely between nodes. So, if your cluster has FileStoreService\PrimaryAccountType set to LocalUser (similarly for SecondaryAccountType), we create them and generate password using the certificate information in the cluster manifest for configuring primary and secondary accounts.

@RajeetN, any idea why the security audit for these users?

**Comment by mattmazzola** [comment]
Disregarding the need for the users, could the they be named something more semantic / readable like ServiceFabric_FileCopyUser so it's less suspicious?

**Comment by oanapl** [comment]
Renaming is cumbersome because of compatibility reasons.
We named them such to have all the information we need: they are meant to represent Primary FileStoreServiceUser and Secondary FileStoreServiceUser. In general, Service Fabric users should not worry about them, so we didn't worry about making the user name more readable.

**Comment by strtdusty** [comment]
Log analytics continually flags these users and shows failed login attempts by them. I even see incidents with them showing under "Logons with a clear text password"

**Comment by oanapl** [comment]
@strtdusty , we have plans to remove these users in the future, but it will take time to change our implementation. If this is a painful issue for you, please open a different issue for tracking and we can think of ways to help with it short term. That will also help us raise priority for the long term fix.
