### ISSUE TITLE
FABRIC_E_FILE_NOT_FOUND when doing a differential package upgrade and using the UnregisterUnusedApplicationVersionsAfterUpgrade option

### ISSUE THREAD

**Issue by garrmark** [Azure/service-fabric-issues#1535]
I'm running an on-prem 3 node windows cluster version 6.4.637.9590

My automated build system is first creating an application package with 11 services in it.  I then run a port of the package versioning task https://github.com/aelij/vsts-service-fabric to remove any code packages that haven't changed since the last build.

I do a `Deploy-FabricApplication.ps1 -ApplicationPackagePath MyPath -PublishProfileFile MyProfile -UnregisterUnusedApplicationVersionsAfterUpgrade $True` to deploy the package.

For code packages that have been removed, I see an error trying to load the code package from the previous version:

> 'System.Hosting' reported Error for property 'Download:1.0:1.10:019e3a8b-05e0-4eba-8886-7d51f2c49811'.
There was an error during download. Failed to download 'Store\OrionType\CustomerCommunicationsServicePkg.Manifest.1.0.0+327.xml.checksum' from ImageStore. Error 'FABRIC_E_FILE_NOT_FOUND'. Check if the file or folder is present in ImageStore by using 'Get-ServiceFabricImageStoreContent -RemoteRelativePath Store\OrionType\CustomerCommunicationsServicePkg.Manifest.1.0.0+327.xml.checksum'.

In this case it's looking for 1.0.0+327 which has been removed and the current type is 1.0.0+328

If I change -UnregisterUnusedApplicationVersionsAfterUpgrade $True to $False and manually remove the old 327 package, I will not see the errors.

I'm guessing there is some sort of timing issue here.  Please let me know what other info I can provide and how to provide it, thanks.

**Comment by wasabii** [comment]
I also periodically see this. I end up having to reregister the old version.

**Comment by garrmark** [comment]
I put in a support ticket and we worked through this issue, the vsts-service-fabric scripts were updating the version of the service even when all of the packages in the service were removed.  This appears to have been my issue.  I changed the logic to use the combined hash of the code and config for the service version numbers instead.
