### ISSUE TITLE
Is it available for features similar to that of Orleans Grain Services?

### ISSUE THREAD

**Issue by buzzers** [Azure/service-fabric-issues#1540]
I'd like to know if service fabric offers grain services and pub/sub features similar to those in Orleans.

This is necessary because my program relies on configuration data that is stored in another reliable stateful service.
When this data needs to be changed, the interface of the service is requested and the configuration data is modified, and the service then needs to notify all service processes in the cluster to update the configuration.

So I need to permanently have a service within all service processes to listen for change events and get a new configuration. 

But I read the documentation and didn't find these features.

**Comment by MedAnd** [comment]
Orleans can be hosted on Service Fabric. There are currently two points of integration with Service Fabric, see [Service Fabric Hosting](https://dotnet.github.io/orleans/1.5/Documentation/Deployment-and-Operations/Service-Fabric.html) for details.

**Comment by buzzers** [comment]
OK,thanks.
