### ISSUE TITLE
Service Fabric across Availability Zones

### ISSUE THREAD

**Issue by gdinak** [Azure/service-fabric-issues#1554]
Hi! Quick clarification regarding Service Fabric across Availability Zones. One of the [recommendations for the topology](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cross-availability-zones#recommended-topology-for-primary-node-type-of-azure-service-fabric-clusters-spanning-across-availability-zones) is,

"Each Node Type should be mapped to its own virtual machine scale set located in different zones."

Is this to make sure the fault domain spans across multiple zones, or are there more benefits/reasons for this? Would this also prevent us from specifying the zone property as an array with a single VMSS, as described in this [documentation](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones#zone-redundant-scale-set-2)?

Thanks!

**Comment by raunakpandya** [comment]
This is just because of some current internal limitation
