### ISSUE TITLE
Testing a simple stateless service with FabricTransportServiceRemotingListener, throws an exception: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported)

### ISSUE THREAD

**Issue by abarberenaCPDS** [Azure/service-fabric-issues#1556]
Hi SF Team, Do you mind please taking a look to the following issue [Testing a simple stateless service with FabricTransportServiceRemotingListener, throws an exception: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported)](https://github.com/microsoft/service-fabric/issues/356) for code, SF versions and steps.

thx!

**Comment by masnider** [comment]
I'll close this one and we can follow up there.
