### ISSUE TITLE
Service Endpoint address is not displayed properly in SF explorer on Linux.

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#156]
Install the [Echo service](https://github.com/Azure-Samples/service-fabric-java-getting-started/tree/master/Services/EchoServer/EchoServer1.0) from the samples on a local development cluster.

Navigate to the service in SFexplorer.

Open the service instance node.

The endpoint address is a (base64) string, not an actual endpoint. I expected to see a URL. like 'http://localhost:8505/getMessage'

![image](https://cloud.githubusercontent.com/assets/12125836/22588482/4f449576-ea06-11e6-9273-00da5b206607.png)

**Comment by VipulM-MSFT** [comment]
Thank you for reporting let me follow up.

**Comment by CodeMartian** [comment]
We have fixed this bug in TP8, which is yet to be released to public.

**Comment by VipulM-MSFT** [comment]
This is a known issue that has been fixed. The fix will released with the upcoming Linux preview release.

**Comment by raunakpandya** [comment]
This has been fixed and will be available in the upcoming Linux release.

**Comment by mani-ramaswamy** [comment]
It is fixed with the latest releaese @ https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/21/release-of-sdk-preview-0-8-0-0-and-runtime-preview-5-5-0-2-for-linux/

**Comment by mani-ramaswamy** [comment]
#fixed
