### ISSUE TITLE
Add-AzServiceFabricClusterCertificate fails with Overprovisioning not allowed on Virtual Machine Scale Sets with Service Fabric extension.

### ISSUE THREAD

**Issue by mholo65** [Azure/service-fabric-issues#1577]
It's soon certificate rollover time, and when I tried adding a secondary cluster certificate using the [Add-AzServiceFabricClusterCertificate](https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/add-azservicefabricclustercertificate?view=azps-2.6.0) cmdlet I get the following error:

```
> Add-AzServiceFabricClusterCertificate -ResourceGroupName "<redacted>" -Name "<redacted>" -KeyVaultResouceGroupName "<redacted>" -KeyVaultName "<redacted>" -CertificateFile "<redacted>" -CertificatePassword $passwd
Add-AzServiceFabricClusterCertificate : Code: OperationNotAllowed, Message: Overprovisioning not allowed on Virtual
Machine Scale Sets with Service Fabric extension.
Details:
At line:1 char:1
+ Add-AzServiceFabricClusterCertificate -ResourceGroupName "ResourcesRg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzServiceFabricClusterCertificate], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricClusterCertificat
   e

WARNING: Exception while performing operation. Rollingback...
Add-AzServiceFabricClusterCertificate : Sequence contains no matching element
At line:1 char:1
+ Add-AzServiceFabricClusterCertificate -ResourceGroupName "ResourcesRg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzServiceFabricClusterCertificate], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricClusterCertificat
   e
```

I don't remember having the same issue last time I rolled over the cluster cert. Maybe related to #145 

//cc @ChackDan

**Comment by MikkelHegn** [comment]
Nothing in the cmdlet codepath changes the overprovision attribute of the VMSS. Try and check if for some reason your VMSS model has this set to true. If so, do a deployment to change it to false and retry the cert command.

**Comment by mholo65** [comment]
@MikkelHegn checked, and it's set to true. This is a quite old scale set (from 2016 IIRC). it might have been enabled by default then.

**Comment by mholo65** [comment]
After updating the VMSS and disabling overprovisioning, it's now possible to add secondary certificate.

In case someone else runs into this issue, this is what I used for disabling overprovisioning:
```
az vmss update --resource-group <resource group> --name <vmss name> --set overprovision=false 
```
