### ISSUE TITLE
Installing ServiceFabric SDK 3.4.676 returns error on Win10 1903

### ISSUE THREAD

**Issue by hmlam** [Azure/service-fabric-issues#1587]
I have one machine where I try to install ServiceFabric SDK (triggered from Viusal Studio 2019 -> WebApi installer as part of the csproj requires it) and it return an error messages without installing.

"Service Fabric product installed, but can not get installed product version.".

WebApi logs is attached.
[webpi.txt](https://github.com/Azure/service-fabric-issues/files/3752196/webpi.txt)

The error in the log suggests that ServiceFabricRuntime_6_5_CU5 install fails so I try to install that separately and I see the following error:

```
C:\WINDOWS\system32>"C:\Users\omitted\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_5_CU5\91D74EDB9EE7BB5DB10096FA7BB3F2F36C569934\MicrosoftServiceFabric.6.5.676.9590.exe" /AcceptEULA
10/21/2019 5:45:56 PM,Info,Installing... Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime.log
10/21/2019 5:45:56 PM,Error,Service Fabric product installed, but can not get installed product version.
10/21/2019 5:45:58 PM,Info,Cleaning temporary directory C:\Program Files\Microsoft Service Fabric.120qci3e.t4l
```
InstallFabricRuntime.log does not contain anything useful it seems.
```
10/21/2019 5:45:56 PM,Info,Installing... Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime.log
10/21/2019 5:45:56 PM,Error,Service Fabric product installed, but can not get installed product version.
10/21/2019 5:45:58 PM,Info,Cleaning temporary directory C:\Program Files\Microsoft Service Fabric.120qci3e.t4l
```
Any help or suggestion on getting the SDK installed will be appreciated.

**Comment by maburlik** [comment]
Is that the full InstallFabricRuntime.log? Can you see if there is a C:\WINDOWS\TEMP\FabricSetup*.log from this time frame?

**Comment by hmlam** [comment]
That is the full log as far as I can tell, and there doesn't seem to be any FabricSetup*.log at all. 

As an additional data point, today I try installing an older build (3.4.664) manually and that actually was successful on the machine. I have not try "upgrading" that install into 3.4.676 just yet (since I need that machine for some other purposes). But at least I am temporary unblock with build 3.4.664.

**Comment by maburlik** [comment]
I looked in the code and the error "Service Fabric product installed, but can not get installed product version" shows up when the SDK registry key version cannot be read at
HKLM
"SOFTWARE\\Microsoft\\Service Fabric SDK"
"FabricSDKVersion"

Can you tell if that value was present? I'm adding logging to make the symptom and solution more clear.

**Comment by hmlam** [comment]
That registry key is defined now and accessible (but it might be because I ruined the repo with installation of 3.4.664). I think at this point you can consider the issue closed if you are adding more logging/error messages so that in future user can proactively triage this better (e.g. try deleting the reg key if it is corrupted for some reason).

**Comment by maburlik** [comment]
Yes I'm making improvements in this area at this time. Thanks for bringing this up.
