### ISSUE TITLE
Possible Memory Leak of fabricCAS.exe 

### ISSUE THREAD

**Issue by zhangxd6** [Azure/service-fabric-issues#1594]
## Expected Behavior
The  memory footprint stay reasonable
## Current Behavior
About 2 days after restart the fabicCAS.exe, its memory usage reached ~3G
![image](https://user-images.githubusercontent.com/1870018/67952169-de164100-fbba-11e9-85d9-a83def713ced.png)

## Steps to Reproduce
1. start the cluster and note the less than 20MB memory of fabricCAS.exe
2. deploy a window container service fabric application. In my case, it is a containerized foxPro app.
3. let the application run for while with some requests to the applcation
4. on day 2, note the memory reached more than 3G

#### Service Fabric Runtime and SDK Version :
Runtime 6.5.664.9590
SDK 3.4.664.9590
#### Operating System :
Window Server 2016

#### Cluster Size :
Test Cluster: 5nodes

**Comment by julioas09** [comment]
I'm seeing a similar behaviour, consuming even more.
![ram](https://user-images.githubusercontent.com/3543529/71898588-00e44900-315a-11ea-9c74-6e3096f0aa1c.png)

**Comment by gkhanna79** [comment]
@zhangxd6 and @julioas09 Thank you for reporting this. Can you please confirm if you still see this on SF 7.0?

**Comment by aryamsft** [comment]
I've investigated this issue and found the memory leak.  The code fix will be in SF 7.1

**Comment by aryamsft** [comment]
No I don't think the issues are related.  I accidentally commented on the other github issue #1626
