### ISSUE TITLE
Service Fabric Build Packages

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#16]
Hi,

shall I check-in the build packages? Normally we dont check in packages.
Is there a nuget package so my solution will download the packages on build?

Thanks..

**Comment by seanmck** [comment]
I assume you're referring to the NuGet package containing the application build artifacts. If you upgrade your projects to the newest release (SDK 2.1.150), VS should automatically add that package for you. It will subsequently be pulled down from nuget.org like any other package.
