### ISSUE TITLE
Allowed Application Ports

### ISSUE THREAD

**Issue by aaneja** [Azure/service-fabric-issues#160]
I'm most likely reading the docs wrong. But [Configure your standalone cluster](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest) states:

`applicationPorts are the ports that will be used by the Service Fabric applications. These should be a subset of the ephemeralPorts, enough to cover the endpoint requirement of your applications. Service Fabric will use these whenever new ports are required, as well as take care of opening the firewall for these ports.`

I noticed though that

1. The json snippet for 'Node Types' though has:
`"applicationPorts": {
        "startPort": "20575",
        "endPort": "20605"
    },
    "ephemeralPorts": {
        "startPort": "20606",
        "endPort": "20861"
    }`
The applicationPorts are *not* a subset of the the ephemeralPorts.

2. This config has no bearing on the endpoints specified in my ServiceManifest.xml. If I specify an endpoint like:
`      <Endpoint Name="ProxyEndpoint" Type="Input" Protocol="https" Port="8282"/>`
I still see on the VMSS instances that a firewall rule is added to allow traffic on port 8282.

What am I reading wrong ? How do I ensure that endpoint ports would not be blocked by service fabric and will always be open on the VM firewalls ?

**Comment by TarasRoshko** [comment]
This may be useful:

http://stackoverflow.com/questions/39886834/what-is-the-purpose-of-service-fabric-cluster-node-type-app-port-range/41733858#41733858

[source](https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-service-manifest-resources)

My understanding is that it's a range used when ports are not specified by you, whatever you put into manifest explicitly is guaranteed to be properly opened on firewall etc

**Comment by aaneja** [comment]
Cool, makes sense now.
