### ISSUE TITLE
Is there any plan to have service fabric windows OS images have .Net 4.8 installed by default?

### ISSUE THREAD

**Issue by ifle** [Azure/service-fabric-issues#1601]
Is there any plan to have service fabric windows OS images have .Net 4.8 installed by default?

**Comment by LastTribunal** [comment]
I have the same question

**Comment by masnider** [comment]
The OS is not controlled by SF. The OS comes with the VM Scale Set that you provision SF on top of. I would redirect this to Azure Support/Azure Core Compute. 

Today I've seen people customize stuff like this by creating custom OS images based on the default marketplace images, or using something like the DSC extension to install the right version of .NET on machine boot. SF would tend to recommend the image based solution, as extensions can be a little tricky to get right, especially if whatever is being set up requires reboots.
