### ISSUE TITLE
Unable To Redeploy Services When Using Service Fabric Azure Files Volume Driver 

### ISSUE THREAD

**Issue by duncan-G** [Azure/service-fabric-issues#1605]
We deployed a Service Fabric application with 3 stateless services to our production cluster. Each service uses Azure Files as a volume. We also have Service Fabric Azure Files Volume Driver on every node in our cluster.

When we first deploy, the deployment happens successfully and we can see the applications in the services are sending data to Azure Files. However, when redeploying, one service goes into an error state. When restarting the service, the service stays in an error state. Furthermore, we do not see any data being sent to Azure Files. It looks likes there is something preventing the service from starting again.

We decided to do a test to see if the issue was the volume driver. We made one change to each service - we removed the volume and so the applications would write to their containers. After this change, we can successfully deploy and redeploy many times.

## Expected Behavior

Expect to deploy and redeploy many times while using azure files as a volume.

## Current Behavior

One service does not restart when upgrading service fabric application.
This looks like a bug with the volume driver.

## Context (Environment)

Every deployment requires deleting the service fabric application if using Service Fabric Azure Files Volume driver. This will not allow for us to have continuous deployment.

#### Service Fabric Runtime and SDK Version :
6.5.676.9590

#### Operating System :
Windows 1903

#### Cluster Size :
7 nodes in production

## Possible Workaround

Currently, we are dealing with this issue by removing the service fabric application - to avoid the upgrade process - and then deploying again. This is not definitely not a long term solution.

**Comment by wangcai0124** [comment]
What is error state show?
Can you please share the following if possible
1. application pkg include application manifest and service manifest
2. service fabric log
3. service fabric explorer link

**Comment by duncan-G** [comment]
Hey, after doing more testing we discovered that this is not a service fabric issue. I'll go ahead and close this issue. Thank you.
