### ISSUE TITLE
Test-ServiceFabricApplicationPackage crach

### ISSUE THREAD

**Issue by aamirsaleemkudcs** [Azure/service-fabric-issues#1608]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by aamirsaleemkudcs** [comment]
C:\Program Files\Microsoft SDKs\Service 
3>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:163 char:38
3>+ ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse)
3>+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : InvalidData: (:) [Test-ServiceFabricApplicationPackage], InvalidDataException
3>    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage

**Comment by aamirsaleemkudcs** [comment]
Can some one please advise me !!!

**Comment by masnider** [comment]
1) please fill out the template and reopen the issue. 
2) Add -Verbose to the call to test application package and call it from outside the VS tools, and see what you get.
