### ISSUE TITLE
Exemple Microsoft.ServiceFabric.Services.Actors.Wcf

### ISSUE THREAD

**Issue by juscelior** [Azure/service-fabric-issues#161]
Hi, 
Exist any example implementing Microsoft.ServiceFabric.Services.Actors.Wcf in client side?
Or the call is still being made using ActorProxy.Create

**Comment by masnider** [comment]
Actors require ActorProxy and don't support other transports today.

**Comment by VipulM-MSFT** [comment]
The ActorProxy and ActorService uses actor remoting transport. This transport can be WCF based or it can be the default TCP transport called FabricTransport.

**Comment by VipulM-MSFT** [comment]
You can change the default remoting transport to be WCF based by using https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.actors.remoting.wcf.wcfactorremotingproviderattribute?view=servicefabricactorswcf-2.5.216&viewFallbackFrom=servicefabricactors-2.6.204 in your interface assembly.
