### ISSUE TITLE
Multiple IService implementations causing 'System.DivideByZeroException' in ServiceRemotingMessageDispatcher

### ISSUE THREAD

**Issue by mbirkes** [Azure/service-fabric-issues#1610]
When two or more IService implementations share the same interface name from different namespaces, and have at least one Operation with the same name, a System.DivideByZeroException occurs during the listener startup for any StatelessService that implements both IService interfaces.  

Also referenced here since it is an SDK issue: 
https://github.com/microsoft/service-fabric-services-and-actors-dotnet/issues/234

## Expected Behavior
Allow a single stateless service instance to implement multiple IService implementations. 

## Current Behavior
ServiceRemotingMessageDispatcher initializer throws exception: System.DivideByZeroException: 'Attempted to divide by zero.'  See stack trace in following section. 

## Steps to Reproduce
1. Define two IService interfaces with the same name in different namespaces
2. At least one method in each Interface should have the same operation Name (parameters can be different)
3. Create a StatelessService implementing the two interfaces
4. Setup a FabricTransportServiceRemotingListener for the service. 
5. During FabricTransportServiceRemotingListener constructor, the Exception will be thrown. 

The following sample code can reproduce the behavior. Removing/Renaming one of the 'OperationA' methods will allow the service to start successfully. 

```csharp
namespace MyServiceA
{
    public interface IMyInterface : IService
    {
        Task<string> OperationA(string request);
        Task OperationC(int request);
    }
}

namespace MyServiceB
{
    public interface IMyInterface : IService
    {
        Task<int> OperationA(int request);
        Task OperationD(int request);
    }
}

namespace MyService
{
   
    internal sealed class MyService : StatelessService, MyServiceA.IMyInterface, MyServiceB.IMyInterface
    {
        public MyService(StatelessServiceContext context) : base(context)
        {
        }

        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new[]
            {
                new ServiceInstanceListener(
                    context => new FabricTransportServiceRemotingListener(context, this), "MyServiceListener"),
            };
        }

        Task<string> MyServiceA.IMyInterface.OperationA(string request)
        {
            return Task.FromResult("test");
        }

        Task MyServiceA.IMyInterface.OperationC(int request)
        {
            return Task.CompletedTask;
        }

        Task<int> MyServiceB.IMyInterface.OperationA(int request)
        {
            return Task.FromResult(1);
        }

        Task MyServiceB.IMyInterface.OperationD(int request)
        {
            return Task.CompletedTask;
        }

    }
}
```

Stack trace:
`   at Microsoft.ServiceFabric.Services.Remoting.Diagnostic.PerformanceCounterInstanceNameBuilder.ComputeTruncatedMethodName(MethodNameBuilder methodNameBuilder)
   at Microsoft.ServiceFabric.Services.Remoting.Diagnostic.PerformanceCounterInstanceNameBuilder.ComputeMethodNameInCounterInstanceName(IEnumerable'1 methodNameBuilders, Dictionary'2 methodOverloads)
   at Microsoft.ServiceFabric.Services.Remoting.Diagnostic.PerformanceCounterInstanceNameBuilder.GetMethodCounterInstanceNames(IEnumerable'1 actorMethodInfo)
   at Microsoft.ServiceFabric.Services.Remoting.Diagnostic.ServicePerformanceCounterProvider.InitializeServiceMethodInfo()
   at Microsoft.ServiceFabric.Services.Remoting.Diagnostic.ServicePerformanceCounterProvider..ctor(Guid partitionId, Int64 replicaOrInstanceId, List'1 interfaceDescriptions, Boolean generateCounterforServiceCategory)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingMessageDispatcher.Initialize(ServiceContext serviceContext, Object serviceImplementation, IEnumerable'1 remotedInterfaces, Boolean nonServiceInterface, IServiceRemotingMessageBodyFactory serviceRemotingMessageBodyFactory)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingMessageDispatcher..ctor(ServiceContext serviceContext, IService serviceImplementation, IServiceRemotingMessageBodyFactory serviceRemotingMessageBodyFactory)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportServiceRemotingListener..ctor(ServiceContext serviceContext, IService serviceImplementation, FabricTransportRemotingListenerSettings remotingListenerSettings, IServiceRemotingMessageSerializationProvider serializationProvider)
   at MyService.MyService.<CreateServiceInstanceListeners>b__1_0(StatelessServiceContext context) in C:\Users\Mason.Birkes\source\repos\NewListenerTest\MyService\MyService.cs:line 53
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.<OpenCommunicationListenersAsync>d__20.MoveNext()`

## Context (Environment)
Need to support multiple interface implementation to the same service instance. This could include multiple listeners on the same service instance.  Currently some interfaces in different namespaces share Interface and Operation names and cannot currently be implemented on the same service with the current SDK. 

#### Service Fabric Runtime and SDK Version :
Service Fabric 7.0.457.9590
SDK: 4.0.457.9590
Microsoft.ServiceFabric.Services.Remoting : 4.0.457

#### Operating System :
Windows 10 1909 18363.476

#### Cluster Size :
One Node - Development 

## Possible Workaround
Create separate service instances for IServices with duplicated Operation names.

**Comment by abarberenaCPDS** [comment]
Hi @mbirkes, your issue is very simple to fix. You need to fix your CreateServiceInstanceListeners method. First, create an array of Listeners, the name of your interface is the name of the Endpoint,

`
protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
        {
            FabricTransportRemotingListenerSettings facet1Settings = new FabricTransportRemotingListenerSettings { EndpointResourceName = nameof(IServiceFacet) };

            FabricTransportRemotingListenerSettings facet2Settings = new FabricTransportRemotingListenerSettings { EndpointResourceName = nameof(IOtherServiceFacet) };

            return new ServiceReplicaListener[]
            {
                new ServiceReplicaListener(context=>new FabricTransportServiceRemotingListener(context, this, facet1Settings),nameof(IServiceFacet)),
                new ServiceReplicaListener(context=>new FabricTransportServiceRemotingListener(context, this, facet2Settings),nameof(IOtherServiceFacet))
            };
        }
`

Second, update the service manifest, go to the Endpoints section and include the update accordingly

`
<Endpoints>
      <Endpoint Name="IServiceFacet" />
      <Endpoint Name="IOtherServiceFacet" />

      
    </Endpoints>
`

Deploy to SF and verify the endpoint names in your SF dashboard for the service. Your Test client should use something like:

`
Uri serviceAddress = new Uri("fabric:/MyApplication/MyStatefulRemotingService");
            IServiceFacet proxy = ServiceProxy.Create<IServiceFacet>(serviceAddress, partitionKey, listenerName: nameof(IServiceFacet));
`

I recommend you to check the Programming WCF services 4th edition book from Juval Lowy & Michael Montgomery to know more about it. Service Fabric represents the evolution in both the Service-oriented Programming model and Platform!

Good Luck and please Let us know how did it go!

**Comment by mbirkes** [comment]
Thank you @abarberenaCPDS for the quick reply and details. Unfortunately this solution does not address the original issue posted.  I'll explain. 

Please see the original source code posted.  The scenario originally described uses two facets (IMyInterface) each under a different namespace (MyServiceA.IMyInterface and MyServiceB.IMyInterface).  I've attached a screenshot of the error. 

The problem is not isolated to the fact that the Facets are named the same, but rather that they are named the same AND at least one method has the same name. The duplicate method name can even have a different signature, but the error remains. If you simply rename one of the OperationA methods, all of it begins to work fine, including client calls. 

I've traced through the SDK and isolated the error to the ServiceRemotedMessageDispatcher. During initialization, it attempts to create a performance counter on the service methods. However, the internals are using the facet and operation names as indexes or hashes and not taking into account the Namespace. Therefore there is a clash in indexing and ultimately causes the Divide By Zero. 

On a side note, @abarberenaCPDS , I'm right there with you. The Programming WCF Services book has been my sidekick since the 3rd addition. Ironically, the multi-facet design mechanism I am using above is an IDesign technique in detailed design for decomposing the volatile service implementations in the system. It, however, ran me up against this hiccup in the current SDK. 

Also, I have only tried this on the current SDK and runtime SF versions as originally posted. I have not attempted on prior versions. 

![Annotation 2019-11-29 180228](https://user-images.githubusercontent.com/272836/69893256-64b26100-12d4-11ea-9071-30fd181060ef.png)

**Comment by mbirkes** [comment]
The error occurs on line 254 of `PerformanceCounterInstanceNameBuilder.cs.` 

The `typeFull` variable is using the type Name instead of the FullName. Line 224:
`var typeFull = methodNameBuilder.MethodInfo.DeclaringType.Name;`

Changing the above line to the following line fixes the issues and the service can be hosted and interrogated by the client:
`var typeFull = methodNameBuilder.MethodInfo.DeclaringType.FullName;`

The error occurs because in `ComputeMethodNameInCounterInstanceName` the `methodOverloads` > 1 for the operation allowing flow to the `ComputeTruncatedMethodName`.  After applying the above fix, the namespace for the Facet is used and can successfully be injected into ` currentMethodBuilderInfo.Names[(int)MethodNameFormat.Truncated]` at line 211. 
See screenshot. 
![Annotation 2019-12-02 074548](https://user-images.githubusercontent.com/272836/69964487-25ecf880-14d8-11ea-8608-fad70366eaba.png)

**Comment by abarberenaCPDS** [comment]
Hey @mbirkes, makes sense, first, I apologize for getting back late, I had a busy weekend! Secondly, for not reading and understanding correctly you problem, after you clarified it made perfect sense.

Now, I still believe this 'issue' is simple to resolve and the error you get from Service Fabric is actually correct, although a bit obscure, as it has always been.

Let me explain why, you said you are aware indeed of a Service-oriented programming model. So if you remember from that book, Chapter 2 discusses about the Service contract implementation in a SOA programming model. What s the first topic discussed there and Why do you think is the exception behaving the expected way?

**Comment by mbirkes** [comment]
Hi @abarberenaCPDS , thanks again for the help.  I really appreciate the second set of eyes. 

Unfortunately the ASF SDK does not honor the `System.ServiceModel.ServiceContractAttribute` and `System.ServiceModel.OperationContractAttribute`  attributes for the `FabricTransportServiceRemotingListener.` It depends on the `Microsoft.ServiceFabric.Services.Remoting.IService` implementation instead. 

However, I did do some testing here to back up my claims. I edited my original post to include the attributes and overloaded operation names (like you would do with WCF).  My findings were the same and the `System.DivideByZeroException` errors continue. 

Now if I host with a WCF listener, I can take advantage of the ServiceModel features and I can make things work. Again, this is just another workaround since i really I need to use the `FabricTransportServiceRemotingListener`.  

If you see my previous reply, I actually found the possible bug in the ASF SDK. When it builds the diagnostics performance counters, it incorrectly uses the short name instead of the full name of the facet type.  I proved this out by pulling the source and making the one code change. After this, everything worked as desired for server and client side.

**Comment by abarberenaCPDS** [comment]
Hey @mbirkes, not a problem, I'm always glad to help a comrade-in-arms.

I did mean when referencing to Operation Overloading is that method overloading has different rules when using SOA vs OO. Using the trick mentioned for the good old ServiceContract can't be applied to SF. It is well explained the reason why doesn't work and should not be designed that way. Luckily for DataContracts is different and we can use versioning and their other capabilities. 

The rules for naming the service operations, however, are more related to your facets design than the SF itself. So I am thinking that renaming as you pointed in the beginning, is the desired approach.

**Comment by masnider** [comment]
Thanks for the report. If it is ok I'm going to close down this one and we can continue in the SDK specific repo. Please go ahead and reopen here if there's different info that needs to be discussed but otherwise we can continue there.
