### ISSUE TITLE
Replicator port assignment.

### ISSUE THREAD

**Issue by davebally** [Azure/service-fabric-issues#1615]
Hi,

We are working in quite a locked down environment and as such are required to limit the port ranges that are open.

For ServiceFabric itself and the applications the ports are defined in the service manifest.  However for the replicator port for stateful services i can find no such setting. 

Am i missing something ?

Thanks

**Comment by tyms** [comment]
Hi,

It's essentially the same process as for service endpoints. You first add an endpoint for the replica in the service manifest [as in this example](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources#example-specifying-an-http-endpoint-for-your-service). If you don't specify a port for this endpoint, SF will choose one from the application port range. Then, specify the ReplicatorEndpoint setting in the ReplicatorConfig section in your service's Settings.xml [like this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration#sample-configuration-file).

Let me know if anything needs additional clarification!

-Ty

**Comment by masnider** [comment]
@davebally Ty's solutions should allow you to specify what you need. Please let us know if this addresses your question.

Thanks!
-Matt

**Comment by davebally** [comment]
Thanks @tyms , @masnider ...
Sorry for the delay,  ive been on leave over the holiday period.

Looks like thats got it.  Small suggestion though to add that the port should be shown in service fabric explorer somewhere ( unless im missing it :) ).  Had to validate with netstat.

Dave
