### ISSUE TITLE
GetImages(): Failed communication with docker with error: FABRIC_E_SERVICE_OFFLINE

### ISSUE THREAD

**Issue by hugginssd** [Azure/service-fabric-issues#1618]
I installed the Server Fabric on the On-Premise production environment. But after installation it give the following docker communication error yet i didn't even install docker on my **Server Fabric**.
Can't figure out what to do with this error and i'm thinking it's one of the errors failing me to deploy Dynamics 365 Finance and Operations.
 
**`EventData`** 

  **`id`**  
  **`type`** `ProcessActivationManager `
  **`text`**  `GetImages(): Failed communication with docker with error: FABRIC_E_SERVICE_OFFLINE`

**Image 1**
![image](https://user-images.githubusercontent.com/26626271/70787133-bf4cc200-1d96-11ea-8762-af6342d7eeb7.png)

**Image 2**
![image](https://user-images.githubusercontent.com/26626271/70786955-6715c000-1d96-11ea-83da-d2c6db324ff3.png)

**Image 3**
![image](https://user-images.githubusercontent.com/26626271/70786908-51a09600-1d96-11ea-8ac8-a569ea349cbc.png)

**Image 4**
![image](https://user-images.githubusercontent.com/26626271/70786826-2cac2300-1d96-11ea-84d8-772bdc456448.png)

Any help please!!

**Comment by masnider** [comment]
Are you sure that this application doesn't require Docker?

At this point, what is the status of the cluster? Is the cluster overall up and healthy?

**Comment by tugup** [comment]
Are you running containers? If not, then add a config DisableContainers to true in your cluster manifest under Hosting Section.

**Comment by hugginssd** [comment]
Ok thanks for your efforts guys!! I managed to resolve the issue.
