### ISSUE TITLE
Azure AD settings are not exported as parameters in ARM template

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#163]
Configure a new cluster on the Azure Portal, secured with Azure AD. Don't create the cluster, but download the template.
In the generated ARM template, the `azureActiveDirectory` values filled in for 'clientApplication', 'clusterApplication' and 'tenantId' are 'hard coded':

```
"type": "Microsoft.ServiceFabric/clusters",
[..]
"azureActiveDirectory": {
	"clientApplication": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa",
	"clusterApplication": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa",
	"tenantId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa"
},
```

notice the '**aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa**' values above, they should be parameters.

**Comment by masnider** [comment]
Thanks for the report, we'll get this filed as an improvement.

**Comment by mhatreabhay** [comment]
bug is created for enhancement. Closing issue.
