### ISSUE TITLE
ServiceFabric template does not work with NuGet.config

### ISSUE THREAD

**Issue by alprema** [Azure/service-fabric-issues#165]
Having a NuGet.config at the root of our repository redirecting the `packages` folder to the root of the repo prevents the Service Fabric services in sub-folders from building.

The services still try to get their NuGet references from a `packages` folder in the solution directory (similar to the comment in [this issue](https://github.com/Azure/service-fabric-issues/issues/58), but we could only manage to get it working with a pre-build event).

**Comment by dbreshears** [comment]
Thanks for reporting. We will investigate a fix for this.

**Comment by ravipal** [comment]
@alprema, I assume you are reporting the issue for existing projects as the new projects will use the repositorypath defined by Nuget.Config.

For existing projects when nugets are installed the relative path is added to the *.csproj file. So after project creation if the repositorypath is added/updated, the existing projects will still use the old path, unless you uninstall and reinstall the nuget packages. Hope this helps.

The  [issue ](https://github.com/Azure/service-fabric-issues/issues/58) that is linked here is different issue where the repositorypath is in different drive than the project.

**Comment by alprema** [comment]
Reinstalling the Nuget helped for the Service but not for the Application (sfproj). I had to edit `<Import Project="` tags in the sfproj manually but it worked (also I confirm that creating a ServiceFabric app after adding the NuGet.config works properly).
