### ISSUE TITLE
Service Fabric User accounts 蠍欥⋧垙타軆펭磾괖꛿ffffffff

### ISSUE THREAD

**Issue by Chemlin** [Azure/service-fabric-issues#1658]
I have an on-premise installation of Service fabric and for some odd reason the user accounts have cryptic Chinese like characters.What could be causing this. I am running Windows Server 2016 Data Center.I know that on Azure the usernames appear proper like  P_FSSUserffffffff.

**Comment by Chemlin** [comment]
@oanapl are you able to help on this one ?

**Comment by oanapl** [comment]
Which SF version are you using? 
The latest SF versions (7.0 CUx) should not create users at all. If you are on an older version and you still need to use NTML users, you should have FileStoreService GenerateV1CommonNameAccount settings false, so it doesn't create those names, but user-readable names.
@JeongPyoHam can help.

**Comment by JeongPyoHam** [comment]
SF creates local user account in predefined name like P_FSSUser or in generated name. Names are generated when CommonName-based certificate is configured in FileStoreService section. For example, CommonName1Ntlmx509CommonName is set in cluster configuration.
The Chinese letter is just visualization of the UI that does its best to find the character code from the locale.
Service Fabric improved this in version 7.0 to prefix every account with "WF-" even in generated account names. Also, the letters in account name are chosen within printable ASCII range.
