### ISSUE TITLE
Rolling over SF certificate with reverse proxy enabled fails

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#168]
Following the guide here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure#add-a-secondary-certificate-using-resource-manager-powershell with the reverse proxy secured with a (I found it has to be the same) ssl certificate as in the instructions here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy does not work.

You're met with a shed load of Error and Warning events such as

`Node name: _Default_0 has failed to open with upgrade domain: 0, fault domain: fd:/0, address: 10.0.0.4, hostname: Default000000, isSeedNode: true, versionInstance: 5.4.164.9494:3, id: 7ec9f3db8d79f7c701957617648293a0, dca instance: 131318513186424571, error: FABRIC_E_INVALID_CONFIGURATION`

`AcquireCredentialsHandle(Microsoft Unified Security Protocol Provider) failed: 0x8009030d`

`Failed to load primary of 'FindByThumbprint:X,FindByThumbprint:Y' in LocalMachine/My, will fall back on secondary` (n.b. both certificates ARE present in certificate store)

`CreateFileW failed 32`

`ParseConfigSettings: ErrorCode=E_FAIL, FileName=D:\\SvcFab\FabricHostSettings.xml`

etc...

and because of this, Node_0 gets stuck on `Status: Updating user certificate` indefinitely.

I cant test much because the more times I create/destroy clusters, the longer it takes to recreate them (2h this time...)

Is there no way to roll over the certificate if you use SF reverse proxy?

I shall try again on Monday sans reverse proxy and report back, but I suspect the whole roll-over workflow is broken.

The only solution, it seems, is to destroy the cluster and recreate it. Not ideal in production!

**Comment by kavyako** [comment]
Hi Mardoxx

By any chance did you copy & paste the thumbprint from the MMC certificate snap-in or Powershell ISE. This adds extra Unicode characters ([that are invisible](https://support.microsoft.com/en-us/help/2023835/certificate-thumbprint-displayed-in-mmc-certificate-snap-in-has-extra-invisible-unicode-character)) and the upgrade runs into issues.

Thanks
Kavya

**Comment by Mardoxx** [comment]
Hi,

This one has tripped me up before! I'm certain it doesn't!

Cheers

**Comment by Mardoxx** [comment]
Just tried it on a cluster deployed without the reverse proxy being secured with an SSL cert. It's still running now after 50 minutes. How long is this meant to take?

I'm getting lots of Errors in my SF Admin event log saying very similar:

`Failed to load primary of 'FindByThumbprint:X,FindByThumbprint:Y' in LocalMachine/My, will fall back on secondary`

Where X is the new cert, and Y is the old one.
Unsure what it means by `FindByThumbprint:X,FindByTumbprint:Y` surely it should only be trying to find one certificate, then if that fails, look for the secondary, not look for both at once.  both certificates are in LocalMachine/My and the thumbprints do not have any hidden characters in them.

Infact, when I open powershell and run

```
cd Cert:/LocalMAchine/My
dir | where {$_.Thumbprint -eq "X"}
dir | where {$_.Thumbprint -eq "Y"}
```

Where X and Y are copied from that error log, it has no problem finding them!

**Comment by Mardoxx** [comment]
Nope, just keeps failing with

```Node name: _Default_0 has failed to open with upgrade domain: 0, fault domain: fd:/0, address: 10.0.0.4, hostname: Default000000, isSeedNode: true, versionInstance: 5.4.164.9494:3, id: 7ec9f3db8d79f7c701957617648293a0, dca instance: 131319275788799753, error: FABRIC_E_INVALID_CONFIGURATION

Node name: _Default_0 is aborting with upgrade domain: 0, fault domain: fd:/0, address: 10.0.0.4, hostname: Default000000, isSeedNode: true, versionInstance: 5.4.164.9494:3, id: 7ec9f3db8d79f7c701957617648293a0, dca instance: 131319275788799753
```

**Comment by Mardoxx** [comment]
The script just finished now, after 1h30, and failed with.

`New-AzureRmResourceGroupDeployment : 21:49:58 - Resource Microsoft.ServiceFabric/clusters '__CLUSTER_NAME__' failed with
message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
  }
}'`

The cluster has reverted back to its previous state.

The only differences in these ARM templates, compared to the test without the reverse proxy being secured with an SSL cert, were that in the initial deploy template we now have the added section:

```
                "reverseProxyCertificate": {
                    "thumbprint": "[parameters('certificateThumbprint')]",
                    "x509StoreName": "[parameters('certificateStoreValue')]"
                },
```


and in the rollover template we now have

```
                "reverseProxyCertificate": {
                    "thumbprint": "[parameters('newCertificateThumbprint')]",
                    "x509StoreName": "[parameters('certificateStoreValue')]"
                },
```

I deployed both the old and new certificate in the initial deployment of both tests. So this rules out any issue with certificate management/deployment.

**Comment by kavyako** [comment]
Once you add a new certificate for the reverse proxy, it also needs to be added to the VMSS osProfile/secrets to ensure correct ACLing.

"osProfile": {
            "adminPassword": "[parameters('adminPassword')]",
             .......
            "computernamePrefix": "[parameters('vmNodeType0Name')]",
            "secrets": [
              {
                "sourceVault": {
                  "id": "[parameters('sourceVaultValue')]"
                },
                "vaultCertificates": [
                  {
                    "certificateStore": "[parameters('certificateStoreValue')]",
                    "certificateUrl": "[parameters('certificateUrlValue')]"
                  }
                ]
              },
              **{
                "sourceVault": {
                  "id": "[parameters('sfReverseProxySourceVaultValue')]"
                },
                "vaultCertificates": [
                  {
                    "certificateStore": "[parameters('sfReverseProxyCertificateStoreValue')]",
                    "certificateUrl": "[parameters('sfReverseProxyCertificateUrlValue')]"
                  }
                ]
              }**
            ]
          },

Ideally the above config should take care of the ACL.  Any chance you could update the ARM template to apiVersion “2016-09-01”, please note the httpApplicationGateway* properties should be updated to reverseProxy* . Let me know if this works.

The error AcquireCredentialsHandle() failed with error 0X8009030D is due to NETWORK SERVICE account does not have access to read the reverse proxy certificates private key. 
Could you confirm if that is the case, Goto mmc -> manage certificates for Computer Account -> Certificates > Personal > Certificates -> check if the Security permissions for the reverse proxy certificate allows the NETWORK_SERVICE account. You could manually grant access there to unblock for now.

**Comment by Mardoxx** [comment]
I'm testing this on a brand new deployment -- Just convincing myself that anything that can go wrong with using service fabric can be remedied. One scenario is certificate rollover, which I am testing/simulating now with two distinct certificates. 

I perhaps didn't make myself clear previously. In both deployments (the one without, and the one with, the reverse proxy certificate) my VMSS has both the old and new certificate: 

```
                                "vaultCertificates": [
                                    {
                                        "certificateStore": "[parameters('certificateStoreValue')]",
                                        "certificateUrl": "[parameters('certificateUrlValue')]"
                                    },
                                    {
                                        "certificateStore": "[parameters('certificateStoreValue')]",
                                        "certificateUrl": "[parameters('newCertificateUrlValue')]"
                                    }
                                ]
```

Service fabric API version is as follows:

```
        {
            "apiVersion": "2016-09-01",
            "type": "Microsoft.ServiceFabric/clusters",
```

**Comment by Mardoxx** [comment]
I think I've "fixed it"... Pure guess work...

According to the json schema https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2016-09-01/Microsoft.ServiceFabric.json , `reverseProxyCertificate` can take a `thumbprintSecondary` as well

If I add:

```
                "reverseProxyCertificate": {
                    "thumbprint": "[parameters('newCertificateThumbprint')]",
                    "thumbprintSecondary": "[parameters('certificateThumbprint')]",
                    "x509StoreName": "[parameters('certificateStoreValue')]"
                },
```

It deploys fine, *but* still serves up the old certificate. If I restart the "primary node" it then serves up the new certificate.

**Comment by kavyako** [comment]
Can you try rolling over the certificate in 2 upgrades. Assuming you have a cluster with Reverse Proxy enabled and configured to use HTTPS (using a different certificate from cluster cert), deployed from a template similar to [5-VM-1-NodeTypes-SecureRP_Step3.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_Step3.json)

1. First upgrade to install the new certificate on all the VMs and acl'ing the certificate.
Refer [5-VM-1-NodeTypes-SecureRP_RollOverStep1.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_RollOverStep1.json)
Add all the sections corresponding to reverseproxy under virtualMachineProfile -> extensionProfile -> extensions -> reverseProxyCertificate and osProfile -> secrets -> vaultCertificates. Diff this template with [5-VM-1-NodeTypes-SecureRP_Step3.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_Step3.json) for exact config entries.

After this, you can see that the certificate is installed on the nodes and the NETWORK_SERVICE account has Read rights on the certificate key.

2. Second upgrade to use the second /new certificate as the Reverse Proxy certificate.
Refer [5-VM-1-NodeTypes-SecureRP_RollOverStep2.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_RollOverStep2.json). Diff this with the previous JSON for the exact config entries.

Once the upgrade is completed, reverse proxy should serve the new certificate.

If you are still running into issues , please share the ARM templates (org and the ones used for the upgrades) and we will take a look.

Thanks
Kavya.

**Comment by Mardoxx** [comment]
Cheers!
