### ISSUE TITLE
Unable to use MachineKey with AspNet.Identity

### ISSUE THREAD

**Issue by haseeb-ahmed-tkxel** [Azure/service-fabric-issues#169]
When using Service Fabric, since Stateless Services are self-hosted, I'm able to use the MachineKey with AspNet.Identity. How can this be done in Service Fabric? I know this is an important feature for having a common Token Consumption mechanism across AppTypes but I couldn't find anything use-able on the internet.

**Comment by MedAnd** [comment]
This approach might be of interest: [ASP.NET Core DataProtection for Service Fabric with Kestrel & WebListener](http://www.medic-consulting.com/2017/01/19/Asp-Net-Core-DataProtection-for-Service-Fabric-with-Kestrel-WebListener/)

**Comment by masnider** [comment]
@haseeb-ahmed-tkxel can you point us at some of the things you tried and what problems you ran into? Also were you able to try the approach that @MedAnd outlined and if so did it work out for you?

**Comment by haseeb-ahmed-tkxel** [comment]
@masnider I didn't try much, after looking at MedAnd's approach (which in my opinion was a bit too much work) what felt more natural for me was to override the TokenProvider with my own... From what I remember, default TokenProvider wasn't picking up the key correctly so by having a custom token provider I had the control over where to pick the key from (in my case AppConfig but you can use Service Fabric App Params as well) and even what encryption algo to use to generate the token.

Hope that helps :-)

**Comment by masnider** [comment]
@haseeb-ahmed-tkxel - so were you able to get this working? Can you share the code that isn't working as you expect today and the errors that you're encountering?

**Comment by masnider** [comment]
Closed as we haven't heard back from you. Glad you got things working!
