### ISSUE TITLE
Packages not found on Web PI and runtime/SDK only is not available

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#17]
The direct links in the release notes for 5.1.150 does not find the intended installation packages.

"Microsoft Web Platform Installer couldn't find the product you tried to install."

It does work to search for Service Fabric, and then install the SDK for Visual Studio 2015 and "15" Preview. But the SDK/runtime only is not available as an option in Web Platform Installer.

This means there is currently no way to download the installer for the SDK and runtime directly.

Workaround for this, is to install the SDK tools for Visual Studio on a machine with Visual Studio, then find the .msi package in the Web PI cache, which is part of the packages that comes with the full SDK.

"C:\Users\[USER]\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_2_1\EA8DC267F7C7C8DD738CEA822839996245D1B9E2\MicrosoftServiceFabricSDK.2.1.150.msi"

**Comment by seanmck** [comment]
Thanks for reporting. The links in the blog post have been fixed. There were also issues with the links on azure.com. Those have been fixed as well and will be published shortly.
