### ISSUE TITLE
reverseProxyCertificate must be the same as cluster certificate

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#170]
### Reproduction steps:
1. Follow this documentation https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy
2. Use a different certificate from the cluster certificate i.e. `certificate.thumbprint !== clusterCertificate.thumbprint`
3. Deployment will fail, Service Fabric error logs will say `FABRIC_E_INVALID_CONFIGURATION`

Is there a reason why these certificates must be the same? If so, this is not clear in the documentation -- unless I have missed it.

**Comment by kavyako** [comment]
Thank you for reporting this! 
Reverse Proxy certificate can be different from cluster certificate.

Updating the Reverse Proxy certificate must be done with 2 step upgrades:

- First upgrade to install the Reverse Proxy certificate on all the VMs and acl'ing the certificate. This adds the new certificate to the following sections:
    1. virtualMachineScaleSets osProfile : To install the certificate on all the VMs.
    2. The Service Fabric extension for virtual machine scale sets : To set the ACL rights on the certificate key for service fabric to access it.
Refer [5-VM-1-NodeTypes-SecureRP_Step2.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_Step2.json)

- Second upgrade to set the new Reverse Proxy certificate thumbprint in the Service Fabric cluster resource. 
Refer [5-VM-1-NodeTypes-SecureRP_Step3.json](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_Step3.json)

The corresponding ARM template samples are under [Configure HTTPS Reverse Proxy in a secure cluster](https://github.com/ChackDan/Service-Fabric/tree/master/ARM%20Templates/ReverseProxySecureSample#configure-https-reverse-proxy-in-a-secure-cluster) for the exact ARM template entries. They are based on the 5-VM-1-NodeTypes-Secure ARM template sample.

We are in the process of updating the documentation to reflect this. 

If you are still running into this issue, do you mind sharing your ARM template (org and the ones used for the upgrades) for further investigation.

**Comment by Mardoxx** [comment]
Amazing, thanks! Will give this a try, wasn't clear from the documentation that the cluster had to be set up _without_ the SecureRP enabled initially!

**Comment by Mardoxx** [comment]
It worked great, thanks!
