### ISSUE TITLE
Can't find fabricClusterAutoupgradeEnabled in ClusterConfig.json

### ISSUE THREAD

**Issue by hugginssd** [Azure/service-fabric-issues#1704]
``
## Expected Behavior
I'm in the process of trying to upgrade my Service Fabric Cluster from 7.0.x to 7.2.x. But now the problem is I can't find the `fabricClusterAutoupgradeEnabled  ` in ClusterConfig.json file in `C:\ProgramData\SF`. 

## Current Behavior

This is my ClusterConfig.json file
[ClusterConfig.txt](https://github.com/microsoft/service-fabric-issues/files/5781289/ClusterConfig.txt)

## Steps to Reproduce

1. Navigated to `C:\ProgramData\SF`
2. Opened `ClusterConfig.json`
3. Couldn't find the `fabricClusterAutoupgradeEnabled`
4.

## Context (Environment)

**NB:** _This is a D365FO on-premise environment_
#### Service Fabric Runtime and SDK Version :
Code version: 7.0.466.9590
#### Operating System :
Windows Server 2016 Datacenter

#### Cluster Size :
3
## Possible Workaround

Any help??

**Comment by craftyhouse** [comment]
Please use this other repo for issues in the future https://github.com/microsoft/service-fabric/issues as noted https://github.com/microsoft/service-fabric-issues#azure-service-fabric-issues

If this is a production cluster please follow the guidance here https://github.com/microsoft/service-fabric/blob/375d9bb735c0d6e05c445da5a4e4e9721540494f/CONTRIBUTING.md#production-issues to get the proper assistance. 

This may answer your question though https://social.msdn.microsoft.com/Forums/en-US/18cde88c-d05d-4229-988c-5dfd36260a65/enable-fabricclusterautoupgradeenabled-flag-on-existing-cluster 

If you end up cross posting please let us/me know so I can respond with similar info to help the community. thanks!

**Comment by hugginssd** [comment]
Thank you @craftyhouse!
