### ISSUE TITLE
Default Service Parameter vs Application Parameters

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#171]
Hey guys,

I defined my Service in ApplicationManifest.xml

```
<Parameters>
    <Parameter Name="InstanceCount" DefaultValue="1" />
  </Parameters>
...
<DefaultServices>
    <Service Name="WarrantyRequestService">
      <StatelessService ServiceTypeName="WarrantyRequestType" InstanceCount="[InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
```

and I have this ApplicationParameters file Integration.xml where I have

```
 <Parameters>
    <Parameter Name="InstanceCount" Value="2" />
  </Parameters>
```

If I try to deploy (update) the service, I get the error:
```
Default service descriptions must not be modified as part of upgrade.
Modified default service: fabric:/WarrantyRequestApplication/WarrantyRequestService
```

I wonder why I get this error as I tought this would be the correct way to define the parameter per environment.

**Comment by mikanyg** [comment]
Have you previously deployed the service with just 1 instance? You cannot add more instances during upgrades. Too add more instance to a deployed service you need to use the powershell api.

**Comment by senj** [comment]
Ok now I understood the workflow (altough for me it's a bit confusing).

1) Deployment of a service with instance count = 1 (in applicationManifest and/or in applicationParameters - doesn't matter)
2) Raise the instance count with the powershell to e.g. '2'.
3) Redeploy the service with the SAME SETTINGS as before (instance count = '1') => after the upgrade, it's still 2.
4) What doesn't work: deploy the service with instance count = 2 (ex. as stated above).

Thanks anyway.
