### ISSUE TITLE
Container Deployment to Service Fabric Cluster Fails

### ISSUE THREAD

**Issue by sg1970** [Azure/service-fabric-issues#173]
I was asked to open a new issue in this thread : https://github.com/docker/docker/issues/30155#issuecomment-281874704

Goal :
trying to get this : https://loekd.blogspot.com/2017/01/running-windows-containers-on-azure.html
working in a corporate env.

Docker image is a .NetCore  1.1 WebAPI that exposes a port (5000) and is tested and it works well on the remote PC ( the VS2015 PC) 

Important thing to Note is that I have tried to make this work on 3 different VM's ( 2 Privarte VM's and one Corporate VM thats behind a proxy and is connected to a domain but all running same versions of Win+docker+SF ). So far I **have been successful** on one of the Personal VM's.  But I'am not sure what is the difference between them. I will get some more time to check over the w/e. 

Any help will be greatly appreciated. 

Thanks

**Details**:

---Error I get on SF explorer when I publish to a remote SF Cluster from VS2015 which is on a remote PC -----
Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count.
fabric:/MyContainerService/MyContainerService -1 1 aa9eb532-c81f-432c-b62d-282b387913ff
IB vm2 Up 131320812583374071
IB vm1 Up 131320812583374072
IB vm0 Up 131320812583374073
(Showing 3 out of 3 replicas. Total available replicas: 0.)

And If I try to run docker ps from command prompt i get :

C:\Program Files\Docker>docker ps
error during connect: Get http://localhost:2375/v1.26/containers/json: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

-- DOCKER_HOST variable setting ---
C:\Program Files\Docker>set | find /i "Docker"
DOCKER_HOST=tcp://localhost:2375

http_proxy=http://user:password@proxy.company.com:8080
https_proxy=https://user:password@proxy.company.com:8080

-----------

docker version:
c:\>docker version
Client:
 Version:      1.13.1-cs1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:05:36 2017
 OS/Arch:      **windows/amd64**

Server:
 Version:      1.13.1-cs1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:05:36 2017
 OS/Arch:      **windows/amd64**
 Experimental: false

---

Service Fabric Version : 5.4.145.9494. Win Server 2016 Build 14393.693
Using 3 Node Single host SF Cluster that is configured using the Unsecure Dev Cluster json template  with standard config entries ( except for hostname in "iPAddress" field )

---

**Comment by RajeetN** [comment]
Hi,

I assume you are running a developer onebox scenario? Could you check if dockerd is running in taskmgr? Also do you see any errors in eventvwr under ServiceFabric Admin channel?

**Comment by sg1970** [comment]
@RajeetN 

Thanks for responding!. 

1. Yes Onebox (with a 3 Node Cluster)  Windows Server VM 2016. ( 2 Private VMs + 1 Corporate VM )

2. dockerd is not running in taskmgr because Docker-Engine service is disabled. If I enable it and try to start it ... it will be shutdown (gracefully) by SF which I think is by design (not sure).  But this behavior is not present on my personal VM that works. On that one I have both SF and Docker Engine running simultaneously . I do not know what different I did to get that 

3. I did not have a  SF Bucket + the Admin , Operational Channels as I hadn't enabled the subscription .... once I did that I see a whole bunch of warnings (Shouldnt they be classified as "Errors" !!! ) . Thanks for mentioning the Channels I was only looking at the Main Application bucket in the Event Viewer so far. 



----- Here are the main errors (Repeated over and over)  that I found on the SF Admin channel ------ 

- End(BeginDownloadAndActivate): Error=0xd00000e5, VersionedServiceTypeId={MyContainerServiceType_App5:MyContainerServicePkg:MyContainerServiceType,1.0:1.0:131320812566473161}, SequenceNumber=16787

- CreateProcessW failed. ErrorCode=0x80070002
 
- End(ContainerProvider process Activate): ErrorCode=0x80070002
 
- Docker process failed to start. ErrorCode=0x80070002, CurrentState=32
 
- EndSendRequest Error 0xd00000e5, imageName sg1970/imgpub01, winHttpError 12029
 
- Failed to import docker image error 0xd00000e5.

--------

BTW  to simplify the scenario I had manually downloaded the Docker Image from my docker repo on Docker Hub.

**Comment by RajeetN** [comment]
Hmm, looks like SF is not able to find dockerd. I suspect the PATH on vm is not set to c:\Program Files\docker. If it is set could you restart the vm?

**Comment by sg1970** [comment]
@RajeetN yep the path was missing. I added it and re-started the Service Fabric host service and looked in the event viewer and saw the same errors as before. Next, to be sure I just re-booted the VM and checked still no joy. Then I deleted my service fabric app+service from Service Fabric Explorer and re-published from VS2015.  Now I get slightly different errors but ultimately its still not working.  It complains that there are files missing ( 7,8,9 below) but they are actually there on the VM.


--- Errors (Actually Warnings) from Event Viewer (may not be exactly in this order but close )----

1. CreateProcessW failed. ErrorCode=0x80070002
2. Docker process failed to start. ErrorCode=0x80070002, CurrentState=32
3. End(Delete): Store:Store\MyContainerServiceType\MyContainerServicePkg.Config.1.0.2, Error:FABRIC_E_FILE_NOT_FOUND
4. The request failed due to FABRIC_E_FILE_NOT_FOUND. StoreRelativePath:Store\MyContainerServiceType\MyContainerServicePkg.Config.1.0.2
5. Ending StoreTransaction for TranitionToIntermediateState. StoreRelativePath:Store\MyContainerServiceType\MyContainerServicePkg.Config.1.0.2, Error:FABRIC_E_FILE_NOT_FOUND
6. StoreOperation: Error:FABRIC_E_FILE_NOT_FOUND
7. FileNotFound=Store\MyContainerServiceType\MyContainerServicePkg.Code.1.0.2.checksum
8. FileNotFound=Store\MyContainerServiceType\MyContainerServicePkg.Manifest.1.0.2.xml.checksum
9. FileNotFound=Store\MyContainerServiceType\MyContainerServicePkg.Manifest.1.0.2.xml
10. WriteNode failed. HRESULT=-2147467259, Output=CustomOutput
11. Failed to communicate with the cluster (get deployed replica detail: FABRIC_E_OBJECT_CLOSED).

Maybe I should just re-install the SF Cluster and try again ? 

Thanks for your time !

**Comment by RajeetN** [comment]
Could you run the following from powershell:
1. Connect-ServiceFabricCluster
2. Get-ServiceFabricApplication | Remove-ServiceFabricApplication -Force
3. Get-ServiceFabricApplicationType | Unregister-ServiceFabricApplicationType -Force
4. This should bring your cluster to a clean slate. Deploy the application again after that. 
Let us know if that doesn't work.

**Comment by mani-ramaswamy** [comment]
Or use the equivalent commands from the CLI @ https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-azure-cli

**Comment by sg1970** [comment]
@RajeetN 

Same result as before I see those 11 warnings + these 2 errors 

1. WriteNode failed. HRESULT=-2147467259, Output=CustomOutput
2. WriteNode failed. HRESULT=-2147467259, Output=CustomOutput (its repeated twice and its a error category not Warning.)

for some reason I missed posting these 2 errors in my previous post but they were there the last time too.

So Next step : Re-Install SF cluster ?

@mani-ramaswamy  Thx thats a useful link.

**Comment by RajeetN** [comment]
So you are still seeing these?
CreateProcessW failed. ErrorCode=0x80070002
Docker process failed to start. ErrorCode=0x80070002, CurrentState=32

In that case would it be possible to get a dump of FabricHost process and share it with us before you reinstall? Just to confirm you set machine wide environment variable right?

Thanks!

**Comment by sg1970** [comment]
@RajeetN Yes i see those errors . And if you mean the path variable then here is the evidence(see below)
How do I send the dump file ? 

-------
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd\

C:\>docker ps
error during connect: Get http://127.0.0.1:2375/v1.26/containers/json: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

C:\>
---------

C:\>set | find /i "Docker"
DOCKER_HOST=tcp://127.0.0.1:2375
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\WindowsHelp\AppData\Local\Microsoft\WindowsApps;C:\Program Files\WinZip;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code;C:\ProgramData\chocolatey\bin;**"C:\Program Files\Docker"**

C:\>

**Comment by RajeetN** [comment]
hmm, the quotes around docker path doesnt seem right.  Could you try changing that?

**Comment by sg1970** [comment]
Success !!!!

But those quotes were inserted by the new GUI in 2016 that allows us to enter each path in a separate line and the quotes are not present when you view the PATH variable from GUI. So I deleted the  C:\Program Files\Docker from GUI and keyed it in as %ProgramFiles%\Docker. Checked to make sure it had taken effect and then Re-started the Service Fabric Host Service. Then Cleaned up the cluster using the 3 Powershell Commands you provided earlier and then Re-Published from VS2015 and it worked instantly. I can see that my webservice is responding from 3 ports ( 1 per each node in the cluster).

Now the next part is to make both Docker and SF co-exist simultaneously. I will take that up tomorrow. 

But a big thank you for helping me out !!

Cheers!

**Comment by RajeetN** [comment]
Great! Thanks for your patience while we sorted this out, What do you mean by SF and Docker co-exist simultaneous?

**Comment by sg1970** [comment]
Meaning I don't want the  Docker Engine Service on the cluster to stop when I deploy my Docker image ? How do we do that ?

Thank You !! I would have never caught that in a million years !

**Comment by RajeetN** [comment]
Docker engine does not stop, SF just starts it up on a different port to manage its lifecycle. Is there a reason you need the service to be running? Note that in upcoming release you will not need to do the -H localhost:2375 to run docker commands and just directly run docker commands.

**Comment by sg1970** [comment]
Mainly for troubleshooting but I see that the docker commands are working again even though the Docker Engine Service is stopped(disabled) . I think this is due to the DOCKER_HOST env variable which is used automatically ?  But if I try to start Docker Engine Service it wont start.

C:\>docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
eef3e3caab32        sg1970/imgpub01     "dotnet out/TokenG..."   34 minutes ago      Up 34 minutes       0.0.0.0:20289->5000/tcp   sf-8-f674c333-5b2f-451e-b2f7-62281fe4300e
5309da3d633a        sg1970/imgpub01     "dotnet out/TokenG..."   34 minutes ago      Up 34 minutes       0.0.0.0:20002->5000/tcp   sf-8-cbcce7d2-5669-4cf1-baea-8e14b12cb127
bfec4345855e        sg1970/imgpub01     "dotnet out/TokenG..."   34 minutes ago      Up 34 minutes       0.0.0.0:20576->5000/tcp   sf-8-4c43b1b5-8adb-4b8e-9edd-5132c7bc817c

And I see this error on Event Viewer for docker :

fatal: Error starting daemon: pid file found, ensure docker is not running or delete C:\ProgramData\docker\docker.pid

**Comment by RajeetN** [comment]
correct. you cannot start it as a service. But you do not need to explicitly disable it either. Service Fabric will do the required steps here. For now, you can keeps the DOCKER_HOST, and get rid of it in the next release.

**Comment by sg1970** [comment]
@RajeetN Iam a little bit confused with the mechanics of things between SF and Docker Engine Service .... 

1. What is the purpose of the Docker Engine (Windows Service) and why does SF shut it down ?
2. Why where my docker commands **not working** when the SF Publish used to fail ? I thought the Docker Engine Service was necessary to run the docker commands (at least manually)  but seems that there is more to it.  Can you please clarify  this ?

So to clarify .... the docker commands (from command prompt) are working now even with the Docker Engine Service being down (just as in that previous personal VM where I had a sucessfull SF docker container publish ) .

**Comment by RajeetN** [comment]
Docker service is responsible for creating and managing containers. SF stops the service and restarts the daemon process so it can start it on a different port for communicating via REST. Your docker commands were not working because it tries to connect to the default named pipe that is no longer there since SF restarted docker engine to listen on different port. Like I mentioned earlier, this is fixed in upcoming release of SF so you wont have to connect via localhost:2375. Hope that clears things up for you.

Thx!

**Comment by mani-ramaswamy** [comment]
This has been fixed and you don't have to connect via localhost:2375 anymore. Closing this issue - please reopen if there are mroe issues.

**Comment by afedyashov** [comment]
@RajeetN, I think I'm seeing similar behavior now on Windows Server 2019 where in the process of local dev cluster deployment docker service is shutdown - and not able to start anymore due to named pipe access error:

````
  202179 Dec 02 17:42  Information docker                          2 debug: Calling HEAD /_ping
  202180 Dec 02 17:42  Information docker                          2 debug: Calling GET /v1.40/images/json
  202181 Dec 02 17:43  Information docker                          2 debug: daemon configured with a 15 seconds minimum shutdown timeout
  202182 Dec 02 17:43  Information docker                          2 debug: start clean shutdown of all containers with a 15 seconds timeout...
  202183 Dec 02 17:43  Information docker                          1 stopping telemetry service
  202184 Dec 02 17:43  Information docker                          2 debug: Clean shutdown succeeded
  202185 Dec 02 17:43  Information docker                          1 Daemon shutdown complete
  202186 Dec 02 17:43  Information docker                          2 debug: Stopping service: <nil>
  202207 Dec 02 17:55  Information docker                          1 Starting up
  202208 Dec 02 17:55  Error       docker                          4 fatal: failed to load listeners: open //./pipe/docker_engine: Access is denied.
  202209 Dec 02 17:55  Information docker                          1 Starting up
  202210 Dec 02 17:55  Error       docker                          4 fatal: failed to load listeners: open //./pipe/docker_engine: Access is denied.
````

I can see using process explorer that there is an instance of dockerd launched most liekly by the service fabric:
"dockerd" -H localhost:2375 -H npipe:// --debug --pidfile "C:\SfDevCluster\Data\_sf_docker_pid\132198128191215475_sfdocker.pid"

And if I setup DOCKER_HOST to match above command line's localhost -then docker works (docker info would complain that using TCP is insecure though).
But it won't work otherwise, and docker commands we have as part of build won't work.
Problem seems specific to Windows Server 2019.
