### ISSUE TITLE
Working with StateManager outside of a cluster

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/service-fabric-issues#174]
I'd like to be able to run some of tests that require `StateManager`. Use case: automated acceptance tests for components that utilize RCs.

Currently, the only way to do it is to mock it. For my scenario, I'd be interested to use a real thing to ensure the code is working with a real reliable collection and not a mocked version of it.

Is that something that is possible?

**Comment by vturecek** [comment]
No, not outside of the Service Fabric environment. The Reliable State Manager requires the Service Fabric runtime to operate properly. For isolation testing outside of the runtime, you have to provide a mock version of IReliableStateManager. This is by design.
