### ISSUE TITLE
Feature: stop/start service (all instances/replicas)

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/service-fabric-issues#175]
To be able to start/stop all instances/replicas of a given service w/o removing/re-deployment.

Has been requested on UserVoice as well: https://feedback.azure.com/forums/293901-service-fabric/suggestions/13714473-ability-to-stop-disable-services-without-removing

**Comment by Mansoor-Mohsin** [comment]
We've noted down the feature request. We'll consider it for the upcoming releases.

**Comment by masnider** [comment]
Ghost is @mansoormohsin, had a bit of an account kerfuffle.

**Comment by masnider** [comment]
@SeanFeldman checking back on this one, and wanted to get some more info: when you say "Removing/Re-Deployment" what specifically are you trying to avoid?

**Comment by masnider** [comment]
But what is the negative impact of "redeploying" that you're trying to avoid?

**Comment by SeanFeldman** [comment]
Unnecessary complexity and chances of things going sideways.
You don't uninstall and reinstall a Windows Service just to change some settings, you pause it 😉

**Comment by masnider** [comment]
You don't need to do that to change some settings for a service fabric service, either, You just upgrade it. That may or may not even require the service process to restart. 

Really trying to get to the bottom of what you're trying to accomplish here so we can see if we need to build something. You seem to be looking for a particular _solution_ , but what's the _problem_ ?

**Comment by SeanFeldman** [comment]
This was a while ago. We needed to pause services that were already deployed. Sorry @masnider, don't recall anything else.

**Comment by SeanFeldman** [comment]
I'm going to close not to drive you nuts as we ended up ditching that project...

**Comment by vikasparihar** [comment]
@SeanFeldman  Could you please reopen this as I need this feature . We are using service fabric as a back end job to  read messages from service bus queue. Whenever we have to deploy a new version we see loss of message  and in our current deployment model we need to wait for when the queue is not chatty. Is there a way i can stop a service so that it graciously ends up all threads. Today we delete the instance from dashboard before any new deployment but not sure if this is the right way and not lead to message loss.  I don't want to go into service bus reliability here but focus on having SF feature of start/stop like we have for Azure function apps. Even a powershell script capable of doing this will help

**Comment by SeanFeldman** [comment]
@vikasparihar I don't think message loss has to do with stopping and starting SF services.
Service Bus supports peek-lock mechanism. If a service instance is deleted, message just should go back to the queue.

**Comment by vikasparihar** [comment]
@SeanFeldman  We are reading message in peek lock mode only but have observed that during deployment  our messages are lost at times. We are using OnMessageAsync from ServiceBus Sdk (WindowsAzure.ServiceBus.3.4.5). Nonetheless i was looking for a capability to stop/start stateless services in Service fabric and was trying to get it prioritized by the team.

**Comment by SeanFeldman** [comment]
@masnider is the person to ping in that case.

**Comment by vikasparihar** [comment]
@masnider  Could you help reopen the issue and prioritize service start/stop as product feature

**Comment by masnider** [comment]
I would file your behavior with SB as a separate issue, we've seen other people successfully do what you're attempting without this feature and just with service create/delete. 

You might also just look at using some of the things the community has already built:

https://github.com/loekd/ServiceFabric.ServiceBus
https://github.com/ianrufus/BlogPosts/tree/master/ServiceBusTrigger
