### ISSUE TITLE
Problems with logging

### ISSUE THREAD

**Issue by EspenG** [Azure/service-fabric-issues#176]
One of our statefull partitions is having trouble. It's stuck throwing a NullReferenceException. http://pastebin.com/9yJn4pFG 
Earlier i have tried to fix the problem by removing the replica instance to no help. I have also seen a COMException "Log space is exhausted" http://pastebin.com/p9kTFa5v but the disk on the vm have many gb free.
Logging into the vm and looking in the event logs i also see this exception http://pastebin.com/U9MranJ2

The closes i have found online is this https://social.msdn.microsoft.com/Forums/sqlserver/en-US/cf917a60-a65c-4a0d-af3d-699aa9bb29ee/log-space-is-exhausted?forum=AzureServiceFabric but i don't think its related as my disk is not full.

Have tried, as mention earlier, to remove the replica instance and rebooting the vm, but nothing helps.

My service is still in this state so let me know if there is anything more that is needed.

**Comment by vturecek** [comment]
What Service Fabric version are you running on?

**Comment by EspenG** [comment]
In case someone else reads this issue in the future with the same problem:
Changing the target replica size to 4 and then back to 3 got our service out of this state.

**Comment by EspenG** [comment]
As far as i can tell this only happens on one of the nodes in the cluster, and only when creating a replica of this one service partition.

**Comment by masnider** [comment]
Hi @EspenG - unfortunately we were really slow to respond to you ( our bad :/ ) and so those pastes have expired. If you still have those errors kicking around that you can share, or a repro of this, we'd like a chance to take a look (and sorry again for the backlog).

**Comment by EspenG** [comment]
Sorry, but i don't have the errors any more.
