### ISSUE TITLE
Large response message or invalid serialization repeats service calls forever

### ISSUE THREAD

**Issue by HakanL** [Azure/service-fabric-issues#177]
I have two scenarios that causes the service fabric communication transport to retry a call to a service forever (it just tried over and over again, never stopping).
The first is if the service is throwing an exception that can't be serialized (or it may be deserialized on the caller, not sure where the error is happening). Then the client/caller will just repeat the call forever.
The second scenario is if we increase the MaxMessageSize on the service side, and then send a large response. If the client doesn't have the same/higher setting then it will throw some internal exception (not showing up anywhere) and it will retry the request, forever.

I think there should be some kind of mechanism to prevent this runaway behavior, like a retry limit.

**Comment by suchiagicha** [comment]
This issue is fixed in sdk 2.5X version .

**Comment by vturecek** [comment]
Thanks @suchiagicha, closing this one out. 
@HakanL can you upgrade your NuGet packages to 2.5.216 and feel free to re-open this if you're still running into the same problem.
