### ISSUE TITLE
DefaultServices in manifest disappears when service contains GeneratedIdRef="<guid>"

### ISSUE THREAD

**Issue by mikanyg** [Azure/service-fabric-issues#18]
We just upgraded to the latest SF SDK, aka. runtime and Visual studio tooling (v2.1.150). We have 3 applications that where upgraded. 2 of them worked just fine, but one started misbehaving.

The reason is the it contained 3 services where the Service instance registration in the application manifest each had an xml attribute like this GeneratedIdRef="some_guid". When building the solution the manifest was updated and the DefaultServices xml section and the Parameters section was left empty.

We have now removed the xml attribute and the manifest is no longer changed by the build target.

We are not entirely sure why this attribute was added (and what it does) in the first place, but can see samples on github and stackoverflow that also reference this attribute.

Information about its usage, and whether it has been deprecated would be appriciated.

**Comment by amanbha** [comment]
The GeneratedRefId is added by VS tooling to clean up the services from application manifest. It is needed to handle actor interface renames correctly from VS. Could you please check if you updated the nuget package as well? If the issue persists, I would like to take a look at the manifests and the installed tools with the SDK, for that you cam send me a msg (amanbha@microsoft.com) to set up sometime.

**Comment by vturecek** [comment]
@mikanyg are you still seeing this problem after updating the SF NuGet packages to 5.2?

**Comment by mikanyg** [comment]
Haven't seen this so I think it's safe to close.

**Comment by vturecek** [comment]
OK, thanks for confirming.
