### ISSUE TITLE
Yeoman generators are not working (Java + Docker)

### ISSUE THREAD

**Issue by yoanisgil** [Azure/service-fabric-issues#180]
According to [this link](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-linux-application-with-java) one must use Yeoman to get started using Java + Service Fabric, however the generators seems to be broken:

> ➜  service-fabric-linux-vagrant-onebox git:(master) ✗ yo azuresfjava
> Error azuresfjava
> 
> You don’t seem to have a generator with the name “azuresfjava” installed.
> But help is on the way:
> 
> You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
> Install them with npm install generator-azuresfjava.
> 
> To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.
> 
> If yo cannot find the generator, run yo doctor to troubleshoot your system.

This command also fails:

> 
> ➜  service-fabric-linux-vagrant-onebox git:(master) ✗ npm install generator-azuresfjava
> npm ERR! Darwin 16.4.0
> npm ERR! argv "/Users/ygil/.nvm/versions/node/v7.5.0/bin/node" "/Users/ygil/.nvm/versions/node/v7.5.0/bin/npm" "install" "generator-azuresfjava"
> npm ERR! node v7.5.0
> npm ERR! npm  v4.1.2
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/generator-azuresfjava
> npm ERR! 404
> npm ERR! 404  'generator-azuresfjava' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/ygil/Documents/Projects/service-fabric-linux-vagrant-onebox/npm-debug.log

The errors also applies to this:

This also applies to the Yeoman instructions described [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-container-linux)

**Comment by yoanisgil** [comment]
It looks like there generators are only available after installing the SDK

**Comment by mani-ramaswamy** [comment]
That is correct. You need the SDK installed to get the templates. If you are only doing container orchestration, you don't need to install the Java SDK.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux
