### ISSUE TITLE
Alternative approach to automatic package versioning

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#181]
The current `ServiceFabricUpdateAppVersions` build task automatically updates the package vesion according to build numbers. It also allows comparing code packages to the previous build, so services that have not changed would not be upgraded unnecessarily.

This approach has several disadvantages:
* PDBs cannot be included since they are always built non-deterministically
* Comparison only works if *every* build is deployed to the cluster, which is usually not the case for production clusters
* Versioning during build time (rather than release) does not mirror the release history
  * Additionally, other transformations to the package (such as applying configuration secrets) should be environment-specific
* Differential packages are not created (thus considerably slowing down deployment)

I propose a new build task that works a bit differently (I've already implemented this in our system):

* Version occurs during release
  * Append the release name to the application, service and config package versions
  * Hash all the files (*except* .pdb) in each code package, and append the hash to the code package version
  * Appending the release name to data packages is optional (since auto-updating them can be dangerous)
* Retrieve the currently deployed code package versions for each service and compare the hashes
  * If they are the same, **delete** the code package directory

For example:

```
App       1.0.0               1.0.0+Release-1
  Service   1.0.0               1.0.0+Release-1
    Code      1.0.0    ==>        1.0.0+789d620d85d370a72c042c9e024e3c16
    Config    1.0.0               1.0.0+Release-1
    Data      1.0.0               1.0.0
```

**Comment by aelij** [comment]
I've published a VSTS extension that works as described above:
https://marketplace.visualstudio.com/items?itemName=aelij.ServiceFabricTools

**Comment by masnider** [comment]
This is great! Adding some of our tooling folks to take a look and consider how much of this we could bake in.

**Comment by MikkelHegn** [comment]
I'll close this as @aelij extension is out there and available.

**Comment by aelij** [comment]
@MikkelHegn Considering what you me at Build, I'm thinking of splitting this into two separate tasks: one that does hash-based versioning (during build or release) and another that does diff packaging by comparing to a deployed Fabric (during release). WDYT?

**Comment by MikkelHegn** [comment]
@aelij: That makes sense - please consider if a PR to this task is possible? https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ServiceFabricUpdateAppVersions

**Comment by aelij** [comment]
@MikkelHegn I'll have a look when I get some free time
