### ISSUE TITLE
Unreliable transport helper warning

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#182]
Hi,

Our production cluster (five * Standard_D2_V2 nodes) has three nodes in a warning state with "UnreliableTransportHelper Warning:_default_0". We haven't had any issues reported though we're running a very light load at the moment.

It's a warning that's not documented or referenced as far as my googling can find. What actions should we be taking to investigate and resolve the underlying issue?

```
NodeName              : _default_0
AggregatedHealthState : Warning
UnhealthyEvaluations  :
                        Unhealthy event: SourceId='System.Testability', Property='UnreliableTransportHelper
                        Warning:_default_0', HealthState='Warning', ConsiderWarningAsError=false.

HealthEvents          :
                        SourceId              : System.Testability
                        Property              : UnreliableTransportHelper Warning:_default_0
                        HealthState           : Warning
                        SequenceNumber        : 131327957283384111
                        SentAt                : 2017-02-28 22:48:48
                        ReceivedAt            : 2017-02-28 22:49:01
                        TTL                   : 00:01:00
                        Description           : Unreliable transport behavior is active beyond threshold
                        time:BlockStatefulServiceReopen__default_0:
                        RemoveWhenExpired     : True
                        IsExpired             : False
                        Transitions           : Ok->Warning = 2017-02-28 03:23:41, LastError = 0001-01-01 00:00:00
```

Edit: There are no related events in Event Viewer at the time of transition `Ok->Warning` for that node. `CollectGuestLogs.exe` seems to consistently fail every hour but I am assuming that's not related.

Kind regards,
Nick

**Comment by LMWF** [comment]
Hi Nick,

Have you used FabricClient.TestManagementClient.InvokeQuourmLossAsync() [powershell equivalent: "Invoke-ServiceFabricPartitionQuorumLoss"] or FabricClient.TestManagementClient.StartPartitionQuorumLossAsync() [powershell equivalent: "Start-ServiceFabricPartitionQuorumLoss"] (please note the slight difference in the names - one has "Invoke" in the name and the other has "Start")?  If you did, can you please provide the value use for the "quorumLossDuration" parameter?

Are all your services healthy or are some in warning state?

Thanks

**Comment by NickDarvey** [comment]
We did, specifically `Invoke-ServiceFabricPartitionQuorumLoss`.

```
Invoke-ServiceFabricPartitionQuorumLoss -QuorumLossMode AllReplicas -QuorumLossDurationInSeconds 400 -PartitionId 00021a80-d21d-482f-9161-5f274f90e06c -ServiceName fabric:/Envoy/EventHubProcessor
```

When viewing under the `/Applications/App/AppInstance` branch of the cluster manager tree, they're all marked as healthy but looking down in to the replicas they are showing as `Unknown`. Browsing under the `/Nodes/Node` branch and in 'Deployed Applications' the applications have the health state of `Unknown`.

**Comment by LMWF** [comment]
Did that PowerShell cmdlet finish gracefully?  Or did it return an error, or was a ctrl+c entered while it was running?

To remove the warning, please run FabricClient.TestManagementClient.CleanTestStateAsync(), or its PowerShell equivalent Clean-ServiceFabricTestState.  Note if you have other Invoke-ServiceFabricPartitionQuorumLoss commands currently running, this will cause the other partitions to come out of quorum loss as well.

Could you also share logs with us, and indicate the time Invoke-ServiceFabricPartitionQuorumLoss was started?

Thanks

**Comment by NickDarvey** [comment]
I believe it returned an error so I ran `Remove-ServiceFabricTestState` as you and the docs mention. I just ran it again returns `CleanTestState operation succeeded` (which I'm pretty sure it returned last time).

We have the logs available in table storage and viewable in OMS. What's the best way to share them with you?

**Comment by LMWF** [comment]
Please create a support request here to share logs: https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request

If you ran Invoke-ServiceFabricPartitionQuorumLoss on a machine outside the cluster, please include the logs from that machine as well.  Also, please include the time (and timezone) Invoke-ServiceFabricPartitionQuorumLoss was executed.

Was Invoke-ServiceFabricPartitionQuorumLoss run on any other partitions?  Were there issues with those?

Thanks

**Comment by NickDarvey** [comment]
Restarting the nodes one-by-one resolved this issue.
