### ISSUE TITLE
[Reverse Proxy] WebSockets shutdown handshake is probably wrong

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#183]
It looks like every server or proxy implements shutdown handshake a different way.

My assumption is as follows: Web Sockets when proxied should be transparent to the client (Client -> Proxy -> Server should behave exactly the same way as Client -> Server from both: Server and Client perspective).

Let's consider following scenario:

Client -> Proxy -> Server

1. Client: connects to the Proxy
2. Proxy: receives ws connect attempt and tries to connect to the Server
3. Server: accepts connection from the Proxy
4. Proxy: accepts connection from the Client
....
5. Server: invokes CloseOutputAsync (initiated close handshake)
6. Proxy: receives Close from server and ....
(and now to scenarios)
- - -
a7. Proxy: Closes connection to the Server (handshake completed)
a8. Proxy: Closes connection to the Client (sends close handhsake to the client but terminates)
a9. Server: Receives Close and closes underlying connection (handshake completed)
a10. Client: Receives Close
...
a11. Client: Decides to complete close handshake and runs CloseOutputAsync()
//Exception is thrown as connection has been already closed so it means Proxy actually has killed the connection to the Client
- - -
b7. Proxy: Sends Close to the Client (initiates (forwards) handshake)
b8. Client: Receives Close
...
b9. Client: Decides to run CloseOutputAsync and closes connection to the Proxy (handshake completed)
b10. Proxy: Receives Close from the Client and closes connection to the Client (hanshake completed)
b11. Proxy: Closes connection to the server (handshake completed)
b12. Server: Receives Close from the Proxy and closes connection (handshake completed)

Now: In my opinion behavior 'a' is WRONG due to obvious reasons, however it is in both AspNetCoreModule for IIS aspnet/AspNetCoreModule#77 and it is also case in Service Fabric Reverse Proxy.

I am not 100% sure, but it seems Service Fabric Reverse Proxy is slightly better than AspNetCoreModule, because it completes one end properly. At point 7 it properly completes handshake where AspNetCoreModule doesn't do even that.

For reproduction you can use code from the: aspnet/AspNetCoreModule#77 . But you can add this line to the client because implementation is **slightly** better.
```
await client.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, null, CancellationToken.None);
```

I have implemented behavior 'b' in aspnet/Proxy#41 . If that's me who is wrong please let me know I will correct my implementation!

But this behavior is consistent with how WebSocket would behave if there was no proxy at all. Tested with Kestrel and HttpSys.

**Comment by kavyako** [comment]
We will look into this and get back to you. Thanks for the feedback..

Kavya.

**Comment by mkosieradzki** [comment]
@kavyako Thanks Kavya. Can you please confirm if this is a bug in Reverse Proxy?

**Comment by kavyako** [comment]
Reverse Proxy behavior is closer to what is outlined in "a", but there are few corrections:
a8. After Proxy sends Close handshake to the client, Reverse Proxy waits for a timeout duration (10 secs) before forcefully terminating the connection.
a11. So if the client responds with a close message within the timeout period, it should not see the exception.

In instances where you are seeing an exception on CloseOutputAsync(), is the CloseOutputAsync called immediately after it receives the close message or is there a delay?

**Comment by mkosieradzki** [comment]
@kavyako Thanks! I will check if that's what is happening. I might have accidentaly forced 10second timeout by using debugger.

**Comment by kavyako** [comment]
@mkosieradzki Did you get a chance to verify this?

**Comment by mkosieradzki** [comment]
@kavyako I apologize, but I have suspended my work on integrating websockets as it was causing too many problems in different areas. I will try to check it during the upcoming week.

**Comment by kavyako** [comment]
Hey didn't hear back from you. If you or anyone else is still experiencing this issue, then please reopen this issue or create a new one.
