### ISSUE TITLE
"Failed to update binding redirects - Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by mleyb** [Azure/service-fabric-issues#184]
Apologies if this has already been raised. 

Service fabric SDK 2.4.164

Repro steps:
- create new service fabric project in VS2015, adding a stateless web api service
- update nuget packages for solution
- select all update options (at the moment mainly Owin, Owin.Hosting, Owin.HttpListener & Newtonsoft.Json)
- apply the update
- Notice package manager output - "Failed to update binding redirects for (<<stateless web api project name>>). Object reference not set to an instance of an object"

**Comment by dbreshears** [comment]
Thanks for the feedback.  No answer at the moment, however I can repro and will look into it.  I don't repro in VS 2017 so looks specific to VS 2015 Update 3.

**Comment by dbreshears** [comment]
@mleyb .  Just confirming you are not blocked by this.  The issue is in the Nuget Package Manager. The binding redirects seem to updated exactly the same in both VS2015 and VS2017,  although 2017 doesn't emit the error you are seeing in the log.

**Comment by mleyb** [comment]
@dbreshears We've moved to VS2017 an I can confirm that the issue does indeed appear to be resolved. Thanks for your help on this, it's much appreciated :)

**Comment by fatherOfWine** [comment]
I've experiencing that issue too. Is there any consequences for that message? Could it be ignored?
I am using SDK and tooling 2.5.216  for VS 2015 update 3.

**Comment by dbreshears** [comment]
@fatherOfWine.   From my understanding,  It's a bug in the 3.4.x version of the Nuget package manager.  https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2015.    I don't know of any adverse consequences and I assume you can ignore.     The version in 2017 doesn't have the bug.  Perhaps the Nuget team can update the VS 2015 version on the marketplace to the a later version.    I created an issue on Nuget for this .

**Comment by fatherOfWine** [comment]
@dbreshears Thank you very much, sir, for the quick response. We will ignore that message for the time being and hope, that either we'll move to VS 2017 or update for the Nuget Manager will come out.:)
