### ISSUE TITLE
Azure cluster unable to bootstrap and achieve vote quorum after VMSS scale operations

### ISSUE THREAD

**Issue by dolly22** [Azure/service-fabric-issues#185]
We are experiencing problems on our test clusters after some (pretty rough) vmss scale operations to a state it's no longer able to boot up and bring it's nodes online.

As a side note - I'm not expecting service fabric cluster data and deployed services to survive the following scenario but I would expect the Arzure SF PaaS infrastructure to be able to eventually bring the cluster back online.

Also this state is quite hard to detect. The only indicating ETW messages (NodeDoesNotMatchFault) are logged at Information level. Also there is no clear indication in event log what might be the problem and why the nodes cannot be opened (there is only general FABRIC_E_TIMEOUT).

The only solution i know of is to completely redeploy cluster to Azure. Is there some better way to "reset" cluster vote nodes or to somehow reset vmss instances to start again at "_0" suffix to reinitialize the cluster?

**Steps to simulate the problem**
1. Create azure vmss service fabric cluster cluster with 3 instances
2. Change vmss instance count (sku/capacity) to 0
3. Wait a few seconds till vmss instances start to shut down
4. Change vmss instance count (sku/capacity) back to 3

**Cluster behavior**

- Cluster endpoint (https://westeurope.servicefabric.azure.com/runtime/clusters/{guid}) returns manifest containing old vote nodes (probably for a good reason) ...
```
<Infrastructure>
  <PaaS>
    <Roles>
	<Role RoleName="nt1vm" NodeTypeRef="nt1vm" RoleNodeCount="3" />
    </Roles>
    <Votes>
	  <Vote NodeName="_evzp-itest-sfabric_0" IPAddressOrFQDN="10.1.1.4" Port="1025" />
	  <Vote NodeName="_evzp-itest-sfabric_1" IPAddressOrFQDN="10.1.1.5" Port="1025" />
	  <Vote NodeName="_evzp-itest-sfabric_2" IPAddressOrFQDN="10.1.1.6" Port="1025" />
    </Votes>
  </PaaS>
</Infrastructure>
```
- VMSS reuses IP addresses for new nodes with different InstanceId. In my case vmss nodes evzp-itest-sfabric_5, evzp-itest-sfabric_6, evzp-itest-sfabric_7 with IP addresses 10.1.1.4, 10.1.1.5, 10.1.1.6 respectively.

- Cluster starts with "wrong" (stale) votes

```
Updating Votes/60e78d59691842cae1bd812e99b31266
Updating Votes/95b878e3d1d8d596d97db763c725eb3c
Updating Votes/fe529cb33c03a17379f95f86ce5941d1
```

- Stange things start to happen...

```
RoutingTable
d065011a19d5d8a00a3197a540576705 consider 7be477fa05a103175321b256b5efd619:131333019899767752,B,10.1.1.6:1025 result [7be477fa05a103175321b256b5efd619:131333019899767752,B,10.1.1.6:1025,empty:0,9223372036854775807,2017-03-06 19:27:59.534]
d065011a19d5d8a00a3197a540576705 consider 361fb6efae4218279b898a6276fa6b44:131333020418126261,B,10.1.1.5:1025 result [361fb6efae4218279b898a6276fa6b44:131333020418126261,B,10.1.1.5:1025,empty:0,9223372036854775807,2017-03-06 19:27:59.534]

P2P
d065011a19d5d8a00a3197a540576705 send message VotePing to 95b878e3d1d8d596d97db763c725eb3c:0 id {9811825c-f601-42dd-bd20-1ea2c3a876ea}:15 false (0)
d065011a19d5d8a00a3197a540576705 receive message NodeDoesNotMatchFault from 7be477fa05a103175321b256b5efd619:131333019899767752 id {4d0eabf2-3ac5-4f95-84a4-753c916e78d1}:266 false (0)

SiteNode
[d065011a19d5d8a00a3197a540576705:131333020791281134] Received Fault message from 7be477fa05a103175321b256b5efd619:131333019899767752 with ErrorCodeValue of P2PNodeDoesNotMatchFault. Original message was targeted to 95b878e3d1d8d596d97db763c725eb3c:0.

P2P
d065011a19d5d8a00a3197a540576705 receive message VotePing from d065011a19d5d8a00a3197a540576705:131333020791281134 id {9811825c-f601-42dd-bd20-1ea2c3a876ea}:26 false (0)
d065011a19d5d8a00a3197a540576705 send message NodeDoesNotMatchFault to d065011a19d5d8a00a3197a540576705:131333020791281134 id {9811825c-f601-42dd-bd20-1ea2c3a876ea}:44 false (0)
d065011a19d5d8a00a3197a540576705 receive message NodeDoesNotMatchFault from d065011a19d5d8a00a3197a540576705:131333020791281134 id {9811825c-f601-42dd-bd20-1ea2c3a876ea}:44 false (0)

```

- Node bootstrap never completes, node does not start listening on port 19000 and fails to open

```
Bootstrap
d065011a19d5d8a00a3197a540576705 owned 0 votes, firstIndex -1: 
60e78d59691842cae1bd812e99b31266@d065011a19d5d8a00a3197a540576705:false,0,0
95b878e3d1d8d596d97db763c725eb3c@d065011a19d5d8a00a3197a540576705:false,0,0
fe529cb33c03a17379f95f86ce5941d1@d065011a19d5d8a00a3197a540576705:false,0,0

FabricNode
Node name: _evzp-itest-sfabric_5 has failed to open with upgrade domain: 0, fault domain: fd:/0, address: 10.1.1.4, hostname: nt1vm000005, isSeedNode: false, versionInstance: 5.4.164.9494:1, id: d065011a19d5d8a00a3197a540576705, dca instance: 131333072199155674, error: FABRIC_E_TIMEOUT

```

- The cluster never comes back online. Service Fabric is repeatedly reinstalled and reconfigured by ServiceFabricNodeBootstrapAgent on vmss nodes...

**Comment by masnider** [comment]
This was Bronze, I suspect, where actions like "scale down the cluster to 0" would even be allowed. If this is happening on higher durability/reliability levels then we'd consider it more of a problem, though I get that this is frustrating. If you can repro this in a higher safety level please let us know as that would be a big problem. In the meantime I'll get a couple other folks to chime in on if there is a good way to get out of this situation.

**Comment by masnider** [comment]
Hi @dolly22 - sorry for the delay in getting back to you :( In general there's not a great way to recover from this. Were you able to validate that doing this sort of thing is impossible on higher reliability/durability levels?

**Comment by ChackDan** [comment]
In a production scenario, you should never scale down to less than 5 nodes. If the min number of healthy nodes falls below 3 nodes, the cluster will go down. the ability for the cluster to come back, will be determied by the state left on the local drives, when a quorum of nodes do come back. 

In azure, when you scale a VMSS down , basically, you are basically deleting the VM and all its contents. So even if you scale the VMSS back up, the VM that shows up, is a brand new with a clean local drive, ie no State. I hope this explains a lot of your observations.

**Comment by dolly22** [comment]
@masnider I tried with higher reliability levels (5 node silver and 7 node gold) with bronze durability both with the same bahavior - no platform protection for "dangerous" scaleset operations. I was not able to verify at gold durability level due to minimal required VM size pricing.

@ChackDan The problem is mainly with seed nodes. I can even create 7 node cluster through azure portal (gold reliability level with 7 seed nodes is created). When you scale such cluster down to 3 nodes it fails and shuts down (seed node vote quorum is lost)

The only operation on service fabric vmss nodes i'm NOT allowed to do is probably "Reimage". I can still change the vmss size, delete, reboot and deallocate instances.

It seems to me that with current state how vmss allocates ip addresses and instance names for new nodes it might impossible to recover/recreate original seed nodes. See the following hypotetical scenario and please correct me where i'm wrong.

**my observation**: when vmss allocates new instance it uses next free node name (next number after highest number used) and first (lowest) available ip address from assigned subnet.

**my observation**: service fabric cluster manifest seed nodes are determined when cluster is created and fixed for the cluster lifetime.

1. Create 5-node SF cluster through azure portal (with mostly default settings)

5-node silver reliability cluster is created with following nodes:
```
_node_0	10.0.0.4
_node_1	10.0.0.5
_node_2	10.0.0.6
_node_3	10.0.0.7
_node_4	10.0.0.8
```

Cluster manifest seed nodes:

```
<Votes>
  <Vote NodeName="_node_0" IPAddressOrFQDN="10.0.0.4" Port="1025" />
  <Vote NodeName="_node_1" IPAddressOrFQDN="10.0.0.5" Port="1025" />
  <Vote NodeName="_node_2" IPAddressOrFQDN="10.0.0.6" Port="1025" />
  <Vote NodeName="_node_3" IPAddressOrFQDN="10.0.0.7" Port="1025" />
  <Vote NodeName="_node_4" IPAddressOrFQDN="10.0.0.8" Port="1025" />
</Votes>
```

2. Add two more instances to the cluster (```az vmss scale --new-capacity 7```) just to maintain enough (>5) nodes so target replica sizes are met.

```
_node_5	10.0.0.9
_node_6	10.0.0.10
```

3. Delete instance 0 from vmss (```az vmss delete-instances --instance-ids 0```) for whatever reason (os failure, i messed up something on that instance, ...)

**my hypothesis**: Cluster size is still >5 nodes, but i have permanently lost one seed node (_node_0) as there is no way how to recreate _node_0 with original ip adress through vmss ARM api.

From service fabric explorer point of view instance __node_0_ state is now _Down_ and my only viable option is to remove this node in sf to bring cluster back to full green state.

4. Add new node to vmss cluster (```az vmss scale --new-capacity 7```) 

Newly created node reuses now available subnet ip adress and first errors from original post (NodeDoesNotMatchFault) appear in logs.
```
_node_7	10.0.0.4
```

5. Repeat steps 3 and 4 and substitute instance 0 with any other seed node (1,2,3,4) - we chose for example instance 1 (```az vmss delete-instances --instance-ids 1```).

Again new node is created and ip adress of deleted instance is reused.
```
_node_8	10.0.0.5
```

6. Pick another seed node instance (2,3,4) and delete it - we chose instance 2 (```az vmss delete-instances --instance-ids 2```)

Before this operation cluster had 7 green nodes and full green state. After this instance is deleted cluster goes down after some time (symtoms same as in original post). There is no way for you to recover the cluster.

We just lost seed node vote quorum. From cluster manifest seed nodes (_0, _1, _2, _3, _4) only nodes _3 and _4 exist. On removed node (_0, _1) ip addresses are now nodes (_7, _8)

**Comment by alecor191** [comment]
Hi! Any thoughts the SF team could share about the above? For us this is a blocker to go into production with ASF. 

The issue is that if a seed node dies (for whatever reason), our cluster is unusable (removing non-seed nodes works fine).

It would be great if someone could share some thoughts on the above as well as if there is a way to add more seed nodes after initial deployment (or converting a non-seed node into a seed node).

**Comment by EspenG** [comment]
Any updates on this?

**Comment by ChackDan** [comment]
1) If you intend to reduce the reliability of your cluster from gold, to bronze, then do that operation first before scaling down the VMSS instances. This will reduce the Seed node count to 3.
2) If a certain node is lost and you know it is not coming back, then call https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricnodestate?view=azureservicefabricps  on that node. The system will then reallocate a seed node in the primary node type (if possible). This operation is slow, and should be performed one node at a time, especially, when the node is a seed node. If the safety of the cluster is at stake, then the operation will most likely get blocked. In general, Failover Manager does not allow operator initiated unsafe operations in the cluster. 
3) I do not want to get into discussions on Seednodes etc, since there is more involved at the federation and transport layer than just the number of seednodes. If you are trying to remove a seednode to try and simulate an azure scenario, where say node1 is migrated from one host to another, you can be assured that this operation happens regularly. The underlying azure infra just moves the Node1 VM to another host and SF gets bootstrapped in the new VM that comes up on the new host. the new VM, get the same identity (IP and name) and so this operation just works without incident. 

hope this helps. If there are more questions, i suggest you bring them up at our monthly customer calls. we can explain it by drawing some diagrams and it will be more interactive.

watch https://blogs.msdn.microsoft.com/azureservicefabric/ for the next Q&A announcement.

**Comment by masnider** [comment]
Fundamentally this operation would be blocked by management operation safety checks if the durability tier of the cluster is Silver or higher. 

If you really want to be able to delete the cluster or scale down to 0 and keep data, we recommend managed storage disks, but this would still require the cluster to be redeployed.
