### ISSUE TITLE
Is there a way to foward local env var to container?

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#186]
We have some settings from host env variable. Guest executable can read host env variables just fine, but I cannot figure out how to pass on the host env variables to my service once I put my service inside container.
I know the `< EnvironmentVariable >` tag can be used to forward `Parameter` to environment variable within container. But what about from other sources?

**Comment by msfussell** [comment]
For env variables usage for all service types including containers see this article https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-manage-multiple-environment-app-configuration#specifying-environment-specific-parameters

For code example for containers see the sample here https://github.com/Azure-Samples/service-fabric-dotnet-containers 

specifically these files

https://github.com/Azure-Samples/service-fabric-dotnet-containers/blob/master/Windows/src/Container.Application/ApplicationPackageRoot/ApplicationManifest.xml

https://github.com/Azure-Samples/service-fabric-dotnet-containers/blob/master/Windows/src/Container.Application/ApplicationPackageRoot/FrontEndServicePkg/ServiceManifest.xml

**Comment by RajeetN** [comment]
Like Mark mentioned the only way to pass environment variables into containers is through EnvironmentVariable tag. GuestExes are different in the sense that they inherit the parent process's environment block but containers only get a predefined set of environment variables in addition to whatever is specified in <EnvironmentVariable> tag.

**Comment by qrli** [comment]
So, if I understand correctly:
* <`EnvironmentVariable`> can only take hard-coded value or value from `parameter`.
* There is no other way to pass variables to containers.

So I cannot pull settings from either host machine or Consul/etcd server at runtime or setup entry runtime. The settings must be applied at publish time. I'll think what I can do.

**Comment by VipulM-MSFT** [comment]
@qrli - you can pull the configuration from external system in to a file that you save on the work directory. We mount the work directory in the container and provide its path in the environment variable Fabric_Folder_App_Work as listed in the document - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-manage-multiple-environment-app-configuration#specifying-environment-specific-parameters. You can then access them from the file in the container.

**Comment by qrli** [comment]
@VipulM-MSFT Thanks for the updated info and doc.

But I didn't quite get what you mean. As I understand, the app folders are created by service fabric with increasing number suffix, so there is no way to know the app folder until setup entry or entry program is executed. But the setup entry and entry run inside container, so I don't see a way to pull settings and save in the Fabric_Folder_App_Work folder outside of container. I must be wrong at some point, aren't I?

**Comment by artisticcheese** [comment]
Why is this closed? Service Fabric is being pushed as a good container orchestrator solution and this is pretty basic requirement which other orchestrators support out of the box for quite sometime. This shall be reopened

**Comment by harahma** [comment]
@artisticcheese This is not closed. This capability already exist. What Vipul meant is that you can specify your setup entry point which is an executable and your main entry point is a container. Your setup entry point can extract the environment information and put that into a file under application's work directory. When the main entry point container comes up it can read that file to get environment information.

**Comment by harahma** [comment]
A work directory applies to your application so it will be same for your setup and main entry point. The environment variable Fabric_Folder_App_Work will point to same directory for both.
 
When a code package comes up, it will first run the setup entry point and then the main entry point. 
You will generate and write to your file in your setup entry point and read the same file in your container main entry point.

**Comment by artisticcheese** [comment]
So how do I do template base deployment in such cases to pass information to local docker system like it's being done in compose (https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates). As you can see from doc above every container which will be created in swarm will be have a specific name following template mentioned. Per your notes the only things which can be passed to a container is a text file in working folder but this is not sufficient to modify behavior of container runtime itself (like container name itself for example).

**Comment by VipulM-MSFT** [comment]
@artisticcheese - could you clarify the requirements? Every container gets Fabric_..environment variables that provides the identity for the container. 

The original issue was about passing the value of the environment variables from the host to the container. The setup entry point methods works for that.

**Comment by artisticcheese** [comment]
You have environment variable called `Foo` which is defined on service fabric host. You want to pass that environment variable and it's value to a container which runs on this host as an environment variable. How do you do that in Service Fabric. It's possible to do in other orchestrators.

**Comment by artisticcheese** [comment]
Please close this case. I will create another requirement for modifying start up option for docker itself to allow to modify parameters of actual container like swarm does (https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates)
