### ISSUE TITLE
Concurrent Queue and .Net Core roadmap

### ISSUE THREAD

**Issue by francescocristallo** [Azure/service-fabric-issues#187]
Is there a roadmap for supporting Concurrent queues and .Net core Framework (not the full, just the core)?
I have a super high throughput API that would like to migrate using .NetCore framework in Service Fabric as "native" reliable service (non Guest exec) file, and would like to have an Idea to when it will be supported.

About concurrent queues, the queues available now even if partitioned in 10.000 partitions, when some get hit very often it became unusable compared to Service Bus or Storage Queues, the write and the "receiver" collide very often. These two features are the only one I miss to migrate all my projects to this amazing technology.
Thanks

**Comment by masnider** [comment]
Regarding the second issue around the "instability" can you provide more information? Timeline for the ReliableConcurrentQueue is expected to GA in the next few months.

**Comment by vturecek** [comment]
The SDK will eventually be built against .NET Standard 2 rather than full .NET Framework, but I don't have a precise timeline on that yet.

**Comment by alecor191** [comment]
Hi @vturecek. Would you be able to share a rough timeline for ASF SDK support of `netcoreapp2.0`? 

As it was announced that ASP.NET Core 2.0 will only support `netcoreapp2.0`, we're currently a bit concerned: We have several dozen ASP.NET Core 1.1 services (currently on full .NET framework) that we're in the process of migrating to ASF (using ASF NuGet SDK packages for deep integration). Eventually we would like to migrate them to 2.0 (which would not be possible if ASF SDK requires full .NET framework).

I found a [comment](https://github.com/Azure/service-fabric-issues/issues/255#issuecomment-298154139)  from @aL3891 indicating that the timeframe for ASF SDK support for `netcoreapp2.0` would be Q3. Are you able to confirm that?

**Comment by vturecek** [comment]
@alecor191 Yes we're targeting .NET Standard 2.0 support no later than Q3, possibly sooner. At that point your services will be able to target netcore 2.0. 

ReliableConcurrentQueue is available now in the 5.6 release.

Hope that helps, feel free to re-open if you need more info.
