### ISSUE TITLE
XML Documentation file is not included in .netcore built apps

### ISSUE THREAD

**Issue by danzel** [Azure/service-fabric-issues#190]
When you enable XML Documentation on a project that is part of a service fabric application, the resulting .xml file is not included with the service fabric app, preventing tools that use it (like Swashbuckle) from working.

This worked correctly with VS2015 and the old .netcore tools, the issue has only started with VS2017 and the new .netcore tools. (I'm using the VS2017 RTM release)

If you create a Service Fabric application with a normal .net project the XML Documentation is included in the build.

Possibly related to #159, there are some notes in https://github.com/Azure/service-fabric-issues/issues/159#issuecomment-284705807

### Steps to reproduce (in VS2017)

File, New Project
Service Fabric Application
ASP.Net Core (Preview)
ASP.Net Core 1.0 (Version doesn't matter, happens on 1.0 and 1.1)
Web API (Haven't tested others, but assume it will reproduce with others)
Authentication: None

Right click Web1, Properties
Build page
[x] Xml documentation file (Enable this)

Save All
Start

App will build. If you check the `Web1\bin\Debug\net452\win7-x64` folder you will see the `Web1.xml` file.
If you check the SfDevCluster deployed folder (`C:\SfDevCluster\Data\_App\_Node_0\CorefailType_App32\Web1Pkg.Code.1.0.0` in my case), the XML file is not included.

**Comment by alzuma** [comment]
+1

**Comment by espenruud** [comment]
+1

**Comment by FelschR** [comment]
I noticed that the XML documentation files for dependencies get deployed. Only the documentation of projects that get deployed are missing.

Might be helpful info for resolving this issue.

**Comment by ravipal** [comment]
The Service Fabric package internally uses dotnet publish which doesn't publish the XML documentation due to the issue https://github.com/dotnet/sdk/issues/795.

**Comment by tristal** [comment]
Is there a workaround that we can use in the interim?

**Comment by vdevappa** [comment]
+1

**Comment by masnider** [comment]
As found by @ravipal this is really due to a change in how documentation got published for asp.net projects. There's a good repo [here ](https://github.com/spboyer/copydocfile-example) listing the options that folks can use (unless and until such a time this is changed back or a different option is provided). The good news is it's just MSBuild. 

Since there's an example with instructions and since this isn't strictly a SF issue, I'm going to close this item.

**Comment by mattfrear** [comment]
I have followed the example at https://github.com/spboyer/copydocfile-example

```
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\$(Configuration)\$(TargetFramework)\*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>
```
This works if I do a `dotnet publish` at the command line - I can see the XML file in the publish folder.
However, it doesn't work for Service Fabric - I right click the Service Fabric project in Visual Studio -> Package. Navigate to the resulting package, into the Code folder, and there's no XML file present.

Has anyone got this working using Service Fabric? Like OP, I want the XML file for Swashbuckle.

**Comment by ben-kotvis** [comment]
This works for me in Service Fabric

`<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>`
