### ISSUE TITLE
Uninstalling Service Fabric Runtime 5.4.145.9494 Fails

### ISSUE THREAD

**Issue by kenlefeb** [Azure/service-fabric-issues#191]
Before installing the new version of the Service Fabric Runtime, the WPI installer throws an error while trying to uninstall the previous version I had already installed. The error on the WPI dialog says:

> Microsoft Azure Service Fabric Runtime - 5.4.164
> This product did not install successfully: Failed to unregister DLL with PerfMon. (-2147024882   ESE      )

Clicking the "View log here" link and searching for this error, I find the first mention appears to be these lines:

> MSI (s) (18:4C) [11:06:05:187]: Executing op: ActionStart(Name=UnregisterPerfmon,,)
> CustomAction RemoveTraceSession returned actual error code -2144337918 but will be translated to success due to continue marking
> MSI (s) (18:4C) [11:06:05:188]: Executing op: CustomActionSchedule(Action=UnregisterPerfmon,ActionType=3073,Source=BinaryData,Target=UnregisterPerfmon,CustomActionData=ESE)
> MSI (s) (18:50) [11:06:05:190]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI3E26.tmp, Entrypoint: UnregisterPerfmon
> MSI (s) (18:F0) [11:06:05:190]: Generating random cookie.
> MSI (s) (18:F0) [11:06:05:192]: Created Custom Action Server with PID 17980 (0x463C).
> MSI (s) (18:7C) [11:06:05:212]: Running as a service.
> MSI (s) (18:7C) [11:06:05:213]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
> UnregisterPerfmon:  Error 0x8007000e: failed to unregsister with PerfMon, DLL: ESE
> MSI (s) (18!DC) [11:06:05:237]: Product: Microsoft Azure Service Fabric -- Error 26252. Failed to unregister DLL with PerfMon.  (-2147024882   ESE      )
> 
> CustomAction UnregisterPerfmon returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> MSI (s) (18:4C) [11:06:05:241]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
> Action ended 11:06:05: InstallFinalize. Return value 3.
> Action ended 11:06:05: INSTALL. Return value 3.

This is, of course, preventing me from proceeding. Is there a way to manually uninstall the previous version of the runtime?

**Comment by oanapl** [comment]
The error you pasted above, -2147024882, is "out of memory". Can you check your memory?

**Comment by kenlefeb** [comment]
I tried rebooting and initiating the uninstall immediately after booting. Task Manager reports a little over 23GB of memory available (26% used). I'm thinking that's a misleading error code. :)

**Comment by mattrowmsft** [comment]
This sounds like a corrupted perf ctr registry.  Essentially the corruption causes the process to blow up in memory when trying to remove an entry from the index.

You will need to run 'lodctr /R' to recover the performance counter registry on your system. Depending on your system, you might need to run lodctr from c:\windows\syswow64 and c:\windows\system32.

**Comment by VipulM-MSFT** [comment]
@kenlefeb - any update on the issue? Is it ok to close this?

**Comment by vturecek** [comment]
Closing this one out, feel free to re-open if run into it again.
