### ISSUE TITLE
Unable to start service fabric cluster in linux local machine

### ISSUE THREAD

**Issue by smaldeniya** [Azure/service-fabric-issues#193]
Hi
I am new to service fabric and azure. Trying to set up my local Ubuntu machine dev env according to below guide.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux

When i execute
 sudo /opt/microsoft/sdk/servicefabric/common/clustersetup/devclustersetup.sh

it hangs around and failed with below message in /var/log/syslog.

> Mar 13 18:27:30 sahanm-Vostro-3559 starthost.sh[8599]: /opt/microsoft/servicefabric/bin/starthost.sh: line 19:  8812 Aborted                 (core dumped) /opt/microsoft/servicefabric/bin/FabricHost -c -skipfabricsetup
Mar 13 18:27:30 sahanm-Vostro-3559 systemd[1]: servicefabric.service: Main process exited, code=exited, status=134/n/a
Mar 13 18:27:43 sahanm-Vostro-3559 systemd[1]: servicefabric.service: Unit entered failed state.
Mar 13 18:27:43 sahanm-Vostro-3559 systemd[1]: servicefabric.service: Failed with result 'exit-code'.
Mar 13 18:27:48 sahanm-Vostro-3559 systemd[1]: servicefabric.service: Service hold-off time over, scheduling restart.
Mar 13 18:27:48 sahanm-Vostro-3559 systemd[1]: Stopped ServiceFabric Daemon.
Mar 13 18:27:48 sahanm-Vostro-3559 systemd[1]: Started ServiceFabric Daemon.
Mar 13 18:27:49 sahanm-Vostro-3559 starthost.sh[9815]: Starting FabricHost
Mar 13 18:27:49 sahanm-Vostro-3559 starthost.sh[9815]: Starting tracing session

**Comment by mani-ramaswamy** [comment]
Thanks for reporting this.  Can you please retry with the latest SDK @ https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/21/release-of-sdk-preview-0-8-0-0-and-runtime-preview-5-5-0-2-for-linux/?

We had a few fixes and if the latest SDK doesn't work we'll have to dig into this more. We might need to get some traces as well...

**Comment by mani-ramaswamy** [comment]
BTW, please also clarify that you are running on Ubuntu 16.04?

**Comment by masnider** [comment]
Hi @smaldeniya - any info that you can provide? Were you able to get this working with @mani-ramaswamy 's instructions? 

We haven't heard from you in a bit and there's lots of examples of this working so I don't think anything intrinsic is going on. If you can repro this and are still having problems, let us know. Otherwise if we don't hear back from you we'll close down the incident (and presume you are happily plugging away :) ). Please let us know.

**Comment by smaldeniya** [comment]
forgive me for the late reply. I'm not using sf anymore and was not following the thread.

the error shown above was on 16.04 Ubuntu development environment. after i gave re installed everything it was gone. but due to some other reasons like document db not available in linux etc, i ve setup windows vm as dev env 

thanks again for the reply

**Comment by mani-ramaswamy** [comment]
closing the thread since we were not able to repro this.
