### ISSUE TITLE
[Question] How should look a minimal ServiceFabric project file in VS2017 using the new SDK?

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#194]
How should look a minimal ServiceFabric project file in VS2017 using the new SDK?

Something like that is not enough:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric" Version="5.4.164" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="2.4.164" />
  </ItemGroup>

</Project>
```

**Comment by ravipal** [comment]
We are working on to support this project format. Will update once we have more information.

**Comment by mkosieradzki** [comment]
Got a working solution based on Microsoft.NET.Sdk.Web workaround from #314 .

Works perfectly even for Stateful services.

BTW. When trying to upgrade your project don't forget to delete bin and obj and add this project as x64 configuration to the ConfigurationManager.
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <OutputType>Exe</OutputType>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PackageRoot\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="2.6.220" />
  </ItemGroup>

</Project>
```

**Comment by Igorbek** [comment]
@ravipal any update on this?

**Comment by ravipal** [comment]
The latest release supports the PackageReference with some limitations. All core services and ASP .Net (both core and .net) services are using PackageReferene. The .Net Framework services are still using package.config format. But you could manually update it to use PackageReference.

**Comment by Igorbek** [comment]
Thank you!

**Comment by chuanboz** [comment]
@ravipal , do you have an example of sfproj that used PackageReference and not project package.config?
for example, what SDK do you use with that PackageReference? and what's the additional change needed for the old style import for Microsoft.VisualStudio.Azure.Fabric.Application.props?

**Comment by ravipal** [comment]
@chuanboz only the service project's are supporting the package reference. The application *sfproj doesn't support package references, it should use the package.config.

**Comment by chuanboz** [comment]
thanks both, I want the application *sfproj to support PackageReference so that I could leverage the default build target from those package reference. let me continue the discusson on the #558 one.
