### ISSUE TITLE
[AzureChinaCloud] Unable to connect with Service Fabric Cluster using -AzureActiveDirectory

### ISSUE THREAD

**Issue by Pradebban** [Azure/service-fabric-issues#195]
Am using the below command, and getting exception, 

Command Used: 

**Connect-ServiceFabricCluste**r -ConnectionEndpoint $ClusterConnectionEndpoint -serverCertThumbprint $PrimaryClusterKVThumbprint **-AzureActiveDirectory** -SecurityToken $accessToken

Connect-ServiceFabricCluster : The specified credentials are invalid.
At line:1 char:1
+ Connect-ServiceFabricCluster -ConnectionEndpoint $ClusterConnectionEndpoint -ser ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException
    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster

**Note**: AzureActiveDirectory seems to be defaulted to global azure.
$accessToken - is a valid Securitytoken, however the authentication fails. 
The command even fails without - SecurityToken (when trying to use interactive mode) 

Thanks,
Pradebban Raja

**Comment by masnider** [comment]
@linggengmsft who can chime in about what may be going wrong here

**Comment by linggengmsft** [comment]
In MoonCake environment, the following regional AAD metadata need to be set:

<Parameter Name="AADLoginEndpoint" Value="https://login.partner.microsoftonline.cn" />
      <Parameter Name="AADTokenEndpointFormat" Value="https://login.partner.microsoftonline.cn/{0}" />
                    <Parameter Name="AADCertEndpointFormat" Value="https://login.partner.microsoftonline.cn/{0}/federationmetadata/2007-06/federationmetadata.xml" />

You would also need to use the "-Location china" when using AAD tenant setup tool.

**Comment by Pradebban** [comment]
Was able to access the cluster after upgrading the cluster with the below settings.

"fabricSettings": [
          {
            "parameters": [
              {
                "name": "ClusterProtectionLevel",
                "value": "EncryptAndSign"
              },
              {
                "name": "**AADLoginEndpoint**",
                "value": "**https://login.partner.microsoftonline.cn**"
              },
              {
                "name": "**AADTokenEndpointFormat**",
                "value": "**https://login.partner.microsoftonline.cn/{0}**"
              },
              {
                "name": "**AADCertEndpointFormat**",
                "value": "**https://login.partner.microsoftonline.cn/{0}/federationmetadata/2007-06/federationmetadata.xml**"
              }
            ],
            "name": "Security"
          }
