### ISSUE TITLE
ErrorAction preference (SilentlyContinue) does not work for Get-ServiceFabricService

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#196]
### Cmdlet(s)
Get-ServiceFabricService

### PowerShell Version
4.0

### OS Version
6.3.9600.17400

### Description

ErrorAction preference of -SilentlyContune does not work for command Get-ServiceFabricService on failure cases.

Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction **SilentlyContinue**

### Debug Output

>> Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden/Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue -debug
VERBOSE: System.Fabric.FabricElementNotFoundException: Application not found ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BDD
VERBOSE:    at System.Fabric.Interop.NativeClient.IFabricQueryClient7.EndGetServiceList2(IFabricAsyncOperationContext context)
VERBOSE:    at System.Fabric.FabricClient.QueryClient.GetServiceListAsyncEndWrapper(IFabricAsyncOperationContext context)
VERBOSE:    at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
VERBOSE:    --- End of inner exception stack trace ---
**Get-ServiceFabricService : Application not found**
At line:1 char:1
+ Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabricService], FabricElementNotFoundException
    + FullyQualifiedErrorId : GetServiceErrorId,Microsoft.ServiceFabric.Powershell.GetService

### Script/Steps for Reproduction

1. Connect to Service Fabric Cluster
2. Run the below command when Application is not deployed yet.
Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue

Thanks,
Pradebban Raja

**Comment by oanapl** [comment]
Thank you for reporting. I opened a bug to track the issue on our side.
@heeldin, FYI.

**Comment by heeldin** [comment]
The only way around this now is to use a try and catch.
You can also change the ErrorActionPreference to silentlycontinue which is a global change and not recommended.

We do not support the silentlycontinue yet in our powershell cmdlets since we throw terminating errors.
