### ISSUE TITLE
Unable to determine whether the application is installed on the cluster or not

### ISSUE THREAD

**Issue by stankovski** [Azure/service-fabric-issues#199]
Almost every other day my local SF cluster (running latest build) would get into the state where I can’t connect to it. To resolve the issue I need to stop and start it again. Sometimes even that doesn’t help and I need to reboot. Not sure if this is a known issue, but I would be glad to provide logs/dumps if necessary.
 
```10>Started executing script 'Set-LocalClusterReady'.
10>Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1'; Set-LocalClusterReady
10>Launching Service Fabric Local Cluster Manager...
10>You can use Service Fabric Local Cluster Manager (system tray application) to manage your local dev cluster.
10>Finished executing script 'Set-LocalClusterReady'.
10>Time elapsed: 00:00:00.7288489
10>Unable to determine whether the application is installed on the cluster or not```

**Comment by mcgear** [comment]
I have been experiencing the exact same things.  For me it seems to have something to do with coming out of sleep.  I'll open and close my Surface Book many times through out the day, but then eventually i crack it open and i get this error.  I mostly have to reboot to resolve.

**Comment by brhinescot** [comment]
I get this too and it seems to be related to coming out of sleep. I'll see a message in the output that the api.exe process has exited with code 0 and the whole local cluster will be unresponsive. I haven't needed to reboot but resetting the local cluster gets it working again.

**Comment by arikanderu** [comment]
I am unable to run app in local SF cluster at all. Latest build, running under non-admin account.

**Comment by sumeshes07** [comment]
I too have the same issue, 'Unable to determine whether the application is installed on the cluster or not'. But after resetting the cluster also I go deployment failure. Then I figured out that the service manifest versions in the applicationmanifest.xml and servicemanifest.xml are different.

**Comment by jacobslusser** [comment]
```
1>------ Build started: Project: ConsumerApi, Configuration: Debug x64 ------
1>Build started 5/9/2017 1:43:33 PM.
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.43
2>------ Deploy started: Project: ConsumerApi, Configuration: Debug x64 ------
2>Started executing script 'GetApplicationExistence'.
2>Finished executing script 'GetApplicationExistence'.
2>Time elapsed: 00:00:00.1008585
2>Unable to determine whether the application is installed on the cluster or not
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```

Same problem for me but has nothing to do with "sleep". I've make sure the service manifest versions between applicationmanifest.xml and servicemanifest.xml are same as @sumeshes07 suggested. I've also tried repairing the Visual Studio installation.

Is there a log file anywhere that would get me more information? I suspect something PowerShell related, but I have literally nothing to go on other that what's pasted above.

**Comment by amanbha** [comment]
@Stankovski , @sumeshes07  Could you check if the cluster was up and running when the machine woke up from sleep, you can check by running Connect-ServiceFabricCluster from a PS.
Also could you provide traces from the <FabricLogRoot>\Traces folder. <FabricLogRoot> is the path in reg value FabricLogRoot in key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric

**Comment by jacobslusser** [comment]
I've made sure the cluster is up and running by looking at the dashboard. To be sure I also stopped and started it again and running `Connect-ServiceFabricCluster`. The output is:

```
PS C:\Users\37668> Connect-ServiceFabricCluster
True
WARNING: Cluster connection with the same name already existed, the old connection will be deleted


ConnectionEndpoint   :
FabricClientSettings : {
                       ClientFriendlyName                   : PowerShell-901d8555-4982-4096-aedb-785829e3bce1
                       PartitionLocationCacheLimit          : 100000
                       PartitionLocationCacheBucketCount    : 1024
                       ServiceChangePollInterval            : 00:02:00
                       ConnectionInitializationTimeout      : 00:00:02
                       KeepAliveInterval                    : 00:00:20
                       ConnectionIdleTimeout                : 00:00:00
                       HealthOperationTimeout               : 00:02:00
                       HealthReportSendInterval             : 00:00:00
                       HealthReportRetrySendInterval        : 00:00:30
                       NotificationGatewayConnectionTimeout : 00:00:30
                       NotificationCacheUpdateTimeout       : 00:00:30
                       AuthTokenBufferSize                  : 4096
                       }
GatewayInformation   : {
                       NodeAddress                          : localhost:19000
                       NodeId                               : bf865279ba277deb864a976fbf4c200e
                       NodeInstanceId                       : 131394314738934854
                       NodeName                             : _Node_0
                       }
```

I'll PM you the trace files.

**Comment by sumeshes07** [comment]
@jacobslusser I think it can be resolved easily, just reset your local cluster by right clicking on the Fabric cluster tray on the taskbar. It will take few minutes to reset.

**Comment by jacobslusser** [comment]
No luck. Tried resetting the cluster and still get the same error.

**Comment by jacobslusser** [comment]
After roping in several other coworkers we were finally able to determine that this was the result of some of our corporate PowerShell policies. We had some deny permissions setup in McAfee to block some aspects of script execution. Once we got those permissions relaxed everything started working beautifully.

**Comment by sumeshes07** [comment]
@jacobslusser Set-ExecutionPolicy RemoteSigned is that what you did ?

**Comment by jacobslusser** [comment]
I initially thought that's what it was too, but no, it was not the execution policy. Turns out some of the commands in the Service Fabric scripts use `-noprompt` which was being blocked by our company because that flag can be used as an attack vector.

**Comment by Lynk5** [comment]
Firewalls can block the exe from running (silently)

**Comment by StenPetrov** [comment]
@xunlu why is this closed? The error message is useless, the tooling should check the basic prerequisites and tell the user if one of them is missing.
I'm experiencing this error as well, SF tray icon seems to be having trouble as well but doesn't report any error back, making it even harder to troubleshoot.

**Comment by healthycola** [comment]
So how do you actually get past this? What do we need to disable in the anti-virus?

**Comment by nikitag-ms** [comment]
Having the same problem as well. None of the suggested solutions helped. Rebooting the machine or resetting the cluster doesn't help either.

**Comment by StenPetrov** [comment]
@xunlu ... here we are again. I'm trying to create a new SF application, still running into the issue, the message is still useless and the issue is still there.

**Comment by sukhovy** [comment]
I faced with the same issue. The actual problem was in publish profile. The ConnectionEndpoint parameter was empty:
`<ClusterConnectionParameters ConnectionEndpoint="" />`

After removing ConnectionEndpoint parameter it works well. I think it is'n the only one reason of this problem but my solution can be useful for someone.
