### ISSUE TITLE
Dotnetcore RC2 Template for Actor Service

### ISSUE THREAD

**Issue by ajaysingh77** [Azure/service-fabric-issues#20]
Thanks for releasing the aspnetcore rc2 template for web services. 
By when can we get the template to create reliable actor based service using dotnetcore rc2? is there any place from i can refer something? Currently i am trying to build actor service using dotnetcore console app template in visual studio 2015 and manually configuring the Service and Application manifest files but after deployment the service fabric is showing codepackage activation fails error.

**Comment by vturecek** [comment]
We currently don't support .net core and .xproj for actor projects. Actor projects have special build tools that only work with .csproj. We will likely bring those tools over to .net core projects in the future.

**Comment by theIceBandit** [comment]
Any update on this? Since dotnetcore has rtm-ed, when can we expect templates for Actor, Stateless and Stateful service for dotnetcore?

**Comment by tanwarsatya** [comment]
Any update on the same and what about having .Net Core based Actor hosted on Linux platform
