### ISSUE TITLE
Service Fabric Reverse Proxy Terminates connection on 304 response

### ISSUE THREAD

**Issue by eelkram** [Azure/service-fabric-issues#200]
When an application being accessed behind the reverse proxy returns a 304 we get a terminated connection from the reverse proxy.  This obviously breaks the consuming application as it does not pass back the 304 response code.

Why does it terminate the response and is this expected?

General Feedback - 
The reverse proxy has continued to cause us a lot of issues with the way that it handles requests.  Our PATCH endpoints don't work (https://github.com/Azure/service-fabric-issues/issues/45), the 404 requests didn't work until we added the additional header and now 304 requests are broken.

**Comment by kavyako** [comment]
We have fixed this issue but it has not been rolled out yet. The deployment will happen next week.  
Version 5.5.219.0 will have this fix.

Thank you for reporting all the issues. Sincere apologies for the issues you have run into. We are trying to fix these missing gaps in the reverse proxy. 

Kavya.

**Comment by eelkram** [comment]
Excellent, thanks @kavyako

**Comment by VipulM-MSFT** [comment]
@eelkram The build 5.5.219 is available as a manual upgrade for Azure Clusters. The clusters that are set to "Automatic" upgrade will get this or a build newer than this at the next rollout in few weeks.

**Comment by eelkram** [comment]
Thanks @VipulM-MSFT

**Comment by mgrishkov** [comment]
Will "Microsoft Service fabric SDK and Tools" package get this update?
Will "Microsoft.Azure.ServiceFabric.WindowsServer" get this update? As I can find currently available only .5.5.216.

**Comment by VipulM-MSFT** [comment]
The SDK refresh is done as part of the normal release rhythm. We are still figuring out the release mechanisms for updates in-between to fix the issues reported by many customers to get them unblocked.
