### ISSUE TITLE
Calling .Netstandard dll from .net 4.6.2 azure service fabric stateful assembly

### ISSUE THREAD

**Issue by teeboy75** [Azure/service-fabric-issues#201]
My issue is explained in [stackoverflow](http://stackoverflow.com/questions/42859444/calling-netstandard-dll-from-net-4-6-2-azure-service-fabric-stateful-assembly)
I am on visual studio 2017 and windows 7 64 bit.
Basically, unable to call .netstandard from .net 4.6.2 project in service fabric stateful service. I am on latest version of service fabric [5.4.164.9494 and SF SDK version: 2.4.164.9494.
Error:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Repo on [github](https://github.com/teeboy75/Servicefabric-Error)

**Comment by TonyGerace** [comment]
This is not a Service Fabric issue but framework in general. If you reference a standard library you must include the NETStandard NuGet package in the framework package.

**Comment by masnider** [comment]
Hi @teeboy75 - were you able to get this working? As @TonyGerace points out, this isn't really a SF thing. We'd like to make sure you're unblocked, so if you're still having issues let us know, otherwise I'll close out this issue in a few days.

**Comment by masnider** [comment]
Closing as no-repro. If you're still having issues please reopen and let us know.
