### ISSUE TITLE
Correct practice to upgrade VM Scaleset size (scale-up)

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#202]
Need to upgrade a VM Scaleset for one node type, not the primary type and this one only contains stateless services, but would still like to do it properly.

When changing the SKU/Size on the VM Scaleset, does the process orchestrate with Azure Service Fabric? From a test I did on one of our test clusters, it took just a few seconds for the first node to shutdown. I did not see anything in the portal regarding disabling of that node, before it went offline.

After the first VM was upgraded, it came back online and registered on the cluster and services started up without issues.

After at least 10-15 minutes of waiting, the second VM started shutdown and upgrade. Since it was delayed, I was able to "Deactivate (Restart)" the second node and the third node (this node type have 3 nodes) is currently in "Disabling" state, which won't complete until the second one is back up again (SF doesn't allow to disable all except 1, I think).

Is it correct to presume that Azure orchestrates the shutdown and upgrade of one and one VM, and we can manually deactivate each node as the process continues?

When selecting a new size, the Azure portal gives the following warning:

"The upgrade policy is set to Automatic for this scale set. Applying this change will immediately restart all instances, which may cause downtime."

Is that message correct, that changing size is suppose to immediately shutdown all the VMs? Or is it correct the behavior I'm experiencing that it takes one and one, and waits a good 10-15 minutes between each?

Have searched and tried to find good documentation on how to scale up with Azure SF, but found very little useful information.

**Comment by pkcsf** [comment]
Please note that, change the size means, VMSS going to provision a brand new VM, so all the steps mentioned in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-scale-up-down is relevant.

**Comment by masnider** [comment]
@ChackDan can also take a look

**Comment by masnider** [comment]
This is covered here - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity#the-durability-characteristics-of-the-cluster
