### ISSUE TITLE
yo azuresfjava service fabric generators not available 

### ISSUE THREAD

**Issue by vbhadrir** [Azure/service-fabric-issues#203]
The yo azuresfjava service fabric generator for Linux is not available in the yoeman generator list but is referred in the service fabric for Linux documentation out here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-linux-application-with-java?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification

**Comment by mani-ramaswamy** [comment]
Did you install the servicefabricsdkjava in addition to the servicefabricsdkcommon and servicefabric (runtime)? And if you did install the Java sdk, did you also run the setup script  sudo /opt/microsoft/sdk/servicefabric/java/sdkjavasetup.sh as described in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux?

**Comment by vbhadrir** [comment]
I have tired installing servicefabricsdkjava and get the following 
warnings when I install it.

root@vjsflinux:~/azure-xplat-cli/azure-xplat-cli# sudo apt-get install 
servicefabricsdkjava
Reading package lists... Done
Building dependency tree 
Reading state information... Done
servicefabricsdkjava is already the newest version (0.8.0.0).
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.
root@vjsflinux:~/azure-xplat-cli/azure-xplat-cli# sudo 
/opt/microsoft/sdk/servicefabric/java/sdkjavasetup.sh
Download yeoman azuresf-guestexec generator dependencies and create npm 
link
npm WARN generator-azuresfguest@0.1.0 No repository field.
npm WARN generator-azuresfguest@0.1.0 No license field.
/root/.node/lib/node_modules/generator-azuresfguest -> 
/opt/microsoft/sdk/servicefabric/common/yeoman-azuresfguest/generator-azuresfguest
Download yeoman azuresf generator dependencies and create npm link
npm WARN generator-azuresfjava@0.1.0 No repository field.
npm WARN generator-azuresfjava@0.1.0 No license field.
/root/.node/lib/node_modules/generator-azuresfjava -> 
/opt/microsoft/sdk/servicefabric/java/yeoman-azuresfjava/generator-azuresfjava
root@vjsflinux:~/azure-xplat-cli/azure-xplat-cli#

**Comment by mani-ramaswamy** [comment]
And before this you did run the sdkcommonsetup.sh script as well? Is the generator working for you now?  Can you paste the output of the "yo azuresfjava" command?

**Comment by vbhadrir** [comment]
Yes, I did run sdkcommonsetup.sh before installing sudo apt-get install 
servicefabricsdkjava and running sudo 
/opt/microsoft/sdk/servicefabric/java/sdkjavasetup.sh

root@vjsflinux:~# yo azuresfjava
Error azuresfjava 

You don’t seem to have a generator with the name “azuresfjava” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via 
http://yeoman.io/generators/. 
Install them with npm install generator-azuresfjava.

To see all your installed generators run yo without any arguments. Adding 
the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your 
system.
root@vjsflinux:~# npm install generator-azuresfjava
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" 
"generator-azuresfjava"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on 
https://registry.npmjs.org/generator-azuresfjava
npm ERR! 404 
npm ERR! 404  'generator-azuresfjava' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name 
yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
root@vjsflinux:~# 


Regards, Vijay

**Comment by mani-ramaswamy** [comment]
You shouldn't need to run npm install (and that wouldn't work).  It seems like that something got messed up during install. Can you also run sudo apt-get update  followed by a 
sudo apt-get install servicefabric, servicefabricsdkcommon

and then run the sudo /opt/.../sdkcommonsetup.sh?

And paste the output messages here?

**Comment by vbhadrir** [comment]
Before running sdkcommonsetup.sh I ran sudo apt-get update followed by 
sudo apt-get install servicefabric, servicefabricsdkcommon

root@vjsflinux:/opt/microsoft/sdk/servicefabric/common# 
./sdkcommonsetup.sh 
Download yeoman azuresf-guestexec generator dependencies and create npm 
link
npm WARN generator-azuresfguest@0.1.0 No repository field.
npm WARN generator-azuresfguest@0.1.0 No license field.
/root/.node/lib/node_modules/generator-azuresfguest -> 
/opt/microsoft/sdk/servicefabric/common/yeoman-azuresfguest/generator-azuresfguest
root@vjsflinux:/opt/microsoft/sdk/servicefabric/common# 

Regards, Vijay

**Comment by mani-ramaswamy** [comment]
Can you please give me the output of sudo apt-get install servicefabric, servicefabricsdkcommon
 as well?

**Comment by vbhadrir** [comment]
Here it is

root@vjsflinux:~# sudo apt-get install servicefabric
Reading package lists... Done
Building dependency tree 
Reading state information... Done
servicefabric is already the newest version (5.5.0.2).
servicefabric set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.
root@vjsflinux:~# sudo apt-get install servicefabricsdkcommon
Reading package lists... Done
Building dependency tree 
Reading state information... Done
servicefabricsdkcommon is already the newest version (0.8.0.0).
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.
root@vjsflinux:~#

Regards, Vijay

**Comment by mani-ramaswamy** [comment]
Adding a couple of folks to investigate this.

I am assuming you are running Ubuntu 16.04? running “lsb_release –a” will tell you.

And do you mind running the following as well:

-          sudo apt-get remove servicefabricsdkjava servicefabricsdkcsharp servicefabricsdkcommon servicefabric

-          sudo apt-get –f autoremove

-          sudo apt-get update

-          sudo apt-get install servicefabricsdkjava servicefabricsdkcssharp

-          sudo /opt/Microsoft/…./sdkcommonsetup.sh


And paste the output for the steps?

Best,
Mani

**Comment by vbhadrir** [comment]
Yes, I am using Ubuntu 16.04

root@vjsflinux:/etc# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
root@vjsflinux:/etc# 

Output of sudo apt-get remove servicefabricsdkjava servicefabricsdkcsharp 
servicefabricsdkcommon servicefabric 

root@vjsflinux:/# sudo apt-get remove servicefabricsdkjava
Reading package lists... Done
Building dependency tree 
Reading state information... Done
The following packages were automatically installed and are no longer 
required:
  jq libcurl4-openssl-dev libonig2 libxml2-utils
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  servicefabricsdkjava
0 upgraded, 0 newly installed, 1 to remove and 247 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 203545 files and directories currently installed.)
Removing servicefabricsdkjava (0.8.0.0) ...
In PreRm - remove
In PostRm - remove
Removing the symbolic links
root@vjsflinux:/# sudo apt-get remove servicefabricsdkcsharp
Reading package lists... Done
Building dependency tree 
Reading state information... Done
Package 'servicefabricsdkcsharp' is not installed, so not removed
The following packages were automatically installed and are no longer 
required:
  jq libcurl4-openssl-dev libonig2 libxml2-utils
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.
root@vjsflinux:/# sudo apt-get remove servicefabricsdkcommon
Reading package lists... Done
Building dependency tree 
Reading state information... Done
The following packages were automatically installed and are no longer 
required:
  jq libcurl4-openssl-dev libonig2 libxml2-utils
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  servicefabricsdkcommon
0 upgraded, 0 newly installed, 1 to remove and 247 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 203447 files and directories currently installed.)
Removing servicefabricsdkcommon (0.8.0.0) ...
In PreRm - remove
In PostRm - remove
Removing the symbolic links
root@vjsflinux:/# sudo apt-get remove servicefabric 
Reading package lists... Done
Building dependency tree 
Reading state information... Done
The following packages were automatically installed and are no longer 
required:
  babeltrace dkms dotnet-dev-1.0.0-preview2-003131 dotnet-host 
dotnet-hostfxr-1.0.1
  dotnet-sharedframework-microsoft.netcore.app-1.0.1 
firebird2.5-common-doc gyp jq libbabeltrace-ctf1 libbabeltrace1
  libcurl4-openssl-dev libib-util libjs-inherits libjs-node-uuid 
libjs-underscore liblldb-3.6 libllvm3.6v5 liblttng-ctl0
  libonig2 libssh2-1 libssl-dev libssl-doc libuv1 libuv1-dev libxml2-utils 
lttng-modules-dkms lttng-tools members
  node-abbrev node-ansi node-ansi-color-table node-archy node-async 
node-block-stream node-combined-stream
  node-cookie-jar node-delayed-stream node-forever-agent node-form-data 
node-fstream node-fstream-ignore
  node-github-url-from-git node-glob node-graceful-fs node-gyp 
node-inherits node-ini node-json-stringify-safe
  node-lockfile node-lru-cache node-mime node-minimatch node-mkdirp 
node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs 
node-read node-read-package-json node-request
  node-retry node-rimraf node-semver node-sha node-sigmund node-slide 
node-tar node-tunnel-agent node-underscore
  node-which nodejs nodejs-dev nodejs-legacy npm python-pkg-resources 
sshpass zlib1g-dev
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  servicefabric
0 upgraded, 0 newly installed, 1 to remove and 247 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 203411 files and directories currently installed.)
Removing servicefabric (5.5.0.2) ...
In PreRm - remove
remove
Stopping service fabric service
Disable service fabric service
Remove servicefabric.service file from systemd
Stopping service fabric updater service
Disable service fabric updater service
Remove servicefabricupdater.service file from systemd
In PostRm - remove
remove
Cleaning up accounts and groups
root@vjsflinux:/# 

Output sudo apt-get –f autoremove



Output of sudo apt-get update

No updates installed

Output of sudo apt-get install servicefabricsdkjava 



Output of sudo apt-get install servicefabricsdkcssharp

root@vjsflinux:/# sudo apt-get install servicefabricsdkcssharp
Reading package lists... Done
Building dependency tree 
Reading state information... Done
E: Unable to locate package servicefabricsdkcssharp

Output of sudo /opt/Microsoft/…./sdkcommonsetup.sh

root@vjsflinux:/# sudo 
/opt/microsoft/sdk/servicefabric/common/sdkcommonsetup.sh
Download yeoman azuresf-guestexec generator dependencies and create npm 
link
npm WARN generator-azuresfguest@0.1.0 No repository field.
npm WARN generator-azuresfguest@0.1.0 No license field.
/root/.node/lib/node_modules/generator-azuresfguest -> 
/opt/microsoft/sdk/servicefabric/common/yeoman-azuresfguest/generator-azuresfguest
root@vjsflinux:/# 

Regards, Vijay

Vijay Bhadriraju
IBM Competitive Project Office
vbhadrir@us.ibm.com

**Comment by mani-ramaswamy** [comment]
Thanks for the patience as we sorted through this and fixed it. The user was logged as root (and there wasn't a separate user so a $NODE_PATH wasn't set. Setting the $NODE_PATH fixed it. 

export NODE_PATH=$NODE_PATH:/root/.node/lib/node_modules 

You might need to add it to your .bashrc or such, so it is always set.
