### ISSUE TITLE
Hundreds of Windows Firewall rules generated

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#205]
On the VMs for Azure Service Fabric cluster, there are hundreds of inbound and outbound firewall rules generated by Service Fabric. Is this correct behavior? Why does it not remove old ones when registering new? Does it register new rules for every single deployment? Is there any documentation on how to clean up, or is that not advised? Does duplicate firewall rules affect performance of the firewall?

Here is just a snippet from one of the VMs:

![image](https://cloud.githubusercontent.com/assets/309938/24254179/8610190c-0fe2-11e7-8eca-0a2f5be0d043.png)

**Comment by masnider** [comment]
If there's nothing running on the machine (and it's been that way for some time) then this is a bug - these should be getting cleaned up (at a minimum) when the application types get cleaned up from the node. 

If you can confirm that none of these are currently corresponding to running workloads on the machine and that the others have been gone for (let's say) at least a few hours, then this is definitely a bug and we can look into it.

**Comment by sondreb** [comment]
These entries are on two different clusters (3 nodes and one 5+3 nodes), the biggest one have been running for 6 months, the other a little less. There have been ~20 deployments to the 5+3, and hundreds to the 3 node one (CI-build-deployment).

There are only 2 different cluster projects on both machines, so the entries correspond to these which are in use.

The majority of entries are for one of the two projects. There is a number appended in the rule name, varies a lot and a lot of 0, 1, 2, 3, 4, 6, 9.

**Comment by RajeetN** [comment]
I tried reproing this behavior but cannot repro it. Just to confirm you are deleting applications deployed on these clusters? SF deletes the firewall rules when applications are deleted or removed from the node. The 0,1,2,3 and so on correspond to the number assigned to application in SF so each app gets a unique number.

**Comment by masnider** [comment]
Hi @sondreb - this should be fixed as of our 5.6 release from last month. Please reopen on us if you're still seeing this (and thanks again for reporting).

**Comment by sondreb** [comment]
This was not fixed in 5.6, but is promised to be fixed in 6.1. We got into more trouble recently due to all the firewall rules (47k +) and got support from Microsoft, and removed the rules using a PowerShell script.

We'll continue monitor when 6.1 upgrade is done and see if the amount of firewall rules increase or becomes stable.

**Comment by RajeetN** [comment]
Sondreb,

This is fixed in 6.1. We noticed that firewall leaks happened when service packages were aborted. The 2 scenarios for this were:
1. Processes crash continuously and do not stabilize.
2. Processes register Ctrl-C handler but don't complete shutdown within the given timeout (around 3 minutes by default)
Do either of these happen in your scenario?

Thanks!
