### ISSUE TITLE
ServiceFabricInternalOperationError when enabling Silver durability tier

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#207]
I have successfully created VMSS with Silver durability level, unfortunately I am unable to enable Silver durability level in the SF (durabilityLevel in ServiceFabricNode extension settings).

I am receiving following error:

Resource Microsoft.Compute/virtualMachineScaleSets 'Front' failed with 
22:33:47 - message '{
22:33:47 -   "status": "Failed",
22:33:47 -   "error": {
22:33:47 -     "code": "ResourceDeploymentFailure",
22:33:47 -     "message": "The resource operation completed with terminal provisioning state 'Failed'.",
22:33:47 -     "details": [
22:33:47 -       {
22:33:47 -         "code": "ServiceFabricInternalOperationError",
22:33:47 -         "message": "Unknown ServiceFabric error."
22:33:47 -       }
22:33:47 -     ]
22:33:47 -   }
22:33:47 - }'

Any hints?

**Comment by AnupVasudevaRao** [comment]
Currently, the only available modes for durability are: Bronze and Gold. 
Could you please try one of those two. 

If you are using Gold, the VM SKUs that are supported are: Standard_D15_v2 and Standard_G5
Bronze is supported on all VM SKUs that Service Fabric supports.

Regarding this unhelpful error message, there will be a fix deployed for this shortly from the Azure teams. That should provide a clearer error message.

Hope this helps.

**Comment by mkosieradzki** [comment]
@AnupVasudevaRao Thanks for your response.

I was hoping Silver Durability tier is already working in latest patch, as VMSS finally supports Silver tier.

:-( We will have apparently to wait a bit longer for Silver Durability tier.
