### ISSUE TITLE
[Reverse Proxy] Dramatic performance when streaming larger files on a connection with medium latency (~50ms)

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#210]
I've started investigating what is the reason behind slow file downloads from Service Fabric hosted service and I have identified very specific issue in the Service Fabric Reverse Proxy.

Consider following scenario:
1. There is a stateful HTTP service in the cluster. Let's call it ContentSource.
2. There is a stateless internet facing HTTP proxy in the cluster. Let's call it ProxyService.
3. ProxyService uses ASP.NET Core Proxy (https://github.com/aspnet/Proxy) to forward request to Service Fabric Reverse Proxy to connect to the ContentSource and then forwards back the response.
4. Customer accesses ProxyService to download a 1.8MB file from the ContentSource.

And now:
Case 1:
Customer is on a fast, low-latency connection (LAN, ~1ms) - download happens immediately (<1s)
Case 2:
Customer is on a fast (300mbps), medium-latency connection (WAN, ~50ms) - download takes over 26 seconds.

Using VPN connection (~50 ms latency, basic azure VPN profile) I have isolated that the issue is being cause by the Service Fabric Proxy.
When accessing the ContentSource service directly (using the internal endpoint listed in the Service Fabric Explorer) I achieve: 2.5 seconds download time.
When accessing the ContentSource service through the (Service Fabric Reverse Proxy (HTTP, no https)) I get over 26 seconds download time.

When accessing the ContentSource service through the (Service Fabric Reverse Proxy (HTTP, no https)) from a local cluster node I can get a nearly immediate download time.
When accessing the ContentSource service through the (ASP.NET Proxy with HTTPS and through the ILB) I get 3.53 seconds download time.

My guess is that it looks like an issue with the Service Fabric Reverse Proxy send buffer size or policy.

Because the reverse proxy seems to work well on a local connection I can try to modify ASP.NET Core Proxy with additional buffering layer, but it does not seem really right!

**Comment by mkosieradzki** [comment]
During futher investigation I have modified a bit my proxy to log exactly places where the delay is introduced (it's basically latest version of Stream.CopyToAsync implemenation + logging:
```
        public static async Task MyCopyToAsync(this Stream stream, Stream destination, int bufferSize, CancellationToken cancellationToken)
        {
            var sw = Stopwatch.StartNew();
            var buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
            bufferSize = 0; // reuse same field for high water mark to avoid needing another field in the state machine
            try
            {
                while (true)
                {
                    Console.WriteLine($"Begin Read {sw.ElapsedMilliseconds}ms");
                    int bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false);
                    Console.WriteLine($"End Read {sw.ElapsedMilliseconds}ms ; read={bytesRead}");
                    if (bytesRead == 0) break;
                    if (bytesRead > bufferSize) bufferSize = bytesRead;

                    Console.WriteLine($"Begin Write {sw.ElapsedMilliseconds}ms");
                    await destination.WriteAsync(buffer, 0, bytesRead, cancellationToken).ConfigureAwait(false);
                    Console.WriteLine($"End Write {sw.ElapsedMilliseconds}ms");
                }
            }
            finally
            {
                Array.Clear(buffer, 0, bufferSize); // clear only the most we used
                ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
                sw.Stop();
            }
        }
```

Results are pretty interesting:
VMSS are machines running on 10.2.140.4-
Proxy is running on 10.2.140.4
ContentSource is running on 10.2.140.6

I have tried to download file using two proxy configurations
1. Direct proxy to 10.2.140.6:<MyServicePort>
2. Proxy through the SFRP: 10.2.140.4:19081/<MyAppPath>

In first situation log looks pretty straightforward:
```
Begin Read 3ms
End Read 6ms ; read=131072
Begin Write 6ms
End Write 326ms
Begin Read 326ms
End Read 326ms ; read=131072
Begin Write 326ms
End Write 441ms
Begin Read 441ms
...
Begin Write 1170ms
End Write 1234ms
Begin Read 1234ms
End Read 1235ms ; read=69234
Begin Write 1235ms
End Write 1320ms
Begin Read 1321ms
End Read 1321ms ; read=0
```
Basically buffer size is: the best shared buffer larger than default size: 81920 (effectively I am getting: 131072).
60 ms delay is created on each roundtrip when sending to the client, but buffer is big enough.

Log on the second case is ridiculous:
```
...
End Read 21131ms ; read=4096
Begin Write 21131ms
End Write 21184ms
Begin Read 21184ms
End Read 21184ms ; read=4096
Begin Write 21184ms
End Write 21239ms
Begin Read 21239ms
End Read 21240ms ; read=8192
Begin Write 21240ms
End Write 21319ms
Begin Read 21319ms
End Read 21319ms ; read=4096
Begin Write 21319ms
End Write 21376ms
Begin Read 21376ms
...
```

Basically Service Fabric Reverse Proxy introduces cutting the stream into 4096 bytes fragment and keeps them until they get ACK.

Ridiculously small buffer size in Service Fabric Reverse Proxy limits the throughput to: 4KiB / latency
What is: 
- 4KiB / 10ms = 4KiB/s * 100 = 400KiB/s = 3200kbps    on 10ms latency
- 4KiB / 50ms = 4KiB/s * 20 = 80 KiB/s = 640kbps      on 50ms latency
- 4KiB / 200ms = 4KiB/s * 5 = 20 KiB/s = 160kbps      on 200ms latency

That pretty much explains what's going on.

**Comment by BharatNarasimman** [comment]
@mkosieradzki - you are correct, this is a performance issue in SF reverseproxy and thanks for the detailed investigation. The fix for this under testing as a part of the release pipeline. I will update the thread when we know the deployment this fix will be part of.
