### ISSUE TITLE
Microsoft Azure Service Fabric -- Installation failed

### ISSUE THREAD

**Issue by VikasKrAgrawal** [Azure/service-fabric-issues#211]
MSI (s) (F0:A8) [21:02:58:455]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:58:457]: Entering MsiProvideAssembly. AssemblyName: System.Fabric.Dca.Validator,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:58:457]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:58:597]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:58:599]: Entering MsiProvideAssembly. AssemblyName: System.Fabric.Strings,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:58:599]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:58:739]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:58:741]: Entering MsiProvideAssembly. AssemblyName: Policy.4.0.System.Fabric,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:58:741]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:58:881]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:58:883]: Entering MsiProvideAssembly. AssemblyName: Policy.3.0.System.Fabric,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:58:883]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:59:023]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:59:025]: Entering MsiProvideAssembly. AssemblyName: Policy.2.0.System.Fabric,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:59:025]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:59:165]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:59:167]: Entering MsiProvideAssembly. AssemblyName: Policy.1.0.System.Fabric,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:59:167]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:59:310]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:59:312]: Entering MsiProvideAssembly. AssemblyName: System.Fabric,version="5.0.0.0",culture="neutral",publicKeyToken="31BF3856AD364E35",processorArchitecture="AMD64", AppContext: , InstallMode: -4
MSI (s) (F0:A8) [21:02:59:312]: Pathbuf: 0, pcchPathBuf: 0
MSI (s) (F0:A8) [21:02:59:452]: MsiProvideAssembly is returning: 1607
MSI (s) (F0:A8) [21:02:59:493]: Note: 1: 2318 2:  
MSI (s) (F0:A8) [21:02:59:498]: No System Restore sequence number for this installation.
MSI (s) (F0:A8) [21:02:59:498]: Unlocking Server
MSI (s) (F0:A8) [21:02:59:578]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
Action ended 21:02:59: INSTALL. Return value 3.
MSI (s) (F0:A8) [21:02:59:582]: Note: 1: 1708 
MSI (s) (F0:A8) [21:02:59:582]: Product: Microsoft Azure Service Fabric -- Installation failed.

MSI (s) (F0:A8) [21:02:59:583]: Windows Installer installed the product. Product Name: Microsoft Azure Service Fabric. Product Version: 5.5.216.0. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 1603.

MSI (s) (F0:A8) [21:02:59:599]: Deferring clean up of packages/files, if any exist
MSI (s) (F0:A8) [21:02:59:599]: MainEngineThread is returning 1603
MSI (s) (F0:90) [21:02:59:604]: RESTART MANAGER: Session closed.
MSI (s) (F0:90) [21:02:59:604]: No System Restore sequence number for this installation.
=== Logging stopped: 3/25/2017  21:02:59 ===
MSI (s) (F0:90) [21:02:59:605]: User policy value 'DisableRollback' is 0
MSI (s) (F0:90) [21:02:59:606]: Machine policy value 'DisableRollback' is 0
MSI (s) (F0:90) [21:02:59:606]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (F0:90) [21:02:59:606]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F0:90) [21:02:59:606]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (F0:90) [21:02:59:607]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (F0:90) [21:02:59:607]: Restoring environment variables
MSI (s) (F0:90) [21:02:59:610]: Destroying RemoteAPI object.
MSI (s) (F0:30) [21:02:59:610]: Custom Action Manager thread ending.
MSI (c) (08:7C) [21:02:59:612]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (08:7C) [21:02:59:612]: MainEngineThread is returning 1603
=== Verbose logging stopped: 3/25/2017  21:02:59 ===

Any Help Please..

**Comment by maburlik** [comment]
Hi Vikas. Could you provide more info about this installation? Which version were you installing? Did you have a previous SF installation present on this machine - SDK/Standalone? Do you see any records for Microsoft Azure Service Fabric in Programs and Features on the machine?

Thanks,
Max

**Comment by DerGroncki** [comment]
I am not able to install the SDK on WIndows 7 Enterprise (64bit) with Visual Studio 2017 installed. Please see attached screenshot and log files.
Thank you.
Michael.

![error web platform installer - azure service fabric sdk](https://cloud.githubusercontent.com/assets/2815398/24653385/e796becc-1935-11e7-8880-0fecf30cfbf0.jpg)

[MicrosoftServiceFabric.5.5.216.0.txt](https://github.com/Azure/service-fabric-issues/files/892840/MicrosoftServiceFabric.5.5.216.0.txt)
[webpi9.txt](https://github.com/Azure/service-fabric-issues/files/892841/webpi9.txt)

**Comment by maburlik** [comment]
Adding Alan. This is what I'm seeing in the MSI log:
InstallDrivers:  Driver Path = C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys 

InstallDrivers:  CreateService LeasLayr successfully.
InstallDrivers:  Error 0x80070241: StartService LeasLayr failed with error code: 577.
InstallDrivers:  Error 0x80004005: InstallDriver LeasLayr returned error 2147942977

0x241
577
ERROR_INVALID_IMAGE_HASH
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

**Comment by AlanWarwick** [comment]
![certmgr](https://cloud.githubusercontent.com/assets/11524862/25599271/b0d9a18c-2e8f-11e7-91fc-70aa83b68428.jpg)

Would you please look at the certificate manager to see if there is a root certificate named Microsoft Root Certificate Authority 2010.  You can reach this screen by typing certmgr.msc at the command line and then clicking into Trusted Root Certificate Authority and then Certificates. It would be helpful if you could send a screen shot of the list as I have above.

**Comment by AlanWarwick** [comment]
One other thing.  Would you please confirm that the date that your PC is set to is before May 11 2017.

**Comment by AlanWarwick** [comment]
We encountered this on another windows 7 machine and the fully updating the machine with Windows Update resolved the issue.

**Comment by ColinM9991** [comment]
For the record, I had this issue on a work PC which is running Windows 7 Enterprise, I posted an answer here on Stackoverflow which resolved the issue for me

http://stackoverflow.com/a/43934928/5062791

**Comment by GuptaParitosh** [comment]
Fatal Error while installing MicrosoftServiceFabric 5.6.210 sdk  on **Window 7** Machine with **Visual Studio 2017**. 

Receiving Error As:
InstallDrivers:  StopSerivce LeasLayr does not exist.
InstallDrivers:  Driver Path = C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys 
InstallDrivers:  CreateService LeasLayr successfully.
InstallDrivers:  Error 0x80070241: StartService LeasLayr failed with error code: 577.
InstallDrivers:  Error 0x80004005: InstallDriver LeasLayr returned error 2147942977

Activity Logs can be downloaded Here:
https://drive.google.com/file/d/0B0PQUsGXIy77TlhWZnBSZldiQzA/view?usp=sharing

Could anyone help in resolving this installation Issue.

Microsoft has already provided a hot fix to resolve such problem for Window 8/Window Server 2012 as given below:
https://support.microsoft.com/en-us/help/2858668/pla-data-collector-sets-stop-after-72-hours-on-a-windows-server-2012-based-computer.

Since we are using **window 7**, this hotfix wouldn't help.

**Comment by AlanWarwick** [comment]
@GuptaParitosh ,  The error indicates that there is not an appropriate root certification authority installed on your Windows 7 machine.  Please use Windows Update to fully update your windows 7 machine to all of the latest updates. In past cases we have seen that after these updates then the appropriate root certificate authority.

**Comment by GuptaParitosh** [comment]
Thanks @AlanWarwick  Issue is resolved by updating Window 7
