### ISSUE TITLE
Service Fabric SDK slows down solution loading

### ISSUE THREAD

**Issue by jahmai** [Azure/service-fabric-issues#212]
After installing the Service Fabric SDK our solution loads markedly slower. We only have two .sfproj projects amongst about 30 projects total. Using dotTrace revealed 16% of main thread time of devenv.exe is dedicated just to loading those two projects.

This is VS2017 using version 5.4.145 and the projects are version 1.5.

![image](https://cloud.githubusercontent.com/assets/2010997/24355522/f8ff36de-1341-11e7-8354-a71b6e12fb9f.png)

**Comment by MikkelHegn** [comment]
@ravipal investigating

**Comment by jahmai** [comment]
Minor correction: Microsoft.VisualStudio.Azure.Fabric.MSBuild package is 1.5, <ProjectVersion> is 1.4

**Comment by ravipal** [comment]
Jahmai, Project version and MSBuild package version should be same otherwise you will run into build issues. I assume you upgraded the Service Fabric SDK and VS tooling is 1.4. Just upgrading the Service Fabric SDK will not slow down the solution loading.

**Comment by MikkelHegn** [comment]
@ravipal: If you wanted to update the runtime, but not the project, can stay on 1.4 for the Microsoft.VisualStudio.Azure.Fabric.MSBuild package and project version, but using the new runtime packages? E.g. downgrade the NuGet above to 1.4 could be a way out.

**Comment by jahmai** [comment]
@ravipal So how do I upgrade to Tools 1.5? If I change it manually in the sfproj, I get the following error:

![image](https://cloud.githubusercontent.com/assets/2010997/24477040/479063a0-1521-11e7-8f29-f2d9e70a2e3b.png)

**Comment by ravipal** [comment]
@jahmai Since the Service Fabric Tools you have is 1.4, the Microsoft.VisualStudio.Azure.Fabric.MSBuild and project version should stay at 1.4. You can upgrade the runtime version to the latest (5.5).

1.5 Service Fabric Tools for VS2017 will be released soon, Once you have this 1.5 version of tool is installed the project and MSBuild nuget package will be upgraded. Also note that 1.5 Service Fabric Tools is available as part of VS 2017 preview.

**Comment by jahmai** [comment]
Ok so I manually dropped the msbuild version to 1.4.0 by modifying packages.config and the sfproj files by hand. This seems to have resolved the issue:

![image](https://cloud.githubusercontent.com/assets/2010997/24478017/061d12b6-1525-11e7-8688-7fd656a12b86.png)
