### ISSUE TITLE
VSTS Release step: The content in ConfigPackage Name:Config and Version:... in Service Manifest ‘xxx’ has changed, but the version number is the same

### ISSUE THREAD

**Issue by dominicheyden** [Azure/service-fabric-issues#214]
Upgraded cluster to 5.5.216
Using VSTS with agent v2.115.0
Using Update Service Fabric App Versions Task with "Update only if changed" checked

Always fails on release step with 
The content in ConfigPackage Name:Config and Version:... in Service Manifest ‘xxx’ has changed, but the version number is the same

**Comment by MikkelHegn** [comment]
Can you share the debug log output from the task? To run a build with debug add a variable to the build definition named debug and set it to true.
Thanks

**Comment by dominicheyden** [comment]
Done by email

**Comment by kyrrigle** [comment]
FWIW I had been running into this and just figured out it was because I had two apps deployed to a single application type.  And both app packages had the same version number.   Service fabric was (I think) correctly balking saying that this conflict didn't make sense.   Resolution for me was to make sure the versions were changed.

**Comment by MikkelHegn** [comment]
@dominicheyden - Sorry for the late reply.
I don’t see any config package changes being identified in the build log. Do you change config files at a later stage, before publishing?
When we update versions, we look at latest build, if not all builds are released you should be considered about how to do that. Some argue that this should actually be done as part of release comparing against the cluster, but we have no tasks for doing that.
Also, it looks like you are using build numbers for versioning, which means that even though you do not release all builds, the version of the package that is failing should be different from what's deployed, unless you have done any manual deployments.

I just ran a simple repro and didn't find any problems.

Try comparing the build artifact (app package), with what's in the cluster https://docs.microsoft.com/en-us/rest/api/servicefabric/get-a-list-of-image-store-content to find the difference in the settings files.

**Comment by MikkelHegn** [comment]
Closing for now - feel free to reopen if problem still exists

**Comment by jricke** [comment]
I am experiencing this issue. Has there been a solution identified?

**Comment by MikkelHegn** [comment]
@jricke: can you please add more info?
The error message indicates you're deploying an application type, where a config package in one of your service types is different than what's already in the cluster, but has the same version number.

**Comment by jricke** [comment]
@MikkelHegn My error message is:

The content in CodePackage Name:Code and Version:0.1.20170829.4 in Service Manifest 'xPkg' has changed, but the version number is the same.

The files are being build by VSTS and are versioned using the Update Service Fabric App Versions task with the Update only when changed option selected. 

All the projects have Determinstic=true in them as well as the build variables and command line arguments to the build tasks.

I've tried with compression on and off in the deployment task but same results.

Am I to manually remove the services that don't change from the application package if the versioning task reports no change in order to do a differential upgrade?

Thanks,
Jason

**Comment by MikkelHegn** [comment]
@jricke The error is a hash comparison between the code package already in SF and the one you deploy. As these are deemed different by the cluster, without a version change, you see this error. A compressed vs. non-compressed code package will also cause this validation error.

It could be the PDB (symbol) files, which are part of your build output. These are not deterministic and will change. Make sure these are not in the code package. You need extra steps in your build definition to remove these somewhere else. If you create a new build definition using the Service Fabric build definition template, this should have all the steps in it.

**Comment by jricke** [comment]
@MikkelHegn I started the build definition using the Service Fabric template. I'm also moving the PDB's to a PDB folder and removing them from the application directory. The Service Fabric App Versioning task will give a warning if PDB's exist in the package directory when trying to compare. This warning does not show when the PDB's are moved. I don't see any changes listed when the versioning task completes. Is there a way to know which files are causing the error to occur?

**Comment by jricke** [comment]
@MikkelHegn I did a diff with WinMerge and the folders came up no different.

Here is the error: The content in CodePackage Name:Code and Version:0.1.20170829.4 in Service Manifest 'Sem.ServiceFabric.ChromePkg' has changed, but the version number is the same.

Here is the Diff:
![image](https://user-images.githubusercontent.com/11906948/29988595-e97680aa-8f33-11e7-982c-b6c2bb572a29.png)

I'm not sure how to get around this problem without removing service packages that don't change per the Service Fabric App Versioning task during the build.

**Comment by MikkelHegn** [comment]
@jricke @oanapl To help looking at traces from the cluster.

**Comment by MikkelHegn** [comment]
@jricke Just realized you open the other issue :-) Closing this one again and working on your issue on #444

**Comment by thejavamentor** [comment]
This issue can be fixed by making changes in configuration file i.e. Settings.xml, instead changing the code. This fix has been worked for me.
