### ISSUE TITLE
[Reverse Proxy] Reverse Proxy strips ETag headers

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#215]
From my observation Service Fabric Reverse Proxy does not forward the ETag headers.

**Comment by kavyako** [comment]
We do not have any special handling for the ETag header in the Reverse Proxy. 

I verified sending the ETag header from a test service, with the request routed via the reverse proxy.The client received the header with the right value. 

Here is how I am setting the ETag header in the Web API:
`            response.Headers.ETag =
                new EntityTagHeaderValue(String.Concat("\"", hash, "\""), true);`

Can you share a repro?

**Comment by mkosieradzki** [comment]
Hi Kavya. I sincerely apologize for this one, the issue was on my side this time. Thank you very much for your help.
