### ISSUE TITLE
ServiceFabricExplorer.exe from SDK Tooling crashes when using AAD

### ISSUE THREAD

**Issue by Expecho** [Azure/service-fabric-issues#218]
As soon as I configure a new connection using AAD and press connect this application crashed. The windows event log shows the following message.

```
Application: ServiceFabricExplorer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at <Module>.GetAccessToken(Char*, Char*, Char*, Char*, Boolean, Char*, Int32)
```

**Comment by VipulM-MSFT** [comment]
@linggengmsft can you take a look?

**Comment by linggengmsft** [comment]
Could you check if these files are in the same folder? Have you modified anything to the tool folder?
Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.xml

**Comment by Expecho** [comment]
Nope, I do not have those files in that folder. And I did not modify anything in the folder. Multiple people in my team have the same issue.

**Comment by linggengmsft** [comment]
Could you provide the SDK version? And did you download it from Microsoft's public website?

**Comment by linggengmsft** [comment]
Hi Expecho,

Looks like these 3 dlls are missing from the ServiceFabricExplorer folder, as a workaround, please copy these from runtime folder to ServiceFabricExplorer  folder:

System.Fabric.AzureActiveDirectory.Client.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll

**Comment by Expecho** [comment]
That works, thank you!
