### ISSUE TITLE
Service Fabric Explorer and deployment port not mapping to all IP addresses on server

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#22]
Upgrading to Service Fabric SDK 2.1.150 and Runtime 5.1.150 and using the new .Net Core template as a guide, required our Web Service to set Kestrel to use //+ as single Azure VM deployments (build server) would not listen to all IP addresses on the Azure VM.

For example listening to serverUrl set using this code:

```
var endpoint = FabricRuntime.GetActivationContext().GetEndpoint(_endpointName);
string serverUrl = $"{endpoint.Protocol}://{FabricRuntime.GetNodeContext().IPAddressOrFQDN}:{endpoint.Port}";
```

would configure Kestrel to only listen to http://localhost:80 as opposed to also listening to the internal Azure VM allocated IP address, mapped to an Azure DNS. The above code though does work on ARM deployed Service Fabric clusters.

The workaround was to configure Kestrel to use //+ as per the below (old owin guidance?), also tested with Azure ARM Cluster deployments, local developer environments and single node Azure VMs:
```
IWebHost webHost = webHostBuilder
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseWebRoot(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot"))
                .UseUrls($"{protocol}://+:{port}")
                .UseStartup<Startup>()
                .Build();
```
Checking Service Fabric Explorer and the deployment port 19000, these internal Service Fabric services appear not be listening to all IP addresses on a manually configured Azure VM server (build server). Not sure if this is by design or a bug?

**Comment by vturecek** [comment]
"http://+" is a construct of [http.sys URL prefixes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364698(v=vs.85).aspx). It doesn't actually mean anything in Kestrel - see this thread: https://github.com/aspnet/KestrelHttpServer/issues/867

Service Fabric Explorer only shows the address returned by ICommunicationListener.OpenAsync, which is any string the service wants to advertise - typically something clients can actually connect to like a URL, but the point is that it's displaying whatever the service says, it's not actually digging up info from the OS or anything like that.

**Comment by MedAnd** [comment]
Closed as using following worked:

.UseUrls($"{protocol}://+:{port}")
