### ISSUE TITLE
ImageStoreService can't handle missing files

### ISSUE THREAD

**Issue by JohnNilsson** [Azure/service-fabric-issues#223]
We're having an issue where the ImageStoreService can't create replicas, currently resulting in the service being stuck in permanent quorum loss.

On the node where a replicas are trying to start there are errors like

```
ImpersonateAndCopyFile for SourcePath:\\10.0.0.4\StoreShare__Node_0\[...], DestinationPath:D:\SvcFab\_App\__FabricSystem_App[...] failed with Error:0x80070002. Retrying with a different access token if available.
```

At closer inspection it seems it's trying to copy files the primary doesn't even recognize `Get-ServiceFabricImageStoreContent -Path -RemoteRelativePath "Store" -ImageStoreConnectionString "fabric:ImageStore"` doesn't list the application type in question.
Yet on the primary node there are empty folders in the store a number of versions of the missing application type. So something seems to think they should be there.

How can I get ImageStoreService replicas to agree on what should be in the store?

**Comment by oanapl** [comment]
How is image store configured in your cluster manifest? Are you using LocalUser for FileStoreService\PrimaryAccountType and FileStoreService\SecondaryAccountType configuration entry?
If so, can you make sure the certificates are correctly installed where you expect them to be?
If the certificates are there, can you check that you see S_FSSUserffffffff and P_FSSUserffffffff users created on the nodes?

**Comment by JohnNilsson** [comment]
LocalUser for both and the certificates are working as expected.
And the users are created.
Actually this has all been working fine. It just broke down just down, for some reason.

For context, this cluster has previously had problems with running out disk space which at one instance ended up with us deleting files from the store manually. Which is probably why it is is looking for them. But it has been working fine until now.

A node was restarted, and after the secondaries hasn't been able to start. I did force the service to be more cooperative with
```
Update-ServiceFabricService -Stateful fabric:/System/ImageStoreService -MinReplicaSetSize 1 -TargetReplicaSetSize 1
Get-ServiceFabricPartition -ServiceName fabric:/System/ImageStoreService | Get-ServiceFabricReplica | where { $_.ReplicaRole -ne "Primary" } | Remove-ServiceFabricReplica -ForceRemove
Get-ServiceFabricPartition -ServiceName fabric:/System/ImageStoreService | Repair-ServiceFabricPartition
```
but the secondaries still have problem starting.

Inspecting the disk now I notice another thing though
On the node with the primary there's an extra Store-folder for the existing apptype
```
work/Store/<primary replica id>/Store/<existing app type>
work/Store/<primary replica id>/<missing app type>
```
On one of the nodes trying to start a secondary
there is no such Store-folder, but the empty <missing app type> folder is there for a bunch of replica ids (not running)
```
work/Store/<not existing replica id 1>/<missing app type>
work/Store/<not existing replica id 2>/<missing app type>
work/Store/<not existing replica id 3>/<missing app type>
```

**Comment by VipulM-MSFT** [comment]
@JohnNilsson See if the following will resolve your issue:

- Login to the machine that is having issue - the one where you have bunch of replica ids
- Stop FabricHost process by "net stop FabricHostSvc"
- Open the Local Users and Groups in computer management
- Delete the users that ends in ...ffff
- Delete the group that end in ...ffff
- Restart the VM

**Comment by lumiao** [comment]
work/Store/<primary replica id>/Store/<existing app type> <-- The application type has been registered. 
work/Store/<primary replica id>/<missing app type> <-- The application package should be copied to here. 
I think if you deleted something from image store unnaturally, It's better off trying to clean up image store first; like unprovision applications and removing application packages; after bringing the secondary replicas back, you can do the copying and provision from scratch.

**Comment by JohnNilsson** [comment]
@VipulM-MSFT That looks like some rather invasive steps, could you elaborate on the theory behind the them?

**Comment by JohnNilsson** [comment]
Ok, got it sorted. With a more controlled sequence of deactivating and removing state from the nodes, the service manage to get the secondaries online again.

**Comment by oanapl** [comment]
In our latest release (>= 5.6.x.x), if we find any user in invalid state (which happened in your case, the user was missing some metadata), we cleanup and re-create the user automatically.
