### ISSUE TITLE
Having the word "Exception" in a Service Name causes Visual Studio Debugging not to work

### ISSUE THREAD

**Issue by keflem** [Azure/service-fabric-issues#224]
If you create a service and the name contains "Exception" debugging will not work in Visual Studio.  The S.F. App will deploy, but then immediately be unregistered.

Repo:
Visual Studio 2015, Update 3
Service Fabric SDK 2.4.145
Service Fabric VS Tools 1.4

From a Service Fabric Application, choose to Add New Service Fabric Service.  In the dialog select a Stateless Service.  Name the Service "ExceptionService".  

This will create the default template.  
Attempt to debug the application.  
Observe that the application is published and started, but then is immediately removed and the debug session ends.

Now change the name of the service to anything without Exception, like Excpt and observe that the service works.

**Comment by dbreshears** [comment]
This should be fixed in the latest release.    Service Fabric 2.5 SDK and 1.5 VS tooling.

**Comment by dbreshears** [comment]
@keflem. I'll close this for now,  if you find that it isn't fixed in VS tools 1.5,  please reopen
