### ISSUE TITLE
Get-ServiceFabricApplicationHealth - ErrorAction SilentlyContinue does not take effect

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#225]
### Cmdlet(s)

Get-ServiceFabricApplicationHealth

### PowerShell Version

4.0

### OS Version

6.3.9600.17400

### Description

Get-ServiceFabricApplicationHealth -ApplicationName "mysfapp1"**-ErrorAction SilentlyContinue**
fails to suppress the error.

Get-ServiceFabricApplicationHealth : Cluster connection instance is null
At line:1 char:1
+ Get-ServiceFabricApplicationHealth -ApplicationName "mysfapp1" -ErrorActio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-ServiceFabricApplicationHealth], NullReferenceException
    + FullyQualifiedErrorId : GetClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.GetApplicationHealth

**Comment by Pradebban** [comment]
@oanapl, @heeldin  please let me know if there is an update. this is blocking our automation.

**Comment by rajaprad** [comment]
@oanapl , @heeldin  - Is there an update, when is the fix targeted ?

**Comment by heeldin** [comment]
This is a breaking change in our side, so we are still discussing it.

**Comment by heeldin** [comment]
The only way around this now is to use a try and catch.
 You can also change the ErrorActionPreference to silentlycontinue which is a global change and not recommended.

We do not support the silentlycontinue yet in our powershell cmdlets since we throw terminating errors.
