### ISSUE TITLE
Reliability Tier Upgrade stuck

### ISSUE THREAD

**Issue by JohnNilsson** [Azure/service-fabric-issues#229]
Using the portal we started en upgrade of the reliability tier. This was two days ago now, but the portal is still reporting it as "Updating cluster"

Trying to inspect the status from PowerShell just yields a timeout
```
PS> Get-ServiceFabricClusterConfigurationUpgradeStatus
Get-ServiceFabricClusterConfigurationUpgradeStatus : Operation timed out.
```

I'm assuming it's not supposed to take days. And we've had some issues with the cluster the past days so it's not surprising that something didn't complete successfully.

How can I abort/cancel this operation and try again, or otherwise force it to complete?

**Comment by Liphi** [comment]
Get-ServiceFabricClusterConfigurationUpgradeStatus is for standalone Service Fabric. For Azure Service Fabric, we could call Get-ServiceFabricClusterUpgrade.

**Comment by JohnNilsson** [comment]
Ok, that helps. At least it agrees with my assesment that it failed
```PS> Get-ServiceFabricClusterUpgrade


TargetCodeVersion                          : 5.5.216.0
TargetConfigVersion                        : 8
UpgradeState                               : Failed
```
OTOH
```PS> Get-ServiceFabricClusterConfiguration
Get-ServiceFabricClusterConfiguration : Could not ping any of the provided Service Fabric gateway endpoints.```
or
```PS> Get-ServiceFabricClusterConfiguration
Get-ServiceFabricClusterConfiguration : Operation timed out.
```
so I guess I need to get that sorted first.

It's somewhat disappointing that `Get-ServiceFabricClusterHealth` reports
```
ApplicationName       : fabric:/System
AggregatedHealthState : Ok
```
when it's clear that it's not Ok. Is there another way to get a more accurate health assessment from the system services? (besides going through the logs)

**Comment by JohnNilsson** [comment]
Is this supposed to work? (given the output of Get-ServiceFabricClusterUpgrade above)
```
PS> Start-ServiceFabricClusterUpgrade -Config -ClusterManifestVersion 8 -FailureAction Rollback -Monitored
Start-ServiceFabricClusterUpgrade : The file does not exist in the store.
```
Since we did have problems with the image store it would not surprise me if things got lost somewhere.
The current manifest is Name="WRP_Generated_ClusterManifest" Version="7"

In the store folder on the nodes I do find various manifests files with version = 8, besides formatting they don't seem to contain any changes relative 7 though.

**Comment by Liphi** [comment]
Have u followed the below sample to register ur manifest and upgrade?

Copy-ServiceFabricClusterPackage -ImageStoreConnectionString "fabric:ImageStore" -Config -ClusterManifestPath "C:\clusterManifest222.xml" 
Register-ServiceFabricClusterPackage -Config -ClusterManifestPath "clusterManifest222.xml"
Start-ServiceFabricClusterUpgrade -Monitored -FailureAction Rollback -Config -ClusterManifestVersion 1

**Comment by JohnNilsson** [comment]
Is there some documentation explaining this in detail?

Both the version I get from ` Copy-ServiceFabricClusterPackage` and the version I found in the store folder results in ```Register-ServiceFabricClusterPackage : Version has already been registered``` though.

But perhaps I can make sure all replicas see the same files...

**Comment by masnider** [comment]
@JohnNilsson - were you ever able to get this working?

**Comment by JohnNilsson** [comment]
Nope, it's still stuck. Now it's getting really annoying though, since the runtime is stuck at the unsupported 5.5-version, and certificates are starting to expire. Hope to have it sorted in the next couple of days though, can report back here if it works out.

**Comment by JohnNilsson** [comment]
I think we've got this sorted now. The required magic was to restore the missing manifest file directly to `WindowsFabricStore` (plus some help help from support to kick the portal out of the "updating" state)
```powershell
Get-ServiceFabricClusterManifest > ClusterManifest.7.xml
Copy-ServiceFabricClusterPackage -ImageStoreConnectionString fabric:ImageStore -ClusterManifestPathInImageStore WindowsFabricStore\ClusterManifest.7.xml -Config  -ClusterManifestPath "ClusterManifest.7.xml"
```
