### ISSUE TITLE
HTTPS Certificate Error

### ISSUE THREAD

**Issue by mburumaxwell** [Azure/service-fabric-issues#23]
I have set up a cluster that authenticates against Azure Active directory. This means that the cluster management web service is served under https. When I load the first time, I get a certificate warning from the browser. On a closer check, the certificate is self-signed and the thumbprint is exactly the same to that used when setting up the cluster.
I do not own *.{region}.cloudapp.azure.com meaning that I cannot get a certificate for it. What would I have to do to get proper https in my browser? Is this a Service Fabric error or is it my mistake?

**Comment by vturecek** [comment]
You would have to register your own domain, get a certificate for that domain, and then access your cluster through that domain. We currently don't provide shared certificates for the cloudapp.azure.com domain. This article gives some more background, although it's aimed at Cloud Services, the same concepts apply - including the part about the VIP being dynamically assigned: https://azure.microsoft.com/en-us/documentation/articles/cloud-services-custom-domain-name/

**Comment by mburumaxwell** [comment]
Thank you for your response. Does this involve recreating the cluster or would an update using an ARM template work as well?

**Comment by vturecek** [comment]
Well the easiest thing to do would be to map a CNAME to your .cloudapp.azure.com domain, in which case you don't need to change anything about your cluster.

If you want to set up an A record to your cluster's public IP, then you'll need to make an update to your cluster's ARM template to configure a static IP on the Azure Load Balancer by assigning it to the load balancer frontend configuration in your ARM template. This shouldn't require recreating the cluster. See here for more info: https://azure.microsoft.com/en-us/documentation/articles/virtual-network-ip-addresses-overview-arm/

**Comment by mburumaxwell** [comment]
Thanks
