### ISSUE TITLE
Reverse Proxy and 410 StatusCode

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#230]
As I can find in [Special handling for port sharing services](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services) I have to use `X-ServiceFabric : ResourceNotFound` to say for proxy that resource has not been found and it should't to search it on other nodes. 
@mkosieradzki suggest nice extension to implement [Fabric Reverse Proxy Integration](https://github.com/Azure/service-fabric-aspnetcore/issues/2). 

But it works only for 404. What shall I do for 410 status code (and another status codes)? Are there any common solution?

**Comment by vturecek** [comment]
The thing with 404 is that the proxy will automatically retry unless you tell it not to. The middleware that @mkosieradzki proposed would make sure the proxy does not retry when you don't want it to on 404.

We added automatic retry handling in the Reverse Proxy for HTTP 410 in the 5.5 release to coincide with our ASP.NET Core integration middleware that uses 410 to signal that the client has connected to the wrong service: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore

Are you looking for a way to tell the reverse proxy to **not** retry on HTTP 410?

**Comment by mgrishkov** [comment]
Yes. I'm looking for it. I use 410 state to tell to the client that the method (action) has been deprecated.

**Comment by vturecek** [comment]
The reverse proxy doesn't support that today for 410. We'll look into adding something for 410 and 503.

**Comment by mgrishkov** [comment]
Ok, thank you for the information. I'll send 404 to clients,

**Comment by baralong** [comment]
I'd like to add my vote to this, I've got different behaviors for 404 and 410 in relation to a sale: 

- 404 = bad sale id
- 410 = sale submitted

I also wonder if it'd be possible to stop the continuous retry, surely if the reverse proxy has had the same response from all services it could try then it should eventually pass the response through to the client, rather than never returning.

**Comment by eelkram** [comment]
We are also wanting to return 410's for our application.  I think the header method used for 404's simply needs to be extended for all status codes.  If the developer wants to return a specific status code we should be able to append a header like "X-ServiceFabric : RPNoRetry" to indicate to the reverse proxy that we don't want it to retry the request and return as is.  I would hate to have to use a different method for each status code and/or have to deal with a matrix of specific codes that can be used and ones that can't.  A single method seems simpler for both developers leveraging Service Fabric and the team developing Service Fabric.

**Comment by sridmad** [comment]
Fixed in a Customer update of 6.4 and later. [Release Notes](https://msdnshared.blob.core.windows.net/media/2019/05/Service-Fabric-64CU6-Release-Notes-V2.pdf)

> If the header X-ServiceFabric=NoRetry is set in the service response, reverse proxy
> will not re-resolve and retry for 404, 410, 503 response status codes from the service.
> It will continue to support the X-ServiceFabric=NotFound header for legitimate 404
> response code.
