### ISSUE TITLE
Missing "IsEnabled" Fabric settings for ApplicationGateway/Http in Azure Portal

### ISSUE THREAD

**Issue by gauravhub** [Azure/service-fabric-issues#232]
I was looking for options to enable ServiceFabric Reverse Proxy through Azure Portal at the time of cluster creation. I can see ApplicationGateway/Http in Fabric Settings section but I don't see "IsEnabled" property in the dropdown as shown in screenshot below. 

Is there any reason on why this property is not available while some of the other properties are available? This section in portal may not be usable if we cannot turn-on the Reverse Proxy from the portal itself? 

In addition for this feature to be complete there should be an additional property to set the port number of reverse proxy in the portal.

![image](https://cloud.githubusercontent.com/assets/5148571/24761256/7a2be5c0-1ab0-11e7-833f-677add956477.png)

**Comment by kavyako** [comment]
The current experience in the portal for the Reverse Proxy configs is very limited.
Our team is working on creating a first class experience to enable/configure the reverse proxy, along with options to specify the port etc. Stay tuned!

**Comment by kavyako** [comment]
Portal now has an option to enable reverse proxy and the port to listen on at the time of cluster creation. 
Closing this issue.
