### ISSUE TITLE
Upgrading docker version on Service Fabric cluster

### ISSUE THREAD

**Issue by gauravhub** [Azure/service-fabric-issues#233]
I provisioned a new Service Fabric cluster with Windows containers support and the docker version used on the cluster is **1.12.2-cs2-ws-beta**. This is a beta version while as of today the latest docker version is **17.03.1-ee**.

Is it safe for us to upgrade the docker version on the Service Fabric cluster or will Service Fabric team upgrade the docker version during their release process?

**Comment by mani-ramaswamy** [comment]
This is completed. Docker version is 17.03 in SF clusters now.

**Comment by MikeChristensen** [comment]
I'm wondering what the intended process is.  Right now, the version of Docker running on our cluster is pretty old (Docker version 18.09.6, build 1578dcadd2).  Are we supposed to upgrade this ourselves, or at some point do we just re-image and all of a sudden get a newer version of Docker?
