### ISSUE TITLE
There was an error during activation.Failed to ACL folders or certificates required by application. Error:0x80090014

### ISSUE THREAD

**Issue by munyirik** [Azure/service-fabric-issues#235]
I'm trying to deploy a service fabric application on my local cluster.

In my ApplicationManifest.xml I'm referencing some certificates. I've given NETWORK SERVICE access to these certificates.

When I try to deploy and run the app, I see the error below in the node running the app:

>> Error event: SourceId='System.Hosting', Property='Activation:1.0'.
There was an error during activation.Failed to ACL folders or certificates required by application. Error:0x80090014

I've also tried to use an admin account but that doesn't work either. Is there anything else I can try?

**Comment by masnider** [comment]
I've seen this before a couple of times when Windows thinks there's too many security rules on the folder already (turns out there's a limit :( ) Can you check that?

**Comment by munyirik** [comment]
How do I check it?

**Comment by masnider** [comment]
https://technet.microsoft.com/en-us/sysinternals/bb897332.aspx
https://technet.microsoft.com/en-us/library/cc754344(v=ws.11).aspx
https://support.microsoft.com/en-us/help/166348/maximum-number-of-access-control-entries-in-the-access-control-list

Though the error code looks to be pointing more at this (0x80090014, -2146893804, NTE_BAD_PROV_TYPE): https://msdn.microsoft.com/en-us/library/windows/desktop/aa379886(v=vs.85).aspx

**Comment by masnider** [comment]
Can you also check: http://stackoverflow.com/questions/22581811/invalid-provider-type-specified-cryptographicexception-when-trying-to-load-pri

**Comment by munyirik** [comment]
Thanks @masnider! It looks like the problem I had was that I was creating CNG private keys (as someone mentioned in your last stackoverflow link). 
So when I specified *-Provider "Microsoft Enhanced Cryptographic Provider v1.0"* for the *New-SelfsignedCertificate* command to create a cert, it works. 

Is it my design that service fabric apps can't read them? or is there a fix on the way?

For now my issue is resolved. Thanks again!

**Comment by masnider** [comment]
Great!

**Comment by mkosieradzki** [comment]
Wait. Why did you close this issue? Changing key type from CNG to legacy provider is a workaround not a solution. IMO SF should correctly handle both types of key, especially CNG is getting more traction.

**Comment by Tadimsky** [comment]
@masnider @vturecek I had the same issue when using `New-SelfSignedCertificate` - it seems like something in Service Fabric needs to be updated to support the standard self-signed cert?

**Comment by berndku** [comment]
+1
