### ISSUE TITLE
Firewall ACLings

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#238]
The documents [here][1] say "HTTP endpoints are automatically ACL'd by Service Fabric."

I'm running a standalone cluster and my service manifest contains:

      <Endpoint Protocol="http" Name="ServiceEndpointHttp" Type="Input" Port="8880" />
      <Endpoint Protocol="https" Name="ServiceEndpointHttps" Type="Input" Port="8843" />

The app binds fine to these ports, but the ACLing isn't created in Windows Firewall. Are there additional steps I need to perform to get this to automatically open the ports?

I'd assume I'm meant to see rules that are named like ones [here][2] for port 8880 and 8843, but I only have the normal WindowsFabric ones.

Looking at the [prerequisites for a standalone cluster][3] it says "Have the Remote Registry Service (remoteregistry) enabled", which I assume is the mechanism it uses to setup firewall rules. In services.msc, My Remote Registry service status is blank and the Startup Type is Automatic (Trigger Start). Should I manually start this service on each node in my cluster? Or is this normal.

  [1]: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources
  [2]: https://github.com/Azure/service-fabric-issues/issues/205
  [3]: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation

**Comment by chrissie926** [comment]
Hi Mardoxx,

Yes you need to manually start the remote registry service on each node in your cluster. You can use the client machine and do SC \\COMPUTERNAME start"SERVICENAME" to start the service remotely.

**Comment by Mardoxx** [comment]
Done that, service is running -- ACLings are still not created for new services!

**Comment by tarynt** [comment]
I've had this same issue in 5.5.216 and the current 5.6.220.

I'm running a standalone dev cluster with 3 nodes (on the same host). All the usual firewall rules get created for the cluster, however none of the specified endpoints get ACL'd as per the documentation.

TestConfiguration.ps1 reports that remote registry is available.

As a workaround I've manually opened up my own port range that I use for configuring endpoints.

**Comment by Mardoxx** [comment]
Seems like there's a setup step missing for normal installs of win server as this clearly works on azure machines!

**Comment by Mardoxx** [comment]
Any updates?

**Comment by masnider** [comment]
This is a bug, if not in setup then at least in the docs. Adding a couple folks.

**Comment by masnider** [comment]
Also can you check to see if the firewall service itself is running?

**Comment by Mardoxx** [comment]
@masnider Amazing, thank you!

Please may you clarify what you mean by `firewall service`?

**Comment by rishirsinha** [comment]
This bug will be fixed in the next release coming out at ignite.

**Comment by Mardoxx** [comment]
Brilliant thanks!
