### ISSUE TITLE
Application/Service deployed with compression, always requires all services have config+code version bump on upgrade.

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#240]
When publishing new application with compress package (maybe rather with any CopyPackageParameters specified) then upgrade cannot be done without also bumping code+config version - for all services in application, regardless of if they had any change or not.

The one thing that differs is the line 
`<CopyPackageParameters CopyPackageTimeoutSec="1800" CompressPackage="true" />`
being present in publish profile when being published for the first time.

When upgrading after this, it will delay for a short moment on line 135 in Publish-UpgradedServiceFabricApplication.ps1, and then exit the script with no explanation of why.

Error message in Event Viewer: 

`Store ConfigPackage with Name:Config and Version:1.0.0 in ServiceManifest:MockPkg: settings file doesn't exist- at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo) at System.Environment.get_StackTrace() at System.Fabric.Common.ReleaseAssert.Failfast(String format, Object[] args) at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseConfigPackageAsync>d__40.MoveNext() at **[snip]**`

How to reproduce:

1. Create a new service fabric application, add an actor.

2. In the publish profile, add this:

`<CopyPackageParameters CopyPackageTimeoutSec="1800" CompressPackage="true" />`

3. Publish to local cluster.

4. Upgrade (bump Code version)

We expect this to fail, without any explanation in output.

5. Upgrade (bump Config version)

This would succeed.

**Comment by zeodamian** [comment]
And also, since we have 9 different services within this application, this problem now arouse:


[13:22:46] A: I cannot get the versions to match, what version can you use when upgrading Auxilliary?
[13:23:17] A: it is really picky, all the different services and applications, it seems now it wants a perfect match of version to accept the upgrade
[13:23:28] B: hmmm true I can see 1.0.0
[13:23:36] B: but I am sure I upgraded to 1.0.1
[13:23:45] A: you did to cloud?
[13:23:59] B: well yesterday when you asked me to upgrade
[13:24:04] B: yes
[13:24:10] B: I did it to auxilliary with v. 1.0.1
[13:24:21] A: there is a version 1.0.1 there
[13:24:28] A: if you click on top level, the application
[13:24:34] A: you see the versions
[13:24:44] B: and you can't upgrade it now because of the mismatch?
[13:24:47] A: but the services themselves don't have any higher versions
[13:25:12] A: yeah I cannot figure out what version number I must provide, and on which service, to get it accepted.

So.. this is kind of inconvenient.

**Comment by zeodamian** [comment]
Since we have 9 services in this application, all 9 require config version bump.

But, then we get "Default service descriptions can not be modified as part of upgrade", although no other change has been made than bumping config version.

Major inconvenience with this version fiddle.

**Comment by zeodamian** [comment]
Update:

We have 9 services in this application, all 9 require config version bump AND code version bump, for upgrade to be accepted.

So this granular upgrade-only-what-you-changed is no longer possible.

**Comment by oanapl** [comment]
When using compress, you need to bump the version on the code/config/data packages and specify them in the service manifest. Otherwise use diff provisioning and do not include the unchanged package in the new version package.

@MikkelHegn, to address the question about why UpgradedServiceFabricApplication.ps1 exits with no explanation of the failure.
If you run the [Copy-ServiceFabricApplicationPackage](https://docs.microsoft.com/powershell/module/servicefabric/copy-servicefabricapplicationpackage?view=azureservicefabricps), do you see an error message saying the checksum/content changed without the version changing?

I will add the info about needing to bump the versions in [Compress a package](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-package-apps#compress-a-package).

**Comment by eisber** [comment]
Hit the same issue. My VS just tells me "PowerShell script failed". Running deployment on command line, just crashes PowerShell.

**Comment by oanapl** [comment]
@eisber, "Running deployment on command line, just crashes PowerShell."
Can you tell us which command you ran on command line? And how did PowerShell crash - do you have a stack trace / exception message?

**Comment by oanapl** [comment]
The same was reported in https://github.com/Azure/service-fabric-issues/issues/259 

Application: powershell.exe Framework Version: v4.0.30319 Description:
The application requested process termination through System.Environment.FailFast(string message).
Message: Store ConfigPackage with Name:Config and Version:1.0.0 in ServiceManifest:Stateful2Pkg: settings file doesn't exist

This is a bug and we will fix it in a future release.

**Comment by alexwun** [comment]
Closing - the PS client crash was fixed in version 5.6.210
