### ISSUE TITLE
Debugging/Trace streaming on a standalone cluster

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#241]
How can I achieve [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#debug-a-remote-service-fabric-application) with a standalone cluster.

I assume I'd have to install remote debug tools on an appropriate node, set appropriate firewall rules, and it will work just like normal remote debugging?

How about [trace streaming](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#streaming-traces-from-a-remote-cluster-node) though, how can I connect to the streams of my own standalone cluster?

**Comment by karolz-ms** [comment]
@Mardoxx yes, for remote debugging you would treat standalone cluster just like a set of machines somewhere on your network and proceed as with normal remote debugging setup https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp

Remote trace streaming is not possible at the moment, sorry. We do not have the trace streaming "transmitter" factored out of the Azure VM extension, so the trace streaming is only possible within Azure. The only way is to do remote desktop to the cluster node and use something like [PerfView](https://github.com/Microsoft/perfview) to capture ETW traces.

**Comment by Mardoxx** [comment]
Will you be looking at adding this in the future? Being able to debug on my standalone cluster in a similar manner to that of an azure one would be very useful!

**Comment by BigMorty** [comment]
No, we don't currently have this on our backlog.

**Comment by mack0196** [comment]
I am looking for a feature to get those logs from a standalone cluster. 

Is there an option to view service fabric diagnostics for standalone clusters now or upcoming?

**Comment by karolz-ms** [comment]
Sorry @mack0196 , this feature (streaming traces for standalone clusters) is not on our backlog

**Comment by mack0196** [comment]
Please add it?
