### ISSUE TITLE
Override Parameter IsEncrypted per PublishProfile

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#243]
Is it possible to override the `IsEncrypted` property of `Parameter`s per publish profile?

Basically I want my dev profile to contain unencrypted strings -- which I don't care about encrypting and never leave my machine -- and  my prod one to contain encrypted ones.

**Comment by vturecek** [comment]
No, that's not supported. Usually what I do is encapsulate my config settings into something that I can mock during local deployments. Also great for unit testing.
