### ISSUE TITLE
Purpose of Parameter MustOverride property

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#244]
What is the purpose of the MustOverride property on application setting's parameters?

I've tried setting this to true and not overriding it, but it doesn't seem to do anything?

Is it there for future features?

**Comment by vturecek** [comment]
MustOverride means you have to have a config override in ApplicationManifest.xml. For example:

```xml
<ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="Stateless1Pkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      <ConfigOverride Name="Config">
        <Settings>
          <Section Name="MyConfigSection">
            <Parameter Name="MyParameter" Value="Foo" />
          </Section>
        </Settings>
      </ConfigOverride>
    </ConfigOverrides>
  </ServiceManifestImport>
```

Note that an empty value is valid.
