### ISSUE TITLE
yo generators for Mac OS

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [Azure/service-fabric-issues#245]
Could you add yo generators for application package templates to Yeoman Generators List?

The idea is to allow a developer to create application packages for SF directly from mac os terminal, instead of connecting to virtual box ubuntu system and doing `yo azuresfguest` there.

**Comment by mani-ramaswamy** [comment]
Yes, we're planning to do exactly that in the coming months. @raunakpandya

**Comment by mani-ramaswamy** [comment]
This was completed a few releases ago. https://www.npmjs.com/search?q=azuresf 
Closing the issue - please reopen as appropriate.
