### ISSUE TITLE
Unable to connect to external apis over https

### ISSUE THREAD

**Issue by prebenh** [Azure/service-fabric-issues#246]
I'm unable to do web requests or soap calls from within the local cluster over https. While the same code works in a console application. See my so question http://stackoverflow.com/questions/43473215/calling-wcf-over-https-in-service-fabric-the-request-was-aborted-could-not-cr

**Comment by masnider** [comment]
This looks to be the acling issue as identified in the SO thread. Nothing really to do with SF and there are also SF specific solutions provided. Please let us know if you're still having issues with this, otherwise I'll close down this incident in a few days.

**Comment by masnider** [comment]
Closing as no repro/handled outside of SF. Please reopen if you're still having issues, or comment in the SO question.
