### ISSUE TITLE
Middleware for call remote service methods by RPC

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#247]
I'm trying to add logging to my service fabric app and I have the following issue. For service that communicate by HTTP I have middleware for logging requests and exception:
```
var stopwatch = Stopwatch.StartNew();
var started = DateTime.UtcNow;
try
{
	await _next.Invoke(context);
}
catch (Exception ex)
{
	_logger.LogException(ex, ex.Message);
	throw;
}
finally
{
	stopwatch.Stop();
	bool success = context.Response.StatusCode < 500;
	_logger.LogRequest(requestContext.RequestId, context, started, stopwatch.Elapsed, success);
}
```
How can I implement something similar for call remote service methods by RPC protocol?
My implementation of RPC communication is based on the answers in [this StackOverflow question](http://stackoverflow.com/questions/34166193/how-to-add-message-header-to-the-request-when-using-default-client-of-azure-serv).

Should I use PostSharp or Castle DynamicProxy for that or is  there a simpler solution?
Please suggest
Thank you in advance

**Comment by masnider** [comment]
With the RPC model there isn't really the concept of middleware or an opportunity to intercept the messages before they are dispatched. Is logging the messages before they are dispatched the main thing you're trying to solve?

**Comment by Marusyk** [comment]
I used `Castle.DynamicProxy` to solve the problem
```
public void Intercept(IInvocation invocation)
{
	string requestId = DistributedTracingHelper.Request.GetCallContext();
	string invocationMethodInfo = GetMethodInfo(invocation);
	var stopwatch = Stopwatch.StartNew();
	var started = DateTime.Now;
	bool success = true;
	try
	{
		invocation.Proceed();
	}
	catch (Exception ex)
	{
		_logger.Exception(requestId, ex, "An unhandled exception has occurred: {Message}.", ex.Message);
		success = false;
		throw;
	}
	finally
	{
		stopwatch.Stop();
		_logger.Dependency(requestId, invocation.TargetType.FullName, "ServiceFabric", invocationMethodInfo, started, stopwatch.Elapsed, success);
	}
}
```

and then 
```
var interceptor = new RequestTrackingInterceptor();
 var proxyGenerator = new ProxyGenerator();
 remoteService = (TServiceInterface)proxyGenerator.CreateInterfaceProxyWithTarget(typeof(TServiceInterface), remoteService, interceptor);
```
