### ISSUE TITLE
MicrosoftAzure-ServiceFabric-CoreSDK - some drivers are unsigned

### ISSUE THREAD

**Issue by arikanderu** [Azure/service-fabric-issues#248]
Installation of MicrosoftAzure-ServiceFabric-CoreSDK.exe on Windows 7 completes with two errors, complaining LeasLayr.sys and KtlLogger.sys are not signed:
"Windows requires a digitally signed driver"

**Comment by AlanWarwick** [comment]
Please use Windows Update and update your windows 7 machine with the latest updates. We have seen this issue in the past and the problem was that one of the root certificates was out of date and thus the drivers appeared as unsigned.

**Comment by masnider** [comment]
Hi @arikanderu - were you able to try out @AlanWarwick 's fix? Please let us know if this resolved the situation for you. If we don't hear back from you in a few days then we'll assume this worked out for you and close the incident (you can always re-open it if you get a repo).

**Comment by arikanderu** [comment]
Hi @masnider - my dev box is setup in corporate environment, which means windows updates are published in controlled way by admins. Can you please point me to specific update which should update certificates? Then I would try to reinstall the sdk.

**Comment by AlanWarwick** [comment]
Hi Arikanderu,  I am sorry but I do not have the information on the specific update needed. Were you able to get the latest updates and successfully install the SDK ?  Thank you.

**Comment by AlanWarwick** [comment]
Closed due to lack of response.
