### ISSUE TITLE
ConnectionDeniedException on new Asp.Net Core Template

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#25]
On the brand new Asp.Net Core Template, if I try to run the WebService **without Service Fabric** the following exception will be thrown. For Tests, the WebService starts a lot faster than deploying the package.
Is there a workaround for this?

![image](https://cloud.githubusercontent.com/assets/5556013/16521949/b7c3b378-3f9a-11e6-8119-6f46d518b9e2.png)

**Comment by MedAnd** [comment]
This might be worth trying: http://www.medic-consulting.com/2016/07/05/Asp-Net-Core-with-Kestrel-and-Service-Fabric/

**Comment by senj** [comment]
Looks promising, thanks
