### ISSUE TITLE
ActorService-based service receives duplicate prefixes to listen on when using HTTP endpoint

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#252]
When using HTTP endpoints, multiple partitions are receiving the same prefix http://10.2.140.4:20009 for listening.

My registration is:
```
<Endpoint Name="<myendpointname>" Protocol="http" />
```
In stateful services this works as an internal endpoint.
Also: it seems replicas are trying to listen on secondaries (I have observed this in Service Fabric Explorer) (despite the fact that default value in ServiceReplicaListener for listenOnSecondary is false.

UPDATE:
I have bumped up the partition count for stateful services and the same thing happens for them as well.

So I believe this issue must be on my side.

And the ActiveSecondary listening happens during failover attempt.

What I am observing:
1. Partitions on different nodes are getting different ports (I am using two listeners for each service):
0: http://10.2.140.4:20019, http://10.2.140.4:20020
1: http://10.2.140.5:20017, http://10.2.140.5:20018
2: http://10.2.140.6:20022, http://10.2.140.6:20023

And some partitions (one per each node) wins the race for those ports, and the others have errors like: "The prefix 'http://+:20018/' is already registered."

UPDATE 2:
Found the updated documentation:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore

It seems it might be this described WebListener issue (AFAIR in preview version there were no such issues).

UPDATE 3:
Updated documentation and changes (since the preview) to the ASP.NET Core integration are really nice. After following the updated documentation everything works as expected!

**Comment by vturecek** [comment]
Tagging with the 5.5.216 milestone, for posterity, when we release the ASP.NET Core integration packages that appear to be the fix to this issue.
