### ISSUE TITLE
Scale out should deploy containers in parallel in new VMs

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/service-fabric-issues#254]
I expanded a fabric cluster from 6 nodes to 8 nodes. It took 12 minutes to create the empty VMs. Then, it took 13 minutes to deploy containers on first VM, and other 13 minutes to deploy containers on second VM.

I was surprised to see it deployed the containers sequentially on the VMs so I repeated the process. I shrink to 6 nodes and expand to 8 nodes. I got similar results.

I ran these commands to perform scale.
```
$vmss = Get-AzureRmVmss -ResourceGroupName "test-scus" -VMScaleSetName "test-scus-fabric-nt0"
$vmss.sku.capacity = 8
Update-AzureRmVmss -ResourceGroupName "test-scus" -Name "test-scus-fabric-nt0" -VirtualMachineScaleSet $vmss 
```

**Comment by RajeetN** [comment]
Windows or Linux?

**Comment by gustavo-armenta** [comment]
windows

**Comment by mani-ramaswamy** [comment]
Gustavo - were you able to reproduce this with the latest 5.6 release?

**Comment by mani-ramaswamy** [comment]
And while Service Fabric will be deploying in parallel, the VM instances may be coming up sequentially leading you think so.

**Comment by gustavo-armenta** [comment]
it happens on Service Fabric 5.6.210.9494 windows

**Comment by mani-ramaswamy** [comment]
Can you confirm that on a  fixed size cluster, it is happening in parallel? When the cluster size scales, it might scale sequentially (though SF deploys in parallel) causing this behavior.

**Comment by mani-ramaswamy** [comment]
Since we've not gotten a response for a few months, I am closing this issue. Please reopen the issue as appropriate.

**Comment by gustavo-armenta** [comment]
Mani, please reopen this issue or explain how the team decided this issue is not important to fix

**Comment by mani-ramaswamy** [comment]
@gustavo-armenta - were you able to confirm that on a fixed size it isn't happening in parallel?  It should be happening in parallel.   The issue you are hitting is because one node is being added  at a time - we can redirect the issue to the appropriate team on adding more VMs simultaneously.
