### ISSUE TITLE
Is Service Fabric compatible with Cross Platform DotNet Core?

### ISSUE THREAD

**Issue by jtoussaint** [Azure/service-fabric-issues#255]
I'm trying to create a dotnet core project on my mac that that will deploy to a service fabric cluster running on a vm.

I grabbed the yeomon generator from the linux vm and generated a project.  The first thing that I noticed is that it generated project.json files, which have now been replaced with csproj files - right?

I ran dotnet migrate on each of those projects and that worked well, however dotnet restore failed, so I updated the project file to use the latest package builds on nuget.  I'm still getting an error that leads me to believe that I cannot create a cross platform dotnet core app.  I am getting an error like this for a number of ServiceFabric packages:

/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Package Microsoft.ServiceFabric 5.5.216 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.ServiceFabric 5.5.216 supports: net45 (.NETFramework,Version=v4.5) 

I see that we are working on providing a new yeomon generator, but at this point I am just trying to get something to compile.  I am happy to fix the project files and references myself if necessary.  What confuses me about this is what I think that at some point the yeomon generator must have created a valid service and test client on a linux box.  I'm guessing that would fail now too.

Can someone confirm if this is even possible?  It feels like I need to create this client on a windows vm, but I'd like some confirmation.

**Comment by Remy-Burney-Powerfront** [comment]
Hi,
I think you can create .net core services but the build project seems to be using .net 4.x on windows.
So maybe it's not fully doable right now on MAC.

**Comment by aL3891** [comment]
Currently you can use .net core projects as guest executables, but the sdk itself does not support .net core, so you can't write services that integrate deeply with service fabric or actor services on .net core yet. They plan to support .net core in the .net core 2 timeframe, so in Q3.

However you can still use _asp_.net core, with the sdk, as long as you host it on full framework

**Comment by mani-ramaswamy** [comment]
aL3891 -  jutoussaint is on LInux/Mac, which is .NET Core, so they can run it natively on Linux/Mac. While on Windows, we don't have the SDK support, on Linux/Mac, the SDK does support it.

Adding a couple of folks to help debug the issue here.

**Comment by deepakjangid-MSFT** [comment]
This will be fixed in next release of the sdk.

**Comment by deepakjangid-MSFT** [comment]
Microsoft.ServiceFabric is part of windows .net sdk and should not be included in project.json or *.csproj files for .net core apps.
Can you please share your project file and the error you were getting in restore before you updated the packages?

Note that core sdk packages for Service Fabric are not available on nuget.org. They are shipped in deb package and the directory path is provided to restore command to complete the restoration.

**Comment by timjroberts-inty** [comment]
I've spent a week trying to do the very same thing - with no luck.

If you pull `Microsoft.ServiceFabric.*` from NuGet you'll be getting packages that do only run on .NET Framework only. I copied the packages from the installed `servicefabricsdkcsharp` package on the Linux machine to my Windows and Mac machines in order to get everything building.

The reason why you're seeing all the `project.json` files is that the `servicefabricsdkcsharp` package is still using .NET Core 1.0.0 Preview 2. I've not been able to get anything successfully running using a later version of .NET Core (targeting `netcoreapp1.0`), and even if I use that specific version of .NET Core, it only appears to work if the build was done on a Linux machine. If I build from Windows or Mac, then I get `Failed to initialize CoreCLR: 0x80131500` during package activation.

It would be nice if Service Fabric simply supported .NET Core rather than having the Windows and Linux flavours of the SDK. I find it ironic that Service Fabric can support Guest Executables and Containers but not .NET Core.

**Comment by mani-ramaswamy** [comment]
@timjroberts-inty . Yes, we plan to support .NET Standard across Windows/Linux over the upcoming months. Today, you create .NET Core apps on Linux and full .NET Framework apps on Windows.

**Comment by bklooste** [comment]
Can we get an Eta  and what version of ,netstandard ( 2.0 is very limiting). Also are there beta / prerelease packages ?

**Comment by hrushib** [comment]
Service Fabric .NET SDK 3.0 Preview is now available, this SDK includes .NET Standard 2.0 based SDK libraries which can be used to build cross platform applications.

For details refer [Service Fabric 6.0 Release](https://blogs.msdn.microsoft.com/azureservicefabric/2017/09/25/service-fabric-6-0-release/)

**Comment by oacsed** [comment]
As stated in the latest release (6.1, see https://blogs.msdn.microsoft.com/azureservicefabric/2018/01/26/service-fabric-6-1-release/), "_In this release, .NET Core 2.0 services are only supported on Service Fabric for Windows. Full cross-platform support for .NET Core 2.0 services on Windows and Linux is coming soon._."

Any ETA for full cross-platform support?

**Comment by mani-ramaswamy** [comment]
Should be in the next couple of months.
