### ISSUE TITLE
Deploying StatelessWebAPi to a https endpoint failes

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#256]
The OwinCommunicatioListener.cs  class has on line 84 this code
`                    this.listeningAddress = string.Format(
                        CultureInfo.InvariantCulture,
                        "http://+:{0}/{1}",
                        port,
                        string.IsNullOrWhiteSpace(this.appRoot)
                            ? string.Empty
                            : this.appRoot.TrimEnd('/') + '/');`

"http" is hard coded it should be nameof(serviceEndpoint.Protocol).

**Comment by Mardoxx** [comment]
Uh... that would output "Protocol"

What version sdk/tooling are you using?

**Comment by eliasnawfal** [comment]
I m using 2.5.216 with VS 2017.

**Comment by vturecek** [comment]
In 2.5.216 we released listeners for ASP.NET Core WebListener and Kestrel that supersedes the OwinCommunicationListener sample code. If you're already on 2.5.216 and VS 2017, you should switch over to ASP.NET Core. More info on that here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore

**Comment by eliasnawfal** [comment]
I'm using OwinCommunicationListener in one of my ServiceFabric apps because I need it for backward compatibility for Azure Mobile Server, all other apps are already on ASP.NET Core.

**Comment by Mardoxx** [comment]
Can you not just make your own, modified version of OwinCommunicationListener?

I don't know your code base but are you certain you can't upgrade?

**Comment by eliasnawfal** [comment]
@Mardoxx  Yes I'm certain I can't upgrade,
It is not a big deal, the problem will show up only on https Endpoint.
I solved the problem using nameof(serviceEndpoint.Protocol).

**Comment by Mardoxx** [comment]
How does thst fix it? Doesn't `nameof(serviceEndpoint.Protocol)` just return the string "Protocol"?

**Comment by eliasnawfal** [comment]
@Mardoxx  This issue is just a remark that when you create new WebApi in Service Fabric, the sample OwinCommunicationListener has http protocol as string and it will not change with your ServiceEndpoint.
In a development environment everything would work, but when you to deploy to an https Endpoint your WebApi will fail. I just changed "http" to nameof(serviceEndpoint.Protocol), this will make it change based on the Endpoint.

**Comment by Mardoxx** [comment]
I'm not seeing how having Owin listen to (literally) "Protocol://+{port}{appRoot}" could possibly fix the issue! "Protocol" isn't even a valid protocol is it?! Very strange.

http://ideone.com/fiJsHG is how I expect `nameof` to behave

**Comment by eliasnawfal** [comment]
nameof(serviceEndpoint.Protocol) will have value http or https. It depends on your selected EndPoint from ServiceManifest.xml
`      <Endpoint Protocol="http" Name="ServiceEndpoint" Type="Input" Port="4004" />
      <Endpoint Protocol="https" Name="ServiceEndpointSecure" Type="Input" Port="5004" />`

**Comment by Mardoxx** [comment]
That isn't what `nameof` does. https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/keywords/nameof

**Comment by eliasnawfal** [comment]
@Mardoxx 
To make it clearer, 
`EndpointResourceDescription serviceEndpoint = this.serviceContext.CodePackageActivationContext.GetEndpoint(this.endpointName);`
`EndpointProtocol protocol = serviceEndpoint.Protocol;`

**Comment by Mardoxx** [comment]
```cs
public Task<string> OpenAsync(CancellationToken cancellationToken)
{
    EndpointResourceDescription serviceEndpoint = this.serviceContext.CodePackageActivationContext.GetEndpoint("ServiceEndpoint");
    string protocol = serviceEndpoint.Protocol;
    int port = serviceEndpoint.Port;

    this.listeningAddress = String.Format(
        CultureInfo.InvariantCulture,
        "{0}://+:{1}/{2}",
        protocol,
        port,
        String.IsNullOrWhiteSpace(this.appRoot)
            ? String.Empty
            : this.appRoot.TrimEnd('/') + '/');
//...
```

**Comment by eliasnawfal** [comment]
@Mardoxx EndpointProtocol  is an Enum in my project.
Maybee different SDK versions
![screenshot 1](https://cloud.githubusercontent.com/assets/15719103/26123600/5fc596ee-3a73-11e7-8773-b6bfd0d89c7d.png)

**Comment by Mardoxx** [comment]
Sorry, missed out `.ToString()`!

http://ideone.com/hkJMC8

**Comment by eliasnawfal** [comment]
@Mardoxx 
Yes nameof() would work the same.

**Comment by Mardoxx** [comment]
No way?! I thought that just work for the enums themselves, and not if it's on a variable?

**Comment by vturecek** [comment]
Going to close this one out since we're removing the OwinCommunicationListener project template and sample code soon here, but yeah for your case I would just modify the source to do what you need.
