### ISSUE TITLE
Test-ServiceFabricApplicationPackage powershell crash

### ISSUE THREAD

**Issue by makar-sasha** [Azure/service-fabric-issues#259]
Hello. After upgrade to sdk 2.5.216 and runtime 5.5.216 Test-ServiceFabricApplicationPackage command works only for complete package. In case of partial app upgrade (diff package) it results in "Windows PowerShell has stopped working". 
to reproduce:
1. create test app with 2 services and deploy.
2. change app version and particular service version.
3. create package and remove Pkg folder from it for the service without modifications.
4. connect to Service Fabric and test like `Test-ServiceFabricApplicationPackage -ApplicationPackagePath "..path" -ImageStoreConnectionString "fabric:ImageStore"`

**Comment by oanapl** [comment]
Thank you for reporting. We will investigate and get back to you.

**Comment by oanapl** [comment]
@makar-sasha, I was not able to repro this.
I built an app with 2 services, copied and provisioned it. Then I increased app version in app manifest, increased one of the services version, referenced increased service version from app manifest. Remove the unchanged service package from manifest. Test worked fine.

```powershell
PS C:\Users\oanapl> Copy-ServiceFabricApplicationPackage -ApplicationPackagePath E:\pkg\FrankApp -ImageStoreConnectionString fabric:ImageStore
Copy application package succeeded

PS C:\Users\oanapl> Register-ServiceFabricApplicationType -ApplicationPathInImageStore FrankApp
Register application type succeeded

PS C:\Users\oanapl> Test-ServiceFabricApplicationPackage -ApplicationPackagePath E:\pkg\FrankApp_v2 -ImageStoreConnectionString fabric:ImageStore
True
```
Can you take a dump or give us the call stack of the powershell crash?

**Comment by makar-sasha** [comment]
@oanapl , thanks for checking. I will provide the dump as soon as I can.
but could you clarify: as I understand you have updated ApplicationManifest.xml ? In my scenario this file contains references to both services, but the folder for unmodified service is deleted from the package.

**Comment by makar-sasha** [comment]
this scenario also happens when we are upgrading app from the visual studio. Could you change app version and particular service version (the second one should have the same version with cloud) and try to publish from visual studio 2017 with "Upgrade the Application" checked?

**Comment by oanapl** [comment]
@makar-sasha, to expand on the changes I had
v1 has AppManifest with version 1.0.0 and references 2 service manifests, both with version 1.0.0
v2 has AppManifest with version 2.0,0 and references service manifest 1 with version 1.0.0 and service manifest 2 with version 2.0.0.
v2 app package contains the app manifest and the service folder for the changed service. Doesn't contain the service that was not changed.

I tried the same scenario in Visual Studio with Upgrade and there was no crash or errors.

There must be something that is missing to repro this. Does this happen for a specific application? Can you detail the steps you took?

**Comment by makar-sasha** [comment]
@oanapl I think the most important part is `<CopyPackageParameters CopyPackageTimeoutSec="3600" CompressPackage="true" />` in publish profile. In my test without it the diff upgrade is working. But with it upgrade from VS2017 is broken.
1. Setup compression
2. Publish from VS2017 app ver 1.0.0 (with 2 services).
3. Upgrade app and first service version.
4. Publish from VS2017 with "Upgrade the Application" option.

Result is - "**The PowerShell script failed to execute"**

**Comment by makar-sasha** [comment]
Actually I think this is similar to [#240](https://github.com/Azure/service-fabric-issues/issues/240).
Because in case of compression diff package testing with `Test-ServiceFabricApplicationPackage -ApplicationPackagePath "..path" -ImageStoreConnectionString "fabric:ImageStore"` results in 

> Application: powershell.exe Framework Version: v4.0.30319 Description: 
The application requested process termination through System.Environment.FailFast(string message). 
Message: Store ConfigPackage with Name:Config and Version:1.0.0 in ServiceManifest:Stateful2Pkg: settings file doesn't exist

**Comment by oanapl** [comment]
Yes, this is the same issue.
Thank you for the error message, very helpful to figure out what is wrong. This is a bug on our side, we will fix in a future release. I will track it in https://github.com/Azure/service-fabric-issues/issues/240
