### ISSUE TITLE
Reload environment variables

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#260]
I store sensitive data for services in environment variables. Sometimes I have to change it. 
How can I reload environment variables for the service?

**Comment by VipulM-MSFT** [comment]
Can you clarify the requirements? This does not seem specific to Service Fabric.

**Comment by mgrishkov** [comment]
For example, I store JWT secret key in the machine  environment variable. Every two month I have to change it's value. A service that using it doesn't catch changing event that send windows till it been restarted. So it continue using old value of secret key.
To solve this issue for IIS I need to restart IIS only. What should I restart when hosting services within service fabric?

P.S. Only way to solve my issue that I found is reboot server, but as for me it is strange solution.

**Comment by qrli** [comment]
you can:
1) use remote powershell to do restart-service FabricHostSvc
2) or use 19080 management page to restart each node
3) or use powershell commands to restart each node
4) or use Consul to manage settings and use envconsul to convert settings to env variables, as well as restart your service. This is similar to Kubernetes' ConfigMap feature.

**Comment by mgrishkov** [comment]
Thank you. Can you please share any information about the 4th point?

**Comment by cwe1ss** [comment]
@qrli Did you setup consul in your Service Fabric cluster? If so, could you share the SF configuration files you've used (ApplicationManifest, etc)?

**Comment by qrli** [comment]
@cwe1ss 
We could host consul servers inside Service Fabric, but we set up consul servers as a separate resource group because we have several clusters to share the same consul. 

On service fabric VM node, we only run a consul proxy agent, which is setup by VM setup script extension of VMSS. It is possible to use a service fabric application package to deploy consul agents to service fabric, but our Ops thinks the VM setup script is easier for them to share code across other IaaS clusters.

**Comment by VipulM-MSFT** [comment]
When you run the application upgrade you can specify the force restart option. You can use environment variables in the user context (as opposed to the machine context). The attached example shows how you can use setup entry point to read the settings and set them as environment variables for the guest executable to read. The example is very raw - it is not curated but should give you an idea on how to use it.

WARNING: The example only shows how you can use the setup entry point to store something in the environment variable of the user. The cleanup of the these environment variables is not explained in the example. The better option than using the "user" or "machine" level environment variables is to store these in the file and then read the file in the guest executable.

When you want to change these settings, you can use the service fabric application upgrade to roll out the changes in the cluster. This will protect you against wrong values in the settings resulting in unavailability of your service. 

Here is how to use the attached example:

[SfGuestEnvApp.zip](https://github.com/Azure/service-fabric-issues/files/1002861/SfGuestEnvApp.zip)

- Deploy the sample 
- Verify that the right environment variables are being read by the guest executable by looking at the envvars.txt file in the work folder of the application
- Change the value of the settings through application upgrade with force restart 
```
Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/SfGuestEnvApp -ApplicationTypeVersion
 1.0.0 -ApplicationParameter @{"MyParameter" = "Value3"} -Monitored -ForceRestart -HealthCheckWaitDurationSec 30  -Failu
reAction Rollback -HealthCheckRetryTimeoutSec 40
```
- Observe that the new value of the environment variable is used by the guest executable

**Comment by VipulM-MSFT** [comment]
For the issue that is opened - you can run application upgrade with -ForceRestart option. You do not need to change the manifest versions. Just update one of the parameter values to new a value when running the upgrade. I will be closing the issue with this and above information.

**Comment by mgrishkov** [comment]
Ok. Thank you for information!

**Comment by wonix** [comment]
ForceRestart does not seem to work? Tried passing in by itself, "true", "True" but the Explorer shows "false" regardless.
![image](https://user-images.githubusercontent.com/1168995/27648695-317d81c4-5be4-11e7-9e43-2565fde51ef0.png)
