### ISSUE TITLE
Error event: SourceId='System.FM', Property='State'. Partition is below target replica or instance count.

### ISSUE THREAD

**Issue by valcs007** [Azure/service-fabric-issues#261]
Hi,

I have set up a local cluster. I wrote a microservice with Remotinlisteners in VS IDE 2015. Most of the time, it throws an exception "Service doesn't exist" when i try the run the code.

When i looked into Service fabric explorer, it was showing healthy and suddenly it the below error

**Error event: SourceId='System.FM', Property='State'. Partition is below target replica or instance count.**

**The ServiceType was not registered within the configured timeout.**

Can you please let me know what could be the issue?

**My Code Snippet:** I invoke my service using Service proxy

ICustService masterService = ServiceProxy.Create<ICustService>(new Uri("fabric:/Customer_Service_Fabric/CustService"));

custList = await masterService.GetCustList() - It throws when it executes this function.

**Few Observations:**
 If i run in debug mode, i don't see this issue

**Comment by vturecek** [comment]
Usually means your service is crashing on start-up. Couldn't tell you why without more output, logs, or stack trace.

**Comment by masnider** [comment]
@valcs007 - hi, without more information, we're not going to be able to help you. Were you able to resolve this issue? As mentioned, this is usually just a misconfiguration where there's more replicas than nodes, or something similar. 

Please let us know if you have more information and we'll be willing to help, otherwise we will close down this issue.

**Comment by valcs007** [comment]
It works fine now, so i will go ahead and close the issue.

**Comment by Fkarajeh** [comment]
I'm facing same error, will you please help me, and tell how you have solve it, please this is urgent

**Comment by Capotasto** [comment]
@valcs007 Hi there, I have the same problem now. How did you solve this?

**Comment by coreConvention** [comment]
I ran into this issue. Service Fabric Explorer was no help. Eventually I found in the StatelessService implementation I had to add HttpClient and FabricClient in the configure services blocks. Hopefully this helps someone:

return new WebHostBuilder()
                            .UseConfiguration(configuration)
                            .UseHttpSys()                            
                            .ConfigureServices(
                                services => services
                                    **.AddSingleton(new HttpClient())
                                    .AddSingleton(new FabricClient())**
                                    .AddSingleton(serviceContext)
                                    .AddSingleton<ITelemetryInitializer>((serviceProvider) =>
                                        FabricTelemetryInitializerExtension.CreateFabricTelemetryInitializer(serviceContext)))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseStartup<Startup>()
                            .UseApplicationInsights()
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseReverseProxyIntegration)
                            .UseUrls(url)
                            .Build();

**Comment by Fkarajeh** [comment]
Dears,

 

Any update please, are we done?

 

Can we test it?

 

With best regards

Fadi Karajeh    CMA,MBA,MBSS

Managing Director



 

Tel: +962 6 5850727

Fax: +962 6 5850161

Jordan Mobile: +962 795053602

KSA Mobile: +966 4910189

Skype: fkarajeh77

Email: fkarajeh@pioneersconsult.com <mailto:fkarajeh@pioneersconsult.com> 

 

p.o. Box 11120 36202

**Comment by coreConvention** [comment]
This change is in your/the users implementation of the Service context in the "CreateServiceInstanceListeners()" override (in my case Microsoft.ServiceFabric.Services.Runtime.StatelessService). I don't think its an issue with the service fabric code itself. I'm not sure why it would be required, but it fixed the issue for me. Although it seems like every issue with service fabric seems to throw a similar or the same exception as far as I can tell from Service Fabric Explorer.
