### ISSUE TITLE
Service resolution fails within same application if services don't run on same node

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#262]
I have a couple of services in the same applcation. Here's a cut down example:

In my application, `FooApplication` have a stateless service `FooService` using the remoting library and a stateless .net core stateless web service `FooWebService`.

The interface to FooService is just something like this

```
public interface IFooService : IService
{
    Task<string> GetFoo();
}
```

`FooWebService` calls this using `ServiceProxy.Create<IFooService>(new Uri("fabric:/FooApplication/FooService"))`

In my `applicationmanifest` `FooWebService` is set to have an instance count of `-1` and `FooService` also has an instance count of `-1`.

I am running this in a standalone 3VM cluster.

This works perfectly.

However! When I change the instance count of `FooService` to less than the number of nodes in my cluster (i.e. > 0 and < 3) the remote call sometimes fails and times out, with no obvious error.

It's as if the service locator can't locate the service unless both are running on the same machine -- (only when the caller and callee are within in the same application!)

I have other services in other applicaitons with singular instance counts, and these are resolved fine from `FooWebService`, just not within the same application it seems.

Is there something obvious I have missed? Or would you like me to provide a cut down repro?

**Comment by Mardoxx** [comment]
Just had another little play with it.

`FooService` is running on `VM0`

`FooWebService` is running on `VM0`, `VM1` and `VM2`.

If I connect to `VM0`, the call to `FooService` works fine.

If I connect to `VM1` or `VM2`, the call to `FooService` times out and fails.

**Comment by Mardoxx** [comment]
Attached is a cut down repro.

1. Install on a non-local cluster.
1. Open port 8888 on each node if SF doesn't do it automatically
1. Open SF explorer and find out which node `FooService` is running on e.g. 10.0.0.10
1. Browse to http://10.0.0.10:8888/api/Foo it should respond with `["foo"]`
1. Browse to http://10.0.0.10:8888/api/Foo/somestring it should respond with "foo somestring"
1. Find a node which has `WebService` installed , e.g. 10.0.0.11
1. Browse to http://10.0.0.11:8888/api/Foo it should respond with `["foo"]`
1. Browse to http://10.0.0.11:8888/api/Foo/somestring it should respond with "foo somestring", _but it does not - it fails_

[SFIssue262.zip](https://github.com/Azure/service-fabric-issues/files/986103/SFIssue262.zip)

**Comment by Mardoxx** [comment]
Okay, even in a separate service this doesn't work. What gives?

**Comment by Mardoxx** [comment]
Problem was firewall ACLings aren't being set up properly by service fabric for local clusters.

**Comment by heavenwing** [comment]
@Mardoxx @igargov
firewall ACLings still aren't being set up properly by service fabric for RemotingListener's port of  a stateless service
could you re-open this issue?
