### ISSUE TITLE
Reverse Proxy: query parameters are not passed when protocol is WebSockets

### ISSUE THREAD

**Issue by skwasiborski** [Azure/service-fabric-issues#266]
When using Service Fabric reverse proxy with http query string parameters are passed as expected. When using web sockets the query part of the url is not passed to the service (i.e. everything after '?' is omitted).

I am using stateless service with OWIN listener. The query string is not present even if I try to trace it in the first middleware of the OWIN pipeline.

**Comment by kavyako** [comment]
This is a bug in the reverse proxy, we will address it for the next release.
Thank you for reporting!
