### ISSUE TITLE
Remove  IService dependency or require just on  Service

### ISSUE THREAD

**Issue by bklooste** [Azure/service-fabric-issues#27]
The IService root dependency for Remoting means all Contracts assemblies depend on ServiceFabric even if they are used in non ServiceFabric Services.   MyService: MyInterface , IService would be ok .

**Comment by vturecek** [comment]
Yeah it does mean you have to pull in Service Fabric packages IService is how you "tag" your interface as the remoting contract. Suppose you have MyService : Interface1, Interface2, IService. It wouldn't be clear which interface is the remoting contract.

**Comment by aelij** [comment]
@vturecek True, but you could allow specifying the contracts in the ServiceRemotingDispatcher constructor instead of reflecting on the type. This would also allow for more advanced dispatching scenarios (for example, adding interception to the service interface).

**Comment by DenisPitcher** [comment]
Please vote for the following suggestion to move IService and related interfaces to a separate namespace + package
https://feedback.azure.com/forums/293901-service-fabric/suggestions/17935681-move-iservice-and-related-remoting-interfaces-to-t

Feel welcome to offer additional suggestions.  Anything would be better than the heavy coupling that is present at the moment

**Comment by VipulM-MSFT** [comment]
@aelij - Yes we are considering changing to specifying the interfaces you want to remote in the constructor. This does mean that every method on that interface and all parent interfaces must be "remote-able". It also has the side effect that we will not be able to check them at build time but only at runtime. Once you deploy your service it may not come up if one of the methods in the interface hierarchy is not remote-able. 

 Furthermore if you do change argument names, method name, type name they will be breaking changes and you cannot do rolling upgrades. This was true with IService based interfaces as well. But as I mentioned we wanted to ensure that developers keep internal interfaces and remoted interfaces as separate and version them separately.

**Comment by aelij** [comment]
> service it may not come up if one of the methods in the interface hierarchy is not remote-able

This is not a huge concern IMO. It's easily fixable after a runtime error (we usually don't deploy services without testing them first ;). Also specifying the types directly could be considered an "advanced" scenario, where the developer wants to accomplish things such as interception I mentioned above.

> ensure that developers keep internal interfaces and remoted interfaces as separate

We keep them in separate assemblies. Usually the remoting interfaces are in `SomeService.Contracts` assembly. Others are implementation detail of a service, so they reside with the service code. Since you can't really enforce it, I don't think `IService` really accomplishes this kind of separation.

A different option altogether is to use an attribute, like WCF's `[ServiceContract]`. The advantage is that it won't require referencing the SF libraries to consume remoting interfaces. I haven't encountered extension methods that rely on `IService` other than `CreateServiceRemotingListener`, which can work without this constraint. 

Another advantage of attributes is that a custom one could be used, thus completely removing the need to reference the SF library for contracts.

Finally, most of the concerns regarding correctness could be appeased by including a Roslyn analyzer for remoting contracts.

**Comment by DenisPitcher** [comment]
FYI, I think @VipulM-MSFT is referring to details discussed in related thread  #55 

@VipulM-MSFT Do you have any guidance published on interface structure and versioning?  This requirement is fairly new to me and I have been working under the assumption that contract versioning for the Service Fabric works similarly to WCF.  I'd like to read up a bit more on the implications for rolling upgrades and what the recommended approach is.

**Comment by bklooste** [comment]
Another great example of why NOT to use remoting , its such a leaky abstraction it permeates all the way through the system. Quick to get running - utter nightmare at scale and and when you have other teams developing stuff.

**Comment by DenisPitcher** [comment]
@bklooste What have you found works better as an alternative?

**Comment by bklooste** [comment]
Web api is fast enough now in most cases ( and you can service json clients)   and my services do a lot of chunky call set operations GetByIds , UpdateMany.. your io limited and the json serializers are so good these days. If i need more performance custom nettcp binding on WCF and further still zeromq  / Avro . Service Fabric don't care...

**Comment by jricke** [comment]
@VipulM-MSFT  Any updates on being able to specify the interfaces via the constructor?

**Comment by Mardoxx** [comment]
I'm sure I read/listened to something about not requiring to implement `IService` about a week ago (Ignite).. Can't for the life of me find it now!

Did I imagine this?

**Comment by suchiagicha** [comment]
With the Service  Remoting  V2 Stack, you can achieve this. 
We are working on publishing sample and documentation.
Here are the steps  for time -being.

1. You need to add a Listener by explicitly specifying a dispatcher. 
[ServiceRemotingDispatcher ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.v2.runtime.serviceremotingmessagedispatcher.-ctor?view=azure-dotnet#Microsoft_ServiceFabric_Services_Remoting_V2_Runtime_ServiceRemotingMessageDispatcher__ctor_System_Collections_Generic_IEnumerable_System_Type__System_Fabric_ServiceContext_System_Object_Microsoft_ServiceFabric_Services_Remoting_V2_IServiceRemotingMessageBodyFactory_) takes list of types to remote on in one of its constructor.

  protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new[]
           {
                new ServiceInstanceListener(this.CreateListener)
            };
        }

        private ICommunicationListener CreateListener(StatelessServiceContext arg)
        {
            IEnumerable<Type> remotingTypes = new Type[]
             {
                typeof(IAdder)
             };
            return new FabricTransportServiceRemotingListener(arg,new ServiceRemotingMessageDispatcher(remotingTypes,
                arg,this));
        }
 
2.  On the Client Side.
You need to create proxy , using this Api.

    var proxyFactory = new ServiceProxyFactory((c) => new FabricTransportServiceRemotingClientFactory());
            var proxy = proxyFactory.CreateNonIServiceProxy<IAdder>(new Uri("fabric:/V2NonMarkerRemoting/Stateless1"));
