### ISSUE TITLE
Disable automatic update of parameter file

### ISSUE THREAD

**Issue by aL3891** [Azure/service-fabric-issues#271]
Hello, 
Is there a way to disable the automatic updates the vs tooling makes to the app manifest and parameters file?

Specifically it seems like the tooling always sets the partition count of any parameter file that is used by the local*.xml publish profiles to 1, and also not having a publish profile specifically named Local.5Node.xml is not allowed witch is a bit annoying. this also seems like a completely arbitrary constraint, I assume its ment for tooling but it should at least be possible to disable it to be able to debug multi partition services and also restore backups from production servers locally

**Comment by aL3891** [comment]
It seems like removing the `GeneratedIdRef=` attribute from each actor service in the app manifest does disable the replacement behavior.

**Comment by amanbha** [comment]
removing GeneratedIdRef is not the correct way, Tooling sets the optimal parameter values in parameter files for the Local.1.Node.xml and Local.5.Node.xml parameter files. Once you change the values in parameter files, they will not be overridden (until and unless you rename the Actor)

**Comment by aL3891** [comment]
Yes i' know it does that, what i want to do is disable it, as i don't consider it "optimal". 

I only want to have one parameter for setting the replica/partition count for all services. (and the reason for that is to simplify deployment scripts) I've found that i can change the service definitions to use a parameter that i define instead of the generated ones, but now i have a ton of unused parameters gunking up the file that i can't remove since the just end up being added back again.

It seems like the proper way to disable this would be to have an msbuild parameter for it, but looking though the targets file i have not been able to find one and as far as i know, the tooling is not open source and taking contributions.

**Comment by amanbha** [comment]
Could you please explain the scenario when you mean one parameter file. You can create other parameter files as well and use them too, they are not touched by tooling in any way.

**Comment by aL3891** [comment]
I'm aware of that, but the tooling also modifies the service manifest and adds parameters for each service there. That's what i want to disable.

i want to have a single parameter to set the replica and partition count, for all services so that i can easily specify it to the powershell cmdlets when deploying, otherwise the scrip will have to know all the services inside the app its deploying. Ideally i would not use parameter _files_ at all and specify the parameters directly to the script

As an aside i also want to have multiple partitions on my local cluster but the tooling overwrites those parameters and set them to 1.

It feels unnecessary to have to add identical parameter files just because the tooling can't leave the default ones alone, also the project doesn't build at all if the default ones are removed witch also seems like a very strange restriction.

**Comment by amanbha** [comment]
Please note that tooling does not change the parameter values once you change them. It only adds optimal values when mainfests and parameter files are generated for the first time(or if you rename Actor)
Local5Node and Local1Node parameter files exist for enabling 5Node and 1Node development scenarios and those files are not intended to be be removed. You can create other parameter files and use them.

You mentioned" Ideally i would not use parameter files at all and specify the parameters directly to the script". Which script are you referring to? You can use SF cmdlets like New-ServiceFarbicApplciation ithout these param files ad pass paramters on command line.

**Comment by aL3891** [comment]
i'm aware of all that, but as i mentioned, the tooling recreates parameters for each service if i remove them. i just want to have a single set of parameters for all services. I have that working now but i don't want to have all the unused parameters in my manifest files.

We have our own scripts that deploy several applications. That is where i'd prefer to specify a single set of parameters. 

I can understand the need for publish profiles when doing local development but that should at least be configurable and not required for even building te project. Also, i dont see why its required to have a single partition for local development, i've debugged multiple partition services on a local cluster just fine.

**Comment by amanbha** [comment]
@aL3891 I understand what you are trying to do. Unfortunately we don't expose this form VS UI yet, I will log a work item to add a UI option in VS for disabling auto generation/modification of manifests for Actors when building the project. @MikkelHegn and @RaviPal  fyi.

**Comment by aL3891** [comment]
Sounds good, thanks!

Are there any plans to make the tooling/msbuild targets open source? i'd be happy to contribute

**Comment by amanbha** [comment]
Manifests for Actors are modified by a tool called FabActUtil.exe which is part of Microsoft.ServiceFarbic.Actors nuget package. Its open sourced at https://github.com/Azure/service-fabric-services-and-actors-dotnet/tree/develop/src. It is invoked by other VS tooling targets. I will let @MikkelHegn chime in for tooling/targets, if there is a plan to open source them.

**Comment by aL3891** [comment]
interesting, thanks! i'll check that out

**Comment by amanbha** [comment]
@aL3891 You can disable updating of manifests by FabActUtil for Actor project by setting the following property to false in Actors .csproj: UpdateServiceFabricManifestEnabled

**Comment by aL3891** [comment]
aha neat, thanks!
closing this one then :)

**Comment by ToyMakerGR** [comment]
@amanbha hint very much appreciated.
