### ISSUE TITLE
Upgrading guest container application fails MaxPercentUnhealthyDeployedApplications is set to 0

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Azure/service-fabric-issues#272]
I am trying to upgrade guest container application on azure SF cluster. The upgrade is basically to updated version of docker image. I ran following command to upgrade, but upgrade fails:
`Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/sample-app -ApplicationTypeVersion 1.0.6 -HealthCheckStableDurationSec 60 -UpgradeDomainTimeoutSec 1200 -UpgradeTimeout 3000   -FailureAction Rollback -Monitored -ApplicationParameter $cloudAppParams`
I can see errors this in explorer: `Error event: SourceId='System.Hosting', Property='CodePackageActivation:service-a.Code:EntryPoint'.
There was an error during CodePackage activation.`

However, there is nothing wrong with application itself, because when I create new application using new docker images, application works fine. Only during upgrade, this error happens.

Also, when I change -MaxPercentUnhealthyDeployedApplications parameter value to something like 50, then upgrade succeeds and new images is in use - even though the above errors are still appearing.

**Comment by RajeetN** [comment]
What version of ServiceFabric is this on?

**Comment by bishal-pdMSFT** [comment]
Current fabric version of cluster is 5.5.216.0

**Comment by mani-ramaswamy** [comment]
Can you please try this on the latest bits 5.6 since we made a lot of fixes there (and containers were in preview in 5.5)?

**Comment by mani-ramaswamy** [comment]
I am closing this issue since we've not heard back (our current version is 5.7 as of 08/18/17). Please re-open or open a new issue if you are still running into issues.
