### ISSUE TITLE
Send <ServiceInstanceName> as a header in reverse proxy

### ISSUE THREAD

**Issue by cwe1ss** [Azure/service-fabric-issues#273]
Please send the `<ServiceInstanceName>` part of the full reverse proxy URL as a header to the backend services. This would allow them to create absolute URLs etc. 

`http(s)://<Cluster FQDN | internal IP>:Port/<ServiceInstanceName>/<Suffix path>?PartitionKey=<key>&PartitionKind=<partitionkind>&ListenerName=<listenerName>&TargetReplicaSelector=<targetReplicaSelector>&Timeout=<timeout_in_seconds>`

@dazhao-msft already does this in his ASP.NET Core gateway project:
https://github.com/dazhao-msft/Hosting/blob/master/Microsoft.ServiceFabric.AspNetCore.Gateway/GatewayMiddleware.cs#L81

This still is the main reason for us why we can't use the integrated reverse proxy.

**Comment by vturecek** [comment]
The service instance name is always available to services (either through ServiceContext for C# services or an environment variable for guest EXEs) so I don't think this is strictly necessary. Is there a situation where you aren't able to get the service name?

**Comment by cwe1ss** [comment]
It's not really about getting the service name, it's about getting the URL path that was used by the proxy. I'd like to use the proxy as an optional thing - meaning services should talk without the proxy internally and the proxy will be used for stuff that's not in the cluster. This means, the service itself must know whether or not it was called from the proxy to generate correct absolut URLs. Sure, ideally services would always generate relative URLs but that's not always possible.

Normally, it would be the responsibility of the proxy to rewrite URLs in the response to match the proxies pattern (e.g. nginx's [ngx_http_sub_module](http://nginx.org/en/docs/http/ngx_http_sub_module.html)) but this probably is a big thing to ask. Forwarding the path to the service so that they can react to it would be an easy "workaround".

**Comment by dazhao-msft** [comment]
AspNet Core now has a URL rewrite middleware. I haven't tried it yet, but it looks like what you might be interested in: https://github.com/aspnet/BasicMiddleware/tree/dev/samples/RewriteSample

**Comment by mkosieradzki** [comment]
@cwe1ss 
You can use XFH header for this purpose. See #113 for discussion.

**Comment by masnider** [comment]
@cwe1ss - does @mkosieradzki 's or @dazhao-msft 's suggestions work for you? If it does we can close down this issue and move this discussion elsewhere. Please let us know if you're still having any issues here.

Thanks
-Matt

**Comment by cwe1ss** [comment]
Unfortuantely not:
* Rewriting of the response would have to happen in the proxy. The service can't use the rewrite module either because it doesn't know about the original path - which comes back to the original issue.
* The X-Forwarded-Host header only contains the host part (e.g. www.example.com) and not the full path. To create an absolute URL, I need X-Forwarded-Host, X-Forwarded-Proto and the relative URL of the proxy.

**Comment by cwe1ss** [comment]
Azure Application Gateway (or more specifically, the IIS URL rewriting module) offers something very similar - it sends a `X-Original-URL` header which contains the full path.

So if Application Gateway would be set up to forward everything on "/blog" to a certain site and if someone would request "/blog/home/about", it would send a request to "/home/about" on the underlying site and include the header `X-Original-URL: /blog/home/about`.

Here's some [very limited info](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#Preserving_Original_URL) about this.

I'd be fine with this as well if you want to preserve some kind of compatibility.

**Comment by Soarc** [comment]
I'm facing similar issue. I want to use service fabric reverse proxy with identityserver4.
I'm accessing my identity service like this
http://localhost:19081/myapp/IdentityService/.well-known/openid-configuration
But because identity service has no idea about proxy, it returns endpoint urls like this
http://localhost:5549/connect/authorize
I was able to fix host and port to correct ones using Microsoft.AspNetCore.HttpOverrides package,
but there is no way to fix pathbase.
If proxy add "X-Forwarded-PathBase" header, then i could use following code to fix this issue.

`
 if (ctx.Request.Headers.TryGetValue("X-Forwarded-PathBase", out StringValues pathBase))
 {
        ctx.Request.PathBase = new PathString(pathBase);
 }
`

**Comment by Mardoxx** [comment]
Contrived example, but I was playing around trying to access our front-end through reverse proxy and have a similar issue to @Soarc.

If serving, for example, an SPA via reverse proxy.. Something like `X-Forwarded-PathBase` would be useful. Then for each request to SPA-host it could write-out `<base href="{X-Forwarded-PathBase}" />`

As it stands, `https://localhost:19081/SPAApp/TenantName/` will serve up the following HTML in the response:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="/">
  </head>
  <body>
    <div>
      <div id="app"></div>
    </div>
    <script type="text/javascript" src="/dist/main.js"></script>
</html>
```

Naturally, this tries to serve `https://localhost:19081/dist/main.js`, which of course does not exist.
Instead, if we could inject the proper base path of `SPAApp/TenantName/` into the response it would work correctly i.e. serving up `https://localhost:19081/SPAApp/TenantName/dist/main.js`.

As I said, a rather contrived example and I am sure there is a better way to achieve this (please let me know, out of curiosity). But just thought I'd chime in!

**Comment by dnewsholme** [comment]
@Soarc  I've got the same issue with Identity Server 4. Did you ever manage to find a workaround?

**Comment by Soarc** [comment]
@dnewsholme Kind of... I wrote my custom reverse proxy service... And later moved to kubernetes at all :D

**Comment by mfmadsen** [comment]
@dnewsholme I believe we have a fix for this issue. I’m not at my machine currently but will get back to you tomorrow.

**Comment by mfmadsen** [comment]
@dnewsholme Sorry, I can see that we are now just using
```
.UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseReverseProxyIntegration)
```
when setting up the web host buileder. Previously we had our own middleware for this but this is no longer necessary. We are using the above setup with IdentityServer 4 as well and it works perfectly.

**Comment by masnider** [comment]
I'm going to close down this issue for now. @dnewsholme Please reopen if you are still having issues. I've seen people use other proxies/gateways such as AppGw, Traefik, and APIM, but I don't know that any of them pass along the original URI requested. It would also be good if you could clarify if you really needed the <ServiceName> or the original URI. The Service should always already know its name, and it looks like the other portions of the URI are obtainable. Worst case I believe you should be able to have the client add these as custom headers which the Reverse Proxy would preserve.
