### ISSUE TITLE
ServiceDnsName attribute doesn't work

### ISSUE THREAD

**Issue by SergiiKliebanov** [Azure/service-fabric-issues#278]
I've just updated SDK and packages in my project, also made a reset for local cluster - now I see DnsService running. 
My current environment setup is
- MSVS 15.2 (26430.6)
- Service Fabric SDK 2.6.204.9494
- Service Fabric 5.6.204.9494

Now I can't publish my app to the local cluster if I have `ServiceDnsName="myservice"` in the ApplicationMainfest. Build and Package run normally, but MSVS hangs on publish. Without this attribute everything works as before.

- Should I somehow change the version to the preview for the local cluster?
- How can I test DnsService on my local cluster?

**Comment by mani-ramaswamy** [comment]
Thanks for reporting this issue. We weren't able to reproduce this - are you able to copy and provision directly from powershell?

**Comment by mani-ramaswamy** [comment]
I am closing this issue since we haven't heard back.  Please feel free to reopen the issue with more information.
