### ISSUE TITLE
Manual to automatic upgrade configuration triggered new upgrade that fails

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#279]
One of our test clusters had automatic upgrade turned on, it had not upgraded from 5.5 to 5.6 yet, so I change it to manual and ran the 5.6 upgrade. Everything worked fine, and it was running for at least an hour or maybe more.

Then I went back into Azure Portal and configured the manual upgrade, to be automatic again. It then started the upgrade processes again, and now it's stuck in a loop where it takes node_0 down, up, down, up, down, up, with reboots.

Version is reported as 5.6.205.9494 on all nodes, also the one that keeps rebooting.

Is it attempting to upgrade from 5.6 to 5.6, and fails to report properly that is has been upgraded? I'm a bit worried that it even started the whole upgrade process again, after I changed from manual to automatic, when the cluster is already running on 5.6.

If this is an issue or bug with the upgrade process, others should be careful about doing something similar in a production cluster, as it will reports a lot of issues and it apparently is not able to fix itself.

Is there a way I can abort the upgrade in progress to get the cluster back in a stable state?

Earlier today I ran Windows Update on the same cluster, so there should be no Windows Updates that has not been installed.

**Comment by sondreb** [comment]
These logs are written in the Windows Event log on every reboot (sorted from latest on the top):

```
INFO: Fabric Process id: -1

WARN: ERROR: Microsoft.Azure.ServiceFabric.Extension.Core.AgentException: Fabric host service is not running
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.StartFabricHostService(Boolean isBootstrapping)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunOnce>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunAsync>d__0.MoveNext()

ERROR: Failed starting service, Error: Microsoft.Azure.ServiceFabric.Extension.Core.AgentException: Fabric host service is not running
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.StartFabricHostService(Boolean isBootstrapping)

WARN: FabricHostSvc status is Stopped; will restart after 2017-05-16T15:08:06.7223947Z if it is still not running

INFO Service Fabric node is configured
```

Screenshot:

![image](https://cloud.githubusercontent.com/assets/309938/26113189/2cdb89f0-3a5a-11e7-886b-884d17694acc.png)

**Comment by sondreb** [comment]
Another entry in Windows Events:

```
The description for Event ID 1042 from source MsiInstaller cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

D:\SvcFab\_BackEnd_0\Fabric\work\FabricUpgrade\WindowsFabric.5.5.216.0.msi
3692
(NULL)
(NULL)
(NULL)
(NULL)

The handle is invalid
```

**Comment by sondreb** [comment]
I was able to edit and save the upgrade configuration right now, I changed from automatic to manual, but in the dropdown of available options there are now both 5.6.204 and 5.6.205, is the 205 a new hotfix that arrived today? I don't remember seeing 205 this morning, but now on this cluster both options was available.

![image](https://cloud.githubusercontent.com/assets/309938/26113672/790b4fa8-3a5b-11e7-878c-558293b5832d.png)

**Comment by sondreb** [comment]
Right before I discovered I was able to modify the upgrade configurations, I removed all deployed applications to ensure less load and faster restarts.

Appears now that after I changed from automatic and back to manual, it stabilized itself. Not been a reboot in a short while, still says "Updating" in Azure Portal but I think it should be fine now, I'll report back again if there continue to be a problem.

Reports a lot of "Fabric host service is running" in Windows Events, appears all good again.

**Comment by mikanyg** [comment]
I had the same issue for our test cluster. Wanted to workaround the deployment issues with SDK 5.6 targeting cluster 5.5, so also changed from automatic upgrade to manual and selected 5.6. After a successfull upgrade I changed it back to automatic update again, and Node 0 got stuck going from Up to Down in a loop.

My solution was to rdp into the node an reboot it. Once it started it repaired itself and went back to working fine again.

**Comment by sondreb** [comment]
Had some similar issues now with another cluster (5.5.216 to 5.6.210.9494), the second node was never able to get back up again. Eventually after 4 hours, it triggered a rollback. 1 node upgraded and started fine, but the first node on the second node type kept attempting for 3+ hours and reverted in the end.

![image](https://cloud.githubusercontent.com/assets/309938/26604726/8a6b4dee-458b-11e7-8332-07c6ed5c7fe0.png)

**Comment by vaishnavk** [comment]
@sondreb - 2 weeks back, 5.5 was the target version for all automatic clusters. Hence switching to automatic mode after upgrading to 5.6 would have caused your cluster to downgrade to 5.5. The earlier issue you reported is already a known issue in 5.6 to 5.5 downgrade path and has already been fixed. 5.6 is now the target version for all automatic clusters.

 For the cluster which failed upgrade from 5.5.216 to 5.6.210.9494 today - what is the resource id and region of this cluster?

**Comment by ChackDan** [comment]
Closed for the lack of response from the customer. we need the resource ID and region to debug further.
