### ISSUE TITLE
Documentation on Get-ServiceFabricApplicationUpgrade isn't clear

### ISSUE THREAD

**Issue by CassandraDied** [Azure/service-fabric-issues#280]
Hello.

I did perform an upgrade and it failed. So, I executed Get-ServiceFabricApplicationUpgrade on the cluster and got next result:

> ApplicationName               : fabric:/App
ApplicationTypeName           : AppType
TargetApplicationTypeVersion  : 1.22.63
ApplicationParameters         : { "Accounts_InstanceCount" = "-1";
                                "Birthdays_InstanceCount" = "1";                                }
StartTimestampUtc             : 16.05.2017 14:49:35
FailureTimestampUtc           : 16.05.2017 15:06:36
FailureReason                 : UpgradeDomainTimeout
UpgradeState                  : RollingBackCompleted
UpgradeDuration               : 00:23:05
CurrentUpgradeDomainDuration  : 00:00:00
NextUpgradeDomain             :
UpgradeDomainsStatus          : { "2" = "Completed";
                                "0" = "Completed";
                                "3" = "Completed";
                                "4" = "Completed";
                                "1" = "Completed" }
UpgradeKind                   : Rolling
RollingUpgradeMode            : UnmonitoredAuto
ForceRestart                  : False
UpgradeReplicaSetCheckTimeout : 00:20:00

According to [this](https://github.com/Microsoft/azure-docs/blob/master/articles/service-fabric/service-fabric-application-upgrade-troubleshooting.md) article, in case if FailureReason is **UpgradeDomainTimeout**, I should be able to see _UpgradeDomainProgressAtFailure_ and some related information to investigate the issue.

But in my output for the command, there is no such information. So, is it some bug in the command or documentation is missing mentioning that mentioned information can be omitted?

I would like to investigate the reason of the upgrade failure, but I don't know how can I do this.

**Comment by alexwun** [comment]
UpgradeDomainProgressAtFailure might be empty in the rare case when the upgrade wasn't actually able to start doing any work, so there was no progress at all. Do you remember if it failed on the first UD? Are all the system services healthy in the cluster?

Also, just noticing that Birthdays_InstanceCount is set to "1". Assuming that's a stateless service instance count, is that intentional or did you mean to set that to "-1"?

**Comment by CassandraDied** [comment]
>  Do you remember if it failed on the first UD?

Last one or 4th.
>  is that intentional or did you mean to set that to "-1"?

Intentional.

By the, list of services is truncated to remove unnecessary information. There are like 25 services overall.

>Are all the system services healthy in the cluster?

No, one service wasn't healthy. Upgrade Service had some issues. An exception has been thrown, but I didn't save the info, so cannot provide any information on that. After the next successful attempt, all system services became healthy.

**Comment by alexwun** [comment]
Okay, so the upgrade service is now healthy and you retried the upgrade successfully?

**Comment by CassandraDied** [comment]
Yes. It wasn't healthy after the first upgrade rolled back. But it became healthy after the second and successful upgrade.

**Comment by alexwun** [comment]
Documentation has been updated
