### ISSUE TITLE
Reverse proxy safe for use as an edge proxy?

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#281]
Is the built in reverse proxy safe for use as an edge proxy that is routed to by Azure Load Balancer?

**Comment by vturecek** [comment]
I don't recommend it because it will expose all of your services that have HTTP endpoints to the Internet. There is currently no way to control which services are exposed through the reverse proxy.

**Comment by Mardoxx** [comment]
I have designed my services so the only ones that use HTTP endpoints are WebAPI services which want to be exposed to the public - everything else uses service remoting. 

I'm asking since it is not recommended to use Kestrel for front facing, and instead use behind IIS or use Weblistener, wondering if there are any recommendations against using the reverse proxy!

**Comment by vturecek** [comment]
In that case, you should be OK. The reverse proxy is built on the same Windows HTTP Server API (http.sys) that WebListener users which provides the DoS protection that is currently missing from Kestrel.

**Comment by Mardoxx** [comment]
Brilliant, thank you 😄
