### ISSUE TITLE
Current sfproj projects are not manageable cross team due to relation to SDK versioning.

### ISSUE THREAD

**Issue by bklooste** [Azure/service-fabric-issues#286]
The current structure and how it relates to the tooling and nuget package is very painful when you have many teams.. One team may be using a VM with 1.5 other teams are using 1.4 ,meanwhile CI may be a different version   If one person follows the prompt and upgrades and checks it in  all other devs cant open it .  We have had mixed reports of 1.5 opening 1.4  after talking to 2  , one person seems to have it working the other seems to get into a weird Nuget restore loop . 

Is 1.5 SDK able to support opening 1.4 ?  Or are we back to VS2003 days ..

**Comment by dbreshears** [comment]
Thanks for the feedback.  This experience should be better going forward, we have been working on  round tripping between tooling versions, so as long as you are not taking advantage of specific 2.6 SDK features you should be able to open projects and F5 in both 1.6 or 1.5 tooling.
