### ISSUE TITLE
Reverse Proxy connecting to HTTPS services returns 404

### ISSUE THREAD

**Issue by alecor191** [Azure/service-fabric-issues#289]
### Scenario
- I have a Reverse Proxy talking to services that are hosted using HTTPS. 
- I followed the instructions in [Connect to a secure service with the reverse proxy](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication#secure-connection-establishment-between-the-reverse-proxy-and-services). I left the default settings for the Reverse Proxy (i.e. certificate validation option for RP should be `None`).
- RP is also configured to use HTTPS
- Connect to a service through the RP: `https://<cluster>:<rp_port>/MyApp/MyService/`

### Expected outcome
Response with `200` status code returned.

### Actual outcome
Response with `404` status code returned.

### Additional information
- Connecting to the service directly (`https://<cluster>:<service_port>/`) succeeds
- Configuring the service to listen to HTTP instead of HTTPS traffic: the request above (`https://<cluster>:<rp_port>/MyApp/MyService/`) works fine.
- The above can be reproduced both on Azure cluster (both RP & services on HTTPS) as well as local dev cluster (RP is listening on HTTP, only services on HTTPS)

Any suggestions what the issue could be or how to further debug this?

**Comment by kavyako** [comment]
Could you share some info
1. What is the Service Fabric version?
2. Is the service exposing multiple endpoints? 
3. Are you passing any other query parameters in the request? like ListenerName?

Regarding your dev cluster setup, RP is listening on HTTP and services on HTTPS is not a supported scenario. Since this way, any clients will be able to obtain info from the service over an unencrypted channel. Could you try with a secure reverse proxy.

**Comment by alecor191** [comment]
Thanks a lot @kavyako for the fast response and the hint about my invalid local cluster scenario.
- I re-created the local cluster as secure one (using the `-AsSecureCluster` flag when calling the SDK's `DevClusterSetup.ps1`). After performing this change, the scenario described above **works**!
- I did some more troubleshooting on my Azure SF cluster (5.6.205.9494) and found the issue there as well (config issue on my end). RP on Azure SF is now **working** as well.

### ApplicationManifest.xml & certificate configs
I have one more question though: My services are ASP.NET Core services using Kestrel. Kestrel is configured to use HTTPS. Required certificates are installed on the VMSS nodes during ARM deployment.
What I noticed is that the scenario above works just fine even if I do **not** provide certificate information in `ApplicationManifest.xml` (like `EndpointBindingPolicy`, `EndpointCertificate`).

So my questions:
- Could you please describe the purpose of those settings in AppManifest? 
- Do they apply when using Kestrel? (my understanding is that if I would use an http.sys based listener, then SF would take care of performing port reservation & cert registration - i.e. what I would do through `netsh http ...`)

**Comment by kavyako** [comment]
EndpointBindingPolicy, EndpointCertificate settings are required for Http.sys based listeners (like WebListener), to perform port reservation, cert registration. 
If you are using Kestrel, you don't need to specify these settings in the ApplicationManifest.xml.

**Comment by alecor191** [comment]
Thanks for confirming!
