### ISSUE TITLE
Patch Orchestration Application not working

### ISSUE THREAD

**Issue by andriktr** [Azure/service-fabric-issues#290]
Just deployed Patch Orchestration Application to my test service fabric cluster. Unfortunately right after deployment application is in error status.

![app_error](https://cloud.githubusercontent.com/assets/25537180/26389486/d1e29278-4062-11e7-8e1d-9942f9749d68.PNG)

![image](https://cloud.githubusercontent.com/assets/25537180/26395167/ee029858-4077-11e7-873e-de417ccc3223.png)

**Comment by novino** [comment]
Hey Andrej,

Could you provide me the following (over mail)
1. [Service fabric logs ](https://support.microsoft.com/en-us/help/3200697/microsoft-azure-service-fabric-logs)from the cluster
  - If it’s an azure cluster ? region, subscription ID and cluster ID for your cluster should suffice.
  - If it’s a standalone cluster, you can provide me the logs around the problematic time period (~30 mins interval)
2. I would be needing the Patch Orchestration Application logs from your node (VM/machine), where coordinator service is failing to come up. 
The path for application logs is [Service Fabric_Installation_Drive]:\PatchOrchestrationApplication\logs
Ex: If Service Fabric was installed on “C” drive, the path would be `C:\PatchOrchestrationApplication\logs`

Warm Regards,
Naveen

**Comment by andriktr** [comment]
Hello Naveen,
1.This is an azure cluster:
      Region: West Europe
      Subscription ID: dc4a14f8-5528-48f4-ac4e-a68ac324a1fa
      Cluster ID: 5ef9b027-415a-420e-8d94-fba165e6d9d4
2. I attaching .zip file with logs from all 5 nodes. In case you will not
receive attachment let me know and I will find another way to share logs
with you.
Thank you for help.

BR,
Andrej.

2017-05-24 12:18 GMT+03:00 Naveen Chandrakar <notifications@github.com>:

**Comment by novino** [comment]
Hey Andrej,

Traced the issue to incorrect value provided for CoordinatorService's setting, could you double check the values you've provided for MaxResultsToCache which should be long. Eg: 3000 is a valid value.

For more details refer to the [documentation ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application
)

**Comment by andriktr** [comment]
Hi Naveen,
I will try to redeploy application with correct params  and will let you
know about results.
Thank you.

2017-05-24 14:31 GMT+03:00 Naveen Chandrakar <notifications@github.com>:

**Comment by andriktr** [comment]
Looks that it's OK now. 
It little bit unclear for me how to view results because I can't access Patch Orchestration Application via endpoint
![image](https://cloud.githubusercontent.com/assets/25537180/26402476/3932849e-4093-11e7-854f-243a6c54f57c.png).

I'm trying to access http://10.0.0.4:20014/PatchOrchestrationApplication/v1/GetWindowsUpdateResults , but this link provides me to download GetWindowsUpdateResults.json file which is empty, should it be so?

Maybe you can provide some examples how results should look.
Thank you.

**Comment by novino** [comment]
You're able to reach the Patch Orchestration Application endpoint correctly, since you're getting the prompt to download the results. The result is empty because the first update hasn't happened yet.

Based on the WUFrequency frequency you've set it'll start the first update when that frequency is hit. (Eg: Default is weekly on Wednesday 7am, so if you've deployed it about an hour back, it'll do the first update on 31st May 7am UTC)
For your test cluster you can try setting WuFrequency as Daily (and if you want immediate result, set a UTC time which is about 30 mins from time when you're deploying the app).

I've attached a result file for reference
[GetWindowsUpdateResults.json.txt](https://github.com/Azure/service-fabric-issues/files/1025462/GetWindowsUpdateResults.json.txt)

**Comment by andriktr** [comment]
It's fully clear now. 
Thank you for help.

**Comment by laughtonsm** [comment]
Hi.  I am having the same issue as andriktr.  However, I have already set frequency to daily.  When I access the results API, I too still get a blank file - even after leaving this for a week.   Any ideas as to what might be causing this?

Cheers

Shaun

**Comment by novino** [comment]
@laughtonsm, can you open a separate GitHub issue for better tracking. 
Do provide more details viz. Azure cluster or standalone, how many updates you can see on the machine VM which are pending installation, logs for your cluster etc..
