### ISSUE TITLE
Secure Local Dev Cluster: generated certificate not accepted for HTTPS

### ISSUE THREAD

**Issue by alecor191** [Azure/service-fabric-issues#292]
I set up a local secure dev cluster using 

```
.\DevClusterSetup.ps1 -PathToClusterDataRoot "c:\SfDevCluster\Data" -PathToClusterLogRoot "c:\SfDevCluster\Log" -AsSecureCluster -CreateOneNodeCluster
```

All is fine and cluster works. I also see that the cert `ServiceFabricDevClusterCert` gets installed to *Trusted Root Authority*.

The one issue I have is that the certificate generated by the script and assigned to Reverse Proxy for performing HTTPS encryption, is not accepted by the browser/other services when sending a request to the RP:

```
https://localhost:19081/MyApp/MyService/
```

The reason is that validation fails with "certificate name mismatch". This is due to the hostname `localhost` not being listed as a Subject Alternative Name in the certificate provided by RP.

While I could intercept certificate validation in my services and ignore the above failing validation, I'm wondering if there is a better way to deal with this?
I couldn't find a way to setup a local cluster providing my custom certificate (where I could add `localhost` as subject alternative name).

I'm using ASF SDK from latest VS2017 installer.

**Comment by kavyako** [comment]
In the local dev cluster, you can have the reverse proxy use a different certificate.

1.Go to the clustermanifest.xml (usually located under C:\SfDevCluster\Data) and update the GatewayX509CertificateFindValue in ApplicationGateway/Http configuration to point to the subject name of the new certificate:

    <Section Name="ApplicationGateway/Http">
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="GatewayAuthCredentialType" Value="X509" />
      <Parameter Name="GatewayX509CertificateFindValue" Value="ServiceFabricDevClusterCert" />
      <Parameter Name="GatewayX509CertificateFindType" Value="FindBySubjectName" />
    </Section>

2.Restart the cluster.

Please ensure the certificate is installed correctly on the machine.

**Comment by alecor191** [comment]
Thanks @kavyako for the pointer. I tried the steps, but unfortunately it didn't work:
- stop local dev cluster using SF Local Cluster Manager (I used the menu item "Stop Local Cluster")
- update `C:\SfDevCluster\Data\clustermanifest.xml` as described
- start local dev cluster using SF Local Cluster Manager (I used the menu item "Start Local Cluster")

RP continued to use the auto-generated SF certificate (ServiceFabricDevClusterCert). Also looking at the "Manifest" tab in SF Explorer showed the old cert config.

What I did next was to update all other .xml manifest files I could find in the local dev cluster directory:
- C:\SfDevCluster\Data\_Node_0\Fabric\ClusterManifest.1.0.xml
- C:\SfDevCluster\Data\_Node_0\Fabric\ClusterManifest.current.xml
- C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Config.1.0.0\Settings.xml

After updating them as well and restarting the cluster, it worked. 

Did I do something wrong in my initial steps? Or is it really required to update also the other .xml files mentioned above?

**Comment by kavyako** [comment]
You are right, clustermanifests for every node need to be updated.
Another option is, the cluster manifest template files are under: C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\Secure\OneNode, or FiveNode folder. 
You could  update the GatewayX509CertificateFindValue in the template instead and recreate the cluster.
Do take a backup before modifying the original templates.

**Comment by alecor191** [comment]
Thanks @kavyako for elaborating!
