### ISSUE TITLE
Service Upgrade on Standalone cluster causes several GB worth of temp files

### ISSUE THREAD

**Issue by cferraguti** [Azure/service-fabric-issues#293]
We are running a standalone Service Fabric Cluster with version 5.5.216.0.  The service monitored upgrades seem to cause a lot of TMP files to be created in the C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp folder that all appear to be related to Event Logs.  We end up getting at least 5-6 GB a day worth of these files and they are never automatically cleaned up.  This only appears to happen on our development cluster.  I've yet to see these files generated on our System Test cluster.  Both clusters are running the same SF version and have the same Services installed.  I can provide sample temp files through email if you would like.

**Comment by maburlik** [comment]
Please send details to sfsa@microsoft.com. 

Please provide answers to:
- What are the files called, and are these generated consistently? 
- Are you running any operational commands against the cluster? 
- How many applications are running?
- What was the original version with which the cluster was deployed?

Please provide:
- Some of the generated files via OneDrive or your choice of storage
- Cluster configuration with secrets removed
- Cluster manifest

Take a look at Resource Monitor disk activity and see if you can find which process is writing these files, and if you can narrow this down, please create a dump file of the process through task manager.

Thanks,
Max

**Comment by cferraguti** [comment]
I tried responding to that email address a few times from different email addresses and keep getting the following error.

550 5.7.133 RESOLVER.RST.SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group

Would you please add my email to the approved senders list?

**Comment by rishirsinha** [comment]
Please send to rsinha@microsoft.com and I will handle adding the right group.

**Comment by rishirsinha** [comment]
First of all apologies for the extremely delayed response. We looked at the files and these seem to be coming from some other component that is generating these files based on the changes of firewall rules when application upgrade is happening. Can you check to see if there is some component on the server machines which is doing the same?

**Comment by rishirsinha** [comment]
@cferraguti. Please update.

**Comment by cferraguti** [comment]
We believe this was actually being caused by NewRelic that was incorrectly configured on the servers that belonged to the cluster.  Thank you for looking into the logs.
