### ISSUE TITLE
Each time when you deploy application you have new copy of windows firewall rule for it's endpoint

### ISSUE THREAD

**Issue by lAnubisl** [Azure/service-fabric-issues#296]
I have noticed this on Azure when I RDP on one node and opened firewall rules:
Looks like when you re-deploy your application new rule is created. Old one remains undeleted:
![multiple firewall rules on single application](https://cloud.githubusercontent.com/assets/1249671/26559267/5230115a-44b7-11e7-9b92-9bf80039fa1b.png)

I'm not sure if this is an issue but definetly looks incorrect

**Comment by sondreb** [comment]
Reported same issue on #205.

**Comment by vturecek** [comment]
Hey @lAnubisl , I'm going to close this out since we're already tracking it in #205.
