### ISSUE TITLE
FabricException constructor not found

### ISSUE THREAD

**Issue by Wjvb** [Azure/service-fabric-issues#297]
While making a method call to another service using service remoting, a MissingMethodException occured. `"Method not found: Void System.Fabric.FabricException..ctor (System.String, System.Exception, Int32)."` After some testing I noticed that any call to `new FabricException(string, Exception, int)` throws a `MissingMethodException`. The NuGet package version used is 5.6.210. After switching to version 5.5.216 I noticed that the constructor doesn't exist in that version, because it uses a struct instead of an integer as third parameter. With version 5.5.216 the remoting call correctly throws a Fabric Exception.

Reproduction:

1. Create a service fabric application with a stateless service.
2. Make sure Service Fabric NuGet package 5.6.204 or 5.6.210 is installed on the service.
3. In the RunAsync method of the service add a try catch block (catch `Exception`) and throw the following exception inside the try scope:
`throw new FabricException("", new Exception(), 0);`

4. Debug the application.
5. A `FatalExecutionEngineError` occurs because a `System.MissingMethodException` was uncaught.

**Comment by Mardoxx** [comment]
Make sure caller and callee are using same assembly version of service fabric

**Comment by Wjvb** [comment]
They are using the same assembly version. Besides that, the reproduction steps don't use service remoting at all.

**Comment by sondreb** [comment]
Could anyone confirm if this is an issue with the SDKs, or if this might happen due to using newer 5.6 SDK on older clusters, like 5.5? Had same problem with 2.6/5.6 upgraded project deployed to 5.5, did not succeed. Never saw same problem on another cluster that was upgraded before upgrading the SDK.

**Comment by sondreb** [comment]
Is it possible that the problem is related to upgrades, where old services have 5.5 SDK and new services have 5.6 SDK, and these perform calls to each-other during an upgrade?

**Comment by Wjvb** [comment]
The issue also occurs when deploying an application to an empty cluster, so it's not exclusive to upgrading.

**Comment by amanbha** [comment]
@sondreb Your cluster runtime version must atleast be 5.6 for deploying applciations built with 5.6/2.6 SDK.

**Comment by sondreb** [comment]
@amanbha: Thanks, I have a suggestion that you perhaps edit the MSDN documentation and explains this a bit clearly to developers, to avoid serious problems.

And unfortunately not able to upgrade to 5.6, having similar issues as I had earlier on another cluster: #279, only that this time it's stuck on the second VM which is unable to start and connect properly to the cluster again...

**Comment by njtrentacoste** [comment]
@amanbha  Please confirm that the cluster runtime must match the application's runtime.  Per issue #267 this is not a requirement.  I am getting this error as well with a standalone cluster running 5.5 with applications referencing 5.6 packages.  For me, a restart of the api code solves the issue, albeit only temporarily.

**Comment by amanbha** [comment]
Please see info about supported sdk and runtie version at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#supported-service-fabric-versions
 #267 is about runtime ps cmdlet compatibility which should always be backward compatible.

**Comment by njtrentacoste** [comment]
@amanbha Thanks for clarifying that and for the link to the reference material.

**Comment by masnider** [comment]
@njtrentacoste does the information describe your situation? It seems like the SDK you are using is probably ahead of what was running in the cluster. While you're correct that the SDK and the cluster don't have to match, the cluster runtime must be equal to or ahead of the SDK version that the applications and services in the cluster are targeted to.

**Comment by njtrentacoste** [comment]
@masnider The information does describe my situation.  I must've misunderstood what I was told in the other bug.  Thankfully, MS released the updated standalone runtime, so all I had to do was upgrade my cluster and the FabricException went away.  Thanks for following up!

**Comment by masnider** [comment]
No problem! Glad you're back up and running.
