### ISSUE TITLE
Using different AccountTypes per environment

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#299]
Hey guys,

how is it possible to user different AccountTypes per environment (Application Parameters)?

I use
```
 <User Name="ServiceUser" AccountType="DomainUser" AccountName="[AccountName]" Password="[Password]" />
```

So I can exchange my AccoutName and Password, but we have INT and QS where we have a Windows Domain and LIVE where we don't have one so I want to run the service under NETWORK SERVICE but this is not possible with "DomainUser". It's also not possible to use a variable there as its an enum...

**Comment by VipulM-MSFT** [comment]
Yes this is not possible today. You can however add two different user names and override the UserRef attribute in the RunAs policy through application parameter.

**Comment by senj** [comment]
Good idea thank you
