### ISSUE TITLE
Environment Variables in Cloud Service Fabric

### ISSUE THREAD

**Issue by shlatchz** [Azure/service-fabric-issues#3]
How can I define an environment variable in the service fabric's cloud deployment?
Can it be done from the portal?

**Comment by ChackDan** [comment]
From the portal - you can specify values to  parameters and variables  that service fabric RP has whitelisted. So the answer would be no. 
If your intent is to add a specific Env variable to each of the VM instances in the VMSS that make up your cluster, then you need to specify that in an ARM template. One way to do that would be to use a "custom Script" VM extension that you define in the VMSS resource.

**Comment by gbowerman** [comment]
Another option would be in the VMSS customData property.

**Comment by shlatchz** [comment]
How do I change the VMSS customData?
