### ISSUE TITLE
Open source service fabric

### ISSUE THREAD

**Issue by blrchen** [Azure/service-fabric-issues#30]
All in title

**Comment by CassandraDied** [comment]
@blrchen we already have this question opened on [feedback Azure forum](https://feedback.azure.com/forums/293901-service-fabric/suggestions/10837218-open-source-service-fabric).

**Comment by vturecek** [comment]
It's currently in progress for parts of Service Fabric. Service Fabric has been internal to Microsoft for a long time, and it's a substantial code base so it's a pretty big effort moving it out. But we're dedicated to the cause, so stay tuned!

**Comment by vturecek** [comment]
Parts of the SDK were open sourced with the 2.5 release. Links to all the SF repos can be found at our new home: https://github.com/Azure/service-fabric

Closing this out for now..
