### ISSUE TITLE
will vs17/dev15 azure workload eventually include required service fabric sdk as well

### ISSUE THREAD

**Issue by myusrn** [Azure/service-fabric-issues#300]
i'm finding that even with the latest vs17/dev15.2 [ 15.0.26430.12 ] update that the azure workload while it includes service fabric tools extension it does not include the web platform installer provided azure service fabric sdk - 2.7 preview [ | 2.6.210 | 2.5.216 ] component necessary to create/build c# | azure | service fabric project templates. 

q1 - will vs17/dev15 azure workload installation eventually include that required service fabric sdk component as well?

q2 - is there a web platform installer or other story for removing the older  azure service fabric sdk - 2.6.210 and 2.5.216  components from my system so i'm able to confirm things work with just the latest webpi applied sdk 2.7 preview in place?

**Comment by MikkelHegn** [comment]
Q1: YES!!! - The great master plan has been put in place - and we are executing to fix this.

Q2: Use Add/Remove Programs (you will have to remove the individual msi packages there)

**Comment by dbreshears** [comment]
A final note on this.     We decided against including  the SF runtime/SDK in the VS installer to allow for the tools and the platform to release independently.
