### ISSUE TITLE
vs2017 package don't move packagereference package to pkg code directory

### ISSUE THREAD

**Issue by zxarcg** [Azure/service-fabric-issues#302]
vs 2017, service fabric 2.6.210  project framework: 4.6.2

i created a stateful template project , default package format is packages.config,  and i changed to packagereference. then i deleted packages.config,  i setup a new nuget package, Open this project by notepad,  i can see: 
<ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.EventFlow">
      <Version>1.1.0</Version>
    </PackageReference>
</ItemGroup>
but after i package sf app , i can't find this package dll . 
if i switch to old packages.config, after i package ,i can find this.
please tell me what should i do ?  must i use old packages.config style?

**Comment by zxarcg** [comment]
btw: sf template project default is msbuild 14.0 as followed:
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

i changed to 15.0 , but it have no effect.

**Comment by MikkelHegn** [comment]
@ravipal

**Comment by ravipal** [comment]
The packaging logic isn't handling the packages that are added using PackageReference. Will address this in the upcoming release.

**Comment by pharring** [comment]
I ran into the same thing. I came up with this workaround that I put in my .sfproj just before the `<Import Project=$(MSBuildToolsPath)\Microsoft.Common.targets" />` line:

```xml
  <!-- 
    Microsoft.VisualStudio.Azure.Fabric.Application.targets includes targets to package the services.
    Unfortunately, it's missing the piece to package "CopyLocal" assemblies that come from NuGet
    packages that are included via PackageReference and not explicitly referenced in the project file.
    This target plugs that gap.
  -->
  <Target Name="AdditionalServiceCodeFiles"
          BeforeTargets="CollectServiceCodeFiles"
          Condition="'@(ServiceProjectReferencesWithCodePackage)' != ''">
    <PropertyGroup>
      <_ServiceProject>%(ServiceProjectReferencesWithCodePackage.Identity)</_ServiceProject>
      <_ServiceManifestName>%(ServiceProjectReferencesWithCodePackage.ServiceManifestName)</_ServiceManifestName>
      <_CodePackageName>%(ServiceProjectReferencesWithCodePackage.CodePackageName)</_CodePackageName>
    </PropertyGroup>

    <!-- Include ReferenceCopyLocalPaths -->
    <MSBuild
      Projects="$(_ServiceProject)"
      Targets="ResolveAssemblyReferences"
      Properties="$(ReferencedProjectCommonBuildProperties)"
      ContinueOnError="false">
      <Output TaskParameter="TargetOutputs" ItemName="ReferenceCopyLocalPaths" />
    </MSBuild>
    <ItemGroup>
      <_ServiceFiles Include="@(ReferenceCopyLocalPaths)">
        <TargetPath>%(ReferenceCopyLocalPaths.DestinationSubDirectory)%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</TargetPath>
      </_ServiceFiles>
    </ItemGroup>
  </Target>

**Comment by jamesmus** [comment]
@pharring Thanks a lot for the workaround.  It's helped me get around this issue without having to revert to packages.config.

**Comment by AsValeO** [comment]
@pharring, thank you but unfortunately, this workaround not helped in my case.
v2.7.198/5.7.198
net4.7
Please add PackageReference support.

**Comment by ravipal** [comment]
@AsValeO, Starting from 1.7 tooling, PackageReference is supported on SDK style projects (<project Sdk="Microsoft.NET.Sdk">). For other projects the PackageReference will be supported in the next release with some limitations. My suggestion would be to convert your project to SDK style project, if you would like to use ProjectReference.

**Comment by profabe** [comment]
@ravipal We also ran into the same problem with *.sfproj being based on package.config, while ASP .NET Core 2.0 is based on PackageReference. Is there any release scheduled yet to add ProjectReference support to *.sfproj? Many thanks in advance!

**Comment by ravipal** [comment]
@profabe Do you see any issue while packaging or you are asking to convert the *.sfproj to use the PackageReference?

**Comment by profabe** [comment]
@ravipal Many thanks for the quick reply! Basically we have an issue: When building the Service Fabric Application in Visual Studio, it does not copy the packages defined in the ASP .NET Core 2.0 project, which is based on PackageReference. Is this issue known? Any plans to align *.sfproj to *.csproj to both use PackageReference?

**Comment by ravipal** [comment]
@profabe It should work. What is the Service Fabric Tools version? Can you please share your *.sfproj file and *.csproj file?

**Comment by profabe** [comment]
@ravipal We solved the issue, basically it was our fault. The DLLs of the 3rd party NuGet package were copied, but the SQL scripts it generated not. We added a PostBuild step to copy the SQL scripts into the bin directory of the Startup project and it worked. Sorry for any inconveniences.

**Comment by MikkelHegn** [comment]
Closing
