### ISSUE TITLE
Publish failure after upgrade to VS 2017 from .Net Core xproj structure

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#303]
Attempting to upgrade from VS 2015 where all projects are in .Net Core xproj structure... overcame various issues and now the solution and all projects compile, however publishing to cluster fails with numerous packaging errors such as the following:

_C:\MyProject\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets(248,5): 
warning MSB3026: Could not copy "C:\MyProject\src\Acme\Acme.Service\bin\x64\Debug\net46\win7-x64\Acme.Service.runtimeconfig.json" to "C:\MyProject\pkg\Debug\Acme.ServicePkg\Code\". Beginning retry 1 in 1000ms. Could not find a part of the path  'C:\MyProject\pkg\Debug\Acme.ServicePkg\Code\'._

**Comment by MedAnd** [comment]
Made some progress by setting the following:

<RuntimeIdentifier>win7-x64</RuntimeIdentifier>
<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>

**Comment by MedAnd** [comment]
Update on this issue, testing a workaround...

**Comment by MikkelHegn** [comment]
@ravipal

**Comment by ravipal** [comment]
@MedAnd, Is it possible to share the solution/similar one with me (ravipal@microsoft.com)?

**Comment by MedAnd** [comment]
@ravipal please see: https://goo.gl/ymHK7R

**Comment by ravipal** [comment]
Based on the article that you linked, it seems like you are trying to user dotnet core actor service project and results into this publish error. Is that right?
Please note that dotnet core actor/stateless/stateful services are not yet supported and we are working on this.

**Comment by MedAnd** [comment]
Will close this issue @ravipal as the workaround is working like a treat… good to know support for this scenario is coming in a future SDK and tooling update.
