### ISSUE TITLE
Certificate update with port sharing web API's

### ISSUE THREAD

**Issue by SainiAshish** [Azure/service-fabric-issues#305]
We have multiple web API's  sharing the same port for example: 8517. We have secured the ssl endpoint with same certificate we used for securing the cluster. Now the issue is when we are trying to update the certificates with new certificate for the web api endpoints it is failed during the update. because that port is already binded with the previous certificate for other services.
In this scenario how to update the certificate for all the web api services.

**Comment by suchiagicha** [comment]
@SainiAshish 

Are all services using same port are of same application?
Are you doing the cluster upgrade or the app upgrade?

**Comment by SainiAshish** [comment]
@suchiagicha 
No, Services are in different applications.
We were doing the app upgrade.

**Comment by amanbha** [comment]
@SainiAshish  So does following describes your scenario:
App1 configures C1
App2 configures C1

Now you decide to use C2 for both
You start App1 upgrade.
You start App2 upgrade.

**Comment by SainiAshish** [comment]
@amanbha 

In App1 during upgrade one of the replica of the web API failed. We didn't see any error except failed to initialize the replica. 
We were using the 5 node cluster and during upgrade as web api upgrade starts one of its replica failed because the rest of the replica's of the same web api are using the same port and certificate.
After that web API service remain in the same state with one replica failed.

Later on we find it is not because of port sharing even if you try to rollover a certificate for web API  which is not sharing port with any of the other web api same thing happens.

The only solution is just delete the web api service and do a fresh upgrade.

**Comment by amanbha** [comment]
@SainiAshish Just 1 replica failed, and it came fine on other nodes?
Just trying to understand it better, Could you explain this in more detail: "Later on we find it is not because of port sharing even if you try to rollover a certificate for web API which is not sharing port with any of the other web api same thing happens."
What is the webserver? Assuming its using http.sys, how the cert was specified in the app manifest? Under what user does the service runs? And to clarify the cert rollover: you installed the new cert on the machine first (still keeping the old one on the machine) and then started the app upgrade with new cert specified in the app manifest.

**Comment by SainiAshish** [comment]
@amanbha 
After 1 replica failed,  upgrade stops there as upgrade is incremental one by one on replicas.
The instance count for Web API should be -1 which means its replica will be only all the nodes of the cluster.
In ServiceManifest
<Endpoints> 
<Endpoint Name="HttpsServiceEndpoint" Port="8527" Type="Input" Protocol="https"/>
</Endpoints> 
In App Manifest
<Policies>
<EndpointBindingPolicy CertificateRef="ServiceCert" EndpointRef="HttpsServiceEndpoint"/>
</Policies>
<Certificates>
<EndpointCertificate Name="ServiceCert" X509FindValue="[CertThumbprint]" X509StoreName="MY"/>
</Certificates>

Yes, The old certificate was on the machine.
As the default way of replacing the certificates is to add a new certificate and roll over the new one as primary and mark the old one as secondary.

**Comment by amanbha** [comment]
@SainiAshish  What was the error for that 1st replica?

**Comment by SainiAshish** [comment]
@amanbha  hosting service activation failed.
There was no more details except this message.

**Comment by amanbha** [comment]
@SainiAshish I am closing this issue, please feel free to open a new issue or reopen this one with more details about the error.
