### ISSUE TITLE
[Standalone] Cluster size 1 is not supported. Cluster size should be between 3 and 1000

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#308]
I am trying to create a single node cluster using Service Fabric Standalone, however I get the error:
`Cluster size 1 is not supported. Cluster size should be between 3 and 1000`.

I know it is possible to create a single node cluster as it works as dev cluster and recently this option is available for Azure. It seems it is not supported in JSON cluster config, but it is supported in cluster manifest like in `ClusterManifest-Server-Default.xml`.

Can I somehow force Standalone to work as single node?

**Comment by maburlik** [comment]
Single node is not supported for standalone deployments.

**Comment by mkosieradzki** [comment]
You can change wontfix to fixed ;). Thanks for fixing this in 5.7. It works!
