### ISSUE TITLE
No option to kill a service on demand 

### ISSUE THREAD

**Issue by shlomcoh** [Azure/service-fabric-issues#309]
Hello,
we had some problems with Deployments takes too much time SF cluster, after some long investigation we found the problem and fixed it. I asked Microsoft to have the ability to Kill applications that refuse to go down for deployment and I got a reply that this option is not possible and i will need to file for a feature request.
One of our web services that should be hosted in SF Cluster will have a lot of instances in production (today we have more than 300 Instances).
I am Afraid that once we will take this Wesbervice to SF, If we will have any issue with Service not going down immediately or any issue with stopping the service we might need to wait with a critical bug in production for x instances multiple 15 minutes timeout for each instance. This is also something that we might miss in a pre-production environment because we don’t have a way of knowing that a service will have issues coming down before we deploy another version.
I understand the problems we might face with killing a service but I think this is something that should be up to us and should be under our consideration.

Regards,
Shlomi

**Comment by vturecek** [comment]
There are a few options already. [Remove-ServiceFabricApplication](https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricapplication?view=azureservicefabricps) has a -ForceRemove option. [Remove-ServiceFabricReplica](https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricreplica?view=azureservicefabricps) has a ForceRemove option as well. 

But these are extreme measures. I'm more concerned with
 1. Why you're removing an application to deploy a new version. You should be doing rolling upgrades.
 2. Why your applications are hanging when you delete them. This means your service code is not responding when the platform asks it to stop which you need to fix.

**Comment by shlomcoh** [comment]
1. sorry if i wasn't clear. I am not using Remove-ServiceFabricApplication and I am doing rolling upgrades, I am using Microsoft SDK for deployment with Publish-UpgradedServiceFabricApplication
after discussing with Microsoft support i undetstood there is no way to kill an application while rolling, the only option we have while rolling is to wait.
2. for your second question, our applications were in hanging mode b/c they were stuck on starting, and our R&D didn't handle cancellation token while starting, this was already fixed and now applications are going down nicely, but it did raise a big concern, in the future when we will go live with our production that has 99.995%, do we want to get to the stage where we have an application delivery that went wrong determine our production state for so long?
we decided this is too much of a risk for us and we need a better solution for Critical Bug fixing in our production Env. something that will say i want to do a rolling upgrade b/c my current application is still working but i want to do it NOW, without waiting 15 minutes for each instance to go down. (again, I understand this is only in cases someone in R&D will do a wrong use of cancellation token again, or something else that might corrupt services to go down smoothly )
