### ISSUE TITLE
Renew Cluster Certificate

### ISSUE THREAD

**Issue by shlatchz** [Azure/service-fabric-issues#31]
Hello,

I have a certificate that I added during the service fabric's creation. The certificate resides in azure's key vault.
This certificate expires in 01/08 and I need to replace it with a new one that I renewed.
How do I replace this certificate? I don't see an option in the GUI. There is only an option to add a secondary certificate, or an admin / read only client certificate.
I presume that a secondary certificate would also work (It will fall back from the expired primary certificate to the secondary certificate), but it's not a real solution.

Thanks!

**Comment by ChackDan** [comment]
Add the secondary (new) cert first. After that you can then flip the secondary (new) and the primary (old cert). once you have it flipped, you can just remove the old cert, if you do not want the system to use it.

Our portal team is working on improving the UI associated with the secure clusters all up. I will let them know. if there are specific suggestions, do suggest.

**Comment by shlatchz** [comment]
errrm... How do I remove the secondary certificate?

**Comment by ChackDan** [comment]
Just copy the thumbprint from the secondary to the primary and remove the secondary. I apologize the UI needs to be improved and will be.

**Comment by georgeslegros** [comment]
I might be looking at the wrong place but I don't see where you do that... Can you please elaborate a bit?

I'm fine doing that through Powershell but I don't find a cmdlet that might do it...

**Comment by ChackDan** [comment]
use the browse UI for it.. look details under - "The configurations that you control" 
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-cluster-upgrade/ 
If you hit issues, let us know.
as for the PS, you just need to submit a the revised ARM template via ARM PS. nothing unique for the cluster resource.

**Comment by georgeslegros** [comment]
Actually, this post seem outdated as the actual Portal does not exactly look like that anymore:

![Service Fabric Security Settings](https://s31.postimg.org/xzhr6pv4r/Seervice_Fabric_Security.png "Service Fabric Security Settings")

The thumbprints can not be edited (as on your post) and the only action possible in the situation I am now is Delete on the secondary (not on primary).

**Comment by shlatchz** [comment]
I second that..

![image](https://cloud.githubusercontent.com/assets/4594463/17168251/0569d4fa-53ea-11e6-9cd1-4cdbcd35b99d.png)

**Comment by aelij** [comment]
@ChackDan Is it possible to do this using an ARM template? Or a PowerShell script?

**Comment by ChackDan** [comment]
Sorry for the delay in responding. Agree with both of you, this is bad.  I will update the documentation and also provide the steps to update the certs using ARM. ETA early next week. I will also have some sample templates, since ARM deployments can be a bit involved. I have talked to the portal team as well, they are planning on updating the portal as well, so swap out the primary and then delete the old cert.

**Comment by ChackDan** [comment]
Sorry about the delay - here is the process to update the certs.
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-cluster-security-update-certs-azure/ 

In the process of updating the other documents wrt cluster creation. It will be updated soon as well. thankyou for being so patient.

**Comment by DenisPitcher** [comment]
The documentation linked suggests "have the template that you used to set up the cluster handy".  I setup my cluster months ago and don't believe I saved the template used.  What do I do in that case?

**Comment by DenisPitcher** [comment]
Ok, nevermind, I see that it is available under the "automation script" menu item

**Comment by paul198204** [comment]
Hi,

 I am also looking for the help on cert rotation. I have primary and secondary certs uploaded to cluster during creation. Now I would like to do the below

Primary cert rotation:
----------------------
Rotate Primary cert using Keyvault
Swap primary cert with secondary cert and upload rotated primary cert as secondary cert
Swap primary with secondary to make sure rotated primary cert becomes primary

Could you please let me know what is the way to do the above steps via Powershell (Not from UI) with out any down time of the cluster.

Thanks,
Paul

**Comment by slandsaw** [comment]
Any ETA as to when the cert renewal/swap experience will be updated in the portal?

**Comment by ChackDan** [comment]
No ETA. It is a part of the backlog, but you can very easily do that using azure PS (4.0+)
Add-AzureRmServiceFabricClusterCertificate

**Comment by slandsaw** [comment]
Perfect. Thanks!

**Comment by slandsaw** [comment]
I know this is an old issue, but I have to ask... is there any down time during the certificate swap? I have a three node cluster that I am getting ready to try this out on.

**Comment by Robar666** [comment]
Is there still no UI update on this issue? If I understand this correctly, I've to switch the certs every over year for new ones (unless I create a self signed one which expires in 2099). This is quite cumbersome to do thi, if I've to fiddl around in https://resources.azure.com.
