### ISSUE TITLE
SDK 2.6.210 on a cluster with SF Runtime Version 5.6.220

### ISSUE THREAD

**Issue by shlomcoh** [Azure/service-fabric-issues#311]
I was trying to deploy a new package from one of the SF nodes in the cluster.
When I tried to install SDK on the cluster I got an error saying I need SF Runtime version 5.6.210.9494.
It looks like I can’t install SDK 2.6.210 on a cluster with SF Runtime Version 5.6.220… and there is no SDK 2.6.220 so It looks like i can't install SDK on that node.
to workaround this issue we had to Install SDK 2.6.210, remove 2.6.220 runtime and add the server as a new node to the cluster for it to work.
Is this by Design? Is it a bug? Do you know if SDK 5.6.220 is about to be released soon?

**Comment by vturecek** [comment]
I'm not clear on what you're trying to do. Why are you trying to install the SDK on your cluster nodes? The SDK installation is for your development environment. 

The 2.6.220 SDK is on its way, but in the meantime you can deploy application built with the 2.6.220 SDK to clusters that are running the 5.6.210 runtime.

**Comment by shlomcoh** [comment]
Hi,
I was trying to install SDK on a cluster node b.c Hui from Microsoft asked me try and reproduce and issue we have with SDK upgrade application powershell script, we have 6 minutes deployment time for an application with 140MB on internal network. he asked me to do the same thing from inside one of the nodes while connected to the same node to eliminate the option of network issue.
so i was trying to install new SDK on one of the nodes and i saw this error.
anyway I don't understand your question to my question. is it a bug? is it by design? do we have a problem with using CI/CD from inside one of the nodes with SF SDK? 
and for your last sentence, I know i can deploy from 5.6.210 to SF 5.6.220 but if i can't install the sdk on a new cluster I will have to use a non Cluster server for deployment. as that is the case here?

**Comment by masnider** [comment]
@shlomcoh you wouldn't need to install the SDK on the nodes of the cluster as all the components and APIs are already present. The same commands that you use to create and delete applications would work there.

**Comment by masnider** [comment]
@shlomchoh - were you ever able to resolve this? You should have just been able to run the commands on the nodes without installing the SDK. And installing the SDK yourself is never going to be supported. 

If you give us more information we can try to recommend you what to do. If we don't hear back from you we'll close the issue down.
