### ISSUE TITLE
EndpointProviderPortRangeExhausted 

### ISSUE THREAD

**Issue by jrouaix** [Azure/service-fabric-issues#312]
Hello,

A stateless service of ours have hard time to activate on all of our nodes, we found some informations on the windows event viewer but have no clue about how the problem or correction.

I post the event viewer message in the next message ...

**Comment by jrouaix** [comment]
The description for Event ID 23041 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

5101db1125ead8d47d6f93321d3eb754:131413100131518173
Activator
Activate: Activate:#########.ApiService.AppType_App122:#########.ApiServicePkg:1.0:1.0:131413147232418232, ErrorCode=EndpointProviderPortRangeExhausted, RetryCount=14

The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

**Comment by maburlik** [comment]
Can you please post your NodeType configuration from the cluster config or manifest? It sounds like your port range configuration is too restrictive.

**Comment by rishirsinha** [comment]
Closing as there is no update.
