### ISSUE TITLE
Warnings in UpgradeService & unable to place replica

### ISSUE THREAD

**Issue by alecor191** [Azure/service-fabric-issues#313]
### Setup
I have the following setup:
- Cluster consisting of 2 node types (each has 3 nodes); one node type has the placement property "IsDMZ=true" the other "IsDMZ=false".
- Application deployed with 2 services: one with placement constraint "IsDMZ==true" the other "IsDMZ==false". Each service is configured to have 2 instances.

### Issue
There are two anomalies I observed now a couple of times in our cluster, and they typically occur at the same time:
1. Warning about SF not being able to place services of the app:
```
The Load Balancer was unable to find a placement for one or more of the Service's Replicas:
Secondary replica could not be placed due to the following constraints and properties:  
TargetReplicaSetSize: 2
Placement Constraint: (isDMZ==true)
Parent Service: N/A

Constraint Elimination Sequence:
PlacementConstraint + ServiceTypeDisabled/NodesBlockListed eliminated 6 possible node(s) for placement -- 0/6 node(s) remain (total of 3 nodes blocklisted for this service).

Nodes Eliminated By Constraints:

PlacementConstraint + ServiceTypeDisabled/NodesBlockListed -- PlacementProperties must Satisfy Service's PlacementConstraint, and Nodes must not have had the ServiceType Disabled or be BlockListed due to Node's Pause/Deactivate Status:
--
FaultDomain:fd:/1 NodeName:_nltsfn001_1 NodeType:nltsfn001 NodeTypeName:nltsfn001 UpgradeDomain:1 isDMZ:true UpgradeDomain: ud:/1 Deactivation Intent/Status: None/None
FaultDomain:fd:/2 NodeName:_nltsfn002_2 NodeType:nltsfn002 NodeTypeName:nltsfn002 UpgradeDomain:2 isDMZ:false UpgradeDomain: ud:/2 Deactivation Intent/Status: None/None
FaultDomain:fd:/1 NodeName:_nltsfn002_1 NodeType:nltsfn002 NodeTypeName:nltsfn002 UpgradeDomain:1 isDMZ:false UpgradeDomain: ud:/1 Deactivation Intent/Status: None/None
FaultDomain:fd:/2 NodeName:_nltsfn001_2 NodeType:nltsfn001 NodeTypeName:nltsfn001 UpgradeDomain:2 isDMZ:true UpgradeDomain: ud:/2 Deactivation Intent/Status: None/None
FaultDomain:fd:/0 NodeName:_nltsfn002_0 NodeType:nltsfn002 NodeTypeName:nltsfn002 UpgradeDomain:0 isDMZ:false UpgradeDomain: ud:/0 Deactivation Intent/Status: None/None
FaultDomain:fd:/0 NodeName:_nltsfn001_0 NodeType:nltsfn001 NodeTypeName:nltsfn001 UpgradeDomain:0 isDMZ:true UpgradeDomain: ud:/0 Deactivation Intent/Status: None/None
```

2. UpgradeService shows a warning with an exception stack:

```
Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPPoll', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpGatewayClient.d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpPackageRetriever.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__18.MoveNext()
```

### Additional info
- Interestingly I have another application running in the same cluster, with it's services also being split among the two node types (same conditions). I didn't observe this issue there.
- Removing the application and then redeploying doesn't help.
- All 6 nodes (3 instances x 2 node types) are in the "Up" state and health is "OK"
- Cluster version: 5.6.210.9494, hosted in Azure
- Screenshot of SF Explorer
![screenshot](https://user-images.githubusercontent.com/6270008/27004238-71b0b996-4e06-11e7-9512-7dbd7864e2ee.png)

Any idea what the issue could be? I'm not sure I understand the explanation text above describing the placement issue: For each service there are 3 healthy nodes it could be hosted on and we only need 2 instances.

Please also note that the warning description above mentions "**Secondary** replica". These are stateless, singleton partition services: Isn't the concept of a "secondary replica" only used for *stateful* services?

**Comment by alecor191** [comment]
**Update**: After some digging I found that there was actually an issue starting up the services of the app (threw exceptions on startup and thus the process died).

So while I was able to get rid of the warnings above, I was wondering what the reason is for SF showing me the warnings above instead of just that it wasn't able to start the services:

Is the TaskCanceledException in UpgradeService caused by a timeout, perhaps because it wasn't able to activate my services within a certain amount of time? Any thoughts on the placement warning (i.e. why show placement warnings instead of just informing that the services simply failed to start)?

**Comment by masnider** [comment]
Hi @alecor191 To address some of your specific concerns:

1. Yeah the Node Blocklisted warning should be an extra warning indicating that the code on the node is crashing for some reason. Which is a hint to go take a look at that health data. However there are cases where depending on how the process is crashing where there aren't health reports generated or they don't have a lot of great information - Ex: they'd be missing the stack trace for the crash (@RajeetN)

1. I've also seen cases where there are node errors but they are not propagated up to the top level "Nodes" node in SFX at the time (@yanchenw & @MikkelHegn). 

1. For issues with the Upgrade service, I've added @ChackDan and @raunakpandya. Most of these are known but they should check.

1. Yes secondaries are only a concept that exist for stateful services.

**Comment by MikkelHegn** [comment]
For SFX this is currently by design, but consider fixing this to make health warnings more discoverable.

**Comment by vaishnavk** [comment]
@alecor191 Does the upgrade service warnings persist or are they transient? If they persistent, please share the cluster id/resource id and the region name and we can take a look.

**Comment by BrainSlugs83** [comment]
Agreed, it would be great to know the exception data, my cluster constraint is "N/A" (because there isn't any constraints) and it still shows the same misleading message without any details of the actual cause (and locally everything works fine), so it's going to be a real pain to debug this. :(

**Comment by masnider** [comment]
There have been improvements to the upgrade service's stability, placement constraint handling, and a lot of work done to improve the handling of errors and also making them easier to diagnose (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-code-package-errors). We have also made improvements to SFX to make errors easier to discover and interpret.
