### ISSUE TITLE
Unable to pack/publish after updating to new csproj

### ISSUE THREAD

**Issue by aL3891** [Azure/service-fabric-issues#314]
Hello, 
I've updated some of our actor/reliable service projects to the new csproj format, however when running the package target, it appears the target calculates the output folder incorrectly. The services are built to `c:\folder\Services\obj\Debug\net462\win7-x64\Services.exe` but the target tried to copy from `c:\folder\Services\obj\64\Debug\net462\win7-x64\Services.exe` That is the Platform is incorrectly added to the path by the sf build target.

Is this a know issue and if so is there a workaround? i noticed it does work in an asp.net core project i have, but i have not found any differences in the project file. The projects i've been converting are "regular" stateless services and actors

specifically, this is the error i get 

    c:\folder\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets(248,5): error MSB3030: Could not copy the file "c:\folder\Services.Assets\bin\x64\Debug\net462\win7-x64\Services.Assets.runtimeconfig.json" because it was not found.

The files do in fact exist in the folder `c:\folder\Services.Assets\bin\x64\Debug\net462\win7-x64\Services.Assets.runtimeconfig.json`

i get three additional errors referring to different files

**Comment by MedAnd** [comment]
I've experienced similar issues during the course of upgrading from VS 2015 to VS 2017... see:

#303
#231

In the last stages of testing several workarounds...

for example if in your *.csproj files you see:

`<RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>`

try replacing with:

`<RuntimeIdentifier>win7-x64</RuntimeIdentifier>`

also are your *.csproj files defined with `<Project Sdk="Microsoft.NET.Sdk">` or `<ProjectSdk="Microsoft.NET.Sdk.Web">`, important in case your projects were .Net Core in VS 2015

**Comment by aL3891** [comment]
@MedAnd Thanks! the Sdk.Web workaround works great!

I hope they fix this in a future release though, seems like it should work with just the regular sdk as well.

**Comment by cwe1ss** [comment]
The "Sdk.Web"-workaround worked for me as well. However, it would be great to see official support for the new format soon!

**Comment by mkosieradzki** [comment]
+1 Thanks @MedAnd for the Sdk.Web - workaround.

To add something from me:
I am using <Platforms>x64</Platforms> (and added it as x64 in solution Configuration Manager) and it works without RuntimeIdentifiers hack.

Works perfectly for stateful services as well

**Comment by BigMorty** [comment]
We added .NET Core 2.x templates for stateful, stateless, and actors quite a while ago, so this workaround should no longer be necessary. As of Visual Studio 2019 16.3.6 you will find these templates work with .NET Core 3.0 as well.

**Comment by MedAnd** [comment]
@bigmorty - some customers are reporting issues with .Net Core 3.0. See #1580 for example.

**Comment by masnider** [comment]
@MedAnd do you still see issues here though or can we consider this specific item resolved?

**Comment by MedAnd** [comment]
I would say this issue is closed but maybe @aL3891 best to confirm?

**Comment by BigMorty** [comment]
Thanks @MedAnd, agree we should use #1580 to track any 3.0 runtime issues, this issue was originally started because of the lack of .NET Core templates. @aL3891, I am closing this since we have templates now, reopen it if you don't agree.
