### ISSUE TITLE
Getting IReliableDictionary via reflection returns DistributedDictionary.

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#317]
I am trying to setup an IReliableDictionary with serialized state from external storage.
Thing is, the generic argument's types come as assembly qualified names - so to get the IReliableDictionary from StateManager, I need to create the generic method of GetOrAddAsync with type arguments that I provide, and invoke it on StateManager.
Next step is to use dynamic and call ContainsAsync and then SetAsync on this supposed-to-be-IReliableDictionary.
Turns out though, that I get a **DistributedDictionary** back, and it doesn't have those methods, so I get exception with 'object' does not contain a definition for 'ContainsKeyAsync'.
I fail to find a way to get an IReliableDictionary back, as I would normally do when not calling the method via reflection. 

**What can I do here?**

This is what I try to do (which all works in test with a MockReliableStateManager):

```
async Task SaveState(string stateKey, Tuple<string, byte[], string> data)
    {
        var viewModelType = data.Item3;

        var emptyType = typeof(IReliableDictionary<,>);
        Type[] typeArgs = { typeof(Guid), Type.GetType(viewModelType) };
        var reliableDictType = emptyType.MakeGenericType(typeArgs);

        var addMeth = typeof(IReliableStateManager)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name == "GetOrAddAsync")
            .Where(m =>
            {
                var p = m.GetParameters().ToList();
                return (p.Count == 2 && p.First().ParameterType == typeof(ITransaction) &&
                    p.Last().ParameterType == typeof(string));
            }).Single();
        var genMeth = addMeth
            .MakeGenericMethod(reliableDictType);

        dynamic state;
        using (var tx = _stateManager.CreateTransaction())
        {
            state = (await (dynamic)genMeth.Invoke(_stateManager, new object[] { tx, stateKey }));
            await tx.CommitAsync();
        }

        var dictType = data.Item1;
        var dictData = data.Item2;
        var dict = (IEnumerable)dictData.Parse(dictType);

        using (var tx = _stateManager.CreateTransaction())
        {
            foreach (var pair in dict)
            {
                var key = ((dynamic)pair).Key;
                var value = ((dynamic)pair).Value;
                var exists = await (Task<bool>)state.ContainsKeyAsync(tx, key);
                if (exists)
                    continue;
                await state.SetAsync(tx, key, value);
            }
            await tx.CommitAsync();
        }
    }
```

**Comment by zeodamian** [comment]
I had to go with a long switch statement.

I guess the functionality I'd like to see here, is just to be able to batch initialize an IReliableDictionary with an IDictionary for example.

**Comment by tyms** [comment]
DistributedDictionary just happens to be the underlying implementation of IReliableDictionary.  It does implement ContainsKeyAsync, but via explicit implementation, so you may have to stand on your head a little more to call it via reflection.

This [stackoverflow](https://stackoverflow.com/questions/3650575/how-can-i-access-an-explicitly-implemented-method-using-reflection) question/answer may help.
