### ISSUE TITLE
High memory usage when calling a Stateful Service when using GCServer true

### ISSUE THREAD

**Issue by AlexFlat** [Azure/service-fabric-issues#320]
Hi,
We are running a Service Fabric application and have recently switched to the `<gcServer enabled="true"/>` for all services as it is recommended for server workloads.
Since this change we have noticed a large spike in memory usage for all our services, some **going from 50mb to more than 700mb**. 
This memory does not seem to release.
This is present in multiple environments in our system.
We currently have 20+ microservices in our application which is now causing our memory usage to max out and in development, causing other applications to close with Out Of Memory exceptions.

By setting it back to false the memory drops down again.
The usage increases when the Proxy.Method() is called and I have simulated this in a test project calling the proxy 1000's of times.
**The test sample can be found in the following GIT repo.**
**https://github.com/AlexFlat/ServiceFabricMemoryTest**
This is using the latest SDK and Runtime (5.6.210.9494)

I am wondering whether the GCServer mode is supported in a large Service Fabric application with many services.

Thanks in advance for your time,

Alex

**Comment by MedAnd** [comment]
@AlexFlat any idea how many active HTTP connections this process has open once it reaches 700mb?

**Comment by VipulM-MSFT** [comment]
We will be closing this issue, please let us know if you still see an issue with the latest SDK and runtime.

**Comment by AlexFlat** [comment]
Hi,
I have updated the SDK to 6.0.219 and it seems I still have the same issue.
Executing the UnitTest once forces the Service1.exe to increase to 330mb.
Running the same UnitTest again causes the memory to grow again to 440mb.
See the attachments for the memory usage details.

Test1
![image](https://user-images.githubusercontent.com/17284248/32206911-6b5fa3ca-be4c-11e7-88ca-56c0d40534bb.png)

Test2
![image](https://user-images.githubusercontent.com/17284248/32206985-e71b746c-be4c-11e7-9a2d-16d5fff88027.png)


As such, I am not confident to change to the GCServer in our production code.
Can you please test this and confirm you see the same behavior?
Can you also keep this open as I don't feel like it has been resolved?

**Comment by johnkattenhorn** [comment]
@MedAnd - thanks for the heads up, those two issues it links too and definitely worth us checking out, I also found I potential additional issue with our code I posted the detail in the SO post here 

https://stackoverflow.com/questions/47681701/service-fabric-stateful-service-consuming-large-amounts-of-unmanaged-memory

Seems we lazy load FabricClient in our Actor Constructor but we never dispose so we are investigating if this could be our issue, any thoughts ? recommendations ? I'm new to WinDbg so maybe misinterpreting what I've found with that tool.

**Comment by pisees** [comment]
Is GCServer recommended now for .NET services: (1)  Full .NET Framework or (2) DotNet Core?
