### ISSUE TITLE
[Question]How can I set Service Fabric Explorer certificate independently to the cluster certificate?

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#322]
Consider following scenario:
1. I would like to use one long-lived certificate for securing internal service fabric traffic (for example self signed).
2. I would like to the same certificate as in one when connecting through the TCP endpoint 19000 (There is a thumbprint validation so everything is self-signed friendly to this point).
3. I would like to use short-lived DV certificates for https Service Fabric explorer endpoint and possibly reuse this certificate in different services (for example wild card cert). I would definitely not want this wildcard certificate to be used for internal cluster authentication.

Is it possible today? What option should I use?

**Comment by linggengmsft** [comment]
@mkosieradzki , unfortunately, there is only one server certificate at a certain time point that can be used by Service Fabric cluster, regardless of TCP or Http channel.

**Comment by mkosieradzki** [comment]
No chances for changing this one? I think it would be helpful to distinguish https auth which depends on public PKI and tcp auth which depends on thumbprints etc.

**Comment by linggengmsft** [comment]
@mkosieradzki , there are no accessibility scope in terms of different communication channels in Service Fabric. i.e., both of your endpoints could be public or internal as long as you configure it in the Load Balancer. Currently, there would be only one server certificate for server authentication.

I agree your requirement is a valid one, we will discuss it internally and see if we could add it in the future release.

**Comment by mkosieradzki** [comment]
@linggengmsft thanks, however I found a more than a valid workaround. I am generating certificate through the let's encrypt CA. That way without unreasonable spending for yet-another-certificate I am generating and automatically rolling over certificate every two-three months.

Thanks to this approach the rollover process is a much more standard procedure (happens much more often) and also certificate rollover is a good security practice. This also influenced me to automate and auto-schedule the entire process. It is a significant, but also a reasonable effort.
