### ISSUE TITLE
Service Fabric sdk Installation Failure due to LeasLayr failed Issue

### ISSUE THREAD

**Issue by GuptaParitosh** [Azure/service-fabric-issues#323]
Fatal Error while installing MicrosoftServiceFabric Runtime 5.6.210 on Window 7 Machine with Visual Studio 2017.

Receiving Error As:
InstallDrivers: StopSerivce LeasLayr does not exist.
InstallDrivers: Driver Path = C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys
InstallDrivers: CreateService LeasLayr successfully.
InstallDrivers: Error 0x80070241: StartService LeasLayr failed with error code: 577.
InstallDrivers: Error 0x80004005: InstallDriver LeasLayr returned error 2147942977

Activity Logs can be downloaded Here:
https://drive.google.com/file/d/0B0PQUsGXIy77TlhWZnBSZldiQzA/view?usp=sharing

Could anyone help in resolving this installation Issue.

Microsoft has already provided a hot fix to resolve such problem for Window 8/Window Server 2012 as given below:
https://support.microsoft.com/en-us/help/2858668/pla-data-collector-sets-stop-after-72-hours-on-a-windows-server-2012-based-computer.

Since we are using window 7, this hotfix wouldn't help.

**Comment by rishirsinha** [comment]
This is a known issue with older versions of Win 7. Making sure that the OS is fully updated has resolved the issue for us when we hit it in the past.

**Comment by AlanWarwick** [comment]
Please go into Windows Update and verify that all updates have been applied and then try again.

**Comment by rishirsinha** [comment]
@GuptaParitosh Can you confirm that the issue is resolved? I will leave the issue up for the next week so that we can get a mutual resolution.

**Comment by GuptaParitosh** [comment]
@rishirsinha Issue is resolved by updating the window 7. Please close this issue.
@rishirsinha  @AlanWarwick  Thanks for the help.
