### ISSUE TITLE
Connecting my Angular- Express/Nodejs client to a Service Fabric application deployed in Azure

### ISSUE THREAD

**Issue by valcs007** [Azure/service-fabric-issues#324]
Hi,

I implemented microservices using Service fabric (Implemented WCF SOAP listener) and deployed in Azure.

**.Net Client:**
I figured out a way to connect my local WPF Client to Service fabric app deployed in Azure by creating Channel using ChannelFactory (SOAP listener was implemented). Everything  works fine

**Angular/ Express Node Js Client:**
In order to connect my Angular client, i replaced SOAP listener with the below HTTPListener call from te help document (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services)

![image](https://user-images.githubusercontent.com/6827384/27302868-a28e8bae-54ed-11e7-8942-08661e60d649.png)

Can you please let me know how can i connect to Azure service fabric  from my local Angular- Node/Express js client?  Please gvie me some sample client code

**PS:** If everything works, we will deploy our Angular client to Azure as well

Thanks,
Valliappan

**Comment by masnider** [comment]
You should just be able to hit the http endpoint of your service. Have you tried this? If so what's the situation that you're running into?

**Comment by masnider** [comment]
@valcs007 - Hi there - we haven't heard back from you on this. At this point we're going to close the issue. If you have more information about what you've tried that you can share with us, please just reopen the issue and let us know, or feel free to create a new issue if you prefer.
