### ISSUE TITLE
Not able to run the Default Service Fabric Stateless application, Need Help

### ISSUE THREAD

**Issue by GopiMtp** [Azure/service-fabric-issues#326]
Hi,

When I start the default Stateless app in VS2015, 2017 I'm getting the below error.

2>Local Service Fabric Cluster is not setup...
2>Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
2>Remove-ServiceFabricNodeConfiguration : Argument 
2>'Remove-ServiceFabricNodeConfiguration' is not recognized as a cmdlet: Unable 
2>to load DLL 'FabricCommon.dll': The specified module could not be found. 
2>(Exception from HRESULT: 0x8007007E)

I've installed the Service Fabric SDK (see below)

![image](https://user-images.githubusercontent.com/24237966/27452026-f82d1f94-5745-11e7-8bf9-c952a440c3ca.png)

I'm running this on Win7 OS

Any quick help would be much appreciated.

**Comment by MikkelHegn** [comment]
Please see if this is related to this issue: https://github.com/Azure/service-fabric-issues/issues/323

**Comment by GopiMtp** [comment]
Thanks for your quick response, but that is related to SF RunTime Installation.  The issue I've reported is more of an error with PowerShell Command. 

Do I need to be the Administrator for the machine to make it work?

**Comment by MikkelHegn** [comment]
You need to run VS as administrator for it to be able to work with the local dev cluster.

**Comment by GopiMtp** [comment]
I made my user as "Administrator", after that I'm getting a different error. PFB 

------ Deploy started: Project: RSSCustomerPortalAPI, Configuration: Debug x64 ------
3>Started executing script 'GetApplicationExistence'.
3>Finished executing script 'GetApplicationExistence'.
3>Time elapsed: 00:00:11.0544212
3>Started executing script 'Set-LocalClusterReady'.
3>Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1'; Set-LocalClusterReady
3>--------------------------------------------
3>Local Service Fabric Cluster is not running...
3>Please wait while we start the Local Service Fabric Cluster. This may take few minutes...
3>Starting service FabricHostSvc. This may take a few minutes...
3>Start-Service : Failed to start service 'Microsoft Service Fabric Host Service 
3>(FabricHostSvc)'.
3>At C:\Program Files\Microsoft SDKs\Service 
3>Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:458 char:5
3>+     Start-Service FabricHostSvc -WarningAction SilentlyContinue
3>+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
3>   ler:ServiceController) [Start-Service], ServiceCommandException
3>    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands 
3>   .StartServiceCommand
3> 
3>StartLocalCluster : Could not start FabricHostSvc
3>At C:\Program Files\Microsoft SDKs\Service 
3>Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1:52 char:9
3>+         StartLocalCluster
3>+         ~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
3>   tion
3>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
3>   n,StartLocalCluster
3> 
3>ScriptHalted
3>At C:\Program Files\Microsoft SDKs\Service 
3>Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:462 char:9
3>+         throw
3>+         ~~~~~
3>    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
3>    + FullyQualifiedErrorId : ScriptHalted
3> 
3>Finished executing script 'Set-LocalClusterReady'.

**Comment by GopiMtp** [comment]
I've checked the logs in Event Viewer and found the below error

.COMException (0x800706D9): There are no more endpoints available from the endpoint mapper. 

googling this error I found this: 
[https://social.technet.microsoft.com/Forums/en-US/fc83c72a-dee6-4a6e-bce3-c19f9536eb23/error-0x800706d9-exchange-2010-sp2-upgrade?forum=exchangesvrdeploylegacy](url)

**Started the Windows Firewall service fixed the issue and able to execute the sample application **

**Comment by MikkelHegn** [comment]
Good to know - btw you link above does not work :-)

**Comment by GopiMtp** [comment]
Updated with correct link!
