### ISSUE TITLE
Swagger not working behind reverse proxy

### ISSUE THREAD

**Issue by hiraldesai** [Azure/service-fabric-issues#327]
I'm having an issue where trying to get Swagger UI working through Service Fabric reverse proxy.

```
        public static void UseSwaggerWithOptions(this IApplicationBuilder builder, string title, string apiSuffix, string version = "v1")
        {
            builder.UseSwagger(options => options.RouteTemplate = "docs/{documentName}/swagger.json");
            builder.UseSwaggerUI(c =>
            {
                c.RoutePrefix = $"{Constants.ServiceFabric.AppName}/{apiSuffix}/docs";
                c.SwaggerEndpoint($"/docs/{version}/swagger.json", $"{title} {version}");                
            });
        }
```

I can access `http://localhost:19081/My.SF.AppName/My.Stateless.Api/docs/v1/swagger.json` but the UI doesn't load when I try to access `http://localhost:19081/My.SF.AppName/My.Stateless.Api/docs`. It times out after spinning for 30 odd seconds.

**Comment by kavyako** [comment]
This is not a Service Fabric reverse proxy issue. The Swagger middleware you are using must expose a way to access the UI via reverse proxies. 
I am assuming you are using SwashBuckle here, SwashBuckle  4.0 and 5.0 had options like ResolveBasePathUsing and RootUrl to configure this.

I tried some configs but could not get this working with SwashBuckle.AspNetCore.
Something like the below loads the UI, however the Try It Out does not seem to working, even though the Web API is receiving and serving the request:
Request URL to get the UI http://localhost:19081/appname/servicename/swagger/

            // Enable middleware to serve generated Swagger as a JSON endpoint.  

            app.UseSwagger(c =>
            {
                c.PreSerializeFilters.Add((swagger, httpReq) => swagger.Host = httpReq.Host.Value);
            });
            // Enable middleware to serve swagger-ui (HTML, JS, CSS etc.), specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/<appname>/<servicename>/swagger/v1/swagger.json", "My API V1");
            });

Here are two open issues in the SwashBuckle.ASpNetCore repository:
[Swagger UI behind Service Fabric Reverse Proxy](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/427)
[Add Support to set BaseURL](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/441)
Let us follow up on these threads to get the right configurations in SwashBuckle.AspNetCore.

**Comment by hiraldesai** [comment]
Thank you for investigating, much appreciated. I will keep an eye out for updates to these too.

**Comment by cwe1ss** [comment]
To a certain extend, this IS a reverse proxy issue. Even if you could set the BaseUrl/RootUrl in Swashbuckle, you'd still have to know the path under which the reverse proxy serves the service to generate a proper absolute URL. Sure this is a well-known path, so you could just hard-code this to e.g. "myapp/myservice" but then you couldn't test it locally anymore.

The correct solution would be for the reverse proxy to forward the original url ("myapp/myservice") to the underlying service. This could then create the absolute URL based on this header.

This is what I requested in https://github.com/Azure/service-fabric-issues/issues/273

**Comment by JDL440** [comment]
I was able to make this work by seeting the basePath like this:
               .UseSwagger(c =>
               {
                   c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/MyServiceApp/MyService");
               })

**Comment by kavyako** [comment]
Thanks @JDL440  for sharing the solution. 
Closing this issue based on the above comment.

**Comment by iparimal** [comment]
I've fixed this using NSwag. 
I’ve removed “Swashbuckle.AspNetCore” and using “NSwag.AspNetCore” now. It works without any issue.

**Comment by Eneuman** [comment]
@iparimal Can you please show us your configuration as I can not get this to work

**Comment by iparimal** [comment]
@Eneuman 
Here are steps to follow:
Install-Package NSwag.AspNetCore

Add below refs:
using NSwag.AspNetCore;
using System.Reflection;
using NJsonSchema;

public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles();

    // Enable the Swagger UI middleware and the Swagger generator
    app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings()
    {
        DefaultPropertyNameHandling = PropertyNameHandling.CamelCase
    });

    app.UseMvc();
}

Let me know if it helps.

**Comment by wswind** [comment]
you can use relative URL to fix thi issue,see this comment:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/380#issuecomment-374711180
