### ISSUE TITLE
Problem with Upgrade Orchestration Service using fabric:ImageStore on Standalone Cluster

### ISSUE THREAD

**Issue by MattDarg** [Azure/service-fabric-issues#329]
I just tried installing Service Fabric 5.6.220.9494 as a new standalone cluster, the cluster was previously version 5.4.145.9494 which was uninstalled first.  As part of the move I wanted to change from using a file share for the image store, to using the built-in fabric:/ImageStore.  The install all went ok except for the Upgrade Orchestration Service which on kept crashing due to a missing dll relating to the image store client (see below).  I changed the image store to a file share and redeployed and it seems ok.

Application: FabricUOS.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Fabric.FabricException: An error occurred during this operation.  Please check the trace logs for more details. ---> System.Runtime.InteropServices.COMException: An attempt to delay-load a .dll or get a function address in a delay-loaded .dll failed. (Exception from HRESULT: 0x80070505)
   at System.Fabric.Interop.NativeImageStore.IFabricNativeImageStoreClient2.UploadContent(IntPtr remoteDestination, IntPtr localSource, UInt32 timeoutMilliseconds, FABRIC_IMAGE_STORE_COPY_FLAG copyFlag)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContentWrapper(String remoteDestination, String localSource, IImageStoreProgressHandler progressHandler, UInt32 timeoutMilliseconds, CopyFlag imageCopyFlag)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.<>c__DisplayClass8_0.<UploadContent>b__0()
   at System.Fabric.Interop.Utility.<>c__DisplayClass25_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   --- End of inner exception stack trace ---
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, IImageStoreProgressHandler progressHandler, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)

See also https://social.msdn.microsoft.com/Forums/azure/en-US/8233e8cd-abaf-4423-ae8c-dbb1047ffb72/problem-with-upgrade-orchestration-service-using-fabricimagestore-on-standalone-cluster?forum=AzureServiceFabric

**Comment by rishirsinha** [comment]
Hi Matt,

In general the error above indicates that there is a mismatch between the version of dll in the GAC (the version in the GAC being older) and the native dlls. If the 5.4 cluster was installed using the MSI, there is a chance that the GACed dlls remain behind in the GAC. MSI does ref counting which might delay removal from the GAC till a reboot. Now that you have installed standalone on top of it, even a reboot will not help. I would suggest uninstall the standalone version by running .\CleanFabric.ps1 (I am assuming it is a single node cluster, if it is not, run the script on all nodes). Once that has happened reboot the machine(s) and then create the standalone cluster. 

The OS level ref counting that the standard MSI installation does is also one of the reasons why we moved to our custom xcopy based install.

**Comment by MattDarg** [comment]
Hi Rishi, 

Thanks for the reply.  I had another go this weekend, with an uninstall / clean and reboot of the 3 nodes, but I still get the same problem.  When I'd done the uninstall I ran gacutil and there was no mention of Fabric there.

While it was starting up and crashing I used ProcessExplorer and can see FabricUOS.exe loaded FabricClient.dll and FabricImageStore.dll ok and from the locations I'd expect.  FabricImageStore was loaded very shortly before the crash.  There's some relevant stuff from process explorer attached, captured just before it crashed.  

I also got the fusion log viewer running and there were two failures I saw, one involving Microsoft.ServiceFabric.Data.Impl which seemed to load ok in the end, and one involving System.Fabric.Management.ServiceModel.XmlSerializers which is also attached.

[FabricUOS.exe.txt](https://github.com/Azure/service-fabric-issues/files/1133863/FabricUOS.exe.txt)

[System_Fabric_Management_ServiceModel_XmlSerializers, Version=5_0_0_0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.txt](https://github.com/Azure/service-fabric-issues/files/1133866/System_Fabric_Management_ServiceModel_XmlSerializers.Version.5_0_0_0.Culture.neutral.PublicKeyToken.31bf3856ad364e35.txt)





Thanks,

Matt.

**Comment by rishirsinha** [comment]
Is it crashing with the same error?

**Comment by MattDarg** [comment]
Yes, FabricUOS was crashing with the same error.  For the moment I've had to revert the cluster to a file share, but ideally we'd use the image store.

**Comment by rishirsinha** [comment]
Matt, will it be possible to get a crash dump of the FabricUOS? Another thing would be to attach a debugger and see which exact dll it is complaining about.

**Comment by MattDarg** [comment]
Hi, sorry for the delay.  I ran the Debug Diagnostic Tool and have attached two logs from it.  I enabled memory dumps for the 0XE0434352 exception for the second one, and can provide any of those if desired.

Thanks,

Matt,

[FabricUOS__PID__20864__Date__10_01_2017__Time_07_31_06PM__888__Log.txt](https://github.com/Azure/service-fabric-issues/files/1347432/FabricUOS__PID__20864__Date__10_01_2017__Time_07_31_06PM__888__Log.txt)


[FabricUOS__PID__46780__Date__10_01_2017__Time_07_57_11PM__254__Log.txt](https://github.com/Azure/service-fabric-issues/files/1347431/FabricUOS__PID__46780__Date__10_01_2017__Time_07_57_11PM__254__Log.txt)

**Comment by MattDarg** [comment]
Also, this is now with version 5.7.198.9494

**Comment by MattDarg** [comment]
With 6.0 FabricUOS no longer crashes, but attempting to use a client to deploy a file results in the same error coming back, which can also be seen in the event viewer on one of the servers as the result of the CopyToStaging operation from the FileStoreService:

CopyToStaging: Source:D:\ServiceFabric\Data\DEV1\Fabric\work\FileTransfer\2ace9119-e094-418f-be47-a85c2f711369, Destination:\\DEV2HOST\StagingShare_DEV2\131526473952770475\859a5809-0b6d-436e-88b3-92cafd69839e\375896f2-8433-4a0c-ac7b-f2e61a9e452c, Error:0x80070505

**Comment by MattDarg** [comment]
In the end we rebuilt the cluster with a fresh install of Windows Server 2016 and it all worked fine with the ImageStore enabled.
