### ISSUE TITLE
Actor Model Usage

### ISSUE THREAD

**Issue by georgeslegros** [Azure/service-fabric-issues#33]
We have an application that has about 1500 entities in a database.
For each of these entities, the application is getting data from different sources (http requests, file upload, ...) and the point of the application is to let users see their data and analyse it.

One of the key point of the application is to ensure the data consistency and raising alerts when it detects that an entity did not receive data.

We decided to use Service Fabric to do that. We used [this post](http://stackoverflow.com/questions/36729732/service-fabric-spawn-actor-on-startup) to create 1 instance of an Actor in order to set reminders for the instance to launch and do the necessary checks for the alerting system.

We created a Service fabric cluster on Azure with 5 A1 nodes and when we publish our app, the cluster seem overloaded. The machines are very often at 100% CPU. Even after more than an hour after publish. And they are actually not doing anything else than spawning the instances for now as we were checking if the spawning was working.
We compared it with another cluster that is identical (same config, different app) and we could see that in average, the CPU usage stays around 10%

That does not seem to be right... Especially when we know that today we have around 1500 entities but we plan for 20K entities in a rather near future.

So, could someone tell us if we're misusing ServiceFabric for this?

Note: here is a small quote from [Service Fabric Overview](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-overview/)

> Deploy applications at higher density than virtual machines, deploying hundreds or thousands of applications per machine.

**Comment by masnider** [comment]
Can you provide more information about what exactly you created? When you say 1 actor do you mean one actor service or literally one actor object? That said: A1's aren't recommended for any workload. If you create the cluster via the portal A1s are even in the recommended class of VM sizes. Keep in mind that the machines run the cluster itself as well as your workload. So an A1 has 1 core, and if you created 1500 actors which were doing work you'd have each of those virtual cores trying to execute ~300 threads + the OS + Service Fabric. Service Fabric seems like a fine fit, it just seems like there aren't enough resources for that particular workload.

**Comment by georgeslegros** [comment]
There is 1 service that hosts an http Endpoint (Owin, created with the VS template) and one Actor Service.
The actor service is created using something similar than in [the post](http://stackoverflow.com/questions/36729732/service-fabric-spawn-actor-on-startup)

Basically, when the ActorService starts, it does a lookup in DB to fetch the entities (to simplify, let's say that they are people so something like SELECT * FROM People) and foreach result it creates an Actor Instance. Something like this:

```
            foreach (var person in people)
            {
                await ActorProxy.Create<IPeopleActor>(new ActorId([INSERT_KEY])).CreateOrUpdate(person);
            }
```

We already found some things that were done at a wrong place, causing the launching of the Actor Instances to be very slow. So the situation now is that for 1.5K instances it takes about 2 minutes between start and end of launch where CPU goes regularly very high (up to 100% but not always).
We made tests with 35K and it takes 16 minutes.
We still have things to improve like the fact that we are initializing a Ninject Kernel for each instances, that will most probably be necessary but we can most probably optimize that to only get the necessary  dependencies.

Once the init is done, with 35K instances, it consumes about 800MB of RAM and about 5%CPU.
Also have to say that they are just not doing anything for now... We're going to add reminders there to execute actions.

You're perfectly right that A1 machines are probably a bit too small. Though, we still have to improve the init process.

**Comment by vturecek** [comment]
It's slow because you're doing 35,000 serial network operations. Doing the math with 35,000 operations in serial at 16 minutes total, that means each one takes ~28 ms, which could be a little faster, but it adds up when you do thousands one after another.

If you're not storing anything in the actor instances, then a lot of that 800MB might just be garbage that hasn't been collected yet. Hard to say without looking at GC perf counters though.

**Comment by hellkama** [comment]
Isn't the memory problem same as this:
https://github.com/Azure/service-fabric-issues/issues/62

**Comment by vturecek** [comment]
The memory issue was resolved a while back, closing this one out too.
