### ISSUE TITLE
Socket exhaustion when using SF-Reverse Proxy

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#330]
Hi,

I have a DEV-Cluster with 26 Applications (each running on two _virtual_ nodes) / REST Services.
Lately I'm getting this error:
![image](https://user-images.githubusercontent.com/5556013/27527034-e48f0d7e-5a49-11e7-85fe-58160bda2f32.png)

Using netstat I saw that also every Service has a Connection to serviceConnectionEndpointPort and  the process Fabric.exe vice versa.
So these are about 26 * 2 * 2 = 104 Sockets, this shoudn't exhauste the system anyway?
Memory is at about 90% and I don't know what queue the error is talking about ..

Edit:

I was now able to reproduce this on a 3-Node Cluster.
As soon as I'm using the SF-Reverse Proxy URL from API Gateway to my Services, after some hours this starts to happen and nothing works! No new SQL / HTTP / RabbitMQ / ...  connection!

**Comment by VipulM-MSFT** [comment]
What version of Service Fabric are you running? 

If is possible that you are running out of ephemeral ports on the machines. See if this helps https://blogs.technet.microsoft.com/clinth/2013/08/09/detecting-ephemeral-port-exhaustion/

You can also check the range of the ports 
netsh int ipv4 show dynamicport tcp
netsh int ipv4 show dynamicport udp
netsh int ipv6 show dynamicport tcp
netsh int ipv6 show dynamicport udp

**Comment by VipulM-MSFT** [comment]
Adding @BharatNarasimman and @kavyako

**Comment by senj** [comment]
Will check this, thanks

**Comment by senj** [comment]
Great infos. We are running version 5.6.220.
Using netsh int ipv4 show dynamicport tcp I can see that there are only 256 ports (I guess this is the default). The PS script says that about 50% of the ports are in use.

Do you think we should raise the number of ports, where are the drawbacks, that is a reasonable number?
I can try using SF-Reverse Proxy again and will check the logs after some time.

**Comment by senj** [comment]
We were running some days without the SF-Reverse proxy successfully.
After turning it back on, one day later, the error reoccurred.
```(provider: TCP Provider, error: 0 - An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.) ---> System.ComponentModel.Win32Exception: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
```

but...
```
Computer = xxx, DateTime = 11.07.2017 10:34:37, LocalAddress = xxx, #OfEPortsInUse = 35, Max#OfEPorts = 256, %EPortUsage = 13,
Computer = xxx, DateTime = 11.07.2017 10:34:37, LocalAddress = 127.0.0.1, #OfEPortsInUse = 26, Max#OfEPorts = 256, %EPortUsage = 10,2.
```

**Comment by kavyako** [comment]
@senj The 256 ports seems very less. 

Usually the output of "netsh int ipv4 show dynamicport tcp" on Windows 7 + is 
Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384
-----
To comply with Internet Assigned Numbers Authority (IANA) recommendations, Microsoft has increased the dynamic client port range for outgoing connections in Windows Vista and in Windows Server 2008. The new default start port is 49152, and the default end port is 65535. This is a change from the configuration of earlier versions of Windows that used a default port range of 1025 through 5000.
-------

Please increase the dynamic port range to address the issue.
Closing the issue. Reopen if you have any concerns.

**Comment by senj** [comment]
Yea sorry, we raised the number to the one you suggested and never had problems again
