### ISSUE TITLE
Running task after packaging

### ISSUE THREAD

**Issue by jorgemmsilva** [Azure/service-fabric-issues#331]
Hi guys, I need to run a msbuild task after packaging and before deployment.
Is there any entrypoint that can be called?

maybe something like this

```
<Target Name="AfterPackage" Condition="'$(Configuration)' == 'Release'">
    ... do stuff here
</Target>
```

**Comment by jorgemmsilva** [comment]
Right now we ended up copying the "CollectPackageFiles" Target from:
`..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets` and overwriting it:

```
<Target Name="CollectPackageFiles">
	<Message Text="$(MSBuildProjectName) -> $([System.IO.Path]::GetFullPath($(PackageLocation)))" Importance="High" />
	<ItemGroup>
		<_AllPackageFiles Include="$(PackageLocation)\**" />
	</ItemGroup>
	... do stuff here..
</Target>
```

However this is not optimal. Since if there is an update on that package we have to manually check and update it on our project

**Comment by MikkelHegn** [comment]
Closing as there are no outstanding questions.
