### ISSUE TITLE
project cannot build given the current state of the project

### ISSUE THREAD

**Issue by AndyPook** [Azure/service-fabric-issues#334]
Copied from https://github.com/Azure/service-fabric/issues/5

When trying to Publish an app to ASF I infrequently get the error "This project cannot build given the current state of the project". There seems to be no reliable way of reproducing the problem that I have discovered. It just seems that VS gets into some state that cannot be recovered from within VS.

Simply rebuilding; closing/reopening the sln; stop/starting VS etc does not help.

The only "fix" I have found is

stop VS
deleting the Package folder
restart VS
manually restore packages (even though this is prompted for at sln load)
rebuild all
Only then will publish get passed the 'GetApplicationExistence' stage
VS2017 15.2 (26430.12)
SF Tools 1.6.20170504.1
MS ASF 5.6.210.9494
MS ASF SDK 2.6.210.9494

1>------ Build started: Project: MyProject, Configuration: Debug x64 ------
2>------ Publish started: Project: MyProject, Configuration: Debug x64 ------
2>Started executing script 'GetApplicationExistence'.
-------- Package started: Project: MyProject, Configuration: Debug x64 ------
2>Finished executing script 'GetApplicationExistence'.
2>Time elapsed: 00:00:05.7293281
2>This project cannot build given the current state of the project.
========== Build: 1 succeeded, 0 failed, 24 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by ravipal** [comment]
@AndyPook Do you still hitting this issue with the latest VS build (15.3)? If so, can you please collect the detailed build log and send it me (ravipal@microsoft.com)?

**Comment by AndyPook** [comment]
15.3 is still in preview so not something I can use for this.

I am currently using 15.2 (26430.16) and can report that I have not seen
this issue for a while. Feel free to close. I will re-open if it reoccurs.

**Comment by gorygregory** [comment]
Hi, this is still occurring sporadically on VS 2015 ver 14.0.25431.01 Update 3 and SF version 5.7. I have not found a reliable way to fix, it appears to be some combination of restarting VS, resetting the local cluster, reinstalling packages and restarting my development environment.

How do I collect build logs to send you?

**Comment by ravipal** [comment]
I mean build output.

Set 'MSBuild project build output verbosity' to 'Detailed' in Tools->Options->Projects and Solutions -> Build and Run. Then copy the logs from output window.

**Comment by gorygregory** [comment]
Attached file: 
[build_log.txt](https://github.com/Azure/service-fabric-issues/files/1308044/build_log.txt)

**Comment by gorygregory** [comment]
Any luck? This is still happening..

**Comment by ravipal** [comment]
Thanks for sharing the log. Will investigate and get back to you.
