### ISSUE TITLE
Cannot run a simple application in service fabric (used to work)

### ISSUE THREAD

**Issue by Jose-CF** [Azure/service-fabric-issues#336]
I create a really simple servicefabric application in .NET 4.6.2 with target platform x64. I do not have any external dependencies other than ServiceFabric as it is a toy example. I insist, the target platform is x64.

I build my application and I check the resulting assemblies `GetAssemblyName()` and check the processor architecture in all of them is x64. Fine.

Install it in the cluster as usual, but it fails to start.
I double check to create the service manually by logging into the VM.
Always get this exception:
![image](https://user-images.githubusercontent.com/24405049/27821498-a9b11a56-60cc-11e7-837d-23b103ebc1d8.png)

I tried different versions of the nuget packages of ServiceFabric. No luck either.

In the past my applications were working normally in ServiceFabric. I have an application that installed some time ago and keeps working fine. That application is also using the same version of ServiceFabric assemblies. Now I cannot run any new application. But I am not sure why.

I know so many related issues to BadImageException are solved by setting the platform to x64. But I insist, all the assemblies are x64.

Any ideas what might be wrong? I insist again, already checked platform is x64.

**Comment by MikkelHegn** [comment]
Closing as this got very old. Please reopen if this is still relevant. Thanks.
