### ISSUE TITLE
Resolving partition keys in Service Fabric + API Management integration is sad

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#337]
I know this probably falls into the API Management teams backlog, but seeing as @vturecek wrote the docs, I'm pinning it on him.

>The back-end policy computes a partition key within that range by converting the id value provided in the URL request path to a 64-bit integer, although any algorithm can be used here to compute the partition key.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-overview#send-traffic-to-multiple-stateful-services

Sounds good except,

**Repro**
```
<policies>
  <inbound>
    <base/>
    <set-backend-service sf-partition-key="@{
                         var md5 = new MD5CryptoServiceProvider();
                         var value = context.Request.MatchedParameters["key"];
                         var hash = md5.ComputeHash(Encoding.ASCII.GetBytes(value));
                         var key = BitConverter.ToInt64(hash, 0);
                         return key;
                         }"
                         backend-id="servicefabric"
                         sf-service-instance-name="fabric:/Reactor/default/WhereService"
                         sf-resolve-condition="@((int)context.Response.StatusCode != 200)"/>
  </inbound>
  <backend>
    <base/>
  </backend>
  <outbound>
    <base/>
  </outbound>
</policies>
```

**Expected**
`key` is resolved as a Int64.

**Actual**
`Error in element 'set-backend-service' on line 4, column 10: Usage of type 'System.BitConverter' is not supported within expressions`

Any chance of the Service Fabric team bugging the ApiM team and getting a solution for resolving partition keys from parameters?

(Apart from that, and the non-ARM deployment, it's a pretty awesome integration to have going!)

Kind regards,
Nick

**Comment by NickDarvey** [comment]
Well'p ILSpying into `System` and I realized I could just do my own `BitConverter.ToInt64`.

```
<policies>
    <inbound>
        <base/>
        <set-backend-service sf-resolve-condition="@((int)context.Response.StatusCode != 204)" sf-service-instance-name="fabric:/Reactor/default/ScheduledFiltersService" backend-id="servicefabric" sf-partition-key="@{
                var md5 = MD5.Create();
                var x = context.Request.MatchedParameters["key"];
                var value = md5.ComputeHash(Encoding.ASCII.GetBytes(x));
                int num = (int)value[0] | (int)value[1] << 8 | (int)value[2] << 16 | (int)value[3] << 24;
                int num2 = (int)value[4] | (int)value[5] << 8 | (int)value[6] << 16 | (int)value[7] << 24;
                return (long)((ulong)num | (ulong)((ulong)((long)num2) << 32));
                }"/>
    </inbound>
    <backend>
        <base/>
    </backend>
    <outbound>
        <base/>
    </outbound>
</policies>
```

Fun! Any chance of anything nicer though?

**Comment by vturecek** [comment]
Thanks @NickDarvey <3

APIM supports only a subset of .NET Framework types. Here's a full list of what they support: https://docs.microsoft.com/en-us/azure/api-management/api-management-policy-expressions

Agreed BitConverter would be nice to have for this stuff. I'll check in with them and see what we can do to make this a bit (heh) easier. 

In the meantime, since it looks like you're going for a uniform distribution, you could potentially go for something simpler (and faster) than Crypto MD5, like FNV hash:

    var value = (Encoding.UTF8.GetBytes(context.Request.MatchedParameters["key"]));
    ulong hash = 14695981039346656037;
    for (int i = 0; i < value.Length; ++i)
    {
        hash ^= value[i];
        hash *= 1099511628211;
    }
    return (long)hash;

Btw, glad you like the integration overall. Better ARM support for setting up the SF back-end in APIM is on the way.

**Comment by NickDarvey** [comment]
That's much better, it works well! Thank you so much @vturecek.
For anyone else trying to do this, make sure you stick it in an Azure API Management 'property' so you can use it in all of your operations.

e.g. Create a property like:
```
name: Partitioning_FnvHash_accountId
value: @{ const ulong FnvPrime = 1099511628211; const ulong FnvOffsetBasis = 14695981039346656037; var data = Encoding.UTF8.GetBytes(context.Request.MatchedParameters[&quot;accountId&quot;]); var hash = FnvOffsetBasis; for (int i = 0; i &lt; data.Length; ++i) { hash ^= data[i]; hash *= FnvPrime; } return (long)hash; }
```
and use it in a policy, like:
```
<set-backend-service sf-partition-key="{{Partitioning_FnvHash_accountId}}"
                               backend-id="servicefabric"
                               sf-service-instance-name="{{Instance}}/ScheduleService"
                               sf-resolve-condition="@((int)context.Response.StatusCode / 100 != 2 )"/>
```

==================================
As an aside,

> a bit (heh) easier

you're killing me.

**Comment by NickDarvey** [comment]
`BitConverter` is now supported in API Management.
