### ISSUE TITLE
[Question] Can we disable running of AppManifestCleanupUtil.exe when building under Vs2017?

### ISSUE THREAD

**Issue by anandvadul** [Azure/service-fabric-issues#338]
I am building the SF App in VS2017 in a lock down environment, Our developer environment does not allow temp exes with arbitrary names from running.  

While building in such an environment, I get the following error on VS 2017

`Error	MSB3073	The command ""C:\Program Files\Microsoft SDKs\Service Fabric\\Tools\AppManifestCleanupUtil\AppManifestCleanupUtil.exe" /amp:"C:\[PathToApplication]\ApplicationPackageRoot\ApplicationManifest.xml" /smpl:"C:\[PathToService1]\PackageRoot\ServiceManifest.xml;C:\[PathToService2]\ServiceManifest.xml;C:\[PathToService3]\PackageRoot\ServiceManifest.xml" /appparamfiles:"C:\[PathToApplication]\ApplicationParameters\Cloud.xml;C:\[PathToApplication]\ApplicationParameters\Local.1Node.xml;C:\[PathToApplication]\ApplicationParameters\Local.5Node.xml"" exited with code 1.	PaceSFApplication	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Service Fabric Tools\Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.targets`

On the executable watching our directories, I get: blocked an attempt by cmd.exe to run the script tmpd7b80cf40b2d45129f53f083df46fe20.exec.cmd because the file is not approved

The file being tried to execute is : 
`c:\users\[El Monte]\appdata\local\temp\tmpd7b80cf40b2d45129f53f083df46fe20.exec.cmd
`
Since this file name changes per build, it is looked at suspiciously as a virus and blocked (rightly so)

When I run the executable AppManifestCleanupUtil.exe in the Developer Command Prompt for VS2017, the execution is successful. 

Is it possible to bypass this step in the build, so I can put this in as a post build command?
Please let us know if this is possible.

**Comment by anandvadul** [comment]
Update on the issue: 

I see the file: 

'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Service Fabric Tools\Microsoft.VisualStudio.Azure.Fabric.ApplicationProject'

Has the following line :
 
`<Exec Condition="Exists('$(_ServiceFabricAppManifestCleanupUtil)')"
          Command="&quot;$(_ServiceFabricAppManifestCleanupUtil)&quot; /amp:&quot;$(MSBuildProjectDirectory)\$(ApplicationManifestFilePath)&quot; /smpl:&quot;@(_ServiceManifestFullPath, ';')&quot; $(ApplicationParametersFilesArg)" WorkingDirectory="$(MSBuildProjectDirectory)" />`

Commenting this and saving the file should make the issue go away - will update once I can override and test.

**Comment by masnider** [comment]
I actually think we fixed this recently. @dbreshears can confirm/deny :)

**Comment by dbreshears** [comment]
@anandvadul .   Yes, recently we allowed turning off some of these utilities that update the manifests.  Please see https://github.com/Azure/service-fabric-issues/issues/53 and see if that helps

**Comment by dbreshears** [comment]
Closing, as this is addressed in  tooling > 1.7
