### ISSUE TITLE
[Question] Recommendations on running Service Fabric on local dev box without Admin access

### ISSUE THREAD

**Issue by ghost** [Azure/service-fabric-issues#340]
Need advice on how to run Service Fabric as a non-admin.

We have a lock down environment in dev and I prefer not to go to admins every time I need something changed in SF. 

I had managed to set up a single node but it has been brought down due to a reboot. 

I have 2 questions : 
1. How to I run service fabric as a regular user so that I don't need to beg the Admin to start/stop/reset 
2. Where do I see what happened to my cluster (Searched for the logs in %appdata% and in the folder but cant find them) 

Any advice is appreciated.

**Comment by anandvadul** [comment]
Update:
I see the logs in `c:\C:\SfDevCluster\Log`
[Log.zip](https://github.com/Azure/service-fabric-issues/files/1128715/Log.zip)
  But do not see any issues there - is there a specific log that is not in the crash dump that could lead me to the answer? I have attached my Dev cluster log here.

Please guide.

**Comment by masnider** [comment]
Hm - SF itself doesn't run as admin and doesn't require those permissions. Are you talking specifically about setup/installation?

**Comment by VipulM-MSFT** [comment]
@anandvadul - can you clarify the issue? Is this about installing / updating when we release a new version?

**Comment by anandvadul** [comment]
@VipulM-MSFT Yes, This is about enabling a non-admin on a machine to be able to install/update when a new version is released. Is this possible to not need the admin on new version upgrades?

**Comment by VipulM-MSFT** [comment]
This issue was not followed up - but it is not possible to update Service Fabric version on the local development environment without admin access. I will be closing the issue based on this being the general question for which the answer was provided.
