### ISSUE TITLE
Can't debug on local host FabricElementAlreadyExistsException  - VS2017 and SF: 5.6.220.9494 

### ISSUE THREAD

**Issue by anandvadul** [Azure/service-fabric-issues#342]
I am able to publish successfully using visual studio 2017 to my local DEV cluster.
This is a single node running service fabric : 5.6.220.9494 

However, I am not able to debug using Visual Studio. 
When I try to debug(F5), The deployer sees the application already deployed, throws a 'FabricElementAlreadyExistsException' successfully undeploys but does not go and deploy again - My Service Fabric Tools window output is as below: 

`         Started executing script Publish-NewServiceFabricApplication. Creating application
New-ServiceFabricApplication : Application already exists
At C:\Program Files\Microsoft SDKs\Service 
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:279 char:9
+         New-ServiceFabricApplication -ApplicationName $ApplicationName -Applicat 
~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [New-ServiceFabricApplication], FabricElementAlreadyExistsException
    + FullyQualifiedErrorId : CreateApplicationInstanceErrorId,Microsoft.ServiceFabric.Powershell.NewApplication
 
Finished executing script Publish-NewServiceFabricApplication.
Time elapsed: 00:00:02.7695740
Unregister application type succeeded.
Finished executing script UnregisterApplicationType.
Time elapsed: 00:00:02.5812582`

How do I debug the application? Is there a workaround for this?

Please help.

**Comment by cheesemacfly** [comment]
Had this issue as well using a guest executable. Deleting the application and unprovisioning the type from the local manager interface fixed it for me.

**Comment by MikkelHegn** [comment]
@anandvadul - sorry for the long delay. I'm closing this for now, please reopen if this still needs attention. Thanks.

**Comment by anandvadul** [comment]
@MikkelHegn , no worries, I still have this issue but now it is more of ease of use with VS. I am using the workaround given by @cheesemacfly but would love to see a more seamless solution.
