### ISSUE TITLE
ServiceRemotingDispatcher cannot be instantiated in tests

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#345]
Seems like the initialization of perf counters fails under certain conditions in tests. Since it occurs in a static ctor, there's no way to circumvent it.

Would it be possible to add an option to disable them?

SDK Version:  2.6.220

Stack Trace:
```
KERNELBASE!RaiseFailFastException+0x74
FabricCommon!Common::Assert::DoFailFast+0xb2
FabricCommon!Common::Assert::CodingError+0x59
FabricCommon!Common::PerformanceProviderDefinition::AddCounterSetDefinition+0x90
FabricCommon!FabricPerfCounterCreateCounterSet+0x2ec
DomainBoundILStubClass.IL_STUB_PInvoke(IntPtr, IntPtr ByRef)+0x8d
System.Fabric.Interop.Utility+<>c__DisplayClass25_0.<WrapNativeSyncInvoke>b__0()+0xf
System.Fabric.Interop.Utility.WrapNativeSyncInvoke[[System.__Canon, mscorlib]](System.Func`1<System.__Canon>, System.String, System.String)+0x1d
System.Fabric.Interop.Utility.RunInMTA(System.Action)+0x2e
System.Fabric.Common.FabricPerformanceCounterInterop.CreateCounterSet(System.Fabric.Common.FabricPerformanceCounterSetDefinition, System.Collections.Generic.IEnumerable`1<System.Fabric.Common.FabricPerformanceCounterDefinition>)+0x30b
System.Fabric.Common.FabricPerformanceCounterSet..ctor(System.Fabric.Common.FabricPerformanceCounterSetDefinition, System.Collections.Generic.IEnumerable`1<System.Fabric.Common.FabricPerformanceCounterDefinition>)+0x108
Microsoft.ServiceFabric.Services.Remoting.Diagnostic.ServicePerformanceCounterProvider.CreateCounterSet(System.Collections.Generic.Dictionary`2<System.Fabric.Common.FabricPerformanceCounterSetDefinition,System.Collections.Generic.IEnumerable`1<System.Fabric.Common.FabricPerformanceCounterDefinition>>, System.String)+0xc1
Microsoft.ServiceFabric.Services.Remoting.Diagnostic.ServicePerformanceCounterProvider.InitializeAvailableCounterTypes()+0x4a
Microsoft.ServiceFabric.Services.Remoting.Diagnostic.ServicePerformanceCounterProvider..cctor()+0x35
Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingDispatcher..ctor(System.Fabric.ServiceContext, Microsoft.ServiceFabric.Services.Remoting.IService)+0x1c2
```

**Comment by dkkapur** [comment]
@harahma @abhishekram have you seen this behavior before? 
@aelij thanks for raising this, we're going to investigate the change and keep you posted with updates.

**Comment by suchiagicha** [comment]
@aelij 

Could you share the dump for the process?

**Comment by aelij** [comment]
@suchiagicha Can you please send me your email (mine is public on my profile)? I found an old dump. Note I'm no longer actively working on this project, and we've employed a workaround so it doesn't happen.

**Comment by suchiagicha** [comment]
@aelij 
You could attach files here by dragging and dropping.  Try creating zip file and then upload here itself.
Also what workaround you are using?

**Comment by aelij** [comment]
@suchiagicha The dumps can contain sensitive information, so I don’t want it public. The workaround was to copy the implementation of `ServiceRemotingDispatcher` into our test framework (without the perf counters, of course).

**Comment by suchiagicha** [comment]
@aelij 

You can try sending the dump to this suchia@microsoft.com and make sure to rename the extension of dump file to zip file otherwise mail server rejects the attachment.

**Comment by suchiagicha** [comment]
@aelij 

Seeing the dump ,looks like you are Fabric Runtime of version 5.5.216.0 and Microsoft.ServiceFabric.Services version is 5.6 , which is not a compatible version. Runtime version should always be higher or same with sdk version. Please upgrade your FabricRuntime and it should then work.

**Comment by aelij** [comment]
@suchiagicha Thanks! I'm pretty sure we did upgrade the runtime on the build server (the dump was from my local machine) and we still experienced this issue. But as I said I'm no longer working on this project, so I can't test it. So I'm closing this issue for now. Will reopen if I encounter it again.
