### ISSUE TITLE
API Management returns 400 for PUT requests with Service Fabric Backends

### ISSUE THREAD

**Issue by pchamakura** [Azure/service-fabric-issues#346]
I have an ASP.NET Web API that exposes a rest endpoint through NancyFX. These APIs are deployed to Service Fabric Cluster. 

When I consume these APIs directly via Reverse Proxy on the SF cluster, they work fine. But when I try them through API management, I can see that that API management retries the APIs few time before sending the response back to the client. 

PUT requests especially fail with 400 error. 

Orignially, I thought the problem is with NancyFX and spent tons of time troubleshooting the issue. But i've realized the problem is with the way services are configured in the API Management. Since these endpoints work just fine when I try the endpoint directly through the SF Reverse Proxy, the problem has to be in API Management configuration. Most of GET requests, send 200 (OK) back to the client. Some of the PUT requests send 202 (Accepted) status code back to the client. API Management somehow doesn't like this response and sends few more requests (to the same node) to resolve. At this point, the server returns 400 which is sent back to the client. It shows an error when there isn't one. 

Here's how I've configured the inbound policy on the API Management. 
    
```
<inbound>
        <base/>
        <set-backend-service backend-id="servicefabric" sf-service-instance-name="fabric:/reztech.sampleapp/sampleservice" sf-resolve-condition="@((int)context.Response.StatusCode != 200)"/>    
</inbound>
```

After debugging it extensively, I've realized there are two issues.

- API Management doesn't like JSON object in the PUT request. I've sent Content-Type="application/json" and it still doesn't like it. It sends multiple requests to the SF backend and sends a 400 response back to the client. If I send the same parameters as a query string, it works. The same JSON objects work in the body of the POST request but not PUT. Am I missing something here?

- Since each endpoint can return different status code depending upon the success/failure of the operation, what is the recommended value for 'sf-resolve-condition'? If I check for content.Response.StatusCode != 200, then any response status code other than 200 triggers mulitple requests to the SF backend and ulimately end up sending a bad request error.

What am I missing here? 

If I change the request to this, it works but I would like to have a more elegant solution than hard coding each and every expected response code. The API returns 400 error code when there is something wrong with the request processing. When it returns 400, I want API management to just sent the response back to the client. I don't want it to try it multiple times to get a 200 response.
```
<inbound>
        <base/>
        <set-backend-service backend-id="servicefabric" sf-service-instance-name="fabric:/reztech.sampleapp/sampleservice" sf-resolve-condition="@(((int)context.Response.StatusCode != 200)&&((int)context.Response.StatusCode != 400))"/>
</inbound>
```

@vturecek Any insight here?

**Comment by vturecek** [comment]
There isn't really a recommended value for `sf-resolve-condition` - each application is different. This is where you get to decide when you want to re-resolve. 

Keep in mind, resolve means "the service has moved, get a new endpoint and try again." HTTP status codes usually don't mean the service has a new endpoint, in fact, this is only true in certain cases with certain web servers.

At the moment, there isn't a default set of rules for re-resolve, but we are adding some basic rules for lower-level network failures that are indicative of an endpoint that has moved to a different node, such as socket connection failures. 

For HTTP status codes, you typically don't want to retry on statuses that you know are not transient, such as a 400 (by transient I mean it might succeed next time you try - a 400 will always be a 400 given the same request). In this case, your `sf-resolve-condition` would include those status codes you don't want to retry on.

@maksimkim might have more suggestions for you. Also, any idea what's going on with the PUT request with a JSON payload?

**Comment by maksimkim** [comment]
@pchamakura, APIM doesn't have any special handling of payload and/or Content-Type header by default. Can you try to use APIM inspector or Azure Monitor to identify whether it's APIM or backend who responds 400.

**Comment by pchamakura** [comment]
@vturecek By that defination, we can just have the resolve condition set to 404, since that indicates the APIM can't find the backend service. Any other status code like 400, 401, 500 are not transient. There is no use in retrying when API returns those status codes. I think setting the resolve condition to 404 is better than saying !=400, !=401, !=500 etc., 

Basically,  the below condition is better than
```
<inbound>
        <base/>
        <set-backend-service backend-id="servicefabric" sf-service-instance-name="fabric:/reztech.sampleapp/sampleservice" sf-resolve-condition="@((int)context.Response.StatusCode == 404)"/>    
</inbound>
```
this one. 
```
<inbound>
        <base/>
        <set-backend-service backend-id="servicefabric" sf-service-instance-name="fabric:/reztech.sampleapp/sampleservice" sf-resolve-condition="@(((int)context.Response.StatusCode != 200)&&((int)context.Response.StatusCode != 400)&&((int)context.Response.StatusCode != 401)&&((int)context.Response.StatusCode != 500))"/>
</inbound>
```
What do you think?

@maksimkim 

Here's what's happening with PUT request.

1) Going through Reverse Proxy on the Service Fabric Cluster with JSON payload works
```
PUT /reztech.sampleapp/sampleservice/samplecontroller/sampleaction HTTP/1.1
Host: samplecluster.westus.cloudapp.azure.com:19008
{ "param1": "291", "param2": "1"}
```
2) Going through API Management with JSON payload gives 400 error
```
PUT /webapi/samplecontroller/sampleaction HTTP/1.1
Host: sampleapi.azure-api.net
{ "param1": "291", "param2": "1"}
```
3) Going through API Management with parameters in query string, works
```
PUT /webapi/samplecontroller/sampleaction?param1=291&amp;param2=1 HTTP/1.1
Host: sampleapi.azure-api.net
```

The really strange part is the second request. Everything else is the same.

It can't be the code since going through Reverse Proxy works just fine. 

Here's the 400 error that shows up in our logs. 
![capture](https://user-images.githubusercontent.com/5086916/28110960-c466069a-66a8-11e7-8bc4-781b06b30b17.PNG)

Here's the trace of the request from APIM.

![capture](https://user-images.githubusercontent.com/5086916/28111200-8eb6ddb6-66a9-11e7-9d78-3bd69836ee0f.PNG)

For some reason, APIM can't find the backend service when the JSON payload is sent in the body of the PUT request.

**Comment by pchamakura** [comment]
@maksimkim I must add that the backend returns 400 to the APIM but APIM returns 500 internal server to the client. 

The backend API is developed using Nancy FX 2.0. 

Here's the method on the API module

```
            Put("/sampleaction", async (args, ctor) =>
            {
                try
                {
                    var _sampleModel= this.Bind<SampleModel>();
                    var validationResult = this.Validate(_sampleModel);

                    if (!validationResult.IsValid)
                    {
                        return Negotiate.WithModel(validationResult).WithStatusCode(HttpStatusCode.BadRequest);
                    }

                    await _sampleService.SampleMethod(_sampleModel);
                    return HttpStatusCode.OK;
                }
                catch (ModelBindingException ex)
                {
                    return await ex.GetModelBindingException(_logger, Negotiate);
                }
                catch (Exception ex)
                {
                    return ex.GetGeneralServiceException(_logger, Negotiate);
                }
            });
```

Nothing out of the ordinary here. JSON payload on the POST request works just fine. It's just the PUT request that's causing the issue.

**Comment by maksimkim** [comment]
@pchamakura by default in order to guarantee maximum throughput APIM don't buffer request payload but directly streams it from the client all the way to the backend which means that once request payload is sent it's not retryable any more. So this is what happens I believe (you should be able to confirm it with trace):

Attempt #1: APIM sends request to selected instance and gets 400 back. Request payload is gone
Re-resolve condition evaluation:  True
Attempt #2:  APIM sends request to another instance with non-zero Content-Length but empty response and immediately gets error "Cannot close stream until all bytes are written".
.......

It doesn't explain why you get 400 on the very first attempt but reveals an important limitation of APIM-SF integration that it doesn't work for requests with payload when retry happens after payload already sent. I'll discuss with @vturecek  how reverse proxy behaves in such cases and see how we can support it in APIM in one of next APIM releases.

Note that in general APIM allows retry for request with payload using combination of retry/set-variable/set-body policies. It just can't be combined with service fabric re-resolution logic.

Regarding your thoughts on proper retry condition, I doubt 404 is a good idea. APIM gets 404 not when it can't find backend service but when specified backend service replies 404 which means it can't find specified resource (whatever it means for a given backend). Imagine http restful api that allows to address entities by ids (/users/{uid}). Providing nonexisting user id results in 404 but it doesn't mean service itself doesn't exist. I would recommend you to start from retrying on transport level connectivity errors only:  @(context.LastError?.Reason == "BackendConnectionFailure")
Later if you find it not sufficient you'll be able to add more conditions.

**Comment by pchamakura** [comment]
@maksimkim Thank you very much for explaining how APIM works with Service Fabric. It's clear why I'm getting the error. But that is a deal breaker for applications with Service Fabric backends since all the retries trigger 500 Internal Server Error, if the payload is not sent again. Essentially, there is no use in trying. 

Here's how I got to the bottom of it. 

I'm working on an eCommerce application that needs to set a flag on an entity with a PUT request. 

If the flag is not set, backend sets the flag, returns 200 status code.
If the flag is already set, it returns a 400 Bad Request and a response JSON that contains error message.

If the parameters are sent in a query string, APIM gets 400, then it retries few times with the same URL. Since all the parameters are available in the URL, the backend responds with the same 400 error each time. After the last try, it sends the 400 back to the client. Expected Result.

But if the parameters are sent in the body of the request as a JSON payload, APIM gets a 400 response from the backend first time. It tries few more times but this time, the JSON payload is not sent. That triggers a 500 response from the backend which is sent to the client.  Not an Expected Result.

I've also tried another scenario, that returns 200 when the flag is not set. In this case, backend processes the request, sets the status, returns 200 to APIM which it forwards it to the client. In this case, since the response from backend is 200, APIM sends 200 to the client. No retries are required and no errors are reported.

One way to get around it to set the resolve condition !=200 and !=400 or @(context.LastError?.Reason == "BackendConnectionFailure"). I'll have to try the second condition and get back to you on that. Thanks for the info. 

I've resolved the issue temporarily but it does needs to be fixed at some point in the future. What if the service is not running on all the nodes? When APIM sends the request to another node to resolve, then all the PUT and POST requests will fail with 500 Internal Server error because it doesn't send JSON payload in the subsequent attempts. To avoid such a situation, I'll have to deploy all the services on all the nodes of the cluster.  There will be lot of services sitting idle for most of their time. Not an ideal situation.

Now that I think of it, if the resolve condition is not met on first attempt, the client gets 500 Internal Server Error , no matter what the actual response from the backend is. 

Let's say resolve condition is set to !=200. Let's say the backend processes the request and sends 404 or something similar to APIM. Since this doesn't meet the resolve condition, APIM will retry. When APIM retries it, it'll get 500 from the backend (since there is no json payload) which will be sent to the client.

**Comment by pchamakura** [comment]
@vturecek - @maksimkim was able to help me to get to the bottom of the issue. It happens because APIM doesn't store JSON payloads. So when resolve condition is not met, all subsequent requests are sent with non-zero Content-Length header with no JSON payload in the body of the request. 

This triggers "Cannot close stream until all bytes are written" from the backend with a 500 status code.

Temporary solution is to deploy all the services on all the nodes and make sure to have a resolve condition that covers all transient status codes.

Thanks a lot for your help!

**Comment by maksimkim** [comment]
@pchamakura Great you were able to workaround it.
However I want to note one more time that sf-resolve-condition only purpose is to specify condition that indicates SF instance is gone. So specifying it in terms of status codes might not be a best thing. Unless you know that if service is gone underlying infrastructure will return that specific status code back.

If on the other hand you need some retry specific to you application (e.g. retry on 500 cause it might indicate transient issue calling database) which don't require calling different SF instance then it's out of scope of SF integration feature and can be achieved using combination of retry/set-body policies.

**Comment by masnider** [comment]
@pchamakura - hi there. If things are working for you and there's no further questions, do you think we can close this issue down? Let us know if you need anything else here. If we don't hear back from you in a week or so we'll consider your problem solved and close the issue down, but if you figure out later that you still have more questions you can just reopen this or create a new issue. Thanks for working through this with @maksimkim and @vturecek

**Comment by pchamakura** [comment]
Thank you @masnider . This issue is resolved and I'm closing it.
