### ISSUE TITLE
Register-ServiceFabricApplicationType : Operation timed out

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#347]
Recently we started to observe timeout for Register-ServiceFabricApplicationType frequently for our daily deployment, which has never happened before. There is no change to the cluster (except SF auto-update), nor change to our SF app packages (except small changes in app code). The VMs are not busy either.

[09:35:53]	Register-ServiceFabricApplicationType : Operation timed out.
[09:35:53]	At C:\Program Files\Microsoft SDKs\Service
[09:35:53]	Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:251 char:9
[09:35:53]	+ Register-ServiceFabricApplicationType -ApplicationPathInImage ...
[09:35:53]	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[09:35:53]	+ CategoryInfo : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic
[09:35:53]	eFabricApplicationType], TimeoutException
[09:35:53]	+ FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp
[09:35:53]	e

What can be the cause?

**Comment by oanapl** [comment]
The default timeout for register operation is 1 minute. If this is not sufficient, you can pass in a bigger timeout. Read more about [register application type](https://docs.microsoft.com/azure/service-fabric/service-fabric-deploy-remove-applications#register-the-application-package).
The same article has a section about [troubleshooting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-remove-applications#troubleshooting) for large packages or packages with many files, where copy package or register application type time out. The suggestions are to either use a bigger timeout value, use -Async so the command returns as soon as the cluster receives it, then use queries to see when it's done and/or compress the application package.

**Comment by qrli** [comment]
The SDK cmdlet (ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1) has no parameter to change timeout for register application type. So I had to modify the SDK code on every machine. :-( After that, it is working.

**Comment by masnider** [comment]
@dbreshears - can we consider this enhancement to the tooling? Exposing more of these configuration options? Or is it already possible somehow?

**Comment by dbreshears** [comment]
@masnider.  Not currently possible.   The Publish-NewServiceFabricApplication.ps1 deployed as part of the SDK and would need to be updated to include a $RegisterApplicationTimeoutSec

**Comment by apryiomka** [comment]
I started to experience the same issue:
```
PS C:\WINDOWS\system32> Register-ServiceFabricApplicationType -ApplicationPathInImageStore MyApp -Debug -Verbose
VERBOSE: System.TimeoutException: Operation timed out. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BFF
   at System.Fabric.Interop.NativeClient.IFabricApplicationManagementClient9.EndProvisionApplicationType2(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
Register-ServiceFabricApplicationType : Operation timed out.
At line:1 char:1
+ Register-ServiceFabricApplicationType -ApplicationPathInImageStore Pr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-ServiceFabricApplicationType], Ti 
   meoutException
    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationType
```

**Comment by apryiomka** [comment]
Does anyone have any mitigation steps? Increasing timeout to 600 will just delay the timeout by 10 minutes with the same ultimate result.

**Comment by oanapl** [comment]
@apryiomka , how big is your application package? Are you applying compression?
See some [troubleshooting tips](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-remove-applications#troubleshooting) for dealing with timeouts in copy and register commands.

**Comment by apryiomka** [comment]
@oanapl  about 44MB. No, i do not apply any compression since i need to be able to debug my application. Debugging from VS2017 doesn't work, publishing from VS2017 doesn't work, publishing with PowerShelll built package doesn't work since all three call Register-ServiceFabricApplicationType and all fail with the same error. Also, this is my local cluster and since when the package size should have any limit?

**Comment by oanapl** [comment]
@apryiomka , 44 MB is a pretty small package, it should not hit any timeouts on register. Register should finish in under the default timeout. There must be some other issue going on. 

Have you tried to pass -Async in your register command, then use Get-ServiceFabricApplicationType to check the progress?

What kind of local cluster is this, 5 nodes or 1 node? Is your cluster healthy? Are all the system services healthy? You can take a look in Service Fabric Explorer or through Powershell. 

```powershell
Get-ServiceFabricApplicationHealth fabric:/System
Get-ServiceFabricClusterHealth
```

What is the cluster's [image store connection string](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-image-store-connection-string)?

Re. your last question, I didn't say that the package should have a limit. I asked to see whether it was a big package (order of GB).

**Comment by apryiomka** [comment]
Ok, i was able to find the root cause of the issue with some experimentation. It still doesn't explain why this fails, but at least i now know the cause. It is the file ownership that causes the registration to fail / timeout. Steps to reproduce:

1. Go to the package folder
2. Right click on a file, pick File Ownership
3. Change from Personal to Work
4. Enjoy the timeouts...

This is totally unexpected behavior and doesn't make any sense. What am i missing here? Is it a bug in SF?

**Comment by oanapl** [comment]
@apryiomka, I am not familiar with the File Ownership you mentioned. Can you give me more info about it, as well as about "Personal" and "Work"? And can you please add details about your OS?

**Comment by apryiomka** [comment]
@oanapl please follow the steps to reproduce the issue, they are fairly straightforward. File ownership is a windows "feature". If the package contain any files that are not personal, it fails to deploy to the cluster.
![fileownership](https://user-images.githubusercontent.com/11861671/34054582-8160ff8c-e180-11e7-925b-c9337c522679.png)

**Comment by oanapl** [comment]
@apryiomka, I believe you are using [Windows Information Protection](https://support.microsoft.com/en-za/help/4012985/windows-10-manage-windows-information-protection-work-personal-files), which is feature that organizations use to protect work data by encrypting it. This feature is an off-by-default enterprise feature. We don't have it enabled at Microsoft, so it's not easy for me to repro.

Service Fabric is not integrated with WIP, and we never tested this scenario. 
The timeout may come from us dropping messages as we don't believe them to be valid. Since messages are dropped, no reply comes back to the user, do you don't get any information about what may be wrong.

If you want us to continue investigation, you can open a support case so we can look more into it. But most probably this this scenario is unsupported and not a high priority for us.

**Comment by codeConcussion** [comment]
Was something actually done to fix this issue? As I see it, the scripts **Publish-NewServiceFabricApplication.ps1** and **Publish-UpgradedServiceFabricApplication.ps1** both call **Register-ServiceFabricApplicationType** but neither of them specify a timeout or have a parameter that allows you to specify the timeout. Can you tell us what was done to "fix" this?

**Comment by amanbha** [comment]
@codeConcussion The fix will be available in our next 6.2 release. Following timeout parameters are introduced in these 2 scripts, also the Register-ServiceFabricApplicationType is now called in async mode and then status is checked after making the register call.

PARAMETER RegisterApplicationTypeTimeoutSec
    Timeout in seconds for registering application type. Default is 600 seconds.

    .PARAMETER UnregisterApplicationTypeTimeoutSec
    Timeout in seconds for unregistering application type. Default is 600 seconds.

**Comment by codeConcussion** [comment]
@amanbha That sounds great - thanks for the info!

**Comment by lAnubisl** [comment]
Please don't close this ticket until fix is widely available.

**Comment by leontheprofessional7** [comment]
I got the timeout exception, but for the `New-ServiceFabricApplication`.

Here is the related logs in verbose (The project is 315MB, and the time out thresh hold is 600s):

`Started executing script 'Publish-NewServiceFabricApplication'.
powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command "[void](Connect-ServiceFabricCluster); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Publish-NewServiceFabricApplication -ApplicationPackagePath 'C:\Project\ServiceFabric\ECommerce\ECommerce\pkg\Debug' -ApplicationParameterFilePath 'C:\Project\ServiceFabric\ECommerce\ECommerce\PublishProfiles\..\ApplicationParameters\Local.1Node.xml' -ApplicationParameter @{_WFDebugParams_='[{"""CodePackageName""":"""Code""","""CodePackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64""","""ConfigPackageName""":"""Config""","""ConfigPackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\PackageRoot\\Config""","""DataPackageName""":null,"""DataPackageLinkFolder""":null,"""LockFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_lock.txt""","""WorkingFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog""","""ServiceManifestName""":"""ECommerce.ProductCatalogPkg""","""EntryPointType""":"""Main""","""DebugExePath""":null,"""DebugArguments""":null,"""DebugParametersFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_debug.txt"""},{"""CodePackageName""":"""Code""","""CodePackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64""","""ConfigPackageName""":"""Config""","""ConfigPackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\PackageRoot\\Config""","""DataPackageName""":null,"""DataPackageLinkFolder""":null,"""LockFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_lock.txt""","""WorkingFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API""","""ServiceManifestName""":"""ECommerce.APIPkg""","""EntryPointType""":"""Main""","""DebugExePath""":null,"""DebugArguments""":null,"""DebugParametersFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_debug.txt"""}]'} -Action Create -SkipPackageValidation:$true -ErrorAction Stop"
Creating application...
Finished executing script 'Publish-NewServiceFabricApplication'.
Time elapsed: 00:08:29.1413596
Started executing script 'Publish-NewServiceFabricApplication'.
powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command "[void](Connect-ServiceFabricCluster); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Publish-NewServiceFabricApplication -ApplicationPackagePath 'C:\Project\ServiceFabric\ECommerce\ECommerce\pkg\Debug' -ApplicationParameterFilePath 'C:\Project\ServiceFabric\ECommerce\ECommerce\PublishProfiles\..\ApplicationParameters\Local.1Node.xml' -ApplicationParameter @{_WFDebugParams_='[{"""CodePackageName""":"""Code""","""CodePackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64""","""ConfigPackageName""":"""Config""","""ConfigPackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\PackageRoot\\Config""","""DataPackageName""":null,"""DataPackageLinkFolder""":null,"""LockFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_lock.txt""","""WorkingFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog""","""ServiceManifestName""":"""ECommerce.ProductCatalogPkg""","""EntryPointType""":"""Main""","""DebugExePath""":null,"""DebugArguments""":null,"""DebugParametersFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.ProductCatalog\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_debug.txt"""},{"""CodePackageName""":"""Code""","""CodePackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64""","""ConfigPackageName""":"""Config""","""ConfigPackageLinkFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\PackageRoot\\Config""","""DataPackageName""":null,"""DataPackageLinkFolder""":null,"""LockFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_lock.txt""","""WorkingFolder""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API""","""ServiceManifestName""":"""ECommerce.APIPkg""","""EntryPointType""":"""Main""","""DebugExePath""":null,"""DebugArguments""":null,"""DebugParametersFile""":"""C:\\Project\\ServiceFabric\\ECommerce\\ECommerce.API\\bin\\Debug\\netcoreapp2.0\\win7-x64\\_VS_ServiceFabric_debug.txt"""}]'} -Action Create -SkipPackageValidation:$true -ErrorAction Stop"
Creating application...
VERBOSE: System.TimeoutException: Operation timed out. ---> System.Runtime.InteropServices.COMException: Exception from
 HRESULT: 0x80071BFF

   at 
System.Fabric.Interop.NativeClient.IFabricApplicationManagementClient10.EndCreateApplication(IFabricAsyncOperationConte
xt context)

   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext 
context)

   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean 
expectedCompletedSynchronously)

   --- End of inner exception stack trace ---
New-ServiceFabricApplication : Operation timed out.
At C:\Program Files\Microsoft SDKs\Service 
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:358 char:9
+         New-ServiceFabricApplication -ApplicationName $ApplicationNam ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [New-ServiceFabr 
   icApplication], TimeoutException
    + FullyQualifiedErrorId : CreateApplicationInstanceErrorId,Microsoft.ServiceFabric.Powershell.NewApplication
 
Finished executing script 'Publish-NewServiceFabricApplication'.
Time elapsed: 00:10:07.4933343`

**Comment by oanapl** [comment]
@leontheprofessional7 , since this is something different than the original thread, please open a new issue so we can follow up appropriately. And please specify the version for Service Fabric and tooling.

**Comment by markfields** [comment]
@oanapl - By now we are using WIP at Microsoft, and I just got bit by this.  Any chance the root cause could be addressed so dropping a work-owned file in your project doesn't poison Service Fabric?

**Comment by oanapl** [comment]
When the initial issue was reported, we opened a tracking bug internally to figure it out. We have prioritized this against other asks and we haven't gotten to it, it's also not currently planned to be worked on. That being said, adding @iyyappam , @dragav for any ideas.

**Comment by LastTribunal** [comment]
I had this problem, solved simply by  -CompressPackage when Copy-ServiceFabricApplicationPackage

**Comment by Jayamohananmr-gep** [comment]
@oanapl - I am also facing the same issue. Could you please review logs


Performing 'RegisterAndCreate' action 
December 7th 2019 12:58:01Info
Copying application to image store... 
December 7th 2019 12:58:34Info
Upload to Image Store succeeded 
December 7th 2019 12:58:34Info
Registering application type... 
December 7th 2019 13:00:34Error
Register-ServiceFabricApplicationType : Operation timed out. 
December 7th 2019 13:00:34Error
At C:\Program Files\Microsoft SDKs\Service  
December 7th 2019 13:00:34Error
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:281 char:9 
December 7th 2019 13:00:34Error
+         Register-ServiceFabricApplicationType -ApplicationPathInImage ... 
December 7th 2019 13:00:34Error
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
December 7th 2019 13:00:34Error
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic  
December 7th 2019 13:00:34Error
   eFabricApplicationType], TimeoutException 
December 7th 2019 13:00:34Error
    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp  
December 7th 2019 13:00:34Error
   e 
December 7th 2019 13:00:34Error
 
December 7th 2019 13:00:34Error
Script 'G:\OctopusHome\Work\20191207072749-658452-12856\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 
December 7th 2019 13:00:34Error
Running rollback conventions... 
December 7th 2019 13:00:34Error
Script 'G:\OctopusHome\Work\20191207072749-658452-12856\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 
December 7th 2019 13:00:34Fatal
The remote script failed with exit code 1

**Comment by oanapl** [comment]
@Jayamohananmr-gep, since this thread is old and closed, please open a new one. @iyyappam, FYI
