### ISSUE TITLE
Error MSB3024 Could not copy the file...runtimeconfig.json...because the destination is a folder instead of a file.

### ISSUE THREAD

**Issue by munyirik** [Azure/service-fabric-issues#348]
I added an .net core console app to my service fabric application. When I try to start the app I'm getting the build error below.

Any ideas why this is happening? I don't see any obvious problem in my manifests. Any pointers would be appreciated.

Version in sfproj is 1.6.0.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3024	Could not copy the file "E:\repos\foo\bin\x64\Debug\net461\foo.runtimeconfig.json" to the destination file "E:\repos\foo\ServiceFabricApplication\pkg\Debug\fooPkg\Code\", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles.	ServiceFabricApplication	E:\repos\nupkgs\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets	248

**Comment by MedAnd** [comment]
@munyirik - what happens if you add the below to your *.csproj file:

<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>

**Comment by munyirik** [comment]
The runtimeconfig.json file exists (even without setting GenerateRuntimeConfigurationFiles to true). 
The problem looks like it's within the service fabric application build process. It's trying to copy the file as a folder.

**Comment by MedAnd** [comment]
@munyirik when you say you added a .net core app, you mean a .net core stateful or stateless service? If so, maybe try this workaround: [Upgrade your .Net Core Service Fabric Microservices from VS 2015 to VS 2017](http://www.medic-consulting.com/2017/06/07/Upgrade-your-Net-Core-Service-Fabric-Microservices-from-VS-2015-to-VS-2017/)

**Comment by Vhab** [comment]
The service fabric build thingybob seems to struggle with `Microsoft.NET.Sdk` projects.
We worked around it by using `Microsoft.NET.Sdk.Web` in the .csproj file for now.

**Comment by munyirik** [comment]
Changing to Microsoft.NET.Sdk.Web did the trick. Thanks @Vhab and @MedAnd.

I'll keep this open in case it's a bug and not by design.

**Comment by MedAnd** [comment]
@munyirik glad to hear the workaround resolved your issue... from what I know this is not a supported scenario currently, but hopefully will be addressed in a tooling update... 

original & duplicate issues:

#303
#231

**Comment by MikkelHegn** [comment]
@dbreshears  @ravipal

**Comment by NK-Hertz** [comment]
I had the same, problem after deleting bin and obj folders. It turned out a member of the team created a project referencing another project, using vs2015 and the compiled files + configs were not compatible with vs2017. As mentioned by @MedAnd upgrading your .net core service fabric does the trick, or if you have visual studio 2017, just creating a new project from there and copying the files from the old project to the new one.

**Comment by BigMorty** [comment]
We added .NET Core 2.x templates for stateful, stateless, and actors quite a while ago, so this workaround should no longer be necessary. As of Visual Studio 2019 16.3.6 you will find these templates work with .NET Core 3.0 as well.

**Comment by masnider** [comment]
Closing as this should be resolved at this time. If you are still experiencing issues with 2.x .NET Core, please open another issue with a repro and we can pick up from there.
