### ISSUE TITLE
Statelss actor service VS template

### ISSUE THREAD

**Issue by CassandraDied** [Azure/service-fabric-issues#35]
I can't find a template for such actor. Seems like it is not possible and every actor should have at least one replica?
And I can't find any documentation on the subject. Can we have documentation or template for such actors if their creation is possible?

Generally, I'm asking this because when I change state persistence from StatePersistence.Persisted to StatePersistence.None, it doesn't change anything and the actors still have one replica.

**Comment by vturecek** [comment]
An actor service with just one replica is equivalent to a stateless actor in that there is no state replication or persistence. However, we can't consider actors to be _truly_ stateless because each actor has a unique ID, and therefore actor instances are not interchangeable.
