### ISSUE TITLE
Running a Clean build on .sfproj requires restoring the Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0 package 

### ISSUE THREAD

**Issue by tcarun** [Azure/service-fabric-issues#350]

**Comment by masnider** [comment]
@dbreshears - known?

**Comment by dbreshears** [comment]
@tcarun .  We use the Fabric.MSBuild Nuget package  to invoke targets that update the app and service manifests so  this package is required to build the .sfproj
