### ISSUE TITLE
Unabled to set PackageLocation on the sfproj package for msbuild step.

### ISSUE THREAD

**Issue by tcarun** [Azure/service-fabric-issues#352]
Package is getting written to the default  (projdir)/pkg/(configuration) folder even though a different location was provided in the build step

**Build Step:**

<Target Name="PackageServiceFabric" DependsOnTargets="PackageContainerProjects">  
	<ItemGroup>
			<ServiceFabricProject Include="**\*.sfproj">				
			</ServiceFabricProject>
	</ItemGroup>	
	
	<Message Text="Output LOCATION for project '@(ServiceFabricProject)' is'$(ServiceFabricPackageDir)\%(FileName)'.........."/>
	
	<MSBuild Projects="@(ServiceFabricProject)" Targets="Package"
     Properties="Platform=$(Platform);
     Configuration=$(Configuration);
     DeployOnBuild=True;
     DeployTarget=Package;
     PackageLocation=$(ServiceFabricPackageDir)\%(FileName);
     PackageAsSingleFile=true;">
    </MSBuild>	
  </Target>

**Log:**

Target PackageServiceFabric:
    Output LOCATION for project 'Dex\Containers\DexWebContainer\DexWebContainer\DexWebContainer.sfproj' is'C:\git\cloud\Binaries\x64\Debug\DexWebContainer'..........
    __________________________________________________
    Project "C:\git\cloud\build.proj" is building "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\DexWebContainer.sfproj" (Package target(s)):

    Target CleanApplicationPackage:
        rmdir /Q /S "pkg\Debug"
    Target PackageApplication:
        __________________________________________________
        Project "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\DexWebContainer.sfproj" is building "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\sn5nyyfs.x5b.sfproj" (___ServiceFabric_GetNoneAndContentFiles target(s)):

        Creating directory "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug".
        Copying file from "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\ApplicationPackageRoot\ApplicationManifest.xml" to "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug\ApplicationManifest.xml".
        Creating directory "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug\DexWebPkg\Config".
        Copying file from "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\ApplicationPackageRoot\DexWebPkg\Config\Settings.xml" to "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug\DexWebPkg\Config\Settings.xml".
        Copying file from "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\ApplicationPackageRoot\DexWebPkg\ServiceManifest.xml" to "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug\DexWebPkg\ServiceManifest.xml".
    Target AddCorrelationIds:
        __________________________________________________
        Project "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\DexWebContainer.sfproj" is building "C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\ihb5s2as.2j0.sfproj" (___ServiceFabric_GetProjectGuid target(s)):

    Target CollectPackageFiles:
        DexWebContainer -> C:\git\cloud\Dex\Containers\DexWebContainer\DexWebContainer\pkg\Debug

**Comment by dbreshears** [comment]
@tcarun ,  Can you zip up a small repro project and share so we can investigate?

**Comment by dbreshears** [comment]
@tcarun , closing this as uncertain what to investigate .  If you have a repro project or set of repro steps, please re-open
