### ISSUE TITLE
Multiple Services In One Visual Studio Project

### ISSUE THREAD

**Issue by andrejohansson** [Azure/service-fabric-issues#354]
Is it possible to have multiple ServiceManifests in one Visual Studio project?

We´re facing a bit of a problem with Visual Studio Project inflation, we´re up to 33 projects already. We roughly have two projects per microservice, one for the implementation and one for tests. 

We´re now thinking that we want to merge all of our projects to one, keeping the service structure in folders and namespaces instead. This will make our project much more manageable and cut build times as well.

However, we do not know hot to package and deploy in this situation and it feels like we will loose all Service Fabric tooling support if we choose this path.

Is there any way we can define multiple manifests and get multiple service packages as output from one project?

**Comment by vturecek** [comment]
The VS tooling for Service Fabric doesn't support this. You can set up projects any way you want as long as you can build and produce Service Fabric service packages, but you'd have to write build scripts to do that yourself.

**Comment by masnider** [comment]
@andrejohansson - does this answer your question?

**Comment by andrejohansson** [comment]
@masnider yes and no! The concrete answer is answered. But I am still interested in some guidance of how you guys setup large systems using Service Fabric. What is your rules for when to create a new actor/service and when do you take the leap to a new application?

**Comment by MikkelHegn** [comment]
There are no rules per se for this question, it really comes down to your specific scenario. I've seen application boundaries aligned with a bounded context in a domain-driven design which to some degree aligns with each application should only exposes one public endpoint.
If your application can have multiple instances of "something", then making use of Application Types is a good practice as well.

We did experiment with features at one point to merge multiple applications post build, but the benefits over just having everything split in to multiple applications were hard to find. E.g. how do you handle dependencies between services for local debugging across applications?

What is your concern with the many projects in VS? Build time or just management?

**Comment by andrejohansson** [comment]
Primarily I would say the development lifecycle. I want a developer to be able to develop, run unit tests quickly using ncrunch. This works fine today. But then the next step to actually run your changes in a cluster  can take some time (even if the local cluster is set to 1 node) if the solution grows a bit. So I'm trying to find a nice balance between:

* Developer velocity (running in actual environment with multiple nodes/partitions to discover the possible hickups you can hit in those scenarios)
* Architectural boundraries and endoints
* Run time resilience (replicas, partitions, different apps)
* Deployment speed (dependent on size of packages, replicas etc) and maintainability

Including somedependencies quickly turns our app output to 100-200Mb in dlls. Pushing these dlls to 10 services with 10 replicas each makes for a quite large size to deploy which takes a bit too much time for my taste. I want to split up and be able to run smaller pieces of the app quicker.

**Comment by MikkelHegn** [comment]
@andrejohansson Do the smaller pieces you run locally have to be one app when deployed to the final environment? I'm asking because there are really no constraints around splitting things in multiple apps. Only thing you loose is it's harder to manage if you run multiple instances of everything.
Or is the scenario that the combination of services developers need differ from time to time?
