### ISSUE TITLE
Cannot download microservice code package when vmss scaling out.

### ISSUE THREAD

**Issue by TonyDou** [Azure/service-fabric-issues#357]
I'm running service fabric cluster on Azure with an windows 2016 vmss. The service fabric system version is 5.6.231.9494. 
When the vmss scales out, the new node sometimes throw the following error and failed to download the code package. I can RDP into it and the code package is indeed not downloaded. The InstanceCount I specified for this micro service is -1.
_Error event: SourceId='System.Hosting', Property='Download:1.0'. There was an error during download._

The scale out can work normally at the beginning, and the micro service on the new node can also start up correctly. But after several rounds of scaling out it happened, it starts to fail. Once it failed, it can never recover. I have to recreate the app again to mitigate this issue.

**Comment by masnider** [comment]
@TonyDou - when you say it failed and didn't recover, what part? Activating the service on that particular node? What information did you see that indicated that it was never going to work?

**Comment by TonyDou** [comment]
I mean when the issue happened, it will always fail to download packages when scaling out. Activating on new nodes, and since it can't download package, so the new node will never get a chance to start the service, the new node will keep at the error state forever, until a redeploy the app. The error message will show on Service Fabric management portal and the service fabric is in yellow warning state.

**Comment by vturecek** [comment]
@TonyDou go ahead and open an Azure support ticket for this so we can get a closer look: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
