### ISSUE TITLE
Connect-ServiceFabricCluster - Does not work with ServicePrincipal and password

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#358]
Below is what I am trying to do.

**Connect-ServiceFabricCluster** -ConnectionEndpoint $ClusterConnectionEndpoint -serverCertThumbprint $PrimaryClusterKVThumbprint -AzureActiveDirectory -SecurityToken $SecurityToken

**$SecurityToken** is acquired with: 
**SF Server Application Id
SF Client Application Id
Credentials**

The credentials parameter does not accept a credential which consist of Service Prinicipal and Password.
Am using Service Prinicipal and Password to get over the limitation with organisational accounts needing the authenticate with a pop-up.

The ServicePrinicipal and Password route works fine for Login-AzureRMAccount like below,
**Login-AzureRmAccount -ServicePrincipal -Credential $SessionCred -TenantId "MYTENANTID"**

**$SessionCred** - is the credential of ApplicationId and Password for the ServicePrinicipal.

I dont see any documentation on the same, please help me if am missing something.

Thanks,
Pradebban Raja

**Comment by linggengmsft** [comment]
@rajaprad 
Acquiring security token is out of band. You will need to use ADAL to acquire access token first and pass it into -SecurityToken, so you would need to refer to ADAL documentation and use the overload which takes service principal username and password. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

**Comment by linggengmsft** [comment]
Also, we have a example in C# code just for your reference.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster

**Comment by rajaprad** [comment]
@linggengmsft , the whole purpose of using AD Service principal is to automate the connection without needing a popup for non organizational accounts. I would re-open this issue to address with a proper workable solution. The documents allow to login with AD but defy the purpose of automation - where a user would be required to authenticate.

**Comment by linggengmsft** [comment]
@rajaprad , yes I acknowledged you were looking for non-interactive node. ADAL library already provides this kind of authentication overload. Also in this link(https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster) we have a section "Connect to a secure cluster non-interactively using Azure Active Directory" that talks about this in C#.

**Comment by rajaprad** [comment]
@linggengmsft,  thanks for further details, I will have a check

**Comment by 4c74356b41** [comment]
@linggengmsft how would i go about that in Azure Automation runbook? I cant use interactive auth there and I cant use ADAL.
