### ISSUE TITLE
Posting large payload to Stateless Service DotNet Core API takes too long

### ISSUE THREAD

**Issue by hiraldesai** [Azure/service-fabric-issues#359]
Hi,

I'm seeing a significant amount of delay when posting a form with a rather large payload to a Service Fabric DotNet Core Stateless Service API. It takes about 1-2 minutes for the API to respond as compared to 50 miliseconds on local.  

Here is some more information: 
* The payload contains a photo uploaded by a user (and some other info). The photo is converted to its base64 data url format before posting. 
* The payload size is not significantly large. It's about 2.1 MB (maybe a little larger for bigger photos). 
* I've tried both application/json form post and multipart/formdata posts.
* There is no delay on local debug (through SF proxy on :19081), only happens on SF cluster hosted on Azure. (PS - internet connection is enterprise level fast - so there are no issues with speed).
* Here is what chrome shows in the xhr request, there is a large amount of TTFB, which makes me wonder if there is some kind of check happening internally in the reverse proxy.
![image](https://user-images.githubusercontent.com/1005174/28444154-f49955ba-6d6f-11e7-8814-e3979ed7be91.png)
* The code doesn't do any blocking database operations or anything, it uploads the image to Azure blob storage, writes the rest of the details from the payload to a reliable collection and returns.
* Here is a sample payload
[https://gist.github.com/hiraldesai/febc58fdc703fc443fb15a74b5ef72de](url)

Can someone please shed some light on this? I will also keep trying to dig deeper into this.

Kind regards,
Hiral

**Comment by hiraldesai** [comment]
I have more information now. I can confirm that it's Reverse Proxy issue because when I change the url of the API from Reverse Proxy (19081) to the direct Stateless API http endpoint (custom port number defined in my service config), the process takes 50 miliseconds!

![image](https://user-images.githubusercontent.com/1005174/28444887-17c7515e-6d75-11e7-87bb-bbc3dcaf68bc.png)

**Comment by kavyako** [comment]
For requests via the reverse proxy, default chunk size that we preallocate for request body is 16k. That is configurable via the ApplicationGateway/Http : BodyChunkSize setting in the ARM template’s Cluster resource type section. Can you try setting it to 64k:

    "fabricSettings": [
      {
        "name": "ApplicationGateway/Http",
        "parameters": [
          {
            "name": "BodyChunkSize",
            "value": "65536"   ->value in bytes for 64k
          }
        ]

**Comment by hiraldesai** [comment]
Great - thanks. I tested and it works as expected now. But our SF cluster is behind Azure Application Gateway and it looks like there is a similar kind of blocker somewhere on the Gateway too. I will now try and find out what that is and how to resolve it.
