### ISSUE TITLE
Actor design patterns

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#36]
There were once a few documents describing some [actor design patterns](https://web.archive.org/web/20150907122734/https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-actors-patterns-introduction/).

I'm wondering why they are no longer available. Is this because they weren't updated to the latest version of the SDK or perhaps because you've come to the conclusion these patterns aren't useful?

**Comment by vturecek** [comment]
Hey Eli, pretty much just lack of resources to keep them up to date after we shipped GA. At some point we'd like to bring back a more comprehensive series of architectural guidance articles across Service Fabric, similar to the actor design patterns articles.

**Comment by aelij** [comment]
Great, thanks.
