### ISSUE TITLE
Binding redirect to System.Fabric, Version=255.0.0.0

### ISSUE THREAD

**Issue by shoorik** [Azure/service-fabric-issues#361]
I wanted to report this in case someone else encounters this.

Using VS2017, I was following this tutorial: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-create-dotnet-app and things were working OK until I got to the "Connecting Services" section, when adding nuget package "Microsoft.ServiceFabric.Services.Remoting". 

I accidentally added the "2.7.0-preview5718" version (I had pre-release checkbox checked). When I realized the mistake and downgraded to stable 2.6.220, I started getting a compile warning:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
Detailed log output reported:

```
There was a conflict between "System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "System.Fabric, Version=255.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
```

After some troubleshooting (double-checking that all projects were targetting x64), I noticed the following binding redirects were added to some of the .config files:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Fabric" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-255.0.0.0" newVersion="255.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Once I removed this binding, things returned to normal.

**Comment by vturecek** [comment]
Thanks for reporting, @shoorik, this is very helpful.

**Comment by danielgauci** [comment]
It is worth searching the SF .csproj files content for 'preview5718' and removing any elements making reference to the preview release. In my case downgrading the nuget package did not remove the imports and was causing VS a lot of confusion locating references.
