### ISSUE TITLE
Provisioning application type throws exception

### ISSUE THREAD

**Issue by RaleS** [Azure/service-fabric-issues#363]
Using Rest API to provision application type:
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-provisionapplicationtype

Getting following error:
System.Exception: Post failed: FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR, Exception while parsing XML file: D:\SvcFab\IB\131451916281286167\qm1fzopt.sll
FileName: D:\SvcFab\IB\131451916281286167\qm1fzopt.sll --> InvalidOperationException: There is an error in XML document (1, 1). --> XmlException: Data at the root level is invalid. Line 1, position 1.

Is there a way to verify that uploaded package is correct?

**Comment by oanapl** [comment]
Not through REST. You can use [Powershell](https://docs.microsoft.com/en-us/powershell/module/servicefabric/test-servicefabricapplicationpackage).

**Comment by RaleS** [comment]
It seems that [FabricClient.CopyApplicationPackage](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.applicationmanagementclient.copyapplicationpackage?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Fabric.FabricClient.ApplicationManagementClient.CopyApplicationPackage);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet) creates an empty file _.dir in each folder.

Is there by any chance an example describing how to use [Upload File](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-uploadfile) in REST?

**Comment by lumiao** [comment]
the empty _.dir file is mark file used by image store service internally to indicate the availability of the linked folder. The brief sample is as follow:

       private static async Task<bool> UploadFile(string imageStoreQueryUri, FileInfo localFile)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(new Uri(imageStoreQueryUri));
            request.Method = "PUT";
            request.KeepAlive = true;

            request.ContentLength = localFile.Length;
            Console.WriteLine("Uploading the file: {0} to {1}", localFile.FullName, request.RequestUri);
            using (FileStream sourceStream = new FileStream(localFile.FullName, FileMode.Open, FileAccess.Read, FileShare.None))
            {
                byte[] data = new byte[localFile.Length];
                sourceStream.Read(data, 0, data.Length);
                Stream targetStream = request.GetRequestStream();
                targetStream.Write(data, 0, data.Length);
                targetStream.Close();

                try
                {
                    using (HttpWebResponse webResponse = (HttpWebResponse)await request.GetResponseAsync())
                    {
                        int statusCode = (int)webResponse.StatusCode;
                        if (statusCode >= 100 && statusCode < 400)
                        {
                            Console.WriteLine("Succeeded, StatusCode: {0}", webResponse.StatusCode.ToString());
                            return true;
                        }
                        else if (statusCode >= 400 && statusCode <= 499)
                        {
                            Console.WriteLine(string.Format("Client Error: {0}", statusCode));
                            return false;
                        }
                        else if (statusCode >= 500 && statusCode <= 599)
                        {
                            Console.WriteLine(string.Format("Server Error: {0}", statusCode));
                            return false;
                        }
                    }
                }
                catch (WebException ex)
                {
                    Console.WriteLine("Error uploading: {0}", ex.Message);
                    return false;
                }
            }
            return true;
        }

**Comment by RaleS** [comment]
Uploading package files using API does not auto-create a mark file in each folder. Provisioning application type where package that does not contain _.dir mark file in each folder returns FABRIC_E_DIRECTORY_NOT_FOUND with message 'The application <appname> is not found in the store.'

I was able to provision application type after uploading _.dir file into each folder.

You should consider mentioning it in the API documentation, or changing the behavior of the API if the behavior is not intentional.

**Comment by lumiao** [comment]
When uploading application package via REST API, the image store service isn't aware of that all files within a folder are uploaded and it's the time to add the mark file; so in REST the mark file has to be uploaded explicitly by client. We'll update the REST document. Thank!
