### ISSUE TITLE
VS 2017 Stateless App Local Deploy Fails

### ISSUE THREAD

**Issue by StephenMP** [Azure/service-fabric-issues#365]
# Backround
I have followed the steps located at: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-application-in-visual-studio

# Specs
**OS:** Win 10 Pro 64-bit
**CPU:** AMD Ryzen 1800x
**IDE:** Visual Studio 2017
**Service Fabric SDK:** Version 2.6.220

# Issue
When I create a new **Stateless App** from the **Stateless App Service Fabric Template** and attempt to deploy the app to my local cluster (via the Start button from visual studio), the project builds successfully; however, when the project attempts to deploy I receive the following output:

```
1>------ Build started: Project: servicefabpoc_stateless, Configuration: Debug x64 ------
2>------ Deploy started: Project: servicefabpoc_stateless, Configuration: Debug x64 ------
2>There is an error in XML document (9, 4).
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```

Using a **Stateful App Template**, everything works perfectly. It seems to be an issue with the **Stateless App Template**.

**Comment by vturecek** [comment]
@StephenMP Can you try updating your VS 2017 installation to the latest version? I've seen this happen when something new is added to the ApplicationManifest/ServiceManifest.xml schema and an older version of the SF tools in VS 2017 doesn't recognize it.

**Comment by StephenMP** [comment]
@vturecek That was actually the first thing I did before even adding the service fabric SDK's. So this was all done on the most up-to-date VS 2017.

**Comment by vturecek** [comment]
@StephenMP Mkay, well the next obvious thing to look at is what you have going on in ApplicationManifest.xml and ServiceManifest.xml around line 9. Can you paste that here?

@dbreshears FYI

**Comment by masnider** [comment]
@StephenMP - if you can share the manifests we can take a look. Did you get this figured out?

**Comment by StephenMP** [comment]
I apologize for the delayed response. Anyhow, I updated Visual Studio and the Stateless App seems to be working properly. Not sure why it wasn't before, but all seems well now.
