### ISSUE TITLE
[Reverse Proxy] Authorization header being stripped over websockets?

### ISSUE THREAD

**Issue by AdJones** [Azure/service-fabric-issues#366]
Hi,

I have been able to get the Reverse Proxy working (in both secure and unsecure modes), however I'm finding that, regardless of how I configure it, the Authorization header is lost when the request is received by my application. Is this expected behaviour of the reverse proxy, or am I missing some configuration, perhaps?

Thanks,

Adam.

**Comment by alecor191** [comment]
I see that this issues is labeled as "bug": Do you have an ETA for the fix you could share? Thanks!

**Comment by kavyako** [comment]
yes,  6.0 release ~ end of September will have the fix.

**Comment by alecor191** [comment]
Perfect! Thanks @kavyako.

**Comment by vturecek** [comment]
@kavyako can you confirm this made it out in 6.0?

**Comment by talarari** [comment]
I'm on 6.0.232.9494 and i'm still experiencing this bug.
@kavyako Any update on when this will be fixed?

**Comment by talarari** [comment]
can someone confirm whether or not this is being worked on?

**Comment by kavyako** [comment]
This went into the 6.1 release, sorry it couldn't make it into 6.0.

**Comment by kavyako** [comment]
Closing this since it has been fixed in 6.1. Please reopen if you are running into any issues.

**Comment by MonDeveloper** [comment]
Hi @kavyako , unfortunately we are still exepriencing the same issue on our on-prem 6.5.676.9590 windows cluster.
Could you help us finding at least a viable workaround since our production is affected?

Thanks in advance,
Marco
