### ISSUE TITLE
Unable to select service fabric applications in multiple startup projects in VS2017.3 (preview5)

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#367]
Fix for #52 probably caused a regression and it is now impossible to select fabric projects as multiple startup projects (only as a single startup project).

I don't really like this, because it make debugging much harder (I am deploying multiple apps simultaneously to mimic the production-environment.

**Comment by mkosieradzki** [comment]
Thanks @MikkelHegn ! That's great news! So it possibly means the issue have been fixed in preview 6.

I mean SF Applications are not showing up on the "Multiple Startup Projects" list.

However, I can right click on such a project and select set as startup project.

**Comment by dbreshears** [comment]
@mkosieradzki , seems something else is going on for you.    I tried both Preview 5 and 6 with 2 SF Application projects with a single service each,  both of them allow me to select both SF apps as startup projects (and actually the services if I wanted too).   Do you repro in that scenario or only your specific solution? 

 I do notice that we have one issue,   once the solution is closed in the multiple startup project scenario, they  have to be reset as they are all reset to none.   I'll look into seeing if that can be fixed.

**Comment by mkosieradzki** [comment]
@dbreshears Thanks a lot!

Currently tested on a single solution o two machines.

 I have accidentally turned on Lightweight solution load - so it might be related to that.

So:
1. I will check if resetting solution (.vs folder) will help
2. I will try to check if this happens for a new solution

**Comment by mkosieradzki** [comment]
BTW. Those projects are not appearing in the Configuration Manager as well.

**Comment by mkosieradzki** [comment]
@dbreshears I have just read again your message:
I can select every solution alone, I just cannot select them for multiple startup project (and they also do not appear in Configuration Manager)

**Comment by dbreshears** [comment]
@mkosieradzki , I assume you mean you can select every Service Fabric Application by itself,  just can't get it to appear in this list or the Configuration manager

![image](https://user-images.githubusercontent.com/3432571/28646430-77102d70-7216-11e7-9117-835fd6e7eb32.png)

**Comment by mkosieradzki** [comment]
@dbreshears Exactly: In my bugged solution: Application1 and Application4 are not appearing there.

On a new solution they appear both.

Also: I was lately porting all other projects to the new dotnet build-system. And .sfproj are the last projects that are legacy msbuild (even services are build using new .csproj format).

**Comment by dbreshears** [comment]
@mkosieradzki,  I'm doubtful Preview 6 is going to change anything.   Probably would need to get a repro solution to investigate since you only repro with this specific solution

**Comment by mkosieradzki** [comment]
@dbreshears This solution is huge (76 projects) btw. I have noticed some other projects are not appearing on the multiple startup project list as well (!).

OK. My current idea is to create a fresh solution and start adding projects and find when it breaks.

**Comment by mkosieradzki** [comment]
@dbreshears  L O L - when I add more than 15 projects to a single solutions projects starts to disappear from the multiple startup projects list. I need to repro this in a new solution.

**Comment by mkosieradzki** [comment]
@dbreshears Please add 15 class libraries to your project and open multiple startup project dialog ;) Prepare for a lot of fun ;)
![vsbug](https://user-images.githubusercontent.com/10385115/28647851-fafbb214-7269-11e7-8fde-ca9b0dfca774.png)

**Comment by dbreshears** [comment]
@mkosieradzki,  yeah looks like fun.  I'll raise the issue internally here and keep you posted

**Comment by mkosieradzki** [comment]
@dbreshears Thanks a lot. I apologize for not doing a proper research in the first place.

**Comment by dbreshears** [comment]
@mkosieradzki , no apologies needed.  Thanks for finding this!  The VS platform team has submitted a fix for 15.3.   You should be able to verify in  preview 7 which is currently slated for next week.

**Comment by mkosieradzki** [comment]
@dbreshears Thanks! That's great news.

**Comment by mkosieradzki** [comment]
It has been fixed in preview 7. Thanks a lot @dbreshears
