### ISSUE TITLE
Microsoft.SqlServer.Types with Service Fabric

### ISSUE THREAD

**Issue by haseeb-ahmed-tkxel** [Azure/service-fabric-issues#369]
Problem is pretty simple. I moved a WebApps project to Service Fabric which had the Microsoft.SqlServer.Types nuget package installed. Now, when trying to access database I'm getting the following error because I'm using spatial types.

> "Spatial types and functions are not available for this provider because the assembly 'Microsoft.SqlServer.Types' version 10 or higher could not be found. "

I've tried adding the following line of code to the class which the FabricRuntime creates an instance of, but that was of no use.

```csharp
SqlServerTypes.Utilities.LoadNativeAssemblies(AppDomain.CurrentDomain.BaseDirectory);
```

Your help would be appreciated, please do let me know if you need more info from me.

**Comment by masnider** [comment]
@haseeb-ahmed-tkxel - is the nuget package present?

https://stackoverflow.com/questions/13174197/microsoft-sqlserver-types-version-10-or-higher-could-not-be-found-on-azure

**Comment by haseeb-ahmed-tkxel** [comment]
@masnider Yep! But it doesn't seem to do anything when working with Service Fabric... it was running fine when our app was a WebApp (ASP.NET WebAPI) and not a Service Fabric ApplicationType.

**Comment by endintiers** [comment]
Struggling with the same problem in Azure Functions...in that case AppDomain.CurrentDomain.BaseDirectory points to the Azure Functions runner binaries, not your binaries - so it doesn't find them. Need a different address but I'm not sure what that is in Service Fabric (or Azure Functions)

**Comment by haseeb-ahmed-tkxel** [comment]
@endintiers Thank man! Your solution + another made it work for me.  Here is what I did:

```csharp
    internal sealed class MyApplicationType : StatelessService
    {
        public MyApplicationType(StatelessServiceContext context)
            : base(context)
        {
            SqlServerTypes.Utilities.LoadNativeAssemblies(Environment.CurrentDirectory);
        }
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            ...
        }
    }
```

Than, after that I opened up the App.Config file and added the following XML in the "assemblyBinding" section.

```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.Types" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0-11.0.0.0" newVersion="14.0.0.0" />
      </dependentAssembly>
```

I hope this helps anyone else having this issue. :-)

**Comment by negberts** [comment]
What should the build action of the native dll's be to be available in the Environment.CurrentDirectory?
If I just 'compile' them, they are not in the work directory but in the package.code directory of the project, which is different on local machine than on azure (because of application version)

**Comment by haseeb-ahmed-tkxel** [comment]
I'll have to re-open this issue. We just moved out app from .NET Framework to .NET Core and even though the above mentioned fix works alright on local cluster, from some reason when deployed I get the same error in App Insights.

> Spatial types and functions are not available for this provider because the assembly 'Microsoft.SqlServer.Types' version 10 or higher could not be found.

Any idea what could be the cause? I have seen the build artifacts and the code folder has the dll files + app.config also has the respected binding redirect. These two things are what fix it on the local.

Kind of on a tight deadline here, any quick help will be appreciated.

@masnider @endintiers

**Comment by dragav** [comment]
@haseeb-ahmed-tkxel Please see if this helps: [CodePackageActivationContext](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.codepackageactivationcontext?view=azure-dotnet), specifically [GetCodePackageObject](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.codepackageactivationcontext.getcodepackageobject?view=azure-dotnet#System_Fabric_CodePackageActivationContext_GetCodePackageObject_System_String_).[Path](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.codepackage.path?view=azure-dotnet#System_Fabric_CodePackage_Path).
