### ISSUE TITLE
Environment Variables aren't getting set

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#371]
My service manifest is as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="UIPkg"
                 Version="0.0.1"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="UI" UseImplicitHost="true" />
  </ServiceTypes>

  <CodePackage Name="Code" Version="0.0.1">
    <EntryPoint>
      <ExeHost>
        <Program>node.exe</Program>
        <Arguments>server.js</Arguments>
        <WorkingFolder>CodeBase</WorkingFolder>
        <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="2048"/>
      </ExeHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="NODE_ENV" Value="production" />
    </EnvironmentVariables>
  </CodePackage>

  <ConfigPackage Name="Config" Version="0.0.1" />

  <Resources>
    <Endpoints>
      <Endpoint Name="ServiceEndpointHttp" Type="Input" Protocol="http" Port="80"/>
      <Endpoint Name="ServiceEndpointHttps" Type="Input" Protocol="https" Port="443"/>
    </Endpoints>
  </Resources>
</ServiceManifest>
```

and my app manifest
```xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest ApplicationTypeName="UI"
                     ApplicationTypeVersion="0.0.1"
                     xmlns="http://schemas.microsoft.com/2011/01/fabric"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Parameters>
    <Parameter Name="UI_InstanceCount" DefaultValue="-1" />
  </Parameters>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="UIPkg" ServiceManifestVersion="0.0.1" />
    <ConfigOverrides />
    <EnvironmentOverrides CodePackageRef="Code">
      <EnvironmentVariable Name="NODE_ENV" Value="staging" />
    </EnvironmentOverrides>
  </ServiceManifestImport>
  <DefaultServices>
    <Service Name="UI">
      <StatelessService ServiceTypeName="UI" InstanceCount="[UI_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>
```

It appears that any environment variables aren't being set. They're not detected in my application and when I log to my VM which is running my application and run `(Get-Process -id {whatever}).StartInfo.EnvironmentVariables` NODE_ENV is nowhere to be seen. What am I doing wrongly here? I would at least expect it to set to `production`!

It's a standalone cluster with WinSrv2016 on each node. Although I remember having similar issues with an azure cluster.

**Comment by Mardoxx** [comment]
Any updates? Pretty important if broken, no?

**Comment by mani-ramaswamy** [comment]
Which version of the runtime is the cluster?

**Comment by Mardoxx** [comment]
@mani-ramaswamy 5.7.198.9494

Although this was also an issue with previous version I had installed:
5.5.216.0
5.6.220.9494

**Comment by mani-ramaswamy** [comment]
Thanks for reporting this - we're investigating this issue.

**Comment by mani-ramaswamy** [comment]
Looping back  - SF is passing the right variables to the processes when we verified it. Can you please tell us if the issue still repros?

**Comment by mani-ramaswamy** [comment]
I am closing this issue, since we haven't heard back (our current version is 6.1). Please reopen the issue or open another one if you are still encountering this issue.

**Comment by jayMax** [comment]
Hi! I have the same issue.
My version is 6.1.467.9494

**Comment by tugup** [comment]
@jayMax  Are you having this problem consistently? DO you see all the variables are missing from the environment?

**Comment by jayMax** [comment]
@tugup I have consistently the same problem.
I have one environment variable and 25 services where this variable should be overridden.
After deploy to cluster I see that manifest files of all services does not contains the variable value.
But the packages files of all 25 services contains the overridden value.

**Comment by Mardoxx** [comment]
@mani-ramaswamy still an issue -- I don't use SF any more however.

@jayMax as a potential workaround you could try with a startup script which sets env vars to appropriate values from SF manifests. Dunno if this would work. 

Not sure about how you're using it but.. Thinking about it I think I was abusing env vars a bit, when really values from a config file would be more appropriate. If you require different vars per instance this may cause an issue unless you have strict placement constraints - not sure if the variables are set for the process, or not.. If so then it's not really a problem!

**Comment by RajeetN** [comment]
@jayMax, @Mardoxx, we tried to repro the problem but could not. We saw the environment variable and its value was being passed in correctly. We took a dump of process too and it should the value correctly set too.  @jayMax, could you clarify what you mean by manifest files for all services does not contain the variable value but packages files do? If you mean service manifest files, then that is expected since the overridden values are read from package files. Would it be possible to wrap your exe in a cmd or bat file and print out all environment variables passed in?
