### ISSUE TITLE
container log file size grows until running out of disk space

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/service-fabric-issues#372]
I am using Windows Service Fabric 5.6.231.9494
I noticed file C:\ProgramData\docker\containers\{container-id}\{container-id}-json.log growing up to 90GB until C: drive ran out of space. I am going to workaround it by disabling NLOG writing to console.

Two requests:
- Set a limit of 10GB
- Change the path to write logs on D: drive which should be a larger drive

**Comment by vturecek** [comment]
@mani-ramaswamy Is this something we can control or is it strictly a docker config setting?

**Comment by mani-ramaswamy** [comment]
You can provide a max-size to limit the size of the logs. 
https://docs.docker.com/engine/admin/logging/overview/
https://stackoverflow.com/questions/37533571/limiting-docker-logging

**Comment by mani-ramaswamy** [comment]
You can pass the same options for log drivers to service fabric through the manifest @ https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-volume-logging-drivers. I am closing this issue, but please feel free to reopen if there was any other issue.
