### ISSUE TITLE
F# support for actors?

### ISSUE THREAD

**Issue by o1lo01ol1o** [Azure/service-fabric-issues#375]
I'm trying to get a simple f# actor service up and running and am running into `Unhandled Exception: System.Fabric.FabricException: Invalid Service Type` at my service entry point as soon as I try to create a service from my cluster.  As far as I can tell, the code that defines interfaces and service tasks is a verbatim translation of the C#.  (Perhaps unrelated, but i'm not sure that VS2017 is actually updating my xml files.  I had to edit them by hand to get the build to work and they seem to be less verbose than the ones that get built by the C# templates.) 

Can anyone advise?  

Additionally, are there any supporting materials for getting F# running with SF datatypes and services?

see gist: https://gist.github.com/o1lo01ol1o/5aa308e2f4d6ab669b4d8bb312494afb

**Comment by vturecek** [comment]
We don't have anything for F# today, but there might be others who've tried this. I would suggest posting this in the Actors and Services repo: https://github.com/Azure/service-fabric-services-and-actors-dotnet

**Comment by alexgman** [comment]
Any updates?

**Comment by VipulM-MSFT** [comment]
At this point, we are not planning to provide F# support. - Closing the issue.
