### ISSUE TITLE
Service fabric remoting not serializing types correctly

### ISSUE THREAD

**Issue by Telavian** [Azure/service-fabric-issues#378]
I have a custom uuid v1 type that my application uses as a record id. Remoting doesn't serialize this type correctly unless I decorate it with [DataContract]. This could also be because there are no public properties and it is just implicitly converted to a guid or string as needed.

Using DataContract may be the recommended approach for all types however I would prefer to use remoting with a different serialization provider and not to have to decorate every type. I also have numerous types that are currently not decorated making it less appealing.

Issue #59 makes it sound like this is possible however how does it work?
This [documentation ](https://github.com/MicrosoftDocs/azure-docs/blob/78e595701b4117371074db450eb0c5692914d804/articles/service-fabric/service-fabric-reliable-services-serialization.md)also makes it seem like it is possible however that seems to pertain only to stateful  services.

Does the service and the ServiceProxy both need to have the serializer registered?

**Comment by BharatNarasimman** [comment]
@Telavian 
The documentation referenced above is for state serialization. The remoting serialization is dependent on DataContract serializer. We are making changes to the remoting stack to support custom serializers, and it should be available by end of this year.
@suchiagicha

**Comment by suchiagicha** [comment]
@Telavian 

Here is the documentation on how to use Custom Serialization Provider with Remoting.
This is available in 2.8 Remoting package

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting

**Comment by Telavian** [comment]
Thanks.

**Comment by Telavian** [comment]
I am just reviewing the documentation at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting.

It is not clear how to upgrade a web api project to the V2 system. Is this different for web api projects?

**Comment by suchiagicha** [comment]
@Telavian 

What do you mean by web api project ?  This is only for remoting use-case.
Are you using web api frontend service to call service fabric remoting service? If that's the case ,  changes still remains the same as mentioned in documentation. You need to create ServiceProxyFactory with serialization provider (step 3)

**Comment by Telavian** [comment]
Ok. I thought there was something improved with that also.

Thanks.

**Comment by brutaldev** [comment]
@suchiagicha 
The JSON serialization provider in the docs is pretty unstable. Even using basic types it still cannot serialize correctly most of the time.
```
ServiceException: The exception System.InvalidCastException was unhandled on the service and could not be serialized for transferring to the client.
Detailed Remote Exception Information: System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
```
The build-in serializer (looks like XML) doesn't handle readonly  properties that are decorated with a `[DataMember]` attribute.

Is remoting only for the most basic of projects? It's going to be a massive undertaking converting all the services we have to use web comms...

**Comment by Telavian** [comment]
I am not sure the capabilities of the built in system however I would
recommend using a custom serializer with the V2 system.

There is a bit of code involved however it is all basic.

At that point you could use json.net or whatever else you want.

**Comment by brutaldev** [comment]
@Telavian @suchiagicha 

The code provided on the documentation page is actually buggy and strips the type information out causing problems with round trips. "IvanPfeff" highlighted this in the comments and his code sample works nicely to resolve it.
> The provided sample json serializer scrubs the parameter types which creates problems. If you are going to use the sample provided serializer I would recommend swapping out the body implementations with these

I've made a pull request to update the code sample and avoid this headache for anyone else: https://github.com/MicrosoftDocs/azure-docs/pull/4380

**Comment by kentcb** [comment]
Is there a way to customize the `DataContractSerializer` used by Service Fabric? For example, if I need to be able to serialize `ImmutableList<T>`...?

**Comment by Telavian** [comment]
I had a lot of problems with the built in system similar to the ones described previously.
I would think with a system like Service Fabric the built in serializer should be similar to BinaryFormatter.
In that it should take anything and always without fail return it back.
However I ended up converting over to the V2 system with a custom serializer.
It actually uses gzipped [ServiceStack.Text](https://github.com/ServiceStack/ServiceStack.Text) for json serialization.

You can review this to see my approach: https://github.com/Telavian/ServiceFabric.Serialization.V2
