### ISSUE TITLE
Make it easier

### ISSUE THREAD

**Issue by alvipeo** [Azure/service-fabric-issues#383]
I have a web app built with ASP.NET Core 1.1 and I have a .NET 4.7 Class library which generates some reports. It uses third party .NET component which is not available for .net core. But I want to stay with .net core web app. So I tried to create a Service Fabric project and make a Stateless Service from that .NET 4.7 lib. That would allow me to keep .net core web app which would talk to this service. But it turns out Service Fabric is not really easy. I particularly dropped that idea because of communication setup between web app and the service. Will try that again when I have time. But I think is should be easier.

Please make an MVA guiding creating a project similar to mine (or even more complex scenario) in VS2017 (latest Preview). So we can see how the tolling works, all the parts and settings.

IF there's already something similar, please let me know.

Also, pricing.... but I'll pass it on to the client. See what he thinks.

**Comment by aL3891** [comment]
You can just run asp.net core on .net4.7, just set TargetFramework to net47
that's completely unrelated to service fabric though :)

**Comment by alvipeo** [comment]
My point is setting up all the things and setting up communication between services are not straightforward. Also, CI/CD is on my list. Hopefully that's going to be easy... well...

As to targeting 4.7, when I created the proj in VS2017 I set to target .Net 4.7. But that still doesn't allow to use .net 4.7 class libraries (by design I think). Or I'm missing something here...

**Comment by masnider** [comment]
@alvipeo what errors are you getting? What do you see in the output when you try to build? Can you share a simple project that repros the behavior?

**Comment by alvipeo** [comment]
guys, I'll get back to SF when I'm done with the current version which basically consists of 2 Web Apps - 1 is .net core and another is .net 4.7.

**Comment by Mardoxx** [comment]
Well no i would not recommend SF for a SPA and simple WebApi backend. Use Azure Websites for that.

However saying that, SF is incredibly easy to set up. Instead of whinging about it because you can't get your head around the plethora of examples and documentation available - why not just post what issues you have specifically and see if some kind soul can assist...

**Comment by alvipeo** [comment]
ok, the help has been great. closing the issue.
