### ISSUE TITLE
DnsService: Get-ServiceFabricClusterConfiguration not exporting addonFeatures/DnsService-Option

### ISSUE THREAD

**Issue by Saphirim** [Azure/service-fabric-issues#385]
After activating the DnsService on an On-Prem Cluster like described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice I exported my Cluster-Configuration via PowerShell using the Get-ServiceFabricClusterConfiguration Cmdlet.

The exported JSON-File didn't show the addonFeatures-Array also missing any hint on the DnsService. Curious about this, I updated the Cluster-Configuration again and watched Service Fabric taking the DnsService down again.

The missing export of the DnsSercive-Activation seems critical to me, since getting the current Cluster-Configuration via PowerShell was the usal first step for us, if anybody needed to deploy changes to the Cluster. Missing the DnsService-Activation in this step may lead to unwanted deactivation of the DnsService, what may destroy the Service-Communication for applications relying on it.

Is this intended behavior? Meaning that Cluster-Administrators need to version and manage their deployed Cluster-Configuration files in a dedicated repository?

I recommend to make the addonFeatures or especially the DnsService-Configuration part of the ClusterConfiguration-Export.

**Comment by masnider** [comment]
I'm guess this is a bug and am going to mark it as such for now. If we find out otherwise later we can remove it, but the behavior you described is what I would have expected as well.

**Comment by Liphi** [comment]
May I know 1) what 'apiVersion' did u specify on the json config when activating DnsService, and 2) what 'apiVersion' value was returned when u call Get-ClusterConfiguration, and 3) what 'apiVersion' did u use when 'I updated the Cluster-Configuration again and watched Service Fabric taking the DnsService down again' ?
According to the Standalone doc, '04-2017' or later should be used as the apiVersion value. U may refer to 'add-on features' section on this link: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest

**Comment by Liphi** [comment]
May I know 1) what 'apiVersion' did u specify on the json config when activating DnsService, and 2) what 'apiVersion' value was returned when u call Get-ClusterConfiguration, and 3) what 'apiVersion' did u use when 'I updated the Cluster-Configuration again and watched Service Fabric taking the DnsService down again', and 4) the code version of your cluster?
 According to the Standalone doc, '04-2017' or later should be used as the apiVersion value. U may refer to 'add-on features' section on this link: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest

**Comment by Saphirim** [comment]
Hi,

you are right, my Cluster-Version was set to: 01-2017

Testing the behavior on another Cluster with latest Version 05-2017 (Latest SF 5.7-Upgrade installed), the Export of AddOn-Features is working es expected including the DNS-Service activation.

Thank's for the hint, I think the bug may be closed, since it just occurred because of the outdated API-Version.

**Comment by Liphi** [comment]
NP. I'll copy Standalone doc content to the Dns Svc main page to eliminate future confusion.
