### ISSUE TITLE
Reverse Proxy security vulnerability

### ISSUE THREAD

**Issue by xela30** [Azure/service-fabric-issues#386]
Reverse Proxy intercepts responses from applications, gets cookies from Set-Cookie header and then randomly reuse it for subsequent requests.

This is especially critical when ASP.NET Forms authentication is being used because unauthenticated users can access authorized users data.

See steps to reproduce and the source code of sample application: https://github.com/xela30/ReverseProxyCookieIssue/blob/master/STR.docx.

Please address this ASAP.

* On-premise cluster 5.6.220
* Windows Server 2016

**Comment by kavyako** [comment]
Thank you for reporting, am investigating this now.

**Comment by kavyako** [comment]
This has been fixed internally, the fix will be available in 5.7 CU1, scheduled to be released next week.

**Comment by xela30** [comment]
Any updates regarding release date?

**Comment by kavyako** [comment]
This fix was released with 5.7 CU1, some time mid august. 
Are you still seeing this? What is your service fabric version?

**Comment by xela30** [comment]
Where I can take that 5.7 CU1 version from?
Following one was released before the fix applied:
https://blogs.msdn.microsoft.com/azureservicefabric/2017/08/09/release-of-sdk-2-7-198-and-runtime-5-7-198-for-windows/

**Comment by elscript** [comment]
Vote for the issue too. This stops us from using SF in production. We have upgraded SF version to 5.7.198 and the problem still occurs.

**Comment by kavyako** [comment]
This is fixed in builds >= 5.7.207.9494. 
For clusters in Azure, go to Settings -> Fabric Upgrades -> Fabric Upgrade Mode (manual) -> Select 5.7.207* version from the drop down.

**Comment by elscript** [comment]
Thanks, could you provide the link for stangalone cluster .cab?

**Comment by ilyalozovyy** [comment]
Any news on how to get the .cab for standalone cluster deployments?
I checked and even though my cluster is configured for automated updates, I am not able to find any information related to being able to download 7.7.207.9494 and I even noticed that Service Fabric version 6.0 was released today but no ability to download the runtime.
There has got to be a better way to allow people to download these runtime and SDK releases than links posted all over the internet that are all old.

**Comment by elscript** [comment]
Still waiting...

**Comment by kavyako** [comment]
It looks like the standalone installer for 5.7 CUx was not released. We will publish it some time next week. 
The 6.0 should also be out soon. Sorry about the delay in getting these out.

**Comment by elscript** [comment]
Ok, please keep us in touch

**Comment by kavyako** [comment]
5.7 CU 5.7.221 is out, [here ](https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/03/service-fabric-5-7-221-2-7-221-refresh-release-for-standalone-windows-and-net-sdk/) is the announcement.
Follow the [download link ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server) to get the new packages.

Thanks
Kavya

**Comment by elscript** [comment]
Thanks, guys! The problem is over now
