### ISSUE TITLE
Service Fabric Application Stuck in Deleting State

### ISSUE THREAD

**Issue by TonyGerace** [Azure/service-fabric-issues#387]
We have a deprecated application we were POCing and decided to not use the application in the cluster. For some reason the application will not delete. All but 3 actor services in the application have Status of "unknown" (I am assuming the have deleted correctly) and the 3 actor services have a state of "deleting". I have tried deleting them via the explorer and powershell and nothing seems to happen. I have tried restarting the 3 node cluster. 

This is now throwing errors in the naming service as well.

Unhealthy event: SourceId='System.NamingService', Property='Duration_NODeleteService.fabric:/CaseManagement/AuthorizationActorService', HealthState='Warning', ConsiderWarningAsError=false. The NODeleteService started at 2017-08-04 18:54:59.495 is taking longer than 30:00.000.
--

Any guidance would be greatly appreciated.

**Comment by oanapl** [comment]
The naming warning (not error) is just showing that it has an active operation that doesn't complete. Have you tried deleting with [-ForceRemove](https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricapplication?view=azureservicefabricps)?

**Comment by masnider** [comment]
@TonyGerace can you provide more information about what's going on? Perhaps share some screenshots from Service Fabric Explorer? As Oana indicates - that's one warning but there should be others when your application is in this state. -ForceRemove will probably work for you, but if you plan on deploying this application again you should see why it is not cleanly closing.

**Comment by francescocristallo** [comment]
I just had the same problem
In Service Fabric Explorer I saw this warning:


Unhealthy event: SourceId='System.PLB', Property='MovementEfficacy_Consecutively_Via_FM', HealthState='Warning', ConsiderWarningAsError=false. Movements that the Load Balancer issued were dropped before execution:Check for relevant unhealthy replicas and paused, deactivating, or unealthly nodes in the cluster and consider restarting them as a possible mitigation.
--

**Comment by oanapl** [comment]
@TonyGerace, did force delete removed the application?

@francescocristallo, have you checked the recommended steps in the health report? Have you tried force delete?

**Comment by oanapl** [comment]
Since there was no reply to the previous questions, I will close the issue. Please re-open / open new issue if you have more information for us.

**Comment by alexzheludov** [comment]
I am having the same problem and I've tried -Force-Remove, but it did not help.
When I try to delete using power shell it times out. I am considering rebuilding a cluster because of this problem, its been sitting in deleting state for a few days now.

**Comment by oanapl** [comment]
Can you check whether there are replicas left behind on one of the nodes? We need to reopen the replicas to remove their state on delete and sometimes I see that failing because either the service code has issues or the node is in a weird state. If you can pinpoint such a replica, you can try restarting the node where it's at. To find the replicas, you can either use queries, or if they show nothing, look at event log to see any repeating traces from Service Fabric regarding reopening a replica.

**Comment by HaakonL** [comment]
We're on 6.1 and with this upgrade the cluster has become somewhat unusable. I have one node that is stuck in Disabled mode for five days now, and nothing I do make it wake up, activate, delete etc. We are getting quite worried about launching our game APIs on Service Fabric, as there seems to be almost impossible to replace faulted nodes, scale up/down etc without deleting the whole cluster and starting from scratch. For a critical production API this is of course not something we can rely on. EC2 has a great user interface and scales up/down in a few minutes, I really miss the same level of quality in Azure Service Fabric.

We need a more reliable setup before the end of June, what are the plans/roadmap for Service Fabric, the explorer and the azure portal to become a full fledged dev ops solution, where scaling up/down, replacing of faulty nodes and spinning up new instances can be done as easily and elegant as in EC2?

And how do I fix the Disabled node? I tried removing it in the azure portal, tried adding new nodes, tried scaling up and down, tried to reactive the disabled node and a hundred other different things, but it's just stuck...

**Comment by oanapl** [comment]
@HaakonL , I am sorry your experience is so frustrating. Can you please open a new issue so we can properly address your concerns (since they are not related to the initial thread)?
For the disabled node, you can open a customer support ticket so we can get all the information we need and help you.

**Comment by DaweiCai** [comment]
I also met this issue. And I have tried following code 
 
 $nodes = Get-ServiceFabricNode
foreach($node in $nodes)
{
    $replicas = Get-ServiceFabricDeployedReplica -NodeName $node.NodeName -ApplicationName "fabric:/OnlineBotServiceType"
    foreach ($replica in $replicas)
    {
        Remove-ServiceFabricReplica -ForceRemove -NodeName $node.NodeName -PartitionId $replica.Partitionid -ReplicaOrInstanceId $replica.ReplicaOrInstanceId
    }
}

to force delete the replicas. Still now work . Could some experts take a look ?

**Comment by DaweiCai** [comment]
@oanapl , I also tried -Force and -ForceRemove, still not work. 
![image](https://user-images.githubusercontent.com/10734523/48750234-1b8b0280-ecb9-11e8-940d-614689515e1c.png)
