### ISSUE TITLE
Using sdk functions while connecting to SF in PS Function

### ISSUE THREAD

**Issue by shlomcoh** [Azure/service-fabric-issues#388]
Hello,
I had some weird behavioral this week when i tried to use Publish-upgradedServiceFabricApplication and  Publish-NewServiceFabricApplication in A powershell Function.
I had a rolling deployment working on my CI/CD and i had to do some changes to it, one of the changes i did was to move the deployment flow from the global script section to a function.
I created a function, in general this is what it does:
Function Start-ServiceFabricDeployment{
Connect-ServiceFabricCluster -ConnectionEndpoint $ClusterName -X509Credential -ServerCertThumbprint $Thumbprint -FindType FindByThumbprint -FindValue $Thumbprint -StoreLocation LocalMachine -StoreName My

            if (Get-ServiceFabricApplication -ApplicationName "fabric:/$FabricName")
            {
                Publish-upgradedServiceFabricApplication -ApplicationPackagePath $ApplicationPathAndFile -ApplicationName "fabric:/$FabricName"
            }
            else
            {
                Publish-NewServiceFabricApplication -ApplicationPackagePath $ApplicationPathAndFile -ApplicationName "fabric:/$FabricName"
            }
}

after moving connect-serviceFabric to the function and trying to run one of the publish functions i got and error saying:
##[error]Get-ServiceFabricClusterManifest : Cluster connection instance is null

After some digging and debugging in the SDK I found out that the $ClusterConnection variable is not getting through to the SDK.
after some more digging I found out non of the parameters i start in any of the functions doesn't move to the SDK functions in the same Scope.
I found two solutions for this issue:.
1. run connect-servicefabriccluster from Main
2. set a new variable: 
Set-Variable -Name ClusterConnection -Value $ClusterConnection -Option AllScope -Visibility Public -Scope Global

Can you please advise if this is by design or an issue?

**Comment by heeldin** [comment]
This is by design in powershell. 
Your solutions are correct. Also after a connect cluster is created, you can use $Global:ClusterConnection=$ClusterConnection

Your script runs in global scope while your module (connect cluster command) runs in a script scope, so the session variable that holds the clusterconnection is not seen by the script at the global scope.
