### ISSUE TITLE
Documentation/Schema for PublishProfile

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#391]
Is this available somewhere?

**Comment by Mardoxx** [comment]
I found it here `{VSInstallDir}\Xml\Schemas\ServiceFabricPublishProfile.xsd`.

**Comment by masnider** [comment]
@Mardoxx are you good at this point, or is there something else you'd like from us?

**Comment by Mardoxx** [comment]
I'm good thanks! Thought I'd closed it :)
