### ISSUE TITLE
Stateful service partition packing issue

### ISSUE THREAD

**Issue by arunas-z** [Azure/service-fabric-issues#394]
I have a cluster with an application, that contains stateful service with 4 partitions, replica set size 3, placed on 3 nodes (test environment, bare minimum to reduce costs).

Most partitions tend to have their active replica on a single node. Not sure why this is happening, naturally I would like for the Service Fabric to spread out active replicas of each partition thorough the nodes as evenly as possible.

Cluster has no customizations to load balancing rules etc. 

In addition, I see that for this cluster PrimaryCount has 1 for the stacked node and 0 for the rest, while ReplicaCount is 1 for all nodes, and I see constant Creation and CreationWithMove actions for these + Count metrics in cluster explorer details. But it does not seem like this is doing anything, replicas are not being recreated or moved and besides the packing issue everything is green and working fine.

Cluster manifest is attached.
[cluster_manifest.txt](https://github.com/Azure/service-fabric-issues/files/1214924/cluster_manifest.txt)

**Comment by masnider** [comment]
Can you take a screenshot of the cluster map and share that as well?

**Comment by arunas-z** [comment]
![image](https://user-images.githubusercontent.com/30899510/29349456-b1cff9c0-8262-11e7-9871-cb288e3023d4.png)

**Comment by masnider** [comment]
@arunas-z sorry for the delay in getting back to you. My fault. Are you still seeing this? If you are, can you also share the output of Get-ServiceFabricNode | Get-ServiceFabricNodeLoadInformation ?

Thanks and sorry again in the delay in replying to you.

**Comment by yltor** [comment]
If the primaryCount and replicaCount are 1, it means there is only one partition get placed. Then I don't follow what does 'stacked node' mean?

**Comment by arunas-z** [comment]
> Are you still seeing this?
I have since rewritten the solution to use stateless services and named service instances. I don't think its better by much but at least now I can define node constraints if needed.

All Get-ServiceFabricNodeLoadInformation have this:
NodeLoadMetricInformationList : {}

> If the primaryCount and replicaCount are 1, it means there is only one partition get placed. Then I don't follow what does 'stacked node' mean?
These were just metric values, in reality there were multiple active replicas of different partitions on node.

**Comment by masnider** [comment]
@arunas-z Did this ever end up making sense to you and working as you expected? How are you creating these services? It sounds like they're somehow getting created with weird or incorrect [default metrics.](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-metrics#default-metrics) Can you Get-ServiceFabricApplication | Get-ServiceFabricService | Get-ServiceFabricServiceDescription and share that so we can see the metric set the services are configured with? Get-ServiceFabricClusterLoadInformation should also show all the metrics (or look inside SFX for the metrics tab) and see if the instances are really stacked up on the same nodes. Or maybe we should talk about what you meant at the beginning by "Active"?

**Comment by masnider** [comment]
@arunas-z Hi there! We haven't heard back from you in a while, so we're going to close this issue down. If you have additional questions or didn't end up getting this to work, feel free to reopen this issue and let us know and we can keep going.
