### ISSUE TITLE
ServiceContext.ListenAddress() gone

### ISSUE THREAD

**Issue by ToyMakerGR** [Azure/service-fabric-issues#395]
I have created a custom FabricTransportServiceRemotingProviderAttribute for my project, and the latest SDK broke my code.
More specifically, in my IServiceRemotingListener.CreateServiceRemotingListener implementation, when I try to return a new FabricTransportServiceRemotingListener instance by passing the service Context and a custom ServiceRemotingDispatcher, I get this:

The error is: Method not found: ‘System.String System.Fabric.ServiceContext.get_ListenAddress()’.
at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.Runtime.FabricTransportServiceRemotingListener..ctor(ServiceContext serviceContext, IServiceRemotingMessageHandler messageHandler, FabricTransportRemotingListenerSettings listenerSettings).

I am running SDK version 5.5 for the time being. However, right now the SDK download seems to have been taken down, so I can't determine if this solves the issue.

**Comment by ToyMakerGR** [comment]
I've managed to download the latest SF SDK (5.7.x), and the behavior returned to normal.

**Comment by JerryGoyal** [comment]
I had to downgrade NuGet package **_Microsoft.ServiceFabric.Services.Remoting_** to 2.6.220 to make it work.(first, uninstall all servicefabric packages and then install **_Microsoft.ServiceFabric.Services.Remoting v2.6.220_**)
