### ISSUE TITLE
Host Multiple HTTPs .NET Core WebAPPs 

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#399]
Can't find documentation or examples on how to host multiple HTTPs WebApps using the WebListener Host.
I want to host many WebApps on port 443 with different external URLs (mapped with externally managed CNAMEs)

I am struggling with the Endpoint configuration and documentation seems very light. 

It seems that even if you modify the url in the `WebListenerCommunicationListener` constructor the strong wildcard is still published to the netsh http urlacl.

Would appreciate some specific documentation in this area :)

**Comment by masnider** [comment]
@ConX-Ryan - are you able to get this working in a selfhosted core app outside of SF? If you can (while we wait for the updates) then I can help you translate that into SF.

**Comment by ConX-Ryan** [comment]
Hi Matt,

Thanks for your response, my current strategy is to have a Setup task that runs the netsh commands manually for each SF service using a .bet file (haha modern technology). 
I then override the .UseUrls param to the applicable value.

What i have noted is that the WebListenerCommunicationListener constructor requires an endpoint even though this will not be used any longer so i have assigned an arbitrary port out of the way.

Please do suggest a more appropriate or sustainable way if you have one. I am currently reading up on the new DNS feature and containers which sound like they may help in the future.

**Comment by masnider** [comment]
A setup entry point was exactly what I as going to recommend you use, so you're on the right track.  When you say that the communication listener requires an endpoint - can you share the code snippet and what you think isn't necessary or what it's doing wrong? We can see if we could improve it.

**Comment by ConX-Ryan** [comment]
`protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                    new WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {`

That "ServiceEndpoint" is a require param and will generate a strong wildcard urlacl on a port even though not required any longer.

**Comment by masnider** [comment]
Yeah we should be able to make that optional if you're doing things outside of SF in your own setup, which folks will have to for all sorts of more advanced scenarios.  @amanbha fyi

**Comment by ConX-Ryan** [comment]
Excellent, is the plan to include a host name configuration (UrlPrefixes supported by http.sys) in the endpoint? that would be great if it fits with all the rest of the stack

Thanks for your time.

**Comment by masnider** [comment]
I don't know of any plans for that. Generally we're moving away from doing more http.sys specific stuff since that inherently means that the app works only on Windows.

**Comment by amanbha** [comment]
@ConX-Ryan Reg, the "ServiceEndpoint" as required param: You can add a class derived from AspNetCoreListener and override GetListenerUrl, like KestrelCommunicationListener (https://github.com/Azure/service-fabric-aspnetcore/blob/develop/src/Microsoft.ServiceFabric.AspNetCore.Kestrel/KestrelCommunicationListener.cs)

**Comment by masnider** [comment]
Hi @ConX-Ryan - did you ever get this sorted out or did @amanbha's suggestion work for you? We haven't heard back from you on this, so we're going to close this issue down for now. If you still have questions or didn't end up getting it to work, please just reopen the issue and let us know. Thanks!

**Comment by ConX-Ryan** [comment]
Yes and No, Yeah the startup task works fine and is acceptable but i am still left with a Mandatory endpoint in the config that will be created and never used which feels wrong to me from a few different angles.
