### ISSUE TITLE
Method called via ServiceProxy remoting being repeatedly called every 5mins

### ISSUE THREAD

**Issue by sarjee** [Azure/service-fabric-issues#4]
[DummyApp.zip](https://github.com/Azure/service-fabric-issues/files/261488/DummyApp.zip)
I believe this is a valid issue and not related to my code. I have attached a sample project that reproduces the behaviour. Basically if you call a long running method via remoting it will be repeatedly called every 5mins. Is there some retry/timeout on remoting calls I am missing? I tried experimenting with different values of FabricTransportListenerSettings.OperationTimeout but this didn't seem to have any affect. I have only tested with a WebApi making the call to a stateless service. 

This only affects v5.0.217 of the Service Fabric assemblies as if I downgrade to v5.0.135 the method runs as expected (once).

This is my calling code:
`IStateless1 processingProxy = ServiceProxy.Create<IStateless1>(processingServiceUri);
processingProxy.DummyMethod();`

And the method itself:
```
public async Task<bool> DummyMethod()
{
	Guid guid = Guid.NewGuid();
	Logger.LogInfo(string.Format("{0} - {1}: Method entered with GUID: {3} @ {2}", this.Partition.PartitionInfo.Id, this.Partition.PartitionInfo.Kind.ToString(), DateTime.Now.ToString(), guid.ToString()));            
	bool result = false;
	try
	{
		await Task.Delay(TimeSpan.FromMinutes(6));
	}
	catch (Exception ex)
	{
		Logger.LogException(ex);
	}

	Logger.LogInfo(string.Format("{0} - {1}: Method ended with GUID: {3} @ {2}", this.Partition.PartitionInfo.Id, this.Partition.PartitionInfo.Kind.ToString(), DateTime.Now.ToString(), guid.ToString()));
	return result;
}
```

**Comment by suchiagicha** [comment]
Hi sarjee

You need to set the timeout on client factory for long running operations instead on service side.
Service side timeout is used for reminders usecase where service is initiating the communication.
Below is one of the way to change the operation timeout..
For old release. default timeout was infinite. That's the reason it worked for you. For latest release, we changed the timeout to 5 min as default.

   var factory = CreateProxyFactoryFabricTransport();
    var proxy = factory.CreateServiceProxy<IMyService>(new Uri("fabric:/Application22/Stateless1"));

 private static IServiceProxyFactory CreateProxyFactoryFabricTransport()
        {
          IServiceProxyFactory clientfactory;

         FabricTransportSettings settings = new FabricTransportSettings();
            settings.OperationTimeout = TimeSpan.FromMinutes(1);
            clientfactory = new ServiceProxyFactory(
                (h) =>
                {
                    return new FabricTransportServiceRemotingClientFactory(settings);
                });
            return clientfactory;
        }

Let me know if this doesn't works for you.

**Comment by sarjee** [comment]
Thanks that solves it! The perils of using default values.

It is interesting to note that you can get stuck in an infinite loop of repeatedly calling a service method if client timeout is set lower than the execution time of a service method.

**Comment by ashishnegi** [comment]
someone looking for the solution in 2018 :

```
            FabricTransportRemotingSettings settings = new FabricTransportRemotingSettings();
            settings.OperationTimeout = TimeSpan.FromMinutes(5);

            return new ServiceProxyFactory(
                (h) =>
                {
                    return new FabricTransportServiceRemotingClientFactory(settings);
                });
```
