### ISSUE TITLE
SFBinaryLoader.cs link is broken

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#400]
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-fabric/service-fabric-services-inside-containers.md

Contains link to SFBinaryLoader.cs which is broken.

**Comment by masnider** [comment]
Yeah looks like it's linking to a private repo. @anmolah - can you move that to a public repo or figure out what you want to do?

**Comment by mani-ramaswamy** [comment]
Thanks for reporting this issue. It has been fixed.
