### ISSUE TITLE
Single node cluster - how to restore from backup?

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#403]
Single node cluster does not have FaultAnalysisService and in consequence StartPartitionDataLossAsync throws 0x80071D0A.

How am I supposed to restore from backup in a single node cluster?

**Comment by rishirsinha** [comment]
Remove-ServiceFabricReplica for the replica should cause a data loss.

**Comment by mkosieradzki** [comment]
@rishirsinha Thanks a lot, unfortunately `Remove-ServiceFabricReplica` has a bit different semantics. `StartPartitionDataLoss` induces full data loss while `Remove-ServiceFabricReplica` actually induces this event, however you need to do restore in Force Mode (instead of safe mode). However it is possible to achieve similar results.

Which approach is recommended?

**Comment by LMWF** [comment]
Conceptually, that will do that same thing in this case because you only have one replica.  Remove-ServiceFabricReplica will drop that one replica, which will cause the system to call your service's OnDataLossAsync() when the new replica comes up.

**Comment by mkosieradzki** [comment]
@LMWF in case there is exactly one replica you are right, but...

you don't want to assume the number of replicas in your code...

From my perspective `Remove-ServiceFabricReplica` sounds like a temporal workaround. However IMO this is such a basic feature, that there should be a single API working consistently across different kinds of clusters. @masnider during August Q&A was proposing adding back FaultAnalysisService to the single Node dev cluster.

Alternatively maybe this issue will be obsolete when the new Backup/Restore feature will finally ship?

**Comment by masnider** [comment]
Hi @mkosieradzki, there's now an internal bug tracking enabling this for the local/dev box scenario. @MikkelHegn fyi

**Comment by motanv** [comment]
FYI a PR is out to enable FabricFAS in one-node dev cluster.
