### ISSUE TITLE
ServiceFabric DataContractSerializer Differing Between Actual Environment Over Unit Tests

### ISSUE THREAD

**Issue by Izzmo** [Azure/service-fabric-issues#405]
Our team ran into a weird quark with the serialization of a data structure between our unit tests and a live service fabric environment. This has been a long-standing issue for us when using the `IReadOnlyList<T>` type and the `DataContractSerializer` needing a `KnownType` attribute adding to any class which consumes it. This has worked fine, until now, by simply adding `[KnownType(typeof(List<MyObject>))]`. _This still works in unit tests, just not in a real environment._ In a real environment, the DataContractSerializer is looking for an implementation under the _System.Collections.ObjectModel_ namespace, but why?

## Unit Test
```csharp
using System;
using Gtm.TestUtilities;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace Gtm.WebService.Models.Tests
{
   [TestClass]
   public class OrderSummaryRequestTest
   {
      [TestMethod]
      public void ShouldSerializeDataContract()
      {
         var lines = CreateOrderLines();
         var instanceForSerialization = new OrderSummaryRequest(lines, AddressTest.CreateStubAddress());
         OrderSummaryRequest deserializedInstance;

         using (var sw = new MemoryStream())
         {
            var serializer = new DataContractSerializer(typeof(OrderSummaryRequest));

            serializer.WriteObject(sw, instanceForSerialization);
            sw.Position = 0;
            return (OrderSummaryRequest)serializer.ReadObject(sw);
         }

         Assert.AreEqual(instanceForSerialization.Lines.Count, deserializedInstance.Lines.Count, "OrderLines Count should be equal.");

         // this test passes when the List<OrderLine> KnownType is added, fails if not.
      }

      public static List<OrderLine> CreateOrderLines()
      {
         return new List<OrderLine>
         {
            new OrderLine(Guid.NewGuid(), "M", 1),
            new OrderLine(Guid.NewGuid(), "L", 2)
         };
      }
   }
}

```

## Data Structure Class
```csharp
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using Gtm.Common;

namespace Gtm.WebService.Models
{
   /// <summary>
   /// An Order Summary Request
   /// </summary>
   [DataContract]
   [KnownType(typeof(ReadOnlyCollection<OrderLine>))] // needs this for a live environment
   [KnownType(typeof(List<OrderLine>))] // needs this for unit tests
   public class OrderSummaryRequest
   {
      [DataMember(Name = "Lines")]
      private readonly IReadOnlyList<OrderLine> lines;

      [DataMember(Name = "ShippingAddress")]
      private readonly Address shippingAddress;

      /// <summary>
      /// Initializes a new instance of the <see cref="OrderSummaryRequest"/> class.
      /// </summary>
      /// <param name="lines">A list of order lines.</param>
      /// <param name="shippingAddress">The address that the order will be shipped to.</param>
      public OrderSummaryRequest(IReadOnlyList<OrderLine> lines, Address shippingAddress)
      {
         ParameterVerifier.VerifyIsNotNull(lines, nameof(lines));
         ParameterVerifier.VerifyIsAtLeast(lines.Count, 1, nameof(lines));
         ParameterVerifier.VerifyIsNotNull(shippingAddress, nameof(shippingAddress));

         this.lines = lines;
         this.shippingAddress = shippingAddress;
      }

      /// <summary>
      /// Gets the order lines of the request.
      /// </summary>
      public IReadOnlyList<OrderLine> Lines => lines;

      /// <summary>
      /// Gets the order shipping address of the request.
      /// </summary>
      public Address ShippingAddress => shippingAddress;
   }
}

```

**Comment by masnider** [comment]
@Izzmo - what are the differences between the two environments? In the unit tests, what's injected/mocked?  In the tests that pass, is there actual replication? Does the same code work when there's > 1 replica?

**Comment by Izzmo** [comment]
@masnider thanks for responding. So, this is a _very basic_ example where we aren't testing against anything in service fabric explicitly, so no mocks are needed.

As far as a call diagram goes, this specific `OrderRequest` class is being setup by a WebApi Controller and then passed into the microservice via a proxy. The microservice is a stateful service with 3 replicas.

Web Request -> Route to Controller -> Pass in `OrderRequest` model -> Pass to Service Proxy class <-> Communication to microservice (breakpoint never reaches entry point into the microservice)

So, to answer your question, _no this does not work when there's greater than 1 replica_.

**Comment by mcoskun** [comment]
Hi @Izzmo , does it work if you change your unit test CreateOrderLines to return a ReadOnlyCollection<OrderLine> instead of List<OrderLine>?

**Comment by mcoskun** [comment]
I do not think so. The object being serialized was of different type in the unit test than production service and hence they needed two Known Types. Now you are using the same type in production and unit test hence second Known Type is not needed.

**Comment by Izzmo** [comment]
@mcoskun `List<OrderLine>` and `ReadOnlyCollection<OrderLine>` both share inheritance for the `IReadOnlyList<OrderLine>`.

Seems odd this wouldn't work.. but I guess this is the downside of serialization with generics.

**Comment by Mardoxx** [comment]
Lines.lines on tests will return List in tests. Lines.lines in prod would return readonly collection. I think this is what serialiser looks at - the concrete type. Herein lies the problem I think?

**Comment by Izzmo** [comment]
@Mardoxx that is definitely correct, but with inheritance and generics, you would hope it could be a little more intelligent and go down to the most basic level which both interfaces adhere to. Nonetheless, just something to be aware of moving forward!

Going to close this out.

**Comment by Mardoxx** [comment]
I've taken to using concrete types in all my remoting interfaces now, which isn't ideal but it avoids me having issues like [this](https://github.com/Azure/service-fabric-issues/issues/502) again. It would be nice if it was more intelligent, as you say!
