### ISSUE TITLE
Actor Service Build Issues

### ISSUE THREAD

**Issue by techiearun** [Azure/service-fabric-issues#407]
I'm trying to run a sample Service Fabric application which contains one stateful service, one actor service and one statless ASP.Net core web api. I'm trying to call the actor from ASP.Net core service. When i build this project in Visual Studio 2017 Community , I get the following error 

The command ""c:\users\arunp\documents\visual studio 2017\Projects\actorsample\packages\Microsoft.ServiceFabric.Actors.2.7.198\build\\FabActUtil.exe" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\x64\Debug\\Actor1.Exe" /arp:"c:\users\arunp\documents\visual studio 2017\Projects\actorsample\Actor1\bin\x64\Debug\\" " exited with code -1.	Actor1			

Since the error is not saying anything much, its very hard understand what is going wrong.
Any help here ??

**Comment by carl-ashby-silvertech** [comment]
Did you ever resolve this issue? I'm seeing the same thing.

**Comment by amanbha** [comment]
@techiearun Could you run the command on a cmd prompt and share the error. also please share the Actor1.exe or its code.

**Comment by carl-ashby-silvertech** [comment]
Moments after posting my comment i noticed that there were Exceptions from FabActUtil in the Build Output window. Resolving the issue below allowed the build to succeed.  

System.ArgumentException: Method 'DecompressFile' of actor interface 'xxxxxxxxxxxxxxxxxxxx' has out/ref/optional parameter 'xxxxxxxxxxxxxxx'. The actor interface methods must not have out, ref or optional parameters.

**Comment by amanbha** [comment]
@techiearun is this resolved for you?

**Comment by VipulM-MSFT** [comment]
We will be closing this issue. If this is not resolved, feel free to re-open or create another issue.
