### ISSUE TITLE
Publish-UpgradedServiceFabricApplication Action=Upgrade bug

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/service-fabric-issues#408]
When doing Action=Upgrade in this PowerShell script, and there is an update error, the script shouldn't try to do an unregister inside catch block. This fails in my scenario as the package is in use by another app.

There's 2 bugs to fix:
a) Don't execute Unregister-ServiceFabricApplicationType in upgrade catch block when Action=Upgrade (ie. it should only do it if Action=RegisterAndUpgrade as no registration was performed)

b) Don't hide the original exception that occurred within the try block. By doing (a) above, if this action fails, one's left into the dark as to why the upgrade failed - i.e. do something like Write-Error $_.Exception|format-list prior to invoking Unregister-ServiceFabricApplicationType
Note: I'm not a Powershell guru...so maybe you want to log the error differently...

Originally opened here: https://github.com/Microsoft/vsts-tasks/issues/5014

**Comment by masnider** [comment]
@MikkelHegn - is there any workaround in the meantime and is there anything on the SF side that we should improve, or is this here just as an FYI?

**Comment by MikkelHegn** [comment]
Workaround is described in the linked issue

**Comment by MikkelHegn** [comment]
@amanbha
