### ISSUE TITLE
Run Service Fabric cluster inside Docker container

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#409]
Is that possible to run Service Fabric cluster inside Docker container?

We're developing microservices application using Azure Service Fabric. There are a few Web API microservices that runs on SF cluster (OnPremise). Now we need to create something like Docker container with SF cluster and run there out application. It should be done for out front-end developers that work on Mac and do not want to install SF cluster

When shoud be the first step? Download one of Docker image, but witch one? _microsoft/windowsservercore_ or _microsoft/mssql-server-windows-expressand_ or maybe other? Then how to install Service Fabric to the image? If someone has the same problems and found the solution please help

I know that I can run Docker container inside Service Fabric, but I need completely opposite solution.

Thank you in advance

**Comment by mani-ramaswamy** [comment]
Not today. However, we're working on enabling this for Mac/Linux.

**Comment by nareshkhatri81** [comment]
is there any release date for this ?
is that going to be available for windows as well ?

**Comment by stachen** [comment]
I'm too, wondering if running service fabric cluster inside Docker container is on the roadmap

**Comment by mani-ramaswamy** [comment]
We'll blog about this in a bit, but here you go: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-local-linux-cluster-windows

We aren't currently to run a Windows development environment inside a container. 

Closing the issue - please reopen as appropriate.
