### ISSUE TITLE
Question on configuration files

### ISSUE THREAD

**Issue by Izzmo** [Azure/service-fabric-issues#410]
Looking for an opinionated response on configuration files.

## Scenario
Let's say we have a stateful service with a static repository of some kind which stores color values. It's very simple and is a dictionary of a color name and hex code.

Now, let's say our business requires us to update this list by modifying it some way, either by adding or removing items or updating some as well.

Right now we have this data stored statically in a class underneath the stateful service (which uses reliable dictionaries).

## Question
**Would it be wise to instead store this data in configuration?** Then it wouldn't be a code update but a configuration update.

**Comment by Mardoxx** [comment]
Store the dictionary in some persistent storage (Azure table storage) - have an internal only endpoint that triggers a get of the dictionary and caches it closer to the service (reliable dictionary).

**Comment by Izzmo** [comment]
@Mardoxx we could do that, and that would work, but we are trying to _not use table or SQL storage_ right now in favor of keeping data in code if possible. This dataset isn't large, it's only 50 entries, with the possibility of going to maybe around 500.

I'm just wondering if this is a good design pattern or not since the dataset is relatively small.

**Comment by Mardoxx** [comment]
Have an endpoint that you post a json/serialized document to then update your dictionary?

Good question aboit the configuration package though

**Comment by Izzmo** [comment]
> Have an endpoint that you post a json/serialized document to then update your dictionary?

I don't think we would want to expose an end-point for updating the data since it's just static data in the code.

**Comment by vturecek** [comment]
@Izzmo Yes this is exactly what config packages are for. Unlike an external data store, a config package is local to your code (no network requests necessary) and upgraded using the same SF APIs you use to upgrade your services (and it's a rolling upgrade so if you make a change that causes your service to crash, SF will automatically roll it back).

**Comment by masnider** [comment]
@Izzmo - Does this answer your question? I'm with Vas - I'd also be keeping this in a config package and deploying changes alongside your code via upgrades.

**Comment by Izzmo** [comment]
I think so, I'll try it out and see how it goes. Thanks!
