### ISSUE TITLE
Backup file format

### ISSUE THREAD

**Issue by aL3891** [Azure/service-fabric-issues#411]
Hello,
On the last standup you mentioned working on a backup "viewer" that, as I understood it, would allow you to look in a backup file and see what's in there.

Is the backup file format specified somewhere right now? if not that would be useful to have, if not as a full spec just having some code/class to be able to read it would be great (that's what I want in the end anyway)

Right now i'm working on a custom backup solution for actors that would allow you to restore actor services to clusters with different partition counts, but while it will have some special properties like enabling live migrations (by having the new cluster request data from the old on an ondemand basis) it seems like the best solution for the initial restore would be to just use the built in backup file format.

On a related note, it would be very useful to be able to get a stream(or even some higher level data structure) back from/to the backup/restore and not just a directory, we have a lot of io in our solution and being able to stream backups directly to where they're going would be very nice

**Comment by masnider** [comment]
@aL3891 It's not written down anywhere at this time and I don't think we have an intention to until we finish some other work. Adding some people who could comment. I'll also mark this as a feature request/enhancement for your last item.

**Comment by aL3891** [comment]
np, i understand, if there some basic hints about the format you could share though that'd be cool though, 
like is it just a compressed stream of xml or a binary serialization of some internal data structure or something like that :)

**Comment by mcoskun** [comment]
It is binary serialization. We do not plan to expose the format, but we are considering to expose a library and a tool that allows you to read it.

**Comment by aL3891** [comment]
Great to hear, such a library would be very useful, especially when doing things like changing the number of partitions
