### ISSUE TITLE
"Error" state because of slowly starting service

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#415]
Hi guys,
I try to run a python application as service fabric guest executable and it's running ok, but because I have to run some scripts first, the startup time is a bit longer (~ 1 Minute).

During this time Service Fabric displays the service in an error state, altough the service hasnt started yet.
Is it possible to increase the "allowed" startup time before stating that the service has an error?

**Comment by appi101** [comment]
Thank you for your question. 

Can you please tell us what are the error health reports? Based on that we can provide the appropriate knobs for configuring them

**Comment by appi101** [comment]
Closing as there was no response
