### ISSUE TITLE
Addressing stateless services externally using the fabric:/ address scheme.

### ISSUE THREAD

**Issue by ctrlaltdan** [Azure/service-fabric-issues#416]
My company would like the ability to deploy many public facing stateless service instances to our nodes without having to specify a port number for the service.

It seems that Service Fabric already supports the ability to route traffic using the Naming Service by the known fabric address. It also supports mapping to DNS names through the DNS Service. Either of these options seem pretty well suited to our requirement.

I've had a pretty thorough search on the internet trying to find a way to address these services externally using some form of Layer 7 stack (ideally using Application Gateway) but I'm drawing a blank.

I have found the [following article](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-quick-start) showing how the API Management product has integrated with Service Fabric. It seems the Azure team have a perfect working implementation here but no documentation on how to achieve this setup using an alternative gateway.

Is there any reference material for how we can configure a product such as Application Gateway to suit our needs?

Many thanks

**Comment by masnider** [comment]
@ctrlaltdan [Traefik ](https://docs.traefik.io/v1.7/configuration/backends/servicefabric/) has some integration which you might be either to use or leverage as a pattern for other gateways. I haven't seen many people use AppGW itself and am not sure what capabilities it provides in terms of backend plugins or URI rewriting, but if it does then you could do something similar to what Traefik and APIM are doing. Another doc that might be useful is [this one](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-and-communicate-with-services).

I hope this answers your question. If you have additional questions, please feel free to open a new issue.
