### ISSUE TITLE
Add-AzureRmServiceFabricClusterCertificate : Code:VMExtensionProvisioningTimeout

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-issues#419]
Attempting to run the Add-AzureRmServiceFabricClusterCertificate command, using -SecretIdentifier parameter with certificate published to Azure Key Vault.

After more than an hour, I received this output in PowerShell:

_**Add-AzureRmServiceFabricClusterCertificate : Code:VMExtensionProvisioningTimeout, Message:Provisioning of VM extension 'VsDebuggerService-a0rq8lmmp7' has timed out. Extension installation may be taking too long, or extension status could not be obtained.**_

What is the normal time it should take to process this command? If it is an hour or more, perhaps the documentation should explain this:

https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/add-azurermservicefabricclustercertificate

**Comment by sondreb** [comment]
Attempted 4 times, same issue. I presume I would have to take this with Microsoft Azure Support?

**Comment by masnider** [comment]
@sondreb yeah do that if you haven't already Adding some folks to take a look as well and see if they can offer more information or improve the PS experience.

**Comment by ChackDan** [comment]
This has nothing to do with the PS command. file an issue with the owner of "VsDebuggerService-a0rq8lmmp7" extension.  It is having issues and not installing properly and on time. The VMSS has a timeout for extension deployment - I think it is 30 mins.. If the owner thinks that the extn code is fine, then file a CSS ticket for the VMSS team.

**Comment by sondreb** [comment]
The extension was most likely installed after remote debugging the Azure Service Fabric cluster from Visual Studio. Looking at the automation script generated in the Azure portal, I can see the extension listed:

```
        {
                                "properties": {
                                    "publisher": "Microsoft.VisualStudio.Azure.RemoteDebug",
                                    "type": "VSRemoteDebugger",
                                    "typeHandlerVersion": "1.1",
                                    "autoUpgradeMinorVersion": false,
                                    "settings": {
                                        "clientThumbprint": "[SNIP]",
                                        "serverThumbprint": "[SNIP]",
                                        "connectorPort": [SNIP],
                                        "fileUploadPort": [SNIP],
                                        "forwarderPort": [SNIP],
                                        "forwarderPortx86": [SNIP]
                                    }
                                },
                                "name": "VsDebuggerService-97to0488gh"
}
```

This extension is listed in the same section as the "ServiceFabricNode" extension.

And looking at that extension, it appears to be both:

"certificate" and "certificateSecondary", but under the "Cluster certificates" section on the Service Fabric blade, only the first certificate appears. So looks like it has partly saved the settings but not entirely.

Running Service Fabric: 5.7.198.9494

Attempted to find some instructions on how to clean up after remote debugging (it will auto-create Azure Key Vault, etc) to see if that might help fix the issue, but could only find this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#debug-a-remote-service-fabric-application

**Comment by sondreb** [comment]
I ran the "Disable Debugging" command from the Cloud Explorer within Visual Studio 2017, it processes for a while and gave some sort of error message. But apparently it did run for a while and after that, the "VsDebuggerService" extension in the cluster ARM template ("Automation script") have disappeared. It's probably a year since remote debugging was run against that cluster.

Hopefully it should work to run the PS command now, I will verify on Monday.

**Comment by sondreb** [comment]
After running the "Disable Debugging" from Cloud Explorer in Visual Studio, it appears to have removed the VsDebuggerService from the virtual machines in the cluster, and now the PS command to add the certificate worked (takes more than an hour to run).

So if anyone in the future see a similar issue, make sure you just run the Disable Debugging if you have ever run remote debugging against the cluster.

![image](https://user-images.githubusercontent.com/309938/29766860-8b4abd30-8be0-11e7-9176-1d790e3c01f1.png)

**Comment by aL3891** [comment]
That's some detective work right there, we had the same issue but ended up rebuilding the cluster, and azure support was not able to find the solution either.

Great to know there is a potential workaround if we run in to it again

**Comment by MikkelHegn** [comment]
@dbreshears @QingChenmsft Can you please coordinate the troubleshooting to figure out where to fix this? Thanks.
