### ISSUE TITLE
FabricTypeHost.exe crashes on Windows 7

### ISSUE THREAD

**Issue by nesherhh** [Azure/service-fabric-issues#42]
FabricTypeHost crashes on Windows 7

Faulting application name: FabricTypeHost.exe, version: 5.1.150.9590, time stamp: 0x5751635d
Faulting module name: ESE.dll_unloaded, version: 0.0.0.0, time stamp: 0x524f002d
Exception code: 0xc0000005
Fault offset: 0x0000000053ba06eb
Faulting process id: 0x37b8
Faulting application start time: 0x01d1d198ad229f8f
Faulting application path: C:\SfDevCluster\Data_Node_3\Fabric\Fabric.Code\FabricTypeHost.exe
Faulting module path: ESE.dll
Report Id: eae09fb1-3d8b-11e6-89c6-989096e22564

Crash is in ese.dll. ESE.Dll loads the library api-ms-win-core-debug-l1-1-0.dll, then tries to find there a function AddVectoredExceptionHandler. It fails, because it absent in Windows 7. So it tries to unload the dll and crashes inside FreeLibrary function.

No issues on Windows 10.

**Comment by KevinOrtman** [comment]
Experiencing the same issue

**Comment by VipulM-MSFT** [comment]
Not all features are supported on Windows 7. Guest executable and reverse proxy are the known functionality that are not supported in Windows 7.
