### ISSUE TITLE
Tray icon app problems after updating to SDK 2.7.198

### ISSUE THREAD

**Issue by antogh** [Azure/service-fabric-issues#420]
After upgrading to the new sdk the tray icon app is having some problems.

On my win10 pro physical dev machine when I power on the pc and I right click the SF tray icon for the first time it  takes minutes to display the menu, then when it appears I select "setup local cluster" the "5 nodes" and I get the message the cluster was already setup. Since then the tray icon works quick and smoothly as in the past. Maybe as a workaround if I could call a script or exe on startup that does the same job  "setup local cluster" does I could avoid waiting minutes for the menu to appear and have the tray icon responsive from start. You can see the steps I described in this screen capture:

![alt text](http://i.imgur.com/6zKfAyd.png)

On my win 2012R2 server Azure VM I had even worse problems. After the upgrade the tray icon was not able to set up or reset the local dev cluster. It took minutes working , just to notify in the end that couldnt perform the action because errors occured. I tried many times, restarted the VM, same problems. Then I created another VM from the same origin (a previous vm capture) applied the upgrade, same problem with tray icon :( At that point I tried to set up the cluster in another way and using the powershell command:

`& "$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1"`

finally worked

It seems there are some issues with the tray icon app, but SF is working fine. I find quite handy the tray icon, it would be nice to have it working like in the past.

Thanks for reading 
Antonio

**Comment by amanbha** [comment]
HI @antogh  Do you still see issues with the Systray tool?

**Comment by antogh** [comment]
Hi @amanbha 
yes I still have the same issue , but honestly didnt upgrade the software since i created this post
Is there any sw update available that could fix this?
How can i check my current version to compare with what is available now?

**Comment by antogh** [comment]
also the win 2012R2 VM  is 3.0.480 

can you help me to set up the cluster in a way that starts automatically at power on?
As i said in this VM if its restarted for any reason the cluster starts in a stopped status and stays like this until someone log in and click on "start" from the tray icon, this is very annoying and creating hiccups / blocked services on a demo machine that should possibly stay always responsive . Thanks

**Comment by amanbha** [comment]
Thanks for verifying @antogh . You mentioned 2 issues: 1) Menu taking long time when you right click on it. 2) When you click to create cluster, it says cluster is already created. Are both of them happening now?
Could you also query the state of FabricHostSvc when this happens.  sc query FabrichostSvc

**Comment by antogh** [comment]
thanks @amanbha 
yes 2 issue on 2 separate machines , the long delay on win10 pro , the cluster to start manually on win2012 server

on win10 now the state is 
SERVICE_NAME: FabrichostSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0


on win2012 
SERVICE_NAME: FabrichostSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by antogh** [comment]
the state corresponds to the real situation, in win10 machine the cluster is stopped 
in win2012 I started it manually this morning from the tray icon, after discovering the server was auto restarted for upgrade and my demo was down / not available to my customers 😞

**Comment by amanbha** [comment]
Thanks for sharing the info.
Reg your question on how to start cluster automatically on a reboot:
Once you setup the cluster, you can set the FabricHostSvc to start automatically by running from admin command prompt: sc config FabricHostSvc start=auto
This will start the cluster after reboots automatically.

**Comment by antogh** [comment]
thanks @amanbha thats a great relief (the auto start) I will try and update here

what about the long delay , only in win10 pro I believe, the server is not showing this issue it seems...

**Comment by antogh** [comment]
unfortunately I have to leave now, but it was great to have this real time exchange of info, very useful, thanks

Later or tomorrow I will do further tests and update this thread, I guess the issue2 should be solved (thanks to your advice) and the issue1 is still alive and need to be solved , but I will be more precise later.

**Comment by antogh** [comment]
sorry @amanbha just a quick last question before I leave , 
I noticed in  my original post when I created the issue I mentioned I just upgrade to SDK 2.7.198  , then I checked now and I have the 3.0.480 on both machines, but I dont remember I ever updated the SDK . 
Does the SDK upgrade automatically with windows update?

**Comment by amanbha** [comment]
AFAIK its not updated by itself. If you want more info or still having issues with this, we can have skype call, you can send me the request at amanbha@microsoft.com

**Comment by antogh** [comment]
thanks @amanbha 
you gave already a great help 
we will stay in touch either here or skype if needed 
I will update soon my findings
I am confident we will clarify all the issues

**Comment by antogh** [comment]
Hi @amanbha,
I made some tests and I wanted to report you the results.

On the win 2012R2 VM everything works fine, the tray icon is functional and responsive right after the power on.

On the win 10 pro phisical machine there is a problem with the tray icon, after power on it takes minutes to show the right click menu. The issue is described very well with pictures in my first post in this thread. After performing the steps described in my 1st post the problem disappear, so it's only affecting the 1st time usage after power on. 

I tried the query command you suggested before and after the issue, result is identical for what i can see

C:\Windows\System32>sc query FabricHostSvc

SERVICE_NAME: FabricHostSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\System32>sc query FabricHostSvc

SERVICE_NAME: FabricHostSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

It seems like the tray icon app after power on is decoupled from the service and cannot communicate well, the after 1st usage it goes ok. 

The problem is only showing on this win 10 machine, since I upgraded to SDK 2.7.198, before was working fine. Both win10 and win2012 have same SF SDK versions and VS2017 version.

It's a bit annoying but I can live with it. I thought anyway it could hide a bigger problem so I opened this issue to make you aware of it.

Another cocnern that came out of this thread is how my machines have upgraded to latest SF apparently automatically, I don't remember doing an update manually. If you can ask your team coworkers if in any case SF SDK can be updated automatically through windows update, that would be interesting to me to know. I like to know the inner working of important tools like SF I rely on for important projects. Thanks.

**Comment by amanbha** [comment]
@antogh  I have confirmed with my team, the SDK is not upgraded automatically.. For the 1st issue, when you set the serviced to auto using  sc config FabricHostSvc start=auto, does it still happens?

**Comment by antogh** [comment]
@amanbha 

>  I have confirmed with my team, the SDK is not upgraded automatically..

Next SDK upgrade I will check and eventually report here/you

> For the 1st issue, when you set the serviced to auto using sc config FabricHostSvc start=auto, does it still happens?

Just checked, the local cluster does start at power on (all the services work) but the tray icon problem persists, ~ 3 minutes to display the menu , start/stop grayed out, only option setup cluster, I click it , it says already setup and from then on it works fine .

**Comment by antogh** [comment]
@amanbha 
forgot to ask:
is there a document describing all the commands I can give with the 
sc config FabricHostSvc ...

**Comment by antogh** [comment]
@amanbha 
weird messages at power on also in the windows notification area

![sf_icon_problem](https://user-images.githubusercontent.com/8667587/38826062-fd6d9f5c-41ae-11e8-8c4f-7e406097bcde.png)

it happens only on this machine win 10 pro, the win 2012 r2 server works fine

**Comment by amanbha** [comment]
@antogh  Reg. sc config: is standard command to manage NT Services, FabricHostSvc is just another service so all those commands apply to it  Reg. the issue: it looks like on power-on its taking sometime to get the current state on Windows 10 Pro. Could you share the traces from C:\SfDevCluster\Log\Traces and the time when you see the issue?

**Comment by antogh** [comment]
Hi @amanbha , sorry for the delay , the file is too big, I'll share it on one drive tomorrow.

**Comment by antogh** [comment]
Hi @amanbha 
here is the file you requested
hope you can find some useful info inside
https://1drv.ms/u/s!Ajx3UQDAY502gcU7SPB0Eh4b91Tkow

**Comment by amanbha** [comment]
Thanks for sharing it @antogh . Could you also share the time (and time zone) when you saw this issue.

**Comment by antogh** [comment]
the picture I posted above shows one time it happened, as you can see in the  in the notification area it is  16 apr-18 19:16 (italy time)

otherwise another time might be few minutes after the power on this morning, UTC time extracted from event viewer:
<TimeCreated SystemTime="2018-04-18T07:09:48.029523100Z" />

**Comment by antogh** [comment]
Hi @amanbha 
I have installed the SF SDK 3.2.162 because I wanted to play with the new SF mesh and I noticed that the problem has totally disappeared. The icon menu is always super fast and responsive since the first power on. 
For this reason I close the issue. The solution is to install the new SF version. 
Thank you for all the support

**Comment by amanbha** [comment]
@antogh that's great to know, thanks for the update!
