### ISSUE TITLE
Unregister an app does not delete dns name

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#422]
Unregister an application does not always delete the dns entry. Because of that, it is not possible to publish the app again. Any help how to manually flush/delete dns entries?

**Comment by dealboy** [comment]
we have the same issue for an on premise SF installation (5.6.220.9494).
Only workaround found so far, restart all the nodes from the SF Explorer

**Comment by milvuko** [comment]
The C# code below deletes the service DNS name:
        static void DeleteServiceDnsName(string clusterEndpoint, string serviceDnsName)
        {
            Uri name = new Uri("fabric:/System/DnsService");
            System.Fabric.FabricClient client = new System.Fabric.FabricClient(clusterEndpoint);
            client.PropertyManager.DeletePropertyAsync(name, serviceDnsName).Wait();
        }

Example how to delete DNS name "my.dns":
       DeleteServiceDnsName("127.0.0.1:19000", "my.dns");

**Comment by milvuko** [comment]
Fixed in SF v6.1.
