### ISSUE TITLE
Invalid attribute (Hostname)

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#424]
According to the documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-securing-containers) it is necessary to set the hostname attribute to enable gmsa. Nevertheless, the attribute is not part of the xsd and the validation of the package fails. In fact, the attribute is not necessary at all. The securityoption node is all it takes.

**Comment by masnider** [comment]
@erikadoyle can you confirm with the engineers if this is required or not and update the docs? @dragav fyi

**Comment by Abdruggi** [comment]
In the meantime the parameter has not only  become part of the xsd but it is also necessary.
