### ISSUE TITLE
service fabric service runtime error netstandard 2.0 

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#427]
**Could not load file or assembly 'netstandard, Version 2.0.0.0 ...'**
I am updating our projects to use EFCore 2.0 and I am having difficulty with the assemblies.

I am using A Stateful Service Project targeting 4.6.1, which should be compatible?
ServiceFabric 5.7.198
ServiceFabric.Services 2.7.198
I've made reference to NETStandard.Library.

Strangely enough I have not encountered this problem with the ASP.Net Core Web projects being converted. I notice that the project structure is quite different between them maybe I am missing an XML directive?

**Comment by ashishnegi** [comment]
Please see if https://github.com/dotnet/standard/issues/328 thread' solution fixes this.
This does not look like a ServiceFabric issue.

**Comment by ConX-Ryan** [comment]
I eventually fixed this having to manually overwrite the .csproj file xml with the new project format.
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
</Project>`

That was enough to get me started. 
This should be an opt in migration i feel that should be handled by the IDE?

**Comment by Mardoxx** [comment]
What was your csproj file like before you modified it?

**Comment by ConX-Ryan** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Microsoft.Net.Compilers.2.2.0\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.2.2.0\build\Microsoft.Net.Compilers.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```

the old format

**Comment by ThiemeNL** [comment]
Found the same issue here: https://github.com/Azure/service-fabric-issues/issues/412

Any update on this? Do I need to manually upgrade my csproj to the new format for my actors?

**Comment by ravipal** [comment]
@ThiemeNL how is your actor project references the netstandard assemblies? Can you please share your project files?

**Comment by ravipal** [comment]
The latest nuget package (1.6.4) has the fix. Please add the property <PackageOutputFolder>true</PackageOutputFolder> to *.sfproj to change the package behavior that will include all the files from output folder.

**Comment by abatishchev** [comment]
I'm using 1.6.6 and having both `<PackageOutputFolder>true</PackageOutputFolder>` and `   `DependsOnNETStandard>true</DependsOnNETStandard>` doesn't seem to resolve this issue.

**Comment by ashishnegi** [comment]
@abatishchev What is your csproj structure ? See if [comment](https://github.com/Azure/service-fabric-issues/issues/427#issuecomment-326240689) helps you.

**Comment by abatishchev** [comment]
I don't see this working in default VS 2017 template for SF app with one stateless service (ASP.NET Core on .NET Framework) with both MSBUild package 1.6.6 and 1.6.4:

Application sfproj:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets=";ValidateMSBuildFiles">
  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>48634df0-846b-4d54-bb93-b1c25d27ee69</ProjectGuid>
    <ProjectVersion>2.1</ProjectVersion>
    <MinToolsVersion>1.5</MinToolsVersion>
    <SupportedMSBuildNuGetPackageVersion>1.6.4</SupportedMSBuildNuGetPackageVersion>
    <TargetFrameworkVersion>v4.7.1</TargetFrameworkVersion>
    <PackageOutputFolder>true</PackageOutputFolder>
    <DependsOnNETStandard>true</DependsOnNETStandard>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Web1\Web1.csproj" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" />
  <PropertyGroup>
    <ApplicationProjectTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Service Fabric Tools\Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.targets</ApplicationProjectTargetsPath>
  </PropertyGroup>
  <Import Project="$(ApplicationProjectTargetsPath)" Condition="Exists('$(ApplicationProjectTargetsPath)')" />
  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />
  <Target Name="ValidateMSBuildFiles">
    <Error Condition="!Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" Text="Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
    <Error Condition="!Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" Text="Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
  </Target>
</Project>
```

Service csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.1.283" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.1.283" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
  </ItemGroup>

</Project>

```

Output:

- \Application1\Web1\bin\Debug\net471\win7-x64
- \Application1\Web1\bin\Debug\net471\win7-x64\refs
- \Application1\Application1\pkg\Debug\Web1Pkg\Code

Neither contains netstandard.dll. Probably I'm doing something wrong, please suggest.

**Comment by abatishchev** [comment]
So the problem/solution is that if I switch to net462 then the output contains netstandard.dll:

-    \Application1\Web1\bin\Debug\net462\win7-x64
-    \Application1\Web1\bin\Debug\net462\win7-x64\refs
-    \Application1\Application1\pkg\Debug\Web1Pkg\Code
