### ISSUE TITLE
ServiceFabric node time not synchronized?

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#428]
We have now seen that a few events in our system, where one can _only_ come as a result of the other, had their timestamps, which use DateTime.UtcNow, not ordered as such.

The first event had a later timestamp than the following event.
In some cases around a second diff.
What you would expect with the delay in the handling between these events, is that the following event have come a few hundred ms up to a second later. So, the potential diff on the nodes is almost 2 seconds?

This has some implications to us, and we need to know if we should expect that ServiceFabric nodes do not guarantee synhronized time within a cluster?

Is there any plan to make them synchronized, or any way that it can be synchronized in settings?

**Comment by xunlu** [comment]
Service Fabric itself is not involved in synchronizing clocks.
The VMs typically has NTP enabled (which is independent of whether service fabric is deployed).  The precision of NTP is limited and it is a best effort algorithm meaning it can't provide any guarantee.  Clock skew of a few seconds is very normal.
