### ISSUE TITLE
Reverse Proxy 404 - FABRIC_E_SERVICE_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by mathlesp** [Azure/service-fabric-issues#429]
The Reverse Proxy will sometime return error 404 - FABRIC_E_SERVICE_DOES_NOT_EXIST when it should not.

see: [https://social.msdn.microsoft.com/Forums/en-US/5992f5a4-74c0-42fc-875a-38477320bd9b/service-fabric-reverse-proxy-404-fabriceservicedoesnotexist?forum=AzureServiceFabric](https://social.msdn.microsoft.com/Forums/en-US/5992f5a4-74c0-42fc-875a-38477320bd9b/service-fabric-reverse-proxy-404-fabriceservicedoesnotexist?forum=AzureServiceFabric)  

Steps to reproduce:

1. In Azure, create a new 5 nodes cluster with the Reverse Proxy enabled (we used image 2016-Datacenter-with-Containers);
2. In VS2017 (with SDK 2.7.198), create a new Service Fabric Application named "SfRp404Test"; 
3. Select the "Stateless ASP.NET Core" template;
4. Then select the "Web API" template (we used ASP.NET Core 2.0);
5. Change "ApplicationManifest.xml" and "ApplicationParameters/Cloud.xml" to set parameter "Web1_InstanceCount" to 1;
6. Deploy the new application to the new cluster;
7. Check on which node the service was deployed and open an RDP session to ANOTHER node (in our test, if the service is deployed to Node0, we RDP to Node2. If it is deployed to Node1, we RDP to Node3)
8. On the node, open Powershell and run:  "wget http://localhost:19081/SfRp404Test/Web1/api/values"
9. You should get a 200 (OK);
10. Now reboot the node and reconnect to it using RDP once rebooted;
11. Run the wget powershell command above again;
12. You should get a 404. If not repeat steps 7-12 (on the same node or another node)
13. If you can still not reproduce the problem, delete and redeploy the application until the service is activated on Node0 or Node1 and then repeat steps 7-12.

This is not 100% reproducible but we can normally reproduce the problem in a few minutes by redeploying the service and rebooting ~random nodes (No need to delete and redeploy the cluster itself).

Here is the template we used to create the cluster and the sample application.
[template and app.zip](https://github.com/Azure/service-fabric-issues/files/1261744/template.and.app.zip)

**Comment by kavyako** [comment]
Do you get the 404 only immediately after the node is rebooted /app is redeployed? What happens if you wait for say 5 -10 minutes after node reboot, is the issue seen even after some time?
What version of service fabric are you on?

**Comment by mathlesp** [comment]
1. We get the 404 anytime after the node is rebooted. However, we mainly did our test right after the node was reported as healthy in the cluster. Sometime the node will fix itself but we have seen the error persist for a long time (hours/days).
2. No issue reported by servie fabric explorer; the app looks healthy;
3. Both the cluster and the app are on the latest version (5.7.198.9494/2.7.198);

Resolving the service using "Get-ServiceFabricApplicationName -ServiceName [servicename]" on the failing node will always fix the issue (until the node is rebooted).
Redeploying the app will often fix the issue (until the node is rebooted).

**Comment by kavyako** [comment]
I am still unable to repro this issue. 
Could you open a support ticket so we can look at the traces to analyze what is going on, with info about the node that was rebooted and the reboot time.

**Comment by kavyako** [comment]
We have identified a bug in the reverse proxy service resolution path that can cause the  FABRIC_E_SERVICE_DOES_NOT_EXIST error.
The fix will be in 6.0 CU1.

**Comment by mathlesp** [comment]
Do you have the version number for 6.0 CU1? I suppose it is not in 6.0.211 yet right?
Thanks

**Comment by kavyako** [comment]
Actually the fix made it to 6.0. Will you be able to check if it fixes the issue you mention above?

**Comment by mathlesp** [comment]
From our preliminary tests, it looks like this issue is indeed fixed. 

Thanks

**Comment by kavyako** [comment]
Thanks for getting back! Closing the issue now.
