### ISSUE TITLE
Issue in Reporting of Custom Health Report TTL

### ISSUE THREAD

**Issue by phil000** [Azure/service-fabric-issues#43]
We make a custom health report where the TTL is clearly 90 seconds in the .NET HealthInformation class and also the corresponding NativeTypes.FABRIC_HEALTH_INFORMATION.

When the health event shows up in the Service Fabric Explorer (web portal) the TTL has changed to 1 day and 1 hour.

PowerShell Get-ServiceFabricDeployedApplicationHealth shows the correct TTL as 90 seconds.

Service Fabric Explorer (desktop app) also shows 90 seconds correctly.

Attached x4
![att1](https://cloud.githubusercontent.com/assets/9067236/18190497/73152e88-7117-11e6-8fed-477dec1ae7a9.png)
![att2](https://cloud.githubusercontent.com/assets/9067236/18190499/731e1bc4-7117-11e6-8faf-8f582b9a140d.png)
![att3](https://cloud.githubusercontent.com/assets/9067236/18190496/7314d500-7117-11e6-9b39-067d1cd2d2b5.png)
![att4](https://cloud.githubusercontent.com/assets/9067236/18190498/7317389a-7117-11e6-84ac-7ab39a5f0d2e.png)

**Comment by phil000** [comment]
Service Fabric 5.1.150.9590
SDK: 2.1.150.9590

**Comment by masnider** [comment]
There's been several changes to make sure that timecodes like this are correctly translated through all layers. Is this still happening with the 5.2 runtime/2.2 sdk?

**Comment by phil000** [comment]
With SDK 2.2.207.9590 (fabric:/System/ClusterManagerService 5.2.207.9590) everything is ok and the TTL is showing well in SFX web.

TTL: 0.00:01:30

**Comment by masnider** [comment]
All right! Glad things are working as expected and sorry for the bug.
