### ISSUE TITLE
Unable to reset scaleset VM password during a cluster upgrade

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#430]
On every cluster upgrade my organisational policy and need is to change the VMSS Machine passwords.
This was working fine for sometime in the past and lately failing with the bellow error,

  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "adminPassword",
    "message": "**Changing property 'adminPassword' is not allowed**."
  }
}'

**Comment by cardanoteamcity** [comment]
Any chance this could be expedited? We really need to rollover passwords in our deployments and we presently cannot without completely redeploying the scaleset. This is pretty bad.

**Comment by dbsanfte** [comment]
Any chance this could be expedited? We really need to rollover passwords in our deployments and we presently cannot without completely redeploying the scaleset. This is pretty bad.

**Comment by gbowerman** [comment]
See [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#extensions](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#extensions) under "How do I reset the password for VMs in my virtual machine scale set?"

**Comment by rajaprad** [comment]
@gbowerman , thanks for the details, however my VMSS is defined in an ARM Template (**SERVICE FABRIC** - Issue created under SF) and the error is from ResourceGroup Deployment. This feature was working sometime back and has stopped working from ResourceGroup deployment. Following another process to update the password outside of one single integrated deployment would cost time and additional steps.

**Comment by gbowerman** [comment]
It has never been possible to change the adminPassword property of a VM scale set. To change this via ARM it has only been possible to do this using a VM extension like VMAccess.

The ability to update this VMSS property will be added soon, though even then the change would only apply to new and reimaged VMs. To change the admin password of existing VMs it would be necessary to do this at the OS level (e.g. manually or scripted).

**Comment by ig-sinicyn** [comment]
Any update on this?
I've tried to apply VMAccess extension via ARM template,
```
							{
								"name": "Microsoft.Compute.VMAccessAgent.Rdp",
								"properties": {
									"publisher": "Microsoft.Compute",
									"type": "VMAccessAgent",
									"typeHandlerVersion": "2.3",
									"autoUpgradeMinorVersion": true,
									"settings": {
										"UserName": "[parameters('deployData').deployment.adminUserName]"
									},
									"protectedSettings": {
										"Password": "[parameters('currentRdpKey')]"
									}
								}
							}
```
but deployment spins for a hour and fails with `Provisioning of VM extension 'Microsoft.Compute.VMAccessAgent.Rdp' has timed out. Extension installation may be taking too long, or extension status could not be obtained` message.

**Comment by gbowerman** [comment]
@ig-sinicyn it's hard to determine the problem based on this packet. Have you tried adding a VMAccess extension using PowerShell as described in the VMSS FAQ? [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#extensions](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#extensions)

**Comment by ig-sinicyn** [comment]
@gbowerman It turns out the issue was the name of the extension. It finally worked with `"name": "Microsoft.Compute.VMAgent"` but fails with any another name.

**Comment by gbowerman** [comment]
Thanks @ig-sinicyn I'm glad you got it working. We do plan to improve this experience.

**Comment by rajaprad** [comment]
@gbowerman - i disagree with stating that VMSSPassword reset never worked from template. I have been handling VMSSScaleset deployments using ARM Template for the past two years and it has stopped working for the past 4-5 months may be. Before that i was able to change the password- any number of time using New-AzureRmResourceGroupDeployment from ARM Template.

**Comment by rajaprad** [comment]
@ChackDan - Please help and advice. If this is treated as a new feature (which was actually working sometime back) in the pipeline, why cant this bug be added to the milestone? Thanks!!

**Comment by gbowerman** [comment]
@rajaprad we've been wanting to add the ability to update the admin credentials in the scale set model since scale sets first GA'd in March 2016, and it has not been possible. As the PM for scale sets I can assure you of this. The good news is we've checked in code to do it recently, and it should be possible starting in November.

**Comment by masnider** [comment]
@rajaprad & @gbowerman - can you open an issue over on https://github.com/Azure/vm-scale-sets/issues to track this, and then add a link back to that here?

**Comment by rajaprad** [comment]
@masnider - Added issue here - [https://github.com/Azure/vm-scale-sets/issues/38](url)

**Comment by gbowerman** [comment]
Closing issue. It is now possible to change the admin credentials of a VM scale set. See the VMSS FAQ [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#compliance-and-security](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#compliance-and-security)
