### ISSUE TITLE
API Management host resolution

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#431]
We're using the Service Fabric + API Management integration and have a couple of services which are called rarely, however when they are called, we'd need them to respond promptly.

Right now, if the service is moved, it takes a long while to detect and our clients time out.

```
service-fabric-backend (21,026.702 ms)
{
    "messages": [
        "Unable to connect to the remote server",
        "Error occured while calling backend service.",
        "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.0.0.5:58450"
    ]
}
```

Is there any configuration of the integration we can tweak to actively scan for host addresses or reduce the timeout period so it'll more aggressively try and re-resolve?

**Comment by maksimkim** [comment]
@NickDarvey, there's no proactive probing in API-M. 
You can use timeout property on forward-request policy to control outgoing request timeout:
https://docs.microsoft.com/en-us/azure/api-management/api-management-advanced-policies#ForwardRequest 

However, on your set-backend-service policy you need to put corresponding logic in sf-resolve-condition property in order to make sure API-M re-resolves in case of such timeout. Probably you don't want API-M to re-resolve on each and every timeout cause it might happen even if service was not moved but just responds slowly. So you might want to do this conditionally for specific api/operation/url etc.

**Comment by rishirsinha** [comment]
@NickDarvey, did this resolve your issue?

**Comment by NickDarvey** [comment]
That'll work, thank you.

**Comment by NickDarvey** [comment]
How do we get APIM to re-resolve on a timeout?

The timeout works, 
```
service-fabric-backend (1,011.362 ms)
{
    "messages": [
        "Error occured while calling backend service.",
        "The request was aborted: The request was canceled.",
        "The request was aborted: The request was canceled."
    ]
}
```
however, in the rest of that request and in the next request the `LastError` variable is empty:
```
service-fabric-backend (1,011.362 ms)
{
    "messages": [
        "Error occured while calling backend service.",
        "The request was aborted: The request was canceled.",
        "The request was aborted: The request was canceled."
    ]
}
```

**Comment by maksimkim** [comment]
Hi Nick, 
Did you try to specify 
sf-resolve-condition="@(context.LastError?.Reason == "Timeout")"
on set-backend-service policy?

**Comment by NickDarvey** [comment]
This works. Thanks for that.
(I'm guessing lots of client-facing developers will need to do this so it'd be nice if there were a built-in solution for it.)

**Comment by inzi25** [comment]
I am not using service fabric service. but I'm getting same error.
Can you please share the full policy update code

**Comment by NickDarvey** [comment]
@inzi25 what policy are you looking for?
We're just using the forward request timeout policy, but this is only useful to us to cause the re-resolution of Service Fabric partition. (I'm not sure how helpful it will be to you.)

```xml
<policies>  
    <inbound>  
        <base/>  
    </inbound>  
    <backend>  
        <forward-request timeout="12"/>  
    </backend>  
    <outbound>  
        <base/>          
    </outbound>  
</policies>
```

**Comment by inzi25** [comment]
Thanks @NickDarvey , I have tried this same way but unfortunately this didn't help. Later we have implemented VNET for APIM sorted the issue.
