### ISSUE TITLE
Cluster Node stuck disabled

### ISSUE THREAD

**Issue by CodedBeard** [Azure/service-fabric-issues#436]
I built a new 5.7 Service fabric cluster in Azure (5 Node Silver) which worked fine for the first day. The day after, one of the nodes status changed to "Disabled". 

When I looked at the status, the node reported:
 ``` 
Azure/PlatformUpdate/4c4143fa-4549-42ed-8056-973d82e3e461/2/1

 Node Deactivation Task Type	Repair
```
It has now been 4 days since this status message appeared, and the node has been disabled the entire time. I've tried manually activating the node through cluster explorer and PowerShell, but nothing happens. I've also tried restarting the node, and restarting the underlying host, neither of which has helped.

Is there anyway to force this node back online, or am I going to have to delete the cluster and start again?

**Comment by Mardoxx** [comment]
At least the 3rd person with this issue and invariably the answer is to recreate.
This happened to me too when I was messing around with it 3mo ago or so. I'm using my own standalone cluster for development now, but would love to know a solution for this just in case it happens to me in prod a few months down the line..

**Comment by CodedBeard** [comment]
@Mardoxx Nope, didn't even get to testing scaling operations.

**Comment by AnupVasudevaRao** [comment]
hi, 
Thanks for reporting. Could you please open a support ticket so we could investigate this further. The details we need are: 
a. SF cluster's resource Id
b. Region
c. The approximate time range of this issue.
d. Any custom operations you performed on the cluster before the issue. E.g. scale up nodes etc.

**Comment by CodedBeard** [comment]
Hi @AnupVasudevaRao,
Do you mean log a support request via the Azure portal, or another?

In response to D, no we did not perform any actions on the cluster other than to deploy a compose application onto it, which worked fine when I left work, but when I got in the next day the node was down. At this point I was the only person with access to the cluster, because I had only just deployed it.

**Comment by AnupVasudevaRao** [comment]
yes, from the portal. 
https://portal.azure.com/?#blade/Microsoft_Azure_Support/HelpAndSupportBlade

Here are some additional reference links w.r.t support.
https://azure.microsoft.com/en-us/support/options/ 
https://docs.microsoft.com/api/Redirect/en-us/documentation/articles/how-to-create-azure-support-request/
https://azure.microsoft.com/en-us/status/
https://azure.microsoft.com/en-us/support/faq/

**Comment by CodedBeard** [comment]
Engaged with support, they couldn't work out why the node had gone down and basically just said we had to use a larger VM size, as they incorrectly assumed we were using the default D: drive, which on the vm size is lower than the recommended. Got fed up and trashed the lot, and the new cluster has been working fine for 4 days now.

**Comment by bobeaton** [comment]
on our production cluster where this happened, I was able to fix it by deleting the application/type and redeploying it. The reason it worked for me (I think), is because when it redeployed, it went to another node (we have a 5 node cluster set up, and it was failing on node 4, but it seems to work fine on nodes 1 & 2)... FYI
