### ISSUE TITLE
Question: Does auto-upgrade recreate service listeners?

### ISSUE THREAD

**Issue by hiraldesai** [Azure/service-fabric-issues#442]
The IoC container used by my service fabric services relies on Azure KeyVault to set some application wide credentials (e.g. Database connection string and some other things). I recently noticed that I had to change one of the values in KeyVault to a different value and I was hoping that a subsequent deployment with rolling Auto-Upgrade on the cluster would cause the services to restart and pick up the new settings. However this didn't happen. My questions are 

1. Is this normal? 
2. Is there a way to easily cause the restart to happen without having to remove application and redeploy?

**Comment by vturecek** [comment]
Depends on the upgrade. If your upgrade includes changes to a code package, then it restarts the process so that your new binaries in the code package get loaded. But if your upgrade is a config package-only upgrade, that does not restart the process by default, but you can instruct it to:

`Start-ServiceFabricApplicationUpgrade -RestartProcess ...`

**Comment by hiraldesai** [comment]
Awesome thanks! Hadn't noticed this option before, I will give it a try now.

I'm guessing this is the same option as far as the VSO plugin is concerned?
![image](https://user-images.githubusercontent.com/1005174/30198166-24a3a198-9421-11e7-8245-9c2236f5e2bc.png)

**Comment by vturecek** [comment]
@MikkelHegn can you confirm that ForceRestart in VSO is the -RestartProcess flag for application upgrades?

**Comment by MikkelHegn** [comment]
It's not, it's the -ForceRestart parameter :-)

https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricapplicationupgrade?view=azureservicefabricps

You should use -ForceRestart and not -RestartProcess:
> -RestartProcess 
> Indicates that the service host restarts as part of the upgrade.
> 
> This parameter has been deprecated. Specify the ForceRestart parameter instead

**Comment by MikkelHegn** [comment]
Closing
