### ISSUE TITLE
1 replica eternally InBuild, hindering upgrade.

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#446]
This application has 1 of its 5 replicas constantly InBuild. We have tried everything, restarting the node, remote into the node and kill the process, disable and reenable the node, restart all nodes, upgrade, upgrade while restarting this failing replica, also deleting the application and installing it again..! Nothing works.

Upgrading does not work, it will always roll back when getting to its upgrade domain.

So, the problems here are:

**1. What to do with this replica that is eternally InBuild? Can it be fixed?**

**2. (Backup plan) How can we upgrade all other 4 nodes, except this node with the faulty replica, and just carry on without it? Because now we must migrate all data everytime we want to upgrade this application, as it just rolls back.. HUGE inconvenience.**

Application is deployed using compression, and upgrading only _one_ of the services is for that reason not possible (see [this issue #240 ](https://github.com/Azure/service-fabric-issues/issues/240)).
We are looking into the diff provisioning as mentioned in the answers there, but have yet to find some detailed instruction online for it.

**Comment by zeodamian** [comment]
Regarding #2, backup plan, I followed the instructions that could be found for diff provisioning, simply excluding the parts that are not supposed to be uploaded, and running

$packageValidationSuccess = (Test-ServiceFabricApplicationPackage $ApplicationPackagePath)

However, this throws error when the code zip for the excluded projects is not in the folder.

So, unless diff provisioning is done in some other way, that seems to be a dead end.

**Comment by zeodamian** [comment]
Have tried the upgrade procedure found here: [https://github.com/vturecek/service-fabric-xray/blob/master/src/xray/Scripts/Deploy-FabricApplication.ps1](https://github.com/vturecek/service-fabric-xray/blob/master/src/xray/Scripts/Deploy-FabricApplication.ps1)

with a structure according to this:

[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced)

..but the ServiceManifests.xml and the Settings.xml is required to exist in a folder hieararchy for the services I do not intend to upgrade, otherwise getting the errors. 
Removing these services from the ApplicationManifest gives **Services must be explicitly deleted before removing their Service Types**.

So, folders with ServiceManifest.xml and Settings.xml in zipped config (tried unzipped too), with and without version bump tried (**The content in ConfigPackage Name:Config and Version:1.0.0 in Service Manifest 'FooPkg' has changed, but the version number is the 
same.**), ultimately it fails on this:

**The BuildLayout of the application in *somepath* is invalid. Code is
 missing for service FooPkg.**

which I could detect already at $packageValidationSuccess = (Test-ServiceFabricApplicationPackage $ApplicationPackagePath), but took a long shot and tried it anyways.


So.. how is this diff provisioning supposed to be done?
We can no longer connect to the services to try do backup the data in them, so there is no option of redeploying them.

**Comment by ConX-Ryan** [comment]
I get this quite a lot i use the PowerShell cmd
`Restart-ServiceFabricNode`
which seems to unblock it for me

**Comment by zeodamian** [comment]
Thanks ConX-Ryan, that has been among all things we've tried, with no success.

Just got this reported from one of our developers: (regarding partial upgrade, i.e. question **#1. Can we upgrade 4 out of 5 nodes only?**)

> I tried different package configurations, they passed Test-ServiceFabricApplicationPackage but I was receiving different errors while publishing upgraded application. I was playing with service manifests, service executables and their references but each time something was wrong.
> Actually I am not sure if it possible (partial upgrade).

**Comment by zeodamian** [comment]
We managed to extract the data, remove the service and redeploy it and initiate it's state with the data.
The cause of the error is unknown, solutions to it are unknown, other than deleting the service (after backing up the data!).

**Comment by zeodamian** [comment]
Even after redeploying the application, one of the replicas is eternally in state InBuild. Nothing helps. No clue what is wrong.
(This is not same error as in #451, which was a bug in our code.)

**Comment by zeodamian** [comment]
So, this doesn't make sense as a result of bugs in our code.

The primary replica works fine.
Three out of four secondary replicas work just fine.

The code being executed in the secondaries are exactly the same, there is no differentiation based on node name or anything like that.

**So, why would 1 single secondary replica be stuck in InBuild mode?**
Even more strange: **Why would this be the case even _after deleting_ and redeploying the application?**

It was a replica on node 2 before deleting, not it is on node 0.

**Comment by zeodamian** [comment]
Would it be possible to have input on what can be done here?

Do you need any more information?

The questions are:
**1. What to do with this replica that is eternally InBuild? Can it be fixed?

2. (Backup plan) How can we upgrade all other 4 nodes, except this node with the faulty replica, and just carry on without it?**

**Comment by zeodamian** [comment]
So, this problem has other causes, I'll close this and open a more focused ticket.
