### ISSUE TITLE
ResourceOverrides in ApplicationManifest not Recognised

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#447]
As title indicates ResourceOverrides is not recognised and deleted from ApplicationManifest before deployment on VS 15.3.3. I checked SF schema and ResourceOverrides is not included
SF SDK Version 2.7.198 
SF Runtime Version 5.7.198

**Comment by MikkelHegn** [comment]
@tugup

**Comment by vturecek** [comment]
Yup, schema needs an update, fix is on the way..

**Comment by eliasnawfal** [comment]
Thank you

**Comment by eliasnawfal** [comment]
@vturecek Do you have any idea when the fix will be released or can you help me with a quick fix?

**Comment by jsturtevant** [comment]
@eliasnawfal this looks to be working in the latest updates that came out this week (9/24)

**Comment by eliasnawfal** [comment]
@jsturtevant I will update today and try it tomorrow after adding the configuration, thank you

**Comment by MikkelHegn** [comment]
Confirming this is in the 2.8 SDK.

**Comment by ladeak** [comment]
I am testing this with VS 2017.4.1 and SDK 2.8.219 and it still complains on schema validation.

**Comment by jshwei** [comment]
See the same issue with service fabric 6.0.232 and sdk 2.8.232. the schema file looks correct. However, when running `Register-ServiceFabricApplicationType`, have the following exception

```
C:\SfDevCluster\Data\IB\131585408126147992\e0csevok.hn3
FileName: C:\SfDevCluster\Data\IB\131585408126147992\e0csevok.hn3 --> InvalidOperationException: There is an error in
XML document (32, 6). --> XmlSchemaValidationException: The element 'ServiceManifestImport' in namespace
'http://schemas.microsoft.com/2011/01/fabric' has invalid child element 'ResourceOverrides' in namespace
'http://schemas.microsoft.com/2011/01/fabric'. List of possible elements expected: 'EnvironmentOverrides, Policies' in
namespace 'http://schemas.microsoft.com/2011/01/fabric'.
At line:1 char:1
+ Register-ServiceFabricApplicationType -ApplicationPathInImageStore 'f ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic
   eFabricApplicationType], FabricException
    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp
   E
```

**Comment by ctding** [comment]
I have a similar issue with EnvironmentOverrides.

The element 'ServiceManifestImport' in namespace 'http://schemas.microsoft.com/2011/01/fabric' has invalid child element 'EnvironmentOverrides' in namespace 'http://schemas.microsoft.com/2011/01/fabric'.

It is not fixed.  I am already using Hosted VS2017!!

**Comment by jeffjft** [comment]
I tried the following, unsuccesffully : 
* Update MSVS 17 / SDK
* fine tune Xml files
* switch visual studio language to enlgish

**Comment by alexgman** [comment]
I'm having this same issue. The full [appmanifest is here. ](https://pastebin.com/zB9gt5r0).

Here's the error:
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GetServiceProjectReferences" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.ValidateReferencedServices()
   at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Application8	C:\Users\smith\Source\Repos\Application8\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.5\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets	94	
```
Do I need to upgrade something?

My VS version:
> 
> Microsoft Visual Studio Enterprise 2017 
> Version 15.5.7
> VisualStudio.15.Release/15.5.7+27130.2036
> Microsoft .NET Framework
> Version 4.6.01590

Here are my SF packages:
```

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.ServiceFabric" version="6.1.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Actors" version="3.0.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Data" version="3.0.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="3.0.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="3.0.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Services" version="3.0.467" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Services.Remoting" version="3.0.467" targetFramework="net462" />
</packages>
```

*What am I doing wrong?*

**Comment by fizxmike** [comment]
I [commented on linked issue with my error](https://github.com/MicrosoftDocs/azure-docs/issues/5505#issuecomment-385188856). Hoping someone subscribed to this issue got this feature to work?
