### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#449]
I'm trying to start debug my application on 1 Node and I'm getting error

> Error HRESULT E_FAIL has been returned from a call to a COM component.

on the line

`ServiceRuntime.RegisterServiceAsync(serviceTypeName, serviceFactory).GetAwaiter().GetResult();`

When I use 5 Node configuration everything works fine. What does this error mean? How can I solve that? I want to use Application Debug Mode: Refresh Application, so I setup cluster to 1 Node.

Details:

> System.Fabric.FabricException occurred
>   HResult=0x80004005
>   Message=An error occurred during this operation.  Please check the trace logs for more details.
>   Source=mscorlib
>   StackTrace:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.ServiceFabric.Services.Runtime.RuntimeContext.<GetOrCreateAsync>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.ServiceFabric.Services.Runtime.ServiceRuntime.<RegisterServiceAsync>d__0.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Deezze.Services.Infrastructure.Api.BaseApiStatelessServiceProgram.Run(String serviceTypeName, Func`2 serviceFactory) in C:\Deezze\src\backend\Packages\Deezze.Services.Infrastructure.Api\BaseApiStatelessServiceProgram.cs:line 12
>    at Deezze.ApiGateway.Program.Main(String[] args) in C:\Deezze\src\backend\Modules\ApiGateway\Deezze.ApiGateway\Program.cs:line 9
> 
> Inner Exception 1:
> COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by harahma** [comment]
@Marusyk Are you hitting this issue when create a fresh one-node cluster and try to debug the app? Can you do a fresh repro and share the SF traces from your local cluster? Please make sure to stop the cluster before copying the traces (to ensure traces are flushed to the disk.)

**Comment by Marusyk** [comment]
@harahma Hello, sorry but I can't share my app. But I attached traces. Thx


[Traces.zip](https://github.com/Azure/service-fabric-issues/files/1393735/Traces.zip)

**Comment by harahma** [comment]
Hello @Marusyk, I looked at the traces and from traces it seems to be hitting some internal error where SF runtime is not able to find Settings.xml file from application package.

Does this issue occur when deploy the app for first time after creating one node cluster or while doing iterative deployments? Could you please share the repro steps so that we can try to repro this locally with a sample app?

**Comment by Marusyk** [comment]
I do not have any Settings.xml and any reference to it in my application.

> Does this issue occur when deploy the app for first time after creating one node cluster or while doing iterative deployments?

It occurs after switch on to 1 Node (it doesn't matter for the first time or not). 
Application Debug Mode: Refresh Application. Steps:
  - Switch to 5 nodes, run, everything works fine
 -  Switch to 1 nodes, run, error
  - Switch to 5 nodes, run, everything works fine

I have a simple project with default configs but I can't share it. Thanks

**Comment by Marusyk** [comment]
Any suggestions?

**Comment by harahma** [comment]
@Marusyk It is difficult to suggest anything at this point as we have no idea what is going in. You will need to share a sample repro with us to be able to repro this locally and figure out the issue.

**Comment by masnider** [comment]
@Marusyk - Were you able to figure out what's going on here? If you have steps where you can start from a clean project and repro this it'd be interesting for us to figure out. Sounds like a required file is not getting packaged or referenced correctly, or something similar.

**Comment by Marusyk** [comment]
It seems I found the solution. I've upgraded runtime to  6.0.232.9494 and SDK to 2.8.232. Then change **Application Debug Mode** to **Remove Application**

Now my application stats in debug mode on 1 node cluster 🥇

**Comment by Marusyk** [comment]
Yeah, Remove Application solve the problem but it takes long time to start debug. Application starts in 2 min after start debug. Can you help me?

**Comment by masnider** [comment]
Do you have some sense of where the time is going? Ex: in the output window of VS, is there a particular step that's taking a bunch of time?

**Comment by Marusyk** [comment]
> -------- Package started: Project: Platform, Configuration: Debug x64 ------
> -------- Package: Project: Platform succeeded, Time elapsed: 00:01:32.6406685 --------
> 2>Started executing script 'Deploy-FabricApplication.ps1'.
> 2>Copying application to image store...
> 2>Upload to Image Store succeeded
> 2>Registering application type...
> 2>Register application type succeeded
> 2>Removing application package from image store...
> 2>Remove application package succeeded
> 2>Finished executing script 'Deploy-FabricApplication.ps1'.
> 2>Time elapsed: 00:01:03.0256891
> 
> Finished executing script 'Publish-NewServiceFabricApplication'.
> Time elapsed: 00:00:08.2192374
> Started executing script 'Get-ServiceFabricApplicationStatus'.
> Finished executing script 'Get-ServiceFabricApplicationStatus'.
> Time elapsed: 00:00:37.2118591

**Comment by Marusyk** [comment]
any updates? This is critical to our development process. We can't spend so much time for debugging app !
 I have only 7 services. How long start application with 100+ services?

**Comment by Marusyk** [comment]
@dbreshears @masnider  @harahma  anyone here can help me? ⚠️  This is critical to our development process ⚠️ 
Why Refresh mode doesn't work?

**Comment by dbreshears** [comment]
@Marusyk,  for refresh mode issue,  can you try the latest 6.2 SDK with most recent VS 15.6 update that just released so we can ensure we are working with the latest released.  If you are still reproducing,  is there any way to share a repro project with us.

**Comment by Marusyk** [comment]
@dbreshears @masnider  @harahma  anyone here can help me? ⚠️  This is critical to our development process ⚠️

**Comment by dbreshears** [comment]
@Marusyk ,  thanks for the repro project.  We are investigating.

**Comment by Marusyk** [comment]
@dbreshears Thank you very much!!! We were one step up to refusing to use ServiceFabric. Thanks. Now application starts in 21 seconds. Adding **Settings.xml** to each services solve the problem
