### ISSUE TITLE
[Reverse Proxy] Websocket loses query string

### ISSUE THREAD

**Issue by poter134** [Azure/service-fabric-issues#450]
The reverse proxy strips additional query string parameters (that aren't used for forwarding to service) when connecting with a websocket.  

It's meant that I have to accept the socket without being able to check their credentials first to get it working.  Which is obviously less than ideal.  

Example URL

www://proxy-ite.company.eu:19081/TenantApps/PdSvc/web?ListenerName=comms&bearerToken=sometoken&otherParam=blah

This will forward to the correct service but any additional parameter is dropped.

**Comment by kavyako** [comment]
What is your service fabric version? We fixed this for 5.7.

**Comment by poter134** [comment]
I just updated my dev cluster to the latest version and I am in fact seeing the query string.  Apologies for not testing this beforehand.
