### ISSUE TITLE
sf volume driver not found

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#452]
When I try to run (5.7, w2k16 with containers):
```
docker volume create --driver sf mydatavol1
```

I get:
```
Error response from daemon: create mydatavol1: Error looking up volume plugin sf: legacy plugin: plugin not found
```

Also container with:
```
<Volume Source="mydatavol1" Destination="C:\data" Driver="sf" />
```

What am I doing wrong? I am unable to find any sf driver documentation over this example: 
```
<Volume Source="myexternalvolume" Destination="c:\testmountlocation3" Driver="sf" IsReadOnly="true"></Volume>
```
on https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-volume-logging-drivers

**Comment by mani-ramaswamy** [comment]
The Service Fabric volume driver has not been shipped publicly yet.  It will be available in an upcoming release.

**Comment by mkosieradzki** [comment]
Hi Mani,

I have installed 6.0 runtime version of runtime and still getting:
```
docker volume create -d sf test1
```
```
Error response from daemon: create test1: Error looking up volume plugin sf: legacy plugin: plugin not found
```

I am going to check this on Linux now.

**Comment by mani-ramaswamy** [comment]
As I mentioned, the SF volume driver hasn't shipped yet - so it is not available for you to try out. you can however, use any other volume drivers that Linux has.  https://docs.docker.com/engine/extend/plugins_volume/

**Comment by mkosieradzki** [comment]
>It will be available in an upcoming release.

>As I mentioned, the SF volume driver hasn't shipped yet 

I am sorry. I thought that you had meant 6.0.

**Comment by mani-ramaswamy** [comment]
No, sorry it is not in 6.0. We'll make sure we'll have a blog announcement on it when it is released.

**Comment by AceHack** [comment]
Do you have any writeups on partitioning with the volume driver?

**Comment by pksorensen** [comment]
Whats the status on this?

**Comment by masnider** [comment]
The SF block storage driver has been deprioritized we do not currently have an expected timeframe. In Azure, we do support the Azure Files backed volume driver, which is GA: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-volume-logging-drivers
