### ISSUE TITLE
Patch Orchestration Application - historical result properties' meaning

### ISSUE THREAD

**Issue by imaterek** [Azure/service-fabric-issues#456]
Hi guys, 

Could you describe the undermentioned properties what meaningfully they stand for?

OperationResult
ResultCode
OperationType
WindowsUpdateQuery: IsInstalled=0
RebootRequired
![image](https://user-images.githubusercontent.com/31987966/30480434-f916092c-9a19-11e7-8de9-9cfa51b86478.png)

**Comment by novino** [comment]
Field | Value | Details
-- | -- | --
OperationResult | 0 - Succeeded, 1 - Succeeded With Errors, 2 - Failed, 3 - Aborted, 4- Aborted With Timeout | This field indicates the result of overall operation (typically involving installation of multiple updates)
ResultCode | Same as OperationResult | This field indicates result of installation operation for an individual update
OperationType | 1 installation, 0 search and download.| 1 or installation is the only operation you'll see for from the publicly documented REST api's
WindowsUpdateQuery | Default is "IsInstalled=0" |This is the Query to get Windows updates. For more information, refer to documentation of POA or WuQuery
RebootRequired | true - reboot was required, false - reboot wasn't required | Indicates whether reboot was required to complete installation of updates
