### ISSUE TITLE
Licensing and Other Non-Technical Issues

### ISSUE THREAD

**Issue by gcampbell-epiq** [Azure/service-fabric-issues#457]
I am looking into using Service Fabric on premise, and I'd like to better understand some non-technical aspects of Service Fabric. Can licensing be made more clear and documented, and could you answer these questions?

 - The licensing is not very clear. It seems like having >=Windows 2012 licensing covers running Service Fabric, will that change?
 - What is Microsoft’s plan for Service Fabric? Is it a product, or will it become one? 
 - What risk is there that Service Fabric will be side-lined or replaced?
 - What’s on the product roadmap for Service Fabric?

**Comment by dkkapur** [comment]
Re your points:
* we don't have plans to change that yet for Windows Server based clusters
* It already is a product in Azure, with 2 offerings today (Azure Service Fabric, and Service Fabric Standalone)
* Several teams / products in Microsoft use SF today to orchestrate their workloads. As such, at this time, it is hard to imagine that SF will go away. We continue to prioritize it and work on it as Microsoft's container and microservice orchestrator.
* Make sure to follow our [Team Blog](https://blogs.msdn.microsoft.com/azureservicefabric/)

**Comment by dkkapur** [comment]
Going to close this for now - please let me know if you want to reopen it for a reason, or feel free to open up a new issue! Thanks!
