### ISSUE TITLE
Can't access node.js application through reverse proxy

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#458]
My app manifest is this:

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest ApplicationTypeName="FrontEnd"
                     ApplicationTypeVersion="0.0.0"
                     xmlns="http://schemas.microsoft.com/2011/01/fabric"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Parameters>
    <Parameter Name="WebUI_InstanceCount" DefaultValue="-1" />
  </Parameters>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="WebUIPkg" ServiceManifestVersion="0.0.0" />
    <ConfigOverrides />
  </ServiceManifestImport>
  <DefaultServices>
    <Service Name="WebUI">
      <StatelessService ServiceTypeName="WebUI" InstanceCount="[WebUI_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>
```

Service manifest
```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="WebUIPkg"
                 Version="0.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="WebUI" UseImplicitHost="true" />
  </ServiceTypes>

  <CodePackage Name="Code" Version="0.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>node.exe</Program>
        <Arguments>server.js</Arguments>
        <WorkingFolder>CodeBase</WorkingFolder>
        <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="2048"/>
      </ExeHost>
    </EntryPoint>
  </CodePackage>

  <ConfigPackage Name="Config" Version="0.0.0" />

  <Resources>
    <Endpoints>
      <Endpoint Name="ServiceEndpointHttp" Type="Input" Protocol="http" Port="80"/>
      <Endpoint Name="ServiceEndpointHttps" Type="Input" Protocol="https" Port="443"/>
    </Endpoints>
  </Resources>
</ServiceManifest>
```

Whe  I browse to

`https://my.cluster:19081/FrontEnd/WebUI` I get `400 FABRIC_E_INVALID_ADDRESS`
`https://my.cluster:443` works fine, however

What have I done wrongly?

----

n.b. I do not get `404 FABRIC_E_SERVICE_DOES_NOT_EXIST`, so it's locating the service fine.
Also `https://my.cluster:19081/foo?ServiceName=fabric:/FrontEnd/WebUI` also fails with `400 FABRIC_E_INVALID_ADDRESS`

**Comment by kavyako** [comment]
What does Service Fabric Explorer show for the Endpoint Address? Does it have http/https prefix?

Can you try adding the UriScheme to Endpoint section in ServiceManifest.
<Endpoint Name="ServiceEndpointHttp"  UriScheme="http" Port="80" Protocol="http" Type="Input"/>

**Comment by Mardoxx** [comment]
No it doesn't!

I shall edit my manifest and redeploy, will get back to you tomorrow

![image](https://user-images.githubusercontent.com/239665/30619761-27b058d2-9d99-11e7-98e8-a94d20c2c207.png)

**Comment by Mardoxx** [comment]
Adding `UriScheme` to the ServiceManifest's Endpoints means I can now access it at `https://my.cluster:19081/FrontEnd/WebUI` However it is now `301`ing to `https://{nodeip}:443` But I think this is due to my https-only middleware not understanding XFP headers (assuming they're being set by Service Fabric's reverse proxy). Will close for now, thank you!

**Comment by kavyako** [comment]
Thanks, I will update the reverse proxy documentation , am sure others might also run into this.

**Comment by GitUser1979** [comment]
I wanted to know, your node.js service runs on which port, when you run without service fabric?

**Comment by Mardoxx** [comment]
80 and 443

**Comment by GitUser1979** [comment]
Thanks.
