### ISSUE TITLE
How to remove guest executable safely

### ISSUE THREAD

**Issue by AhmadSaleem2604** [Azure/service-fabric-issues#459]
Hi,
I am deploying a python service on my azure service fabric cluster. I am able to remove guest executable successfully by reverse engineering the deployment process, everything is working fine but there is a problem when i again create a guest executable service with the same name then it throws Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageException , if the name of new guest executable is different then there is no issue.

**Comment by linggengmsft** [comment]
How did you deploy it and how did you remove it by "reverse engineering"? There is a remove application API you should call to remove a Service Fabric application?

**Comment by AhmadSaleem2604** [comment]
I am using visual studio to build and deploy and guest executable. I was following steps to remove guest executable.
1)delete guest executable folder in from ApplicationPackageRoot directory
2) remove its instances from applicationManifest.xml
3) remove its references from cloud.xml

I was googling around to see how can i remove guest executable from my project but couldnt find anything or that there is api for that. Can you share  some more information regarding that.

**Comment by dbreshears** [comment]
@AhmadSaleem2604,  unfortunately  our tooling is a one-way street currently with regards to this, so manual cleanup to remove the artifacts would be necessary and appears you have that working.   We are investigating changes to the templates that likely will make this easier in the future.

**Comment by dbreshears** [comment]
I copied this to our tooling backlog and marked as an enhancement, but I am uncertain when or if we will update the tooling unless you find you are blocked with the tooling not having this.   I wasn't able to repro the packagexception following your steps to remove manually as they should work.
