### ISSUE TITLE
Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageException

### ISSUE THREAD

**Issue by AhmadSaleem2604** [Azure/service-fabric-issues#461]
Hi,
I am trying to deploy a guest executable but that executable is in a subfolder of my code directory like this below is my serviceManifest.xml
```
<EntryPoint>
      <ExeHost>
        <Program>Anaconda\python.exe</Program>
        <Arguments>InitialFiltering\back_testing_agent_python_consumer.py</Arguments>
        <WorkingFolder>CodeBase</WorkingFolder>
        <!-- Uncomment to log console output (both stdout and stderr) to one of the
             service's working directories. -->
        <!-- <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="2048"/> -->
      </ExeHost>
    </EntryPoint>
```
but whenever i try to deploy it upon my local cluster it throws PackageException. however if the exe is directly under the code folder like this
`        <Program>python.exe</Program>`
then it works fine

**Comment by AhmadSaleem2604** [comment]
This issue only rises when the size of guest executable is large other wise it works fine, moreover i also try to make it work by changing WorkingFolder but still no success

**Comment by iyyappam** [comment]
Ahmad, Thanks for reporting the issue.

We might need additional information to investigate further
1. Do know on which stage of the process you get this error ie) Copying application package, provisioning or during application creation.
2. Do you know the threshold limit size after which you see the issue.
3. Could you send us the complete service and application manifest.

**Comment by AhmadSaleem2604** [comment]
Basically I was wrong in my approach I was putting python compiler and python code files in guest executable, but the problem is there. The size of the complete directory is 1.5 GB. The exception is thrown when it starts packaging the application
Following is the image of exception
![image](https://user-images.githubusercontent.com/32084716/31066322-7be6a89a-a765-11e7-8dcc-fb208f18a643.png)

Service Manifest
![image](https://user-images.githubusercontent.com/32084716/31066356-d6c1b44e-a765-11e7-8761-fb03a2a9cc95.png)

Application Manifest
![image](https://user-images.githubusercontent.com/32084716/31066380-f82a01f4-a765-11e7-8c83-851a5eb026d9.png)

 Irrelevant from the topic but my problem is resolved by following the approach suggested in this answer
https://stackoverflow.com/questions/39573315/deploy-python-executable-to-azure-service-fabric

**Comment by iyyappam** [comment]
It looks like Visual Studio is throwing the exception during packaging. We will ask VS team to take a look.

**Comment by dbreshears** [comment]
Yes.. We will take a look

**Comment by petertiedemann** [comment]
I am seeing this problem when trying to publish https://github.com/jjcollinge/traefik-on-service-fabric .

VS 15.6.4 in case that matters.

**Comment by ravipal** [comment]
I tried to package the application in the above repo and it works fine.
Couple of things I need to do
- When the project is opened in VS 2019, it auto upgraded
- Couple of *exe were missing in the repo, so removed these from the project file.
