### ISSUE TITLE
The upgrade policy is not allowed on standalone cluster

### ISSUE THREAD

**Issue by Doomblaster** [Azure/service-fabric-issues#462]
Basically I'm just trying to enable EnableDefaultServicesUpgrade, so I've added
`{
	"name": "ClusterManager",
	"parameters": {
		"name": "EnableDefaultServicesUpgrade",
		"value": true
	}
}`

under "fabricSettings" in the clusterconfig.json. I also incremented "clusterConfigurationVersion". In the explorer it says "Fabric upgrade validation failed on the node.There was an error reading the output of Fabric Deployer file.". Looking at the event viewer we get this:

> System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: The upgrade policy is not allowed
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.CompareSettings(ClusterManifestType newClusterManifest, String nodeTypeNameFilter)
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.CompareAndAnalyze(ClusterManifestType currentClusterManifest, ClusterManifestType targetClusterManifest, Infrastructure infrastructure, DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.CompareAndAnalyze(ClusterManifestType currentClusterManifest, ClusterManifestType targetClusterManifest, Infrastructure infrastructure, DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)

Not sure what upgrade policy is wrong...I'm basically just using Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\clusterconfig.json. Worth mentioning that this is a single machine with 3 nodes running version 5.7, our dev cluster.

**Comment by Liphi** [comment]
What is the apiVersion on your clusterconfig.json ? And the only config change is to add EnableDefaultServicesUpgrade ?

**Comment by Doomblaster** [comment]
I've tried both 01-2017 and 05-2017. Didn't seem to make a difference.

**Comment by taxiatms** [comment]
@Doomblaster  First of all, the syntax you added is incorrect. The "**parameters**" is actually a json array object. Therefore, you should really add square brackets. 
However, when you start the cluster like this, you should got error from Best Practice Analyzer saying Json config is invalid. Does this pop out too? 

I've tried to add the settings and it worked fine on my windows server 2012 R2, using 5.7 release and apiVersion of "05-2017". Is there anything I'm missing here? By the way, here is my full json config for unsecured 3 node cluster.


{
  "name": "SampleCluster",
  "clusterConfigurationVersion": "1.0.1",
  "apiVersion": "05-2017",
  "nodes": [
    {
      "nodeName": "vm0",
      "iPAddress": "localhost",
      "nodeTypeRef": "NodeType0",
      "faultDomain": "fd:/dc1/r0",
      "upgradeDomain": "UD0"
    },
    {
      "nodeName": "vm1",
      "iPAddress": "localhost",
      "nodeTypeRef": "NodeType1",
      "faultDomain": "fd:/dc2/r0",
      "upgradeDomain": "UD1"
    },
    {
      "nodeName": "vm2",
      "iPAddress": "localhost",
      "nodeTypeRef": "NodeType2",
      "faultDomain": "fd:/dc3/r0",
      "upgradeDomain": "UD2"
    }
  ],

  "properties": {
    "diagnosticsStore": {
      "metadata": "Please replace the diagnostics file share with an actual file share accessible from all cluster machines. For example, \\\\localhost\\DiagnosticsStore.",
      "dataDeletionAgeInDays": "7",
      "storeType": "FileShare",
      "connectionstring": "c:\\ProgramData\\SF\\DiagnosticsStore"
    },
    "nodeTypes": [
      {
        "name": "NodeType0",
        "clientConnectionEndpointPort": "19000",
        "clusterConnectionEndpointPort": "19001",
        "leaseDriverEndpointPort": "19002",
        "serviceConnectionEndpointPort": "19003",
        "httpGatewayEndpointPort": "19080",
        "reverseProxyEndpointPort": "19081",
        "applicationPorts": {
          "startPort": "20001",
          "endPort": "20031"
        },
        "isPrimary": true
      },
      {
        "name": "NodeType1",
        "clientConnectionEndpointPort": "19004",
        "clusterConnectionEndpointPort": "19005",
        "leaseDriverEndpointPort": "19006",
        "serviceConnectionEndpointPort": "19007",
        "httpGatewayEndpointPort": "19082",
        "reverseProxyEndpointPort": "19083",
        "applicationPorts": {
          "startPort": "20288",
          "endPort": "20318"
        },
        "isPrimary": true
      },
      {
        "name": "NodeType2",
        "clientConnectionEndpointPort": "19008",
        "clusterConnectionEndpointPort": "19009",
        "leaseDriverEndpointPort": "19010",
        "serviceConnectionEndpointPort": "19011",
        "httpGatewayEndpointPort": "19084",
        "reverseProxyEndpointPort": "19085",
        "applicationPorts": {
          "startPort": "20575",
          "endPort": "20605"
        },
        "isPrimary": false
      }
    ],
    "fabricSettings": [
      {
        "name": "Setup",
        "parameters": [
          {
            "name": "FabricDataRoot",
            "value": "C:\\ProgramData\\SF"
          },
          {
            "name": "FabricLogRoot",
            "value": "C:\\ProgramData\\SF\\Log"
          }
        ]
      },
      {
        "name": "ClusterManager",
        "parameters": [
          {
            "name": "EnableDefaultServicesUpgrade",
            "value": true
          }
        ]
      }
    ]
  }
}

**Comment by Doomblaster** [comment]
All my issues went away when I recreated the cluster. Now I can update configuration as I like. I was also able to update the QA cluster. 

Regardless though, I was able to create a new cluster on a new VM with the same configuration that got validation errors on the old dev cluster. The only thing I can think of is that it was some old libs or scripts from v5.6 that made it fail. Before reinstalling I cleaned the machine thoroughly and now it works.

Anyways, you can close this issue as right now I'm not really able to reproduce it.
