### ISSUE TITLE
Service Fabric Activation Error - 7148

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#466]
Hello Team,

Service is not getting activated and its taking around 20 minutes or so for service fabric to activate service after lots of retry.
is there way to figure it out whats going on ? is there troubleshoot guide which we can refer.
is it better if service fabric explorer shows actual error with activated service to save on troubleshooting efforts.
i am seeing service is getting activated but after lots of retry by service fabric cluster.
There was an error during CodePackage activation.The service host terminated with exit code:7148

can we get list of exit code and there explanation ? so is easy to troubleshoot.

Thanks,
Naresh

**Comment by oanapl** [comment]
7148 means Service Fabric intentionally terminated the process due to some error. You can look in the event log and see if there's something that can pinpoint what is wrong. For example, there may be some misconfiguration that prevent Service Fabric to launch the process correctly, like certificate configuration.
We hear you that it's hard to figure out what is going on. We have an enhancement on our side to provide more information in the health report.

**Comment by JannikMichel1** [comment]
Hey Oanapl,

i have the same issue.  Can you please be more specific about wich event log we should look into. I'm really interested in SF but i can't develop anything with it while this error exists.

Best.

Jannik

**Comment by oanapl** [comment]
@JannikMichel1 , like I mentioned above, this can happen for very different reasons. You can look in the event log for anything Warning or Error that is related to Service Fabric and/or your application.

@harahma / @RajeetN , do we have any troubleshooting guide we can share?

There is some limited information [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-understand-and-troubleshoot-with-system-health-reports#deployedapplication-system-health-reports). We plan to improve this article with more information.

**Comment by JannikMichel1** [comment]
I have just gained some inside to what might be happening. Kestrel would get started but the Runasync part wasn't called at all many times or returned "RunAsync has been cancelled for a stateful service replica.  The cancellation will be considered 'slow' if RunAsync does not halt execution within 15000 milliseconds".

**Comment by pixelicous** [comment]
@oanapl Any news on the enhancement of health status??

**Comment by oanapl** [comment]
@pixelicous , we have made some improvements (coming in our 6.1 release, which is going to roll out soon). For example, we integrated with docker HEALTHCHECK and improved some error messages. There are more improvements being worked on, they will probably come in our 6.2 release. @RajeetN is working on those, so I will let him give more details if needed.

**Comment by oanapl** [comment]
In our latest releases, we have improved many scenarios to add information about what really fails. We will continue to make improvements case by case. Closing the issue. 
If you encounter cases where the health report message is not helpful, please open new issues so we can address them appropriately.

**Comment by pixelicous** [comment]
@oanapl Is there a place to see a changelog and which event number correspond to which failure? to be honest the logging is quite vague at the moment, so is the documentation on this subject.
thank you

**Comment by oanapl** [comment]
@pixelicous , what health report are you seeing and what SF version are you on?

**Comment by saneeshkunjunni** [comment]
Hi @oanapl, I faced same situation on  SF version 7.2.413.9590. Service Fabric actor service was not activated but the health state is in OK status. Could you please help me to resolve this issue ? can we restart the service through  c# code ?
