### ISSUE TITLE
Command not responding/misleading:  Get-ServiceFabricNodeConfiguration

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#47]
This command does not respond, and gives me the following error.

PS C:\Windows\system32> Get-ServiceFabricNodeConfiguration
Get-ServiceFabricNodeConfiguration : Could not find a part of the path 'C:\ProgramData\Microsoft\SF'.
At line:1 char:1
- Get-ServiceFabricNodeConfiguration
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Get-ServiceFabricNodeConfiguration], DirectoryNotFoundException
  - FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.ServiceFabric.Powershell.GetNodeConfiguration

**Note**: Am able to successfully connect to the cluster before issuing this command.

ConnectionEndpoint   : {somename.eastus.cloudapp.azure.com:19000}
FabricClientSettings : {
                       ClientFriendlyName                   : PowerShell-b9f84f40
                       PartitionLocationCacheLimit          : 100000
                       PartitionLocationCacheBucketCount    : 1024
                       ServiceChangePollInterval            : 00:02:00
                       ConnectionInitializationTimeout      : 00:00:02
                       KeepAliveInterval                    : 00:00:20
                       HealthOperationTimeout               : 00:02:00
                       HealthReportSendInterval             : 00:00:00
                       HealthReportRetrySendInterval        : 00:00:30
                       NotificationGatewayConnectionTimeout : 00:00:30
                       NotificationCacheUpdateTimeout       : 00:00:30
                       AuthTokenBufferSize                  : 4096
                       }
GatewayInformation   : {
                       NodeAddress                          : 10.0.3.5:19000
                       NodeId                               : 1f4dda
                       NodeInstanceId                       : 13117
                       NodeName                             : somename
                       }

There is no example in msdn as well:  https://msdn.microsoft.com/en-us/library/mt628676.aspx

Thanks,
Pradebban Raja

**Comment by masnider** [comment]
I've seen this happen if the path gets corrupted or if the product is installed recently but the window the command being run from was opened before the install/update. Are you still experiencing this? If so can you share how you installed the product, the versions you're at, and whether it persists after a logout/login/restart?

**Comment by masnider** [comment]
@rajaprad - we never heard back from you. I'm going to close this issue down. If you have any feedback or can let us know if this ended up working for you, just reopen this issue or create a new one with a specific repro.
