### ISSUE TITLE
AzureChinaCloud: VMSS Size update inconsistent/misleading

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#472]
when trying to change my VM Scaleset VM size in Service Fabric cluster getting the below error:

9/20/2017 9:54:41 PM: Exception while Provisioning/Upgrading SF Cluster
9/20/2017 9:54:41 PM:9:54:41 PM - Resource Microsoft.Compute/virtualMachines 'testsdnvmRDP' failed with message '{
  "error": {
    "code": "OperationNotAllowed",
    "target": "vmSize",
    "message": "Unable to resize the VM 'sample' because the requested size **Standard_D3_v2** **is not available** **in the current hardware cluster.** 

**The available sizes are:** Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Stan
dard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_v2,Standard_D2_v2,**Standard_D3_v2**,Standard_D4_v2,Standard_D5_v2,St
andard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v2_Promo,Standard_D3_v2_Promo,Standard_D
4_v2_Promo,Standard_D5_v2_Promo,Standard_D11_v2_Promo,,Standard_A8_v2,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,S
tandard_DS1,Standard_DS2,Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14,Standard_DS1_v2,Standar
d_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,Standard_DS13-2_v2,Standard_......

**Standard_D3_v2 is included in the available sizes list, however am not able to use it for the upgrade!**
I have say 5 nodetypes and 5 VMSS in the cluster, and during a cluster upgrade to resize - some VMSS gets the new size when others show up this error. This is inconsistent and extremely misleading and denies the feature to be used for resizing when needed.

**Comment by ChackDan** [comment]
This error is coming from the Azure infrastructure indicating that their is no capacity to scale. Users can retry and will most likely succeed eventually. This error has nothing to do with service fabric.

**Comment by rajaprad** [comment]
@ChackDan - We have retried multiple time and has failed on every instance. Please let us know the path to create the issue if ServiceFabric is not the correct path

**Comment by masnider** [comment]
@rajaprad I would take it up with Azure Compute via https://github.com/Azure/vm-scale-sets/issues @gbowerman fyi - in case you have any other suggestions.

**Comment by gbowerman** [comment]
I would recommend a support case be logged for this. Issue appears to be at fabric/cluster/capacity level rather than scale set. A CSS engineer would be able to investigate.

**Comment by masnider** [comment]
Closing as not related to SF.
