### ISSUE TITLE
Using ServiceEventSource and ActorEventSource classes inside a common library

### ISSUE THREAD

**Issue by frenchyjef** [Azure/service-fabric-issues#473]
When creating a new Service Fabric project (Service or Actor) in Visual Studio, a ServiceEventSource/ActorEventSource class is automatically created to easily allow to log events.

Since I will be creating more than 100 different services/actors types, I would like to move most of the code from the ServiceEventSource/ActorEventSource class into a "base class" stored in a Shared Library. This way, if I need to customize the code in the ServiceEventSource/ActorEventSource class or fix a bug, I will only need to do it in the base class and I will not do apply the same changes to all projects.

However, when I split the code into the base class, I get the following error on the WriteEvent method call:

`System.IndexOutOfRangeException: 'Index was outside the bounds of the array.`

Here is a bit more detail on how I structured the ServiceEventSource and BaseServiceEventSource classes:

StatefulService1\ServiceEventSource.cs
```
    [EventSource(Name = "StatefulService1")]
    internal sealed class ServiceEventSource : BaseServiceEventSource
    {
        public static readonly ServiceEventSource Current = new ServiceEventSource();

        static ServiceEventSource()
        {
            // A workaround for the problem where ETW activities do not get tracked until Tasks infrastructure is initialized.
            // This problem will be fixed in .NET Framework 4.6.2.
            Task.Run(() => { });
        }

        // Instance constructor is private to enforce singleton semantics
        private ServiceEventSource() : base() { }
    }
```

SharedLibrary\BaseServiceEventSource.cs

```
    public abstract class BaseServiceEventSource : EventSource
    {
         #region Keywords
         ...
         #endregion 

         #region Events
         ...
         #endregion 

         #region Private methods
         ...
         #endregion 
    }
```

Any guidance would be appreciated...

Cheers,
J-F

**Comment by ravipal** [comment]
@frenchyjef I tried the same and it works for me. Can you please make sure you don't have duplicate EventSource specified.

**Comment by masnider** [comment]
@frenchyjef - Hi there - we haven't heard back from you on this. At this point we're going to close the issue. If you have more information about what you've tried that you can share with us, please just reopen the issue and let us know, or feel free to create a new issue if you prefer.

**Comment by frenchyjef** [comment]
I apologize for the delay in my response but I got around to try this again with the latest Service Fabric bits and still getting the following error:

`System.IndexOutOfRangeException: 'Index was outside the bounds of the array.`

The issue occurs on the following line of code:

`WriteEvent(ServiceTypeRegisteredEventId, hostProcessId, serviceType);`

And just to reiterate, I am removing most of the code inside the original ServiceEventSource.cs and moving it into a base class so I can reuse the code across all my services. Notice below how the BaseServiceEventSource class is in a separate assembly.

StatefulService1.csproj ==> ServiceEventSource.cs

```
    [EventSource(Name = "StatefulService1")]
    internal sealed class ServiceEventSource : **BaseServiceEventSource**
    {
        public static readonly ServiceEventSource Current = new ServiceEventSource();

        static ServiceEventSource()
        {
            // A workaround for the problem where ETW activities do not get tracked until Tasks infrastructure is initialized.
            // This problem will be fixed in .NET Framework 4.6.2.
            Task.Run(() => { });
        }

        // Instance constructor is private to enforce singleton semantics
        private ServiceEventSource() : base() { }
    }
```

SharedLibrary.csproj ==> BaseServiceEventSource.cs

```
    public abstract class BaseServiceEventSource : EventSource
    {
         #region Keywords
         ...
         #endregion 

         #region Events

         private const int ServiceTypeRegisteredEventId = 3;
         [Event(ServiceTypeRegisteredEventId, Level = EventLevel.Informational, Message = "Service host process {0} registered service type {1}", Keywords = Keywords.ServiceInitialization)]
         public void ServiceTypeRegistered(int hostProcessId, string serviceType)
         {
             WriteEvent(ServiceTypeRegisteredEventId, hostProcessId, serviceType);
         } 

        ...
 
        #endregion 

         #region Private methods
         ...
         #endregion 
    }
```
