### ISSUE TITLE
Autofac.ServiceFabric integration and ServiceEventSource

### ISSUE THREAD

**Issue by frenchyjef** [Azure/service-fabric-issues#474]
Hi,

I have setup a few of my Stateful Service projects to leverage Dependency Injection using Autofac (see [link](https://alexmg.com/posts/introducing-the-autofac-integration-for-service-fabric)) 

Everything works great except for the out-of-box ServiceEventSource class no longer does proper logging.  I can see the events logged in my Diagnostic Events viewer but they do not contain the correct content...

Is this a bug in Service Fabric & Autofac Integration? Anyone has a short example to share that could put me in the right direction, that would be much appreciated!

Here is an example of the Event written to the Diagnostic viewer:

```
{
  "Timestamp": "2017-09-22T14:45:51.1718039-07:00",
  "ProviderName": "SomeServiceName",
  "Id": 0,
  "Message": null,
  "ProcessId": 20916,
  "Level": "Always",
  "Keywords": "0xFFFFFFFFFFFFFFFF",
  "EventName": "EventSourceMessage",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "message": **"ERROR: Exception in Command Processing for EventSource SomeServiceName: Unsupported type Exception in event source."**
  }
}
```

Cheers,
J-F

**Comment by Mardoxx** [comment]
I habe Autofac working, although I haven't looked at my event logs... I shall have a look tomorrow!

Try opening an issue here https://github.com/autofac/Autofac.ServiceFabric

**Comment by mattrowmsft** [comment]
That specific message seems like you have public method on your EventSource derived class that takes Exception parameter that isn't marked with NonEventAttribute.  I think those are validation events that EventSource itself puts out.

**Comment by fvenezia** [comment]
@mattrowmsft  You're right! your comment save my day, I couldn't figure out why my ServiceEventSource class didn't log anything. 
All public methods on this class must use primitive type parameters (and few other types like Datetime and Guid) or be marked [NonEvent].
Anyone should read comments in the Events region of ServiceEventSource file in a Service Fabric  Project template.

**Comment by masnider** [comment]
@frenchyjef Hi there - we haven't heard back from you on this, and it looks like there are multiple solutions. We encourage you to open issues on the autofac folks if this still isn't working for some reason. Thanks @mattrowmsft for the hints as well!
