### ISSUE TITLE
DNS Issue after upgrade to 5.7.217.9494

### ISSUE THREAD

**Issue by vinfos** [Azure/service-fabric-issues#478]
The SF Cluster was upgraded from 5.7.207.9494 to 5.7.217.9494 and DNS stopped resolving names. After manual downgrade to 5.7.207.9494, it started to work again.

**Comment by milvuko** [comment]
Build 5.7.217.9494 has a regression that affects DnsService in secure Windows clusters. DnsService is running under a special user and doesn't have enough privileges to access the cluster's certificate and is therefore unable to resolve DNS queries. Note that this is the only build that has this issue. Downgrade to previous build or upgrade to 6.0 build fixes the problem. In case upgrade/downgrade is not an option, 
the mitigation is to modify the permissions on the certificate's private key to grant read access to the user DnsService runs under. This has to be done on every node.

**Comment by vinfos** [comment]
Unfortunately, downgrade to the 5.7.207 did not go smoothly. The DNS service stopped running in cluster. It was present in manifest and FabricDNS.exe was on disc. There were no meaningful errors. 
We ended up with following steps to fix it
* remove it from template
* run template
* add to template
* run template
