### ISSUE TITLE
INFO - How to pass ECR during compose sf cli command

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#480]
We get aws token after doing aws configure with client id and client secret. we need to pass that short term token to aws to get images from aws ecr when doing sf cli compose command.

**Comment by linggengmsft** [comment]
If ECR accepts that token as the same format for the normal container registry password, you could set it in the compose creation parameters:

    --compose-file   [Required]: Path to the Compose file to use.
    --encrypted                : If true, indicate to use an encrypted password rather than
                                 prompting for a plaintext one.
    --repo-pass                : Encrypted contain repository password.
    --repo-user                : Container repository user name if needed for authentication.
