### ISSUE TITLE
Service Fabric Compose Deploy fails went built with 6.0.211.9494

### ISSUE THREAD

**Issue by brandmo** [Azure/service-fabric-issues#484]
I've just upgraded my build server with Service Fabric v6.0.211.9494 with SDK v2.8.211.9494.

No my Service Fabric Compose Deploy release step in VSTS fails with the following message:

The term 'Get-ServiceFabricComposeApplicationStatus' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

All of the links to the compose cmdlets here https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps are broken.

I upgraded my fabric to v6.0 the other day while my build server was still on the version before and I had no issues deploying my compose app.

Should i downgrade my build server or are there other steps i can take to get things working again?

P.S.
The Service Fabric Compose Deploy and Docker Compose build steps have all lost their "Preview" tags but are still at v0.* I presume they're still in preview mode.

**Comment by oanapl** [comment]
We changed the cmdlets to have 'Deployment' rather than 'Application' in the name. Try
[Get-ServiceFabricComposeDeploymentStatus](https://docs.microsoft.com/en-us/powershell/module/servicefabric/Get-ServiceFabricComposeDeploymentStatus?view=azureservicefabricps) instead.
@rwike77 , can you make sure that the [main page](https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps) is updated to show the new cmdlets?

**Comment by rwike77** [comment]
@oanapl  List of cmdlets on the [main page ](https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps)have been updated.

**Comment by rwike77** [comment]
@brandmo Could you verify the list of cmdlets on  [main page ](https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps)?

**Comment by oanapl** [comment]
I verified that links work properly now. Thank you, @rwike77 ! 
@brandmo, thank you for reporting! Let us know if you have any other issues.

**Comment by brandmo** [comment]
Thanks for the reply. I don't have any control over the cmdlet that's used by the Service Fabric Compose build step in VSTS so I guess I'll need to downgrade to the previous version for the moment. 

Is there going to be an update soon?

**Comment by loekd** [comment]
Now that VSTS has been upgraded to run v6 of the SDK, the VSTS Task "Service Fabric Compose Deploy" fails due to this issue.

**Comment by mdegroot71** [comment]
I tried setting up a cluster using version 5.7.198.9494 and I get the same error as above.  Dropping versions doesn't seem to provide any relief.

**Comment by brandmo** [comment]
I found dropping versions didn't immediately work, but when i tried again a few days later it did, I have no clue why.

As this ticket is closed you might want to follow progress here: https://github.com/Microsoft/vsts-tasks/issues/5505
