### ISSUE TITLE
NuGet Error - Failed to add reference. - 'Microsoft.ServiceFabric.Diagnostics.Internal' 

### ISSUE THREAD

**Issue by keithbeller** [Azure/service-fabric-issues#485]
I'm getting a Failed to add reference error when trying to update Service Fabric on an existing project using NuGet on Visual Studio 2017. The package 'Microsoft.ServiceFabric.Diagnostics.Internal' tried to add a framework reference to 'System.ServiceModel' which was not found in the GAC.   I'm getting the error when attempting to upgrade the Microsoft.ServiceFabric assembly to latest version v6.0.211.

**Comment by mattrowmsft** [comment]
@keithbeller  What .net version are you targeting? I would expect System.ServiceModel to be in your GAC.

**Comment by masnider** [comment]
@keithbeller - As @mattrowmsft  mentioned this dll should be present on the machine automatically, and we haven't seen this elsewhere. I tried and haven't been able to reproduce it. 

Given we have no repro, no other reports, can't reproduce the issue, and haven't heard back from you with more information, at this point we're going to close the issue. If you have more information about what you've tried that you can share with us, please just reopen the issue and let us know, or feel free to create a new issue if you prefer. Steps to reproduce or a specific project that exhibits the issue would be great.
