### ISSUE TITLE
Insufficient ETW/EventSource documentation

### ISSUE THREAD

**Issue by tuhland** [Azure/service-fabric-issues#487]
We recently ran into some issues with the ETW and Service-/ActorEventSources.

The main problem is, that there seem to be some "reserved" Event IDs (Either officially registered somewhere in the whole ETW mess or in some common understanding at MS) which are not documented (completely).

Some are documented here, but there seem to be more: 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-diagnostics

We created a generic custom EventSource for our services and actors which basically had some events for error, info and debug logging. The cluster is configured to route these events into the WADServiceFabricReliable(Actor/Service)EventTables. 

Now, after finally finding a way to set up OMS, to monitor these logs (OMS isn't available in the german cloud where our services are running), the OMS Service Fabric module reported tons of issues in our services. After looking closely at the responsible query, the following Event IDs are reported as issues:

EventId == 2 or 
EventId == 4 or 
EventId == 5 or 
EventId == 7 or 
EventId == 9 or 
EventId == 10

One of these incidentally is our debug event ID.

The sample code on this page also uses one of these for debug logging:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-generation-app

We changed the Event IDs of our custom methods to new values, but now, because of some evil ETW voodoo, the log entries are empty. See issue #355 for another victim of this. ;)

Which leads us to the following issues:
- Either the Event IDs "reserved" by the SF runtime need to be documented and it needs to prominently indicated that they shouldn't be used, or when to use them - in case I really want to report an issue
- Or it needs to be indicated that you shouldn't route your events into the default tables - but then the OMS module doesn't gather them anymore

It should also be indicated that it will be hard or next to impossible to change these events after the cluster is up and running.

**Comment by tuhland** [comment]
After re-reading my issue, I feel this probably partially a OMS Service Fabric module issue. 

But still i think there's some guidance missing around the whole EventSource => Cluster ETW configuration => OMS Module flow. 

Even if I used the auto-generated EventSource to report some application level events (which is the most common usage probably) through the ServiceMessage method it would end up as a "Notable Issue" because this uses Event ID 2.

**Comment by mattrowmsft** [comment]
I think this is an issue in the way the OMS dashboards for SF are defined.  I'll follow up with appropriate people and report back.

**Comment by tuhland** [comment]
Yep, you're probably right.
 
It still would be great to know, what events SF is emitting into these default logs/tables and if we're supposed/allowed to use the default tables for application level logging, or even if ETW is still the way to go.

**Comment by dkkapur** [comment]
By default, if Diagnostics it turned on, then SF is just emitting the "Operational channel" to tables, which are then ingested into OMS. https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-generation-operational is a list of those events. We have a few other ETW channels as well that you could enable via your WadCfg as needed. You can definitely use the default tables for application level logging in case you want to configure less things to get OMS to work. 

In terms of the Event IDs in OMS - as Matt pointed out, this has to do with the current iteration of the SF solution. This is in process of being updated and will no longer rely on specific Event IDs. Feel free to check out current progress on the new version here: https://github.com/dkkapur/service-fabric-monitor-solution.
