### ISSUE TITLE
Support for using additional storage disk

### ISSUE THREAD

**Issue by awcab** [Azure/service-fabric-issues#490]
I have a .net SF application that needs to use a large amount of additional storage for temporary calculations.  However, I can find little in the way of documentation for how to attach and mount an additional disk or use the storage from the application. Since all the the instances at selection mention additional disk support, I was expecting some SDK support and docs for how to actually use them.  I did find[ this doc](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/attach-managed-disk-portal), but it doesn't really address this use case, especially in the case of scaling.

**Comment by masnider** [comment]
@awcab - There's two parts to this. 1 is adding more drives to your VM to use as storage. 2 is then having various services directed to use those drives. When you say you have a lot of temporary data, is this data that you keep in reliable collections or just on your own?

**Comment by awcab** [comment]
@masnider That's correct!  I would add that for (1) I need to add drives to the template so they scale.  This data is on the order of 100GB or so.  I'm not currently using collections because it appears that they aren't well suited to large amounts of data.  Can you confirm if this is correct or if there is some other best practice I should be using for storing and accessing this data across instances?

**Comment by masnider** [comment]
This is supported. Go ahead.
