### ISSUE TITLE
Service Fabric Compose Deploy build step in VSTS uses old cmdlets and fails

### ISSUE THREAD

**Issue by brandmo** [Azure/service-fabric-issues#491]
The Service Fabric Compose Deploy build step in VSTS still uses the "Application" cmdlets.
These cmdlets have been renamed to "Deployment" in the latest release of Service Fabric, runtime v6, SDK v2.8 so the step fails with the following message "The term 'Get-ServiceFabricComposeApplicationStatus' is not recognized as the name of a cmdlet, function, script file, or operable program."

Get-ServiceFabricCompose**Application**Status has been renamed to Get-ServiceFabricCompose**Deployment**Status

After downgrading my build server to back v5.7 I get the error Argument 'Test-ServiceFabricApplicationPackage' is not recognized as a cmdlet: Unable to load DLL 'FabricCommon.dll'. The error goes away when i upgrade to v6.0..

It appears that the Compose Deploy build step has been upgraded to use the Test-ServiceFabricApplicationPackage cmdlet which isn't available in 5.7 but still references the "Application" cmdlets which are only available in v5.7.

So I can't deploy my compose application with v5.7 or v6.0

Please help!

**Comment by MikkelHegn** [comment]
The 2.7 SDK will work against a version 6.0 cluster, but the task will not work on with the 2.8 SDK installed on the agent.
I've opened an issue in the VSTS Tasks repo to track this: https://github.com/Microsoft/vsts-tasks/issues/5505

**Comment by brandmo** [comment]
Hi Mikkel, 

The task has stopped working with v2.7 of the SDK installed on the agent as well. I get this error "Argument 'Test-ServiceFabricApplicationPackage' is not recognized as a cmdlet: Unable to load DLL 'FabricCommon.dll".

It started happening when I upgraded my fabric to 6.0, but downgrading to 5.7 doesn't make a difference. I found the other problem when I upgraded my agent to SDK 2.8 to try and resolve it.

Cheers,
Brandon

**Comment by MikkelHegn** [comment]
Please track this on the VSTS-Tasks repo: https://github.com/Microsoft/vsts-tasks/issues/5505 This should be fixed now.

**Comment by brandmo** [comment]
It doesn't appear to be fixed. I tried again today and got the following error "##[error]The term 'Get-ServiceFabricComposeApplicationStatus' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by emilverwoerd** [comment]
got the exact same problem as brandmo
