### ISSUE TITLE
Reverse proxy configuration/certificate validation

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#492]
Is it possible to configure Reverse Proxy validation policy on a on-premise cluster (5.7.198.9494)

We follow instructions from : 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication 

We add in json configuration 
`"FabricSettings": [
{
       "Name": "Setup",
        "Parameters": [
          {
            "Name": "FabricDataRoot",
            "Value": "D:\\FabricDataRoot"
          },
          {
            "Name": "FabricLogRoot",
            "Value": "L:\\FabricLogRoot\\log"
          }
        ]
      },
      {
        "Name": "ApplicationGateway/http",
    "Parameters": [
    {    
          "name": "ApplicationCertificateValidationPolicy",
           "value": "None"
        }
        ]
      }
],
`

and then run 
` Start-ServiceFabricClusterConfigurationUpdate `

but the command returns without any errors, no update takes place.

Using the same configuration for First Time cluster creation, we get error that **ApplicationGateway/http** is a duplicate entry in the configuration, though it is not!

I can see that there is a similar need (but for local dev clusters) here https://github.com/Azure/service-fabric-issues/issues/292 
Is this possible via json?

kind regards
Yannis

**Comment by dealboy** [comment]
I can see that there is a similar request, but for DEV (local) cluster here
https://github.com/Azure/service-fabric-issues/issues/292 

Is there a way to do the same using json files? or touching the cluster xml files?

**Comment by kavyako** [comment]
Yes it should be possible. 
Do you have secure reverse proxy set up already?  Have you configured reverseProxyCertificate property in the cluster resource type section ?

**Comment by dealboy** [comment]
No, we do not have a secure reverse proxy set up (but we plan/want  that as next step).
The only configuration we have so far for reverse proxy is the "reverseProxyEndpointPort" value in the json file, as defined in the sample file: 

https://github.com/Azure-Samples/service-fabric-dotnet-standalone-cluster-configuration/blob/master/Samples/ClusterConfig.Windows.MultiMachine.json

Please note that our secure cluster is based on windows security and not on X509
`"ClusterCredentialType": "Windows",
"ServerCredentialType": "Windows",`

Is it possible to define reverseProxyCertificate  while using windows security ?

**Comment by kavyako** [comment]
Reverse Proxy only supports X509. You have to specify a certificate for the secure reverse proxy endpoint. 

Refer to [Reverse proxy in Azure Service Fabric ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy) to configure the secure reverse proxy. 
Sections of interest for configuring the HTTPS reverse proxy:
-  "To configure SSL certificates on the port for the reverse proxy, add the certificate to the reverseProxyCertificate property in the Cluster Resource type section" 
- "Supporting a reverse proxy certificate that's different from the cluster certificate"

**Comment by dealboy** [comment]
I have the feeling that all the instructions are pointing to Azure cloud configurations and not on-premise ones.
The on premise json file has different structure.
Is there a mapping between on-premise json configuration and usage of  Cluster Resource types?

**Comment by kavyako** [comment]
When you downloaded the standalone Service Fabric package, you should see sample JSON files for X509 config:  ClusterConfig.X509.DevCluster.JSON and ClusterConfig.X509.MultiMachine.JSON . Configurations starting with ReverseProxy show how to specify the reverse proxy certificate. Note: the config name is different for dev cluster and multi machine.

**Comment by kavyako** [comment]
Here is the https://github.com/Azure-Samples/service-fabric-dotnet-standalone-cluster-configuration/blob/master/Samples/ClusterConfig.X509.MultiMachine.json 
The configs you want are : ReverseProxyCertificateCommonNames and reverseProxyEndpointPort.
This will enable secure reverse proxy.
Additional ApplicationCertificateValidationPolicy settings can be placed under fabricSettings, similar to what is described in the [reverse proxy secure communication blog](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication).

If it still does not work, please share the original and new config jsons and I can take a look.

**Comment by dealboy** [comment]
Can we have windows security between cluster nodes ("ClusterCredentialType": "Windows") , **and** certificates for outside connections  ("ServerCredentialType": "X509") ?

Combine 
"ClusterCredentialType": "Windows", 
"ServerCredentialType": "X509",
**and** then define : 
ReverseProxyCertificate


(I tried it, but although the configuration is accepted and passes basic validation, in my case it fails during cluster creation)

**Comment by kavyako** [comment]
You can do Windows security for ClusterCredentialType and ServerCredentialType. And have reverse proxy configured to use a certificate. 
Here is the config I used, and it seems to work:
`

        "security": {
            "ClusterCredentialType": "Windows",
            "ServerCredentialType": "Windows",
            "WindowsIdentities": {                
                "ClusterIdentity": "domain\\machinegroup",
                "ClientIdentities": [
                    {
                        "Identity": "domain\\username",
                        "IsAdmin": true
                    }
                ]
            },
           "CertificateInformation": {
                 "ReverseProxyCertificateCommonNames": {
                  "CommonNames": [
                      {
                        "CertificateCommonName": "Test-Cert-Cn"
                      }
                    ],
                    "X509StoreName": "My"
                }
            }
        },
`

**Comment by dealboy** [comment]
Yes, applied it and now listens to https! 
thanks a lot man!

**Comment by julioas09** [comment]
Hi, one question you could probably answer.
Setting this Reverse Proxy certificate, establishes https in the whole channel or only TO the Rev Proxy?
I also have a WS2016 on-prem cluster with Windows security, and we want to establish an end-to-end https channel when services communicate through the reverse proxy:
Origin --(https)--> Reverse Proxy --(https)--> Destination

Thanks.
