### ISSUE TITLE
Reverse Proxy Does not work on local 5 Node Cluster

### ISSUE THREAD

**Issue by rufio620** [Azure/service-fabric-issues#494]
I cannot seem to get the reverse proxy to work on my local 5 node dev cluster. I have a simple nancyfx HttpListener setup as described [here](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin). I am able to access the service but when I attempt to access via the reverse proxy I get net::ERR_CONNECTION_REFUSED from chrome which leads me to believe nothing is running on that port. 

I have checked the cluster FabricHostSettings.xml and the following settings are present. 

```
    <Parameter Name="HttpApplicationGatewayListenAddress" Value="19081" />
    <Parameter Name="HttpApplicationGatewayProtocol" Value="http" />
```

```
  <Section Name="ApplicationGateway/Http">
    <Parameter Name="IsEnabled" Value="true" />
  </Section>
```

Can you please provide some information on how to get the reverse proxy running locally as there does not seem to be anything documented online. Thanks.

**Comment by rufio620** [comment]
I just tried this with a web api project and I am having the same issue so it does not appear to be nancyfx.
Navigating to http://localhost:19081/TestApp/Website/api/values fails with connection refused.


[TestApp.zip](https://github.com/Azure/service-fabric-issues/files/1342297/TestApp.zip)

**Comment by kavyako** [comment]
What is the service fabric version. 
How did  you generate the 5 node cluster? Reverse proxy is enabled by default on local dev clusters.
What http response/status code do you get when you try just http://localhost:19081/ 

When deploying from Visual Studio, can you [enable diagnostics ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics) for the reverse proxy and see what error it is reporting.

**Comment by rufio620** [comment]
The service fabric version is 6.0.211.9494 and the SDK version is 2.8.211.9494

I deployed the cluster from the Service Fabric Local Cluster Manager tray application that installs with the SDK. This is a Windows 7 machine, not sure if that would make a difference.

http://localhost:19081/ gets the same error. 

This site can’t be reached

localhost refused to connect.
Search Google for localhost 19081
ERR_CONNECTION_REFUSED

I will enable the diagnostics and send over what I find. I'm also gonna try to deploy a local cluster on a windows 10 machine to see if that makes a difference.

**Comment by rufio620** [comment]
I added Microsoft-ServiceFabric:4:0x4000000000000010 to the diagnostic events.

I don't see anything that looks like it relates to the reverse proxy. I have quite a few of these events though.

{
  "Timestamp": "2017-09-28T17:28:53.376461-04:00",
  "ProviderName": "MSNT_SystemTrace",
  "Id": 65535,
  "Message": null,
  "ProcessId": 0,
  "Level": "Always",
  "Keywords": "0x0000000000000000",
  "EventName": "LostEvent/RTLostEvent",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {}
}

Should the reverse proxy service show up in the dashboard? I don't see it just the DnsService.

![image](https://user-images.githubusercontent.com/1992395/30991468-2c9554de-a473-11e7-8804-aaedb1ecefc5.png)

**Comment by kavyako** [comment]
Ah unfortunately Reverse proxy is not supported on Windows 7 since the websockets implementation it uses is only available starting Windows 8. You want Windows 10.

**Comment by kavyako** [comment]
Also reverse proxy will not show up with the system services. You should see FabricApplicationGateway.exe process running when it is enabled.

**Comment by rufio620** [comment]
Ok that explains it. Does that mean it would not work on Server 2008 R2 as well? 

Also I don't recall seeing anything about this in any of the documentation for reverse proxy any way to get that updated? It might save some others some time. Thanks.

**Comment by kavyako** [comment]
Right, it will not work on Server 2008. Minimum required : Windows Server 2012

And yes, we will update the documentation.

**Comment by rufio620** [comment]
OK thanks for all your help.
