### ISSUE TITLE
SerializationException when using the V2 remoting and 6.0/2.8 version

### ISSUE THREAD

**Issue by juho-hanhimaki** [Azure/service-fabric-issues#497]
I upgraded to 2.8 and V2 remoting but now I see serialization erros on some of my remoting methods.

As example the method:

        Interface:
        Task<IEnumerable<long>> GetLongsAsync();

        Implementation:
        public async Task<IEnumerable<long>> GetLongsAsync()
        {
            var results = new long[] { 1, 2, 3 };
            //var results = await ComputeResultsAsync();

            return results;
        }

Returns error when called via remoting:

    "message": "Type 'System.Int64[]' with data contract name 'ArrayOflong:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.",
    "exception": "SerializationException"

On previous versions of Service Fabric and remoting I had no problems with code similar to the above example.

Is this change by design and is there a recommended way to solve this issue?

**Comment by juho-hanhimaki** [comment]
It seems this issue happens to me only when using V2 remoting. So V1 remoting with 6.0/2.8 behaves as expected.

**Comment by juho-hanhimaki** [comment]
Basically same as #502

**Comment by suchiagicha** [comment]
@juho-hanhimaki  

Yes , this is expected in Remoting V2. 
Scenario is by default , Remoting Api Types needs to be of concrete Type. In above case , if you change type IEnumerable<long> to long[] , it will work. By default , we take serialization knowntypes from the Api return/response types.

Other solution is to explicitly add knownTypes by following way.

1 You need to implement IServiceRemotingMessageSerializationProvider. Below is one of the sample for your case. It just wraps the default serialization Provider with your knownTypes. Make sure you add all the knownTypes.

2.  Plugin the provider on Client Factory and Listener. Here are the steps 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2



public class CustomDataContractProvider:IServiceRemotingMessageSerializationProvider
    {
        private ServiceRemotingDataContractSerializationProvider provider;
        private IEnumerable<Type> myTypes;

        public CustomDataContractProvider()
        {
            this.provider = new ServiceRemotingDataContractSerializationProvider();
            this.myTypes = new List<Type>()
            {
                typeof(long[])
            };
        }
        public IServiceRemotingMessageBodyFactory CreateMessageBodyFactory()
        {
          return  this.provider.CreateMessageBodyFactory();
        }

        public IServiceRemotingRequestMessageBodySerializer CreateRequestMessageSerializer(Type serviceInterfaceType,
            IEnumerable<Type> requestBodyTypes)
        {
            return this.provider.CreateRequestMessageSerializer(serviceInterfaceType,requestBodyTypes);
        }

        public IServiceRemotingResponseMessageBodySerializer CreateResponseMessageSerializer(Type serviceInterfaceType,
            IEnumerable<Type> responseBodyTypes)
        {
            var result = responseBodyTypes.Concat(this.myTypes);
            return this.provider.CreateResponseMessageSerializer(serviceInterfaceType, this.myTypes);
        }
    }

**Comment by juho-hanhimaki** [comment]
It would be quite a lot of work to implement the custom providers for the whole system I am developing. In my case there are a lot of methods that have optional filtering and/or ordering done via LINQ.

I guess the other option is to call ToList or ToArray in all such cases, but that would probably have negative performance implications which kinda counters the whole purpose of using the new remoting.

**Comment by shacal** [comment]
I don't think there are any performance change. If you have IEnumerable in interface there is zero filtering happening, basically you get full data set from another service to local memory and then filtering behind the scene. V2 just makes you think your interface more and allow filtering in right place.

**Comment by juho-hanhimaki** [comment]
I guess it depends how the DataContract serialization works internally.

ToList and ToArray allocate arrays which can be wasted garbage collection.

If the DataContract serializer enumerates the IEnumerable during serialization without building the array it seems obvious it's more optimal to not call ToList or ToArray.

**Comment by Mardoxx** [comment]
>call ToList or ToArray in all such cases, but that would probably have negative performance implications

Interesting... I suppose it depends on implementation. As I understand if the serialiser receives `IEnumerable` and only accesses the enumerator, then there will be no (little?) performance hit. However if it then materialises this as a list using `ToList()` it will be creating an entirely new copy of the list.

I think the only way to know would be have someone who understand the internals of SF's serialisation explain it -- or perf test it yourself!

**Comment by Marusyk** [comment]
Hello @suchiagicha, 
I tried to use that fix but as a result I get at runtime:

> AggregateException: One or more errors occurred.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+<InvokeWithRetryAsync>d__24.MoveNext()
> 
> InvalidCastException: Specified cast is not valid.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+<InvokeWithRetryAsync>d__24.MoveNext()

Could you please suggest how can I fix that? Thanks

**Comment by Marusyk** [comment]
what is the purpose of V2 if it can work only with primitive types. What about domain models? Is it ready for use in production code?

**Comment by suchiagicha** [comment]
@Marusyk 
V2 default Serializer works not just with primitive Type. It works with concrete type also. What do you mean by domain models? 
If you have concrete type you can use v2  in production.

**Comment by Marusyk** [comment]
@suchiagicha 

Thanks for "quick" response. By "domain models" I mean any model (class). You say:

>  It works with concrete type also.

But did you read the error that I posted? I'll copy 

> AggregateException: One or more errors occurred.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+d__24.MoveNext()
> 
> InvalidCastException: Specified cast is not valid.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+d__24.MoveNext()

I'm using example from site but with model like
```
class Model
{
    public int Id {get; set;}
    public string Name {get; set;}
}
```

**Comment by suchiagicha** [comment]
@Marusyk 
can you repro this in sample and share with us?

**Comment by wandelson** [comment]
![image](https://user-images.githubusercontent.com/810174/38836134-8800c72c-41a3-11e8-9b16-68843aad2716.png)

using Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime;

Why ?

**Comment by wandelson** [comment]
I think this documentation confuse

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2

**Comment by ashishnegi** [comment]
@wandelson If you are referring to namespace for `ServiceRemotingJsonSerializationProvider`, then it is a custom class. Its not provided by Service Fabric. The code is on the blog. You need to copy and add that to your project.
