### ISSUE TITLE
Question: Is moving large data between Service Fabric services is bad design?

### ISSUE THREAD

**Issue by AsValeO** [Azure/service-fabric-issues#498]
I'm developing a web data crawler using Service Fabric. I've devided a crawling proccess into Stateless services pipeline. First service loads HTML. (S1) Second one parses data from it. (S2) Third one saves result into DB and performs additional operations. (S3) HTML code moves from S1 to S2, than to S3 (by design, I need HTML in third service). The problem that HTML itself is a big amount of data and I am forced to set
`[assembly: FabricTransportServiceRemotingProvider(MaxMessageSize = 1073741824)]`
1) Is this wrong design? Should I perform all work with HTML inside singe service?
2) If I place whole crawler pipeline inside one service, would it contradict the principles of SF (microservices)? Is Azure Cloud Service matches better in this case?

**Comment by mkosieradzki** [comment]
@AsValeO 

Regarding design and microservices architecture you will definitely find your answers here:

https://mva.microsoft.com/en-us/training-courses/azure-service-fabric-patterns-and-practices-16925
and here:
https://www.youtube.com/watch?v=sXZvbqkPu14

Long story short: Service Fabric does not REQUIRE micro-services. Do micro-services only when you have a good reason. In the second movie Jeffrey Richter explains good scenarios for micro-services. Also in the first MVA you have a good explanation what does it mean to have fine-grained services.

Regarding FabricTransportServiceRemotingProvider question: (it is completely separate from the microservices question). IMO it is a terrible idea to use Service Fabric Remoting for streaming data! Use raw HTTP or split your communication into smaller messages. Service Fabric Remoting does implicit message buffering and that's awful for this specific scenario.

I personally do a lot of data transfer between services, but I use raw HTTP and it works just great.

**Comment by masnider** [comment]
Yup. I would say this captures it. What's bad and what's necessary are up to your application. Service Fabric doesn't really care. As a guideline, yeah, don't use buffered transports for large amounts of data, and yes generally smaller more granular chunks of state and messages are better than larger ones.

**Comment by olivergrimes** [comment]
@mkosieradzki - I know this is an old thread... When you suggest raw HTTP, I assume you still use a `ServiceRemotingListener`?
