### ISSUE TITLE
Service Fabric - System Services disaster recovery

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#499]
Do you plan to provide any means to backup the cluster state and config?

Currently there are no means to preserve configuration of the entire cluster (application images, running instances configuration etc.). The more advanced dynamic micro-services usage is, the more information is stored in-cluster only.

Unless there is some means to backup the entire cluster state, in more advanced scenarios it is required to mirror the entire Service Fabric Application model what sounds.... ridiculous.

The risk of loosing the entire cluster configuration is higher in Azure, because the default configuration uses temporary SSDs which are lost in case of many not-so-rare circumastances, including (but not limited to):
- Account freeze due to spending limit
- VMSS VM-size change (without silver durability tier)
- Some accidental billing issue

Those specific cases can be overcome by using Premium Storage instead of Temp SSD but that defies multiple benefits coming from using Service Fabric including:
- temp ssd performance and low price
- independence from external service potential availability issues (Premium Storage)

So the question is whether there are some plans to provide some backup facility for cluster state (for example together with the release of the new Service Fabric native State Provider implementation) or are the SF users supposed to mirror all the configuration of cluster services on their side or wait or try to find other ways of backup/restore?

**Comment by dkkapur** [comment]
This is interesting. One step in this direction is to starting using ARM to manage applications and services that are required on the cluster at any given point. See https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-arm-resource for more info on this. Nonetheless, this is not a comprehensive "snapshot" of your entire cluster as you describe. 
@ChackDan what is the current recommendation on this front?

**Comment by mkosieradzki** [comment]
Thanks @dkkapur! I didn't know about possiblity of using ARM for this purpose (it seems to be a new feature). However, I believe, I cannot use ARM in an on-premises solution.

As of today I have implemented something very similar to this ARM solution which contains desired state description and I have implemented a tool responsible for transitioning cluster to such a state. I will have a closer look on your ARM template definition for applications, maybe I will find some more useful ideas.

**Comment by masnider** [comment]
There's no backup and restore solution for the cluster as a whole. This is why the system services are all persisted and replicated, some partitioned, and why the core Failover Manager has the notion of rebuilding its state from the nodes its finds in case those replicas get lost somehow. So for most cases in place dataloss and recovery is already handled, just not through traditional backup and restore or declaration mechanisms. 

So while this is good it doesn't give you a way to check in a declaration of what services should be running, or a way to snap that information easily out of a running cluster to back it up somewhere. As Deep points out there's some capabilities for this in Azure but not via the core platform. We're investigating this enhancement or what else we could do to meet your scenario, but as it stands using the queries to gather the information you want and tracking what you put in outside of SF is the way to go.

**Comment by masnider** [comment]
This would be accomplished via managed disks for the OS disks or whichever disks you have mounted for the SF system services storage location (FabricDataRoot). For other services we recommend the backup and restore service.
