### ISSUE TITLE
Microsoft.VisualStudio.Azure.Fabric.MSBuild 1.2 gives output error 

### ISSUE THREAD

**Issue by bklooste** [Azure/service-fabric-issues#50]
1.1 fine , 1.2 gives the old output path error.. revert the nuget and its fine...

  <ItemGroup>
    <ProjectReference Include="..\src\Fis.Configuration.WebAPI\Fis.Configuration.WebAPI.csproj" />
    <ProjectReference Include="..\src\Fis.NameValue.Service\Fis.NameValue.Service.csproj" />
  </ItemGroup>

**Comment by johnkattenhorn** [comment]
I'm also seeing the same after SDK upgrade today, this error description is

```
The OutputPath property is not set for project 'MKopa.M2M.IBIS2.App.sfproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
```

**Comment by mkosieradzki** [comment]
You can try restoring all nuget packages and rebuild. I had the same issue.

**Comment by slicc** [comment]
Same problem here, seeing this on all out sfproj projects that are upgraded to MSBuild 1.2.

**Comment by sandersaares** [comment]
This happens because upgrading the NuGet package does not update the MSBuild project include path in the sfproj file (it still points to the old version of the NuGet package).

**Comment by slicc** [comment]
Yes, that is what happened. Additionally I didn't have the latest Azure service fabric VS tools installed. As I did all this out of sequence I didn't get the new Loca.1Node.xml and Local.5Node.xml settings and publish files created so had to manually create those also (VS didn't seem to want to create them, but complained about their absence).

**Comment by MikkelHegn** [comment]
When we release a new version of the tooling, the intent is that we upgrade your .sfproj the first time it's opened in Visual Studio. For 1.2 that included migrating to the new Local.xNode.xml files and upgrading the reference to the NuGet build package.

Did you not get prompted with an upgrade the first time you opened the project in VS?

**Comment by slicc** [comment]
It is likely that we did get prompted (I've upgraded a few projects now and I have been notified on all of the new ones so far). 

However, I think it is likely that on the first project I clicked "No", thinking I should do the NuGet update first, at which point I never got prompted again to update the .sfproj. I then had to go down the manual route, creating the xNode.xml files by hand. 

If I do it the other way round (click Yes to upgrade .sfproj then do NuGet) everything was fine.

**Comment by MikkelHegn** [comment]
Thanks for confirming.

You're right it might be confusing that we are only upgrading the project, and not your services to run against the new runtime (Service Fabric NuGet packages).

**Comment by MikkelHegn** [comment]
If you are an error similar to the one posted by John above...

If you have checked in the backup of the .sfproj file, make sure that your build tasks points to the right .sfproj file and not the one in the backup folder.

**Comment by bobeaton** [comment]
@MikkelHegn, my problem (I think) was that I have multiple solutions in the same sub-folder and so when I told it to go ahead and upgrade my project it caused VS (2015) to hang. (I did have the new local.1node.xml file, but not the 5node and it hadn't updated the *.sfproj file with the references to MSBuild.1.2.0. Once I changed that manually, copied 1node.xml to 5node.xml and added both of these to the project, then it began working

**Comment by masnider** [comment]
@bobeaton thanks for confirming and glad that you're back up and running. Let us know if you run into anything else.
