### ISSUE TITLE
Full Reliable Service communication example with deploy on cloud?

### ISSUE THREAD

**Issue by AsValeO** [Azure/service-fabric-issues#501]
I can't find full example that covers:
1) Reliable Service with communication listener creation
2) Communicating local client with it (Local cluster)
3) Publish to Azure
**4) Communicating local client with it (Published in cloud)**
Last one is missing in every tutorial. For a people like me, who have not a WebAPI/WCF backgroung such example could be very handy at the beginning.

**Comment by MikkelHegn** [comment]
If you are trying to communicate through Service Remoting from outside the cluster, this is not supported.
