### ISSUE TITLE
V2 remoting: difference in handling of IEnumerable<T> output

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#502]
Service interface operation:

```
public interface IBackupRestoreService : IService
{
     Task<IEnumerable<BackupMetadata>> ListBackups();
}
```

Using Remoting V1:
When returning a `List<BackupMetadata>` from the implementing Service, the remoting client accepts the result.

Using Remoting V2:
When returning a `List<BackupMetadata>`, the remoting client throws an exception, stating that `List<BackupMetadata>` was not expected.

As a workaround, I changed my Service to declare a `List<T>` instead of `IEnumerable<T>`. This works, however, I liked the first implementation better, as the returned List is mutable.

**Comment by suchiagicha** [comment]
@loekd 

Here is the solution
https://github.com/Azure/service-fabric-issues/issues/497

**Comment by suchiagicha** [comment]
Closing this issue. If you still have any question , reopen it.

**Comment by loekd** [comment]
If V2 is not backward compatible with V1, can you explain to me the benefits of me going to v2 anyway?
(I talked to Mark Fussell about this :-) )

**Comment by Mardoxx** [comment]
I'd also like a more detailed answer to this. From your release notes all it says is:

Service Remoting V2
A new version of Service Remoting is now available for reliable services and actors. The new version 
works the same as the current service remoting, but introduces several features and improvements, 
including custom serialization and memory use optimizations such as buffer pooling and reduction of 
buffer copying.
More information about RemotingV2 can be found here:
• https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-
communication-remoting#how-to-use-remoting-v2-stack
• https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-
platform#actor-using-remoting-v2-stack

**Comment by benbenwilde** [comment]
updated link for using V2 in actors https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-using#actor-using-remoting-v2-stack
