### ISSUE TITLE
Add support for docker HEALTHCHECK

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#503]
HEALTHCHECK are a very helpful and convenient way to monitor app running inside services in a container, e. g. IIS Websites. Service Fabric should restart a container whenever healthcheck reports the container as unhealthy.

**Comment by mani-ramaswamy** [comment]
We're working on making this available. Stay tuned.

**Comment by Abdruggi** [comment]
Awesome. Looking forward to it.

**Comment by mani-ramaswamy** [comment]
This is available with 6.1 https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-docker-healthcheck

**Comment by Abdruggi** [comment]
@mani-ramaswamy 
Could you share some insight about the expected time frame for the 6.1 on premise version?

**Comment by mani-ramaswamy** [comment]
In the next few weeks.

**Comment by nareshkhatri81** [comment]
@mani-ramaswamy 
i am able to test this behaviour on premsie.
one thing i noticed is the container name.
is it way to display user friendly or SF uses service name while running docker containers ?

**Comment by mani-ramaswamy** [comment]
Adding @RajeetN. 

Thanks for testing it out @nareshkhatri81.  Can you elaborate your question?  SF does create service types & application types for containers.

**Comment by nareshkhatri81** [comment]
In SF Explorer where Health of App events are displayed, it displays container name + some random string not healthy.
My all containers are not healthy now so not able to capture what is displays but its container name + Random string.

i was thinking when SF runs docker containers, it gives containers name as service name which is defined in ApplicationMainfest/ServiceMainfest file. 

Also in Service Tab, State of service was displayed as ready. if service fabric can display there health of containers then it would be helpful.

Thanks,
Naresh Khatri

**Comment by adityapkanthe** [comment]
I am trying to integrate docker healthcheck with service fabric, I want service fabric to restart the container when it turns unhealthy, but this is not working for me. The container was unhealthy for more than 50 minutes but it never restarted and I don't see any unhealthy events in Health Events section in service fabric explorer.

<img width="910" alt="unhealthy_container" src="https://user-images.githubusercontent.com/36767136/37449576-cd2d94fe-2850-11e8-895e-92ea5e198a98.PNG">


<img width="754" alt="service_fabric_health_events" src="https://user-images.githubusercontent.com/36767136/37449439-3683f6f6-2850-11e8-97d7-d0b0f557687c.PNG">

Following is my setup

1. I have following HEALTHCHECK line in my dockerfile

"Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "powershell -command try {$response = iwr http://localhost/status/ping -UseBasicParsing; if ($response.StatusCode -eq 200) { return 0} else {return 1}; } catch { return 1 }"
                ],
                "Interval": 90000000000,
                "Timeout": 10000000000,
                "Retries": 3
            }

2. I have added following in ApplicationManifest ContainerHostPolicies section

HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true" RestartContainerOnUnhealthyDockerHealthStatus="true"/

3. I am working on Service fabric standalone version "6.1.472.9494" and I have a one node cluster.

4. Following is the Hosting section from cluster configuration.

    Section Name="Hosting"
      Parameter Name="ContainerImageDownloadTimeout" Value="2400"
      Parameter Name="EnableDockerHealthCheckIntegration" Value="true" 
      Parameter Name="EndpointProviderEnabled" Value="true"
      Parameter Name="FirewallPolicyEnabled" Value="true"
      Parameter Name="RunAsPolicyEnabled" Value="true"
    Section

@mani-ramaswamy  Can you please provide some inputs on way forward to get this work.

Thanks,
Aditya Kanthe
