### ISSUE TITLE
Deploying a sample stateful service VS error

### ISSUE THREAD

**Issue by jlim1973** [Azure/service-fabric-issues#508]
Hi, 

I have just setup my development environment for azure and trying to test and deploy a sample stateful service, but failed to deploy in VS - got error message "There were deployment errors. Continue?" - The PowerShell script failed to execute. Error logs and my environment details below. What could be causing this? any help to get me up and running with Azure would be appreciated. Thank you.

Error logs in output window:
===================

1>------ Build started: Project: Stateless1, Configuration: Debug x64 ------
1>  Stateless1 -> c:\users\administrator.crmdev\documents\visual studio 2015\Projects\Application1\Stateless1\bin\x64\Debug\Stateless1.exe
2>------ Build started: Project: Application1, Configuration: Debug x64 ------
3>------ Deploy started: Project: Application1, Configuration: Debug x64 ------
3>Started executing script 'GetApplicationExistence'.
3>Finished executing script 'GetApplicationExistence'.
3>Time elapsed: 00:00:01.7270989
3>Started executing script 'Set-LocalClusterReady'.
3>Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1'; Set-LocalClusterReady
3>--------------------------------------------
3>Local Service Fabric Cluster is not setup...
3>Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
3>
3>Using Cluster Data Root: C:\SfDevCluster\Data
3>Using Cluster Log Root: C:\SfDevCluster\Log
3>
3>The generated json path is C:\Users\administrator.CRMDEV\AppData\Local\Temp\tmp5778.tmp.json
3>Processing and validating cluster config.
3>Create node configuration succeeded
3>Starting service FabricHostSvc. This may take a few minutes...
3>
3>Waiting for Service Fabric Cluster to be ready. This may take a few minutes...
3>Local Cluster ready status: 4% completed.
3>Local Cluster ready status: 8% completed.
3>Local Cluster ready status: 12% completed.
3>Local Cluster ready status: 17% completed.
3>Local Cluster ready status: 21% completed.
3>Local Cluster ready status: 25% completed.
3>Local Cluster ready status: 29% completed.
3>Local Cluster ready status: 33% completed.
3>Local Cluster ready status: 38% completed.
3>Local Cluster ready status: 42% completed.
3>Local Cluster ready status: 46% completed.
3>Local Cluster ready status: 50% completed.
3>Local Cluster ready status: 54% completed.
3>Local Cluster ready status: 58% completed.
3>Local Cluster ready status: 62% completed.
3>Local Cluster ready status: 67% completed.
3>Local Cluster ready status: 71% completed.
3>Local Cluster ready status: 75% completed.
3>Local Cluster ready status: 79% completed.
3>Local Cluster ready status: 83% completed.
3>Local Cluster ready status: 88% completed.
3>Local Cluster ready status: 92% completed.
3>Local Cluster ready status: 96% completed.
3>Local Cluster ready status: 100% completed.
3>WARNING: Service Fabric Cluster is taking longer than expected to connect.
3>
3>Waiting for Naming Service to be ready. This may take a few minutes...
3>Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS 
3>issue.
3>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:620 char:12
3>+     [void](Connect-ServiceFabricCluster @connParams)
3>+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException
3>    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster
3> 
3>Naming Service ready status: 8% completed.
3>Naming Service ready status: 17% completed.
3>Naming Service ready status: 25% completed.
3>Naming Service ready status: 33% completed.
3>Naming Service ready status: 42% completed.
3>Naming Service ready status: 50% completed.
3>Naming Service ready status: 58% completed.
3>Naming Service ready status: 67% completed.
3>Naming Service ready status: 75% completed.
3>Naming Service ready status: 83% completed.
3>Naming Service ready status: 92% completed.
3>Naming Service ready status: 100% completed.
3>WARNING: Naming Service is taking longer than expected to be ready...
3>Local Service Fabric Cluster created successfully.
3>--------------------------------------------------
3>Launching Service Fabric Local Cluster Manager...
3>You can use Service Fabric Local Cluster Manager (system tray application) to manage your local dev cluster.
3>Finished executing script 'Set-LocalClusterReady'.
3>Time elapsed: 00:07:38.6749609
3>The PowerShell script failed to execute.
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

The local cluster manager seems to be started in system tray, but I can’t do anything with it. select any option e.g. Manage local cluster, it will display an error message unable to start cluster or something similar.

I followed the following to set up my environment and for the sample:

- https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started
- https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-application-in-visual-studio

FYI, I have installed/run the following:

- Service Fabric SDK 2.8.211
- Service Fabric runtime 6.0.211
- Service Fabric Tools for Visual Studio 2015 1.7.50721
- Enable PowerShell script execution
- Run VS as administrator

Environment:

-  VS 2015 with Update 3
- Windows server 2012 R2

Regards,
Joe

**Comment by taxiatms** [comment]
@jlim1973  Are you able to start a cluster with the tray icon? you may try to reset the cluster first.

**Comment by jlim1973** [comment]
@taxiatms Thank you for your reply. No, selecting Manage local cluster results in an error message "Failed to open local cluster explorer. Please restart the local cluster manager and try again.". I have tried reset, and also remove local cluster and build again but no luck.

**Comment by taxiatms** [comment]
@jlim1973  It might be some legacy files from previous installation. Are you able to uninstall sdk/runtime and install it again? Any error with that?

**Comment by jlim1973** [comment]
I did tried uninstall and reinstall runtime and sdk. But still same issue. I might have to try again.


Joseph Lim

A Level 10, 500 Collins Street, Melbourne, VIC 3000
T +61396130220<tel:+61396130220>
W www.pa.com.au<http://www.pa.com.au> |

[cid:image001.png@01D34277.06BC9500]<https://www.linkedin.com/company/15711?trk=tyah> [cid:image007.jpg@01D34277.06C17700] <https://twitter.com/ProfessionalAdv>  [cid:image008.jpg@01D34277.06C17700] <http://blog.pa.com.au/>

  |

[cid:image004.png@01D34277.06BC9500]

1300 658 608

[cid:image005.gif@01D34277.06BC9500]<http://www.pa.com.au/>

**Comment by taxiatms** [comment]
If there is no error in reinstalling, the you can try to setup a cluster without deploying apps to it. One way to do that is open local tray and setup 1-node cluster. No need to create an VS project here. 
Let me know if that works.

**Comment by jlim1973** [comment]
Coincidentally I just tried that a few minutes ago. The first attempt, It did pop up a message saying “something went wrong.. trying again”, and then appears to complete setting up the cluster. However, same issue when I try to start manage local cluster.


Joseph Lim

A Level 10, 500 Collins Street, Melbourne, VIC 3000
T +61396130220<tel:+61396130220>
W www.pa.com.au<http://www.pa.com.au> |

[cid:image001.png@01D34279.6FA7A490]<https://www.linkedin.com/company/15711?trk=tyah> [cid:image002.jpg@01D34279.6FA7A490] <https://twitter.com/ProfessionalAdv>  [cid:image003.jpg@01D34279.6FA7A490] <http://blog.pa.com.au/>

  |

[cid:image004.png@01D34279.6FA7A490]

1300 658 608

[cid:image005.gif@01D34279.6FA7A490]<http://www.pa.com.au/>

**Comment by taxiatms** [comment]
Can you send the trace file to taxi@microsoft.com? It should be located in C:\sfDevCluster\Log\Traces. The most recent few ones.
Thanks.

**Comment by rishirsinha** [comment]
@jlim1973, was this resolved?

**Comment by jlim1973** [comment]
@rishirsinha no, not yet. I did received an email from @taxiatms on 4/11 to send the trace file to taxi@microsoft.com, which I did - the trace log was sent to taxi@microsoft.com on 8/11. That was the last correspondent and haven't heard anything back since then.

**Comment by taxiatms** [comment]
@jlim1973 I checked the trace and couldn't find out what's wrong. Can you contact the support team? Thanks,

**Comment by gsoulavy** [comment]
Hi all, I have exactly the same issue, however, I am running on Visual Studio 2017 Pro, SF SDK 2.8.232.9494, SF Runtime 6.0.232.9494,  Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.51106. 
I am running vs with admin elevated. I have also tried to set the 1 node. 
The service fabric host service is running, but the following errors are filling my event log:
'The Service Fabric Host Service service terminated unexpectedly. It has done this 4 time(s). The following corrective action will be taken in 5000 milliseconds: Restart the service.'

The 'Manage local cluster' also produces some errors:
'Failed to open local cluster explorer'

I have also reinstalled the SDK/Runtime, c++ redist (x64) without error. 
Is there any conflict or did I miss something?

**Comment by gsoulavy** [comment]
I have also noticed, that after installation and running DevClusterSetup script I have the following log in the events: 'Copy of Powershell from C:\Program Files\Microsoft Service Fabric\bin\WindowsFabric to C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\WindowsFabric Failed'. 
The 'C:\Program Files\Microsoft Service Fabric\bin\WindowsFabric' folder is missing from my computer. Is it necessary? If yes, how can I install?

**Comment by rishirsinha** [comment]
That particular folder is is not necessary. We will fix the warning message soon.

Can you please send me the traces?

**Comment by gsoulavy** [comment]
Hi @rishirsinha, thanks for the response. Please find the traces attached.  [traces.zip](https://github.com/Azure/service-fabric-issues/files/1592003/traces.zip)
I cannot connect to the cluster (client-localhost:19000/127.0.0.1:19000) and I believe this is the reason why the local cluster explorer is not working.

**Comment by rishirsinha** [comment]
@gsoulavy 

It looks like both Fabric.exe and FabricDCA.exe (needed for system to function) are crashing as soon as they come up. Can you just go to c:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code and run Fabric.exe? It will probably tell you exactly why it is crashing.

My hunch is that the VC redist 14 install is corrupted. What we have seen is that VC redist 14 has dependencies on a particular Windows Update that occasionally gets pulled out. If you reinstall vc redist 14 things should get back on track.

**Comment by gsoulavy** [comment]
Hi @rishirsinha,
I have updated the correspondent VC redist 14s. I have also reinstalled the fabric runtime and SDK. When I create the dev cluster it still gives the connection failed error and 
the node and DCA exits with event:
'HostedServiceInstance:HostedService/_Node_0_Fabric terminated with exitcode 3221225794'
'HostedService: _Node_0 on node id bf865279ba277deb864a976fbf4c200e terminated unexpectedly with code 3221225794 and process name FabricDCA.exe'
'HostedServiceInstance:HostedService/_Node_0_DCA terminated with exitcode 3221225794'

If I try to run the Fabric.exe I have the following event error:
'Lease agent bf865279ba277deb864a976fbf4c200e:131589778700954950@localhost:19001 register with driver failed with ERROR_ACCESS_DENIED; Check system section in device manager to see if the driver is in working state and you have authorization to access driver.'
And an other event error follows: 
'Throwing coding error - bf865279ba277deb864a976fbf4c200e:131589778700954950@localhost:19001 got invalid return code 5 for registration Symbol paths: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;;
Symbol loading time: 00.089
Stack trace:
    00007ff7:375d7458( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758929b( windows_error(487): Attempt to access invalid address.  )
    00007ff7:375891a3( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3785dd77( windows_error(487): Attempt to access invalid address.  )
    00007ff7:375b20f7( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3760453c( windows_error(487): Attempt to access invalid address.  )
    00007ff7:37601c59( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:376013eb( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758eabb( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e25d( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e644( windows_error(487): Attempt to access invalid address.  )
    00007ff7:375ed218( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758eabb( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e25d( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e644( windows_error(487): Attempt to access invalid address.  )
    00007ff7:37441e26( windows_error(487): Attempt to access invalid address.  )
    00007ff7:374419bb( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3742bb01( windows_error(487): Attempt to access invalid address.  )
    00007ff7:374406da( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758eabb( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e25d( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758e644( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3743b536( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3758c09a( windows_error(487): Attempt to access invalid address.  )
    00007ff7:3742b7b1( windows_error(487): Attempt to access invalid address.  )
    00007ff7:37439f2f( windows_error(487): Attempt to access invalid address.  )'

The vc_redist is on version: 14.12.258.10 (32/64), 12.0.30501 (32/64), 11.0.51106 (64), 10.0.402.19 (32/64).

Please find my attached newest traces:
[fabric_traces.zip](https://github.com/Azure/service-fabric-issues/files/1592318/fabric_traces.zip)

**Comment by gsoulavy** [comment]
I have also tried to install sf without secure boot. The drivers look normal in device manager/system devices and I can also confirm that the following services are successfully installed:
'A service was installed in the system.

Service Name:  LeasLayr
Service File Name:  C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys
Service Type:  kernel mode driver
Service Start Type:  auto start
Service Account:  '

'A service was installed in the system.

Service Name:  KtlLogger
Service File Name:  C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\KtlLogger.sys
Service Type:  kernel mode driver
Service Start Type:  auto start
Service Account:  '

I have also rolled back the latest vc_redist 14 and reinstalled them from `C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\vc14_redist.x64.exe` and `C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\vc_redist_x64.exe`. When I reinstall sf sdk with the runtime, i also clear up the cache of the web platform installers `%LocalAppData%\Microsoft\Web Platform Installer\installers` folder.

Shall I create a local admin account for the service to avoid the `ERROR_ACCESS_DENIED` issue?

**Comment by rishirsinha** [comment]
@gsoulavy 

This does not look like an issue because we do the ACLing of the accounts as late as possible. Any chance you can send me the traces from the latest attempt?

**Comment by gsoulavy** [comment]
Hi @rishirsinha,
Yes of course:
[fabric_traces.zip](https://github.com/Azure/service-fabric-issues/files/1593244/fabric_traces.zip)

**Comment by rishirsinha** [comment]
The issue is still the same. The exe comes up and dies immediately. Is there a crash dump being generated? Can you try running FabricDCA.exe in the DCA.Code directory independently to see what happens?

**Comment by gsoulavy** [comment]
The application crash dump was empty, but the content of the CrashDump folder is the following:
https://drive.google.com/open?id=1fWE8iHbfZf2ZzOiZT5fiqMFhgPcT6AbO
The FabricDCA.exe hangs like a console app with Thread.Sleep(), it does not produce any exception and event logs.

**Comment by rishirsinha** [comment]
This is proving harder to debug than I thought. When you are opening the executables directly they seem to work. However, when launching through FabricHost (system entry point), they crash instantly as if not able to find a dll. Am not sure without a closer look at the setup how I can debug.

**Comment by gsoulavy** [comment]
Thanks, Can it be related to any issue during deployment or any windows update? 
The system level path variables for the sf installation are the following entities:
`C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;
C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;
C:\Users\MyUserName\AppData\Local\Microsoft\WindowsApps;`
I have looked at the registry and I can see the two entries for sf sdk and sf runtime. 
When I open the dump file and run it with VS, it fails at the LeaseAgent.OnOpen()/Assert DoFailFast (although i don't know if it is the expected behavior). 
Is there any way I can IM you?

**Comment by rishirsinha** [comment]
It could be windows update related, but that is easy to mitigate by simply restarting the OS. The dumps seem to be from the times you tried to start Fabric.exe independent of the FabricHost and hence are not helpful. We can chat on skype / skype for business if at all possible.

**Comment by rishirsinha** [comment]
Also is this issue persistent across multiple machines or specific to a machine?

**Comment by gsoulavy** [comment]
Thanks @rishirsinha, is specific only one machine. Yes, the dump has been produced when I individually tried to run the Fabrik.exe. 
Thanks again for the quick response.
My skype id is g.soulavy@gmail.com

**Comment by rishirsinha** [comment]
I am having problems with my skype account. Once I have fixed it I will ping you.

**Comment by gsoulavy** [comment]
Thanks!

**Comment by gsoulavy** [comment]
Hi,
I have created 3 dump files when the FabricHostSvc was running. (3 x Every 5 seconds). I hope it will help.
I have installed service fabric on another box successfully from the same download.

The dump files are located below:
https://drive.google.com/file/d/1fm0EJanPYGLVgJs9PWtn39Llr4F7F9WK/view?usp=sharing

**Comment by rishirsinha** [comment]
@gsoulavy 

Can you check what Microsoft Service Fabric Host Service is running as?

Thanks,
Rishi

**Comment by gsoulavy** [comment]
Hi @rishirsinha,

it runs as Local System Account (unticked with Allow interact with User Desktop).

**Comment by rishirsinha** [comment]
Can you try killing the Fabrichost process in TaskManager. It should restart immediately. Once it restarts it should Launch FabricSetup.exe and in a few seconds FabricDeployer.exe too. Can you check if they are being launched?

**Comment by gsoulavy** [comment]
Yes, they were, however the cpu usage was 0%. I also saw the Fabric.exe turning up for about a second.

**Comment by rishirsinha** [comment]
How long did the two executables last?

**Comment by gsoulavy** [comment]
They were visible about 6-7 seconds

**Comment by ajeetcoolkarni** [comment]
Facing exactly same issue as gsoulavy, with Runtime version 6.1.456 and VS 2015 with update 3 on windows 7 machine.

**Comment by deckertron9000** [comment]
Same issue here. Have there been any updates?

**Comment by xxrichard1** [comment]
Same issue here with 6.2 Refresh installed yesterday on standalone Windows 10.
This is the 4th SF update I have installed. It is a headache every time.  Problems usually related to LeasLayr.sys failing to access a port. Never found a resolution. Previously have l kept reinstalling, stopping, starting, resetting, rebooting until one day it magically works.

**Comment by deckertron9000** [comment]
My issue was resolved following the workaround on #1056

**Comment by maburlik** [comment]
This thread has gone stale and the original poster has not sent an update since 2017. If you are still hitting issues please refer to #1056, and if the suggested mitigations don't work and you think your issue is not the same, please create another item so we can track this.

Thanks
