### ISSUE TITLE
Can't reach Reliable Service with WCF communication after publish to the Cloud

### ISSUE THREAD

**Issue by AsValeO** [Azure/service-fabric-issues#509]
Here is a simple Service Fabric stateless service with WCF communication and it's client - a console app. It works well on the local cluster, client gets responce from the service. But I don't know how to communicate with a service if I deploy it in the cloud. What exactly should I change in code /  to access it from console app?

**SF Stateless service with WCF communications:**

Contract:

```
 [ServiceContract]
    public interface IPresidentialService
    {
        [OperationContract]
        Task<string> GetInfo();
    }
```
Service:

```
internal sealed class PresidentialService : StatelessService, IPresidentialService
{
    public PresidentialService(StatelessServiceContext context) : base(context)
    {
    }

    public Task<string> GetInfo() => Task.FromResult($"Node {Context.NodeContext.NodeName} operating");

    protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
    {
        return new[]
        {
            new ServiceInstanceListener(context =>
                new WcfCommunicationListener<IPresidentialService>(wcfServiceObject: this, serviceContext: context,
                    endpointResourceName: "WcfServiceEndpoint",
                    listenerBinding: WcfUtility.CreateTcpListenerBinding()))
        };
    }
}
}
```

**Client console app:**

WCF client:

```
public class PresidentialServiceClient : ServicePartitionClient<WcfCommunicationClient<IPresidentialService>>
    {
        public PresidentialServiceClient(
            ICommunicationClientFactory<WcfCommunicationClient<IPresidentialService>> communicationClientFactory,
            Uri serviceUri, ServicePartitionKey partitionKey = null,
            TargetReplicaSelector targetReplicaSelector = TargetReplicaSelector.Default, string listenerName = null,
            OperationRetrySettings retrySettings = null) : base(communicationClientFactory, serviceUri, partitionKey,
            targetReplicaSelector, listenerName, retrySettings)
        {
        }

        public Task<string> GetInfo() => InvokeWithRetryAsync(client => client.Channel.GetInfo());
    }
```
Client App:

```
private static void Main(string[] args)
        {
            var binding = WcfUtility.CreateTcpClientBinding();
            var partitionResolver = ServicePartitionResolver.GetDefault();
            var wcfClientFactory =
                new WcfCommunicationClientFactory<IPresidentialService>(binding,
                    servicePartitionResolver: partitionResolver);
            var serviceUri = new Uri("fabric:/Application5/PresidentialService");
            var client = new PresidentialServiceClient(wcfClientFactory, serviceUri, ServicePartitionKey.Singleton);
            do
            {
                Console.WriteLine(client.GetInfo().Result);
                Console.ReadKey();
            } while (true);
        }
```
Added to `ServiceManifest.xml`:

```
<Endpoints>
      <Endpoint Name="WcfServiceEndpoint" />
</Endpoints>
```

**Then service published to the cloud.**

`ServicePartitionResolver `changed to:

`var partitionResolver = new ServicePartitionResolver("sfapp.westeurope.cloudapp.azure.com:19000");`

Endpoind changed to:

`<Endpoint Name="WcfServiceEndpoint" Protocol="tcp"  Port="333" />`

TCP port 777 opened in Load Balancer rules. Still no success. Application freezes at line `Console.WriteLine(client.GetInfo().Result);`, no exception thrown.

**Comment by masnider** [comment]
@AsValeO - This is almost always because there's no connectivity between the client and the service. 
The client probably can't resolve the service directly since the address that the service is listening on is an internal azure IP address. 

You should have the client just send its messages to the public DNS or IP address of the public azure load balancer, which will then route them to the actual nodes in the cluster. If your service is running on all the nodes it will pick up the messages and process them. The only other thing you need to look at is to be sure that the azure network load balancer is mapping the external port that your client is sending to to the port on the actual nodes that the service is listening on.

**Comment by AsValeO** [comment]
Question answered, problem solved.
