### ISSUE TITLE
Issue with certificate management for containers (DataPackage)

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#510]
According to the documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-securing-containers) it should be possible to use datapackages to access certificates inside a container (>= Version 5.7). Unfortunately, the attributes are not part of the xsd and the validation fails. Is this a 6.0 feature?

**Comment by rakshitatandon** [comment]
Yes, this feature was added in 6.0.

**Comment by mani-ramaswamy** [comment]
Abdruggi - please let us know by reopening the issue if you are still hitting the problem. Closing this for now.

**Comment by Abdruggi** [comment]
OK, I'll wait for the 6.0 standalone release.
