### ISSUE TITLE
Remote listener overrides KestrelCommunicationListener

### ISSUE THREAD

**Issue by yarlenvas** [Azure/service-fabric-issues#511]
I have a service with 2 endpoints, one to remote communication and one to http request, but when I publish on my local 5 nodes cluster, I notice the remotelistener always takes the ServiceEndpoint and not the RpcEnpoint

` var instanceListeners = new List<ServiceInstanceListener>();

            var remoteListener = new ServiceInstanceListener((serviceContext) => this.CreateServiceRemotingListener(serviceContext), "RpcEnpoint");
            
            var kestrelListener = new ServiceInstanceListener(serviceContext =>
                   new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                   {
                       ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                       return new WebHostBuilder()
                                   .UseKestrel()
                                   .ConfigureServices(
                                       services => services
                                           .AddSingleton<StatelessServiceContext>(serviceContext))
                                   .UseContentRoot(Directory.GetCurrentDirectory())
                                   .UseStartup<Startup>()
                                   .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                   .UseUrls(url)
                                   .Build();

                   }));

            

            //var remoteListener = new ServiceInstanceListener((context) => this.CreateServiceRemotingListener(context), "RpcEnpoint");
            instanceListeners.Add(remoteListener);
            instanceListeners.Add(kestrelListener);

            return instanceListeners;`

and in ServiceManifest.xml:

`<Endpoints>
      

      <Endpoint Protocol="tcp" Name="RpcEnpoint" Type="Input" Port="34014" />
      <Endpoint Protocol="http" Name="ServiceEndpoint" Type="Input" Port="34013" />
    </Endpoints>`

Thx for help

**Comment by vturecek** [comment]
The extension method [this.CreateServiceRemotingListener(context)](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/develop/src/Microsoft.ServiceFabric.Services.Remoting/Runtime/ServiceRemotingExtensions.cs) is a convenience method that uses default settings for remoting, including an endpoint named "ServiceEndpoint" from ServiceManifest.xml. The "RpcEnpoint" parameter you're passing in is actually the name of the listener that a client uses to refer to a specific listener when you have more than one - you can see it in the service's endpoint in Service Fabric Explorer.

So, you can either use that extension method with an Endpoint definition named "ServiceEndpoint", or you can create a [FabricTransportServiceRemotingListener](https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/develop/src/Microsoft.ServiceFabric.Services.Remoting/V2/FabricTransport/Runtime/FabricTransportServiceRemotingListener.cs) and specify settings yourself.

**Comment by masnider** [comment]
Looks like this one was solved. Great! Closing. Please let us know if you have any other questions or issues, either by reopening this issue here or creating a new one.
