### ISSUE TITLE
Manual to automatic upgrade configuration change triggered cluster downgrade

### ISSUE THREAD

**Issue by RaleS** [Azure/service-fabric-issues#512]
We have followed the [Service Fabric release note](https://blogs.msdn.microsoft.com/azureservicefabric/2017/09/25/service-fabric-6-0-release/) and upgraded cluster to 6.0.211

Once cluster was at 6.0.211, we have sat the 'Fabric upgrade mode' to 'Automatic', and that change triggered a downgrade to 5.7.217

Is this expected behavior?

**Comment by juho-hanhimaki** [comment]
From user standpoint its hard to see how that could be expected.

**Comment by starkna** [comment]
We experienced the same behavior described by RaleS on our cluster today.

**Comment by vaishnavk** [comment]
Currently, version 5.7.217 is the goal version for all clusters in azure. All clusters in Automatic mode tend to upgrade towards the goal version. The only exception is for new clusters which will never be downgraded.

You can set the cluster to manual mode and upgrade it to any valid version. However, when you are setting the upgrade mode back to Automatic, you are asking Azure to take control of the cluster version and hence it is being moved to the goal version.

**Comment by RaleS** [comment]
@vaishnavk Any chance you can indicate current goal version on the 'Fabric upgrades' blade?

**Comment by vaishnavk** [comment]
@RaleS : We are having internal discussions on how we can improve on this experience so that there are no surprises.

**Comment by MikkelHegn** [comment]
To clarify, this was the case before the release of 6.0 refresh (Linux: 6.0.127 / Windows: 6.0.219): https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/13/service-fabric-6-0-refresh-release-for-windows-server-standalone-azure-and-net-sdk/. At this point automatic upgrade will take you to this release.
