### ISSUE TITLE
TargetReplicaSelector : 'RandomSecondaryReplica'  not found when/after upgrading.

### ISSUE THREAD

**Issue by zeodamian** [Azure/service-fabric-issues#514]
As soon as upgrade of the stateful service starts, all services that try to reach it gets this error:

`No endpoint found for the service '...' partition '..' that matches the specified TargetReplicaSelector : 'RandomSecondaryReplica' `

Additionally, this stays so, and only after restarting the nodes will it go away.

So, the rolling upgrade does not give the intended benefits of HA because of this.

What can we do to avoid this error from happening?

Edit: Cloud. 5 nodes. The service has 10 partitions, 5 replicas. version 5.7.217.9494

**Comment by vturecek** [comment]
What are your service using to communicate with this stateful service? Reverse Proxy? Remoting?

**Comment by zeodamian** [comment]
Hi, 
Sorry, I missed that.

Remoting.

**Comment by vturecek** [comment]
@zeodamian  Do you have your remoting listener configured to open on secondary replicas? By default, a listener is not opened on secondary replicas.

**Comment by zeodamian** [comment]
Yes they are configured for this. Everything works as it should until upgrade (requesting data from secondaries).

During and after upgrade it does not. However this is not appearing as often in the 5 node cloud cluster anymore. But cannot guess why.

**Comment by amanbha** [comment]
@zeodamian You mentioned that it doesn't appear as often in 5 node cluster, how many nodes are in the cluster where it appears. Also what is the target and min replica set size for the service?

**Comment by suchiagicha** [comment]
Please re-open if you need more information
