### ISSUE TITLE
Upgrading a stateful service with VisualStudio (F5) fail/hang on a 1 Node cluster

### ISSUE THREAD

**Issue by mathlesp** [Azure/service-fabric-issues#516]
Hello,

Environment:
- Development environment
- Visual Studio 2017 (15.3.5)
- Microsoft Azure Service Fabric **SDK - 2.8.11**

Steps:
- Using the "Service Fabric Local Cluster Manager" system tray icon, make sure the cluster is in 1-Node mode (**Switch Cluster Mode->1 Node**)
- In VisualStudio, New Project->Cloud->Service Fabric Application
- On the New Service Fabric Service page, select "**Stateful Service**" (default Name: Stateful1)
- Right-click the Application project->Properties- and set **"Application Debug Mode" to "Auto Upgrade"**
- **Press F5 to deploy** the application and start debugging (wait for application to be deployed)
- Press Shift+F5 to stop debugging
- Make minor change to Stateful1.cs (i.e. change "Current Counter Value" to "Current Counter Value test1"
- **Press F5 to Upgrade** the application and start debugging

Results:
- The VisualStudio Output window will get stuck on "Waiting for upgrade..." (~30 minutes)
- The Service Fabric Explorer will display the following Warning for the application:
```
The Cluster Resource Manager was unable to find a placement for one or more of the Service's Replicas:
Secondary replica could not be placed due to the following constraints and properties:  
TargetReplicaSetSize: 1
Placement Constraint: N/A
Parent Service: N/A

Constraint Elimination Sequence:
Existing Primary Replica eliminated 1 possible node(s) for placement -- 0/1 node(s) remain. 
```
- Eventually, the upgrade will succeed (~30 minutes)

Workaround 1:
- Manually Publish the application from Visual Studio using the Publish context menu on the application project using UnmonitoredAuto and UpgradeReplicaSetCheckTimeoutSec=1
- Cons: ApplicationTypeVersion must be manually edited each time we need to publish

Workaround 2:
- Delete the Application and redeploy (or use another "Application Debug Mode")
- Cons: state is lost..

Workaround 3:
- Switch cluster mode to 5-Nodes
- Cons: development flow/cycle will be slowed down

Workaround 4:
- Edit "c:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1"
- Find the line "Write-Host "Start upgrading application..."" and insert "$UpgradeParameters["UpgradeReplicaSetCheckTimeout"] = 1" above it:
```
            $UpgradeParameters["UpgradeReplicaSetCheckTimeout"] = 1
            Write-Host "Start upgrading application..." 
```
- Cons: The file will eventually be overwritten when the SDK is upgraded.
- Cons: The Application will display "Quorum lost" warning for 1-2 seconds

Is this a known issue or an "as designed" behavior? Does anyone know of a better workaround?

Thanks

**Comment by dbreshears** [comment]
@mathlesp  - Thanks for detailed repro steps. We should  pass this UpgradeReplicaSetCheckTimeout = 1 param in for this app debug mode on F5 from the tooling (1 node only) so you don't have to update the script .   Also assuming the second Con - the Quorum lost for 1-2 seconds is just annoying but not causing issues?

**Comment by andersosthus** [comment]
@dbreshears 
We've been hit with the same issue as well on our OneNode dev clusters, and I believe the issue is the new setting `IsSingletonReplicaMoveAllowedDuringUpgrade` that was added in 2.7.

In `ClusterSettings.json` that is used to create the local clusters, this setting is set to `true`. There is also no override of this setting in the `ClusterManifestTemplate.json` for OneNode.

Based on how I read that this setting works, if it's true, SF will create the new replica and then swap primary. This doesn't work on a OneNode cluster, since SF will hit placement constraints trying to place the old and new replica on the same node, and thus we got this issue.

The proper fix I believe would be to set `IsSingletonReplicaMoveAllowedDuringUpgrade` to false on OneNode deployments.

**Comment by taxiatms** [comment]
@hrushib can you confirm on what @andersosthus said ?

**Comment by taxiatms** [comment]
@andersosthus , the setting can be override in ClusterManifestTemplate.json for one node.  You can add 

> {

        "name": "FailoverManager",
        "parameters": [
          {
            "name": "IsSingletonReplicaMoveAllowedDuringUpgrade",
            "value": "False"
          }
        ]
}


in fabricSettings

**Comment by andersosthus** [comment]
@taxiatms Ya, we've done that as a workaround, but I believe it should be like that by default for OneNode dev clusters

**Comment by Liphi** [comment]
Will do a code fix to set the value as false by default for OneNode. Thx.

**Comment by dbreshears** [comment]
This sounds good.  I'll hold off on the other change I mentioned earlier then to @mathlesp

**Comment by hbailles3** [comment]
Was this ever fixed?  I'm still running into this same issue when debugging locally with a 1 node cluster in Auto Upgrade debug mode.

**Comment by andersosthus** [comment]
@hbailles3 Not sure if the fix has been pushed out or not, but if you change the value in your ClusterManifestTemplate.json, you'll need to reset your local cluster before the change is applies if I'm not mistaken.

**Comment by hbailles3** [comment]
@andersosthus  OK, so I found out I put the IsSingletonReplicaMoveAllowedDuringUpgrade in the wrong spot in the file. I missed that it was in the "FabricSettings" section.  So, I fixed that, did a reset, did an initial 1 node deploy, stopped debugging, made a change to one of the files, updated the manifest version, then ran debug again.  Took a little bit, but the upgrade did finish. :)  Thanks!
