### ISSUE TITLE
Questions - Service Fabric Deployments

### ISSUE THREAD

**Issue by AndrewJWaite** [Azure/service-fabric-issues#518]
During the recent Service Fabric Q&A session, I asked how to deploy services independently which are part of the same solution and Service Fabric application (meaning all services are built and versioned at the same time) and deployed using VSTS. It was suggested I post a question here.

In addition, another customer asked about deployment best practices. The reply was this is being covered at MS Ignite. Is this presentation online? I would be very interested in seeing this.

Many thanks, Andy

**Comment by MikkelHegn** [comment]
Hi Andy, take a look at this video (it's "old" but still relevant): https://mva.microsoft.com/en-US/training-courses/service-fabric-patterns-and-practices-16925?l=78h5ofSGD_305167344

For individual service deployments, you can use differential packages: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#upgrade-with-a-diff-package

**Comment by MikkelHegn** [comment]
Closing for now, please reopen if there are follow-up questions. Thanks
