### ISSUE TITLE
Service Fabric application always in start up projects

### ISSUE THREAD

**Issue by apoutney** [Azure/service-fabric-issues#52]
Not sure if this is a service fabric issue or visual studios, but we have a solution that contains many projects  which include several web applications and a service fabric application.  Most of the time when debugging we don't want the service fabric application to start up so we have taken it out of the start up projects for the solution. Great, it doesn't run when we click start.  However, if visual studio is closed and re-opened the service fabric application is back in the start up projects.  If i remove one of the web applications from the start up projects, it doesn't come back when i next open visual studio so why is it happening with service fabric applications. 

Its really annoying having to edit the start up projects everyday

**Comment by dbreshears** [comment]
We do set the startup project explicitly in Service Fabric to work around issues where it was getting reset and causing F5 of Service Fabric applications to fail.  At the time it wasn't very clear why this was happening and not a good error message when it did.    We will investigate and see what we can do.

**Comment by kenticomartinh** [comment]
Any update on this? We have the same problem. We have an MVC project in SLN based on the Service Fabric template modified so we can run it during development in IIS Express for faster start-up time and ability to update views and scripts while the application runs. We only run it on local Service Fabric for final testing and deployment. But it keeps resetting the startup project to the Service Fabric one. Is there some workaround for that?

**Comment by MikkelHegn** [comment]
Currently no workaround, but we are working hard to get an updated F5 experience for SF out in the coming months, which should speed up the debug cycle dramatically and support edit and refresh for web projects.

**Comment by dbreshears** [comment]
@kenticomartinh.  Thanks for bringing this back to our attention.  I thought we had done something about this but looks like it might have slipped. I have assigned a bug and we will investigate a better fix for the next release.  Our implementation is too aggressive,  we will either remove the code that does this, or  only set the SFApp as the startup, only if there are zero startup projects in the solution.

**Comment by zaphide** [comment]
Anything further on this? We have similar issues to the above, and would prefer not to split off the SF pieces into separate solution(s).

**Comment by dbreshears** [comment]
Yeah.. This is fixed in the next version of the tooling, just awaiting release which should be fairly soon.

**Comment by jonathh21** [comment]
So.. i am still getting this......

**Comment by dbreshears** [comment]
Which version of Visual Studio?   I just tested on 16.5.1 and didn't repro with these steps

- Created SF application with 3 .net core 3.1 services
- Add .Net Core 3.1 Web project (MVC) and WebAPI project (non-SF)
- Set startup projects on solution to Web + WebAPI
- F5 launches both web projects
- Closed VS and re-opened solution
- Startup projects unchanged, F5 launches both web projects
