### ISSUE TITLE
Reverse Proxy / Naming Service not working as expected

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#521]
Hi guys,

we have a  three-node cluster and until today it was the first time service fabric made some troubles.
We use the built-in reverse proxy / naming service for service resolution.
We use an API Gateway that talks with the SF-Naming Service.

The problem was, that for some services every 3rd request resulted in 404 Not found.
I got the E_SERVICE_NOT_FOUND response (you know what I mean)..

I had to "manually" call each services over the reverse proxy endpoint (19081) to bring back the full functionality. Seems to me that the naming service on one node stopped working correctly.

Did anyone experience something similar?

**Comment by kavyako** [comment]
What is the service fabric version? 

Also, you mentioned:
 1) "some services every 3rd request resulted in 404 Not found. " and
 2) "I had to "manually" call each services over the reverse proxy endpoint (19081) to bring back the full functionality".
What was the difference between 1) and 2). For the first case, were the requests not being sent via the reverse proxy? 
Also when you say "We use an API Gateway that talks with the SF-Naming Service." does this go via the reverse proxy or not? Can  you share a sample request URL and the flow/path of the request from client to service.

**Comment by senj** [comment]
We are currently on 5.6.220

Sorry for the confusion, the confiuration is named ApplicationGateway, in the documentation it is called ReverseProxy and for me, basically, it is a naming service. I mean the lookup via 19081/Application/Service.

In the first case, the call went trough the API Gateway, which routes the call to the SF-ApplicationGateway.
{ API Gateway } -> { Load-Balanced on [host1 - host3]:19081/Application/Service } -> { Service }
In this case, every 3rd request was a 404.

In the second case, I called the service via the ApplicationGateway.
{ host:19081/Application/Service } -> { Service }
In this case, it took some seconds until I got a response but it resolved the address correctly.

**Comment by kavyako** [comment]
In 6.0, we have fixed a bug in the reverse proxy resolution logic where it was returning 404 when the service was up. This sounds similar to that. Can you try upgrading to 6.0 ?

**Comment by senj** [comment]
Is there already a stand alone package for 6.0? As far as I saw, there is a Service Fabric 5.7.221 / 2.7.221 package but 6.0 is on cloud only? But will try as soon as it's released

**Comment by kavyako** [comment]
Standalone package for 6.0 is released, [here ](http://go.microsoft.com/fwlink/?LinkId=730690)is the download link.
Get back to us if you are still seeing the failures with this build.

**Comment by vturecek** [comment]
@senj closing this out, feel free to re-open if you're still hitting this issue in 6.0 builds
