### ISSUE TITLE
PatchOrchestration on premise - Setup error

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#522]
Trying to deploy PatchOrchestration 1.2 on premise (5.7.198.9494) , the application cannot be installed.

The error is (see also attached image)

> **Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:SetupEntryPoint'. There was an error during CodePackage activation.Service host failed to activate. Error:0x80070569**

and in the Event log

> **CodePackageInstance with EntryPointDescription { EntryPointType = ExeExecutable = ExeEntryPointDescription { Program = SetupEntryPoint.bat, Arguments = , WorkingFolder = CodePackage, PeriodicIntervalInSeconds = 0 ConsoleRedirectionEnabled = false ConsoleRedirectionFileRetentionCount = 2 ConsoleRedirectionFileMaxSizeInKb = 20480 }} has failed to transition to the right state while starting. ErrorCode: FABRIC_E_OBJECT_CLOSED=CurrentState=Aborted. CodePackageInstanceIdentifier { ServicePackageInstanceId = PatchOrchestrationApplicationType_App79:NodeAgentServicePkg, CodePackageName = Code }:131522022288671419**

The cluster uses 'windows security' and we see that the setup of NodeAgentServicePkg needs to run as user in Administrators group.

Our questions are
1. Are there any specific settings to enable NodeAgentServicePkg when having windows security?
2. Can we use the POA  on a on premise cluster with WSUS ? (our cluster has no direct internet connectivity)

kind regards
Yannis
![poa](https://user-images.githubusercontent.com/1675899/31445116-bd1edcbc-ae9d-11e7-9187-5baf3e4d5d68.PNG)

**Comment by novino** [comment]
Yes, NodeAgentServicePkg requires to be run as admin. Could you try adding below in your cluster manifest.
Ref: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security
```
"ClientIdentities": [
{
"Identity": "NT AUTHORITY\\SYSTEM",
"IsAdmin": true
}
]
```

You can use POA with WSUS, we've tried this on a Azure based cluster using one of the Azure VM's as WSUS server. 
If your machines/VM's are already configured to get updates via WSUS (located on intranet), you can go ahead and install POA on your cluster. Let us know how it goes.

**Comment by dealboy** [comment]
Hi again,

I modified the application manifest and installation works fine! Thanks!

Do you have to do extra configurations on WSUS group policies to work with Service Fabric?
In documentation ( https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application )  it states: 
> However, if the settings are managed by an administrator or group policy, we recommend setting the Windows Update policy to “Notify before Download” explicitly.

is this the only setting required?

**Comment by novino** [comment]
> I modified the application manifest and installation works fine! Thanks!

Nice to hear that.

> is this the only setting required?

Yep, windows update policy is the only settings you'll have to change. The idea is to let POA handle the windows update installation. 
By default POA will try to set the windows update policy on user's behalf on all cluster nodes, so you may not require this step also. In case POA is unable to set the right policy (eg: due to  permission), POA will emit warning level health report against the affected nodes.
