### ISSUE TITLE
Service Fabric Runtime cannot be installed if user folder contains special characters

### ISSUE THREAD

**Issue by barishamil** [Azure/service-fabric-issues#525]
Log:
10/12/2017 10:58:27 AM running: C:\Users\Barış Hamil\AppData\Local\Temp\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric" /E /Y

Console screen:
Unable to extract exe. ExitCode: 1

I installed it from another user successfully

**Comment by taxiatms** [comment]
The installer needs to access the %temp% folder to extract some files during installation. So if the username contains special characters, it could be a problem. We will fix this in the next release
