### ISSUE TITLE
Custom StateSerializer does not replicate state correctly 

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#529]
Hey folks,

I don't know if it's related to #158, I have written a custom implementation of IStateSerializer with Newtonsoft Json and it works with target replica = 1, but as soon as I want to use more than one, on replication, the following error occurs:

`Replica had multiple failures innode2 API call: IStatefulServiceReplica.Open(); Error = System.Runtime.Serialization.SerializationException (-2146233076)
There was an error deserializing the object of type Models.NewsletterRequest. The input source is not correctly formatted.
`

I guess the Replica uses another serializer than the one I registered with `TryAddStateSerializer`.
How can I fix this? If it's the same problem as in the other issue, I'll wait for the `incoming fix`

Thanks..

**Comment by mcoskun** [comment]
In your one replica case, what happens when you restart the replica? Does it also start to fail?
Are you calling [TryAddStateSerializer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.ireliablestatemanager.tryaddstateserializer?view=azure-dotnet) inside the constructor of Stateful Service?

**Comment by senj** [comment]
No I added it later in a Singleton. After review, it also fails with 1 replica.
Now I serialize the data first (json) and use the default serializer. Works for me.

**Comment by senj** [comment]
No I added it later inside a Singleton ctor. After review, it also fails with 1 replica.
Now I serialize the data first (json) and use the default serializer. Works for me.
