### ISSUE TITLE
Configuration files continually require committing to source control

### ISSUE THREAD

**Issue by apoutney** [Azure/service-fabric-issues#53]
Service fabric projects have several configuration files (Settings.xml, ApplicationManfiest.xml, ServiceManifest.xml).  This files seem to be rewritten every time the projects are built in visual studio, this causes the source control to think that the files have been edited (even though the file is identical to that in source control) so they always appear in Pending Changes.

I dont think I can simply ignore these files from source control because contain information required to run the applications but i dont want to have to keep committing files to going through and excluding them from Pending Changes. 

Is there a solution to this?

**Comment by amanbha** [comment]
What version of Service Fabric SDK are you using? Are the files actually modified? If you are using git does it shows file as modified?

**Comment by apoutney** [comment]
I currently have version 2.2.207.9590 of the Service Fabric SDK installed, however the projects would have been created whilst using an earlier version.  We're not using git, we have TFS and it shows in VS as being modified and is listed as pending changes, however there has been no change to the files.

**Comment by amanbha** [comment]
Thanks for providing the SDK version. What's the nuget package version used by Actor projects? Would it be possible to update the nuget package version in these projects to the latest and see if the issue persists.
Could you also check that there are no changes in terms of spacing or formatting? Does this happen for every build even after you commit these files?

**Comment by ravipal** [comment]
As part of build we run a utility script that can potentially modify the ApplicationManifest.xml and ServiceManifest.xml, so we checkout these files before running the utility otherwise it will fail.

As a workaround ca you use 'tfs undo' to undo checkout of unmodified files before committing the changes?

**Comment by apoutney** [comment]
I can do 'tfs undo', but I don't really want to have to keep doing this every time i commit anything.

Surely other project types do similar things with their config files, but they don't keep appearing in pending changes so there must be a way to solve this

**Comment by LeroyK** [comment]
This is very annoying indeed, especially when you have several SF projects. I currently get 48 pending changes just by building the solution, none of which are actually modified.

Can't this bug be fixed by only checking out the files when they get changed? Perhaps by first storing the potential new version in a temporary folder or in memory and doing a comparison afterwards.

What may work as well (only for local TF workspaces) is to instruct VS / TF to save the file after the SF build task is done with it. I am suggesting this because if I open the file in VS and save it, it detects that it hasn't changed, and removes the change automatically. Perhaps this works as well if you do this using VS SDK.

We are currently using SF tools version 5.3.301 (as of writing, the latest version).

This should get priority for the next SF release.

**Comment by LeroyK** [comment]
Actually, I don't think you need to do a checkout at all when it's a **local** TF workspace. So the fix may be to only checkout the file when it's in a **server** workspace.

**Comment by MikkelHegn** [comment]
Added this as a bug to our backlog. Will report back once we have investigated what can be done.

**Comment by sstrodel** [comment]
have there been any updates on this? any workarounds in VS?

**Comment by karolz-ms** [comment]
Just to clarify: you experience the issue with TF workspaces, but not with Git repositories, correct?

**Comment by apoutney** [comment]
I haven't tried it using Git so I couldn't say for sure, Ive only had these issues using TFVC.

**Comment by sstrodel** [comment]
we are seeing the issue with TFS and VS

**Comment by sklappal** [comment]
We are also starting to use service fabric and faced this annoying issue. We are using TFS as source control and VS 2015.

**Comment by mtucker2112** [comment]
Any update on this?  We also see this issue.

In the meantime, for others with this issue.  We added this TFS 2015 Powertools call as an external tool (Tools > External Tools) to more easily undo checkout of all these XML files:

```
Command: %windir%\System32\cmd.exe
Arguments: /C echo y | "%ProgramFiles(x86)%\Microsoft Team Foundation Server 2015 Power Tools\TFPT.EXE" uu /recursive /noget
Initial Directory: $(SolutionDir)
Use Output Window: true
```

It works, but it's still a pain to have to do this every time you compile.

**Comment by dbreshears** [comment]
@mtucker2112, We have bumped up the priority of this and started discussing options for a fix.   Hope to have something in an upcoming release.

**Comment by jgmeier** [comment]
Looking forward to a fix for this as well.  It has been quite the nuisance.

**Comment by mtucker2112** [comment]
Any update on this fix?  We upgraded to the latest bits yesterday and this appears to still be happening.

**Comment by dbreshears** [comment]
In the upcoming release which should happen sometime this month,  we are enabling a property you can add to the .sfproj file so that we don't add default services during build.    

You can also leverage this property to _**workaround**_ this issue with our build process and the TFVC provider.  By setting UpdateServiceFabricApplicationManifestEnabled=false  in the .sfproj you can turn off updating the manifests during the build and thus we don't checkout the files prior as well.    I'll be curious to see if this will help with the issue, suffice as potential fix to the problem.  If not then we can pursue other potential fixes as discussed earlier in the following release.

**Comment by jackbond** [comment]
@dbreshears Will the UpdateServiceFabricApplicationManifestEnabled feature be part of the   Microsoft.VisualStudio.Azure.Fabric.MSBuild Nuget package. If so, is it included in the 1.6.1 version which was released on 8/15/17. If so, where in the .sfproj file do you place it? Thanks

**Comment by dbreshears** [comment]
Yes. This is in the latest release on 8/15.  It is not in the Nuget package but in the updated extension for our 1.7  tooling.  You can add a reference as such to the top of the .sfproj file

```
 <PropertyGroup Label="Globals">
    <ProjectGuid>156be188-fbe5-418b-ac29-eb329dba33f2</ProjectGuid>
    <ProjectVersion>1.7</ProjectVersion>
    <MinToolsVersion>1.5</MinToolsVersion>
    <UpdateServiceFabricApplicationManifestEnabled>false</UpdateServiceFabricApplicationManifestEnabled>
    <SupportedMSBuildNuGetPackageVersion>1.6</SupportedMSBuildNuGetPackageVersion>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
  </PropertyGroup>

```

**Comment by sklappal** [comment]
This does not work in my case.

Expected: The files Settings.xml, ServiceManifest.xml for all services, ApplicationManifest.xml and the application parameters for the application do not get checked out during build.

Actual: All the mentioned files get checked out and not modified during the build.


My sfproj header looks like the following. I have two service fabric applications in my solution.

  <Import Project="..\..\Packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.1\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\..\Packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.1\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>ee429e06-2def-4dbe-9837-5997d3befc0f</ProjectGuid>
    <ProjectVersion>1.7</ProjectVersion>
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <MinToolsVersion>1.5</MinToolsVersion>    
    <SupportedMSBuildNuGetPackageVersion>1.6</SupportedMSBuildNuGetPackageVersion>    
 <UpdateServiceFabricApplicationManifestEnabled>false</UpdateServiceFabricApplicationManifestEnabled>
  </PropertyGroup>

I have Visual Studio Enterprise 2015 Update 3. We just upgraded to Team Foundation Server 2017 source control.

**Comment by dbreshears** [comment]
I just tested this scenario with VSTS / TFS on VS 2015 Update 3 and latest 1.7 tooling and wasn't able to repro.     Are you referencing the same service projects from both SFApp projects, and if so,  is this setting in both .sfproj files and did you close and re-open solution?  What is the makeup of services in the SF applications?   Double checking that the version in Programs and Features for the tools is  1.7.50721.2?         

I don't believe the version of TFS would matter, we don't call any TFS client code to  check out the files when this property is set.    So somehow it seems that the property isn't set when reaching this code.   If still not working for you, can you share the detailed MSBuild output from the build?

**Comment by sklappal** [comment]
Thanks for the pointers @dbreshears! I was now able to get it working. The issue was indeed on my end, I had not installed the tools version 1.7.50721.2. 

Btw - as this is presented as a workaround, are there some drawbacks in turning this setting to false?

**Comment by dbreshears** [comment]
You will need to manage the manifest updating yourself manually or update the property to true and reload the solution.   For instance if you add new Actors or remove referenced services from the SF application the tooling won't update the manifests accordingly are a couple of instances I can think of.
