### ISSUE TITLE
Unable to use Refresh Application with .Net framework 4.6.2

### ISSUE THREAD

**Issue by dazhang88** [Azure/service-fabric-issues#530]
I am unable to use Refresh Application with .Net framework 4.6.2. The initial F5 works fine, but after I stop my application, make some changes, and hit F5 again, my micro-services are not being stopped, which means the build fails because it's not able to copy the EXE to the output directory. In the Build window, I see weird error messages like "Sequence contains more than one matching element" and "Operation timed out." - full output is here: [output.txt](https://github.com/Azure/service-fabric-issues/files/1384271/output.txt)

**Comment by MikkelHegn** [comment]
@dbreshears

**Comment by dbreshears** [comment]
@dazhang88,  I'm unable to repro with initial test using a simple application w/ a single asp.net core MVC web service.  .  Does this not occur with .Net framework 4.6.1?  I'll do some more testing with more complex solutions.   in the meantime, do you repro with a simple test?  What is the makeup of you solution with regards to projects,  services and references.

**Comment by masnider** [comment]
@dazhang88 - Hi there - we haven't heard back from you on this. At this point we're going to close the issue. If you have more information about what you've tried that you can share with us, please just reopen the issue and let us know, or feel free to create a new issue if you prefer.

**Comment by dazhang88** [comment]
Matt, thanks for following up. I've followed up with Devin offline, and the issue is now understood.
