### ISSUE TITLE
TimeoutException after upgrading to 6.0.219

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#532]
@mani-ramaswamy 

After upgrading to 6.0.219 (and Windows Creators Update, and .NET 4.7) - I did all the upgrade at once (so not sure which one was the trigger) reliable collections started to work a bit faster. However I started getting timeout exception in places I would never expect them, i.e. in `SetAsync()` (after reading key earlier with `LockMode.Update` - so there should be no locking issues. Before I have never seen TimeoutException in reliable collections when they were used carefully lock-wise. 

Exception comes from TStore.

```
   at System.Fabric.Store.TStore`5.<AddOrUpdateAsync>d__224.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.Collections.DistributedDictionary`2.<AddOrUpdateAsync>d__98.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

I've tested both SDKs 5.8.211 and 5.8.219 (and also 6.0.211 runtime after downgrading).

UPDATE: This is all kind of strange. I think it's mostly related to upgrading application from .NET 4.6.1 to .NET 4.7. As I am able to reproduce this behavior on 6.0.211 as well. I started getting this exception on a machine which was never updated to 6.0.219.

UPDATE2: I have made additional tests and It seems to be unrelated to the .NET version. Apparently, I have not been running performance tests since updating to 6.0, but it seems that 6.0 introduces SIGNIFICANT performance improvements to the reliable collections and now reliable collections are blazingly fast and this TimeoutException is a side-effect of perf-work related to the increased throughput,

**Comment by preethasubbarayalu** [comment]
A transaction can be granted an update lock if there are readers in flight and there are no writers. If it was granted when there are existing readers, it cannot be promoted to an exclusive (write) lock until the existing readers are drained. You can see a timeout in this case. Once a transaction is granted an update lock, no new transactions can acquire a read or write lock.

Please refer to the lock matrix in the link below for more details:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-reliable-collections-transactions-locks
Note: This is not a recent change. It has always been the case.

**Comment by mkosieradzki** [comment]
Thanks @preethasubbarayalu ! That explains really a lot. You are right! There is a Repeatable Reads isolation level set for ReliableDictionary reads. I don't know why I thought that Snapshot is the default isolation level - perhaps because it sounds the most reasonably?

Is there any way to decrease isolation level for reliable dictionary to snapshot?

The recent change that triggered this is probably some other perf-work that increased some throughput.

**Comment by preethasubbarayalu** [comment]
@mkosieradzki - We currently don't have a way for you to change isolation level. On primary, enumerations by default use snapshot and point reads use repeatable read. We will look into exposing isolation levels.
In your scenario, I assume you read a key and then update it based on what you have read. If that is the case, when the isolation level is repeatable read, once you take a read lock you are guaranteed that no other transaction can update it before your write. Please correct me if my assumption is wrong.

**Comment by mkosieradzki** [comment]
@preethasubbarayalu  - Nope. If I read a key and intend to update it I always take a write-lock when reading (by using LockMode.Update - to avoid deadlocks on lock upgrades, but also to prevent other transactions from altering my value).

Please also take into consideration that we are a in single process and I one can use some additional standard locking mechanisms when required (as no distributed locks are required in stateful services).

If I only read a value and do not intend to update this value I am forced to take an read lock today :-( while to me it makes no sense as I would prefer to get a lock-free snapshot to have consistent reads and that's definitely a strong enough guarantee for me.

This read lock provides in some scenarios but for me it is not beneficial at all.

This probably explains a lot why I am observing a better throughput on my alternative backend which uses RocksDB (there is a high lock contention on some often-used keys due to Read-Locks).

@preethasubbarayalu, thanks a lot for looking into this.

One option I can see would be to change the API without affecting preexisting customers:
Add `LockMode.Snapshot` so instead of acquiring the read lock (default) one can decide to have no lock - only snapshot.

But even a better solution to me to would be to allow changing of the isolation level when creating transactions. I will, due to my personal preference, probably nearly always use snapshot.

Because this is related: I would really love to be able to create a long-running, read-only snapshot transaction. Such a transaction would keep snapshots of keys in database but would not block any operations including delete. In terms of RocksDB it means creating a snapshot, but no pessimistic transaction.

**Comment by preethasubbarayalu** [comment]
Yes, we will be exposing snapshot support soon.
