### ISSUE TITLE
Debug error on service fabric cluster with internal load balancer

### ISSUE THREAD

**Issue by govjobss** [Azure/service-fabric-issues#533]
I have 2 node cluster with one public loadbalance for frontend and internal loadbalancer for backend(primary node).  i have VS in same subnet as backend node but the debug is  giving error on 
 internal load balancer. 
is there any limitation with internal lb or vs debug?

**Comment by ravipal** [comment]
Remote debugging is supported only on cluster with public load balancer with IP address.

**Comment by masnider** [comment]
Two node clusters are not supported.
