### ISSUE TITLE
WF-App-4294967295-{guid} user group

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#537]
I was having a look at my user accounts and groups and saw that there's this `WF-App-4294967295-{guid}` group with the users `P_FSSUserffffffff` and `S_FSSUserffffffff` in it. Any idea what this is from? Its description is `WinFabApplication-LocalGroup` which is similar to other created groups by SF.

An app ID of 4294967295 sounds to me like something has gone wrong, or someone's set it as a hard-coded value as a temporary workaround? Is it safe to remove this group?

**Comment by oanapl** [comment]
Service Fabric creates the group and the users for internal usage. They are needed, so please do not remove.
The users P_FSSUserffffffff and S_FSSUserffffffff are used by image store for authentication when executing SMB copy operations between nodes. The name of the users represent "primary file store service user" and "secondary file store service user" (the cryptic names come from the user name size limitation in Windows).
The application id is an internal number we are using. It looks correct. It's not hard-coded, we generate it.

**Comment by Mardoxx** [comment]
Thanks for your prompt and informative reply :)

I doubt anyone need worry about 4294967294 applications being registered!

**Comment by ConX-Ryan** [comment]
What is the default user password for these ? i have a conflict with HP Sure Start and it appears that these users are the only windows users displayed

**Comment by oanapl** [comment]
There is no default password, we generate the password by hashing a secret using the specified certificate found on the node. The same algorithm is used on all nodes, so we can then use NTLM to authenticate the SMB shares our image store needs.
