### ISSUE TITLE
Stop Publish-*ServiceFabricApplication from printing ApplicationParameters

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#538]
I store some sensitive info like connection strings in my app params..The `Publish-*ServiceFabricApplication` outputs all these in its log e.g.

```
2>ApplicationName        : fabric:/Identity
2>ApplicationTypeName    : Identity
2>ApplicationTypeVersion : 2.0.0
2>ApplicationParameters  : { "ConnectionString" = "Persist Security Info=False;User 
2>                         ID=user;Password=SecretPassword;Initial Catalog=db;Server=10.0.10.10";
```

I understand I can encrypt these, and I probably will when it comes to production, but It would be nice if these commands printed the keys by default, and only outputted the values if a flag was set (e.g. for debugging) Just doesn't seem right having sensitive info printed in plain text in my deploy logs!

**Comment by mkosieradzki** [comment]
Is something wrong with encryption? I use encryption in all the environments: development, testing and production.

**Comment by masnider** [comment]
@Mardoxx yeah, we'd recommend that those should be encrypted parameters and then decrypted by the service at runtime. That should solve the problem.  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management

**Comment by Mardoxx** [comment]
No, no, nothing wrong with encryption  -  I was just being lazy :smile:

Thanks!

**Comment by VipulM-MSFT** [comment]
We cannot change the default behavior of the command or API as it would be a breaking change. However we have included an option to exclude application parameters as an optional argument.

 Get-ServiceFabricApplication -ExcludeApplicationParameters
