### ISSUE TITLE
Unable to load DLL Fabric.Common.dll when trying install standalone Azure Service Fabric

### ISSUE THREAD

**Issue by Valeriy1991** [Azure/service-fabric-issues#539]
Hello!

I'm have virtual machine with Windows Server 2012 R2 Standard onboard. I'm trying to create Azure Service Fabric 6.0.219.9494 by following this instruction: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server (step 1C - "Create an offline (internet-disconnected) cluster"). 

When I'm run this command:
`.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.json -FabricRuntimePackagePath .\MicrosoftAzureServiceFabric.6.0.219.9494.cab -AcceptEULA`
I'm getting an error:
![error-install-ASF-6-0](https://i.imgur.com/yphcxKW.png)

This virtual machine does not have an internet access.

What I'm doing wrong?

**Comment by Liphi** [comment]
Have u installed SDK on this machine? If so, pls make sure the SDK/ runtime versions installed with the SDK package is the same as the Standalone version u wanna deploy, or to simplify just uninstall SDK/ runtime on this machine.

**Comment by Valeriy1991** [comment]
@Liphi thanks, but where can I find the SDK offline installer? I'm only found the download links for Standalone package and for the cab file. None of them is SDK, right? Also I'm found link to download file MicrosoftAzure-ServiceFabric-CoreSDK.exe, but this is Windows Platform Installer, that requires Internet access... I'm not found link for download SDK offline installer in ASF documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started). In this article contains links to download SDK for Visual Studio. But why do I need Visual Studio on the server machine, where I've planning install only ASF?

**Comment by Liphi** [comment]
I mean, first of all, before running CreateCluster.ps1, u'd better NOT install SDK or runtime on the machine.
Secondly, may I know the .net version installed on ur box? The tools in the deployment package are built on .net 4.5.

**Comment by Valeriy1991** [comment]
@Liphi I'm was not installed any additional .NET Framework to my virtual machine. Only one that comes along with Win Server 2012 R2 Standard

**Comment by Liphi** [comment]
U need to install .Net 4.5 on both the control node (the machine where u run CreateCluster.ps1) and every cluster node. Could u check?

**Comment by Valeriy1991** [comment]
@Liphi I installed .NET Framework (firstly 4.5.2 then 4.6.2) - the result the same

**Comment by Liphi** [comment]
@maburlik Hi Max, do u have any suggestion on further diagnostics ?

**Comment by maburlik** [comment]
Please check in your system PATH environment variable to see if a different version of FabricCommon is coming from another directory.

Have you had the SDK installed on this machine before? If so there may be artifacts left behind.

**Comment by Valeriy1991** [comment]
@maburlik PATH is: %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\

> Have you had the SDK installed on this machine before?
No. I tryed to install ASF immediately after creating the virtual machine.

**Comment by maburlik** [comment]
Please scan your system drive for any instances of FabricCommon.dll, and check event viewer for the time frame of when you are making the call to see if there are any missing system-level dependencies. It could be that you are missing some Windows updates to run VC++14 binaries.

To determine if this is the issue, try running the vcredist installer manually: https://www.microsoft.com/en-us/download/details.aspx?id=48145
or install the dependent Windows update:
https://www.microsoft.com/en-us/download/details.aspx?id=49063

**Comment by Valeriy1991** [comment]
Yeah, link to "Visual C++ Redistributable for Visual Studio 2015" has helped - the ASF was installed successfully. @Liphi @maburlik thanks.
