### ISSUE TITLE
Change property Trace/Etw in SF Standalone

### ISSUE THREAD

**Issue by juscelior** [Azure/service-fabric-issues#541]
How can I change the Trace/Etw property?

<Parameter Name = "Level" Value = "4" />

I found how to do for the azure, but not for standalone.

**Comment by Liphi** [comment]
Which exact properties on the cluster manifest do u wanna change?

**Comment by juscelior** [comment]
this one -> Level for 2

`<Section Name="Trace/Etw">
      <Parameter Name="Level" Value="4" />
    </Section>
`

**Comment by Liphi** [comment]
Just like Setup/FabricLogRoot, a Trace/Etw section could be added under FabricSettings on the Standalone cluster json config.

**Comment by Liphi** [comment]
Will close the thread for now. Any more questions, feel free to re-activate it. Thx.
