### ISSUE TITLE
SF reported healthy Application when it was down

### ISSUE THREAD

**Issue by CodedBeard** [Azure/service-fabric-issues#542]
Not sure this is directly a Service fabric issue per say, but thought I'd log it anyway.

Earlier today, I pushed an updated docker compose application from VSTS onto our Azure SF cluster (Version 6.0.211.9494). Normally this will result in Application gateway reporting no connectivity for a few seconds before the containers finish spinning up, however this time, the alert was still going after a couple of mins for 3 out of the 4 containers in the application.

I went to SF Explorer, and it reported everything as healthy, with no current warnings/errors. So I then tried to browse directly to one of the containers that Application gateway was reporting it could not reach, and sure enough I could not connect directly either.

I then connected to one of the hosts with the failing container, and could see the container was running, however when I then docker exec into the container, I discovered that the container networking had failed to bring up the network properly. Simply stopping the container on that host, caused SF to detect the container stopping and start it on another host, which then worked fine.

I guess my issue is, that I would have expected SF to be able to detect that the container network had not started correctly, and automatically restart/move the container in an attempt to resolve the network issue. Should that have been the case, or is this not something that SF can support?

**Comment by RajeetN** [comment]
Did you have a healthcheck defined for the container so SF could detect that networking was not enabled? In upcoming release of SF, if you have a healthcheck policy defined SF can monitor for container health events and restart the container as needed. If there is no health check, SF wont be able to detect this

**Comment by CodedBeard** [comment]
Hi @RajeetN, yes the container does declare a healthcheck, although that uses localhost within the container, so not sure it would have actually failed (I didn't check it at the time).
Any idea of a general time frame to support healthchecks? 6.1/6.2 or later?

**Comment by oanapl** [comment]
@CodedBeard , see more information about HEALTHCHECK support at https://github.com/Azure/service-fabric-issues/issues/503

**Comment by mani-ramaswamy** [comment]
General time frame will be in the next 2-3 months.

**Comment by mani-ramaswamy** [comment]
This is available in 6.1. Refer to https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-docker-healthcheck
