### ISSUE TITLE
InQuorumLoss after removing reliable state and data class

### ISSUE THREAD

**Issue by silvioboehme** [Azure/service-fabric-issues#543]
Fabric Version: 6.0.211.9494

I have a running stateful Service with one reliable dictionary calles "MySamples" where key is Guid and Value is MyClass (with DataContract, DataMember...). Everything is fine so far.

I want to remove the  reliable dictionary AND MyClass.
I was trying this steps without success:

1.) remove all access to MySamples

2.) Update Cluster -> Fine

3.) delete the  reliable dictionary with StateManager.RemoveAsync("MySamples")

4.) Update Cluster -> Fine (if i call RemoveAsync again, it throws an error, because there is no reliable state with this name -> this is fine an expected)

5.) Delete the class MyClass from source code

6.) Update Cluster -> Failed, all Replicas are down and "InQuorumLoss" after this Action

Why? Whats the prefered way to delete a reliable state from an running cluster without leaving a unused data class?

Thanks
Silvio

**Comment by masnider** [comment]
In step 6, how did you update the cluster? If the upgrade was a normal rolling one with health checks I would have expected it to catch that the replicas were not coming back and halt after the first upgrade domain. @mcoskun may be able to help figure out what's going on and whether you can recover the existing service in place, if that's what you're trying to do. He also may be able to note any missing steps here.

**Comment by silvioboehme** [comment]
All upgrades were "Unmonitored Auto", because i checked this on my local dev machine.
Maybe this is an Explanation for the crash.

But why is this a Problem, to delete an unused class?? How can i delete this?
I removed all states but can't delete the old class?

My temp solution is:
Remove everything from MyClass, but leave the class in the assembly.

**Comment by mcoskun** [comment]
Hi @silvioboehme , [IReliableStateManager.RemoveAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.ireliablestatemanager.removeasync?view=azure-dotnet#Microsoft_ServiceFabric_Data_IReliableStateManager_RemoveAsync_Microsoft_ServiceFabric_Data_ITransaction_System_Uri_System_TimeSpan_) is a delayed operation where the effects would be visible immediately after commit, but the actual Reliable State/Collection and its persisted state will not be deleted until it is safe (it will never be needed for building another replica and it cannot be false progressed). Since we do not expose when it is safe to the user, you cannot delete a type being used in a Reliable Collection safely.

I will create a work item to track this internally.

**Comment by quangtran-groove** [comment]
Hi @mcoskun ,

Could you please help me to explain more about how 'IReliableStateManager.RemoveAsync' works?

I am falling into this situation: when I try removing a Reliable Dictionary, the disk capacity of that Reliable Dictionary doesn't be cleared immediately even if the Reliable Dictionary's state was actually removed.

Thanks

**Comment by masnider** [comment]
@zuhairp / @preethasubbarayalu - what do we recommend customers do today in order to force a checkpoint?

**Comment by zuhairp** [comment]
> what do we recommend customers do today in order to force a checkpoint?

One way is to set [LogTruncationIntervalSeconds ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-configuration#configuration-names-1) to a non-zero number (preferably to something in the range of minutes, not seconds, to avoid perf degradation) and wait. Unfortunately, there isn't any good way to know when the checkpoint happens and completes, but if you wait long enough, in most cases, it will have occurred.

**Comment by zuhairp** [comment]
Closing issue since there hasn't been any additional recent activity
