### ISSUE TITLE
azure service fabric in visual studio hresult 0x80131500

### ISSUE THREAD

**Issue by thdotnet** [Azure/service-fabric-issues#545]
I've just faced this strange issue which is also described in here:

https://stackoverflow.com/questions/42278795/azure-service-fabric-in-visual-studio-hresult-0x80131500/42489250#42489250

After downloading the Visual Studio 2017 Enterprise Edition and adding Service Fabric SDK. Steps to reproduce:

1-Download Visual Studio Enterprise from www.visualstudio.com
2-Select Web and Cloud during the install process
2.1-Select .NET Core
3-Select Service Fabric on Individual Component Tab

File new project, Service Fabric, ASPNET Core Serverless application.

It will throw the error. The curious thing: if I install the community edition, and selecting the same items, it works fine.

**Comment by taxiatms** [comment]
@thdotnet Have you installed SDK through WebPI?

**Comment by thdotnet** [comment]
@taxiatms from both: VS installer and WebPI

**Comment by taxiatms** [comment]
@thdotnet Are you able to setup a cluster without deploying any apps to it? You can do that by using the "Service Fabric Local Cluster Manager" tray icon.

**Comment by thdotnet** [comment]
I am using Vs Community at this moment. I could not wait for a response / solution. I've just reported this issue because it's affecting others (like the stackoverflow link)

**Comment by taxiatms** [comment]
@dbreshears Customer is saying VS enterprise has some issues and VS Community doesn't.

**Comment by dbreshears** [comment]
@thdotnet, @taxiatms ,   I don't know of any installation issues are specific to Enterprise SKU.   What I have seen is that VS 2017 Install fails for another reason and thus doesn't get to installing our project / service templates properly.   In that case,   a Repair of the VS installation with Azure Workload and Service Fabric tools should fix this issue, assuming the repair is successful.   The StackOverflow issue was specific to 2015 and WebPI and thus a different issue at the time,  the HRresult error being thrown is fairly generic and can manifest in more than one way, but typically has indicated issues with the template isntallation

**Comment by dbreshears** [comment]
Also, I am assume by step #2 with "web and cloud", that you have the "ASP.NET and web development" and the  "Azure development" workloads installed.

**Comment by thdotnet** [comment]
I know it's outdated, but it's exactly the same error. And the problem is exactly what you've described, it seems that it's not installing the templates properly (only for VS 2017 Enterprise). Feel free to close this if you think it's not an issue, I just would like to report it because it can affect others too.

**Comment by thdotnet** [comment]
yes, asp.net and web development and azure development were installed

**Comment by dbreshears** [comment]
Curious, did you happen to have Azure SDK installed on this machine?

**Comment by thdotnet** [comment]
yeap

**Comment by dbreshears** [comment]
Ok,  what "might" have occurred as I have seen it happen several times now, is that if the Azure Storage emulator is running (tray icon) when the VS installation is going, the storagemulator msi fails to install and thus kills the VS 2017 installation as well, prior to installing our templates.   There is an open issue with the  address this with the storageemulator msi

**Comment by dbreshears** [comment]
I closed, please re-open if you need to revisit this.

**Comment by thdotnet** [comment]
that was not the case. A brand new laptop with no VS / emulator on it.

**Comment by maxamorim** [comment]
I've faced the same problem today with VS Community 2017, i've discovered in my case that was the language package. I have pt-BR installed and no english package, i've uninstalled my current language package and installed the english package (maybe service fabric only work with english package). Hope this helps.

**Comment by dbreshears** [comment]
@maxamorim,    we will investigate our templates not working on pt-BR and follow up.  @thdotnet, I walked through your repro steps again today but couldn't repro on a clean machine,  I assume you were able to get things working through VS installation repair?    For #3 in your repro steps, the Service Fabric tools are default in the Azure workload so they should have already been checked in the components tab.

**Comment by thdotnet** [comment]
I think I first did the installation through web platform. And then, the VS one. Maybe it was a conflict between the two. I'm not sure what I did, but I could only solve installing the VS Community. VS enterprise was not working even after some repairs and reinstalling it.

**Comment by robertoprjr** [comment]
@maxamorim, I was with the same problem that you were and when I've changed the language package for English, it works!! Probably some incompatibility with pt-BR
