### ISSUE TITLE
Specified cast is not valid calling System.Fabric.FabricRuntime.GetActivationContext()

### ISSUE THREAD

**Issue by grantborthwick** [Azure/service-fabric-issues#546]
After updating from version 2.7.198 to 2.8.219, we get the following exception when calling System.Fabric.FabricRuntime.GetActivationContext():

```
System.InvalidCastException: Specified cast is not valid.
   at System.Fabric.Interop.NativeRuntime.FabricGetActivationContext(Guid& riid)
   at System.Fabric.FabricRuntime.NativeFabricRuntimeFactory.GetCodePackageActivationContextHelper()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
   ... our service code
```

I only see this exception when executing in my cluster on Windows in Azure, not when running locally.

The Azure Portal reports the Service Fabric version as 5.7.217.9494 and we're using Automatic upgrade mode. We're also using version 1.6.3 of Microsoft.VisualStudio.Azure.Fabric.MSBuild to build and package our sfrpoj.

**Comment by amanbha** [comment]
You need runtime version of at least 6.0.* to work with 2.8.* nuget packages. Since you are using Automatic upgrade, it should have been updated, @vaishnavk for help with as to why the cluster is still in older runtime.

**Comment by vaishnavk** [comment]
We are in the process of rolling out 6.0.* version globally. If you cluster is set to Automatic upgrade, it should haven't already received it by now or will receive it by Monday.

**Comment by grantborthwick** [comment]
I now see version 6.0.219.9494 in my clusters, and have successfully upgraded to Microsoft.ServiceFabric.Services version 2.8.219.

Do you expect that you'll make breaking changes to this package like this in the future that will require newer runtime versions to be installed? If so, where do you document these changes publically? I would like to know when this occurs.

Thank you!

**Comment by amanbha** [comment]
@grantborthwick Thanks for confirming. To answer your question about requiring newer runtime, that could happen, our support matrix is listed here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#supported-service-fabric-versions
