### ISSUE TITLE
Custom ActorFactory for V2 fails

### ISSUE THREAD

**Issue by patrikSE83** [Azure/service-fabric-issues#547]
Hello. I just migrated to V2 remoting in my projects. And I never got my Actors to be able to communicate when I forced V2 only (RemotingListener.V2Listener).

After alot of tests, I found out that it was my custom ActorFactory that was causing the issues. When creating a custom Factory that points to V2 (same as services) but an ActorProxyFactory it seems like it's using the V2Client (when looking at the proxy) but I guess it's talking against the wrong endpoint.

Because I get;

Type 'Microsoft.ServiceFabric.Actors.Remoting.V2.ActorRemotingMessageHeaders' with data contract name 'ActorHeader:urn:actors' is not expected.

When moving to the default ActorProxy it identifes the service as a V2 and can communicate without any issues. So this issue is located somewhere in the;

```
public static IActorProxyFactory CreateActorFactory()
    {
      IActorProxyFactory clientfactory;

      var settings = new FabricTransportRemotingSettings();
      settings.OperationTimeout = TimeSpan.FromSeconds(30);
      settings.MaxMessageSize = 1073741824;


      var retrySettings = new OperationRetrySettings(TimeSpan.FromSeconds(30), TimeSpan.FromSeconds(1), 5);

      var clientFactory = new Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory(settings);
      clientFactory.ClientConnected += ActorClientFactory_ClientConnected;
      clientFactory.ClientDisconnected += ActorClientFactory_ClientDisconnected;

      clientfactory = new ActorProxyFactory(
          (h) =>
          {
            return clientFactory;
          }, retrySettings);


      return clientfactory;
    }
```

Sorry for the full namespace references - it's because I have been testing with swapping the V1 and V2.

Please help me understand what you guys have implemented in the ActorProxy to identify endpoint correctly that does not work for a custom proxy.

**Comment by amanbha** [comment]
@patrikSE83  its done here   https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/5da278522d789217734797211fc614a0da723916/src/Microsoft.ServiceFabric.Actors/Client/ActorProxyFactory.cs#L204
Could you please share a simple repo. both for your actor service and client side code?

**Comment by patrikSE83** [comment]
Hello. Sorry for not replying, have been out traveling.

I found in the code that you have implemented a new class.

FabricTransportActorRemotingClientFactory that inherits from FabricTransportServiceRemotingClientFactory.

But it's still possible to only create a factory for only FabricTransportServiceRemotingClientFactory to ActorsProxy. But the communication will not work.

Haven't had time to test this myself, but I guess you should do a validation that if trying to communicate to a Actor, it must be an FabricTransportActorRemotingClientFactory and not only a FabricTransportServiceRemotingClientFactory.

And also, the behaviour of creating FabricTransportActorRemotingClientFactory  has been altered, in the FabricTransportServiceRemotingClientFactory the IServiceRemotingCallbackMessageHandler is optional, but in the FabricTransportActorRemotingClientFactory  the IServiceRemotingCallbackMessageHandler is required. - this should also be set to Optional - to mimic it's base class.

You can now close this issue.

**Comment by tanwarsatya** [comment]
@patrikSE83 is correct, the communication is failing. 

I have a method to check active actors and when by default I try to create ActorServiceProxy it's using the V1 client by default.  

Same method creates a V2 client if before creating ActorServiceProxy I create any other Actor Proxy which has V2.Client attribute specified in Interface. 

` public async Task<List<string>> GetActiveActorsIds()
        {
            ActorProxyFactory factory = new ActorProxyFactory();
            
            
            
            var fabricClient = new FabricClient(); // Re-use as much as possible

            ServicePartitionList partitionList = await fabricClient.QueryManager.GetPartitionListAsync(_uri);

            List<string> actorIds = new List<string>();

            foreach (var partition in partitionList)
            {
                var key = partition.PartitionInformation as Int64RangePartitionInformation;
                
                Microsoft.ServiceFabric.Actors.

                IActorService actorServiceProxy = ActorServiceProxy.Create(_uri, key.LowKey);

                ContinuationToken continuationToken = null;

                var cancellationTokenSource = new CancellationTokenSource();

                do
                {
                    PagedResult<ActorInformation> page = await actorServiceProxy.GetActorsAsync(continuationToken, cancellationTokenSource.Token);
                    actorIds.AddRange(page.Items.Select(x => x.ActorId.GetStringId()));

                    continuationToken = page.ContinuationToken;
                }
                while (continuationToken != null);
            }

            return actorIds;
        }
`
What should be the default behavior when we are exclusively using the V2.Client by specifying the attribute on ??

Or should we be creating a custom service to register our actors. Currently the main method for my actor service uses ActorService class to register our actors. 

` private static void Main()
        {
            try
            {

                using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("SchoolWayz-Actors-DiagnosticsPipeline"))
                 {

                    // Create default garbage collection settings for all the actor types
                    var settings = new ActorGarbageCollectionSettings(Constants.ActorIdelTimeout, Constants.ActorScanInterval);
                    
                    ActorRuntime.RegisterActorAsync<DeviceMessageQueueActor>(
                                    (context, actorType) => new ActorService(context,
                                        actorType,
                                        (s, i) => new DeviceMessageQueueActor(s, i),
                                        null,
                                        null,
                                        new ActorServiceSettings
                                        {
                                            ActorGarbageCollectionSettings = settings
                                        })).GetAwaiter().GetResult();


                    // Register SmartTrack Device Actor
                    ActorRuntime.RegisterActorAsync<SmartTrackDeviceActor>(
                    (context, actorType) => new ActorService(context,
                        actorType,
                        (s, i) => new SmartTrackDeviceActor(s, i),
                        null,
                        null,
                        new ActorServiceSettings
                        {
                            ActorGarbageCollectionSettings = settings
                        })).GetAwaiter().GetResult();


                    // Register SmartTrack Device Message Processor Actor
                    ActorRuntime.RegisterActorAsync<SmartTrackDeviceMessageProcessorActor>(
                    (context, actorType) => new ActorService(context,
                        actorType,
                        (s, i) => new SmartTrackDeviceMessageProcessorActor(s, i),
                        null,
                        null,
                        new ActorServiceSettings
                        {
                            ActorGarbageCollectionSettings = settings
                        })).GetAwaiter().GetResult();

                    Thread.Sleep(Timeout.Infinite);
                 }
          
            }
            catch (Exception e)
            {
                ActorEventSource.Current.ActorHostInitializationFailed(e);
                throw;
            }
        }`
