### ISSUE TITLE
SDK install failed: Access to the path 'ese.dll' is denied

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#549]
When installing the latest (2.8) SDK, the following error popped up in the log:

```
10/19/2017 8:42:21 AM,Info,Try deleting C:\Program Files\Microsoft Service Fabric...
10/19/2017 8:42:21 AM,Error,Exception caught. Wait for 2 seconds and retrying...
System.UnauthorizedAccessException: Access to the path 'ese.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TryCleanFolder(String path)
```

I searched for the process locking the DLL in procexp, and it was a Docker service. After stopping both Docker services on the machine, the installation completed successfully.

**Comment by taxiatms** [comment]
@aelij Thanks for reporting this.

**Comment by Pete1138** [comment]
still getting this. What was the fix?

**Comment by anantshankar17** [comment]
This hasnt been fixed yet, refer to the thread: https://github.com/Azure/service-fabric-issues/issues/1457.

**Comment by maburlik** [comment]
This is being tracked under
https://github.com/microsoft/service-fabric/issues/92
