### ISSUE TITLE
Problem detecting IService in an interface hierarchy of a StatefulService exposed over Remoting

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/service-fabric-issues#55]
Hi,
Here is an issue found in the latest Service Fabric SDK 2.2.207. Consider the following interface hierarchy (in order to lower coupling between business interface and Service Fabric interface): 

```
public interface IWebHookRepository
{
Task<WebHookStoreRegistration[]> GetAll(string user, CancellationToken ct = default(CancellationToken));
}

public interface IWebHookRepositoryService : IWebHookRepository, IService
{
}

internal sealed class WebHookRepositoryService : StatefulService, IWebHookRepositoryService
{
	[...]
}
```

While doing reflection to validate if the type is appropriate for remoting, the following error is returned:

> The service type 'WebHookRepositoryService' does not implement any service interfaces. A service interface is the one that derives from 'Microsoft.ServiceFabric.Services.Remoting.IService' type.
Parameter name: serviceType
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceTypeInformation.Get(Type serviceType)
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingExtensions.CreateServiceRemotingListener(ServiceContext serviceContext, Object serviceImplementation)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__1c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__6.MoveNext()

In order to have the interface accepted by the framework, I had to convert to something like this:

```
public interface IWebHookRepository, IService
{
Task<WebHookStoreRegistration[]> GetAll(string user, CancellationToken ct = default(CancellationToken));
}

internal sealed class WebHookRepositoryService : StatefulService, IWebHookRepository
{
	[...]
}
```

**Comment by VipulM-MSFT** [comment]
The error message we provide is not accurate. We will fix that. However the implementation above cannot be remoted. The interface IWebHookRepositoryService is deriving from an interface that is not IService. All remoted interfaces must derive from IService. This allows us to identify the interfaces that needs to be remoted. If the derived interface needs to be remoted, all of the parent interfaces needs to be as well.

If you do not want to remote IWebHookRepository, change the code in the following way OR have IWebHookRepository derive from IService.

public interface IWebHookRepository
{
Task<WebHookStoreRegistration[]> GetAll(string user, CancellationToken ct = default(CancellationToken));
}

public interface IWebHookRepositoryService : IService
{
Task<WebHookStoreRegistration[]> GetAll(string user, CancellationToken ct = default(CancellationToken));
}

internal sealed class WebHookRepositoryService : StatefulService, IWebHookRepositoryService, IWebHookRepository
{
    [...]
}

**Comment by SimonLuckenuik** [comment]
Thank you for your feedback and clarifying the current implementation.

The workaround that you suggest is not convenient from my perspective, considering that the interface would need to be duplicated and maintained twice and that coupling between the platform and the business code is still happening.

Is there any location I can submit the suggestion to support my scenario? Could be as simple as, if the service inherits from a single interface that has IService somewhere in it's hierarchy, then enable remoting.

Considering that lowering coupling between a platform and business code is standard these days, preventing from having the marker interface everywhere would make sense, I think. I would prefer having an attribute based notation on the derived StatefulService to identify which interfaces I want to be remoted rather than having to inherit from IService. Probably 99% of the time, when a StatefulService implements an interface it would be to be exposed publicly through remoting, considering that it will not be instantiated directly from code or injected through IoC.

Also, .NET Framework guidelines have specific recommendations against marker interfaces (like IService):
https://msdn.microsoft.com/en-us/library/ms229022(v=vs.110).aspx  ==> "AVOID using marker interfaces (interfaces with no members). If you need to mark a class as having a specific characteristic (marker), in general, use a custom attribute rather than an interface."

Thanks!
Simon

**Comment by VipulM-MSFT** [comment]
The remoted interfaces are a contract between client and service, they need to be carefully versioned compare to the non-remoted interfaces. We recommend that you maintain the internal and external interfaces seperately and version them separately. For example, changes in the parameter names of the remoted interface are breaking in addition to all of the breaking changes for public interfaces such as addition/removal of the methods, parameter order and count, namespace or name changes for the methods and interface.

The mechanism of marker interface vs. attribute, is kind of orthogonal; the dilemma for the platform is about making the assumptions of public vs. internal interfaces. This is especially challenging with respect to interface hierarchy as any derived interface "is" a base interface. Therefore the proxy created on the client side for the derived interface must support all of the base interfaces. If the hierarchy did contain an internal interface that was not supposed to be public, we would inadvertently remote them.

**Comment by masnider** [comment]
@SimonLuckenuik there's always our UserVoice forum for submitting new ideas or requesting features. https://feedback.azure.com/forums/293901-service-fabric

**Comment by SimonLuckenuik** [comment]
@VipulM-MSFT Thank you for the info the breaking changes for a remoted interface, I wasn't expecting parameter name to be one of those. I would also not have expected adding a method being a breaking change as well.
Just to clarify, my general goal with the code initially posted is to enable easier unit testing by preventing my custom business code to depend directly on SF base classes (and infrastructure), so my initial goal is reusing the same interface both for the StatefulService and a business oriented service where the StatefulService would act as a simple decorator to redirect calls as is to the business service. I guess I will live with the IService marker interface being inherited.

@masnider Thanks for the link!

**Comment by DenisPitcher** [comment]
@SimonLuckenuik Did you create a uservoice request for this issue?

I am also disappointed that you have to inherit directly from IService which effectively couples your code to the platform.

**Comment by masnider** [comment]
@DenisPitcher IService is only necessary if you intend to use the Service Remoting. If you're just communicating over http or something like that, then no IService interface marker is required. [This sample][1] has an example, there are many others. 

[1]: https://github.com/Azure-Samples/service-fabric-dotnet-data-aggregation/blob/master/HealthMetrics.CountyService/Service.cs

**Comment by DenisPitcher** [comment]
@masnider yes, that is understood, however if you want to use remoting then you effectively are forced to couple your business logic to the platform are you not?

**Comment by masnider** [comment]
Sure but that's a choice to use Remoting, which is part of the same platform. It's circular and doesn't have to do anything with IService, specifically. That requirement for IService comes with the choice of remoting. So don't use remoting :)

**Comment by DenisPitcher** [comment]
I can appreciate and understand that there were design constraints in the choice to require IService.  However I am rather disappointed that IService is included in the Microsoft.ServiceFabric.Services.Remoting namespace which effectively means you're coupled to the entire service fabric namespace.

It would be appreciated if these interfaces could be moved into their own nuget/reference project so as to reduce the amount of coupling.

**Comment by DenisPitcher** [comment]
I have created the following Uservoice request for moving the IService and related interfaces into their own package and namespace

https://feedback.azure.com/forums/293901-service-fabric/suggestions/17935681-move-iservice-and-related-remoting-interfaces-to-t

**Comment by badreal** [comment]
@SimonLuckenuik have you found a temporary solution for that issue ?

**Comment by baoduy** [comment]
I'm facing the similar solution if it is working fine if my interface just inherited from IService. The error is throwing if there are more than 1 interfaces on my class.
