### ISSUE TITLE
Publish from Visual Studio occassionally failing (Azure Active Directory Authentication)

### ISSUE THREAD

**Issue by berndku** [Azure/service-fabric-issues#550]
Hi,
we have several Service Fabric Cluster in Azure and have turned on Azure Active Directory Authentication. 
From time to time we cannot publish from Visual Studio 2017 anymore (Connection Parameters: ServerCertThumbprint = "XXX", AzureActiveDirectory = "true"), because authentication is failing. When this happens, we also cannot drill into the Service Fabric node in Cloud Explorer anymore. Trying to reconnect by right-clicking "Refresh" on the cluster node in Cloud Explorer, does not popup the Azure AD login, shows only an user it not authenciated error in the output.  After restarting Visual Studio, it usually works again. 

Looks like the AAD Token is not properly refreshed in the background. Please improve, because this is pretty annoying and reduces productivity. 

Many thanks
Bernd

**Comment by dbreshears** [comment]
Thanks for the feedback.   we did some work on this in the past to attempt to fix these token issues but looks like it isn't fixed.   Let me see if I can setup a repro.  I assume you are on the Latest 15.4 release of VS 2017 which would include our 1.8 tooling.

**Comment by berndku** [comment]
Was using 15.2 release. After upgrade to 15.4 the problem seems to be solved. Thanks!
