### ISSUE TITLE
Unable to get Windows Security client-to-node security to work on prem

### ISSUE THREAD

**Issue by SixFootRhino** [Azure/service-fabric-issues#551]
As per the documentation here:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-securityf

We started with this:

ClusterConfig.Windows.MultiMachine.JSON

We are trying to use machine group. We do not want to use gMSA.

Here's the modification (among other things) we tried:

`
        "security": {
            "WindowsIdentities": {
                "ClusterCredentialType": "Windows", 
                "ServerCredentialType": "Windows", 
                "WindowsIdentities": {
                    "ClientIdentities": [
                        {
                            "Identity": "ourdomain.local\\Service_Fabric_Admins", 
                            "IsAdmin": true
                        }, 
                        {
                            "Identity": "ourdomain.local\\Service_Fabric_Users", 
                            "IsAdmin": false
                        }
                    ], 
                    "ClusterIdentity": "ourdomain.local\\Service_Fabric_Machine_Group"
                }
            }
        }
`

The resulting manifest:

`
    <Section Name="Security">
      <Parameter Name="AllowDefaultClient" Value="False" />
      <Parameter Name="ClientRoleEnabled" Value="true" />
      <Parameter Name="ClusterCredentialType" Value="None" />
      <Parameter Name="DisableFirewallRuleForDomainProfile" Value="true" />
      <Parameter Name="DisableFirewallRuleForPrivateProfile" Value="true" />
      <Parameter Name="DisableFirewallRuleForPublicProfile" Value="true" />
      <Parameter Name="ServerAuthCredentialType" Value="None" />
    </Section>
`

We tried a bunch of other stuff as well. Our DevOps lead who was doing this work will update this post with additional info and participate in the dialog. At one point we were getting the missing SPN in the trace log, but that didn't fix the issue either.

As per the Community Streaming discussion earlier, we are turning on node-to-node security as well, but that shouldn't have been a problem. Setting the ClusterIdentity should do this, correct?

This is going to become a big problem in short order as we are we can't take our services to production until secured.

Thanks in advance!

**Comment by closepin** [comment]
More data in regard to this (I work with Rhino) I've been trying different permutations of the settings, the above referenced ones obviously have an issue with dual WindowsIdentity keys in the JSON. I've gotten some kind of result using:

`    
['properties']['security'] = {
        "ClusterCredentialType": "Windows",
        "ServerCredentialType": "Windows",
        "WindowsIdentities": {
            "ClusterIdentity": "our_domain.local\\SF_GDS_Nodes",
            "ClusterIdentities": [
                {
                    "Identity": "our_domain.local\\my_user",
                    "IsAdmin": True
                }
            ]
        }
    }`

Where SF_GDS_Nodes is a machine group will the nodes added.
This results in messages in resulting deployment traces stating that ClusterSPN was not supplied, so we tried adding that alongside the Server and Cluster Credential type keys as such:

`            "ClusterSpn": "our_domain.local",`

I am not clear from the documentation if this is meant to be a specific user or just the domain. When we create the cluster, we are running the process under a service user created specifically for cluster management. During our initial automation for creating clusters we found it was necessary to have a user that was an administrator across all nodes, and rather than using our own administrative accounts, we made one for this purpose.

All testing I've done with multiple permutations of the security settings has either resulted in a cluster that is completely inaccessible, with no logs. Or cluster creation reporting success, and no cluster actually created.

Also, thanks in advance, I've been banging head against this for a couple days and I am at a loss for whatever other permutations of the configurations I should be using.

**Comment by Liphi** [comment]
There's typo in ur json on ur reply. There should be only one ClusterIdentities. For the other one, u need to name it 'ClientIdentities'. For non-gmsa scenario, ClusterSpn is not needed.
After correcting the typo, if there's still problems with cluster setup, u may attach ur entire json config  file (with sensitive info removed), and I'll help take a look.
BTW, what is ur cluster code version? Suggest to use the latest version (6.0) if it's a new cluster.

**Comment by elscript** [comment]
We have almost the same issue with version 5.7.221:

**Comment by elscript** [comment]
Hmmm, now this works. Seems like if Identity is from not accessible domain from that machine cluster connection hangs on.

**Comment by closepin** [comment]
Newest attempt on code version 6.0.219.9494

``` json
{
    "apiVersion": "08-2017", 
    "clusterConfigurationVersion": "1.0.0", 
    "name": "staging_cluster", 
    "nodes": [
        {
            "IPAddress": "10.177.9.130", 
            "faultDomain": "fd:/dc1/r0", 
            "nodeName": "node_0.fqdn", 
            "nodeTypeRef": "nodeTypePrimary", 
            "upgradeDomain": "UD_000"
        }, 
        {
            "IPAddress": "10.176.90.49", 
            "faultDomain": "fd:/dc1/r1", 
            "nodeName": "node_1.fqdn", 
            "nodeTypeRef": "nodeTypePrimary", 
            "upgradeDomain": "UD_001"
        }, 
        {
            "IPAddress": "10.176.90.31", 
            "faultDomain": "fd:/dc1/r2", 
            "nodeName": "node_2.fqdn", 
            "nodeTypeRef": "nodeTypePrimary", 
            "upgradeDomain": "UD_002"
        }, 
        {
            "IPAddress": "10.176.90.5", 
            "faultDomain": "fd:/dc1/r3", 
            "nodeName": "node_3.fqdn", 
            "nodeTypeRef": "nodeType0", 
            "upgradeDomain": "UD_003"
        }, 
        {
            "IPAddress": "10.176.90.50", 
            "faultDomain": "fd:/dc1/r4", 
            "nodeName": "node_4.fqdn", 
            "nodeTypeRef": "nodeType0", 
            "upgradeDomain": "UD_004"
        }
    ], 
    "properties": {
        "addonFeatures": [
            "DnsService"
        ], 
        "diagnosticsStore": {
            "connectionstring": "\\\\machine1\\DiagnosticsStore", 
            "dataDeletionAgeInDays": "7", 
            "metadata": "Please replace the diagnostics file share with an actual file share accessible from all cluster machines. For example, \\\\machine1\\DiagnosticsStore.", 
            "storeType": "FileShare"
        }, 
        "fabricSettings": [
            {
                "name": "Setup", 
                "parameters": [
                    {
                        "name": "FabricDataRoot", 
                        "value": "C:\\ProgramData\\SF"
                    }, 
                    {
                        "name": "FabricLogRoot", 
                        "value": "C:\\ProgramData\\SF\\Log"
                    }
                ]
            }
        ], 
        "nodeTypes": [
            {
                "applicationPorts": {
                    "endPort": "20031", 
                    "startPort": "20001"
                }, 
                "clientConnectionEndpointPort": "19000", 
                "clusterConnectionEndpointPort": "19001", 
                "httpGatewayEndpointPort": "19080", 
                "isPrimary": true, 
                "leaseDriverEndpointPort": "19002", 
                "name": "nodeTypePrimary", 
                "placementProperties": {
                    "event_relay": true, 
                    "gateway": true, 
                    "lan_1g": true, 
                    "secondary_storage": true, 
                    "secure_gateway": true, 
                    "wan_1g": true
                }, 
                "reverseProxyEndpointPort": "19081", 
                "serviceConnectionEndpointPort": "19003"
            }, 
            {
                "applicationPorts": {
                    "endPort": "20031", 
                    "startPort": "20001"
                }, 
                "clientConnectionEndpointPort": "19000", 
                "clusterConnectionEndpointPort": "19001", 
                "httpGatewayEndpointPort": "19080", 
                "leaseDriverEndpointPort": "19002", 
                "name": "nodeType0", 
                "placementProperties": {
                    "event_relay": true, 
                    "gateway": true, 
                    "lan_1g": true, 
                    "secondary_storage": true, 
                    "secure_gateway": true, 
                    "wan_1g": true
                }, 
                "reverseProxyEndpointPort": "19081", 
                "serviceConnectionEndpointPort": "19003"
            }
        ], 
        "security": {
            "ServerCredentialType": "Windows", 
            "WindowsIdentities": {
                "ClientIdentities": [
                    {
                        "Identity": "our_domain\\my_user", 
                        "IsAdmin": true
                    }
                ]
            }
        }
    }
}
```
This config (with more legit data obviously) resulted in no logs in the traces folder, and no cluster running at all.

Changed the security setting above to:

``` json
    "securtity": {
        "ServerCredentialType": "Windows",
        "WindowsIdentities": {
            "ClusterIdentity": "our_domain\\machine_group_id]",
            "ClientIdentities": [
                {
                    "Identity": "our_domain\\my_user",
                    "IsAdmin": true
                }
            ]
        }
    }
```

Resulted in a cluster that won't show on the explorer; here are the traces:
[sf_logs.zip](https://github.com/Azure/service-fabric-issues/files/1408083/sf_logs.zip)


Is there any info about the machine group other than just adding the nodes to it? Wondering it there is something missing about how to set it up.

Random question, why are the ports strings instead of integers?

**Comment by Liphi** [comment]
'ClusterIdentity' needs to be a AD security group including all the nodes as its members.
Could u provide the ClusterManifest xml on any of the cluster nodes, by removing the sensitive info? The location should be %fabric data root%\node name\clustermanifest.current.xml.
The traces u provide are installer traces which unfortunately don't help here. Runtime traces is needed if trace log analysis is necessary, and to collect/ upload the logs u may contact Microsoft support.

**Comment by closepin** [comment]
Fabric data root is set to C:\ProgramData\SF - unfortunately the only things in there are the deployment traces logs that I previously attached. 

The ClusterIdentity that I am using is a machine group comprised of the machines within the cluster. I am wondering if there's any special AD permissions that would need to be added to that particular group to make it be respected by the create cluster commands, or if the presence of the groups and it's members is enough.

We install under a service user from the AD on these set to be an Administrator over these machines. He does have a <clustername>.<version>.ClusterManifest.xml in his AppData\Temp directory (attached) is this what you're looking for?
It does't look like cluster creation worked at all, and reported success anyway.

[staging_cluster.zip](https://github.com/Azure/service-fabric-issues/files/1408645/staging_cluster.zip)

**Comment by Liphi** [comment]
Have u already removed the cluster? If not, the clustermanifest.xml should be C:\ProgramData\SF\clustermanifest.xml.
As for permission, u need to check several things, like: does every node have access to the diagnostics file share, if it's configured as a shared folder instead of local folder.

**Comment by closepin** [comment]
The only thing in ProgramData\SF is the Log folder with the contents I shared previously.

```
C:\ProgramData\SF>dir /S .
 Volume in drive C has no label.
 Volume Serial Number is 08A3-1425

 Directory of C:\ProgramData\SF

10/23/2017  05:03 PM    <DIR>          .
10/23/2017  05:03 PM    <DIR>          ..
10/23/2017  05:03 PM    <DIR>          Log
               0 File(s)              0 bytes

 Directory of C:\ProgramData\SF\Log

10/23/2017  05:03 PM    <DIR>          .
10/23/2017  05:03 PM    <DIR>          ..
10/23/2017  05:03 PM    <DIR>          Traces
               0 File(s)              0 bytes

 Directory of C:\ProgramData\SF\Log\Traces

10/23/2017  05:03 PM    <DIR>          .
10/23/2017  05:03 PM    <DIR>          ..
10/23/2017  05:03 PM             3,368 fabricdeployer-636443750101451926.trace
10/23/2017  05:03 PM             7,441 fabricdeployer-636443750101581975.trace
               2 File(s)         10,809 bytes

     Total Files Listed:
               2 File(s)         10,809 bytes
               8 Dir(s)  49,789,997,056 bytes free
```

**Comment by Liphi** [comment]
So, the cluster hasn't been removed by RemoveCluster.ps1 ? If yes, have u checked all ur nodes? None of them contains clustermanifest.xml ?

**Comment by closepin** [comment]
Correct the cluster has not been removed, this is the state of the machine post cluster creation reported success - directory listing of the same directory from all machines shows no additional files. In fact, the one that we ran createcluster on only has the two previously attached, all the other machines have nothing at all.

**Comment by closepin** [comment]
I am currently removing the cluster and rebuilding it to see if another machine running cluster creation may leave us with more files.

**Comment by closepin** [comment]
This time the machine chosen for cluster creation didn't even create those trace files. Cluster creation still reported success.

**Comment by Liphi** [comment]
could u provide the powershell output of CreateCluster.ps1, by removing sensitive info?

**Comment by closepin** [comment]
Will try to get that now - we run the cluster creation through a user in our automation, so my current user isn't privileged do that action. Will report asap.

**Comment by closepin** [comment]
Interestingly our automation is not catching the errors that are coming from the cluster creation process, and the script is exiting cleanly.

> System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: IP address is not allowed for credential type 'Windows' when fabric runs as NetworkService, please use hostnames.

I assume this is what is biting us, getting this to you now while I clean up rest of the output. I'll add process to our automation to pipe this output to file so that we can actually see errors from the script as well.
If we are meant to put in hostnames for the machines, does this mean that we will no longer be able to use the private network these machines are living upon in order to facilitate communication between them without security? The private network on the cluster was made for this purpose.

**Comment by closepin** [comment]
Also interestingly, the best practices analyzer didn't catch this.

**Comment by closepin** [comment]
Changed the IPs in the cluster config to machine names (not domain qualified) and I am seeing success messages in the output. Still waiting for cluster creation to complete.

**Comment by closepin** [comment]
So now i am getting successes on cluster creation on 3 - 4 of the 5 nodes in the cluster, and the remaining nodes are throwing the following exception:

> Timed out waiting for Installer Service to complete for machine node_001. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
> Timed out waiting for Installer Service to complete for machine node_000. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
> CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine node_001. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
>    at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(List`1 machines, FabricPackageType fabricPackageType)
>    at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
> ---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine node_001. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
>    at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
> 
> ---> (Inner Exception #1) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine node_000. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
>    at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
> 
> Trace folder already exists. Traces will be written to existing trace folder: C:\prereqs\service_fabric\DeploymentTraces
> Cleaning up faulted installation.

**Comment by Liphi** [comment]
Great progress! To further diagnose, we need to further look into runtime trace logs on the machines timed out the deployment. To collect/ upload runtime trace logs, u may contact Microsoft support team. Please don't share it on this thread, which doesn't conform to compliance. Thx.

**Comment by closepin** [comment]
Is there documentation I can follow in this regard? First time doing that.

**Comment by Liphi** [comment]
Close this thread for now. Feel free if u have any further questions.
To upload logs, u may contact Microsoft support to open an case:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#report-production-issues-or-request-paid-support-for-standalone-service-fabric-clusters

**Comment by closepin** [comment]
The cluster we're attempting to do this on is not a production environment. We're going through these efforts to be ready for production.
I just removed all the code to do security set up and the cluster created successfully without issues. 
If security is the issue here, and timeouts are occurring, this implies something incorrectly set either on our AD or on the machines specifically. Finding out what that is will help a lot more than just me (at least one other person has commented saying they are seeing similar behavior as this)

During my last test, after letting the cluster machines rest for 10 minutes, I am now seeing timeouts on 4 of the 5 machines. 
Is there some global setting that may need to be enabled to allow this?

**Comment by Liphi** [comment]
Not that I'm aware of.

**Comment by closepin** [comment]
From what I am seeing in the security log from the machine that tried to create the cluster, the issue looks to be related to setting up custom firewall rules on the machine. Issue here is that our AD server administers the firewall, so any settings that SF is trying to add are going to be ignored. Looking at an unsecure cluster, these events never happen.

If we give rights to the user creating the cluster to be able to add these domain level firewall rules, could that resolve this issue? If not, can we create these rules ourselves somehow? Are the necessary ports only the ports listed in the cluster config json used during cluster creation? Or are there more that are specifically for SF that need to be enabled?

**Comment by closepin** [comment]
We have attempted the following:
Set our user to Domain Admin
Disabled the firewall

We're seeing 116 firewall rules being added in incoming and outgoing rules, I've exported those to a file for review. In addition, I got this stack trace from a fabricDeployer trace log:
```
2017/11/01-16:26:49.363,Warning,11812,FabricDeployer.FabricDeployer,Error detecting if Containers feature is present. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)
2017/11/01-16:26:49.363,Info,11812,FabricDeployer.FabricDeployer,Dism closing session...
2017/11/01-16:26:49.437,Info,11812,FabricDeployer.FabricDeployer,Dism closing session completed
2017/11/01-16:26:49.437,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down...
2017/11/01-16:26:49.469,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down completed
2017/11/01-16:26:49.472,Info,11812,FabricDeployer.FabricDeployer,Dism log file content: 	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰸ圠牡楮杮†††††††䐠卉⁍†䥄䵓倠潲楶敤⁲瑓牯㩥倠䑉㌽㐲‰䥔㵄㤸㐸䘠楡敬⁤潴䰠慯⁤桴⁥牰癯摩牥›㩃睜湩潤獷呜䵅屐㙁㕃䘹ㅃ〭㜱ⵄ㈴ㄱ䈭㙂ⴵぁぁ䔷ㅂ䅃㥃停偅潲楶敤⹲汤⹬ⴠ䌠䥄䵓牐癯摩牥瑓牯㩥䤺瑮牥慮彬敇側潲楶敤⡲牨〺㡸〰〷㜰⥥਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†䥄䵓倠捡慫敧䴠湡条牥›䥐㵄㈳〴吠䑉㠽㠹‴慆汩摥琠⁯敧⁴桴⁥灕慤整琠牨畯桧䌠卂‮‭䑃卉偍捡慫敧㨺湉整湲污佟数䙮慥畴敲栨㩲砰〸昰㠰挰ഩ㈊㄰ⴷㄱ〭‱㘱㈺㨶㤴‬牅潲⁲††††††††䥄䵓†䐠卉⁍慐正条⁥慍慮敧㩲倠䑉㌽㐲‰䥔㵄㤸㐸䘠楡敬⁤潴朠瑥琠敨甠摮牥祬湩⁧䉃⁓敆瑡牵⁥‭䑃卉偍捡慫敧㨺灏湥敆瑡牵⡥牨〺㡸〰て〸⥣਍믯㊿㄰ⴷㄱ〭‱㘱㈺㨶㤴‬牅潲⁲††††††††䥄䵓†䄠䥐›䥐㵄㐸㐸吠䑉㠽㘳‸慆汩摥琠⁯灯湥映慥畴敲䌠湯慴湩牥⁳‭䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣㨺湉整湲污硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄㌸㠶䤠瑮牥慮䕬數畣整映楡敬⁤‭䉃獡䍥浯慭摮扏敪瑣㨺硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄ㄱㄸ′䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣椠瑮牥慮⁬硥捥瑵潩⁮慦汩摥ⴠ䐠獩䝭瑥敆瑡牵䥥普䥯瑮牥慮⡬牨〺㡸〰て〸⥣਍
2017/11/01-16:26:49.472,Warning,11812,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. Treating feature as not present and continuing. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)	   at System.Fabric.FabricDeployer.DockerDnsHelper.IsContainersFeaturePresent()
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Containers feature not present. Not continuing further
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Successfully completed DockerDnsHelper.CleanupAsync
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Completed DockerDnsHelper.CleanupAsync
2017/11/01-16:26:49.485,Info,11812,FabricDeployer.FabricDeployer,Dism initializing...
2017/11/01-16:26:49.487,Info,11812,FabricDeployer.FabricDeployer,Dism initializing completed, opening online session...
2017/11/01-16:26:50.046,Info,11812,FabricDeployer.FabricDeployer,Dism opening online session completed, getting feature info...
2017/11/01-16:26:50.374,Warning,11812,FabricDeployer.FabricDeployer,Error detecting if Containers feature is present. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)
2017/11/01-16:26:50.374,Info,11812,FabricDeployer.FabricDeployer,Dism closing session...
2017/11/01-16:26:50.438,Info,11812,FabricDeployer.FabricDeployer,Dism closing session completed
2017/11/01-16:26:50.438,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down...
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down completed
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Dism log file content: 	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ圠牡楮杮†††††††䐠卉⁍†䥄䵓倠潲楶敤⁲瑓牯㩥倠䑉㐽㔵′䥔㵄㜹㐶䘠楡敬⁤潴䰠慯⁤桴⁥牰癯摩牥›㩃睜湩潤獷呜䵅屐㈱㘷䄷㈵䄭䕃ⴹ䐴〴䈭㤷ⴹ䄶㘳䄲㑅䘱㥅停偅潲楶敤⹲汤⹬ⴠ䌠䥄䵓牐癯摩牥瑓牯㩥䤺瑮牥慮彬敇側潲楶敤⡲牨〺㡸〰〷㜰⥥਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†䥄䵓倠捡慫敧䴠湡条牥›䥐㵄㔴㈵吠䑉㤽㘷‴慆汩摥琠⁯敧⁴桴⁥灕慤整琠牨畯桧䌠卂‮‭䑃卉偍捡慫敧㨺湉整湲污佟数䙮慥畴敲栨㩲砰〸昰㠰挰ഩ㈊㄰ⴷㄱ〭‱㘱㈺㨶〵‬牅潲⁲††††††††䥄䵓†䐠卉⁍慐正条⁥慍慮敧㩲倠䑉㐽㔵′䥔㵄㜹㐶䘠楡敬⁤潴朠瑥琠敨甠摮牥祬湩⁧䉃⁓敆瑡牵⁥‭䑃卉偍捡慫敧㨺灏湥敆瑡牵⡥牨〺㡸〰て〸⥣਍믯㊿㄰ⴷㄱ〭‱㘱㈺㨶〵‬牅潲⁲††††††††䥄䵓†䄠䥐›䥐㵄㐸㐸吠䑉㔽㜶‶慆汩摥琠⁯灯湥映慥畴敲䌠湯慴湩牥⁳‭䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣㨺湉整湲污硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄㘵㘷䤠瑮牥慮䕬數畣整映楡敬⁤‭䉃獡䍥浯慭摮扏敪瑣㨺硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄ㄱㄸ′䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣椠瑮牥慮⁬硥捥瑵潩⁮慦汩摥ⴠ䐠獩䝭瑥敆瑡牵䥥普䥯瑮牥慮⡬牨〺㡸〰て〸⥣਍
2017/11/01-16:26:50.470,Warning,11812,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. Treating feature as not present and continuing. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)	   at System.Fabric.FabricDeployer.Utility.IsContainersFeaturePresent()
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Skipping container network clean up since containers feature has been disabled.
2017/11/01-16:26:50.472,Info,11812,ImageStoreClient.ManagedFileLock,Released writer lock on C:\ProgramData\SF\lock_Remove
```
Any information would be greatly appreciated.
