### ISSUE TITLE
Add docker image store as default service in service fabric

### ISSUE THREAD

**Issue by AceHack** [Azure/service-fabric-issues#553]
Please add a built in private docker image store in service fabric.

**Comment by mani-ramaswamy** [comment]
Service Fabric is a microservices and container orchestration platform.  We recommend using the private Azure Container registry for storing docker images (which we integrate with) - we don't have any plans to build our own container registry.

**Comment by AceHack** [comment]
This does not work on prem so offers an incomplete solution for on prem.  Please reconsider.

**Comment by mani-ramaswamy** [comment]
You can build your own on-premise private container registry. It doesn't have be ACR.
