### ISSUE TITLE
Too many secondary replicas after failed upgrade?

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#555]
I have a service which has:
Target Replica Set Size | 3
Min Replica Set Size | 2

I have upgraded this service (same version, different application parameters).
This upgrade has failed due to health issues. (This is correct, I made a mistake in config).
Upgrade has completed in 3 UDs and failed in 4th. However it was rolled back.
Now after rollback I have:
Primary, ActiveSecondary, ActiveSecondary, IdleSecondary

Is this something expected?

**Comment by navyahmed** [comment]
it is expected.
IdleSecondary does not count towards Target but if an ActiveSecondary goes down then system can promote Idle to Active to reach Target

**Comment by navyahmed** [comment]
for more details see https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-replica-lifecycle

**Comment by mkosieradzki** [comment]
@navyahmed Thanks for your explanation and links, however I think how replica lifecycle works. And I understand a good reason during upgrade to create additional replica. What I don't understand why after failed upgrade (rollback) such a replica is not "garbage collected" for couple of days (!). It got recycled when I upgraded my cluster today to 6.0.219.

It suggests that there might be a minor bug causing this scenario.

**Comment by Mansoor-Mohsin** [comment]
How long a stand by replica is kept is controlled by _StandByReplicaKeepDuration_: https://docs.microsoft.com/en-us/dotnet/api/system.fabric.description.statefulservicedescription.standbyreplicakeepduration?view=azure-dotnet

You can set the desired value for your service.

**Comment by mkosieradzki** [comment]
@Mansoor-Mohsin thanks, that very helpful.
