### ISSUE TITLE
Microsoft.VisualStudio.Azure.Fabric.Vsix.Alpha not work

### ISSUE THREAD

**Issue by hanxinimm** [Azure/service-fabric-issues#557]
![image](https://user-images.githubusercontent.com/13499426/31848678-f44bafac-b669-11e7-8e51-84d682dafd1f.png)

select the .net core template

![image](https://user-images.githubusercontent.com/13499426/31848687-20a334d0-b66a-11e7-8b44-328be393ccc8.png)

next 

![image](https://user-images.githubusercontent.com/13499426/31848689-2bad80ba-b66a-11e7-8f3e-6a7ffcaed83c.png)

**Comment by MikkelHegn** [comment]
@dbreshears Please check if the .net core 2.0 SDK is installed: https://www.microsoft.com/net/download/core

**Comment by hanxinimm** [comment]
![image](https://user-images.githubusercontent.com/13499426/31887371-aa305bbc-b82a-11e7-98d7-eb5209c8f9d9.png)
![image](https://user-images.githubusercontent.com/13499426/31887509-37452c3a-b82b-11e7-92a3-909f57a414bd.png)

**Comment by dbreshears** [comment]
@hanxinimm,    The Alpha Pack is currently ENU only and we haven't tested on non-ENU VS/OS.   We will address this in the next release.

**Comment by hanxinimm** [comment]
thanks,Do you have plans to unveil a new version within a month.

**Comment by dbreshears** [comment]
@hanxinimm ,   unsure at the moment when the next update will be of the Preview tooling, if we update it would likely be prior to or around 12/1

**Comment by dbreshears** [comment]
Going to close this for now since ENU is only supported option for the Preview
