### ISSUE TITLE
Question: Multiple services with same endpoint

### ISSUE THREAD

**Issue by AsValeO** [Azure/service-fabric-issues#559]
Is there a way to make multiple different SF services in same cluster listen to the same endpoint http 80? Services have their WebAPIs with different routes.

`<Endpoint Protocol="http" Name="ServiceEndpoint" Type="Input" Port="80" />`
I'm getting an error:

> Failed to bind to address http://[::]:80: address already in use.

Is there a way to avoid this?

**Comment by xunlu** [comment]
If two services are running on the same machine, then you will get port conflict from OS, unless you are using something that allows port sharing (e.g. http.sys).  Service Fabric itself does not affect how your listening port is created.
If you don't want two services using the same port to run on the same node, you can use placement constraint to make sure that they are not placed together.

**Comment by raunakpandya** [comment]
Closing this issue assuming the above reply addresses your question,
