### ISSUE TITLE
New Actor project gets created in My Documents/Visual Studio 2015/Projects

### ISSUE THREAD

**Issue by dotdestroyer** [Azure/service-fabric-issues#56]
Given you are creating a brand new Service Fabric Solution ( after you have specified your solution name ) you then prompted to add a SF template, choosing 'Actor Service' creates this My Documents/Visual Studio 2015/Projects.

It should create the actor service under your solution directory, NOT in My Documents/...

Btw If you choose to create a Stateless Web Api (instead of actor service) it gets placed in the solution directory correctly.

**Comment by MikkelHegn** [comment]
Hi dotdestroyer,

This is a know issue that will be fixed in the next release. This should only happen if you uncheck "Create directory for solution", when creating the Service Fabric Application project.

/mikkel

**Comment by VipulM-MSFT** [comment]
This has been fixed since 1.5 tools release or Service Fabric 2.5 SDK release.
