### ISSUE TITLE
Specifying Service Fabric DNS as parameter

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#561]
How can I specify different ServiceDnsName per environment (dev, testing, production, ect)? I'm trying something like this

```
<Service Name="ApiGateway" ServiceDnsName="[ApiGateway_DnsName]">
  <StatelessService ServiceTypeName="ApiGatewayType" InstanceCount="[ApiGateway_InstanceCount]">
    <SingletonPartition />
  </StatelessService>
</Service>
```
Where `ApiGateway_DnsName` is one of parameters in ApplicationManifest.xml

`<Parameter Name="ApiGateway_DnsName" DefaultValue="api.dev" />`

But I got when start debug

> Register-ServiceFabricApplicationType : The ServiceDnsName for DefaultService 'ApiGateway' is invalid. FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\PlatformType\ApplicationManifest.xml

Other people have the same problem. See comments here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-dnsservice

Trying to find help on stackoverflow https://stackoverflow.com/questions/46857890/specifying-service-fabric-dns-as-parameter but no answers. So, please help :(

**Comment by EvilAvenger** [comment]
I can see the same error as described.
However I decided to change URLs of my application's services depending on ENV variables dev/staging/prod while DNS name stays always the same for all configurations.

**Comment by vturecek** [comment]
This is one of the limitations with "Default services" which is a kind of shorthand for the way services are normally created in Service Fabric using the "create" command:

    sfctl service create --app-id MyApp --name fabric:/MyApp/ApiGateway --service-type ApiGatewayType --stateless --singleton-scheme --instance-count 1 --dns-name my.dns.name 

or 

    New-ServiceFabricService -Stateless -ApplicationName fabric:/MyApp -ServiceName fabric:/MyApp/ApiGateway -PartitionSchemeSingleton -ServiceTypeName ApiGatewayType  -InstanceCount -1 -ServiceDnsName my.dns.name

In full context, your deployment process would pass deployment-specific variables to the application and service create commands. When you deploy through Visual Studio, the parameter XML files do exactly that.

**Comment by Marusyk** [comment]
Thanks. Could you please suggest how it can be done?

**Comment by Marusyk** [comment]
Also I cannot create a new instance of applicaion because DNS conflict

**Comment by masnider** [comment]
@Marusyk dns names are scoped to the cluster, so you can't have multiple services with the same dns name. You'd have to change those names as well.

**Comment by EvilAvenger** [comment]
@Marusyk The only option I can imagine is to have 2 applications that are hosted in one cluster, each of which references to the same set of  services/projects.

Each application should have different set of env variables in config which allows you to change URLs of those services.

**Comment by Marusyk** [comment]
@masnider 

> dns names are scoped to the cluster, so you can't have multiple services with the same dns name.

of couse I know, so I asked how to configure that name. See question

> How can I specify different ServiceDnsName per environment

**Comment by masnider** [comment]
@VipulM-MSFT @milvuko - is DNS name paramaterizable and available in Default Services?

@Marusyk if it isn't, then you'd have to create the services imperatively (Via C# or Rest) at which point you could set the DNS name to whatever you wanted.

**Comment by Marusyk** [comment]
Thank you all.
