### ISSUE TITLE
Unable to load System.Private.Xml.resources.dll

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#563]
When trying to run my app compiled using 3.0.219-preview SDK as netcoreapp2.0 I can observe following exceptions.
```
FileNotFoundException: Could not load file or assembly 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS\System.Private.Xml.resources.dll'. The system cannot find the file specified.
```
```
FileNotFoundException: Could not load file or assembly 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS\System.Private.CoreLib.resources.dll'. The system cannot find the file specified.
```

I have no idea why it tries to search for .NET Core 2.0 assemblies (and satellite assemblies) in `C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS\`

**Comment by raunakpandya** [comment]
This could be some issue in the Assembly resolver. We will take a look but as a workaround do you have these assemblies in you code package folder?

Thanks,
Raunak Pandya
________________________________

**Comment by mkosieradzki** [comment]
Nope. Because application is deployed as FDD (framework-dependent deployment as described here: https://docs.microsoft.com/en-us/dotnet/core/deploying/). And those are framework assemblies. 

Any tips how to force Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.2 (I am using 1.6.2 due to #531 ) to build app as SCD (Self-contained deployment)? Or maybe there is some option in csproj to create SCD?

**Comment by Eneuman** [comment]
Here is the exception received,
![exception](https://user-images.githubusercontent.com/12099277/31907186-5cbaa24e-b833-11e7-9432-a6db6c7abdbc.png)

This happens only for statfull services not stateless.

**Comment by mkosieradzki** [comment]
Any news on this one? This is a blocker for any work on .NET Core and in consequence SF for Linux adoption.

**Comment by onovotny** [comment]
Getting an assembly resolver done for .NET Core is complicated. @bradwilson got it working for xunit here (and related classes): https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Utility/NetCoreAssemblyDependencyResolver.cs

I think Brad was working on a blog post explaining this?

**Comment by bradwilson** [comment]
The assembly resolver required for xUnit.net came about because we do things a little unusually: we want to be able to load an assembly dynamically (the unit test assembly) and support all of its dependencies from the NuGet cache, so that users are not required to use `dotnet publish` before running the tests.

**Comment by mkosieradzki** [comment]
@raunakpandya My observation is that you have switched to the SCD ;). Am I right? Is this final fix?

**Comment by raunakpandya** [comment]
@mkosieradzki  The issue of unable to load System.Private.Xml.resources.dll should be resolved with the latest SDK. However we are looking at the issue you have reported recently.

**Comment by mkosieradzki** [comment]
@raunakpandya yup, I see that you have changed the deployment model to the SCD instead of using custom assembly loader (all the required files are copied to the package folder).

Thanks for solving this issue. I will try to run other services from my projects to see if the issue is really fixed and close this issue.
