### ISSUE TITLE
Service Fabric ephemeralPorts and different subnets

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#564]
Hi,

we have a service fabric cluster on premise that is deployed on 4 different subnets (each nodeType on different subnet). 
It follows a similar network configuration as the one described here: 
https://brentdacodemonkey.wordpress.com/2016/08/01/network-isolationsecurity-with-azure-service-fabric/

Between all subnets there is a network firewall.

Do we have to open the ephemeral ports range between subnets? 
Are there any default Service Fabric services that use/listen to ephemeral ports during installation or runtime?
Our applications listen on applicationPorts and these are open on the network firewall.

kind regards
Yannis

**Comment by ChackDan** [comment]
We have an NSG sample template in the azure template gallery that lists the rules that you can apply.
https://github.com/ChackDan/azure-quickstart-templates/tree/master/service-fabric-secure-nsg-cluster-65-node-3-nodetype 

Specifically in this file, look for the security rules under the resource type - "Microsoft.Network/networkSecurityGroups"
 https://github.com/ChackDan/azure-quickstart-templates/blob/master/service-fabric-secure-nsg-cluster-65-node-3-nodetype/azuredeploy.json 

At a high level - 
**In bound - allow the following** 
ClientConnectionEndpoint (TCP) – 19000
HttpGatewayEndpoint (HTTP/TCP) – 19080
SMB support for Image Store – 445, 134
ClusterConnectionEndpointPort (TCP) – 1025
LeaseDriverEndpointPort (TCP) – 1026
Ephemeral Port range – as needed, min 256 ports
Application ports – as needed
**Out bound** – donot block.

you need to allow the first five inbound rules between subnets.

**Comment by dealboy** [comment]
thanks for the reply and the samples provided.

Double checking them I can see that "Microsoft.Network/networkSecurityGroups" in  
https://github.com/ChackDan/azure-quickstart-templates/blob/master/service-fabric-secure-nsg-cluster-65-node-3-nodetype/azuredeploy.json

does not open only the first five ports, but has also a security rule to "allowSvcFabEphemeral".

this issue is submitted because running these scenarios with only the first five inbound rules allowed between the subsets, leads to an on prem cluster that is has several SF services in error mode (for example they cannot access/create required secondary partitions).

I would prefer not to limit or define Ephemeral Port range (especially because we have guest executables that are socket hungry).

From your azuredeploy.json example, looks that it cannot be done otherwise, can you please confirm?

kind regards
Yannis

**Comment by ChackDan** [comment]
Defining the Ephemeral Port range (as needed, min 256 ports) is a must. you can define as many port as you need to that @Liphi  to confirm/correct me.

**Comment by dealboy** [comment]
what we want to avoid is opening the network firewall between subnets for all ephemeral ports. 
Our internal apps do not need these ports to be opened across firewall, only on local firewall level, but the  SF core services looks-like they do.

If you have any info if SF uses things like MS-RPC, maybe we could configure our firewall accordingly (and not open the full ephemeral port range between subnets)

**Comment by maburlik** [comment]
SF system services rely on the ephemeral port range to communicate. One way you might be able to work around opening subnet-to-subnet ephemeral ranges is to configure only one of the NodeTypes as primary such that system services run in this node type. Then you only need to open the intra-subnet firewall so these primary node type nodes can talk to one another in this range.

**Comment by dealboy** [comment]
@maburlik : that is exactly what we tried to do, and ensured that all VMs of primary nodetype are the same subnet. 
Then we saw that during installation of the SF cluster some system services were trying to deploy/access other nodetypes on other subnets (more precisely trying to deploy secondary replicas there, for example the Repair Service), and failed because of network firewall blocks. The whole installation was incomplete (giving pending update nodes when doing Get-ServiceFabricClusterUpgrade ) 

Do the system services use RPCs? do you have a uuid for them? this could easily unblock us and the firewall

**Comment by maburlik** [comment]
Adding Bharat and Ray to answer whether system services use RPCs.

**Comment by maburlik** [comment]
Is it an option to hide the 4 subnets behind a larger subnet, and maintain the firewall at the upper level?

**Comment by maburlik** [comment]
Bharat has relayed that System services use direct TCP socket communication, so you will need to unblock the firewall for the ephemeral range.

**Comment by dealboy** [comment]
that is clear, 
thanks all of you guys for the answers!
