### ISSUE TITLE
Cannot start FabricHostSvc

### ISSUE THREAD

**Issue by brutaldev** [Azure/service-fabric-issues#566]
Using SDK 2.8.219.

FabricHostSvc simply will not start, it remains in a "Starting" state forever and overnight consumed all my hard disk space in trace logs.

The only information in the Event Logs is: `The Service Fabric Host Service service terminated unexpectedly.  It has done this 1492 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.`

I've tried the solution here to re-install the C++ runtime which made no difference: https://social.msdn.microsoft.com/Forums/azure/en-US/a74bf0f7-3106-4b48-b48f-4ea250a24964/cluster-setup-errors-connectservicefabriccluster-a-communication-error-caused-the-operation-to?forum=AzureServiceFabric

I've tried unregistering counters but it does not find any: https://stackoverflow.com/a/36415584/564726
`Unregister-ScheduledTask : No MSFT_ScheduledTask objects found with property 'TaskName' equal to 'FabricCounters'.`

The Windows Defender Firewall service is running so that does not seem to be the problem.

The cluster manager tray application just hangs when you select any options and then becomes completely disabled. I've re-installed the runtime and SDK twice, exactly the same results.

I cleared the logs and tried to start the service and attached the trace logs after 5 minutes when it fails.
https://brutaldev.com/download/SfDevCluster-Log.zip

```
PS C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup> .\DevClusterSetup.ps1

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

The generated json path is C:\Users\werne\AppData\Local\Temp\tmp737B.tmp.json
Processing and validating cluster config.
Create node configuration succeeded
Starting service FabricHostSvc. This may take a few minutes...
Start-Service : Failed to start service 'Service Fabric Host Service (FabricHostSvc)'.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:532 char:5
+     Start-Service FabricHostSvc -WarningAction SilentlyContinue
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

StartLocalCluster : Could not start FabricHostSvc
At C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1:75 char:1
+ StartLocalCluster
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,StartLocalCluster

ScriptHalted
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:536 char:9
+         throw
+         ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by Mardoxx** [comment]
Have you tried uninstalling any old SF SDK versions, then reinstalling the new one from WPI?

**Comment by brutaldev** [comment]
Yes. I uninstalled both the runtime and SDK from _Apps and Features_ as well as removing Service Fabric tools from the _Visual Studio Installer_

I had previously installed the latest version using Web PI, I'm going to restart the PC, install the tools from Visual Studio Installer, then the SDK from Web PI, and see if everything starts after that.

Is there anything else I should get rid of before starting to install all over again?

**Comment by maburlik** [comment]
Had you run a cluster reset at any point? The errors I'm seeing in your logs indicate that the node is not configured.

@taxiatms Please look at the cluster configuration workflow for SDK to see if you can determine how the machine got into this state.

**Comment by taxiatms** [comment]
@brutaldev When you uninstall service fabric runtime and SDK, make sure "C:\Program Files\Microsoft SDK\Service Fabric" and "C:\Program Files\Microsoft Service Fabric" are deleted. Then try to install latest SDK from WebPI

**Comment by brutaldev** [comment]
From the cluster manager it just hangs indefinitely, using `CleanCluster.ps1` just completes instantly with no console output.

Managed to get it to work though after uninstalling everything and starting from scratch (including removing any remnants of Service Fabric directories and registry entries just to be sure).

1. Install Service Fabric tools using the Visual Studio Installer.
2. Install Service Fabric SDK using WebPI.
3. Run `DevClusterSetup.ps1 -PathToClusterDataRoot X:\SfDevCluster\Data -PathToClusterLogRoot X:\SfDevCluster\Log` to create the cluster and specify new log and data locations.
4. Edit `ClusterManifestTemplate.json` files to reduce data and log sizes and retention.
5. Start the system tray cluster manager and select appropriate cluster mode.
6. Test it out with a quick new project in Visual Studio.

I believe there was a version conflict somewhere, after a full re-install of all the tools things looked different, the registry settings for data and log locations were being ignored and the registry settings looked different as well. Things installed to different paths among other things so I think there were multiple versions conflicting.

Still no closer to figuring out why the service never started up causing most of these problems. I have no idea what version I had before I upgraded to the latest :(

**Comment by SergeyBoiko** [comment]
Hi, thanks @brutaldev for detailed description in your last comment, it helped me. Just want to add a short comment how I fixed it. No sure what went wrong, but I had an error: **Cannot find any service with service name 'FabricHostSvc'.** and it looks like removing Service Fabric staff from registry is the key point before re-installing everything.

My machine is Windows 10 Pro 64-bit and here is what helped me:

1. Uninstall Microsoft Service Fabric SDK by using "Your Uninstaller" (selected "Super Mode for proper register clearing).
2. Uninstall Service Fabric tools using the Visual Studio Installer.
3. Delete folder: C:\Program Files\Microsoft Service Fabric
4. Delete folder from registry: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric
5. Reboot PC
6. Download Microsoft Web PI from [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started#sdk-installation-only) and install the Microsoft Azure Service Fabric SDK. Btw. after I've deleted registry entries of SF I've noticed that Web PI has finally installed three needed components (not only Azure Service Fabric SDK as it was for previous re-installations):

- Microsoft Visual C++ 2012 SP1 Redistributable Paskage (x64)
- Microsoft Azure Service Fabric Runtime - 6.3.162
- Microsoft Azure Service Fabric SDK - 3.2.162

7. Install Service Fabric tools using the Visual Studio Installer.
8. Create test project in Visual Studio 2017 and run it. Visual Studio created cluster automatically and finally I got my solution running :)

Thanks.
