### ISSUE TITLE
How to minimize deployment time for non-production deployments

### ISSUE THREAD

**Issue by rodolfograve** [Azure/service-fabric-issues#567]
Hi.

We continuously deploy our services to an integration environment on every build and would like to minimize the time that deployment takes. Since Service Fabric is designed for resiliency, could you please suggest what settings would make the deployment faster, even if we lose some resiliency?

Cheers

**Comment by Eneuman** [comment]
Have a look at my findings in #573 
Maby you got the same problem as I do?

**Comment by rodolfograve** [comment]
Thanks @Eneuman We'll take a look.

I'd also like to get a response from the team about to minimize the delays intentionally built into ServiceFabric.

**Comment by masnider** [comment]
@rodolfograve What delays are you looking at? And when you say deployment are you talking about the creation of an entirely new app and service or an upgrade?

**Comment by alexwun** [comment]
Are you deploying to an Azure cluster?

[This article](https://docs.microsoft.com/azure/service-fabric/service-fabric-application-upgrade) describes the upgrade workflow and various delays that exist.

If applicable, start by reducing HealthCheckWaitDurationSec and HealthCheckStableDurationSec as described [here](https://docs.microsoft.com/azure/service-fabric/service-fabric-application-upgrade-parameters).

Also try reducing UpgradeStatusPollInterval as described [here](https://docs.microsoft.com/azure/service-fabric/service-fabric-cluster-fabric-settings).

**Comment by rodolfograve** [comment]
Thanks @alexwun 
Yes, we are deploying to an Azure cluster as part of our continuous delivery process. We'll take a look at those documents.

**Comment by masnider** [comment]
@rodolfograve - Hi there. We haven't heard back from you in a while, so for now we'll presume the docs helped :) If you have other questions or want to provide mode information, then feel free to reopen the issue or leave some more comments. Thanks!
