### ISSUE TITLE
SF does not dectypt CertificateRef password 

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#568]
If IsPasswordEncrypted is set to true, sf should decrypt the password before string it into the password file.

**Comment by masnider** [comment]
Hi @Abdruggi - I'm not sure what you mean by "into the password file". Also which password are you speaking about here? Is this for container images or something else?

**Comment by Abdruggi** [comment]
According to the documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-securing-containers) it is possible to reference a certificate in a data package and provide the password as encrypted string (IsPasswordEncrypted). In my understanding, sf should decrypt the password before writing it into the password file (Certificate_ServicePackageName_CodePackageName_CertName_Password). Am I wrong? Otherwise the IsPasswordEncrypted Attribute would not make any sense.

**Comment by Abdruggi** [comment]
@masnider - Any news about the issue? It's prevents us from going live with our applications.

**Comment by masnider** [comment]
@Abdruggi AFAIK we don't auto-decrypt the values, you'd need to do that within the container itself. Adding some experts to help out and hopefully get you a clear answer.

**Comment by rakshitatandon** [comment]
@Abdruggi Thanks for reporting. This looks like a bug in SF. It will be fixed in subsequent releases.

**Comment by Abdruggi** [comment]
Thx for the status update

**Comment by Abdruggi** [comment]
@rakshitatandon Could you share a time frame for the fix?

**Comment by rakshitatandon** [comment]
@Abdruggi This bug was fixed in 6.1.456.9494

**Comment by Abdruggi** [comment]
@rakshitatandon Thx. I'll give it a try tomorrow.
