### ISSUE TITLE
SF - Reverse Proxy - Discovering service via Reverse proxy service - FABRIC_E_ENDPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#569]
Hello Team,

when i try to hit service via ipaddress:port of node, its able to return response but when i try to hit it through proxy service like below
**Name of Service** - fabric:/risxfacsV3/claim
--- http://localhost:19081/risxfacsV3/claim/swagger/docs/v1 - Inside Node
i get 404 FABRIC_E_ENDPOINT_NOT_FOUND as status code and response is black.
 
i tried to play around and see if reverse proxy is able to find service by changing from Claim to ClaimV1
http://localhost:19081/risxfacsV3/claimV1/swagger/docs/v1.
i got error Service Not Found. that is true becuause claimV1 doesnt exist in cluster.

Above service is listining on port 55903. so i am able to get to swagger without any issue but with service fabric proxy its returning FABRIC_E_ENDPOINT_NOT_FOUND.
http://xx.xxx.xxx.xx:55903/swagger/docs/v1 - This renders fine.

Thanks,
Naresh khatri

**Comment by Mardoxx** [comment]
Reverse proxy URLs are case sensitive. I would check this.

You may be running in to this https://github.com/Azure/service-fabric-issues/issues/458#issuecomment-330697306 whereby the protocol isn't being set as http so [something] goes wrong.

BTW, in case you didn't know... if you actually want to send 404 to the client you need to add `X-ServiceFabric` header with `ResourceNotFound` otherwise it keeps retrying nodes until it times out after so many seconds 😄  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services

**Comment by nareshkhatri81** [comment]
I am using docker compose for deployment. So i am not using mainfest files.
Reverse proxy is able to locate service but not resource. Thats very strage.

**Comment by kavyako** [comment]
There is a known issue accessing swagger behind the reverse proxy, it was a limitation of the swagger middleware. 
https://github.com/Azure/service-fabric-issues/issues/327

Are you able to access other other paths exposed by the service?

**Comment by nareshkhatri81** [comment]
I tried with hello world that also didnt render with reverse proxy.
http://localhost:19081/risxfacsV2/risxfacs.webapi.claim/api/HelloWorld -Status Code:404 FABRIC_E_ENDPOINT_NOT_FOUND
http://xx.xxx.xxx.xx:55903/api/HelloWorld - Works fine.

we are also not using swashbuckle middleware that has issue mentioned in post. we are using nswag for swagger file generation.

i also dont see URISchema as mentioned above by Mardoxx in service mainfest file.

As we are using docker compose and mainfest files are automatically generated by service fabric behind the scene. how can i those settings in docker compose file ?

sfctl compose create --application-id fabric:/ClaimV5 --compose-file D:\ProjectsV1\sf-docker-compose.yml

<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="Compose_risxfacsV3" ApplicationTypeVersion="131533180973232115" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="claimPkg" ServiceManifestVersion="636444269000223958" />
    <Policies>
      <ContainerHostPolicies CodePackageRef="claim.Code">
        <PortBinding ContainerPort="84" EndpointRef="claimEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="clientPkg" ServiceManifestVersion="636444269000223958" />
    <Policies>
      <ContainerHostPolicies CodePackageRef="client.Code">
        <PortBinding ContainerPort="84" EndpointRef="clientEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="inboxPkg" ServiceManifestVersion="636444269000113945" />
    <Policies>
      <ContainerHostPolicies CodePackageRef="inbox.Code">
        <PortBinding ContainerPort="84" EndpointRef="inboxEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="lossPkg" ServiceManifestVersion="636444269000223958" />
    <Policies>
      <ContainerHostPolicies CodePackageRef="loss.Code">
        <PortBinding ContainerPort="84" EndpointRef="lossEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    <Service Name="claim" ServiceDnsName="" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="claimType">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="client" ServiceDnsName="" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="clientType">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="inbox" ServiceDnsName="" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="inboxType">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="loss" ServiceDnsName="" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="lossType">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>


<ServiceManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="claimPkg" Version="636444269000223958" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="claimType" UseImplicitHost="true" />
  </ServiceTypes>
  <CodePackage Name="claim.Code" Version="latest">
    <EntryPoint>
      <ContainerHost>
        <ImageName>risxfacs.webapi.claim</ImageName>
      </ContainerHost>
    </EntryPoint>
    <EnvironmentVariables />
  </CodePackage>
  <Resources>
    <Endpoints>
      <Endpoint Name="claimEndpoint" Port="55907" />
    </Endpoints>
  </Resources>
</ServiceManifest>

**Comment by nareshkhatri81** [comment]
[mainfest.txt](https://github.com/Azure/service-fabric-issues/files/1414382/mainfest.txt)

**Comment by kavyako** [comment]
For compose deployment you need to specify the http scheme in the port key: 
e.g:
```
version: '3'
services:
  web:
    image:
     "microsoft/iis:latest"
    ports:
     - "80:80/http"
```
What does Service Fabric Explorer show for the Endpoint Address? Does it have http/https prefix?

**Comment by nareshkhatri81** [comment]
After adding http in docker compose file. i can see response to services via api gateway.
i guess by default it should have be http handle by SF. if that parameter is not available then default to http.
