### ISSUE TITLE
Cannot create new Service Fabric Cluster from Azure Portal

### ISSUE THREAD

**Issue by profnimrod** [Azure/service-fabric-issues#57]
I can't create a new Service Fabric Cluster from Azure Portal.  I get the following errors in my browser (Firefox, but have tried on IE/Edge and Chrome) console:

[Microsoft_Azure_ServiceFabric]  16:58:37 MsPortalFx/ViewModels/ViewModels.Part ViewModels.Part: Part's onInputsSet promise failed.
Error: _errorData: {"readyState":4,"responseText":"","status":404,"statusText":"Not Found"}

baseTypes: ["MsPortalFx.Errors.NotFoundDataError","MsPortalFx.Errors.DataError","MsPortalFx.Errors.Error"]

code: undefined

data: undefined

dataSetName: DataCache:5:1

errorLevel: 2

extension: Microsoft_Azure_ServiceFabric

handled: true

innerErrors: []

message: 

name: Error

source: DataCache:5:1

stack: t@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:34:809
t@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:35:152
t@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:35:566
et</t.prototype._getErrorDataForFailedRequest@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:391:525
et</t.prototype._fetchData/<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:391:254
.Deferred/r.then/</</<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:870
i.Callbacks/c@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:52:554
i.Callbacks/s.fireWith@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:317
.Deferred/r.then/</</<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:983
i.Callbacks/c@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:52:554
i.Callbacks/s.fireWith@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:317
.Deferred/</t[i[0]]@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:54:278
n/this.reject@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:204:181
b</n.prototype._worker/</<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFx_250169D92F12C2DE00E7026B6D959FDDB6C43BB7.js:203:634
.Deferred/r.then/</</<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:870
i.Callbacks/c@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:52:554
i.Callbacks/s.fireWith@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:53:317
b@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:88:25
.send/i/<@https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/MsPortalFxStable_8022EED1C8753C0C5674A83408EF9CD5C6B73BC4.js:93:824

timestamp: 50894.185

type: MsPortalFx.Errors.NotFoundDataError

![capture](https://cloud.githubusercontent.com/assets/3297421/18819252/cb015c16-8341-11e6-8f23-2ecbb8d1b606.PNG)

**Comment by profnimrod** [comment]
As a workaround, I execute the folllowing command in PowerShell after switching to the correct subscription:

`Register-AzureRmResourceProvider -ProviderNamespace Microsoft.ServiceFabric`

**Comment by mani-ramaswamy** [comment]
Thanks for reporting this issue. We have fixed this issue - please let us know if you're still running into problems creating a cluster.
