### ISSUE TITLE
V2 and V1 listeners consumed in same service

### ISSUE THREAD

**Issue by Mardoxx** [Azure/service-fabric-issues#570]
Is it possible to consume both V2 (only, i.e. not compat listener) and V1 listener services in the same service?

I have three services, two of which are using V2 only and one which is still using V1, that are being consumed by some orchestration service.. When my code comes to sending a request off to my V1 service, I'm met with `FabricInvalidAddressException: NamedEndpoint 'V2Listener' not found in the address xxxxxxx`, which of course, it shouldn't have.

If it is meant to be possible I can try and put together a simple repro.

**Comment by BharatNarasimman** [comment]
Your orchestration service should be able to talk to v2 listener and v1 listener services. Can you plz share your repro?

**Comment by Mardoxx** [comment]
Sure, will get to it asap

**Comment by Mardoxx** [comment]
[SFIssue570.zip](https://github.com/Azure/service-fabric-issues/files/1417989/SFIssue570.zip)

Deploy project, go to `http://localhost:9026/api/message/test`.

```
Entrypoint Web1, using 6.0.219 and 2.8.219 libraries, Kestrel listener
Web1 calls OrchSvc, using 6.0.219 and 2.8.219 libraries, V2 listener
OrchSvc calls Svc1, using 5.7.221 and 2.7.221 libraries. V1 listener
        calls Svc2, using 6.0.219 and 2.8.219 libraries, V2 listener
```

`Svc1` uses old package versions effectively simulating my env above. Only difference is that `IService` interfaces are in separate projects in my env. The same issue still appears though.

Updating the libraries in `Svc1` does not remedy this issue.

**Comment by Mardoxx** [comment]
Forcing the proxy listener name to "", i.e. `ISvc1 svc1 = ServiceProxy.Create<ISvc1>(new Uri("fabric:/SFIssue570/Svc1"), listenerName: "");` doesn't help either.

**Comment by Mardoxx** [comment]
Seems that `ServiceProxy.Create` does not infer service type (either at all, or incorrectly) from the service interface.

Workaround is this:

```csharp
// ...
using V1FabricTransportClient = Microsoft.ServiceFabric.Services.Remoting.V1.FabricTransport.Client;
using V2FabricTransportClient = Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client;
// ...

namespace ORchSvc
{
// ...
        public async Task<List<string>> SendMessagesAsync(string message)
        {
            List<string> messages = new List<string>();

            var v1ProxyFactory = new ServiceProxyFactory(c => new V1FabricTransportClient.FabricTransportServiceRemotingClientFactory());

            ISvc1 svc1 = v1ProxyFactory.CreateServiceProxy<ISvc1>(new Uri("fabric:/SFIssue570/Svc1"));
            messages.Add(await svc1.SendMessageAsync(message));

            var v2ProxyFactory = new ServiceProxyFactory(c => new V2FabricTransportClient.FabricTransportServiceRemotingClientFactory());

            ISvc2 svc2 = v2ProxyFactory.CreateServiceProxy<ISvc2>(new Uri("fabric:/SFIssue570/Svc2"));
            messages.Add(await svc2.SendMessageAsync(message));

            return messages;
        }
}

**Comment by VipulM-MSFT** [comment]
Thank you for posting the solution. The stack for v1 and v2 is separate so even if we created a façade at the top it would have been more confusing when things did not work as expected and hence we decided to keep them separate. I will be closing this issue. Thank you again for the question and solution!

**Comment by Mardoxx** [comment]
If the two stacks are completely incompatible I think it should be in the docs somewhere. I'm not the only one who has thought they are somewhat backwards compatible! I would not have expected the above solution to fail!

Also having a quick look at the ServiceProxyFactory code it does look like it trys to infer the stack from the assembly attribute on the interface. However I think it defaults to V2 if no attribute is present (which is good).

**Comment by Mardoxx** [comment]
Are you sure this is correct behaviour? Basically this means you can't consume V1 and V2 services using `ServiceProxy.Create<IService>()` without my workaround. Which is rather unintuitive!

Seems like a bug to me.. Also depends on what order you resolve the Service Proxies -- strange indeed as the class should be stateless?!


```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using Svc1;
using Svc2;
using System;
using System.Threading.Tasks;

namespace Web1.Controllers
{
    [Route("api/[controller]")]
    public class MessageController : Controller
    {
        private readonly ISvc1 svc1;
        private readonly ISvc2 svc2;

        public MessageController()
        {
            this.svc1 = ServiceProxy.Create<ISvc1>(new Uri("fabric:/SFIssue570/Svc1"));
            this.svc2 = ServiceProxy.Create<ISvc2>(new Uri("fabric:/SFIssue570/Svc2"));
        }

        [HttpGet("{message}")]
        public async Task<IActionResult> Get([FromRoute( Name = "message")] string message)
        {
            var res1 = await svc1.SendMessageAsync(message); // works
            var res2 = await svc2.SendMessageAsync(message); // exception

            return Ok();
        }
    }
}
```

vs

```csharp
        public MessageController()
        {
            this.svc2 = ServiceProxy.Create<ISvc2>(new Uri("fabric:/SFIssue570/Svc2"));
            this.svc1 = ServiceProxy.Create<ISvc1>(new Uri("fabric:/SFIssue570/Svc1"));
        }

        [HttpGet("{message}")]
        public async Task<IActionResult> Get([FromRoute( Name = "message")] string message)
        {
            var res1 = await svc1.SendMessageAsync(message); // exception
            var res2 = await svc2.SendMessageAsync(message); // works (check by wrapping above in try catch)

            return Ok();
        }
    }
}
```

**Comment by Mardoxx** [comment]
Ok so poking around.... `DefaultProxyProvider` is a singleton... and the way the proxy factories are initialised depend on the first `IService`'s attributes.

**Comment by Mardoxx** [comment]
I need more information... like why is it initialised the way it is...

Will create a PR and someone can pass comment there...

**Comment by Mardoxx** [comment]
@VipulM-MSFT "The stack for v1 and v2 is separate so even if we created a façade at the top it would have been more confusing when things did not work as expected and hence we decided to keep them separate."

I have some confusion as to what use the `ServiceProxy`  class with singleton `ServiceProxyFactory` is?
Internal `DefaultProxyProvider` is intialised (through magic of assembly attribute properties) as either a V1 or a V2 listener.. meaning you can't talk to v1 and v2 services using ServiceProxy class. Either one type, or the other. Seems inherently broken, no?

It doesn't too much matter to me, because I'm the only developer at the moment doing R&D, but others may likely have issue.

**Comment by suchiagicha** [comment]
@Mardoxx 
V1 stack is not support for .Net core services.

**Comment by ManojRanga** [comment]
@suchiagicha  does this mean I need to upgrade the service which is using v1 listener to support v2??
