### ISSUE TITLE
Windows Defender and Service Fabric on Azure VM does not work well together

### ISSUE THREAD

**Issue by Eneuman** [Azure/service-fabric-issues#573]
I noticed that when setting up a Service Fabric cluster on Azure, no exclusions are added to Windows Defender settings. Accordning to https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation there are alot of exclusions that should be added.

Since no exclusions are added, Windows Defender starts to scan everything when doing a deploy.
For a D2_v2 VM the scanning process takes around 2 minutes per application (2-3 services) to complete during witch the CPU is around 80%. We currently have 7 servers and 11 applications.
This meens that when we do a full deploy **we are waiting for Windows Defender (and spending 80% CPU) for 154 minutes in total**, just for the Anti Virus Scan.

The problem escalates when creating .Net Core 2.0 SF services.
A SF service created in .Net 4.6.1 was around 250 files (most .dlls) but in .Net Core it up to 600 files.

In my calculations, our deploy would be around 80% faster if it wasn't for Windows Defender.

I would like to find a way to turn off scanning of anything that Service Fabric deploys to the server.
(We are using CI so noone can deoply anything from there local machines, it is all handled by VSTS)

**Comment by toddabel** [comment]
Is there a workaround for Azure that someone has found? It seems that Defender can be configured using RM, but not sure how that applies for Service Fabric based VMSS. Does anyone have a sample of how to do this?

**Comment by slicc** [comment]
Any update on this? This is also a problem for me, I created a cluster in the last few weeks and Windows Defender is still killing deployments. On a single node test cluster in Azure, deployments time out (after approx. 30 minutes), if I disable Windows Defender Real Time Protection on the VM, it takes about 3 minutes. Obviously disabling the protection is not a viable solution, especially in a SF cluster, so we really need a more permanent solution here.

**Comment by masnider** [comment]
We had this question over on [StackOverflow](https://stackoverflow.com/questions/49495766/configure-windows-defender-for-vms-in-scaleset) a while ago and there's been multiple pieces of docs and guidance posted since then. 

https://blogs.msdn.microsoft.com/azuresecurity/2016/10/07/add-microsoft-antimalware-to-azure-service-fabric-clusters/

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#environment-setup

**Comment by slicc** [comment]
Thanks masnider, I guess step 17 on the second link is what I need to do, but I can't see any details on how to do this in a service fabric cluster. I could remote on to each machine in the cluster, but this isn't going to apply the changes if I scale the vm scaleset up and down.

**Comment by rfcdejong** [comment]
I used DSC to add the rules and called it from my ARM deployment template, works fine.

```
configuration ServiceFabricAntivirusExclusions
{
    Import-DscResource -ModuleName WindowsDefender

    [string[]]$exclusionPath = "C:\Program Files\Microsoft Service Fabric\","D:\SvcFab\";
    [string[]]$exlusionProcess = "Fabric.exe","FabricHost.exe","FabricInstallerService.exe","FabricSetup.exe","FabricDeployer.exe","ImageBuilder.exe","FabricGateway.exe","FabricDCA.exe","FabricFAS.exe","FabricUOS.exe","FabricRM.exe","FileStoreService.exe";

    WindowsDefender x
    { 
        IsSingleInstance = 'Yes';
        ExclusionPath = $exclusionPath;
        ExclusionProcess = $exlusionProcess;
    }
}
```

**Comment by Eneuman** [comment]
@rfcdejong Thank you for your suggestions. I tried to configure my ARM template with DSC but I couldn't get it to work so in the end I created i powershell script that I manually ran on my VMs.

The script looks like this for anyone that needs it. (It needs to be run with elevated priv.)
```
#Run as elevated

#Antivirus Excluded directories

Add-MpPreference -ExclusionPath "C:\Program Files\Microsoft Service Fabric"
Add-MpPreference -ExclusionPath "D:\SvcFab"
Add-MpPreference -ExclusionPath "D:\SvcFab\Log"

#Antivirus Excluded processes

Add-MpPreference -ExclusionProcess "Fabric.exe"
Add-MpPreference -ExclusionProcess "FabricHost.exe"
Add-MpPreference -ExclusionProcess "FabricInstallerService.exe"
Add-MpPreference -ExclusionProcess "FabricSetup.exe"
Add-MpPreference -ExclusionProcess "FabricDeployer.exe"
Add-MpPreference -ExclusionProcess "ImageBuilder.exe"
Add-MpPreference -ExclusionProcess "FabricGateway.exe"
Add-MpPreference -ExclusionProcess "FabricDCA.exe"
Add-MpPreference -ExclusionProcess "FabricFAS.exe"
Add-MpPreference -ExclusionProcess "FabricUOS.exe"
Add-MpPreference -ExclusionProcess "FabricRM.exe"
Add-MpPreference -ExclusionProcess "FileStoreService.exe"

```

I would be great if someone from the SF team could write a blog post about the different options

**Comment by ChackDan** [comment]
Alex  - let us create a doc tracking defect for this and get this done

**Comment by Eneuman** [comment]
Is there any reason for not adding the exclusions to Windows Defender?
If not, maby this should be default when creating a new cluster?

**Comment by aljo-microsoft** [comment]
```powershell
If (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))
{
  New-WinEvent -ProviderName "Microsoft-Windows-PowerShell" -Id 45090 -Payload @("Script needs to RunAs Adminstrator")
}
# https://docs.microsoft.com/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#environment-setup
Install-WindowsFeature -Name Windows-Defender

$servicefabric_exe = "Fabric.exe","FabricHost.exe","FabricInstallerService.exe","FabricSetup.exe","FabricDeployer.exe","ImageBuilder.exe","FabricGateway.exe","FabricDCA.exe","FabricFAS.exe","FabricUOS.exe","FabricRM.exe","FileStoreService.exe"
# $_.ProcessName +.exe
for ($i = 0; $i -lt $servicefabric_exe.Length; $i++)
{
  Add-MpPreference -ExclusionProcess $servicefabric_exe[$i]
}

$servicefabric_storage = "C:\Program Files\Microsoft Service Fabric","D:\SvcFab","D:\SvcFab\Log"
# Storage Path
for ($i = 0; $i -lt $servicefabric_storage.Length; $i++)
{
  Add-MpPreference -ExclusionPath $servicefabric_storage[$i]
}
```
