### ISSUE TITLE
Certificates uploaded with ServiceFabricRPHelpers not in proper format

### ISSUE THREAD

**Issue by mikanyg** [Azure/service-fabric-issues#577]
I was following this [guide](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-arm#add-certificates-to-your-key-vault) to setup a new Azure Service Fabric Cluster with cluster certificates and application certifices. A guide I previous have used with success several times. But ran into issues around uploading certs to Azure KeyVault with the `ServiceFabricRPHelpers ` cmdlet

Added the following comment to the docs

> I have previous used the ServiceFabricRPHelpers to upload cluster and application certifactes to Azure KeyVault with success, but today I could not get it to work.
> 
> Using the guide to upload the certs works as expected, but when deploying the Service Fabric cluster, the deployment fails stating that the cert data was in improper format.
> 
> The only way I could get the certs uploaded was to use the Azure KeyVault UI in the portal for uploading certificate as a secret. I suspect that Azure KeyVault might have some changes in the json schema that is not reflected in the ServiceFabricRPHelpers.
> 
> So for anyone having trouble with certs, just use the Azure KeyVault UI to upload them.

I suggest you update the docs or fix the `ServiceFabricRPHelpers` cmdlet

**Comment by mikanyg** [comment]
I can confirm that using `ServiceFabricRPHelpers` cmdlet to create and upload self-signed cert has the same behaviour. The cert is uploaded but not in a valid format.

**Comment by mikanyg** [comment]
@ChackDan Can you confirm this?

**Comment by ChackDan** [comment]
Thankyou for reporting this.. Let me see if I have the same issues. I have added it to my backlog.

In the meanwhile I suggest using command lets we shipped to help with this at  [service fabric arm module](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/?view=azurermps-4.4.1 )

The module ships in the azure PS. All you do is install it and

**Comment by masnider** [comment]
These were scripts put together by Chacko that have been superseded by real functionality in sfctl/Azure-Az family of command line tools. Please use those instead.
