### ISSUE TITLE
The api IStatefulServiceReplica.ChangeRole(S) on node X is stuck

### ISSUE THREAD

**Issue by karunasagark** [Azure/service-fabric-issues#579]
One of the service of a given stateful type is facing this issue, other services of the same type are running fine.

The service has a unhealthy evaluation - 
Unhealthy event: SourceId='System.FM', Property='State', HealthState='Warning', ConsiderWarningAsError=false. Partition reconfiguration is taking longer than expected.

And the primary replica has status=ready, but has warning - 
Unhealthy event: SourceId='System.RAP', Property='IStatefulServiceReplica.ChangeRole(S)Duration', HealthState='Warning', ConsiderWarningAsError=false.
The api IStatefulServiceReplica.ChangeRole(S) on node X is stuck

The 2 active secondaries have status=inbuild, and health=ok.

Why is this happening?

**Comment by karunasagark** [comment]
The code does handle cancellation token passed into runasync. Can you suggest how do I identify the process to take a dump to identify the issue? There are multiple processes for this service type.

**Comment by masnider** [comment]
As a part of the error message you should have the necessary information to run Get-ServiceFabricDeployedReplica. The output of this contains the **HostProcessID**

```
PS C:\Users\masnider> Get-ServiceFabricDeployedReplica -NodeName _Node_4 -ApplicationName "Fabric:/GettingStartedApplica
tionType" -ServiceManifestName "StatefulBackendServicePkg" -PartitionId "8f97c174-93e1-41c0-8757-c6b109dee346"


ServiceName                : fabric:/GettingStartedApplicationType/StatefulBackendService
Partitionid                : 8f97c174-93e1-41c0-8757-c6b109dee346
ReplicaId                  : 131538557433100834
ReplicaRole                : Primary
ReplicaStatus              : Ready
ServiceTypeName            : StatefulBackendServiceType
ServiceManifestName        : StatefulBackendServicePkg
ServicePackageActivationId :
CodePackageName            : Code
Address                    : {"Endpoints":{"":"http:\/\/localhost:57259\/8f97c174-93e1-41c0-8757-c6b109dee346\/13153855
                             7433100834\/eff8d05a-0d90-4cf8-9c0b-50c017a14c15"}}
HostProcessId              : 15648
ReconfigurationInformation : {
                             PreviousConfigurationRole            : None
                             ReconfigurationPhase                 : None
                             ReconfigurationType                  : None
                             }
```

**Comment by francescocristallo** [comment]
I have the same problem on a very simple Asp.net core 2.0 Stateful service on /Net Standard and Fabric version 6.0.219.9494 with high throughput (1Million+ calls per hour).
Any guideline on how to debug/detect the problem?

**Comment by raunakpandya** [comment]
Are you facing this issue in .NET Core App?

**Comment by eisber** [comment]
We see the same messages on SF 6.0.211.9494

**Comment by vturecek** [comment]
@karunasagark What version of the Service Fabric NuGet packages are you using?

**Comment by eisber** [comment]
6.0.211

**Comment by raunakpandya** [comment]
Can you share you application logs when it gets stuck?

Thanks,
Raunak Pandya
________________________________

**Comment by masnider** [comment]
Hi @eisber, were you eventually able to figure this out? We haven't heard back from you in a while, so we'll close out this issue. If you have more questions or want to post back what eventually worked, just comment or reopen the issue. Thanks!

**Comment by abatishchev** [comment]
Getting the same error often without any additional info or clue why is is happening and what this means.

**Comment by abatishchev** [comment]
For me I'm getting is error when an application is stuck on deleting (forever) until I need restart the code package on given node, then deleting completes almost immediately.

**Comment by abatishchev** [comment]
Actually getting this error also during upgrade what after timeout causes rollback and deployment failure.

**Comment by shacal** [comment]
Hosted services seems bump this issue thru the roof 💃

**Comment by patdaman** [comment]
Ours also.  This is started with a hanging deployment from Azure DevOps.

Oddly it only started when we switched the SSL settings in the Application Gateway to TLS 1.2.  If we delete the app, switch back to TLS 1.1, then deployment and application work just fine once again.

I cannot find any documentation other than this that addresses this situation at all, although using an Application Gateway is supposed to remedy any need to follow this:
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Security/TLS%20Configuration.md

Anyone seen this before?
