### ISSUE TITLE
Application project (sfproj) sometimes ignores NuGet.config

### ISSUE THREAD

**Issue by aelij** [Azure/service-fabric-issues#58]
I've seen this happen mostly when upgrading to a newer SDK version (happened both in 2.1 and 2.2). The project upgrades but the reference to the `Microsoft.VisualStudio.Azure.Fabric.MSBuild` package is created in a `packages` folder under the solution's directory instead of the the one indicated by the `NuGet.config` file.

We have to manually fix the `sfproj` imports and remove the added packages folder.

SF packages in other (`csproj`) projects are unaffected.

**Comment by MikkelHegn** [comment]
Thanks for reporting this Eli. We'll look in to the upgrade logic in this matter.

**Comment by ravipal** [comment]
Eli, I tried it by upgrading a project from 2.1 to 2.2 and it honors the Nuget.config. I had a Nuget.config under a folder where all the projects are located (example:- C:\Users\ravipal\Documents\Visual Studio 2015\Projects).

Please provide more information on where is the location of Nuget.config? Also what do you mean by sometimes it ignores? Does that mean, it works in other scenarios?

**Comment by aelij** [comment]
@ravipal I have upgraded 4 solutions (with 4 SF app projects) that have a NuGet.config in a shared root. 3 out of 4 exhibited the problem. I really have no idea what made that one that did upgrade successfully different.

This is the directory structure:
```
Root
|-- NuGet.Config
+-- src
|   +-- Server
|   |   |-- Server.sln
|   |   +-- Services
|   |   |   |-- Services.sfproj
|   +-- Web
|   |   |-- Web.sln
|   |   |-- Website1
|   |   |   |-- Website1.sfproj
|   |   |-- Website2
|   |   |   |-- Website2.sfproj
```

**Comment by aelij** [comment]
Also, not sure if this makes any difference, but these projects were created during the private preview of the SDK, and have been upgraded continuously ever since.

**Comment by ravipal** [comment]
Is the project that upgraded successfully also created during private preview? Would be great if you could share both successful and unsuccessful project file before the upgrade. The before upgrade project will be backed up under backup folder.

**Comment by aelij** [comment]
I can email you the projects if you send me your address.

**Comment by ravipal** [comment]
please send it to ravipal@microsoft.com

**Comment by aelij** [comment]
I copied the projects to a different folder to send a repro to you, and then I noticed that they converted properly. I then renamed the original folder and it worked as well. Seems like there's some sort of cache that caused the problem.

I'm closing the issue. If you'd still like me to send you the project files let me know.

**Comment by doberman-ch** [comment]
@ravipal I also had the similar issue with sfproj when nuget.config is available. In my case it is always reproducing when the repositoryPath settings points to the different drive in nuget.config
`<add key="repositoryPath" value="D:\NuGetPackages" />`
e.g. if my source code on the drive C:\ but this variable point to the D:\, sfproj cannot restore packages, if I specify C:\ everything is working

Steps in my case:
1. add nuget.config with repositoryPath settings that point to the different drive
2. create Service Fabric project

In the result VS will show two dialogs, 
- one is error dialog is shown (Object reference not set...)
- nuget restore dialog is shown where only No button is working. 
- Also the Service project is not created
- in the sfproj are missed several lines
```
<Import Project="D:\NuGetPackages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('D:\NuGetPackages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
<Import Project="D:\NuGetPackages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('D:\NuGetPackages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />
```

NOTE: it is valid for 2.4.164 Service Fabric SDK
