### ISSUE TITLE
Service Fabric SDK 2.8.219 / Service Fabric Runtime 6.0 Installation fails

### ISSUE THREAD

**Issue by konkked** [Azure/service-fabric-issues#580]
Trying to install Service Fabric SDK 2.8.219, fails with 
"This product requires Service Fabric Runtime to be installed"

At first already had a runtime installed, so checked the logs says the runtime needs to be 6, which I don't have, try uninstalling my current SDK and runtime and still getting the same error. 

Now I am basically stuck and unable to even develop on my other projects.

Been looking online for a link to download the 6.0 runtime for an hour and have not been able to find it.

Not really sure what to do at this point.

**Comment by MedAnd** [comment]
Hi @konkked, I got a very similar error and the fix was: https://github.com/Azure/service-fabric-issues/issues/560

**Comment by konkked** [comment]
@MedAnd does not seem like the same issue, my installation completely fails, from the log, just a note, when looking at what individually is going to be installed in Web Platform Installer does not show the runtime, was trying to follow the steps from #556 where @taxiatms seems to be helping see below:

![image](https://user-images.githubusercontent.com/4019164/32105817-c68e8dc2-baf7-11e7-9911-a5fef593726e.png)

**Comment by MedAnd** [comment]
@konkked so a little more detail... 

- I uninstalled the previous version of the SF runtime and sdk... then removed the SF Tools from VS 2017 as per #560 ... 
- Manually downloaded the latest sdk and runtime (using platform installer also failed for me)
- Rebooted
- Manually installed (via powershell session but cmd should also work) new sdk and runtime with /AcceptEULA
- Rebooted

**Comment by konkked** [comment]
After downloading Service Fabric Runtime via link provided by @taxiatms in one of his comments in #556 was able to run installer fine. 

Not sure why these links are easily available for download.

Closing issue.
