### ISSUE TITLE
Linked files are not copying to data directory for debug session

### ISSUE THREAD

**Issue by lAnubisl** [Azure/service-fabric-issues#582]
Steps to reproduce:

1. Create Data folder
2. In Visual Studio add existing file "as link" to data folder.
3. Run project in Debug.

**Result:** Linked file **is not** in the data folder of running service fabric app.
**Expected result**:  Linked file **is** in the data folder of running service fabric app.

**Comment by Mardoxx** [comment]
Do you not need to set it as copy to output directory = always as well?

**Comment by masnider** [comment]
@Mardoxx @lAnubisl Yes - that's usually the answer. Can you try that and let us know?

**Comment by lAnubisl** [comment]
@masnider It is not working. But I found work around using pre-build script + copy

**Comment by dbreshears** [comment]
@lAnubisl,    is the Data folder and linked file in the packaged output?   I tried a simple test to create a new Stateless service,  created a Data folder and linked an existing .docx file into Stateless1\Data folder via VS, made sure to set Copy to Output Directory = Copy Always.    The file ended up in packaged output as well as in the local cluster at C:\SfDevCluster\Data\_App\_Node_2\Application50Type_App5\Stateless1Pkg.Code.1.0.0\Data on F5.    Is there something I am missing in what you are attempting to do?

**Comment by lAnubisl** [comment]
@dbreshears 
Imagine you have your service in **c:\Dev\MyService**
When you add a reference file in data directory and set "Copy to Output Directory" = "Copy always" then after build you will see your file in c:\Dev\MyService\bin\debug\PackageRoot\Data\

When you press F5 the debugger session is started and SF will create
**C:\SfDevCluster\Data\_App\_Node_0\MyService\** with links to Data, Config, Code directories. These links are pointing to **c:\Dev\MyService\PackageRoot** but not to **c:\Dev\MyService\bin\debug\PackageRoot\** so you will not see your files copied to output directory.

**Comment by bartbovendeerdt** [comment]
This is only the case when the `Application Debug Mode` is set to `Refresh Application`. It does work when using `Remove Application`. It would be great if it also worked with Refresh so there is no difference in what is deployed.

**Comment by ravipal** [comment]
#823
