### ISSUE TITLE
Very slow initial ActorProxy.Create

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-issues#583]
I've got a very slow creation of an ActorProxy the first time it is created.  

I'm currently testing on my development machine (Surface Pro 4, i7, 16gb ram - so a reasonable spec). One of my actor interfaces takes 7 seconds, a simpler one takes 1 second.

Here's the actor interface.
```
    public interface ISessionActor : IActor
    {
        Task<SessionInformation> GetSessionInformation();
        Task<BatchResponse> Batch(ServerInformation server, string remoteIpAddress, IList<BatchEvent> events);
        Task StartSession(ServerInformation server, string remoteIpAddress, SessionStart details);
        Task StopSession(ServerInformation server, string remoteIpAddress, SessionStop details);
        Task HandleContentReference(ServerInformation server, string remoteIpAddress, ContentReference details);
        Task HandleMediaReference(ServerInformation server, string remoteIpAddress, MediaReference details);
        Task HandleResponse(ServerInformation server, string remoteIpAddress, Response details);
        Task HandlePhysicalLocation(ServerInformation server, string remoteIpAddress, PhysicalLocation details);
        Task HandleHeartbeat(ServerInformation server, string remoteIpAddress, Heartbeat details);
        Task HandleIdle(ServerInformation server, string remoteIpAddress, IdleEvent details);
        Task ClearAllActive(ServerInformation server, string remoteIpAddress, ClearEvent details);
        Task<CommandResponse> HandleCommand(ServerInformation server, string remoteIpAddress, CommandEvent details);
    }
```

The data structures are complex(ish). 

To be honest, I would be happy if the first call took 1 second, but 7 seconds seems a bit high. I know if happens in production as well, but haven't instrumented it, because my first call to the actor via a web api always takes a long time and I've never been able to work out why until now.

Here's how I warm it up and time it
```
            var sw = Stopwatch.StartNew();
            ActorProxy.Create<ISessionActor>(new ActorId(Guid.Empty));
            RawLog.Information("Created actor proxy in {Elapsed}", sw.Elapsed);
```
The resulted in the following log entry: `Created actor proxy in 00:00:07.3088321 `

This appears to be similar in both V1 and V2 remoting.

Is this something expected? 

I've switched the first proxy creation to my web api startup, so the first call to the actor now happens much quicker!

**Comment by VipulM-MSFT** [comment]
The first time you use the actor proxy for a particular interface, the runtime dynamically generates the proxy including the data types needed to serialize and de-serialization the method arguments and return values. This cost dominates the first call cost. There is additional cost of resolving and establishing the connection when you make the actual request but that happens on every failover as well.

**Comment by nrandell** [comment]
Thanks for the quick response. However I know the first time is slow, as explained below. But 7 seconds is probably close to 700,000 million instructions on my PC. What's happening in that time? Mining bitcoins?

Seriously, I know subsequent operations are quick, but this initial delay just seems to be over the top!

Also - why close the issue so quickly without allowing me, and possibly others to respond and comment on it? Are you targeted on closed issues per week?

**Comment by nrandell** [comment]
Any feedback on my comment? I would rather not raise another issue, but I believe performance is something that should be considered.
