### ISSUE TITLE
Info - Updating Reverse Proxy Port

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#584]
Hi Team,
i found there is settings in  "reverseProxyEndpointPort": "19081" in Clusterconfig for each node.
I would like to change that to other port so on each node its listen on same port.
i change those settings. which command should i run for changes to take places in cluster.

one more issue i am seeing with localhost inside node, i am able to resolve to endpoints via proxy services like this http://localhost:19081/app/service/swagger/docs/v1
but outside with ip address of node. i am getting

This site can’t be reached

xx.xxx.xxx.xx refused to connect.
ERR_CONNECTION_REFUSED

**Comment by nareshkhatri81** [comment]
HTTP ERROR 504 is coming when trying to access outside node.

**Comment by masnider** [comment]
@nareshkhatri81 I don't know if the setting is upgradable since it isn't listed [here][1]. But that said - the port should be the same for all nodes of a given node type at least. Are you seeing something else?

For your second problem, is this an azure cluster? You may need to punch a hole in the Azure Network Load Balancer to allow connections into the cluster based on the dns name or public ip address. If the ip address you're trying is not routable from outside the cluster (ex: 10.*.*.*) then that is part of the problem. Or - what is the IP address you're trying to use?

[1]: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings

**Comment by nareshkhatri81** [comment]
when we configured cluster, it seems we use default config file which came with installer. In that it seems port is different for each node in cluster. is there any way to update that port and run the some command ?

Other issue above Gateway timeout 504 - we are running cluster in onpremise. 
SF Explorer which runs on in cluster is accessible outside via IP Address in our network.
Similar way i can access service via http://ipaddress:port combination but we need to access service via proxy service something like http://ipaddress:19081/risxfacsV4/client/swagger/docs/v1 but this gives gateway timeout.

is there way to investigate if request has reached to service proxy service ? and its calling containers ? does reverse proxy logs all information of request received etc ?

**Comment by nareshkhatri81** [comment]
i tried to use below command but got exception to update port of reverse proxy.

PS C:\SF\Microsoft.Azure.ServiceFabric.WindowsServer.5.7.198.9494> Start-ServiceFabricClusterConfigurationUpgrade

cmdlet Start-ServiceFabricClusterConfigurationUpgrade at command pipeline position 1
Supply values for the following parameters:
ClusterConfigPath: C:\SF\Microsoft.Azure.ServiceFabric.WindowsServer.5.7.198.9494\ClusterConfig.Unsecure.MultiMachine.json
Start-ServiceFabricClusterConfigurationUpgrade : Cluster connection instance is null
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Start-ServiceFa...gurationUpgrade], NullReferenceException
    + FullyQualifiedErrorId : GetClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade

**Comment by nareshkhatri81** [comment]
After connecting to cluster. i am not sure if this command can be used to update port of reverse proxy.

PS C:\SF\Microsoft.Azure.ServiceFabric.WindowsServer.5.7.198.9494> Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath "C:\SF\Microsoft.Azure.ServiceFabric.WindowsServer
.5.7.198.9494\ClusterConfig.Unsecure.MultiMachine.json"
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: A configuration upgrade with identical configuration version is not allowed.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath "C: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade

**Comment by nareshkhatri81** [comment]
Any update on how can i update port of reverse proxy in one of node ?

**Comment by vturecek** [comment]
The port is set per node type. Every node that belongs to a node type will use the same port. Example config:

    "nodeTypes": [
      {
        "name": "NodeType0",
        "clientConnectionEndpointPort": "19000",
        "clusterConnectionEndpointPort": "19002",
        "leaseDriverEndpointPort": "19001",
        "serviceConnectionEndpointPort": "19006",
        "httpGatewayEndpointPort": "19080",
        "reverseProxyEndpointPort": "19081",
        "applicationPorts": {
          "startPort": "30001",
          "endPort": "31000"
        },
        "isPrimary": true
      },

**Comment by nareshkhatri81** [comment]
Yes. We already have cluster running. We want to update reverse proxy port to common across all nodes.

**Comment by nareshkhatri81** [comment]
Recreated cluster.
