### ISSUE TITLE
Please allow using ServerCommonName for Server Authentication in SF VSTS tasks

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#586]
SF VSTS Tasks always use Thumbrint for Server Authentication. If you rollover cluster certificate on regular basis it is quite annoying to update this thumbprint every time. 

ServerCommonName as an alternative to ServerThumbprint would be very useful.

**Comment by masnider** [comment]
I feel like this should be possible, but I don't see a good way to do it. @dbreshears to comment

**Comment by dbreshears** [comment]
Yes, certainly doable,   we would need to update our task and connection endpoint to take a ServerCommonName.    We can look into doing this at some point, perhaps when we update to take an array of thumbprints as well.

**Comment by MikkelHegn** [comment]
Closing issue here and referring to the VSTS repo for this enhancement.
