### ISSUE TITLE
Unable to disable DNS Service on a ServiceFabric "onebox" (developer workstation) cluster

### ISSUE THREAD

**Issue by jtermine** [Azure/service-fabric-issues#588]
Our developer workstations use a custom DNS server that runs on their workstations and developers use "onebox" SF clusters to test services.  Certain individuals have attempted to disable the Service Fabric DNS service (fabric:/System/DnsService) so it does not interfere with this custom DNS server.  When I change the DnsService section in the C:\SfDevCluster\Data\FabricHostSettings.xml file to 

```
  <Section Name="DnsService">
    <Parameter Name="InstanceCount" Value="0" />
    <Parameter Name="IsEnabled" Value="False" />
  </Section>
```

And restart the cluster, the DNS Service does not appear to be disabled.  Is there an alternate way to do this?

**Comment by vturecek** [comment]
You're looking in the wrong place. C:\SfDevCluster are the "in-use" files of a running cluster. You need to restart the cluster with different settings.

First select **Remove local cluster** from the little SF tray icon.

Then go to C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\NonSecure\OneNode (or FiveNode for a local 5 node cluster) and update ClusterManifestTemplate.json.

Look for:
    
    "addOnFeatures": [
      "DnsService"
    ]

And just remove DnsService from that list.

Then start up the cluster again.

**Comment by jtermine** [comment]
Thank you. That is exactly what I needed to know.
