### ISSUE TITLE
Reverse Proxy Cipher Suites - Question

### ISSUE THREAD

**Issue by AndrewJWaite** [Azure/service-fabric-issues#589]
A recent security review indicated the following:

**Title**
The remote service accepted encrypted connections using weak cipher suites (key shorter than 128 bits)

**Action**
Disable support for cipher suites using keys shorter than 128 bits

**Description**
>The system completed the handshake using a weak SSL cipher suite with the key shorter than 128 bits, as follows: 
        TLS_RSA_WITH_*3DES*_EDE_CBC_SHA                     -              *112 bits*
The 3DES cipher (identified as containing 3DES or CBC3 in the cipher name), although nominally using a 168 bit key, effectively uses only 112 bits due to the implementation. 
Block ciphers such as DES and 3DES are additionally affected by the Sweet32 plain-text recovery attack. 
> 

**Question**
My understanding is the Reverse proxy terminates the SSL connection. So, is the Reverse Proxy supporting weak cipher suites and if so what are the options?

**Comment by AndrewJWaite** [comment]
Hi @kavyako and @vturecek 

Have you had a chance to review the question above?

Thanks, Andy

**Comment by kavyako** [comment]
@AndrewJWaite  Thank you for reporting. I am looking into this, will get back to you in a day.

**Comment by kavyako** [comment]
@AndrewJWaite 
Reverse proxy does not have any configs for restricting the cipher suites. The underlying crypto apis use the SCHANNEL specific registry keys to decide the cipher suites being used. You can configure these registry keys on the windows machines to disable support for certain ciphers.

[This Microsoft support document ](https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc) has details of the registry keys and their values. Please configure them to suit your requirements.

**Comment by AndrewJWaite** [comment]
Thanks for the reply @kavyako.

Can you supply any advice or documentation as to how you would reliably bootstrap a Service Fabric node/VM Scale Set to cover initial provisioning via an ARM template and scaling up operations?

**Comment by kavyako** [comment]
@AndrewJWaite If this is not related to the reverse proxy, let us close this thread and open a new one so that the area experts are involved and you get the right guidance.

**Comment by AndrewJWaite** [comment]
OK @kavyako 

I've created issue #623

**Comment by kavyako** [comment]
Closing this issue.
