### ISSUE TITLE
ASF Remoting details

### ISSUE THREAD

**Issue by slipdef** [Azure/service-fabric-issues#59]
Couldn't find any info on how it works under the cover. I'm interested mainly in 2 areas:
- serialization format
- communication protocol

**Comment by masnider** [comment]
Today the default serialization for Remoting is DataContractSerializer and the TCP communication stack is the internal one that is used for the rest of the Service Fabric Cluster. We don't have many details published about the internal TCP communication as it is not a public surface area that we expose for implementation or interop today.

**Comment by VipulM-MSFT** [comment]
We also provide a WCF based remoting implementation. You can also write your own remoting transport provider and use that with ServiceProxy/ActorProxy. In the future versions of the stack we will allow overriding the serialization provider.
