### ISSUE TITLE
Unable to secure cluster

### ISSUE THREAD

**Issue by SixFootRhino** [Azure/service-fabric-issues#593]
We are still having this issue, but it appears the former topic was closed despite not being solved:

https://github.com/Azure/service-fabric-issues/issues/551#issuecomment-338025899

New information has been posted to that thread which is awaiting feedback. But since it's closed, I'll just create this new one, with the same information. ;-)

Picking up where we left off when it was closed...

In particular, we scoured the Application, System, and Security event logs looking for reasons why the nodes were timing out. Based on the information gleaned, it appeared to be a firewall issue. Our AD policies are setup so that only firewall rules specified at the AD level are honored, and in our previous tests, the SF account was not Domain Admin.

So we added the user to be a Domain admin, and we Disabled the Firewall just for kicks. 

Cluster creation script then created 116 firewall rules that were being created, but weren't being honored before. However, we ran into a error from the fabricDeploy trace log:

`2017/11/01-16:26:49.363,Warning,11812,FabricDeployer.FabricDeployer,Error detecting if Containers feature is present. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)
2017/11/01-16:26:49.363,Info,11812,FabricDeployer.FabricDeployer,Dism closing session...
2017/11/01-16:26:49.437,Info,11812,FabricDeployer.FabricDeployer,Dism closing session completed
2017/11/01-16:26:49.437,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down...
2017/11/01-16:26:49.469,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down completed
2017/11/01-16:26:49.472,Info,11812,FabricDeployer.FabricDeployer,Dism log file content: 	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰸ圠牡楮杮†††††††䐠卉⁍†䥄䵓倠潲楶敤⁲瑓牯㩥倠䑉㌽㐲‰䥔㵄㤸㐸䘠楡敬⁤潴䰠慯⁤桴⁥牰癯摩牥›㩃睜湩潤獷呜䵅屐㙁㕃䘹ㅃ〭㜱ⵄ㈴ㄱ䈭㙂ⴵぁぁ䔷ㅂ䅃㥃停偅潲楶敤⹲汤⹬ⴠ䌠䥄䵓牐癯摩牥瑓牯㩥䤺瑮牥慮彬敇側潲楶敤⡲牨〺㡸〰〷㜰⥥਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†䥄䵓倠捡慫敧䴠湡条牥›䥐㵄㈳〴吠䑉㠽㠹‴慆汩摥琠⁯敧⁴桴⁥灕慤整琠牨畯桧䌠卂‮‭䑃卉偍捡慫敧㨺湉整湲污佟数䙮慥畴敲栨㩲砰〸昰㠰挰ഩ㈊㄰ⴷㄱ〭‱㘱㈺㨶㤴‬牅潲⁲††††††††䥄䵓†䐠卉⁍慐正条⁥慍慮敧㩲倠䑉㌽㐲‰䥔㵄㤸㐸䘠楡敬⁤潴朠瑥琠敨甠摮牥祬湩⁧䉃⁓敆瑡牵⁥‭䑃卉偍捡慫敧㨺灏湥敆瑡牵⡥牨〺㡸〰て〸⥣਍믯㊿㄰ⴷㄱ〭‱㘱㈺㨶㤴‬牅潲⁲††††††††䥄䵓†䄠䥐›䥐㵄㐸㐸吠䑉㠽㘳‸慆汩摥琠⁯灯湥映慥畴敲䌠湯慴湩牥⁳‭䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣㨺湉整湲污硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄㌸㠶䤠瑮牥慮䕬數畣整映楡敬⁤‭䉃獡䍥浯慭摮扏敪瑣㨺硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㐺ⰹ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄ㄱㄸ′䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣椠瑮牥慮⁬硥捥瑵潩⁮慦汩摥ⴠ䐠獩䝭瑥敆瑡牵䥥普䥯瑮牥慮⡬牨〺㡸〰て〸⥣਍
2017/11/01-16:26:49.472,Warning,11812,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. Treating feature as not present and continuing. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)	   at System.Fabric.FabricDeployer.DockerDnsHelper.IsContainersFeaturePresent()
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Containers feature not present. Not continuing further
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Successfully completed DockerDnsHelper.CleanupAsync
2017/11/01-16:26:49.483,Info,11812,FabricDeployer.FabricDeployer,Completed DockerDnsHelper.CleanupAsync
2017/11/01-16:26:49.485,Info,11812,FabricDeployer.FabricDeployer,Dism initializing...
2017/11/01-16:26:49.487,Info,11812,FabricDeployer.FabricDeployer,Dism initializing completed, opening online session...
2017/11/01-16:26:50.046,Info,11812,FabricDeployer.FabricDeployer,Dism opening online session completed, getting feature info...
2017/11/01-16:26:50.374,Warning,11812,FabricDeployer.FabricDeployer,Error detecting if Containers feature is present. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)
2017/11/01-16:26:50.374,Info,11812,FabricDeployer.FabricDeployer,Dism closing session...
2017/11/01-16:26:50.438,Info,11812,FabricDeployer.FabricDeployer,Dism closing session completed
2017/11/01-16:26:50.438,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down...
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Dism shutting down completed
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Dism log file content: 	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	[8484] [0x8007007b] FIOReadFileIntoBuffer:(1415): The filename, directory name, or volume label syntax is incorrect.	[8484] [0xc142011c] UnmarshallImageHandleFromDirectory:(511)	[8484] [0xc142011c] WIMGetMountedImageHandle:(2568)	〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ圠牡楮杮†††††††䐠卉⁍†䥄䵓倠潲楶敤⁲瑓牯㩥倠䑉㐽㔵′䥔㵄㜹㐶䘠楡敬⁤潴䰠慯⁤桴⁥牰癯摩牥›㩃睜湩潤獷呜䵅屐㈱㘷䄷㈵䄭䕃ⴹ䐴〴䈭㤷ⴹ䄶㘳䄲㑅䘱㥅停偅潲楶敤⹲汤⹬ⴠ䌠䥄䵓牐癯摩牥瑓牯㩥䤺瑮牥慮彬敇側潲楶敤⡲牨〺㡸〰〷㜰⥥਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†䥄䵓倠捡慫敧䴠湡条牥›䥐㵄㔴㈵吠䑉㤽㘷‴慆汩摥琠⁯敧⁴桴⁥灕慤整琠牨畯桧䌠卂‮‭䑃卉偍捡慫敧㨺湉整湲污佟数䙮慥畴敲栨㩲砰〸昰㠰挰ഩ㈊㄰ⴷㄱ〭‱㘱㈺㨶〵‬牅潲⁲††††††††䥄䵓†䐠卉⁍慐正条⁥慍慮敧㩲倠䑉㐽㔵′䥔㵄㜹㐶䘠楡敬⁤潴朠瑥琠敨甠摮牥祬湩⁧䉃⁓敆瑡牵⁥‭䑃卉偍捡慫敧㨺灏湥敆瑡牵⡥牨〺㡸〰て〸⥣਍믯㊿㄰ⴷㄱ〭‱㘱㈺㨶〵‬牅潲⁲††††††††䥄䵓†䄠䥐›䥐㵄㐸㐸吠䑉㔽㜶‶慆汩摥琠⁯灯湥映慥畴敲䌠湯慴湩牥⁳‭䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣㨺湉整湲污硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄㘵㘷䤠瑮牥慮䕬數畣整映楡敬⁤‭䉃獡䍥浯慭摮扏敪瑣㨺硅捥瑵⡥牨〺㡸〰て〸⥣਍〲㜱ㄭⴱ㄰ㄠ㨶㘲㔺ⰰ䔠牲牯††††††††䐠卉⁍†偁㩉倠䑉㠽㠴‴䥔㵄ㄱㄸ′䝃瑥敆瑡牵䥥普䍯浯慭摮扏敪瑣椠瑮牥慮⁬硥捥瑵潩⁮慦汩摥ⴠ䐠獩䝭瑥敆瑡牵䥥普䥯瑮牥慮⡬牨〺㡸〰て〸⥣਍
2017/11/01-16:26:50.470,Warning,11812,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. Treating feature as not present and continuing. Exception: System.Runtime.InteropServices.COMException (0x800F080C): Exception from HRESULT: 0x800F080C	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)	   at System.Fabric.FabricDeployer.Utility.IsContainersFeaturePresent()
2017/11/01-16:26:50.470,Info,11812,FabricDeployer.FabricDeployer,Skipping container network clean up since containers feature has been disabled.
2017/11/01-16:26:50.472,Info,11812,ImageStoreClient.ManagedFileLock,Released writer lock on C:\ProgramData\SF\lock_Remove
`

Any additional help would be greatly appreciated. We have spent dozens of hours on this. As you can see, we got a lot further, but are stuck again and really need and welcome your assistance here. Specific questions we have:

1) How we do get past the above errors that now block us?
2) Why do have to run as Domain Admin, and what can we do to make it so that we don't have to?
3) Given the policy of firewall rules being specified by the AD, how do you suggest we overcome that issue? Will there be a problem with scripting the creation of those rules and running that prior to SF Cluster Creation? What is the long-term impact of doing so? Will cluster upgrades silently fail if you add new rules that also fail to be created? Are  you adding rules often? Given how cluster creation works today, this seems like it would be risky.

Again, thanks in advance for helping us with this. We're stuck.

**Comment by Liphi** [comment]
@sdkadam2017 , could u help take a look? Some container related code path is hit in fabric deployer.

**Comment by sdkadam2017** [comment]
2017/11/01-16:26:50.470,Warning,11812,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. Treating feature as not present and continuing.

Even though you see exceptions related to Dism the above log statement 
indicates that we have proceeded with deployment. Btw - is this Windows 2016 DataCenter With containers image?

**Comment by mani-ramaswamy** [comment]
@SixFootRhino Closing the issue since we've not heard back for 4 months. Please reopen the issue if you are still hitting it.
