### ISSUE TITLE
Info - Onpremise SF - Reverse Proxy Logs

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#594]
Hello Team,
what is location of Reverse proxy logs and is there way to get all errors from logs file using some tool ?
i know Microsoft message analyzer is there but not sure about patters of reverse proxy logs file.
we were seeing 504 gateway issue that resolved automatically but i would like to do analysis of logs to figure it out if there are any exception.

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
There is folder in each node C:\ProgramData\SF\DiagnosticsStore but this contains lots of information. is there way to filter only reverse proxy logs ?
do i need to enable reverse proxy logs to go to some specific folder ?

**Comment by nareshkhatri81** [comment]
any updates guys ?
This is blocker for us.
There is no much help available to filter logs.
there are tons of logs generated.
how to filter logs to see exception only ?

**Comment by mgrishkov** [comment]
@nareshkhatri81 I've asked about Reverse Proxy logging earlier.  You may found some breadcrumbs [here](https://github.com/Azure/service-fabric-aspnetcore/issues/29). The main idea is that you can subscribe to ETW source to catch traces. For further information [see doc](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics).

**Comment by dkkapur** [comment]
[This doc](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad#collect-reverse-proxy-events) describes the appropriate ETW channel + logLevelFilter to tap into the Reverse Proxy logs. The first keyword filters for only Error and Critical traces, the second enables everything. Hope that helps!

**Comment by nareshkhatri81** [comment]
Which tool to use for analysis of logs ? Is it possible to remotely do analysis from visual studio ?

**Comment by nareshkhatri81** [comment]
Are there steps documented somewhere to use microsoft message analyzer to view sf logs ?
Or steps to configure visual studio to remotely see logs of onprem cluster ?

**Comment by nareshkhatri81** [comment]
@dkkapur  - With Microsoft message anlayzer i am able to view live traces but i am not sure how to filter it.
i am still not sure what is procedure to get all channels or to see specific channels.
if you have any document which highlights those it will be great.

**Comment by nareshkhatri81** [comment]
@dkkapur -
In Microsoft message analyzer. There is option of seeing live traces.
In Live Traces windows you select Add providers and select Service fabric as ETW providers then you will see live traces of events getting published to that channel by Service fabric.
one thing i noticed is that log type is coming as null which could be used to filter it.
and i don't see channel for Data and Messaging.

**Comment by dkkapur** [comment]
@nareshkhatri81 when you set the ETW provider, I'm assuming you are using the guid to do so? Is there a place for you to add additional parameters like keyword filters and log level filters? You'll have to change the keyword filter to get data and messaging channel events.

**Comment by dkkapur** [comment]
Going to close this for now - please let me know if you want to reopen it for a reason, or feel free to open up a new issue! Thanks!
