### ISSUE TITLE
Please support Functions as a Service FaaS in Service Fabric

### ISSUE THREAD

**Issue by AceHack** [Azure/service-fabric-issues#597]
For a MVP version just support like HTTP and Remoting triggers and only .NET and/or containers support, that would be a great start.  I think it would require having a built in service for FaaS and the ability to upload functions at runtime, maybe some UI in a stretch. :)

**Comment by mkosieradzki** [comment]
Azure Functions Runtime is currently in preview and AFAIK it is container based. It would be really nice to be able to eventually run all Azure Functions Runtime components on top of the Service Fabric. One of bigger highlights can be support for Durable Functions (see #592).

**Comment by masnider** [comment]
At this point we've seen a lot of folks having success running the azure functions runtime directly on top of SF. There's also the one hosted in IIS, which works fine if you containerize it. 

At this point there's no plans for a first classed function model on top of SF.  I personally agree that this would be great, but there's nothing showing up in the runtime any time soon. For now we'll focus on making sure the functions runtime works well. 

Thanks for the suggestion and the feature request! We may revisit this in a future version of Service Fabric, or more tightly integrate the functions runtime at a later date.

**Comment by eponerine** [comment]
@masnider , when you say "directly on top of SF", you're referring to the Runtimes co-existing with each other on the same node(s)?

**Comment by pksorensen** [comment]
Anyone found some examples of someone who have put the function's runtime into there service fabric cluster?
