### ISSUE TITLE
Service Fabric Compose Deploy VSTS build task does not use the new upgrade commands

### ISSUE THREAD

**Issue by brandmo** [Azure/service-fabric-issues#598]
Hi there,

v2.8/6.0 included new functionality to allow Compose Deploy apps to be upgraded rather than deleting and deploying new versions.

See https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose
Start-ServiceFabricComposeDeploymentUpgrade
Get-ServiceFabricComposeDeploymentUpgrade

The Service Fabric Compose Deploy build task in VSTS doesn't yet take advantage of this, so existing deployments are still deleted and replaced rather than upgraded.

**Comment by MikkelHegn** [comment]
@brandmo - I would recommend that you to open a new issue in the Microsoft/vsts-tasks repo to track this work, as the tasks reside there.

**Comment by brandmo** [comment]
Thanks @MikkelHegn 

https://github.com/Microsoft/vsts-tasks/issues/5760

**Comment by MikkelHegn** [comment]
Closing here - as this is tracked in the vsts repo.
