### ISSUE TITLE
Question - Service Fabric Reverse Proxy

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#599]
Hi Team,
i have 3 nodes running in 2 VMs onpremise.
Service 1 is deployed on both node 1 and node2.
http://node1ipaddress:19081/app/service1 - will this always go to service 1 which is running on node1 always.
http://node2ipaddress:19081/app/service1 - will this always go to service 1 which is running on node2 always.
or its possible for request to go to any of node ?
is there way for us to know if reverse proxy which uses naming service has resolved to node 1 service or node 2 service ?

Thanks,
Naresh

**Comment by Mardoxx** [comment]
I don't think it is deterministic.

You could add a custom header which adds node name. Is there a legitimate reason you need to know this?

**Comment by nareshkhatri81** [comment]
We could add headers but i would like to know what algorithium SF Reverse proxy uses. Does it go to local service or service running on other node.
Reverse proxy also can add header information which node:port has handled request. So everyone can benefit and use that feature

**Comment by nareshkhatri81** [comment]
I think for secuiry reason we wont be able to add header as its going to be sent back to FE.
For test env, we can do that.
But still does SF naming service resolve randomly or local node is given perf or based on perf counter etc.

**Comment by vturecek** [comment]
For stateless services it's a random instance. More info here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

**Comment by nareshkhatri81** [comment]
Is there way to configure it to go to local instance as it may improve perf.
