### ISSUE TITLE
Unreasonably large sflog files

### ISSUE THREAD

**Issue by wmeddie** [Azure/service-fabric-issues#60]
I have a single node in my cluster with two SFLOG files in the work directory.  The files are both around 250 GB but only take up 50 GB of physical space.  These files are causing disk space warnings because the drive they are on only has 50 GB of space.

What are these files for?  Why caused them to become so large?

**Comment by masnider** [comment]
These are sparse files, which is why the size and size on disk don't line up (more info: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365564(v=vs.85).aspx). These are internal files that are used by some of the Service Fabric System Services. That said I'm surprised that they are consuming 50GB of real disk space. Can you confirm that? On my local cluster I only see them consuming several hundred K. Has this cluster been running for a really long time? Can you confirm that these files are actually that large? (usually they are quite small and smaller hard drives have more problems with our ETW logging, which is why I ask)

**Comment by wmeddie** [comment]
You were right, after checking the actual used disk space the SFLog files aren't the files eating up all the disk.  I downloaded and ran WinDirStat on the affected node (the only one of the 5 nodes with a nearly full disk) and found that SvcFab only took up 23 GB the rest are from an unknown file.  Any idea what it could be?

![unknownfile](https://cloud.githubusercontent.com/assets/122480/19077842/02168aca-8a89-11e6-9d41-91d5c6c1e612.png)

**Comment by masnider** [comment]
No idea. .SFK is not an extension known to be associated with Service Fabric, and "unknown" just looks like how windirstat reports things it can't access: https://blog.windirstat.net/20061013/unknown-space

**Comment by gzepeda** [comment]
We discovered that problem today when one of the nodes of the cluster was down. There is a \work folder under the _app/<application name> which had millions of folders and Terabytes of SFLOG files. In one case 4,500,000 folder and over 106TB of SFLOG file. 

Between the 10 nodes of that particular cluster we were using a Petabyte of storage. We deleted the services and cleaned up the used space. These services were created and compiled with the latest version of the SDK and they are all stateful services. 

Waiting to hear from you in case there is already a fix for this.

**Comment by masnider** [comment]
As I said above 

> These are sparse files, which is why the size and size on disk don't line up (more info: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365564(v=vs.85).aspx). 

You are not actually using a PB of storage.

**Comment by mviswan** [comment]
I had similar issue. On my local the servicefabric app would create logs to a point till my c:/ drive ran out of space. Looks like we had antivirus/amp software (sourcefire) installed which spiked service fabric to do this, After disabling  sourcefireamp it is working as expected (consumes ~10 GB)

**Comment by himanshuladola** [comment]
![image](https://user-images.githubusercontent.com/24384240/49868504-a764fa00-fe33-11e8-88df-41b8864dd4a1.png)

I was trouble-shooting issue of disk space and found that SF (Service fabric) log files contains lots of ETL files. I am not sure is it safe to delete those and why it's dumping/eating these much of space. Attached win-dir snapshot for better understanding. 

I have installed on-prem instance of service bus azure (Service bus 1.1)
