### ISSUE TITLE
Service Fabric stuck on Deploying on Datacenter-Core-1709-with-Containers-smalldisk

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#602]
I am trying to deploy a new cluster in Azure. I am trying to use Datacenter-Core-1709-with-Containers-smalldisk image, but my cluster is stuck on Deploying phase. Is semi annual windows branch supported by Service Fabric 6.0.219?

**Comment by mani-ramaswamy** [comment]
It should just work if it is a new cluster. We're working on documentation and features that makes it easier to upgrade from containers built on Datacenter-Core-with-Containers to containers built with version 1709.  
We might need to troubleshoot this further if it is stuck.

**Comment by mkosieradzki** [comment]
@mani-ramaswamy after many hours (and creating support ticket (117110316605332)) it got unstuck.

**Comment by mani-ramaswamy** [comment]
:) Closing the issue for now. Please reopen as appopriate.

**Comment by mkosieradzki** [comment]
@mani-ramaswamy I have checked this on a different cluster. Service Fabric Deployment phase on Datacenter-Core-1709-with-Containers-smalldisk takes around 4 hours on 5xD1_v2. Isn't this a bit too long?
