### ISSUE TITLE
sfproj build collapses multi-line attributes

### ISSUE THREAD

**Issue by grantborthwick** [Azure/service-fabric-issues#603]
Whenever we build the sfproj for our application in Visual Studio, the multi-line attributes in our xml get reformatted onto a single line. This occurs with multi-line attributes in ApplicationManifest.xml and each environments ApplicationParameters xml file, but doesn't appear to affect ServiceManifest.xml or Settings.xml (defined in a references project).

We prefer to keep this JSON on multiple lines so that it is easier to edit without making mistakes.

When I build with 
```xml
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="fabric:/MyApplication" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="SomeJSONConfiguration" Value="
      {
        'SomeKey': ['SomeValue','AnotherValue'],
        'SomeDictionary':
        {
          'SomeDictionaryKey': {
            'AKey': 'AValue',
            'BKey': 'BValue'
          },
          'AnotherDictionaryKey': {
            'CKey': 'CValue',
            'DKey': 'DValue'
          }
        }
      }" />
  </Parameters>
</Application>
```
the file is overridden with
```xml
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="fabric:/MyApplication" xmlns="http://schemas.microsoft.com/2011/01/fabric">
    <Parameter Name="SomeJSONConfiguration" Value="       {         'SomeKey': ['SomeValue','AnotherValue'],         'SomeDictionary':         {           'SomeDictionaryKey': {             'AKey': 'AValue',             'BKey': 'BValue'           },           'AnotherDictionaryKey': {             'CKey': 'CValue',             'DKey': 'DValue'           }         }       }" />
  </Parameters>
</Application>
```

We're using Microsoft.VisualStudio.Azure.Fabric.MSBuild version 1.6.3.
We're also using Microsoft.ServiceFabric.Services version 2.8.219, but that is referenced only in our csproj projects.

**Comment by dbreshears** [comment]
@grantborthwick,  yeah that is kind of ugly.   You can workaround this by adding the following to your .sfproj and reloading the project.    But this means you will obviously need to update manifests by hand when adding services or updating parameters, etc.. 
    <UpdateServiceFabricApplicationManifestEnabled>False</UpdateServiceFabricApplicationManifestEnabled>

We should really add this property to the UI (properties window) of the SFApp.  Will look into the formatting issue as well as that for a future release.   Let me know if the workaround helps.

**Comment by dbreshears** [comment]
@amanbha,  looks like appmanifestcleanuputil.exe is the culprit

**Comment by amanbha** [comment]
It uses the to XmlSerializer to serialize/deserialize the xml and rewrite, so behavior comes form it. But it only rewrites the file when something needs to be changed in it.. Does it happen on every build, or only after the first re-build after removing or renaming a service?

**Comment by Mardoxx** [comment]
@amanbha I just tried this, for me it's every build

**Comment by Mardoxx** [comment]
Maybe it's not even possible? https://stackoverflow.com/a/11467016/3515174

Apparently it's invalid to have CDATA in an attribute value, so that's a no-go either 😢

**Comment by amanbha** [comment]
Thanks @Mardoxx , its difficult to preserve it when serializing back but I will look into it and see if I can preserve it somehow by some other workaround. Is it just its difficult to manipulate it, and causing no functional issues, correct?

**Comment by Mardoxx** [comment]
I can't speak for @grantborthwick but I don't imagine it does -- not unless someone is relying on the line breaks to be in specific locations!

Ability to have XML stored as an app param is just an aside, but some may find it useful -- not really sure. I'm still unsure myself as to what, exactly, is appropriate to put in the app params files!

Thanks 😄
