### ISSUE TITLE
Remoting V2 on .Net standard occasional Unhealty, stuck partitions or Quorum loss

### ISSUE THREAD

**Issue by francescocristallo** [Azure/service-fabric-issues#604]
I have a Service Fabric Cluster version 6.0.219.9494 using the SDK 2.18.219 on Widows Server 2016 Datacenter-Server-Core.
There is an Asp.net Core 2.0 Stateless service on .Net Standard calling a Stateful Service using Service Remote V2. The throughput is around 300 calls per second.
The machines are 10 D3_V2 Azure machines.

I have two problems: If I deploy more than 100 partitions, even with the default VS2017 template the Stateful service never goes up, it struggles on getting all the partitions ready.
**Is this because the .NetStandard support is still in preview?**

I lowered the partitions to 25 and it goes up correctly, but during the normal use after a couple of hours I start seeing warnings:

**Unhealthy partitions: 12% (3/25), MaxPercentUnhealthyPartitionsPerService=0%.**
**Unhealthy event: SourceId='System.RAP', Property='IReplicator.CloseDuration', HealthState='Warning', ConsiderWarningAsError=false.The api IStatefulServiceReplica.Open on node _Workers_3 is stuck**

and 

**Secondary Replication Queue Usage of 82% has reached/exceeded the threshold 80%.**

The stuck partitions are extremely slow and do not recover or autorepair anymore.

Sometimes one of the partitions goes on quorum loss and the calls to the stateless service that call the stateful are stuck raising the CPU of the stateless service node.

The parameters for the stateful service are 
```

<Parameter Name="Worker1_PartitionCount" Value="25" />

    <Parameter Name="Worker1_TargetReplicaSetSize" Value="3" />

    <Parameter Name="Worker1_MinReplicaSetSize" Value="2" />
```

Any idea on how to understand why this happens?
Also, if the Stateful partition is not responsive, the Stateless service calling it is stuck too, the timeout seems to be 4 minutes, how do I change it?

Thanks

**UPDATE:**

I disabled autoscale on the Stateful services and it's 24h that I don't see the problem anymore. When was active I was autoscaling often.
Could this be autoscale related?

**Comment by vturecek** [comment]
There is an issue with stateful services on .NET Core in the 3.0-preview packages that can cause replicas to get stuck during shut down. Should have a fix out for that soon.

@amanbha  what's the best way to change timeouts in the latest Service Remoting?

**Comment by amanbha** [comment]
reg, the timeouts: Default retry parameters are provied by [OperationRetrySettings]. (https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.communication.client.operationretrysettings) User can configure these values by passing OperationRetrySettings object to ServiceProxyFactory constructor.

**Comment by francescocristallo** [comment]
@amanbha Thanks for the reply. I need another push to get this right, on the stateless service I call the remote one 

`  var myservice= ServiceProxy.Create<IStorageCacheService>(new Uri("fabric:/MyCompany/Service"), new ServicePartitionKey(Fnv1aHashCode.Get64bitHashCode(key)));
           `
I then use myservice to cal the remote method via an interface

`await myservice.DoSomething();`

I can't figure out where to pass OperationRetrySettings , I can't find the ServiceProxyFactory constructor.
Do I have to create a custom ServiceProxyFactory? If you have a code reference would be greatly appreciated, because of the bug in this topic Stateful services are getting stuck multiple times per day and the Node with the stateless services got stuck too autoscaling the machines like crazy, setting a timeout to 500ms would help. 

Thanks

**Comment by amanbha** [comment]
Following cnippet shows how to configure FabricTransportRemotingSettings and OperationRetrySettings.
Its using the constructor https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.client.serviceproxyfactory.-ctor?view=azure-dotnet#Microsoft_ServiceFabric_Services_Remoting_Client_ServiceProxyFactory__ctor_System_Func_Microsoft_ServiceFabric_Services_Remoting_V2_Client_IServiceRemotingCallbackMessageHandler_Microsoft_ServiceFabric_Services_Remoting_V2_Client_IServiceRemotingClientFactory__Microsoft_ServiceFabric_Services_Communication_Client_OperationRetrySettings_

`
var remotingSettings = new FabricTransportRemotingSettings();
            remotingSettings.OperationTimeout = TimeSpan.FromSeconds(20);

            var retrySettings = new OperationRetrySettings(
                TimeSpan.FromMilliseconds(1000),
                TimeSpan.FromMilliseconds(1000),
                10);

            var proxyFactory = new ServiceProxyFactory(
               callbackClient =>
               {
                   return new FabricTransportServiceRemotingClientFactory(
                                   remotingSettings,
                                   callbackClient);
               }, retrySettings);

            var myService = proxyFactory.CreateServiceProxy<IMyService>(new Uri("fabric:/MyApp/MyService"), new ServicePartitionKey(1));
            await myService.Method1();
`

**Comment by francescocristallo** [comment]
@vturecek Any idea how long will take until the next release and the fix of this bug? 
The stateful services are impossible to use, I had to remove all references from Stateless services to any Stateful because were causing 

**There was an error during CodePackage activation.The service host terminated with exit code:2147943401**

and after 20 min from the first deploy the entire cluster was down

**Comment by raunakpandya** [comment]
This should be resolved in the latest SDK release.

**Comment by raunakpandya** [comment]
Can you please share your cluster logs for the stateful service stuck issue?

**Comment by francescocristallo** [comment]
Unfortunately I had to remove it and create another one using only stateless services. Anyway If I'm going to find the problem again, could you please share the right way to share the logs?

**Comment by raunakpandya** [comment]
If its publicly possible you can share it via dropbox or any other sharing platform. If not, you can mail me @ raunakp at Microsoft dot com

**Comment by raunakpandya** [comment]
Can you also share which nuget packages are you using? and the SDK and runtime version where you tried latest.

**Comment by ashishnegi** [comment]
The current 6.2.283 SDK has fixes for replica stuck problem mentioned. 
Please reactivate if you still see issue with latest SDK.
