### ISSUE TITLE
RemotingListener property of the Actor service always seems to be set to V1Listener

### ISSUE THREAD

**Issue by MattDarg** [Azure/service-fabric-issues#605]
I'm using the V2 Listener, the endpoint shows as V2 in the config and V2 functions are in the remoting stack but the RemotingListener property reports V1Listener.

**Comment by Mardoxx** [comment]
Fancy posting some code? The `RemotingListener` where?

**Comment by MattDarg** [comment]
Sorry, it wasn't clear in the title - the ActorService class.  Also, I just realised these have their own repo so I will propose a patch there.
