### ISSUE TITLE
False ServiceReplicaStatus of guest executable 

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#606]
Iam using a guest executable which hosts a nodejs application with npm packages zipped. In the service manifest of the Guest Exe we have 
```
<SetupEntryPoint>
      <ExeHost>
        <Program>MySetup.bat</Program>
        <WorkingFolder>CodePackage</WorkingFolder>
        <ConsoleRedirection FileRetentionCount="10"/>
      </ExeHost>
</SetupEntryPoint>
```

this is responsible for unzipping the npm packages before the nodejs server starts. All this is working fine but we get a false (ready) status on the replica instance of the guest service, i.e while the npm packages are being unzipped the status is shown to be ready, which should instead be ready when the unzip completes and server starts listening for requests

**Comment by RajeetN** [comment]
SF cant tell when you are done processing to be in "ready" state inside your guest exe. If you need such status control, you will need to implement it as stateless/stateful SF service

**Comment by nineralpha** [comment]
@RajeetN so when does SF marks a guest service as ready? like when the code package is copied successfully or something similar??

**Comment by RajeetN** [comment]
Currently SF marks the guest service as ready when starting the guest exe after copying.
