### ISSUE TITLE
Package .sfproj with msbuild results in an error

### ISSUE THREAD

**Issue by fplaten** [Azure/service-fabric-issues#609]
I'm trying to package my Service Fabric application with 
`msbuild MyProject.sfproj /t:Package /p:platform="x64" /p:configuration="Debug"`, which results in an error:

> System.InvalidOperationException: There is an error in XML document (4, 45). ---> System.Xml.Schema.XmlSchemaValidationException: The 'Value' attribute is not declared.

I've debugged for hours without having any luck. I don't even know what this exception is trying to tell me. Is msbuild looking for a <Value> tag and can't find it?

I'm happy about any help or pointers to the right direction.

Btw VS for mac is not able to package an Service Fabric application, right?

**Comment by xunlu** [comment]
Please share your project or at least the manifest files.

**Comment by dbreshears** [comment]
@fplaten Correct in that VS for mac will not be able package your Service Fabric Application.   If you would like to see Service Fabric tooling in VS for Mac I would suggest logging a suggestion on https://visualstudio.uservoice.com.        

As far as the issue, have you discovered the issue yet,  If not,  can you share your Manifest files?
