### ISSUE TITLE
[Linux] Debian Package EULA prevents automated install

### ISSUE THREAD

**Issue by rcarmo** [Azure/service-fabric-issues#61]
Hi there,

## Issue Detail

When doing:

```
apt-get install servicefabricsdkcommon
```

I am prompted for a EULA (which is OK), but there is apparently no way to script the EULA acceptance using `debconf-set-selections` as is common practice (which is not OK). 

## What Should Happen

For instance, for the JDK I usually do:

```
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
```

And then ```apt-get install -y oracle-java8-installer``` works without any prompting.

## Debugging Steps Taken

Doing a ```debconf-get-selections | grep azure``` yields nothing, so I am assuming this is not baked in to the `.deb` file as is common practice.

## Impact

This effectively blocks me from doing automated installs on Linux and setting up reproducible environments without manual intervention during the install phase (or hacky and error-prone shell scripts).

**Comment by anmolah** [comment]
Thanks for the feedback @rcarmo. We will be looking into fixing this as soon as we can.

**Comment by mani-ramaswamy** [comment]
Fixed with the latest release - servicefabric version 5.3.0.3 and servicefabricsdkcommon, servicefabricsdkjava, servicefabricsdkcsharp versions 0.6.0.1.

You can upgrade to the latest with the foll.:
sudo apt-get update
sudo apt-get install servicefabricsdkjava  (or servicefabricsdkcsharp), and it will pull the rest in.

**Comment by rcarmo** [comment]
Hi guys! Thanks, but how do I set the flag to bypass the EULA?

**Comment by anmolah** [comment]
For servicefabric package  - echo "servicefabric servicefabric/accepted-eula-v1  select true" | debconf-set-selections

For servicefabricsdkcommon package - echo "servicefabricsdkcommon servicefabricsdkcommon/accepted-eula-v1  select true" | debconf-set-selections

**Comment by rcarmo** [comment]
Thanks @anmolah - that's great!

**Comment by knizami** [comment]
Hello, this works on my docker host but when I try to dockerize it, it doesn't appear to work.

Please see so:

http://askubuntu.com/questions/881318/automate-acceptance-of-eula-in-servicefabricsdkcommon-package-on-ubuntu

**Comment by knizami** [comment]
FYI - 

I was able to fix this by adding
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
at the top of my Dockerfile

**Comment by sonata82** [comment]
Don't forget to set
`DEBIAN_FRONTEND=noninteractive`
:smile:
