### ISSUE TITLE
FABRIC_E_ENDPOINT_NOT_FOUND when trying to access Guest Executable through the Reverse Proxy

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#615]
I am experimenting with lift and shift for pre-existing ASP.NET Core applications. I have overcome most of difficulties using proper powershell and cmd scripts.
1. I can deal with dynamic ports using Service Fabric and ASP.NET core environment variables
2. I can deal with encrypted secrets using powershell script

However I am unable to handle Reverse Proxy:
1. ImplicitHost does probably not register Listener for endpoint and in consequence Reverse Proxy is unable to find any endpoint (even if there is a single one)
2. No one can expect port sharing related headers to be handled properly in a lift and shift scenario. So even if ImplicitHost would perform proper registration Reverse Proxy still requires some special handling for guest executables.

My understanding is that Reverse Proxy cannot handle guest executables today. Or am I missing something?

**Comment by kavyako** [comment]
Reverse proxy should be able to forward to endpoints opened by guest executables.
1. Can you share the service manifest. 
2. How is the listener opened? can you share a sample code snippet.
In your local dev cluster, could you check what diagnostics show up in the VS diagnostic event viewer when the request through reverse proxy fails. Refer [Collect reverse proxy events section ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad) here.

**Comment by mkosieradzki** [comment]
@kavyako thanks. I have created a simple project from scratch to help you reproduce the issue. See attachment.

[SFWebAppRepro.zip](https://github.com/Azure/service-fabric-issues/files/1458102/SFWebAppRepro.zip)

You can easily access the application at the endpoint address registered in Service Fabric, but not through the Reverse Proxy.

Application is just an empty ASP.NET Core 2.0 hello world application.

This is the service manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="Guest1Pkg" Version="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="Guest1Type" UseImplicitHost="true" />
  </ServiceTypes>
  
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>run.cmd</Program>
        <Arguments></Arguments>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </EntryPoint>
  </CodePackage>

  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      <Endpoint Name="Public" Type="Internal" Protocol="http" />
    </Endpoints>
  </Resources>
</ServiceManifest>
```

run.cmd:
```
powershell.exe -File run.ps1
```

run.ps1:
```
$Env:ASPNETCORE_URLS = "http://*:$Env:FABRIC_ENDPOINT_PUBLIC"
& ./WebApplication1.exe
```

**Comment by Mardoxx** [comment]
Something to note is that the URLs inside SF Explorer does not have http:// in its endpoint defn.

**Comment by mkosieradzki** [comment]
@Mardoxx Good point, however I have checked the manifest of deployed application and it has protocol specified as http.
```
<Endpoints>
  <Endpoint Name="Public" Protocol="http" />
</Endpoints>
```

So despite I specify explicitly protocol as http my app is not registered as HTTP. Maybe due to lack of explicit port specification?

Have you eventually managed to make your nodejs application to work via RP?

**Comment by Mardoxx** [comment]
I edited my response after you replied!

**Comment by Mardoxx** [comment]
@kavyako woud a viable solution be to default urischeme to protocol if it's not set? @mkosieradzki and I certainly won't be the only ones caught out by this

**Comment by mkosieradzki** [comment]
Thanks @Mardoxx ! I was not aware of this undocumented trick. I think it will fix my issue ;).

Especially it is not needed if your are not using implicit host. Another thing worth testing now is handling for ResourceNotFound. I am curious how it is handled in this scenario, because it makes no sense to expect from lift and shift guest executable to understand the ResourceNotFound mechanism.

**Comment by Mardoxx** [comment]
I don't think it is! See
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services
(the bit about X-ServiceFabric header). I think in lift and shift scenario
you still have to add special handling for this (there is a middleware for
aspnet core provided by MS though).

On 10 Nov 2017 5:26 pm, "mkosieradzki" <notifications@github.com> wrote:

Thanks @Mardoxx <https://github.com/mardoxx> ! I was not aware of this
undocumented trick. I think it will fix my issue ;).

Especially it is not needed if your are not using implicit host. Another
thing worth testing now is handling for ResourceNotFound. I am curious how
it is handled in this scenario, because it makes no sense to expect from
lift and shift guest executable to understand the ResourceNotFound
mechanism.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/service-fabric-issues/issues/615#issuecomment-343535346>,
or mute the thread

**Comment by mkosieradzki** [comment]
@Mardoxx I am aware of this middleware, because I am the author ;).

IMO for guest executables X-ServiceFabric header should be configurable #613 .

For example if you are using Guest Executable to host nodejs application - you can provide this header, however if you are running a preexisting application you cannot do such things. This is why it should be a configuration option for implicit host.

**Comment by mkosieradzki** [comment]
@Mardoxx thanks. I can confirm that UriScheme trick works. Unfortunately as expected Reverse Proxy requires X-ServiceFabric header for 404, what makes the guest executable mechanism unusable for preexisting applications.

**Comment by Mardoxx** [comment]
@mkosieradzki Ahh! Well thanks for that, saved me a lot of typing and issues where I forgot to add the header for 404!

You make a good point there for existing applications -- you'd expect that you'd be able to just change the way the application is hosted and it should work out of the box with no modification!

**Comment by kavyako** [comment]
@Mardoxx  thank you for suggesting the fix :)
The "Protocol" attribute is used to add the url acls. 
The "UriScheme" attribute is used for endpoint publishing.
I'll see if we can simplify this.

To make the X-ServiceFabric header configurable, it is in our backlog of items to tackle.

**Comment by kavyako** [comment]
Using UriScheme addresses the problem, hence closing the issue.
We will continue to use #613  to track the X-Servicefabric header.
