### ISSUE TITLE
Patching Orchestration Application: How to collect telemetry

### ISSUE THREAD

**Issue by GeorgiMateev** [Azure/service-fabric-issues#617]
Hello,
[The documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patch-orchestration-application#disclaimers) about POA states that:

> The patch orchestration app collects telemetry to track usage and performance. The application’s telemetry follows the setting of the Service Fabric runtime’s telemetry setting (which is on by default).

But there is no information about:

- what metrics are collected
- where are they stored
- how we can stream them to Application Insights (I see that the Coordinator Service have the Microsoft.ApplicationInsights.dll in its Code folder)

Can you please provide information on the above points and also update the docs if possible?

Thanks!

**Comment by novino** [comment]
Hey @GeorgiMateev ,

Data collected by POA includes unique ID's of cluster, type of cluster (Azure vs standalone, which OS), number of installations done, how many installations were successful, some key settings of POA.

All this data is stored in Service Fabric team's app insight accounts and this data is intended for internal use by SF POA team.

Any specific reason why you're looking for this data ?

Warm Regards,
Naveen

**Comment by GeorgiMateev** [comment]
Hi @novino ,
I want to keep trace record of all patch installations and all errors in our Application Insights without having to ping and parse the CoordinatorService endpoint.
With this data we can setup alerts and correlate with other diagnostic events in App Insights when issues occur.

**Comment by novino** [comment]
For your usecase I would recommend tapping onto below event from coordinator. It has the same information which are collected as part of telemetry. Everytime an installation operation completes coordinator primary would emit this event.

Provider ID - 24afa313-0d3b-4c7c-b485-1047fd964b60
EventID - 11

You can use the fields clusterId, nodeName, totalInstallations, successfulInstallations for your data collection.

Below is the actual event of eventsource for your reference.
```
        private const int PatchInstallationTelemetryEventId = 11;

        [Event(PatchInstallationTelemetryEventId, Level = EventLevel.Verbose,
            Message = "TelemetryEvent : PatchInstallationEvent clusterId = {0}, tentantId = {1}, clusterType = {2}" +
                      "nodeName = {3}, updateFrequency = {4}, updateQuery = {5}, approvalPolicy = {6}, applicationVersion = {7}, totalInstallations = {8}" +
                      "successfulInstallations = {9}, operationResult = {10}")]
        public void PatchInstallationTelemetryEvent(string clusterId,
            string tenantId,
            string clusterType,
            string nodeName,
            string updateFrequency,
            string updateQuery,
            string approvalPolicy,
            string applicationVersion,
            double totalInstallations,
            double successfulInstallations,
            string operationResult)
        {
            this.WriteEvent(PatchInstallationTelemetryEventId, clusterId, tenantId, clusterType, nodeName,
                updateFrequency, updateQuery, approvalPolicy, applicationVersion, totalInstallations,
                successfulInstallations, operationResult);
        }
```

**Comment by GeorgiMateev** [comment]
Thanks @novino ,
```json
{
    "provider": "e39b723c-590c-4090-abb0-11e3e6616346",
    "scheduledTransferPeriod": "PT5M",
    "DefaultEvents": {
        "eventDestination": "PatchOrchestrationApplicationTable"
    }
},
{
    "provider": "fc0028ff-bfdc-499f-80dc-ed922c52c5e9",
    "scheduledTransferPeriod": "PT5M",
    "DefaultEvents": {
        "eventDestination": "PatchOrchestrationApplicationTable"
    }
},
{
    "provider": "24afa313-0d3b-4c7c-b485-1047fd964b60",
    "scheduledTransferPeriod": "PT5M",
    "DefaultEvents": {
        "eventDestination": "PatchOrchestrationApplicationTable"
    }
},
{
    "provider": "05dc046c-60e9-4ef7-965e-91660adffa68",
    "scheduledTransferPeriod": "PT5M",
    "DefaultEvents": {
        "eventDestination": "PatchOrchestrationApplicationTable"
    }
}
```
In the WadConfig / EtwProviders is correctly pushing all events in the table or Application Insights sink, if configured.

**Comment by novino** [comment]
@GeorgiMateev From your above reply, it looks like you're able to make it work using WAD.
If possible could you paste a screenshot from your table/app insight for reference. (do hide out clusterId and other details).
