### ISSUE TITLE
What's the timeline for supporting docker containers in SF on Windows 10?

### ISSUE THREAD

**Issue by markphillips100** [Azure/service-fabric-issues#618]
This [doc](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-overview) notes that deploying docker containers to an SF cluster on Windows 10 is not supported "yet".  Can we assume that it will be and if so when this will likely occur?

If the feature is off the radar or not likely for some time, other than installing Windows Server 2016 on dev machines what are the alternative dev setups, assuming local dev OS is Win 10 running VS 2017 and Windows containers would be used along with a docker compose.yml?

**Comment by RajeetN** [comment]
The feature is in the works but we don't have a firm timeline to share as yet. At this point Windows Server 2016 is the way to deploy windows containers
