### ISSUE TITLE
Stateful services on .NET Core (Tools 2.0 Preview) stuck InBuild

### ISSUE THREAD

**Issue by tarynt** [Azure/service-fabric-issues#619]
Hi,

I've been trying to get up and running with the new templates for .NET Core 2.0 mentioned at https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/12/visual-studio-2017-service-fabric-tools-2-0-preview/

Stateless services work fine, however stateful gets stuck with the status InBuild. For both types I am using the basic templates under Service Fabric Application > .Net Core 2.0 (Preview).

Sample VS output from stateful app:
```
Service Status:
fabric:/Application1/Stateful1 is not ready, 1 partitions remaining.

... repeats ...

Service Status:
fabric:/Application1/Stateful1 is not ready, 1 partitions remaining.

Something is taking too long, the application is still not ready.
Finished executing script 'Get-ServiceFabricApplicationStatus'.
Time elapsed: 00:00:46.6919343
```

I can hit breakpoints in the stateful services Main() method and everything flows through to the Thread.Sleep. No breakpoints in CreateServiceReplicaListeners or RunAsync are hit.

I'm running Service Fabric SDK ~~2.8.219~~ 2.8.232 as well as the tools 2.0 preview from the above link. Nuget packages for the projects are ~~6.1.219-preview~~ 6.1.232-preview and ~~3.0.219-preview~~ 3.0.232-preview. I've tried on both a 1 node and 5 node dev cluster.

Has anyone else got this working, and were there any additional steps needed?

**Comment by raunakpandya** [comment]
This should be resolved with the latest SDK. Let us know if you still encounter some issues.

**Comment by tarynt** [comment]
Hi @raunakpandya, unfortunately I'm still seeing the same with with the new SDK (Installed via Web Platform Installer). Let me know if there is anything I could attach that would help.

**Comment by raunakpandya** [comment]
Reactivating..

**Comment by tarynt** [comment]
Windows. I'm running against the local dev cluster on a Windows 10 Pro 1709 machine.

**Comment by raunakpandya** [comment]
Can you share your cluster logs?

**Comment by tarynt** [comment]
Sure. I recreated a fresh cluster and ran a single deploy. Linked is the Log folder from inside SfDevCluster.

https://www.dropbox.com/s/okg91m3atf372ax/Log.zip?dl=0

**Comment by raunakpandya** [comment]
@tarynt Thanks for sharing the logs. Would it be possible for you to share the app code/ package which you are using here.

**Comment by tarynt** [comment]
@raunakpandya No worries. Linked are both the package as well as the VS project.

https://www.dropbox.com/s/ynvqoiq6qff9opb/Package.zip?dl=0
https://www.dropbox.com/s/e335jw454926hxr/Project.zip?dl=0

**Comment by tarynt** [comment]
Just an update. I decided to try all the above on an Azure VM with the the same version of VS2017. Everything worked as it should.

I can't see any notable differences between the dev clusters on either machine via Service Fabric Explorer.

**Comment by raunakpandya** [comment]
Thanks for the confirmation @tarynt . Yes, that's what I would expect. There is some difference specific to your dev environment which is causing the app to go in build. I am still trying to understand what it could be.

**Comment by raunakpandya** [comment]
@tarynt  BTW, I went through this thread again and I see you mentioned above that you are running Service Fabric SDK 2.8.219 and preview packages. Both these packages are mutually exclusive. Can you confirm once again what nuget/ SDK and runtime version are you running on your dev cluster?

**Comment by tarynt** [comment]
I'll update the original message, it was written prior to the release of the current SDK. I've confirmed my dev machine is currently running SDK 2.8.232, and NuGet packages for the project are 6.1.232-preview and 3.0.232-preview.

**Comment by raunakpandya** [comment]
@tarynt  - Can you check your event viewer under Windows Logs -> Application and look for event ID 1025, Source - .NET Runime which relates to your application crashing? If you find one, can you share the event data?

**Comment by tarynt** [comment]
@raunakpandya - I couldn't find any events matching that. I've attached the VS2017 debug output which shows exit codes when the stateful service crashes.

[Debug.txt](https://github.com/Azure/service-fabric-issues/files/1477976/Debug.txt)
[Service Fabric Tools.txt](https://github.com/Azure/service-fabric-issues/files/1477977/Service.Fabric.Tools.txt)

**Comment by lvbnhj** [comment]
Same thing happens with me
empty stateful service won't run.
When I start my app in debug mode I can see regular message "The program '[2404] Evos.WebTN.OrderService.exe' has exited with code -2146232797 (0x80131623)"

**Comment by tarynt** [comment]
I've just dusted off an older Windows 10 PC (1703), updated VS2017 to the latest and installed the SDK + tools and ran into the same problems. I'm going to run a Windows 10 instance on Azure next and see if I can repro there. I'll report back.

**Comment by tarynt** [comment]
Everything worked correctly on Windows 10 Pro (1709) on Azure.

**Comment by tarynt** [comment]
Alright, I reinstalled my machine and performed the exact same steps as with the Windows 10 Azure instance. Unfortunately it still won't run here. Could this be a hardware issue? :\

**Comment by raunakpandya** [comment]
Its weird. First I would like to say thanks to you for helping us investigate this further.

Can you try targeting .NET framework 451 and deploy on the same cluster where things were failing. Keep using the preview nugets.

Thanks,
Raunak Pandya
________________________________

**Comment by tarynt** [comment]
@raunakpandya No worries, glad I can help.

I changed the project over to .NET 451 while keeping the preview nugets, this made everything work correctly. So it seems the issue is something with .NET Core.

**Comment by tarynt** [comment]
@raunakpandya On a hunch I decided to download the US version of Win10 and try again. My machines all use Win10 1709 International (For English/Australia). Using the US version everything is now running correctly with .NET Core.

After this worked I tried changing the locale/region settings from US to Australia to see if I could get it to break again, but to no avail.

**Comment by hrushib** [comment]
@tarynt thanks for your help and patience. We were able to repro this issue using steps shared by you. There is bug in coreclr - dotnet/coreclr#12668 which results in this application crash. This issue is fixed in latest dotnet servicing release 2.0.3 - https://github.com/dotnet/corefx/releases/tag/v2.0.3. 

Meantime workaround mentioned by @danmosemsft in coreclr issue discussion works in this case. 
`Put new ArgumentException(); on the first line of Main. This should cause the neutral resources to be cached, avoiding the failure.`
I updated code shared by you with above workaround and could get the app working as expected.

@lvbnhj, please check if the latest dotnet release or the workaround is fixing the issue at your end.

**Comment by tarynt** [comment]
This doesn't appear to be fixed for me in dotnet 2.0.3, however adding `new ArgumentException();` to Main does resolve the issue as a workaround.

**Comment by Eneuman** [comment]
I can also confirm that this has **not** been fixed in 2.0.3 and also that @tarynt workaround do work.

**Comment by danmosemsft** [comment]
Hmm I wonder whether 2.0.3 bits are not being picked up, as this has fixed the bug in other cases. @tarekgh could you please help figure this out?

**Comment by lvbnhj** [comment]
@hrushib 
After updating projects to the 2.0.3 runtime service runs without errors
Thanks

**Comment by hrushib** [comment]
Thanks @lvbnhj for confirming this.
