### ISSUE TITLE
Possible memory leak in Actor Proxy

### ISSUE THREAD

**Issue by hellkama** [Azure/service-fabric-issues#62]
I have a application that has a Stateful Service that is communicating with Volatile Actor service using the Actor Proxy.

The Stateful Service was having serious memory leak issues with unmanaged memory and large amount of objects of `System.EventHandler<Client.CommunicationClientEventArgs<Client.IServiceRemotingClient>>`

The stateful service was basically doing this few times a second:
`
private async Task PublishData(string site, int sourceId, string data)

        {
            var source = ActorProxy.Create<ISource>(Configuration.GetActorId(site, sourceId), Configuration.GetServiceUri(site));
            await source.PublishDataAsync(data);
        }
`

If i commented out the two lines inside the function there were no leaks. I also tried to make it so that ActorProxy is created only once per Actor which also fixed the memory leak.

`
        private async Task PublishData(string site, int sourceId, string data)

        {
            var source = ActorProxyWrapper.GetSingletonInstance(site, sourceId)
            await source.PublishDataAsync(data);
        }
`

Any idea what might be causing this? I have a feeling my code was so fool proof that it must have been a problem within the actor proxy or rest of the service fabric.

However I might not have the time and possibility to provide full solution to reproduce this issue.

**Comment by VipulM-MSFT** [comment]
There is a known issue in the current SDK. Caching the ActorProxy is the right workaround. This will be fixed with the upcoming SDK refresh for 5.3 runtime.

**Comment by hellkama** [comment]
I feel this is why we need to further open source the development of Service Fabric. I feel lot of my time goes to waste if I don't have access to source.

And then I hear that the issue was already known, but not reported anywhere.

**Comment by VipulM-MSFT** [comment]
@hellkama - We are working on open sourcing the programming models.
