### ISSUE TITLE
Question - Is it possible to add data disk to service fabric vm scale set?

### ISSUE THREAD

**Issue by Seohol** [Azure/service-fabric-issues#621]
Hi, I'm trying to add empty data disk to my vm scale set

```
              "dataDisks":[{
                "lun": 1,
                "createOption": "Empty",
                "diskSizeGB": 1023
              }
            ]
```

And I got error:

```
 Activity: Write-Error
 Message: ==================
3:46:16 PM - Resource Microsoft.Compute/virtualMachineScaleSets 'inode' failed with message '{
  "error": {
    "code": "OperationNotAllowed",
    "target": "dataDisk",
    "message": "Addition of a managed disk to a VM with blob based disks is not supported."
  }
}'
```

Is it even possible? to add data disk to sf scale set? Or template example with os and data disks?

**Comment by mkosieradzki** [comment]
This is not exactly Service Fabric related question, but you need to make the OS Disk in your ARM template managed disk, or create the dataDisk as blob disk.

For example this template uses managed disks: https://github.com/Azure/azure-quickstart-templates/blob/master/service-fabric-secure-cluster-5-node-1-nodetype/azuredeploy.json.
