### ISSUE TITLE
Question: Bootstrpping VMSS/Service Fabric Nodes

### ISSUE THREAD

**Issue by AndrewJWaite** [Azure/service-fabric-issues#623]
Can you supply any advice or documentation as to how you would reliably bootstrap a Service Fabric node/VMSS to cover initial provisioning via an ARM template and horizontal scaling operations?

This question relates to advice given in issue #589

Thanks

**Comment by Mardoxx** [comment]
I would be great if someone from Microsoft could give some insight, however...

I believe you can use [custom script extensions](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-customscript) on your VMSS definitions for your node types. There's an example [here](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-custom-script-windows) that you may find useful. I think with this you'd be able to run whatever you like to configure your nodes, e.g. a registry import.

**Comment by mhatreabhay** [comment]
https://github.com/Azure/azure-quickstart-templates/tree/master/service-fabric-secure-nsg-cluster-65-node-3-nodetype

Please take a look at this template. 
SF extension is added on each node type to bootstrap service fabric runtime on vmss.
