### ISSUE TITLE
Remove DnsService Standalone Cluster

### ISSUE THREAD

**Issue by njtrentacoste** [Azure/service-fabric-issues#625]
Is it possible to remove the DnsService from a standalone cluster after cluster provisioning?  I have performed a configuration upgrade and removed DnsService from the AddonFeatures section of the config.  The configuration has been upgraded however the DnsService is still running and I still see it present in the Manifest from Service Fabric Explorer.  Any guidance is greatly appreciated.

**Comment by Mardoxx** [comment]
No, you have to rebuild the cluster with it disabled

**Comment by njtrentacoste** [comment]
Sigh.  Thank you for the quick response.  Is this under consideration for being a capability?

**Comment by milvuko** [comment]
Hi @njtrentacoste ,
to disable DnsService, please add the DnsService section to fabricSettings:
```
              "fabricSettings": [
                   {
                       "name": "DnsService",
                       "parameters": [
                           {
                               "name": "IsEnabled",
                               "value": "false"
                           }
                       ]
                   }
               ]
```
Note that DnsService will be removed after the upgrade is completed (all Upgrade Domains are in Completed state and Upgrade State is RollingForwardCompleted) and FailoverManagerService primary is restarted.

**Comment by njtrentacoste** [comment]
Wonderful news!  I'll try this tomorrow and let you know what happens.

**Comment by njtrentacoste** [comment]
Just to update, this started out well.  In my 3 node cluster, the first two upgrade domains completed, but it stalled out on the third.  This is because during this process, it caused the ImageStoreService to fall into an error state due to an issue with the replica on the upgraded node from UD1.  I attempted to repair the partition as well as disable/restart/enable the node in question but that caused the upgrade to rollback.  Now I'm left in a state where I think I have no other choice but to tear down and rebuild the cluster.  Unless anybody has any ideas?
