### ISSUE TITLE
Service Fabric SDK 2.8.219 Failing to Install Properly

### ISSUE THREAD

**Issue by tommytiang** [Azure/service-fabric-issues#628]
I've tried unsuccessfully to install the latest Service Fabric SDK on my machine. Using Web Platform Installer and followed all instructions in https://github.com/Azure/service-fabric-issues/issues/483 but still no luck. 
The install "seems" to work fine (at least, from looking at WPI UI) - but the Service Fabric Host Service never starts and I'm unable to get it started. I've tried running from powershell Start-Service FabricHostSvc but all I'm getting is:
Warning: Waiting for service ... to finish starting... - it seems to be stuck in the Starting mode...

Looking at Event Viewer for SF these are the errors I'm seeing:
-  Event Id: 23041, FabricActivationManager
   FabricSetup operation returned errorcode 0xffffffff
- EventID 53760, FabricSetup.FabricSetupOperationExecutor, FabricDeployer::Install failed with error 0xffffffff, Rolling back
- EventID 53760, FabricSetup.FabricSetupOperationBase, FabricDeployer::Install failed with error 0xffffffff
- EventID 53761, FabricSetup.FabricDeployer, Configuration Deployment failed with error 0xffffffff
- EventID58368, FabricDeployer, System.ArgumentException: Neither TargetInformation.xml nor ClusterManifest.Current.xml found. FabricHost started without configuring the node. Nothing to do. at System.Fabric.FabricDeployer.RestartOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace) at System.Fabric.FabricDeployer.Program.Main(String[] args)
-  EventID58368, FabricDeployer, Neither TargetInformation.xml nor ClusterManifest.Current.xml found. FabricHost started without configuring the node. Nothing to do.</Data> 

Please help - this is ridiculous!! It shouldn't be this hard to install Service Fabric SDK tools.
I'm running Windows 7 64-bit.

**Comment by Adebeer** [comment]
I fixed this issue was resolved by installing Powershell 5.1 on his machine. Only version 2 was previously installed. 

The installer should probably detect this required install dependency

**Comment by rishirsinha** [comment]
Will take that as a work item.
