### ISSUE TITLE
Windows Service Fabric - SF Explorer: Remove node state left cluster in inoperable state

### ISSUE THREAD

**Issue by helgemahrt** [Azure/service-fabric-issues#629]
Windows Service Fabric (on-Prem) version 6.0.219.9494
Nodes are Azure IaaS VMs, 2 Front End, 4 Back End

We had an issue on one of the FE nodes which left the Azure VM inaccessible, (all vCPUs at 100% except one, even after resizing/redeploying; VM agent inaccessible) so we decided to recreate the node from scratch. We had some issues removing the node from the cluster using a configuration upgrade (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes#remove-nodes-from-your-cluster), because the new config (without the node) wouldn't validate for various reasons (UDs, FDs, expired certificates). 
I went to Service Fabric Explorer and saw the option "Remove Node State". I wrongly assumed this meant removing the node from the cluster. (I now know better :) ) Anyway, after selecting this, the following happened:

- SF Explorer did not render the cluster tree to the left anymore and displayed an error say that it was unable to get the information of the cluster
- When getting the current cluster information using the PowerShell CMDlet **Get-ServiceFabricClusterConfiguration**, I would get a configuration without the node for which I selected "Remove Node State"
- When looking at the **ClusterManifest.current.xml** and **InfrastructureManifest.xml** files in the local files of the cluster nodes, I would still see the node
- Adding a new node as outlined here did not work, because the script was unable to connect to cluster system microservices: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes#add-nodes-to-your-cluster

Not sure what happened here because 1) the modified config never validated and never succeeded in updating the cluster, and therefore never removed the node and 2) removing the node state shouldn't remove the node from the cluster. So I'm not sure why **Get-ServiceFabricClusterConfiguration** started returning a config without the problematic node.
To recuperate the cluster, I had to RDP into each node of the cluster and manually edit the **ClusterManifest.current.xml** and **InfrastructureManifest.xml** files, removing the references to the problematic node manually. Only then did the SF Explorer start working again, and I was able to add a new node to the cluster.

This was a really bad experience, considering that an operation initiated from the UI left the cluster in such a bad state. I'll gladly answer any questions about the cluster setup which may have contributed to reaching this state.

Cheers,
Helge

**Comment by dkkapur** [comment]
Helge - at what version was the original cluster set up? What were the issues you were facing with updating the cluster config without the node in it exactly?

**Comment by rakshitatandon** [comment]
Was the node disabled with intent -RemoveNode before removing its state ? Ideally, the node should be disabled so that the replicas can be moved away from this node before removing it. Was this a seed node ?
RemoveNodeState will remove the node from the cluster's viewpoint (Fabric is still installed on the node but it will not join the ring) and hence Get-ServiceFabricClusterConfiguration will not report that node. 
Multiple things could have gone wrong depending on what services were hosted on the node at the time when -RemoveNodeState was invoked or if this node was a seed node and quorum was being hit. Hard to comment on what actually went wrong without the traces.

**Comment by helgemahrt** [comment]
@dkkapur - The cluster has gone through a few updates already. I believe the first version was 5.5.216.0. The validation first complained about 2 UDs not being enough and then that the FDs weren't populated right. (Or the other way around, not sure anymore) After fixing these it said something about an expired certificate. At that point I had lost confidence in this method of removing the node from the cluster and was looking for alternatives.

@rakshitatandon - No, I did not use -RemoveNode first. However, the node was displayed as offline in the SF Explorer because it was inaccessible, so there shouldn't have been any replicas on it anymore anyway.
The node wasn't a seed node.

I get that it's hard to do a post-mortem analysis without any data to look at. If you think there's still anything useful on the other nodes, I'd be happy to send you any logs you need.

**Comment by dkkapur** [comment]
@helgemahrt - just readdressing this issue. What was the resolution in the end?

**Comment by helgemahrt** [comment]
@dkkapur - sorry for the delay. To recuperate the cluster, I had to RDP into each node of the cluster and manually edit the ClusterManifest.current.xml and InfrastructureManifest.xml files, removing the references to the problematic node manually. Only then did the SF Explorer start working again, and I was able to add a new node to the cluster.

**Comment by dkkapur** [comment]
Thanks for this. Going to go ahead and close the issue now. Let us know if there are still issues!
