### ISSUE TITLE
Deployment to dev cluster freezes VS w/o errors

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/service-fabric-issues#63]
After upgrading to SF SDK to v2.2.207 one of my services couldn't be deployed anymore.
It would freeze during deployment at the step #3  of `Publish-NewServiceFabricApplication.ps1`, which is executing `Register-ServiceFabricApplicationType`. At that point script freezes w/o any exception and so does VS. The package is copied to the image store, but not registered. 

I've tried to validate it myself and found that `Publish-NewServiceFabricApplication.ps1` throws an exception on invalid settings.xml file of a service. Sadly, not only that exception is not propagated, but also VS is completely halted and has to be killed :disappointed: 

The settings.xml validate error should really be surfaced up.

Update: the issue has nothing to do with the SF SDK update, but should focus on the scripts freezing VS w/o providing any information.

**Comment by MikkelHegn** [comment]
Thanks for reporting - looking in to this...

**Comment by MikkelHegn** [comment]
The issue with settings.xml is an incorrectly encoded value. So rather than having `&amp;` it was just `&`, that froze VS to death.

Still we will investigate to make sure we do at least do not freeze VS.

**Comment by mthalman-msft** [comment]
@SeanFeldman: Can you describe the invalid content in your settings.xml that caused the hang?  I've tried to reproduce this issue by making an invalid settings.xml that is missing an angle bracket on one of the XML elements but that doesn't cause a hang.  Instead, it produces an appropriate error message in the output:
```
2>Register-ServiceFabricApplicationType : Exception while parsing XML file: 
2>C:\SfDevCluster\Data\ImageBuilderProxy\AppType\Application37Type\Stateless1Pkg\Config\Settings.xml
2>FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\Application37Type\Stateless1Pkg\Config\Settings.xml --> 
2>InvalidOperationException: There is an error in XML document (2, 1). --> XmlException: Data at the root level is 
2>invalid. Line 2, position 1.
2>At C:\Program Files\Microsoft SDKs\Service 
2>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:244 char:9
2>+         Register-ServiceFabricApplicationType -ApplicationPathInImage ...
2>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic 
2>   eFabricApplicationType], FabricException
2>    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp 
2>   e
2> 
```

**Comment by SeanFeldman** [comment]
@mthalman-msft in my case one of the values was not xml-encoded properly. It was a connection string. Once I've encoded it to escape characters not allowed by XML, things were working again.

The original value looked like this (for security reason I'm spoofing the value):
```
<Parameter Name="SasToken" Value="SharedAccessSignature sr=sb%3a%2f%2fblah.servicebus.windows.net&sig=xyz" />
```

```
 <Parameter Name="SasToken" Value="SharedAccessSignature sr=sb%3a%2f%2fblah.servicebus.windows.net&amp;sig=xyz" />

**Comment by mthalman-msft** [comment]
@SeanFeldman: Using that first value you provided still correctly gives me an error in the output:
```
3>Register-ServiceFabricApplicationType : Exception while parsing XML file: 
3>C:\SfDevCluster\Data\ImageBuilderProxy\AppType\Application37Type\Stateless1Pkg\Config\Settings.xml
3>FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\Application37Type\Stateless1Pkg\Config\Settings.xml --> 
3>InvalidOperationException: There is an error in XML document (4, 106). --> XmlException: '=' is an unexpected token. 
3>The expected token is ';'. Line 4, position 106.
```

Can you provide a clear set of repro steps, starting from a fresh project?

**Comment by SeanFeldman** [comment]
@mthalman-msft if that gives you an error and for me it was freezing VS, then we don't operate under the same setup. Providing you the a "clear set of repro steps" unfortunately not going to be any different from
1. Create a SF app with a statefull service
2. For the service, add a custom setting
3. For the setting, add a value that is not XML encoded properly
4. Run with F5, the project freezes
5. Start VS2015 and encode the value to have a valid XML value
6. Run with F5, project deployed and running.

**Comment by mthalman-msft** [comment]
@SeanFeldman: When you encounter this hang, try to wait for just over 3 minutes and see whether execution continues after that point.  That'd be valuable information for us in order to determine the cause.

Also, when you say that VS freezes, does that mean the UI is completely frozen?  Or what is the behavior that you are seeing?

**Comment by SeanFeldman** [comment]
UI was frozen to the point I had to kill VS and restart it.
I'll get back to you on the 3 mins wait next week.

**Comment by masnider** [comment]
Hey @SeanFeldman - any feedback or info that you can share? Is this still reproing for you?
