### ISSUE TITLE
Question - onpremise cluster Upgrade From 5.7 to 6.0

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#630]
Hi Team,
We dont have internet connectivity For automatic upgrade.
How can i upgade from 5.7 to 6.0 standalone cluster ?

Thanks,
Naresh

**Comment by Mardoxx** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server#upgrade-the-cluster-configuration
Under `Upgrade clusters that have no connectivity to download the latest code and configuration` > `Cluster upgrade workflow`

Latest (6.0.219.9494) package URL can be found on Service Fabric blog, or here's the link for it https://download.microsoft.com/download/B/0/B/B0BCCAC5-65AA-4BE3-AB13-D5FF5890F4B5/6.0.219.9494/MicrosoftAzureServiceFabric.6.0.219.9494.cab
