### ISSUE TITLE
Question - is it possible to preappend reverse proxy url ?

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#631]
Hi Team,
Is it possible to preappend something to RP URL?

Currenlty it listen to http://ipaddress:19082/appname/servicename.

Is it possible to preappend something like
Http://ipaddeess:19082/sf/appname/servicename ?

Thanks,
Naresh

**Comment by mkosieradzki** [comment]
@nareshkhatri81 AFAIK today the best you can do is to name your application fabric:/sf/appname .
