### ISSUE TITLE
Diagnostic Events Tab no longer loads with default listeners

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#632]
can we please add in the default listeners back into the Diagnostic Events tab for debugging?

it would be great if you could also add the service under debug by default please.

**Comment by karolz-ms** [comment]
@ConX-Ryan what version of SF tools are you using?

**Comment by ConX-Ryan** [comment]
VS2017
SF SDK 2.8.232

**Comment by karolz-ms** [comment]
I chatted with @BinWuMSFT and looks like the fix for this issue is in the pipeline, but hasn't been released yet. ETA early December

**Comment by ConX-Ryan** [comment]
Thanks Team keep up the good work

**Comment by ericcox** [comment]
Any updates?  It's now early January.  :^)

I'm using VS2017 v15.5.3, SF 6.0.232.9494, and SF SDK v2.8.232.9494 and still see the problem. I can give you a repro if you need it.

**Comment by BinWuMSFT** [comment]
Hi,

We will do a release this week and it will be 15.5.4. I will keep you updated when it is available.

Thank you!

Best,

Bin

**Comment by ConX-Ryan** [comment]
This has been left out of 15.5.4 it seems 👎

**Comment by ConX-Ryan** [comment]
Can anyone give me an update on the release plan for this fix? 

debugging is important to me because my code often doesn't work first time it compiles :(

**Comment by ericcox** [comment]
I've taken to just leaving a text file in my solution with all of the provider names. It just means I have to copy/paste the providers into the Diagnostic Events window each time I debug. It's not too painful.

**Comment by ConX-Ryan** [comment]
can you share the default list please i might have to adopt the same strategy might be a while before next release cycle

**Comment by ConX-Ryan** [comment]
Working in VS 15.5.6

Thanks Team keep up the good work!
