### ISSUE TITLE
Question - how can i access App/services which are versioned by reverse proxy ?

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#633]
Hello Team,

Consider i deployed app named sf version 1.0 with 3 service inside it having version 1.0

Http://ipaddress:19082/App/service1
Suppose now i deployed version 2 of this app sf and 3 services which are having 2.0.

Now how can i access version 2 of this app via reverse proxy.

We would like to test green blue deployment with service fabric vai reverse proxy.

Once we validate version 2 of this app, we will upgrade version 1 to 2.

Thanks,
Naresh

**Comment by nareshkhatri81** [comment]
I guess we need to deploy version 2 with sf

**Comment by nareshkhatri81** [comment]
Closed by mistake.
Do we need to deploy version 2 of app which would be having different appname and once we are done with validating via reverse proxy like
Http://ipaddress:19082/sfv2/

And then upgrade version 1 to version 2.

Is there any other way to do this ?

**Comment by mkosieradzki** [comment]
There are two main approaches to this problem:
1. Make your app compatible, implement health checks, use rolling upgrades.
2. Run two apps and make swap after upgrade

There are also multiple hybrid and advanced approaches (manual checking etc)

If you are using 1 approach you have one application, you perform rolling upgrade of your application. Health checks should help making sure that app is OK. So long story short checking if everything is OK is done by Service Fabric. During rolling upgrade some services are run in version 1 and some in version 2, your app should be widely compatible between versions 1 and 2. This might be challenging during larger changes... but it is feasible for most scenarios. Earlier you should test this upgrade in testing environment. However if something fails during upgrade according to rolling upgrade settings upgrade can be automatically rolled back by SF.

If you are using second approach you just name second app version differently and it is accessible under the new name. For practical reasons this kind of upgrade is only feasible for stateless services and is non-sense for stateful services.

Now to answer directly your questions:
> Now how can i access version 2 of this app via reverse proxy.

Exactly under the name you have deployed your application, so for example:
Http://ipaddress:19082/Appv2/service1

This is approach 2.

But if you want to do rolling upgrade (approach 1) just see:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade

**Comment by nareshkhatri81** [comment]
With approach 2 where we have 2 apps running in cluster with version 1 and 2.
Once V2 is validated.
We have to do rolling upgarded of v1 to v2.
There is no concept of swap in SF?

**Comment by mkosieradzki** [comment]
Yup, if you need to do the swap, you need to do this on some kind of external proxy/load balancer,

This is mostly because SF has no proper internet facing. SF Reverse Proxy is intended to provide convenient connectivity between services - not to expose services to the internet.

**Comment by masnider** [comment]
@nareshkhatri81 : @mkosieradzki has it right. You'd end up with two different application instances and hence two different names, and then some sort of additional balancer that would roll traffic targeting from one of those names to another.
