### ISSUE TITLE
InvalidDataException: Failed to copy 124 items while copying ...

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#636]
When trying to upload image from inside of the service fabric cluster
client.ApplicationManager.CopyApplicationPackage behaves very strange.

I can easily upload one app package, but when I try to upload the second one I am experiencing very slow copy-speed (During first one it is super-fast) and it breaks down with InvalidDataException.

Is this a known issue? Is there something wrong with my package? What kind of issues should I look for?

If this is an unknown issue I will try to prepare a repro.

I am working on DevCluster, version 6.0.219.

I looked into C:\SfDevCluster\Data\ImageStoreShare\<MyAppTypeName>_<MyAppVersion>.new 
and I am observing that it has problems with files with names like:
1e547be6e9d48af9a306fcae8e0f37c8.gif

but also with some other files.

I can successfully upload very same app package to a normal (non-dev) cluster with fabric:ImageStore, maybe I am hitting some limitations of file-share based image store?

**Comment by oanapl** [comment]
@mkosieradzki , this is not a known issue, a repro would be great. The expanded exception message would also be a great start.

To recap: 
- Local cluster uses the fileshare based image store
- CopyApplicationPackage for package 1 is fast
- CopyApplicationPackage for package 2 is slow and eventually fails with InvalidDataException

Are the 2 packages similar - do they contain the same file types? 

While copy is in progress, have you verified that no other process writes to the source package path (eg. another build writes to the same directory, corrupting the package)?

Do you have any antivirus on the machine that would scan some files and not others? And if you have an antivirus software, can you exclude the folders involved in copy to see if that affects the copy operation?

**Comment by mkosieradzki** [comment]
@oanapl in that case I will try to isolate factors important for the repro.

Where can I send binaries/source code if I don't want to do this publicly?

**Comment by oanapl** [comment]
oanapl at microsoft.com

**Comment by mkosieradzki** [comment]
@oanapl I have tried to isolate the issue, but I am unable, however I found what **might** be the cause.

My observation is that filesystem inside `C:\SfDevCluster\Data\_App\_Node_0\<appname>\<code package name>` has a bit strange semantics. I have not investigated it yet, but I am experiencing multiple strange effects right there.

My mistake was that I was writing to the current code package folder instead of work or temp folder.

The issue I was experiencing was happening when I was trying to install an app that was extracted to one of code package folder subfolders. After switching to work folder the issue disappeared, at least for now.

**Comment by oanapl** [comment]
Can you paste the command you run to copy the application package? What was the command for the first package (that succeeded) and the second one (that failed)? I assume you specified ApplicationPackagePathInImageStore - what value did you give it? It should be a relative location in the image store, eg. "MyAppFolder".
I am trying to determine how you did this: "I was writing to the current code package folder instead of work or temp folder."

**Comment by mkosieradzki** [comment]
@oanapl 
I need to do some explanations here:

I have multiple applications let's call them AppA, AppB, AppC.... I have recently create new Application called ManagementApp. This App is a Stateful Services and it downloads AppA, AppB, AppC from external repo, extracts them to local path: `packages/AppA_<Version>` then using Service Fabric C# management API tries to upload all the applications, register them and provision applications and services in the cluster.

After changing extraction path from `packages/AppA_<Version>` (I had WorkingDirectory set to CodePackage in ServiceManifest.xml) to a fully qualified path pointing to `Path.Combine(Context.CodePackageActivationContext.WorkDirectory, "packages/AppA_<Version>")` everything started to work correctly.

The reason why I was using local paths instead of app's WorkDirectory  was historical: that app is a direct port from a command-line utility I was using before.

The original failure consistently happened:
- on multiple different machines (all dev clusters)
- despite resetting cluster
- without deploying the first app

ApplicationPackagePathInImageStore: `BasicProjectManagementAppType_8.1.1-ci.2490` - but it is definitely not the problem only with this name, because after switching to `WorkDirectory` everything works fine and also app with a very similar name: `AuthAppType_8.1.1-ci.2490` was deploying just fine.

Another strange observation. When I tried to extract a zip file to the CodePackage subfolder extraction failed after extracting first file with message that it is unable to find path. Maybe there is something wrong with some kind of junctions/links, reparse points (didn't find one), filter driver, fs permissions or some SF process actively monitoring Code Package folders?

Regarding antivirus software: I have only Windows Defender.

**Comment by oanapl** [comment]
@harahma for the code package related question.

How do you ensure that AppA, AppB, etc are only downloaded / uploaded once? Is your stateful service singleton (just one partition)? Do you have one or multiple services of the same service type running in the cluster?

We are trying to determine whether you have multiple replicas belonging to different partitions of the same service type hosted in the same host process.

**Comment by mkosieradzki** [comment]
ManagementService_PartitionCount was set to 1. But you are right I should have switched this to a singleton just to make sure. I forgot that Singleton is not the default.

**Comment by harahma** [comment]
@mkosieradzki partition count 1 is equivalent to singleton partition. Could you please share a repro for this? You can email the zipped files to me at harahma[at]microsoft[dot]com.

**Comment by mkosieradzki** [comment]
@harahma I can't promise, because this one is not blocking me after using proper workdir, I have already spent significant amount of time on isolation attempts and failed.

**Comment by harahma** [comment]
@mkosieradzki no problem. I am marking this issue as closed for now. If you happen to have a repro in future feel free to re-open this one of create a new issue.
