### ISSUE TITLE
Runtime cannot be installed in a docker container + hang bug if FabricSetup.exe can't install driver

### ISSUE THREAD

**Issue by LiamLeane** [Azure/service-fabric-issues#637]
We run our builds in a docker container which obviously presents a problem as fabric runtime is a requirement to install the SDK and the runtime installs a driver. Setup itself just hangs forever without any obvious error until you run FabricSetup directly;

`
FabricSetup.exe invoked with arguments (C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricSetup.exe /operation:install). Current Exe version 6.0.219.9494
Environment information Data Root C:\ProgramData\Microsoft Service Fabric, Log Root C:\ProgramData\Microsoft Service Fabric\log
Starting service eventlog
Starting service pla
Starting UserGroupManager::Install
UserGroupManager::Install successful
Starting VCRedistManager::Install
VC++ is already installed; returning success.
VCRedistManager::Install successful
Starting RegistryManager::Install
Creating the registry key Software\Microsoft\Service Fabric
Setting the ACLs for the registry key Software\Microsoft\Service Fabric
lockFileName:Service Fabric.lock
Obtained exclusive file Service Fabric.lock
Released exclusive file Service Fabric.lock
Creating the registry key SYSTEM\CurrentControlSet\Services\ESE\Performance
RegistryManager::Install successful
Starting FolderACLManager::Install
Obtained exclusive file C:\ProgramData\Microsoft Service Fabric\daclupdate.lock
Released exclusive file C:\ProgramData\Microsoft Service Fabric\daclupdate.lock
Obtained exclusive file C:\ProgramData\Microsoft Service Fabric\log\daclupdate.lock
Released exclusive file C:\ProgramData\Microsoft Service Fabric\log\daclupdate.lock
FolderACLManager::Install successful
Starting EnvironmentManager::Install
EnvironmentManager::Install successful
Starting EventTraceInstaller::Install
EventTraceInstaller::Install successful
Starting CrashDumps::Install
CrashDumps::Install successful
Starting EventLogManager::Install
CreateProcess Successful for CommandLine:wevtutil um "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-Events.man". ProcessId:1108 MainThreadId:7708 ProcessHandle:1d4
CreateProcess Successful for CommandLine:wevtutil im "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-Events.man" /rf:"C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\FabricResources.dll" /mf:"C:\Program Files\Mic
rosoft Service Fabric\bin\Fabric\Fabric.Code\FabricResources.dll". ProcessId:4888 MainThreadId:7976 ProcessHandle:1d0
CreateProcess Successful for CommandLine:wevtutil um "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-LeaseEvents.man". ProcessId:1324 MainThreadId:8232 ProcessHandle:1d4
CreateProcess Successful for CommandLine:wevtutil im "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-LeaseEvents.man" /rf:"C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\leaslayr.sys" /mf:"C:\Program Files\Micro
soft Service Fabric\bin\Fabric\Fabric.Code\leaslayr.sys". ProcessId:7852 MainThreadId:988 ProcessHandle:1bc
CreateProcess Successful for CommandLine:wevtutil um "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-KtlEvents.man". ProcessId:4396 MainThreadId:7428 ProcessHandle:170
CreateProcess Successful for CommandLine:wevtutil im "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft-ServiceFabric-KtlEvents.man" /rf:"C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\KtlEvents.dll" /mf:"C:\Program Files\Micros
oft Service Fabric\bin\Fabric\Fabric.Code\KtlEvents.dll". ProcessId:9060 MainThreadId:7144 ProcessHandle:1bc
EventLogManager::Install successful
Starting GACManager::Install
Removing System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.dll to gac
Removing Policy.1.0.System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.1.0.System.Fabric.dll to gac
Removing Policy.2.0.System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.2.0.System.Fabric.dll to gac
Removing Policy.3.0.System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.3.0.System.Fabric.dll to gac
Removing Policy.4.0.System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.4.0.System.Fabric.dll to gac
Removing Policy.5.0.System.Fabric from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.5.0.System.Fabric.dll to gac
Removing System.Fabric.Strings from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.Strings.dll to gac
Removing System.Fabric.Dca.Validator from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.Dca.Validator.dll to gac
Removing DcaStandardPluginValidator from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\DcaStandardPluginValidator.dll to gac
Removing System.Fabric.dSTSClient from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.dSTSClient.dll to gac
Removing Microsoft.ServiceFabric.Data.Interfaces from gac
Adding C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft.ServiceFabric.Data.Interfaces.dll to gac
GACManager::Install successful
Starting DriverInstallManager::Install
Uninstalling Driver: LeasLayr.
Stopping Driver: LeasLayr.
Driver stop exited with permissible errorcode 0x80070424.
Installing Driver: LeasLayr from C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\LeasLayr.sys.
Driver uninstall timed out. This may have downstream impact.
`
I was ultimately able to work around this by installing the registry keys from my desktop machine and manually doing most of the other commands it tries to do, after that point I can successfully install and build with the SDK.

Suggestions;

- Fix this bug
- Offer a runtime installer option to not install items like the driver when we are just installing the runtime to enable build support
- Offer real build tools support, I am sure Microsoft don't have VS17 installed on build servers to enable Fabric builds. If you dont want to invest time in to an installer offering documentation of how to configure a build server appropriately for Fabric would be nice.

**Comment by lurock** [comment]
I am trying to do the same thing and running into the same issue.  @LiamLeane  can you post how you are working around getting this working or maybe just post your docker file.  Thanks.

**Comment by LiamLeane** [comment]
@lurock 

`
FROM stefanscherer/chocolatey

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Import-Module C:\\ProgramData\\Chocolatey\\helpers\\chocolateyInstaller.psm1;"]

RUN choco install -y vcredist2015 vcredist2010 dotnet4.5

ADD ServiceFabricRuntime.reg ServiceFabricRuntime.reg

ADD ServiceFabricRuntime.zip ServiceFabricRuntime.zip

RUN New-Item 'C:\Program Files\Microsoft Service Fabric' -type directory

RUN Add-Type -AssemblyName System.IO.Compression.FileSystem; \
	[System.IO.Compression.ZipFile]::ExtractToDirectory('ServiceFabricRuntime.zip', 'C:\Program Files\Microsoft Service Fabric')

RUN $assemblies = @('C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.1.0.System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.2.0.System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.3.0.System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.4.0.System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Policy.5.0.System.Fabric.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.Strings.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.Dca.Validator.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\DcaStandardPluginValidator.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\System.Fabric.dSTSClient.dll', \
					'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Microsoft.ServiceFabric.Data.Interfaces.dll'); \
	Add-Type -AssemblyName System.EnterpriseServices; \
	$publish = New-Object System.EnterpriseServices.Internal.Publish; \
	$assemblies | % {$publish.GacInstall($_)};

RUN Copy-Item 'C:\Program Files\Microsoft Service Fabric\bin\ServiceFabric' 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\' -Recurse
	
RUN regedit /s ServiceFabricRuntime.reg

RUN setx PATH "$env:path;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code" /m

RUN Install-ChocolateyPackage -PackageName 'ServiceFabricSDK' -FileType 'msi' -SilentArgs '/quiet /norestart /l* c:\fabricsdkinstall.log STARTUPTYPE=disabled IACCEPTEULA=yes' -Url 'https://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi' -ChecksumType 'sha256' -validExitCodes @(0) -Checksum '10E96BF85E25FD12657483B4D604CB3E11D49E3422E1D57F201F59792887D6DF'

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
`

ServiceFabricRuntime.reg is an export of HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric
ServiceFabricRuntime.zip contains everything in C:\Program Files\Microsoft Service Fabric

There is currently no way of using the fabric runtime installer without running setup (no arguments to do so I have found) which causes the freeze, I haven't yet found a handy way to extract the files from the runtime installer (as its not really an installer).

**Comment by rishirsinha** [comment]
Installation of SF inside windows containers is not supported as they do not allow installation of kernel drivers.
