### ISSUE TITLE
Generate Service Fabric package in MSBuild

### ISSUE THREAD

**Issue by kostrse** [Azure/service-fabric-issues#64]
`Microsoft.VisualStudio.Azure.Fabric.MSBuild` provides a build target _Package_.

Running MSBuild for a solution of projects (.sln) with target _Package_ leads to build errors because not all projects have the Package task defined.

```
MSB4057: The target "Package" does not exist in the project.
```

Running MSBuild for a Service Fabric project (.sfproj) with target _Package_ leads to build errors below because not all transient dependencies of Service Fabric services projects are especially x64 targets. In common case common libraries are defined as AnyCPU.

```
The OutputPath property is not set for project 'ClassLibrary1.csproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
```

What is the recommended build configuration for producing Service Fabric application package outside of Visual Studio?

[Similar question on StackOverflow](http://stackoverflow.com/questions/34079411/how-to-use-msbuild-on-the-sfproj)

**Comment by johnkattenhorn** [comment]
This is what I do:

```
nuget restore 'C:\Repos\[SourceRepo]\[SolutionName].sln'

& 'C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe' 'C:\Repos\[SourceRepo]\[SolutionName].sln' /p:platform="x64" /p:configuration="Release"

Get-ChildItem -Path 'C:\Repos\[SourceRepo]\' -Filter "*.sfproj" -Recurse | ForEach-Object {
    $fullName = $_.FullName

Write-Host "Building Binaries $fullName"

Write-Host "Packaging Service Fabric Apps"

& 'C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe' "$fullName" /t:Package /p:platform="x64" /p:configuration="Release"

}
```

WARNING: My fails because of another dotnet core related problem which I'm just logging an issue about.

**Comment by MikkelHegn** [comment]
We require the target to be "x64".

See here: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-add-a-web-frontend/

> Note that the class library project, MyStatefulService.Interface, is configured to build for Any CPU. To work correctly with Service Fabric, it must be explicitly targeted at x64. Click the Platform dropdown and choose New, then create an x64 platform configuration.

**Comment by lanfeust69** [comment]
Our solution (pun totally intended) is to use the `after.<SolutionName>.sln.targets` feature :
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build"
         xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- This file will be included when tranforming MySln.sln into an MSBuild -->
  <!-- project (MySln.sln.metaproj if emitted), so that we can call the      -->
  <!-- "Package" target of the sfproj.                                       -->
  <!-- Note that trying to build directly the sfproj fails because mapping   -->
  <!-- of project configuration AnyCPU vs x64 is not done.                   -->
  <Target Name="Package">
    <MSBuild Condition="$([System.String]::Copy('%(ProjectReference.Identity)').EndsWith('sfproj'))"
             Projects="@(ProjectReference)" Targets="Package" BuildInParallel="True"
             ToolsVersion="$(ProjectToolsVersion)"
             Properties="Configuration=Debug; Platform=x64;BuildingSolutionFile=true; CurrentSolutionConfigurationContents=$(CurrentSolutionConfigurationContents); SolutionDir=$(SolutionDir); SolutionExt=$(SolutionExt); SolutionFileName=$(SolutionFileName); SolutionName=$(SolutionName); SolutionPath=$(SolutionPath)"
    />
  </Target>
</Project>
```

**Comment by Remy-Burney-Powerfront** [comment]
I had this issue after I upgraded the package Microsoft.VisualStudio.Azure.Fabric.MSBuild to a new version, like 1.6.0
In theory nuget will do a good job, but what nuget does not do is updating the csproj file to reflect the version change.
I fixed this issue by editing the actual csproj file and changing the path and references to MSBuild package from 1.5.0 to 1.6.0

`  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" /> `

the error from Visual Studio is very missleading as it's really a reference issue to the package folder.

Hope this will help others.

**Comment by Jose-CF** [comment]
Ok, might I ask, WHY does it has to be x64? Isn't AnyCPU target a superset including x64? I am puzzled by that. 

I must add something: It would be extremely valuable if in the error message of ServiceFabric you give a warning/error or anything you wish that points a bit in the direction of the real problem.

Or much better support AnyCPU :)

If you look at StackOverflow you would be atonished how many people experiencing this issue.

Just my two cents.

**Comment by anandvadul** [comment]
June 28, 2017
This issue got me for an entire day :( 
Would like to echo @Jose-CF 's feelings. Can the 'Any CPU' build be made available please?

**Comment by MikkelHegn** [comment]
We are currently investigating to fix this issue for msbuild.

**Comment by shabanovanton** [comment]
Hi,

Any updates on this side?

**Comment by dbreshears** [comment]
I'm following up internally on the AnyCPU issue with MSBuild.

Another workaround I discovered as an alternative to adding the x64 build configurations to the ClassLibrary project is to pass the following parameter to MSBuild when calling the package target  on the .sfproj

/p:ShouldUnsetParentConfigurationAndPlatform=true

**Comment by Jose-CF** [comment]
Just out of curiosity. Why MUST the assemblies be x64? Dudes if someone can answer me that it would make my day.
If the assemblies are built AnyCPU, shouldn't that also include x64?!?!

**Comment by aL3891** [comment]
The reason is that they have native dependencies that are x64, they _can_ be AnyCpu, but in that case you have to make sure that they are actually run as x64. Msbuild doesn't automatically do this, but you can get around it by changing the targets to always run x64, or building as x64 explicitly

**Comment by rokobasilisk** [comment]
@MikkelHegn has there been any update on this?

**Comment by anandvadul** [comment]
@aL3891 I have typically followed the open assemblies (as in assemblies set to any CPU) and closed executables (EXE set to specific platform like x64) path. Got stumped when this did not work in SF Package.
