### ISSUE TITLE
Could not load file or assembly 'System.Fabric.Management'

### ISSUE THREAD

**Issue by PepijnGramberg** [Azure/service-fabric-issues#640]
Using Visual studio 15.4.4
Using 3.0.232-preview/6.1.232-preview

We want to connect to a Service Fabric cluster to manage our applications from a C# manager.
With the new preview packages we want to switch our project to netstandard/netcore. (using runtimeidentifier win7-x64)

This resulted in an error on one of our first operations which is removing an applicationpackage.
`fabricClient.ApplicationManager.RemoveApplicationPackage(imageStoreConnectionString, applicationTypeName);`

It gives the following exception
`Could not load file or assembly 'System.Fabric.Management, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`

The System.Fabric.dll and System.Fabric.Management.ServiceModel.dll are located in the folder as expected.

**Comment by ashishnegi** [comment]
@PepijnGramberg Can you share SF runtime version, Env like Linux or windows machine.

**Comment by raunakpandya** [comment]
Tracking this as part of issue #638 .. Closing this issue as duplicate. 
@PepijnGramberg  Do still share your environment details..

**Comment by PepijnGramberg** [comment]
Tried both on windows server 2012 r2 and developer machine windows 10
2.8.232 SDK is installed on both machines.
Tried platform agnostic and with runtimeIdentifier win7-x64

Using Visual studio 15.4.4 (with preview tools installed for netcore SF)
Using 3.0.232-preview/6.1.232-preview nuget packages
If more specific details are required, just ask.

**Comment by raunakpandya** [comment]
Thank you.. Nothing more at the moment.
