### ISSUE TITLE
Using a custom Service Fabric configuration provider with ASP.NET Core

### ISSUE THREAD

**Issue by spottedmahn** [Azure/service-fabric-issues#641]
Just read a [great article](https://blogs.msdn.microsoft.com/azurecat/2017/04/06/using-a-custom-service-fabric-configuration-provider-with-asp-net-core/) on how to:

> expose Service Fabric configuration settings to ASP.NET Core, using the ASP.NET Core configuration API.

Are there any plans to create make this a first-class citizen?  Like a nuget package maybe?

Reference: [Nuget package issue on sample prj](https://github.com/MikeWasson/ServiceFabric-AspNetCore-Sample/issues/1)

**Comment by Mardoxx** [comment]
https://github.com/Azure/service-fabric-aspnetcore/issues/9

**Comment by spottedmahn** [comment]
Thanks @Mardoxx !
