### ISSUE TITLE
sfctl Compose deployment - Application Type it shows as Compose_0

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#647]
Hi Team,

i used below command to do deployment and providing these arguments.

sfctl compose create --deployment-name sf --file-path D:\ProjectsV1\sf-docker-compose.yml

In service fabric explorer i am seeing Application type as Compose_0. how can i pass user friendly application type.
earlier with 5.7 Runtime, it used to display something based on application- id

Thanks,
Naresh Khatri

**Comment by linggengmsft** [comment]
@nareshkhatri81 , application type is generated in cluster side, so you couldn't "pass" or "specify" it. The reason is in compose deployment, you wouldn't need to provide application package, so you needn't worry about application type.

**Comment by nareshkhatri81** [comment]
Application type is good way to isolate, segragate apps in cluster.  Meaningful name is preferable to locate.

**Comment by linggengmsft** [comment]
@nareshkhatri81 compose deployment is a single instance deployment which actually doesn't need a "type" anymore. The fact application type being there is only because that's the existing way how Service Fabric modeling applications.
If you need a way to isolate applications for compose, there is a field called ApplicationDefinitionKind which you could filter while querying or on the query return. That would be the best way to isolate applications created by compose deployment.

**Comment by nareshkhatri81** [comment]
I guess it shud be consistent with other app types whrather its compose or other deploment.
Earlier with 5.7, it used to derive from appname. So assume with 6.0 with new sfctl sdk, it shud be same.
About different instance,  i was able to create diff instance of compose deployment from explorer.

**Comment by linggengmsft** [comment]
@nareshkhatri81, I think the confusion here is Service Fabric Explorer is showing compose deployments the same view as the Service Fabric applications. We are actually making a change to display compose deployments differently in the explorer and eventually they will not show under "application type".

For what you reported that being able to create instance from Service Fabric explorer, that is a bug we will fix. Thanks!

**Comment by nareshkhatri81** [comment]
Why do u think its bug?
I guess its good feature to spin up new instance without doing deployment.
I can deploy to dev, then spin up test by creating new instance and then prod.

**Comment by linggengmsft** [comment]
Thanks for the feedback, @nareshkhatri81 . This is not an intentional behavior, creating multiple instances from the same compose would cause DNS name conflict in v6.0 runtime.
Allowing creating applications without re-deployment is a valid point, and is some feature we are internally discussing.

**Comment by MikkelHegn** [comment]
@nareshkhatri81: To get to your scenario you can deploy your containers using application and service manifests. That will give you a real Application Type to instantiate in the cluster: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#create-the-containerized-service-in-visual-studio
