### ISSUE TITLE
FabricHost.exe, version: 6.0.219.9494 crashing onpremise

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#648]
Hi Team,

I am seeing this issue in one of my node in cluster.
is there way to troubleshoot ?

Faulting application name: FabricHost.exe, version: 6.0.219.9494, time stamp: 0x59dc1fe1
Faulting module name: FabricHost.exe, version: 6.0.219.9494, time stamp: 0x59dc1fe1
Exception code: 0xc0000602
Fault offset: 0x000000000003cd52
Faulting process id: 0x3b68
Faulting application start time: 0x01d35ed43f1b00a4
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\FabricHost.exe
Faulting module path: C:\Program Files\Microsoft Service Fabric\bin\FabricHost.exe
Faulting package full name: 
Faulting package-relative application ID: 

The Service Fabric Host Service service terminated unexpectedly.  It has done this 14 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.

Thanks,
Naresh

**Comment by maburlik** [comment]
Questions:
Is this happening after a cluster upgrade, or was the node running fine in this version for some time? What type of deployment is this? Is this created through the Azure portal or on-premise/standalone?
Are you aware of any recent changes on this node?
When this you discover this was crashing?

Can you discover any more details about the crash in the Windows event logs under Applications/System/Service Fabric logs? Please take a look and let us know.

Is the service coming up before crashing (i.e. entered Running state), or is it crashing right away?

You can also take a look at logs in the defined FabricLogRoot of your configuration. If you need help, please send us the logs.

**Comment by nareshkhatri81** [comment]
We recreated vm again.
Will reopen if issue occurs again.

**Comment by nareshkhatri81** [comment]
Hello Team,

@maburlik - we are again seeing some of process of service fabric is crashing.
i spoke with my manager and we can provide logs to MS to investigate for us.
Please let me know email address so i can send crash dumbs and logs files.

Thanks,
Naresh Khatri

**Comment by maburlik** [comment]
This has been stale for a while. If you are still hitting issues please send a mail to maburlik@microsoft.com.

**Comment by tugup** [comment]
To mitigate, you can set SkipDockerProcessManagement in Hosting section to true and ServiceFabric won't monitor the docker process. Please make sure once you set this to true that Docker service is running on the machine before you deploy the containers.
