### ISSUE TITLE
service fabric Deploy-FabricApplication.ps1 xml parse error

### ISSUE THREAD

**Issue by jk1510karti** [Azure/service-fabric-issues#649]
Hi, I am getting below error when publish the application. here is the PS output 

1>------ Build started: Project: Application8, Configuration: Debug x64 ------
2>------ Publish started: Project: Application8, Configuration: Debug x64 ------
2>Started executing script 'GetApplicationExistence'.
-------- Package started: Project: Application8, Configuration: Debug x64 ------
2>Finished executing script 'GetApplicationExistence'.
2>Time elapsed: 00:00:02.1380673
Application8 -> C:\Users\karthik.jaganathan\source\repos\Application8\Application8\pkg\Debug
-------- Package: Project: Application8 succeeded, Time elapsed: 00:00:19.3126482 --------
2>Started executing script 'Deploy-FabricApplication.ps1'.
2>. 'C:\Users\karthik.jaganathan\source\repos\Application8\Application8\Scripts\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'C:\Users\karthik.jaganathan\source\repos\Application8\Application8\pkg\Debug' -PublishProfileFile 'C:\Users\karthik.jaganathan\source\repos\Application8\Application8\PublishProfiles\Cloud.xml' -DeployOnly:$false -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'SameAppTypeAndVersion' -SkipPackageValidation:$false -ErrorAction Stop
2>Test-ServiceFabricApplicationPackage : Exception while parsing XML file: C:\Users\karthik.jaganathan\AppData\Local\Temp
2>\TestApplicationPackage_20292917112277\5f2rrjei.2jc\Debug\ApplicationManifest.xml
2>FileName: C:\Users\karthik.jaganathan\AppData\Local\Temp\TestApplicationPackage_20292917112277\5f2rrjei.2jc\Debug\Appli
2>cationManifest.xml
2>At C:\Program Files\Microsoft SDKs\Service 
2>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:131 char:38
2>+ ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse)
2>+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati 
2>   onException
2>    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
2> 
2>Finished executing script 'Deploy-FabricApplication.ps1'.
2>Time elapsed: 00:00:02.6048279
2>The PowerShell script failed to execute.
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by oanapl** [comment]
To get more info about the xml issue, please run the following in Powershell:
```powershell
Test-ServiceFabricApplicationPackage -ApplicationPackagePath  'C:\Users\karthik.jaganathan\source\repos\Application8\Application8\pkg\Debug'
```

**Comment by jk1510karti** [comment]
hi,

thanks for replying. I have remove Application8 from my projects. But I have created another application "mfsapplication" and that also having same problem.. When I ran the above powershell command (replacing new application path).. I get the following error.


PS C:\Windows\system32> Test-ServiceFabricApplicationPackage -ApplicationPackagePath  'C:\Users\karthik.jaganathan\source\repos\mysfapplication\mysfapplication\pkg\Debug'
False
Test-ServiceFabricApplicationPackage : Exception while parsing XML file: 
C:\Users\karthik.jaganathan\AppData\Local\Temp\TestApplicationPackage_20461887452842\gefd5jvw.ueh\Debug\ApplicationManifest.xml
FileName: 
C:\Users\karthik.jaganathan\AppData\Local\Temp\TestApplicationPackage_20461887452842\gefd5jvw.ueh\Debug\ApplicationManifest.xml
At line:1 char:1
+ Test-ServiceFabricApplicationPackage -ApplicationPackagePath  'C:\Use ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidationException
    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage

**Comment by oanapl** [comment]
ApplicationManifest.xml doesn't have expected format. How are you generating the package? Could you share the file?

This could be anything, but one case when I hit this was when the whitespaces in the xml were incorrect. For example, when the xml is processed somehow (use XmlDocument to load an existing app manifest, process it then write back without PreserveWhitespace set to true).

**Comment by oanapl** [comment]
@jk1510karti, were you able to figure out what is wrong with your ApplicationManifest.xml file? Have you checked the whitespaces? Is it a valid xml document?

**Comment by oanapl** [comment]
I haven't seen any updates lately. I will close the issue, feel free to re-open if you still have trouble with the application package.

**Comment by Rakesh201180** [comment]
Hi oanpl,


I am adding healthconfig in application manifest file and i a getting  parse error...after removing that tag its working fine .

  <Policies>
      <ContainerHostPolicies CodePackageRef="Code" Isolation="default">
        <RepositoryCredentials AccountName="#{ContainerRegistry_AccountName}" Password="#{ContainerRegistry_Password}" PasswordEncrypted="false"/>
        <NetworkConfig NetworkType="Open"/>
        **<HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true" RestartContainerOnUnhealthyDockerHealthStatus="false"/>**
      </ContainerHostPolicies>
      <ServicePackageResourceGovernancePolicy CpuCores="0.5"/>
      <ResourceGovernancePolicy CodePackageRef="Code" CpuShares="1024" MemoryReservationInMB="1024"  />
    </Policies>

**Comment by oanapl** [comment]
HealthConfig should not be inside ContainerHostPolicies, but a child of the Policies.
