### ISSUE TITLE
Ignore child element order in ApplicationManifest.xml schema

### ISSUE THREAD

**Issue by cwe1ss** [Azure/service-fabric-issues#65]
The current `ApplicationManifest.xml` schema enforces correct ordering of child elements. This means, the following file fails on deployment:

``` xml
<ApplicationManifest>
  <Parameters />
  <ServiceManifestImport />
  <Principals>
  <Certificates>
  <Policies /> <!-- Error: "Policies" must be between "Principals" and "Certificates" -->
</ApplicationManifest>
```

It seemed natural to me to describe the certificate before its usage in a policy so I wrote this section at the end. Unfortunately, it took me an hour to find and fix this problem.

I think, you should use `<xs:all />` instead of `<xs:sequence />` wherever possible in the schema definition.

I'd be happy to create a PR if it was open source. :D 😸 👯

**Comment by cwe1ss** [comment]
```
Test-ServiceFabricApplicationPackage : Exception while parsing XML file: C:\Users\c.weiss\AppData\Local\Temp\TestApplicationPackage_257591334264\4ufgroap.2x5\ApplicationPackage\ApplicationManifest.xml
FileName: C:\Users\c.weiss\AppData\Local\Temp\TestApplicationPackage_257591334264\4ufgroap.2x5\ApplicationPackage\ApplicationManifest.xml
In Zeile:1 Zeichen:1
+ Test-ServiceFabricApplicationPackage -ApplicationPackagePath .\C3.Per ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidationException
    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
```

**Comment by masnider** [comment]
We've filed and are tracking this as an improvement we could make. Thanks for the report!

**Comment by pixelicous** [comment]
Still no changes.. throws errors on order of tags..

**Comment by VipulM-MSFT** [comment]
We understand that this is an issue and it is frustrating. This is a limitation of our design and implementation dependencies on XSD. When a ‘sequence’ is converted to ‘all’, XSD generated code changes to ‘object[]’ which requires multiple changes in our deployment and validation framework .

As a workaround; open "C:\Program Files\Microsoft SDKs\Service Fabric\schemas\ServiceFabricServiceModel.xsd" in Visual Studio while authoring or modifying any of the Service Fabric manifests. This will allow you to check the order and provide intelli-sense, definitely it does not fully eliminate the problem.
