### ISSUE TITLE
AzureAD login problems to Service Fabric Linux Explorer

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#650]
I have configured AAD logon to Service Fabric Linux (6.0.127.1) exactly the same way as I have configured it for standard Service Fabric. Unfortunately Linux version asks for Client Certificate despite AAD is configured. Windows-based version asks for certificate only if it cannot logon with AAD.

I can successfully open Service Fabric Explorer on Linux by picking a random certificate (it is ignored and logon is made using AAD), however all requests to backend fail with messages like:
`Get applications failed (Client certificate required)`.

**Comment by xunlu** [comment]
AAD is not yet supported on Linux.
Mani, let's add this difference to our documentation.

**Comment by mkosieradzki** [comment]
@xunlu are you planning to fix this in a predictable tine, or is this something very difficult? Lack of AAD support requires a lot of changes in my security planning...

**Comment by linggengmsft** [comment]
@mkosieradzki, are you able to access this REST API? 
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getaadmetadata
Also, when you login on the explorer, does AAD page even show up or it asks for certificate immediately?

**Comment by mkosieradzki** [comment]
Ad1. I will need to check (it can take some time as I don't have access to my work PC now.
Ad2. It asks for the certificate immediately, then I pick any certificate (invalid) and explorer correctly shows my name from aad in the top right corner.

No AAD logon shows up at any point.

**Comment by linggengmsft** [comment]
Is it an Azure cluster or local cluster? Azure cluster has not enabled AAD yet, we are tracking this work item internally.

**Comment by mkosieradzki** [comment]
Azure Cluster

**Comment by mani-ramaswamy** [comment]
This has been fixed and Azure AD works with Linux clusters now. Please reopen the issue if you are hitting errors.
