### ISSUE TITLE
Please create example of SQL Server 2017 in containers in Servcie Fabric in HA

### ISSUE THREAD

**Issue by AceHack** [Azure/service-fabric-issues#651]
Please create a Service Fabric example of using SQL Server 2017 in containers in HA mode using Always on Avialabiity Groups with Naming service and/or other service fabric services as SQLs CLUSTER_TYPE EXTERNAL.  This would be an amazing use of combining Microsoft's technologies to really create an Amazing solution.  Also this would serve as a great example of how to get other database technologies working in a container in service fabric in a HA way.

Thanks.

**Comment by AceHack** [comment]
To be honest I do not believe this is possible 100% today using exiting service fabric runtime.  I think it would require enhancements which is the real reason I created this request so this scenaro could be thought about and make sure all the necessary features exist in service fabric to support this.

**Comment by mani-ramaswamy** [comment]
We're working on a volume driver that is built into the SF cluster that would replicate ....stay tuned

**Comment by AceHack** [comment]
I'm aware of the volume driver but I don't see how that would offer any help to solving this issue.  SQL server does it's own replication in HA mode and it's fast I'm sure much faster than replicating generic block storage.  I do not want to use a replicated volume driver in SF for this since SQL already has it's own.  I want to take full advantage of SQLs HA mode inside SF inside containers.

**Comment by mani-ramaswamy** [comment]
I see - got it, you want the SQL HA solution to run in SF. We'll look into creating a writeup.

**Comment by AceHack** [comment]
Also preferably this would use the docker compose syntax

**Comment by twright-msft** [comment]
@AceHack - Can you please clarify if you are looking for Windows-based containers or Linux-based containers or if you don't have a preference?

**Comment by AceHack** [comment]
Windows would be best, or Linux on windows when that is supported.  I would like to get several stateful open source projects running on service fabric that all have their own HA and persistence outside of service fabric so I'm just looking for some good examples and best practices, SQL server seems like a great fit since both are Microsoft projects.

Having a single place to manage all applications internal and 3rd party, view their health, move containers around when VMs go down, this is all very valuable even when the applications themselves don’t need the state management of service fabric.  One of the biggest benefit is ops agility and the ability to wrap up all prerequisites in a container for things like SQL server and then just deploy to service fabric.  This would make the installing and ops work an absolute breeze and reproducible.

Currently the product has many 3rd party dependencies and getting everything installed and configured on-prem is a mammoth effort that takes a week at minimum per customer even though I’ve written a ton of PowerShell Desired State Configuration (DSC) to automate a lot of the install process it is still not fully automated and requires a rather herculean effort given the amount of external dependencies and interconnections.  I’ve also had to give tons of training to other employees, so they would be able to successfully install the product as well, as it stands I’m still the only person who has been able to successfully stand up the product from scratch in a repeatable reproducible way.  I’m trying to simplify the process immensely, so I can get back to architecture and development instead of installing the product every time we get a new customer.

The project I'm working on relies heavily on SQL server and much of the machine learning in 2016 and somewhat 2017 (It's mostly R with a little Python at this point).  Most of the services for the project I'm working on are already using service fabric services and actors so having an easy way to deploy SQL using the same technology would be wonderful and be real convenient.  This project runs both in the cloud and on-prem but even in the cloud since SQL on-prem seems to get things like R and Python first I use SQL 2017 CU1 Enterprise.

Just an FYI some of the other projects I'm looking to get running in service fabric myself are Rabbit MQ, Kafka, etcd, consul, ZooKeeper, Solr, and Mongo DB.  I've already created windows docker containers for many of these and had varying success with nanoserver.  For example, I've only been able to get Rabbit MQ working with nanoserver insider edition docker images not RTM versions of nanoserver.

Much of the SF stuff I'm working on for running these stateful open source projects inside SF that have their own HA and persistence I've been given the go ahead from my company to allow me to open source the projects but with lack of any examples and best practices on how to do this in service fabric in a reliable way it's been almost a no starter.

We are currently heavily considering using AKS instead since Kubernetes would allow for running these containers on-prem in HA mode with their own persistence without much fuss.  We would likely use the upcoming version of docker swarm that has Kubernetes built in for on-prem deployments and AKS for cloud deployments.

I hope this helps understand what I'm looking for.

Thanks.

**Comment by AceHack** [comment]
Also, since I didn’t mention it before we are about 60% a .NET/JavaScript (TypeScript 😊) shop that has been migrating to .NET core.  About 20% of our codebase is C/C++ for our hardware/IoT side of things.  Most of the .NET project are C# with F# sprinkled in there where it makes sense.  We do have some projects that use other languages such as R, Python, Ruby, Elixir, Go, of course SQL/T-SQL, PL/SQL, PowerShell and a handful of others at a lesser extent.  So, you can see we have a nice mix of Microsoft and non-Microsoft 3rd parties we depend on.  It makes everyday real fun though when you never know what language you might have to code in today to fix a bug or add a feature and adds a whole new meaning to full stack.  What I’m really looking for is a pattern I can follow to wrap up all of these 3rd party services and our 1st party services into a single unified ops experience so I can stop spending so much time on the ops side of things and make the installs very automated and simple to hand off to others.  I REALLY want this to be service fabric since it’s such a great tool for our 1st party services already.  That’s why I asked for this SQL Server example because I’m hoping it will be a launchpad I can use to integrate all these other 3rd party services into a SF cluster.  Thanks.

**Comment by MedAnd** [comment]
@Haishi2016 has written a great & detailed post on something very similar [Setting up High available MySQL deployments on Service Fabric using containers and Docker Compose](http://haishibai.blogspot.com.au/2017/11/setting-up-high-available-mysql.html)

@mani-ramaswamy agree with @AceHack that more working examples of docker containers in SF are needed... any update on running Linux Docker containers in SF on Windows (1709)?

**Comment by mani-ramaswamy** [comment]
@MedAnd Thanks for the link, I would've given the same :). @AceHack  - let me know if that was sufficient.  BTW, we're still investigating and testing running of Linux containers on WIndows SF clusters. Adding @RajeetN.

**Comment by AceHack** [comment]
No I’m really looking for an official Microsoft SQL server HA best practices setup, 0 down time with failing nodes in service fabric.  This is my SQL, uses tons of work arounds, runs into SF bugs and not really fully HA in all of the services, not any VM could be lost and have 0 down time.  I appreciate the article but it’s not what I’m looking for.

**Comment by Haishi2016** [comment]
Hi @AceHack, would a managed service like Azure SQL Database work for you? What's the benefit you are seeking for to run SQL Server on the SF cluster? Is it for lifetime management and/or name discovery? What if we supported Open Service Broker API https://www.openservicebrokerapi.org/ that helps you to provision and bind to managed SQL Database instances when you deploy your application?

**Comment by AceHack** [comment]
On premises


Sent from Yahoo Mail for iPhone


On Monday, December 4, 2017, 9:15 PM, Haishi2016 <notifications@github.com> wrote:


Hi @AceHack, would a managed service like Azure SQL Database work for you? What's the benefit you are seeking for to run SQL Server on the SF cluster? Is it for lifetime management and/or name discovery? What if we supported Open Service Broker API https://www.openservicebrokerapi.org/ that helps you to provision and bind to managed SQL Database instances when you deploy your application?

**Comment by MedAnd** [comment]
Hi @Haishi2016 @mani-ramaswamy, some of my projects could really benefit from an industry standard way of deploying Linux Docker containers (HA clusters) on Windows... I created the following issue to capture the idea: https://github.com/Azure/service-fabric-issues/issues/666

**Comment by masnider** [comment]
Closing this issue down as there has not been discussion in some time. The sample/example pointed to by Haishi remains the best example of this.
