### ISSUE TITLE
Service Fabric Cluster Upgrade fails from 5.5.216.0 -> 6.0.219.9494

### ISSUE THREAD

**Issue by MattHartz** [Azure/service-fabric-issues#653]
This also occurs upgrading another cluster from 5.7.198.9494 as well.

**Comment by Mardoxx** [comment]
Any logs?

**Comment by MattHartz** [comment]
@Mardoxx Where can i view these logs? I only see the error message of "Cluster provisioning failed" and then when i click that it redirects me to "AzureDiagnosticsBlade" where I don't see any log information.

**Comment by Mardoxx** [comment]
Not sure how well integrated it is with azure, but I would rdp to one of your nodes where the upgrade failed and view service fabric logs in event viewer. They're relatiively descriptiv.

**Comment by MattHartz** [comment]
Okay, i'll look into that shortly.  I tried just now removing all existing applications and retried.  So if that fails, ill then rdp into one of them.  Thanks 👍

**Comment by masnider** [comment]
@MattHartz  any updates? You can also get-ServiceFabricClusterUpgrade and Get-ServiceFabricClusterHealth to see information on the upgrade.

**Comment by navyahmed** [comment]
@MattHartz - any update
 if you continue to experience this problem pls open a support ticket with Microsoft.
