### ISSUE TITLE
Generate Service Fabric Package Fails using MSBUILD

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/service-fabric-issues#66]
If I build our Service Fabric Applications using VS everything works fine, however if I try to build via the command line like:

```
nuget restore 'C:\Repos\[SourceRepo]\[SolutionName].sln'
dotnet restore
& 'C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe' 'C:\Repos\[SourceRepo]\[SolutionName].sln' /p:platform="x64" /p:configuration="Release"

Get-ChildItem -Path 'C:\Repos\[SourceRepo]\' -Filter "*.sfproj" -Recurse | ForEach-Object {
    $fullName = $_.FullName

Write-Host "Building Binaries $fullName"

Write-Host "Packaging Service Fabric Apps"

& 'C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe' "$fullName" /t:Package /p:platform="x64" /p:configuration="Release"

}
```

Or just try a single `.sfproj` that contains a dotnet core application then it fails with error like

```
"C:\repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway.App\MKopa.M2M.Gateway.App.sfproj" (Package target) (1) -
>
"C:\repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway2.Service\MKopa.M2M.Gateway2.Service.xproj" (default targ
et) (24) ->
(CoreCompile target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : Fa
iled to make the following project runnable: MKopa.M2M.Gateway2.Service (.NETFramework,Version=v4.5.2) reason: Illegal
characters in path. [C:\repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway2.Service\MKopa.M2M.Gateway2.Service.
xproj]
  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : Pa
rameter name: path [C:\repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway2.Service\MKopa.M2M.Gateway2.Service.x
proj]
```

We've tried moving projects, and researching the error from a core perspective, there seem like many potential issues for this (read-only attributes on files, app.config / web.config not required) but none the workaround has worked for us.

Creating a simple SF hosted Project works fine so its something to do with our project but we are stumped, spent about a week on this so far and stops us from implementing CI / CD.

**Comment by johnkattenhorn** [comment]
Any ideas how we could try to diagnose this fault ? We've tried MSBUILD verbose logging but it doesn't help reveal any more detail

**Comment by vturecek** [comment]
"Illegal characters in path."

This is a funny one. And not ha-ha funny unless you're completely losing your mind trying to solve it like I almost did recently.

Check your PATH environment variable. I'm not joking. Echo %PATH%. Look for paths wrapped in double-quotes, e.g., "C:\Program Files\Java". Double-quotes are illegal characters and will cause this error. If you're on Windows 10, then be wary of the new PATH editor UI: http://madebyknight.com/illegal-characters-path-problem-windows-10/

**Comment by johnkattenhorn** [comment]
So here's the output from `echo $env:Path`

```
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQ
L Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
 Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Too
ls\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windo
ws Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;
C:\Program Files\Git\cmd;C:\Program Files\Seq\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\M
icrosoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDK
s\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\
Tools\GitVersion;C:\Tools\NuGet;C:\Tools\AsmSpy;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
```

I've narrowed this down to this individual line from the SF Build 

`& 'C:\Program Files\dotnet\dotnet.exe' build 'C:\repos\M-KOPA M2MR2\src\MKopa.M2M.Gateway\MKopa.M2M.Gateway2.Service' --configuration Release --no-dependencies
`

This fails on PowerShell but works through Visual Studio. I still think you might be onto something @vturecek so I'm going to try a few things and will report back.

**Comment by masnider** [comment]
@johnkattenhorn - any followup here? Were you able to get this working?

**Comment by johnkattenhorn** [comment]
He @masnider - we moved all of our code back to full .NET as we couldn't solve it. We should try it again someday though.

**Comment by SeanFeldman** [comment]
Not being able to `dotnet` our solution has bitten me as well.
Fails on `dotnet restore` due to .sfproj incompatibility.

**Comment by dbreshears** [comment]
Closing this issue as it seems like this is fixed.  I am able to Msbuild using  /t:package on the .sfproj file that has  .Net Core services.     Please re-open with updated repro steps if still encountering the issue.
