### ISSUE TITLE
Documentation regarding development (Refresh) app packages

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-issues#660]
SF Visual Studo SDK currently uses some kind of mechanism to register a service package pointing to a local directory. How can I do such thing programmatically?

I would like to use my application or service (which uses SF SDK) to perform deployment of service fabric applications on the local cluster and I would like to limit usage of Visual Studio default mechanisms.

However I would like to be able to retain benefits like rapid refresh and ideally some to be able to make Visual Studio attach to all the process spawned for my services (even if those services are not deployed using VS). Is this possible somehow?

I don't feel like Visual Studio has any kind of support for advanced SF scenarios with applications deployed by other applications.

**Comment by MikkelHegn** [comment]
@dbreshears to help explain how this works in VS today.

**Comment by ravipal** [comment]
You should be able to make use of the refresh mode functionality when you deploy the application from your service. During application deployment, VS passes set of application parameters that controls the way how the application will be deployed to  Publish-NewServiceFabricApplication . In case of refresh mode, the application parameter will be as shown below. If CodePackageLinkFolder and ConfigPackageLinkFolder are not null, then the application deployment will create a symbolic link folder and reuse the bits in these folder.

-ApplicationParameter @{_WFDebugParams_='[{"CodePackageName":"Code","CodePackageLinkFolder":"c:\\users\\user1\\source\\repos\\Application6\\Stateless1\\bin\\x64\\Debug","ConfigPackageName":"Config","ConfigPackageLinkFolder":"c:\\users\\user1\\source\\repos\\Application6\\Stateless1\\PackageRoot\\Config","DataPackageName":null,"DataPackageLinkFolder":null,"LockFile":"c:\\users\\user1\\source\\repos\\Application6\\Stateless1\\bin\\x64\\Debug\\_VS_ServiceFabric_lock.txt","WorkingFolder":"c:\\users\\user1\\source\\repos\\Application6\\Stateless1","ServiceManifestName":"Stateless1Pkg","EntryPointType":"Main","DebugExePath":null,"DebugArguments":null,"DebugParametersFile":"c:\\users\\user1\\source\\repos\\Application6\\Stateless1\\bin\\x64\\Debug\\_VS_ServiceFabric_debug.txt"}]'} 

So in your custom deployment logic you could reuse such parameters to make use of refresh mode.

Please note the following restrictions and pre requisites to make use of this feature
1. Refresh mode is supported only on 1 node local cluster.
2. Once the application is deployed, the binaries are locked and being used and care should be taken when you try to update the binaries. The application should be stopped before updating the binaries.
3. The symbolic link target folder that holds the service assemblies need to grant execute permission to "Service Fabric Allowed Users"

**Comment by mkosieradzki** [comment]
@masnider @vturecek do you think some of those parameters might be helpful to do what we discussed during Q&A?

**Comment by mkosieradzki** [comment]
@ravipal Thanks a lot for your explanation here and in this thread: https://stackoverflow.com/questions/42827223/service-fabric-debugging-with-codepackagedebugparameters

I am trying to use all those information to create a convenient debugging experience for following scenario:
1. I have a management app type
2. I have multiple workload app types
3. management app uses SF API to deploy workload app types (from local package folders) and instantiate them
4. I am starting management app type in debugger
5. I would like to get debugger automatically attached to my workload app types.

Let's start without using the "refresh app" approach only simple debugging.

My idea was to get _WFDebugParams_ from management app instance and flow this parameter when instantiating workload app types. It contains the guid for a named pipe in VS so it should get the app connected, but it does not seem to work.

Please see following attached project it's very simplistic and the code is awful, but it is to show my point:
1. Open the project in VS 2017
2. Place breakpoint somewhere in Stateful2.cs
3. Right click on MyTestApp and do "package"
4. Right click on MyEntryPointApp and do "debug"

I would expect that when MyTestApp is deployed by MyEntryPointApp it should get the debugger attached using options from WFDebugParams, but apparently it does not :-( . But apparently debugger is not attached to the Stateful2.exe - I don't know why.

Any hints?
@masnider @vturecek - this is my attempt to do what we have discussed yesterday. Maybe you have some ideas?


[MyEntryPointApp.zip](https://github.com/Azure/service-fabric-issues/files/1646574/MyEntryPointApp.zip)

**Comment by mkosieradzki** [comment]
Got it working ;). Process Monitor helped me discover that VsDebugLaunchNotify.exe was not started, and then I have realized that I need to specify ServiceManifestName properly in _WFDebugParams_ :).

My understanding is that reusing guid generated for a single service can be safely reused for other services.

Looking at the `IVsDebugLaunchNotifyListenerFactory110.StartListener` I don't see any connection between generated GUID and Service/Application being debugged. So my assumption is that it should work and it worked :).

_WFDebugParams_ is my new favorite feature ;).
