### ISSUE TITLE
Add support for autopilot pattern in Docker containers

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#666]
Similar to work underway to integrate Lyft Envoy, consider supporting Autopilot Pattern or integration with Joyent Containerpilot for Docker containers. This is required for complex clusters of Docker containers.

- [Autopilot Pattern Applications](http://autopilotpattern.io/)
- [Autopilot Pattern - Docker container examples](https://github.com/autopilotpattern)
- [containerpilot](https://github.com/joyent/containerpilot)

**Comment by MedAnd** [comment]
Unofficial Service Fabric Golang API which could facilitate the above integration:

[Unofficial Service Fabric Golang API](https://github.com/jjcollinge/servicefabric)
[Træfik extra: Service Fabric Provider](https://github.com/containous/traefik-extra-service-fabric)

**Comment by masnider** [comment]
We have no plans to support this pattern at this time.

**Comment by MedAnd** [comment]
Agree... I raised this request over 2 years ago and so much has changed since 😁
