### ISSUE TITLE
Unable to deploy aspnetcore stateful service 

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#668]
Duplicate of [#40 in aspnetcore thread](https://github.com/Azure/service-fabric-aspnetcore/issues/40)
__
Dear team, what happens with statefull services - I cannot deploy none of them.
I've created sample projects for aspnetcore1.0, aspnetcore1.1 and aspnetcore 2.0 and none of them cannot be deployed seccessfully. At the same time stateless service works fine.

I've just created sample application from template "Stateful ASP.Net Core" with web api service targeted to aspnetcore1.1, update servicefabric packages to the latest versions an try to debug the service.
Exceptions:
`
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
`

Repository with sample you can [find here](https://github.com/mgrishkov/sf-statefull-web-api).
Here you can find [Build](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/build.log), [Debug](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/debug.log) and [Service Fabric Tools logs](https://github.com/mgrishkov/sf-statefull-web-api/blob/master/logs/service-fabric-tools.log).

I found issue #36 and it seems to be fixed, but I don't understand how to solve my issue. Does it connected somehow with my issue #627?

P.S. I've also tried to deploy standard net462 stateful service and connect to it via remoting, but I get the same COM exception.

System information:
```
Win10.
ServiceFabric local cluster: 6.0.232.9494
ServiceFabric SDK: 2.8.232.9494

```

**Comment by hrushib** [comment]
Completed investigation, the exception reported by @mgrishkov isn't root cause of this issue, this is a benign exception - #265. The real issue is **FileNotFoundException** for **System.IO.FileSystem.AccessControl**, see the exception details below. This is known issue - #639 and workaround exists for this. Add reference to **System.IO.FileSystem.AccessControl v4.4.0** Nuget package in **Web1** project and this should make your App working.

`Exception in OpenAsync.  Type: System.IO.FileNotFoundException Message: Could not load file or assembly 'System.IO.FileSystem.AccessControl, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. HResult: 0x80070002. Stack Trace:
	at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
	at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
	at System.Reflection.RuntimeMethodInfo.GetParameters()
	at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
	at System.Exception.GetStackTrace(Boolean needFileInfo)
	at Microsoft.ServiceFabric.Replicator.KtlLogManager.<CreateLogFileAsync>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.ServiceFabric.Replicator.LogManager.<OpenAsync>d__81.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.ServiceFabric.Replicator.LoggingReplicator.<OpenAsync>d__141.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.ServiceFabric.Replicator.LoggingReplicator.<OpenAsync>d__140.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OpenAsync>d__110.MoveNext().
`

Let me know if the workaround mentioned above works as expected on your end or not.

**Comment by mgrishkov** [comment]
@hrushib , thank you for your reply. Unfortunately workaround does not solve my issue. I updated sources for sample project in the [repo](https://github.com/mgrishkov/sf-statefull-web-api) and update [logs.](https://github.com/mgrishkov/sf-statefull-web-api/tree/master/logs)

Actual exception is:
`Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Fabric.dll
Exception thrown: 'System.Fabric.FabricTransientException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Fabric.FabricTransientException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Error collecting 4 of the configured performance counters. Please check the configuration.`

**Comment by hrushib** [comment]
@mgrishkov are you running Windows 10 with en-US or some other locale? You may run _Get-UICulture_ command in **PowerShell** to get this info.

**Comment by mgrishkov** [comment]
Win.10 russian locale. Pay attention please that the project use net462 as target framework and aspnetcore version is 1.1.2.

```
PS C:\Users\grishkov.mn> Get-UICulture
LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            Русский (Россия)
```

**Comment by hrushib** [comment]
I am able to run this app without any issue on system with dotnet 2.0.3 installed. Please check the dotnet version on your system and upgrade this to 2.0.3 if already not at 2.0.3. In case this doesn't work then try below workaround (as mentioned in #619 & #643)
`Put new ArgumentException(); on the first line of Main. This should cause the neutral resources to be cached, avoiding the failure.`

Let me know if this resolves issue on your end. If not, then I will investigate further to root cause the same.

**Comment by mgrishkov** [comment]
I already use detcore 2.03.
`
PS C:\Users\grishkov.mn> dotnet --version
2.0.3
`
I tried to update ASP Net Core packages up to 2.0.1  and put strange `new ArgumentException()` to the top of Main() in Program.cs (as you suggested) - **service is still dead**. But there is effect on exception message. It has been chaned to the folowing:
`
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
`

Is it possible to share with me any sample VS2017 solution that 100% healthy works on you machine? I'll check it on my.

**Comment by mgrishkov** [comment]
@hrushib can you please pay more attention for my issue due to it already has business impact due to I'm unable to implement important feature.

**Comment by hrushib** [comment]
@mgrishkov I am already looking at this issue and am sure that we can soon root cause this and get it working. Meanwhile, note that this is preview version of SDK and not supported for production scenarios. In case you are planning to release important feature to production then please use 6.0.232/2.8.232 versions of SDK packages instead of 6.1.232/3.0.232 and things should work fine.

Please share VS2017 version you are using to build this App.

**Comment by hrushib** [comment]
@mgrishkov pulled your changes and tried deploying those, service is not working. Issue is that Web1 project is referencing wrong version of System.IO.FileSystem.AccessControl, it needs to reference to System.IO.FileSystem.AccessControl version 4.4.0. See the git change below 

` -   <PackageReference Include="System.IO.FileSystem.AccessControl" Version="4.5.0-preview1-25914-04" />`
`+   <PackageReference Include="System.IO.FileSystem.AccessControl" Version="4.4.0" />`

Post above change, your app should work as expected.

**Comment by mgrishkov** [comment]
@hrushib  I update fs sdk to check whether it solve my issue #627  Package System.IO.FileSystem.AccessControl has been upgrated to the latest version today when I update aspnetcore to 2.0.1. Now I've downgraded packages and up to the one you recomended. Changes has been commited to the repo.

**Bad news:** I try to deploy and it is faild again. SDK 2.8.232.9494
**Good news:** I've asked for my collaegue to deploy the app and he was succeeded. SDK 2.8.219.9494

Conclusion: there is something wrong with my environment or with SDK 2.8.232.9494. I try to reinstall SF SDK and let you know whether it works or not.

**Comment by mgrishkov** [comment]
@hrushib it seems the problem with the latest sdk.
Install SDK 2.8.219 and the application working well.
Update SDK 2.8.232.... it fails. And again I've got `System.Runtime.InteropServices.COMException`.

Which version of SDK you've used to test my sample?

**Comment by hrushib** [comment]
@mgrishkov as mentioned in my earlier comment, if you just change package reference version for **System.IO.FileSystem.AccessControl** from **4.5.0-preview1-25914-04** to **4.4.0** in Web1.csproj file then your existing sample code should start running with the Service Fabric cluster setup using 2.8.232 installation.

Please do this change and let me know if this works as expected or not.

**Comment by mgrishkov** [comment]
I performed my tests with version 4.4.0.
And application failed after updating SDK up to 2.8.232 even for System.IO.FileSystem.AccessControl v. 4.4.0.

**Comment by hrushib** [comment]
@mgrishkov please repro this application failure in fresh cluster and share cluster logs which will help me investigate this further.

1. In case you already have local cluster setup then delete this cluster. You may use following step to do so - Right click on **Service Fabric Local Cluster Manager** icon  located in notification area of Windows task bar and click on Remove Local Cluster option to remove presently setup cluster.
 2. Recreate local 5 node cluster by using Setup Local cluster option of **Service Fabric Local Cluster Manager** 
3. Publish your App to local cluster created in step 2, then wait for approximately 10 minutes.
4. Share Service Fabric cluster trace **fabric_traces_*.etl** which is typically present at location **%systemdrive%\SfDevCluster\Log\Traces**.

**Comment by mgrishkov** [comment]
It very-very strange but after **switching cluster from 1 node mode to 5 node mode and back to 1 node** the application published and works successfully.
So it's all problem of my environment that has not been solved even by SDK reinstallation.  

In case when I faced with that problem again, I'll perform actions that you recommended, and attach traces to the new issue.

@hrushib  **thank you for support.**

**Comment by hrushib** [comment]
@mgrishkov - Good to know that you are able to get this application running.

Please note that preview Nuget packages are not supported for production scenario. For services targeted for production scenario, you need to use non-preview Service Fabric Nuget packages.
