### ISSUE TITLE
POA on premise -  Not Authorized to connect 

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#671]
Hi,

we followed the advice  #522  to install POA on premise and the setup goes through ok.
We used as SetupAdminUser :
`<User` Name="SetupAdminUser" AccountType="LocalSystem" />        

But it is not patching the VMs, the error we get is 

> 2017-11-23 10:18:32.888,Error,8972,3152,POA-NodeAgentSFUtility.ErrorMessage,NodeAgentSFUtility failed with exception : System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricConnectionDeniedException: Not authorized to connect ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C43

(similar issue is logged #353 )

I can see the suggestion

> "ClientIdentities": [
                                       {
"Identity": "NT AUTHORITY\\SYSTEM",
"IsAdmin": true
}
]

But can we configure that in an existing cluster with Windows security?
What permissions are needed to make it work?

kind regards
Yannis

**Comment by raunakpandya** [comment]
Yes, you can update existing cluster to update the clientidentities. You need to be cluster admin who has permission to trigger cluster config upgrade.

**Comment by dealboy** [comment]
Hi @raunakpandya 

I did the setup, and I do not get anymore errors in the event log or in SF logs!
But still, invoking 
`Invoke-WebRequest http://myhost.development.int:20001/PatchOrchestrationApplication/v1/GetWindowsUpdateResults`

returns 200 but without any results.
and the X:\PatchOrchestrationApplication\logs\PatchOrchestrationServiceTraces_XYZ.etl file has no useful info.

How can I check why I get no results?

**Comment by raunakpandya** [comment]
You should see results once update time is hit and some update happens. What is your configured update schedule or frequency?

**Comment by dealboy** [comment]
Hi @raunakpandya 
The update frequency I set is daily!  to be able to trace the progress of the process.

we deploy using: 
.\Deploy.ps1 -ApplicationParameters @{TaskApprovalPolicy ="UpgradeDomainWise"; WUQuery ="IsInstalled=0"; WUFrequency ="Daily,14:20:00";}

the deployment succeeds.

but then the we get the following events we that cannot understand 

In PatchOrchestrationService generated etl file: 
![image2017-12-22 2012_52_57](https://user-images.githubusercontent.com/1675899/34298511-7503c910-e71e-11e7-96ba-7c9822b6facb.png)

In Windows Event Log : 
![image2017-12-22 2012_59_50](https://user-images.githubusercontent.com/1675899/34298512-752950cc-e71e-11e7-84cc-74b5c2ca7e6a.png)

and inside the referenced file from Windows Event Log ( C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_10.0.14393.1794_7e272f438c97d62813f46db5eed1bf48196677ad_00000000_2a13ab70 )


> Version=1
> EventType=WindowsUpdateFailure3
> EventTime=131583403333233189
> Consent=1
> ReportIdentifier=bbadd3a5-e65b-11e7-9109-005056a338c9
> AppSessionGuid=000003c4-0000-002b-374f-e3931873d301
> TargetAppId=W:0000f519feec486de87ed73cb92d3cac802400000000!00000dac68816ae7c09efc24d11c27c3274dfd147dee!svchost.exe
> TargetAppVer=2016//07//16:02:25:32!d1ac!svchost.exe
> BootId=4294967295
> Response.type=4
> Sig[0].Name=ClientVersion
> Sig[0].Value=10.0.14393.1794
> Sig[1].Name=Win32HResult
> Sig[1].Value=8024002e
> Sig[2].Name=UpdateID
> Sig[2].Value=00000000-0000-0000-0000-000000000000
> Sig[3].Name=Scenario
> Sig[3].Value=Scan
> Sig[4].Name=RevisionID
> Sig[4].Value=0
> Sig[5].Name=IsManaged
> Sig[5].Value=0
> Sig[6].Name=LastError
> Sig[6].Value=0
> Sig[7].Name=CallerAppID
> Sig[7].Value=<<PROCESS>>: NodeAgentNTService.exe
> Sig[8].Name=ServiceUsed
> Sig[8].Value={9482F4B4-E343-43B6-B170-9A65BC822C77}
> Sig[9].Name=MiscField2
> Sig[9].Value=0
> DynamicSig[1].Name=OS Version
> DynamicSig[1].Value=10.0.14393.2.0.0.272.7
> DynamicSig[2].Name=Locale ID
> DynamicSig[2].Value=2057
> FriendlyEventName=Windows Update installation problem
> ConsentKey=WindowsUpdateFailure3
> AppName=Host Process for Windows Services
> AppPath=C:\Windows\System32\svchost.exe
> ReportDescription=A Windows update did not install properly. Sending the following information to Microsoft can help improve the software.
> ApplicationIdentity=00000000000000000000000000000000
> MetadataHash=1680105538



any ideas on the issue and what prevents POA updating our Win2016 OS?
(note that we have an internal WSUS server)

kind regards
Yannia

**Comment by novino** [comment]
Hey Yannia, could you attach the etl file on this thread or email it to nachandr@microsoft.com

Etl files containing eventsource events cannot be opened in windows event viewer as-is. I can view them and let you know what is going wrong.
I'm hoping you're able to patch your nodes using windows update UI at the moment.

PS: I would also recommend using the latest version of POA 1.2.0 (unrelated to the current issue at hand though).

**Comment by dealboy** [comment]
Hi @novino 
Could you please explain (or point me to a link) how can I also view the eventsource events? 
How should I open them? 

I will send you the the etl files as soon as I am back at office.

kind regards
Yannis
PS: We have deployed (and trying to use) the latest POA 1.2.0

**Comment by novino** [comment]
We use an internal tool to open such etl files, I've not come across any open source tool for same.

On latest supported/recommended SF versions these logs would be part of SF logs and POA logs won't be generated @ X:\PatchOrchestrationApplication\logs.
SF logs are archived csv files (.dtr.zip) which are relatively easy to open and view, If you're running SF version 5.6.220.9494 and above.

Will wait for the etl files meanwhile.

**Comment by novino** [comment]
Closing the issue as there is no response from @dealboy in a while
