### ISSUE TITLE
creation failed due to DNS name

### ISSUE THREAD

**Issue by mulugetan** [Azure/service-fabric-issues#673]
whenever i publish my services i encountered the creation failed due to DNS name errors for my services.

please assist me to resolve this.

sample messages below
Service fabric:/ETDCAPI/CheckinAPI creation failed due to DNS name checkinapi.etdcapi is in use.

**Comment by milvuko** [comment]
Hi @mulugetan,
I think you are hitting a bug described here:
https://github.com/Azure/service-fabric-issues/issues/422

The bug is fixed in the SF v6.1.

**Comment by milvuko** [comment]
Fixed in SF v6.1.
