### ISSUE TITLE
Service Fabric Configuration Upgrade fails

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#674]
Hi,

we tried to change the number of ephemeral ports on a 6.0.219 cluster on premise by using Start-ServiceFabricConfigurationUpgrade command. 
The first invocation of the command was accepted without errors, but failed immediately  (checking Get-ServiceFabricConifgurationUpgradeStatus) 

![image](https://user-images.githubusercontent.com/1675899/33285331-4051d358-d3b2-11e7-89e7-b40425e97622.png)

then we tried to execute a second time Start-ServiceFabricConfigurationUpgrade and we get : 

![image](https://user-images.githubusercontent.com/1675899/33285356-5aa431ec-d3b2-11e7-9b70-6f5b5c89e132.png)

We waited to see if somehow SF finishes the failed upgrade, but after 2 days the cluster is in the same condition. 
There are no obvious errors in the Event Log, nor in the diagnostic store.

Is there a way to bring the cluster in a healthy state?
Are there any specific messages we must check in logs or event log?

kind regards
Yannis

**Comment by Liphi** [comment]
Could u provide the json config files before and after the config upgrade? Please remove the sensitive info on them. thx.

**Comment by dealboy** [comment]
Hi 
the change was only on the ephemeralPorts
initial
"ephemeralPorts": {
	  "startPort": "20102",
          "endPort": "20402"
},

final
"ephemeralPorts": {
	  "startPort": "21002",
          "endPort": "21002"
},

We have 4 clusters, we applied the change to two of them and worked fine and the third and fourth failed as described above.

The goal is to recover the status and make cluster able to upgrade again. 
Are there any commands to resume or cancel upgrade ?
Maybe use Update-ServiceFabricNodeConfiguration  ?

kind regards
Yannis
[beforejson.txt](https://github.com/Azure/service-fabric-issues/files/1513724/beforejson.txt)
[afterjson.txt](https://github.com/Azure/service-fabric-issues/files/1513723/afterjson.txt)

**Comment by Liphi** [comment]
The json files look good. Need to take a look at trace logs and the output of Get-ServiceFabricClusterUpgradeOrchestrationServiceState. U may contact Microsoft support team to upload these info for further analysis by product team. Due to compliance concerns, please don't attach them in this thread.

**Comment by dealboy** [comment]
Get-ServiceFabricClusterUpgradeOrchestrationServiceState gives timeout

**Comment by dealboy** [comment]
opened a case, thanks
