### ISSUE TITLE
Question: Container and `<CertificateRef>`

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#675]
It seems `<CertificateRef>` only allows find certificate by thumbprint. So what happens when the certificate needs to be updated? E.g. when expired or leaked. Does it mean we have to update the service manifest and then rebuild/republish?

**Comment by rakshitatandon** [comment]
Yes, currently only FindByThumbprint is supported, so you will need to republish with a new service manifest. We are working on improving this experience for future releases.

**Comment by mani-ramaswamy** [comment]
And @qrli  you can pass multiple certificate ref. Thus, when the certificate is updated the apps can continue to work.

**Comment by mani-ramaswamy** [comment]
Closing this issue for now. Please reopen as appropriate.
