### ISSUE TITLE
Log configuration in fabricSettings - standalone clusters 

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#677]
Hi,

is there a way to configure (frequency, size, number) the log files under FabricLogRoot for on-premise standalone clusters?

In documentation for configuring [standalone clusters](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest) there is nothing,
but for [Clusters on Azure](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings)  I can see various options under the

> fabricSettings

like Diagnostics\MaxDiskQuotaInMB

My goal is to reduce (or eliminate) the Query Trace *.etl files generated on the VM disk and keep only the ones in pushed to diagnosticsStore disk .

kind regards
Yannis

**Comment by dealboy** [comment]
any news ?

**Comment by Sweiii** [comment]
I am also waiting on news.

**Comment by dealboy** [comment]
Hi,
did a cluster configuration upgrade, using the following config snippet, hopping it will work... they were accepted from the cluster, but still the Query Tace files (I thought that was the WinFabPerfCtrFolder ) not getting deleted.


 "FabricSettings": [
      {
..........
.........
      {
        "Name": "WinFabPerfCtrFolder",
        "Parameters": [
          {
            "Name": "DataDeletionAgeInDays",
            "Value": "2"
          }
        ]
      },
      {
        "Name": "WinFabEtlFile",
        "Parameters": [
          {
            "Name": "DataDeletionAgeInDays",
            "Value": "2"
          }
        ]
      }
    ],

**Comment by sdkadam2017** [comment]
what are the diagnostic parameters for where you find this -  <Parameter Name="WindowsFabricEtlType" Value="QueryEtl" />

**Comment by MattDarg** [comment]
I'd like to know this as well.  The actual DiagnosticsStore we have is set up to be a network share with plenty of space, but the local QueryTraces directory is still filling up and I can't seem to find the setting to control this...

**Comment by mattrowmsft** [comment]
How much space are you seeing used by the \Log folder?  What version are you on?  If you are seeing more than 10GB in that folder you are probably hitting a bug that we can work on mitigating/fixing instead of changing configuration.

**Comment by MattDarg** [comment]
It was up to 25GB or so with the vast majority of that in QueryTraces.  We're running version 6.0.232.9494.  Worth noting it had been fine in earlier releases.

Thanks, Matt.

**Comment by dealboy** [comment]
Hi @mattrowmsft , 

I see that this is categorized as a bug.  (our issue is also with QueryTraces folder)
Is there a workaround? 
Is there a plan when this will be fixed?

thanks
Yannis

**Comment by mattrowmsft** [comment]
We don't yet understand the issue but we have a few msft internal customers hitting the same issue now so we are using them to diagnose.  I'll report back here once we understand the issue better.

**Comment by mattrowmsft** [comment]
Update: We have the issue figured out.  We are working at getting a fix into the next release.  I'll publish a service which will apply workaround for now.

**Comment by mattrowmsft** [comment]
https://github.com/mattrowmsft/SF-FolderCleaner
I created a project with a workaround for now.  It just deletes the query folder periodically. We will have a fix going in for this as well, but I don't know its version number yet.

Some background:
When the original cluster manifests were written for stand alone, certain features were disabled for environments only leveraging file shares.  One of those is our diagnostic agent uploading certain events to Azure Storage tables.  This inadvertently disabled all management of the files being produced with those events.  This wasn't noticed previously because the number of events being generated was quite low.  Over time more SF components have been leveraging these type events with 6.0 seeing a significant increase.  This caused the files to grow quite large in this folder without DCA doing any management of the files.  Going forward we will change DCA to manage all folders no matter its configuration, to prevent these types of configuration mistakes.

**Comment by bnmaa** [comment]
Hi @mattrowmsft,
Will those `*.etl` under `Log\Traces` also be affected by this issue?
Recently we have a node whose disk space is full, it's flooded with `Log\Traces\*.etl`.

**Comment by dealboy** [comment]
my 2 cents: our ops people modified the cmd inside SF-FolderCleaner to support multiple dirs llike "L:\FabricLog\log\QueryTraces","l:\FabricLog\log\AppInstanceData\Etl","l:\FabricLog\log\CrashDumps","l:\FabricLog\log\ArchivedTraces","l:\FabricLog\log\Traces"

**Comment by Abdruggi** [comment]
We use a slightly different approach. We use env vars instead of hard coded folder path and retention period. Doing so, we are able to have different configurations for different environments.

**mainEntryPoint.bat**
```
powershell.exe -ExecutionPolicy Bypass -Command ".\mainEntryPoint.ps1"
```

**mainEntryPoint.ps1**

```
$Folder = $env:Folder
$RetentionPeriod = $env:RetentionPeriod
$SleepInterval = $env:SleepInterval

while(1)
{
	Get-ChildItem $Folder | ? { -not $_.PSIsContainer -and $_.LastWriteTime -lt (Get-Date).AddDays($RetentionPeriod) } | Remove-Item -Force
	Start-Sleep -seconds $SleepInterval
}
```

**Comment by Abdruggi** [comment]
@mattrowmsft is the fix included in the 6.1 release?

**Comment by mattrowmsft** [comment]
@Abdruggi  It isn't in the initial release of 6.1, but will come in a fauture 6.1.x release.

**Comment by mattrowmsft** [comment]
We have tested some additional configuration you can add to your SA cluster config to use as a workaround for now.

```
"fabricSettings": [
{
          "parameters": [
            {
              "name": "ProducerInstances",
              "value": "WinFabEtlFile, WinFabCrashDump, WinFabPerfCtrFolder, ServiceFabricEtlFileQueryable"
            }
          ],
          "name": "Diagnostics"
},
{
            "parameters": [
              {
                "name": "IsEnabled",
                "value": "true"
              },
              {
                "name": "ProducerType",
                "value": "EtlFileProducer"
              },

              {
                "name": "WindowsFabricEtlType",
                "value": "QueryEtl"
              }

            ],
            "name": "ServiceFabricEtlFileQueryable"
}
]
```

**Comment by dealboy** [comment]
hi @mattrowmsft , can you please explain a bit the logic of that configuration.

does ServiceFabricEtlFileQueryable allow DataDeletionAgeInDays ?
should I use isEnabled = false? (would then microsoft be able to support me? )

kind regards
Yannis

**Comment by mattrowmsft** [comment]
@dealboy  sorry I missed this.  This additional section governs the local retention policies for our QueryTraces.  It does support DataDeletionAgeInDays, but that only controls its local storage.  You should set isEnabled = true for this to mitigate the issue.  The fix will ensure these sections are enabled no matter the configuration.  I should have a build number / date for the fix soon.

**Comment by mattrowmsft** [comment]
6.1.467 is released now.

**Comment by ucgeek** [comment]
@mattrowmsft is this a issue in Fabric 5.5.226.0? I've installed Skype for Business 2019 and this is the version it uses. Every one of my pool nodes is accumulating massive amounts of ETL files in C:\ProgramData\Microsoft\SF\Log\Traces. At last check each node had consumed 60GB of data. Any ideas?

**Comment by eponerine** [comment]
I'm posting this here in case anyone else who uses **SDNv2 on Windows Server 2019** experiences this.

It appears that **Network Controller** runs **Service Fabric 6.0.240.9494**, at least based on the ETL filenames in the QueryTraces directory. That means even if you're shipping your NC logs to an SMB share, you're still gonna explode in storage consumption. And without direct access to Service Fabric to deploy applications, I think we're gonna need to script the cleanup ourselves:

![image](https://user-images.githubusercontent.com/503974/80006535-fe9cc500-8492-11ea-99a9-a8d7cc1af235.png)
