### ISSUE TITLE
Please support a VS connected cluster experience like K8

### ISSUE THREAD

**Issue by AceHack** [Azure/service-fabric-issues#684]
https://www.hanselman.com/blog/AnnouncingVisualStudioAndKubernetesVisualStudioConnectedEnvironment.aspx

This is an amazing feature that’s really needed for read production with a large number of micro services.

**Comment by AceHack** [comment]
This concept of spaces is a real must.  We have multiple dozens of microsoft services in service fabric and multiple teams.  Debugging the real application as a whole is very hard.  Something like this concept of spaces would be amazing.  Also I really want a little more advance scenario, like hierarchical spaces.  So we can have a shared cluster across multiple teams.  Each team can have it's own space that team member inherit but then also team memeber can have thier own space that inherits from the team space but also allows further indiviual overrides.  In a perfect would this would also apply to database and stateful service changes as well with maybe a copy on write pattern or something like that so I could test out schema changes as well.

Thanks.

**Comment by johnsta** [comment]
Hi AceHack, I'm on the VS Connected Environment team. Our immediate goal is to deliver an initial Kubernetes-based experience and learn how developers wish to use it. We do plan on adapting this to other platforms, including Service Fabric, although I don't have a timeline to share at this point. Regarding the spaces concept, we do plan on supporting the hierarchical approach you suggested - I agree that it has the potential to open up some really interesting use cases. Looking forward to your feedback when you try the preview!
