### ISSUE TITLE
VS for Mac not opening .sfproj file. How to build sf projects on Mac?

### ISSUE THREAD

**Issue by jackhawa** [Azure/service-fabric-issues#687]
Hello, after having setup a local docker container and having service fabric cluster running on it on my mac, I wanted to open my sfproj in Vs for Mac but it said that it doesn't support it. Am I missing something?

If VS for Mac doesn't indeed support it, is there a timeline when it will? And is there anyway I can develop a C# sf application on Mac?

Thank you.

**Comment by BigMorty** [comment]
Sorry, we currently don't have plans for SF project support in VS for Mac at this time. Feel free to start thread on http://visualstudio.uservoice.com.

Thanks,
Mike
