### ISSUE TITLE
Where can old versions of SDK be downloaded in order to uninstall it?

### ISSUE THREAD

**Issue by Igorbek** [Azure/service-fabric-issues#688]
I was trying to setup the latest SDK (2.8.232), but it turned out that I already had previously installed version of SDK (2.0.135). Somehow I have no original msi package of that version which results in being unable to uninstall older version.
I am not sure why Web Platform Installer cannot locate and download the package in order to uninstall, so it just fails with `Product: Microsoft Azure Service Fabric SDK -- Error 1714. The older version of Microsoft Azure Service Fabric SDK cannot be removed.  Contact your technical support group.  System Error 1612.`

My guess is that it will work if I can bring the old msi package back at the searched location. But where can I find it? I searched almost everywhere without any success.

### Details:
- Product to install: Microsoft Azure Service Fabric SDK 2.8.232
- Error: `Product: Microsoft Azure Service Fabric SDK -- Error 1714. The older version of Microsoft Azure Service Fabric SDK cannot be removed.  Contact your technical support group.  System Error 1612.`
- Old product that cannot be uninstalled: Microsoft Azure Service Fabric SDK 2.0.135

**Comment by vturecek** [comment]
Release notes should have links to direct downloads of the MSI installer. Those are posted on our blog at https://blogs.msdn.microsoft.com/azureservicefabric/

Here's 2.0.135 for you:
https://download.microsoft.com/download/7/5/E/75E350B7-EE54-4A10-9322-2E94772E9777/MicrosoftServiceFabric.5.0.135.9590.msi
https://download.microsoft.com/download/7/5/E/75E350B7-EE54-4A10-9322-2E94772E9777/MicrosoftServiceFabricSDK.2.0.135.msi
https://download.microsoft.com/download/7/5/E/75E350B7-EE54-4A10-9322-2E94772E9777/MicrosoftAzureServiceFabricTools.VS140.en-us.msi
