### ISSUE TITLE
StatefulService ctor doesn't check for null arguments

### ISSUE THREAD

**Issue by Ubiguchi** [Azure/service-fabric-issues#69]
Passing null ServiceContext or IReliableStateManagerReplica arguments to the base class throw NullReferenceExceptions rather than ArgumentNullExceptions.

It's been a while since I programmed, so shoot me down if practices have moved on, but it used to be consider bad programming practice not to validate and guard arguments against nulls as it can lead to a proliferation of, hard-to-track-down NullReferenceExceptions.

**Comment by vturecek** [comment]
Times haven't changed that much! Looking into it..

**Comment by vturecek** [comment]
Moved to Azure/service-fabric-services-and-actors-dotnet#9
