### ISSUE TITLE
Cannot AddNode to on-premises cluster, and Get-ServiceFabricRuntimeSupportedVersion fails

### ISSUE THREAD

**Issue by viskin** [Azure/service-fabric-issues#690]
Version **6.0.232.9494**
It's impossible to add node:

\> .\AddNode.ps1 -NodeName ....
> Runtime package cannot be downloaded. Check you internet connectivity. If the cluster is not connected to the internet run Get-ServiceFabricClusterUpgrade and note the TargetCodeVersion. Run Get-ServiceFabricRuntimeSupportedVersion from a machine connected to the internet to get the download links for all supported fabric versions. Download the package corresponding to your TargetCodeVersion. Pass -FabricRuntimePackageOutputDirectory <Path to runtime package> to AddNode.ps1 in addition to other parameters. Exception thrown : System.InvalidOperationException: Sequence contains more than one matching element
>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Microsoft.ServiceFabric.Powershell.GetRuntimeSupportedVersion.FormatOutput(Object output)
>    at Microsoft.ServiceFabric.Powershell.GetRuntimeSupportedVersion.ProcessRecord()
>    at System.Management.Automation.CommandProcessor.ProcessRecord()

The same error can be reproduced much simpler, just run Get-ServiceFabricRuntimeSupportedVersion in any environment (not only on-premise):

\> Get-ServiceFabricRuntimeSupportedVersion

> Get-ServiceFabricRuntimeSupportedVersion : Sequence contains more than one matching element
> At line:1 char:1
>  Get-ServiceFabricRuntimeSupportedVersion
>      CategoryInfo          : NotSpecified: (:) [Get-ServiceFabricRuntimeSupportedVersion], InvalidOperationException
>      FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.ServiceFabric.Powershell.GetRuntimeSupportedVersion

**Comment by rishirsinha** [comment]
We are actively working on mitigating this issue.

**Comment by rakshitatandon** [comment]
For now, you can pass in -FabricRuntimePackagePath parameter to AddNode which points to the CAB file location. You can download the runtime out-of-band from https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server

**Comment by chiokejjones** [comment]
Hey @rakshitatandon.  I've tried passing the FabricRuntimePackagePath parameter to the AddNode script but still receive the same error as the OP.  Using the -FabricRuntimePackageOutputDirectory parameter results in the same error.  I'm running an on-premise cluster, and recently upgraded to 6.0.232.9494.
