### ISSUE TITLE
Remoting method call times out after 5 min without reaching target service

### ISSUE THREAD

**Issue by pevyhlas** [Azure/service-fabric-issues#692]
Hi,

I am getting TimeoutExceptions from remote calls to service:

`var serviceProxy = this.serviceProxyFactory.CreateServiceProxy("serviceId");`
`var result = await serviceProxy.GetData(); // throws TimeoutException `

It seems like target service is not reached (I don't have any logs about target method execution start or from RemotingServiceDispatcher)
Timeout happens +-5 mins after proxy call -> SF remoting timeout is set to 5 mins

`Exception:System.TimeoutException: This can happen if message is dropped when service is busy or its long running operation and taking more time than configured Operation Timeout.    at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__24`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWithResult>d__3`1.MoveNext() `

It usually works but from time to time it stops working. This is probably related to node updates.

Any idea what can be the root cause?

Thanks,
Petr

UPDATE: 
It's remoting v1.
There are several warnings "RunAsync was slow to respect the cancellation token and halt execution for a stateful service replica." for different stateful services.
Also multiple "Microsoft.ServiceFabric.Actors.ActorConcurrencyLockTimeoutException: Acquisition of turn based concurrency lock for actor '{ActorId}' timed out after 00:01:22.4390000."

Timeline:
7:04 - remoting call (multiple occurences until it starts working again)
7:09 - remoting call timeout (after 5 min)
7:31 - multiple SlowCancellation warnings for stateful services with actual cancellation time 20-22-24-28 min - different services from source and target of remoting call (however in same .exe)
7:35 - it works again

**Comment by rasmus-s** [comment]
I see the same issue after I upgrade to latest SF version and using remoting v1. The only change we made was upgrade the nuget packags and change to use the remoting V1. 
Any suggestion to fix it?

**Comment by rasmus-s** [comment]
Our stacktrace look like this:
System.TimeoutException: This can happen if message is dropped when service is busy or its long running operation and taking more time than configured Operation Timeout.
 at async Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.InvokeWithRetryAsync[](?)
 at async Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceRemotingPartitionClient.InvokeAsync(?)
 at async Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.InvokeAsync(?)
 at async Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.ContinueWithResult[](?)
--- (Line when we call the actors method)

**Comment by VipulM-MSFT** [comment]
what do you mean by changing to use remoting V1? You were using remoting V2 and then changed to V1?

**Comment by rasmus-s** [comment]
@VipulM-MSFT Yes due #590 I was not able to get V2 to working. I the tried to get the remoting V1 to work, so we at least use the latest nuget package - but then I hit this issue. I perfer using V2.

**Comment by VipulM-MSFT** [comment]
Yeah so during the time you switched, you would have issues as the protocols are not compatible, you have to go through the reverse process of upgrading from V1 to V2 i.e. use the compatibility mode (two listeners on the service). I have already provided you workaround for 590 for now.
