### ISSUE TITLE
Service Fabric runtime issue FileNotFoundException System.Runtime

### ISSUE THREAD

**Issue by mtscanlan** [Azure/service-fabric-issues#693]
I'm having an issue running a net462 service fabric application referencing a netstandard2.0 class library where an exception is thrown stating;

> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

The library is part of the solution and referenced as a project reference. I've replicated the issue here; https://github.com/mtscanlan/Personal/tree/master/ServiceFabricRuntimeIssue/ServiceFabricRuntimeIssue

I found this post from @terrajobst that suggests migrating from project.json to PackageReference within the csproj file.
https://github.com/dotnet/announcements/issues/31

I did that here in this repo;
https://github.com/mtscanlan/Personal/tree/master/ServiceFabricRuntimeIssue/ServiceFabricPackageReferenceFix

The Service Fabric publish now fails deployment with the following output;
> An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'Microsoft.Diagnostics.EventFlow.ServiceFabric, Version=1.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I'm not sure where to go from here, in the same repo we have a netcoreapp2.0 project that depends on the netstandard2.0 library as well which runs fine.

**Comment by ashishnegi** [comment]
@mtscanlan Can you confirm following :
1. Do you see System.Runtime.dll and lot of other dlls in `Personal\ServiceFabricRuntimeIssue\RuntimeIssue\bin\x64\Debug` ?
2. Are these dlls present in `Personal\ServiceFabricRuntimeIssue\ServiceFabricRuntimeIssue\pkg\Debug\RuntimeIssuePkg\Code`.
3. Similarly for `PackageReferenceNotEnteringMain` and `ServiceFabricPackageReferenceFix`.

Also, What is your VS version number ?

**Comment by mtscanlan** [comment]
I ended up solving this by following the instructions provided by ConX-Ryan [in this post.](https://github.com/Azure/service-fabric-issues/issues/427) After manually creating a csproj file using the new project format I no longer received the FileNotFoundException runtime issue.

**Comment by ravipal** [comment]
The latest nuget package (1.6.4) has the fix. Please add the property \<PackageOutputFolder>true\</PackageOutputFolder> to *.sfproj to change the package behavior that will include all the files from output folder.

**Comment by gumaflux** [comment]
@ravipal I have 1.6.4 installed, but still had to add <PackageOutputFolder>true</PackageOutputFolder> to the *.sfproj

**Comment by ravipal** [comment]
The PackageOutputFolder is needed to change the package behavior. We added this flag to not break the existing behavior as some other projects may not want to package everything in output folder.

**Comment by gumaflux** [comment]
I see, thanks for the clarification.

**Comment by tanwarsatya** [comment]
@ravipal could you provide a sample .sfproj for this. I am adding the <PackageOutputFolder>true</PackageOutputFolder> under the project  element and now my project is not loading  in VS.

**Comment by tanwarsatya** [comment]
I confirm adding the below mentioned lines fixed the issue. Make sure lines are under the 'PropertyGroup' which don't have label 'Global'

` <PropertyGroup>
    <PackageOutputFolder>true</PackageOutputFolder>
  </PropertyGroup>`
