### ISSUE TITLE
EOF linefeed in sfproj gets removed against my choice

### ISSUE THREAD

**Issue by ghost** [Azure/service-fabric-issues#696]
Background: https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

Git requires an extra line at the end of file. If someone's sources are hosted on github, you might have seen the abnormal EOF terminator marker in diff view:

<img src="https://user-images.githubusercontent.com/33230602/33692855-25e6c774-daf8-11e7-8ebe-4b7f6c609870.png" width="30%" />

Folks who work on Unix systems,  most of the editors tend to add that extra linefeed automatically so those folks don't particularly see this in diffs. This is something special to CRLF-like OSes.

It used to be an issue with VS for any xml format file (config, proj, xml, resx, xaml) that it removed the extra whitespace from the end of file whenever we used to build or modify some designer etc. that the XML source conrresponds to. I think starting from VS2015 or 2017, VS has stopped doing it for csproj/vbproj or introduced some kind of switch for project system devs to chose this behavior that C#/VB project systems are using?

* Clone some git repo with sfproj
* Open sfproj in some non-VS editor and add extra line feed at the end
* Run `git diff` to verify the EOF linefeed is really there
* Open sln in VS and build
* Run `git diff` to find VS reverted the EOF [CR]LF that y'all added there..

Note if you already have an extra feed, do not add an additional one:

```
</project>X---DONOT END THE FILE HERE---X
0---END HERE---0
X---DONOT END THE FILE HERE EITHER---X  (otherwise you will see additional linefeed in git, which probably you don't want)
```

Please sync with VS or dotnet folks (@davkean and co.) to find what setting they have to prevent VS from behaving against the will of user. Then please fix it for sfproj in future release.

**Comment by ravipal** [comment]
Does this happen during project upgrade? I tried it on the latest VS and building a *.sfproj didn't update the file and preserves the newline at the end of the line.
