### ISSUE TITLE
Remove nodes from standalone cluster

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#698]
Hi,

I am following the process described in [Remove nodes from your cluster](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes) and the cluster configuration upgrade is not initiated at all.
The `Start-ServiceFabricClusterConfigurationUpgrade ` command returns without errors, but nothing happens.

My setup is standalone cluster 6.0.232 using Windows security.

In the past #486 remove node was not available, is it fixed now?

Are there any specific configurations or permissions needed to perform the action?

cheers
Yannis

**Comment by rakshitatandon** [comment]
The issue in #486 is fixed in 6.0.232. Please share your cluster traces at ratando@microsoft.com.

**Comment by maburlik** [comment]
This has been left stale for a while. Let us know by opening a new issue if you are still hitting similar issues.
