### ISSUE TITLE
Multiple Startup Projects w/ Refresh Application Debug Mode FAILED

### ISSUE THREAD

**Issue by spottedmahn** [Azure/service-fabric-issues#699]
When I tried using a refresh app w/ 2 startup projects I received the following error on one of the projects:

>CSC : error CS2012: Cannot open 'C:\Users\mdepouw\Source\Repos\My App Repo\MyApp.WebApiDomain\WebApiDomain\obj\x64\Debug\net462\win7-x64\WebApi.exe' for writing -- 'The process cannot access the file 'C:\Users\mdepouw\Source\Repos\My App Repo\MyApp.WebApiDomain\WebApiDomain\obj\x64\Debug\net462\win7-x64\WebApi.exe' because it is being used by another process.'
Done building project "WebApi.csproj" -- FAILED.

I got around this by setting the failing project as the only startup project and F5ing from VS.  I was then able to go back to having multiple startup projects.

Is this a supported scenario?  Is there any official documentation on this feature?

Reference: [Speed up Service Fabric development with the new Refresh Application debug mode](https://blogs.msdn.microsoft.com/azureservicefabric/2017/04/17/speed-up-service-fabric-development-with-the-new-refresh-application-debug-mode-2/#comment-16306)

**Comment by ravipal** [comment]
This looks like a timing issue. There was a timing issue during build and rebuild and it is fixed the upcoming release.

**Comment by ravipal** [comment]
The fix is not released yet. So keeping it open.

**Comment by spottedmahn** [comment]
Thanks for the update @ravipal !  When it is released, can you please post the version # so everyone would know what minimum version they would need?  Thanks!

**Comment by dbreshears** [comment]
Latest version of the tooling is in VS2017 15.6 update.    Believe this is fixed now, re-open if still seeing this
