### ISSUE TITLE
Add SF .NET reference to the doco

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/service-fabric-issues#7]
Currently PS and REST are the only listed options under SF [doco, Reference section](https://azure.microsoft.com/en-us/documentation/services/service-fabric/)

**Comment by seanmck** [comment]
The .NET reference docs are broken down by namespace. The management APIs (which are the equivalent of the PS/REST docs) are found in the [System.Fabric namespace](https://msdn.microsoft.com/library/mt416943.aspx).

**Comment by SeanFeldman** [comment]
@seanmck sorry for bugging, but by closing do you mean that the System.Fabric ns doco will be added as a .NET reference for management? I got my answer, but others might be still looking for it.

**Comment by seanmck** [comment]
@SeanFeldman: It's already there.

![image](https://cloud.githubusercontent.com/assets/11199476/15564801/8740861e-22ca-11e6-8073-9bee1032e10e.png)

**Comment by SeanFeldman** [comment]
Excellent. Could swear it wasn't a few days ago :)
