### ISSUE TITLE
JsonADDomainExtension isn't compatible with Service Fabric Cluster ARM deployment

### ISSUE THREAD

**Issue by olitomlinson** [Azure/service-fabric-issues#70]
JsonADDomainExtension works with VMSS deployments but doesnt work with Service Fabric Cluster deployments.

The Deploy fails with the following error : 

`{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'joindomain'. Error message: \"Join completed for Domain 'dev'\"."
      }
    ]
  }
}`

The error message looks quite suspicous given that it says 'Join completed' so I logged onto the isntance and checked, and the machine was not part of the domain, and still connected to WORKGROUP.

Here is the extension json fragment I used ( which was taken from https://github.com/apulliam/ModularARM/blob/master/webserver/azureDeploy.json) :

`{
                                "name": "joindomain",
                                "properties": {
                                    "publisher": "Microsoft.Compute",
                                    "type": "JsonADDomainExtension",
                                    "typeHandlerVersion": "1.0",
                                    "settings": {
                                        "Name": "***",
                                        "OUPath": "OU=***,DC=***,DC=***",
                                        "User": "***\\***",
                                        "Restart": "true",
                                        "Options": "3"
                                    },
                                    "protectedsettings": {
                                        "Password": "******"
                                    }
                                }
                            },`

**Comment by msfussell** [comment]
We will look into this. Given the recent release of AAD there may be a few things changing here and clearly scenarios that have not yet been tried out. If you find out more, please post to this thread.

**Comment by Liphi** [comment]
By VMSS deployment, do u mean standalone deployment? And by 'Service Fabric Cluster deployments', do u mean Azure deployment?

**Comment by dotdestroyer** [comment]
By VMSS deployment I mean - using an ARM script to provision a new VMSS, in Azure  (not on prem)

By Service Fabric Cluster Deployment, I mean - Using an ARM script to provision a new VMSS with ServiceFabricNode extension, in Azure (not on prem)

**Comment by Romiko** [comment]
What is the status of this? Can we use this extension with Service Fabric Nodes?

**Comment by ChackDan** [comment]
Sorry @Romiko  for the delay in responding.   "VMExtensionProvisioningError" is coming from the VMSS agent that deploys VM extensions. This has nothing to do with the fact that you are doing this in a VMSS that is a part of the SF cluster. May I suggest you file with issue on https://stackoverflow.com/questions/tagged/azure-vm-scale-set or file an azure CSS ticket on VMSS.

**Comment by aljo-microsoft** [comment]
@Romiko 

Service Fabric does support operating on Windows hosts that are joined to Azure Active Directory Domain; the VMSS extension used to configure your machines to achieve that is not the only means to achieve your goal. If you are unable to successfully use this extension to achieve your goal; then"you can use the Azure Automation Desired State Configuration (Automation DSC) extension."

To achieve whatever it is you want to on those machines: 

Ref:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq

Given this is NOT a Service Fabric issue, but a VMSS extension execution issue; please file an issue against the above documentation for that extension.
