### ISSUE TITLE
Question - Running redis as stateful service orGuest Executable in SF.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#702]
Hello Team,

SF has stateful service so there is no need to use redis but in lift and shift scenario.
we would like to migrate existing application and just change endpoints of redis from aws to local redis service running in cluster.
is it possible to deploy redis as stateful service or guest executable ?
are there any samples available for that.

Thanks,
naresh Khatri

**Comment by masnider** [comment]
This should be possible via a container, we are not planning to support these things as stateful services directly. Thus managing the state for something like redis would have to be accomplished via its own mechanisms and configuration.
