### ISSUE TITLE
Cannot add node to existing cluster

### ISSUE THREAD

**Issue by MathijsHofkens** [Azure/service-fabric-issues#704]
I'm currently in the progress of deploying a 2-type service fabric cluster on-premises.

I have the following 2 types:
- ManagementNodes (running the service fabric services)
- ApplicationNodes (running the deployed applications)

While the initial cluster deployment succeeded with the ManagementNodes, I can not add the ApplicationNodes.

The AddNode.ps1 script succeeds, but the output of Get-ServiceFabricNode does not include the newly added node. Both windows services FabricHostSvc and FabricInstallerSvc are installed and the FabricHostSvc is running.

Can you please assist in further steps?

**Comment by maburlik** [comment]
Are you still hitting this issue?

**Comment by maburlik** [comment]
This thread has been stale for a while so I will assume this is no longer relevant. If this is still impacting, please feel free to send a mail to me at maburlik@microsoft.com.


Thanks
