### ISSUE TITLE
Intermittent errors when running SF project from VS 2015

### ISSUE THREAD

**Issue by aaronla-ms** [Azure/service-fabric-issues#706]
Occasionally when running service fabric project from within VS2015, I get the following error:

8>An application with name 'fabric:/My.App' already exists in the cluster with Application Type 'My.AppType' and Version '1.0.9.710'. Removing it.
8>Remove-ServiceFabricApplication : Application not found

It appears that the deployment powershell script doesn't wait for the previous removal to complete, causing transient failures.

Repro:
1) open sfproj application in VS 2015
2) F5. Wait for services to be running.
3) press "stop" in debugger".
4) F5

[expected]
succeeds, debugging app

[actual]
above error message re "Remove-ServiceFabricApplication : Application not found"

**Comment by dbreshears** [comment]
Indeed looks like a timing issue when on the subsequent F5 the app still exists and by the time the script removes it, it has since been removed.    What length of time in between step 3 and 4 would you say this repro's?  I suspect only a second or two?  

 I would think a fix would likely need to be in Remove-ServiceFabricApplication to ignore or handle the application not found

**Comment by aaronla-ms** [comment]
Yeah, I've seen this everywhere from a couple seconds to a couple minutes. A tight dev inner loop is critical for me.

Sent from Outlook
________________________________

**Comment by oanapl** [comment]
@aaronla-ms , can you try changing your Publish-NewServiceFabricApplication.ps1 script to call Remove-ServiceFabricApplication with ForceRemove flag? You can find the script in under our service fabric sdk. %ProgramFiles%\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK
(It should be line 202 in your version)

```powershell
Remove-ServiceFabricApplication -ForceRemove -Force
```

We will update the script, but this may help you get unblocked until then.

**Comment by am11** [comment]
`-ForceRemove` fixed the sporadic failure I was getting with deploying from VS (and debug mode set to `Remove Application`). In order to share the patch with team, I checked in `Publish-NewServiceFabricApplication.ps1` in our source tree. Looking forward to the official/ootb fix. :)
Thanks!
