### ISSUE TITLE
current_metadata.sfm created on workfolder when you create a reliable collection

### ISSUE THREAD

**Issue by gopimails** [Azure/service-fabric-issues#71]
A stateful microservice is generating numerous folders containing "current_metadata.sfm" files inside when you create a reliable dictionary or reliable queue.

Why is it getting created and how can it be avoided?
Example workfolder path: C:\SfDevCluster\Data\_App\_Node_1\__FabricSystem_App4294967295\work\00000000000000000000000000005000_131201109502389281_131201109876020155

`for(var i = 0; i < 10; i++)
{
   await this.StateManager.GetOrAddAsync<IReliableDictionary<string, long>>(Guid.NewGuid().ToString());
}`

I am using service fabric version 2.2.207.

**Comment by masnider** [comment]
We're creating these files to track various pieces of metadata. Is there some concern/is this causing any problems, or are you just asking out of curiosity?

**Comment by gopimails** [comment]
The "current_metadata.sfm" files and its container folders never gets deleted while service is running and the number keeps on increasing.  And there are folders without any sfm files.

I wanted to understand and confirm if that is normal and that will keep on adding till the life of service.
Also, if fabric is doing that, why not fabric cleaning it up.

**Comment by masnider** [comment]
It is normal, it should not go on forever during the lifetime of the service, just while the collections are in use. Also for the record you're looking inside the app folder of an internal Service Fabric service, most of what is going on here really should not effect you.

**Comment by gopimails** [comment]
Thanks for that update.
