### ISSUE TITLE
Install Microsoft Azure Service Fabric SDK command line silently

### ISSUE THREAD

**Issue by lurock** [Azure/service-fabric-issues#710]
I am trying to create a docker container that I can use on my build server to build Service Fabric applications.  I need to be able download the Service Fabric SDK installer and install it silently without user interaction via the command line.

How do install the Microsoft Azure Service Fabric SDK via the command line without user interaction?

**Comment by lurock** [comment]
I figured it out:

```
# # Install visual c++ 2012 SP1 redistributable package
Invoke-WebRequest "http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU1/vcredist_x64.exe" -OutFile "C:\vcredist.exe" -UseBasicParsing; \
    Start-Process "C:\vcredist.exe" -ArgumentList '/install', '/passive' -NoNewWindow -Wait; \
    rm "C:\vcredist.exe"

# Install Service Fabric Runtime
Invoke-WebRequest "http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabric.6.0.232.9494.exe" -OutFile "C:\ServiceFabricRuntime.exe" -UseBasicParsing; \
    Start-Process "C:\ServiceFabricRuntime.exe" -ArgumentList '/AcceptEULA', '/QUIET' -NoNewWindow -Wait; \
    rm "C:\ServiceFabricRuntime.exe"

# Install Service Fabric SDK
Invoke-WebRequest "http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi" -OutFile "C:\ServiceFabricSDK.msi" -UseBasicParsing; \
    Start-Process "msiexec" -ArgumentList '/i', 'C:\ServiceFabricSDK.msi', '/passive', '/quiet', '/norestart', '/qn' -NoNewWindow -Wait; \
    rm "C:\ServiceFabricSDK.msi"

```

**Comment by eimerreis** [comment]
My use case is not a docker container, but an Azure VM. I solved it using WebPlattform Installer. 

```powershell
choco install webpicmd -y
Start-Process -Path "C:\ProgramData\chocolatey\bin\WebpiCmd-x64.exe" -ArgumentList "/Install /Products:MicrosoftAzure-ServiceFabric-CoreSDK /AcceptEULA /SuppressReboot"
```

**Comment by steve-hawkins** [comment]
@eimerreis choco can use webpi as a source and will install the webpicmd if not already present, so you could simply use:-
`choco install MicrosoftAzure-ServiceFabric-CoreSDK --source webpi --confirm`

**Comment by rexwhitten** [comment]
@steve-hawkins  - This seems to be missing a step.  After running the above choco one liner, I am unable to use  Import-Module ServiceFabric for example.   It does not have all the DLLs installed or GAC'd correctly.  Is this potentially a problem in the choco package it self?

**Comment by petertiedemann** [comment]
@lurock Did you succeed in creating such a docker container? I am trying to follow these steps in a Windows Server Core container, and the installation process gets stuck on `choco install MicrosoftAzure-ServiceFabric-CoreSDK --source webpi --confirm`:
```
Downloaded: 'Microsoft Azure Service Fabric SDK - 3.0.480'
 ...
```

**Comment by Flern** [comment]
@petertiedemann Installation in docker containers is not supported due to the inability to install drivers in the docker containers (root cause is because the SDK requires the runtime be installed).  A separate issue tracks docker specifically at #711 but we've seen no movement or response from Microsoft regarding the community needs.  I suggest making a comment there or opening a new issue to get some attention since this issue is closed.

**Comment by petertiedemann** [comment]
@Flern Thanks, that is very unfortunate, especially since such a docker container exists for Linux:

https://hub.docker.com/r/microsoft/service-fabric-onebox/

**Comment by mike-christensen** [comment]
There's also a discussion of this issue [over here](https://github.com/MicrosoftDocs/azure-docs/issues/15792)
