### ISSUE TITLE
New Service Instance ignored by Service Remoting instance address resolution

### ISSUE THREAD

**Issue by MarekLani** [Azure/service-fabric-issues#713]
Hi,

I noticed that when scaling up stateless service, new instances are ignored when trying to invoke methods thru service remoting. I have two stateless services. One acting as server, one as client. Client service is calling method on server service thru SF remoting implemented within RunAsync method as stated bellow: 

protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var client = ServiceProxy.Create<IContract>(new Uri("fabric:/SF_repo1/StatelessServer"));
                var fromClient = await client.WhoAreYou();

                ServiceEventSource.Current.ServiceMessage(this.Context, "*** Response from: {0}", fromClient);
                Console.WriteLine("*** Response from: {0}", fromClient);

                await Task.Delay(TimeSpan.FromSeconds(5), cancellationToken);
            }
        }

According to documentation, the instance of server service should be selected randomly. It is selected randomly indeed, however when I scale up my server instance, new instances are never targeted by remoting.

**Comment by BharatNarasimman** [comment]
To handle the scale out, you need to add the following code to your service as a part of its initialization

            // This fabricclient object should be cached in your service.
            FabricClient client = new FabricClient();

            // The applicationName Uri is the name of your application that hosts your services that you are scaling out.
            ServiceNotificationFilterDescription filter = new ServiceNotificationFilterDescription(new Uri(<TARGET_APPLICATION_NAME>), true, false);
            client.ServiceManager.RegisterServiceNotificationFilterAsync(filter);
            var resolver = new ServicePartitionResolver(() => client);
            ServicePartitionResolver.SetDefault(resolver);

We will add this to the service fabric remoting code in our future release, so this works without explicitly adding the above code.

**Comment by MarekLani** [comment]
Hi Bharat, thank you for reaction. On local dev cluster this causes that only one instance is being called. Is that expected behavior?

**Comment by MarekLani** [comment]
@BharatNarasimman please was this already solved, or is it stil needed to use work around?

**Comment by amanbha** [comment]
This has been enabled with 3.2.162 release Microsoft.ServiceFabric.Services.Remoting nuget package, please pgrade package to version >-3.2.162
