### ISSUE TITLE
Service Fabric Remoting - FabricCommon.dll not found

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#715]
Hello Team,
we are trying to use remoting feature of Service fabric.
while trying to invoke remoting api inside containers, its throwing exception.
does it has any dependency of GAL or SF Run time to be installed ?
i looked into all nuget packages which comes with service fabric but didnt find this dll.

"Exception occuredThe type initializer for 'System.Fabric.Common.AppTrace' threw an exception.   at System.Fabric.Common.AppTrace.get_TraceSource()\r\n   at Microsoft.ServiceFabric.FabricTransport.FabricTransportSettings.TryLoadFrom(String sectionName, FabricTransportSettings& settings, String filepath, String configPackageName)\r\n   at Microsoft.ServiceFabric.FabricTransport.FabricTransportSettings.GetDefault(String sectionName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings.GetDefault(String sectionName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportServiceRemotingProviderAttribute.CreateServiceRemotingClientFactory(IServiceRemotingCallbackClient callbackClient)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.CreateServiceRemotingClientFactory(Type serviceInterfaceType)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.GetOrCreateServiceRemotingClientFactory(Type serviceInterfaceType)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxy.Create[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)\r\n   at *****************************System.DllNotFoundException: Unable to load DLL 'FabricCommon.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r\n   at System.Fabric.Interop.NativeCommon.FabricGetConfigStore(Guid& riid, IFabricConfigStoreUpdateHandler updateHandler)\r\n   at System.Fabric.Common.NativeConfigStore.CreateHelper(IFabricConfigStoreUpdateHandler updateHandler)\r\n   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)\r\n   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)\r\n   at System.Fabric.Common.Tracing.TraceConfig.InitializeFromConfigStore(Boolean forceUpdate)\r\n   at System.Fabric.Common.AppTrace..cctor()"

**Comment by nareshkhatri81** [comment]
is there any workaround for this ?

**Comment by nareshkhatri81** [comment]
@RajeetN @mani-ramaswamy 
do you guys think with this approach mentioned below will work ?
its loading runtime inside containers.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-services-inside-containers

**Comment by nareshkhatri81** [comment]
@RajeetN @mani-ramaswamy - This issue got resolved after loading service fabric runtime inside containers and following above steps.
As above feature is in preview. are there any limitations of this feature.
its just creating symbolic link to runtime on host and then refereeing to those dll.

**Comment by nareshkhatri81** [comment]
@RajeetN  @mani-ramaswamy 
i tried to load runtime inside containerse which creates symbolink link of SF runtime between host and container but that approch didnt work out.
i still see same above exception.
could you update if you have any workaround for same ?

**Comment by dzoech** [comment]
Hello @nareshkhatri81 
Could you please tell me how you solved this issue? Thanks!

**Comment by nareshkhatri81** [comment]
Hi @dzoech 
It didnt work for me as well. We went ahead with using REVERSE PROXY.

Thank
Naresh

**Comment by dzoech** [comment]
Thanks for your response @nareshkhatri81 
So you call the service from the client using HTTP?
