### ISSUE TITLE
Duplicate cluster names aren't disallowed when provisioning new instances across subscriptions (sometimes)

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/service-fabric-issues#716]
If I create a new Service Fabric cluster in the portal, the first box of the first step requires that I supply a cluster name. That value and the selection of a location to deploy to will comprise both the client connection and management endpoints (along with their respective ports later on).

On at least two occasions in the last day, in neither the portal or when provisioning a Service Fabric instance with an ARM template, will I receive an error if I use a duplicate cluster name. I've got an existing cluster spun up and working in one subscription. If I enter the name of this cluster in the portal while logged into another subscription, it briefly looks as though it's validating it, but then will put the green check box beside the field and allow me to continue. Similarly, my ARM template will pass syntactical validation and will successfully deploy even with the naming conflict. 

In contrast, it will fail validation if I enter a duplicate name within the same subscription. It has failed sometimes when deploying the ARM template, but I usually have gotten an error that never sheds any light on it being this particular issue.

Unfortunately, when you successfully spin up a cluster with the duplicate name, the instance in the portal will be unable to contact any of its nodes, list any applications and the endpoint will, as you'd expect, fail to point to the correct instance (as there are now two instances vying for that address) either in the browser, via the connect cmdlet in Powershell or via other tools like VSTS.

I've been working with Azure support on this for nearly three days now without much success until I accidentally provisioned a duplicate of my existing instance on another subscription and encountered the same error. While reporting on that, I realized it was the same endpoint between the two, deployed a third cluster with a distinct endpoint name and it works fine off the same script with no other changes.

Reproduction steps:
1) Provision a new cluster in Azure. Note the name and the location you use - the rest of the details don't matter much.
2) When that provisioning completes, log into a separate subscription and attempt to use the same location and name as before (I've had better luck reproducing this using ARM templates, but managed twice this evening to reproduce in the portal as well).
3) Note an inability to connect to either instance (though everything will be deployed and otherwise appear to be configured without error). No helpful tips in the logs on the VMs either.

**Comment by masnider** [comment]
These are DNS names associated with the public IP address of the cluster, and hence are managed externally to SF. Please follow up with networking about why sometimes there are conflicts and other times not, but I would imagine it is based on the regions or other parts of the dns name.
