### ISSUE TITLE
SF - Error pulling image from AWS ECR.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#717]
Hello Team,

when trying to pull images from ECR, we are getting below exception.
how we can investigate further if auth is failing or download is failing ?
we have set accountname and Password correctly in ApplicationManifest.xml file.

Error event: SourceId='System.Hosting', Property='Download:1.0:1.0'.
There was an error during download.Failed to download container image *******

i can see below process are running on nodes in cluster.

PS C:\Windows\system32> Get-Process do*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    370      18    27188      44164     118.91   4684   0 dockerd

PS C:\Windows\system32> Get-Process fa*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    635      76    72252      82276  16,070.27   7828   0 Fabric
    139    5639   709676      97636       0.47   5520   0 FabricApplicationGateway
    512      38    68152      81504     881.56   4540   0 FabricDCA
    407      51    59352      83412      12.77   5992   0 FabricFAS
    220     124    24548      32404     121.20   7504   0 FabricGateway
    392      20     9000      20848      57.39   3592   0 FabricHost
    684      64    99696     123720       8.58   5808   0 FabricUOS

This is blocker for us. 

Manually using docker pull i am able to pull images from ECR. its strange why service fabric is having issue downloading images if not present.

Thanks,
Naresh Khatri

**Comment by masnider** [comment]
This is almost always that there's something misconfigured with the container image or security access to the registry. I presume it's a secure registry? Can you share the image and registry information and the snippet you have in the manifest pointing to the image?

**Comment by nareshkhatri81** [comment]
yes registry is secure as in AWS ECR.
i am able to pull using docker from AWS ECR but SF is not able to pull.

i replaced our secrets with ***** below.
AccounName has our accountid
Password is what we get using  aws ecr get-login --no-include-email --region us-east-2

 <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ContainerPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="clients.Code">
        <RepositoryCredentials AccountName="https://*******.dkr.ecr.useast-2.amazonaws.com" Password="************" PasswordEncrypted="true" />
        <PortBinding ContainerPort="***" EndpointRef="ClientContainerTypeEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>

**Comment by nareshkhatri81** [comment]
Issue was with AccountName was not proper.
