### ISSUE TITLE
SDK won't install, complains about lack of SF Runtime

### ISSUE THREAD

**Issue by abyys** [Azure/service-fabric-issues#719]
The link on your own site: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started under the heading "Visual Studio 2017" doesn't work out of the box since it doesn't seem to include the run time dependency, of which i cannot find a single link to on the entire internet!

Some context, earlier today i have a slightly older version of the SDK and runtime working fine, with my apps running nicely on SF cluster on this machine. I needed a newer version of the runtime and SDK, which i downloaded - enter issue one which was that the cluster wouldn't start locally on my windows machine, the cluster manager ran, but it would just spit out a generic error when trying to start a cluster. (I tried restarting the manager as well as the entire windows machine, neither resolved this issue.) 

So after wrestling with this half the day i decided a clean install was the way to go, so i uninstalled service fabric tools and the SDK. Only when i tried to reinstall the SDK as per your website - Web Platform installer 5 says that "This product did not install sucessfully: This product requires Service Fabric Runtime to be installed"

This is SDK 2.8.232 i am trying to install (which i need).

Could i please have the direct link for the windows version of the SF  **runtime** that goes with 2.8.232 SDK (basically the latest stable one i think), also maybe fix the link on your site/add a runtime link since i am clearly not the only one having this issue (see the unanswered comments). Thanks.

**Comment by masnider** [comment]
Direct download links are always available in the release notes for a given release, and the release notes are always at the [team blog](https://blogs.msdn.microsoft.com/azureservicefabric/).

For the release you're looking for, the announcement is [here](https://blogs.msdn.microsoft.com/azureservicefabric/2017/11/13/service-fabric-6-0-second-refresh-release-for-windows-server-standalone-azure-and-net-sdk/), the release notes are [here](https://servicefabricsdkstorage.blob.core.windows.net/public-release-notes/Microsoft%20Azure%20Service%20Fabric%20Release%20Notes%20-%20SDK%202.8.CU2%20-%20Runtime%206.0.CU2.pdf) and this should be the direct [download link](http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabric.6.0.232.9494.exe).

Unfortunately there have been multiple issues with WebPI (broken feeds or caching issues leading to invalid download links) and hence several comments on that page are referring to other issues. If there was a specific one you think is this issue let me know so I can look at it. I do see one that looks like your issue with the suggestion to come here and report an issue, but others look like the old broken feeds issue. 

@maburlik @MikkelHegn shouldn't the SDK link here be auto installing the runtime as well? Or is this just a doc bug where we should have a separate link to the current runtime download as well?

**Comment by MikkelHegn** [comment]
The direct download links are the individual runtime and sdk MSI's - there are two you need to install. WebPI simplifies this by installing both MSIs as one WebPI entry.
