### ISSUE TITLE
Please create a Service Fabric virtual-kubelet provider

### ISSUE THREAD

**Issue by AceHack** [Azure/service-fabric-issues#720]
Please create a virtual-kubelet provider allowing me to use K8s to send commands and packages to SF.

**Comment by masnider** [comment]
For ref: https://github.com/virtual-kubelet/virtual-kubelet

**Comment by mkosieradzki** [comment]
Alternatively this can be considered as exposing ACI API on top of SF? :)

**Comment by AceHack** [comment]
@mkosieradzki it could be done that way or it might be possible to do extras that are not possible through the ACI interface, so I could see benefits to both way.

**Comment by amolenk** [comment]
There's now an experimental version available: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/sfmesh/README.md

**Comment by masnider** [comment]
Today we expect most customers to use ACI in azure via VN.
