### ISSUE TITLE
Monitoring SF Health/Load metrics with Azure Log Analytics

### ISSUE THREAD

**Issue by alecor191** [Azure/service-fabric-issues#722]
We would like to monitor load and health metrics using solutions like Azure Log Analytics: The goal is to 
- define **dashboards**: showing _historical_ data: e.g. how certain health metrics for a specific service behaved over time; or how some load metrics of a service behaved over time.
- **queries**: analyze issues by looking up infra metrics (e.g. node CPU/memory consumption) as well as SF service metrics (load/health) and ideally combine them
- **alerts** to get notified if something goes wrong (e.g. send an email to DevOps team if a health metric of a service gets unhealthy).

Using SF Explorer doesn't allow us to setup e.g. alerts. We looked into SF PS cmdlet/REST API/etc, however that approach would require us to setup apps/services that constantly poll SF and then push the data we get into a solution like Log Analytics.

We saw there is integration with OMS for ETW traces, events, etc. However, we haven't seen that data including load/health metrics.

Does anyone have a recommendation how to get SF services' load/health metric information pushed to a solution like Azure Log Analytics (besides implementing services in a way that they report load/health to both SF and Log Analytics)?

**Comment by dkkapur** [comment]
@alecor191, these steps should help: 
- [Set up WAD to push data to a Storage table](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad#deploy-the-diagnostics-extension). Configure it to pick up health and load events, as described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad#collect-health-and-load-events.
- Set up OMS to read data in from the appropriate storage table: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-oms-setup.

After this is configured, you should be able to set up alerts, query your data in Log Analytics, and build a dashboard in Portal or in OMS.

**Comment by dkkapur** [comment]
@alecor191, I'm going to go ahead and close the issue for now. Let us know if the suggested path does not work.

**Comment by tudorsibiu90** [comment]
For the record, it doesn't work, only if you deploy everything all at once
