### ISSUE TITLE
Cluster Configuration Upgrade ignores -MaxPersentUnhealthyApplications

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#725]
Hi,

command 
`Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\cluster_v3.3.54.json  -MaxPersentUnhealthyApplications 30`

ignores the _-MaxPersentUnhealthyApplications_ setting on  windows standalone cluster environment. 
If there is an application in unhealthy state on the cluster, the final result of the upgrade command is  

> UpgradeState: RollingBackCompleted

 (cluster configuration is not upgraded)

Please log this as a bug.

**Workaround**: 
Invoking just after the above command : 
`Upgrade-ServiceFabricClusterUpgrade -MaxPersentUnhealthyApplications 30` 
sets the value, and the cluster can be updated even if an app is not working fine.

kind regards
Yannis

**Comment by rishirsinha** [comment]
This is a bug which will be fixed in the upcoming release.
