### ISSUE TITLE
When will the Backup & Restore addon feature be available in Azure

### ISSUE THREAD

**Issue by ThiemeNL** [Azure/service-fabric-issues#730]
Hi,

Is there any news on the progress of the backup and restore addon which was announced at Ignite?
I saw this video: https://youtu.be/EO4BUkgHaD8?t=41m50s but cannot find out when it will be available. 

We are planning to implemented this library: https://github.com/loekd/ServiceFabric.BackupRestore 
But maybe it is worth waiting.

Could you please give some insights and advise.
Thanks,

**Comment by raunakpandya** [comment]
Hey @ThiemeNL , The feature is planned for preview early next year..

**Comment by ThiemeNL** [comment]
Thanks!

**Comment by samsta1128** [comment]
Any updates on the preview release timing?

**Comment by raunakpandya** [comment]
Should be available by April..

**Comment by ThiemeNL** [comment]
Hi, are you still planning this feature for April? Do you already have a preview?

**Comment by raunakpandya** [comment]
Yup on track.. Preview is going to be announced soon along with the next runtime update.

**Comment by mschulz531** [comment]
Any update on this? I read a different thread on this topic that talked about rework of the feature that was being impacted by the integration of the linux and windows ReliableCollection code.  Is that a separate issue, or is the timeline for this feature delayed past the end of April?

**Comment by ThiemeNL** [comment]
Hi @mschulz531, I just read the new release notes of SF6.2: https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/19/service-fabric-6-2-release/

•	The Backup and Restore service for Windows is now in public preview. This enables you to more easily backup and restore your Reliable Collections. To learn more about this feature, visit the following [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster).

**Comment by raunakpandya** [comment]
Yes the service is available as preview as part of the v6.2 release. Please use it and provide your feedback.

**Comment by starforce** [comment]
Hello, 
How long before this feature  will be ready for production release?

**Comment by ThiemeNL** [comment]
Hi @starforce I'm also waiting for the GA. @MikkelHegn mentioned something about the GA at ignite: https://www.youtube.com/watch?v=uVJx_WJ3xbY&t=1271s

**Comment by MikkelHegn** [comment]
The plan is to make the service general available with the 6.4 release coming up soon.

**Comment by starforce** [comment]
Thanks @ThiemeNL for the YouTube link. I am excited about it. However, in the demo they are using the same WebRefernce solution which is not built on .NET Core. Outside of using  existing .NET apps and porting  them over to service fabric, why wouldn't you create any new app using .NET Core?

**Comment by MikkelHegn** [comment]
@starforce - the services have to be built using Service Fabric SDK version 3.1 or above.

From: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster#prerequisites

> For applications targeting .Net Core 2.0, application should be built using Service Fabric SDK version 3.1 or above.

Closing as 6.4 has now released with this feature.

**Comment by raunakpandya** [comment]
@starforce The backup restore service does support .NET Core based apps/ services.
