### ISSUE TITLE
Certificates from ApplicationManifest not refreshed

### ISSUE THREAD

**Issue by ladeak** [Azure/service-fabric-issues#734]
Having an application with https endpoints on port 443 with some certificate. When I changed the related certificate and deployed the application to my dev cluster on my local machine, everything worked fine.

In another case, I have the same setup and steps but using custom port (say) 19855. This time application fails to start after the certificate has been changed.

Workarounds:

1. change the endpoint using the certificate to a different port. Say port 19856, deploy again, and application comes up

2. if above workaround is not feasible, reset local cluster (note removing the application/apptype is not enough)

**Comment by RajeetN** [comment]
@ladeak, do you already have another service listening on port 19855 with a different certificate?

**Comment by ladeak** [comment]
@RajeetN that is very unlikely. I have explicitly removed every application from the cluster, beforehand. I have not stopped/started any other application during the process.

**Comment by RajeetN** [comment]
@ladeak, could you share the traces from your service fabric cluster?

**Comment by ladeak** [comment]
I will do so next time I am replacing thumbprints, at the end of March.

**Comment by masnider** [comment]
@ladeak - any updates here? Since we haven't heard back from you I'm going to close down this issue for now. If you have a repro or any other questions, you can reopen it or create a new one. Thanks!

**Comment by ladeak** [comment]
I did not see the issue again, switching the certificate thumbprint worked as expected.
