### ISSUE TITLE
SerializationException when using Services Remoting V2

### ISSUE THREAD

**Issue by Marusyk** [Azure/service-fabric-issues#735]
I'm try to use the new version of Services Remoting (v2) and one of my remote method is 
```
public Task<IEnumerable<string>> GetLanguagesAsync(int labelId)
```
when I call it I get:

> 
> AggregateException: One or more errors occurred.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+<InvokeWithRetryAsync>d__24.MoveNext()
> 
> SerializationException: Type 'System.String[]' with data contract name 'ArrayOfstring:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

So, I change `Task<IEnumerable<string>> ` to `Task<string[]>` then  it works fine. But I need  `IEnumerable<string>`. Why it is the problem with IEnumerable? How can I use it without creating of Custom Serialization?

Also I tried to use [Custom Serialization](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting) but the error is:

> AggregateException: One or more errors occurred.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+<InvokeWithRetryAsync>d__24.MoveNext()
> 
> InvalidCastException: Specified cast is not valid.
> Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient+<InvokeWithRetryAsync>d__24.MoveNext()

**Comment by Mardoxx** [comment]
Related https://github.com/Azure/service-fabric-issues/issues/497

**Comment by Marusyk** [comment]
The fix from #497 doesn't work.
The custom serialization in V2 is cool but does it really need 6 classes? 
Why can't you implement a single interface with something like Serialize and Deserialize?

**Comment by ericcox** [comment]
You can't serialize an interface. See suchiagicha's reply in #497.   "Yes , this is expected in Remoting V2.
Scenario is by default , Remoting Api Types needs to be of concrete Type. In above case , if you change type IEnumerable to long[] , it will work."  [See also](https://stackoverflow.com/questions/2639362/why-are-interfaces-not-serializable)

But honestly, that seems like a lot of work just to avoid copying a IEnumerable<string> into a string[], which takes one line of code. (Unless you're dealing with thousands of strings and want to avoid the performance hit, but then, you shouldn't be sending thousands of strings in one remoting call anyway)

**Comment by Marusyk** [comment]
any information?

**Comment by Lybecker** [comment]
I ran into this problem too.

It works if you change the return type to a concrete implementation like List or []:
`public Task<List<string>> GetLanguagesAsync(int labelId)`

This is a bug, that should be fixed

**Comment by suchiagicha** [comment]
Remoting v2 today  by default doesn't support interface types for return types and parameters for remoting methods. You can override this behavior by adding knowntypes or adding any other serialization provider.

In 6.3 , we are adding support for interface types also.

**Comment by pksorensen** [comment]
I read here that it should work with string[], but when tried this myself i got

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Element 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:Value' contains data of the 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfstring' data contract. The deserializer has no knowledge of any type that maps to this contract. Add the type corresponding to 'ArrayOfstring' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.) ---> System.Runtime.Serialization.SerializationException: Element 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:Value' contains data of the 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfstring' data contract. The deserializer has no knowledge of any type that maps to this contract. Add the type corresponding to 'ArrayOfstring' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.
```

```
 public interface IServiceNotificationService:IService
    {
        Task RegisterServiceNotification(string  serviceName);
        Task ClearProxyAsync(string serviceUri, string[] endpoints);
    }
```

**Comment by suchiagicha** [comment]
Hi @pksorensen 
I am not able to repro this issue. I tried your interface, it worked fine.

Could you share your sample for both service and client?

**Comment by pksorensen** [comment]
@suchiagicha I dont have a minimal repro at this point and just made a quick fix to get by now with string.join(","..) and string.split("," ..) instead of the array. 

No need to look further as this if it works for you.

**Comment by hung-doan** [comment]
@suchiagicha I tested again in latest SDK, It didn't work . I don't think "In 6.3 , you added support for interface types ."
```

Service Fabric 6.3.187.9494
Service Fabric SDK and Tools 3.2.187.9494

.NET Package: Microsoft.ServiceFabric 6.3.187

```
I read release note for 6.3, but It does't mention about supporting interface type or IEnumberable.

**Comment by suchiagicha** [comment]
@hung-doan 
Are you using Remoting V2_1 for service and client?
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#use-the-remoting-v2-interface-compatible-stack

**Comment by hung-doan** [comment]
@suchiagicha , thanks you for your prompt reply. 
I think I missed that point, I will retest V2_1 & give you a feedback soon.

**Comment by hung-doan** [comment]
thanks you @suchiagicha . 
I tested V2_1 and confirm that V2_1 support IEnumerable
