### ISSUE TITLE
Timestamps for unhealthy evaluations

### ISSUE THREAD

**Issue by skyflyer** [Azure/service-fabric-issues#736]
The service fabric console (web interface on port 19080) shows unhealthy evaluations section (`UNHEALTHY EVALUATIONS`) but there are no timestamps present, so it is not really evident when was the last time the error occured.

Kind | Health State | Description
-- | -- | --
Services | Error | Unhealthy services: 100% (1/1), ServiceType='Stateless1Type', MaxPercentUnhealthyServices=0%.
Service | Error | Unhealthy service: ServiceName='fabric:/MessageResponder/Stateless1', AggregatedHealthState='Error'.
Partitions | Error | Unhealthy partitions: 100% (1/1), MaxPercentUnhealthyPartitionsPerService=0%.
Partition | Error | Unhealthy partition: PartitionId='c5d528de-a829-418d-ad8c-2a06c3bfae34', AggregatedHealthState='Error'.
Event | Error | Error event: SourceId='System.FM', Property='State'. Partition is below target replica or instance count. fabric:/MessageResponder/Stateless1 -1 1 c5d528de-a829-418d-ad8c-2a06c3bfae34   (Showing 0 out of 0 replicas. Total available replicas: 0)  For more information see: http://aka.ms/sfhealth

<img width="966" alt="screen shot 2017-12-30 at 08 47 28" src="https://user-images.githubusercontent.com/415535/34452378-242d4c8e-ed3e-11e7-8b57-13299f954e76.png">

My suggestion is to include the timestamp of the generated events.

**Comment by oanapl** [comment]
The unhealthy evaluations show the reason for the current health state. They extract minimal information that can inform people of what may be wrong. There can be more issues in the cluster, but unhealthy evaluations only point to the first one.

To get more information, you need to go to the unhealthy entities and see the health events. For example, the service above is unhealthy because the specified partition has an error event on it. If you go to the partition in Service Fabric Explorer, the details will show you the events, which include the timestamps. 

If SFX is not an option, you can get the same through Powershell:

```powershell
Get-ServiceFabricPartitionHealth c5d528de-a829-418d-ad8c-2a06c3bfae34
```

**Comment by skyflyer** [comment]
Thanks. I can see the timestamp in the partition details, but there is only one entry there. It seems that only the last error for this application instance (type?) is shown there. Is this correct?

I see that fabric is trying to deploy the app as it transitions through different states and only the last error is displayed (I figure all are the same anyhow).

Where could I get more information about what this error really means? (I suppose this ticket is not the right place).

**Comment by oanapl** [comment]
@skyflyer , please read more about the [health model](https://docs.microsoft.com/azure/service-fabric/service-fabric-health-introduction). This article describes how the health reporting works and describes the events and the unhealthy evaluations.

To understand the system health reports, see [this article](https://docs.microsoft.com/azure/service-fabric/service-fabric-understand-and-troubleshoot-with-system-health-reports).

The partition usually has one event, the one reported by System.FM. Other watchdogs and even system components may report more events, but one event is the most seen case. In your previous post, the partition was below replica target. You have a stateless service configured with -1, so the expected is one instance on each node. Currently you have one instance which is not yet up. Try looking at the instance and see what is its health state. It may be that the instance crashes, and you see the id changing.
In most cases, there is a bug in user code or a configuration problem that prevents the service instance from coming up. Take a look at the event log and see whether you can spot any warnings/errors regarding the instance. Have you tried stepping through the code?

**Comment by skyflyer** [comment]
I will read up on the documentation, thanks. I understand the health reporting hierarchy -- I was expecting to see more history with it and more details (such as those provided by the event log in this case). One can hope. :)

I know the service isn't working and I've opened up another issue for that (it is some sort of incompatibility with the Service Fabric). The suggestion to RDP into the machine (from the linked docs above) was helpful to figure out what exactly went wrong with deployment of the app (fwiw, it is this bug: https://github.com/dotnet/standard/issues/328)

As this ticket deals with timestamps not being present on health reports, I won't go off-topic here with other issues I'm seeing with service fabric.

Since the timestamps are visible in the partition details, I'll close this issue now.
