### ISSUE TITLE
Unable to deploy stateless service which uses Microsoft.Extensions.Configuration and IoT Hub Device SDK

### ISSUE THREAD

**Issue by skyflyer** [Azure/service-fabric-issues#738]
I've created a HelloWorld application and dpeloyed it successfully. I then added some Application Insights logging (hardcoded) and that worked too. I then used Microsoft.Extensions.Configuration to read a JSON file and even though the code is in a try/catch, the service fails to deploy with rather nondescriptive error message:

```
Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'.
There was an error during CodePackage activation.The service host terminated with exit code:255
```

When running on a local dev cluster, this works, but breaks at using IoT Hub SDK as documented here: https://github.com/Azure/azure-iot-sdk-csharp/issues/313.

Some related context can be found here: #736

The code in question, which breaks the deployment is:

```c#
            IConfiguration config = null;
            try {
                config = new ConfigurationBuilder()
                    .AddJsonFile("config.json")
                    .Build();
                telemetryClient.TrackTrace("Config file read.");
            } catch (Exception x) {
                telemetryClient.TrackTrace(x.Message, SeverityLevel.Error);
            }
```

Apparently, there are some limitations as to what can or can't be deployed to service fabric?

If needed, I can provide the whole Hello World source code.

**Comment by skyflyer** [comment]
It seems this is connected with https://github.com/dotnet/standard/issues/328. Will investigate if this fixes the problem and report back.

**Comment by masnider** [comment]
Yeah there's no such limitations, SF will deploy whatever you tell us to. Let us know how the other investigation goes. You may also be running into some variant of https://github.com/dotnet/standard/issues/481

**Comment by skyflyer** [comment]
@masnider, the code using Microsoft.Extensions.Configuration is working with .NET 4.7.1 (haven't tried the other workarounds) but it still fails with System.Net.Http not being found. Even on local cluster.

As I don't think this is an issue with service fabric, I'm closing this.
