### ISSUE TITLE
Stateless Actor cluster node - RAM memory going very high

### ISSUE THREAD

**Issue by manoj-kumar1** [Azure/service-fabric-issues#742]
Hi All,

We are building an application where we have following communication with all service deployed in Azure Service Fabric cluster:
 WebAPI (Deploy in same cluster) -> Instance Actor (Stateful Actor with state persist) --> ARM Actor (StatePersistence: Non Actor). 
The ARM Actor make the Azure Fluent API calls and does many operations like VM deployment etc...
**Issue:** After some continuous testing, we started getting following exception and cluster became unstable..
  _"Message": "Acquisition of turn based concurrency lock for actor '6c1d740d-06a2-c1fb-fa65-08d5534d6be1' timed out after 00:01:32.6380000.",
at Microsoft.ServiceFabric.Actors.Runtime.ActorConcurrencyLock.<Acquire>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<DispatchToActorAsync>d__29`1.MoveNext()_
When we checked Actor memory in cluster nodes then found following where ARM Actor has very high RAM memory.
![highmemeoryarmactor](https://user-images.githubusercontent.com/5748980/34600847-86db23a2-f21f-11e7-8830-e1ef660e4902.PNG)

We have already tried these:
Keeping Port=0, increase timeout to 10 mins, and use Remoting V2.
We are nearing to **product release**, any quick help would be greatly appreciated..

**Comment by amanbha** [comment]
Concurrency lock timeout means that  existing actor method call is taking more time. Is there any telemetry within your actor methods which can tell how much time does the external call is taking. Please look at this https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-diagnostics to look at actor perf counters to see how much time your actor method is taking. Also please analyze the dump to see what is using the memory..
