### ISSUE TITLE
Cannot install Service Fabric Runtime

### ISSUE THREAD

**Issue by NiebylskiM** [Azure/service-fabric-issues#744]
In general, I wanted to install latest Service Fabric SDK based on instructions here https://docs.microsoft.com/en-in/azure/service-fabric/service-fabric-get-started.
I have Visual Studio 2017 with Azure Development installed. Therefore I downloaded MicrosoftAzure-ServiceFabric-CoreSDK.exe to install SDK. First of all, I had a lot of problems with Web Platform Installer (e.g. hanging on Visual C++ Redistributable package installation) but I will not focus on this here. So in the end I decided to install SDK manually. 
It depends on Service Fabric Runtime - I downloaded MicrosoftServiceFabric.6.0.232.9494.exe and try to run it from console with administrative privilleges. In the end it fails with result:
**Unable to install Service Fabric Runtime using InstallFabric.ps1. ExitCode: 1**
Whe I looked into the %temp%/FabricSetupLog.log I have following information:

> Starting service eventlog
> Error E_ACCESSDENIED while starting service 'eventlog'
> Unable to start eventlog service because of error E_ACCESSDENIED
> Failed the pre-requisite check for fabric setup

I saw that people (e.g. @YuraGoots) already had same issues [here ](https://github.com/Azure/service-fabric-issues/issues/439) but @maburlik suggestions (Please make sure you are running in a user session that has privileges to start the eventlog service. Also check if the service is disabled, and if so, enable it.) do not help. I'm running this on user with administrative privilleges, Eventlog service is enabled. I can run this manually.

Please advise what to do as I know more and more people in our company struggling with this.

**Comment by NiebylskiM** [comment]
OK, in my case it was 3rd party software blocking installation of this executable - Avecto Defendpoint. Now I'm able to install runtime and SDK, so I'm closing this issue.

**Comment by manojverma-net** [comment]
Hi @NiebylskiM , I am facing same issue like yours. But how did you find 3rd party software blocking the installation.

Thanks in advance !!
