### ISSUE TITLE
ASP.NET Core 2.0 TagHelper

### ISSUE THREAD

**Issue by steverobprice** [Azure/service-fabric-issues#748]
Hi,

I am getting this error after when trying to access any ASP.NET Core MVC page running in Service Fabric in Azure. It works locally and have also tried a new ASP.NET Core project created via the Service Fabric template. The odd part is that we have narrowed down the issue to something in our VSTS build and deployment. Deploying the application via Visual Studio does not cause this issue.

Below is the error I get:
```
Error RZ3501: Invalid tag helper bound property 'RouteValues' on tag helper 'Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper'. 'Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeNameAttribute.DictionaryAttributePrefix' must be null unless property type implements 'IDictionary<string, TValue>'.
```

Has anyone else come across this issue? Any help would be greatly appreciated. Thanks in advance.

**Comment by steverobprice** [comment]
Turns out that our build agent had VS version 15.2 and by upgrading the build agent to the latest version 15.5, that solved the problem.

**Comment by rishirsinha** [comment]
Thanks for reporting both the issue and the fix.
