### ISSUE TITLE
Question - Service Fabric Platform/Application Logs to ELK stack

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#749]
Hello Team,

i was reading documentation and found its possible to send platform logs of Service fabric to Elastic stack(ELK Stack).

is there any documentation available of how to configure that sink ?

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-overview

https://www.elastic.co/products

Thanks,
Naresh Khatri

**Comment by dealboy** [comment]
we are also interested on that topic.

Already did some investigation to use Filebeat but as ASF platform logs are in a zipped format, it is not straight forward.

+ our dev team is investigating older content like https://github.com/Huachao/azure-content/blob/master/articles/service-fabric/service-fabric-diagnostic-how-to-use-elasticsearch.md , but that is not for ASF platform logs.

cheers
Yannis

**Comment by nareshkhatri81** [comment]
@dealboy naming service is down currently for us. we are not able to instigate whats wrong. is there other tool your team used in past to do analysis of logs ?
do you know where can i see logs of naming service only.
There are tons of logs generated by SF.

Thanks,
Naresh

**Comment by dealboy** [comment]
Hi @nareshkhatri81 , we are using winlogbeat on each SF node for Service Fabric events and then query the aggregated logs on our kibana UI.

**Comment by nareshkhatri81** [comment]
@dealboy as u said earlier sf logs are in zipped format. Are u still able to send to elastic search and view it in kibana using winlogbeat ?
Are u running elk stacks as containers ?

**Comment by dealboy** [comment]
@nareshkhatri81 yes, the comment for zip was for trying to use the contents of the diagnostic store with filebeat, as (our) applications usually log in files. but another option is to go straight to the source, the windows event log (using winlogbeat).

**Comment by nareshkhatri81** [comment]
@dealboy - thanks for information.
Can u share some more information ? Like which kind of errors of service fabric you are able to see now after storing those to elastic search.
Screenshot of kibana and instruction of how to filter those would be great help.

**Comment by nareshkhatri81** [comment]
@dkkapur, @anmolah 
do you have any update how platform logs can be sink to other platform like ELK ?

**Comment by rishirsinha** [comment]
We would discourage putting all platform logs into ELK. I would recommend listen to the operational channel we have and push the events in that channel into ELK through any ETW / Event Log provider.

**Comment by nareshkhatri81** [comment]
@rishirsinha thanks for update.
What would u recommened for getting insights into sf platform if u dont recommend ELK?
We are onpremise currently.
Any drawbacks of ELK ?

**Comment by rishirsinha** [comment]
The suggestion was to push the operational event channel that we have into ELK rather than upload the entire SF logs. My understanding of ELK is a bit limited, but from what I understand you can point ELK providers to event channels and they will read from it. The channel we want people to listen to is the Applications and Services logs\Microsoft-Service-Fabric\Operational event channel.

**Comment by nareshkhatri81** [comment]
@dkkapur - i tried to open those zip files in Microsoft message analyzer but i was seeing everything in byte format.
which tool we should use to look into those file ? does Microsoft has any recommendation ?

**Comment by dkkapur** [comment]
@nareshkhatri81 those zip files are not meant to be consumed for any reason other than by us to help diagnose failures in the case that there is an issue with the cluster. we recommend using the ETW provider + the appropriate keyword filter to get the logs you need.

**Comment by dkkapur** [comment]
Going to close this for now - please let me know if you want to reopen it for a reason, or feel free to open up a new issue! Thanks!
