### ISSUE TITLE
strange msbuild problem with 1.6.3 package

### ISSUE THREAD

**Issue by silvioboehme** [Azure/service-fabric-issues#753]
Running msbuild (like in VSTS) doesn't respect a custom CodeAnalysisRuleSet either in the csproj files for the fabric service or in the sfproj file.

The result is the following:
* running msbuild on the solution is fine, because this sets the right ruleset from my csproj
* running msbuild on the sfproj file results in many warning, because my custom ruleset is not loaded

msbuild AutoFinance\AutoFinance.sfproj /nologo /nr:false /t:Package /p:PackageLocation=D:\Test /p:DebugType=none /p:DebugSymbols=false /p:platform="x64" /p:configuration="Release"

CSPROJ
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
  <CodeAnalysisRuleSet>..\Analyzers.Release.ruleset</CodeAnalysisRuleSet>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
  <CodeAnalysisRuleSet>..\Analyzers.Debug.ruleset</CodeAnalysisRuleSet>
</PropertyGroup>

Is there a way to pass the right ruleset to the build with the sfproj?
Or better to disable all analyzers when building the fabric project?

/p:RunCodeAnalysis=false
Passing this to msbuild is not working.

**Comment by silvioboehme** [comment]
Hi!

It seems, that a build/package with Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.2 is fine, but shows the reported behavior with Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.3.

The main difference is, that build 1.6.2 searched the compiled bin in the right path (bin\x64\Debug\net471) while 1.6.3 searches in bin\Debug\net471\win7-x64, didn't find the bin, and recompiles the whole party again, without respecting everything in the csproj file!
For a big solution this costs alot of time, throws unnessesary warnings, and have some more side effects?!?!

**Output with 1.6.2**

1>------ Build started: Project: ClassLibrary1, Configuration: Debug x64 ------
1>ClassLibrary1 -> D:\Projects\Application1\ClassLibrary1\bin\x64\Debug\net471\win7-x64\ClassLibrary1.dll
2>------ Build started: Project: Web1, Configuration: Debug x64 ------
**2>Web1 -> D:\Projects\Application1\Web1\bin\x64\Debug\net471\win7-x64\Web1.exe**
3>------ Build started: Project: Application1, Configuration: Debug x64 ------
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
-------- Package started: Project: Application1, Configuration: Debug x64 ------
**Web1 -> D:\Projects\Application1\Web1\bin\x64\Debug\net471\win7-x64\Web1.exe**
Web1 -> D:\Projects\Application1\Web1\obj\Debug\net471\win7-x64\PubTmp\Out\
Application1 -> D:\Projects\Application1\Application1\pkg\Debug
-------- Package: Project: Application1 succeeded, Time elapsed: 00:00:06.4074610 --------

**Output with 1.6.3**

1>------ Build started: Project: ClassLibrary1, Configuration: Debug x64 ------
1>ClassLibrary1 -> D:\Projects\Application1\ClassLibrary1\bin\x64\Debug\net471\win7-x64\ClassLibrary1.dll
2>------ Build started: Project: Web1, Configuration: Debug x64 ------
**2>Web1 -> D:\Projects\Application1\Web1\bin\x64\Debug\net471\win7-x64\Web1.exe**
3>------ Build started: Project: Application1, Configuration: Debug x64 ------
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
-------- Package started: Project: Application1, Configuration: Debug x64 ------
Controllers\ValuesController.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
Program.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
ServiceEventSource.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
Startup.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
Web1.cs(1,1,1,1): warning SA1633: The file header is missing or not located at the top of the file.
CSC : warning SA0001: XML comment analysis is disabled due to project configuration
**Web1 -> D:\Projects\Application1\Web1\bin\Debug\net471\win7-x64\Web1.exe**
Web1 -> D:\Projects\Application1\Web1\obj\Debug\net471\win7-x64\PubTmp\Out\
Done building project "Web1.csproj".
Application1 -> D:\Projects\Application1\Application1\pkg\Debug
-------- Package: Project: Application1 succeeded, Time elapsed: 00:00:07.2530608 --------

**Comment by dbreshears** [comment]
@silvioboehme ,  can you try 1.6.5 package,  we fixed some regressions in packaging that might address this issue.

**Comment by ravipal** [comment]
Please try the latest nuget package and reopen if you still hit this issue.
