### ISSUE TITLE
"Corrupt" SF cluster - can't delete application anymore

### ISSUE THREAD

**Issue by jbrunet** [Azure/service-fabric-issues#759]
- Environment : Production, On-Premise
- Using the Fabric Explorer UI, i created a new instance of an existing application type
- By mistake i entered a wrong application name "fabric:/somethingfabric:/somethingelse"
- Fabric started the application
- Now, i can't delete this application anymore, using SF UI or by code using FabricClient, Got error "This application does not exist", despite seen in SF Explorer UI. Problem persists even after reboots

I'd like to avoid reinstalling the on-premise cluster completely, it holds other production SF apps

Any help appreciated

**Comment by masnider** [comment]
What do you mean when you say you can't delete it? How are you trying to do the delete? 

Can you share the output of Get-ServiceFabricApplication?

**Comment by oanapl** [comment]
@jbrunet , can you send us more information? The scenario you described should work without issues. 

Like @masnider asked, can you send us the output of Get-ServiceFabricApplication? Have you tried force deleting the application (passing -ForceRemove parameter in Powershell for example)?

**Comment by jbrunet** [comment]
Hi, i successfully removed the application using PowerShell today - not via the UI. Not sure what happened... maybe a special character in the app name ( i copy-pasted the app name from Get-ServiceFabricApplication instead of from the explorer UI )

Thanks for you answers. i'm closing the issue
