### ISSUE TITLE
Support for batch files in EntryPoint (ServiceManifest.xml)

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#763]
As part of hosting a multi-tenant Go process I need to pass some local env variables into the Go process with the recommendation being via a batch file... currently the EntryPoint does not support batch files although SetupEntryPoint does?

**Comment by masnider** [comment]
Shouldn't make a difference, what error are you seeing?

But if you're just trying to specify environment variables, have you looked at [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-how-to-specify-environment-variables)?

**Comment by MedAnd** [comment]
@masnider will close this issue as more testing showed it was my firewall and account related... .bat files are working with SETLOCAL environment variables scoped per process as expected.
