### ISSUE TITLE
Node Stuck in Upgrade mode

### ISSUE THREAD

**Issue by ballm** [Azure/service-fabric-issues#764]
Creating a new 3 node standalone cluster.

Cluster creates successfully and images can be deployed to it, however Node 1 is showing the following error in the Explorer

I wondering if this is due to a minimum replica value that doesn't allow the cluster to drop below 3 nodes, or whether there are additional problems (see the event log error at the bottom). I've been trying to find a complete list of all the possible values you can specify in the cluster config used to create a cluster, as the cluster manifest shows default replica values of 3, but no idea how I could set them in the configuration (if they are set-able).

I have tried rebooting the node, but always comes back up with the same error. Just shows as Down in the explorer then, it doesn't help the upgrade. I tried using the Update-ServiceFabricClusterUpgrade to attempt to rollback, but that didn't seem to do anything.

```
Error event: SourceId='System.Hosting', Property='FabricUpgrade:6.0.232.9494:0'.
Fabric upgrade failed on the node.
```

Requesting the Cluster Health (Get-ServiceFabricClusterHealth)

```
AggregatedHealthState   : Error
UnhealthyEvaluations    :
                          Unhealthy nodes: 33% (1/3), MaxPercentUnhealthyNodes=0%.

                          Unhealthy node: NodeName='Node 1', AggregatedHealthState='Error'.

                                Error event: SourceId='System.Hosting', Property='FabricUpgrade:6.0.232.9494:0'.

NodeHealthStates        :
                          NodeName              : Node 1
                          AggregatedHealthState : Error

                          NodeName              : Node 3
                          AggregatedHealthState : Ok

                          NodeName              : Node 2
                          AggregatedHealthState : Ok

ApplicationHealthStates :
                          ApplicationName       : fabric:/System
                          AggregatedHealthState : Ok

HealthEvents            : None
HealthStatistics        :
                          Node                  : 2 Ok, 0 Warning, 1 Error
                          Application           : 0 Ok, 0 Warning, 0 Error
                          Service               : 0 Ok, 0 Warning, 0 Error
                          Partition             : 0 Ok, 0 Warning, 0 Error
                          Replica               : 0 Ok, 0 Warning, 0 Error
                          DeployedApplication   : 0 Ok, 0 Warning, 0 Error
                          DeployedServicePackage : 0 Ok, 0 Warning, 0 Error
```

Viewing details of the Upgrade I see the following (Get-ServiceFabricClusterUpgrade)

```
TargetCodeVersion                          : 6.0.232.9494
TargetConfigVersion                        : 0
StartTimestampUtc                          : 15/01/2018 17:25:07
UpgradeState                               : RollingForwardInProgress
UpgradeDuration                            : 00:14:00
CurrentUpgradeDomainDuration               : 00:14:00
CurrentUpgradeDomainProgress               : UD0

                                             NodeName            : Node 1
                                             UpgradePhase        : Upgrading
NextUpgradeDomain                          : UD1
UpgradeDomainsStatus                       : { "UD0" = "InProgress";
                                             "UD1" = "Pending";
                                             "UD2" = "Pending" }
UpgradeKind                                : Rolling
RollingUpgradeMode                         : Monitored
FailureAction                              : Rollback
ForceRestart                               : False
UpgradeReplicaSetCheckTimeout              : 49710.06:28:15
HealthCheckWaitDuration                    : 00:00:00
HealthCheckStableDuration                  : 00:00:00
HealthCheckRetryTimeout                    : 00:10:00
UpgradeDomainTimeout                       : 10675199.02:48:05.4775807
UpgradeTimeout                             : 10675199.02:48:05.4775807
ConsiderWarningAsError                     :
MaxPercentUnhealthyApplications            :
MaxPercentUnhealthyNodes                   :
ApplicationTypeHealthPolicyMap             :
EnableDeltaHealthEvaluation                : False
MaxPercentDeltaUnhealthyNodes              :
MaxPercentUpgradeDomainDeltaUnhealthyNodes :
ApplicationHealthPolicyMap                 : {}
```

Viewing windows EventLogs for Node 1 in question I see the following error for the FabricDeployer.
```
System.Fabric.FabricDeployer.InvalidCommandLineParametersException: The argument 1 is invalid.
   at System.Fabric.FabricDeployer.CommandLineInfo.PrintUsage(String errorMessage)
   at System.Fabric.FabricDeployer.CommandLineInfo.Parse(String[] args)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)
```

**Comment by abhaymhatre** [comment]
Is this cluster running in azure ?  / your private infrastructure? 
if in azure, can you share more details
? Resource Id: 
? Region: 
? Deployment times

**Comment by ballm** [comment]
Hi, sorry for not being clearer originally. 

This is a stand alone cluster running on Windows VMs within AWS.

**Comment by Liphi** [comment]
U're creating a new cluster, not trying to perform code or config upgrade, right? Need to take a look at the cluster json config, as well as the trace logs. For json config, we could help take a look if u remove all sensitive info on it. For trace logs, for compliance purpose, u need to contact Microsoft support to upload it.

**Comment by ballm** [comment]
That is correct, this is creating a new cluster.

Cluster config added below. Is a very simple set up. What is the best approach for contacting Microsoft support? I'm not sure if I have access to any support plans that are appropriate? We have an Azure subscription which may have a support plan, but this is around self hosting rather than hosting on Azure so not sure it would be covered anyway? Thank you.


[ClusterConfig.json.txt](https://github.com/Azure/service-fabric-issues/files/1677853/ClusterConfig.json.txt)

**Comment by Liphi** [comment]
The json config looks good. U may refer to this link for how to engage Microsoft support: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server#get-support-for-the-service-fabric-for-windows-server-package

**Comment by maburlik** [comment]
This thread has been stale for a while after providing support info. If the issue is still impacting please create another item so we can actively track this.
