### ISSUE TITLE
Looking for Streaming Websocket example on secured service fabric cluster

### ISSUE THREAD

**Issue by ratherbeoutdoors** [Azure/service-fabric-issues#767]
I'm creating a stateful service to stream audio data to Azure Cognitive Services.  Following the example in [https://github.com/Azure-Samples/service-fabric-dotnet-data-streaming-websockets,](url) I was able to get it working on my local unsecured cluster, but have not been able to get it working in a secured cluster on Azure.  When deploying the application to the cloud, I'm continually getting an error:   
Failed to listen on prefix 'https://+:20007/AudioStreamingServiceWS/xxxxxxx/xxxxxxx' because it conflicts with an existing registration on the machine.' from the remote cluster. I'm able to connect to the secured cluster in Visual Studio (2017) and through the Cluster Explorer in my browser without issue but when the service is starting, this error is being thrown when creating the http listener.  Does anyone have any examples of getting a websocket listener working on a secured cluster?

**Comment by mikebranstein** [comment]
This documentation was very helpful for me: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources#example-specifying-an-https-endpoint-for-your-service. It describes how to setup an HTTP endpoint. Note you have to specify changes in the application manifest and the service manifest files.

**Comment by ratherbeoutdoors** [comment]
That was exactly what I needed.  Thanks!
