### ISSUE TITLE
Including Action Method Name In Reverse Proxy URL Returning 504 FABRIC_E_TIMEOUT

### ISSUE THREAD

**Issue by ravindraaditya** [Azure/service-fabric-issues#770]
My Service Fabric Application is having Stateful Asp.Net Core service with BotDataStoreTableController and with these action methods:

1) public async Task<BotDataEntity> **Retrieve**(string partition, string rowKey) { }
Proxy URL: `http://localhost:19081/EmployeeEngagementSF/EmployeeEngagementData/api/BotDataStoreTable/Retrieve?partition=emulator:conversation&rowKey=36l156c3khcm&PartitionKey=4&PartitionKind=Int64Range`

2) public async Task<BotDataEntity> **Get**(string partition, string rowKey) { }
Proxy URL:
`http://localhost:19081/EmployeeEngagementSF/EmployeeEngagementData/api/BotDataStoreTable/?partition=emulator:conversation&rowKey=36l156c3khcm&PartitionKey=4&PartitionKind=Int64Range`

Only action method with **Get** is reachable while **Retrieve** is returning 504 FABRIC_E_TIMEOUT

I understand from the following [URL  ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy) **Suffix path**: 

> This is the actual URL path, such as _myapi/values/add/3_, for the service that you want to connect to

and is possible to have own action method name

Wondering where am i going wrong or missing any configuration?

**Comment by vturecek** [comment]
Does the "Retrieve" URL work if you try to connect to it directly without the reverse proxy?

**Comment by ravindraaditya** [comment]
It worked swiftly by making following change to action method.

~~[HttpGet]~~ => **[HttpGet("Retrieve")]**
public async Task **Retrieve**(string partition, string rowKey) { }

Proxy URL: `http://localhost:19081/EmployeeEngagementSF/EmployeeEngagementData/api/BotDataStoreTable/Retrieve?partition=emulator:conversation&rowKey=36l156c3khcm&PartitionKey=4&PartitionKind=Int64Range`

Thankyou.
