### ISSUE TITLE
VSTS Docker-Compose Image Download Error 

### ISSUE THREAD

**Issue by mark-micallef** [Azure/service-fabric-issues#773]
We are trying to use the VSTS Docker-Compose feature to deploy a docker container to Service Fabric.  We store the image on an Azure registry and I've manually managed to pull the image and start it up on my laptop so I know that part of the process is working.  However, when we deploy on service fabric, the deployment succeeds and we see the following error in the Service Fabric Explorer:

`There was an error during download. Failed to download container image `

Has anyone ever encountered this?

**Comment by mgreen** [comment]
Do you have access to run a `docker pull` on the host?

**Comment by mark-micallef** [comment]
Hi Michael, thanks for this. I didn't realise you could RDP into nodes on a SF Cluster on Azure. 
I've logged in, tried a docker pull and there is a more descriptive error (basically, the image is Linux-based and Docker is saying I cannot use it on Windows 2016).  I can work around this.  Thank you :)

**Comment by bjd145** [comment]
I was getting a similar error with my Service Fabric cluster and docker compose. I am pulling the IIS container from Microsoft's public repo on Docker Hub.  

My docker-compose file is:
version: '3'
services:
  web002:
    image: microsoft/iis
    ports:
    - "81:80" 

When I did this, Service Fabric/docker would pull down microsoft/iis:10.0.14393.206 but it should pull down the latest according to Docker's documentation -"If no tag is provided, Docker Engine uses the :latest tag as a default. " (https://docs.docker.com/engine/reference/commandline/pull/#parent-command)
I do not know why its pulling a container from well over a year ago when there are many other new containers on Docker Hub - https://hub.docker.com/r/microsoft/iis/tags/

If I do append the :latest tag to my docker-compose file then Service Fabric will pull the correct container

**Comment by masnider** [comment]
@bjd145 can you open a new issue for your report please?

Otherwise @mark-micallef & @mgreen glad you folks got this sorted out!
