### ISSUE TITLE
Local Cluster unable to resolve DNS for container application

### ISSUE THREAD

**Issue by AndyWNorris** [Azure/service-fabric-issues#774]
Scenario:
I have an application that is using windows containers running under service fabric consisting of multiple services communicating with each other using DNS (using ServiceDnsName in application manifest).

When I deploy to an Azure cluster, the application functions correctly and communicate between services.
My local environment is Windows Server 2016 with containers with Visual Studio 2017 and the Service Fabric SDK. 

When I deploy to the local cluster no communication between the services is working. If I attach to one of the containers failing containers and use  Test-NetConnection to ping the relevant ServiceDnsName name, I can see that the name is registered and resolves to 127.0.0.1 the request can not be routed. Going through the same actions on the Azure cluster, the name is registered against the relevant 10.0.0.* address where the instance is running and it is able to resolve the address to the relevant docker container and correctly route the request.

Differing outputs for Test-NetConnection are:

Failing Local Cluster 
PS C:\web-app> Test-NetConnection -ComputerName save-handler -InformationLevel Detailed
ComputerName           : save-handler
RemoteAddress          : 127.0.0.1
NameResolutionResults  : 127.0.0.1
InterfaceAlias         : Loopback Pseudo-Interface 2
SourceAddress          : 127.0.0.1
NetRoute (NextHop)     : 0.0.0.0
PingSucceeded          : True
PingReplyDetails (RTT) : 0 ms

Working Azure Cluster
PS C:\web-app> Test-NetConnection -ComputerName save-handler -InformationLevel Detailed
WARNING: Ping to save-handler failed -- Status: TimedOut
ComputerName           : save-handler
RemoteAddress          : 10.0.0.4
NameResolutionResults  : 10.0.0.4
InterfaceAlias         : vEthernet (Container NIC 44ba5cd1)
SourceAddress          : 172.31.198.68
NetRoute (NextHop)     : 172.31.192.1
PingSucceeded          : False
PingReplyDetails (RTT) : 0 ms

**Comment by vturecek** [comment]
What version of Windows Server 2016 are you running locally? Is the DnsService healthy on your local cluster?

**Comment by AndyWNorris** [comment]
Windows Server 2016 version 1607 Build 14393.2035
All system services (including DNS) up, healthy and stable
All Application services up, healthy and stable. Failure only happens at run time when services try to talk to each other via DNS.

**Comment by Abdruggi** [comment]
We are suffering from the same. Our application consists out of two container: app and cache. if sf deploys the app container before the cache container dns is not working.

**Comment by milvuko** [comment]
Hi @AndyWNorris,
The issue here is that the OneBox cluster (local cluster)  has to be configured slightly differently in order for **container** endpoint resolve to work. In ClusterManifest there is a Node tag which has IPAddressOrFQDN parameter:
```
      <NodeList>
        <Node NodeName="_Node_0" IPAddressOrFQDN="localhost" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/0" UpgradeDomain="0" />
        <Node NodeName="_Node_1" IPAddressOrFQDN="localhost" IsSeedNode="true" NodeTypeRef="NodeType1" FaultDomain="fd:/1" UpgradeDomain="1" />
        <Node NodeName="_Node_2" IPAddressOrFQDN="localhost" IsSeedNode="true" NodeTypeRef="NodeType2" FaultDomain="fd:/2" UpgradeDomain="2" />
        <Node NodeName="_Node_3" IPAddressOrFQDN="localhost" NodeTypeRef="NodeType3" FaultDomain="fd:/3" UpgradeDomain="3" />
        <Node NodeName="_Node_4" IPAddressOrFQDN="localhost" NodeTypeRef="NodeType4" FaultDomain="fd:/4" UpgradeDomain="4" />
      </NodeList>
```
 The value needs to be changed from localhost to the actual IP address of the machine (or DNS name if it has one) that is running the OneBox. 

For example, if the machine running OneBox has a DNS name, then OneBox cluster can be setup by the following command:
`.\DevClusterSetup.ps1 -UseMachineName`

**Comment by AndyWNorris** [comment]
@milvuko Thanks for that, ran the below command and it is now working fine. It may be worth updating the SF documentation in Azure around containers and DNS with this as it is far from intuitive that that set up is required for a local cluster.

Many thanks for your help.
Andy

.\DevClusterSetup.ps1 -UseMachineName -CreateOneNodeCluster

**Comment by milvuko** [comment]
Thank you @AndyWNorris, you are right, documentation needs to be updated. Glad I was able to help.
