### ISSUE TITLE
Guest Executable : Custom Environment Variable for endpoint port specification

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#776]
Hi, We are working on an SF application having a C# stateful service and a Nodejs based Guest Exe. We want to run the guest executable on service fabric assigned port, and after some research we found out [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-environment-variables-reference) that that we need to specify the endpoint in ServiceManifest of guest exe like this : 
`<Endpoint Name="GuestEndpoint"  Type="Input" Protocol="http" />`
And access the port in NodeJs app using this environment variable : 
` process.env.Fabric_Endpoint_GuestEndpoint`

This works fine and nodejs exe listens on the appropriate port as expected but, we want to have a custom name for this environment variable. We tried assigning this `process.env.Fabric_Endpoint_GuestEndpoint` to another environemnt variable in the manifest but that didn't work. Is it possible to do so.

Note that we want to do this because the same Guest Executable code would be used in other environments like dockers etc, and we dont want to name the environment variable to service fabric specific names.

**Comment by guibirow** [comment]
You can if you don't execute the application as the main entry point, instead, you should execute from a batch file, something like this will work:

In your **ServiceManifest.xml**:
```
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>start.bat</Program>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </EntryPoint>
  </CodePackage>
```

On the same folder (code) of your node.exe, you create the start.bat file with following contents:

```
set PORT=%Fabric_Endpoint_GuestEndpoint%
node start.js
```

you should have the port assigned to your service on the **PORT** environment variable.
