### ISSUE TITLE
Service fabric installation issue with error -  0x80070430

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#777]
Hi Team,

One of the node in cluster is failing while deploying with error 0x80070430.

2018-01-22 12:05:09.270,Warning ,19940,FabricInstallerService.FabricUpgradeManager,Upgrade commandline "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\FabricSetup.exe /operation:Install" failed with error 0x80070430, and timeout for retry was hit. Rolling back..

could you please let us know what is meaning of this error.

Thanks,
Naresh Khatri

**Comment by vturecek** [comment]
This is a standalone Service Fabric installation, right?

**Comment by nareshkhatri81** [comment]
Yes its standalone onprem.

**Comment by rishirsinha** [comment]
There would be trace files of the format FabricSetup*.trace and FabricDeployer*.trace. Opening them in any text viewer and searching for error there will give you more insight into exactly what is failing.

**Comment by nareshkhatri81** [comment]
@rishirsinha - Above traces are from those files. i didn't see anything error apart from that error code.
do we know what that error code means ?

**Comment by nareshkhatri81** [comment]
@rishirsinha 
do we have list of error codes and there description documented somewhere ?

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
This issue got resolved.
i have to manually delete earlier services using sc delete servicename command and restart the machine.
