### ISSUE TITLE
Where's App.Config?

### ISSUE THREAD

**Issue by spottedmahn** [Azure/service-fabric-issues#779]
I'm currently having the following exception:

>System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I noticed that my service fabric app **doesn't have an app.config** file which seems to auto-generate binding directs to automatically solve this issue.

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.2" newVersion="4.1.1.2" />
      </dependentAssembly>
...
```
---
Our SLN has mutliple service fabric apps and the apps created previously have an app.config file.  The recently created service fabric app does not.

I tried manually adding an app.config file and add the binding redirects but it doesn't seem to be taking effect (or I did something wrong).

Shouldn't my SF app have an app.config file?  And should Visual Studio be automatically adding binding redirects to it?

**Comment by vturecek** [comment]
What version of Visual Studio 2017 are you using?

**Comment by spottedmahn** [comment]
Yes, 15.5.4.

![image](https://user-images.githubusercontent.com/14079228/35281233-6178a4b8-0020-11e8-8c32-5052fdb3ad3a.png)

**Comment by dbreshears** [comment]
No, the SF app shouldn't have an app.config file.  Individual services may each have one however or in the case of web services would have web.config.,    The SFapp does not compile into an application or binary, it is there only as way to package and deploy the service projects.   Which service is failing to load?   I would look at adding the binding redirects to that service project.

**Comment by spottedmahn** [comment]
I see, thanks for the info! 🙌 

And you're right, my issue was at the service level.  After many hours of digging, [I figured it out](https://stackoverflow.com/questions/48389302/there-was-a-conflict-between-system-net-http/48412386#48412386) 😄 

---

Why do some our or SF Apps have app.configs then?  I'm pretty sure nobody manually added them.  I assume it has something to do w/ [Automatic Binding Redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)?  But if this is not applicable for SF apps, why are they there?

I don't seem them on recently created SF apps though.  Maybe there is bug/issue in the past?

**Comment by dbreshears** [comment]
I suppose that is possible, perhaps created as a result of adding a Connected Service,  we wouldn't prevent say AppInsights from adding it to the .sfproj.  At one point we allowed adding AppInsights to the SFProj but due to issues we now only enable it at the Service level.
