### ISSUE TITLE
Serilog doesn't work in Reliable Actor Services

### ISSUE THREAD

**Issue by jonnovaretti** [Azure/service-fabric-issues#782]
Hi!!

I have two Service Fabric application. The first is an Asp.Net Core Service Fabric, the second is an Actor Service that run with timer.

Both are set up with Serilog. The Asp.Net Core work very well. no problem there, but the second service, Actor Service, I use the same configurations and nuget package but Serilog doesn't save any log.

**Comment by jetmaxim** [comment]
@jonnovaretti 
I am suffering the same problem. Service Fabric Reliable Actor doesn't write Serilog messages. And I have no problems with Asp.Net service as well. Could you please publish the solution or refer to the source code? 
I checked "Serilog doesn't work in Reliable Actor Services" article at stackoverflow, but it doesn't have a solution. I have a hard time to figure out where to invoke CloseAndFlush method.
Thanks

**Comment by jonnovaretti** [comment]
@jetmaxim, sorry to answer so late. Actually, it has worked partially, so I gave up and changed the service to Reliable Statelles, because in my case I just have to schedule a service and I do not use all resources of Actor Model.

I recently found this package ServiceFabric.Actors.Serilog, maybe it can help you
