### ISSUE TITLE
Service fabric v2 remoting causes InvalidCastException when using Guid's

### ISSUE THREAD

**Issue by dubs999** [Azure/service-fabric-issues#783]
I have an issue with using the boilerplate JSON serialization offered here:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2

When using a `Guid` in the signature of your `IService` derived interface an `InvalidCastException` is thrown.

A repro with steps is available on my Github
https://github.com/dubs999/ServiceFabricExample

Short of wrapping every request and response in an object, is there a known workaround for this?

**Comment by steph7308** [comment]
I have the same issue. It appears when a service method has more than 1 parameter. I have a service method with 4 parameters => it fails. I modified the method to pass the 4 parameters inside a single object, and it works. It tried to add an int parameter, it fails :(

**Comment by suchiagicha** [comment]
@dubs999 

Json by default serializes Guid to string. You need to makes sure while deserializing its should of  type Guid  . 
And  for objects , json serialize it as object , hence you wont see this issue if you wrap  Guid in an object.
https://www.newtonsoft.com/json/help/html/SerializationGuide.htm

Simple Fix would be to use Guid Parse method while returning parameter(Below code shows how to do it). You can also write your own  json converters . 

 class JsonRemotingRequestBody : IServiceRemotingRequestMessageBody
    {
        public readonly Dictionary<string, object> parameters = new Dictionary<string, object>();

        public void SetParameter(int position, string parameName, object parameter)
        {
            this.parameters[parameName] = parameter;
        }

        public object GetParameter(int position, string parameName, Type paramType)
        {
            if (paramType.Equals(typeof(Guid)))
            {
                return Guid.Parse((string) this.parameters[parameName]);
            }
            return this.parameters[parameName];
        }
    }

**Comment by suchiagicha** [comment]
@steph7308 

We are not aware of this issue. Could you share your repro?

**Comment by suchiagicha** [comment]
Please re-open this issue if you need more information.
