### ISSUE TITLE
SF ignores Data Package Version

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#784]
We have three clusters running (Testing, Staging and Production). In or build pipeline, the "Update Service Fabric App Versions" task is responsible for versioning. The flag "Updated only if changed" is set to just updated the modified parts.
The testing and staging clusters are working fine. On the production system sf ignores the data package version and uses the code version instead. Because of that, sf is not able to find the certificates in the data package and is unable to spin up the containers.

Error in CopyCertificateFromDataPackage: FABRIC_E_FILE_NOT_FOUND

**Comment by masnider** [comment]
Hi @Abdruggi - I'm pretty sure the platform as a whole is respecting the version and not using a different one but it sounds like you're saying the VSTS tasks are populating the wrong fields or something? Can you give a specific example of the packages produced and what you think it should be?

**Comment by Abdruggi** [comment]
My fault. Everything works like it should.
