### ISSUE TITLE
Unable to create a replica after scaling the application Please help...........

### ISSUE THREAD

**Issue by RAJESHKUMAR905** [Azure/service-fabric-issues#790]
| Unhealthy event: SourceId='System.FM', Property='State', HealthState='Warning', ConsiderWarningAsError=false. Partition is below target replica or instance count. fabric:/Voting/VotingWeb 2 1 b78dca7b-5e78-49ab-b4b7-97fe4c00459a   IB _Node_2 Up 131613518719639864   (Showing 1 out of 2 replicas. Total available replicas: 1)  For more information see: http://aka.ms/
-- | --

  | Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on _Node_2. API call: IStatelessServiceInstance.Open(); Error = System.IO.IOException (-2146232800) Failed to bind to address http://[::]:8080: address already in use.    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.d__21`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Hosting.Internal.WebHost.d__26.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()    at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__13.MoveNext() For more information see: http://aka.ms/sfhealth
-- | --

I have replicated the application and it is assigned to node_2 but i am getting the above warning please help..

**Comment by vturecek** [comment]
The answer is in the error message: Failed to bind to address http://[::]:8080: address already in use.

I'm guessing this is a local cluster?

**Comment by masnider** [comment]
@RAJESHKUMAR905 Hi there! We haven't heard back from you in a while, so we're going to be closing this issue down. If you feel like you haven't figured out yet what's wrong, please feel free to reopen this issue or create a new one. Thanks!

**Comment by NISHANTH2066** [comment]
I have also faced the same issue, and it is a local cluster

**Comment by Franklin89** [comment]
@vturecek @masnider Hi Vaclav, i am hitting this same error. I want to create a demo for a client with service fabric. I want to have a service running on my Local 5 Node cluster with 5 replicas. So on each Node. I want to demonstrate rolling updates etc. but i keep running into this issure that the address is alread in use. I mean I understand if this would happen with 1 node cluster...but with 5 and setting the instance count to -1.

Please help!

**Comment by kumarbs9** [comment]
Is this issue solved, please let me know if any one has answers
