### ISSUE TITLE
Service Fabric hosted web api load testing,getting error: “System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel”

### ISSUE THREAD

**Issue by salariamanisha** [Azure/service-fabric-issues#792]
I have a Hosted web API on a Azure service fabric cluster (on Azure). Now I am trying to do a Load testing using Visual Studio Web Api load test project. When i set the WebTest run count as 1, things works fine. But if i increase the run count to let say 10, the api starts failing with error:

"System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at Microsoft.VisualStudio.TestTools.WebStress.WebTestTransaction.ResponseReceived(IAsyncResult result)"

Same issue has been raised in stackoverflow:  https://stackoverflow.com/questions/48434692/service-fabric-hosted-web-api-load-testing-getting-error-system-net-webexcepti

**Comment by vturecek** [comment]
What web server are you using? Can you establish multiple HTTPS connections outside of the VS load test environment?

**Comment by salariamanisha** [comment]
1. I am using UseKestrel as web server. 
2. Yes the HTTPS connections working outside VS load test.
