### ISSUE TITLE
How to set interactive mode of a docker container in SF

### ISSUE THREAD

**Issue by fouadroumieh** [Azure/service-fabric-issues#793]
I have an image for a console application, when deploying to SF it doesn't work because the container process is exiting even with Console.Readline() in it.
https://stackoverflow.com/questions/38549006/docker-container-exits-immediately-even-with-console-readline-in-a-net-core-c
If I run my docker container with docker run -i myimage is working and alive.
I changed the code to add like infinite loop with system.sleep inside and it works in SF.
How to solve this issue? and can I pass -i or -it argument to SF when starting my container?

**Comment by fouadroumieh** [comment]
@RajeetN Do you have an idea around this issue?

**Comment by RajeetN** [comment]
In the upcoming 6.1 release you can specify interactive flag in ContainerHostPolicies.

**Comment by fouadroumieh** [comment]
@RajeetN any workaround available now?

**Comment by fouadroumieh** [comment]
@RajeetN I see it is already released https://blogs.msdn.microsoft.com/azureservicefabric/2018/01/26/service-fabric-6-1-release/

Do you have an example of such config?
