### ISSUE TITLE
Service Fabric Reverse Proxy does not return 404 Notfound for undefined endpoints

### ISSUE THREAD

**Issue by kahootali** [Azure/service-fabric-issues#795]
I have a service with an endpoint and only **POST** verb exposed and for all other verbs, I want to return **404 NotFound**, as .NetCore does, but what happens is when I call from the client, Service Fabric does not return **404 NotFound** rather it returns **GatewayTImeout** after 120 seconds when the request Timeouts , 

I also explicitly made a `[HttpGet]` endpoint and returned a **404 NotFound** status, even then it does not return rather the call keeps coming again and again in the Get function until the request timeouts. 

I then changed the status from NotFound to BadRequest in the `Get` function and now it works fine. But this way I would explicitly have to make separate functions for all of my endpoints and explicitly send **BadRequest** status. So how to return a **404 NotFound** status.

**This issue occurs only using Reverse Proxy.**

**Comment by kavyako** [comment]
If you want your service to return 404 NotFound explicitly, please add the following header in the service's response:
X-ServiceFabric : ResourceNotFound
Upon seeing this header, reverse proxy will forward the 404 back to the client.

Without the header, reverse proxy gets into a re-resolve and retry loop. Reason for this is explained [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services)

**Comment by kavyako** [comment]
Closing the issue. Please reopen if you have any concerns.

**Comment by jpoon** [comment]
In case this saves somebody a couple minutes of Googling. To send a custom header:

```
       [HttpGet]
        public async Task<IActionResult> GetAsync(string key)
        {
            ...

            Request.HttpContext.Response.Headers.Add("X-ServiceFabric", "ResourceNotFound");
            return NotFound();
        }
```
