### ISSUE TITLE
Start-ServiceFabricClusterConfigurationUpgrade Exception: Cluster configuration upgrade of type StandAloneBaselineUpgradeState is already in progress and cannot be  interrupted.

### ISSUE THREAD

**Issue by zhendl** [Azure/service-fabric-issues#797]
Hello,

I've a standalone SF cluster with 4 vms, and without internet. OS is Windows Server 2016. SF version is 6.0.232.9494. I'd like to upgrade my cluster to the new SF version 6.1.456.9494, I read and act according the flollowing aritcle:

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server#upgrade-the-cluster-configuration

1.Connect-ServiceFabricCluster -ConnectionEndpoint "169.254.183.57:19000"
2.Get-ServiceFabricClusterConfiguration -UseApiVersion -ApiVersion 08-2017
3.Modify the ClusterConfig.json and set the FabricClusterAutoupgradeEnabled to false and saved.
{
  "Properties": {
    "Security": {
      "$id": "1",
      "ClusterCredentialType": "None",
      "ServerCredentialType": "None"
    },
    "NodeTypes": [
      {
        "Name": "NodeType0",
        "ClientConnectionEndpointPort": 19000,
        "HttpGatewayEndpointPort": 19080,
        "ReverseProxyEndpointPort": 19081,
        "LeaseDriverEndpointPort": 19002,
        "ClusterConnectionEndpointPort": 19001,
        "ServiceConnectionEndpointPort": 19003,
        "ApplicationPorts": {
          "StartPort": 20001,
          "EndPort": 20031
        },
        "IsPrimary": true
      }
    ],
    "AddonFeatures": [],
    "FabricSettings": [
      {
        "Name": "Setup",
        "Parameters": [
          {
            "Name": "FabricDataRoot",
            "Value": "C:\\ProgramData\\SF"
          },
          {
            "Name": "FabricLogRoot",
            "Value": "C:\\ProgramData\\SF\\Log"
          }
        ]
      }
    ],
    "EnableTelemetry": true,
    "DiagnosticsStore": {
      "StoreType": "FileShare",
      "DataDeletionAgeInDays": 7,
      "Connectionstring": "\\\\169.254.183.57\\DiagnosticsStore",
      "IsEncrypted": false
    },
    "FabricClusterAutoupgradeEnabled": false
  },
  "Nodes": [
    {
      "NodeName": "vm3",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.235.175",
      "FaultDomain": "fd:/dc4/r0",
      "UpgradeDomain": "UD3"
    },
    {
      "NodeName": "vm2",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.52.10",
      "FaultDomain": "fd:/dc3/r0",
      "UpgradeDomain": "UD2"
    },
    {
      "NodeName": "vm1",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.110.231",
      "FaultDomain": "fd:/dc2/r0",
      "UpgradeDomain": "UD1"
    },
    {
      "NodeName": "vm0",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.183.57",
      "FaultDomain": "fd:/dc1/r0",
      "UpgradeDomain": "UD0"
    }
  ],
  "ApiVersion": "08-2017",
  "Name": "BOCCluster",
  "ClusterConfigurationVersion": "1.0.1"
} 

4.run Start-ServiceFabricClusterConfigurationUpgrade and got the following exceptions:
PS C:\ServiceFabric\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494> Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath "C:\ServiceFabric\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494\ClusterConfig.json"
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
FabricException: Cluster configuration upgrade of type StandAloneBaselineUpgradeState is already in progress and cannot be 
interrupted.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath "C: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gu 
   rationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfig 
   urationUpgrade
 
5.run Get-ServiceFabricClusterUpgrade and get the following message:

PS C:\ServiceFabric\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494> Get-ServiceFabricClusterUpgrade

TargetCodeVersion             : 6.0.232.9494
TargetConfigVersion           : 0
StartTimestampUtc             : 1/23/2018 7:57:23 AM
FailureTimestampUtc           : 1/23/2018 8:40:35 AM
FailureReason                 : HealthCheck
UpgradeState                  : Failed
UpgradeDuration               : 00:42:26
CurrentUpgradeDomainDuration  : 00:00:00
NextUpgradeDomain             : 
UpgradeDomainsStatus          : { "UD0" = "Completed";
                                "UD1" = "Completed";
                                "UD2" = "Completed";
                                "UD3" = "Completed" }
UnhealthyEvaluations          : 
                                Unhealthy nodes: 25% (1/4), MaxPercentUnhealthyNodes=0%.
                                
                                Unhealthy node: NodeName='vm3', AggregatedHealthState='Error'.
                                
                                	Error event: SourceId='FabricDCA', Property='DataCollectionAgent'.
                                
UpgradeKind                   : Rolling
RollingUpgradeMode            : UnmonitoredAuto
ForceRestart                  : False
UpgradeReplicaSetCheckTimeout : 49710.06:28:15

The figure is my portal screenshot, it looks good.
![portal](https://user-images.githubusercontent.com/35913186/35501531-35a4e51e-0515-11e8-9826-cb6cb1ebc6ff.jpg)

Would you please tell me how to resolve the issue?

Thank you!

**Comment by Liphi** [comment]
I don't understand. U mentioned 'I'd like to upgrade my cluster to the new SF version 6.1.456.9494'. But the steps u've executed are config upgrade. There's no step that u're inputting the target code version to the system. Have I missed anything?

**Comment by zhendl** [comment]
@Liphi Please see the following figure, I need to finish the configuration upgrade before upgrade  Cluster.

![step4](https://user-images.githubusercontent.com/35913186/35671146-7a99a922-0775-11e8-99aa-82184917c02c.JPG)

**Comment by Liphi** [comment]
So, if i understand u correctly, u wanna do config upgrade, and then do 6.0->6.1 code upgrade. Now u're having problem with config upgrade. May I take a look at the current and target json config files? Pls remove sensitive info before uploading them. Thx.

**Comment by zhendl** [comment]
@Liphi 
This is my current json config file:

[ClusterConfig.json.txt](https://github.com/Azure/service-fabric-issues/files/1687727/ClusterConfig.json.txt)

This is my target json config file:

[ClusterConfig.json - target.txt](https://github.com/Azure/service-fabric-issues/files/1687730/ClusterConfig.json.-.target.txt)

This is my powershell command list:
[commands.txt](https://github.com/Azure/service-fabric-issues/files/1687734/commands.txt)

**Comment by zhendl** [comment]
@Liphi 
This is my current json config file:

[ClusterConfig.json.txt](https://github.com/Azure/service-fabric-issues/files/1687727/ClusterConfig.json.txt)

This is my target json config file:
{
  "Properties": {
    "Security": {
      "$id": "1",
      "ClusterCredentialType": "None",
      "ServerCredentialType": "None"
    },
    "NodeTypes": [
      {
        "Name": "NodeType0",
        "ClientConnectionEndpointPort": 19000,
        "HttpGatewayEndpointPort": 19080,
        "ReverseProxyEndpointPort": 19081,
        "LeaseDriverEndpointPort": 19002,
        "ClusterConnectionEndpointPort": 19001,
        "ServiceConnectionEndpointPort": 19003,
        "ApplicationPorts": {
          "StartPort": 20001,
          "EndPort": 20031
        },
        "IsPrimary": true
      }
    ],
    "AddonFeatures": [],
    "FabricSettings": [
      {
        "Name": "Setup",
        "Parameters": [
          {
            "Name": "FabricDataRoot",
            "Value": "C:\\ProgramData\\SF"
          },
          {
            "Name": "FabricLogRoot",
            "Value": "C:\\ProgramData\\SF\\Log"
          }
        ]
      }
    ],
    "EnableTelemetry": true,
    "DiagnosticsStore": {
      "StoreType": "FileShare",
      "DataDeletionAgeInDays": 7,
      "Connectionstring": "\\\\169.254.183.57\\DiagnosticsStore",
      "IsEncrypted": false
    },
    "FabricClusterAutoupgradeEnabled": false
  },
  "Nodes": [
    {
      "NodeName": "vm3",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.235.175",
      "FaultDomain": "fd:/dc4/r0",
      "UpgradeDomain": "UD3"
    },
    {
      "NodeName": "vm2",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.52.10",
      "FaultDomain": "fd:/dc3/r0",
      "UpgradeDomain": "UD2"
    },
    {
      "NodeName": "vm1",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.110.231",
      "FaultDomain": "fd:/dc2/r0",
      "UpgradeDomain": "UD1"
    },
    {
      "NodeName": "vm0",
      "NodeTypeRef": "NodeType0",
      "IPAddress": "169.254.183.57",
      "FaultDomain": "fd:/dc1/r0",
      "UpgradeDomain": "UD0"
    }
  ],
  "ApiVersion": "08-2017",
  "Name": "BOCCluster",
  "ClusterConfigurationVersion": "1.0.1"
}


This is my powershell command list:
[commands.txt](https://github.com/Azure/service-fabric-issues/files/1687734/commands.txt)

Thank you!

**Comment by Liphi** [comment]
Looks like the only change u're doing is turning off the FabricClusterAutoupgradeEnabled switch. That's fine.
When baseline upgrade fails, the fix may be tricky. My suggestion is to re-create the cluster. And if the baseline upgrade fails again, there must be something fundamentally wrong with ur unsecure cluster topology, and we could help look at trace logs.

**Comment by zhendl** [comment]
@Liphi Thank you, I've recreated the cluster, and when I try to upgrade the cluster, it shows me: The first Fabric upgrade must specify both the code and config versions, but how to specify the config versions? I cannot find it in the article: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server

PS C:\WINDOWS\system32> Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 6.1.456.9494 -Monitored -FailureAction Rollback
Start-ServiceFabricClusterUpgrade : The first Fabric upgrade must specify both the code and config versions. Requested
value: 6.1.456.9494:
所在位置 行:1 字符: 1
+ Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 6.1.456.9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa
   bricClusterUpgrade]，FabricException
    + FullyQualifiedErrorId : UpgradeClusterErrorId,Microsoft.ServiceFabric.Powershell.StartClusterUpgrade

**Comment by zhendl** [comment]
In addition, I download two zip files of version 6.1.456.9494:
Microsoft.Azure.ServiceFabric.WindowsServer.6.1.456.9494.zip
MicrosoftAzureServiceFabric.6.1.456.9494.cab

But I can only find copy and register MicrosoftAzureServiceFabric.6.1.456.9494.cab, and cannot find how to use the Microsoft.Azure.ServiceFabric.WindowsServer.6.1.456.9494.zip in the article: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server

**Comment by Liphi** [comment]
For ur first question, are u trying to do config upgrade or code upgrade this time? For Standalone, it's not supported to do both in 1 shot. For config upgrade u need to call Start-SfClusterConfigurationUpgrade, and for code upgrade u need to call Start-SfClusterUpgrade. For both code and config upgrade, u should start after the cluster completes baseline upgrade and enters a stable state.
For ur second question, the zip is the deployment package, and the cab is the runtime package. For code upgrade, u should register the cab package.

**Comment by Liphi** [comment]
For Q1, as I said, for config upgrade u need to call Start-SfClusterConfigurationUpgrade, and for code upgrade u need to call Start-SfClusterUpgrade. This is the difference between the 2 cmdlets in Standalone environment.
For Q2, u don't use the zip package when calling Start-SfClusterUpgrade or Start-SfClusterConfigurationUpgrade.
The sample script for performing Standalone code upgrade/ downgrade is as below:

Connect-ServiceFabricCluster XXX
Copy-ServiceFabricClusterPackage -ImageStoreConnectionString "fabric:ImageStore" -Code -CodePackagePath C:\Users\xiaoming\Desktop\MyRuntime.cab
Register-ServiceFabricClusterPackage -Code -CodePackagePath MyRuntime.cab
Get-ServiceFabricRegisteredClusterCodeVersion
Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 5.6.89.9494 -Monitored -FailureAction Rollback

**Comment by Liphi** [comment]
The original ask of this thread is addressed, so this thread will be closed. For other questions, u may open a new thread.
