### ISSUE TITLE
InvalidClusterVersionSelected

### ISSUE THREAD

**Issue by RaleS** [Azure/service-fabric-issues#799]
According to [latest release note](https://blogs.msdn.microsoft.com/azureservicefabric/2018/01/26/service-fabric-6-1-release/) 6.1.456 is available.

Following error message is returned while deploying template
{
  "error": {
    "code": "InvalidClusterVersionSelected",
    "message": "Version '6.1.456.9494' is not valid. Available versions are 6.0.219.9494, 6.0.232.9494.",
    "details": []
  }
}

Datacenter: North Europe

**Comment by Cheesebaron** [comment]
Could seem like everything in the release note isn't actually released.

Looks like currently there is no way of downloading the new version of the SDK. Visual Studio 15.5.6 hasn't been released yet, so the new templates are not available yet, either.

**Comment by navyahmed** [comment]
6.1.456 is in flight, should be available in all regions by end of week.
