### ISSUE TITLE
UnreliableTransportSettings Error

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#80]
I have problems deploying one service. The log is filled with:
`Failed to acquire ReaderLock for path E:\SF\node1\Fabric\work\UnreliableTransportSettings.ini. LockType = writer`

Any idea what this is about?
The file is there but it's empty.

SF tells me:
![image](https://cloud.githubusercontent.com/assets/5556013/19854246/53f17888-9f6e-11e6-9612-bfae61560983.png)

**Comment by masnider** [comment]
Can you use something like [handle](https://technet.microsoft.com/en-us/sysinternals/handle.aspx) to see what might be holding the file?

**Comment by masnider** [comment]
Added @VipulM-MSFT  mostly FYI. I haven't seen this one, but we also haven't heard from you in a while. If you have a good repro for this let us know and we can take another look, otherwise I'll close the issue down shortly.

**Comment by senj** [comment]
Ich often Had this error when updating nuget package but not deleting bin folder. But this solved it for me.

**Comment by masnider** [comment]
Can you give me a little more information about the series of steps that would reproduce this? If it is an issue with our SDK or tooling I'd like to be able to figure it out and repro it. Can you still repro it on a more recent release?

**Comment by VipulM-MSFT** [comment]
We are going to close this issue - if this is still happening please feel free to re-open with more information for us to investigate.
