### ISSUE TITLE
UpgradeOrchestrationService in Quorum Loss after deploying Service Fabric

### ISSUE THREAD

**Issue by Sweiii** [Azure/service-fabric-issues#800]
Hi,
I just deployed a Service Fabric cluster (3node different VMS) and when its done i have UpgradeOrchestrationService in Quorum Loss. I have tried to reset the cluster and redeploy but the same problem.

![Error message](https://user-images.githubusercontent.com/31694507/35512219-3454bd30-04ff-11e8-8eb8-8efeb0310ece.PNG)

I have also tried repairing but no luck.

Service Fabric: MicrosoftAzureServiceFabric.6.1.456.9494
[ClusterConfigUAT.txt](https://github.com/Azure/service-fabric-issues/files/1673650/ClusterConfigUAT.txt)
[Service Fabric Log folder](https://ibol-my.sharepoint.com/:f:/g/personal/andreas_molnbolaget_com/EiI3vs9t2eJMiZMgSY8mnS4BrjTC9wfWtR8ozuTgnBLimg?e=gYawsO)

Can you help me?

**Comment by Liphi** [comment]
First, regarding the json config, suggest to remove the below sections since they're covered by the diagnosticsStore section. And, with deployment package v6.1, u could use 10-2017 instead of 08-2017.

			{
				"Name": "WinFabPerfCtrFolder",
				"Parameters": [
					{
						"Name": "DataDeletionAgeInDays",
						"Value": "5"
					}
				]
			},
			{
				"Name": "WinFabEtlFile",
				"Parameters": [
					{
						"Name": "DataDeletionAgeInDays",
						"Value": "5"
					}
					]
			},
Secondly, to diagnose we need to look at trace logs from all nodes, but the attached logs come from the same box. And for compliance concerns, pls remove sensitive information before providing any config or trace logs.

**Comment by hkuizenga** [comment]
We seem to be hitting the same issue when setting up a new cluster with v6.1.456.9494.  The following event was recorded.

![image](https://user-images.githubusercontent.com/36278411/35993981-d7ef92c8-0cc3-11e8-885e-c1939170a2c3.png)

This seems to manifest itself only when installing a new cluster.  We recently upgraded an existing cluster (from 6.0.232.9494 to 61.456.9494) and did not experience this issue.

**Comment by rakshitatandon** [comment]
Can you make sure you are using the right client binaries from http://go.microsoft.com/fwlink/?LinkId=730690 ? Please download and run the CreateCluster script from within this folder.

**Comment by hkuizenga** [comment]
We used the latest client binaries and the problem went away.  For future versions, it would be much better if old binaries either installed the older cluster version or simply errored out, rather that producing an improperly configured cluster.

**Comment by rakshitatandon** [comment]
Thanks for your feedback @hkuizenga
