### ISSUE TITLE
Rolling upgrade from 6.0 to 6.1 of standalone install caused server reboots

### ISSUE THREAD

**Issue by garrmark** [Azure/service-fabric-issues#801]
I ran the following in my test environment and it went without a hitch:

Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 6.1.456.9494 -Monitored -FailureAction Rollback

I then ran it in my production environment and it caused a server reboot this was in the event log:

```
Log Name:      System
Source:        User32
Date:          1/29/2018 9:06:56 AM
Event ID:      1074
Task Category: None
Level:         Information
Keywords:      Classic
User:          SYSTEM
Computer:      ####
Description:
The process FabricInstallerService.exe has initiated the restart of computer #### on behalf of user NT AUTHORITY\SYSTEM for the following reason: Application: Unresponsive
 Reason Code: 0x40005
 Shutdown Type: restart
 Comment: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="User32" Guid="{b0aa8734-56f7-41cc-b2f4-de228e98b946}" EventSourceName="User32" />
    <EventID Qualifiers="32768">1074</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-29T14:06:56.436556500Z" />
    <EventRecordID>164365</EventRecordID>
    <Correlation />
    <Execution ProcessID="652" ThreadID="1072" />
    <Channel>System</Channel>
    <Computer>####</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="param1">FabricInstallerService.exe</Data>
    <Data Name="param2">####</Data>
    <Data Name="param3">Application: Unresponsive</Data>
    <Data Name="param4">0x40005</Data>
    <Data Name="param5">restart</Data>
    <Data Name="param6">
    </Data>
    <Data Name="param7">NT AUTHORITY\SYSTEM</Data>
  </EventData>
</Event>
```

Please help me to understand why it chose to reboot the server.

**Comment by garrmark** [comment]
The log file gives more information on why it rebooted.  I would still like to prevent reboots.

[FabricInstallerService_6.1.456.9494_131617083768576987.txt](https://github.com/Azure/service-fabric-issues/files/1674506/FabricInstallerService_6.1.456.9494_131617083768576987.txt)

**Comment by Liphi** [comment]
The reason to reboot is internal logic of service fabric system and is prone to change over the time. So, it's by design.
As for whether we already have such a knob to disable reboot, Max could confirm. If not, we could record a feature request, and triage within the product team.
Thx.

**Comment by maburlik** [comment]
The reasoning for rebooting is based around the fact that Fabric must have complete control over its own lifetime and its installation files. If there is a powershell session, event viewer, or other executable holding handles to Fabric installation directory files and is running using administrative privileges, these handles may not be able to be automatically released by terminating processes from FabricInstallerService's end.

We expect that when FabricHost is no longer running, nothing is holding onto Fabric resources. If something violates this premise, we take any and all means to be able to upgrade Fabric installation resources as part of code upgrade. For this reason we force a reboot to be able to replace the installation directory.

To get details on the particular reasoning of the reboot you can inspect the FabricInstallerService logs in FabricLogRoot (as configured for your cluster), and prevent running such applications during Fabric code upgrade. There is no knob to disable the feature.
