### ISSUE TITLE
[VS-OnLine] Build/Release Error: Config is missing for service

### ISSUE THREAD

**Issue by jonnovaretti** [Azure/service-fabric-issues#802]
I'm trying to create a build and release to a actors service in Visual Studio Online. I already created build and release to anothers services fabric without problem. But with this specific service I getting the error below:

_The BuildLayout of the application in E:\SFabric\SP\SP2DS\Fabric\work\ImageBuilderProxy\AppType\SchedulerServiceAppType is invalid. Config is missing for service SchedulerServicePkg._

The first time the release works fine, but after the first version is released, the others releases I got this error.

The others services are Stateless, I dont know why this problem happens and just with this service that is Stateful.

**Comment by NCarlsonMSFT** [comment]
Couple of questions to help steer the investigation:
+ Does the folder exist in the build artifact?
+ Are you doing an upgrade, or are you overwriting the application?
+ Are you using a diff package?

**Comment by BigMorty** [comment]
I assume you resolved the issue, I plan to close this. If that is not the case please re-open and include the additional information requested so we can look into it.
