### ISSUE TITLE
Upgrading dev-cluster

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#804]
As I found in the [documentation ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server) there only one solution how to upgrate dev-styled cluster - recreate it.
It's sad due to we have aboud 20 applications runs on the dev-cluster and I have to redeploy them one by one after upgrade finished.
Is there any way to recreate it, but keep configuration and applications?

**Comment by rishirsinha** [comment]
Yes definitely. 

There might be other ways, but this late at night I can think of one.

- rename C:\SfDevCluster to C:\SfDevCluster_BU
- Upgrade the code.
- rename C:\SfDevCluster_BU to C:\SfDevCluster

**Comment by mgrishkov** [comment]
@rishirsinha, shall I stop cluster befor renaming? What do you mean by "Upgrade the code"?
Can you please share full manual how shall I upgrade dev-cluster in my case.

**Comment by mgrishkov** [comment]
Are there any updates or step by step manual?

**Comment by rishirsinha** [comment]
Upgrade the code is basically, run the web pi installer to install the new version of the product.

**Comment by adduxa** [comment]
I figured out how to upgrade DevCluster without re-creating the whole cluster:

Connect to the cluster
```powershell
Connect-ServiceFabricCluster
```

Check if there is available registered runtime packages
In our case there is only the current one
```powershell
Get-ServiceFabricRegisteredClusterCodeVersion
```

Download the last runtime package
```powershell
Get-ServiceFabricRuntimeUpgradeVersion -BaseVersion 6.1.456.9494
```

Copy the downloaded package into the cluster image store
```powershell
Copy-ServiceFabricClusterPackage -Code -CodePackagePath .\MicrosoftAzureServiceFabric.6.1.472.9494.cab -ImageStoreConnectionString "fabric:ImageStore"
```

Register the copied package
```powershell
Register-ServiceFabricClusterPackage -Code -CodePackagePath MicrosoftAzureServiceFabric.6.1.472.9494.cab
```

Check again registered runtime packages. Now there is two of them
```powershell
Get-ServiceFabricRegisteredClusterCodeVersion
```

Start a cluster upgrade without Health-check
```powershell
Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 6.1.472.9494 -UnmonitoredAuto
```

You can monitor the progress of the upgrade with the following command
```powershell
Get-ServiceFabricClusterUpgrade
```

Note: Service Fabric will restart many times, and the ConnectionEndpoint will not be accessible during them. Thus you can look for listening port `19000` with Windows Resource Monitor and then connect to the cluster with `Connect-ServiceFabricCluster`.
If Service Fabric does not shows up on `19000` for a long time, you may need to reboot the server.

You can also run the upgrade in `UnmonitoredManual` mode to prevent possible continious SF restarts. In this case, you will need to resume it manually:
```powershell
Resume-ServiceFabricClusterUpgrade -UpgradeDomainName "UD1"
```

Or change the upgrade mode while the upgrade is still active
```powershell
Update-ServiceFabricClusterUpgrade -UpgradeMode UnmonitoredManual
```

**Comment by maburlik** [comment]
Thanks @adduxa. These steps should be good to update the runtime; with each runtime we also release a new SDK version so in order to pull in the new dev tools you should run the WebPI installer AFTER running the steps above. In such case the new runtime will already be recognized as installed and only the SDK will be installed, which should preserve SF cluster data.
