### ISSUE TITLE
DataPackageVersion should be optional in CertificateRef

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#806]
As long as the VSTS Agent task "Update Service Fabric App Versions" is not able to update the "DataPackageVersion" attribute, it (the attribute) should be optional.

**Comment by MikkelHegn** [comment]
Versioning package components is a core capability of the platform, which we will not change.

If you encounter problems with the VSTS task, please open an issue here: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ServiceFabricUpdateManifests.

Thanks.

**Comment by Abdruggi** [comment]
@MikkelHegn You got me wrong. I don't say you should get completely rid of versioning. We use it to speed up our deployment and don't want to miss it. My problem is somewhere else.

To reference the code package it is enough to provide the name:

**ApplicationManifest.xml**
```
<EnvironmentOverrides CodePackageRef="Code">
...
<ContainerHostPolicies CodePackageRef="Code" Isolation="process">
```
But to reference the data package from the CertificateRef node it is necessary to provide the version beside the name:

**ApplicationManifest.xml**
```
<CertificateRef Name="SecretsCertificate" DataPackageRef="Data" DataPackageVersion="1.0.0" ...>
```

Why is it necessary to specify the data package version but not the code package version?

**Comment by MikkelHegn** [comment]
@BharatNarasimman to help answer this.

**Comment by bishal-pdMSFT** [comment]
@MikkelHegn can we please re-open this again to finalize whether and why we need data package version in reference? VSTS task should only change behavior if this is a platform feature and not an unintended bug.

**Comment by bishal-pdMSFT** [comment]
@BharatNarasimman @MikkelHegn any update on this?

**Comment by bishal-pdMSFT** [comment]
@BharatNarasimman @MikkelHegn any comment on this? We will need to update VSTS task if this is expected behavior for updating data package version update.
