### ISSUE TITLE
Publish-NewServiceFabricApplication fails to unregister the application type

### ISSUE THREAD

**Issue by ravipal** [Azure/service-fabric-issues#808]
This issue was reported in developer community. https://developercommunity.visualstudio.com/content/problem/174681/in-vs155-service-fabric-not-unregistering-applicat.html

The application has about 10 services and 8 actor projects. And this problem is not always reproducible, but happens 5-6 times per day.

During F5 or publish, the VS tooling calls the Publish-NewServiceFabricApplication, which uninstalls the application and application type if already exists. This code runs into error while unregistering the application type.

26>An application with name 'fabric:/SERVICE-NAME' already exists in the cluster with Application Type 'SERVICE-NAME-Type' and Version '1.0.0'. Removing it.
26>Application Type SERVICE-NAME-Type and Version 1.0.0 was already registered with Cluster, unregistering it...
26>Unregister-ServiceFabricApplicationType : Application type and version is still in use
26>At C:\Program Files\Microsoft SDKs\Service 
26>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:231 char:20
26>+ $reg | Unregister-ServiceFabricApplicationType -Force
26>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
26> + CategoryInfo : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Unregister-Serv 
26> iceFabricApplicationType], FabricException
26> + FullyQualifiedErrorId : UnregisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.UnregisterApplicatio 
26> nType
26> 
26>Finished executing script 'Deploy-FabricApplication.ps1'.

**Comment by dbreshears** [comment]
This is the same timing issue in #706

**Comment by ravipal** [comment]
#706 is about Remove-ServiceFabricApplication complains about the application not found. This issue is about the "Unregister-ServiceFabricApplicationType -Force" is not able to remove the application type. I will keep this open.

**Comment by oanapl** [comment]
Sorry, I closed the issue by mistake, thank you for keeping me straight :)

Unregister application type usually fails because the application delete that was issued before takes  time. This is the timing @dbreshears mentioned.
For #706: application not found should be considered success (as the application was successfully removed).
