### ISSUE TITLE
Timeout behavior of Reliable Queue operations is unclear

### ISSUE THREAD

**Issue by sandersaares** [Azure/service-fabric-issues#81]
I am trying to understand the timeout behavior of various SF operations and ran into some aspects that do not appear to be clearly documented.

First of all, it is not clear in the documentation whether there is any implicit timeout on [TryDequeueAsync(ITransaction)](https://msdn.microsoft.com/en-us/library/dn971446.aspx). An exception mentions "The operation failed to complete within the default timeout" but what this default timeout is or how it can be controlled is unclear. I request this be clarified.

Another overload [TryDequeueAsync(ITransaction, TimeSpan, CancellationToken](https://msdn.microsoft.com/en-us/library/dn706266.aspx) has both a TimeSpan and a CancellationToken parameter, which is confusing to me.

I do not have a timeout to supply for the *TryDequeueAsync* call specifically, I have a timeout for the entire unit of work, driven by a CancellationToken. I want the timeout to occur when the entire unit of work times out, without caring for individual calls within the unit of work.

If there is a way to accomplish this via the reliable queue API, it is not clear to me and I request that it be documented. If there is no way to accomplish this, I request it be added.

The same applies more globally. StateManager.GetOrAddAsync, for example, does not even have any overloads that I could pass a CancellationToken to, so the scenario I care about appears flat out impossible (is it?).

**Comment by mcoskun** [comment]
Hi, 

All Reliable Collection APIs use 4 seconds as the default timeout. You can find this documented in https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-services-reliable-collections. We will also add it to the reference documentation to for convenience.  

Timeouts are used for the "acceptance" stage of the API. Acceptance includes the acquisition of the asynchronous lock and operation to be added to the replication queue.

As you mentioned, we have an overload that uses default timeout (4 seconds) and CancellationToken.None. We do not have an overload for passing only the CancellationToken or Timeout. This is an convenience feature we are considering. Matthew Snider can help with make an official feature request.

Thank you,
