### ISSUE TITLE
Restarting a container causes SF to crash

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#811]
Manually restarting a container (Deployed Code Package Code -> Restart) causes SF to crash. I could share the FabricHost crash dump files.

**Comment by navyahmed** [comment]
please share the dump files

**Comment by Abdruggi** [comment]
@navyahmed I will upload the dumps to onedrive and send you the link. Could you please give me an email address for that?

**Comment by tugup** [comment]
Can you share the traces to? Send an email to tugup@microsoft.com

**Comment by Abdruggi** [comment]
@tugup the reorg job was faster than me. because the problem did not occur again, i am going to close the issue for now.
