### ISSUE TITLE
Services.Remoting.V1 in netstandard vs net45 libraries (v3.0.456)

### ISSUE THREAD

**Issue by loekd** [Azure/service-fabric-issues#815]
I have a [class ](https://github.com/loekd/ServiceFabric.Mocks/blob/master/src/ServiceFabric.Mocks/MockServiceProxy.cs)that implements `IServiceProxy`. 
When compiling against the `NET45` build of the package `microsoft.servicefabric.services.remoting` (v 3.0.456), I must implement:

    Type ServiceInterfaceType { get; }
    ServicePartitionClient { get; }
    ServicePartitionClient2 { get; }

However, when targeting the `netstandard2.0` build of the same package, I must implement:

    Type ServiceInterfaceType { get; }
    ServicePartitionClient2 { get; }

**Issue**
It appears that Remoting.V1 was dropped from the netstandard package. 
(There's nothing in the release notes about this?)

**Reproduce this:**
- Clone https://github.com/loekd/ServiceFabric.Mocks
- Open the [csproj](https://github.com/loekd/ServiceFabric.Mocks/blob/master/src/ServiceFabric.Mocks/ServiceFabric.Mocks.csproj) files
- Replace `<TargetFrameworks>net451;net46</TargetFrameworks>` with `<TargetFrameworks>netstandard2.0</TargetFrameworks>`
- Restore packages & rebuild
- Notice build errors caused by absence of Remoting V1:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'V1' does not exist in the namespace 'Microsoft.ServiceFabric.Services.Remoting' (are you missing an assembly reference?)	ServiceFabric.Mocks(netstandard2.0)`

**Comment by festivus** [comment]
The V1 version is also not specified when you target net47. In addition, at runtime I get an error that 'Method 'get_ServicePartitionClient' in type 'XXX' from assembly 'XXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.' So, compile time it says you don't need ServicePartitionClient { get; } anymore, but at runtime it says it does.

Also, if I create a .net console app using the Windows Classic Desktop template and target the 4.7 framework, it still requires both V1 and V2 ServicePartitionClient and it works at runtime.

**Comment by MicahMcKittrick-MSFT** [comment]
@festivus I have reached out to @raunakpandya and have been informed that RemotingV1 is not supported in NS2.0

**Comment by raunakpandya** [comment]
@festivus which sdk version are you using?

**Comment by festivus** [comment]
3.0.472

**Comment by ashishnegi** [comment]
Remoting V1 is not available in netstandard. It is older remoting stack. V2 is newer and better. Please use [V2 stack](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-remoting-v2-stack). 
Closing this issue.

**Comment by ashishnegi** [comment]
@festivus If you are seeing this issue with net47, please open a new issue with reproducible steps or share a sample project on which we can see the issue.

In net47, you can use both V1 and V2. But two services should be using `either` V1 stack or V2 stack for communicating. There is [migration guide](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-upgrade-from-remoting-v1-to-remoting-v2) from V1stack to V2stack.

**Comment by festivus** [comment]
Are you kidding me? Did you read the issue?

**Comment by festivus** [comment]
Are you kidding me? Follow loekd steps except use net47 instead of netstandard2.0.
