### ISSUE TITLE
Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4 failing to build 

### ISSUE THREAD

**Issue by dalestone** [Azure/service-fabric-issues#817]
I've recently installed the latest SDK 3.0 and now are having issues building my project.

Visual Studio 2017 Professional requires me to upgrade my project (previously 2.8 SDK), it changes the reference of `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.2 to Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4`

This results in the following build error:
`
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(750,5): error : The OutputPath property is not set for project
`

If I manually change the version in the .sfproj and local packages.config back to `1.6.2` it builds fine. I thought I'd mention it here as it is a bit annoying to have Visual Studio upgrade your project and then you can no longer build.

**Comment by dbreshears** [comment]
Sorry about that but not something we have encounterd in our testing.  What types of services do you have in your solution?   Does your .sfproj get updated to the 1.6.4 version correctly and the nuget package installed in solution root and updated in packages.config ?   1.6.2 and 1.6.4 should be fairly equivalent when it comes to building the SFApp.     Please  make sure that everything is still building "x64" from Build->Configuration  manager menu after the project is upgrade and loads?     Can you share a repro project?

**Comment by dalestone** [comment]
Sure if you clone the following repo https://github.com/dalestone/service-fabric-build-issue

The build\build.cmd is targeting x64.

1. cd to `build\build.cmd` - Build error as the Iot.Admin.Application.sfproj and packages.config reference `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4`
![image](https://user-images.githubusercontent.com/3886432/35941142-33680e12-0c49-11e8-8bd8-7e63933ed757.png)


2. Now change them to reference `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.2`instead and run `build\build.cmd`  again- No longer a build error regarding output path.
![image](https://user-images.githubusercontent.com/3886432/35941187-596fb2cc-0c49-11e8-8626-4111cb0dceab.png)

**Comment by SamHard** [comment]
Make sure you delete the "ServiceFabricBackup" folder, which is created automatically when Visual Studio updates the .sfproj file.  The contents of that folder were causing issues with MSBuild for my team.

**Comment by caxepok** [comment]
Upgrade to 1.6.5 helped me.

**Comment by dbreshears** [comment]
Yes, this is fixed 1.6.5 of the Nuget package.

**Comment by swe-AF** [comment]
I've had a similar issue as initially described. i installed the latest SDK 3.0 building my project locally went well, while a CI build in VSTS failed with `error : The OutputPath property is not set for project...`, which didn't happen before the update.

For me Visual Studio 2017 Professional changes the reference of `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0` to `Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4`

Manually changing the version in the .sfproj and local packages.config to 1.6.5 results in a failed build in VSTS as well. Only changing it to 1.6.2 fixes the issue for me as the project can be loaded and the build doesn't fail.

**Comment by dbreshears** [comment]
@swe-AF,   Can you share your SFProj and the service project files or a repro of this?   I assume that building from the command line with MSBuild locally is also failing.

**Comment by rufio620** [comment]
I am experiencing this issue as well. I have opened a related issue at https://github.com/Azure/service-fabric-issues/issues/920

The issue appears to stem from the new csproj format not having a way to set the default platform. All of my projects have a single x64 platform target but when building the sfproj via msbuild it seems to disregard the supplied platform and just default to AnyCpu.
