### ISSUE TITLE
Changing .Net Core 2.0 Actor Service to target x64 breaks build

### ISSUE THREAD

**Issue by burgonb** [Azure/service-fabric-issues#819]
We are trying to create a new Service Fabric application with services targeting .Net Core 2.0. However, if we change the target platform of an actor service from "Any CPU" to "x64" the build fails with the following error:
```
1>Target UpdateServiceFabricApplicationManifest:
1>    Target _CopyAssembliesToFabActUtilWorkingDir:
1>        C:\Users\i54744\.nuget\packages\microsoft.servicefabric.actors\3.0.456\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(16,5): error MSB3030: Could not copy the file "c:\repos\Core2Test\Core2Actor\bin\Release\netcoreapp2.0\win7-x64\\Core2Actor.runtimeconfig.dev.json" because it was not found.
1>    Done building target "_CopyAssembliesToFabActUtilWorkingDir" in project "Core2Actor.csproj" -- FAILED.
1>
1>    Done building project "Core2Actor.csproj" -- FAILED.
```
On one developer computer this failure happened in both Debug and Release Configurations.  On another it happened only for Release.

Steps to reproduce:
1. Create a new Visual Studio solution using the `Service Fabric Application` template.
2. In the "New Service Fabric Service dialog, select the `Actor Service` template in the `.Net Core 2.0` section and create the service.
3. Everything builds as expected.
4. Open the configuration manager.
5. Set the Actor Service and Actor Interfaces projects to target the x64 platform instead of Any CPU
6. Attempting to build the solution produces the error shown above.

Environment where this occurred:
Visual Studio Professional version 15.5.6
Service Fabric and SDK version 6.1.456.9494
.Net Core Runtime version 2.0.5
.Net Core SDK version 2.1.4

Please let me know if further information is required to reproduce or diagnose this issue.

**Comment by dbreshears** [comment]
@burgonb ,  thanks for the repro steps, indeed can repro.   We will investigate.

**Comment by dbreshears** [comment]
@burgonb,   one way to workaround this is to right click on the Actor and Actor.Interfaces projects and select "edit actor1.csproj".    Then add the following line below.  You might find an entry all ready that has Platforms (plural), you can remove it but I didn't find it caused an issue if it is there.  The problem is it has both "AnyCPU;x64" which causes the issue.  

`<Platform>x64</Platform>`

**Comment by eliasnawfal** [comment]
@dbreshears Thank you for the workaround, it happens only in Release for me

**Comment by burgonb** [comment]
Thank you for the workaround.  We will try it out.

**Comment by cimryan** [comment]
@dbreshears Thanks for the workaround. We found that when we removed the "Platforms" element the Configuration Manager became less useful: It just showed "AnyCPU" for these projects. We're guessing that the Configuration Manager doesn't know about the Platform element. So, for now, we have both
```
<Platform>x64<Platform>
<Platforms>x64<Platforms>
```

**Comment by codepic** [comment]
I had to add

```
<Platform>x64<Platform>
<Platforms>x64<Platforms>
```

for all the projects in my solution and then remove the AnyCPU solution configuration.

But it did the trick.
