### ISSUE TITLE
Service Fabric Reverse Proxy translates 404 into 504

### ISSUE THREAD

**Issue by Rurouni** [Azure/service-fabric-issues#82]
Hi,

I have seen consistent behavior where GET that results in 404 on backend service  is translated by SFRP into 1 min delay(probably default timeout) and then 504 for the client. 
Backend service is accessible through SFRP and same endpoint returning 200, 401 or 403 works fine.

Version: Azure (5.3.301.9590)

Thank you

**Comment by mkosieradzki** [comment]
Have a look on: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reverseproxy/
find text about 404. 

There is a header X-ServiceFabric : ResourceNotFound that overrides this builtin mechanism.

**Comment by Rurouni** [comment]
Thank you @mkosieradzki, that definitely explains it.
Personally I would prefer if it was opt in rather than opt out behavior, 
because this together with requirement to use <App>/<Service> in the path makes SF ReverseProxy quite disruptive to retrofit.
