### ISSUE TITLE
Service deletion failed

### ISSUE THREAD

**Issue by ifle** [Azure/service-fabric-issues#820]
I have application with 2 services deployed as containers. I've used Compose deployment. 
I can't delete them. During update the SF does not remove already not used docker images from VM's of nodes.
```
Error:  Service deletion failed.
Code: E_FAIL
Message: Invalid operation on compose application. Use compose deployment operation.

```

**Comment by oanapl** [comment]
As the message above say, you must use compose deployment instead of direct service related commands. See [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose). Try Remove-ServiceFabricComposeDeployment or Start-ServiceFabricComposeDeploymentUpgrade.

**Comment by oanapl** [comment]
@ifle, there have been no update in a while. I will close the issue, feel free to reopen if you still have questions.
