### ISSUE TITLE
Publish from VS2017 got stuck in Copying application to image store...

### ISSUE THREAD

**Issue by hengyiliu** [Azure/service-fabric-issues#821]
VS2017 15.5.6
Azure Service Fabric on Linux: 6.1.183.1
Service Fabric SDK: 3.0.456.9494

I have a Azure Service Fabric cluster on Linux and a simple project created from VS template. When I publish from VS, it got stuck in "Copying application to image store..." for hours and won't complete:
```
2>Started executing script 'Deploy-FabricApplication.ps1'.
2>powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command ". 'c:\test\SimpleSF\SimpleSF\Scripts\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'c:\test\SimpleSF\SimpleSF\pkg\Debug' -PublishProfileFile 'c:\test\SimpleSF\SimpleSF\PublishProfiles\Cloud.xml' -DeployOnly:$false -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'SameAppTypeAndVersion' -SkipPackageValidation:$false -ErrorAction Stop"
2>Copying application to image store...
```

Service Fabric explorer page showed nothing deployed. I have also tried to re-create a new project and a new cluster from Azure Portal, and still got stuck in the same place. It was working fine a few days ago. Has anything changed recently?

**Comment by Sveer** [comment]
The same trouble on Windows cluster.
I try to add -ShowProgress parameter, but still nothing in build window. 
Parameters for Copy-ServiceFabricApplicationPackage:
Copy-ServiceFabricApplicationPackage -ApplicationPackagePath C:\Projects\Sample\Sample\pkg\Debug -ImageStoreConnectionString fabric:ImageStore -ApplicationPackagePathInImageStore SampleType -TimeOutSec 6000 -CompressPackage -ShowProgress -ShowProgressIntervalMilliseconds 500

**Comment by juho-hanhimaki** [comment]
I think I've encountered this too when publishing from VS.

As workaround removing the following parameter from publish profile fixed the issue for me:
  <CopyPackageParameters CompressPackage="true" />

**Comment by Sveer** [comment]
@juho-hanhimaki 
Doesn't work for me. Totally remove -CompressPackage, but nothing changed. :(

**Comment by Sveer** [comment]
Additional information.
If I run scripts manually:
`Connect-ServiceFabricCluster -X509Credential -ServerCertThumbprint...`
Then: 
`Copy-ServiceFabricApplicationPackage -ApplicationPackagePath C:\xxx\pkg\Debug -ImageStoreConnectionString fabric:ImageStore -ApplicationPackagePathInImageStore xxxType -TimeOutSec 6000  -ShowProgress -ShowProgressIntervalMilliseconds 2500`
Process start and after 2 minutes all freezes on:
![image](https://user-images.githubusercontent.com/4079141/35779237-adecc126-09da-11e8-928a-6f391adc6965.png)

**Comment by hengyiliu** [comment]
Looks like there's some problem in ImageStore service. For now, I'm using an external store as a workaround.
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-remove-applications#register-the-application-package-copied-to-an-external-store

**Comment by Sveer** [comment]
@hengyiliu . Thanks, i'll check.
More diagnostic:. If I copy pkg folder by RDP to one of the servicefabric machine and run Copy-ServiceFabricApplicationPackage  - all is working. => Troubles with coping from remote machine to ImageStore...

**Comment by oanapl** [comment]
This seems similar to #813. We are currently investigating.

**Comment by cata** [comment]
Same problem here - it appears that attempting to uploading files larger than ~4MB hangs the transfer.

**Comment by oanapl** [comment]
I will close this issue as duplicate, and use #813 to track the fix.

As I answered in #813 , this is due to a configuration mismatch between standalone and Azure clusters for MaxMessageSize configuration, which is 10 MB for standalone and only 4 MB for the cluster. It happens when the local cluster is set up on the client, which changes the default configuration to 10 MB. 

We will make a fix to ensure the 2 are in sync.

Meanwhile, the mitigation is to remove the local cluster, then upload to the Azure cluster succeeds.
