### ISSUE TITLE
Deploy-FabricApplication should fail when PublishProfile does not exist

### ISSUE THREAD

**Issue by klettier** [Azure/service-fabric-issues#822]
Hello,

If you call [Deploy-FabricApplication.ps1](https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/blob/master/src/GettingStartedApplication/GettingStartedApplication/Scripts/Deploy-FabricApplication.ps1) with a **PublishProfile** that does not exist [this line](https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/blob/master/src/GettingStartedApplication/GettingStartedApplication/Scripts/Deploy-FabricApplication.ps1#L132) will throw but the exception **will be swallowed** and the script will continue.

This is really bad and could lead to unexpected results.

kévin

**Comment by dbreshears** [comment]
@klettier ,  thanks for letting us know.     How do you get an invalid publish profile?  The Deploy-FabricApplicaiton.ps1 was intended for use inside of VS and perhaps customize within the context of VS debugging,  are you hitting this on F5 or in VSTS  CI/CD,  or just running from the command line?  If running from the command line I would recommend to just target the Service Fabric PS cmdlet's in the SDK directly to publish.

**Comment by klettier** [comment]
Hi @dbreshears 

Thank you for your reply, I'm running it from the command line.
The interesting part of this script is the **PublishProfile** [parsing](https://github.com/Azure-Samples/service-fabric-dotnet-getting-started/blob/master/src/GettingStartedApplication/GettingStartedApplication/Scripts/Deploy-FabricApplication.ps1#L129) and it's why I'm using it directly.

Any plan to extract this function in the SDK ?

Thanks
