### ISSUE TITLE
Since upgrading to Service Fabric SDK 3.0 and VS 15.5.6 the local cluster mode is wrong

### ISSUE THREAD

**Issue by ktheeten** [Azure/service-fabric-issues#824]
I have my local cluster in 5-node mode, but visual studio thinks it is in 1-node when trying to debug or publish :

![image](https://user-images.githubusercontent.com/9086583/35800030-f3a899b4-0a67-11e8-9254-7fc3d3d27aa3.png)

Using: 
Microsoft Azure Service Fabric Tools for Visual Studio - 2.0
Service Fabric SDK: 3.0.456
VS2017 15.5.6

How can I force it to use the 5-node publish profile when debugging?

**Comment by MikkelHegn** [comment]
@dbreshears @Liphi please take a look at this.

**Comment by Liphi** [comment]
What's the Service Fabric runtime version?

**Comment by dbreshears** [comment]
I am not able to reproduce.   What is in the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Service Fabric SDK\LocalClusterNodeCount registry value?

**Comment by Liphi** [comment]
I can't repro either.

**Comment by ktheeten** [comment]
The registry key you mention was empty.  However, I reinstalled the SF runtime and now it is working as expected.  Please close the issue. Sorry for the inconvenience.
