### ISSUE TITLE
FabActUtil FileNotFoundException Microsoft.ServiceFabric.Actors

### ISSUE THREAD

**Issue by keggster101020** [Azure/service-fabric-issues#825]
As the title suggests, when going to build a Service Fabric project I get the following error 
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at FabActUtil.ToolContext..ctor()
   at FabActUtil.Tool.Run(ToolArguments arguments)
   at FabActUtil.Program.Main(String[] args)
```

This error happens on the command 
```
~/packages\Microsoft.ServiceFabric.Actors.2.8.232\build\\FabActUtil.exe /app:"xxx\ApplicationPackageRoot" /spp:"PackageRoot" /t:manifest /ap:"xxx" /sp:"xxx" /in:"\xxx.Exe" /arp:"\" /local5nodeappparamfile:"xxx\ApplicationParameters\Local.5Node.xml" /local1nodeappparamfile:"xxx\ApplicationParameters\Local.1Node.xml"
```

Any help would be appreciated

SF Information:
Service Fabric Version:  6.1.456.9494

Service Fabric SDK: 3.0.456.9494

Visual Studio: 15.5.6

**Comment by keggster101020** [comment]
I think this issue might be caused when a class inherits Actor & IActor (in my case they are both sub-inherited from two different base classes)

**Comment by amanbha** [comment]
@keggster101020 Could you share your complete project, in the command you shared, the /arp argument takes $(TargetDir) by default, looks like TargetDir is incorrect.

**Comment by keggster101020** [comment]
@amanbha I have sent you a mail with the project. I'm not sure if this is a project issue as I am able to build the same code on other machines?

Thanks!

**Comment by amanbha** [comment]
Closing as per discussion with @keggster101020 as it seems to be a corrupt VS install.
