### ISSUE TITLE
Service activation error:  ErrorCode=EndpointProviderNotEnabled

### ISSUE THREAD

**Issue by hongdai** [Azure/service-fabric-issues#826]
I have a stateless service that in the "Error" state. The Service Fabric event log shows:

8714957acfb8f59a0acaa6c27d4327:131623301243550238
Activator
Activate: Activate:Application13Type_App0:Stateless1Pkg@a5e31af8-5a9b-4a8d-b6ba-52460a00ae3a@6a8da7e3-9153-4f3c-8852-1ad11dd3f763:1.0:1.0:131623651882224175, ErrorCode=EndpointProviderNotEnabled, RetryCount=1

What could be the possible causes?

**Comment by masnider** [comment]
There's usually other errors that are actually causing the service to fail. What version of Sf are you on, as we should also be providing better error messages.

**Comment by hongdai** [comment]
I have figured it out it's the cluster configuration issue. Thanks for trying to help!
