### ISSUE TITLE
Referencing service with multi framework target couses MSB4057 build error.

### ISSUE THREAD

**Issue by Soarc** [Azure/service-fabric-issues#828]
Microsoft Visual Studio 2017 enterprise, 15.5.6

**Steps to reproduce**
1. Create azure service fabric project with netcore2.0 stateless service
2. Edit service's csproj and add new target to net461
`<TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>`
3. Build solution

**Expected Behavior**:
Solution should build for both frameworks or define method to choose target framework for compilation. 

**Actual Behavior**:
Fails build service fabric project with "error MSB4057: The target "GetTargetPath" does not exist in the project." error message.
[Here](https://gist.github.com/Soarc/61b635cc1143a60b626a4a812dd4528a) is detailed build log.

**Background**:
I want to use service fabric to orchestrate services on linux, so i need netcoreapp2.0. On the other hand project uses Specflow for testing, which currently does not support netcoreapp and only can target net461. So i need both platforms. 

Any suggestions or workarounds?

**Comment by dbreshears** [comment]
@Soarc.  I was able to repro and also workaround this by specifying both in the stateless1.csproj file

```
  <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
    <TargetFramework>netcoreapp2.0</TargetFramework>
```

Does this work for you?  Seems to be producing both builds for me without error

**Comment by Soarc** [comment]
Thanks for suggested workaround. Can't test it right now. I'll try it and let you know in few days.

**Comment by ashishnegi** [comment]
@Soarc It will be great if you can try above suggestion. Let us know if you face any other problem.

**Comment by Soarc** [comment]
@ashishnegi , @dbreshears  Sorry for late response. I have done a some testing and get following results:

Project build succeeded, but now i'm facing deployment issues. When i deploying to my local fabric cluster, i'm getting follwing error.

>  Project is targeting runtime 'win7-x64' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.

Removing `<RuntimeIdentifier>win7-x64</RuntimeIdentifier>` from service csproj, couses a bunch of build warnings and deployment error.

> warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "...\.nuget\packages\microsoft.servicefabric.data\3.0.456\ref\netstandard2.0\Microsoft.ServiceFabric.Data.dll", "AMD64"

> Register-ServiceFabricApplicationType : The EntryPoint Soarc.MultitargetService.exe is not found.

Also, if i reference service from project, targeting net461 framework, i'm getting following runtime error.

> An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by deepakjangid-MSFT** [comment]
You definitely don't need this for projects targeting multiple platforms.
```<RuntimeIdentifier>win7-x64</RuntimeIdentifier>```

For the processor architecture issue, you can add this to you project file.
```<PlatformTarget>x64</PlatformTarget>```

You can reference .NetStandard2.0 DLL from .Net4.6.1 App and .NetCore2.0 App.
For referencing scenario, I need more clarity on what are all the project types you are referencing. Please list all the projects, there output type and targeting platforms.

**Comment by Soarc** [comment]
Adding x64 platform target fixes processor architecture warnings. But deployment error still exists.
Here is my setup.
https://gist.github.com/Soarc/896d0e1b5809df8f2bf36fe25ff86960

I can also create github repo, if it is required.

The first file is service fabric service, that have multiple targets. 
Second file is tests project, targeting net461 and referencing first project.

**Comment by ashishnegi** [comment]
@Soarc Can you share a GitHub repo ? It seems you faced multiple issues and most of them are solved.
What is your current project / csproj ? Please share a GitHub repo where we can reproduce it.

**Comment by hrushib** [comment]
@Soarc, didn't hear back from on this. Marking this issue as closed, you can re-open this with details about GitHub repo containing code with repro of this issue.
