### ISSUE TITLE
Unable to download container image from private repository

### ISSUE THREAD

**Issue by UsamaAslam23** [Azure/service-fabric-issues#829]
I am trying to run SF cluster locally on  windows server 2017 with docker container. When I publish the application from VS17 I get the following error on SF explorer:

I am trying to deploy an application pointing to my private repo, e.g. hub.docker.com/r/myrepo/container
I am able to use the repository credentials specified in the manifest to login to the repo from docker cli.

Docker was installed prior and was working and running these same images. 
Before installed SF I removed all running containers and cleaned up images and private repository logins.
Also tried to publish the app by pulling the container from docker hub before publishing the app.

When SF tries to deploy the container it states:

> 
Error event: SourceId='System.Hosting', Property='Download:1.0:1.0'. There was an error during download.Failed to download container image hub.docker.com/r/myrepo/container

--

ServiceManifest
```
<EntryPoint>
  <ContainerHost>
    <ImageName>hub.docker.com/r/myrepo/container</ImageName>
  </ContainerHost>
</EntryPoint>
```
ApplicationManifest

```
<Policies>
  <ContainerHostPolicies CodePackageRef="Code">
    <RepositoryCredentials AccountName="myrepo" Password="mysecret" PasswordEncrypted="false" />
  </ContainerHostPolicies>
</Policies>
```

One other thing to note, the image is rather large at about 5gb, however the download fails almost immediately after publishing the application.

**Comment by fdkdervis** [comment]
I have the same problem, failed because it can't donwload the image from the private registry. Is there a way to specify the login also ?

**Comment by RajeetN** [comment]
@UsamaAslam23. you need to provide the imagename with version tag for SF to download. So your imagename should be r/myrepo/container:versiontag. 
@fdkdervis, yes you use RepositoryCredentials element in Application Manifest.

**Comment by fdkdervis** [comment]
@RajeetN, finally for me it was related to the certificate, I resolved my problem after I enabled the ssl in your private registry

**Comment by UsamaAslam23** [comment]
@RajeetN I have tried by adding latest tag as well, same error still.

**Comment by mani-ramaswamy** [comment]
@UsamaAslam23  you can't use the latest tag with Service Fabric. You will have to explictly specify a version as Rajeet suggested. The reason we force that is during an upgrade, you know which version your container is running (otherwise it will all be latest). However, we are working on making the description more helpful in SFX.

**Comment by mani-ramaswamy** [comment]
@UsamaAslam23  -  Closing this since I assume the issue was mitigated. Pls reopen if you are still hitting issues.
