### ISSUE TITLE
Environment variables: Fabric_ServiceName

### ISSUE THREAD

**Issue by nineralpha** [Azure/service-fabric-issues#830]
I need to access **Fabric_ServiceName** in my guest service(exclusive process) but can't find it. even when i enlist all environment variables this one is missing, i have also checked stateful service variables list it is also missing there.
according to documentation https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-environment-variables-reference i should be able to get this.
any idea why it is missing?

**Comment by RajeetN** [comment]
This variable value is only available if you create the service with ServicePackageActivationMode ExclusiveProcess.
