### ISSUE TITLE
Accessing secured service fabric cluster on aspnetcore (.NET Core) UserPasswordCredential not enabled

### ISSUE THREAD

**Issue by mvperez** [Azure/service-fabric-issues#833]
Hi,
I implement [this ](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-fabric/service-fabric-connect-to-secure-cluster.md) on aspnetcore targeting .net framework, it's working fine. With the release of service fabric runtime 6.1 I converted my project to .NET Core. But UserPasswordCredential is not recognize and it is by design based from [here ](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482). What is the alternative for .NET Core?
Thanks

**Comment by masnider** [comment]
From our [docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-connect-to-secure-cluster#connect-to-a-secure-cluster-non-interactively-using-azure-active-directory) is the real issue that UserCredential doesn't take a username/password as parameters?

Also - there should be some other APIs you can use to acquire the token. Perhaps AcquireTokenSilentAsync?

**Comment by masnider** [comment]
@jmprieur may be able to help out

**Comment by masnider** [comment]
At a minimum we'll probably have to update our docs to not show that mechanism.

**Comment by marvinvperez** [comment]
Hi @masnider, I'm not sure how to use AcquireTokenSilentAsync _(but I can research it)_ but I'm also not sure if that will work without providing the cluster ClientAppId. Connecting to secure cluster interactively is an option to me but following the documentation I could not make it to work both .NET Core and .NET Framework. In .Net Framework I'm getting this error: 
![image](https://user-images.githubusercontent.com/17961526/36082745-cc55c680-0fde-11e8-91a4-af16ccec6e78.png)
For .NET Core, it crashed the program.
![image](https://user-images.githubusercontent.com/17961526/36082782-1bc51388-0fdf-11e8-953c-e75837442519.png)

**Comment by marvinvperez** [comment]
Hi @amanbha, thanks for opening up an issue regarding UserPasswordCredential though seems no progress. However, as I've mentioned in this issue I'm also open to using interactive AD authentication where users are redirected to a microsoft login page. Those two screenshots above are an attempt to do that but I'm getting those errors both in .net full framework or dotnet core. Can you check how can I user interactive authentication? preferable dotnetcore.
Thanks.

**Comment by jmprieur** [comment]
Here are the flows you should use in a Web App: [Confidential application flows](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Confidential-client-applications-flows) (that is Web Apps, Web Apis and daemon/service applications). Username/password is really for desktop apps.
Please tell me if you need help moving to one of these flows.

**Comment by marvinvperez** [comment]
Hi @jmprieur and @amanbha, It's really okay to us not using username/password and in fact it is preferred. But I'm not really sure if you and me can figure out solution this without the service fabric team to try and help out by providing example for asp.net (.net core). [On Behalf Of](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki) seems a good option for us. I can get the access token but when I pass this token to FabriClient I'm getting "The specified credentials are invalid." error. Please code snippets below.

```
private static async Task<string> GetAccessToken(string tenantId, string clientId, string secretKey)
{
            string resource = "https://graph.microsoft.com";
            string authorityFormat = @"https://login.microsoftonline.com/{0}";
            string authority = string.Format(CultureInfo.InvariantCulture, authorityFormat, tenantId);
            var authContext = new AuthenticationContext(authority);
            var clientCredential = new ClientCredential(clientId, secretKey);
            var authResult = await authContext.AcquireTokenAsync(resource, clientCredential);
            return authResult.AccessToken;
}
```

```
                string tenantId = "C15CFCEA-02C1-40DC-8466-FBD0EE0B05D2";                
                string clusterApplicationId = "118473C2-7619-46E3-A8E4-6DA8D5F56E12";
                string secretKey = "zMgOefSeEruLmudi0D76pbGqZKP3ELbzq2aVwpKrfPU=";

                string token = await GetAccessToken(tenantId, clusterApplicationId, secretKey);

                var claimsCredentials = new ClaimsCredentials();
                string serverCertThumb = "A8136758F4AB8962AF2BF3F27921BE1DF67F4326";
                string connection = "clustername.westus.cloudapp.azure.com:19000";
                claimsCredentials.ServerThumbprints.Add(serverCertThumb);
                claimsCredentials.LocalClaims = token;

                try
                {
                    var fc = new FabricClient(claimsCredentials, connection);
                    var ret = fc.ClusterManager.GetClusterManifestAsync().Result;
                    Console.WriteLine(ret.ToString());
                }
                catch (Exception e)
                {
                    Console.WriteLine("Connect failed: {0}", e.Message);
                }
```
Error

![image](https://user-images.githubusercontent.com/17961526/36472265-e31c5fcc-1723-11e8-83e3-ba5343dd6b58.png)

**Comment by amanbha** [comment]
@marvinvperez Is it working now or you need help from the AAD team on this?

**Comment by marvinvperez** [comment]
I haven't look at it for long time and abandon this since no good response from my last post. As of today, Is there an update on this so I can give it another try?

**Comment by amanbha** [comment]
@marvinvperez This seems more like a ADAL issue, its complaining of invalid JWT token, could you debug what was the token you got grom AAD.

**Comment by jmprieur** [comment]
This is actually Azure AD complaining of an invalid token. Do you want to contact me directly? (Jean-Marc.Prieur at Microsoft.com)
