### ISSUE TITLE
Provider Registration hangs

### ISSUE THREAD

**Issue by DIThoS** [Azure/service-fabric-issues#834]
When I try to create a Service Fabric Cluster the deployment hangs, because the registration of the resource provider Microsoft.ServiceFabric cannot finish successfully. The state is 'Registering' and it's possible to Re-Register or Unregister the provider neither in Azure portal nor in Powershell. Any ideas what could I do?

**Comment by juho-hanhimaki** [comment]
This happens to me occasionally too (on azure). Maybe 30% of cluster deploys seem to never finish. Don't really have time to look at this closer but event logs had some errors.

**Comment by ChackDan** [comment]
Delete the RG and recreate.  That is the only clean way to get this moving. If you would like to figure out the rootcause, then file a CSS ticket and we will collect the logs necessary to answer that.
