### ISSUE TITLE
Visual Studio 2017 Crashes when creating a new Service Project

### ISSUE THREAD

**Issue by rexwhitten** [Azure/service-fabric-issues#835]
Visual Studio 2017 Crashes when creating a new Service Project via the project templates for .NET Core 2.  

**Environment** 
+ Windows 10 Enterprise 
+ Visual Studio 2017 Enterprise  ( Version 15.5.6 ) 
+ Microsoft Service Fabric Tools for Visual Studio  2.0
+ Service Fabric SDK 3.0.456 

**Steps (Creating a new Service Fabric Project in VS 2017)** 
+ Selected Service Fabric Project Template 
+ Selected .NET Core 2.0  (Stateless or Stateful) 
+ Name the Project 
+ Select 'Web API' 
+ Launches the "Service Fabric next steps page" 
+ Mouse cursor becomes a spinner for some time 
+ Shows the "Microsoft Visual Studio 2017 has stopped working" dialog then a   "Microsoft Visual Studio 2017 is restarting" dialog. 
+ VS 2017 restarts. 

Hard to grab anything from the output console, as VS is unresponsive while the "spinner" is on the cursor, so I cant navigate anywhere in VS during the crash. 

I have launched VS with logging and performed the above steps. The log contained no Errors, but a ton of warnings.  I can post if needed. 

Have tried deleting the component cache of Visual Studio., but this did not change behavior.  

Additionally,  I can reproduce this on different machines, running the same specs as above.  

I am happy to provide further details.

**Comment by dbreshears** [comment]
@rexwhitten ,  Can you launch another instance of VS 2017, Debug Attach to Process... and attach to the other instance of VS 2017, then trigger the crash .  Under the Debug menu select "Save Dump As...." and then share this .dmp file.    My only other suggestion at this point would be to try to repair the VS 2017 installation.

**Comment by rexwhitten** [comment]
Tracking this down in event viewer I was able to find that my organizations ForcePoint client was blocking downloads that occur during the new Service Fabric project setup.  Nuget packages were properly downloading however. 

We can allow the downlaods from microsoft's vortex site, however inquiring minds want to know what is being downloaded from the internet while creating a new Service Fabric Project?  (besides nuget packages we know about those) 

After disabling ForcePoint I can create a new Service Fabric project. However, this is not the solution.

**Comment by dbreshears** [comment]
@rexwhitten,    What service type and does it block on,  does it block on  just a simple stateless service or does it require asp.net core services?    Outside of the webpage that loads (including images) for the SF application next steps in the document window,  I don't know of anything we are downloading specifically.  You might try running fiddler and see if that helps narrow down and also I'll try pulling the network plug here and see what I get.   For a stateless service our Nuget package references are all local in the SF SDK folder

**Comment by rexwhitten** [comment]
@dbreshears  - Thanks for the response.  Nothing showed up in fiddler, however my success with fiddler is 50/50 in any case).  I cant see the whole path in the UI before it would crash, but its downloading from vortex. (Microsoft vortex that is). 

Besides my followup question, I think I am passed this issue. Appreciate everything you guys do.

**Comment by ravipal** [comment]
Closing since customer is not hitting this issue anymore.

**Comment by vcx** [comment]
I know it's closed already, but it would be nice if SF Tools in VS didn't "phone home" when you create a new Project. There are lots of customers, especially in finance and public sector verticals, that limit internet access in development teams. Remote calls like these limit SF adoption among people that are just trying to learn or do PoCs.

As a workaround, I found also that if you install Fiddler, open it and configure to intercept HTTPS calls, you'll be able to bypass ForcePoint and VS won't crash while creating a new SF project.
