### ISSUE TITLE
SDK Download Link Error

### ISSUE THREAD

**Issue by optimumcadence** [Azure/service-fabric-issues#836]
The install link from VS https://go.microsoft.com/fwlink/?linkid=861713
gives:
Server Error in '/' Application.

**Comment by rexwhitten** [comment]
That link was broken all day yesterday and affected many Microsoft downloads. The link you posted works, and works for me now.

**Comment by masnider** [comment]
Yes. This was an error with WebPI which is now fixed. Sorry for the blip, and we're working with them to try to figure out how to prevent such things in the future.
