### ISSUE TITLE
ConfigurationProperty.DecryptValue() doesn't gracefully fails when value is empty

### ISSUE THREAD

**Issue by andersosthus** [Azure/service-fabric-issues#84]
Hi,

Trying to call ```.DecryptValue()``` on an empty encrypted setting (see example below) does not fail gracefully or throw an exception.

What happens seems to be that an Event is logged in the Event Log:
```CryptDecryptMessage failed when trying to get decryptedMessageSize```. The code execution seems to stop at this point. No exceptions are thrown.

The setting I tried to decrypt:
```
<Parameter IsEncrypted="true" Name="TestSetting" Value="" />
```

Cluster Version: 5.3.301.9590
SDK: 5.2

**Comment by vturecek** [comment]
Hey Anders, what do you mean code execution stops at that point? Are you actually seeing execution hang on the DecryptValue() method call?

**Comment by andersosthus** [comment]
Hi Vaclav,

That might have been a quick assumption from me based on what I saw:

I had a ```settings.xml``` with 4 or 5 keys that had no value (```value=""```).
In my ```RunAsync()``` I looped through all the settings trying to read them into memory (calling ```.DecryptValue()``` on each of them).

I only got 1 error of the one above in the Event Log.
When I tried to get out a value from memory, I couldn't.

I'll try to do a repro of this issue tomorrow, and if I can repro it, I'll put it on GitHub.

**Comment by vturecek** [comment]
Thanks Anders, we're checking into it too.

**Comment by andersosthus** [comment]
Sorry Vaclav, I didn't have time to do more testing before we moved to 5.3, so I haven't been able to confirm/deny the initial observations I saw.

**Comment by vturecek** [comment]
@andersosthus - We looked into this and it appears DecryptValue() does throw an exception when the value is empty. The inner exception message reads "ASN1 unexpected end of data. (Exception from HRESULT: 0x80093102)." [See here for ASN.1 error codes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375564(v=vs.85).aspx).

Can you check again, or perhaps post a code snippet from where you're running into this problem?

**Comment by LekhaSahdev** [comment]
If you have spaces in your encrypted value this issue comes. Delete those spaces and try
