### ISSUE TITLE
Service Fabric Stateful ASP.NET core 2.0 service partitions are not auto healing

### ISSUE THREAD

**Issue by ravindraaditya** [Azure/service-fabric-issues#841]
In our production ready SF application we are now facing errors "Partition is below target replica or instance count"

we have recently updated to latest service fabric sdk / .NET Core SDK / VS2017 Community Edition.

To repro the issue we are able to, in simple vanilla service fabric application with ASP.NET Core 2.0 Stateful service publish it in debug / release mode to local dev cluster.

**Below is the error:**

> Services	
>  Error
>  Unhealthy services: 100% (1/1), ServiceType='ServiceFabricTest2.Web1Type', MaxPercentUnhealthyServices=0%.
>     Service	
>  Error
>  Unhealthy service: ServiceName='fabric:/ServiceFabricTest2/ServiceFabricTest2.Web1', AggregatedHealthState='Error'.
>         Partitions	
>  Error
>  Unhealthy partitions: 100% (1/1), MaxPercentUnhealthyPartitionsPerService=0%.
>             Partition	
>  Error
>  Unhealthy partition: PartitionId='8c39ac04-ac89-4800-8caf-5dcba4c24550', AggregatedHealthState='Error'.
>                 Event	
>  Error
>  Error event: SourceId='System.FM', Property='State'.
> Partition is below target replica or instance count.
> fabric:/ServiceFabricTest2/ServiceFabricTest2.Web1 3 3 8c39ac04-ac89-4800-8caf-5dcba4c24550
>   N/P InBuild _Node_4 131628102389300199
>   (Showing 1 out of 1 replicas. Total available replicas: 0)
> 
> For more information see: http://aka.ms/sfhealth

So, what we did was we attempted to run the application in debug mode with 0 breakpoints to see what is happening. however, we constantly get break at this line in Program.cs file of stateful service.

```
                // Prevents this host process from terminating so services keeps running. 
                Thread.Sleep(Timeout.Infinite);
```
Then we hit continue and we see application getting crashed and this repeats.

> The program '[18200] ServiceFabricTest2.Web1.exe' has exited with code -2146232797 (0x80131623).
> The thread 0x5484 has exited with code 0 (0x0).
> The thread 0x1520 has exited with code 0 (0x0).

In release mode also partitions are not auto healing for more than 24hrs.

Nodes are healthy and stateless services are also taking a bit of time to up initially however they are auto healing.

Any help / documentation link on how to fix this issue or at least workaround?

**Comment by xunlu** [comment]
As the comment says, the Sleep is to keep the process running and execution should never past this line.  For the error of "Partition is below target replica or instance count", how many nodes are there and how many replicas are you trying to bring up?

**Comment by ravindraaditya** [comment]
@xunlu , I do understand that. earlier when we tried to debug application it used to never break at Thread.Sleep.. but why now? sorry, if i had missed anything here.

Well, we enabled 5 nodes in dev cluster with default values. MinReplicaSetSize= 3, PartitionCount =1, TargetReplicaSetSize = 3.

**Comment by ravindraaditya** [comment]
@raunakpandya , I spinned new Windows Server 2016 VM. there, I'm able to see test SF application with stateful service up and running which is of fresh installation of all tools and pretty fast. I dono whether this will work or not - Now, what I'm going to do is auto repair existing visual studio 2017 community edition on Windows 10 Professional. please standby to see output.

**Comment by raunakpandya** [comment]
Any updates here? What was the .NET Core runtime version you are using?

**Comment by ravindraaditya** [comment]
Hi @raunakpandya ,

As said, I attempted to do repair VS2017 as well as reinstalling Service Fabric SDK. 

While reinstalling Service Fabric SDK i faced issue with `ese.dll` file located in 

> C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code

For this what i did was killed the `Docker.Service` which is running in random port.

After re-installation completely some how successfully. 

Now, I'm facing the following errors:

> 
> Service fabric:/System/DnsService
> 
> Kind	Health State  	Description
> Partitions	
>  Error
>  Unhealthy partitions: 100% (1/1), MaxPercentUnhealthyPartitionsPerService=0%.
>     Partition	
>  Error
>  Unhealthy partition: PartitionId='4af68a04-0b3f-4c1c-8328-2bcd81e41603', AggregatedHealthState='Error'.
>         Event	
>  Error
>  Error event: SourceId='System.FM', Property='State'.
> Partition is below target replica or instance count.
> DnsService 1 1 4af68a04-0b3f-4c1c-8328-2bcd81e41603
>   IB _Node_0 Up 131628853227156753
>   (Showing 1 out of 1 replicas. Total available replicas: 0)
> 
> For more information see: http://aka.ms/sfhealth
> 
> -----
> Kind	Health State  	Description
> Event	
>  Warning
>  Unhealthy event: SourceId='System.FabricDnsService', Property='Socket', HealthState='Warning', ConsiderWarningAsError=false.
> DnsService UDP listener is unable to start. Please make sure there are no processes listening on the DNS port 53.
> List of processes listening on the DNS port:
>   UDP    0.0.0.0:53             *:*                                    9656
> 
> ------
> 
> 
> Health State  	Source 	Property 	Source UTC 	TTL 	Sequence Number 	Remove When Expired 	Is Expired 
>  OK
> System.RA	State	Mon, 12 Feb 2018 05:02:02 GMT	Infinity	131628853229692298	false	false
> Replica has been created on_Node_0.
> For more information see: http://aka.ms/sfhealth
>  Warning
> System.FabricDnsService	Socket	Mon, 12 Feb 2018 05:02:48 GMT	Infinity	131628853684183001	false	false
> DnsService UDP listener is unable to start. Please make sure there are no processes listening on the DNS port 53.
> List of processes listening on the DNS port:
>   UDP    0.0.0.0:53             *:*                                    9656
>  Warning
> System.RA	ReplicaOpenStatus	Mon, 12 Feb 2018 05:04:33 GMT	Infinity	131628854735551696	false	false
> Replica had multiple failures during open on _Node_0. -2147467259
> For more information see: http://aka.ms/sfhealth

Then, What i did was I stopped `SharedAccess Internet Connection Sharing (ICS)` service to somehow rectify `Service fabric:/System/DnsService` partition to healthy state.

However, the main issue is still prevailing. we can't move with these many issues leaving my machine with service fabric unstable while upgrading to latest which I always need to do on-demand for every next available version. so, I'm dumping my Windows 10 Professional Machine with Windows Server 2016 which is pretty fast, super cool with service fabric.

Regarding .NET Core Version `SDK v2.1.4`

**Comment by vmendi** [comment]
Something like this happened to me recently on my development machine after installing Docker for Windows and the required Hyper-V. Uninstalling Hyper-V fixed the issue.

**Comment by raunakpandya** [comment]
DNS service had an issue with ICS alongside. This I believe was fixed in recent release. Regarding your original problem, we would need logs to investigate that further. For now, assuming you are not facing any issue. I am closing this. Please reopen if you still have this issue.
