### ISSUE TITLE
Deployment and management nuked in latest release

### ISSUE THREAD

**Issue by jackbond** [Azure/service-fabric-issues#842]
All my deployments from Visual Studio now hang during the copy stage, and when I try to connect with a FabricClient I get...

"Could not ping any of the provided Service Fabric gateway endpoints."

Any ideas what is going on?

**Comment by xunlu** [comment]
Is the cluster up?  What do you see from service fabric explorer?  Are the fabric processes running?

**Comment by jackbond** [comment]
I'm experiencing the same problem with multiple service fabrics. Everything looks fine in the fabric explorer. I just tried another deploy, and it is able to communicate enough to see that an app with the same name exists, uninstalls it, but then hangs during the copy.

**Comment by oanapl** [comment]
@jackbond , this seems similar to https://github.com/Azure/service-fabric-issues/issues/813

**Comment by oanapl** [comment]
@jackbond , [6.1 refresh](https://blogs.msdn.microsoft.com/azureservicefabric/2018/02/22/service-fabric-6-1-refresh-release) is now available. Can you please try to upgrade and see if that fixes your issue?

**Comment by oanapl** [comment]
@jackbond , we haven't heard from you in a while. I will close the issue, please try the new release which fixes the copy hang issue.
If you still have questions/issues, feel free to reopen this issue or open a new one.
