### ISSUE TITLE
Reverse Proxy logs/diagnostics for standalone cluster 

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#845]
Hi,

on a standalone cluster we see error entries in logs like the following:

`2018-2-12 11:46:40.583,Informational,1460,5900,ReverseProxy.ForwardRequestErrorRetrying,75f1fd71-4cc6-4078-bd69-d25bb3e106ef Forwarding request to service failed, retrying with re-resolve: phase = SendRequestHeaders, error = 3489661157, internal error = ERROR_WINHTTP_CANNOT_CONNECT`
 

`2018-2-12 11:48:04.601,Warning,9060,5900,ReverseProxy.ForwardRequestConnectionError,77a3a057-4a8a-491d-a63e-7169dd05296b Connection error while forwarding request, disconnecting client: phase = FinishSendRequest, internal error = ERROR_WINHTTP_CONNECTION_ERROR`

`2018-2-12 11:48:13.721,Informational,2504,5900,ReverseProxy.ForwardRequestErrorRetrying,9839c533-5a78-414f-b677-19f4720b04d3 Forwarding request to service failed, retrying with re-resolve: phase = SendRequestHeaders, error = 3489661157, internal error = ERROR_WINHTTP_TIMEOUT`

How can we enable similar diagnostic logging as described here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics ?

Can we tune the ReverseProxy timeout values?

thanks
Yannis

**Comment by masnider** [comment]
Adding Kavya for RP question and Deep for diagnostics.

**Comment by dealboy** [comment]
Hi @masnider , @dkkapur 

any updates on that?

Can we tune ReverseProxy timeout values?
Can we enable similar diagnostic logging in (for example) ELK ?

kind regards
Yannis

**Comment by MonDeveloper** [comment]
We also absolutely need to tune the RP timeout, now 6.0.232 (2.8.232) it seems to be 120 seconds.
Please, any online available guide about RP timeout is related to Azure Resourse Manager but I didn't find anything related to the OnPrem version of SF.

We urgently need it!

**Comment by kavyako** [comment]
@dealboy The error entries you pasted above are the reverse proxy diagnostic logs. can you track a request that failed with its activity ID (eg 75f1fd71-4cc6-4078-bd69-d25bb3e106ef) and see which endpoint it was resolved to. Next step would be verify if the service was up on that endpoint during that time or not.

**Comment by kavyako** [comment]
Since the diagnostic message says connection error, this implies service endpoint was not up. Please reopen the issue if you believe the service endpoint was up (and listening at the specified ip:port path) but the reverse proxy still failed to forward the request to the service.
