### ISSUE TITLE
Stateful Service won't start in 6.1.456

### ISSUE THREAD

**Issue by aloneguid** [Azure/service-fabric-issues#848]
I've upgraded to Service Fabric 6.1.456, running in onebox scenario and .NET Core 2.0. Creating a stateful service and running it without any modifications won't succeed:

![image](https://user-images.githubusercontent.com/3155189/36142709-ca1da686-10a0-11e8-82ee-f54c5f89470d.png)

There are no errors to be seen anywhere else, ETW only shows that the service will try to start in a loop:

![image](https://user-images.githubusercontent.com/3155189/36142748-e739c9e8-10a0-11e8-8985-5cb48d5ae4e3.png)

**Comment by raunakpandya** [comment]
Can you please share the cluster logs?

**Comment by aloneguid** [comment]
@raunakpandya happy to do that, could you please point me how to collect cluster logs from onebox?

**Comment by Marusyk** [comment]
Hello, I have the same problem.

**Comment by aloneguid** [comment]
@Marusyk same here, stateless work flawlessly so far.

**Comment by nrandell** [comment]
Try adding the following the either the csproj file or Directory.Build.props in the solution directory.

```
<PropertyGroup>
<RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
</PropertyGroup>
```
There appears to be an issue that is fixed in 2.0.5

**Comment by aloneguid** [comment]
@nrandell adding this has fixed the issue, brilliant!

**Comment by nrandell** [comment]
@aloneguid  I'm not sure why - issue #643 is where it was originally raised and has been pen for some time! I'm sure it's on track to be fixed at some stage!

**Comment by aloneguid** [comment]
Closing as seems to be a duplicate of #643

**Comment by Marusyk** [comment]
@nrandell I have added `<RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>` but it doesn't help. Any suggestions? Thx
