### ISSUE TITLE
Feature request: Support powershell script in <SetupEntryPoint>

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#85]
Currently only batch file and exe are allowed in <SetupEntryPoint>. But we are using powershell most of the time. So we have to create a setup.cmd to invoke powershell and then forward the exit code:

``` bat
Powershell.exe -ExecutionPolicy ByPass -File setup.ps1
IF %ERRORLEVEL% NEQ 0 (
  EXIT /B 1
)
```

**Comment by msfussell** [comment]
Just so that I understand, agreed this is non-ideal, but is there any particular scenario that you are experiencing that you cannot achieve?

**Comment by qrli** [comment]
Just for ease of use and no pit of failure. 
 I spent hours to figure out powershell does not work directly, as well as the magic to pass back failure code.

**Comment by vturecek** [comment]
The general rule here is "only things the OS can execute." We'll consider adding support for other common file types like PowerShell. For now I'll update the documentation to show how to do it through a cmd file.

**Comment by GeorgeTsiokos** [comment]
Powershell script in `<SetupEntryPoint>`:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security
