### ISSUE TITLE
Could not copy the file..because it was not found Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets

### ISSUE THREAD

**Issue by NNara** [Azure/service-fabric-issues#857]
I have the latest version of SDK and VS 2017 update.

I am trying to package/deploy from VS2017 and it fails with the error -

Error | MSB3030 | Could not copy the   file "C:\Users\XXXXXXXXXXX\SFApplication2\Application2\Stateless4.exe.config"   because it was not found. | Application2 | C:\Users\XXXXX\SFApplication1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets | 309 |  
-- | -- | -- | -- | -- | -- | --
Error | MSB3030 | Could not copy the   file "C:\Users\XXX\Repos\SFApplication2\Stateless4\obj\BWS\Debug\Stateless4.exe"   because it was not found. | Application2 | C:\Users\XXX\SFApplication1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets | 309 |  
-- | -- | -- | -- | -- | -- | --
Error | MSB3030 | Could not copy the   file "C:\Users\XXX\Repos\SFApplication2\Stateless4\obj\BWS\Debug\Stateless4.pdb"   because it was not found. | Application2 | C:\Users\XXXXXX\SFApplication1\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets | 309 |  

Package and publish works of a .Net core stateless service. It fails only for .Net framework services.

**Comment by caxepok** [comment]
Same problem here. Fail after update from 1.6.2 to 1.6.4

**Comment by ravipal** [comment]
We have a new version of nuget package 1.6.5. Please install this new nuget package and restart the solution. This should fix the issue.

**Comment by Telavian** [comment]
I have noticed that for some reason every time the Microsoft.VisualStudio.Azure.Fabric.MSBuild package is updated it gets installed correctly in packages.config however the sfproj is never updated.
I have to manually update it.

**Comment by ravipal** [comment]
During project load of *.sfproj, we check if a new version of package is installed and if so, then the *sfproj will be updated. Do you still see the *.sfproj is not updated after reloading the project/solution?

**Comment by ravipal** [comment]
1.6.5 version of nuget package has the fix. @NNara if you see this issue after upgrading to 1.6.5 nuget package please reopen this issue.
