### ISSUE TITLE
Old Docker container deployed with compose deploy

### ISSUE THREAD

**Issue by brandmo** [Azure/service-fabric-issues#863]
Hi there,

I have a docker compose app. Service fabric is pulling the wrong/old version of my container whenever I deploy it.

I was using the Build, Push and Lock VSTS build steps, but in order to use the reverse proxy I need to specify my own docker-compose file that is invalid by docker standards and include the following ports: - "80:80/http" and leave out the Lock step.

When using the Lock command it creates a docker-compose file that results in the correct images being pulled. When I don't use Lock and supply my own docker-compose file the correct image isn't pulled.

Even with a single image in my repository tagged as latest, I'm getting an old image, or maybe it's just ignoring the new one.

When i pull the image down to my PC and run it, it is correct.

Deleting my container repository and recreating it and pushing the new image to it works but obviously I'd rather not have to do that.

I can provide de-identified VSTS steps and docker-compose files if it will help.

**Comment by RajeetN** [comment]
Service Fabric requires that you provide explicit versions to your images to ensure the right images are pulled and to guarantee immutability. Providing "latest" as tag is not recommended.
