### ISSUE TITLE
Question - Azure Application Gateway with Service Fabric

### ISSUE THREAD

**Issue by AndrewJWaite** [Azure/service-fabric-issues#865]
Hi,

We have provisioned a secure (AAD) Azure Service Fabric cluster with three VMSS, provisioned into different subnets within the same Virtual Network.
- Management
- Public
- Private

We have multiple internet facing services deployed to the Public VMSS (13 and growing - not deployed to all nodes), we also have multiple private services deployed to the Private VMSS (again, not deployed to all nodes).

Secure (https) external access is via the Azure Load balancer and the Service Fabric Reverse Proxy (with SSL enabled).

LB + SF RP + Our Services

I would like to introduce Azure Application Gateway with Service Fabric. I've read there is a hard limit of 20 backend pools with the AG.

My initial thoughts are:

AG + LB + SF RP + Our Services

I have a couple questions:

1. What is the recommended approach for fronting Service Fabric with Application Gateway

2. Currently, the Service Fabric Reverse Proxy has SSL enabled. Long term I would prefer to install the SSL certificate only on the AG. However, this certificate is also used as the cluster certificate. What are the best practices for disabling SSL on the reverse proxy if the certificate is also the cluster certificate?

Many thanks, Andy

**Comment by vturecek** [comment]
Azure Application Gateway is somewhat limited when it comes to a high-density, dynamic environment like Service Fabric (lots of services that move around a lot in response to resource balancing and self-healing). AAG works at the IP/port level; it doesn't know about services or service discovery. You can make it work with some aggressive health probes, but that back-end pool limitation will be a problem.

We don't recommend using the Reverse Proxy to front your services, because there is no way to control which services can be accessed through the Reverse Proxy. Once you make the Reverse Proxy port available to the public Internet through the LB, all of your back-end services can be accessed through it.

At this point in time, there are a couple solutions available to you that don't require you to write your own gateway service:

 - Azure API Management. [APIM integrates with Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-overview), meaning it has a Service Fabric back-end option that understands Service Fabric's service discovery so it's aware of services and how to discover their endpoints (works for stateful services too). If you end up having to manage a lot of front-end services, this could be a good option for you as APIM is specifically designed for that scenario.

 - Host a proxy server that can route traffic at L7. This is the direction we're going with an integrated ingress proxy, but that's still a few months out at least at this point. In the meantime though, take a look at running Traefik in your cluster, which integrates with Service Fabric and should be able to provide SSL termination and L7 traffic routing: https://docs.traefik.io/configuration/backends/servicefabric/

**Comment by mburumaxwell** [comment]
@AndrewJWaite I was able to setup NGINX to handle almost a similar scenario, I wrote a post to explain it [https://maxwellweru.com/nginx-for-aspnetcore-applications-in-service-fabric/](https://maxwellweru.com/nginx-for-aspnetcore-applications-in-service-fabric/)

**Comment by AndrewJWaite** [comment]
Thanks @vturecek for the reply.

I would like to clarify this statement please.

> We don't recommend using the Reverse Proxy to front your services, because there is no way to control which services can be accessed through the Reverse Proxy. Once you make the Reverse Proxy port available to the public Internet through the LB, all of your back-end services can be accessed through it.
> 

What is the Reverse Proxy for then?
This article covers access services from outside of the cluster:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

At the moment, we don't have any services which expose http listeners that are not public. However, I can see that if we wanted a private API, even if this was deployed into the private VMSS/subnet the reverse proxy would still resolve and be able to connect to the service. Unless we explicitly denied access on the subnets NSG.

One of the drivers for using the Application Gateway was to limit the SSL ciphers available (via the AAG SSL policy). Do you know if this is possible with APIM?

Many thanks, Andy

**Comment by AndrewJWaite** [comment]
Thanks @mburumaxwell 

I will take a look at the article.

Many thanks, Andy

**Comment by ckittel** [comment]
>  I've read there is a hard limit of 20 backend pools with the AG.

So, we found out @AndrewJWaite  that it's actually a somewhat soft limit and can be raised to 40 (actual hard limit?).  I know that it's a complete answer/solution, but it's buying us time before something like an integrated ingress proxy is added to the platform.

**Comment by steve-hawkins** [comment]
to add to @vturecek answer you can now have an [API Management resource on your internal VNET exposed via an Application Gateway](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-integrate-internal-vnet-appgateway)

**Comment by mburumaxwell** [comment]
Hi @steve-hawkins , API Management with VNET support and an SLA would cost ~$2,795.17/month according to [this](https://azure.microsoft.com/en-us/pricing/details/api-management/). It would be better to have an integrated ingress proxy in the platform. There's traefik [here](https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/05/intelligent-routing-on-service-fabric-with-traefik/) which also works very well. I wonder, @vturecek , is this the recommended way to go about it?

**Comment by ohwellwhatever** [comment]
I see NGINX mentioned above, and Application Gateway v2 is based on NGINX.  The right solution for the product groups to offer is some sort of middle tier APIM sku with VNET integration that doesn't cost an arm and a leg.  Most customers will completely underutilize the other features of the premium APIM sku just to gain common sense, standard security functionality.

**Comment by AndrewJWaite** [comment]
As I raised the initial issue, I thought I would share the 'workaround' I adopted.

**Application Gateway**
- SSL Termination
- HTTP > HTTPS redirect
- Path based rules (allowing access to all services under an application or only specific services)
- Backend VMSS (Public)
- HTTP Settings for Service Fabric Reverse Proxy
- Custom health probe (accepting non 200 responses) - http://127.0.0.1/ping - results in 400 response


**Virtual Machine Scale Set** (Public)
With Service Fabric Reverse Proxy (HTTP)


**Monitor**
Alert on node unhealthy


Application Gateway > VMSS > Service Fabric Reverse Proxy > Service Fabric Service


Providing the reverse proxy health check returns a status lower than 499 (usually 400) the node is considered healthy.


This met our design goals of:

1. Restricting which cipher suites are being exposed _(Application Gateway TLS policy)_
2. Ability to restrict which Service Fabric Services were exposed _(Application Gateway path rules)_
3. Option of enabling WAF
4. Benefiting from the discovery, connect and retry of the Service Fabric Reverse Proxy _(VMSS with HTTP Service Fabric Reverse Proxy)_
5. Keeping the infrastructure as simply and cost effective as possible _(native Azure resources and not using the expensive API Management)_
 

**Cons**
- Likely not supported
- Breaks HTTP best practices. If you enter an incorrect application name or service in the path the response will be 502 (from the Application Gateway and not 404 from the reverse proxy).

As the team are in control of the majority of the clients these cons were accepted

I hope this helps

**Comment by heavenwing** [comment]
On-premise, I use IIS ARR as web gateway for Web Front App running on Service Fabric. I think that AG is similar with IIS ARR, so we should use AG to route web request into Service Fabric. Is it right?

**Comment by martinjosephogorman** [comment]
Application Gateway >**Internal load balancer** > VMSS > Service Fabric Reverse Proxy > Service Fabric Service.  Internal Load Balancer is supported.  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-patterns-networking

**Comment by masnider** [comment]
Closing down this issue at this time. The above guidance is correct with regards to the current options and recommendations. Adding @peterpogorski to determine if there are changes or amendments necessary to our docs to reflect current guidance. 

If folks are still having issues with a particular gateway, we do recommend following up with those teams regarding the best ways to configure those gateways. I can say that we do see people using a variety of different proxies and load balancers, so feel free to pick and configure the one that works best for your needs.

**Comment by festivus** [comment]
> Azure Application Gateway is somewhat limited when it comes to a high-density, dynamic environment like Service Fabric (lots of services that move around a lot in response to resource balancing and self-healing). AAG works at the IP/port level; it doesn't know about services or service discovery. You can make it work with some aggressive health probes, but that back-end pool limitation will be a problem.

@vturecek Why would you need aggressive health probes if calling the reverse proxy from the app GW? Wouldn't you only be worried if a node goes down, which shouldn't happen very often?

**Comment by pisees** [comment]
@masnider, to clarify when you said "The above guidance is correct with regards to the current options and recommendations. " -- this is confirming guidance from @vturecek,https://github.com/Azure/service-fabric-issues/issues/865#issuecomment-368096868.
