### ISSUE TITLE
Rolling upgrade published through VS or through CI/CD on VSTS does not complete

### ISSUE THREAD

**Issue by ezuidema** [Azure/service-fabric-issues#866]
I did an upgrade, after removing the local cluster (issue [#813](https://github.com/Azure/service-fabric-issues/issues/813)) but now the Azure Cluster is stuck in the process of upgrading the application. It has been there for hours and the application isn't very big, ~100MB.

It has no failures, no way of cancelling, it is just stuck in upgrading since: Tue, 20 Feb 2018 09:37:19 GMT

More info:
![sf-upgrade](https://user-images.githubusercontent.com/4758803/36423543-af144b10-1640-11e8-972f-2a24f531e012.JPG)

It is a single node dev cluster.
Version:  6.1.456.9494

I removed the application using the Service Fabric Explorer, and did a new deploy and that worked, but that is of course not an ideal way of doing an upgrade...

After that I followed the guides for CI/CD (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-deploy-app-with-cicd-vsts) and I encounter the same issue. The upgrade seems to be stuck. It has been over 2,5 hours already.

**Comment by oanapl** [comment]
The screenshot you provided shows that the upgrade is stuck on safety check. The partition will lose availability if we bring down the node. The upgrade waits for replica set check timeout (which is by default set to a huge value) before bringing the replica down. Check [upgrade params](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-parameters) for UpgradeReplicaSetCheckTimeout description.

As a starting point, take a look at the partition in question and check its configuration (replica target/min set size for stateful or instance count for stateless). Then look at how many replicas are up and their state.  

Check this article about [troubleshooting application upgrades](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-troubleshooting).

**Comment by ezuidema** [comment]
@oanapl Thanks a lot for the advice.

I managed to successfully deploy the Service Fabric solution using CI/CD on VSTS. 

Maybe it is an idea to add a note/remark to the documentation for settings up using a single node development instance of the cluster?
