### ISSUE TITLE
SF Reverse Proxy overrides X-Forwarded-Proto header

### ISSUE THREAD

**Issue by rikbosch** [Azure/service-fabric-issues#868]
Hi,

We're experiencing an issue with the Service Fabric Reverse Proxy.

Our current setup is like this:

1. https terminating azure app-service, with url-rewrite rules to internal SF http reverse proxy
2. SF http proxy
3. stateless aspnet core http web api

We're setting the X-Forwarded-Proto header in (1) to 'https', but the SF reverse proxy overrides the header with value 'http'.

The SF reverse proxy should not override the X-Forwarded-Proto header when it is already set (https://tools.ietf.org/html/rfc7239#section-5.4)

**Comment by kavyako** [comment]
This is a known issue, also being tracked by https://github.com/Azure/service-fabric-issues/issues/113 
Fixing this is in our backlog.

**Comment by kavyako** [comment]
@rikbosch: Am closing this issue. Let us use #113 for tracking the X-Forwarded-* header handling by the reverse proxy.
