### ISSUE TITLE
Service Fabric Application with multiple guest executables

### ISSUE THREAD

**Issue by pableess** [Azure/service-fabric-issues#87]
I have a service fabric application with 3 guest executable services.  Each one links to the same Code folder with different command line args.

Both VS and MS build does not handle this.  The link to the code folder only works for the first link defined in the sfproj file.  The other two service do not show or correctly package the Code directory

**Comment by EricJizbaMSFT** [comment]
That’s a [known limitation](https://msdn.microsoft.com/en-us/library/tfszfd6t.aspx) of the C# project system:
> The Visual Basic and Visual C# project system has a limitation in that there can only be one link with the same name per project. This means, for example, that you cannot have a link to file.vb in both folder A and folder B of the project.

As a workaround, you could copy the code folder to three separate locations and thus have three unique links.
