### ISSUE TITLE
Microsoft Azure Service Fabric Data Collection Agent is eating up the entire processor

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#870]
Clustertype: Standalone
Version: 6.1.456.9494

Every time after patching the OS, upgrading SF or just the configuration the Microsoft Azure Service Fabric Data Collection Agent is eating up the entire processor on some of our nodes. Because of that, sf is not able to successfully activate containers and the cluster goes totally crazy. Moving around containers without any luck. Is that an expected behavior?

**Comment by vslepakov** [comment]
We also have this problem. In our case FabricDCA wakes up periodically and causes very high CPU load for about 10-30 seconds. This has a negative impact on the overall performance of our system. If I am correct there should a fix in 6.1.457.xxxx but this version is not available in West Europe. 
Are there any updates on this?

**Comment by juho-hanhimaki** [comment]
Not related to containers, but our system is also experiencing high cpu usage by DCA. It uses remoting v2 at high rate (up to thousand calls per second per node). I guess every remoting call gets logged and it causes the DCA to spike the cpu and disk when it goes to work.

I had azure support ticket to investigate this and outcome was that sometime in the future the team will look into implementing more control or reduction to traces of the remoting feature in future.

**Comment by m1stegmann** [comment]
Any update to this issue. We have the same problem.

**Comment by Abdruggi** [comment]
Any news? it is a huge problem for us. we are stuck at the moment. it is not possible to update the cluster or the configuration.

**Comment by mattrowmsft** [comment]
@romendmsft this sounds like DCA container issue.  I think we have mitigation for this right?

**Comment by Abdruggi** [comment]
Exactly. Because of the high cpu usage and memory usage of the dca process the container never reach the running state before the orchestration restarts them.

**Comment by Abdruggi** [comment]
Looks like the problem was resolved with one of the updates in the meantime.
