### ISSUE TITLE
HandlerAsyncOperation EndProcessReverseProxyRequest failed

### ISSUE THREAD

**Issue by Abdruggi** [Azure/service-fabric-issues#871]
Clustertype: Standalone
Version: 6.1.456.9494

The service fabric admin event log is full of message like this:

`
4fef3308-f73a-4511-90e9-48e2b1d606d3 HandlerAsyncOperation EndProcessReverseProxyRequest failed with 3489660929
`

Any idea?

**Comment by kavyako** [comment]
This is usually seen when reverse proxy is forwarding the response to the client but the client has disconnected the request. Could you check if that is the case? Do you have any telemetry at the client side to verify this?
Also refer [Reverse proxy diagnostics](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics) doc for further troubleshooting tips. 
You can track a request by the GUID "4fef3308-f73a-4511-90e9-48e2b1d606d3" in the above case, look for other messages for this GUID. It will shed more light into what the request URL was and in which phase the request processing failed.

**Comment by kavyako** [comment]
Closing the issue since this is unlikely to be a reverse proxy issue. Please follow the diagnostics documentation for troubleshooting and reopen if you have any more concerns.
