### ISSUE TITLE
Cluster upgrade warning

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-issues#873]
SF Cluster Explorer shows warning icon for the cluster with message 
`The current cluster version 6.1.456.9494 support ends 5/30/2018 12:00:00 AM. Please view available upgrades using Get-ServiceFabricRegisteredClusterCodeVersion and upgrade using Start-ServiceFabricClusterUpgrade.`
Get-ServiceFabricRegisteredClusterCodeVersion command shows
```
CodeVersion
-----------
6.1.456.9494
```
What reason for showing the warning in case of there is no available upgrades?

**Comment by rakshitatandon** [comment]
@mgrishkov There is a newer version available "6.1.467.9494". It seems like your cluster failed to provision the package and hence, you don't see it in the above list. The system should retry once every 24 hours so you should be able to see the entry next time it retrys. Alternatively, you can download and provision the latest package directly from https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server

**Comment by mgrishkov** [comment]
Ok, thank you.
