### ISSUE TITLE
Upgrading to 6.1.467.9494, UpgradeOrchestrationService unhealty partition

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#875]
While upgrading to 6.1.467.9494, fabric:/System/UpgradeOrchestrationService has a permanent error. My cluster on Azure stuck in upgrade mode with provisioning failed error. All apps are working but my cluster stuck in upgrade mode. Also, all System Services are on 6.1.467.9494, if I try to upgrade from azure portal, I got an error cluster cannot be interrupted while upgrading
How can I fix this?

This is the error:
`

Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'. Exception encountered: System.IO.FileNotFoundException: The file '{0}' was not found in the Image Store ---> System.Runtime.InteropServices.COMException (0x80071C00): Exception from HRESULT: 0x80071C00    at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeFabric(IFabricAsyncOperationContext context)    at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.b__0(IFabricAsyncOperationContext context)    at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.FabricClientWrapper.d__24.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.FabricClientWrapper.d__22.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.ClusterCoordinator.d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Fabric.UpgradeService.ClusterCoordinator.d__17.MoveNext()
`

**Comment by rakshitatandon** [comment]
Is the error coming from UpgradeService or UpgradeOrchestrationService ? For azure clusters, there should be no UpgradeOrchestrationService. Is this a standalone cluster or azure ?

**Comment by vaishnavk** [comment]
Can you try restarting FabricUpgradeService primary and see if that fixes the issue? Could you share the region and resource id of the cluster? We will take a look.

**Comment by eliasnawfal** [comment]
The error is coming from  fabric:/System/UpgradeService, this Cluster is on Azure.
Region : UK South
Resource Id: /subscriptions/c5ffbabd-c3f6-4c8a-9bb1-42d0b5eafcd6/resourcegroups/StampunoUK/providers/Microsoft.ServiceFabric/clusters/stampuno

What I tried recently I changed the size of my VM, then the Cluster reverted to 6.0.232.9494, I tried upgrading again to 6.1.467.9494 with 0 Apps, the Cluster provisioning failed, same error appeared and cluster stuck in upgrade mode. 

I will try to restart FabricUpgradeService  now

**Comment by eliasnawfal** [comment]
I recreated my Cluster with latest Fabric version, working like a charm.
