### ISSUE TITLE
Resource Limits in docker compose file

### ISSUE THREAD

**Issue by aragula12** [Azure/service-fabric-issues#876]
Using the following compose file throws an exception when deploying to service fabric via New-ServiceFabricComposeDeployment powershell command.

**services:
&nbsp;&nbsp;mydns.com:
&nbsp;&nbsp;&nbsp;&nbsp;image:&nbsp;myappimage:1.0
&nbsp;&nbsp;&nbsp;&nbsp;deploy:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replicas:&nbsp;-1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;placement:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraints:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;NodeTypeName==nodetype1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resources:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;limits:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;cpu-shares=256
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;memory=2000
&nbsp;&nbsp;&nbsp;&nbsp;ports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;"8500:80"**

      
      
System.Fabric.FabricException: services.mydns.com.deploy.resources - **limits expects a mapping** ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BE6
   at System.Fabric.Interop.NativeClient.IInternalFabricApplicationManagementClient.EndCreateComposeDeployment(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
  
What is the right way to specify resource limits?

**Comment by puzovicnikola** [comment]
Hello @aragula12,

The correct format for specifying resources is to use dictionary, like this:

      resources:
        limits:
          cpu-shares:256
          memory:2000

You can check the docker compose documentation for more details: https://docs.docker.com/compose/compose-file/#resources

Nikola

**Comment by aragula12** [comment]
Thanks for your response @puzovicnikola 

Unfortunately, I still seeing the same exception - 'limits expects a mapping' even after I made the change as per your suggestion.

**Comment by BharatNarasimman** [comment]
@aragula12  can you share the compose file ?(updated with Nikola's suggestion)

**Comment by aragula12** [comment]
@BharatNarasimman 
Here is the updated compose file:

services:
&nbsp;&nbsp;mydns.com:
&nbsp;&nbsp;&nbsp;&nbsp;image:&nbsp;myappimage:1.0
&nbsp;&nbsp;&nbsp;&nbsp;deploy:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replicas:&nbsp;-1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;placement:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraints:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;NodeTypeName==nodetype1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resources:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;limits:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cpu_shares:256
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;memory:2000
&nbsp;&nbsp;&nbsp;&nbsp;ports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;"8500:80"

**Comment by BharatNarasimman** [comment]
There is a space ' ' missing

version: 3
services:
  mydns.com:
    image: myappimage:1.0
    deploy:
      replicas: -1
      placement:
        constraints:
          - NodeTypeName==nodetype1
      resources:
        limits:
          cpu_shares: 256
          memory: 2g
    ports:
      - "8500:80"

**Comment by aragula12** [comment]
@BharatNarasimman
Fantastic!  That worked!
