### ISSUE TITLE
SF cluster manager is not responsive - Failed to create log container on Os X 

### ISSUE THREAD

**Issue by donykyyenko** [Azure/service-fabric-issues#878]
I can't get my cluster running properly with container image servicefabricoss/service-fabric-onebox on Mac. 
 
I followed this guide
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac
I started SF manager and i can even open it in the browser - the only thing i don't see any details about application running, and receive toasters with Timeouts
{"Error":{"Code":"FABRIC_E_TIMEOUT","Message":"Operation timed out."}}

I receive many errors like this in output for ./run.sh in the container.  

> {00000000-0000-0000-0000-000000001000}:131640388489995780 - OnCreateAndOpenPhysicalLogAsync - Failed to create log container. Path: /home/ClusterDeployer/ClusterData/Data/N0020/Fabric/work/NS/nsshared.log, id: 00000000-0000-0000-0000-000000001000, size: 1073741824, maxStreams: 24576, maxBlockSize: 0, creationFlags: UseNonSparseFile, status: -1073741670
131640388489995780: Message: OpenPhysicalLogHandleAsync: CreateAndOpenPhysicalLogAsync Guid: 00000000-0000-0000-0000-000000000000 Alias:  NTSTATUS: ffffffffc000009a

I tired create files manually in these directories in the container and it worked ok.

When i tried to deploy application in output after some time i can see errors like this.  

> 500 Server Error: Internal Error for url: 
http://localhost:19080/ImageStore/****/ApplicationManifest.xml?api-version=3.0-preview
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 154, in upload
    show_progress)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 102, in upload_to_native_imagestore
    res.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Error for url: http://localhost:19080/ImageStore/****/ApplicationManifest.xml?api-version=3.0-preview
Error occurred in request., RetryError: HTTPConnectionPool(host='localhost', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/msrest/service_client.py", line 201, in send
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='localhost', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))

Looks like this error 'Failed to create log container.' is root cause, any suggestions on what might be wrong? 

OS: High Siera 10.13.3 
Docker version Version 17.12.0-ce-mac49 (21995)

**Comment by suhuruli** [comment]
Can you try running the following commands: 

1.	socat -d TCP-LISTEN:2376,reuseaddr,fork UNIX:/var/run/docker.sock on the host machine. This forks a new process. Run this command before you run the docker container. 
2.	Also run sed -i 's/172.17.0.1/docker.for.mac.host.internal/' ClusterManifest.SingleMachineFSS.xml while SSH'd inside the container. Run this command before running the ./setup.sh and ./run.sh scripts. 

Let me know if this fixes the errors.

**Comment by donykyyenko** [comment]
It doesn't. 
Here're some logs attached: 
[logs02_28.txt](https://github.com/Azure/service-fabric-issues/files/1768811/logs02_28.txt)

**Comment by suhuruli** [comment]
We are pushing out a fix for this soon. Apologies for the issue.

**Comment by suhuruli** [comment]
Pushed a fix and the updated image can be obtained from [microsoft/service-fabric-onebox](https://hub.docker.com/r/microsoft/service-fabric-onebox/)

**Comment by donykyyenko** [comment]
Thank you for the update. 

I run into the same issue with the new image. 
I tried it twice. Completely removed container and image from my machine. Then i pulled a new one, started it and got the same result. 
I can see that new image is pulled from docker hub
but in statistics it doesn't look like a fresh one  
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
microsoft/service-fabric-onebox                 latest              74f2c5c95012        5 days ago          1.22GB
On docker hub i can also see it's updated a few days ago.
Last pushed: 4 days ago

It shouldn't be cached. Can you confirm it's update one?

**Comment by suhuruli** [comment]
Can you try resetting your docker environment to rule out any caching if you are able to? 

Docker Icon -> Preferences -> Reset -> Reset to factory defaults

**Comment by suhuruli** [comment]
@donykyyenko can you confirm the fix?

**Comment by suhuruli** [comment]
Closing for now, feel free to comment if the problem comes up again :)
