### ISSUE TITLE
Reading Environment specific settings from outside of SF project

### ISSUE THREAD

**Issue by pableess** [Azure/service-fabric-issues#88]
I am porting a WebJob executable (written in python, no source code) to run in service fabric.  This program reads environment variables (set from Azure Portal) for environment specific configuration settings like connection strings etc.

I am trying to use a guest executable project to accomplish this.  I have looked into SetupEntryPoint for setting env variables.

I am wondering if there is a way to run a different setupEntryPoint script per environment (PublishProfile).

Also is there a way to read encrypted settings from non ServiceFabric C# projects like in the case of a guest executable.  IE, in a SetupEntryPoint (I would like to read and possible decrypt) all of the settings that have been overridden for the current environment and set them as environment variables on the service process.

**Comment by masnider** [comment]
Yeah there's no way to parameterize that today, you would have to create different manifests. I don't know of a good way to read encrypted settings if you can't access our APIs or modify the existing code. If you are trying to do it in a setupentrypoint and you can control and modify that, then you're looking for System.Fabric.Security.EncryptionUtility.EncryptText/DecryptText

**Comment by qrli** [comment]
I have went through a similar scenario. The issue with using SetupEntryPoint to set environment variables is that: the changes are not visible to services until the VM is restarted. It is because the FabricHostSvc process has already taken a copy of the environment variables, so modifying machine/user environment variables won't be updated to FabricHostSvc process's copy.

It is also tricky to make use of the <parameter> from manifest: many layers of redeclaration and very limited and unflexible. And it needs a proxy fabric app to read the values and then pass on to guest exe. I gave up.

In the end, I just set up the environment variables in a script invoked by VMSS extension. This way, I still lost the dynamic change capability, though.

**Comment by msfussell** [comment]
I think what you want is coming in the next release 5.4. In your Service manifest.xml you can declare and set environment variables that you want to use. Like this

  <ServiceTypes>
    
    <StatelessServiceType ServiceTypeName="Guest1Type" UseImplicitHost="true" />
  </ServiceTypes>
 
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>mycode.exe</Program>
      </ExeHost>
    </EntryPoint>
    
    <EnvironmentVariables>
      <EnvironmentVariable Name="VariableName" Value="VariableValue"/>
    </EnvironmentVariables>
  </CodePackage>

In the applicationmanifest.xml you can override these with different values if needed like this

  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="Guest1Pkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <EnvironmentOverrides CodePackageRef="Code">
      <EnvironmentVariable Name="VariableName" Value="VariableValue"/>
    </EnvironmentOverrides>
  </ServiceManifestImport>

**Comment by pableess** [comment]
Yes, I think that this is what we want.  Is there a SF roadmap that describes potential release dates?

Also it would be nice if there would be an optional way to keep the values of the environment variables (plain text) outside of manifests which are generally stored in source control or stored them as encrypted text in the manifests but would be automatically decrypted when they are set on the service process.

**Comment by msfussell** [comment]
You can keep the values outside of the manifest by providing these as application input parameters. That way you can have different publish profile files (cloud.xml, pre-production.xml) to set these values. 
The ability to set these are encrypted values makes total sense. This is not something we consider on environment variables. I will get back to you on this.
 
The 5.4 release will be out before the end of the year. There is a regular release of feature in dot releases approx. every 8 weeks.

**Comment by rh78** [comment]
Unfortunately the newest Service Fabric Tools cannot be installed. Always fail during installation (2.4.164, 2.3.311 works)

**Comment by dbreshears** [comment]
Based on the linked issue above it seems related to installing German.  We have a known issue we are working on right now to fix that.  Sorry for this.  I'll update when we get this resolved.

**Comment by rh78** [comment]
a no problem it was just 5 hours of swearing. but now with switch to english it works. thanks!
