### ISSUE TITLE
Need to restart a service inside an azure role instance

### ISSUE THREAD

**Issue by sujithnani** [Azure/service-fabric-issues#881]
To restart a service inside an azure role instance, I am trying to use Service fabric nuget package to utilize 
https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.servicemanagementclient.restartreplicaasync?view=azure-dotnet 

Code : 
var xc = GetCredentials(clientCertThumb, serverCertThumb, CommonName);
var fc = new FabricClient(xc, connection);
var restarttask = fc.ServiceManager.RestartReplicaAsync(nodeName, partionID, replicaOrInstanceId);
restarttask.Wait();

I am getting an exception as : " Restart can only be performed on persisted services. For volatile or stateless services use Remove"

Could you please suggest how to restart my service replica.

**Comment by masnider** [comment]
Should be pretty much what the message says. Use [this ](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.servicemanagementclient.removereplicaasync?view=azure-dotnet) instead.

**Comment by sujithnani** [comment]
Thanks team for the help. 

Facing another issue now when a service has multiple replicas which are having different partition id's. As we have to pass partition id as a parameter, Can you please suggest how can we find right Partition id out of multiple.

**Comment by sujithnani** [comment]
Request any one of the team to suggest an approach.

thanks in advance

**Comment by masnider** [comment]
If you know what node it's on you can query the node with something like GetDeployedReplicaListAsync to see what partitions are there before you try to restart it. If there are multiple, only you know which one you're actually trying to restart.

**Comment by masnider** [comment]
Hi there @sujithnani . Haven't heard back from you in a while so I presume that your problems here are sorted out. I'm going to close down this issue. If you have other questions, please feel free to open a new issue and we can take care of it!
