### ISSUE TITLE
stateful service assign all the primary replica to only one Node, but there are 5 nodes in the scale set.

### ISSUE THREAD

**Issue by TonyWu1991** [Azure/service-fabric-issues#882]
Hi,

Nowadays, I am stuck in the problem mentioned in the title that I have never seen before.

I have a 5 nodes cluster and set 15 partitions for one stateful service. TargetReplicaSetSize is 5 and MinReplicaSetSize is 3. But after deployment on Azure Service Fabric Cluster, all the 15 primary replicas are on only one VM, the ActiveSecondary replicas are on the rest four machines.

And the problem will not occur on my local computer development cluster.

How can I set primary replica averagely on each node?

**Comment by raunakpandya** [comment]
That shouldn't be the case by default.. Are you using any sort of placement constraints?

**Comment by TonyWu1991** [comment]
I didn't add the placement constraints. And if 15 primary replicas are on one machine, the load of that machine will be high. And when it trying to transfer primary replica to other nodes, the process will be affected and cause some problem. Do you have any idea to set primary replica averagely on each node by default?

**Comment by raunakpandya** [comment]
By default this should be distributed.. I cant think of a reason why its not.. @yltor any idea?

**Comment by yltor** [comment]
How many services are there in the cluster totally? Are other services also partitioned services? Was the overall primary counts (for all services) balanced in the cluster?

**Comment by puzovicnikola** [comment]
Closing the issue as there has been no further input. @TonyWu1991 Please reopen if needed and provide the answers in that case.
