### ISSUE TITLE
Strange log messages from Service Fabric in log with log level "Fatal"

### ISSUE THREAD

**Issue by VladyslavPyshnenko** [Azure/service-fabric-issues#883]
Hello!
We are gathering some logs from Service Fabric and found some strange messages with log level "Fatal". We see next message: "MAEVNTPROBE:MA_ETWSESSION_WAD_e62e566a_8c63_4be6_a11d_b16f3b33d349_IaaS__ad3appla_5"
This messages Service Fabric send only from one of five nodes. Fabric is sending them each 3 minutes.
We are able to see those messages almost in all our environments.
![image](https://user-images.githubusercontent.com/36155251/36723771-d883cac4-1bb9-11e8-9ad2-44361c20e61c.png)

Can you explain what is happening with this node? Do this messages mean that something wrong is going with some node from the cluster?

**Comment by dkkapur** [comment]
@VladyslavPyshnenko looks like something is wrong with the Windows Azure Diagnostics extension installed on the machines. Are you losing any events from that node that you expected to see?

**Comment by VladyslavPyshnenko** [comment]
@dkkapur I am not losing any messages from this node. Just can see this strange messages in log all the time.  And for me looks strange that I can see messages with "Fatal" log level, and at the same time everything works fine. How could it be possible?

**Comment by dkkapur** [comment]
@VladyslavPyshnenko looks like these are the probes being emitted by WAD to the ETW provider. I'm not sure why only one of your nodes is doing this, is there anything special about your configuration on that particular node? Nonetheless, you can add 'providerHeartbeats=”false”' to your ETW Provider Configuration in your "WadCfg" of your ARM template.json for your cluster, and run an update, to get rid of these events. Let me know if you have issues with this step.

**Comment by VladyslavPyshnenko** [comment]
@dkkapur I just found that I was sending logs to ELK only from one node. When I changed it, I have found that I can see this messages with "Fatal" log level from all nodes. How can I verify that  Windows Azure Diagnostics extension works fine to check your theory?

**Comment by VladyslavPyshnenko** [comment]
Also, I get a dump from this messages. Maybe it can help to define the source of this strange messages.

  <Event MSec= "33999.0113" PID="3164" PName=        "" TID="4656" ActivityID="20fe135f5ba44b98b33973e4e367bd8a" EventName="EventSourceMessage"
  TimeStamp="03/06/18 14:35:28.559441" ID="0" Version="0" Keywords="0xFFFFFFFFFFFFFFFF" TimeStampQPC="272,018,799,561"
  Level="Critical" ProviderName="Microsoft-ServiceFabric-Actors" ProviderGuid="0e1ec353-9f02-55d7-fbb8-f3857458acbd" ClassicProvider="False"
  ActivityID="20fe135f-5ba4-4b98-b339-73e4e367bd8a"
  Opcode="0" Task="65534" Channel="0" PointerSize="8"
  CPU="0" EventIndex="27" TemplateType="DynamicTraceEventData">
  <Payload Length="168">
       0:  4d  0 41  0 45  0 56  0 | 4e  0 54  0 50  0 52  0   M.A.E.V. N.T.P.R.
      10:  4f  0 42  0 45  0 3a  0 | 4d  0 41  0 5f  0 45  0   O.B.E.:. M.A._.E.
      20:  54  0 57  0 53  0 45  0 | 53  0 53  0 49  0 4f  0   T.W.S.E. S.S.I.O.
      30:  4e  0 5f  0 57  0 41  0 | 44  0 5f  0 30  0 36  0   N._.W.A. D._.0.6.
      40:  36  0 33  0 35  0 66  0 | 32  0 62  0 5f  0 66  0   6.3.5.f. 2.b._.f.
      50:  36  0 32  0 61  0 5f  0 | 34  0 36  0 30  0 39  0   6.2.a._. 4.6.0.9.
      60:  5f  0 62  0 30  0 32  0 | 36  0 5f  0 62  0 61  0   _.b.0.2. 6._.b.a.
      70:  37  0 32  0 34  0 34  0 | 39  0 62  0 38  0 33  0   7.2.4.4. 9.b.8.3.
      80:  65  0 39  0 5f  0 49  0 | 61  0 61  0 53  0 5f  0   e.9._.I. a.a.S._.
      90:  5f  0 61  0 64  0 33  0 | 61  0 70  0 70  0 6c  0   _.a.d.3. a.p.p.l.
      a0:  61  0 5f  0 34  0  0  0 |                           a._.4... 
  </Payload>
</Event>

<Event MSec= "33999.0136" PID="3164" PName=        "" TID="4656" ActivityID="20fe135f5ba44b98b33973e4e367bd8a" EventName="EventSourceMessage"
  TimeStamp="03/06/18 14:35:28.559443" ID="0" Version="0" Keywords="0xFFFFFFFFFFFFFFFF" TimeStampQPC="272,018,799,584"
  Level="Critical" ProviderName="Microsoft-ServiceFabric-Services" ProviderGuid="13c2a97d-71da-5ab5-47cb-1497aec602e1" ClassicProvider="False"
  ActivityID="20fe135f-5ba4-4b98-b339-73e4e367bd8a"
  Opcode="0" Task="65534" Channel="0" PointerSize="8"
  CPU="0" EventIndex="28" TemplateType="DynamicTraceEventData">
  <Payload Length="168">
       0:  4d  0 41  0 45  0 56  0 | 4e  0 54  0 50  0 52  0   M.A.E.V. N.T.P.R.
      10:  4f  0 42  0 45  0 3a  0 | 4d  0 41  0 5f  0 45  0   O.B.E.:. M.A._.E.
      20:  54  0 57  0 53  0 45  0 | 53  0 53  0 49  0 4f  0   T.W.S.E. S.S.I.O.
      30:  4e  0 5f  0 57  0 41  0 | 44  0 5f  0 30  0 36  0   N._.W.A. D._.0.6.
      40:  36  0 33  0 35  0 66  0 | 32  0 62  0 5f  0 66  0   6.3.5.f. 2.b._.f.
      50:  36  0 32  0 61  0 5f  0 | 34  0 36  0 30  0 39  0   6.2.a._. 4.6.0.9.
      60:  5f  0 62  0 30  0 32  0 | 36  0 5f  0 62  0 61  0   _.b.0.2. 6._.b.a.
      70:  37  0 32  0 34  0 34  0 | 39  0 62  0 38  0 33  0   7.2.4.4. 9.b.8.3.
      80:  65  0 39  0 5f  0 49  0 | 61  0 61  0 53  0 5f  0   e.9._.I. a.a.S._.
      90:  5f  0 61  0 64  0 33  0 | 61  0 70  0 70  0 6c  0   _.a.d.3. a.p.p.l.
      a0:  61  0 5f  0 34  0  0  0 |                           a._.4... 
  </Payload>
</Event>

**Comment by dkkapur** [comment]
@brahmnes for further comments.

@VladyslavPyshnenko to validate if WAD is working - are you getting any other events from Service Fabric in ELK at all? Or just these?

**Comment by VladyslavPyshnenko** [comment]
@dkkapur I am getting other events also (like ActorTypeRegistered and etc.)

**Comment by dkkapur** [comment]
@VladyslavPyshnenko how about other events from the Operational Channel - any events for app deployment, upgrades, scaling?

**Comment by VladyslavPyshnenko** [comment]
@dkkapur We are not listening Operational Channel, so I can't say.

**Comment by dkkapur** [comment]
@VladyslavPyshnenko regardless, you seem to be getting actor events from WAD, so looks like it should be fine!

**Comment by dkkapur** [comment]
Going to close this for now - please let me know if you want to reopen it for a reason, or feel free to open up a new issue! Thanks!
