### ISSUE TITLE
VSTS: Registering application type - Operation timed out

### ISSUE THREAD

**Issue by HaakonL** [Azure/service-fabric-issues#886]
Unable to deploy through VSTS after you rolled out the latest version. First it was timing out during image upload, after setting the timeout param in the vsts task it started to time out in the registering application type step.

Also unable to deploy from Visual Studio without first removing the local cluster.

Are we ever going to get a stable product from you?

**Comment by oanapl** [comment]
@HaakonL , are you trying to deploy to Azure cluster? Is you cluster healthy? What is the health of the fabric:/System/ImageStoreService service?
Can you give us more details about runtime, SDK versions and VSTS tooling version on client and runtime version in your cluster?
Is this the same cluster where you had issues with the disabled node?

**Comment by oanapl** [comment]
@HaakonL , I haven't heard back from you. I will close this issue, feel free to re-open or open a new one if you still have trouble.

**Comment by HaakonL** [comment]
Hi @oanapl,

I didn't respond to this as I saw that there were several other similar issues registered. I forgot to write in the initial post that to deploy from my local machine, I also had to edit the Powershell script and set a TimeoutSec 3600 parameter on the Upgrade task.

The other threads shows that this is a known bug, and that people has waited for a fix for several months. When will you roll out a fix where the timeout can be specified in the Cloud.xml? Until you do that we are unable to use VSTS to deploy without first remoting into each of our service fabric instances and modify the upgrade script in the SDK. Which is not an alternative.

**Comment by oanapl** [comment]
@HaakonL , @amanbha is adding a timeout parameter for register application type. Since there are other issues opened for this, let's track the progress there.

**Comment by PTC-JoshuaMatthews** [comment]
@oanapl  Has there been progress?

**Comment by oanapl** [comment]
Our latest service fabric release exposes the provision/unprovision timeout in our scripts. I will let VSTS team comment on whether this is now consumed by their scripts.
