### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by Terricide** [Azure/service-fabric-issues#89]
We had a more traditional application spread across vm's across the globe. We recently added a service fabric cluster to do some of the back-end processing. As we have been deploying the new version of our app and using the cluster it seems to slow down or get hung after a couple of days.

When I look at the cpu usage we only seem to be around 40-50% 

Any ideas?

**Comment by vturecek** [comment]
You should open a support ticket through the Azure portal, if you're hosting on Azure. It's virtually impossible to tell you why your application is running slowly from here.
