### ISSUE TITLE
No placement properties information is displayed when expecting Node through the Service Fabric Explorer.

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/service-fabric-issues#891]
It would be great to have placement properties displayed in Service Fabric Explorer on Node view (currently this can be found in Cluster -> Manifest but this isn't right I think).

P.S. This was found on Azure Standalone Cluster for Windows Server version 6.1.467.9494

**Comment by rishirsinha** [comment]
Please open an issue at

https://github.com/Azure/service-fabric-explorer/issues

Thanks,
Rishi
