### ISSUE TITLE
Can't seem to create a cluster in UK, choose a size options are all greyed out

### ISSUE THREAD

**Issue by dannycrone** [Azure/service-fabric-issues#893]
When I go to create a cluster in UK South when it prompts me to choose a size, all options are greyed out with "Not Avaliable". Not that if I choose East US, it seems to allow me to choose an option. This is the image from the UK attempt:
![image](https://user-images.githubusercontent.com/16937257/36858124-383aeb96-1d72-11e8-9baa-dc3c8730cbc6.png)

**Comment by ChackDan** [comment]
Jenna – can you take a look. It looks like the SKU picker is not working .

https://github.com/Azure/service-fabric-issues/issues/893

**Comment by ChackDan** [comment]
I can’t do anything there without more information – it could be that the sizes are being disallowed by the backend API (which is the more common case). Do you have any additional information here?

From: Chacko Daniel
Sent: Thursday, March 1, 2018 11:09 AM
To: Azure/service-fabric-issues <reply@reply.github.com>; Azure/service-fabric-issues <service-fabric-issues@noreply.github.com>; Jenna Netland <jenetlan@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [Azure/service-fabric-issues] Can't seem to create a cluster in UK, choose a size options are all greyed out (#893)

Jenna – can you take a look. It looks like the SKU picker is not working .

https://github.com/Azure/service-fabric-issues/issues/893

**Comment by dannycrone** [comment]
What more information do you need, I can provide what I can

**Comment by ChackDan** [comment]
Jenna – what additional information do you need, can you let Danny know. Respond to the github thread directly.

**Comment by i-e-b** [comment]
I had the same issue in UK West and UK south, where a large number of size were shown, all "Unavailable".
Switched to West Europe, and the list was then only 3 options, all of which were enabled.

**Comment by ChackDan** [comment]
@i-e-b  - Sorry for the delay. in discussions with the portal team, they think this may be an issue with quotas in your subscription, So could you please file a ticket at [https://portal.azure.com/#create/Microsoft.Support ](https://portal.azure.com/#create/Microsoft.Support) . The CSS team would then review you subcription and advice you on next steps.

**Comment by i-e-b** [comment]
@ChackDan - opened as 118032117855120

**Comment by ChackDan** [comment]
Thankyou Sir. Let us use that ticket to get this issue to closure.

**Comment by dannycrone** [comment]
I get this for UK South, UK North and North Europe but it seems to be okay for West Europe??

**Comment by ChackDan** [comment]
Please add this information to the ticket, the support team will appreciate this information.
