### ISSUE TITLE
Breakpoint is not working when debug SF app which debug model is Remove Application

### ISSUE THREAD

**Issue by Damon227** [Azure/service-fabric-issues#897]
Hi,
My Service Fabric app's breakpoint is not working which debug model is Remove Application, but it's working when the debug model is Refresh Application.

In particular, my actor install a nuget  pkg which is PostSharp(5.0.45),
before I install PostSharp, the breakpoint is working in Remove Application debug model.

When I build actor, the pdf file will be generate, but when I debug application with Remove Application debug model, the pdf file will not copy to local cluster, this situation only appeared on actor which installed PostSharp.

I update something in actor's csproj file:

![image](https://user-images.githubusercontent.com/20295242/36889990-401b3670-1e37-11e8-9643-1ee9805b3c51.png)

It's still not work.

Env info:
Local Cluster : 6.1.467.9494 
Service Fabric SDK : 3.0.467

**Comment by MikkelHegn** [comment]
@ravipal: Can you please help

**Comment by ravipal** [comment]
@Damon227 Looks like the nuget package PostSharp is messing with the pdb file generation. You need to set the property DebugType=full to generate the property pdb file. I was able to repro the breakpoint not hitting issue, but once I added the DebugType=full, it works.

You added this property conditionally, can you please set this property without any condition. Also is there any error in output window indicating the pdb file generation issue?

**Comment by Damon227** [comment]
@ravipal When I set the property without any condition, it works. Thank you!
