### ISSUE TITLE
SF reverse proxy: accessing https service

### ISSUE THREAD

**Issue by qrli** [Azure/service-fabric-issues#90]
Our security policy requires https even for internal service communication. When I access a `https` service via service fabric reverse proxy, it fails. It works well for `http` service though.

From the event log, it seems the reverse proxy tries to access the `https` service with target VM name, which fails the domain name validation, because the https certificate is not associated with the VM name but public domain name of the cluster.

Any solution for this scenario? 
PS: I'd expect it just works.

**Comment by VipulM-MSFT** [comment]
The reverse proxy today does not support target services to be HTTPS based. We will be adding this feature in the future releases, but do not have a timeline or ETA at this time.

**Comment by qrli** [comment]
@VipulM-MSFT Good to know that.
To add a few more info: The minimun feature to satisfy our requirement is an setting to disable domain name validation for reverse proxy to access https services.

**Comment by kavyako** [comment]
Hi,

We are working on enabling reverse proxy<-> internal service HTTPS endpoint communication.
Here are the main options we plan to expose, would appreciate early feedback here:
- During the SSL handshake, Reverse proxy presents its certificate to the internal service. This is the same certificate that the reverse proxy uses for its HTTPS endpoint.
- Reverse proxy will provide an option to validate the certificate that the service presents in its https endpoint. For this validation, the CN Name or Subject Alternative Name in the certificate must match the service fabric service name (of the format: fabric:/myapp/myservice). Wildcards will be supported, for instance Reverse Proxy will successfully verify certificates with the subject name fabric:/myapp/* while connecting to services under fabric:/myapp.

Does this sound reasonable?  Are you looking for anything else when it comes to end to end HTTPS communication?

**Comment by qrli** [comment]
@kavyako Thanks for considering this!
For the 1st point: Do you mean reverse proxy presents its HTTPS certificate as **client certificate** to internal HTTPS endpoint? If that's what you mean, it is unrelated to our case because we don't check client certificate. Instead, we use the Azure Load Balancer port mapping and VSG to control access.

For 2nd point: It will introduce another difficulty as it needs special certificates. I know we can generate them by openssl easily. But we are a big company, which has tight security control. Our certificates have to be generate through a centralized system controlled by global security team. And I'm not confident that `fabric:/myapp/*` could pass that system. 
My naive idea is: the internal HTTPS endpoint simply uses the same certificate as the reverse proxy.

**Comment by qrli** [comment]
Another point to consider: we will have several **applications** sharing the same cluster, and we may add new one anytime. We don't want to re-provision the cluster only to add new certificate. So I prefer our services share the same certificate.

**Comment by kavyako** [comment]
Makes sense. Also looks like most root CAs issue certificates with FQDN s in Subject Name or SANs. They deny requests for URIs in SANs.
We will try to simplify the approach and maybe stick to the certificate issued to the domain name.
Thanks.

**Comment by qrli** [comment]
Any progress on this?

**Comment by kavyako** [comment]
This is on track for the next release during //Build 2017 (mid May timeframe).

**Comment by colindooley11** [comment]
@kavyako -  Hi what is the progress on this as we are planning on rolling our own Reverse Proxy to allow this.....Having this available would save alot of effort.

**Comment by alecor191** [comment]
I believe this should be supported with 5.6. From [5.6 release notes](https://blogs.msdn.microsoft.com/azureservicefabric/2017/05/10/release-of-sdk-2-6-204-and-runtime-5-6-204-for-windows-and-a-preview-of-whats-next/): 

> A number of new features and improvements have gone into the Reverse Proxy, including **HTTPS forwarding**, client certificate authentication, and support for custom user-defined HTTP verbs.

But I haven't found more info than that.

**Comment by kavyako** [comment]
With 5.6, reverse proxy can connect to secure services. 
For more information, please refer to : [Connect to a secure service with the reverse proxy ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy-configure-secure-communication)

Let us know if you have any feedback.

**Comment by kavyako** [comment]
Also, here are some ARM template samples demonstrating how to specify the different config options :[EnableSecureReverseProxy ARM templates](https://github.com/ChackDan/Service-Fabric/tree/master/ARM%20Templates/ReverseProxySecureSample)

Closing this thread now.
