### ISSUE TITLE
Securing different instances of a service within an application (Question)

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#901]
Hi, 
Iam working on a scenario where there would be multiple instances (not replica) of a service type. Each downloading a file from internet and working on that file. My question is that is there a way to secure the file downloaded i.e only allow the service that downloaded the file to access the file, my thoughts were that there would be something like creating a user for each instance and only that user account can access that file. I have looked into this article (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security#create-local-users)   but it seems that this only secures one service from another

**Comment by rishirsinha** [comment]
The security boundary for SF apps is the application instance. Application instance 1 can isolate against application instance 2 by providing run as accounts which are overwritten at application create time. Once that happens we will provide the correct ACLs to ensure that the work directory of different applications are only accessible by the run as user specified. 

However, if you do not want to create new application instances as Lu said this is not possible.
