### ISSUE TITLE
.NET CORE Microsoft.ServiceFabric.Services.Remoting

### ISSUE THREAD

**Issue by hanxinimm** [Azure/service-fabric-issues#911]
```
namespace Actor1.Interfaces
{
    /// <summary>
    /// 
    /// 
    /// </summary>
    public interface IActor1 : IActorService
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        Task<int> GetCountAsync(CancellationToken cancellationToken);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="count"></param>
        /// <returns></returns>
        Task SetCountAsync(int count, CancellationToken cancellationToken);
    }
}
```
Or

```
namespace Actor1.Interfaces
{
    /// <summary>
    /// 
    /// 
    /// </summary>
    public interface IActor1 : IService
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        Task<int> GetCountAsync(CancellationToken cancellationToken);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="count"></param>
        /// <returns></returns>
        Task SetCountAsync(int count, CancellationToken cancellationToken);
    }
}
```

build exception

2>Actor1 -> C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\bin\Debug\netcoreapp2.0\win7-x64\Actor1.dll
2>Assert Failure
2>Expression: [Recursive resource lookup bug]
2>Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic
2>Stack Trace:
2>   at System.SR.InternalGetResourceString(String key)
2>
2>   at System.SR.GetResourceString(String resourceKey, String defaultString)
2>
2>   at System.ArgumentNullException..ctor(String paramName)
2>
2>   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
2>
2>   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
2>
2>   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
2>
2>   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
2>
2>   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2>
2>   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2>
2>   at System.SR.InternalGetResourceString(String key)
2>
2>   at System.SR.GetResourceString(String resourceKey, String defaultString)
2>
2>   at System.ArgumentNullException..ctor(String paramName)
2>
2>   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
2>
2>   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
2>
2>   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
2>
2>   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
2>
2>   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2>
2>   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2>
2>   at System.SR.InternalGetResourceString(String key)
2>
2>   at System.SR.GetResourceString(String resourceKey, String defaultString)
2>
2>   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
2>
2>   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
2>
2>   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
2>
2>   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
2>
2>   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2>
2>   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2>
2>   at Microsoft.ServiceFabric.Actors.Runtime.ActorTypeInformation.Get(Type actorType)
2>
2>   at FabActUtil.Tool.LoadActors(Assembly inputAssembly, IList`1 actorFilters, IList`1 actorTypes)
2>
2>   at FabActUtil.Tool.LoadActors(ToolContext context)
2>
2>   at FabActUtil.Tool.Run(ToolArguments arguments)
2>
2>   at FabActUtil.Program.Main(String[] args)
2>C:\Users\HanXin\.nuget\packages\microsoft.servicefabric.actors\3.0.467\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(22,5): error MSB3073: 命令“dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp2.0\win7-x64\\Actor1.dll" /arp:"C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\bin\Debug\netcoreapp2.0\win7-x64\\" ”已退出，代码为 -2146232797。

<ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric" Version="6.1.467" />
    <PackageReference Include="Microsoft.ServiceFabric.Actors" Version="3.0.467" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="3.0.467" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.0.467" />
  </ItemGroup>

**Comment by ashishnegi** [comment]
This is netcore bug. @hanxinimm Try fix provided at https://github.com/dotnet/corefx/issues/23608#issuecomment-325422701

Or update your dotnet runtime to 2.0.3.

**Comment by hanxinimm** [comment]
@ashishnegi 

i know it is netcore bug. 

it still does not work

![image](https://user-images.githubusercontent.com/13499426/37386375-1e27850e-2793-11e8-90e4-eed2d64b857a.png)

**Comment by ashishnegi** [comment]
@hanxinimm Can you share result of command `dotnet --info` ? 

Also, please share log generated by below command after setting environment variable: `COREHOST_TRACE=1`

command: `COREHOST_TRACE=1 dotnet "obj\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp2.0\win7-x64\Actor1.dll" /arp:"C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\bin\Debug\netcoreapp2.0\win7-x64\"`

**Comment by hanxinimm** [comment]
@ashishnegi 


![image](https://user-images.githubusercontent.com/13499426/37388686-7272e5b4-279c-11e8-82eb-13dadae1a5c5.png)


[log.txt](https://github.com/Azure/service-fabric-issues/files/1810271/log.txt)

**Comment by ashishnegi** [comment]
Thanks for sharing logs.

@hanxinimm Can you also share `C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json`  and `C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.dev.json` ?

From logs shared above : 

```
3>Runtime config is cfg=C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json dev=C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.dev.json
3>
3>Attempting to read runtime config: C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json
3>
3>Attempting to read dev runtime config: C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.dev.json
3>
3>Runtime config [C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json] is valid=[1]
3>
3>Ignoring host interpreted additional probing path C:\Users\HanXin\.dotnet\store\x64\ as it does not exist.
3>
3>Executing as a standalone app as per config file [C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.runtimeconfig.json]
3>
3>--- Resolving hostpolicy.dll version from deps json [C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.deps.json]
3>
3>Resolved version 2.0.0 from dependency manifest file [C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\FabActUtil.deps.json]

3>CoreCLR path = 'C:\Users\HanXin\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\coreclr.dll', CoreCLR dir = 'C:\Users\HanXin\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\'
3>
```

**Comment by hanxinimm** [comment]
@ashishnegi  

[FabActUtilTemp.zip](https://github.com/Azure/service-fabric-issues/files/1810637/FabActUtilTemp.zip)

**Comment by ashishnegi** [comment]
@hanxinimm Can you try building after removing any other sdk from `C:\Program Files\dotnet\sdk` except 2.0.3 or later (latest is best) ?

**Comment by hanxinimm** [comment]
@ashishnegi 
 it still does not work

**Comment by ashishnegi** [comment]
@hanxinimm we are looking into this issue. Will revert back once we have a solution.

**Comment by ashishnegi** [comment]
@hanxinimm I tried to repro this locally. My box only has runtime `2.0.3` under `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`. I have folders `2.0.3` and `NuGetFallbackFolder` under `C:\Program Files\dotnet\sdk`. The issue does not repro.

Can you follow these 3 steps one by one ?

1. This one is simplest and fastest. Add a global.json file in your `<project-root-directory>` with content :

{
  "sdk": {
    "version": "2.0.3"
  }
}

and try building. The folder and subfolders containing global.json will be build with 2.0.3 sdk.

2. If it does not work, uninstall dotnet, clean `dotnet\shared` and `dotnet\sdk` directories and `%USER%\.dotnet` and reinstall latest dotnet.

3. If you still face the problem, please provide details I asked before like `dotnet --info` and content of `C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\obj\FabActUtilTemp\` and output of command :

```
COREHOST_TRACE=1 dotnet "obj\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp2.0\win7-x64\Actor1.dll" /arp:"C:\Users\HanXin\Documents\Visual Studio 2017\Projects\Application3\Actor1\bin\Debug\netcoreapp2.0\win7-x64\"
```

Thanks

**Comment by hanxinimm** [comment]
[log.txt](https://github.com/Azure/service-fabric-issues/files/1814176/log.txt)

**Comment by ashishnegi** [comment]
Your `System.Private.CoreLib.dll` is still picked up from : `C:\Users\HanXin\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\System.Private.CoreLib.dll;` 
`2.0.0` in above path is the problem.

@hanxinimm Can you add `<RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>` to your csproj ? This should change above paths to 2.0.3

Also, what is your machine culture ? Is it not en-US ? Asking because, some people are mitigating this issue by adding following to `Main` :

```
          Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
          Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US"); 
```

Since, i am not able to repro this on my machine, hence, this back and forth.

**Comment by hanxinimm** [comment]
@ashishnegi 
my machine culture  ZH-CN

![image](https://user-images.githubusercontent.com/13499426/37454709-40607e4e-2876-11e8-853a-1eb0d5116034.png)

new error:

[log.txt](https://github.com/Azure/service-fabric-issues/files/1814735/log.txt)

**Comment by ashishnegi** [comment]
Phew!!! new error.. some progress :)

You are now getting coding errors : 
```
2>System.ArgumentException: The actor type 'Actor1.Actor1' does not implement any actor interfaces or one of the interfaces implemented is not an actor interface. All interfaces(including its parent interface) implemented by actor type must be actor interface. An actor interface is the one that ultimately derives from 'Microsoft.ServiceFabric.Actors.IActor' type
```

Q1. Was this error not visible in VS ?

Potential solution :
If you derive from IActorService , you need to implement two [interfaces ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.actors.iactorevents?view=azure-dotnet): 
```     
     DeleteActorAsync(ActorId, CancellationToken) 
     GetActorsAsync(ContinuationToken, CancellationToken)
```

Otherwise, derive from [IActor.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.actors.iactor?view=azure-dotnet) if you want default logic.

Have a look at [actor docs ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-get-started). It is related to full framework but code snippets will work in .net core.

**Comment by hanxinimm** [comment]
@ashishnegi 

cannot inherit interface Microsoft.ServiceFabric.Services.Remoting.IService


![image](https://user-images.githubusercontent.com/13499426/37455694-a6f54322-2878-11e8-922c-dffb80108337.png)
![image](https://user-images.githubusercontent.com/13499426/37455743-c67848b6-2878-11e8-89c3-5a9dce89171b.png)
![image](https://user-images.githubusercontent.com/13499426/37455758-d181839e-2878-11e8-9990-c532a068d488.png)
![image](https://user-images.githubusercontent.com/13499426/37455859-10adec42-2879-11e8-834a-a2e206a1cea7.png)

**Comment by ashishnegi** [comment]
@hanxinimm  You can now remove `COREHOST_TRACE=1` from the command you have. This will reduce the amount of logs present.
I think the bug we are tracking is solved for you now. This is now some coding error. Please open a separate bug if our documentation is not clear. 
Mixing multiple bugs in open will confuse future OPs when they look for solution.
Closing this issue.
