### ISSUE TITLE
Property Management API in PowerShell

### ISSUE THREAD

**Issue by Igorbek** [Azure/service-fabric-issues#914]
Is any plan to support functionality to manage service properties in PowerShell?
Looks like `sfctl` has it [supported](https://github.com/Azure/service-fabric-cli/pull/53), but not PowerShell.

**Comment by oanapl** [comment]
The work is in our backlog. You can execute [the C# APIs](https://docs.microsoft.com/dotnet/api/system.fabric.fabricclient.propertymanagementclient?view=azure-dotnet) in Powershell for now.

**Comment by oanapl** [comment]
@Igorbek , we have a [new, REST-based Powershell module](https://blogs.msdn.microsoft.com/azureservicefabric/2018/12/11/announcing-new-rest-based-service-fabric-powershell-module/) that has support for the property management API. See the list of [supported cmdlets](https://github.com/Microsoft/service-fabric-client-dotnet/blob/develop/docs/SFPowershellUsage.md). 
We don't plan to add support for property management API in the old Powershell module.
