### ISSUE TITLE
High memory usage on fabric.exe

### ISSUE THREAD

**Issue by robgonfer** [Azure/service-fabric-issues#917]
On our 5 node cluster running SF version 6.1.467.9494 we are seeing a high memory usage for the fabric.exe process (see screenshots below). This is happening in two of the servers and in those fabric.exe has been steadily growing memory usage up to 1GB. In the other 3 servers it is just consuming around 40MB

The services deployed in this cluster are all stateless and we do not use reliable collections nor actors. They are regular .net WEB API apps and an Orleans cluster.

Is this memory usage expected? Is there any way to find out the reason? I took a dump but didn´t really find anything special (not an expert on windbg) other than one heap taking like 600MB. In the event viewer I do not find anything obvious.

![image](https://user-images.githubusercontent.com/25771228/37387443-aeb9bd62-275c-11e8-85af-ed6665b31998.png)

![image](https://user-images.githubusercontent.com/25771228/37387479-d5125a82-275c-11e8-8317-c85fe246082c.png)

**Comment by senj** [comment]
I see the same
![image](https://user-images.githubusercontent.com/5556013/37399967-991891f0-2783-11e8-8470-759635cb94b7.png)

**Comment by robgonfer** [comment]
Update: after the latest software upgrade looks like this issue is not happening anymore. 

Closing.

**Comment by NanashiGIT** [comment]
Even after upgrading our cluster we are still facing the issue of memory leaking fabric.exe which leads to massive slowdowns. We run a 5 Node cluster with 4 gb ram. The version is 6.1.480.9494.

@robgonfer Are you sure just a cluster version upgrade solved your problems or did you do anything else that might have fixed it?
