### ISSUE TITLE
Switching LocalCluster from 5-node to 1-node fails - "access denied deleting fabric.exe"

### ISSUE THREAD

**Issue by sathiathirumal** [Azure/service-fabric-issues#919]
Service Fabric Runtime 6.1.467
Service Fabric SDK 3.0.467

Node_0\fabric.exe and Node_3\Fabric.exe are still running per process explorer. I am unable to terminate them manually ("access denied"). 

ETL logs show:

ThreadID="21,644" id="" type="FabricDeployer" message=**"SafeDeleteDirectory failed deleting file: C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\Fabric.exe**. Exception: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) at System.Fabric.Interop.NativeCommon.FabricFileDelete(IntPtr path, SByte deleteReadonly) at System.Fabric.Common.FabricFile.DeleteHelper(String path, Boolean deleteReadonly) at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0() at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs) at System.Fabric.Interop.Utility.RunInMTA(Action action) at System.Fabric.Common.FabricFile.Delete(String path, Boolean deleteReadonly) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter)." FormattedMessage="SafeDeleteDirectory failed deleting file: C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\Fabric.exe. Exception: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) at System.Fabric.Interop.NativeCommon.FabricFileDelete(IntPtr path, SByte deleteReadonly) at System.Fabric.Common.FabricFile.DeleteHelper(String path, Boolean deleteReadonly) at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0() at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs) at System.Fabric.Interop.Utility.RunInMTA(Action action) at System.Fabric.Common.FabricFile.Delete(String path, Boolean deleteReadonly) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter). " 

ThreadID="21,644" id="" type="FabricDeployer" message="System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) at System.Fabric.Interop.NativeCommon.FabricFileDelete(IntPtr path, SByte deleteReadonly) at System.Fabric.Common.FabricFile.DeleteHelper(String path, Boolean deleteReadonly) at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0() at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs) at System.Fabric.Interop.Utility.RunInMTA(Action action) at System.Fabric.Common.FabricFile.Delete(String path, Boolean deleteReadonly) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.CleanupDeployment(DeploymentParameters parameters) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace) at System.Fabric.FabricDeployer.Program.Main(String[] args)" FormattedMessage="System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) at System.Fabric.Interop.NativeCommon.FabricFileDelete(IntPtr path, SByte deleteReadonly) at System.Fabric.Common.FabricFile.DeleteHelper(String path, Boolean deleteReadonly) at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0() at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs) at System.Fabric.Interop.Utility.RunInMTA(Action action) at System.Fabric.Common.FabricFile.Delete(String path, Boolean deleteReadonly) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.SafeDeleteDirectory(String directoryName, String directoryFilter, String fileFilter) at System.Fabric.FabricDeployer.RemoveOperation.CleanupDeployment(DeploymentParameters parameters) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters) at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace) at System.Fabric.FabricDeployer.Program.Main(String[] args) "
--

ThreadID="4,548" id="" type="FabricSetup.FabricSetupOperationExecutor" text="Error 0xffffffff while running FabricDeployer::Uninstall, Ignoring" FormattedMessage="Error 0xffffffff while running FabricDeployer::Uninstall, Ignoring "
--

**Comment by rishirsinha** [comment]
Can you check if reboot helps?

**Comment by sathiathirumal** [comment]
Rebooting does help. I also found out that I have better success if I first “Stop Local cluster” and then attempt to switch it. Perhaps this is what the switching process should do automatically?

Sent from Mail for Windows 10

**Comment by maburlik** [comment]
We've had some updates in the SDK over the last few versions to stabilize the cluster setup/reset experience. Please let us know if you still hit the same issue by creating a new item.

**Comment by MattHartz** [comment]
This issue still exists :(
