### ISSUE TITLE
New csproj format does not support default configuration preventing building of sfproj

### ISSUE THREAD

**Issue by rufio620** [Azure/service-fabric-issues#920]
I am running into an issue where I cannot build the sfproj via msbuild when including a ASP.NET core service. Each project defines only platform x64 but when packaging via msbuild I get the following errors. This is due to the fact that the new csproj does not seem to have way of defining the default configuration like the older format did. This is preventing our build automation from working in service fabric.

msbuild "C:\Users\horvathg\Desktop\BDB\src\BDBApp\BDBApp.sfproj" /t:Package /p:PackageLocation=C:\Temp\applicationpackage /p:platform="x64" /p:configuration="Debug" /p:VisualStudioVersion="15.0" 

![image](https://user-images.githubusercontent.com/1992395/37433086-f2eab532-27b0-11e8-851a-26aedfd0216b.png)

**Comment by rufio620** [comment]
This appears to be related to this issue https://github.com/aspnet/Home/issues/1804

**Comment by rufio620** [comment]
Also appears to be related to this issue https://github.com/Azure/service-fabric-issues/issues/64

This issue was closed but was never really addressed. The suggested work around to add the use "ShouldUnsetParentConfigurationAndPlatform=true" does not appear to work anymore.

**Comment by ravipal** [comment]
@rufio620, can you please try 1.6.5 package, we fixed a regression in packaging that might address this issue.

**Comment by rufio620** [comment]
I can confirm I am using 1.6.5 and still facing the issue.

**Comment by ravipal** [comment]
@rufio620, Is it possible to share a sample repro project?

**Comment by rufio620** [comment]
Having trouble reproducing the issue on a sample project. It appears that adding any cpu platform back to the website project in my original application fixes the issue. This is a little strange when the configuration for all other projects is x64 but it does work around the issue.
