### ISSUE TITLE
Not able to Up and run the microservice with WebListener 

### ISSUE THREAD

**Issue by fazilmajeed** [Azure/service-fabric-issues#923]
Hi ,
When trying to up and run the microservice in service fabrics with WebListener. I am getting an exception 

: 'Method 'StartAsync' in type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' from assembly 'Microsoft.AspNetCore.Server.WebListener, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

Why I used WebListener is, I need to use HTTPS locally to develop the microservice with .netcore web api.

I can able to up and run it with kestrel, But I can't configure the https locally on kestrel..

**Comment by masnider** [comment]
UseWebListener was renamed to UseHttpSys. Check out these threads:

https://github.com/dotnet/core/issues/835
https://github.com/aspnet/Hosting/issues/1128

**Comment by masnider** [comment]
Hi @fazilmajeed - hopefully this worked for you?

**Comment by masnider** [comment]
Closing this down as we haven't heard back from you and the breaking aspnet change is almost certainly the main problem. If you're still running into this after verifying that change, please reopen the issue. If you're having other problems, please file a new issue. Thanks!
