### ISSUE TITLE
Logging and monitoring

### ISSUE THREAD

**Issue by vi1996ash** [Azure/service-fabric-issues#924]
I want to log my message using Ilogger and see my message on OMS. How can i do it?

**Comment by dkkapur** [comment]
EventFlow should be able to help here: https://github.com/Azure/diagnostics-eventflow. 
Use ILogger as your input, and OMS as your output.

**Comment by vi1996ash** [comment]
Hi Deep,
I configured input as ilogger and output as oms. How or where  can i see
output log message at oms.

Regards,
Vikash kumar jangid

**Comment by dkkapur** [comment]
Are they not in the OMS workspace you configured with EventFlow? 
Perhaps you can also add stdout as another output to EventFlow, to make sure the logs are flowing correctly!

**Comment by dkkapur** [comment]
Going to close this for now - please let me know if you want to reopen it for a reason, or feel free to open up a new issue! Thanks!
