### ISSUE TITLE
Question: How to add API Management to Service Fabric?

### ISSUE THREAD

**Issue by jmaocanada** [Azure/service-fabric-issues#927]
I am trying to utilize the virtual network created by Service Fabric. My idea is to add the API management into the virtual network illustrated in below link. If it gets successful, I can hide my reverse proxy internally and only expose selected APIs to public network.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-overview 

https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet

However, after working on it for a few days, we realized it is not possible to add API management to the same subnet the virtual machine scaleset resides. I can only add API management to a different subnet. In this case, apparently I cannot use fabric:/ url to access my services. And I also found I cannot use the internal reverse proxy port (19085 by default). 

There must be a solution because this approach is documented in SF website. But I do need more details to get this done. 

Thanks in advance!

**Comment by kavyako** [comment]
@vturecek any ideas?

**Comment by maksimkim** [comment]
@jmaocanada, API Management always requires dedicated subnet. 
However by creating network security group for each of your subnets you can allow incoming traffic to SF subnet only from API Management subnet. 
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-nsg

**Comment by kavyako** [comment]
@jmaocanada  Does the above comment address your concern? 
Let us know if you still have any issues.

**Comment by jmaocanada** [comment]
@kavyako not really. We are using certificates authentication now to secure our API access. But this question is still there. Is there a solution to use internal IP access SF load balancer from API management within the VNET? Then we don't need to renew the certificates on the regular basis.

**Comment by kavyako** [comment]
@vturecek again to help out here.

**Comment by masnider** [comment]
@jmaocanada Check out some of the combinations offered in [this issue](https://github.com/Azure/service-fabric-issues/issues/865). 

I think the restriction that some people have pointed out is a part of APIM (that it can't share subnets) but the other suggestions about restricting the other subnets via NSGs should be sufficient. SF does also support internal LBs, though that's a function of how the Standard LB is configured (fundamentally, SF doesn't really know or care about the network or the ingress path so long as the nodes have connectivity). 

Closing this down for now. If you're still having this issue feel free to open it back up. If you've found a solution that worked for you that would be good to share as well! If you have any other problems or questions, please feel free to open a new issue.
