### ISSUE TITLE
Consider enabling DTD processing on ApplicationManifest.xml

### ISSUE THREAD

**Issue by Vhab** [Azure/service-fabric-issues#93]
We're struggling to manage the ever growing complexity of our `ApplicationManifest.xml`.
In particular we end up copy-paste large chunks of `ConfigOverride` and various blocks of `Policies` inside this file.

Hoping to combat the repetition somewhat, we tried using some DTD magic to include/repeat bits of XML from an additional external XML file.

Unfortunately, attempting to do so we're greeted with:

```
1>  Error while deserializing our\path\to\ApplicationManifest.xml, please verify thats its a valid ServiceFabric ApplciationManifest. For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
```

Please consider allowing DTD or alternative ways to make managing large ApplicationManifest.xml more convenient.

**Comment by masnider** [comment]
I don't know of a reason why DTD alone would result in invalid manifests. Can you share the before and after manifest? Does the produced manifest and package pass Test-ServiceFabricApplicationPackage?

**Comment by VipulM-MSFT** [comment]
DTD processing is not allowed to mitigate the security risks. We have issue 576 opened to track the enhancement. 

https://github.com/Azure/service-fabric-issues/issues/576
