### ISSUE TITLE
System.Runtime.InteropServices.COMException in Microsoft.ServiceFabric.Data.Impl.dll Element not found Exception from HRESULT: 0x80070490

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#938]
I upgraded a stale project to VS 2017, MSBuild 15.0, many NuGet packages and now my stateful service fails to instantiate with the following exception:

>Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.ServiceFabric.Data.Impl.dll
Element not found. (Exception from HRESULT: 0x80070490)

Then after several attempts another exception is thrown:

>Exception thrown: 'System.Fabric.FabricTransientException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Fabric.FabricTransientException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Fabric.dll
Exception from HRESULT: 0x80071BC5

and all services die, VS debugger deattaches.

Here's the list of packages were used then:

    <package id="Microsoft.ServiceFabric" version="5.3.301" />
    <package id="Microsoft.ServiceFabric.Data" version="2.3.301" />
    <package id="Microsoft.ServiceFabric.Services" version="2.3.301" />

and now:

    <package id="Microsoft.ServiceFabric" version="6.1.472" />
    <package id="Microsoft.ServiceFabric.Data" version="3.0.472" />
    <package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="3.0.472" />
    <package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="3.0.472" />
    <package id="Microsoft.ServiceFabric.Rnm.Internal" version="6.1.472.9494" />
    <package id="Microsoft.ServiceFabric.Services" version="3.0.472" />
    <package id="Microsoft.ServiceFabric.Services.Remoting" version="3.0.472" />

Also sfproj body then:

    <ProjectVersion>1.3</ProjectVersion>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>

and now:

    <ProjectVersion>2.0</ProjectVersion>
    <SupportedMSBuildNuGetPackageVersion>1.6.4</SupportedMSBuildNuGetPackageVersion>
    <MinToolsVersion>1.5</MinToolsVersion>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>

I tried to downgrade, install additional packages as prescribed in https://github.com/Azure/service-fabric-issues/issues/668 but nothing helps.

**Comment by MikkelHegn** [comment]
Hi @abatishchev - to set expectations, it's a big upgrade jump :-) @amanbha to see if he has ideas on what might break this?

**Comment by raunakpandya** [comment]
What is the runtime version here?

**Comment by abatishchev** [comment]
>it's a big upgrade jump

sure, I realize that! however this service doesn't do much. I suspect the error comes from logging/telemetry (Geneva, Kusto)

>What is the runtime version here?
Here's what I have installed locally:
Runtime 6.1.472.9494
SDK 3.0.472.9494
Tools for VS2015 2.0.10124.2 (if that matters, I'm using VS2017 primarily)

**Comment by abatishchev** [comment]
The paradox is that exactly the same source runs fine in VS2015 and fails in VS2017. How can this be?

**Comment by abatishchev** [comment]
I think this can be closed. I haven't seen this exception for a while. I think it was caused by DLL versions mismatch somewhere internally/locally.
