### ISSUE TITLE
Event 65534 - the message resource is present but the message is not found in the string/message table

### ISSUE THREAD

**Issue by am11** [Azure/service-fabric-issues#941]
There are many entries of event 65534 being produced in `{FabricLogRoot}\QueryTraces\query_traces_*.etl`.

It was spotted due to another bug https://github.com/Azure/service-fabric-issues/issues/677, a node disk was full in a production environment. That issue is fixed as the log retention policy is abided in the latest release.

However, it would be good to fix the root cause of this event. It does not seem like hosted application is at fault here as installing VS2017 with Service Fabirc on a new system and deploying a hello-world application in cluster has shown query traces with event 65534.

**Comment by karolz-ms** [comment]
65534 is a special "manifest event" that is sent by EventSource to advertise its ETW (Event Tracing for Windows) manifest, that is, the schema of data the EventSource exposes. The data it carries is essential for ETW consumers of EventSource data to properly interpret it, but other than that it is about "plumbing" and can be ignored.

@mattrowmsft @masnider FYI

**Comment by am11** [comment]
Thanks @karolz-ms for the information.
