### ISSUE TITLE
Service Fabric Deployment Error: ServiceManifest.xml is missing for service with Octopus Deploy

### ISSUE THREAD

**Issue by cpatte7372** [Azure/service-fabric-issues#942]
Hello Community

I have spent many hours/days trying to Deploy a Service Fabric App to my Local Service Fabric cluster but to no avail.
I keep on getting the following error:

```
Deploying package:    C:\Octopus\Packages\Voting1\Voting1.1.0.14.nupkg 

Test-ServiceFabricApplicationPackage : The BuildLayout of the application in  

C:\WINDOWS\TEMP\TestApplicationPackage_39776636640\l5oaadrb.ivn\staging is  

invalid. ServiceManifest.xml is missing for service VotingDataPkg. 

At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricS 

DK\Publish-NewServiceFabricApplication.ps1:131 char:38 

+ ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse) 

+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplica  

   tionPackage], FabricImageBuilderValidationException 

    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceF  

   abric.Powershell.TestApplicationPackage 

 

Script 'C:\Octopus\Work\20180324195849-318-5\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 

Running rollback conventions... 

Script 'C:\Octopus\Work\20180324195849-318-5\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 
March 24th 2018 19:58:56Fatal
The remote script failed with exit code 1 
March 24th 2018 19:58:56Fatal
The action fab app 4 on the Octopus Server failed 
```
Can someone please let me know what may be causing the problem and how to fix it?

Thanks

Carlton

**Comment by masnider** [comment]
"ServiceManifest.xml is missing for service VotingDataPkg."

Where's the application package coming from? Is this some normal piece of VSTS or VS build output? 

If so can you check in that output and confirm whether the ServiceManifest.xml is present like you'd expect? If you have the whole application package you can also just Test-ServiceFabricApplicationPackage on it and see if it's right. If it isn't getting produced correctly in the first place then it will also fail when Octopus tries to deploy it to the cluster.

**Comment by masnider** [comment]
Hi there @cpatte7372 - we haven't heard back from you. We want to make sure your problem is solved though. I'm going to close this issue down for now. If you are still experiencing the issue and can provide the information requested, then please go ahead and reopen the issue. If you've got other issues or questions, please go ahead and open a new issue. Thanks!
