### ISSUE TITLE
Unable to download container image from private repository

### ISSUE THREAD

**Issue by MichalKoscielniak** [Azure/service-fabric-issues#944]
I have tried to host simple container application in service fabric cluster.
I have created a cluster in Azure ( using "Windows Server 2016 with Containers" image ), created simple service fabric application with contenerized service and tried to deploy simple image containing simple dummy ASP .NET Core web application ( created image is based on microsoft/aspnetcore image )
After deploying the application Service Fabric presents following error:

> Error event: SourceId='System.Hosting', Property='Download:1.0:1.0'.
> There was an error during download.Failed to download container image testregistrymichal.azurecr.io/samples/myasp

I have checked EventLog and following Warnings are appearing every couple of seconds:

> ContainerImagesOperation returned FABRIC_E_INVALID_OPERATION, isDelete
> Failed to import docker image error FABRIC_E_INVALID_OPERATION.

I did RDP to the machine and tried to pull the image manually and I'm seeing following error:

![image](https://user-images.githubusercontent.com/34438784/37905655-cd8b58b6-30ff-11e8-821e-fd199694066e.png)

When i tried to pull "microsoft/aspnetcore" image which my image is based on - the download suceeded - so it seems like an issue with downloading images from private registry.

**Comment by RajeetN** [comment]
@MichalKoscielniak, see https://github.com/Azure/service-fabric-issues/issues/752#issuecomment-376131250

**Comment by MichalKoscielniak** [comment]
@RajeetN are you sure about that ? The image which is failing was built using official microsoft/aspnetcore image as base. When i try to download official "microsoft/aspnotecore" it does not fail. This would suggest my image is more or less the same as the one which works ( unless docker pull is smart enough that it knew to download version targeting specific OS )
