### ISSUE TITLE
Node being reset by failure in leaslayr.sys

### ISSUE THREAD

**Issue by sjhawke** [Azure/service-fabric-issues#945]
leaslayr.sys caused the following error:

Log Name:      System
Source:        User32
Date:          3/21/2018 9:19:13 PM
Event ID:      1074
Task Category: None
Level:         Information
Keywords:      Classic
User:          SYSTEM
Computer:      node0000000
Description:
The process FabricInstallerService.exe has initiated the restart of computer node0000000 on behalf of user NT AUTHORITY\SYSTEM for the following reason: Application: Unresponsive
 Reason Code: 0x40005
 Shutdown Type: restart
 Comment: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="User32" Guid="{b0aa8734-56f7-41cc-b2f4-de228e98b946}" EventSourceName="User32" />
    <EventID Qualifiers="32768">1074</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2018-03-21T21:19:13.507992100Z" />
    <EventRecordID>162001</EventRecordID>
    <Correlation />
    <Execution ProcessID="440" ThreadID="1040" />
    <Channel>System</Channel>
    <Computer>node0000000</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="param1">FabricInstallerService.exe</Data>
    <Data Name="param2">node0000000</Data>
    <Data Name="param3">Application: Unresponsive</Data>
    <Data Name="param4">0x40005</Data>
    <Data Name="param5">restart</Data>
    <Data Name="param6">
    </Data>
    <Data Name="param7">NT AUTHORITY\SYSTEM</Data>
  </EventData>
</Event>

We have crash dumps for the service but are not keen to share them publicly. Please comment with a microsoft.com email address to enable me to forward more detail.

Simon

**Comment by masnider** [comment]
@chenxumsft @jeffreychenmsft  can you folks check this out. 
@sjhawke  can you provide more information about when you see this happening? Is this a prod environment? Dev laptop during setup? etc etc. If you are still seeing it on a recent release I think that'd be interesting.

**Comment by jeffreychenmsft** [comment]
@masnider The log message is not a Lease message. The message looks to be related to FabricInstallerService.

**Comment by sjhawke** [comment]
Hey - I have left the company using service fabric so am unable to provide more detail now. Sorry
