### ISSUE TITLE
Unable to create new Service Fabric Cluster in Azure Portal - all sizes "unavailable"

### ISSUE THREAD

**Issue by stan-dcip** [Azure/service-fabric-issues#95]
When going through the creation process, I get to the point where I used to be able to choose a CM size and all sizes are "Not Available" this worked last week, but hasn't worked for the past two Mondays.

![image](https://cloud.githubusercontent.com/assets/23409522/20534124/934a1e16-b0a5-11e6-8ad3-1b7c2d153d1f.png)

**Comment by masnider** [comment]
This is usually because either the VMs that you're trying to use are not available in the region that you're trying to create them in OR because your subscription is generally already near or over quota. Can you check these?

**Comment by aspiringtfsguru** [comment]
Additionally, there was an outage around creating VMs from the portal. The recommended work around at that time was to use Powershell, Azure CLI or Rest APIs. Not sure if that caused this, but it's worth noting.

**Comment by danzel** [comment]
Can you create a VM in the region you are trying to create the service fabric?
I'm having this problem, but it turns out I can't make VMs in the region I had selected for some reason. Selecting a region I can make VMs in makes it work. Raising that with support now...

**Comment by masnider** [comment]
Hi @stan-dcip, we haven't heard back from you on this issue. Is it still reproing for you? If not we can consider this case closed.

**Comment by i-e-b** [comment]
This seems to be related to the still open https://github.com/Azure/service-fabric-issues/issues/893

**Comment by dannycrone** [comment]
I get this for UK South, UK North and North Europe but it seems to be okay for West Europe??
