### ISSUE TITLE
Error Message:IPC requires loopback addresses, 0.0.0.0:0 is not

### ISSUE THREAD

**Issue by hongdai** [Azure/service-fabric-issues#951]
The cluster isn't working probably. It refuses to create a service. I see error message in the Service Fabric
event log:

"231ad4b49b0: IPC requires loopback addresses, 0.0.0.0:0 is not".

Could someone tell me why the Error message?

**Comment by masnider** [comment]
That error may be unrelated. 

Can you provide more information about the cluster? Is it local, in azure, on-prem, how it was created, etc? 

Can you provide more information about the service and how you're creating it? Is this during VS deployment, or powershell? When it fails what error do you see? Can you share the error text?

**Comment by tonyhxh** [comment]
I am facing the same problem. This is an effort to install ServiceBus_1_1_TLS_1_2, and make workflow manger 1.0 work with TLS 1.2. After installation, when trying to do add-sbhost, I saw this problem in Microsoft-Service Fabric Admin event log. 

Thanks
Tony

**Comment by cakriwut** [comment]
I have same error on hardened Windows 2016. Unfortunatelly, I am unable to find more detailed error.

**Comment by cakriwut** [comment]
Update to the #issue, I am trying to enable tls 1.2 in workflow manager CU5. Following are my steps, which work in non hardened Windows 2016 - but failed in the hardened counterpart.
1. Remove-SBHost
2. Uninstall Service Bus 1.1
3. Uninstall Windows Fabric
4. Install Service_Bus_1_1_with_TLS_1_2
5. Invoke-SBhostUpgrade
6. Add-SBHost

The step 6, failed while starting SBHost in the hardened server with exact error as above. Could it be permission issue?
I imagine, the process can not start service on loopback, or it failed to read some value.

Any clues?

**Comment by masnider** [comment]
Ah @tonyhxh has the real issue. WF manager and Service Bus standalone both use _really old_ versions of Service Fabric from a long time ago internally. You can't install them on machines that run modern Service Fabric. This is probably the root cause of all the issues described.

**Comment by leikong** [comment]
The transport error indicates configuration settings wasn't loaded properly, which is probably caused by what Matt mentioned above.

**Comment by leikong** [comment]
Add @Ning Jiang<mailto:Ning.Jiang@microsoft.com> @Jeffrey Chen<mailto:jefchen@microsoft.com> @Cheng Xu<mailto:chenxu@microsoft.com> as FYI
