### ISSUE TITLE
Complete cluster failure - ImageStoreService - The api IReplicator.OnDataLoss on node ***** is stuck.

### ISSUE THREAD

**Issue by patrikSE83** [Azure/service-fabric-issues#952]
During the holiday I went in to just upgrade our small cluster to a new size of VMset. Have done this a few time on the testcluster without any issues at all.

But after the upgrade I got a system failure of the ImageStoreService - I noticed that 3 of my 16 application's packages was "lost" somehow. Since I have all them accessible from GIT this is no issue - but it turned out after about 6hours of messing about. I can't get the cluster to accept ANYTHING and do ANYTHING after the ImageStoreService has been corrupted.

I have tried most of the stuff i have seen on different forums, deleting users and suff. I have also tried to "recreate" the work/store/app folders with the xml - all without any luck what so ever.

From the system health guide I read that when a service is calling out for "OnDataLoss" it is waiting for admin to do something manual. But in this case - I don't even know what todo - I would just have wished to delete the application package type and just redeploy it. But no no.

Since the ImageStoreService is "locked" i can't even run
Get-ServiceFabricImageStoreContent 

Going to be along night - setting up a new cluster from scratch in azure instead - don't know what else to actually do.

**Comment by oanapl** [comment]
@patrikSE83 , when you upgrade VMs in place, it wipes out the data; if data on multiple VMs is wiped out at the same time, the system services lose state. This triggered the dataloss you are seeing now. Next time, please follow the [recommended scale-in and out steps](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-scale-up-down).
Now, to recover this cluster: 
Since you have the state externally, try reducing the replica size to 1 so image store service can recover.
```powershell
Update-ServiceFabricService -Stateful -ServiceName fabric:/System/ImageStoreService -MinReplicaSetSize 1 -TargetReplicaSetSize 1
```
If the service becomes healthy after a while, change back the min and target to your original configuration. Eg. if you had 3/5 before, run:
```powershell
Update-ServiceFabricService -Stateful -ServiceName fabric:/System/ImageStoreService -MinReplicaSetSize 3 -TargetReplicaSetSize 5
```
If the service still doesn't recover, please open a support case so we can look at the cluster.

**Comment by oanapl** [comment]
We have made improvements to the way image store service handles the data loss to prevent it from getting stuck like this. This change will be available in 6.2 release.

**Comment by patrikSE83** [comment]
Thank you. Just to give you some more context on how the snowball went;

* 3 out of 16 packages was lost. 

Of course was these 3 applications spread over the full cluster, so each of the nodes hang themselvs in "Downloading package". And because of this, neither of them could then start deleting applications - and therefore, i couldn't delete applicationpackages.

Also tried the Start-ServiceFabricRepairTask - but this either gave me that I couldn't run the -NodeNames, and then it just timed out - at the same time as the rest of the nodes was up and healthy.

As it looks right now, the re-imaging did the trick,  - but my "Service Fabric cluster" in the azure portal just states it's status as "Failed", will this solve itself or do I need to re-sync them somehow?

Thank you for the info that this will be resolved in the future.

**Comment by oanapl** [comment]
@juhacket to help with the Failed cluster status in portal.

**Comment by juhacket** [comment]
The failed state in the Azure Portal represents the state of the last cluster resource operation in ARM. This is by design as you have not performed any successful operations since then. The cmdlets you used to mitigate this issue talk directly to the SF cluster and do not go through ARM. The next time you perform a cluster operation through ARM (i.e. Portal) you will see the state change.

**Comment by patrikSE83** [comment]
Just had easter, after the re-image everything has worked as it should.

A few follow-up questions / feature requests.

1) The fabric:/ImageStore - I know that in the article ( https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-image-store-connection-string ) you state that this will be updated in the future. My question is that is it possible to have a semi-update to this? And be able to have a "ImageStoreConnectionStringPrimary" that could also point to an AzureStore or another filesystem. So the ImageStore would store and work just as today in the /work/store/ folders localy on each of the replicasets. But then the primary would ALSO store them external if your infrastructure supports it.

My example; I will continue to run fabric:/ImageStore as my primary ImageStoreConnectionString since as you stated in the article - it makes most sence, but at the same time. Theese application packages are so important and unique to each cluster (since the _appXXX) I would also like the PRIMARY ImageStoreService to store the data on a Azure Storage (or a backup file storage).

2) "Purge" Application / ApplicationPackages - In my world, the installed applications and applicationpackages isn't as hard to install / setup / configure to run - as the VM-set and loadbalancer it is behind. And sometimes the "normal" procedure to setartup a Node (this has now happend to me twice, first i had an corrupt applicationpackage on one of the nodes, and now i lost the applicationpackages). And I got stuck at the same problems both times - Service Fabric is trying to be to nice and shutdown / delete stuff "friendly". As everything always works correct :)

I noticed you started with the ImageBuilderProxy to start adding folders for CleanUp applicationPaths. But we need something even harder. My thought here is that a Purge ONLY applies to a restart of a node. So if you want to really purge a application - it doesn't apply the purge feature until you "Node -> Restart" and then it just don't try to start the application at all. (as if the Service Fabric applications were in a database, and I just enter that database and remote the entity for that specific application, and then restart the nodes).

**Comment by oanapl** [comment]
@patrikSE83 , the article said that any improvements we make are going to be in the native image store, as opposed to File or Azure image store. It didn't talk about a specific improvement. 
If you need a copy of your packages, you can copy them to a backup store out of band. We also support [provisioning from that external store](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-package-apps#create-an-sfpkg), basically skipping the copy operation that brings the package to the cluster. When provisioning from external store, the packages will end up in our native image store, and you will have the original package in your external store. This is useful for example when the same package needs to used in multiple clusters.

I am not clear on your feature request for 2. 
To give you a short summary of how image store operations work: first you bring the package in the cluster with copy, then you provision the package, which makes the bits available in the image store, then you create applications. When you create applications, we bring that package on the node that needs to host the replica. If the replica moves, or a new replica needs to be brought up on a different node, then we copy the package on the new node from image store. To delete the package from image store, you unprovision it. You can read more [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-remove-applications).

"I noticed you started with the ImageBuilderProxy to start adding folders for CleanUp applicationPaths" -> which feature are you mentioning here?

**Comment by oanapl** [comment]
Haven't heard back in a bit and the initial problem was resolved. @patrikSE83 , please let me know if my suggestions above help and if you have any clarifications for the feature requests.
I will close for now, feel free to re-open with more info.
