### ISSUE TITLE
Local 1-node service fabric cluster sets Environment.CurrentDirectory to source path

### ISSUE THREAD

**Issue by palenshus** [Azure/service-fabric-issues#955]
This certainly seems like a bug.

When running a local 5-node cluster, the Environment.CurrentDirectory gets set to what you'de expect, a directory under the appropriate node path, for example: 

    C:\SfDevCluster\Data\_App\_Node_0\ApplicationAnalysisPipelineType_App0\work

However, when running as a local 1-node cluster, it gets set to the project source path itself, something like:

    D:\<repo>\Source\<project>

I assume this inconsistency is a mistake. To work around this, I end up doing:

    Environment.CurrentDirectory = context.CodePackageActivationContext.WorkDirectory

in my StatelessService constructor.

**Comment by masnider** [comment]
I would always be using the context.CodePackageActivationContext.WorkDirectory to find this. What you're seeing is probably a side effect of the single node deployment mode where it's really symlinking the "deployed" builds to your build/source directory to speed up deployment. Adding some folks to confirm.

**Comment by amanbha** [comment]
This is expected in VS Refresh Application debug mode.

**Comment by nimibs** [comment]
Can you share why is this expected? i consider this as bug.
