### ISSUE TITLE
Actors : Compile error : The actor interface methods cannot be overloaded.

### ISSUE THREAD

**Issue by hanxinimm** [Azure/service-fabric-issues#956]
build exception

[IDCreatorCoordinatorApp.zip](https://github.com/Azure/service-fabric-issues/files/1865296/IDCreatorCoordinatorApp.zip)

System.ArgumentException: Method 'GetUniqueNumberAsync' of actor interface 'IDCreatorActor.Interfaces.IIDCreatorActor' is overloaded. The actor interface methods cannot be overloaded.
4>Parameter name: actorInterfaceType
4>   at Microsoft.ServiceFabric.Services.Remoting.Description.InterfaceDescription.ThrowArgumentExceptionForMethodChecks(String remotedInterfaceKindName, Type remotedInterfaceType, MethodInfo methodInfo, String resourceName)
4>   at Microsoft.ServiceFabric.Services.Remoting.Description.InterfaceDescription.EnsureValidMethods(String remotedInterfaceKindName, Type remotedInterfaceType, MethodReturnCheck methodReturnCheck)
4>   at Microsoft.ServiceFabric.Services.Remoting.Description.InterfaceDescription.GetMethodDescriptions(String remotedInterfaceKindName, Type remotedInterfaceType, MethodReturnCheck methodReturnCheck, Boolean useCRCIdGeneration)
4>   at Microsoft.ServiceFabric.Services.Remoting.Description.InterfaceDescription..ctor(String remotedInterfaceKindName, Type remotedInterfaceType, Boolean useCRCIdGeneration, MethodReturnCheck methodReturnCheck)
4>   at Microsoft.ServiceFabric.Actors.Runtime.ActorTypeInformation.Get(Type actorType)
4>   at FabActUtil.Tool.LoadActors(Assembly inputAssembly, IList`1 actorFilters, IList`1 actorTypes)
4>   at FabActUtil.Tool.LoadActors(ToolContext context)
4>   at FabActUtil.Tool.Run(ToolArguments arguments)
4>   at FabActUtil.Program.Main(String[] args)

**Comment by ashishnegi** [comment]
@amanbha OP has a class derived from `IActor` which has overloaded interfaces. It gives compiler error that : `The actor interface methods cannot be overloaded.`
Is there any such requirement ? 

```
public interface IIDCreatorActor : IActor
    {
        /// <summary>
        /// 获取全局唯一编码
        /// </summary>
        /// <returns></returns>
        Task<long> GetUniqueNumberAsync(CancellationToken cancellationToken);

        /// <summary>
        /// 获取全局唯一编码
        /// </summary>
        /// <returns></returns>
        Task<long> GetUniqueNumberAsync(int count, CancellationToken cancellationToken);

    }
```

**Comment by ashishnegi** [comment]
@hanxinimm To get unblocked for time being, you can rename 2nd method to `GetUniqueNumberWithCountAsync` ?

**Comment by amanbha** [comment]
Yes in service remoting and actors, method overloads are not supported.
