### ISSUE TITLE
Multiple workers doing the same job (Question)

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#957]
Hi, I have a problem domain where I want to have multiple services doing a same job (e.g reading from a bulk data-store like table storage and writing to a queue). The data is in bulk and I would like to have 100 of services consuming this data. What type of service fabric service should I be looking at for this problem domain?

**Comment by dotdestroyer** [comment]
We need more information to help, try to be more explicit. 

I have to assume you are talking about Azure Table Storage? And when you say 'Queue' is that a ReliableQueue, ReliableConcurrentQueue, Azure Storage Queue or Azure Service Bus Queue? 

1. How often are you writing to the azure table store? X writes per minute?
2. What is your PartitionKey for Azure table storage? is it a defined range 0-100, A-Z, or is it entirely random?
3. Do your storage consumers need to scale with load? 
4. What is your target latency between an item being written to the storage table, and then being published to the queue?
5. Do you need to delete data from the Table Storage after the data has been published to a queue?

**Comment by usamaazhar** [comment]
Yes, Iam reading from an azure table storage, than processing the data and writing the results in the azure queue for some webclients to read. And yes it must have the ability to scale

**Comment by masnider** [comment]
I would start [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-scalability). Some more information or specific answers to @dotdestroyer's questions would be great, otherwise anything should work.

**Comment by masnider** [comment]
Hi there @usamaazhar - we haven't heard back from you in a little while. At this point with the information provided, the scalability article's instructions are probably your best bet. If you can provide more specific questions or give us more information we might be able to do better. In the meantime I'm going to close down this issue. If you have more info or want to ask more questions on this topic, just go ahead and reopen it.
