### ISSUE TITLE
Fabric.exe memory leak

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/service-fabric-issues#958]
In this process dump, Fabric is using 600MB of memory

https://gavdiag901.blob.core.windows.net/public/Fabric.DMP

**Comment by masnider** [comment]
Ok, but what makes you think that's a leak? Can you provide more information (we'll also take a look). Ex: if this was a larger cluster that could be a totally reasonable amount of memory.

**Comment by gustavo-armenta** [comment]
Its a cluster of 2 machines. Each machine has 7GB RAM. Windows Server 2016 is using 4GB RAM so my applications can only use the remaining 3GB.

Fabric.exe uses 40MB when the machine is just started. When the machine becomes unrespopnsive, I notice very low CPU and high memory usage with Fabric.exe above 500MB

**Comment by tuhland** [comment]
We have the same issue, including slow remote connection to that node. Fabric.exe goes up to 900MB-1GB of memory usage. We then usually restart that node. It's a 5 node cluster, Windows Server 2012 R2 with 4GB RAM.

**Comment by slandsaw** [comment]
Same here. Runtime version is 6.1.472.9494. The memory usage is only high on two of the nodes (primary and secondary maybe?).

**Comment by robbenwangcn** [comment]
@masnider  Any updates? I'm facing the same issue. Current fabric version 6.1.480.9494. Fabric.exe is taking 500M+ memory. 3 nodes with D1V2

**Comment by senj** [comment]
See also #917

**Comment by hallipr** [comment]
I can seen memory leaks from Fabric.exe on 71 nodes across 32 clusters.  Each instance grows at a rate of 50 to 100 MB / day.

We've seen some instances at more than 6GB.

This is a 2 week graph of Fabric.exe Physical Memory from some of the nodes.  Values in MB.
![image](https://user-images.githubusercontent.com/1291634/41131814-4f702f68-6a72-11e8-992e-db329dace392.png)

**Comment by ivanlysiuk** [comment]
I would like to confirm that the issue exists in an on-prem cluster running on version 6.2.283.9494. In a 6 node cluster, two nodes have Fabric.exe consuming memory linearly in time, independent of load (we do performance tests a couple of hours a day) at the rate ~2.5MB/hour. 

When Fabric.exe is killed, it restarts with a low memory footprint and resumes eating memory at the same rate as before.

Once there is no memory left, due to Fabric.exe, other processes representing services of SF applications start failing until Fabric.exe is killed.

**Comment by tknerr** [comment]
I'm also seeing this on 2 nodes in our 5-node SF cluster running on version 6.2.283.9494.

The upgrade to 6.2.283.9494 happened on June 1st, since then you see the constant decline:

![image](https://user-images.githubusercontent.com/365744/41281443-ae6a6282-6e31-11e8-8c99-6c4d18552e72.png)

**Comment by tknerr** [comment]
Note that we also see a slight increase in CPU usage for the nodes which are leaking memory. We observe this consistently across environments. Also, not all of the nodes are leaking, but only a few:

 * in our 5-node clusters we see 2 nodes leaking
 * in out 3-node clusters we see 1 node leaking

CPU increase:

![image](https://user-images.githubusercontent.com/365744/41342827-730bcbaa-6efd-11e8-8bc3-2a3b861e4277.png)

**Comment by masnider** [comment]
Confirmed that this should be the same as a known bug we discovered around the same time internally. Fixes are already prepared and should be included in the next release (6.3) and also we've backported to 6.2 CU3, which has started rolling out in Azure and should be made more broadly available soon.

**Comment by masnider** [comment]
These releases have been shipped, so this issue should be resolved at this point. I'm going to close down this issue. If you have another repro of this, please reopen, and if you see any other leaks or things like this in the future, please open another issue. Thank you for reporting!
