### ISSUE TITLE
Using a SecretsCertificate to decrypt a domain user password with attribute Encrypted='true' fails

### ISSUE THREAD

**Issue by serbrech** [Azure/service-fabric-issues#96]
My ApplicationManifest is as below : 

Principals : 

``` xml
<Principals>
    <Users>
      <User Name="SvcAccount" AccountType="DomainUser" AccountName="domain\serviceuser" Password="MIIBKQYJKoZIhvcNAQcD...rvtewFvicEhHd3Ysi/5ow==" PasswordEncrypted="true" />
    </Users>
</Principals>
```

Policies with SecurityAccessPolicy ResourceType="Certificate" : 

``` xml
<Policies>
      <RunAsPolicy CodePackageRef="Code" UserRef="SvcAccount" />
      <SecurityAccessPolicy ResourceRef="ServiceEndpoint" PrincipalRef="SvcAccount" />
      <SecurityAccessPolicy ResourceRef="ServiceEndpointSsl" PrincipalRef="SvcAccount" />

      <SecurityAccessPolicy ResourceRef="Cert2" PrincipalRef="SvcAccount" ResourceType="Certificate" />
</Policies>
```

And of course I define the certificates : 
``` xml
<Certificates>
    <SecretsCertificate X509FindValue="FAEC44B0B0E9456E38A90459218858988C38CD82" Name="Cert2" />
    <EndpointCertificate X509FindValue="FAEC44B0B0E9456E38A90459218858988C38CD82" Name="Cert" />
  </Certificates>
```

I run this on the local dev cluster with 5 nodes config, and use a self signed certificate. I know the certificate definition and thumbprint are fine because if I do not encrypt the password I am able to get the https endpoint up and running for my service.

It seems that a Certificate Resource is expected in the ServiceManifest.xml, but intellisense at least does not let me add a Certificate in the Service Manifest resource.

Running Test-ServiceFabricApplicationPackage : 
```
Test-ServiceFabricApplicationPackage -ApplicationPackagePath .
False

Test-ServiceFabricApplicationPackage : The ResouceRef 'Cert2' in SecurityAccessPolicy is invalid. There is no matching Resource in the corresponding ServiceManifest.
FileName:
 
C:\Users\ode\AppData\Local\Temp\TestApplicationPackage_440837549664\kdjjxvh3.4zh\Debug\ApplicationManifest.xml
At line:1 char:1
+ Test-ServiceFabricApplicationPackage -ApplicationPackagePath .
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidationException
    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
```

I updated the SDK to the latest but that did not help.
I am basically following the doc, confirmed by this answer by stackoverflow answer : http://stackoverflow.com/questions/39126630/how-to-run-a-service-fabric-application-with-different-security-permissions

This seems unanswered question seems to be a related issue : 
https://stackoverflow.com/questions/40601411/azure-service-fabric-securityaccesspolicy-to-access-certificate-for-a-specific#

**Comment by serbrech** [comment]
I close this issue since no comment was ever made

**Comment by cemheren** [comment]
Hi, I am hitting the same issue. Did you ever get around this problem?
