### ISSUE TITLE
multi-linux VM cluster

### ISSUE THREAD

**Issue by lin-jianjun** [Azure/service-fabric-issues#960]
How do you deploy the service fabric cluster on a multi-linux VM?

**Comment by lin-jianjun** [comment]
Modify nonsecure/ servicefabri-scalemin.xml as follows.

<NodeList>
                <Node NodeName="_Node_0" IPAddressOrFQDN="localhost" IsSeedNode="true"  NodeTypeRef="NodeType0" FaultDomain="fd:/0" UpgradeDomain="0" />
                <Node NodeName="_Node_1" IPAddressOrFQDN="172.21.128.217" IsSeedNode="true"  NodeTypeRef="NodeType0" FaultDomain="fd:/1" UpgradeDomain="1" />
                <Node NodeName="_Node_2" IPAddressOrFQDN="localhost" IsSeedNode="true"  NodeTypeRef="NodeType2" FaultDomain="fd:/1" UpgradeDomain="2"/>
                <Node NodeName="_Node_3" IPAddressOrFQDN="localhost" IsSeedNode="false" NodeTypeRef="NodeType3" FaultDomain="fd:/3" UpgradeDomain="3" />
                <Node NodeName="_Node_4" IPAddressOrFQDN="localhost" IsSeedNode="false" NodeTypeRef="NodeType4" FaultDomain="fd:/4" UpgradeDomain="4" />
            </NodeList>

report error：
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: Even though the deployment is split over multiple machines there is at least one node with a loopback address
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.ValidateNodeList()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.Validate()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.UpdateNodeStateOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.CreateorUpdateOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)

**Comment by lin-jianjun** [comment]
Modify nonsecure/ servicefabri-scalemin.xml as follows.
 <NodeList>
                <Node NodeName="_Node_0" IPAddressOrFQDN="localhost" IsSeedNode="true"  NodeTypeRef="NodeType0" FaultDomain="fd:/0" UpgradeDomain="0" />
                <Node NodeName="_Node_1" IPAddressOrFQDN="172.21.128.217" IsSeedNode="true"  NodeTypeRef="NodeType0" FaultDomain="fd:/1" UpgradeDomain="1" />
                <Node NodeName="_Node_2" IPAddressOrFQDN="localhost" IsSeedNode="true"  NodeTypeRef="NodeType2" FaultDomain="fd:/1" UpgradeDomain="2"/>
                <Node NodeName="_Node_3" IPAddressOrFQDN="localhost" IsSeedNode="false" NodeTypeRef="NodeType3" FaultDomain="fd:/3" UpgradeDomain="3" />
                <Node NodeName="_Node_4" IPAddressOrFQDN="localhost" IsSeedNode="false" NodeTypeRef="NodeType4" FaultDomain="fd:/4" UpgradeDomain="4" />
            </NodeList>

**Comment by masnider** [comment]
Hi @lin-jianjun - what do you mean by "multi-Linux"? Just more than 1 VM? And is your question in reference to Azure?

There's a pretty good walkthrough [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-arm), but in the portal it's really just as simple as picking a Linux operating system when setting up the cluster.

![image](https://user-images.githubusercontent.com/10968331/38330963-d15ee760-3806-11e8-948f-46ffb91f5bbe.png)

**Comment by mani-ramaswamy** [comment]
We don't yet support multi-machine stand alone Linux clusters. However, this will be released in the upcoming months.

**Comment by lin-jianjun** [comment]
Thank you very much!I also want to know whether FabricDeploy does not support or service fabric does not support.In addition, service fabric has those capabilities that are not supported.

**Comment by mani-ramaswamy** [comment]
Sorry, not following your question. We are not supporting any multi-machine Linux cluster outside of Azure today.

**Comment by rishirsinha** [comment]
There is nothing that inherently prevents creation of multi-machine standalone clusters on Linux. However, the work to make it come together has not happened yet.

**Comment by lin-jianjun** [comment]
@rishirsinha

**Comment by lin-jianjun** [comment]
@rishirsinha

**Comment by lin-jianjun** [comment]
@rishirsinha

**Comment by lin-jianjun** [comment]
@rishirsinha

**Comment by mani-ramaswamy** [comment]
It will come in the upcoming months.

**Comment by mani-ramaswamy** [comment]
What do you mean by "internal" and "external" SF clusters?

**Comment by masnider** [comment]
Closing for now. Lin if you can clarify your question then we can answer.
