### ISSUE TITLE
Service Fabric fails to download image from ACR

### ISSUE THREAD

**Issue by stoepa** [Azure/service-fabric-issues#962]
I have a service fabric cluster in azure with one node, this is just a test environment.

I have create a docker compose file with a exisitng asp.net webform within it. It runs locally, so it is containerized and uploaded to my private ACR.

I have added all the requirements in the SF manifest files, I have even search this forum for any help but it seems as if there are no solutions and issues get closed before any real workaround or tip is given.

The SF cluster is running Windows Server 2016 with containers update 1709.

I have also made sure my docker image is pulling the server core base image 1709.

SF hangs with the following error. There was an error during download.

I mean that can many things, non descriptive issues are trivial. I am also not sure how to check the logs for SF to maybe get more detail.

Any help will be appreciated.

**Comment by masnider** [comment]
One quick thing to check is whether you can successfully docker pull the image on the machine itself. You can verify this by RDPing into the machine and trying to pull the image from ACR. If this works there's usually some accidental error in the manifests that is preventing download or referencing the wrong image. 

If you can try the first thing and verify that works (to eliminate connection issues), and then share the manifest and how you're specifying the image and security information, that'd be great.

**Comment by masnider** [comment]
Closing as we haven't heard back from you. If you're still experiencing this problem, please reopen or create a new issue with a complete description. The most common issue, as I outlined, is that the image is incompatible. If you're able to pull and run the image on the target machine outside of SF, then we can absolutely take a look.
