### ISSUE TITLE
Cluster upgrade to 6.1.480.9494 failed

### ISSUE THREAD

**Issue by olitomlinson** [Azure/service-fabric-issues#963]
from : `6.1.467.9494`
to : `6.1.480.9494`

I manually triggered an upgrade of my VMSS-backed 5 node SF cluster in the portal. The upgrade began and then rolled back after some time.

As the upgrade was happening, I spotted a bunch of new nodes that were reporting as unhealthy. As you can see from the following screen shot :
![abnormal1](https://user-images.githubusercontent.com/4224880/38244628-3201eb82-3733-11e8-8f80-02aec8b45a09.PNG)

The upgrade continued as I expected. In the screen shot you can see nodes 0 and 1 completed successfully, and the state of the upgrade was 'RollingForwardPending'.

![abnormal2](https://user-images.githubusercontent.com/4224880/38244668-4f82e5ee-3733-11e8-9a1a-33abe7468057.PNG)

At this point, things stopped happening and I left it for an hour or so to go to a meeting.

I came back and the upgrade had completely rolled back. You can see the upgrade state as 'RollingBackCompleted'
![abnormal3](https://user-images.githubusercontent.com/4224880/38244794-a78dee14-3733-11e8-876e-1b517f5f5105.PNG)

Now I am left with a bunch of random nodes which are errored with the state (down) with the following messages : 

![abnormal4](https://user-images.githubusercontent.com/4224880/38244860-df074f16-3733-11e8-9fb4-ce23814d985d.PNG)

My questions are 
1. Why did the upgrade fail? Where can I go to find this information? How do I upgrade my cluster now?
2. What are these random nodes beginning with 'nodeid:xxxxxxxxx' ? Are they transient/temporary nodes that should clear down on their own or are they something permanent, different?
3. Why has SF not cleared down these temporary nodes?
4. Can I delete these temporary nodes?

**Comment by olitomlinson** [comment]
**UPDATE** I decided to do it again (I also took a chance and deleted those random unhealthy nodes) and the upgrade worked fine this time...

Some questions still outstanding around those random nodes, what were they? why didn't the runtime clear them up? etc

**Comment by hkuizenga** [comment]
@olitomlinson How did you delete those "random unhealthy nodes"?  I tried an AddNode to an existing cluster with the 6.1.480.9494 install files (which failed) and ended up with a node named similarly to the one you are showing above.  So far, I've been unable to delete it.

**Comment by olitomlinson** [comment]
I deleted them in SFE

**Comment by hkuizenga** [comment]
This may be a dumb question, but how did you do in SFE?  I didn’t know that was possible (NOTE:  My cluster is at v6.1.472.9494).

**Comment by olitomlinson** [comment]
There is an options menu against each node on the left. In there is an option called ‘Remove Node State’ which is what I used. Disclaimer: Make sure you are 100% before you do this as it’s a destructive and not reversible.
