### ISSUE TITLE
Thread.CurrentThread.CurrentCulture in Actors

### ISSUE THREAD

**Issue by eliasnawfal** [Azure/service-fabric-issues#966]
I'm calling my Actor from an Asp.Net Core 2 website using 
```
IExampleActorService actor = ActorProxy.Create<IExampleActorService>(ActorId.CreateRandom(),
                new Uri("fabric:/App/ExampleActorService"));
await actor.CallExampleFunction().ConfigureAwait(false);
```
My website supports localisation and I want to pass current culture to my actors.
I noticed that Thread.CurrentThread.CurrentCulture in actor doesn't change with the website that called the actor.
Is this a bug? Is there any clean way I can pass  Thread.CurrentThread Cultures to my Actors.

Thank you

**Comment by jmaocanada** [comment]
I don't think this is a bug. Actor (not the proxy) actually runs in another context or even another node of the cluster. So we cannot expect it is in the same thread with the same current culture at all. 
What about just pass the culture name as a parameter when you call your actor? Such as:
`await actor.CallExampleFunction(Thread.CurrentThread.CurrentCulture.Name).ConfigureAwait(false);`

**Comment by amanbha** [comment]
@eliasnawfal What @jmaocanada explained is correct and the option suggested by him can be used.
You can also add the culture info in the headers on the client side, and retrieve it on the service side using custom client proxy and custom message handlers, you can then pass it to method calls by adding it to the CallContext. Following sample demonstrates this using ServiceFabric V2 Remoting https://github.com/amanbha/servicefabric/tree/master/samples/ActorCustomMessageHandler

**Comment by eliasnawfal** [comment]
@amanbha @jmaocanada 
I already implemented @jmaocanada way and passed Culture as a string in all my Actors' method for the sake of time.
I will look into the example on Github for later Implementation.

Thank you for your time and fast response
