### ISSUE TITLE
DNS Service startup issue

### ISSUE THREAD

**Issue by nileshbits** [Azure/service-fabric-issues#972]
Im having a DNS service startup issue:
"
DnsService UDP listener is unable to 
                        start. Please make sure there are no processes listening on the DNS port 53.
                        List of processes listening on the DNS port:
                          UDP    0.0.0.0:53             *:*                                    8576
                        "

`netstat -ano` also gives the same output, but that process is not "listening", and hasnt bound the port. I can see the same on my local machine and the SF cluster is working well.

Is there any other reason the service may not be starting up? Seems like a bug since there's nothing really listening on that port.

**Comment by masnider** [comment]
This is probably the same thing as https://github.com/Azure/service-fabric-issues/issues/971, but on a local box I presume?

**Comment by nileshbits** [comment]
sorry, I added a new issue by mistake, should've updated here. Closing this one.
