### ISSUE TITLE
DockerProcessManager failed to transition state error FABRIC_E_INVALID_OPERATION current state 64

### ISSUE THREAD

**Issue by MathijsHofkens** [Azure/service-fabric-issues#977]
After installing a new cluster we are seeing a few error logs:

`DockerProcessManager failed to transition state error FABRIC_E_INVALID_OPERATION current state 64`

and

`The current process does not have required privilege SeAssignPrimaryTokenPrivilege. Modify the local security policy or run the process under an account that has this privilege.`

What do those mean?

**Comment by harahma** [comment]
@MathijsHofkens  Which version of SF is this? Is it a local dev cluster?

**Comment by MathijsHofkens** [comment]
@harahma 6.1.480.9494, it's a 5 node windows 2016 server cluster.

**Comment by harahma** [comment]
The error in themselves are fine and do not necessarily indicate an in itself. Are you seeing any errors/health warnings in Service Fabric Explorer?

**Comment by MathijsHofkens** [comment]
Ok, great to hear. No errors or warnings in Service Fabric Explorer, but I wanted to make sure the cluster was working.

Is there any document available regarding these error messages? Because they really need clarification.

**Comment by harahma** [comment]
They are internal transient warning/errors meant for internal usage only. If you observe any health error/warning in SFX or any functionality not working as expected then we can look into it.

**Comment by MathijsHofkens** [comment]
Ok, I understand. You can close this. Thanks for the feedback, appreciated!
