### ISSUE TITLE
Remoting - where to use KnownType?

### ISSUE THREAD

**Issue by nesherhh** [Azure/service-fabric-issues#98]
I have following service interface
```
public interface ISomeService : IService
{
  Task<bool> DoAsync(Enum action);
}
```
To access this service I'm creating proxy instance using ServiceProxy:
```
ISomeService svc = ServiceProxy.Create<ISomeService>(uri);
await svc.DoAsync(MyEnum.SomeValue);
```
When I execute the DoAsync method I get SerializationException telling that MyEnum.SomeValue is unexpected and I should use KnownTypeAttribute. My service implementation already have them:
```
[KnownType(typeof(MyEnum))]
public class SomeService : StatelessService, ISomeService
{}
```
But this does not work.
Where should I write KnownType attribute?

**Comment by SimonLuckenuik** [comment]
KnowType attributes are usually used with Data Contract and the DataContractSerializer:
https://msdn.microsoft.com/en-us/library/ms730167(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/ms731072(v=vs.110).aspx

As a quick workaround, you could probably create an Action class which contains the Enum and then use the KnownType attribute. Make sure your Enum is using Data Contract attributes:
https://msdn.microsoft.com/en-us/library/system.runtime.serialization.enummemberattribute(v=vs.110).aspx

You could also look into ServiceKnownType (assuming it is supported by SF):
https://msdn.microsoft.com/fr-fr/library/system.servicemodel.serviceknowntypeattribute(v=vs.110).aspx

**Comment by nesherhh** [comment]
I was hoping not to change the interface/contract. Attribute  would be ok, but it didn't worked.

**Comment by VipulM-MSFT** [comment]
You need to wrap the enumeration in a new type.
