### ISSUE TITLE
Can I use the native and managed APIs to write applications in C++?

### ISSUE THREAD

**Issue by lin-jianjun** [Azure/service-fabric-issues#981]
Application programming documentprovides only c # and JAVA.
 (https://docs.microsoft.com/zh-cn/azure/service-fabric/service-fabric-create-your-first-linux-
application-with-csharp)   

  Can I use the native and managed apis to write applications in C++? Are there any documents that use c++ programming?

**Comment by lin-jianjun** [comment]
@masnider Thank you very much.
Are there any detailed documents that use C# programming?
The documentation I know now is relatively simple.
(documentation site:https://docs.microsoft.com/zh-cn/azure/service-fabric/service-fabric-reliable-services-introduction)

**Comment by masnider** [comment]
The rest of the documentation for SF lives in the actual [API docs](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-fabric?view=azure-dotnet) and our [samples](https://azure.microsoft.com/en-us/resources/samples/?service=service-fabric&sort=0).
