### ISSUE TITLE
Environment variable passed in service manifest file is visible in the service fabric explorer

### ISSUE THREAD

**Issue by hiteshg40** [Azure/service-fabric-issues#984]
I have a requirement to pass the database credentials to the docker instance created by service fabric. This works if I pass the value as an environment variable in the service manifest files. However the problem is around being able to view this value in the service fabric explorer. Is there a way where I can filter out the content/manifest value from the explorer?

**Comment by xunlu** [comment]
You should encrypt the credential and set it in your manifest.  Please refer to: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management

**Comment by masnider** [comment]
Hi @hiteshg40. We haven't heard back from you on this with any further questions and the doc that @xunlu pointed to is the correct one. I'm going to close this issue down for now. If you have more questions on this topic just reopen this issue, or if you have other questions go ahead and create a new issue. Thanks!
