### ISSUE TITLE
How to upgrade from Remoting V1 to Remoting V2. 

### ISSUE THREAD

**Issue by wandelson** [Azure/service-fabric-issues#986]
![image](https://user-images.githubusercontent.com/810174/38836134-8800c72c-41a3-11e8-9b16-68843aad2716.png)

Why ? What's the namespace ? I think this documentation confuse.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2

below the code, this my github. can you help me ?

https://github.com/wandelson/service-fabric-ecommerce/tree/master

Ticket linked
https://github.com/Azure/service-fabric-issues/issues/497

**Comment by francescocristallo** [comment]
What I did to upgrade a Stateful Service to Remoting V2 was to use

`  protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
        {
            return this.CreateServiceRemotingReplicaListeners();
        }`

and on my Interface class the assembly line 

`[assembly: FabricTransportServiceRemotingProvider(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]
`
also in the ServiceManifest.xml of the Stateful Service update the name to

`  <Endpoint Name="ServiceEndpointV2" />`

**Comment by ashishnegi** [comment]
@wandelson If you are referring to namespace for `ServiceRemotingJsonSerializationProvider`, then it is a custom class. Its not provided by Service Fabric. The code is on the blog. You need to copy and add that to your project.

**Comment by suchiagicha** [comment]
@francescocristallo 
Are we good to close this issue?

**Comment by mcquiggd** [comment]
@amanbha 

That new example looks perfect - many thanks for creating that. 

Regarding the Pluralsight code - personally I had already fixed that, but was trying to help out the original poster, who I believe has a first language of Brasilian Portuguese rather than English - and also receive official guidance from Microsoft for these scenarios to verify the approach I had taken.

Thanks again for creating an end to end sample as a reference. Much appreciated.

**Comment by amanbha** [comment]
@mcquiggd that's great. I will close this issue, feel free to open new one if you need any help.

**Comment by mcquiggd** [comment]
@amanbha  - this is not my issue, so, it's up to @wandelson to decide if he has enough information.

**Comment by quangtran-groove** [comment]
Hi all,

Anyone please let me know the differences between Data Contract Provider vs Custom Serializer, I am confusing.

Thanks

**Comment by tarunbhatt9784** [comment]
> @amanbha
> 
> That new example looks perfect - many thanks for creating that.
> 
> Regarding the Pluralsight code - personally I had already fixed that, but was trying to help out the original poster, who I believe has a first language of Brasilian Portuguese rather than English - and also receive official guidance from Microsoft for these scenarios to verify the approach I had taken.
> 
> Thanks again for creating an end to end sample as a reference. Much appreciated.

How did you resolve the issue? I am following Pluralsight code and finding it hard to change. Can you please advise?

**Comment by tarunbhatt9784** [comment]
> > @amanbha
> > That new example looks perfect - many thanks for creating that.
> > Regarding the Pluralsight code - personally I had already fixed that, but was trying to help out the original poster, who I believe has a first language of Brasilian Portuguese rather than English - and also receive official guidance from Microsoft for these scenarios to verify the approach I had taken.
> > Thanks again for creating an end to end sample as a reference. Much appreciated.
> 
> How did you resolve the issue? I am following Pluralsight code and finding it hard to change. Can you please advise?

Please ignore, I have been able to resolve the compilation issue, there are runtime issues, looking into them
