### ISSUE TITLE
Error on Service Fabric ClusterConfiguration Upgrade

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#99]
Hello,
I try to use: https://docs.microsoft.com/en-us/powershell/servicefabric/vlatest/start-servicefabricclusterconfigurationupgrade

but I get the following error: 
![image](https://cloud.githubusercontent.com/assets/5556013/20927393/ab51eada-bbc1-11e6-87d3-d952adb71fc9.png)

It seems my connection is null, but I did a Connect-ServiceFabric before calling the method.
It is a 3-node Windows Cluster with Windows Authorization.

![image](https://cloud.githubusercontent.com/assets/5556013/20927634/c4bed9dc-bbc2-11e6-9fb4-b129b442cb41.png)

**Comment by masnider** [comment]
And the connection was successful? Do other methods succeed?

**Comment by senj** [comment]
yes all others I need do work ⁣​

**Comment by maburlik** [comment]
Did you add any nodes to the cluster after initial deployment? What is the Fabric version of your cluster? There was a fix that went into 5.4 which fixed configuration upgrade for clusters that have had nodes added. Please follow the steps at this link for upgrading your existing cluster version to 5.4:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-upgrade-windows-server

**Comment by senj** [comment]
Update on this one:
I have Version 5.3... and now I'm getting an ArgumentException that the value doesn't fall within the expected value. This seems to be an common error with the API.  :/

I can add my config on monday, but all I tried was to add another Windows User to the secure Cluster configuration. The Configuration Test Fails with "there is already a deployed Cluster", of cause, but all other entries look good.

A replacement of the Cluster isn't an Option, it's a productive system where we want to add CI and need to add a build user

**Comment by masnider** [comment]
Hi @senj - did you happen to have an answer to @maburlik 's question? Also (taking a fresh look at this) the ArgumentOutOfRange error can happen when the version of the SDK that you are using is _ahead_ of the version that runs in the cluster. Perhaps that was the case? 

If you can provide us more information on this we can take a look, but given that 5.3 is out of support at this point (and if it isn't an issue for you on newer versions) then we can consider this issue closed. 

Please let us know when you get a chance

Thanks
-Matt
