### ISSUE TITLE
Capacity Limit of Reliable Collections in Stateful services

### ISSUE THREAD

**Issue by usamaazhar** [Azure/service-fabric-issues#992]
What is the size restriction of Reliable Collections in service fabric? Is it the size of the memory or the disk?
I read the answer here but just want to be sure on official forum
[url](https://stackoverflow.com/questions/39592967/service-fabric-reliable-collection-capacity?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by masnider** [comment]
@olitomlinson Thanks Oliver. @usamaazhar in that answer I didn't even talk about Garbage Collection/Garbage overhead and Serialization:)  TLDR: Generally start with memory as your limit and you _may_ be able to do more optimizations to reduce that footprint and to take advantage of disk, but those are not applicable in all situations. Please let us know if you have any further questions (or feel free to propose edits to that SO question).

**Comment by masnider** [comment]
@usamaazhar Hi there! We haven't heard back from you on this, so I hope my answer was sufficient. If you have further questions on this topic, please just let us know. For now I'm going to close down this issue. Thanks!
