### ISSUE TITLE
Microsoft.ServiceFabric - Encrypt/Decrypt Error 

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#995]
Hi Team,

https://msdn.microsoft.com/en-us/library/system.fabric.security.encryptionutility.encrypttext.aspx

I am trying to use Microsoft.ServiceFabric package which has capabilities to Encrypt/Decrypt secrets using certificates.

I created sample Console application in C#.

Added Below Package
Install-Package Microsoft.ServiceFabric

string EncryptedText = EncryptionUtility.EncryptText("Test", "‎ef5d044856ccb15a92f819864597d1cbe34b727b", @"CurrentUser\Personal\Certificates");

            StoreLocation storelocation = StoreLocation.CurrentUser;
            System.Security.SecureString DecryptText = EncryptionUtility.DecryptText(EncryptedText, storelocation);

Getting below error.

An unhandled exception of type 'System.BadImageFormatException' occurred in Unknown Module.
Could not load file or assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Thanks,
Naresh Khatri

**Comment by ashishnegi** [comment]
Make sure you are targeting `x64` platform. 

If this does not solve your problem, please give details on : Which SDK and runtime version are you using ? Is it .Net Framework or dotnet Core app ?

**Comment by nareshkhatri81** [comment]
@ashishnegi 

Tried with x64.
its console application targeting 4.6 framework and below are various SDK.
  <package id="Microsoft.IdentityModel.Logging" version="5.2.1" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.2.1" targetFramework="net461" />
  <package id="Microsoft.ServiceFabric" version="6.2.262" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="net461" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.2.1" targetFramework="net461" />

Getting below exception.
Exception from HRESULT: 0x80071BF2

   at System.Fabric.Security.EncryptionUtility.EncryptText(String textToEncrypt, String thumbprint, String storeName, StoreLocation storeLocation, String algorithmOid)
   at System.Fabric.Security.EncryptionUtility.EncryptText(String textToEncrypt, String thumbprint, String storeName)
   at TestConnectivity.Program.Main(String[] args) in C:\Users\10641189\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 40

Thanks,
Naresh Khatri

**Comment by ashishnegi** [comment]
Some progress :)
This error code means : FABRIC_E_INVALID_X509_THUMBPRINT

From documentation : https://msdn.microsoft.com/en-us/library/system.fabric.security.encryptionutility.encrypttext.aspx

```
Encrypt text string with an installed X509 certificate. 
Certificate store location is LocalMachine and the encryption algorithm is AES256 CBC.
```
See if you are satisfying these properties.

**Comment by nareshkhatri81** [comment]
@ashishnegi 
i don't have privileges to install certificates at local machine.
i tried on other machine to local machine but strange thing is below error there.

Unable to load DLL 'FabricCommon.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

this dll is not part of nuget package. i copied it from SF runtime to my published bin folder but same error.

**Comment by ashishnegi** [comment]
How are you running this code ? Have you created a sample app ?
The code you are using is from SF SDK which is used for writing SF apps.
You need to install SF runtime, run the cluster, deploy the app to access SF apis.

**Comment by nareshkhatri81** [comment]
@ashishnegi - End target is to use this inside containers. but i would like to test in console application then port the code to container.
Inside containers also there is no SF runtime.
As these are client side nuget package why it has dependencies of runtime ?

**Comment by ashishnegi** [comment]
I didn't know that this is client side part. You are right, this does not require runtime.
Can you share minimum sample repro project ?

**Comment by nareshkhatri81** [comment]
i tried other signature and got below error. what are valid values for AlgorihtiumOID

string EncryptedText = EncryptionUtility.EncryptTextByCertFile("test", @"D:\ModernRFCom\Features\ContainerTest\secretsder.cer","None");

Unknown cryptographic algorithm. (Exception from HRESULT: 0x80091002)

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
do you have link to Error Code and its description ?

it simple console app target 4.6 framework if you would like to give a try.

just added below nuget packages and few lines of code.
Microsoft.ServiceFabric" version="6.2.262" targetFramework="net461"


   ///string EncryptedText = EncryptionUtility.EncryptTextByCertFile("test", @"proxy.pfx", "0");


                ////string EncryptedText = EncryptionUtility.EncryptText("Test", "‎ef5d044856ccb15a92f819864597d1cbe34b727b", @"CurrentUser\Personal\Certificates");

               //// string EncryptedText1234 = EncryptionUtility.EncryptText("Test", "‎ef5d044856ccb15a92f819864597d1cbe34b727b", "CurrentUser");

             ////   string EncryptedText1234 = EncryptionUtility.EncryptText("Test", "‎ef5d044856ccb15a92f819864597d1cbe34b727b", "My");

Thanks,
Naresh Khatri

**Comment by ashishnegi** [comment]
@rishirsinha to help here.

**Comment by ashishnegi** [comment]
@nareshkhatri81 You will need to run this console application on a machine with SF runtime installed.

The last error you have got is : `Unknown cryptographic algorithm`. 

See how its used here : https://github.com/Microsoft/service-fabric/blob/master/src/prod/src/Common/CryptoUtility.cpp#L1444
and you can pass different values like `null` and others mentioned at https://github.com/Microsoft/service-fabric/blob/master/src/prod/src/inc/clr/PAL.h#L2459

**Comment by nareshkhatri81** [comment]
@ashishnegi - we are running workloads inside containers. 
we don't install SF Runtime inside containers.
do we need to have that inside containers to work as it have dependencies on FabricCommon.dll ?
or we can have just put this dll as part of bin folder and it will work.

is there any reason of tight coupling of SF Runtime and Client Libraries ?

Thanks,
naresh Khatri

**Comment by ashishnegi** [comment]
@nareshkhatri81 Please follow this [document](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-services-inside-containers) to get access to SF runtime outside of container.

Are you using .Net Framework or dotnet coreclr ? The above document is for .Net Framework. 
Let me know if you know details for dotnet coreclr apps.

**Comment by nareshkhatri81** [comment]
@ashishnegi 
yes we are aware of this capability of SF. 

is there any time frame when both will be decoupled ?

**Comment by ashishnegi** [comment]
@masnider for above question.
@nareshkhatri81 Let us know if you are able to successfully use these apis or run into any errors.

**Comment by ashishnegi** [comment]
Closing this as currently we only support accessing runtime from inside container.
