### ISSUE TITLE
SetupEntryPoint causes main not be invoked

### ISSUE THREAD

**Issue by chenfeiw** [Azure/service-fabric-issues#996]
Our service has a SetupEntryPoint which run a setup.bat to setup the environment.  The bat file will cost some time to setup the environment since it need to install something. 
I got an error when I run the service - "The ServiceType was not registered within the configured timeout". I debug the code, and find out that the main is never be invoked. As my understanding, ServiceType is registered in the main. 
If I change the setup.bat to do nothing, then the service can startup successfully. 
Seems SetupEntryPoint  and EntryPoint share the same execution time, when SetupEntryPoint  cost long time, timeout happen, EntryPoint won't get a chance to be invoked. 
I don't think this the expected behavior, because sometimes you really need to setup a lot of stuff during when startup which cannot be finished in very short time.

**Comment by RajeetN** [comment]
This is the expected behavior. You can set the ServiceTypeRegistrationTimeout in Hosting section of FabricSettings to increase the registration timeout. Having said that, the registration timeout should be large enough already, unless you are running a onebox dev setup
