### ISSUE TITLE
Service Fabric Type Initialization Exception

### ISSUE THREAD

**Issue by cjmakwana** [Azure/service-fabric-issues#997]
Hello,

After upgrading the following Nuget packages of the service fabric framework assemblies, I started getting the exception as highlighted below (please note that the solution is based on .NET framework 4.6.1 for all the service fabric services):

Service Fabric Current Version: 6.1.480.9494
Service Fabric SDK Version: 3.0.480.9494

Upgraded Nuget packages:

Microsoft.ServiceFabric (from 6.1.480 to 6.2.262)
Microsoft.ServiceFabric.Data (from 3.0.480 to 3.1.262)
Microsoft.ServiceFabric.Services (from 3.0.480 to 3.1.262)
Microsoft.ServiceFabric.Services.Remoting (from 3.0.480 to 3.1.262)
Microsoft.ServiceFabric.FabricTransport.Internal (from 3.0.480 to 3.1.262)
Microsoft.ServiceFabric.Diagnostics.Internal (from 3.0.480 to 3.1.262)
Microsoft.ServiceFabric.Actors (from 3.0.480 to 3.1.262)

Exception started to get (please note that before the above upgrade, all the services were working as expected):

{
    "Message": "An error has occurred.",
    "ExceptionMessage": "The type initializer for 'System.Fabric.Common.AppTrace' threw an exception.",
    "ExceptionType": "System.TypeInitializationException",
    "StackTrace": "   at System.Fabric.Common.AppTrace.get_TraceSource()\r\n   at Microsoft.ServiceFabric.FabricTransport.FabricTransportSettings.TryLoadFrom(String sectionName, FabricTransportSettings& settings, String filepath, String configPackageName)\r\n   at Microsoft.ServiceFabric.FabricTransport.FabricTransportSettings.GetDefault(String sectionName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings.GetDefault(String sectionName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportServiceRemotingProviderAttribute.CreateServiceRemotingClientFactory(IServiceRemotingCallbackClient callbackClient)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.CreateServiceRemotingClientFactory(Type serviceInterfaceType)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.GetOrCreateServiceRemotingClientFactory(Type serviceInterfaceType)\r\n   at Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)\r\n   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)\r\n   at ..............cs:line 115\r\n   at ............Controller.<Create>d__2.MoveNext() in ...............Controller.cs:line 27\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()",
    "InnerException": {
        "Message": "An error has occurred.",
        "ExceptionMessage": "The type initializer for 'ExtensionsEvents' threw an exception.",
        "ExceptionType": "System.TypeInitializationException",
        "StackTrace": "   at System.Fabric.Common.Tracing.FabricEvents.ExtensionsEvents..ctor(EventTask code)\r\n   at System.Fabric.Common.AppTrace..cctor()",
        "InnerException": {
            "Message": "An error has occurred.",
            "ExceptionMessage": "Could not load type 'System.Fabric.Common.Tracing.TableEntityKind' from assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.",
            "ExceptionType": "System.TypeLoadException",
            "StackTrace": "   at System.Fabric.Common.Tracing.FabricEventSource.GenerateEventDescriptors(IVariantEventWriter variantEventWriter)\r\n   at System.Fabric.Common.Tracing.FabricEvents..ctor()\r\n   at System.Fabric.Common.Tracing.FabricEvents.<>c.<.cctor>b__22_0()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Fabric.Common.Tracing.FabricEvents.ExtensionsEvents..cctor()"
        }
    }
}

I am not sure whether I need to adjust my code with the upgraded assembly. Please advise me on this.

Regards,

Chandresh.

**Comment by cjmakwana** [comment]
Hi, please see the snap below:

![image](https://user-images.githubusercontent.com/23075550/39093104-8d115fa4-4637-11e8-838c-297d287a80ba.png)

In all the stateful service, I am facing the issue at this override. This was not the case before Nuget packages upgrade.

**Comment by abramjablonski** [comment]
@cjmakwana : I'm guessing those services are running on you local development cluster - if so, upgrade your dev box to the Service Fabric 6.2 SDK, it'll fix the issue (for me, it also required a reset of my local cluster)

**Comment by ashishnegi** [comment]
Please check your SF cluster runtime version is equal or higher than SF SDK version you are using in your apps.

**Comment by negberts** [comment]
When will 6.2 be available in Azure? We cannot deploy the latest version now...

**Comment by cjmakwana** [comment]
Hi @ashishnegi, @negberts @abramjablonski 

Kind thanks for your quick support. After upgrading to 6.2, I was able to run all the services as expected. Hence, closing this issue.

**Comment by ThiemeNL** [comment]
Hi, we have the same issue, when will the 6.2 be available in Azure?
