### ISSUE TITLE
Firewall rules explosion

### ISSUE THREAD

**Issue by makar-sasha** [Azure/service-fabric-issues#998]
Hello. 
We have created cluster about 1 month ago (ver 6.1.472.9494).
Today 2 of 5 nodes are down (have started to occupy about 100% of cpu because of "Service Host: Local Service" and FabricHost processes). In the past I saw similar issue related to the number of firewall rules. So I have checked and problem nodes have about 85 000 of rules (other nodes have about 8 000).  I have started "Remove-NetFirewallRule -Description "*WindowsFabric*"" but it will take a lot of hrs.
Is this issue fixed or must be reopened? 
Thanks,
Alex.

**Comment by tugup** [comment]
Fixed in release 6.4 and onwards
